ORIGEN API: Core/dc/tests/tstLibraryHeader.cpp File Reference
tstLibraryHeader.cpp File Reference
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/dc/LibraryHeader.h"
#include "Standard/Interface/SerialStream.h"
Functions
TEST (LibraryHeader, Serialization)
Function Documentation
TEST (LibraryHeader , Serialization)
References FakeFactory::createLibraryHeader_random1(), LibraryHeader::deserialize(), and LibraryHeader::serialize().
 {
     // get a fake
     LibraryHeader obj1 = FakeFactory::createLibraryHeader_random1();
     // serialize
     SerialStream ss;
     int return_code = obj1.serialize( &ss );
     EXPECT_EQ( 0, return_code );
     // deserialize
     LibraryHeader obj2;
     return_code = obj2.deserialize( &ss );
     EXPECT_EQ( 0, return_code );
     // compare
     EXPECT_EQ( obj1, obj2 );
 }