ORIGEN API: State Class Reference
State Class Reference
#include <State.h>
Container for state data.
Public Types
typedef std::shared_ptr< State > SP
typedef std::shared_ptr< const State > SCP
Public Member Functions
State ()
bool operator== (const State &a) const
const StateInfo & definition () const
return a const reference to definition
SCP_StateInfo scp_definition () const
return a shared (read-only) definition pointer
bool has_definition () const
return whether the class has a non-null definition
void get_definition (StateInfo &) const
populate an existing StateInfo with a copy of definition
void set_definition (const StateInfo &)
set the definition (copy operation)
void getptr_definition (const StateInfo *&) const
retrieve pointer (read-only) to definition
void manageptr_definition (StateInfo *&)
set the definition (ownership transfer)
const Concentrations & concs () const
return a const reference to concs
SCP_Concentrations scp_concs () const
return a shared (read-only) concs pointer
bool has_concs () const
return whether the class has a non-null concs
void get_concs (Concentrations &) const
populate an existing Concentrations with a copy of concs
void set_concs (const Concentrations &)
set the concs (copy operation)
void getptr_concs (const Concentrations *&) const
retrieve pointer (read-only) to concs
void manageptr_concs (Concentrations *&)
set the concs (ownership transfer)
const AlphaSpectra & alpha_spectra () const
return a const reference to alpha_spectra
SCP_AlphaSpectra scp_alpha_spectra () const
return a shared (read-only) alpha_spectra pointer
bool has_alpha_spectra () const
return whether the class has a non-null alpha_spectra
void get_alpha_spectra (AlphaSpectra &) const
populate an existing AlphaSpectra with a copy of alpha_spectra
void set_alpha_spectra (const AlphaSpectra &)
set the alpha_spectra (copy operation)
void getptr_alpha_spectra (const AlphaSpectra *&) const
retrieve pointer (read-only) to alpha_spectra
void manageptr_alpha_spectra (AlphaSpectra *&)
set the alpha_spectra (ownership transfer)
const NeutronSpectra & neutron_spectra () const
return a const reference to neutron_spectra
SCP_NeutronSpectra scp_neutron_spectra () const
return a shared (read-only) neutron_spectra pointer
bool has_neutron_spectra () const
return whether the class has a non-null neutron_spectra
void get_neutron_spectra (NeutronSpectra &) const
populate an existing NeutronSpectra with a copy of neutron_spectra
void set_neutron_spectra (const NeutronSpectra &)
set the neutron_spectra (copy operation)
void getptr_neutron_spectra (const NeutronSpectra *&) const
retrieve pointer (read-only) to neutron_spectra
void manageptr_neutron_spectra (NeutronSpectra *&)
set the neutron_spectra (ownership transfer)
const GammaSpectra & gamma_spectra () const
return a const reference to gamma_spectra
SCP_GammaSpectra scp_gamma_spectra () const
return a shared (read-only) gamma_spectra pointer
bool has_gamma_spectra () const
return whether the class has a non-null gamma_spectra
void get_gamma_spectra (GammaSpectra &) const
populate an existing GammaSpectra with a copy of gamma_spectra
void set_gamma_spectra (const GammaSpectra &)
set the gamma_spectra (copy operation)
void getptr_gamma_spectra (const GammaSpectra *&) const
retrieve pointer (read-only) to gamma_spectra
void manageptr_gamma_spectra (GammaSpectra *&)
set the gamma_spectra (ownership transfer)
const BetaSpectra & beta_spectra () const
return a const reference to beta_spectra
SCP_BetaSpectra scp_beta_spectra () const
return a shared (read-only) beta_spectra pointer
bool has_beta_spectra () const
return whether the class has a non-null beta_spectra
void get_beta_spectra (BetaSpectra &) const
populate an existing BetaSpectra with a copy of beta_spectra
void set_beta_spectra (const BetaSpectra &)
set the beta_spectra (copy operation)
void getptr_beta_spectra (const BetaSpectra *&) const
retrieve pointer (read-only) to beta_spectra
void manageptr_beta_spectra (BetaSpectra *&)
set the beta_spectra (ownership transfer)
size_t total_nuclides () const
size_t num_neutron_groups () const
size_t num_alpha_groups () const
size_t num_gamma_groups () const
size_t num_beta_groups () const
void accumulate (const State &, double wt=1.0)
Scale::Json::Value to_json () const
std::string to_string () const
Static Public Member Functions
static bool match (const State &a, const State &b)
Protected Member Functions
void canonicalize_definition ()
void canonicalize_concs ()
void canonicalize_neutron_spectra ()
void canonicalize_gamma_spectra ()
void canonicalize_alpha_spectra ()
void canonicalize_beta_spectra ()
Protected Attributes
SP_StateInfo b_definition
SP_Concentrations b_concs
SP_NeutronSpectra b_neutron_spectra
SP_GammaSpectra b_gamma_spectra
SP_AlphaSpectra b_alpha_spectra
SP_BetaSpectra b_beta_spectra
Friends
class StateSet
class GridView_State
Detailed Description
Container for state data.
The State is a data set which contains:
StateInfo (definition info)
Concentrations (nuclide conentration data)
Spectra (Alpha, Beta, Neutron, Gamma)
The StateInfo is required but all other components are optional. The StateSet (list of states) is the in-memory version of the SCALE/ORIGEN concs file, sometimes called the ft71 file as in legacy SCALE it was always output as ft71f*.
Examples:
tstGridView.cpp, tstState.cpp, and tstStateSet.cpp.
Member Typedef Documentation
typedef std::shared_ptr<State> SP
typedef std::shared_ptr<const State> SCP
Constructor & Destructor Documentation
State ()
     : b_definition( new StateInfo() )
     , b_concs( new Concentrations() )
     , b_neutron_spectra( new NeutronSpectra() )
     , b_gamma_spectra( new GammaSpectra() )
     , b_alpha_spectra( new AlphaSpectra() )
     , b_beta_spectra( new BetaSpectra() )
 {
 }
Member Function Documentation
bool operator== (const State & a) const
References State::alpha_spectra(), State::b_alpha_spectra, State::b_beta_spectra, State::b_concs, State::b_definition, State::b_gamma_spectra, State::b_neutron_spectra, State::beta_spectra(), State::concs(), State::definition(), State::gamma_spectra(), and State::neutron_spectra().
 {
     ORIGEN_COMPARE_SP( definition, b_definition, a.b_definition );
     ORIGEN_COMPARE_SP( concs, b_concs, a.b_concs );
     ORIGEN_COMPARE_SP( alpha_spectra, b_alpha_spectra, a.b_alpha_spectra );
     ORIGEN_COMPARE_SP( beta_spectra, b_beta_spectra, a.b_beta_spectra );
     ORIGEN_COMPARE_SP( gamma_spectra, b_gamma_spectra, a.b_gamma_spectra );
     ORIGEN_COMPARE_SP(
         neutron_spectra, b_neutron_spectra, a.b_neutron_spectra );
     return true;
 }
bool match (const State & a, const State & b) static
References State::concs(), State::definition(), StateInfo::match(), and Concentrations::match().
Referenced by GridView_State::match().
 {
     return Concentrations::match( a.concs(), b.concs() ) &&
            StateInfo::match( a.definition(), b.definition() );
 }
const StateInfo & definition () const
return a const reference to definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of State goes out of scope.
Examples:
tstGridView.cpp, tstState.cpp, and tstStateSet.cpp.
Referenced by State::accumulate(), StateSet::alpha_spectra(), StateSet::beta_spectra(), StateSet::check_headers(), StateSet::concs(), StateSet::energies(), StateSet::fluxes(), StateSet::gamma_spectra(), State::match(), StateSet::neutron_spectra(), State::operator==(), StateSet::powers(), TEST(), StateSet::times(), StateSetIO_bof::write(), and StateSetIO_s62b::write().
SCP_StateInfo scp_definition () const
return a shared (read-only) definition pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstGridView.cpp.
Referenced by TEST().
bool has_definition () const
return whether the class has a non-null definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by State::accumulate(), Origen::createContentString(), StateSetIO_bof::write(), and StateSetIO_s62b::write().
void get_definition (StateInfo & definition) const
populate an existing StateInfo with a copy of definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_definition (const StateInfo & definition)
set the definition (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstGridView.cpp, and tstState.cpp.
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_bof::read(), StateSetIO_s61::read(), Origen::saveStateSet(), FakeFactory::StateSet_random1(), and TEST().
void getptr_definition (const StateInfo *&) const
retrieve pointer (read-only) to definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_definition (StateInfo *& definition)
set the definition (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const Concentrations & concs () const
return a const reference to concs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of State goes out of scope.
Examples:
tstState.cpp, and tstStateSet.cpp.
Referenced by State::accumulate(), Obiwan_diff::diff(), State::match(), State::operator==(), TEST(), timing_ref(), timing_ref_at(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_Concentrations scp_concs () const
return a shared (read-only) concs pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by StateSet::concs().
bool has_concs () const
return whether the class has a non-null concs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by State::accumulate(), State::total_nuclides(), and StateSetIO_bof::write().
void get_concs (Concentrations & concs) const
populate an existing Concentrations with a copy of concs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_concs (const Concentrations & concs)
set the concs (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstState.cpp, and tstStateSet.cpp.
Referenced by State::accumulate(), FakeFactory::newspStateSet_10nuclide(), StateSetIO_s61::read(), StateSetIO_s62b::read(), StateSetIO_bof::read(), Origen::saveStateSet(), FakeFactory::StateSet_random1(), and TEST().
void getptr_concs (const Concentrations *&) const
retrieve pointer (read-only) to concs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_concs (Concentrations *& concs)
set the concs (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const AlphaSpectra & alpha_spectra () const
return a const reference to alpha_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of State goes out of scope.
Referenced by State::operator==(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_AlphaSpectra scp_alpha_spectra () const
return a shared (read-only) alpha_spectra pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by StateSet::alpha_spectra().
bool has_alpha_spectra () const
return whether the class has a non-null alpha_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by State::num_alpha_groups(), and StateSetIO_bof::write().
void get_alpha_spectra (AlphaSpectra & alpha_spectra) const
populate an existing AlphaSpectra with a copy of alpha_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_alpha_spectra (const AlphaSpectra & alpha_spectra)
set the alpha_spectra (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and FakeFactory::StateSet_random1().
void getptr_alpha_spectra (const AlphaSpectra *&) const
retrieve pointer (read-only) to alpha_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_alpha_spectra (AlphaSpectra *& alpha_spectra)
set the alpha_spectra (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const NeutronSpectra & neutron_spectra () const
return a const reference to neutron_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of State goes out of scope.
Referenced by State::operator==(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_NeutronSpectra scp_neutron_spectra () const
return a shared (read-only) neutron_spectra pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by StateSet::neutron_spectra().
bool has_neutron_spectra () const
return whether the class has a non-null neutron_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by State::num_neutron_groups(), and StateSetIO_bof::write().
void get_neutron_spectra (NeutronSpectra & neutron_spectra) const
populate an existing NeutronSpectra with a copy of neutron_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_neutron_spectra (const NeutronSpectra & neutron_spectra)
set the neutron_spectra (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and FakeFactory::StateSet_random1().
void getptr_neutron_spectra (const NeutronSpectra *&) const
retrieve pointer (read-only) to neutron_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_neutron_spectra (NeutronSpectra *& neutron_spectra)
set the neutron_spectra (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const GammaSpectra & gamma_spectra () const
return a const reference to gamma_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of State goes out of scope.
Referenced by State::operator==(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_GammaSpectra scp_gamma_spectra () const
return a shared (read-only) gamma_spectra pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by StateSet::gamma_spectra().
bool has_gamma_spectra () const
return whether the class has a non-null gamma_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by State::num_gamma_groups(), and StateSetIO_bof::write().
void get_gamma_spectra (GammaSpectra & gamma_spectra) const
populate an existing GammaSpectra with a copy of gamma_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_gamma_spectra (const GammaSpectra & gamma_spectra)
set the gamma_spectra (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), StateSetIO_bof::read(), and FakeFactory::StateSet_random1().
void getptr_gamma_spectra (const GammaSpectra *&) const
retrieve pointer (read-only) to gamma_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_gamma_spectra (GammaSpectra *& gamma_spectra)
set the gamma_spectra (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const BetaSpectra & beta_spectra () const
return a const reference to beta_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of State goes out of scope.
Referenced by State::operator==(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_BetaSpectra scp_beta_spectra () const
return a shared (read-only) beta_spectra pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by StateSet::beta_spectra().
bool has_beta_spectra () const
return whether the class has a non-null beta_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by State::num_beta_groups(), and StateSetIO_bof::write().
void get_beta_spectra (BetaSpectra & beta_spectra) const
populate an existing BetaSpectra with a copy of beta_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_beta_spectra (const BetaSpectra & beta_spectra)
set the beta_spectra (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and FakeFactory::StateSet_random1().
void getptr_beta_spectra (const BetaSpectra *&) const
retrieve pointer (read-only) to beta_spectra
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_beta_spectra (BetaSpectra *& beta_spectra)
set the beta_spectra (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
size_t total_nuclides () const
References State::b_concs, and State::has_concs().
Referenced by Origen::createContentString(), StateSetIO_s62b::read(), and StateSetIO_bof::read().
 {
     return !has_concs() ? 0 : b_concs->total_nuclides();
 }
size_t num_neutron_groups () const
References State::b_neutron_spectra, and State::has_neutron_spectra().
Referenced by StateSet::check_headers(), Origen::createContentString(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and StateSetIO_s62b::write().
 {
     return !has_neutron_spectra() ? 0 : b_neutron_spectra->intensity_size();
 }
size_t num_alpha_groups () const
References State::b_alpha_spectra, and State::has_alpha_spectra().
Referenced by StateSet::check_headers(), Origen::createContentString(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and StateSetIO_s62b::write().
 {
     return !has_alpha_spectra() ? 0 : b_alpha_spectra->intensity_size();
 }
size_t num_gamma_groups () const
References State::b_gamma_spectra, and State::has_gamma_spectra().
Referenced by StateSet::check_headers(), Origen::createContentString(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and StateSetIO_s62b::write().
 {
     return !has_gamma_spectra() ? 0 : b_gamma_spectra->intensity_size();
 }
size_t num_beta_groups () const
References State::b_beta_spectra, and State::has_beta_spectra().
Referenced by StateSet::check_headers(), Origen::createContentString(), StateSetIO_s62b::read(), StateSetIO_bof::read(), and StateSetIO_s62b::write().
 {
     return !has_beta_spectra() ? 0 : b_beta_spectra->intensity_size();
 }
void accumulate (const State & state, double wt = 1.0)
References State::b_concs, State::b_definition, State::concs(), State::definition(), State::has_concs(), State::has_definition(), and State::set_concs().
 {
     // check definition
     Insist( state.has_definition(),
             "definition to accumulate must be non-nullptr" );
     // accumulate definition
     if( has_definition() && !b_definition->match( state.definition() ) )
     {
         jDebugLine( "state headers must match to accumulate--null op" );
         return;
     }
     // accumulate concentrations
     double old_volume = 0.0;
     if( has_concs() && b_concs->total_nuclides() > 0 )
     {
         jDebugLine( "accumulating concs with wt=" << wt );
         old_volume = b_concs->volume();
         b_concs->accumulate_concs( state.concs(), wt );
     }
     else
     {
         jDebugLine( "setting concs" );
         set_concs( state.concs() );
         b_concs->scale( wt );
     }
     // accumulate definition
     double new_volume = b_concs->volume();  // volume implicitly includes wt
     b_definition->accumulate_definition(
         state.definition(),
         new_volume - old_volume,  // this state's volume
         old_volume );             // previous total volume
     jDebugLine( "dones" );
 }
Json::Value to_json () const
References State::b_concs.
Referenced by State::to_string().
 {
     Json::Value root;
     root["concs"] = b_concs->to_json();
     // root["definition"]=b_definition->to_json();
     return root;
 }
std::string to_string () const
References State::to_json().
 { return to_json().toStyledString(); }
void canonicalize_definition () protected
 {
     // null op
 }
void canonicalize_concs () protected
 {
     // null op
 }
void canonicalize_neutron_spectra () protected
 {
     // null op
 }
void canonicalize_gamma_spectra () protected
 {
     // null op
 }
void canonicalize_alpha_spectra () protected
 {
     // null op
 }
void canonicalize_beta_spectra () protected
 {
     // null op
 }
Friends And Related Function Documentation
friend class StateSet friend
friend class GridView_State friend
Member Data Documentation
SP_StateInfo b_definition protected
Referenced by State::accumulate(), and State::operator==().
SP_Concentrations b_concs protected
Referenced by State::accumulate(), State::operator==(), State::to_json(), and State::total_nuclides().
SP_NeutronSpectra b_neutron_spectra protected
Referenced by State::num_neutron_groups(), and State::operator==().
SP_GammaSpectra b_gamma_spectra protected
Referenced by State::num_gamma_groups(), and State::operator==().
SP_AlphaSpectra b_alpha_spectra protected
Referenced by State::num_alpha_groups(), and State::operator==().
SP_BetaSpectra b_beta_spectra protected
Referenced by State::num_beta_groups(), and State::operator==().
The documentation for this class was generated from the following files:
Core/dc/State.h
Core/dc/State.cpp