ORIGEN API: NuclideResource Class Reference
NuclideResource Class Reference
#include <NuclideResource.h>
Classes
struct Properties
Public Types
typedef std::shared_ptr< NuclideResource > SP
typedef std::shared_ptr< const NuclideResource > SCP
Public Member Functions
NuclideResource (bool load_default=false)
bool is_present (const int izzzaaa) const
std::string to_string () const
Scale::Json::Value to_json () const
double mass (int) const
double abundance_num (int) const
double abundance_wt (int) const
Static Public Member Functions
static SCP default_resource ()
static void clear_default_resource ()
Public Attributes
std::map< int, Properties > parent_map
Static Protected Attributes
static SCP b_default_resource = nullptr
Detailed Description
Examples:
tstNuclideResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<NuclideResource> SP
typedef std::shared_ptr<const NuclideResource> SCP
Constructor & Destructor Documentation
NuclideResource (bool load_default = false) explicit
References Origen::defaultNuclideResource().
Member Function Documentation
bool is_present (const int izzzaaa) const
Examples:
tstNuclideResource.cpp.
Referenced by TEST().
std::string to_string () const
Json::Value to_json () const
References NuclideResource::Properties::abundance_num, NuclideResource::Properties::abundance_wt, and NuclideResource::Properties::mass.
double mass (int izzzaaa) const
Referenced by Origen::populateLibraryMass_NuclideResource().
double abundance_num (int izzzaaa) const
Referenced by Origen::populateLibraryAbundance_NuclideResource().
double abundance_wt (int izzzaaa) const
NuclideResource::SCP default_resource () static
Examples:
tstNuclideResource.cpp.
Referenced by Origen::populateLibraryAbundance(), Origen::populateLibraryMass(), and TEST().
void clear_default_resource () static
Examples:
tstNuclideResource.cpp.
Referenced by TEST().
Member Data Documentation
std::map<int, Properties> parent_map
Examples:
tstNuclideResource.cpp.
Referenced by Origen::populateNuclideResource_StdComp(), and TEST().
NuclideResource::SCP b_default_resource = nullptr static protected
The documentation for this class was generated from the following files:
Core/re/NuclideResource.h
Core/re/NuclideResource.cpp