ORIGEN API: Origen::test Namespace Reference
Origen::test Namespace Reference
Classes
class STab1Writer
class YieldResourceIO_F
Functions
TEST (Material, Setup)
TEST (Material, Accessors)
TEST (MaterialMap, Accessors)
SP_Material newspMaterial_local ()
TEST (Material, Flush)
TEST (Material, PowerBurnup)
TEST (Material, NuclideRemoval)
TEST (Ampx, FloatWriting)
TEST_F (YieldResourceIO_F, Basic)
TEST_F (YieldResourceIO_F, WrongTextFormat)
TEST_F (YieldResourceIO_F, AmpxLoadingAndErrorCatching)
TEST (YieldResourceIO, IntenseRoundTrip)
TEST (YieldResourceJobs, Rebaseline)
TEST (YieldResourceJobs, ExperimentalCumulativeYields)
TEST (TransitionMatrixUpdater, Load)
TEST (TransitionMatrixUpdater, LoadUpdate)
TEST (TransitionMatrixUpdater, LoadUpdateGet)
TEST (TransitionMatrixUpdater, LoadUpdateGetClear)
std::map< int, std::map< int, double > > reference_sb47g_constants ()
std::map< int, std::map< int, double > > reference_ub47g_constants ()
TEST (TransitionMatrixUpdater, StorageBounds47g)
TEST (TransitionMatrixUpdater, UserBounds47g)
TEST (TransitionMatrixUpdater, FetchNuclides)
TEST (TransitionMatrixUpdater, LoadWithUserReactions)
std::string int2str (int i)
TEST (TransitionMatrixUpdater, Example)
Function Documentation
Origen::test::TEST (Material , Setup)
Examples:
tstMaterial.cpp, tstTransitionMatrixUpdater.cpp, and tstYieldResourceIO.cpp.
References FakeFactory::Library_random1().
Origen::test::TEST (Material , Accessors)
References FakeFactory::Library_scale_pwr(), and FakeFactory::vera_uox_e360().
Origen::test::TEST (MaterialMap , Accessors)
References MaterialMap::add(), MaterialMap::cold_volume(), MaterialMap::initial_hm_mass(), MaterialMap::initial_mass(), FakeFactory::Library_scale_pwr(), and FakeFactory::vera_uox_e360().
SP_Material Origen::test::newspMaterial_local ()
Examples:
tstMaterial.cpp.
References FakeFactory::newspLibrary_scale_pwr(), and FakeFactory::vera_uox_e360().
Referenced by TEST().
Origen::test::TEST (Material , Flush)
References kernel_rksuite::f(), and newspMaterial_local().
Origen::test::TEST (Material , PowerBurnup)
References newspMaterial_local().
Origen::test::TEST (Material , NuclideRemoval)
References Removal::create(), newspMaterial_local(), r, and Concentrations::vals_at().
Origen::test::TEST (Ampx , FloatWriting)
References SEXPECT_EQ.
Origen::test::TEST_F (YieldResourceIO_F , Basic)
Examples:
tstYieldResourceIO.cpp.
References YieldParent::data_at(), YieldParent::fp_index(), YieldParent::get_energies(), YieldParent::get_fp_ids(), YieldParent::get_interp_yields(), YieldParent::has_fp(), Origen::printYields(), and YieldData::yield_at().
Origen::test::TEST_F (YieldResourceIO_F , WrongTextFormat)
Origen::test::TEST_F (YieldResourceIO_F , AmpxLoadingAndErrorCatching)
Origen::test::TEST (YieldResourceIO , IntenseRoundTrip)
References Origen::loadYieldResource(), and Origen::saveYieldResource().
Origen::test::TEST (YieldResourceJobs , Rebaseline)
References Origen::INTERP_LINLIN, Origen::loadYieldResource(), Origen::printInterpolatedYields(), Origen::printYieldEnergies(), and Origen::printYields().
Origen::test::TEST (YieldResourceJobs , ExperimentalCumulativeYields)
References Origen::INTERP_LINLIN, Origen::loadYieldResource(), Origen::printInterpolatedYields(), Origen::printYieldEnergies(), and Origen::printYields().
Origen::test::TEST (TransitionMatrixUpdater , Load)
References TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::initialized(), and TransitionMatrixUpdater::load().
Origen::test::TEST (TransitionMatrixUpdater , LoadUpdate)
References TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), and TransitionMatrixUpdater::update_mg_flux().
Origen::test::TEST (TransitionMatrixUpdater , LoadUpdateGet)
References TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), and TransitionMatrixUpdater::update_mg_flux().
Origen::test::TEST (TransitionMatrixUpdater , LoadUpdateGetClear)
References TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), and TransitionMatrixUpdater::update_mg_flux().
std::map<int, std::map<int, double> > Origen::test::reference_sb47g_constants ()
Examples:
tstTransitionMatrixUpdater.cpp.
References r.
Referenced by TEST().
std::map<int, std::map<int, double> > Origen::test::reference_ub47g_constants ()
Examples:
tstTransitionMatrixUpdater.cpp.
References r.
Referenced by TEST().
Origen::test::TEST (TransitionMatrixUpdater , StorageBounds47g)
References TransitionMatrixUpdater::clear(), FakeFactory::energy_bounds_mpact_47g(), TransitionMatrixUpdater::get_transition_matrix(), FakeFactory::getUniformFlux(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), TransitionMatrixUpdater::mg_database(), TransitionSystem::nuclide(), ReactionResource::print(), reference_sb47g_constants(), TransitionMatrixP::toQString(), TransitionMatrixUpdater::transition_system(), and TransitionMatrixUpdater::update_mg_flux().
Origen::test::TEST (TransitionMatrixUpdater , UserBounds47g)
References TransitionMatrixUpdater::clear(), FakeFactory::energy_bounds_mpact_47g(), TransitionMatrixUpdater::get_transition_matrix(), FakeFactory::getUniformFlux(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), TransitionMatrixUpdater::mg_database(), TransitionSystem::nuclide(), ReactionResource::print(), reference_ub47g_constants(), TransitionMatrixUpdater::set_user_bounds(), TransitionMatrixP::toQString(), TransitionMatrixUpdater::transition_system(), and TransitionMatrixUpdater::update_mg_flux().
Origen::test::TEST (TransitionMatrixUpdater , FetchNuclides)
References TransitionMatrixUpdater::base_transition_matrix(), TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::fetch_ts_nuclides(), TransitionMatrixUpdater::initialized(), and TransitionMatrixUpdater::load().
Origen::test::TEST (TransitionMatrixUpdater , LoadWithUserReactions)
References TransitionMatrixUpdater::clear(), TransitionMatrixP::find_nuclide(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_itot(), TransitionMatrixP::get_kd_(), TransitionMatrixP::get_loc(), TransitionMatrixP::get_non(), TransitionMatrixP::get_non0_(), TransitionMatrixP::get_nucl(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::get_xs(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), TransitionMatrixUpdater::update_mg_flux(), and TransitionMatrixUpdater::update_user_xs().
std::string Origen::test::int2str (int i)
Examples:
tstTransitionMatrixUpdater.cpp.
Origen::test::TEST (TransitionMatrixUpdater , Example)
References TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), TransitionSystemAdapter_AmpxN::print(), TransitionSystemAdapter_AmpxN::set_reaction_resource(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().