ORIGEN API: Channel Class Reference
Channel Class Reference abstract
#include <Channel.h>
Defines the channel interface for the TransitionSystem.
Public Types
typedef SP_Channel SP
strong pointer
typedef WP_Channel WP
weak pointer
typedef CWP_Channel CWP
const weak pointer
INTERFACE<<Origen::Channel>>
See Origen::Channel for details.
int num_transitions () const
SP_Transition transition (int transition_id) const
void get_transition (int transition_id, SP_Transition &transition) const
void set_transition (SP_Transition transition)
SP_Transition add_transition (int transition_id)
SP_Transition add_transition (int transition_id, double yield)
std::vector< SP_Transition > transitions () const
void get_transitions (std::vector< SP_Transition > &transitions) const
void set_transitions (std::vector< SP_Transition > transitions)
std::vector< SP_Transition > byproduct_transitions () const
void get_byproduct_transitions (std::vector< SP_Transition > &transitions) const
void update_byproduct_transitions ()
SP_ChannelType channel_type () const
void get_channel_type (SP_ChannelType &channel_type) const
void set_channel_type (SP_ChannelType channel_type)
bool has_initialized_channel_type () const
double decay_constant () const
Channel & set_decay_constant (double decay_constant)
bool has_initialized_decay_constant () const
double xs () const
Channel & set_xs (double xs)
bool has_initialized_xs () const
CWP_Nuclide parent () const
void get_parent (WP_Nuclide &parent) const
void set_parent (WP_Nuclide parent)
bool has_initialized_parent () const
int daughter_mass_number () const
int daughter_charge_number () const
double coeff () const
double rate () const
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
Private Member Functions
virtual int num_transitions_impl () const =0
virtual int daughter_mass_number_impl () const
virtual int daughter_charge_number_impl () const
virtual SP_Transition transition_impl (int transition_id) const =0
virtual void get_transition_impl (int transition_id, SP_Transition &transition) const =0
virtual void set_transition_impl (SP_Transition transition)=0
virtual CWP_Nuclide parent_impl () const =0
virtual void get_parent_impl (WP_Nuclide &parent) const =0
virtual void set_parent_impl (WP_Nuclide parent)=0
virtual bool has_initialized_parent_impl () const
virtual double coeff_impl () const =0
virtual double rate_impl () const =0
virtual SP_ChannelType channel_type_impl () const =0
virtual void get_channel_type_impl (SP_ChannelType &channel_type) const =0
virtual void set_channel_type_impl (SP_ChannelType channel_type)=0
virtual bool has_initialized_channel_type_impl () const
virtual double decay_constant_impl () const =0
virtual void set_decay_constant_impl (double decay_constant)=0
virtual bool has_initialized_decay_constant_impl () const
virtual double xs_impl () const =0
virtual void set_xs_impl (double xs)=0
virtual bool has_initialized_xs_impl () const
virtual std::vector< SP_Transition > transitions_impl () const =0
virtual void get_transitions_impl (std::vector< SP_Transition > &transitions) const =0
virtual void set_transitions_impl (std::vector< SP_Transition > transitions)=0
virtual SP_Transition add_transition_impl (int transition_id)=0
virtual SP_Transition add_transition_impl (int transition_id, double yield)=0
virtual std::string name_impl () const
virtual int id_impl () const
virtual bool is_initialized_impl () const
useful to chain
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual Scale::Json::Value to_json_impl () const
useful to chain
virtual std::vector< SP_Transition > byproduct_transitions_impl () const =0
virtual void get_byproduct_transitions_impl (std::vector< SP_Transition > &transitions) const =0
virtual void update_byproduct_transitions_impl ()=0
Detailed Description
Defines the channel interface for the TransitionSystem.
The channel, in the context of the transition system, manages five main pieces of data:
identification
channel type
transitions
The channel also has
a strong pointer to a list of Transitions
a weak pointer to a Nuclide
See also
Nuclide, Transition, Species, TransitionSystem
Member Typedef Documentation
typedef SP_Channel SP
strong pointer
typedef WP_Channel WP
weak pointer
typedef CWP_Channel CWP
const weak pointer
Member Function Documentation
int num_transitions () const
 { return num_transitions_impl(); }
SP_Transition transition (int transition_id) const
Referenced by Channel_Gen::add_transition_impl(), LibraryBuilder::create_reaction_transitions(), Channel_Gen::get_transition_impl(), Channel_Gen::set_transition_impl(), and Channel_Gen::update_byproduct_transitions_impl().
 {
     return transition_impl( transition_id );
 }
void get_transition (int transition_id, SP_Transition & transition) const
 {
     get_transition_impl( transition_id, transition );
 }
void set_transition (SP_Transition transition)
 {
     set_transition_impl( transition );
 }
Transition::SP add_transition (int transition_id)
Referenced by Channel_Gen::add_transition_impl().
 {
     return add_transition_impl( transition_id );
 }
Transition::SP add_transition (int transition_id, double yield)
 {
     return add_transition_impl( transition_id, yield );
 }
std::vector< SP_Transition > transitions () const
 {
     return transitions_impl();
 }
void get_transitions (std::vector< SP_Transition > & transitions) const
 {
     get_transitions_impl( transitions );
 }
void set_transitions (std::vector< SP_Transition > transitions)
 {
     set_transitions_impl( transitions );
 }
std::vector< SP_Transition > byproduct_transitions () const
 {
     return byproduct_transitions_impl();
 }
void get_byproduct_transitions (std::vector< SP_Transition > & transitions) const
 {
     get_byproduct_transitions_impl( transitions );
 }
void update_byproduct_transitions ()
Referenced by Channel_Gen::set_channel_type_impl(), and Channel_Gen::set_parent_impl().
 {
     update_byproduct_transitions_impl();
 }
SP_ChannelType channel_type () const
Referenced by Channel_Gen::add_transition_impl(), Channel_Gen::coeff_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Channel_Gen::set_channel_type_impl(), and Channel_Gen::update_byproduct_transitions_impl().
 { return channel_type_impl(); }
void get_channel_type (SP_ChannelType & channel_type) const
 {
     get_channel_type_impl( channel_type );
 }
void set_channel_type (SP_ChannelType channel_type)
Referenced by Channel_Gen::Channel_Gen().
 {
     set_channel_type_impl( channel_type );
 }
bool has_initialized_channel_type () const
Referenced by Channel_Gen::coeff_impl(), and Channel_Gen::update_byproduct_transitions_impl().
 {
     return has_initialized_channel_type_impl();
 }
double decay_constant () const
Referenced by Channel_Gen::coeff_impl(), and Channel_Gen::set_decay_constant_impl().
 { return decay_constant_impl(); }
Channel & set_decay_constant (double decay_constant)
 {
     set_decay_constant_impl( decay_constant );
     return *this;
 }
bool has_initialized_decay_constant () const
 {
     return has_initialized_decay_constant_impl();
 }
double xs () const
Referenced by Channel_Gen::coeff_impl(), and Channel_Gen::set_xs_impl().
 { return xs_impl(); }
Channel & set_xs (double xs)
 {
     set_xs_impl( xs );
     return *this;
 }
bool has_initialized_xs () const
 { return has_initialized_xs_impl(); }
CWP_Nuclide parent () const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Channel_Gen::add_transition_impl(), Nuclide_Gen::append_gain_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), Channel_Gen::rate_impl(), Channel_Gen::set_parent_impl(), TEST_F(), and Channel_Gen::update_byproduct_transitions_impl().
 { return parent_impl(); }
void get_parent (WP_Nuclide & parent) const
Referenced by Channel_Gen::add_transition_impl().
 {
     get_parent_impl( parent );
 }
void set_parent (WP_Nuclide parent)
 { set_parent_impl( parent ); }
bool has_initialized_parent () const
Referenced by Channel_Gen::add_transition_impl(), Channel_Gen::rate_impl(), and Channel_Gen::update_byproduct_transitions_impl().
 {
     return has_initialized_parent_impl();
 }
int daughter_mass_number () const
Referenced by Channel_Gen::add_transition_impl().
 {
     return daughter_mass_number_impl();
 }
int daughter_charge_number () const
Referenced by Channel_Gen::add_transition_impl().
 {
     return daughter_charge_number_impl();
 }
double coeff () const
Referenced by Channel_Gen::rate_impl().
 { return coeff_impl(); }
double rate () const
 { return rate_impl(); }
virtual int num_transitions_impl () const private pure virtual
Implemented in Channel_Gen.
int daughter_mass_number_impl () const private virtual
References Origen::BAD_INT.
 {
     if( has_initialized_channel_type() && has_initialized_parent() &&
         parent()->has_initialized_species() )
     {
         return parent()->species()->mass_number() +
                channel_type()->delta_mass_number();
     }
     return BAD_INT;
 }
int daughter_charge_number_impl () const private virtual
References Origen::BAD_INT.
 {
     if( has_initialized_channel_type() && has_initialized_parent() &&
         parent()->has_initialized_species() )
     {
         return parent()->species()->charge_number() +
                channel_type()->delta_charge_number();
     }
     return BAD_INT;
 }
virtual SP_Transition transition_impl (int transition_id) const private pure virtual
Implemented in Channel_Gen.
virtual void get_transition_impl (int transition_id, SP_Transition & transition) const private pure virtual
Implemented in Channel_Gen.
virtual void set_transition_impl (SP_Transition transition) private pure virtual
Implemented in Channel_Gen.
virtual CWP_Nuclide parent_impl () const private pure virtual
Implemented in Channel_Gen.
virtual void get_parent_impl (WP_Nuclide & parent) const private pure virtual
Implemented in Channel_Gen.
virtual void set_parent_impl (WP_Nuclide parent) private pure virtual
Implemented in Channel_Gen.
bool has_initialized_parent_impl () const private virtual
 {
     return parent() != nullptr && parent()->is_initialized();
 }
virtual double coeff_impl () const private pure virtual
Implemented in Channel_Gen.
virtual double rate_impl () const private pure virtual
Implemented in Channel_Gen.
virtual SP_ChannelType channel_type_impl () const private pure virtual
Implemented in Channel_Gen.
virtual void get_channel_type_impl (SP_ChannelType & channel_type) const private pure virtual
Implemented in Channel_Gen.
virtual void set_channel_type_impl (SP_ChannelType channel_type) private pure virtual
Implemented in Channel_Gen.
bool has_initialized_channel_type_impl () const private virtual
 {
     return channel_type() != nullptr && channel_type()->is_initialized();
 }
virtual double decay_constant_impl () const private pure virtual
Implemented in Channel_Gen.
virtual void set_decay_constant_impl (double decay_constant) private pure virtual
Implemented in Channel_Gen.
bool has_initialized_decay_constant_impl () const private virtual
References Origen::BAD_DOUBLE.
 {
     return decay_constant() != BAD_DOUBLE;
 }
virtual double xs_impl () const private pure virtual
Implemented in Channel_Gen.
virtual void set_xs_impl (double xs) private pure virtual
Implemented in Channel_Gen.
bool has_initialized_xs_impl () const private virtual
References Origen::BAD_DOUBLE.
 { return xs() != BAD_DOUBLE; }
virtual std::vector<SP_Transition> transitions_impl () const private pure virtual
Implemented in Channel_Gen.
virtual void get_transitions_impl (std::vector< SP_Transition > & transitions) const private pure virtual
Implemented in Channel_Gen.
virtual void set_transitions_impl (std::vector< SP_Transition > transitions) private pure virtual
Implemented in Channel_Gen.
virtual SP_Transition add_transition_impl (int transition_id) private pure virtual
Implemented in Channel_Gen.
virtual SP_Transition add_transition_impl (int transition_id, double yield) private pure virtual
Implemented in Channel_Gen.
std::string name_impl () const private virtual
Reimplemented from Checkable.
 {
     std::string parent_name = "BAD";
     if( parent() != nullptr )
     {
         parent_name = parent()->name();
     }
     std::stringstream ss;
     ss << "CHANNEL(" << parent_name << "," << id() << ")";
     return ss.str();
 }
int id_impl () const private virtual
Reimplemented from Checkable.
References Origen::BAD_INT.
 {
     if( has_initialized_channel_type() && channel_type()->has_initialized_id() )
     {
         return channel_type()->id();
     }
     return BAD_INT;
 }
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     return has_initialized_parent() && has_initialized_decay_constant() &&
            has_initialized_channel_type() && has_initialized_xs() &&
            Checkable::is_initialized_impl();
 }
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
References ORIGEN_CHECKABLE_ERROR.
 {
     bool pass = Checkable::good_impl( errors );
     if( !has_initialized_parent() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized parent", pass, errors );
     if( !has_initialized_decay_constant() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized decay_constant", pass, errors );
     if( !has_initialized_channel_type() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized channel_type", pass, errors );
     if( !has_initialized_xs() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized xs", pass, errors );
     return pass;
 }
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     Json::Value json( Json::objectValue );
     json = Checkable::to_json_impl();
     json["channel_type"] = "UNDEFINED";
     if( has_initialized_channel_type() )
     {
         json["channel_type"] = channel_type()->to_json();
     }
     json["xs"] = xs();
     json["has_initialized_xs"] = has_initialized_xs();
     json["daughter_mass_number"] = daughter_mass_number();
     json["daughter_charge_number"] = daughter_charge_number();
     json["decay_constant"] = decay_constant();
     json["has_initialized_decay_constant"] = has_initialized_decay_constant();
     json["parent"] = "UNDEFINED";
     if( has_initialized_parent() )
     {
         json["parent"] = parent()->name();
     }
     Json::Value json_transitions( Json::arrayValue );
     std::vector<SP_Transition> transitions = this->transitions();
     for( size_t i = 0; i < transitions.size(); ++i )
     {
         json_transitions[(int)i] = transitions[i]->to_json();
     }
     json["transitions"] = json_transitions;
     return json;
 }
virtual std::vector<SP_Transition> byproduct_transitions_impl () const private pure virtual
Implemented in Channel_Gen.
virtual void get_byproduct_transitions_impl (std::vector< SP_Transition > & transitions) const private pure virtual
Implemented in Channel_Gen.
virtual void update_byproduct_transitions_impl () private pure virtual
Implemented in Channel_Gen.
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Channel.h
Core/ts/Channel.cpp