ORIGEN API: Electron Class Reference
Electron Class Reference
#include <Species_FunPart.h>
Member Typedef Documentation
typedef SP_Species SP inherited
strong pointer
typedef WP_Species WP inherited
weak pointer
Member Function Documentation
int charge_number_impl () const private virtual
Implements Species.
References Origen::ELECTRON_CHARGE_NUMBER.
int mass_number_impl () const private virtual
Implements Species.
References Origen::ELECTRON_MASS_NUMBER.
double mass_impl () const private virtual
Implements Species.
References Origen::ELECTRON_MASS.
std::string name_impl () const private virtual
Reimplemented from Species.
int id_impl () const private virtual
Reimplemented from Species.
References Origen::ELECTRON_BYPRODUCT_ID.
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Species.
int charge_number () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_charge_number_impl().
void get_charge_number (int & charge_number) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_charge_number (int charge_number) inherited
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_charge_number () const inherited
int mass_number () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_number_impl().
void get_mass_number (int & mass_number) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_mass_number (int mass_number) inherited
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_mass_number () const inherited
double mass () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_impl().
void get_mass (double & mass) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_mass (double mass) inherited
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_mass () const inherited
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), and ChannelType_Reac::good_impl().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), and Channel_Gen::set_transition_impl().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Species_FunPart.h
Core/ts/Species_FunPart.cpp