ORIGEN API: Solver_cram Class Reference
Solver_cram Class Reference
#include <Solver_cram.h>
CRAM depletion solver class satisfying Origen::solver.
INTERFACE<<Origen::Solver>>
See Origen::Solver for details.
void set_continuous_loss (Vec_Dbl *lambda)
void set_transition_matrix (TransitionMatrixP *trx)
void set_source (Vec_Dbl *src)
void get_defaults (ScaleUtils::IO::DB &dc, bool force=false)
bool check_opts (ScaleUtils::IO::DB &dc, bool allow_missing=true)
void set_opts (const ScaleUtils::IO::DB &opts)
bool solve (const Vec_Dbl &in, double flux, double dt, Vec_Dbl *out)
const ScaleUtils::IO::DB & status () const
void clear ()
Public Member Functions
Solver_cram ()
virtual ~Solver_cram ()
Static Public Member Functions
static void get_defaults_static (ScaleUtils::IO::DB &dc, const bool force)
static bool check_opts_static (ScaleUtils::IO::DB &opts, bool allow_missing)
Private Member Functions
void set_continuous_loss_impl (Vec_Dbl *lambda)
void set_transition_matrix_impl (TransitionMatrixP *trx)
void set_source_impl (Vec_Dbl *src)
void get_defaults_impl (ScaleUtils::IO::DB &dc, bool force)
bool check_opts_impl (ScaleUtils::IO::DB &opts, bool allow_missing)
void set_opts_impl (const ScaleUtils::IO::DB &opts)
bool solve_impl (const Vec_Dbl &in, double flux, double dt, Vec_Dbl *out)
const ScaleUtils::IO::DB & status_impl () const
void clear_impl ()
Private Attributes
Vec_Dbl * d_lambda
Vec_Dbl * d_src
TransitionMatrixP * d_trx
ScaleUtils::IO::UP_DB d_opts
Detailed Description
CRAM depletion solver class satisfying Origen::solver.
Author
Aarno Isotalo
See also
Origen::Solver, kernel_cram()
The options for the CRAM solver are:
"cramOrder" (int)
The order of the cram approximation.
Must be an even integer between 4 and 16.
Default: 16.
"cramInternalSubsteps" (int)
The number of internal substeps in CRAM.
Must be a positive integer.
Default: 1.
"isAdjoint" (bool)
Is this an adjoint calculation?
Can be true or false.
Default: false.
"solver" (string)
Which solver are the options for? Used for some consistency checks.
Must be "cram".
Default: "cram".
"cramRemoveNegatives" (int)
Whether any negative values in the results should be set to zero.
Can be:
0: Do not do anything.
1: Remove all negatives. Note that some adjoint calculations may intentionally involve negative input and hence negative-but-still-physical output.
2: Remove all negatives in forward calculations. Remove all negatives in adjoint calculations if:
All initial concentrations are non-negative 0,
All feed rates are non-negative, AND
Source term is constant.
Default: 2
"cramResultsCutoff" (double)
Concentrations whose absolute value is below cramCutoff*sum(abs(n_final)) are returned as zero.
Must be non-negative.
Default: 0.0 (does nothing)
"tallyEnergyReleased" (bool)
Whether to add a tally nuclide to collect the amount of energy released during the depletion step.
With non zero flux, uses the reaction kappas that include decay
With zero flux, uses decay q-values.
Note that if you sum depletion and subsequent decay steps, the decay energy will be counted twice (as it was already rolled to the reaction kappas),
The result is found in status()->get<double>("energyReleased") and is in [MeV]/[units of n0]
Default: false.
"tallyNumFissions" (bool)
Whether to add a tally nuclide to collect the number of neutron induced fissions.
The result is found in status()->get<double>("numFissions") and is in the units of n0.
Default: false.
"tallyNumCaptures" (bool)
Whether to add a tally nuclide to collect the total number of neutron induced removal reactions (including fissions).
The result is found in status()->get<double>("numCaptures") and is in the units of n0.
Default: false.
"tallyAveConcentrations" (bool)
Whether to add a tally nuclides to collect the average concentrations of ALL nuclides in the library.
The results are found in status()->get<double>("ave_<ZZZAAAI>") and is in the units of n0. <ZZZAAAI> is the extended ZAID of the nuclide (leading zeroes ommited).
Default: false.
The default values are returned by Solver::get_defaults() if the Solver is Solver_cram. They can also be retreived with the static function Solver_cram::get_defaults_static(). The default values should not be hard coded anywhere else than this class.
Examples:
tstSolver_cram.cpp.
Constructor & Destructor Documentation
Solver_cram ()
References Solver_cram::d_opts, and Solver::get_defaults().
     : d_lambda( nullptr )
     , d_src( nullptr )
     , d_trx( nullptr )
     , d_opts( new ScaleUtils::IO::DB() )
 {
     // Get and set default solver options
     this->get_defaults( *d_opts, true );
 }
~Solver_cram () virtual
 { /* * */}
Member Function Documentation
void get_defaults_static (ScaleUtils::IO::DB & dc, const bool force) static
Static version of Solver::get_defaults() for the CRAM solver. Gets default solver options.
Note
See Origen::Solver_cram for list of options. This function is the Only place that should actually contain the default values.
Parameters
[out] dc A SCALE DataContainer where to write the options.
[in] force If true, any values already in dc will be overwritten. If false, only parameters without any value in dc are set. Optional (default = false).
Referenced by Solver_cram::get_defaults_impl().
 {
     if( !dc.has<std::string>( "solver" ) || force )
         dc.set<std::string>( "solver", "cram" );
     if( !dc.has<int>( "cramOrder" ) || force ) dc.set<int>( "cramOrder", 16 );
     if( !dc.has<int>( "cramInternalSubsteps" ) || force )
         dc.set<int>( "cramInternalSubsteps", 1 );
     if( !dc.has<bool>( "isAdjoint" ) || force )
         dc.set<bool>( "isAdjoint", false );
     if( !dc.has<int>( "cramRemoveNegatives" ) || force )
         dc.set<int>( "cramRemoveNegatives", 2 );
     if( !dc.has<double>( "cramResultsCutoff" ) || force )
         dc.set<double>( "cramResultsCutoff", 0.0 );
     if( !dc.has<bool>( "tallyEnergyReleased" ) || force )
         dc.set<bool>( "tallyEnergyReleased", false );
     if( !dc.has<bool>( "tallyNumFissions" ) || force )
         dc.set<bool>( "tallyNumFissions", false );
     if( !dc.has<bool>( "tallyNumCaptures" ) || force )
         dc.set<bool>( "tallyNumCaptures", false );
     if( !dc.has<bool>( "tallyAveConcentrations" ) || force )
         dc.set<bool>( "tallyAveConcentrations", false );
 }
bool check_opts_static (ScaleUtils::IO::DB & opts, bool allow_missing) static
Static version of Solver::check_opts for Solver_cram. Check that a set of CRAM solver options is valid. This does not quarantee that the results will be accurate, only that the solver can be run with the options.
Note
See Origen::Solver_cram for description of the options.
Parameters
[in,out] opts In: the solver options. out: any error messages about the options.
[in] allow_missing Whether opts is allowed to miss options without prompting an error. Optional (default = true)
Returns
true if the check is passed, false if the check fails.
Note
Any errors will be written to opts.
Examples:
tstSolver_cram.cpp.
Referenced by Solver_cram::check_opts_impl(), and TEST().
 {
     // *** Check the option "solver" ***
     if( opts.has<std::string>( "solver" ) )
     {
         if( opts.get<std::string>( "solver" ) != "cram" )
         {
             // "solver" is not CRAM (this function checks CRAM options)
             std::stringstream ss;
             ss << "Option \"solver\" is \"" << opts.get<std::string>( "solver" )
                << "\" but check_opts from Solver_cram was called." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     else if( !allow_missing )
     {
         // "solver" is missing
         std::stringstream ss;
         ss << "Option \"solver\" is missing but allow_missing is false."
            << std::endl;
         opts.appendError( ss.str() );
     }
     // *** Check the option "cramOrder" ***
     if( opts.has<int>( "cramOrder" ) )
     {
         if( ( opts.get<int>( "cramOrder" ) < 4 ) ||
             ( opts.get<int>( "cramOrder" ) > 16 ) ||
             ( opts.get<int>( "cramOrder" ) % 2 != 0 ) )
         {
             // CRAM order must be between 4 and 16 and even
             std::stringstream ss;
             ss << "CRAM order is " << opts.get<int>( "cramOrder" )
                << " but only even orders between 4 and 16 are allowed."
                << std::endl;
             opts.appendError( ss.str() );
         }
     }
     else if( !allow_missing )
     {
         // "cramOrder" is missing
         std::stringstream ss;
         ss << "Option \"cramOrder\" is missing but allow_missing is false."
            << std::endl;
         opts.appendError( ss.str() );
     }
     // *** Check the option "cramInternalSubsteps" ***
     if( opts.has<int>( "cramInternalSubsteps" ) )
     {
         if( opts.get<int>( "cramInternalSubsteps" ) < 1 )
         {
             // number of substeps must be positive
             // CRAM order must be between 4 and 16 and even
             std::stringstream ss;
             ss << "Number of internal substeps for CRAM is "
                << opts.get<int>( "cramInternalSubsteps" )
                << " but must be positive." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     else if( !allow_missing )
     {
         // "cramInternalSubsteps" is missing
         std::stringstream ss;
         ss << "Option \"cramInternalSubsteps\" is missing but allow_missing"
            << " is false." << std::endl;
         opts.appendError( ss.str() );
     }
     // *** Check the option "isAdjoint" ***
     if( opts.has<bool>( "isAdjoint" ) )
     {
         // cram can handle adjoint so either works
     }
     else if( !allow_missing )
     {
         // "isAdjoint" is missing
         std::stringstream ss;
         ss << "Option \"isAdjoint\" is missing but allow_missing"
            << " is false." << std::endl;
         opts.appendError( ss.str() );
     }
     // *** Check the option "cramRemoveNegatives" ***
     if( opts.has<int>( "cramRemoveNegatives" ) )
     {
         // Valid values are 0, 1, and 2
         if( ( opts.get<int>( "cramRemoveNegatives" ) < 0 ) ||
             ( opts.get<int>( "cramRemoveNegatives" ) > 2 ) )
         {
             std::stringstream ss;
             ss << "Option \"cramRemoveNegatives\" is "
                << opts.get<int>( "cramRemoveNegatives" )
                << " but must be 0, 1, or 2." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     else if( !allow_missing )
     {
         // "cramRemoveNegatives" is missing
         std::stringstream ss;
         ss << "Option \"cramRemoveNegatives\" is missing but allow_missing"
            << " is false." << std::endl;
         opts.appendError( ss.str() );
     }
     // *** Check the option "cramResultsCutoff" ***
     if( opts.has<double>( "cramResultsCutoff" ) )
     {
         // must be non-negative
         if( opts.get<double>( "cramResultsCutoff" ) < 0.0 )
         {
             std::stringstream ss;
             ss << "Option \"cutoff\" must be non-negative" << std::endl;
             opts.appendError( ss.str() );
         }
     }
     else if( !allow_missing )
     {
         // "cramRemoveNegatives" is missing
         std::stringstream ss;
         ss << "Option \"cutoff\" is missing but allow_missing"
            << " is false." << std::endl;
         opts.appendError( ss.str() );
     }
     // *** Check the options for tally nuclides ***
     if( !allow_missing )
     {
         if( !opts.has<bool>( "tallyEnergyReleased" ) )
         {
             // "tallyEnergyReleased" is missing
             std::stringstream ss;
             ss << "Option \"tallyEnergyReleased\" is missing but allow_missing"
                << " is false." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     if( !allow_missing )
     {
         if( !opts.has<bool>( "tallyNumFissions" ) )
         {
             // "tallyNumFissions" is missing
             std::stringstream ss;
             ss << "Option \"tallyNumFissions\" is missing but allow_missing"
                << " is false." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     if( !allow_missing )
     {
         if( !opts.has<bool>( "tallyNumCaptures" ) )
         {
             // "tallyNumFissions" is missing
             std::stringstream ss;
             ss << "Option \"tallyNumCaptures\" is missing but allow_missing"
                << " is false." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     if( !allow_missing )
     {
         if( !opts.has<bool>( "tallyAveConcentrations" ) )
         {
             // "tallyNumFissions" is missing
             std::stringstream ss;
             ss << "Option \"tallyAveConcentrations\" is missing but"
                << " allow_missing is false." << std::endl;
             opts.appendError( ss.str() );
         }
     }
     if( opts.numError() == 0 )
         return true;
     else
         return false;
 }
void set_continuous_loss_impl (Vec_Dbl * lambda) private virtual
Implements Solver.
References Solver_cram::d_lambda.
 {
     d_lambda = lambda;
 }
void set_transition_matrix_impl (TransitionMatrixP * trx) private virtual
Implements Solver.
References Solver_cram::d_trx.
 {
     d_trx = trx;
 }
void set_source_impl (Vec_Dbl * src) private virtual
Implements Solver.
References Solver_cram::d_src.
 { d_src = src; }
void get_defaults_impl (ScaleUtils::IO::DB & dc, bool force) private virtual
Implements Solver.
References Solver_cram::get_defaults_static().
 {
     this->get_defaults_static( dc, force );
 }
bool check_opts_impl (ScaleUtils::IO::DB & opts, bool allow_missing) private virtual
Implements Solver.
References Solver_cram::check_opts_static().
 {
     return this->check_opts_static( opts, allow_missing );
 }
void set_opts_impl (const ScaleUtils::IO::DB & opts) private virtual
Implements Solver.
References Solver::check_opts(), CLASS_NAME, and Solver_cram::d_opts.
 {
     if( dc.has<bool>( "isAdjoint" ) )
         d_opts->set<bool>( "isAdjoint", dc.get<bool>( "isAdjoint" ) );
     if( dc.has<int>( "cramRemoveNegatives" ) )
         d_opts->set<int>( "cramRemoveNegatives",
                           dc.get<int>( "cramRemoveNegatives" ) );
     if( dc.has<double>( "cramResultsCutoff" ) )
         d_opts->set<double>( "cramResultsCutoff",
                              dc.get<double>( "cramResultsCutoff" ) );
     if( dc.has<int>( "cramOrder" ) )
         d_opts->set<int>( "cramOrder", dc.get<int>( "cramOrder" ) );
     if( dc.has<int>( "cramInternalSubsteps" ) )
         d_opts->set<int>( "cramInternalSubsteps",
                           dc.get<int>( "cramInternalSubsteps" ) );
     if( dc.has<bool>( "tallyEnergyReleased" ) )
         d_opts->set<bool>( "tallyEnergyReleased",
                            dc.get<bool>( "tallyEnergyReleased" ) );
     // i5q at Nov 18, 2015: this is a temporary hack to remain compatible with
     // Exnihilo while changing the variable names. If you see this in 2016 or
     // later, remove the below option
     if( dc.has<bool>( "cramTallyEnergyReleased" ) )
         d_opts->set<bool>( "tallyEnergyReleased",
                            dc.get<bool>( "cramTallyEnergyReleased" ) );
     if( dc.has<bool>( "tallyNumFissions" ) )
         d_opts->set<bool>( "tallyNumFissions",
                            dc.get<bool>( "tallyNumFissions" ) );
     if( dc.has<bool>( "tallyNumCaptures" ) )
         d_opts->set<bool>( "tallyNumCaptures",
                            dc.get<bool>( "tallyNumCaptures" ) );
     if( dc.has<bool>( "tallyAveConcentrations" ) )
         d_opts->set<bool>( "tallyAveConcentrations",
                            dc.get<bool>( "tallyAveConcentrations" ) );
     // "solver" must be cram, this includes it in the below check so we get an
     //  error if the parameter set was for a different solver
     if( dc.has<std::string>( "solver" ) )
         d_opts->set<std::string>( "solver", dc.get<std::string>( "solver" ) );
     // Check that the options are valid
     this->check_opts( *d_opts, false );
     if( d_opts->numError() > 0 )
     {
         std::fprintf(
             stderr, "\n%s: set_opts_impl() failed because:\n", CLASS_NAME );
         std::cerr << d_opts->dumpErrorStack();
         std::exit( EXIT_FAILURE );
     }
 }
bool solve_impl (const Vec_Dbl & in, double flux, double dt, Vec_Dbl * out) private virtual
Implements Solver.
References TransitionMatrixP::add_concentration_tallies(), TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_captures_tally(), TransitionMatrixP::add_num_fissions_tally(), Solver::check_opts(), Solver_cram::d_lambda, Solver_cram::d_opts, Solver_cram::d_src, Solver_cram::d_trx, TransitionMatrixP::fold_flux(), TransitionMatrixP::get_itot(), TransitionMatrixP::get_kd_(), TransitionMatrixP::get_loc(), TransitionMatrixP::get_non(), TransitionMatrixP::get_non0_(), TransitionMatrixP::get_nucl(), and kernel_cram().
 {
     jDebugLine( "      CRAM solve time=" << dt << " flux=" << flux << " ..." );
     Require( flux >= 0.0 );
     Require( dt >= 0.0 );
     Require( out != nullptr );
     Require( ( this->check_opts( *d_opts, false ) ) );
     int energy_tally_idx = -1;  // < 0 == not set
     int fission_tally_idx = -1;
     int capture_tally_idx = -1;
     int concentration_tally_idx = -1;
     TransitionMatrixP trx_copy;
     TransitionMatrixP* trx;
     Vec_Dbl n0( in );
     Vec_Int tally_zaids;  // used if average concentrations are tallied
     // Store the physical number of nuclides
     int physical_itot = d_trx->get_itot();
     // Check if there are tallies, if yes, copy the TransitionMatrix
     // NOTE: this copy could be avoided easily by giving the
     // Transition matrix a "removeTallies" function. All you need to do
     // is store the original sizes of the arrays and then truncate to those.
     if( d_opts->has<bool>( "tallyEnergyReleased" ) ||
         d_opts->has<bool>( "tallyNumFissions" ) ||
         d_opts->has<bool>( "tallyNumCaptures" ) ||
         d_opts->has<bool>( "tallyAveConcentrations" ) )
     {
         trx_copy = TransitionMatrixP( *d_trx );
         trx = &trx_copy;
     }
     else
     {
         trx = d_trx;
     }
     // Add tallies (to the copy)
     if( d_opts->has<bool>( "tallyEnergyReleased" ) &&
         d_opts->get<bool>( "tallyEnergyReleased" ) )
     {
         energy_tally_idx = trx->add_energy_tally( flux );
         n0.push_back( 0.0 );
     }
     if( d_opts->has<bool>( "tallyNumFissions" ) &&
         d_opts->get<bool>( "tallyNumFissions" ) )
     {
         fission_tally_idx = trx->add_num_fissions_tally();
         n0.push_back( 0.0 );
     }
     if( d_opts->has<bool>( "tallyNumCaptures" ) &&
         d_opts->get<bool>( "tallyNumCaptures" ) )
     {
         capture_tally_idx = trx->add_num_captures_tally();
         n0.push_back( 0.0 );
     }
     if( d_opts->has<bool>( "tallyAveConcentrations" ) &&
         d_opts->get<bool>( "tallyAveConcentrations" ) )
     {
         concentration_tally_idx = trx->add_concentration_tallies( tally_zaids );
         n0.insert( n0.end(), tally_zaids.size(), 0.0 );
     }
     // Fold library.
     DoubleList diag, a;
     trx->fold_flux( flux, diag, a );
     // Get the number of nuclides.
     int itot = trx->get_itot();
     // Ensure that the output array has enough space.
     out->resize( n0.size(), 0.0 );
     // Check if there is a source term.
     int source_order = -1;
     if( d_src != nullptr )
         for( int i = 0; i < itot; i++ )
             if( d_src->at( i ) > 0.0 )
             {
                 source_order = 0;
                 break;
             }
     // Allocate and set the source term.
     double** source_term = nullptr;
     if( source_order > -1 )
     {
         source_term = (double**)std::malloc( itot * sizeof( double* ) );
         for( int i = 0; i < itot; i++ )
             source_term[i] =
                 (double*)std::calloc( source_order + 1, sizeof( double ) );
         for( int i = 0; i < d_src->size(); i++ )
             source_term[i][0] = ( *d_src )[i];
     }
     // Set removal rates.
     if( d_lambda != nullptr )
         for( int i = 0; i < physical_itot; i++ ) diag[i] -= ( *d_lambda )[i];
     // Is the flux zero? (We do not pass the flux itself to the solver.)
     int zero_flux_step = 0;
     if( flux == 0 ) zero_flux_step = 1;
     // Call the actual solver function (isn't this call beautiful).
     int rv = kernel_cram( &( *out )[0],
                           &( n0[0] ),
                           source_term,
                           source_order,
                           dt,
                           itot,
                           trx->get_non(),
                           &( trx->get_non0_()->front() ),
                           &( trx->get_kd_()->front() ),
                           &diag[0],
                           &a[0],
                           &( trx->get_loc()->front() ),
                           zero_flux_step,
                           d_opts->get<bool>( "isAdjoint" ),
                           d_opts->get<int>( "cramOrder" ),
                           d_opts->get<int>( "cramInternalSubsteps" ),
                           d_opts->get<int>( "cramRemoveNegatives" ),
                           d_opts->get<double>( "cramResultsCutoff" ),
                           &( trx->get_nucl()->front() ) );
     // Free memory.
     if( source_order > -1 )
     {
         for( int i = 0; i < itot; ++i ) std::free( source_term[i] );
         std::free( source_term );
     }
     // Add status flag to the internal status container.
     d_opts->set<int>( "statusFlag", rv );
     if( rv != 0 )
     {
         std::stringstream ss;
         ss << "CRAM solution failed with exit code " << rv << std::endl;
         d_opts->appendError( ss.str() );
     }
     // Extract the tally results
     if( energy_tally_idx > 0 )
         d_opts->set<double>( "energyReleased", ( *out )[energy_tally_idx] );
     if( fission_tally_idx > 0 )
         d_opts->set<double>( "numFissions", ( *out )[fission_tally_idx] );
     if( capture_tally_idx > 0 )
         d_opts->set<double>( "numCaptures", ( *out )[capture_tally_idx] );
     if( concentration_tally_idx > 0 )
         for( int i = 0; i < tally_zaids.size(); ++i )
         {
             char param_name[512];
             sprintf( param_name, "ave_%d", tally_zaids[i] );
             double val = ( *out )[concentration_tally_idx + i] / dt;
             d_opts->set<double>( param_name, val );
         }
     out->resize( in.size() );
     return ( rv == 0 );
 }
const ScaleUtils::IO::DB & status_impl () const private virtual
Implements Solver.
References Solver_cram::d_opts.
 { return *d_opts; }
void clear_impl () private virtual
Implements Solver.
References Solver_cram::d_opts, Solver::get_defaults(), Solver::set_continuous_loss(), Solver::set_source(), and Solver::set_transition_matrix().
 {
     this->set_continuous_loss( nullptr );
     this->set_transition_matrix( nullptr );
     this->set_source( nullptr );
     d_opts->clear();
     this->get_defaults( *d_opts, true );  // Get default solver options.
 }
void set_continuous_loss (Vec_Dbl * lambda) inherited
Set continuous removal rates. The rates are defined by decays constants that decay the nuclide out of existence.
Parameters
[in] lambda The removal rates >= 0 [1/s] for each nuclide.
Examples:
tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::set_continuous_loss_impl().
Referenced by Solver_cram::clear_impl(), Solver_matrex::clear_impl(), and TEST().
 {
     set_continuous_loss_impl( lambda );
 }
void set_transition_matrix (TransitionMatrixP * trx) inherited
Set an Origen TransitionMatrix (library data).
Parameters
[in] trx Origen::TransitionMatrix containing the library data.
Examples:
exNEAMS.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::set_transition_matrix_impl().
Referenced by Solver_cram::clear_impl(), Solver_matrex::clear_impl(), and TEST().
 {
     set_transition_matrix_impl( trx );
 }
void set_source (Vec_Dbl * src) inherited
Set constant source term.
Parameters
[in] src The source terms for each nuclide [(units of n0 in Solver::solve()) per second].
Examples:
tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::set_source_impl().
Referenced by Solver_cram::clear_impl(), Solver_matrex::clear_impl(), and TEST().
 { set_source_impl( src ); }
void get_defaults (ScaleUtils::IO::DB & dc, bool force = false) inherited
Get default solver opts.
Note
The options are solver specific. See the appropriate solver subclass for list of opts.
Parameters
[out] dc A SCALE DataContainer where to write the opts.
[in] force If true, any values already in dc will be overwritten. If false, only parameters without any value in dc are set. Optional (default = false).
Examples:
tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::get_defaults_impl().
Referenced by Solver_cram::clear_impl(), Solver_matrex::clear_impl(), Solver_cram::Solver_cram(), Solver_matrex::Solver_matrex(), and TEST().
 {
     get_defaults_impl( dc, force );
 }
bool check_opts (ScaleUtils::IO::DB & opts, bool allow_missing = true) inherited
Check that a set of solver options is valid. This does not quarantee that the results will be accurate, only that the solver can be run with the opts.
Note
The options are solver specific. See the appropriate solver subclass for list of opts.
Parameters
[in,out] opts In: the solver opts. out: any error messages about the opts.
[in] allow_missing Whether opts is allowed to miss options without prompting an error. Optional (default = true).
Returns
true if the check is passed, false if the check fails.
Note
Any errors will be written to opts.
Examples:
tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::check_opts_impl().
Referenced by Solver_cram::set_opts_impl(), Solver_matrex::set_opts_impl(), Solver_cram::solve_impl(), Solver_matrex::solve_impl(), and TEST().
 {
     return check_opts_impl( opts, allow_missing );
 }
void set_opts (const ScaleUtils::IO::DB & dc) inherited
Set solver opts. Dies if you try to set incorrect values, so use Solver::check_opts() first if you want to be sure. Any options that are not specified in opts will be left to their earlier values (all are set to defaults by the constructor and by Solver::clear().
Note
The options are solver specific. See the appropriate solver subclass for list of opts.
Parameters
[in] dc The new solver opts. Any option not specified will be left untouched.
Examples:
tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::set_opts_impl().
Referenced by TEST().
 { set_opts_impl( dc ); }
bool solve (const Vec_Dbl & in, double flux, double dt, Vec_Dbl * out) inherited
Perform a single depletion calculation. TransitionMatrix must be set.
Note
Concentration units. "in" can have any units directly proportional to the number of atoms. The solver does not care about scaling. "out" will be in the same units. Make sure that the source term is in the correct units. Valid units include [1], [1/cm3], [1/bcm], [mol], etc.
Parameters
[in] in Initial concentrations or abundances [see the note].
[in] flux Neutron flux density [1/cm2s].
[in] dt Step length [s].
[out] out Final concentrations or abundances [same units as "in"].
Returns
true on success or false on failure.
Examples:
exNEAMS.cpp, tstSolver.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::solve_impl().
Referenced by TEST().
 {
     return solve_impl( in, flux, dt, out );
 }
const ScaleUtils::IO::DB & status () const inherited
Return current solver options and possible error messages from Solver::solve(). Note, however, that the solver kernels do not actually send any error messages as of yet and instead terminate the process.
Note
The options are solver specific. See the appropriate solver subclass for list of opts.
Returns
the options and error messages.
Examples:
tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References Solver::status_impl().
Referenced by TEST().
 { return status_impl(); }
void clear () inherited
Clear all data returning the solver option to the state it had right after constructor. All solver options get default values.
Note
This never needs to be called for memory management or other similar reasons.
Examples:
exNEAMS.cpp.
References Solver::clear_impl().
Referenced by TEST().
 { clear_impl(); }
Member Data Documentation
Vec_Dbl* d_lambda private
Referenced by Solver_cram::set_continuous_loss_impl(), and Solver_cram::solve_impl().
Vec_Dbl* d_src private
Referenced by Solver_cram::set_source_impl(), and Solver_cram::solve_impl().
TransitionMatrixP* d_trx private
Referenced by Solver_cram::set_transition_matrix_impl(), and Solver_cram::solve_impl().
ScaleUtils::IO::UP_DB d_opts private
Referenced by Solver_cram::clear_impl(), Solver_cram::set_opts_impl(), Solver_cram::solve_impl(), Solver_cram::Solver_cram(), and Solver_cram::status_impl().
The documentation for this class was generated from the following files:
Solver/cram/Solver_cram.h
Solver/cram/Solver_cram.cpp