ORIGEN API: auxiliary_erf_m Module Reference
auxiliary_erf_m Module Reference
Data Types
interface erf
interface erfc
Functions/Subroutines
real function real_erf (z)
real(c_double) function double_erf (z)
real function real_erfc (z)
real(c_double) function double_erfc (z)
subroutine erf_erfc
real(c_double) function csevl (x, cs, n)
Variables
real(c_double), parameter, private dp0 = 0._C_DOUBLE
real(c_double), parameter, private dp1 = 1._C_DOUBLE
real(c_double), parameter, private dp2 = 2._C_DOUBLE
real(c_double), parameter, private dp3 = 3._C_DOUBLE
real(c_double), parameter, private dp4 = 4._C_DOUBLE
real(c_double), parameter, private dph = .5_C_DOUBLE
real(c_double), parameter, private dp5 = 5._C_DOUBLE
real(c_double), parameter, private dp8 = 8._C_DOUBLE
real(c_double), parameter, private dpth = dp1/dp3
real(c_double), parameter, private dppi = 3.14159265358979323846_C_DOUBLE
real(c_double), parameter, private dp2th = dp2/dp3
real(c_double), dimension(21), private erfcs = (/ -.49046121234691808039984544033376e-1_C_DOUBLE, -.14226120510371364237824741899631e+0_C_DOUBLE, +.10035582187599795575754676712933e-1_C_DOUBLE, -.57687646997674847650827025509167e-3_C_DOUBLE, +.27419931252196061034422160791471e-4_C_DOUBLE, -.11043175507344507604135381295905e-5_C_DOUBLE, +.38488755420345036949961311498174e-7_C_DOUBLE, -.11808582533875466969631751801581e-8_C_DOUBLE, +.32334215826050909646402930953354e-10_C_DOUBLE, -.79910159470045487581607374708595e-12_C_DOUBLE, +.17990725113961455611967245486634e-13_C_DOUBLE, -.37186354878186926382316828209493e-15_C_DOUBLE, +.71035990037142529711689908394666e-17_C_DOUBLE, -.12612455119155225832495424853333e-18_C_DOUBLE, +.20916406941769294369170500266666e-20_C_DOUBLE, -.32539731029314072982364160000000e-22_C_DOUBLE, +.47668672097976748332373333333333e-24_C_DOUBLE, -.65980120782851343155199999999999e-26_C_DOUBLE, +.86550114699637626197333333333333e-28_C_DOUBLE, -.10788925177498064213333333333333e-29_C_DOUBLE, +.12811883993017002666666666666666e-31_C_DOUBLE /)
real(c_double), dimension(49), private erc2cs = (/ -.6960134660230950112739150826197e-1_C_DOUBLE, -.4110133936262089348982212084666e-1_C_DOUBLE, +.3914495866689626881561143705244e-2_C_DOUBLE, -.4906395650548979161280935450774e-3_C_DOUBLE, +.7157479001377036380760894141825e-4_C_DOUBLE, -.1153071634131232833808232847912e-4_C_DOUBLE, +.1994670590201997635052314867709e-5_C_DOUBLE, -.3642666471599222873936118430711e-6_C_DOUBLE, +.6944372610005012589931277214633e-7_C_DOUBLE, -.1371220902104366019534605141210e-7_C_DOUBLE, +.2788389661007137131963860348087e-8_C_DOUBLE, -.5814164724331161551864791050316e-9_C_DOUBLE, +.1238920491752753181180168817950e-9_C_DOUBLE, -.2690639145306743432390424937889e-10_C_DOUBLE, +.5942614350847910982444709683840e-11_C_DOUBLE, -.1332386735758119579287754420570e-11_C_DOUBLE, +.3028046806177132017173697243304e-12_C_DOUBLE, -.6966648814941032588795867588954e-13_C_DOUBLE, +.1620854541053922969812893227628e-13_C_DOUBLE, -.3809934465250491999876913057729e-14_C_DOUBLE, +.9040487815978831149368971012975e-15_C_DOUBLE, -.2164006195089607347809812047003e-15_C_DOUBLE, +.5222102233995854984607980244172e-16_C_DOUBLE, -.1269729602364555336372415527780e-16_C_DOUBLE, +.3109145504276197583836227412951e-17_C_DOUBLE, -.7663762920320385524009566714811e-18_C_DOUBLE, +.1900819251362745202536929733290e-18_C_DOUBLE, -.4742207279069039545225655999965e-19_C_DOUBLE, +.1189649200076528382880683078451e-19_C_DOUBLE, -.3000035590325780256845271313066e-20_C_DOUBLE, +.7602993453043246173019385277098e-21_C_DOUBLE, -.1935909447606872881569811049130e-21_C_DOUBLE, +.4951399124773337881000042386773e-22_C_DOUBLE, -.1271807481336371879608621989888e-22_C_DOUBLE, +.3280049600469513043315841652053e-23_C_DOUBLE, -.8492320176822896568924792422399e-24_C_DOUBLE, +.2206917892807560223519879987199e-24_C_DOUBLE, -.5755617245696528498312819507199e-25_C_DOUBLE, +.1506191533639234250354144051199e-25_C_DOUBLE, -.3954502959018796953104285695999e-26_C_DOUBLE, +.1041529704151500979984645051733e-26_C_DOUBLE, -.2751487795278765079450178901333e-27_C_DOUBLE, +.7290058205497557408997703680000e-28_C_DOUBLE, -.1936939645915947804077501098666e-28_C_DOUBLE, +.5160357112051487298370054826666e-29_C_DOUBLE, -.1378419322193094099389644800000e-29_C_DOUBLE, +.3691326793107069042251093333333e-30_C_DOUBLE, -.9909389590624365420653226666666e-31_C_DOUBLE, +.2666491705195388413323946666666e-31_C_DOUBLE /)
real(c_double), dimension(59), private erfccs = (/ +.715179310202924774503697709496e-1_C_DOUBLE, -.265324343376067157558893386681e-1_C_DOUBLE, +.171115397792085588332699194606e-2_C_DOUBLE, -.163751663458517884163746404749e-3_C_DOUBLE, +.198712935005520364995974806758e-4_C_DOUBLE, -.284371241276655508750175183152e-5_C_DOUBLE, +.460616130896313036969379968464e-6_C_DOUBLE, -.822775302587920842057766536366e-7_C_DOUBLE, +.159214187277090112989358340826e-7_C_DOUBLE, -.329507136225284321486631665072e-8_C_DOUBLE, +.722343976040055546581261153890e-9_C_DOUBLE, -.166485581339872959344695966886e-9_C_DOUBLE, +.401039258823766482077671768814e-10_C_DOUBLE, -.100481621442573113272170176283e-10_C_DOUBLE, +.260827591330033380859341009439e-11_C_DOUBLE, -.699111056040402486557697812476e-12_C_DOUBLE, +.192949233326170708624205749803e-12_C_DOUBLE, -.547013118875433106490125085271e-13_C_DOUBLE, +.158966330976269744839084032762e-13_C_DOUBLE, -.472689398019755483920369584290e-14_C_DOUBLE, +.143587337678498478672873997840e-14_C_DOUBLE, -.444951056181735839417250062829e-15_C_DOUBLE, +.140481088476823343737305537466e-15_C_DOUBLE, -.451381838776421089625963281623e-16_C_DOUBLE, +.147452154104513307787018713262e-16_C_DOUBLE, -.489262140694577615436841552532e-17_C_DOUBLE, +.164761214141064673895301522827e-17_C_DOUBLE, -.562681717632940809299928521323e-18_C_DOUBLE, +.194744338223207851429197867821e-18_C_DOUBLE, -.682630564294842072956664144723e-19_C_DOUBLE, +.242198888729864924018301125438e-19_C_DOUBLE, -.869341413350307042563800861857e-20_C_DOUBLE, +.315518034622808557122363401262e-20_C_DOUBLE, -.115737232404960874261239486742e-20_C_DOUBLE, +.428894716160565394623737097442e-21_C_DOUBLE, -.160503074205761685005737770964e-21_C_DOUBLE, +.606329875745380264495069923027e-22_C_DOUBLE, -.231140425169795849098840801367e-22_C_DOUBLE, +.888877854066188552554702955697e-23_C_DOUBLE, -.344726057665137652230718495566e-23_C_DOUBLE, +.134786546020696506827582774181e-23_C_DOUBLE, -.531179407112502173645873201807e-24_C_DOUBLE, +.210934105861978316828954734537e-24_C_DOUBLE, -.843836558792378911598133256738e-25_C_DOUBLE, +.339998252494520890627359576337e-25_C_DOUBLE, -.137945238807324209002238377110e-25_C_DOUBLE, +.563449031183325261513392634811e-26_C_DOUBLE, -.231649043447706544823427752700e-26_C_DOUBLE, +.958446284460181015263158381226e-27_C_DOUBLE, -.399072288033010972624224850193e-27_C_DOUBLE, +.167212922594447736017228709669e-27_C_DOUBLE, -.704599152276601385638803782587e-28_C_DOUBLE, +.297976840286420635412357989444e-28_C_DOUBLE, -.126252246646061929722422632994e-28_C_DOUBLE, +.539543870454248793985299653154e-29_C_DOUBLE, -.238099288253145918675346190062e-29_C_DOUBLE, +.109905283010276157359726683750e-29_C_DOUBLE, -.486771374164496572732518677435e-30_C_DOUBLE, +.152587726411035756763200828211e-30_C_DOUBLE /)
real(c_double), private sqrtpi = 1.7724538509055160272981674833411_C_DOUBLE
real(c_double), private xsml = -6.01368735695764033977e+00_C_DOUBLE
real(c_double), private xmax = 2.65332996850925972865e+01_C_DOUBLE
real(c_double), private sqeps = 1.49011611938476562500e-08_C_DOUBLE
real(c_double), private x
real(c_double), private y
real(c_double), private yy
real(c_double), private er
real(c_double), private ec
integer, private nterf =12
integer, private nterc2 =24
integer, private nterfc =20
Function/Subroutine Documentation
real function auxiliary_erf_m::real_erf (real z)
References er, erf_erfc(), and x.
         real :: z
         x = z
         call erf_erfc
         zr = er
real(c_double) function auxiliary_erf_m::double_erf (real(c_double) z)
References er, erf_erfc(), and x.
Referenced by origen_neutron::totaln().
         real(C_DOUBLE) :: z
         x = z
         call erf_erfc
         zr = er
real function auxiliary_erf_m::real_erfc (real z)
References ec, erf_erfc(), and x.
         real :: z
         x = z
         call erf_erfc
         zr = ec
real(c_double) function auxiliary_erf_m::double_erfc (real(c_double) z)
References ec, erf_erfc(), and x.
         real(C_DOUBLE) :: z
         x = z
         call erf_erfc
         zr = ec
subroutine auxiliary_erf_m::erf_erfc ()
References csevl(), dp0, dp1, dp2, dp3, dp5, dp8, dph, ec, er, erc2cs, erfccs, erfcs, nterc2, nterf, nterfc, sqeps, sqrtpi, x, xmax, xsml, y, and yy.
Referenced by double_erf(), double_erfc(), real_erf(), and real_erfc().
         y = abs(x)
         if ( x <= xsml ) then
           er = -dp1
           ec = dp2
         else if (y <= sqeps) then
           er = dp2*x/sqrtpi
           ec = dp1 - er
 !
 ! erf(x) = 1.0 - erfc(x) for -1.0 .le. x .le. 1.0
 !
         else if (y <= dp1) then
           er = x*(dp1+csevl(dp2*x**2-dp1,erfcs,nterf))
           ec = dp1 - er
 !
 ! erf(x) = 1.0 - erfc(x) for  abs(x) .gt. 1.0
 !
         else if (y <= dp2) then
           yy = y**2
           ec = exp(-yy)/y*(dph+csevl((dp8/yy-dp5)/dp3,erc2cs,nterc2))
           if ( x < dp0 ) ec = dp2-ec
           er = dp1-ec
         else if (y <= xmax) then
           yy = y**2
           ec = exp(-yy)/y*(dph+csevl(dp8/yy-dp1,erfccs,nterfc))
           if ( x < dp0 ) ec = dp2-ec
           er = dp1-ec
         else
           er = dp1
           ec = dp0
         endif
real(c_double) function auxiliary_erf_m::csevl (real(c_double) x, real(c_double), dimension(n) cs, integer n)
References dp0, dp2, and dph.
Referenced by erf_erfc().
         real(C_DOUBLE) :: x
         integer  :: n
         real(C_DOUBLE) , dimension(n) :: cs
         real(C_DOUBLE) :: b0, b1, b2, twox
         integer  :: i
         b1 = dp0
         b0 = dp0
         twox = dp2*x
         do i=n,1,-1
           b2 = b1
           b1 = b0
           b0 = twox*b1-b2 + cs(i)
         enddo
         csevl = dph*(b0-b2)
Variable Documentation
real(c_double), parameter, private dp0 = 0._C_DOUBLE
Referenced by csevl(), and erf_erfc().
       real(C_DOUBLE),parameter,private ::  &
           dp0   = 0._c_double, dp1 = 1._c_double, dp2  = 2._c_double,    &
           dp3   = 3._c_double, dp4 = 4._c_double, dph  = .5_c_double,    &
           dp5   = 5._c_double, dp8 = 8._c_double, dpth = dp1/dp3,      &
           dppi  = 3.14159265358979323846_c_double,                   &
           dp2th = dp2/dp3
real(c_double), parameter, private dp1 = 1._C_DOUBLE
Referenced by erf_erfc().
real(c_double), parameter, private dp2 = 2._C_DOUBLE
Referenced by csevl(), and erf_erfc().
real(c_double), parameter, private dp3 = 3._C_DOUBLE
Referenced by erf_erfc().
real(c_double), parameter, private dp4 = 4._C_DOUBLE
real(c_double), parameter, private dph = .5_C_DOUBLE
Referenced by csevl(), and erf_erfc().
real(c_double), parameter, private dp5 = 5._C_DOUBLE
Referenced by erf_erfc().
real(c_double), parameter, private dp8 = 8._C_DOUBLE
Referenced by erf_erfc().
real(c_double), parameter, private dpth = dp1/dp3
real(c_double), parameter, private dppi = 3.14159265358979323846_C_DOUBLE
real(c_double), parameter, private dp2th = dp2/dp3
real(c_double), dimension(21), private erfcs = (/ -.49046121234691808039984544033376e-1_C_DOUBLE, -.14226120510371364237824741899631e+0_C_DOUBLE, +.10035582187599795575754676712933e-1_C_DOUBLE, -.57687646997674847650827025509167e-3_C_DOUBLE, +.27419931252196061034422160791471e-4_C_DOUBLE, -.11043175507344507604135381295905e-5_C_DOUBLE, +.38488755420345036949961311498174e-7_C_DOUBLE, -.11808582533875466969631751801581e-8_C_DOUBLE, +.32334215826050909646402930953354e-10_C_DOUBLE, -.79910159470045487581607374708595e-12_C_DOUBLE, +.17990725113961455611967245486634e-13_C_DOUBLE, -.37186354878186926382316828209493e-15_C_DOUBLE, +.71035990037142529711689908394666e-17_C_DOUBLE, -.12612455119155225832495424853333e-18_C_DOUBLE, +.20916406941769294369170500266666e-20_C_DOUBLE, -.32539731029314072982364160000000e-22_C_DOUBLE, +.47668672097976748332373333333333e-24_C_DOUBLE, -.65980120782851343155199999999999e-26_C_DOUBLE, +.86550114699637626197333333333333e-28_C_DOUBLE, -.10788925177498064213333333333333e-29_C_DOUBLE, +.12811883993017002666666666666666e-31_C_DOUBLE /)
Referenced by erf_erfc().
       real(C_DOUBLE),dimension(21),private ::  erfcs = (/             &
  -.49046121234691808039984544033376e-1_c_double,  -.14226120510371364237824741899631e+0_c_double,        &
  +.10035582187599795575754676712933e-1_c_double,  -.57687646997674847650827025509167e-3_c_double,        &
  +.27419931252196061034422160791471e-4_c_double,  -.11043175507344507604135381295905e-5_c_double,        &
  +.38488755420345036949961311498174e-7_c_double,  -.11808582533875466969631751801581e-8_c_double,        &
  +.32334215826050909646402930953354e-10_c_double, -.79910159470045487581607374708595e-12_c_double,       &
  +.17990725113961455611967245486634e-13_c_double, -.37186354878186926382316828209493e-15_c_double,       &
  +.71035990037142529711689908394666e-17_c_double, -.12612455119155225832495424853333e-18_c_double,       &
  +.20916406941769294369170500266666e-20_c_double, -.32539731029314072982364160000000e-22_c_double,       &
  +.47668672097976748332373333333333e-24_c_double, -.65980120782851343155199999999999e-26_c_double,       &
  +.86550114699637626197333333333333e-28_c_double, -.10788925177498064213333333333333e-29_c_double,       &
  +.12811883993017002666666666666666e-31_c_double       /)
real(c_double), dimension(49), private erc2cs = (/ -.6960134660230950112739150826197e-1_C_DOUBLE, -.4110133936262089348982212084666e-1_C_DOUBLE, +.3914495866689626881561143705244e-2_C_DOUBLE, -.4906395650548979161280935450774e-3_C_DOUBLE, +.7157479001377036380760894141825e-4_C_DOUBLE, -.1153071634131232833808232847912e-4_C_DOUBLE, +.1994670590201997635052314867709e-5_C_DOUBLE, -.3642666471599222873936118430711e-6_C_DOUBLE, +.6944372610005012589931277214633e-7_C_DOUBLE, -.1371220902104366019534605141210e-7_C_DOUBLE, +.2788389661007137131963860348087e-8_C_DOUBLE, -.5814164724331161551864791050316e-9_C_DOUBLE, +.1238920491752753181180168817950e-9_C_DOUBLE, -.2690639145306743432390424937889e-10_C_DOUBLE, +.5942614350847910982444709683840e-11_C_DOUBLE, -.1332386735758119579287754420570e-11_C_DOUBLE, +.3028046806177132017173697243304e-12_C_DOUBLE, -.6966648814941032588795867588954e-13_C_DOUBLE, +.1620854541053922969812893227628e-13_C_DOUBLE, -.3809934465250491999876913057729e-14_C_DOUBLE, +.9040487815978831149368971012975e-15_C_DOUBLE, -.2164006195089607347809812047003e-15_C_DOUBLE, +.5222102233995854984607980244172e-16_C_DOUBLE, -.1269729602364555336372415527780e-16_C_DOUBLE, +.3109145504276197583836227412951e-17_C_DOUBLE, -.7663762920320385524009566714811e-18_C_DOUBLE, +.1900819251362745202536929733290e-18_C_DOUBLE, -.4742207279069039545225655999965e-19_C_DOUBLE, +.1189649200076528382880683078451e-19_C_DOUBLE, -.3000035590325780256845271313066e-20_C_DOUBLE, +.7602993453043246173019385277098e-21_C_DOUBLE, -.1935909447606872881569811049130e-21_C_DOUBLE, +.4951399124773337881000042386773e-22_C_DOUBLE, -.1271807481336371879608621989888e-22_C_DOUBLE, +.3280049600469513043315841652053e-23_C_DOUBLE, -.8492320176822896568924792422399e-24_C_DOUBLE, +.2206917892807560223519879987199e-24_C_DOUBLE, -.5755617245696528498312819507199e-25_C_DOUBLE, +.1506191533639234250354144051199e-25_C_DOUBLE, -.3954502959018796953104285695999e-26_C_DOUBLE, +.1041529704151500979984645051733e-26_C_DOUBLE, -.2751487795278765079450178901333e-27_C_DOUBLE, +.7290058205497557408997703680000e-28_C_DOUBLE, -.1936939645915947804077501098666e-28_C_DOUBLE, +.5160357112051487298370054826666e-29_C_DOUBLE, -.1378419322193094099389644800000e-29_C_DOUBLE, +.3691326793107069042251093333333e-30_C_DOUBLE, -.9909389590624365420653226666666e-31_C_DOUBLE, +.2666491705195388413323946666666e-31_C_DOUBLE /)
Referenced by erf_erfc().
       real(C_DOUBLE),dimension(49),private ::  erc2cs = (/            &
  -.6960134660230950112739150826197e-1_c_double,  -.4110133936262089348982212084666e-1_c_double,         &
  +.3914495866689626881561143705244e-2_c_double,  -.4906395650548979161280935450774e-3_c_double,         &
  +.7157479001377036380760894141825e-4_c_double,  -.1153071634131232833808232847912e-4_c_double,         &
  +.1994670590201997635052314867709e-5_c_double,  -.3642666471599222873936118430711e-6_c_double,         &
  +.6944372610005012589931277214633e-7_c_double,  -.1371220902104366019534605141210e-7_c_double,         &
  +.2788389661007137131963860348087e-8_c_double,  -.5814164724331161551864791050316e-9_c_double,         &
  +.1238920491752753181180168817950e-9_c_double,  -.2690639145306743432390424937889e-10_c_double,        &
  +.5942614350847910982444709683840e-11_c_double, -.1332386735758119579287754420570e-11_c_double,        &
  +.3028046806177132017173697243304e-12_c_double, -.6966648814941032588795867588954e-13_c_double,        &
  +.1620854541053922969812893227628e-13_c_double, -.3809934465250491999876913057729e-14_c_double,        &
  +.9040487815978831149368971012975e-15_c_double, -.2164006195089607347809812047003e-15_c_double,        &
  +.5222102233995854984607980244172e-16_c_double, -.1269729602364555336372415527780e-16_c_double,        &
  +.3109145504276197583836227412951e-17_c_double, -.7663762920320385524009566714811e-18_c_double,        &
  +.1900819251362745202536929733290e-18_c_double, -.4742207279069039545225655999965e-19_c_double,        &
  +.1189649200076528382880683078451e-19_c_double, -.3000035590325780256845271313066e-20_c_double,        &
  +.7602993453043246173019385277098e-21_c_double, -.1935909447606872881569811049130e-21_c_double,        &
  +.4951399124773337881000042386773e-22_c_double, -.1271807481336371879608621989888e-22_c_double,        &
  +.3280049600469513043315841652053e-23_c_double, -.8492320176822896568924792422399e-24_c_double,        &
  +.2206917892807560223519879987199e-24_c_double, -.5755617245696528498312819507199e-25_c_double,        &
  +.1506191533639234250354144051199e-25_c_double, -.3954502959018796953104285695999e-26_c_double,        &
  +.1041529704151500979984645051733e-26_c_double, -.2751487795278765079450178901333e-27_c_double,        &
  +.7290058205497557408997703680000e-28_c_double, -.1936939645915947804077501098666e-28_c_double,        &
  +.5160357112051487298370054826666e-29_c_double, -.1378419322193094099389644800000e-29_c_double,        &
  +.3691326793107069042251093333333e-30_c_double, -.9909389590624365420653226666666e-31_c_double,        &
  +.2666491705195388413323946666666e-31_c_double        /)
real(c_double), dimension(59), private erfccs = (/ +.715179310202924774503697709496e-1_C_DOUBLE, -.265324343376067157558893386681e-1_C_DOUBLE, +.171115397792085588332699194606e-2_C_DOUBLE, -.163751663458517884163746404749e-3_C_DOUBLE, +.198712935005520364995974806758e-4_C_DOUBLE, -.284371241276655508750175183152e-5_C_DOUBLE, +.460616130896313036969379968464e-6_C_DOUBLE, -.822775302587920842057766536366e-7_C_DOUBLE, +.159214187277090112989358340826e-7_C_DOUBLE, -.329507136225284321486631665072e-8_C_DOUBLE, +.722343976040055546581261153890e-9_C_DOUBLE, -.166485581339872959344695966886e-9_C_DOUBLE, +.401039258823766482077671768814e-10_C_DOUBLE, -.100481621442573113272170176283e-10_C_DOUBLE, +.260827591330033380859341009439e-11_C_DOUBLE, -.699111056040402486557697812476e-12_C_DOUBLE, +.192949233326170708624205749803e-12_C_DOUBLE, -.547013118875433106490125085271e-13_C_DOUBLE, +.158966330976269744839084032762e-13_C_DOUBLE, -.472689398019755483920369584290e-14_C_DOUBLE, +.143587337678498478672873997840e-14_C_DOUBLE, -.444951056181735839417250062829e-15_C_DOUBLE, +.140481088476823343737305537466e-15_C_DOUBLE, -.451381838776421089625963281623e-16_C_DOUBLE, +.147452154104513307787018713262e-16_C_DOUBLE, -.489262140694577615436841552532e-17_C_DOUBLE, +.164761214141064673895301522827e-17_C_DOUBLE, -.562681717632940809299928521323e-18_C_DOUBLE, +.194744338223207851429197867821e-18_C_DOUBLE, -.682630564294842072956664144723e-19_C_DOUBLE, +.242198888729864924018301125438e-19_C_DOUBLE, -.869341413350307042563800861857e-20_C_DOUBLE, +.315518034622808557122363401262e-20_C_DOUBLE, -.115737232404960874261239486742e-20_C_DOUBLE, +.428894716160565394623737097442e-21_C_DOUBLE, -.160503074205761685005737770964e-21_C_DOUBLE, +.606329875745380264495069923027e-22_C_DOUBLE, -.231140425169795849098840801367e-22_C_DOUBLE, +.888877854066188552554702955697e-23_C_DOUBLE, -.344726057665137652230718495566e-23_C_DOUBLE, +.134786546020696506827582774181e-23_C_DOUBLE, -.531179407112502173645873201807e-24_C_DOUBLE, +.210934105861978316828954734537e-24_C_DOUBLE, -.843836558792378911598133256738e-25_C_DOUBLE, +.339998252494520890627359576337e-25_C_DOUBLE, -.137945238807324209002238377110e-25_C_DOUBLE, +.563449031183325261513392634811e-26_C_DOUBLE, -.231649043447706544823427752700e-26_C_DOUBLE, +.958446284460181015263158381226e-27_C_DOUBLE, -.399072288033010972624224850193e-27_C_DOUBLE, +.167212922594447736017228709669e-27_C_DOUBLE, -.704599152276601385638803782587e-28_C_DOUBLE, +.297976840286420635412357989444e-28_C_DOUBLE, -.126252246646061929722422632994e-28_C_DOUBLE, +.539543870454248793985299653154e-29_C_DOUBLE, -.238099288253145918675346190062e-29_C_DOUBLE, +.109905283010276157359726683750e-29_C_DOUBLE, -.486771374164496572732518677435e-30_C_DOUBLE, +.152587726411035756763200828211e-30_C_DOUBLE /)
Referenced by erf_erfc().
       real(C_DOUBLE),dimension(59),private ::  erfccs = (/            &
  +.715179310202924774503697709496e-1_c_double,  -.265324343376067157558893386681e-1_c_double,          &
  +.171115397792085588332699194606e-2_c_double,  -.163751663458517884163746404749e-3_c_double,          &
  +.198712935005520364995974806758e-4_c_double,  -.284371241276655508750175183152e-5_c_double,          &
  +.460616130896313036969379968464e-6_c_double,  -.822775302587920842057766536366e-7_c_double,          &
  +.159214187277090112989358340826e-7_c_double,  -.329507136225284321486631665072e-8_c_double,          &
  +.722343976040055546581261153890e-9_c_double,  -.166485581339872959344695966886e-9_c_double,          &
  +.401039258823766482077671768814e-10_c_double, -.100481621442573113272170176283e-10_c_double,         &
  +.260827591330033380859341009439e-11_c_double, -.699111056040402486557697812476e-12_c_double,         &
  +.192949233326170708624205749803e-12_c_double, -.547013118875433106490125085271e-13_c_double,         &
  +.158966330976269744839084032762e-13_c_double, -.472689398019755483920369584290e-14_c_double,         &
  +.143587337678498478672873997840e-14_c_double, -.444951056181735839417250062829e-15_c_double,         &
  +.140481088476823343737305537466e-15_c_double, -.451381838776421089625963281623e-16_c_double,         &
  +.147452154104513307787018713262e-16_c_double, -.489262140694577615436841552532e-17_c_double,         &
  +.164761214141064673895301522827e-17_c_double, -.562681717632940809299928521323e-18_c_double,         &
  +.194744338223207851429197867821e-18_c_double, -.682630564294842072956664144723e-19_c_double,         &
  +.242198888729864924018301125438e-19_c_double, -.869341413350307042563800861857e-20_c_double,         &
  +.315518034622808557122363401262e-20_c_double, -.115737232404960874261239486742e-20_c_double,         &
  +.428894716160565394623737097442e-21_c_double, -.160503074205761685005737770964e-21_c_double,         &
  +.606329875745380264495069923027e-22_c_double, -.231140425169795849098840801367e-22_c_double,         &
  +.888877854066188552554702955697e-23_c_double, -.344726057665137652230718495566e-23_c_double,         &
  +.134786546020696506827582774181e-23_c_double, -.531179407112502173645873201807e-24_c_double,         &
  +.210934105861978316828954734537e-24_c_double, -.843836558792378911598133256738e-25_c_double,         &
  +.339998252494520890627359576337e-25_c_double, -.137945238807324209002238377110e-25_c_double,         &
  +.563449031183325261513392634811e-26_c_double, -.231649043447706544823427752700e-26_c_double,         &
  +.958446284460181015263158381226e-27_c_double, -.399072288033010972624224850193e-27_c_double,         &
  +.167212922594447736017228709669e-27_c_double, -.704599152276601385638803782587e-28_c_double,         &
  +.297976840286420635412357989444e-28_c_double, -.126252246646061929722422632994e-28_c_double,         &
  +.539543870454248793985299653154e-29_c_double, -.238099288253145918675346190062e-29_c_double,         &
  +.109905283010276157359726683750e-29_c_double, -.486771374164496572732518677435e-30_c_double,         &
  +.152587726411035756763200828211e-30_c_double         /)
real(c_double), private sqrtpi = 1.7724538509055160272981674833411_C_DOUBLE
Referenced by erf_erfc().
       real(C_DOUBLE),private ::                                       &
                sqrtpi =  1.7724538509055160272981674833411_c_double,  &
                  xsml = -6.01368735695764033977e+00_c_double,         &
                  xmax =  2.65332996850925972865e+01_c_double,         &
                 sqeps =  1.49011611938476562500e-08_c_double
real(c_double), private xsml = -6.01368735695764033977e+00_C_DOUBLE
Referenced by erf_erfc().
real(c_double), private xmax = 2.65332996850925972865e+01_C_DOUBLE
Referenced by erf_erfc().
real(c_double), private sqeps = 1.49011611938476562500e-08_C_DOUBLE
Referenced by erf_erfc().
real(c_double), private x
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp, and Manager/mzd/tests/tstParallelDepletion.cpp.
Referenced by double_erf(), double_erfc(), DiscreteSpectrum::energies(), erf_erfc(), DiscreteSpectrum::intensities(), Origen::printConcentrations_csv(), real_erf(), real_erfc(), GridData_TransitionCoeff::setx(), Concentrations::sum_hm(), Origen::tabulateMaterialFission(), Origen::tabulateMaterialIsotopics(), Origen::tabulateMaterialLoss(), TEST(), and origen_neutron::totaln().
       real(C_DOUBLE),private :: x, y, yy, er, ec
real(c_double), private y
Examples:
Core/dc/tests/tstTime.cpp.
Referenced by YieldParent::add_data(), erf_erfc(), and TEST().
real(c_double), private yy
Referenced by erf_erfc().
real(c_double), private er
Examples:
Core/re/tests/tstEmissionResource.cpp.
Referenced by double_erf(), EmissionResource::energy_range(), DiscreteSpectrum::energy_range(), Spectrum::energy_range(), erf_erfc(), real_erf(), and TEST().
real(c_double), private ec
Referenced by double_erfc(), erf_erfc(), and real_erfc().
integer, private nterf =12
Referenced by erf_erfc().
       integer,private :: nterf=12, nterc2=24, nterfc=20
integer, private nterc2 =24
Referenced by erf_erfc().
integer, private nterfc =20
Referenced by erf_erfc().