ORIGEN API: YieldResourceIO_ampx Class Reference
YieldResourceIO_ampx Class Reference
#include <YieldResourceIO_ampx.h>
Public Member Functions
bool read (YieldResource &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const YieldResource &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Member Function Documentation
bool read (YieldResource & obj, std::istream & stream, ScaleUtils::IO::DB opts)
basic file definition: PART 1: FISSIONABLE NUCLIDE DEFINITION ZA - NUMBER_OF_DATA_SETS - - - PART 2: DATA SET DEFINITION ENERGY - - INTERPOLATION_FLAG - NUM_FISSION_PRODUCTS PART 3: FISSION PRODUCT YIELDS FP_ZA1 FP_YLD1 FP_ZA2 FP_YLD2 FP_ZA3 FP_YLD3 (3 pairs per line) PART 4: LINE OF ZEROES PART 5: LINE OF ZEROES
References YieldResource::add_fissionable(), and CUMULATIVE.
bool write (const YieldResource & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
References CUMULATIVE, YieldParent::data_at(), YieldParent::energy_at(), YieldResource::fissionable_at(), YieldParent::fp_index(), YieldParent::get_fp_ids(), YieldParent::id(), YieldParent::interp_method(), YieldParent::num_energies(), YieldResource::num_fissionables(), YieldData::num_yields(), and YieldData::yield_at().
The documentation for this class was generated from the following files:
Core/io/YieldResourceIO_ampx.h
Core/io/YieldResourceIO_ampx.cpp