ORIGEN API: DecayChannel Class Reference
DecayChannel Class Reference
#include <DecayResource.h>
Public Member Functions
DecayChannel ()
~DecayChannel ()
void list_residual_ids (Vec_Int &daughter_ids) const
void get_yield_map (Vec_Int &daughter_ids, std::vector< double > &yields) const
double get_yield (const int id) const
double get_branch_ratio () const
void set_branch_ratio (double value)
int num_residuals () const
int get_yield_type () const
void set_yield_type (int value)
const std::map< int, double > & get_const_yield_map () const
std::map< int, double > & get_yield_map ()
Private Attributes
double branch_ratio
int yield_type
std::map< int, double > yield_map
Detailed Description
Examples:
Core/io/tests/tstDecayResourceIO.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Constructor & Destructor Documentation
DecayChannel ()
     : branch_ratio( 0.0 ), yield_type( DecayResource::MISSING_YIELDS )
 {
 }
~DecayChannel ()
 {}
Member Function Documentation
void list_residual_ids (Vec_Int & daughter_ids) const
References DecayChannel::yield_map.
 {
     list.clear();
     std::map<int, double>::const_iterator it;
     for( it = yield_map.begin(); it != yield_map.end(); it++ )
     {
         list.push_back( it->first );
     }
 }  // DecayChannel::list_residual_ids
void get_yield_map (Vec_Int & daughter_ids, std::vector< double > & yields) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References DecayChannel::yield_map.
Referenced by DecayResourceIO_cimg::read(), and TEST_F().
 {
     yield_ids.clear();
     yields.clear();
     std::map<int, double>::const_iterator it;
     for( it = yield_map.begin(); it != yield_map.end(); it++ )
     {
         yield_ids.push_back( it->first );
         yields.push_back( it->second );
     }
 }  // DecayChannel::get_yield_map
double get_yield (const int id) const
References DecayChannel::yield_map.
 {
     std::map<int, double>::const_iterator it = yield_map.find( id );
     if( it == yield_map.end() )
     {
         return 0.0;
     }
     else
     {
         return it->second;
     }
 }
double get_branch_ratio () const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References DecayChannel::branch_ratio.
Referenced by DecayResource::check_consistency(), TransitionSystemAdapter_DecayResource::extend(), Origen::printDecayTable(), DecayResourceIO_cimg::read(), TEST_F(), and DecayResource::to_json().
 {
     return branch_ratio;
 }  // DecayChannel::get_branch_ratio
void set_branch_ratio (double value)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References DecayChannel::branch_ratio.
Referenced by DecayResourceIO_cimg::read(), and TEST_F().
 { branch_ratio = value; }
int num_residuals () const
References DecayChannel::yield_map.
 { return yield_map.size(); }
int get_yield_type () const
References DecayChannel::yield_type.
Referenced by DecayResource::check_consistency(), and DecayResource::to_json().
 { return yield_type; }
void set_yield_type (int value)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References DecayChannel::yield_type.
Referenced by DecayResourceIO_cimg::read(), and TEST_F().
 {
     yield_type = value;
 }  // DecayChannel::set_yield_type
const std::map< int, double > & get_const_yield_map () const
References DecayChannel::yield_map.
Referenced by DecayResource::check_consistency(), TransitionSystemAdapter_DecayResource::extend(), Origen::printDecayTable(), and DecayResource::to_json().
 {
     return yield_map;
 }
std::map< int, double > & get_yield_map ()
References DecayChannel::yield_map.
 { return yield_map; }
Member Data Documentation
double branch_ratio private
Referenced by DecayChannel::get_branch_ratio(), and DecayChannel::set_branch_ratio().
int yield_type private
Referenced by DecayChannel::get_yield_type(), and DecayChannel::set_yield_type().
std::map<int, double> yield_map private
Referenced by DecayChannel::get_const_yield_map(), DecayChannel::get_yield(), DecayChannel::get_yield_map(), DecayChannel::list_residual_ids(), and DecayChannel::num_residuals().
The documentation for this class was generated from the following files:
Core/re/DecayResource.h
Core/re/DecayResource.cpp