ORIGEN API: Species_Gen Class Reference
Species_Gen Class Reference
#include <Species_Gen.h>
General-purpose implementation of the Species interface.
Public Types
typedef SP_Species SP
strong pointer
typedef WP_Species WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Species>>
See Origen::Species for details.
int charge_number () const
void get_charge_number (int &charge_number) const
void set_charge_number (int charge_number)
bool has_initialized_charge_number () const
int mass_number () const
void get_mass_number (int &mass_number) const
void set_mass_number (int mass_number)
bool has_initialized_mass_number () const
double mass () const
void get_mass (double &mass) const
void set_mass (double mass)
bool has_initialized_mass () const
Public Member Functions
Species_Gen ()
Species_Gen (int charge_number, int mass_number)
Species_Gen (int charge_number, int mass_number, double mass)
virtual ~Species_Gen ()
Private Member Functions
virtual int charge_number_impl () const
virtual void get_charge_number_impl (int &charge_number) const
virtual void set_charge_number_impl (int charge_number)
virtual int mass_number_impl () const
virtual void get_mass_number_impl (int &mass_number) const
virtual void set_mass_number_impl (int mass_number)
virtual double mass_impl () const
virtual void get_mass_impl (double &mass) const
virtual void set_mass_impl (double mass)
Private Attributes
int b_charge_number
int b_mass_number
double b_mass
Detailed Description
General-purpose implementation of the Species interface.
See also
Origen::ChannelType_Gen
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef SP_Species SP inherited
strong pointer
typedef WP_Species WP inherited
weak pointer
Constructor & Destructor Documentation
Species_Gen ()
     : b_charge_number( BAD_INT ), b_mass_number( BAD_INT ), b_mass( BAD_DOUBLE )
 {
 }
Species_Gen (int charge_number, int mass_number)
     : b_charge_number( charge_number )
     , b_mass_number( mass_number )
     , b_mass( BAD_DOUBLE )
 {
 }
Species_Gen (int charge_number, int mass_number, double mass)
     : b_charge_number( charge_number )
     , b_mass_number( mass_number )
     , b_mass( mass )
 {
 }
~Species_Gen () virtual
 {}
Member Function Documentation
int charge_number_impl () const private virtual
Implements Species.
References Species_Gen::b_charge_number.
 { return b_charge_number; }
void get_charge_number_impl (int & charge_number) const private virtual
Reimplemented from Species.
References Species_Gen::b_charge_number.
 {
     charge_number = b_charge_number;
 }
void set_charge_number_impl (int charge_number) private virtual
Reimplemented from Species.
References Species_Gen::b_charge_number, and Species::charge_number().
 {
     b_charge_number = charge_number;
 }
int mass_number_impl () const private virtual
Implements Species.
References Species_Gen::b_mass_number.
 { return b_mass_number; }
void get_mass_number_impl (int & mass_number) const private virtual
Reimplemented from Species.
References Species_Gen::b_mass_number.
 {
     mass_number = b_mass_number;
 }
void set_mass_number_impl (int mass_number) private virtual
Reimplemented from Species.
References Species_Gen::b_mass_number, and Species::mass_number().
 {
     b_mass_number = mass_number;
 }
double mass_impl () const private virtual
Implements Species.
References Species_Gen::b_mass.
 { return b_mass; }
void get_mass_impl (double & mass) const private virtual
Reimplemented from Species.
References Species_Gen::b_mass.
 { mass = b_mass; }
void set_mass_impl (double mass) private virtual
Reimplemented from Species.
References Species_Gen::b_mass, and Species::mass().
 { b_mass = mass; }
int charge_number () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_charge_number_impl(), and TEST().
 { return charge_number_impl(); }
void get_charge_number (int & charge_number) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
 {
     get_charge_number_impl( charge_number );
 }
void set_charge_number (int charge_number) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
 {
     set_charge_number_impl( charge_number );
 }
bool has_initialized_charge_number () const inherited
 {
     return has_initialized_charge_number_impl();
 }
int mass_number () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_number_impl(), and TEST().
 { return mass_number_impl(); }
void get_mass_number (int & mass_number) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
 {
     get_mass_number_impl( mass_number );
 }
void set_mass_number (int mass_number) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
 {
     set_mass_number_impl( mass_number );
 }
bool has_initialized_mass_number () const inherited
 {
     return has_initialized_mass_number_impl();
 }
double mass () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_impl(), and TEST().
 { return mass_impl(); }
void get_mass (double & mass) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
 { get_mass_impl( mass ); }
void set_mass (double mass) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
 { set_mass_impl( mass ); }
bool has_initialized_mass () const inherited
 {
     return has_initialized_mass_impl();
 }
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
int b_charge_number private
Referenced by Species_Gen::charge_number_impl(), Species_Gen::get_charge_number_impl(), and Species_Gen::set_charge_number_impl().
int b_mass_number private
Referenced by Species_Gen::get_mass_number_impl(), Species_Gen::mass_number_impl(), and Species_Gen::set_mass_number_impl().
double b_mass private
Referenced by Species_Gen::get_mass_impl(), Species_Gen::mass_impl(), and Species_Gen::set_mass_impl().
The documentation for this class was generated from the following files:
Core/ts/Species_Gen.h
Core/ts/Species_Gen.cpp