ORIGEN API: Checkable Class Reference
Checkable Class Reference
#include <Checkable.h>
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
Public Member Functions
Checkable ()
virtual ~Checkable ()
Protected Member Functions
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual bool is_initialized_impl () const
useful to chain
virtual Scale::Json::Value to_json_impl () const
useful to chain
Private Member Functions
virtual std::string name_impl () const
virtual void get_name_impl (std::string &name) const
virtual void set_name_impl (std::string name)
virtual int id_impl () const
virtual void get_id_impl (int &id) const
virtual void set_id_impl (int id)
virtual bool has_initialized_id_impl () const
virtual std::string to_string_impl () const
virtual bool good_impl () const
Detailed Description
An interface for ORIGEN objects that should have quality control.
In a lot of cases with data structures you want to be able to
identify it with an integer id,
identify it with a string,
check if it has been initialized,
print it to a string,
print it to a special text structure, and finally
check if its contents make sense.
Origen::Checkable defines such an interface.
Constructor & Destructor Documentation
Checkable () inline
virtual ~Checkable () inline virtual
Member Function Documentation
std::string name () const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name)
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id)
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const
bool good (Vec_Str & errors) const
bool is_initialized () const
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const
std::string name_impl () const private virtual
Reimplemented in NullField, NeutrinoField, Nuclide, Channel, PositronField, ChannelType, ElectronField, Null, AlphaField, Neutrino, HelionField, Positron, Species, Transition, Electron, TritonField, Field, Alpha, Helion, DeuteronField, Triton, ProtonField, Deuteron, Proton, NeutronField, and Neutron.
void get_name_impl (std::string & name) const private virtual
void set_name_impl (std::string name) private virtual
int id_impl () const private virtual
Reimplemented in NullField, NeutrinoField, Nuclide, Channel, PositronField, ChannelType, ElectronField, Null, AlphaField, Neutrino, HelionField, Positron, Species, Transition, Electron, TritonField, Field, Alpha, Helion, DeuteronField, Triton, ProtonField, Deuteron, Proton, NeutronField, and Neutron.
References Origen::BAD_INT.
void get_id_impl (int & id) const private virtual
void set_id_impl (int id) private virtual
bool has_initialized_id_impl () const private virtual
References Origen::BAD_INT.
std::string to_string_impl () const private virtual
bool good_impl () const private virtual
bool good_impl (Vec_Str & errors) const protected virtual
useful to chain
Reimplemented in Nuclide, Channel, Null, Neutrino, Positron, Species, Transition, Electron, Field, Alpha, ChannelType_Reac, ChannelType_Decay, ChannelType_Fiss, Helion, TransitionSystem_Gen, Triton, Deuteron, Proton, and Neutron.
References ORIGEN_CHECKABLE_ERROR.
bool is_initialized_impl () const protected virtual
useful to chain
Reimplemented in Nuclide, Channel, ChannelType, Species, Transition, Field, and TransitionSystem_Gen.
Json::Value to_json_impl () const protected virtual
useful to chain
Reimplemented in Nuclide, Channel, TransitionSystem, ChannelType, Species, Transition, and Field.
The documentation for this class was generated from the following files:
Core/ts/Checkable.h
Core/ts/Checkable.cpp