ORIGEN API: origen_casewrapper_m Module Reference
origen_casewrapper_m Module Reference
Origen_CaseWrapper_M Fortran module provides class Origen_CaseWrapper .
Data Types
type origen_casewrapper
Functions/Subroutines
subroutine flip_time (nstep, time, flux)
Invert time steps and flux array (for the adjoint calculation)
Detailed Description
Origen_CaseWrapper_M Fortran module provides class Origen_CaseWrapper .
use origen_casewrapper_m
type(origen_casewrapper) :: casew
Function/Subroutine Documentation
subroutine origen_casewrapper_m::flip_time (integer, intent(in) nstep, real(c_double), dimension(0:nstep), intent(inout) time, real(c_double), dimension(1:nstep), intent(inout) flux)
Invert time steps and flux array (for the adjoint calculation)
Parameters
[in] nstep number of steps
[in,out] time time array
[in,out] flux flux array
initial time
References depletion::deplete(), origen_iofunctions_m::origen_appendstateset(), origen_definitions_m::origen_concentrationunit_gatoms, origen_iofunctions_m::origen_loadstateset(), and origen_iofunctions_m::rstop().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> number of steps
     integer, intent(in) :: nstep
     !> time array
     real(C_DOUBLE), intent(inout) :: time(0:nstep)
     !> flux array
     real(C_DOUBLE), intent(inout) :: flux(1:nstep)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> initial time
     real(C_DOUBLE) :: tmo
     tmo = time(0)
     call flip(nstep + 1, time)
     time(:) =  time(:) - time(0)
     time(:) = -time(:)
     time(:) =  time(:) + tmo
     call flip(nstep, flux)