ORIGEN API: ConcentrationConverter Class Reference
ConcentrationConverter Class Reference
#include <ConcentrationConverter.h>
Public Member Functions
double convert_to (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val) const
returns uninitialized double if cannot convert
double convert_to (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const
returns uninitialized double if cannot convert
bool convertible_to (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold) const
can convert to
SCP_NuclideResource nuclide_resource () const
return shared (read-only) nuclide_resource resource \
bool has_nuclide_resource () const
whether this instantiation of class has the nuclide_resource resource \
void set_nuclide_resource (SCP_NuclideResource)
set a new shared (read-only) nuclide_resource resource (non-const version) \
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
void set_decay_resource (SCP_DecayResource)
set a new shared (read-only) decay_resource resource (non-const version) \
Protected Attributes
SCP_NuclideResource r_nuclide_resource
SCP_DecayResource r_decay_resource
Private Member Functions
double mol2n (ConcentrationUnit, int, double) const
double mol2m (ConcentrationUnit, int, double) const
double mol2d (ConcentrationUnit, int, double) const
double n2n (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double n2m (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double n2d (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double d2n (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double d2m (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double d2d (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double m2n (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double m2m (ConcentrationUnit, int, ConcentrationUnit, double, double) const
double m2d (ConcentrationUnit, int, ConcentrationUnit, double, double) const
Detailed Description
Examples:
tstConcentrationConverter.cpp.
Member Function Documentation
double convert_to (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val) const
returns uninitialized double if cannot convert
Examples:
tstConcentrationConverter.cpp.
References Origen::needsVolumeToConvert().
Referenced by Concentrations::convert_units(), ConcentrationConverter::convertible_to(), and TEST().
 {
     Require( !needsVolumeToConvert( unew, uold ) );
     return convert_to( unew, izzzaaa, uold, val, 1.0 );
 }
double convert_to (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const
returns uninitialized double if cannot convert
References Origen::BAD_DOUBLE, ConcentrationConverter::d2d(), ConcentrationConverter::d2m(), ConcentrationConverter::d2n(), Origen::isDecayUnit(), Origen::isMassUnit(), Origen::isNumberUnit(), Origen::isReactionUnit(), Origen::isSpectrumUnit(), ConcentrationConverter::m2d(), ConcentrationConverter::m2m(), ConcentrationConverter::m2n(), ConcentrationConverter::n2d(), ConcentrationConverter::n2m(), and ConcentrationConverter::n2n().
 {
     // don't care about zeros
     if( val == 0.0 ) return 0.0;
     // always allow this
     if( uold == unew ) return val;
     // conversion matrix (see Polaris/FrontEnd/TimeUnit for better ways)
     if( isNumberUnit( uold ) )
     {
         if( isNumberUnit( unew ) )
             return n2n( unew, izzzaaa, uold, val, volume );
         if( isMassUnit( unew ) ) return n2m( unew, izzzaaa, uold, val, volume );
         if( isDecayUnit( unew ) )
             return n2d( unew, izzzaaa, uold, val, volume );
     }
     else if( isMassUnit( uold ) )
     {
         if( isMassUnit( unew ) ) return m2m( unew, izzzaaa, uold, val, volume );
         if( isNumberUnit( unew ) )
             return m2n( unew, izzzaaa, uold, val, volume );
         if( isDecayUnit( unew ) )
             return m2d( unew, izzzaaa, uold, val, volume );
     }
     else if( isDecayUnit( uold ) )
     {
         if( isDecayUnit( unew ) )
             return d2d( unew, izzzaaa, uold, val, volume );
         if( isNumberUnit( unew ) )
             return d2n( unew, izzzaaa, uold, val, volume );
         if( isMassUnit( unew ) ) return d2m( unew, izzzaaa, uold, val, volume );
     }
     // If we get to here, we can't do the conversion. Let's check to see that
     // it is with the Spectrum or Reaction unit categories.
     Ensure( isSpectrumUnit( uold ) || isReactionUnit( uold ) );
     Ensure( isSpectrumUnit( unew ) || isReactionUnit( unew ) );
     return BAD_DOUBLE;
 }
bool convertible_to (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold) const
can convert to
Examples:
tstConcentrationConverter.cpp.
References Origen::BAD_DOUBLE, and ConcentrationConverter::convert_to().
Referenced by TEST().
 {
     double val = 1.0;
     double volume = 1.0;
     return convert_to( unew, izzzaaa, uold, val, volume ) != BAD_DOUBLE;
 }
SCP_NuclideResource nuclide_resource () const
return shared (read-only) nuclide_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_nuclide_resource () const
whether this instantiation of class has the nuclide_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Referenced by ConcentrationConverter::mol2m().
void set_nuclide_resource (SCP_NuclideResource nuclide_resource)
set a new shared (read-only) nuclide_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Referenced by Concentrations::convert_units().
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Referenced by ConcentrationConverter::mol2d().
void set_decay_resource (SCP_DecayResource decay_resource)
set a new shared (read-only) decay_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Examples:
tstConcentrationConverter.cpp.
Referenced by Concentrations::convert_units(), and TEST().
double mol2n (ConcentrationUnit u, int izzzaaa, double volume) const private
References Origen::ATOMS_B_CM, Origen::BAD_DOUBLE, Origen::CM_2_BARN, Origen::GATOMS, Origen::isNumberUnit(), and Origen::MOLES.
 {
     Require( isNumberUnit( u ) );
     switch( u )
     {
         case MOLES:
             return 1.0;
         case GATOMS:
             return 1.0;
         case ATOMS_B_CM:
             return 1e-24 * AVOGADRO / volume;
         case CM_2_BARN:
             return 1e-24 * AVOGADRO;
         default:
             throw nemesis::assertion(
                 "this mole conversion restricted to numbers" );
     }
     return BAD_DOUBLE;
 }
double mol2m (ConcentrationUnit u, int izzzaaa, double volume) const private
References Origen::BAD_DOUBLE, Origen::GPERCM_3, Origen::GRAMS, ConcentrationConverter::has_nuclide_resource(), Origen::isMassUnit(), Origen::KILOGRAMS, and ConcentrationConverter::r_nuclide_resource.
 {
     Require( isMassUnit( u ) );
     // if we dont have any data then we just use mass number
     double m = izzzaaa % 1000;
     if( has_nuclide_resource() )
     {
         auto it = r_nuclide_resource->parent_map.find( izzzaaa );
         if( it != r_nuclide_resource->parent_map.end() )
         {
             m = it->second.mass;
         }
     }
     Check( m > 0.0 );
     switch( u )
     {
         case GRAMS:
             return m;
         case KILOGRAMS:
             return m / 1000.;
         case GPERCM_3:
             Check( volume > 0.0 );
             return m / volume;
         default:
             throw nemesis::assertion(
                 "this mole conversion restricted to masses" );
     }
     return BAD_DOUBLE;
 }
double mol2d (ConcentrationUnit u, int izzzaaa, double volume) const private
References Origen::AIRM_3, Origen::BAD_DOUBLE, Origen::BECQUERELS, Origen::CURIES, Origen::GAMMEVS, Origen::GAMWATTS, DecayParent::get_decay_constant(), DecayParent::get_q_fraction_from_photons(), DecayParent::get_rcg_for_air(), DecayParent::get_rcg_for_water(), DecayParent::get_recoverable_energy_value(), Origen::H2OM_3, ConcentrationConverter::has_decay_resource(), Origen::isDecayUnit(), Origen::MEVS, ConcentrationConverter::r_decay_resource, and Origen::WATTS.
 {
     Require( isDecayUnit( u ) );
     // if we dont have any data then we wont' try
     if( !has_decay_resource() )
     {
         jDebugTaggedLine( "no decay resource" );
         return BAD_DOUBLE;
     }
     // nuclide doesn't have decay data then all will be zero below
     if( !r_decay_resource->is_present( izzzaaa ) )
     {
         jDebugTaggedLine( "no decay data for izzzaaa=" << izzzaaa );
         return 0;
     }
     // get data
     const DecayParent* p = r_decay_resource->get_parent_ptr( izzzaaa );
     Check( p != nullptr );
     double lambda = p->get_decay_constant();
     double q = p->get_recoverable_energy_value();
     double fg = p->get_q_fraction_from_photons();
     double rcga = p->get_rcg_for_air();
     double rcgw = p->get_rcg_for_water();
     switch( u )
     {
         case CURIES:
             return lambda * AVOGADRO / CURIE_TO_BECQUEREL;
         case BECQUERELS:
             return lambda * AVOGADRO;
         case WATTS:
             return lambda * q * AVOGADRO / JOULE_TO_MEV;
         case GAMWATTS:
             return lambda * q * fg * AVOGADRO / JOULE_TO_MEV;
         case MEVS:
             return lambda * q * AVOGADRO;
         case GAMMEVS:
             return lambda * q * fg * AVOGADRO;
         case AIRM_3:
             return lambda / rcga * AVOGADRO / CURIE_TO_BECQUEREL;
         case H2OM_3:
             return lambda / rcgw * AVOGADRO / CURIE_TO_BECQUEREL;
         default:
             throw nemesis::assertion(
                 "this mole conversion restricted to decay-type output" );
     }
     return BAD_DOUBLE;
 }
double n2n (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double n2m (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double n2d (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double d2n (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double d2m (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double d2d (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double m2n (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double m2m (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
double m2d (ConcentrationUnit unew, int izzzaaa, ConcentrationUnit uold, double val, double volume) const private
Referenced by ConcentrationConverter::convert_to().
Member Data Documentation
SCP_NuclideResource r_nuclide_resource protected
Referenced by ConcentrationConverter::mol2m().
SCP_DecayResource r_decay_resource protected
Referenced by ConcentrationConverter::mol2d().
The documentation for this class was generated from the following files:
Core/dc/ConcentrationConverter.h
Core/dc/ConcentrationConverter.cpp