ORIGEN API: TransitionGroupFilter Class Reference
TransitionGroupFilter Class Reference
#include <TransitionGroupFilter.h>
Public Member Functions
TransitionGroupFilter ()
bool filter (int transition_id) const
Static Public Member Functions
static bool filter (int transition_id, void *obji)
Public Attributes
bool allow_decay
bool allow_reaction
bool allow_fission
std::set< int > allow_transition_id
Constructor & Destructor Documentation
TransitionGroupFilter () inline
         : allow_decay( true ), allow_reaction( true ), allow_fission( false )
     {
     }
Member Function Documentation
bool filter (int transition_id) const inline
Referenced by TransitionGroupFilter::filter(), and Origen::graphvizLibrary().
     {
         if( transition_id == 18 && !allow_fission ) return true;
         if( transition_id < 0 && !allow_decay ) return true;
         if( transition_id > 0 && !allow_reaction ) return true;
         bool keep_this = allow_transition_id.empty() ||
                          allow_transition_id.count( transition_id );
         return !keep_this;
     }
static bool filter (int transition_id, void * obji) inline static
References TransitionGroupFilter::filter().
     {
         TransitionGroupFilter *obj =
             static_cast<TransitionGroupFilter *>( obji );
         return obj->filter( transition_id );
     }
Member Data Documentation
bool allow_decay
Referenced by Origen::view().
bool allow_reaction
Referenced by Origen::view().
bool allow_fission
Referenced by Origen::view().
std::set<int> allow_transition_id
The documentation for this class was generated from the following file:
Core/dc/TransitionGroupFilter.h