ORIGEN API: Origen::detail Namespace Reference
Origen::detail Namespace Reference
Classes
struct Header
class RRNuclide
class RRXs
Functions
void setupEndianness (ScaleUtils::IO::IStreamManipulator_FBin &binsman, ScaleUtils::IO::DB &opts)
template<typename T >
void readGeneral (ScaleUtils::IO::IStreamManipulator_FBin &binsman, std::string name, T &vec, bool has_header, bool has_length, bool use_size)
template<typename T >
void writeGeneral (std::ostream &stream, std::string name, const T &vec, bool has_header, bool has_length)
void read (ScaleUtils::IO::IStreamManipulator_FBin &binsman, std::string name,::Origen::Vec_Flt &fvec, bool has_header)
read float vector with size already set
void read (ScaleUtils::IO::IStreamManipulator_FBin &binsman, std::string name,::Origen::Vec_Int &ivec, bool has_header)
read int vector with size already set
void write (std::ostream &stream, std::string name, const ::Origen::Vec_Flt &fvec, bool has_header)
write float vector without vector size
void write (std::ostream &stream, std::string name, const ::Origen::Vec_Int &ivec, bool has_header)
write int vector without vector size
void readScale61 (ScaleUtils::IO::IStreamManipulator_FBin &binsman, std::string name,::Origen::Vec_Int &ivec, bool has_header)
void readScale61 (ScaleUtils::IO::IStreamManipulator_FBin &binsman, std::string name,::Origen::Vec_Flt &fvec, bool has_header)
void writeScale61 (std::ostream &stream, std::string name, const ::Origen::Vec_Int &ivec, bool has_header)
write int vector with length
void writeScale61 (std::ostream &stream, std::string name, const ::Origen::Vec_Flt &fvec, bool has_header)
write float vector with length
void writeScale61Title (std::ostream &stream, std::string title)
void writeScale61EmptyRecords (std::ostream &stream, std::string name, int num)
Function Documentation
void setupEndianness (ScaleUtils::IO::IStreamManipulator_FBin & binsman, ScaleUtils::IO::DB & opts)
Referenced by LibraryIO_s61::read(), StateSetIO_s61::read(), and LibraryIO_s62b::read().
 {
     //
     // Read first header to check for endianess
     // First fortran header should less 1000 and > zero
     //
     int test = 0;
     bool revBytes = false;
     binsman >> test;
     if( test < 0 || test > 1000 )
     {
         revBytes = true;
     }
     binsman.setReverseBytes( revBytes );
     // Add file endianness
     opts.set( "readFileEndian",
               ScaleUtils::IO::EndianUtils::file_is_big_endian( !revBytes )
                   ? "big"
                   : "little" );
 }
void Origen::detail::readGeneral (ScaleUtils::IO::IStreamManipulator_FBin & binsman, std::string name, T & vec, bool has_header, bool has_length, bool use_size) inline
Referenced by read(), and readScale61().
 {
     // header
     if( has_header ) binsman.readHeader( name );
     // vec length
     if( has_length )
     {
         int len;
         binsman >> len;
         jDebugLine( "read length of Vec " << name << ": " << len );
         if( use_size ) vec.resize( len );
     }
     // read content
     binsman >> vec;
     jDebugLine( "read Vec " << name << " size: " << vec.size() );
     // footer
     if( has_header ) binsman.readFooter();
 }
void Origen::detail::writeGeneral (std::ostream & stream, std::string name, const T & vec, bool has_header, bool has_length) inline
Referenced by write(), and writeScale61().
 {
     jDebugLine( "write Vec " << name << " size: " << vec.size() );
     // bytes size
     int size = 0;
     size += vec.size() * sizeof( typename T::value_type );
     if( has_length ) size += sizeof( int );
     // header
     if( has_header ) stream.write( (char*)&size, sizeof( size ) );
     // vec length
     if( has_length )
     {
         int len = (int)vec.size();
         stream.write( (char*)&len, sizeof( len ) );
     }
     // content
     if( vec.size() > 0 )
     {
         stream.write( (char*)&vec[0],
                       vec.size() * sizeof( typename T::value_type ) );
     }
     // footer
     if( has_header ) stream.write( (char*)&size, sizeof( size ) );
 }
void read (ScaleUtils::IO::IStreamManipulator_FBin & binsman, std::string name, ::Origen::Vec_Flt & fvec, bool has_header)
read float vector with size already set
References readGeneral().
Referenced by LibraryIO_s62b::read(), and StateSetIO_s61::read().
 {
     readGeneral( binsman, name, fvec, has_header, false, false );
 }
void read (ScaleUtils::IO::IStreamManipulator_FBin & binsman, std::string name, ::Origen::Vec_Int & ivec, bool has_header)
read int vector with size already set
References readGeneral().
 {
     readGeneral( binsman, name, ivec, has_header, false, false );
 }
void write (std::ostream & stream, std::string name, const ::Origen::Vec_Flt & fvec, bool has_header)
write float vector without vector size
References writeGeneral().
 {
     writeGeneral( stream, name, fvec, has_header, false );
 }
void write (std::ostream & stream, std::string name, const ::Origen::Vec_Int & ivec, bool has_header)
write int vector without vector size
References writeGeneral().
 {
     writeGeneral( stream, name, ivec, has_header, false );
 }
void readScale61 (ScaleUtils::IO::IStreamManipulator_FBin & binsman, std::string name, ::Origen::Vec_Int & ivec, bool has_header)
read int vector with size already set, but still reading int dummy (maybe supposed to be vector length but not always the case)
References readGeneral().
Referenced by LibraryIO_s61::read().
 {
     readGeneral( binsman, name, ivec, has_header, true, false );
 }
void readScale61 (ScaleUtils::IO::IStreamManipulator_FBin & binsman, std::string name, ::Origen::Vec_Flt & fvec, bool has_header)
read float vector with size already set, but still reading int dummy (maybe supposed to be vector length but not always the case)
References readGeneral().
 {
     readGeneral( binsman, name, fvec, has_header, true, false );
 }
void writeScale61 (std::ostream & stream, std::string name, const ::Origen::Vec_Int & ivec, bool has_header)
write int vector with length
References writeGeneral().
Referenced by LibraryIO_s61::write(), and writeScale61EmptyRecords().
 {
     writeGeneral( stream, name, ivec, has_header, true );
 }
void writeScale61 (std::ostream & stream, std::string name, const ::Origen::Vec_Flt & fvec, bool has_header)
write float vector with length
References writeGeneral().
 {
     writeGeneral( stream, name, fvec, has_header, true );
 }
void writeScale61Title (std::ostream & stream, std::string title)
Referenced by LibraryIO_s61::write(), and LibraryIO_s62b::write().
 {
     // make sure title is divisible by 4
     if( title.size() == 0 )
     {
         title = "    ";
     }
     else
     {
         title.append( title.size() % 4, ' ' );
     }
     Check( title.size() % 4 == 0 );
     int size = 0;
     size += sizeof( int );  // number of title lines
     size += title.size();
     //
     // Write header
     //
     stream.write( (char*)&size, sizeof( size ) );
     //
     // Write record content
     //
     int temp_size = (int)title.size();
     int nti = temp_size / 4;
     stream.write( (char*)&( nti ), sizeof( int ) );
     if( temp_size > 0 ) stream.write( &title[0], temp_size );
     //
     // Write footer
     //
     stream.write( (char*)&size, sizeof( size ) );
 }
void writeScale61EmptyRecords (std::ostream & stream, std::string name, int num)
References writeScale61().
Referenced by LibraryIO_s61::write().
 {
     for( int i = 0; i < num; ++i )
     {
         writeScale61( stream, name, Vec_Int{1}, true );
     }
 }