ORIGEN API: MaterialMap Class Reference
MaterialMap Class Reference
#include <MaterialMap.h>
Simple map of materials id->Origen::Material.
INTERFACE<<Standard::Serializable>>
See Standard::Serializable for details.
virtual int serialize (Standard::AbstractStream *stream) const
virtual int deserialize (Standard::AbstractStream *stream)
virtual unsigned long getSerializedSize () const
virtual Standard::Serializable * getCopy () const
Public Member Functions
SP_Material get (int id) const
get a material (returns nullptr if not found)
void add (SP_Material mat)
add a new material
double power () const
total power (W) for last step
double power_over (int i) const
total power (W) for any interval
double cold_volume () const
total cold volume (cm^3)
double initial_mass () const
total mass (g)
double initial_hm_mass () const
total hm mass (g)
std::string to_string () const
Public Attributes
K keys
STL member.
T elements
STL member.
Detailed Description
Simple map of materials id->Origen::Material.
Examples:
tstio.cpp, tstMaterial.cpp, tstMaterialBuffer.cpp, tstMultiZoneDepleter.cpp, and tstParallelDepletion.cpp.
Member Function Documentation
SP_Material get (int id) const
get a material (returns nullptr if not found)
 {
     MaterialMap::const_iterator it = this->find( id );
     if( it == this->end() )
     {
         return nullptr;
     }
     else
     {
         return it->second;
     }
 }
void add (SP_Material mat)
add a new material
Examples:
tstMaterial.cpp.
Referenced by TEST().
 {
     Require( mat != nullptr );
     Require( mat->id() != 0 );
     ( *this )[mat->id()] = mat;
 }
double power () const
total power (W) for last step
 {
     double total = 0;
     for( const auto& id_mat : *this )
     {
         total += id_mat.second->power();
     }
     return total;
 }
double power_over (int i) const
total power (W) for any interval
 {
     double total = 0;
     for( const auto& id_mat : *this )
     {
         total += id_mat.second->power_over( i );
     }
     return total;
 }
double cold_volume () const
total cold volume (cm^3)
Examples:
tstMaterial.cpp.
Referenced by TEST().
 {
     double total = 0;
     for( const auto& id_mat : *this )
     {
         total += id_mat.second->cold_volume();
     }
     return total;
 }
double initial_mass () const
total mass (g)
Examples:
tstMaterial.cpp.
Referenced by TEST().
 {
     double total = 0;
     for( const auto& id_mat : *this )
     {
         total += id_mat.second->initial_mass();
     }
     return total;
 }
double initial_hm_mass () const
total hm mass (g)
Examples:
tstMaterial.cpp.
Referenced by TEST().
 {
     double total = 0;
     for( const auto& id_mat : *this )
     {
         total += id_mat.second->initial_hm_mass();
     }
     return total;
 }
int serialize (Standard::AbstractStream * stream) const virtual
 {
     Insist( false, "not implemented" );
     return 0;
 }
int deserialize (Standard::AbstractStream * stream) virtual
 {
     Insist( false, "not implemented" );
     return 0;
 }
unsigned long getSerializedSize () const virtual
 {
     Insist( false, "not implemented" );
     return 0;
 }
Standard::Serializable * getCopy () const virtual
 {
     Insist( false, "not implemented" );
     return nullptr;
 }
std::string to_string () const
 {
     Origen::MaterialMap::const_iterator it;
     std::stringstream os;
     {
         for( it = this->begin(); it != this->end(); ++it )
         {
             // base variables
             Origen::SP_Material mat = it->second;
             Check( mat != nullptr );
             os << "material: " << mat->to_string() << std::endl;
         }
     }
     return os.str();
 }
Member Data Documentation
K keys inherited
STL member.
T elements inherited
STL member.
The documentation for this class was generated from the following files:
Core/dc/MaterialMap.h
Core/dc/MaterialMap.cpp