ORIGEN API: StateInfo Class Reference
StateInfo Class Reference
#include <StateInfo.h>
Container for a State information tag.
Public Types
typedef std::shared_ptr< StateInfo > SP
typedef std::shared_ptr< const StateInfo > SCP
Public Member Functions
StateInfo ()
virtual ~StateInfo ()
std::string to_string () const
Scale::Json::Value to_json () const
int case_number () const
void set_case_number (int)
int step_number () const
void set_step_number (int)
int library_position () const
void set_library_position (int)
bool match (const StateInfo &b) const
void accumulate_definition (const StateInfo &definition, float volume, float previous_volume=1.0)
float power () const
void set_power (float)
float flux () const
void set_flux (float)
float time () const
void set_time (float)
float fluence () const
void set_fluence (float)
float energy () const
void set_energy (float)
float burnup () const
void set_burnup (float)
const TagManager & tag_manager () const
return a const reference to tag_manager
SCP_TagManager scp_tag_manager () const
return a shared (read-only) tag_manager pointer
bool has_tag_manager () const
return whether the class has a non-null tag_manager
void get_tag_manager (TagManager &) const
populate an existing TagManager with a copy of tag_manager
void set_tag_manager (const TagManager &)
set the tag_manager (copy operation)
void getptr_tag_manager (const TagManager *&) const
retrieve pointer (read-only) to tag_manager
void manageptr_tag_manager (TagManager *&)
set the tag_manager (ownership transfer)
int serialize (Standard::AbstractStream *stream) const
int deserialize (Standard::AbstractStream *stream)
unsigned long getSerializedSize () const
Standard::Serializable * getCopy () const
virtual Standard::Serializable::UID getUID () const
std::string toString () const
Static Public Member Functions
static bool match (const StateInfo &a, const StateInfo &b)
Static Public Attributes
static const Standard::Serializable::UID uid = 0x0c298a37d502b3a8
Protected Member Functions
void canonicalize_tag_manager ()
bool isEqualStateInfo (const StateInfo &a) const
virtual bool isEqual (const Standard::Serializable &b) const
Protected Attributes
int b_case_number
int b_step_number
int b_library_position
float b_power
float b_flux
float b_time
float b_fluence
float b_energy
SP_TagManager b_tag_manager
Friends
class GridView_StateInfo
class State
class ScaleUtils::IO::Accessor< StateInfo >
Detailed Description
Container for a State information tag.
This container is meant to function like a header for a Origen::State. It allows for interpolation of states and grouping of states. It is a small data structure and must be non-null on each State.
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstState.cpp, and Core/dc/tests/tstStateInfo.cpp.
Member Typedef Documentation
typedef std::shared_ptr<StateInfo> SP
typedef std::shared_ptr<const StateInfo> SCP
Constructor & Destructor Documentation
StateInfo ()
Referenced by StateInfo::getCopy().
     : b_case_number( BAD_INT )
     , b_step_number( 0 )
     , b_library_position( 0 )
     , b_power( 0.0f )
     , b_flux( 0.0f )
     , b_time( 0.0f )
     , b_fluence( 0.0f )
     , b_energy( 0.0f )
     , b_tag_manager( new TagManager() )
 {
 }
virtual ~StateInfo () inline virtual
 {}
Member Function Documentation
std::string to_string () const
References StateInfo::to_json().
Referenced by StateInfo::toString().
 { return to_json().toStyledString(); }
Json::Value to_json () const
References StateInfo::b_case_number, StateInfo::b_energy, StateInfo::b_fluence, StateInfo::b_flux, StateInfo::b_library_position, StateInfo::b_power, StateInfo::b_step_number, StateInfo::b_tag_manager, StateInfo::b_time, and StateInfo::uid.
Referenced by StateInfo::to_string().
 {
     Json::Value root;
     root["uid"] = Json::Value::Int64( uid );
     root["case"] = b_case_number;
     root["step"] = b_step_number;
     root["libpos"] = b_library_position;
     root["power"] = b_power;
     root["flux"] = b_flux;
     root["time"] = b_time;
     root["fluence"] = b_fluence;
     root["energy"] = b_energy;
     root["TagManager"] = b_tag_manager->to_json();
     return root;
 }
int case_number () const
int - Case number in concentration file
Examples:
Core/dc/tests/tstStateSet.cpp.
References StateInfo::b_case_number.
Referenced by StateInfo::match(), StateSet::matching_states(), StateSetIO_s62b::read(), StateSetIO_bof::read(), StateInfo::set_case_number(), TEST(), StateSetIO_s62b::write(), and Origen::write().
 { return b_case_number; }
void set_case_number (int case_number)
int - Set case number in concentration file
References StateInfo::b_case_number, and StateInfo::case_number().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s61::read(), StateSetIO_s62b::read(), Origen::read(), Origen::saveStateSet(), and FakeFactory::StateSet_random1().
 {
     b_case_number = case_number;
 }
int step_number () const
int - Step number in concentration file
References StateInfo::b_step_number.
Referenced by StateSetIO_bof::read(), StateSetIO_s62b::read(), StateInfo::set_step_number(), StateSetIO_s62b::write(), and Origen::write().
 { return b_step_number; }
void set_step_number (int step_number)
int - Set step number in concentration file
References StateInfo::b_step_number, and StateInfo::step_number().
Referenced by StateSetIO_s61::read(), StateSetIO_s62b::read(), Origen::read(), Origen::saveStateSet(), and FakeFactory::StateSet_random1().
 {
     b_step_number = step_number;
 }
int library_position () const
int - Library position
References StateInfo::b_library_position.
Referenced by StateSetIO_bof::read(), StateSetIO_s62b::read(), StateInfo::set_library_position(), StateSetIO_s62b::write(), and Origen::write().
 { return b_library_position; }
void set_library_position (int library_position)
int - Set library position
References StateInfo::b_library_position, and StateInfo::library_position().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), Origen::read(), Origen::saveStateSet(), and FakeFactory::StateSet_random1().
 {
     b_library_position = library_position;
 }
bool match (const StateInfo & a, const StateInfo & b) static
References StateInfo::case_number(), TagManager::match(), and StateInfo::tag_manager().
Referenced by StateInfo::isEqualStateInfo(), GridView_StateInfo::match(), State::match(), and StateInfo::match().
 {
     return a.case_number() == b.case_number() &&
            a.tag_manager().match( b.tag_manager() );
 }
bool match (const StateInfo & b) const
References StateInfo::match().
 { return match( *this, b ); }
void accumulate_definition (const StateInfo & definition, float volume, float previous_volume = 1.0)
Examples:
Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_energy, StateInfo::b_fluence, StateInfo::b_flux, StateInfo::b_power, StateInfo::energy(), StateInfo::fluence(), StateInfo::flux(), and StateInfo::power().
Referenced by TEST().
 {
     b_power += definition.power();
     b_energy += definition.energy();
     float total_volume = volume + previous_volume;
     if( total_volume > 0 )
     {
         float previous_frac = previous_volume / total_volume;
         float frac = volume / total_volume;
         b_flux = b_flux * previous_frac + definition.flux() * frac;
         b_fluence = b_fluence * previous_frac + definition.fluence() * frac;
     }
 }
float power () const
float - return power [MW]
Examples:
Core/dc/tests/tstState.cpp, Core/dc/tests/tstStateInfo.cpp, and Core/dc/tests/tstStateSet.cpp.
References StateInfo::b_power.
Referenced by StateInfo::accumulate_definition(), StateSet::powers(), StateSetIO_s62b::read(), StateSetIO_bof::read(), StateInfo::set_power(), TEST(), StateSetIO_s62b::write(), and Origen::write().
 { return b_power; }
void set_power (float power)
float - set power [MW]
Examples:
Core/dc/tests/tstState.cpp, and Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_power, and StateInfo::power().
Referenced by StateSetIO_s61::read(), StateSetIO_s62b::read(), Origen::read(), Origen::saveStateSet(), FakeFactory::StateSet_random1(), and TEST().
 { b_power = power; }
float flux () const
float - return flux [1/cm^2-s]
Examples:
Core/dc/tests/tstState.cpp, Core/dc/tests/tstStateInfo.cpp, and Core/dc/tests/tstStateSet.cpp.
References StateInfo::b_flux.
Referenced by StateInfo::accumulate_definition(), StateSet::fluxes(), StateSetIO_s62b::read(), StateSetIO_bof::read(), StateInfo::set_flux(), TEST(), StateSetIO_s62b::write(), and Origen::write().
 { return b_flux; }
void set_flux (float flux)
float - set flux [1/cm^2-s]
Examples:
Core/dc/tests/tstState.cpp, and Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_flux, and StateInfo::flux().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), Origen::read(), Origen::saveStateSet(), FakeFactory::StateSet_random1(), and TEST().
 { b_flux = flux; }
float time () const
float - return time [s]
Examples:
Core/dc/tests/tstStateInfo.cpp, and Core/dc/tests/tstStateSet.cpp.
References StateInfo::b_time.
Referenced by StateSet::alpha_spectra(), StateSet::beta_spectra(), StateSet::check_headers(), StateSet::concs(), StateSet::gamma_spectra(), StateSet::nearest_time(), StateSet::neutron_spectra(), StateSetIO_s62b::read(), StateSetIO_bof::read(), StateInfo::set_time(), TEST(), StateSet::times(), StateSetIO_s62b::write(), and Origen::write().
 { return b_time; }
void set_time (float time)
float - set time [s]
Examples:
Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_time, and StateInfo::time().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), Origen::read(), Origen::saveStateSet(), FakeFactory::StateSet_random1(), and TEST().
 { b_time = time; }
float fluence () const
float - return fluence [1/cm^2]
Examples:
Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_fluence.
Referenced by StateInfo::accumulate_definition(), StateInfo::set_fluence(), TEST(), and Origen::write().
 { return b_fluence; }
void set_fluence (float fluence)
float - set fluence [1/cm^2]
Examples:
Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_fluence, and StateInfo::fluence().
Referenced by Origen::read(), and TEST().
 { b_fluence = fluence; }
float energy () const
float - return energy released [MWd]
Examples:
Core/dc/tests/tstStateInfo.cpp, and Core/dc/tests/tstStateSet.cpp.
References StateInfo::b_energy.
Referenced by StateInfo::accumulate_definition(), StateSet::alpha_spectra(), StateSet::beta_spectra(), StateSet::check_headers(), StateSet::concs(), StateSet::energies(), StateSet::gamma_spectra(), StateSet::neutron_spectra(), StateSetIO_bof::read(), StateSetIO_s62b::read(), StateInfo::set_burnup(), StateInfo::set_energy(), TEST(), StateSetIO_s62b::write(), and Origen::write().
 { return b_energy; }
void set_energy (float energy)
float - set energy released [MWd]
Examples:
Core/dc/tests/tstStateInfo.cpp.
References StateInfo::b_energy, and StateInfo::energy().
Referenced by StateSetIO_s62b::read(), Origen::read(), FakeFactory::StateSet_random1(), and TEST().
 { b_energy = energy; }
float burnup () const
float - return energy released [MWd]
References StateInfo::b_energy.
 { return b_energy; }
void set_burnup (float energy)
float - set energy released [MWd]
References StateInfo::b_energy, and StateInfo::energy().
 { b_energy = energy; }
const TagManager & tag_manager () const
return a const reference to tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of StateInfo goes out of scope.
Referenced by StateInfo::match(), and Origen::write().
SCP_TagManager scp_tag_manager () const
return a shared (read-only) tag_manager pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_tag_manager () const
return whether the class has a non-null tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_tag_manager (TagManager & tag_manager) const
populate an existing TagManager with a copy of tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_tag_manager (const TagManager & tag_manager)
set the tag_manager (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstGridView.cpp.
Referenced by Origen::read(), Origen::saveStateSet(), and TEST().
void getptr_tag_manager (const TagManager *&) const
retrieve pointer (read-only) to tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_tag_manager (TagManager *& tag_manager)
set the tag_manager (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
int serialize (Standard::AbstractStream * stream) const
References StateInfo::b_case_number, StateInfo::b_energy, StateInfo::b_fluence, StateInfo::b_flux, StateInfo::b_library_position, StateInfo::b_power, StateInfo::b_step_number, StateInfo::b_tag_manager, StateInfo::b_time, StateInfo::getSerializedSize(), and Origen::write().
 {
     Require( stream != nullptr );
     // Write UID.
     int return_code = write( stream, StateInfo::uid );
     if( return_code != 0 ) return return_code;
     // Write size of object.
     unsigned long size = getSerializedSize();
     stream->write( (char*)&size, sizeof( unsigned long ) );
     Remember( long oldWriteHead = stream->getWriteHead() );
     // Write object components.
     size_t bytes = 0;
     bytes += write( stream, b_case_number );
     bytes += write( stream, b_step_number );
     bytes += write( stream, b_library_position );
     bytes += write( stream, b_power );
     bytes += write( stream, b_flux );
     bytes += write( stream, b_time );
     bytes += write( stream, b_fluence );
     bytes += write( stream, b_energy );
     bytes += write( stream, b_tag_manager );
     // Check that size expected matches size write.
     Ensure( bytes == size );
     Ensure( ( stream->getWriteHead() - oldWriteHead ) ==
             static_cast<long>( size ) );
     if( bytes != size ) return 1;
     return 0;
 }  // serialize
int deserialize (Standard::AbstractStream * stream)
References StateInfo::b_case_number, StateInfo::b_energy, StateInfo::b_fluence, StateInfo::b_flux, StateInfo::b_library_position, StateInfo::b_power, StateInfo::b_step_number, StateInfo::b_tag_manager, StateInfo::b_time, StateInfo::canonicalize_tag_manager(), and Origen::read().
 {
     Require( stream != nullptr );
     // Read UID.
     int return_code = read( stream, StateInfo::uid );
     if( return_code != 0 ) return return_code;
     // Read size of object.
     unsigned long size = 0;
     stream->read( (char*)&size, sizeof( unsigned long ) );
     // Read object components.
     size_t bytes = 0;
     bytes += read( stream, b_case_number );
     bytes += read( stream, b_step_number );
     bytes += read( stream, b_library_position );
     bytes += read( stream, b_power );
     bytes += read( stream, b_flux );
     bytes += read( stream, b_time );
     bytes += read( stream, b_fluence );
     bytes += read( stream, b_energy );
     b_tag_manager = std::make_shared<TagManager>();
     bytes += read( stream, b_tag_manager );
     canonicalize_tag_manager();
     // Check that size expected matches size read.
     Ensure( bytes == size );
     if( bytes != size ) return 1;
     return 0;
 }  // deserialize
unsigned long getSerializedSize () const
References StateInfo::b_case_number, StateInfo::b_energy, StateInfo::b_fluence, StateInfo::b_flux, StateInfo::b_library_position, StateInfo::b_power, StateInfo::b_step_number, StateInfo::b_tag_manager, and StateInfo::b_time.
Referenced by StateInfo::serialize().
 {
     Standard::AbstractStream* a = nullptr;
     return sizeof( b_case_number ) + sizeof( b_step_number ) +
            sizeof( b_library_position ) + sizeof( b_power ) + sizeof( b_flux ) +
            sizeof( b_time ) + sizeof( b_fluence ) + sizeof( b_energy ) +
            Standard::bytes( a, b_tag_manager );
 }
Standard::Serializable * getCopy () const
References StateInfo::StateInfo().
 {
     return new StateInfo( *this );
 }
Standard::Serializable::UID getUID () const virtual
References StateInfo::uid.
 { return StateInfo::uid; }
std::string toString () const
References StateInfo::to_string().
 { return to_string(); }
void canonicalize_tag_manager () protected
Referenced by StateInfo::deserialize().
 {
     // null op
 }
bool isEqualStateInfo (const StateInfo & a) const protected
References StateInfo::b_energy, StateInfo::b_fluence, StateInfo::b_flux, StateInfo::b_power, StateInfo::b_time, and StateInfo::match().
Referenced by StateInfo::isEqual().
 {
     /// \todo add TagManager equality check
     return match( *this, a ) && b_power == a.b_power && b_flux == a.b_flux &&
            b_time == a.b_time && b_fluence == a.b_fluence &&
            b_energy == a.b_energy;
 }
bool isEqual (const Standard::Serializable & b) const protected virtual
References StateInfo::isEqualStateInfo().
 {
     return isEqualStateInfo( static_cast<const StateInfo&>( a ) );
 }
Friends And Related Function Documentation
friend class GridView_StateInfo friend
friend class State friend
friend class ScaleUtils::IO::Accessor< StateInfo > friend
Member Data Documentation
const Standard::Serializable::UID uid = 0x0c298a37d502b3a8 static
Referenced by StateInfo::getUID(), and StateInfo::to_json().
int b_case_number protected
Referenced by StateInfo::case_number(), StateInfo::deserialize(), StateInfo::getSerializedSize(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_case_number(), and StateInfo::to_json().
int b_step_number protected
Referenced by StateInfo::deserialize(), StateInfo::getSerializedSize(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_step_number(), StateInfo::step_number(), and StateInfo::to_json().
int b_library_position protected
Referenced by StateInfo::deserialize(), StateInfo::getSerializedSize(), StateInfo::library_position(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_library_position(), and StateInfo::to_json().
float b_power protected
Referenced by StateInfo::accumulate_definition(), StateInfo::deserialize(), StateInfo::getSerializedSize(), StateInfo::isEqualStateInfo(), StateInfo::power(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_power(), and StateInfo::to_json().
float b_flux protected
Referenced by StateInfo::accumulate_definition(), StateInfo::deserialize(), StateInfo::flux(), StateInfo::getSerializedSize(), StateInfo::isEqualStateInfo(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_flux(), and StateInfo::to_json().
float b_time protected
Referenced by StateInfo::deserialize(), StateInfo::getSerializedSize(), StateInfo::isEqualStateInfo(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_time(), StateInfo::time(), and StateInfo::to_json().
float b_fluence protected
Referenced by StateInfo::accumulate_definition(), StateInfo::deserialize(), StateInfo::fluence(), StateInfo::getSerializedSize(), StateInfo::isEqualStateInfo(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), StateInfo::set_fluence(), and StateInfo::to_json().
float b_energy protected
Referenced by StateInfo::accumulate_definition(), StateInfo::burnup(), StateInfo::deserialize(), StateInfo::energy(), StateInfo::getSerializedSize(), StateInfo::isEqualStateInfo(), StateInfo::serialize(), StateInfo::set_burnup(), StateInfo::set_energy(), and StateInfo::to_json().
SP_TagManager b_tag_manager protected
Referenced by StateInfo::deserialize(), StateInfo::getSerializedSize(), Accessor< Origen::StateInfo >::read(), StateInfo::serialize(), and StateInfo::to_json().
The documentation for this class was generated from the following files:
Core/dc/StateInfo.h
Core/dc/StateInfo.cpp