ORIGEN API: Core/fn/tests/tsttabulate.cpp File Reference
tsttabulate.cpp File Reference
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/fn/print.h"
#include "Origen/Core/fn/tabulate.h"
#include "Origen/Core/xf/Solver_Fake.h"
Classes
class TabulateMaterial
Functions
TEST (Tabulate, Append)
TEST_F (TabulateMaterial, Isotopics)
TEST_F (TabulateMaterial, TransitionRate)
TEST_F (TabulateMaterial, LossRate)
TEST_F (TabulateMaterial, FissionRate)
Function Documentation
TEST (Tabulate , Append)
References FakeFactory::newspLibrary_10nuclide(), and Origen::tabulateLossXs().
 {
     auto lib = Origen::FakeFactory::newspLibrary_10nuclide();
     // set of values for the first column
     int sizzzaaa = 0;
     std::string idform = "";
     int prec = 5;
     int pos = 1;
     std::string column_name = "x";
     bool append_column = false;
     ScaleUtils::IO::Table2D table;
     tabulateLossXs(
         *lib, sizzzaaa, idform, prec, pos, column_name, append_column, &table );
     // set for the second column
     pos = 4;
     column_name = "y";
     prec = 3;
     append_column = true;
     tabulateLossXs(
         *lib, sizzzaaa, idform, prec, pos, column_name, append_column, &table );
     // printTable( false, &table );
     EXPECT_EQ( "x", table.headersX[0] );
     EXPECT_EQ( "y", table.headersX[1] );
     EXPECT_EQ( "1.000e+00", table.data[1][1] );
     // printTable( false, &table );
 }
TEST_F (TabulateMaterial , Isotopics)
References Origen::printTable(), and Origen::tabulateMaterialIsotopics().
 {
     ScaleUtils::IO::Table2D table;
     size_t point = 1;
     Origen::SCP_Vec_Int base_ids;  // ids that will be print in the table (set
                                    // by call with append_column=false)
     Origen::tabulateMaterialIsotopics( *mat1, point, &table, base_ids );
     Origen::tabulateMaterialIsotopics( *mat2, point, &table, base_ids );
     std::stringstream ss;
     Origen::printTable( false, &table, ss );
     // std::cout << ss.str() << std::endl;
     EXPECT_NE( "", ss.str() );
 }
TEST_F (TabulateMaterial , TransitionRate)
References Origen::printTable(), and Origen::tabulateMaterialTransitionRates().
 {
     ScaleUtils::IO::Table2D table;
     size_t step = 0;
     Origen::SCP_TransitionStructure base_tstruct;
     Origen::tabulateMaterialTransitionRates(
         *mat1, step, &table, base_tstruct );
     Origen::tabulateMaterialTransitionRates(
         *mat2, step, &table, base_tstruct );
     std::stringstream ss;
     Origen::printTable( false, &table, ss );
     // std::cout << ss.str() << std::endl;
     EXPECT_NE( "", ss.str() );
 }
TEST_F (TabulateMaterial , LossRate)
References Origen::printTable(), and Origen::tabulateMaterialLossRate().
 {
     ScaleUtils::IO::Table2D table;
     size_t step = 0;
     bool append = false;
     Origen::tabulateMaterialLossRate( *mat1, step, &table, append );
     Origen::tabulateMaterialLossRate( *mat2, step, &table, append );
     std::stringstream ss;
     Origen::printTable( false, &table, ss );
     // std::cout << ss.str() << std::endl;
     EXPECT_NE( "", ss.str() );
 }
TEST_F (TabulateMaterial , FissionRate)
References Origen::printTable(), and Origen::tabulateMaterialFissionRate().
 {
     ScaleUtils::IO::Table2D table;
     size_t step = 0;
     bool append = false;
     Origen::tabulateMaterialFissionRate( *mat1, step, &table, append );
     Origen::tabulateMaterialFissionRate( *mat2, step, &table, append );
     std::stringstream ss;
     Origen::printTable( false, &table, ss );
     // std::cout << ss.str() << std::endl;
     EXPECT_NE( "", ss.str() );
 }