ORIGEN API: Obiwan_patch Class Reference
Obiwan_patch Class Reference
#include <Obiwan_patch.h>
execute obiwan in patch mode
Public Member Functions
Obiwan_patch (int argc, char **argv)
Obiwan_patch (ScaleUtils::IO::DB opts)
~Obiwan_patch () noexcept(false)
int execute (std::ostream &out, std::ostream &err)
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in patch mode
Examples:
Core/ut/tests/tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_patch (int argc, char ** argv)
References Obiwan_patch::b_opts, and Obiwan_patch::populate().
 {
     b_opts = populate( argc, argv );
 }
Obiwan_patch (ScaleUtils::IO::DB opts)
 : b_opts( opts ) {}
~Obiwan_patch () inline noexcept
 {}
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_patch::execute().
 {
     const char* help = R"help(
 //! [help]
  PURPOSE: patch an ORIGEN file with data from another file
  USAGE: obiwan patch -from=SOURCE -data="path/to/data" [opts] file
         -flag=Type(DefaultValue)       DESCRIPTION
         ________________________       ____________________________
         -from=File(ft33f001)           existing data file OR "NULL"
         -data=Path()                   a special a heirarchical data description
                                        using "/" separators, data paths supported:
                                        coeff[POS]/n_production_xs
                                        coeff[POS]/nu
                                        POS=1,2,...,N where N is the total number of positions
                                        POS=* can be used to specify all positions
                                        POS=1|2|... can be used to specify a list of positions
                                        NOTE: coeff/ and coeff[*]/ are identical
         -pos=Int(0)                    position on <file> to apply patch
                                        (0=attempty to apply to all positions)
         -type=String()                 load only a partciular type
                                           f33: Library
         -verbose                       verbose mode (extra output to STDERR)
  NOTE: all non-essential output goes to STDERR
  EXAMPLE 1 (patch all neutron production cross sections with a single data set)
     $ obiwan patch -from=my.f33 -data=coeff[1]/n_production_xs patched.f33
     $ obiwan view -format=genneu -type=f33 -pos=1 patched.f33
  EXAMPLE 2 (patch pos=2 data with zeros)
     $ obiwan patch -from=NULL -data=coeff/n_production_xs -pos=2 patched.f33
  EXAMPLE 3 (patch 3-position library with data from 1,1,2
     $ obiwan patch -from=my.f33 -data=coeff[1|1|2]/n_production_xs patched.f33
  EXAMPLE 4 (patch 3-position library with new data--my.f33 must have 3 positions)
     $ obiwan patch -from=my.f33 -data=coeff[*]/n_production_xs patched.f33
  EXAMPLE 5 (patch 3-position library with new data--my.f33 must have 3 positions)
     $ obiwan patch -from=my.f33 -data=coeff/n_production_xs patched.f33
  EXAMPLE 6 (just correct the nu portion of actinides production assuming it is
             dominant, i.e. nu=from_prodxs/from_fisxs --> to_prodxs=nu*to_fisxs
     $ obiwan patch -from=my.f33 -data=coeff/nu patched.f33
 //! [help]
     )help";
     // break up tag so Doxygen doesn't think this is a 3rd tag
     return ScaleUtils::IO::removeSubstring( help,
                                             "//! ["
                                             ""
                                             "help"
                                             ""
                                             "]" );
 }
ScaleUtils::IO::DB populate (int argc, char ** argv) static
References Origen::baseOptions().
Referenced by Obiwan_patch::Obiwan_patch().
 {
     Standard::CommandLine cmd( argc, argv );
     // get files
     Vec_Str files = cmd.arguments();
     ScaleUtils::IO::DB base;
     // output error message
     if( files.size() == 0 )
     {
         base.set( "help", true );
     }
     else if( files.size() != 1 )
     {
         base.appendError( "Please provide 1 and only 1 filename" );
     }
     else
     {
         // expand globs (e.g. *.txt)
         ScaleUtils::IO::expandPaths( files );
         // set
         base = detail::baseOptions( cmd );
         base.set( "path", files[0] );
     }
     return base;
 }
int execute (std::ostream & out, std::ostream & err)
References Origen::applyPatch(), Obiwan_patch::b_opts, Obiwan_patch::help(), Origen::loadLibrary(), Origen::loadMulti(), and Origen::saveLibrary().
Referenced by Origen::obiwan_main().
 {
     // quick returns
     if( b_opts.get( "help", false ) )
     {
         out << help() << std::endl;
         return 1;
     }
     else if( b_opts.numError() > 0 )
     {
         out << b_opts.dumpErrorStack();
         return -1;
     }
     // data to generate patch from
     auto fromPath = b_opts.get( "fromPath", "" );
     SP_Library fromLib;
     // data to insert patch into
     auto path = b_opts.get( "path", "" );
     SP_Library lib;
     // variables
     ScaleUtils::IO::DB opts = b_opts.clone();
     bool verbose = opts.get<bool>( "verbose", false );
     // load data
     void* obj_ptr = loadMulti( path, opts );
     std::string loadedDataType = opts.get( "loadedDataType", "UNKNOWN" );
     if( opts.numError() != 0 )
     {
         opts.dumpErrorStack();
         return -1;
     }
     if( loadedDataType == "Origen::Library" )
     {
         lib = SP_Library( (Library*)( obj_ptr ) );
         if( fromPath != "NULL" )
             fromLib = SP_Library( loadLibrary( fromPath, opts ) );
     }
     if( opts.numError() != 0 )
     {
         opts.dumpErrorStack();
         return -1;
     }
     // extract all positions of data on fromLib
     // check that if multiple positions was specified for fromLib, then lib
     // has same number of positions
     // if a single position of data was specified, copy it to all positions
     auto error = applyPatch( fromLib,
                              opts.get<IntegerList*>( "coeffPosList" ),
                              opts.get<std::string>( "coeffDataKey" ),
                              lib,
                              opts.get<int>( "pos" ) );
     if( error != "" ) opts.appendError( error );
     // output options in JSON
     opts.set( "overwrite", true );
     saveLibrary( *lib, path, opts );
     if( verbose ) err << opts << std::endl;
     // final chance for error
     if( opts.numError() != 0 )
     {
         opts.dumpErrorStack();
         return -1;
     }
     return 0;
 }
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_patch::execute(), and Obiwan_patch::Obiwan_patch().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_patch.h
Core/ut/Obiwan_patch.cpp