ORIGEN API: ChannelType_Fiss Class Reference
ChannelType_Fiss Class Reference
#include <ChannelType_Fiss.h>
Channel type for fission.
Public Types
typedef SP_ChannelType SP
strong pointer
typedef WP_ChannelType WP
weak pointer
INTERFACE<<Origen::ChannelType>>
See Origen::ChannelType for details.
int reaction_mt () const
void set_reaction_mt (int reaction_mt)
std::string reaction_mt_name () const
bool has_initialized_reaction_mt () const
int decay_mode () const
void set_decay_mode (int decay_mode)
std::string decay_mode_name () const
bool has_initialized_decay_mode () const
SP_Field field () const
void get_field (SP_Field &field) const
void set_field (SP_Field field)
bool has_initialized_field () const
bool is_reaction () const
bool is_decay () const
bool has_followon_decay () const
bool has_distribution_of_daughters () const
double num_residuals_per_event () const
int num_byproduct (const ByproductId byproduct_id) const
bool has_byproduct (const ByproductId byproduct_id) const
ByproductCount_t num_byproducts () const
void increment_num_byproducts (ByproductCount_t &num_byproducts) const
int delta_nucleus_protons () const
int delta_nucleus_neutrons () const
int delta_mass_number () const
int delta_charge_number () const
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
Public Member Functions
ChannelType_Fiss ()
ChannelType_Fiss (Field::SP field)
Static Public Member Functions
static int channel_id (int decay_mode)
channel id for decay only
static int channel_id (SP_Field field, int reaction_mt, int decay_mode=0)
channel id for reaction+decay
Private Member Functions
virtual int reaction_mt_impl () const
virtual void set_reaction_mt_impl (int reaction_mt)
virtual int decay_mode_impl () const
virtual void set_decay_mode_impl (int decay_mode)
virtual Field::SP field_impl () const
virtual void set_field_impl (Field::SP field)
virtual bool is_reaction_impl () const
virtual bool is_decay_impl () const
virtual bool has_followon_decay_impl () const
virtual bool has_distribution_of_daughters_impl () const
virtual double num_residuals_per_event_impl () const
virtual int num_byproduct_impl (const ByproductId byproduct_id) const
virtual bool has_byproduct_impl (const ByproductId byproduct_id) const
virtual ByproductCount_t num_byproducts_impl () const
virtual int delta_nucleus_protons_impl () const
virtual int delta_nucleus_neutrons_impl () const
virtual int delta_mass_number_impl () const
virtual int delta_charge_number_impl () const
virtual bool good_impl (Vec_Str &errors) const
useful to chain
Private Attributes
Field::SP b_field
int b_reaction_mt
Detailed Description
Channel type for fission.
See also
ChannelType
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef SP_ChannelType SP inherited
strong pointer
typedef WP_ChannelType WP inherited
weak pointer
Constructor & Destructor Documentation
ChannelType_Fiss ()
References ChannelType::set_reaction_mt().
ChannelType_Fiss (Field::SP field)
References ChannelType::set_field(), and ChannelType::set_reaction_mt().
Member Function Documentation
int reaction_mt_impl () const private virtual
Implements ChannelType.
References ChannelType_Fiss::b_reaction_mt.
void set_reaction_mt_impl (int reaction_mt) private virtual
Implements ChannelType.
References ChannelType_Fiss::b_reaction_mt, and ChannelType::reaction_mt().
int decay_mode_impl () const private virtual
Implements ChannelType.
void set_decay_mode_impl (int decay_mode) private virtual
Implements ChannelType.
Field::SP field_impl () const private virtual
Implements ChannelType.
References ChannelType_Fiss::b_field.
void set_field_impl (Field::SP field) private virtual
Implements ChannelType.
References ChannelType_Fiss::b_field, and ChannelType::field().
bool is_reaction_impl () const private virtual
Reimplemented from ChannelType.
bool is_decay_impl () const private virtual
Reimplemented from ChannelType.
bool has_followon_decay_impl () const private virtual
Reimplemented from ChannelType.
bool has_distribution_of_daughters_impl () const private virtual
Reimplemented from ChannelType.
double num_residuals_per_event_impl () const private virtual
Reimplemented from ChannelType.
int num_byproduct_impl (const ByproductId byproduct_id) const private virtual
Reimplemented from ChannelType.
bool has_byproduct_impl (const ByproductId byproduct_id) const private virtual
Reimplemented from ChannelType.
ByproductCount_t num_byproducts_impl () const private virtual
Implements ChannelType.
int delta_nucleus_protons_impl () const private virtual
Implements ChannelType.
References Origen::BAD_INT.
int delta_nucleus_neutrons_impl () const private virtual
Implements ChannelType.
References Origen::BAD_INT.
int delta_mass_number_impl () const private virtual
Implements ChannelType.
References Origen::BAD_INT.
int delta_charge_number_impl () const private virtual
Implements ChannelType.
References Origen::BAD_INT.
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
References ChannelType::field(), Checkable::name(), and ChannelType::reaction_mt().
int reaction_mt () const inherited
Referenced by ChannelType_Fiss::good_impl(), ChannelType_Reac::good_impl(), ChannelType_Fiss::set_reaction_mt_impl(), and ChannelType_Reac::set_reaction_mt_impl().
void set_reaction_mt (int reaction_mt) inherited
Referenced by ChannelType_Fiss::ChannelType_Fiss(), and ChannelType_Reac::ChannelType_Reac().
std::string reaction_mt_name () const inherited
bool has_initialized_reaction_mt () const inherited
int decay_mode () const inherited
Referenced by ChannelType_Decay::good_impl().
void set_decay_mode (int decay_mode) inherited
Referenced by ChannelType_Decay::ChannelType_Decay().
std::string decay_mode_name () const inherited
bool has_initialized_decay_mode () const inherited
SP_Field field () const inherited
Referenced by ChannelType_Fiss::good_impl(), ChannelType_Reac::good_impl(), ChannelType_Fiss::set_field_impl(), and ChannelType_Reac::set_field_impl().
void get_field (SP_Field & field) const inherited
void set_field (SP_Field field) inherited
Referenced by ChannelType_Fiss::ChannelType_Fiss(), and ChannelType_Reac::ChannelType_Reac().
bool has_initialized_field () const inherited
bool is_reaction () const inherited
bool is_decay () const inherited
bool has_followon_decay () const inherited
bool has_distribution_of_daughters () const inherited
double num_residuals_per_event () const inherited
int num_byproduct (const ByproductId byproduct_id) const inherited
bool has_byproduct (const ByproductId byproduct_id) const inherited
ByproductCount_t num_byproducts () const inherited
void increment_num_byproducts (ByproductCount_t & num_byproducts) const inherited
int delta_nucleus_protons () const inherited
int delta_nucleus_neutrons () const inherited
int delta_mass_number () const inherited
int delta_charge_number () const inherited
int channel_id (int decay_mode) static inherited
channel id for decay only
Referenced by TransitionSystem_Gen::channel_type_impl(), and TransitionSystemAdapter_AmpxN::update().
int channel_id (SP_Field field, int reaction_mt, int decay_mode = 0) static inherited
channel id for reaction+decay
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
Field::SP b_field private
Referenced by ChannelType_Fiss::field_impl(), and ChannelType_Fiss::set_field_impl().
int b_reaction_mt private
Referenced by ChannelType_Fiss::reaction_mt_impl(), and ChannelType_Fiss::set_reaction_mt_impl().
The documentation for this class was generated from the following files:
Core/ts/ChannelType_Fiss.h
Core/ts/ChannelType_Fiss.cpp