ORIGEN API: Alpha Class Reference
Alpha Class Reference
#include <Species_FunPart.h>
Public Types
typedef SP_Species SP
strong pointer
typedef WP_Species WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Species>>
See Origen::Species for details.
int charge_number () const
void get_charge_number (int &charge_number) const
void set_charge_number (int charge_number)
bool has_initialized_charge_number () const
int mass_number () const
void get_mass_number (int &mass_number) const
void set_mass_number (int mass_number)
bool has_initialized_mass_number () const
double mass () const
void get_mass (double &mass) const
void set_mass (double mass)
bool has_initialized_mass () const
Private Member Functions
int charge_number_impl () const
int mass_number_impl () const
double mass_impl () const
std::string name_impl () const
int id_impl () const
bool good_impl (Vec_Str &errors) const
useful to chain
Member Typedef Documentation
typedef SP_Species SP inherited
strong pointer
typedef WP_Species WP inherited
weak pointer
Member Function Documentation
int charge_number_impl () const private virtual
Implements Species.
References Origen::ALPHA_CHARGE_NUMBER.
int mass_number_impl () const private virtual
Implements Species.
References Origen::ALPHA_MASS_NUMBER.
double mass_impl () const private virtual
Implements Species.
References Origen::ALPHA_MASS.
std::string name_impl () const private virtual
Reimplemented from Species.
int id_impl () const private virtual
Reimplemented from Species.
References Origen::ALPHA_BYPRODUCT_ID.
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Species.
int charge_number () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_charge_number_impl(), and TEST().
void get_charge_number (int & charge_number) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_charge_number (int charge_number) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_charge_number () const inherited
int mass_number () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_number_impl(), and TEST().
void get_mass_number (int & mass_number) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_mass_number (int mass_number) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_mass_number () const inherited
double mass () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_impl(), and TEST().
void get_mass (double & mass) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_mass (double mass) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_mass () const inherited
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Species_FunPart.h
Core/ts/Species_FunPart.cpp