ORIGEN API: Origen Namespace Reference
Origen Namespace Reference
Namespaces
detail
test
Classes
class Alpha
class AlphaField
fundamental particle field class: alpha field
class AlphaSpectra
Container for alpha spectrum data.
class BetaSpectra
Container for beta spectrum data.
class Case
class Channel
Defines the channel interface for the TransitionSystem.
class Channel_Gen
General-purpose implementation of the Channel interface.
class ChannelType
Defines the channel type interface for the TransitionSystem.
class ChannelType_Decay
Channel type for decay.
class ChannelType_Fiss
Channel type for fission.
class ChannelType_Reac
Channel type for (non-fission) reactions.
class Checkable
struct CompContainer
Struct to store compositions (always as number fractions)
class CompManager
Class for mixing up sweet materials.
class ConcentrationConverter
class Concentrations
Container for Concentrations data.
class DecayChannel
class DecayData
class DecayParent
class DecayResource
class DecayResourceIO
class DecayResourceIO_cimg
class Deuteron
class DeuteronField
fundamental particle field class: deuteron field
class Diff
simple interface for differs
class DiscreteSpectrum
defines a set of lines (energy points and intensities)
class Electron
class ElectronField
fundamental particle field class: electron field
class EmissionResource
class EmissionSpectrum
defines a continuous + discrete line spectra for a single nuclide
struct Energy
class EnergyResource
Computes kappa values for fission/capture based on izzzaaa lookup.
class FakeFactory
class Field
Defines the field interface for the TransitionSystem.
class Field_Gen
General-purpose implementation of the Field interface.
class GammaResource
class GammaResourceIO
class GammaResourceIO_cimg
class GammaSpectra
Container for gamma spectrum data.
class GridData_TransitionCoeff
Creates a GridData object for TransitionCoeff-based responses, used to interpolate TransitionCoeff objects.
class GridView
GridView provides a template for creating "views" of date usable with GridData to perform interpolation and "permute" interpolated types.
class GridView_State
class GridView_StateInfo
class GridView_TransitionCoeff
Viewer for interpolating TransitionCoeff data using GridData.
class Helion
class HelionField
fundamental particle field class: helion field
class History
struct implicitTag
struct LexicalOrderIZZZAAA
sorting function
class Library
class LibraryBuilder
class LibraryHeader
class LibraryIO
class LibraryIO_bof
class LibraryIO_s61
class LibraryIO_s62b
class LibraryType
class LocalDiff
class Material
Container for an ORIGEN depletable material.
class MaterialMap
Simple map of materials id->Origen::Material.
class MultiZoneDepleter
Performs one step of irradiation (potentially many substeps) for many materials, with a fixed transition matrix which resides on each material.
class Neutrino
class NeutrinoField
fundamental particle field class: neutrino field
class Neutron
class NeutronField
fundamental particle field class: neutron field
class NeutronSpectra
Container for gamma spectrum data.
class Nuclide
Defines the nuclide interface for the TransitionSystem.
class Nuclide_Gen
General-purpose implementation of the Nuclide interface.
class NuclideGroupFilter
class NuclideResource
class NuclideResourceIO
class NuclideResourceIO_json
class NuclideResourceIO_sclib
class NuclideSet
class Null
class NullField
fundamental particle field class: null field (for decay)
class Obiwan_convert
execute obiwan in convert mode
class Obiwan_diff
execute obiwan in diff mode
class Obiwan_info
execute obiwan in info mode
class Obiwan_interp
execute obiwan in interp mode
class Obiwan_patch
execute obiwan in patch mode
class Obiwan_tag
execute obiwan in tag mode
class Obiwan_view
execute obiwan in view mode
class Positron
class PositronField
fundamental particle field class: positron field
struct Power
class Proton
class ProtonField
fundamental particle field class: proton field
class Quantity
class ReactionResource
Multi-group cross section/yields resource.
class ReactionResourceIO
class ReactionResourceIO_ampx
class Solver
Interface satisfied ORIGEN single step depletion/decay solver.
class Solver_cram
CRAM depletion solver class satisfying Origen::solver.
class Solver_Fake
A fake solver satisfying the Origen::Solver interface.
class Solver_matrex
MATREX solver class satisfying Origen::solver.
class SolverSelector
Class for getting the selected solver.
class Species
Defines the species interface for the TransitionSystem.
class Species_Gen
General-purpose implementation of the Species interface.
class Spectrum
Container for spectrum data.
struct STab1
a simplified Tab1 container
class STab1Reader
simplified Tab1 reader
class STab1Writer
simplified Tab1 writeer
class State
Container for state data.
class StateInfo
Container for a State information tag.
class StateSet
class StateSetIO
class StateSetIO_bof
class StateSetIO_s61
class StateSetIO_s62b
class TagManager
TagManager class definition.
struct Time
class Transition
Defines the transition interface for the TransitionSystem.
class Transition_Gen
class Transition_GenByp
class TransitionCoeff
Container for transition coefficient data.
class TransitionGroupFilter
class TransitionMatrixP
class TransitionMatrixUpdater
class TransitionStructure
Container for transition structure data.
class TransitionSystem
Defines the interface TransitionSystem.
class TransitionSystem_Gen
General-purpose implementation of the TransitionSystem interface.
class TransitionSystemAdapter_AmpxN
class TransitionSystemAdapter_DecayResource
class TransitionSystemAdapter_TransitionMatrix
class Triton
class TritonField
fundamental particle field class: triton field
struct Unitless
class YieldData
class YieldParent
class YieldResource
class YieldResourceIO
class YieldResourceIO_stab1
Typedefs
typedef AlphaSpectra::SP SP_AlphaSpectra
typedef AlphaSpectra::SCP SCP_AlphaSpectra
typedef BetaSpectra::SP SP_BetaSpectra
typedef BetaSpectra::SCP SCP_BetaSpectra
typedef Concentrations::SP SP_Concentrations
typedef Concentrations::SCP SCP_Concentrations
typedef DecayData::SP SP_DecayData
typedef DecayData::SCP SCP_DecayData
typedef std::vector< double > Vec_Dbl
typedef Vec_Dbl EnergyBounds
typedef std::pair< double, double > Line
typedef std::set< Line, std::greater< Line > > Set_Line
typedef EmissionSpectrum::SP SP_Emission
typedef EmissionSpectrum::SCP SCP_Emission
typedef GammaSpectra::SP SP_GammaSpectra
typedef GammaSpectra::SCP SCP_GammaSpectra
typedef GridView_TransitionCoeff::SP SP_GridView_TransitionCoeff
typedef Quantity< Unitless > U
typedef Library::SP SP_Library
typedef Library::SCP SCP_Library
typedef LibraryHeader::SP SP_LibraryHeader
typedef LibraryHeader::SCP SCP_LibraryHeader
typedef std::shared_ptr< DoubleList > SP_DoubleList
typedef Origen::TransitionMatrixP TrMatrix
typedef std::shared_ptr< TrMatrix > SP_TrMatrix
typedef std::deque< SP_TrMatrix > Deq_TrMatrix
typedef std::deque< SP_DoubleList > Deq_Amt
typedef std::shared_ptr< MaterialBuffer > SP_MaterialBuffer
typedef std::shared_ptr< Material > SP_Material
typedef std::shared_ptr< MaterialMap > SP_MaterialMap
typedef NeutronSpectra::SP SP_NeutronSpectra
typedef NeutronSpectra::SCP SCP_NeutronSpectra
typedef NuclideSet::SP SP_NuclideSet
typedef NuclideSet::SCP SCP_NuclideSet
typedef Spectrum::SP SP_Spectrum
typedef Spectrum::SCP SCP_Spectrum
typedef State::SP SP_State
typedef State::SCP SCP_State
typedef StateInfo::SP SP_StateInfo
typedef StateInfo::SCP SCP_StateInfo
typedef std::pair< double, double > Pair_TB
typedef std::pair< Pair_TB, SCP_NeutronSpectra > Pair_NSpectra
typedef std::pair< Pair_TB, SCP_AlphaSpectra > Pair_ASpectra
typedef std::pair< Pair_TB, SCP_BetaSpectra > Pair_BSpectra
typedef std::pair< Pair_TB, SCP_GammaSpectra > Pair_GSpectra
typedef std::pair< Pair_TB, SCP_Concentrations > Pair_Concs
typedef std::vector< Pair_NSpectra > Vec_Pair_NSpectra
typedef std::vector< Pair_ASpectra > Vec_Pair_ASpectra
typedef std::vector< Pair_BSpectra > Vec_Pair_BSpectra
typedef std::vector< Pair_GSpectra > Vec_Pair_GSpectra
typedef std::vector< Pair_Concs > Vec_Pair_Concs
typedef std::vector< SP_State > Vec_SP_State
typedef std::shared_ptr< Vec_SP_State > SP_Vec_SP_State
typedef StateSet::SP SP_StateSet
typedef StateSet::SCP SCP_StateSet
typedef TagManager::SP SP_TagManager
typedef TagManager::SCP SCP_TagManager
typedef TransitionCoeff::SP SP_TransitionCoeff
typedef TransitionCoeff::SCP SCP_TransitionCoeff
typedef TransitionMatrixP::SP SP_TransitionMatrixP
typedef TransitionMatrixP::SCP SCP_TransitionMatrixP
typedef TransitionStructure::SP SP_TransitionStructure
typedef TransitionStructure::SCP SCP_TransitionStructure
typedef std::vector< std::string > Vec_Str
typedef std::vector< int > Vec_Int
typedef std::vector< float > Vec_Flt
typedef std::vector< size_t > Vec_Sze
typedef std::vector< bool > Vec_Bool
typedef std::deque< double > Deq_Dbl
typedef std::vector< Vec_Dbl > Vec_Vec_Dbl
typedef std::shared_ptr< Vec_Int > SP_Vec_Int
typedef std::shared_ptr< Vec_Dbl > SP_Vec_Dbl
typedef std::shared_ptr< Vec_Flt > SP_Vec_Flt
typedef std::shared_ptr< const Vec_Int > SCP_Vec_Int
typedef std::shared_ptr< const Vec_Dbl > SCP_Vec_Dbl
typedef std::shared_ptr< const Vec_Flt > SCP_Vec_Flt
typedef unsigned short int FieldId
typedef int NuclideId
typedef int SpeciesId
typedef int ByproductId
typedef std::pair< FieldId, int > ChannelTypeId_t
typedef std::map< int, size_t > IdMap
typedef std::shared_ptr< IdMap > SP_IdMap
typedef std::shared_ptr< const IdMap > SCP_IdMap
typedef std::pair< double, double > EnergyRange_t
typedef std::shared_ptr< Diff > SP_Diff
typedef std::shared_ptr< STab1 > SP_STab1
smart pointer
typedef DecayResource::SP SP_DecayResource
typedef DecayResource::SCP SCP_DecayResource
typedef EmissionResource::SP SP_EmissionResource
typedef EmissionResource::SCP SCP_EmissionResource
typedef GammaResource::SP SP_GammaResource
typedef GammaResource::SCP SCP_GammaResource
typedef NuclideResource::SP SP_NuclideResource
typedef NuclideResource::SCP SCP_NuclideResource
typedef ReactionResource::SP SP_ReactionResource
typedef ReactionResource::SCP SCP_ReactionResource
typedef std::map< int, int > FPMap_t
typedef std::map< int, int > ParentMap_t
typedef std::shared_ptr< YieldResource > SP_YieldResource
typedef TransitionSystem::SP SP_TransitionSystem
typedef std::shared_ptr< Species > SP_Species
typedef std::shared_ptr< Field > SP_Field
typedef std::shared_ptr< ChannelType > SP_ChannelType
typedef std::shared_ptr< Channel > SP_Channel
typedef std::shared_ptr< Nuclide > SP_Nuclide
typedef std::shared_ptr< Transition > SP_Transition
typedef Species * WP_Species
typedef Field * WP_Field
typedef ChannelType * WP_ChannelType
typedef Channel * WP_Channel
typedef Nuclide * WP_Nuclide
typedef Transition * WP_Transition
typedef TransitionSystem * WP_TransitionSystem
typedef const Species * CWP_Species
typedef const Field * CWP_Field
typedef const ChannelType * CWP_ChannelType
typedef const Channel * CWP_Channel
typedef const Nuclide * CWP_Nuclide
typedef const Transition * CWP_Transition
typedef const TransitionSystem * CWP_TransitionSystem
typedef std::map< ByproductId, int > ByproductCount_t
typedef std::shared_ptr< CompManager > SP_CompManager
typedef std::shared_ptr< MultiZoneDepleter > SP_MultiZoneDepleter
typedef std::shared_ptr< Solver > SP_Solver
typedef std::shared_ptr< const Solver > SCP_Solver
typedef std::shared_ptr< Solver_Fake > SP_Solver_Fake
typedef std::vector< Transition::WP > Vec_Trans
typedef ScaleData::MGFluxMapper< float > MGFluxMapper
typedef std::shared_ptr< MGFluxMapper > SP_MGFluxMapper
typedef std::shared_ptr< SolverSelector > SP_SolverSelector
typedef std::shared_ptr< const SolverSelector > SCP_SolverSelector
Enumerations
enum ConcentrationUnit {
NOT_GIVEN = -1, GATOMS = 0, ATOMS_B_CM = 1, GRAMS = 2,
CURIES = 3, ABSORPTIONS = 4, CAPTURES = 5, FISSIONS = 6,
AIRM_3 = 7, APELEM = 8, BECQUERELS = 9, GAMWATTS = 10,
GAMMEVS = 11, GPERCM_3 = 12, H2OM_3 = 13, KILOGRAMS = 14,
WPELEM = 15, WATTS = 16, MEVS = 17, PARTICLES_SEC = 18,
PARTICLES_SEC_MEV = 19, ENERGY_SEC_MEV = 20, MOLES = 21, CM_2_BARN = 22,
WPPM = 23, APPM = 24, LAST_CONCENTRATION_UNIT
}
enum Representation { CONSTANT = 0, LINEAR = 1 }
enum YieldType {
YIELD_UNKNOWN = 0, YIELD_SIMPLE = 1, YIELD_ISOMERIC = 2, YIELD_DISTRIBUTED = 3,
YIELD_MISSING = 4
}
Functions
string convertConcUnitToPrettyString (ConcentrationUnit unit)
string convertConcUnitToString (ConcentrationUnit unit)
ConcentrationUnit convertStringToConcUnit (const string &value)
int unitAsInt (const ConcentrationUnit &unit)
ConcentrationUnit intAsUnit (const int &unit)
bool isMassUnit (ConcentrationUnit unit)
bool isNumberUnit (ConcentrationUnit unit)
bool isDecayUnit (ConcentrationUnit unit)
bool isSpectrumUnit (ConcentrationUnit unit)
bool isReactionUnit (ConcentrationUnit unit)
bool isVolumetric (ConcentrationUnit unit)
bool needsVolumeToConvert (ConcentrationUnit unita, ConcentrationUnit unitb)
template<>
double Energy::base< Energy::JOULE > ()
template<>
double Energy::base< Energy::EV > ()
template<>
double Energy::base< Energy::KWH > ()
template<>
double Energy::base< Energy::MWD > ()
template<>
double Energy::base< Energy::GWD > ()
template<>
double Energy::base< Energy::GWYR > ()
template<>
std::string Energy::name< Energy::JOULE > ()
template<>
std::string Energy::name< Energy::EV > ()
template<>
std::string Energy::name< Energy::KWH > ()
template<>
std::string Energy::name< Energy::MWD > ()
template<>
std::string Energy::name< Energy::GWD > ()
template<>
std::string Energy::name< Energy::GWYR > ()
Vec_Int create_zzzaaai_seq1 (size_t total_nuclides)
NuclideSet createNuclideSet_random1 ()
Vec_Int createNuclideIds5 ()
Vec_Int createNuclideIds6 ()
DecayData createDecayData_random1 (const LibraryHeader &def)
TransitionStructure createTransitionStructure_random1 (const LibraryHeader &def)
TransitionCoeff createTransitionCoeff_random1 (const LibraryHeader &def)
template<>
double Unitless::base< Unitless::ONE > ()
template<>
std::string Unitless::name< Unitless::ONE > ()
double integrate_history (const Vec_Dbl &scaling, const Material::History_t &hist)
std::string h2string (const Material::History_t &hist)
template<>
double Power::base< Power::WATT > ()
template<>
std::string Power::name< Power::WATT > ()
void SerialRegistrar (Standard::SerialFactory *factory)
Registrar for serializable objects.
std::vector< implicitTag > checkImplicitTags (const std::vector< TagManager > &tagManList, const TagManager &tm)
Function to check the tag managers from a set of TagManagers (e.g., from a set of Library objects) to enssure that they have all of the tags requested in a reference TagManager. Then checks to see if the libraries have any other interpolable tags. If so, these are collected along with all of the values for that tag on all of the TagManagers and returned.
void addImpliedTags (const std::vector< implicitTag > &tagSpans, TagManager *tm, Vec_Str *dimNames)
Function to add unspecified interpolable tags to a reference tag manager with the average value of that tag over all libraries provided.
std::string parseTags (const std::string &str, Vec_Str *tags, Vec_Str *values, Vec_Bool *modify)
template<>
double Time::base< Time::SECONDS > ()
template<>
double Time::base< Time::MINUTES > ()
template<>
double Time::base< Time::HOURS > ()
template<>
double Time::base< Time::DAYS > ()
template<>
double Time::base< Time::YEARS > ()
template<>
std::string Time::name< Time::SECONDS > ()
template<>
std::string Time::name< Time::MINUTES > ()
template<>
std::string Time::name< Time::HOURS > ()
template<>
std::string Time::name< Time::DAYS > ()
template<>
std::string Time::name< Time::YEARS > ()
bool nuclide_in_bounds (const int n, const int ntotal)
bool only_set_component (const int mt_in)
void toQString_tinds_2d (const IntegerList &nind_list, const IntegerList &transition_ids, const Integer2dList &tinds_2d)
void read (const bof::BOFObject &obj, TagManager &tag_manager)
read a tag manager from a bof object
void read (const bof::BOFObject &obj, std::string name, TagManager &tag_manager)
read a tag manager from a bof object
void write (bof::BOFObject &obj, std::string name, const TagManager &tag_manager)
write a tag manager to a bof object
void write (bof::BOFObject &obj, const TagManager &tag_manager)
write a tag manager to a bof object
void read (const bof::BOFObject &obj, std::string name, StateInfo &states_info)
read state info from a bof object
void read (const bof::BOFObject &obj, StateInfo &states_info)
read state info from a bof object
void write (bof::BOFObject &obj, std::string name, const StateInfo &states_info)
write state info to a bof object
void write (bof::BOFObject &obj, const StateInfo &states_info)
write state info to a bof object
SP_Diff diffLibrary (const Library &a, const Library &b, int pos, double reltol)
std::string diffConcentrations (const Concentrations &a, const Concentrations &b, double reltol)
template<typename T >
std::string diffLine (const std::string &head, const T &val1, const T &val2, float tol=1.0e-5)
template<typename T >
std::string diffHalfLine (const std::string &head, const T &val, const int &side)
void graphvizLibrary (const Library &lib, int pos, std::ostream &os)
void graphvizLibrary (const Library &lib, int pos, const std::vector< double > *numden, const NuclideGroupFilter &nfilter, const TransitionGroupFilter &tfilter, bool include_byproducts, std::ostream &os)
SP_Library interpLibraryND (const std::vector< TagManager > &tagManList, const TagManager &tm)
SP_Library interpLibraryND (const std::vector< SCP_Library > &, const TagManager &)
on-disk
std::vector< TagManager > selectLibraries (const std::vector< TagManager > &tmList, const TagManager &tmRef)
Function to take a wide selection of Origen Libraries in memory and only return those that have the ID and Interp tags requested in the provided TagManager. Then checks to make sure the ID tag values match.
std::vector< SCP_Library > selectLibraries (const std::vector< SCP_Library > &libList, const TagManager &tmRef)
Function to take a wide selection of Origen Libraries in memory and only return those that have the ID and Interp tags requested in the provided TagManager. Then checks to make sure the ID tag values match.
std::vector< SP_TagManager > collectLibraries (const std::vector< std::string > &lib_names)
Function that accepts names of Origen library files on disk which can be full paths if necessary.
std::vector< SP_TagManager > collectLibrariesParallel (const std::vector< std::string > &lib_names)
Function that accepts names of Origen library files on disk which can be full paths if necessary.
bool setbuLibrary (Library &obj, ScaleUtils::IO::DB &opts)
bool thinLibrary (Library &obj, ScaleUtils::IO::DB &opts)
bool convertLibrary (Library &obj, const std::string &path, ScaleUtils::IO::DB &opts)
bool convertStateSet (StateSet &obj, const std::string &path, ScaleUtils::IO::DB &opts)
void * loadMulti (const std::string &path, ScaleUtils::IO::DB &opts)
void saveStateSet (const MaterialMap &matmap, const std::string &path, ScaleUtils::IO::DB opts)
saves all isotopics in a MaterialMap to an FT71 (StateSet)
void saveStateSet (size_t pstart, size_t pend, const MaterialMap &matmap, const std::string &path, ScaleUtils::IO::DB opts)
void saveLibraries (size_t pstart, size_t pend, const MaterialMap &matmap, const std::string &pathfmt, ScaleUtils::IO::DB opts)
void setAppVersionWrite (bof::BOFWriter &writer, ScaleUtils::IO::DB &opts, const std::string &name)
std::string stringifySublib (int sublib)
std::string stringifyNuclide (int id, std::string idform)
idform can include various symbols to be substituted
void populateLossXsValues (DoubleList *times, DoubleList *responseValues, const Library &obj, const int nind)
void populateNuclideResource_StdComp (NuclideResource *nr, const ScaleData::StdComp &stdcomp)
populate a nuclide resource (in place) from a ScaleData::StdComp object
std::map< int, double > construct_neutron_yields_map (const Library &x, int pos)
std::map< int, double > construct_neutron_prod_map (const Library &x, int pos)
std::map< std::pair< int, int >, double > construct_coeff_map (const Library &x, int pos)
void populateLibraryToxicity_DecayResource (Library *lib, const DecayResource &dr)
populate a library with toxicity factors from a decay resource
void populateLibraryAbundance (Library *lib, const ScaleUtils::IO::DB &opts)
populate a library with abundances from a nuclide resource
void populateLibraryAbundance_NuclideResource (Library *lib, const NuclideResource &nr)
populate a library with abundances from a nuclide resource
void populateLibraryMass_NuclideResource (Library *lib, const NuclideResource &nr)
populate a library with mass from a nuclide resource
void populateLibraryDecayEnergy_DecayResource (Library *lib, const DecayResource &dr)
populate decay energy
void populateCurrentTimes (int *year, int *month, int *day)
void populateLibraryHeader_YieldResource (LibraryHeader *lh, const Vec_Int &sizzzaaa_list, const YieldResource &yr, Vec_Int *fissionable_ids)
void populateFissionables (Vec_Int *fissionable_ids, const Vec_Int &sizzzaaa_list, const Vec_Int &transition_ids, const Vec_Int &parent_positions)
void populateMass_ids (std::vector< float > *masses, const std::vector< int > &sizzzaaa_list)
grabs the masses to use for each nuclide (mass number, A)
template<typename DirectYields_t >
std::map< int, CrossSection1d * > collect_direct_yields (int izzzaaa, LibraryNuclide *ampx_nuclide, const DirectYields_t &direct_yields)
void populateReactionResource_AmpxLibrary (ReactionResource *rr, const AmpxLibrary &ampx)
void populateEnergyBounds_AmpxLibrary (Vec_Flt *bounds, const AmpxLibrary &ampx)
void populateVec_CrossSection1d (Vec_Flt *vec, const CrossSection1d &xs1d)
void populateFlux_AmpxLibrary (Vec_Flt *flux, const AmpxLibrary &ampx, int mix_id, int flux_nuclide_id, int flux_mt)
void populateLibraryMass (Library *lib, const ScaleUtils::IO::DB &opts)
void populateObiwan_dataType (ScaleUtils::IO::DB *base, const std::string &type)
void populateXs_CrossSection1d (Vec_Flt *xs, const CrossSection1d &xs1d)
void printReactionTransitions (const LibraryHeader &lh, const TransitionStructure &tm, bool output_zeros, const std::string &idform, std::ostream &stream)
prints reaction transitions on a library
void printReactionTransitions (const Library &lib, bool output_zeros, const std::string &idform, std::ostream &stream)
prints reaction transitions on a library
void printDecayTable (const DecayResource &dr, std::ostream &stream)
prints all decay info on the library
void printInterpolatedYields (const YieldResource &yr, const int id, const double energy, const int interp, std::ostream &stream)
void printYields (const YieldResource &yr, std::ostream &os)
void printYieldEnergies (const YieldResource &yr, std::ostream &os)
void printIdTags_json (const Library &lib, std::ostream &os)
void printInterpTags_json (const Library &lib, std::ostream &os)
void printTags_json (const Library &lib, const std::string &file, std::ostream &os)
void printTable (bool transpose, Table2D *table, std::ostream &os)
void printNuclideInfo (const Library &lib, int sizzzaaa, bool transpose, const std::string &idform, int prec, std::ostream &os)
void printBurnups (const Library &lib, bool transpose, int prec, std::ostream &os)
void printFissionXs (const Library &lib, int sizzzaaa, bool transpose, const std::string &idform, int prec, int pos, std::ostream &os)
void printLossXs (const Library &lib, int sizzzaaa, bool transpose, const std::string &idform, int prec, int pos, std::ostream &os)
void printTransitionCoeff (const Library &lib, int sizzzaaa, int tid, bool transpose, bool output_zeros, double flux, bool output_transition_ids, const std::string &idform, int prec, int pos, std::ostream &os)
void printConcentrations_csv (const StateSet &f71, ConcentrationUnit concUnit, SP_Library library, const std::string &idform, std::ostream &os)
std::string createContentString (const State &state)
void printStateInfo (const StateSet &state_set, int start_position, std::ostream &os)
prints information describing the state_set
void printTags_json (const StateSet &state_set, std::ostream &os)
prints information describing the state_set
void printNeutronProductionRatio (const Library &x, int pos, std::ostream &os)
void printNeutronYields (const Library &x, int pos, std::ostream &os)
void printTimingReport (std::ostream &os)
void printTransitionSystemXs (const TransitionSystem &ts, std::ostream &os)
void printConcentrations_csv (const StateSet &f71, ConcentrationUnit concUnit, std::shared_ptr< Library > library=nullptr, const std::string &idform="$S$I$ZZZ$AAA", std::ostream &os=std::cout)
template<typename T >
void printLine_csv (std::string id, const std::vector< T > &vals, std::ostream &os=std::cout)
template<typename T >
void printList (const char *name, T *list, std::ostream &os=std::cout)
void printTable (bool transpose, ScaleUtils::IO::Table2D *table, std::ostream &os=std::cout)
void tabulateNuclideLabel (const Vec_Int &ids, int sizzzaaa, const std::string &idform, const std::string &units_row, Table2D *table)
void tabulateInitialNuclideColumns (const Vec_Int &ids, ScaleUtils::IO::Table2D *table)
std::vector< const TransitionCoeff * > getTransitionCoeffList (const Library &lib)
void getPosRange (size_t max_size, int pos, size_t &first_index, size_t &last_index)
void tabulateNuclideInfo (const Library &lib, int sizzzaaa, const std::string &idform, int prec, Table2D *table)
void tabulateFissionXs (const Library &lib, int sizzzaaa, const std::string &idform, int prec, int pos, Table2D *table)
void tabulateLossXs (const Library &lib, int sizzzaaa, const std::string &idform, int prec, int pos, const std::string &column_name, bool append_column, Table2D *table)
void tabulateLossXs (const LibraryHeader &lh, const std::vector< const TransitionCoeff * > &tcoeff_list, int sizzzaaa, const std::string &idform, int prec, int pos, const std::string &column_name, bool append_column, Table2D *table)
void tabulateReactionTransitions (const LibraryHeader &lh, const TransitionStructure &tm, bool output_zeros, const std::string &idform, Table2D *table)
void tabulateTransitionCoeff (const LibraryHeader &lh, const TransitionStructure &tm, const std::vector< const TransitionCoeff * > &tcoeff_list, int sizzzaaa, int tid, bool output_zeros, double flux, bool output_transition_ids, const std::string &idform, int prec, int pos, Table2D *table)
void tabulateTransitionCoeff (const Library &lib, int sizzzaaa, int tid, bool output_zeros, double flux, bool output_transition_ids, const std::string &idform, int prec, int pos, Table2D *table)
void tabulateBurnups (const Library &lib, int prec, Table2D *table)
void tabulateMaterialIsotopics (const Material &mat, size_t point, ScaleUtils::IO::Table2D *table, SCP_Vec_Int &base_ids)
void tabulateMaterialTransitionRates (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, SCP_TransitionStructure &base_tstruct)
void tabulateMaterialLoss (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append, int type)
void tabulateMaterialLossXs (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append)
void tabulateMaterialLossRate (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append)
void tabulateMaterialDecayConstant (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append)
void tabulateMaterialFission (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append, int type)
void tabulateMaterialFissionXs (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append)
void tabulateMaterialFissionRate (const Material &mat, size_t step, ScaleUtils::IO::Table2D *table, bool &append)
void tabulateNuclideLabel (const LibraryHeader &lh, int sizzzaaa, const std::string &idform, const std::string &units_row, ScaleUtils::IO::Table2D *table)
void tabulateNuclideInfo (const Library &lib, int sizzzaaa, const std::string &idform, int prec, ScaleUtils::IO::Table2D *table)
void tabulateFissionXs (const Library &lib, int sizzzaaa, const std::string &idform, int prec, int pos, ScaleUtils::IO::Table2D *table)
void tabulateLossXs (const Library &lib, int sizzzaaa, const std::string &idform, int prec, int pos, const std::string &column_name, bool append_column, ScaleUtils::IO::Table2D *table)
void tabulateLossXs (const LibraryHeader &lh, const std::vector< const TransitionCoeff * > &tcoeff_list, int sizzzaaa, const std::string &idform, int prec, int pos, const std::string &column_name, bool append_column, ScaleUtils::IO::Table2D *table)
void tabulateTransitionCoeff (const Library &lib, int sizzzaaa, int tid, bool output_zeros, double flux, bool transition_ids, const std::string &idform, int prec, int pos, ScaleUtils::IO::Table2D *table)
void tabulateTransitionCoeff (const LibraryHeader &lh, const TransitionStructure &tm, const std::vector< const TransitionCoeff * > &tcoeff_list, int sizzzaaa, int tid, bool output_zeros, double flux, bool transition_ids, const std::string &idform, int prec, int pos, ScaleUtils::IO::Table2D *table)
void tabulateBurnups (const Library &lib, int prec, ScaleUtils::IO::Table2D *table)
void tabulateReactionTransitions (const LibraryHeader &lh, const TransitionStructure &tm, bool output_zeros, const std::string &idform, ScaleUtils::IO::Table2D *table)
DecayResource * loadDecayResource (const Str path, ScaleUtils::IO::DB opts)
bool saveDecayResource (const DecayResource &obj, const Str path, ScaleUtils::IO::DB opts)
GammaResource * loadGammaResource (const Str path, ScaleUtils::IO::DB opts)
bool saveGammaResource (const GammaResource &obj, const Str path, ScaleUtils::IO::DB opts)
double guess_last_bin_energy (size_t nc, Vec_Dbl &e, size_t next)
Library * loadLibrary (const Str path, ScaleUtils::IO::DB opts)
bool saveLibrary (const Library &obj, const Str path, ScaleUtils::IO::DB opts)
char endian_selector (const std::string &end)
NuclideResource * loadNuclideResource (const Str path, ScaleUtils::IO::DB opts)
bool saveNuclideResource (const NuclideResource &obj, const Str path, ScaleUtils::IO::DB opts)
ReactionResource * loadReactionResource (const Str path, ScaleUtils::IO::DB opts)
bool saveReactionResource (const ReactionResource &obj, const Str path, ScaleUtils::IO::DB opts)
StateSet * loadStateSet (const Str path, ScaleUtils::IO::DB opts)
bool saveStateSet (const StateSet &obj, const Str path, ScaleUtils::IO::DB opts)
YieldResource * loadYieldResource (const Str path, ScaleUtils::IO::DB opts)
bool saveYieldResource (const YieldResource &obj, const Str path, ScaleUtils::IO::DB opts)
std::string _to_id_string (int id)
void defaultNuclideResource (Origen::NuclideResource *nr)
add default contents to a nuclide resource
void get_default_kappas (const std::vector< int > &sizzzaaa_list, std::vector< float > &kappa_capture, std::vector< float > &kappa_fission)
bool id_matches (SP_Transition transition, int product_id)
std::string yield_type_name (const YieldType yt)
ScaleUtils::IO::DB baseOptions (Standard::CommandLine &cmd)
int info (const StateSet &state_set, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
int info (const Library &lib, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
int info (const DecayResource &dr, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
int info (const YieldResource &yr, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
static ScaleUtils::IO::DB baseOptions ()
std::string splash ()
std::string random_line (std::string mode)
std::string help ()
int obiwan_main (Vec_Str args, std::ostream &out, std::ostream &err)
int obiwan_main (int argc, char **argv, std::ostream &out, std::ostream &err)
std::string applyPatch (SP_Library fromLib, IntegerList *coeffPosList, const std::string &coeffData, SP_Library lib, int pos)
static ScaleUtils::IO::DB baseOptions ()
int view (const Origen::Library &lib, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
int view (const StateSet &state_set, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
int view (const DecayResource &decay_resource, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
int view (const YieldResource &yield_resource, ScaleUtils::IO::DB opts, std::ostream &out, std::ostream &err)
const char * version ()
const char * config (const char *field="")
std::string doIndent (int indent)
std::string toYesNo (bool yes_no)
void setup_search_variables (const std::vector< NuclideId > &in_sizzzaaa_list, std::map< NuclideId, size_t > &nind_lookup)
bool check_sizes (size_t total_nuclides, size_t total_transitions, std::vector< int > &num_decay_parents, std::vector< int > &num_parents, std::vector< int > &parent_positions, std::vector< int > &transition_ids, std::vector< double > &transition_coeff)
template<typename T >
void vector_copy (size_t nelem, size_t start, const std::vector< T > *old_list, std::vector< T > &new_list)
template<typename T >
void shrink_to_fit (std::vector< T > &x)
double calculate_neutron_production_xs (SP_Nuclide residual)
template<typename TS_t , typename DirectYields_t >
std::map< int, std::pair< CrossSection1d *, SP_Transition > > collect_direct_yields (SP_Field neutron_field, SP_Nuclide nuclide, int izzzaaa, TS_t ts, LibraryNuclide *ampx_nuclide, const DirectYields_t &direct_yields)
Variables
const int TIME_S = 1
const int TIME_M = 2
const int TIME_H = 3
const int TIME_D = 4
const int TIME_Y = 5
const int SUBLIB_LEGACY_ELEMENT = 4
const double EMIN = 1e-99
const double EMAX = 1e+99
const double ETOL = 1e-11
const double ERR = 1.0e-44
const int BAD_INT = std::numeric_limits<int>::max()
const double BAD_DOUBLE = std::numeric_limits<double>::max()
const float BAD_FLOAT = std::numeric_limits<float>::max()
const size_t BAD_SIZE_T = std::numeric_limits<size_t>::max() / 2 - 1
const double BRANCH_RATIO_TOLERANCE
const double YIELD_TOLERANCE = 100 * std::numeric_limits<float>::epsilon()
const double MAXIMUM_MASSNUMBER_LOST = 0.3
const double MAXIMUM_MASS_LOST = 0.01
const double MAXIMUM_ZZZAAA_LOST = 0.5
const double NUCLEON_TOLERANCE = 1e-6
const double MINIMUM_HEAVY_PARTICLE_MASS = 0.5
const double NEUTRON_MASS = 1.00866491600
const double PROTON_MASS = 1.007276466812
const double ELECTRON_MASS = 5.4857990946e-4
const double DEUTERON_MASS = 2.013553212712
const double TRITON_MASS = 3.0155007134
const double HELION_MASS = 3.0149322468
const double ALPHA_MASS = 4.001506179125
const double POSITRON_MASS = 5.4857990946e-4
const double NEUTRINO_MASS = 1e-20
const double NULL_MASS = 0.0
const int SUBLIB_1LT = 1
const int SUBLIB_2AC = 2
const int SUBLIB_3FP = 3
const int SUBLIB_4U1 = 4
const int SUBLIB_5U2 = 5
const int SUBLIB_6U3 = 6
const int SUBLIB_7U4 = 7
const int SUBLIB_8TA = 8
const int SUBLIB_9BY = 9
const FieldId NULL_FIELD = 0
field numbers used when accessing fields by FieldId
const FieldId NEUTRON_FIELD = 1
const FieldId PROTON_FIELD = 2
const FieldId DEUTERON_FIELD = 3
const FieldId TRITON_FIELD = 4
const FieldId HELION_FIELD = 5
const FieldId ALPHA_FIELD = 6
const FieldId ELECTRON_FIELD = 7
const FieldId POSITRON_FIELD = 8
const FieldId PHOTON_FIELD = 9
const FieldId NEUTRINO_FIELD = 10
const ByproductId NULL_BYPRODUCT_ID = BAD_INT
byproduct ids used when accessing byproducts by ByproductId
const ByproductId NEUTRON_BYPRODUCT_ID = 1
const ByproductId PROTON_BYPRODUCT_ID = 1001
const ByproductId DEUTERON_BYPRODUCT_ID = 1002
const ByproductId TRITON_BYPRODUCT_ID = 1003
const ByproductId HELION_BYPRODUCT_ID = 2003
const ByproductId ALPHA_BYPRODUCT_ID = 2004
const ByproductId ELECTRON_BYPRODUCT_ID = -1000
const ByproductId POSITRON_BYPRODUCT_ID = 1000
const ByproductId NEUTRINO_BYPRODUCT_ID = 0
const int NEUTRON_MASS_NUMBER = 1
mass numbers
const int PROTON_MASS_NUMBER = 1
const int DEUTERON_MASS_NUMBER = 2
const int TRITON_MASS_NUMBER = 3
const int HELION_MASS_NUMBER = 3
const int ALPHA_MASS_NUMBER = 4
const int ELECTRON_MASS_NUMBER = 0
const int POSITRON_MASS_NUMBER = 0
const int NEUTRINO_MASS_NUMBER = 0
const int NULL_MASS_NUMBER = 0
const int NEUTRON_CHARGE_NUMBER = 0
charge/atomic numbers
const int PROTON_CHARGE_NUMBER = 1
const int DEUTERON_CHARGE_NUMBER = 1
const int TRITON_CHARGE_NUMBER = 1
const int HELION_CHARGE_NUMBER = 2
const int ALPHA_CHARGE_NUMBER = 2
const int ELECTRON_CHARGE_NUMBER = -1
const int POSITRON_CHARGE_NUMBER = +1
const int NEUTRINO_CHARGE_NUMBER = 0
const int NULL_CHARGE_NUMBER = 0
static const int INTERP_PREFERRED = 0
static const int INTERP_HISTOGRAM = 1
static const int INTERP_LINLIN = 2
static const int INTERP_LINLOG = 3
static const int INTERP_LOGLIN = 4
static const int INTERP_LOGLOG = 5
static const int IMPLICIT_BYPRODUCT_MAX_MASSNUMBER = 4
Detailed Description
This description has been copied from the SCALE 6.1 Manual, pg. F7.A.1, the section titled "F7.A. DESCRIPTION OF CONCENTRATION BINARY FILES". Only minor formatting adjustments have been made.
The concentrations, in units gram-atoms, of all the ORIGEN-S nuclides may be saved to the binary file associated with unit NXTR, by applying the unit number input in the 0$ data or the default of 71 (which makes the file named ft71f001). These concentrations may be read in a subsequent run to define the initial concentrations for a restart case. The input descriptions in Sects. F7.6.3 and F7.6.4 have details of using NXCMP in the 56$ data to apply input from NXTR or using MOUT and MSUB in the 56$ data to save concentrations and spectral data at requested time steps on unit NXTR. There are other uses of unit NXTR, related to creating certain photon libraries, that should not be applied if concentrations are wanted. All of the data associated with a given time step are saved in two binary records. The position of each of these pair of records is dependent upon the order in which the time step is saved. If data at a given position are read from NXTR (e.g., restart case), the first subsequent time step saved will be located in the next position after that of the input time step record. It is recommended that the user copy the file before using it, particularly if data following that input needs to be saved and is to be written over. At the end of a job in which data are saved in NXTR, the first record of the pair described above is written again with the first variable set to zero, making a termination record. The remaining variables are not used. Also, arrays pertaining to spectral data that were not requested by the input would have meaningless data and should not be used. The first record, in the pair discussed above, is always written with the same set of variables. The three Fortran 90 write statements are as follows:
!Record Type 1
write (unit=n96) itxx, ilite, iact, ifp, nrflag, msub1, nstepo, &
    kasepo, jobpos, nocs, noblnd, ndset, ntype, ngrp, nelem, &
    nvert, ng, mmn, mout, index, mstar, nunit, kblend, nenle, &
    nenac, nenfp, l1, l2, l3, l4, tmo, fracpw, tconst, tunit, &
    twrite, pwrite, fwrite
!Record Type 2
write (unit=n96) (nucl(i),i=1,itot), (x(msub1,j),j=1,itot), &
    title, basis, (egamle(i1),i1=1,n1), (egamac(i2),i2=1,n2), &
    (egamfp(i3),i3=1,n3), (specle(i4,msub),i4=1,l1), &
    (specac(i5,msub),i5=1,l2), (specfp(i6,msub),i6=1,l3), &
    (ener(i7),i7=1,n4), (dsav(i8,msub),i8=1,ng), &
    (esav(i9,msub),i9=1,ng), (itsav(i10,msub),i10=1,20), &
    (spnnuc(i11,msub),i11=1,l4),(alpnuc(i12,msub),i12=1,l4), &
    (spneut(i13,msub),i13=1,ngrp), & (specan(i14,msub),i14=1,ngrp), &
    (specsp(i15,msub),i15=1,ngrp),(eneuts(i16),i16=1,n5)
where
n2 = nenac + 1
n3 = nenfp + 1
n4 = ng + 1
n5 = ngrp + 1
The variable and array descriptions below indicate the position of the listed variable, the variable name, the size of an array or a character variable, and the variables definition or meaning. The first record contains only integers, except for one character variable, TUNIT. Most of the values are sizes of libraries, spectrum energy-group sizes, or other array sizes. Some values indicate the data position in the file. Some are code flags or triggers used in specifying data. The second type of record contains only arrays, either numerical or character types, where the sizes are either given or readily obtained (e.g., by adding one) from the first record values. The spectra energy-group structures are in ascending order. The gamma spectra may pertain to all nuclides in the problem, or a subset of nuclides (e.g., actinides only) as determined from the case input description used to generate the spectra.
The first record description follows.
Record Type 1
ITXX total number of nuclides or '0' to signal an end-of-file
ILITE number of nuclides in light element library - 0 if not using
IACT number of nuclides in actinide library - 0 if not using
IFP number of nuclides in fission product library - 0 if not using
NRFLAG flag that determines position numbers for data set to be saved
MSUB1 time step number of the data to be saved
NSTEPO position of requested data in concentration file
KASEPO position of the requested case in the concentration file
JOBPOS position in the file of the job containing the requested data
NOCS case number in the case containing the requested data
NOBLND 0/1/N job termination/no blending/N streams blended
NDSET nuclear data library unit number
NTYPE the type of library on NDSET, 0/>0 card-image/binary library
NGRP the number of neutron energy groups
NELEM maximum atomic number of nuclides in library
NVERT -N/0/N request integral option and writing N/not wanted/reading N
NG the number of photon energy groups in the master photon library
MMN number of irradiation time-step intervals in a case
MOUT controls writing concentrations on unit NXTR If MOUT=0 and MSUB=m, concentration for time step m is written If MOUT=-N and MSUB>= 0, concentrations for time steps MSUB through N, inclusive, are written
INDEX 0/1 power read in 58* array/flux read in 59* array
MSTAR time step at which concentration print cutoffs are applied
NUNIT 1/2/3/4/5/6 time (in 60*) units s/min/h/d/y/other
KBLEND time-step number indicating when blending is to occur
NENLE number of groups in light element photon library
NENAC number of groups in actinide photon library
NENFP number of groups in fission product photon library
L1 max0(1, NENLE)
L2 max0(1, NENAC)
L3 max0(1, NANFP)
L4 max0(1, IACT)
TMO time at start of first time step
FRACPW ratio of case irradiation time to total case irradiation time
TCONST If NUNIT=6, number of seconds in the special time unit.
TUNIT time unit printed in output (4-character variable)
TWRITE value of time-step accumulative time of concentrations written in file
PWRITE value of time-step power of concentrations written in file
FWRITE value of time-step flux of concentrations written in the file
Record Type 2
NUCL(ITXX) ITXX values of nuclide IDs as ZAS (Z=atomic number, A=mass number, S=metastable state, S=0 for ground state) X(ITXX) ITXX values of gram-atom concentrations, at step requested MSUB TITLE(20) 80-character title for this case if NTI=1 or 3 BASIS(10) 40-character title for basis of calculation - may be blank if NTI=2 or 3 EGAMLE(NENLE+1) Gamma group boundaries for light elements EGAMAC(NENAC +1) Gamma group boundaries for actinides EGAMFP(NENFP +1) Gamma group boundaries for fission products SPECLE(L1) L1 values of gamma source spectrum for light elements in photons/s SPECAC(L2) L2 values of gamma source spectrum for actinides in photons/s SPECFP(L3) L3 values of gamma source spectrum for fission products in photons/s ENER(NG+1) NG +1 values of gamma energy group boundaries on master photon library DSAV(NG) NG values of master photon spectrum in photons/s ESAV(NG) NG values of master photon spectrum in MeV/s ITSAV(20) 80-character photon spectrum title SPNNUC(L4) L4 values of spontaneous fission neutron source in neutrons/s ALPNUC(L4) L4 values of actinide nuclide (,n) source in neutrons/s SPNEUT(NGRP) NGRP values of total neutron spectrum in neutrons/s SPECAN(NGRP) NGRP values of (,n) spectrum in neutrons/s SPECSP(NGRP) NGRP values of spontaneous fission neutron spectrum in neutrons/s ENEUTS(NGRP+1) NGRP+1 Neutron energy-group boundaries
For each time step, ORIGEN writes one of each of these record types.
Typedef Documentation
typedef AlphaSpectra::SP SP_AlphaSpectra
typedef AlphaSpectra::SCP SCP_AlphaSpectra
typedef BetaSpectra::SP SP_BetaSpectra
typedef BetaSpectra::SCP SCP_BetaSpectra
typedef Concentrations::SP SP_Concentrations
typedef Concentrations::SCP SCP_Concentrations
typedef DecayData::SP SP_DecayData
typedef DecayData::SCP SCP_DecayData
typedef Vec_Dbl EnergyBounds
typedef std::pair<double, double> Line
typedef std::set<Line, std::greater<Line> > Set_Line
typedef EmissionSpectrum::SP SP_Emission
typedef EmissionSpectrum::SCP SCP_Emission
typedef GammaSpectra::SP SP_GammaSpectra
typedef GammaSpectra::SCP SCP_GammaSpectra
typedef GridView_TransitionCoeff::SP SP_GridView_TransitionCoeff
typedef Quantity<Unitless> U
typedef Library::SP SP_Library
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstMaterial.cpp, Core/io/tests/tstLibraryIO.cpp, Core/io/tests/tstMaterialBuffer.cpp, Manager/mzd/tests/tstParallelDepletion.cpp, and Solver/cram/src/tests/tstCRAM.cpp.
typedef Library::SCP SCP_Library
typedef LibraryHeader::SP SP_LibraryHeader
typedef LibraryHeader::SCP SCP_LibraryHeader
typedef std::shared_ptr<DoubleList> SP_DoubleList
typedef Origen::TransitionMatrixP TrMatrix
typedef std::shared_ptr<TrMatrix> SP_TrMatrix
typedef std::deque<SP_TrMatrix> Deq_TrMatrix
typedef std::deque<SP_DoubleList> Deq_Amt
typedef std::shared_ptr<MaterialBuffer> SP_MaterialBuffer
typedef std::shared_ptr<Material> SP_Material
typedef std::shared_ptr<MaterialMap> SP_MaterialMap
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
typedef NeutronSpectra::SP SP_NeutronSpectra
typedef NeutronSpectra::SCP SCP_NeutronSpectra
typedef NuclideSet::SP SP_NuclideSet
typedef NuclideSet::SCP SCP_NuclideSet
typedef Spectrum::SP SP_Spectrum
typedef Spectrum::SCP SCP_Spectrum
typedef State::SP SP_State
typedef State::SCP SCP_State
typedef StateInfo::SP SP_StateInfo
typedef StateInfo::SCP SCP_StateInfo
typedef std::pair<double, double> Pair_TB
typedef std::pair<Pair_TB, SCP_NeutronSpectra> Pair_NSpectra
typedef std::pair<Pair_TB, SCP_AlphaSpectra> Pair_ASpectra
typedef std::pair<Pair_TB, SCP_BetaSpectra> Pair_BSpectra
typedef std::pair<Pair_TB, SCP_GammaSpectra> Pair_GSpectra
typedef std::pair<Pair_TB, SCP_Concentrations> Pair_Concs
typedef std::vector<Pair_NSpectra> Vec_Pair_NSpectra
typedef std::vector<Pair_ASpectra> Vec_Pair_ASpectra
typedef std::vector<Pair_BSpectra> Vec_Pair_BSpectra
typedef std::vector<Pair_GSpectra> Vec_Pair_GSpectra
typedef std::vector<Pair_Concs> Vec_Pair_Concs
typedef std::vector<SP_State> Vec_SP_State
typedef std::shared_ptr<Vec_SP_State> SP_Vec_SP_State
typedef StateSet::SP SP_StateSet
Examples:
Core/fn/tests/tstio.cpp, and Core/io/tests/tstStateSetIO.cpp.
typedef StateSet::SCP SCP_StateSet
typedef TagManager::SP SP_TagManager
Examples:
Core/dc/tests/tstGridView.cpp, and Core/dc/tests/tstTagManager.cpp.
typedef TagManager::SCP SCP_TagManager
typedef TransitionCoeff::SP SP_TransitionCoeff
Examples:
Core/dc/tests/tstLibrary.cpp, and Core/fn/tests/tstinterp.cpp.
typedef TransitionCoeff::SCP SCP_TransitionCoeff
typedef TransitionMatrixP::SP SP_TransitionMatrixP
Examples:
Solver/matrex/tests/tstSolver_matrex.cpp.
typedef TransitionMatrixP::SCP SCP_TransitionMatrixP
typedef TransitionStructure::SP SP_TransitionStructure
typedef TransitionStructure::SCP SCP_TransitionStructure
typedef std::shared_ptr<Diff> SP_Diff
typedef std::shared_ptr<STab1> SP_STab1
smart pointer
typedef DecayResource::SP SP_DecayResource
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
typedef DecayResource::SCP SCP_DecayResource
typedef EmissionResource::SP SP_EmissionResource
typedef EmissionResource::SCP SCP_EmissionResource
typedef GammaResource::SP SP_GammaResource
typedef GammaResource::SCP SCP_GammaResource
typedef NuclideResource::SP SP_NuclideResource
typedef NuclideResource::SCP SCP_NuclideResource
typedef ReactionResource::SP SP_ReactionResource
typedef ReactionResource::SCP SCP_ReactionResource
typedef std::map<int, int> FPMap_t
typedef std::map<int, int> ParentMap_t
typedef std::shared_ptr<YieldResource> SP_YieldResource
typedef std::shared_ptr< TransitionSystem > SP_TransitionSystem
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
typedef std::shared_ptr<Species> SP_Species
typedef std::shared_ptr<Field> SP_Field
typedef std::shared_ptr<ChannelType> SP_ChannelType
typedef std::shared_ptr<Channel> SP_Channel
typedef std::shared_ptr<Nuclide> SP_Nuclide
typedef std::shared_ptr<Transition> SP_Transition
typedef Species* WP_Species
typedef Field* WP_Field
typedef ChannelType* WP_ChannelType
typedef Channel* WP_Channel
typedef Nuclide* WP_Nuclide
typedef Transition* WP_Transition
typedef TransitionSystem* WP_TransitionSystem
typedef const Species* CWP_Species
typedef const Field* CWP_Field
typedef const ChannelType* CWP_ChannelType
typedef const Channel* CWP_Channel
typedef const Nuclide* CWP_Nuclide
typedef const Transition* CWP_Transition
typedef const TransitionSystem* CWP_TransitionSystem
typedef std::map<ByproductId, int> ByproductCount_t
typedef std::shared_ptr<CompManager> SP_CompManager
typedef std::shared_ptr<MultiZoneDepleter> SP_MultiZoneDepleter
typedef std::shared_ptr<Solver> SP_Solver
typedef std::shared_ptr<const Solver> SCP_Solver
typedef std::shared_ptr<Solver_Fake> SP_Solver_Fake
typedef std::vector<Transition::WP> Vec_Trans
typedef ScaleData::MGFluxMapper<float> MGFluxMapper
typedef std::shared_ptr<MGFluxMapper> SP_MGFluxMapper
typedef std::shared_ptr<SolverSelector> SP_SolverSelector
typedef std::shared_ptr<const SolverSelector> SCP_SolverSelector
Enumeration Type Documentation
enum ConcentrationUnit
Enumerator
NOT_GIVEN
not given – invalid state (or not set)
GATOMS
Gram atoms, gram-atomic weights or moles.
ATOMS_B_CM
Atoms/barn-cm.
GRAMS
Mass, grams.
CURIES
Radioactivity, Ci.
ABSORPTIONS
total capture reaction rate
CAPTURES
(total capture - fission) reaction rate
FISSIONS
fission reaction rate
AIRM_3
Toxicity, cubic meters of air to dilute to RCG_a.
APELEM
Atom % of element. Isotopic atom percents of all elements.
BECQUERELS
Radioactivity, Bq.
GAMWATTS
Gamma-ray thermal power, watts.
GAMMEVS
Gamma-ray thermal power, MeV.
GPERCM_3
Partial density, grams/cubic cm.
H2OM_3
Toxicity, cubic meters of water to dilute to RCG_w.
KILOGRAMS
Mass, kilograms.
WPELEM
Weight % of element. Isotopic weight percents of all elements.
WATTS
Total thermal power, watts.
MEVS
Total thermal power, MeVs.
PARTICLES_SEC
Spectra particles per second.
PARTICLES_SEC_MEV
Photon spectra intensity photons per second MeV.
ENERGY_SEC_MEV
Photon spectra energy intensity in MeV per second*MeV.
MOLES
Mole unit.
CM_2_BARN
cm^2/barn unit.
WPPM
weight fraction in ppm (*1e6)
APPM
atom fraction in ppm (*1e6)
LAST_CONCENTRATION_UNIT
Always add new ones before this.
 {
     //! not given -- invalid state (or not set)
     NOT_GIVEN = -1,
     //! Gram atoms, gram-atomic weights or moles.
     GATOMS = 0,
     //! Atoms/barn-cm.
     ATOMS_B_CM = 1,
     //! Mass, grams
     GRAMS = 2,
     //! Radioactivity, Ci
     CURIES = 3,
     //! total capture reaction rate
     ABSORPTIONS = 4,
     //! (total capture - fission) reaction rate
     CAPTURES = 5,
     //! fission reaction rate
     FISSIONS = 6,
     //! Toxicity, cubic meters of air to dilute to RCG_a
     AIRM_3 = 7,
     //! Atom % of element. Isotopic atom percents of all elements
     APELEM = 8,
     //! Radioactivity, Bq
     BECQUERELS = 9,
     //! Gamma-ray thermal power, watts
     GAMWATTS = 10,
     //! Gamma-ray thermal power, MeV
     GAMMEVS = 11,
     //! Partial density, grams/cubic cm.
     GPERCM_3 = 12,
     //! Toxicity, cubic meters of water to dilute to RCG_w.
     H2OM_3 = 13,
     //! Mass, kilograms
     KILOGRAMS = 14,
     //! Weight % of element. Isotopic weight percents of all elements
     WPELEM = 15,
     //! Total thermal power, watts.
     WATTS = 16,
     //! Total thermal power, MeVs.
     MEVS = 17,
     //! Spectra particles per second
     PARTICLES_SEC = 18,
     //! Photon spectra intensity photons per second MeV
     PARTICLES_SEC_MEV = 19,
     //! Photon spectra energy intensity in MeV per second*MeV
     ENERGY_SEC_MEV = 20,
     //! Mole unit.
     MOLES = 21,
     //! cm^2/barn unit.
     CM_2_BARN = 22,
     //! weight fraction in ppm (*1e6)
     WPPM = 23,
     //! atom fraction in ppm (*1e6)
     APPM = 24,
     //! Always add new ones before this.
     LAST_CONCENTRATION_UNIT
 };  // enum ConcentrationUnit
enum Representation
Enumerator
CONSTANT
LINEAR
 {
     CONSTANT = 0,
     LINEAR = 1
 };
enum YieldType
Enumerator
YIELD_UNKNOWN
YIELD_SIMPLE
YIELD_ISOMERIC
YIELD_DISTRIBUTED
YIELD_MISSING
 {
     YIELD_UNKNOWN = 0,
     YIELD_SIMPLE = 1,
     YIELD_ISOMERIC = 2,
     YIELD_DISTRIBUTED = 3,
     YIELD_MISSING = 4
 };
Function Documentation
string convertConcUnitToPrettyString (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ABSORPTIONS, AIRM_3, APELEM, APPM, ATOMS_B_CM, BECQUERELS, CAPTURES, CM_2_BARN, CURIES, ENERGY_SEC_MEV, FISSIONS, GAMMEVS, GAMWATTS, GATOMS, GPERCM_3, GRAMS, H2OM_3, KILOGRAMS, MEVS, MOLES, PARTICLES_SEC, PARTICLES_SEC_MEV, WATTS, WPELEM, and WPPM.
Referenced by printConcentrations_csv(), StateSetIO_bof::read(), StateSetIO_s62b::read(), TEST(), Concentrations::to_json(), and StateSetIO_s62b::write().
 {
     switch( unit )
     {
         case GPERCM_3:
             return "g/cm3";
         case ATOMS_B_CM:
             return "at/bcm";
         case WPELEM:
             return "wt% iso";
         case APELEM:
             return "at% iso";
         case GRAMS:
             return "grams";
         case KILOGRAMS:
             return "kilograms";
         case GATOMS:
             return "gram-atoms";
         case WATTS:
             return "watts";
         case GAMWATTS:
             return "gamma-watts";
         case MEVS:
             return "MeV/s";
         case GAMMEVS:
             return "gamma-MeV/s";
         case AIRM_3:
             return "m3 air";
         case H2OM_3:
             return "m3 water";
         case CURIES:
             return "Ci";
         case BECQUERELS:
             return "Bq";
         case ABSORPTIONS:
             return "absorption fraction";
         case FISSIONS:
             return "fission fraction";
         case CAPTURES:
             return "capture fraction";
         case PARTICLES_SEC:
             return "1/s";
         case PARTICLES_SEC_MEV:
             return "1/(s.MeV)";
         case ENERGY_SEC_MEV:
             return "MeV/(s.MeV)";
         case MOLES:
             return "mol";
         case CM_2_BARN:
             return "cm^2/barn";
         case WPPM:
             return "weight ppm";
         case APPM:
             return "atoms ppm";
         default:
             throw nemesis::assertion(
                 "Unknown or unsupported concentration unit." );
     }
     return "";
 }
string convertConcUnitToString (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ABSORPTIONS, AIRM_3, APELEM, APPM, ATOMS_B_CM, BECQUERELS, CAPTURES, CM_2_BARN, CURIES, ENERGY_SEC_MEV, FISSIONS, GAMMEVS, GAMWATTS, GATOMS, GPERCM_3, GRAMS, H2OM_3, KILOGRAMS, LAST_CONCENTRATION_UNIT, MEVS, MOLES, PARTICLES_SEC, PARTICLES_SEC_MEV, WATTS, WPELEM, and WPPM.
Referenced by TEST().
 {
     switch( unit )
     {
         case GPERCM_3:
             return "gper";
         case ATOMS_B_CM:
             return "atom";
         case WPELEM:
             return "wpel";
         case APELEM:
             return "apel";
         case GRAMS:
             return "gram";
         case KILOGRAMS:
             return "kilo";
         case GATOMS:
             return "gato";
         case WATTS:
             return "watt";
         case GAMWATTS:
             return "gamw";
         case MEVS:
             return "mevs";
         case GAMMEVS:
             return "gamm";
         case AIRM_3:
             return "airm";
         case H2OM_3:
             return "h2om";
         case CURIES:
             return "curi";
         case BECQUERELS:
             return "becq";
         case ABSORPTIONS:
             return "abso";
         case FISSIONS:
             return "fiss";
         case CAPTURES:
             return "capt";
         case PARTICLES_SEC:
             return "part";
         case PARTICLES_SEC_MEV:
             return "inte";
         case ENERGY_SEC_MEV:
             return "ener";
         case MOLES:
             return "mole";
         case CM_2_BARN:
             return "cm2b";
         case APPM:
             return "appm";
         case WPPM:
             return "wppm";
         case LAST_CONCENTRATION_UNIT:
         default:
             throw nemesis::assertion(
                 "Unknown or unsupported concentration unit='" +
                 std::to_string( unit ) + "'." );
     }
     return "";
 }
ConcentrationUnit convertStringToConcUnit (const string & value)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ABSORPTIONS, AIRM_3, APELEM, APPM, ATOMS_B_CM, BECQUERELS, CAPTURES, CM_2_BARN, CURIES, ENERGY_SEC_MEV, FISSIONS, GAMMEVS, GAMWATTS, GATOMS, GPERCM_3, GRAMS, H2OM_3, KILOGRAMS, MEVS, MOLES, NOT_GIVEN, PARTICLES_SEC, PARTICLES_SEC_MEV, WATTS, WPELEM, and WPPM.
Referenced by main(), TEST(), and view().
 {
     // Convert string to lower case
     string lower = ScaleUtils::IO::stringToLower( value );
     // Keep the full string because that's what ORIGEN SON input uses
     string lowerFull = lower;
     // Use first four characters
     if( lower.size() >= 4 ) lower = lower.substr( 0, 4 );
     if( lower == "abso" ) return ABSORPTIONS;
     if( lower == "fiss" ) return FISSIONS;
     if( lower == "capt" ) return CAPTURES;
     if( lower == "airm" || lowerFull == "m3_air" ) return AIRM_3;
     if( lower == "apel" ) return APELEM;
     if( lower == "atom" || lowerFull == "atoms-per-barn-cm" ) return ATOMS_B_CM;
     if( lower == "becq" ) return BECQUERELS;
     if( lower == "curi" || lowerFull == "curies" ) return CURIES;
     if( lower == "gamw" || lowerFull == "g-watts" ) return GAMWATTS;
     if( lower == "gamm" ) return GAMMEVS;
     if( lower == "gato" || lowerFull == "gram-atoms" ) return GATOMS;
     if( lower == "gper" ) return GPERCM_3;
     if( lower == "gram" || lowerFull == "grams" ) return GRAMS;
     if( lower == "h2om" || lowerFull == "m3_water" ) return H2OM_3;
     if( lower == "kilo" ) return KILOGRAMS;
     if( lower == "wpel" ) return WPELEM;
     if( lower == "watt" || lowerFull == "watts" ) return WATTS;
     if( lower == "mevs" ) return MEVS;
     if( lower == "part" ) return PARTICLES_SEC;
     if( lower == "inte" ) return PARTICLES_SEC_MEV;
     if( lower == "ener" ) return ENERGY_SEC_MEV;
     if( lower == "mole" ) return MOLES;
     if( lower == "cm2b" ) return CM_2_BARN;
     if( lower == "appm" || lowerFull == "atoms_ppm" ) return APPM;
     if( lower == "wppm" || lowerFull == "weight_ppm" ) return WPPM;
     throw nemesis::assertion(
         "Unknown or unsupported concentration unit='" + lowerFull +
         "'. Use one of: \n"
         "(abso|fiss|capt|airm|apel|atom|becq|curi|gamw|gamm|gato|\n"
         "gper|gram|h2om|kilo|wpel|watt|mevs|part|inte|ener|mole|cm2b|wppm|appm)"
         ". " );
     // will never get here...but to quiet warnings
     return NOT_GIVEN;
 }  // convertStringToConcUnit
int unitAsInt (const ConcentrationUnit & unit)
Obtain the integer enumeration for the given origen f71 concentration
Parameters
unit - the concentration unit (GATOMS,ATOMS_B_CM,GRAMS,CURIES)
Returns
the f71 integer enumeration
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ATOMS_B_CM, CURIES, GATOMS, and GRAMS.
Referenced by TEST(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
 {
     switch( unit )
     {
         case Origen::GATOMS:
             return 0;
         case Origen::ATOMS_B_CM:
             return 1;
         case Origen::GRAMS:
             return 2;
         case Origen::CURIES:
             return 3;
         default:
             throw nemesis::assertion(
                 "Unsupported or unknown unit to be written to F71 file." );
     }
     return -1;
 }  // end of unitAsInt
ConcentrationUnit intAsUnit (const int & unit)
Obtain the concentration enumeration for the given origen f71 int concentration
Parameters
unit - the int f71 unit enumeration (0,1,2,3)
Returns
the f71 concentration enumeration (GATOMS,ATOMS_B_CM,GRAMS,CURIES)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ATOMS_B_CM, CURIES, GATOMS, GRAMS, and NOT_GIVEN.
Referenced by StateSetIO_bof::read(), StateSetIO_s62b::read(), and TEST().
 {
     switch( unit )
     {
         case 0:
             return Origen::GATOMS;
         case 1:
             return Origen::ATOMS_B_CM;
         case 2:
             return Origen::GRAMS;
         case 3:
             return Origen::CURIES;
         default:
             throw nemesis::assertion(
                 "Unsupported or unknown unit read from F71 file." );
     }
     return Origen::NOT_GIVEN;
 }  // end of intAsUnit
bool isMassUnit (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References GPERCM_3, GRAMS, KILOGRAMS, WPELEM, and WPPM.
Referenced by ConcentrationConverter::convert_to(), ConcentrationConverter::mol2m(), and TEST().
 {
     switch( unit )
     {
         case GRAMS:
             return true;
         case KILOGRAMS:
             return true;
         case GPERCM_3:
             return true;
         case WPELEM:
             return true;
         case WPPM:
             return true;
         default:
             break;
     }
     return false;
 }
bool isNumberUnit (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References APELEM, APPM, ATOMS_B_CM, CM_2_BARN, GATOMS, and MOLES.
Referenced by ConcentrationConverter::convert_to(), ConcentrationConverter::mol2n(), and TEST().
 {
     switch( unit )
     {
         case MOLES:
             return true;
         case GATOMS:
             return true;
         case ATOMS_B_CM:
             return true;
         case APELEM:
             return true;
         case CM_2_BARN:
             return true;
         case APPM:
             return true;
         default:
             break;
     }
     return false;
 }
bool isDecayUnit (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References AIRM_3, BECQUERELS, CURIES, GAMMEVS, GAMWATTS, H2OM_3, MEVS, and WATTS.
Referenced by ConcentrationConverter::convert_to(), ConcentrationConverter::mol2d(), and TEST().
 {
     switch( unit )
     {
         case CURIES:
             return true;
         case BECQUERELS:
             return true;
         case WATTS:
             return true;
         case GAMWATTS:
             return true;
         case MEVS:
             return true;
         case GAMMEVS:
             return true;
         case AIRM_3:
             return true;
         case H2OM_3:
             return true;
         default:
             break;
     }
     return false;
 }
bool isSpectrumUnit (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ENERGY_SEC_MEV, PARTICLES_SEC, and PARTICLES_SEC_MEV.
Referenced by ConcentrationConverter::convert_to(), and TEST().
 {
     switch( unit )
     {
         case PARTICLES_SEC:
             return true;
         case PARTICLES_SEC_MEV:
             return true;
         case ENERGY_SEC_MEV:
             return true;
         default:
             break;
     }
     return false;
 }
bool isReactionUnit (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ABSORPTIONS, CAPTURES, and FISSIONS.
Referenced by ConcentrationConverter::convert_to(), and TEST().
 {
     switch( unit )
     {
         case ABSORPTIONS:
             return true;
         case CAPTURES:
             return true;
         case FISSIONS:
             return true;
         default:
             break;
     }
     return false;
 }
bool isVolumetric (ConcentrationUnit unit)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References ATOMS_B_CM, and GPERCM_3.
Referenced by Concentrations::accumulate_concs(), needsVolumeToConvert(), and TEST().
 {
     switch( unit )
     {
         case GPERCM_3:
             return true;
         case ATOMS_B_CM:
             return true;
         default:
             break;
     }
     return false;
 }
bool needsVolumeToConvert (ConcentrationUnit unita, ConcentrationUnit unitb)
Examples:
Core/dc/tests/tstConcentrationUnit.cpp.
References isVolumetric().
Referenced by ConcentrationConverter::convert_to(), and TEST().
 {
     // one volumetric and one not
     int sum = (int)isVolumetric( unita ) + (int)isVolumetric( unitb );
     return sum == 1;
 }
double Origen::Energy::base< Energy::JOULE > () inline
 {
     return 1.;
 }
double Origen::Energy::base< Energy::EV > () inline
 {
     return 1.60217657e-19;
 }
double Origen::Energy::base< Energy::KWH > () inline
 {
     return 1e3 * 60 * 60;
 }
double Origen::Energy::base< Energy::MWD > () inline
 {
     return 1e6 * 60 * 60 * 24;
 }
double Origen::Energy::base< Energy::GWD > () inline
 {
     return 1e9 * 60 * 60 * 24;
 }
double Origen::Energy::base< Energy::GWYR > () inline
 {
     return 1e9 * 60 * 60 * 24 * 365.25;
 }
std::string Origen::Energy::name< Energy::JOULE > () inline
 {
     return "J";
 }
std::string Origen::Energy::name< Energy::EV > () inline
 {
     return "eV";
 }
std::string Origen::Energy::name< Energy::KWH > () inline
 {
     return "kWh";
 }
std::string Origen::Energy::name< Energy::MWD > () inline
 {
     return "MWd";
 }
std::string Origen::Energy::name< Energy::GWD > () inline
 {
     return "GWd";
 }
std::string Origen::Energy::name< Energy::GWYR > () inline
 {
     return "GWyr";
 }
Vec_Int Origen::create_zzzaaai_seq1 (size_t total_nuclides)
Referenced by createNuclideSet_random1(), and FakeFactory::StateSet_random1().
 {
     Vec_Int ids( total_nuclides, 0 );
     for( size_t j = 0; j < total_nuclides; ++j )
     {
         int z = j % 98 + 1;
         int a = j % 254 + 1;
         int i = j % 2;
         ids[j] = z * 1e4 + a * 1e1 + i;
     }
     return ids;
 }
NuclideSet Origen::createNuclideSet_random1 ()
References create_zzzaaai_seq1(), and NuclideSet::set_ids_legacy().
Referenced by FakeFactory::createLibraryHeader_random1().
 {
     NuclideSet obj;
     Vec_Int ids = create_zzzaaai_seq1( 2226 );
     int nlt = 742;
     int nac = 556;
     int nfp = 928;
     obj.set_ids_legacy( nlt, nac, nfp, ids );
     return obj;
 }
Vec_Int Origen::createNuclideIds5 ()
Examples:
Core/dc/tests/tstNuclideSet.cpp.
Referenced by TEST().
 {
     return Vec_Int( {10008016, 20092235, 21092235, 20092238, 30054135} );
 }
Vec_Int Origen::createNuclideIds6 ()
Examples:
Core/dc/tests/tstNuclideSet.cpp.
Referenced by TEST().
 {
     return Vec_Int(
         {10008016, 20092235, 21092235, 20092238, 30053135, 30054135} );
 }
DecayData Origen::createDecayData_random1 (const LibraryHeader & def)
References CREATE_FLOAT_VEC_DIRECT, CREATE_INT_VEC_DIRECT, LibraryHeader::nuclide_set(), NuclideSet::num_in_sublib(), SUBLIB_1LT, and NuclideSet::total_nuclides().
Referenced by FakeFactory::DecayData_random1(), and FakeFactory::Library_random1().
 {
     DecayData obj;
     size_t itot = def.nuclide_set().total_nuclides();
     size_t ilite = def.nuclide_set().num_in_sublib( SUBLIB_1LT );
     CREATE_FLOAT_VEC_DIRECT( abund_of_lite_nuclides, ilite, 0.0, 1.0 )
     CREATE_FLOAT_VEC_DIRECT( decay_constants, itot, 0.0, 1e-2 )
     CREATE_INT_VEC_DIRECT( fissionable_nuclide_ids, 10, 922330, 962550 )
     CREATE_FLOAT_VEC_DIRECT( q_fractions_from_photons, itot, 0.0, 1.0 )
     CREATE_FLOAT_VEC_DIRECT( rcg_for_air, itot, 0.0, 40. )
     CREATE_FLOAT_VEC_DIRECT( rcg_for_water, itot, 0.0, 30. )
     CREATE_FLOAT_VEC_DIRECT( recoverable_energy_values, itot, 0.0, 7. )
     return obj;
 }
TransitionStructure Origen::createTransitionStructure_random1 (const LibraryHeader & def)
References CREATE_INT_VEC, LibraryHeader::nuclide_set(), TransitionStructure::set_num_parents(), and NuclideSet::total_nuclides().
Referenced by FakeFactory::Library_random1(), and FakeFactory::TransitionStructure_random1().
 {
     TransitionStructure obj;
     size_t itot = def.nuclide_set().total_nuclides();
     size_t non = 54217;
     CREATE_INT_VEC( transition_ids, non, 16, 200 )
     CREATE_INT_VEC( parent_positions, non, 1, itot )
     CREATE_INT_VEC( num_parents, itot, 4, 7 )
     CREATE_INT_VEC( num_decay_parents, itot, 1, 3 )
     // fix up number of transitions we are going to be short
     int short_transitions =
         static_cast<int>( non ) - ScaleSTL::sum( num_parents );
     num_parents[itot - 1] += short_transitions;
     obj.set_num_parents( num_parents );
     return obj;
 }
TransitionCoeff Origen::createTransitionCoeff_random1 (const LibraryHeader & def)
References CREATE_FLOAT_VEC, LibraryHeader::nuclide_set(), NuclideSet::num_in_sublib(), TransitionCoeff::set_burnup(), SUBLIB_1LT, SUBLIB_2AC, and NuclideSet::total_nuclides().
Referenced by FakeFactory::Library_random1(), and FakeFactory::TransitionCoeff_random1().
 {
     TransitionCoeff obj;
     obj.set_burnup( randomVal<float>( 0, 60000 ) );
     size_t ilite = def.nuclide_set().num_in_sublib( SUBLIB_1LT );
     size_t iact = def.nuclide_set().num_in_sublib( SUBLIB_2AC );
     size_t ineu = ilite + iact;
     size_t itot = def.nuclide_set().total_nuclides();
     size_t non = 54217;
     size_t nneg = 238;
     CREATE_FLOAT_VEC( matrix, non, 0.0, 1e-2 )
     CREATE_FLOAT_VEC( fission_xs, iact, 0.0, 60.0 )
     CREATE_FLOAT_VEC( flux, nneg, 0.0, 1e14 )
     CREATE_FLOAT_VEC( neutron_yields, ineu, 0.0, 2.6 )
     CREATE_FLOAT_VEC( loss_xs, itot, 0.0, 1e6 )
     CREATE_FLOAT_VEC( kappa_capture, itot, 0.0, 5 )
     CREATE_FLOAT_VEC( kappa_fission, iact, 0.0, 200 )
     return obj;
 }
double Origen::Unitless::base< Unitless::ONE > () inline
 {
     return 1.;
 }
std::string Origen::Unitless::name< Unitless::ONE > () inline
 {
     return "-";
 }
double Origen::integrate_history (const Vec_Dbl & scaling, const Material::History_t & hist)
Referenced by Material::record_average_flux(), and Material::record_average_power().
 {
     Require( scaling.size() == hist.size() );
     size_t i = 0;
     double acc = 0;
     double trel1, frel1, trel0, frel0;
     double s0;
     double s1;
     for( auto& it : hist )
     {
         trel1 = it.first;
         frel1 = it.second;
         s1 = scaling[i];
         if( i > 0 )
             acc += 0.5 * ( trel1 - trel0 ) * ( s1 * frel1 + s0 * frel0 );
         ++i;
         trel0 = trel1;
         frel0 = frel1;
         s0 = s1;
     }
     return acc;
 }
std::string Origen::h2string (const Material::History_t & hist)
Referenced by Material::to_string().
 {
     std::stringstream ss;
     for( const auto& it : hist )
     {
         ss << it.first << "=" << it.second << " ";
     }
     return ss.str();
 }
double Origen::Power::base< Power::WATT > () inline
 {
std::string Origen::Power::name< Power::WATT > () inline
void SerialRegistrar (Standard::SerialFactory * factory)
Registrar for serializable objects.
Parameters
Standard::SerialFactory * factory - the factory to which Library objects are registered
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by TEST_F().
 {
     if( factory == nullptr ) return;
     factory->registerSerializable( new TagManager() );
     factory->registerSerializable( new MaterialMap() );
     factory->registerSerializable( new Library() );
     factory->registerSerializable( new LibraryHeader() );
     factory->registerSerializable( new TransitionCoeff() );
     factory->registerSerializable( new DecayData() );
     factory->registerSerializable( new TransitionStructure() );
 }
std::vector< implicitTag > checkImplicitTags (const std::vector< TagManager > & tagManList, const TagManager & tm)
Function to check the tag managers from a set of TagManagers (e.g., from a set of Library objects) to enssure that they have all of the tags requested in a reference TagManager. Then checks to see if the libraries have any other interpolable tags. If so, these are collected along with all of the values for that tag on all of the TagManagers and returned.
Parameters
tagManList List of all of the tag managers in question.
tm Reference TagManager.
Returns
List of implicitTag structures, which contains the name and a vector of values corresponding to that tag name from all of the libraries.
References TagManager::compare(), TagManager::hasTag(), implicitTag::name, and implicitTag::values.
Referenced by interpLibraryND().
 {
     std::vector<implicitTag> tagSpans;
     for( auto& tagMan : tagManList )
     {
         Insist(
             tm.compare( tagMan ).size() == 0,
             "A Library does not contain necessary tags for interpolation." );
         for( auto& tag : tagMan.listInterpTags() )
         {
             if( !tm.hasTag( tag ) )
             {
                 bool tmpbool = true;
                 while( tmpbool )
                 {
                     for( auto& implied : tagSpans )
                     {
                         if( implied.name == tag )
{
                             implied.values.push_back(
                                 tagMan.getInterpTag( tag ) );
                             tmpbool = false;
                             break;
                         }
                     }
                     if( !tmpbool ) break;
                     implicitTag newTag;
                     newTag.name = tag;
                     newTag.values.push_back( tagMan.getInterpTag( tag ) );
                     tagSpans.push_back( newTag );
                     tmpbool = false;
                 }
             }
         }
     }
     return ( tagSpans );
 }
void addImpliedTags (const std::vector< implicitTag > & tagSpans, TagManager * tm, Vec_Str * dimNames)
Function to add unspecified interpolable tags to a reference tag manager with the average value of that tag over all libraries provided.
Parameters
tagSpans List of implicitTag structure which contains the name of a tag and all of the values that tag has on all of the libraries in use.
tm Reference TagManager to which the implied tags will be added.
References TagManager::setInterpTag().
Referenced by interpLibraryND().
 {
     for( auto& newTags : tagSpans )
     {
         float average = 0.;
         for( auto& num : newTags.values )
         {
             average += num;
         }
         average = average / ( newTags.values.size() * 1. );
         tm->setInterpTag( newTags.name, average );
         dimNames->push_back( newTags.name );
         std::cout << "WARNING: Unspecified tag '" << newTags.name
                   << "' added with averaged value '" << average << "'."
                   << std::endl;
     }
 }
std::string parseTags (const std::string & str, Vec_Str * tags, Vec_Str * values, Vec_Bool * modify)
parse the command line argument that has tags of the form tag1,tag2=,tag3=val3,... convenient for use with TagManager
Referenced by Obiwan_interp::populate(), and Obiwan_tag::populate().
 {
     Vec_Str tmptags = ScaleUtils::IO::splitString( ",", str );
     modify->resize( 0 );
     values->resize( 0 );
     tags->resize( 0 );
     for( auto tag : tmptags )
     {
         modify->push_back( false );
         values->push_back( "" );
         tags->push_back( "" );
         Vec_Str left_right = ScaleUtils::IO::splitString( "=", tag );
         if( left_right.size() == 2 )
         {
             modify->back() = true;
             if( left_right[1] != "" )
             {
                 values->back() = left_right[1];
                 tags->back() = left_right[0];
             }
         }
         else if( left_right.size() == 1 && left_right[0] != "" )
         {
             modify->back() = true;
             tags->back() = left_right[0];
         }
         else if( left_right.size() > 2 )
         {
             return "tag expression: " + tag + " has too many =";
         }
     }
     Ensure( modify->size() == tags->size() );
     Ensure( values->size() == tags->size() );
     return "";
 }
double Origen::Time::base< Time::SECONDS > () inline
 {
double Origen::Time::base< Time::MINUTES > () inline
 {
     // unit enum
     enum UNITS
double Origen::Time::base< Time::HOURS > () inline
double Origen::Time::base< Time::DAYS > () inline
double Origen::Time::base< Time::YEARS > () inline
std::string Origen::Time::name< Time::SECONDS > () inline
std::string Origen::Time::name< Time::MINUTES > () inline
     {
         return base<from>() / base<to>();
std::string Origen::Time::name< Time::HOURS > () inline
     {
         return base( from ) / base<to>();
std::string Origen::Time::name< Time::DAYS > () inline
References Time::base().
     {
         return base( from ) / base( to );
     }
std::string Origen::Time::name< Time::YEARS > () inline
bool Origen::nuclide_in_bounds (const int n, const int ntotal)
Referenced by TransitionMatrixP::get_xs(), and TransitionMatrixP::set_xs().
 {
     if( !( n >= 0 && n < ntotal ) )
     {
         SErrLine( 1,
                   "nuclide index out of bounds, must be between 0 and "
                       << ( ntotal - 1 )
                       << " (as 0-start index)" );
         return false;
     }
     return true;
 }
bool Origen::only_set_component (const int mt_in)
Referenced by TransitionMatrixP::set_xs().
 {
     if( mt_in == 27 || mt_in == 101 )
     {
         SErrLine( 1,
                   "cannot set MT=27 or MT=101 directly (specify a component, "
                   "e.g. MT=102" );
         return false;
     }
     return true;
 }
void Origen::toQString_tinds_2d (const IntegerList & nind_list, const IntegerList & transition_ids, const Integer2dList & tinds_2d)
Referenced by TransitionMatrixP::fast_set_xs(), and TransitionMatrixP::setup_fast_transition_access().
 {
     fprintf( stderr, "%7s %7s [%s]\n", "nind", "mt", "tinds" );
     for( size_t i = 0; i < tinds_2d.size(); i++ )
     {
         IntegerList* tinds_ptr = tinds_2d[i];
         fprintf( stderr, "%7d %7d [", nind_list[i], transition_ids[i] );
         for( size_t j = 0; j < tinds_ptr->size(); j++ )
         {
             fprintf( stderr, "%7d ", tinds_ptr->at( j ) );
         }
         fprintf( stderr, "]\n" );
     }
     return;
 }
void read (const bof::BOFObject & obj, TagManager & tag_manager)
read a tag manager from a bof object
read TagManager from BOF object
Examples:
Core/io/tests/tstGammaResourceIO.cpp.
References TagManager::setIdTag(), and TagManager::setInterpTag().
Referenced by LibraryHeader::deserialize(), StateInfo::deserialize(), TransitionStructure::deserialize(), Concentrations::deserialize(), TransitionCoeff::deserialize(), LibraryIO_bof::read(), StateSetIO_bof::read(), Accessor< Origen::Concentrations >::read(), Accessor< Origen::TransitionCoeff >::read(), Accessor< Origen::StateInfo >::read(), Accessor< Origen::TagManager >::read(), read(), Accessor< Origen::LibraryHeader >::read(), Accessor< Origen::NuclideSet >::read(), GammaResourceData::SetUp(), and TEST().
 {
     Vec_Str id_names, id_values, interp_names;
     Vec_Dbl interp_values;
     read( obj, "idn", id_names );
     read( obj, "idv", id_values );
     read( obj, "itn", interp_names );
     read( obj, "itv", interp_values );
     Check( id_values.size() == id_names.size() );
     for( size_t i = 0; i < id_names.size(); i++ )
     {
         tag_manager.setIdTag( id_names[i], id_values[i] );
     }
     Check( interp_names.size() == interp_values.size() );
     for( size_t i = 0; i < interp_names.size(); i++ )
     {
         tag_manager.setInterpTag( interp_names[i], interp_values[i] );
     }
 }
void read (const bof::BOFObject & obj, std::string name, TagManager & tag_manager)
read a tag manager from a bof object
read TagManager from named BOF sub-object
References read().
 {
     Require( name != "" );
     Require( obj.containsKey( name ) );
     const bof::BOFObject& sub = obj.get<bof::BOFObject>( name );
     read( sub, tag_manager );
 }
void write (bof::BOFObject & obj, std::string name, const TagManager & tag_manager)
write a tag manager to a bof object
write TagManager to named BOF sub-object
Referenced by LibraryHeader::serialize(), StateInfo::serialize(), TransitionStructure::serialize(), Concentrations::serialize(), TransitionCoeff::serialize(), LibraryIO_bof::write(), StateSetIO_bof::write(), Accessor< Origen::Concentrations >::write(), Accessor< Origen::TransitionCoeff >::write(), Accessor< Origen::StateInfo >::write(), Accessor< Origen::TagManager >::write(), write(), Accessor< Origen::LibraryHeader >::write(), and Accessor< Origen::NuclideSet >::write().
 {
     Require( name != "" );
     bof::BOFObject sub;
     write( sub, tag_manager );
     obj.add( name, sub );
 }
void write (bof::BOFObject & obj, const TagManager & tag_manager)
write a tag manager to a bof object
write TagManager to BOF object
References TagManager::listIdTags(), TagManager::listIdValues(), TagManager::listInterpTags(), TagManager::listInterpValues(), and write().
 {
     write( obj, "idn", tag_manager.listIdTags() );
     write( obj, "idv", tag_manager.listIdValues() );
     write( obj, "itn", tag_manager.listInterpTags() );
     write( obj, "itv", tag_manager.listInterpValues() );
 }
void read (const bof::BOFObject & obj, std::string name, StateInfo & states_info)
read state info from a bof object
read StateInfo from named BOF sub-object
References read().
 {
     Require( name != "" );
     Require( obj.containsKey( name ) );
     const bof::BOFObject& sub = obj.get<bof::BOFObject>( name );
     read( sub, states_info );
 }
void read (const bof::BOFObject & obj, StateInfo & states_info)
read state info from a bof object
read StateInfo from BOF object
References read(), StateInfo::set_case_number(), StateInfo::set_energy(), StateInfo::set_fluence(), StateInfo::set_flux(), StateInfo::set_library_position(), StateInfo::set_power(), StateInfo::set_step_number(), StateInfo::set_tag_manager(), and StateInfo::set_time().
 {
     int cn, sn, lp;
     float po, bu, fl, ti, fluence;
     read( obj, "cn", cn );
     states_info.set_case_number( cn );
     read( obj, "sn", sn );
     states_info.set_step_number( sn );
     read( obj, "lp", lp );
     states_info.set_library_position( lp );
     read( obj, "po", po );
     states_info.set_power( po );
     read( obj, "bu", bu );
     states_info.set_energy( bu );
     read( obj, "fl", fl );
     states_info.set_flux( fl );
     read( obj, "ti", ti );
     states_info.set_time( ti );
     read( obj, "fluence", fluence );
     states_info.set_fluence( fluence );
     TagManager tag_manager;
     read( obj, "TagManager", tag_manager );
     states_info.set_tag_manager( tag_manager );
 }
void write (bof::BOFObject & obj, std::string name, const StateInfo & states_info)
write state info to a bof object
write StateInfo to named BOF sub-object
References write().
 {
     Require( name != "" );
     bof::BOFObject sub;
     write( sub, states_info );
     obj.add( name, sub );
 }
void write (bof::BOFObject & obj, const StateInfo & states_info)
write state info to a bof object
write StateInfo to BOF object
References StateInfo::case_number(), StateInfo::energy(), StateInfo::fluence(), StateInfo::flux(), StateInfo::library_position(), StateInfo::power(), StateInfo::step_number(), StateInfo::tag_manager(), StateInfo::time(), and write().
 {
     write( obj, "cn", states_info.case_number() );
     write( obj, "sn", states_info.step_number() );
     write( obj, "lp", states_info.library_position() );
     write( obj, "po", states_info.power() );
     write( obj, "bu", states_info.energy() );
     write( obj, "fl", states_info.flux() );
     write( obj, "ti", states_info.time() );
     write( obj, "fluence", states_info.fluence() );
     write( obj, "TagManager", states_info.tag_manager() );
 }
SP_Diff diffLibrary (const Library & a, const Library & b, int pos, double reltol)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References construct_coeff_map().
Referenced by Obiwan_diff::diff(), TEST(), and TEST_F().
 {
     std::stringstream diffs;
     bool have_difference = false;
     std::map<std::pair<int, int>, double>::const_iterator ita, itb, itc;
     std::map<std::pair<int, int>, double> amap = construct_coeff_map( a, pos );
     std::map<std::pair<int, int>, double> bmap = construct_coeff_map( b, pos );
     std::map<std::pair<int, int>, double> cmap = amap;
     cmap.insert( bmap.begin(), bmap.end() );
     for( itc = cmap.begin(); itc != cmap.end(); ++itc )
     {
         std::pair<int, int> did_pid = itc->first;
         ita = amap.find( did_pid );
         itb = bmap.find( did_pid );
         double coeffa = 0.0;
         double coeffb = 0.0;
         double relpct = 1e99;
         std::string diffstr = "";
         if( ita == amap.end() )
         {
             coeffb = itb->second;
             if( coeffb != 0 )
             {
                 diffstr = "DIFF(<)";
                 have_difference = true;
             }
         }
         else if( itb == bmap.end() )
         {
             coeffa = ita->second;
             if( coeffa != 0 )
             {
                 diffstr = "DIFF(>)";
                 have_difference = true;
             }
         }
         else
         {
             coeffa = ita->second;
             coeffb = itb->second;
             relpct = 100 *
                      std::fabs( ( 1e-99 + coeffb ) / ( 1e-99 + coeffa ) - 1.0 );
             if( relpct > reltol || std::isnan( relpct ) )
             {
                 diffstr = "DIFF(|)";
                 have_difference = true;
             }
         }
         if( ita != amap.end() ) coeffa = ita->second;
         if( itb != bmap.end() ) coeffb = itb->second;
         diffs << did_pid.first << " <-- " << did_pid.second << std::scientific
               << std::setw( 14 ) << std::setprecision( 5 ) << coeffa << " "
               << std::scientific << std::setw( 14 ) << std::setprecision( 5 )
               << coeffb << " " << std::scientific << std::setw( 10 )
               << std::setprecision( 1 ) << relpct << "%"
               << " " << diffstr << std::endl;
     }
     return std::make_shared<LocalDiff>( have_difference, diffs.str() );
 }
std::string diffConcentrations (const Concentrations & a, const Concentrations & b, double reltol)
References NuclideSet::get_ids(), Concentrations::get_vals(), and Concentrations::nuclide_set().
Referenced by Obiwan_diff::diff(), TEST(), and TEST_P().
 {
     std::stringstream diffs;
     bool header_written = false;
     std::map<int, double> a_map;
     std::map<int, double> b_map;
     {
         // Make mapping for concentration A:
         const NuclideSet& nuc_set = a.nuclide_set();
         Vec_Int a_nucs;
         nuc_set.get_ids( a_nucs );
         Vec_Dbl a_vals;
         a.get_vals( a_vals );
         for( int i = 0; i < a_nucs.size(); i++ )
         {
             a_map.insert(
                 std::pair<int, double>( a_nucs.at( i ), a_vals.at( i ) ) );
         }
     }
     {
         // Make mapping for concentration B:
         const NuclideSet& nuc_set = b.nuclide_set();
         Vec_Int b_nucs;
         nuc_set.get_ids( b_nucs );
         Vec_Dbl b_vals;
         b.get_vals( b_vals );
         for( int i = 0; i < b_nucs.size(); i++ )
         {
             b_map.insert(
                 std::pair<int, double>( b_nucs.at( i ), b_vals.at( i ) ) );
         }
     }
     std::map<int, double> nucl_not_on_a;
     std::map<int, double> nucl_not_on_b;
     // Do some comparisons:
     std::multimap<double, int> abs_ab;
     for( auto& it : a_map )
     {
         int iza = it.first;
         double val = it.second;
         std::map<int, double>::iterator loc = b_map.find( iza );
         if( loc != b_map.end() )
         {
             if( !ScaleSTL::approx_eq( it.second, b_map.at( iza ) ) )
             {
                 if( !header_written )
                 {
                     diffs << "  IZA           Conc. A          Conc. B         "
                              "   |A-B|           Diff. [%]\n";
                     diffs << "  ===           =======          =======         "
                              "   =====           =========\n";
                     header_written = true;
                 }
                 abs_ab.insert( std::pair<double, int>(
                     -1. * std::abs( it.second - b_map.at( iza ) ), iza ) );
             }
         }
         else
         {
             nucl_not_on_b.insert( std::make_pair( iza, val ) );
         }
     }
     for( auto& it : abs_ab )
     {
         int iza = it.second;
         std::string line = nprintf(
             "%d % 17.8E % 17.8E % 17.8E % 17.8E\n",
             iza,
             a_map.at( iza ),
             b_map.at( iza ),
             -1. * it.first,
             ( ( b_map.at( iza ) - a_map.at( iza ) ) / a_map.at( iza ) ) *
                 100.0 );
         diffs << line;
     }
     for( auto& it : b_map )
     {
         int iza = it.first;
         double val = it.second;
         std::map<int, double>::iterator loc = a_map.find( iza );
         if( loc == a_map.end() )
         {
             nucl_not_on_a.insert( std::make_pair( iza, val ) );
         }
     }
     if( !nucl_not_on_b.empty() || !nucl_not_on_a.empty() )
     {
         if( !header_written )
         {
             diffs << "  IZA           Conc. A          Conc. B            "
                      "|A-B|           Diff. [%]\n";
             diffs << "  ===           =======          =======            "
                      "=====           =========\n";
             header_written = true;
         }
         for( const auto& it : nucl_not_on_b )
         {
             std::string line =
                 nprintf( "%d % 17.8E % 17.8E\n", it.first, it.second, 0.0 );
             diffs << line;
         }
         for( const auto& it : nucl_not_on_a )
         {
             std::string line =
                 nprintf( "%d % 17.8E % 17.8E\n", it.first, 0.0, it.second );
             diffs << line;
         }
     }
     return diffs.str();
 }
std::string diffLine (const std::string & head, const T & val1, const T & val2, float tol = 1.0e-5)
Referenced by Obiwan_diff::diff().
 {
     std::stringstream ss;
     std::string diffstr( "" );
     if( std::abs( val1 - val2 ) >= tol ) diffstr = " DIFF(|)";
     ss << std::setw( 15 ) << head << std::scientific << std::setw( 15 )
        << std::setprecision( 5 ) << val1 << std::scientific << std::setw( 15 )
        << std::setprecision( 5 ) << val2 << std::setw( 10 ) << diffstr
        << std::endl;
     return ss.str();
 }
std::string diffHalfLine (const std::string & head, const T & val, const int & side)
Referenced by Obiwan_diff::diff().
 {
     std::stringstream ss;
     if( col == 1 )
     {
         ss << std::setw( 15 ) << head << std::scientific << std::setw( 15 )
            << std::setprecision( 5 ) << val << std::setw( 10 ) << "*"
            << std::endl;
     }
     else
     {
         ss << std::setw( 15 ) << head << std::setw( 10 ) << "*"
            << std::setw( 5 ) << " " << std::scientific << std::setw( 15 )
            << std::setprecision( 5 ) << val << std::endl;
     }
     return ss.str();
 }
void graphvizLibrary (const Library & lib, int pos, std::ostream & os)
Referenced by view().
 {
     NuclideGroupFilter nfilter;
     TransitionGroupFilter tfilter;
     graphvizLibrary( lib, pos, nullptr, nfilter, tfilter, false, os );
 }
void graphvizLibrary (const Library & lib, int pos, const std::vector< double > * numden, const NuclideGroupFilter & nfilter, const TransitionGroupFilter & tfilter, bool include_byproducts, std::ostream & os)
References Library::definition(), kernel_rksuite::f(), TransitionGroupFilter::filter(), NuclideGroupFilter::filter(), NuclideSet::ids(), Library::newsp_transition_matrix_at(), and LibraryHeader::nuclide_set().
 {
     SP_TransitionMatrixP trx =
         lib.newsp_transition_matrix_at( static_cast<size_t>( pos - 1 ) );
     const Vec_Int& ids = lib.definition().nuclide_set().ids();
     const DoubleList* amatrix = trx->get_a();
     IntegerList* nucl = trx->get_nucl();
     const DoubleList* tocap = trx->get_tocap();
     double max_sigma0 = 0.0;
     for( size_t i = 0; i < ids.size(); ++i )
     {
         int sizzzaaa = ids[i];
         if( nfilter.filter( sizzzaaa ) ) continue;
         double sig = tocap->at( i );
         if( numden != nullptr )
         {
             sig *= numden->at( i );
         }
         os << "// " << i << " sigma=" << sig << std::endl;
         max_sigma0 = std::max( sig, max_sigma0 );
     }
     const double max_sigma( max_sigma0 );
     os << "//max_sigma=" << max_sigma << std::endl;
     os << "digraph System { " << std::endl;
     int w = 130;
     int h = 80;
     std::set<int> nuclide_used;
     std::set< std::pair<int,int> >transition_used;
     for( size_t i = 0; i < ids.size(); ++i )
     {
         int sizzzaaa = ids[i];
         if( nfilter.filter( sizzzaaa ) ) continue;
         int s, I, z, a;
         ScaleData::Utils::split_pizzzaaa( sizzzaaa, s, I, z, a );
         double sig = tocap->at( i );
         if( numden != nullptr )
         {
             sig *= numden->at( i );
         }
         double frac = sig / max_sigma;
         frac = std::log10( 1e6 * ( frac + 1e-20 ) );  // should be -inf to 6 now
         int color = 1 + std::min( 6.0, std::max( 0.0, frac ) );  // 1 to 7
         os << "// Z=" << z << " A=" << a << " I=" << I << std::endl;
         bool numeric_label = false;
         std::string label;
         if( numeric_label )
         {
             std::stringstream ss;
             ss << z << ":" << a << ":" << I;
             label = ss.str();
         }
         else
         {
             label = ScaleData::Utils::pizzzaaa_to_symbol( sizzzaaa );
         }
         int parent_id = nucl->at( i ) % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         if( nuclide_used.count(parent_id)==0 ){
             nuclide_used.insert( parent_id );
             os << parent_id << " [label=\"{" << label << "|" << std::fixed
                << std::setprecision( 1 ) << sig << std::fixed << "b}\", pos=\""
                << w * ( a - z ) << "," << h * ( 2 * z + I )
                << "\", shape=record, rankdir=LR, "
                << "style=\"filled\", colorscheme=reds9, color=" << color << "];"
                << std::endl;
         }
         IntegerList dds, ddm, tdd;
         trx->find_daughters( i, dds, ddm, tdd );
         for( size_t j = 0; j < dds.size(); j++ )
         {
             int daughter_loc = dds.at( j );
             int transition_id = ddm.at( j );
             if( tfilter.filter( transition_id ) ) continue;
             std::pair<int,int> combo(parent_id,transition_id);
             if( transition_used.count(combo)>0 ){
                 continue;
             } else {
                 transition_used.insert( combo );
             }
             std::string color;
             std::string style( "solid" );
             float max_penwidth = 3.0;
             float penwidth = max_penwidth;
             if( transition_id < 0 )
             {
                 color = "palegreen3";
                 style = "dashed";
                 float dk_normalizer = 0.0001;  // 0.7 hr half-life
                 float value = amatrix->at( tdd.at( j ) );
                 os << "// dk value=" << value << std::endl;
                 penwidth =
                     max_penwidth *
                     std::max( 0.1f, std::min( 1.0f, value / dk_normalizer ) );
             }
             else
             {
                 float barn_normalizer = 20;  // barns is maximum thickness
                 float value = amatrix->at( tdd.at( j ) );
                 os << "// rx value=" << value << std::endl;
                 penwidth =
                     max_penwidth *
                     std::max( 0.1f, std::min( 1.0f, value / barn_normalizer ) );
                 if( transition_id == 16 )
                 {
                     color = "red";
                 }
                 else if( transition_id == 17 )
                 {
                     color = "orange";
                 }
                 else if( transition_id == 22 )
                 {
                     color = "yellow";
                 }
                 else if( transition_id == 23 )
                 {
                     color = "green";
                 }
                 else if( transition_id == 24 )
                 {
                     color = "blue";
                 }
                 else if( transition_id == 25 )
                 {
                     color = "purple";
                 }
                 else if( transition_id == 28 )
                 {
                     color = "brown";
                 }
                 else if( transition_id == 29 )
                 {
                     color = "violetred4";
                 }
                 else if( transition_id == 32 )
                 {
                     color = "springgreen1";
                 }
                 else if( transition_id == 33 )
                 {
                     color = "slateblue2";
                 }
                 else if( transition_id == 34 )
                 {
                     color = "palevioletred1";
                 }
                 else if( transition_id == 37 )
                 {
                     color = "black";
                 }
                 else if( transition_id == 102 )
                 {
                     color = "red3";
                     style = "solid";
                 }
                 else if( transition_id == 103 )
                 {
                     color = "orange3";
                     style = "solid";
                 }
                 else if( transition_id == 104 )
                 {
                     color = "orange4";
                     style = "solid";
                 }
                 else if( transition_id == 105 )
                 {
                     color = "yellow3";
                     style = "solid";
                 }
                 else if( transition_id == 106 )
                 {
                     color = "yellow4";
                     style = "solid";
                 }
                 else if( transition_id == 107 )
                 {
                     color = "cyan";
                     style = "solid";
                 }
                 else if( transition_id == 108 )
                 {
                     color = "blue4";
                     style = "solid";
                 }
                 else if( transition_id == 111 )
                 {
                     color = "lightskyblue";
                     style = "solid";
                 }
                 else if( transition_id == 112 )
                 {
                     color = "lightsteelblue";
                     style = "solid";
                 }
                 else if( transition_id == 51 )
                 {
                     color = "magenta1";
                     style = "dashed";
                 }
                 else
                 {
                     color = "black";
                     style = "solid";
                 }
             }
             Require( daughter_loc >= 0 && daughter_loc < (int)nucl->size() );
             // we need a better check for byproducts (should use
             // transition_id=0)
             if( !include_byproducts &&
                 ( nucl->at( daughter_loc ) / 10000 ) <= 2 )
             {
                 continue;
             }
             Require( i >= 0 && i < nucl->size() );
             os << nucl->at( i ) << "-> " << nucl->at( daughter_loc )
                << " [penwidth=\"" << penwidth << "\", color=\"" << color
                << "\", style=\"" << style
                << "\", labelangle=45, labeldistance=20";
             bool print_label = false;
             if( print_label )
             {
                 os << ", label=\"" << transition_id << "\"";
             }
             os << "];" << std::endl;
             // os <<  nucl->at(dds.at(j));
             // if( j<(dds.size()-1) ){os <<  "; ";}
         }
         // os << "// max_sigma="<<max_sigma<<std::endl;
         // os <<  "} [penwidth=\"0.1\"];" << std::endl;
     }
     os << "}" << std::endl;
 }
SP_Library interpLibraryND (const std::vector< TagManager > & tagManList, const TagManager & tm)
Examples:
Core/fn/tests/tstinterp.cpp.
References addImpliedTags(), checkImplicitTags(), GridData_TransitionCoeff::get_tm_indexMap(), GridData_TransitionCoeff::getWts(), TransitionCoeff::has_kappa_capture(), TransitionCoeff::has_kappa_fission(), GridData_TransitionCoeff::interpolate_transition_coeff(), TransitionCoeff::kappa_capture_size(), TransitionCoeff::kappa_fission_size(), TagManager::listInterpTags(), loadLibrary(), GridData_TransitionCoeff::setr(), and GridData_TransitionCoeff::setx().
Referenced by Obiwan_interp::execute(), and TEST().
 {
     // Setting up options for opening the libraries on-disk.  New library
     // is returned by this function.
     //Assert(tagManList.size() > 0);
     ScaleUtils::IO::DB opts;
     opts.set( "fileFormat", "bof" );
     // Dimensions over which interpolation will be performed.
     std::vector<std::string> dimNames = tm.listInterpTags();
     // 1 burnup + 5 TC vectors = 6 responses, allowing for the situation
     // in which kappa_fission and kappa_capture vectors aren't present.
     int numR = 6;
     // Check to see if kappa_fission and kappa_capture exist;
     // calibrate the number of interpolated responses accordingly
     SP_Library checkLib =
         SP_Library( loadLibrary( tagManList[0].getIdTag( "Filename" ), opts ) );
     const TransitionCoeff& checkTC = checkLib->transition_coeff_at( 0 );
     if( checkTC.has_kappa_fission() && checkTC.kappa_fission_size() > 0 )
         numR++;
     if( checkTC.has_kappa_capture() && checkTC.kappa_capture_size() > 0 )
         numR++;
     /*
      * This sweeps through the tag managers and ensures that each one has
      * the dimensions over which interpolation has been requested.  Also
      * checks to see if there are populated dimensions that haven't been
      * specified and collects those tags along with their values.
      */
     std::vector<implicitTag> tagSpans = checkImplicitTags( tagManList, tm );
     // If other tags were found, the average of their values is taken
     // and interpolation will be performed to that average value.
     TagManager new_tm( tm );
     addImpliedTags( tagSpans, &new_tm, &dimNames );
     /*
      * Set up the N-dimensional space over which we have libraries and
      * return a std::vector specifying the position of each library in libList
      * in a single flat std::vector in the order they appear in the grid.
      */
     std::vector<size_t> libOrder;
     GridData_TransitionCoeff InterpGrid;
     InterpGrid.setx( tagManList, dimNames, numR );
     libOrder = InterpGrid.get_tm_indexMap();
     // Now re-order the Libraries based on libOrder
     std::vector<TagManager> gridOrderedLibs;
     for( auto& idx : libOrder )
     {
         Check( idx < tagManList.size() );
         gridOrderedLibs.push_back( tagManList[idx] );
     }
     Insist( tagManList.size() == gridOrderedLibs.size(),
             "Did not get the same numbers out of Libraries out of re-order as "
             "went in." );
     // Determine the weights for the libraries and order to match libOrder.
     GridData_TransitionCoeff::Vec_Xptr wts = InterpGrid.getWts( new_tm );
     // Determine which libraries have non-zero weights.
     // These are the only ones that will be opened.
     std::vector<bool> nonzero = InterpGrid.nonzero_wt_map( wts );
     Insist( nonzero.size() == gridOrderedLibs.size(),
             "Weights std::vector size doesn't match Ordered Library size." );
     // Now add the responses to the grid via GridView objects
     // Do this for the first burnup value on the Library
     SP_Library refLib = SP_Library(
         loadLibrary( gridOrderedLibs[0].getIdTag( "Filename" ), opts ) );
     SP_TransitionCoeff blankTC = refLib->transition_coeff_at( 0 ).clone();
     blankTC->scale( 0.0 );
     // Set up the new library that will hold the interpolated TCs
     SP_Library newLib = refLib->clone();
     newLib->set_tag_manager( new_tm );
     for( size_t bu = 0; bu < refLib->transition_coeff_size(); ++bu )
     {
         std::vector<GridView_TransitionCoeff> gridResponses;
         for( size_t k = 0; k < nonzero.size(); ++k )
         {
             if( nonzero[k] )
             {
                 SP_Library tempLib = SP_Library( loadLibrary(
                     gridOrderedLibs[k].getIdTag( "Filename" ), opts ) );
                 Ensure( tempLib->has_transition_coeff_at( bu ) );
                 Insist( refLib->transition_coeff_size() ==
                             tempLib->transition_coeff_size(),
                         "Number of burnups non-equal between libraries." );
                 gridResponses.emplace_back(
                     tempLib->scp_transition_coeff_at( bu ) );
             }
             else
             {
                 gridResponses.emplace_back( blankTC );
             }
         }
         InterpGrid.setr( gridResponses );
         SP_TransitionCoeff interpTC =
             InterpGrid.interpolate_transition_coeff( wts );
         // Replace the TC at each burnup point
         newLib->set_transition_coeff_at( *interpTC, bu );
         Ensure( newLib->has_transition_coeff_at( bu ) );
     }  // end loop over burnups
     return ( newLib );
 }
SP_Library interpLibraryND (const std::vector< SCP_Library > & libList, const TagManager & tm)
on-disk
References addImpliedTags(), checkImplicitTags(), GridData_TransitionCoeff::get_tm_indexMap(), GridData_TransitionCoeff::getWts(), GridData_TransitionCoeff::interpolate_transition_coeff(), TagManager::listInterpTags(), GridData_TransitionCoeff::setr(), and GridData_TransitionCoeff::setx().
 {
     // In-memory libraries provided directly to the function
     // Dimensions over which interpolation will occur, based on provided
     // TagManager.
     std::vector<std::string> dimNames = tm.listInterpTags();
     // 1 burnup and 5 definite TC vectors.  kappa_fission and kappa_capture may
     // be
     // empty.  This will be determined later and numR will be adjusted
     // accordingly.
     int numR = 6;
     // Check to see if the libraries have kappa_fission and kappa_capture in
     // their transition coefficients in order to properly calibrate the number
     // of interpolated responses
     SCP_Library refLib = libList[0];
     SCP_TransitionCoeff refTC = refLib->scp_transition_coeff_at( 0 );
     if( refTC->has_kappa_fission() && refTC->kappa_fission_size() > 0 ) numR++;
     if( refTC->has_kappa_capture() && refTC->kappa_capture_size() > 0 ) numR++;
     // List of tag managers to feed to tag-checking function.
     // These tags will also be used to define the interpolation grid.
     std::vector<TagManager> tagManList;
     for( auto& lib : libList ) tagManList.push_back( lib->tag_manager() );
     /*
      * Checks that each library provided in libList has the dimensions for
      * interpolation
      * specified in its tag manager. Also checks to see if there are other
      * dimensions
      * over which the libraries span.  If so, the points in those dimensions are
      * collected
      * for later assessment.
      */
     std::vector<implicitTag> tagSpans = checkImplicitTags( tagManList, tm );
     /*
      * Reviews the values of the tags in any dimension not specified. The
      * average value in each dimension is calculated and that value is
      * added to the tag manager as target values for interpolation.
      */
     TagManager new_tm( tm );
     if( tagSpans.size() > 0 ) addImpliedTags( tagSpans, &new_tm, &dimNames );
     /*
      * Set up the GridData grid space over which we have libraries and
      * return a std::vector specifying the position of each library in libList
      * in a single flat std::vector in the order they appear in the grid.
      */
     GridData_TransitionCoeff InterpGrid;
     InterpGrid.setx( tagManList, dimNames, numR );
     std::vector<size_t> libOrder = InterpGrid.get_tm_indexMap();
     // Now re-order the Libraries based on libOrder
     std::vector<SCP_Library> gridOrderedLibs;
     for( auto& idx : libOrder )
     {
         Check( idx < libList.size() );
         gridOrderedLibs.push_back( libList[idx] );
     }
     Insist( libList.size() == gridOrderedLibs.size(),
             "Did not get the same number of Libraries out of re-order as went "
             "in." );
     /*
      * Uses interpwts_lin to determine the weights of the libraries for
      * interpolation based on their relative proximity to the specified
      * values in each dimension for the new Library.
      */
     GridData_TransitionCoeff::Vec_Xptr wts = InterpGrid.getWts( new_tm );
     // std::vector specifiying which libraries have non-zero weights so we only
     // use the libraries that we need for interpolation.
     std::vector<bool> nonzero = InterpGrid.nonzero_wt_map( wts );
     Insist( nonzero.size() == gridOrderedLibs.size(),
             "Weights std::vector size doesn't match Ordered Library size." );
     // Initialization of final library.  Non-burnup dependent data is copied.
     SP_Library newLib = refLib->clone();
     // Tag manager with all dimensions specified added to final library.
     newLib->set_tag_manager( new_tm );
     // Now add the responses to the grid via GridView objects
     // Do this for the first burnup value on the Library
     SP_TransitionCoeff blankTC = refLib->transition_coeff_at( 0 ).clone();
     blankTC->scale( 0.0 );
     for( size_t bu = 0; bu < refLib->transition_coeff_size(); ++bu )
     {
         std::vector<GridView_TransitionCoeff> gridResponses;
         for( size_t k = 0; k < nonzero.size(); ++k )
         {
             if( nonzero[k] )
             {
                 Ensure( gridOrderedLibs[k]->has_transition_coeff_at( bu ) );
                 Ensure(
                     gridOrderedLibs[k]->transition_coeff_at( bu ).burnup() ==
                     refLib->transition_coeff_at( bu ).burnup() );
                 Insist( refLib->transition_coeff_size() ==
                             gridOrderedLibs[k]->transition_coeff_size(),
                         "Number of burnups non-equal between libraries." );
                 gridResponses.emplace_back(
                     gridOrderedLibs[k]->scp_transition_coeff_at( bu ) );
             }
             else
             {
                 gridResponses.emplace_back( blankTC );
             }
         }
         // Setup the responses to interpolate & generate an
         // interpolated TransitionCoeff at this burnup
         InterpGrid.setr( gridResponses );
         SP_TransitionCoeff interpTC =
             InterpGrid.interpolate_transition_coeff( wts );
         // Add the new transition coefficient to the library.
         // newLib->add_transition_coeff(*interpTC);
         // Replace TCs at each burnup point
         newLib->set_transition_coeff_at( *interpTC, bu );
         Ensure( newLib->has_transition_coeff_at( bu ) );
     }  // end loop over burnups
     return ( newLib );
 }
std::vector< TagManager > selectLibraries (const std::vector< TagManager > & tmList, const TagManager & tmRef)
Function to take a wide selection of Origen Libraries in memory and only return those that have the ID and Interp tags requested in the provided TagManager. Then checks to make sure the ID tag values match.
Parameters
libList - List of Origen Library TagManagers that contain a subset that match the tags contained in the SP_TagManager tm.
tm - TagManager containing the ID tags for the type of Libraries that are desired and interp tags with values for the new Library that will be generated using the ND_LibInterp. This function does NOT check the values of the interp tags
Examples:
Core/fn/tests/tstinterp.cpp.
Referenced by Obiwan_interp::execute(), and TEST().
 {
     std::vector<TagManager> newList;
     for( auto& tm : tmList )
     {
         if( tm.interpolationCompare( tmRef ) ) newList.push_back( tm );
     }
     return ( newList );
 }
std::vector< SCP_Library > selectLibraries (const std::vector< SCP_Library > & libList, const TagManager & tmRef)
Function to take a wide selection of Origen Libraries in memory and only return those that have the ID and Interp tags requested in the provided TagManager. Then checks to make sure the ID tag values match.
libList Set of Origen Library objects containing a subset that have TagManager objects with tags that match the tags in tm
Parameters
tm - TagManager containing the ID tags for the type of Libraries that are desired and interp tags with values for the new Library that will be generated using the ND_LibInterp. This function does NOT check the values of the interp tags
 {
     std::vector<SCP_Library> newList;
     for( auto& lib : libList )
     {
         if( lib->tag_manager().interpolationCompare( tmRef ) )
             newList.push_back( lib );
     }
     return ( newList );
 }
std::vector< SP_TagManager > collectLibraries (const std::vector< std::string > & lib_names)
Function that accepts names of Origen library files on disk which can be full paths if necessary.
Parameters
lib_names -vector of strings giving the library file names as a relative or absolute path.
Returns
Vector of SP_TagManager objects from all of the libraries in lib_names with a new ID tag with name "Filename" and value of the string from lib_names.
Examples:
Core/fn/tests/tstio.cpp.
References loadMulti(), and TagManager::setIdTag().
Referenced by collectLibrariesParallel(), and TEST().
 {
     std::vector<SP_TagManager> tagmans;
     for( auto name : lib_names )
     {
         ScaleUtils::IO::DB opts;
         opts.set( "dataType", "Origen::Library" );
         Origen::TagManager tmp_tm;
         jDebugLine( "    opening library: " << name );
         auto lib = SP_Library( (Library*)( loadMulti( name, opts ) ) );
         std::string typ = opts.get<std::string>( "loadedDataType" );
         if( typ != "Origen::Library" )
         {
             opts.clearErrorStack();
             continue;
         }
         else if( !lib->has_tag_manager() )
         {
             continue;
         }
         lib->get_tag_manager( tmp_tm );
         tmp_tm.setIdTag( "Filename", name );
         lib->set_tag_manager( tmp_tm );
         auto tmp = SP_TagManager( new TagManager( tmp_tm ) );
         tagmans.push_back( tmp );
     }
     return(tagmans);
 }
std::vector< SP_TagManager > collectLibrariesParallel (const std::vector< std::string > & lib_names)
Function that accepts names of Origen library files on disk which can be full paths if necessary.
Parameters
lib_names -ector of strings giving the library file names as a relative or absolute path.
Returns
Vector of SP_TagManager objects from all of the libraries in lib_names with a new ID tag with name "Filename" and value of the string from lib_names.
Examples:
Core/fn/tests/tstio.cpp.
References collectLibraries().
Referenced by TEST().
 {
 //  Function uses the previous function to collect libraries if
 //  there are few enough, with asynchronus recursive calls to this
 //  function if there are too many libraries.
     size_t numlibs = lib_names.size();
     if( numlibs < 100)
     {
       std::vector<SP_TagManager> tagmans = collectLibraries( lib_names );
       return( tagmans );
     }
     std::vector<std::string> midlibs( lib_names.rbegin(), lib_names.rbegin()+99 );
     std::vector<std::string> beglibs( lib_names.begin(), lib_names.end()-99 );
     auto final_half = std::async( std::launch::async, collectLibrariesParallel, midlibs );
     std::vector<SP_TagManager> tagmans = collectLibrariesParallel( beglibs );
     for( auto midtags : final_half.get() ) tagmans.push_back( midtags );
     return ( tagmans );
 }
bool Origen::setbuLibrary (Library & obj, ScaleUtils::IO::DB & opts)
References TransitionCoeff::set_burnup(), Library::set_transition_coeff_at(), Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by convertLibrary().
 {
     if( opts.has<DoubleList*>( "newBurnups" ) )
     {
         auto newBurnups = opts.get<DoubleList*>( "newBurnups" );
         size_t n = newBurnups->size();
         if( n != obj.transition_coeff_size() )
         {
             opts.appendError( nprintf(
                 "new burnups size=%d inconsistent with number on library=%d",
                 n,
                 obj.transition_coeff_size() ) );
             return false;
         }
         for( size_t i = 0; i < n; ++i )
         {
             auto tc = obj.transition_coeff_at( i );
             tc.set_burnup( newBurnups->at( i ) );
             obj.set_transition_coeff_at( tc, i );
         }
     }
     return true;
 }
bool Origen::thinLibrary (Library & obj, ScaleUtils::IO::DB & opts)
References TransitionCoeff::burnup(), Library::definition(), Library::delete_transition_coeff_at(), NuclideSet::lookup_index_guess(), LibraryHeader::nuclide_set(), populateLossXsValues(), Library::regrid(), Library::regrid_Interp1D(), Library::set_interpolator(), NuclideSet::symbol_to_izzzaaa(), Library::total_nuclides(), Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by convertLibrary().
 {
     if( opts.get<bool>( "thinningEnabled" ) )
     {
         // time units
         std::string timeUnits = opts.acquire( "timeUnits", "MWD/MTIHM" );
         if( timeUnits != "MWD/MTIHM" )
         {
             opts.appendError( " only timeUnits='MWD/MTIHM' supported." );
             return false;
         }
         auto timeValues = opts.acquire<DoubleList*>( "timeValues" );
         if( timeValues->size() == 0 )
         {
             for( size_t i = 0; i < obj.transition_coeff_size(); ++i )
             {
                 timeValues->push_back( obj.transition_coeff_at( i ).burnup() );
             }
         }
         // interpolation
         std::string interpMethod = opts.acquire( "interpMethod", "lin" );
         if( interpMethod == "lin" )
         {
             obj.set_interpolator(
                 &(ScaleUtils::Math::interpwts_lin<Vec_Flt, float>));
         }
         else if( interpMethod == "near" )
         {
             obj.set_interpolator(
                 &(ScaleUtils::Math::interpwts_near<Vec_Flt, float>));
         }
         else if( interpMethod == "cubic" )
         {
             // Do nothing for now; eventually initialize an Interp1D_CubicSpline
             // object?
         }
         else
         {
             opts.appendError(
                 " only interpMethod='cubic'|'lin'|'near' supported." );
             return false;
         }
         std::string responseVariable =
             opts.acquire( "responseVariable", "loxs" );
         if( responseVariable != "loxs" )
         {
             opts.appendError( " only responseVariable='loxs' is supported" );
             return false;
         }
         // get response values
         std::string responseNuclide =
             opts.acquire( "responseNuclide", "pu240" );
         int id =
             obj.definition().nuclide_set().symbol_to_izzzaaa( responseNuclide );
         if( id <= 0 )
         {
             opts.appendError( " responseNuclide='" + responseNuclide +
                               "' could not be converted to integer id" );
             return false;
         }
         size_t nind = obj.definition().nuclide_set().lookup_index_guess( id );
         if( nind > obj.total_nuclides() )
         {
             opts.appendError( nprintf(
                 "nuclide id=%d does not exist (parsed from string='%s')",
                 id,
                 responseNuclide.c_str() ) );
             return false;
         }
         auto oldResponseValues =
             opts.acquire<DoubleList*>( "oldResponseValues" );
         auto oldTimeValues = opts.acquire<DoubleList*>( "oldTimeValues" );
         // get old loss XS
         populateLossXsValues( oldTimeValues, oldResponseValues, obj, nind );
         // regrid the library to the user values
         if( interpMethod == "cubic" )
         {
             Vec_Dbl dblTimeValues( timeValues->begin(), timeValues->end() );
             obj.regrid_Interp1D( dblTimeValues );
         }
         else
         {
             Vec_Flt fltTimeValues( timeValues->begin(), timeValues->end() );
             obj.regrid( fltTimeValues );
         }
         // get new loss XS
         auto responseValues = opts.acquire<DoubleList*>( "responseValues" );
         populateLossXsValues( timeValues, responseValues, obj, nind );
         Check( obj.transition_coeff_size() == responseValues->size() );
         // remove duplicates
         size_t i = 0;
         while( i < timeValues->size() - 1 )
         {
             if( timeValues->at( i ) == timeValues->at( i + 1 ) )
             {
                 timeValues->erase( i + 1 );
                 responseValues->erase( i + 1 );
                 obj.delete_transition_coeff_at( i + 1 );
             }
             else
             {
                 ++i;
             }
         }
     }
     return true;
 }
bool convertLibrary (Library & obj, const std::string & path, ScaleUtils::IO::DB & opts)
References saveLibrary(), setbuLibrary(), and thinLibrary().
Referenced by Obiwan_convert::execute().
 {
     // try to get an explicit file format to convert to
     std::string fileFormat = opts.get( "fileFormat", "" );
     // otherwise use the convert string
     if( fileFormat.length() == 0 )
     {
         auto targetVersion =
             Version( opts.acquire( "targetScaleVersion", "6.2" ) );
         if( targetVersion >= Version( "6.2.0" ) )
         {
             fileFormat = "bof";
         }
         else if( targetVersion >= Version( "6.2.pre-b1" ) )
         {
             fileFormat = "s62b";
         }
         else if( targetVersion >= Version( "6.1.0" ) )
         {
             fileFormat = "s61";
         }
         else
         {
             fileFormat = "bof";
         }
         opts.set( "fileFormat", fileFormat );
     }
     std::string directory = opts.get( "targetDirectory", "." );
     // get new path
     bool removeExtension = true;
     std::string baseName =
         ScaleUtils::IO::getBaseName( path.c_str(), removeExtension );
     std::string newFile = baseName + ".f33";
     std::string newPath =
         directory + ScaleUtils::IO::getSeparatorCharacter() + newFile;
     bool overwrite = opts.get( "overwrite", false );
     if( ScaleUtils::IO::fileExists( newPath ) && !overwrite )
     {
         opts.appendError( " will not overwrite file='" + newPath + "'" );
         return false;
     }
     // try to add burnups to library
     if( !setbuLibrary( obj, opts ) ) return false;
     // try to thin library
     if( !thinLibrary( obj, opts ) ) return false;
     return saveLibrary( obj, newPath, opts );
 }
bool convertStateSet (StateSet & obj, const std::string & path, ScaleUtils::IO::DB & opts)
References saveStateSet().
Referenced by Obiwan_convert::execute().
 {
     // try to get an explicit file format to convert to
     std::string fileFormat = opts.get( "fileFormat", "" );
     // otherwise use the convert string
     if( fileFormat.length() == 0 )
     {
         auto targetVersion =
             Version( opts.acquire( "targetScaleVersion", "6.2" ) );
         if( targetVersion >= Version( "6.2.0" ) )
         {
             fileFormat = "bof";
         }
         else if( targetVersion >= Version( "6.2.pre-b1" ) )
         {
             fileFormat = "s62b";
         }
         else if( targetVersion >= Version( "6.1.0" ) )
         {
             fileFormat = "s61";
         }
         else
         {
             fileFormat = "bof";
         }
         opts.set( "fileFormat", fileFormat );
     }
     std::string directory = opts.get( "targetDirectory", "." );
     // get new path
     bool removeExtension = true;
     std::string baseName =
         ScaleUtils::IO::getBaseName( path.c_str(), removeExtension );
     std::string newFile = baseName + ".f71";
     std::string newPath =
         directory + ScaleUtils::IO::getSeparatorCharacter() + newFile;
     bool overwrite = opts.get( "overwrite", false );
     if( ScaleUtils::IO::fileExists( newPath ) && !overwrite )
     {
         opts.appendError( " will not overwrite file='" + newPath + "'" );
         return false;
     }
     return saveStateSet( obj, newPath, opts );
 }
void * loadMulti (const std::string & path, ScaleUtils::IO::DB & opts)
References loadDecayResource(), loadLibrary(), loadStateSet(), loadYieldResource(), YieldResource::num_fissionables(), DecayResource::num_parents(), StateSet::states_size(), and Library::transition_coeff_size().
Referenced by collectLibraries(), Obiwan_tag::execute(), Obiwan_patch::execute(), Obiwan_convert::execute(), and Obiwan_diff::execute().
 {
     Require( opts.numError() == 0 );
     // quick return if path is bad
     if( !opts.checkFile( path ) )
     {
         opts.appendError( "path=" + path + " does not exist" );
         return nullptr;
     }
     auto dataType = opts.get<std::string>( "dataType", "" );
     // save original options
     auto get_opts = opts.clone();
     ///\todo: Can use templated load below for each data type in the blocks for
     ///       load operations. Will have to do loadedSets still but it will
     ///       still reduce a lot of the redundant code below.
     if( dataType == "Origen::Library" || dataType == "" )
     {
         Library* lib = loadLibrary( path, get_opts );
         if( lib )
         {
             opts.swap( get_opts );
             opts.set<int>( "loadedSets", lib->transition_coeff_size() );
             opts.set( "loadedDataType", "Origen::Library" );
             return lib;
         }
     }
     if( dataType == "Origen::StateSet" || dataType == "" )
     {
         StateSet* mat = loadStateSet( path, get_opts );
         if( mat )
         {
             opts.swap( get_opts );
             opts.set<int>( "loadedSets", mat->states_size() );
             opts.set( "loadedDataType", "Origen::StateSet" );
             return mat;
         }
     }
     if( dataType == "Origen::YieldResource" || dataType == "" )
     {
         YieldResource* yld = loadYieldResource( path, get_opts );
         if( yld )
         {
             opts.swap( get_opts );
             opts.set<int>( "loadedSets", yld->num_fissionables() );
             opts.set( "loadedDataType", "Origen::YieldResource" );
             return yld;
         }
     }
     if( dataType == "Origen::DecayResource" || dataType == "" )
     {
         DecayResource* dr = loadDecayResource( path, get_opts );
         if( dr )
         {
             opts.swap( get_opts );
             opts.set<int>( "loadedSets", dr->num_parents() );
             opts.set( "loadedDataType", "Origen::DecayResource" );
             return dr;
         }
     }
     opts.swap( get_opts );
     return nullptr;
 }
void saveStateSet (const MaterialMap & matmap, const std::string & path, ScaleUtils::IO::DB opts)
saves all isotopics in a MaterialMap to an FT71 (StateSet)
Examples:
Core/fn/tests/tstio.cpp, Core/io/tests/tstStateSetIO.cpp, and Core/ut/tests/tstObiwan.cpp.
References BAD_SIZE_T.
Referenced by convertStateSet(), TEST(), and TEST_F().
 {
     saveStateSet( BAD_SIZE_T, BAD_SIZE_T, matmap, path, opts );
 }
void saveStateSet (size_t pstart, size_t pend, const MaterialMap & matmap, const std::string & path, ScaleUtils::IO::DB opts)
saves a range of isotopics in a MaterialMap to an FT71 (StateSet) Isotopics from time points p satisfying pstart<=p<=pend are saved. Consider isotopics data at 5 time points.
p=0   1   2   3   4
  |   |   |   |   |
To ask for a dump of p=2,3,4 isotopics, supply pstart=2,pend=4 and the
time points below will be dumped.
p=0 1 2 3 4 | | * * *
References BAD_SIZE_T, Material::flux_over(), Material::get_concs_at(), Material::library(), Material::name(), Material::ntimes(), Material::power_over(), StateInfo::set_case_number(), State::set_concs(), State::set_definition(), StateInfo::set_flux(), StateInfo::set_library_position(), Concentrations::set_nuclide_set(), StateInfo::set_power(), StateInfo::set_step_number(), StateInfo::set_tag_manager(), StateInfo::set_time(), TagManager::setIdTag(), and Material::time_at().
 {
     // BAD_SIZE_T means start at 0
     size_t local_pstart = pstart == BAD_SIZE_T ? 0 : pstart;
     // append to existing files if pstart>0 AND not already set (acquire
     // is a good way to do that)
     opts.acquire<bool>( "appendExisting", local_pstart > 0 );
     // add data here
     StateSet state_set;
     // iterate through and add data
     for( const auto& id_mat : matmap )
     {
         int id = id_mat.first;
         const Material& mat = *id_mat.second;
         // BAD_SIZE_T means go to the end
         size_t local_pend = pend == BAD_SIZE_T ? mat.ntimes() - 1 : pend;
         Check( local_pstart <= local_pend );
         Check( local_pend < mat.ntimes() );
         for( size_t p = local_pstart; p <= local_pend; ++p )
         {
             // save data on the interval i
             // first map from time point "p" to interval "i"
             // p=0,1 get the same interval data
             size_t i = p == 0 ? 0 : p - 1;
             // populate definition
             StateInfo def;
             def.set_power( mat.power_over( i ) );
             def.set_flux( mat.flux_over( i ) );
             def.set_step_number( i );
             def.set_case_number( id );
             def.set_time( mat.time_at( p ) );
             def.set_library_position( i );
             // populate tags
             TagManager tagman;
             tagman.setIdTag( "name", mat.name() );
             tagman.setIdTag( "id", std::to_string( id ) );
             def.set_tag_manager( tagman );
             // create state
             State state;
             // 1. add definition
             state.set_definition( def );
             // 2. add concs
             Concentrations concs;
             concs.set_nuclide_set( mat.library()->definition().nuclide_set() );
             mat.get_concs_at( &concs, p );
             state.set_concs( concs );
             // 3. add state
             state_set.add_states( state );
         }
     }
     // dump data
     StateSetIO io;
     io.save( state_set, path, opts );
 }
void saveLibraries (size_t pstart, size_t pend, const MaterialMap & matmap, const std::string & pathfmt, ScaleUtils::IO::DB opts)
saves a range of transition data in a MaterialMap to an FT33 (Library)
Data from time intervals satisfying pstart<=i<pend are saved, pstart and pend are the starting and ending time points, and i is the time interval. Consider data with 5 time points and therefore 4 intervals.
p=0   1   2   3   4
  |   |   |   |   |
  i=0   1   2   3
To ask for a dump of interval i=2,3 data, you would supply pstart=2,pend=4 and the * intervals below will be dumped.
p=0   1   2   3   4
  |   |   | * | * |
  i=0   1   2   3
Note that transition data is calculated as an average over an interval so that for any data to be dumped, one must have pstart<pend.
Unlike saveStateSet, saveLibraries outputs a file for each material individually. The pathfmt argument allows substitution of both the Material::name() and Material::id(). The path is written using: std::string path=findAndReplace(pathfmt,"$name",mat.name()); if(path.find("%")!=std::string::npos){ path=nprintf(path.c_str(),mat.id()); }
References BAD_SIZE_T, Material::library(), Material::name(), Material::ntimes(), Library::resize_transition_coeff(), and Material::transition_matrix_over().
 {
     // BAD_SIZE_T means start at 0
     size_t local_pstart = pstart == BAD_SIZE_T ? 0 : pstart;
     // append to existing files if pstart>0 AND not already set (acquire
     // is a good way to do that)
     opts.acquire<bool>( "appendExisting", local_pstart > 0 );
     // iterate through and add data
     for( const auto& id_mat : matmap )
     {
         int id = id_mat.first;
         const Material& mat = *id_mat.second;
         // BAD_SIZE_T means go to the end
         size_t local_pend = pend == BAD_SIZE_T ? mat.ntimes() - 1 : pend;
         // make sure we have something to do
         if( local_pstart < local_pend )
         {
             // create path
             std::string path =
                 ScaleUtils::IO::findAndReplace( pathfmt, "$name", mat.name() );
             if( path.find( "%" ) != std::string::npos )
             {
                 path = nprintf( path.c_str(), id );
             }
             // create a library but erase the coefficients
             //(don't worry, this is really cheap because of COW)
             Library lib( *mat.library() );
             lib.resize_transition_coeff( 0 );
             // add data to library
             for( size_t i = local_pstart; i < local_pend; ++i )
             {
                 lib.add_transition_matrix( *mat.transition_matrix_over( i ) );
             }
             // dump library
             LibraryIO io;
             io.save( lib, path, opts );
         }
     }
 }
void setAppVersionWrite (bof::BOFWriter & writer, ScaleUtils::IO::DB & opts, const std::string & name)
References version().
Referenced by LibraryIO_bof::write(), and StateSetIO_bof::write().
 {
     writer.setAppName( name );
     opts.set( "wroteAppName", name );
     auto version = Scale::globalProductVersion();
     writer.setAppMajor( bof::uchar( version.major() ) );
     writer.setAppMinor( bof::uchar( version.minor() ) );
     writer.setAppMicro( bof::uchar( version.micro() ) );
     opts.set( "wroteAppMajor", version.major() );
     opts.set( "wroteAppMinor", version.minor() );
     opts.set( "wroteAppMicro", version.micro() );
     opts.set( "wroteAppVersion", version.asString() );
 }
std::string Origen::stringifySublib (int sublib)
References SUBLIB_1LT, SUBLIB_2AC, SUBLIB_3FP, SUBLIB_4U1, SUBLIB_5U2, SUBLIB_6U3, SUBLIB_7U4, SUBLIB_8TA, and SUBLIB_9BY.
Referenced by stringifyNuclide().
 {
     if( sublib == Origen::SUBLIB_1LT ) return "LT";
     if( sublib == Origen::SUBLIB_2AC ) return "AC";
     if( sublib == Origen::SUBLIB_3FP ) return "FP";
     if( sublib == Origen::SUBLIB_4U1 ) return "U1";
     if( sublib == Origen::SUBLIB_5U2 ) return "U2";
     if( sublib == Origen::SUBLIB_6U3 ) return "U3";
     if( sublib == Origen::SUBLIB_7U4 ) return "U4";
     if( sublib == Origen::SUBLIB_8TA ) return "TA";
     if( sublib == Origen::SUBLIB_9BY ) return "BY";
     return "";
 }
std::string stringifyNuclide (int id, std::string idform)
idform can include various symbols to be substituted
Examples:
Core/fn/tests/tstpopulate.cpp.
References stringifySublib().
Referenced by printConcentrations_csv(), printTransitionSystemXs(), tabulateMaterialTransitionRates(), tabulateNuclideLabel(), tabulateReactionTransitions(), tabulateTransitionCoeff(), and TEST().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( id, s, i, z, a );
     // quick return on standard SIZZZAAA form
     if( idform == "$S$I$ZZZ$AAA" || idform == "" )
     {
         return nprintf( "%07d", id );
     }
     std::string str = idform;
     // get various element representations
     std::string ee = stringToLower( ScaleData::Utils::z_to_symbol( z ) );
     std::string EE = stringToUpper( ee );
     std::string Ee = ee;
     std::transform( Ee.begin(), Ee.begin() + 1, Ee.begin(), ::toupper );
     std::string TY = stringifySublib( s ).c_str();
     std::string ty = stringToLower( TY );
     // get various metastable representations
     std::string M = "";
     if( i > 0 ) M = "M";
     if( i > 1 ) M += std::to_string( i );
     std::string m = stringToLower( M );
     str = findAndReplace( str, "$ZZZ", nprintf( "%03d", z ) );
     str = findAndReplace( str, "$ZZ", nprintf( "%02d", z ) );
     str = findAndReplace( str, "$Z", nprintf( "%d", z ) );
     str = findAndReplace( str, "$AAA", nprintf( "%03d", a ) );
     str = findAndReplace( str, "$AA", nprintf( "%02d", a ) );
     str = findAndReplace( str, "$A", nprintf( "%d", a ) );
     str = findAndReplace( str, "$S", nprintf( "%d", s ) );
     str = findAndReplace( str, "$I", nprintf( "%d", i ) );
     str = findAndReplace( str, "$EE", nprintf( "%s", EE.c_str() ) );
     str = findAndReplace( str, "$ee", nprintf( "%s", ee.c_str() ) );
     str = findAndReplace( str, "$Ee", nprintf( "%s", Ee.c_str() ) );
     str = findAndReplace( str, "$M", nprintf( "%s", M.c_str() ) );
     str = findAndReplace( str, "$m", nprintf( "%s", m.c_str() ) );
     str = findAndReplace( str, "$TY", nprintf( "%s", TY.c_str() ) );
     str = findAndReplace( str, "$ty", nprintf( "%s", ty.c_str() ) );
     return str;
 }
void populateLossXsValues (DoubleList * times, DoubleList * responseValues, const Library & obj, const int nind)
References TransitionCoeff::burnup(), TransitionCoeff::loss_xs(), Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by thinLibrary().
 {
     size_t n = obj.transition_coeff_size();
     responseValues->resize( n );
     times->resize( n );
     for( size_t i = 0; i < n; ++i )
     {
         ( *times )[i] = obj.transition_coeff_at( i ).burnup();
         ( *responseValues )[i] =
             obj.transition_coeff_at( i ).loss_xs().at( nind );
     }
 }
void populateNuclideResource_StdComp (Origen::NuclideResource * nr, const ScaleData::StdComp & stdcomp)
populate a nuclide resource (in place) from a ScaleData::StdComp object
References NuclideResource::Properties::abundance_num, NuclideResource::Properties::abundance_wt, NuclideResource::Properties::mass, auxiliary::nuclide(), and NuclideResource::parent_map.
Referenced by defaultNuclideResource().
 {
     Require( nr != nullptr );
     nr->parent_map.clear();
     // masses
     for( auto i = stdcomp.getNuclides().begin(),
               end = stdcomp.getNuclides().end();
          i != end;
          i++ )
     {
         Origen::NuclideResource::Properties props;
         int nuclide_id = i->first;
         int P, I, Z, A;
         ScaleData::Utils::split_pizzzaaa( nuclide_id, P, I, Z, A );
         if( P != 0 ) continue;
         if( Z == 0 || Z > 130 ) continue;
         if( A == 0 || A > 300 ) continue;
         ScaleData::Nuclide* nuclide = i->second;
         Check( nuclide != nullptr );
         props.mass = nuclide->getMass();
         // jDebugLine("nuclide id="<<nuclide_id);
         // jDebugLine("nuclide mass="<<std::setprecision(12)<<props.mass);
         props.abundance_wt = 0.0;
         props.abundance_num = 0.0;
         nr->parent_map[nuclide_id] = props;
     }
     // abundances
     std::set<int> found;
     for( auto i = stdcomp.getElements().begin(),
               end = stdcomp.getElements().end();
          i != end;
          i++ )
     {
         if( i->second.size() == 0 ) continue;
         ScaleData::Element* element = i->second[0];
         // check that it looks like an element id
         int element_id = element->getId();
         if( element_id % 1000 != 0 ) continue;
         int z = element_id / 1000;
         if( z == 0 || z > 130 ) continue;
         jDebugLine( "element id=" << element_id << " z=" << z );
         if( found.count( z ) > 0 )
         {
             jDebugLine( "    already found" );
             continue;
         }
         found.insert( z );
         const auto& nucs = element->getNuclidesMap();
         std::vector<int> ids;
         std::vector<float> wts;
         std::vector<float> nums;
         std::vector<float> masses;
         double sum_nums = 1e-100;
         for( auto k = nucs.begin(), kend = nucs.end(); k != kend; k++ )
         {
             ScaleData::Nuclide* nuclide = k->second.first;
             Check( nuclide != nullptr );
             float wt = k->second.second;
             int id = nuclide->getId();
             float mass = nuclide->getMass();
             float num = wt / mass;
             ids.push_back( id );
             masses.push_back( mass );
             wts.push_back( wt );
             nums.push_back( num );
             sum_nums += num;
         }
         for( size_t k = 0; k < ids.size(); ++k )
         {
             Origen::NuclideResource::Properties props;
             props.mass = masses[k];
             props.abundance_wt = wts[k];
             props.abundance_num = nums[k] / sum_nums;
             nr->parent_map[ids[k]] = props;
             //             jDebugLine("    nuclide id="<<ids[k]);
             //             jDebugLine("    nuclide mass="<<masses[k]);
             //             jDebugLine("    nuclide wt fraction="<<wts[k]);
             //             jDebugLine("    nuclide num
             //             fraction="<<nums[k]/sum_nums);
         }
     }
     jDebugLine( "leaving populateNuclideResource_StdComp" );
 }
std::map< int, double > construct_neutron_yields_map (const Library & x, int pos)
References Library::definition(), NuclideSet::ids_at(), TransitionCoeff::neutron_yields(), LibraryHeader::nuclide_set(), and Library::transition_coeff_at().
Referenced by Obiwan_diff::diff(), and printNeutronYields().
 {
     const LibraryHeader& lh = x.definition();
     const NuclideSet& nucset = lh.nuclide_set();
     const Vec_Flt& ny = x.transition_coeff_at( pos - 1 ).neutron_yields();
     std::map<int, double> xmap;
     for( size_t i = 0; i < ny.size(); ++i )
     {
         xmap[nucset.ids_at( i )] = ny.at( i );
     }
     return xmap;
 }
std::map< int, double > construct_neutron_prod_map (const Library & x, int pos)
References Library::definition(), NuclideSet::ids_at(), TransitionCoeff::loss_xs(), TransitionCoeff::neutron_yields(), LibraryHeader::nuclide_set(), and Library::transition_coeff_at().
Referenced by printNeutronProductionRatio().
 {
     const LibraryHeader& lh = x.definition();
     const NuclideSet& nucset = lh.nuclide_set();
     const Vec_Flt& ny = x.transition_coeff_at( pos - 1 ).neutron_yields();
     const Vec_Flt& nl = x.transition_coeff_at( pos - 1 ).loss_xs();
     std::map<int, double> xmap;
     for( size_t i = 0; i < ny.size(); ++i )
     {
         double ratio = 0.0;
         if( nl.at( i ) != 0.0 ) ratio = ny.at( i ) / nl.at( i );
         xmap[nucset.ids_at( i )] = ratio;
     }
     return xmap;
 }
std::map< std::pair< int, int >, double > construct_coeff_map (const Library & x, int pos)
References Library::definition(), NuclideSet::ids_at(), NuclideSet::ids_size(), TransitionCoeff::matrix(), LibraryHeader::nuclide_set(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), Library::transition_coeff_at(), and Library::transition_structure().
Referenced by diffLibrary().
 {
     std::map<std::pair<int, int>, double> xmap;
     const LibraryHeader& lh = x.definition();
     const NuclideSet& nucset = lh.nuclide_set();
     const TransitionStructure& tm = x.transition_structure();
     const TransitionCoeff& bd =
         x.transition_coeff_at( static_cast<size_t>( pos - 1 ) );
     //
     // initialize to zero
     //
     int tind = -1;
     const Vec_Int& num_parents = tm.num_parents();
     const Vec_Int& parent_pos = tm.parent_positions();
     for( size_t i = 0; i < nucset.ids_size(); ++i )
     {
         int dsizzzaaa = nucset.ids_at( i );
         for( int count = 0; count < num_parents.at( i ); ++count )
         {
             ++tind;
             int pos = parent_pos.at( tind );
             int psizzzaaa = nucset.ids_at( pos - 1 );
             xmap[std::make_pair( dsizzzaaa, psizzzaaa )] = 0.0;
         }
     }
     //
     // accumulate coefficients (same as above loop)
     //
     tind = -1;
     const Vec_Flt& matrix = bd.matrix();
     for( size_t i = 0; i < nucset.ids_size(); ++i )
     {
         int dsizzzaaa = nucset.ids_at( i );
         for( int count = 0; count < num_parents.at( i ); ++count )
         {
             ++tind;
             int pos = parent_pos.at( tind );
             int psizzzaaa = nucset.ids_at( pos - 1 );
             xmap[std::make_pair( dsizzzaaa, psizzzaaa )] += matrix.at( tind );
         }
     }
     return xmap;
 }
void populateLibraryToxicity_DecayResource (Library * lib, const DecayResource & dr)
populate a library with toxicity factors from a decay resource
References Library::decay_data(), Library::definition(), DecayResource::get_const_parent_map(), NuclideSet::ids(), LibraryHeader::nuclide_set(), DecayData::rcg_for_air, DecayData::rcg_for_water, and Library::set_decay_data().
Referenced by LibraryBuilder::create_decay_library().
 {
     Require( lib != nullptr );
     const Vec_Int& ids = lib->definition().nuclide_set().ids();
     Vec_Flt rcg_for_air( ids.size(), 0.0 );
     Vec_Flt rcg_for_water( ids.size(), 0.0 );
     for( size_t j = 0; j < ids.size(); ++j )
     {
         int izzzaaa = ids[j] % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         const auto& pmap = dr.get_const_parent_map();
         auto it = pmap.find( izzzaaa );
         if( it != pmap.end() )
         {
             rcg_for_air[j] = it->second.get_rcg_for_air();
             rcg_for_water[j] = it->second.get_rcg_for_water();
         }
     }
     // replace rcg on decay data
     DecayData dd = lib->decay_data();
     dd.rcg_for_air = rcg_for_air;
     dd.rcg_for_water = rcg_for_water;
     lib->set_decay_data( dd );
     jDebugTaggedLine( "leaving populateLibraryToxicity_DecayResource" );
 }
void populateLibraryAbundance (Library * lib, const ScaleUtils::IO::DB & opts)
populate a library with abundances from a nuclide resource
populate library from options
References DecayData::abund_of_lite_nuclides, Library::decay_data(), NuclideResource::default_resource(), and populateLibraryAbundance_NuclideResource().
Referenced by c_Origen_populateLibraryAbundance(), LibraryIO_s62b::read(), LibraryIO_s61::read(), and LibraryIO_bof::read().
 {
     bool update_abundance = lib->decay_data().abund_of_lite_nuclides.empty() ||
                             opts.get<bool>( "updateAbundance", false );
     if( update_abundance )
     {
         SCP_NuclideResource nr =
             NuclideResource::default_resource();  // singleton
         populateLibraryAbundance_NuclideResource( lib, *nr );
     }
 }
void populateLibraryAbundance_NuclideResource (Library * lib, const NuclideResource & nr)
populate a library with abundances from a nuclide resource
References DecayData::abund_of_lite_nuclides, NuclideResource::abundance_num(), Library::decay_data(), Library::definition(), NuclideSet::has_sublib(), NuclideSet::has_sublibs(), NuclideSet::ids(), LibraryHeader::nuclide_set(), NuclideSet::num_in_sublib(), Library::set_decay_data(), and SUBLIB_1LT.
Referenced by LibraryBuilder::create_decay_library(), and populateLibraryAbundance().
 {
     Require( lib != nullptr );
     const NuclideSet& ns = lib->definition().nuclide_set();
     const Vec_Int& ids = ns.ids();
     Vec_Flt abundance( ids.size(), 0.0 );
     if( ns.has_sublibs() && ns.has_sublib( SUBLIB_1LT ) )
     {
         abundance.resize( ns.num_in_sublib( SUBLIB_1LT ) );
     }
     // get decay data
     DecayData dd = lib->decay_data();
     dd.abund_of_lite_nuclides.resize( abundance.size(), 0.0 );
     for( size_t j = 0; j < abundance.size(); ++j )
     {
         int izzzaaa = ids[j] % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         abundance[j] = 100 * nr.abundance_num( izzzaaa );
         jDebugLine( "abund[izzzaaa=" << izzzaaa << "] "
                                      << dd.abund_of_lite_nuclides[j]
                                      << " --> "
                                      << abundance[j] );
     }
     // replace abundance on decay data
     dd.abund_of_lite_nuclides = abundance;
     lib->set_decay_data( dd );
     jDebugTaggedLine( "leaving populateLibraryAbundance_NuclideResource" );
 }
void populateLibraryMass_NuclideResource (Library * lib, const NuclideResource & nr)
populate a library with mass from a nuclide resource
populate a library with masses from a nuclide resource
References Library::decay_data(), Library::definition(), NuclideSet::izzzaaa_at(), NuclideResource::mass(), LibraryHeader::nuclide_set(), Library::set_decay_data(), and NuclideSet::total_nuclides().
Referenced by LibraryBuilder::create_decay_library(), and populateLibraryMass().
 {
     Require( lib != nullptr );
     const NuclideSet& ns = lib->definition().nuclide_set();
     Vec_Flt masses( ns.total_nuclides(), 0.0 );
     // get decay data
     DecayData dd = lib->decay_data();
     // extract masses
     for( size_t j = 0; j < masses.size(); ++j )
     {
         int id = ns.izzzaaa_at( j );
         masses[j] = nr.mass( id );
         jDebugLine( "mass[izzzaaa=" << id << "] " << ( id % 1000 ) << " --> "
                                     << masses[j] );
         Check( masses[j] > 0.0 );
     }
     // replace mass on decay data
     dd.masses = masses;
     lib->set_decay_data( dd );
     jDebugTaggedLine( "leaving populateLibraryMass_NuclideResource" );
 }
void populateLibraryDecayEnergy_DecayResource (Library * lib, const DecayResource & dr)
populate decay energy
References Library::decay_data(), Library::definition(), DecayResource::get_const_parent_map(), NuclideSet::ids(), LibraryHeader::nuclide_set(), DecayData::q_fractions_from_photons, DecayData::recoverable_energy_values, and Library::set_decay_data().
Referenced by LibraryBuilder::create_decay_library().
 {
     Require( lib != nullptr );
     const Vec_Int& ids = lib->definition().nuclide_set().ids();
     Vec_Flt recoverable_energy_values( ids.size(), 0.0 );
     Vec_Flt q_fractions_from_photons( ids.size(), 0.0 );
     for( size_t j = 0; j < ids.size(); ++j )
     {
         int izzzaaa = ids[j] % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         const auto& pmap = dr.get_const_parent_map();
         auto it = pmap.find( izzzaaa );
         if( it != pmap.end() )
         {
             recoverable_energy_values[j] =
                 it->second.get_recoverable_energy_value();
             q_fractions_from_photons[j] =
                 it->second.get_q_fraction_from_photons();
         }
     }
     // replace energy on decay data
     DecayData dd = lib->decay_data();
     dd.recoverable_energy_values = recoverable_energy_values;
     dd.q_fractions_from_photons = q_fractions_from_photons;
     lib->set_decay_data( dd );
     jDebugTaggedLine( "populateLibraryAbundance_NuclideResource" );
 }
void populateCurrentTimes (int * year, int * month, int * day)
Referenced by LibraryBuilder::create_library().
 {
     Require( year != nullptr );
     Require( month != nullptr );
     Require( day != nullptr );
     auto t = std::time( 0 );  // get time now
     auto now = localtime( &t );
     *year = now->tm_year + 1900;
     *month = now->tm_mon + 1;
     *day = now->tm_mday;
 }
void populateLibraryHeader_YieldResource (LibraryHeader * lh, const Vec_Int & sizzzaaa_list, const YieldResource & yr, Vec_Int * fissionable_ids)
References YieldResource::fissionable(), NuclideSet::ids_size(), NuclideSet::izzzaaa_at(), NuclideSet::s_at(), NuclideSet::set_ids(), LibraryHeader::set_nuclide_set(), SUBLIB_2AC, and NuclideSet::zzzaaai_at().
Referenced by main().
 {
     Require( lh != nullptr );
     // nuclides
     NuclideSet nuc_set;
     nuc_set.set_ids( sizzzaaa_list );
     // set on header
     lh->set_nuclide_set( nuc_set );
     std::set<int> fiso;
     for( size_t j = 0; j < nuc_set.ids_size(); ++j )
     {
         int s = nuc_set.s_at( j );
         if( s == SUBLIB_2AC || s == 0 )
         {
             const YieldParent* yp = yr.fissionable( nuc_set.izzzaaa_at( j ) );
             if( yp != nullptr )
             {
                 fiso.insert( nuc_set.zzzaaai_at( j ) );
             }
         }
     }
     fissionable_ids->clear();
     fissionable_ids->assign( fiso.begin(), fiso.end() );
 }
void populateFissionables (Vec_Int * fissionable_ids, const Vec_Int & sizzzaaa_list, const Vec_Int & transition_ids, const Vec_Int & parent_positions)
References NuclideSet::convert_sizzzaaa_to_zzzaaai().
Referenced by LibraryBuilder::create_library().
 {
     Require( fissionable_ids != nullptr );
     Vec_Int ivec = sizzzaaa_list;
     NuclideSet::convert_sizzzaaa_to_zzzaaai( &ivec );
     std::set<int> fiso;
     for( size_t i = 0; i < transition_ids.size(); ++i )
     {
         int tid = transition_ids[i];
         if( tid == 18 )
         {
             int pos = parent_positions[i];  // starts at 1
             Check( pos > 0 && pos <= ivec.size() );
             int id = ivec[pos - 1];
             fiso.insert( id );
         }
     }
     fissionable_ids->clear();
     fissionable_ids->assign( fiso.begin(), fiso.end() );
 }
void populateMass_ids (std::vector< float > * masses, const std::vector< int > & sizzzaaa_list)
grabs the masses to use for each nuclide (mass number, A)
Referenced by populateLibraryMass().
 {
     Require( masses != nullptr );
     masses->resize( sizzzaaa_list.size() );
     for( size_t i = 0; i < sizzzaaa_list.size(); i++ )
     {
         ( *masses )[i] = sizzzaaa_list[i] % ScaleData::Utils::PIZZZAAA_Z_OFFSET;
     }
 }
std::map<int, CrossSection1d*> Origen::collect_direct_yields (int izzzaaa, LibraryNuclide * ampx_nuclide, const DirectYields_t & direct_yields)
Referenced by populateReactionResource_AmpxLibrary(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     std::map<int, CrossSection1d*> yield_map;
     // loop through now and collect cross sections
     int num_1dxs = ampx_nuclide->getNumNeutron1dData();
     for( int k = 0; k < num_1dxs; k++ )
     {
         CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
         int mt = xs->getMt();
         jDebugTaggedLine( "collect_direct_yields: mt=" << mt );
         // check for direct yields (e.g. nubar=452)
         auto itd = direct_yields.find( mt );
         if( itd != direct_yields.end() )
         {
             // evaluate target_mt (e.g. fission=18)
             int target_mt = itd->second.first;
             yield_map[target_mt] = xs;
         }
     }
     return yield_map;
 }
void populateReactionResource_AmpxLibrary (ReactionResource * rr, const AmpxLibrary & ampx)
References ReactionResource::allowed_mts(), collect_direct_yields(), ReactionResource::direct_yields(), ReactionResource::map_xs(), ReactionResource::max_isomeric_state(), populateEnergyBounds_AmpxLibrary(), populateFlux_AmpxLibrary(), ReactionResource::set_disallowed_mts(), ReactionResource::set_library_bounds(), ReactionResource::set_library_flux(), YIELD_DISTRIBUTED, YIELD_ISOMERIC, YIELD_SIMPLE, and YIELD_UNKNOWN.
Referenced by ReactionResourceIO_ampx::load().
 {
     // clear the internal database to ensure we don't have
     // issues with ghosts (because we don't store any pointers, this
     // should clear all the memory as well)
     rr->clear();
     // get energy bounds & flux on library and save copy (required)
     Vec_Flt bounds, flux;
     populateEnergyBounds_AmpxLibrary( &bounds, ampx );
     populateFlux_AmpxLibrary( &flux, ampx );
     rr->set_library_bounds( bounds );
     rr->set_library_flux( flux );
     // multi-group data size
     int mg_size = bounds.size() - 1;
     // iteration variables
     int izzzaaa;
     int mt;
     int final_isomeric_state;
     int initial_isomeric_state;
     bool partial;
     // iterate through AMPX nuclides
     int num_ampx_nuclides = ampx.getNumberNuclides();
     for( int j = 0; j < num_ampx_nuclides; j++ )
     {
         LibraryNuclide* ampx_nuclide = ampx.getNuclideAt( j );
         // this type of AMPX library should have mixture ids=0
         Check( ampx_nuclide->getMixture() == 0 );
         izzzaaa = ampx_nuclide->getId();
         int s, i, z, a;
         ScaleData::Utils::split_pizzzaaa( izzzaaa, s, i, z, a );
         // don't allow stuff with prefixes (stainless steel)
         Check( s == 0 );
         // filter isomeric states we can't handle
         if( i > rr->max_isomeric_state() )
         {
             jDebugTaggedLine( "import: disallowing nuclide="
                               << izzzaaa
                               << " because isomeric_state="
                               << i
                               << " greater than max allowed of "
                               << rr->max_isomeric_state() );
             continue;
         }
         // create a new database entry
         ReactionResource::Nuclide& a_nd = ( *rr )[izzzaaa];
         // first iterate through once and collect any direct yields (nubar=452)
         const auto& direct_yields = rr->direct_yields();
         auto yield_map =
             collect_direct_yields( izzzaaa, ampx_nuclide, direct_yields );
         // iterate through cross sections
         int num_1dxs = ampx_nuclide->getNumNeutron1dData();
         for( int k = 0; k < num_1dxs; k++ )
         {
             CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
             mt = xs->getMt();
             // deconstructs and modifies MT in place
             ScaleData::Utils::transform_mt(
                 mt, partial, final_isomeric_state, initial_isomeric_state );
             // filter MTs user doesn't want
             const auto& allowed_mts = rr->allowed_mts();
             auto ita = allowed_mts.find( mt );
             if( ita == allowed_mts.end() )
             {
                 rr->set_disallowed_mts( Vec_Int( {mt} ), true );
                 jDebugTaggedLine(
                     "import: establishing on-fly rule to disallow izzzaaa="
                     << izzzaaa
                     << " mt="
                     << mt );
                 continue;
             }
             else if( !ita->second )
             {
                 jDebugTaggedLine(
                     "import: disallowing izzzaaa=" << izzzaaa << " mt=" << mt
                                                    << " by established rule" );
                 continue;
             }
             // filter isomeric states we can't handle for reaction
             if( final_isomeric_state > rr->max_isomeric_state() )
             {
                 jDebugTaggedLine( "import: disallowing final_isomeric_state="
                                   << final_isomeric_state
                                   << " for mt="
                                   << mt
                                   << " because greater than max allowed"
                                      " of "
                                   << rr->max_isomeric_state() );
                 continue;
             }
             // if we get here, this data will be imported
             jDebugTaggedLine(
                 "import: importing izzzaaa=" << izzzaaa << " mt=" << mt
                                              << " initial_isomeric_state="
                                              << initial_isomeric_state
                                              << " final_isomeric_state="
                                              << final_isomeric_state );
             // partial cross sections should satisfy
             Check( partial ? i == initial_isomeric_state : true );
             // create a new xs data entry
             ReactionResource::Nuclide::Xs& a_xd = a_nd[mt];
             // save partial/isomeric cross section
             // note that the total is not given if partials are so it's
             // important that we don't normalize in order to sum to
             // get the total channel cross section (totxs)
             if( partial )
             {
                 // remember the type of this data
                 a_xd.yield_type = YIELD_ISOMERIC;
                 jDebugTaggedLine( "import: nuclide has a partial xs" );
                 // resize to fit this data
                 a_xd.pyield.resize( 1 + final_isomeric_state );
                 Vec_Flt& mxs = a_xd.pyield[final_isomeric_state];
                 // store partial yields
                 mxs.resize( mg_size );
                 for( int g = 0; g < mg_size; ++g )
                 {
                     mxs[g] = xs->getValues()[g];
                     // would like to not have to have this check!
                     if( mxs[g] < 0.0 )
                     {
                         jDebugBlock(
                             jDebugTaggedWarning( "WARNING: nuclide="
                                                  << izzzaaa
                                                  << " has negative mxs["
                                                  << g
                                                  << "]="
                                                  << mxs[g]
                                                  << " for final_isomeric_state="
                                                  << final_isomeric_state ); );
                         mxs[g] = 0.0;
                     }
                     Check( mxs[g] >= 0.0 );
                 }
                 rr->map_xs( &mxs );  // map to library group
                 continue;
             }
             // must be a channel total
             jDebugTaggedLine(
                 "import: fallback to treating as total channel xs" );
             // Only overwrite type if unknown to allow for a DISTRIBUTED
             // yield which also uses totxs, e.g. fission
             Check( a_xd.yield_type == YIELD_UNKNOWN );
             if( mt == 18 )
             {
                 a_xd.yield_type = YIELD_DISTRIBUTED;
                 // Add a nubar because we always want to have a yield
                 // of neutrons if we have fission
                 bool using_approx_nubar = false;
                 if( yield_map.count( 18 ) == 0 )
                 {
                     using_approx_nubar = true;
                     // Use Journal of Nuclear and Radiochemical Sciences, Vol.
                     // 9, No.1, pp. 19-25, 2008
                     float nubar = 0.27318 * z - 22.7734;
                     if( nubar < 0 ) nubar = 0;
                     auto nu = new CrossSection1d();
                     nu->setSize( mg_size );
                     for( int g = 0; g < mg_size; ++g )
                         nu->getValues()[g] = nubar;
                     yield_map[18] = nu;
                 }
                 // Associate nu data (fission will be done below as part of
                 // totxs.)
                 auto& a_xdd = a_nd[18];
                 auto& direct_yield = a_xdd.dyield[1];  // 1=NEUTRON
                 direct_yield.resize( mg_size );
                 auto nu = yield_map[18];
                 Check( nu != nullptr );
                 for( int g = 0; g < mg_size; ++g )
                 {
                     direct_yield[g] = nu->getValues()[g] * xs->getValues()[g];
                 }
                 if( using_approx_nubar ) delete yield_map[18];  // created above
                 rr->map_xs( &direct_yield );  // map to library group
             }
             else
             {
                 a_xd.yield_type = YIELD_SIMPLE;
             }
             // store channel total xs (as opposed to partial)
             Vec_Flt& totxs = a_xd.totxs;
             totxs.resize( mg_size );
             for( int g = 0; g < mg_size; ++g )
             {
                 totxs[g] = xs->getValues()[g];
                 // would like to not have to have this check!
                 if( totxs[g] < 0.0 )
                 {
                     jDebugBlock( jDebugTaggedWarning( "WARNING: nuclide="
                                                       << izzzaaa
                                                       << " has negative totxs["
                                                       << g
                                                       << "]="
                                                       << totxs[g] ); );
                     totxs[g] = 0.0;
                 }
                 Check( totxs[g] >= 0.0 );
             }
             rr->map_xs( &totxs );  // map to library group
         }
     }
 }
void populateEnergyBounds_AmpxLibrary (Vec_Flt * bounds, const AmpxLibrary & ampx)
Referenced by populateReactionResource_AmpxLibrary().
 {
     Require( bounds != nullptr );
     int bounds_size = ampx.getNeutronEnergyBounds()->getBoundsSize();
     float* eb = ampx.getNeutronEnergyBounds()->getBounds();
     bounds->resize( bounds_size );
     for( int g = 0; g < bounds_size; ++g )
     {
         ( *bounds )[g] = eb[g];
     }
 }
void populateVec_CrossSection1d (Vec_Flt * vec, const CrossSection1d & xs1d)
Referenced by populateFlux_AmpxLibrary(), and TransitionSystemAdapter_AmpxN::update().
 {
     Require( vec != nullptr );
     vec->resize( xs1d.getSize() );
     for( size_t g = 0; g < vec->size(); ++g )
     {
         ( *vec )[g] = xs1d.getValues()[g];
     }
 }
void populateFlux_AmpxLibrary (Vec_Flt * flux, const AmpxLibrary & ampx, int mix_id, int flux_nuclide_id, int flux_mt)
References populateVec_CrossSection1d().
Referenced by populateReactionResource_AmpxLibrary(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     Require( flux != nullptr );
     // loop to find a flux
     CrossSection1d* flux_ptr = nullptr;
     int num_ampx_nuclides = ampx.getNumberNuclides();
     for( int j = 0; j < num_ampx_nuclides; j++ )
     {
         LibraryNuclide* ampx_nuclide = ampx.getNuclideAt( j );
         if( mix_id > -1 && ampx_nuclide->getMixture() != mix_id ) continue;
         if( flux_nuclide_id > -1 && ampx_nuclide->getId() != flux_nuclide_id )
             continue;
         int num_1dxs = ampx_nuclide->getNumNeutron1dData();
         for( int k = 0; k < num_1dxs; k++ )
         {
             CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
             int mt = xs->getMt();
             if( mt != flux_mt ) continue;
             flux_ptr = xs;
             break;
         }
         break;
     }
     populateVec_CrossSection1d( flux, *flux_ptr );
 }
void populateLibraryMass (Library * lib, const ScaleUtils::IO::DB & opts)
References Library::decay_data(), NuclideResource::default_resource(), Library::definition(), NuclideSet::ids(), DecayData::masses, LibraryHeader::nuclide_set(), populateLibraryMass_NuclideResource(), populateMass_ids(), and Library::set_decay_data().
Referenced by c_Origen_populateLibraryMass(), LibraryIO_s62b::read(), LibraryIO_s61::read(), and LibraryIO_bof::read().
 {
     Require( lib != nullptr );
     bool legacyMass = opts.get<bool>( "legacyMass", false );
     bool force_legacyMass =
         std::getenv( "ORIGEN_IO_FORCE_legacyMass" ) != nullptr;
     jDebugTaggedLine( "force_legacyMass=" << force_legacyMass << " legacyMass="
                                           << legacyMass );
     bool updateMass = lib->decay_data().masses.empty() ||
                       opts.get<bool>( "updateMass", false );
     bool force_updateMass =
         std::getenv( "ORIGEN_IO_FORCE_updateMass" ) != nullptr;
     jDebugTaggedLine( "force_updateMass=" << force_updateMass << " updateMass="
                                           << updateMass );
     if( force_legacyMass || legacyMass )
     {
         jDebugTaggedLine( "    updating using legacy mass..." );
         DecayData dd = lib->decay_data();
         populateMass_ids( &dd.masses, lib->definition().nuclide_set().ids() );
         lib->set_decay_data( dd );
     }
     else if( force_updateMass || updateMass )
     {
         jDebugTaggedLine( "    updating with actual mass..." );
         SCP_NuclideResource nr =
             NuclideResource::default_resource();  // singleton
         populateLibraryMass_NuclideResource( lib, *nr );
     }
     else
     {
         jDebugTaggedLine( "  not updating mass..." );
     }
 }
void populateObiwan_dataType (ScaleUtils::IO::DB * base, const std::string & type)
Referenced by baseOptions(), and Obiwan_view::populate().
 {
     Require( base != nullptr );
     std::string dataType;
     if( type == "Origen::Library" || type == "lib" || type == "ft33" ||
         type == "f33" )
     {
         dataType = "Origen::Library";
     }
     else if( type == "Origen::StateSet" || type == "conc" || type == "ft71" ||
              type == "f71" )
     {
         dataType = "Origen::StateSet";
     }
     else if( type == "yld" || type == "Origen::YieldResource" )
     {
         dataType = "Origen::YieldResource";
     }
     else if( type == "dec" || type == "Origen::DecayResource" )
     {
         dataType = "Origen::DecayResource";
     }
     else if( type != "" )
     {
         base->appendError(
             "Values for type are 'f33', 'f71', 'yld', or 'dec' \n"
             "  f33 - read as Origen::Library \n"
             "  f71 - read as Origen::StateSet \n"
             "  dec - read as Origen::DecayResource \n"
             "  yld - read as Origen::YieldResource \n" );
     }
     base->set( "dataType", dataType );
 }
void Origen::populateXs_CrossSection1d (Vec_Flt * xs, const CrossSection1d & xs1d)
void printReactionTransitions (const LibraryHeader & lh, const TransitionStructure & tm, bool output_zeros, const std::string & idform, std::ostream & stream)
prints reaction transitions on a library
References printTable(), and tabulateReactionTransitions().
Referenced by view().
 {
     Table2D table;
     tabulateReactionTransitions( lh, tm, output_zeros, idform, &table );
     printTable( false, &table, stream );
 }
void printReactionTransitions (const Library & lib, bool output_zeros, const std::string & idform, std::ostream & stream)
prints reaction transitions on a library
References Library::definition(), and Library::transition_structure().
 {
     printReactionTransitions( lib.definition(),
                               lib.transition_structure(),
                               output_zeros,
                               idform,
                               stream );
 }
void printDecayTable (const DecayResource & dr, std::ostream & stream)
prints all decay info on the library
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
References DecayChannel::get_branch_ratio(), DecayParent::get_const_channel_map(), DecayResource::get_const_parent_map(), DecayChannel::get_const_yield_map(), DecayParent::get_decay_constant(), DecayParent::get_q_fraction_from_photons(), and DecayParent::get_recoverable_energy_value().
Referenced by TEST(), and view().
 {
     std::map<int, int> sort_map;
     for( std::map<int, DecayParent>::const_iterator it =
              dr.get_const_parent_map().begin();
          it != dr.get_const_parent_map().end();
          ++it )
     {
         int zzzaaai = ScaleData::Utils::pizzzaaa_to_zzzaaai( it->first );
         sort_map[zzzaaai] = it->first;
     }
     int count = -1;
     stream << "---------------\n"
            << "    ind: index\n"
            << "izzzaaa: 7-digit id composed of \n"
            << "              i: 1-digit isomeric (metastable) state\n"
            << "            zzz: 3-digit atomic number\n"
            << "            aaa: 3-digit mass number\n"
            << " symbol: element-aaa(m) where m is first metastable state\n"
            << "     dk: decay constant in 1/s\n"
            << "      Q: recoverable energy in MeV\n"
            << " fQphot: fraction of energy in photons\n"
            << "   mode: decay mode and yield pairs in the form\n"
            << "         decay_mode1(isomeric_states1) yield1 \n"
            << "         decay_mode2(isomeric_states2) yield2 \n"
            << "         ...\n"
            << "---------------\n"
            << std::endl;
     stream << " ind"
            << " "
            << " izzzaaa"
            << " "
            << "  symbol"
            << " "
            << "  dk(1/s)"
            << " "
            << "   Q(MeV)"
            << " "
            << "  fQphot"
            << " " <<
         //                "   RCGair" << " "<<
         //                " RCGwater" << " "<<
         " mode(isomeric) yield" << std::endl;
     for( std::map<int, int>::const_iterator it = sort_map.begin();
          it != sort_map.end();
          ++it )
     {
         count++;
         // ids
         int zzzaaai = it->first;
         int izzzaaa = it->second;
         // parent_map
         const std::map<int, DecayParent> parent_map = dr.get_const_parent_map();
         const DecayParent parent = parent_map.find( izzzaaa )->second;
         stream << std::setw( 4 ) << count << " " << std::setw( 8 ) << izzzaaa
                << " " << std::setw( 8 )
                << ScaleData::Utils::zzzaaai_to_symbol( zzzaaai ) << " "
                << std::setw( 8 ) << std::scientific << std::setprecision( 3 )
                << parent.get_decay_constant() << " " << std::setw( 8 )
                << std::scientific << std::setprecision( 3 )
                << parent.get_recoverable_energy_value() << " " << std::setw( 8 )
                << std::fixed << std::setprecision( 3 )
                << parent.get_q_fraction_from_photons() << " ";
         //                        std::setw(8) << std::scientific <<
         //                        std::setprecision(3) << parent.rcg_for_air <<
         //                        " " <<
         //                        std::setw(8) << std::scientific <<
         //                        std::setprecision(3) << parent.rcg_for_water
         //                        << " ";
         stream << "  ";
         for( std::map<int, DecayChannel>::const_iterator it2 =
                  parent.get_const_channel_map().begin();
              it2 != parent.get_const_channel_map().end();
              ++it2 )
         {
             const DecayChannel& channel = it2->second;
             for( std::map<int, double>::const_iterator it3 =
                      channel.get_const_yield_map().begin();
                  it3 != channel.get_const_yield_map().end();
                  ++it3 )
             {
                 stream << ScaleData::Utils::decay_mode_to_name( it2->first )
                        << "[m" << std::fixed << std::setw( 1 ) << it3->first
                        << "] " << std::scientific << std::setprecision( 3 )
                        << channel.get_branch_ratio() * it3->second << " ";
             }
             stream << " ";
         }
         stream << std::endl;
     }
 }
void printInterpolatedYields (const YieldResource & yr, const int id, const double energy, const int interp, std::ostream & stream)
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
References YieldParent::data_at(), YieldParent::energy_at(), YieldResource::fissionable(), YieldParent::get_fp_ids(), YieldParent::get_interp_yields(), YieldResource::has_fissionable(), YieldParent::num_energies(), and YieldData::yield_at().
Referenced by TEST(), and TEST_F().
 {
     if( !yr.has_fissionable( id ) )
     {
         stream << "no fissionable id=" << id << std::endl;
     }
     else
     {
         const YieldParent* yp = yr.fissionable( id );
         Check( yp != nullptr );
         Vec_Int fp_ids;
         yp->get_fp_ids( &fp_ids );
         Vec_Dbl yields;
         yp->get_interp_yields( &yields, energy, interp );
         stream << std::setw( 6 ) << "j" << std::setw( 9 ) << "id";
         for( int i = 0; i < yp->num_energies(); i++ )
         {
             stream << std::setw( 14 ) << yp->energy_at( i );
         }
         stream << std::setw( 14 ) << "interp(" << energy << ")" << std::endl;
         for( size_t j = 0; j < yields.size(); j++ )
         {
             stream << std::setw( 6 ) << j << std::setw( 9 ) << fp_ids[j];
             for( int i = 0; i < yp->num_energies(); i++ )
             {
                 stream << std::setw( 14 ) << yp->data_at( i ).yield_at( j );
             }
             stream << std::setw( 14 ) << yields[j] << std::endl;
         }
     }
     return;
 }
void printYields (const YieldResource & yr, std::ostream & os)
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
References YieldParent::data_at(), YieldData::energy(), YieldResource::fissionable_at(), YieldResource::get_fissionable_ids(), YieldParent::get_fp_ids(), YieldParent::num_energies(), YieldResource::num_fissionables(), and YieldData::yield_at().
Referenced by main(), TEST(), TEST_F(), and view().
 {
     Vec_Int ids;
     yr.get_fissionable_ids( &ids );
     for( int k = 0; k < yr.num_fissionables(); ++k )
     {
         int id = ids[k];
         const YieldParent& yp = yr.fissionable_at( k );
         Vec_Int fp_ids;
         yp.get_fp_ids( &fp_ids );
         for( int i = 0; i < yp.num_energies(); i++ )
         {
             const YieldData& ys = yp.data_at( i );
             for( size_t j = 0; j < fp_ids.size(); ++j )
             {
                 int fp_iza = fp_ids[j];
                 // new output dump
                 os << nprintf( "%8d %.5e %8d %.5e\n",
                                id,
                                ys.energy(),
                                fp_iza,
                                ys.yield_at( j ) );
             }
         }
     }
 }
void printYieldEnergies (const YieldResource & yr, std::ostream & os)
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
References YieldParent::data_at(), YieldData::energy(), YieldResource::fissionable_at(), YieldResource::get_fissionable_ids(), YieldParent::num_energies(), and YieldResource::num_fissionables().
Referenced by TEST(), and TEST_F().
 {
     Vec_Int ids;
     yr.get_fissionable_ids( &ids );
     for( int k = 0; k < yr.num_fissionables(); ++k )
     {
         int id = ids[k];
         const YieldParent& yp = yr.fissionable_at( k );
         os << std::setw( 9 ) << id << " ";
         for( int i = 0; i < yp.num_energies(); i++ )
         {
             const YieldData& ys = yp.data_at( i );
             os << std::setprecision( 6 ) << std::scientific << ys.energy()
                << " ";
         }
         os << std::endl;
     }
 }
void printIdTags_json (const Library & lib, std::ostream & os)
References TagManager::getIdTag(), TagManager::listIdTags(), and Library::tag_manager().
Referenced by printTags_json().
 {
     os << "   idtags: {";
     const TagManager& tm = lib.tag_manager();
     for( size_t i = 0; i != tm.listIdTags().size(); ++i )
     {
         os << "\n      " << tm.listIdTags()[i] << ": "
            << tm.getIdTag( tm.listIdTags()[i] );
         if( i < tm.listIdTags().size() - 1 ) os << ", ";
     }
     os << "   }\n";
 }
void printInterpTags_json (const Library & lib, std::ostream & os)
References TagManager::getInterpTag(), TagManager::listIdTags(), TagManager::listInterpTags(), and Library::tag_manager().
Referenced by printTags_json().
 {
     os << "   interptags: {";
     const TagManager& tm = lib.tag_manager();
     for( size_t i = 0; i != tm.listInterpTags().size(); ++i )
     {
         os << "\n      " << tm.listInterpTags()[i] << ": "
            << tm.getInterpTag( tm.listInterpTags()[i] );
         if( i < tm.listIdTags().size() - 1 ) os << ", ";
     }
     os << "   }\n";
 }
void printTags_json (const Library & lib, const std::string & file, std::ostream & os)
References printIdTags_json(), and printInterpTags_json().
Referenced by Obiwan_interp::execute(), Obiwan_tag::execute(), and view().
 {
     os << file << ": {" << std::endl;
     printIdTags_json( lib );
     printInterpTags_json( lib );
     os << "}\n";
 }
void Origen::printTable (bool transpose, Table2D * table, std::ostream & os)
Examples:
Core/fn/tests/tsttabulate.cpp.
Referenced by printBurnups(), printFissionXs(), printLossXs(), printNuclideInfo(), printReactionTransitions(), printTransitionCoeff(), and TEST_F().
 {
     if( transpose )
     {
         os << table->transposed().text( 12, 12 );
     }
     else
     {
         os << table->straight().text( 12, 12 );
     }
 }
void printNuclideInfo (const Library & lib, int sizzzaaa, bool transpose, const std::string & idform, int prec, std::ostream & os)
References printTable(), and tabulateNuclideInfo().
Referenced by view().
 {
     Table2D table;
     tabulateNuclideInfo( lib, sizzzaaa, idform, prec, &table );
     if( transpose ) table.setTitle( "burnup" );
     printTable( transpose, &table, os );
 }
void printBurnups (const Library & lib, bool transpose, int prec, std::ostream & os)
References printTable(), and tabulateBurnups().
Referenced by view().
 {
     Table2D table;
     tabulateBurnups( lib, prec, &table );
     if( transpose ) table.setTitle( "burnup" );
     printTable( transpose, &table, os );
 }
void printFissionXs (const Library & lib, int sizzzaaa, bool transpose, const std::string & idform, int prec, int pos, std::ostream & os)
References printTable(), and tabulateFissionXs().
Referenced by view().
 {
     Table2D table;
     tabulateFissionXs( lib, sizzzaaa, idform, prec, pos, &table );
     if( transpose ) table.setTitle( "burnup" );
     printTable( transpose, &table, os );
 }
void printLossXs (const Library & lib, int sizzzaaa, bool transpose, const std::string & idform, int prec, int pos, std::ostream & os)
References printTable(), and tabulateLossXs().
Referenced by view().
 {
     Table2D table;
     tabulateLossXs( lib, sizzzaaa, idform, prec, pos, "", false, &table );
     if( transpose ) table.setTitle( "burnup" );
     printTable( transpose, &table, os );
 }
void printTransitionCoeff (const Library & lib, int sizzzaaa, int tid, bool transpose, bool output_zeros, double flux, bool output_transition_ids, const std::string & idform, int prec, int pos, std::ostream & os)
References printTable(), and tabulateTransitionCoeff().
Referenced by view().
 {
     Table2D table;
     tabulateTransitionCoeff( lib,
                              sizzzaaa,
                              tid,
                              output_zeros,
                              flux,
                              output_transition_ids,
                              idform,
                              prec,
                              pos,
                              &table );
     if( transpose ) table.setTitle( "burnup" );
     printTable( transpose, &table, os );
 }
void Origen::printConcentrations_csv (const StateSet & f71, ConcentrationUnit concUnit, SP_Library library, const std::string & idform, std::ostream & os)
Examples:
Core/dc/tests/tstStateSet.cpp.
References convertConcUnitToPrettyString(), info(), NOT_GIVEN, printLine_csv(), Concentrations::scp_nuclide_set(), StateSet::scp_states_at(), Concentrations::set_decay_resource(), Concentrations::set_units(), StateSet::states_size(), stringifyNuclide(), Concentrations::total_nuclides(), Concentrations::vals(), Concentrations::volume(), and auxiliary_erf_m::x.
Referenced by main(), TEST(), and view().
 {
     Origen::SCP_State state;
     Origen::SCP_StateInfo info;
     Origen::SCP_Concentrations scp_concs;
     // collect concentrations info into a map
     typedef std::map<int, double> conc_t;
     std::map<std::string, conc_t> case_matrix;
     std::vector<int> cases, steps;
     std::vector<double> times, powers, fluxes, volumes;
     // get the native units (assume case0 and other cases are identical
     state = f71.scp_states_at( 0 );
     scp_concs = state->scp_concs();
     {
         Origen::ConcentrationUnit concUnit0 = scp_concs->units();
         SErrLine( 1,
                   "file_units=" << convertConcUnitToPrettyString( concUnit0 ) );
         if( concUnit == NOT_GIVEN )
         {
             SErrLine( 1,
                       "convert_units="
                           << convertConcUnitToPrettyString( concUnit0 ) );
         }
         else
         {
             SErrLine(
                 1,
                 "convert_units=" << convertConcUnitToPrettyString( concUnit ) );
         }
     }
     std::vector<int> user_to_master, master_to_user;
     SCP_DecayResource dr( nullptr );
     if( library != nullptr )
     {
         dr = SCP_DecayResource( new DecayResource( *library ) );
     }
     // construct the map
     size_t final_count = 0;
     for( int c = 0; c < f71.states_size(); c++ )
     {
         state = f71.scp_states_at( c );
         scp_concs = state->scp_concs();
         // skip if we don't have concentrations
         if( scp_concs->vals_size() == 0 ) continue;
         ++final_count;
         info = state->scp_definition();
         times.push_back( info->time() );
         powers.push_back( info->power() );
         fluxes.push_back( info->flux() );
         cases.push_back( info->case_number() );
         steps.push_back( info->step_number() );
         // need to own this one
         Concentrations concs = *scp_concs;
         volumes.push_back( concs.volume() );
         // set decay resource
         if( dr != nullptr ) concs.set_decay_resource( dr );
         // convert units
         if( concUnit != NOT_GIVEN ) concs.set_units( concUnit );
         const Vec_Dbl& vals = concs.vals();
         // assemble map
         conc_t conc_map;
         SCP_NuclideSet nuc_set = concs.scp_nuclide_set();
         for( size_t i = 0; i < concs.total_nuclides(); ++i )
         {
             std::string idstr =
                 stringifyNuclide( nuc_set->ids_at( i ), idform );
             auto it = case_matrix.find( idstr );
             if( it == case_matrix.end() )
             {
                 case_matrix[idstr][final_count - 1] = vals[i];
             }
             else
             {
                 it->second[final_count - 1] += vals[i];
             }
         }
     }
     // print out in csv form
     std::map<std::string, conc_t>::const_iterator it;
     os.setf( std::ios_base::uppercase | std::ios_base::scientific );
     printLine_csv( "case", cases, os );
     printLine_csv( "step", steps, os );
     printLine_csv( "time", times, os );
     printLine_csv( "power", powers, os );
     printLine_csv( "flux", fluxes, os );
     printLine_csv( "volume", volumes, os );
     for( it = case_matrix.begin(); it != case_matrix.end(); it++ )
     {
         os << std::setw( 14 ) << it->first;
         for( const auto& x : it->second )
         {
             os << "," << std::setprecision( 7 ) << std::setw( 14 ) << x.second;
         }
         os << std::endl;
     }
 }
std::string Origen::createContentString (const State & state)
References State::has_definition(), State::num_alpha_groups(), State::num_beta_groups(), State::num_gamma_groups(), State::num_neutron_groups(), and State::total_nuclides().
Referenced by printStateInfo().
 {
     std::string content;
     content += state.has_definition() ? "D" : "-";
     content += state.total_nuclides() > 0 ? "C" : "-";
     content += state.num_gamma_groups() > 0 ? "G" : "-";
     content += state.num_neutron_groups() > 0 ? "N" : "-";
     content += state.num_alpha_groups() > 0 ? "A" : "-";
     content += state.num_beta_groups() > 0 ? "B" : "-";
     return content;
 }
void printStateInfo (const StateSet & state_set, int start_position, std::ostream & os)
prints information describing the state_set
References createContentString(), info(), StateSet::scp_states_at(), and StateSet::states_size().
Referenced by c_Origen_printStateInfo(), and view().
 {
     // create the format statement
     std::string fmt;
     std::string pos_str;
     if( start_position < 0 )
     {
         // interpret as offset and format with +
         fmt = "%+6d";
         start_position = std::abs( start_position );
         pos_str = "+pos";
     }
     else
     {
         fmt = "%6d";
         pos_str = "pos";
     }
     fmt += " %12.5e %12.5e %12.5e %12.5e %12.5e %6d %6d %6d %6s\n";
     // header line
     os << nprintf( "%6s %12s %12s %12s %12s %12s %6s %6s %6s %6s\n",
                    pos_str.c_str(),
                    "time",
                    "power",
                    "flux",
                    "fluence",
                    "energy",
                    "libpos",
                    "case",
                    "step",
                    "DCGNAB" );
     // units
     os << nprintf( "%6s %12s %12s %12s %12s %12s %6s %6s %6s %6s\n",
                    "(-)",
                    "(s)",
                    "(MW)",
                    "(n/cm2-s)",
                    "(n/cm2)",
                    "(MWd)",
                    "(-)",
                    "(-)",
                    "(-)",
                    "(-)" );
     // table body
     for( int c = 0; c < state_set.states_size(); c++ )
     {
         auto state = state_set.scp_states_at( c );
         auto info = state->scp_definition();
         std::string content = createContentString( *state );
         os << nprintf( fmt.c_str(),
                        ( c + start_position ),
                        info->time(),
                        info->power(),
                        info->flux(),
                        info->fluence(),
                        info->energy(),
                        info->library_position(),
                        info->case_number(),
                        info->step_number(),
                        content.c_str() );
     }
     os << "    D - state definition present" << std::endl;
     os << "    C - concentrations present" << std::endl;
     os << "    G - gamma emission spectra present" << std::endl;
     os << "    N - neutron emission spectra present" << std::endl;
     os << "    A - alpha emission spectra present" << std::endl;
     os << "    B - beta emission spectra present" << std::endl;
     if( pos_str == "+pos" )
     {
         os << " NOTE: +pos indicates file was appended to and " << std::endl;
         os << "       positions shown are RELATIVE to the original."
            << std::endl;
     }
 }
void printTags_json (const StateSet & state_set, std::ostream & os)
prints information describing the state_set
References info(), StateSet::scp_states_at(), and StateSet::states_size().
 {
     Json::Value root( Json::objectValue );
     for( int c = 0; c < state_set.states_size(); c++ )
     {
         auto state = state_set.scp_states_at( c );
         auto info = state->scp_definition();
         auto tagman = info->scp_tag_manager();
         Json::Value node( Json::objectValue );
         node["tags"] = tagman->to_json();
         node["info"]["time"] = info->time();
         node["info"]["power"] = info->power();
         node["info"]["flux"] = info->flux();
         node["info"]["fluence"] = info->fluence();
         node["info"]["energy"] = info->energy();
         node["info"]["library_position"] = info->library_position();
         node["info"]["case_number"] = info->case_number();
         node["info"]["step_number"] = info->step_number();
         root[std::to_string( c + 1 )] = node;
     }
     os << root.toStyledString() << std::endl;
 }
void printNeutronProductionRatio (const Library & x, int pos, std::ostream & os)
References construct_neutron_prod_map().
Referenced by view().
 {
     auto xmap = construct_neutron_prod_map( x, pos );
     for( auto it : xmap ) os << it.first << ": " << it.second << std::endl;
 }
void printNeutronYields (const Library & x, int pos, std::ostream & os)
References construct_neutron_yields_map().
Referenced by view().
 {
     auto xmap = construct_neutron_yields_map( x, pos );
     for( auto it : xmap ) os << it.first << ": " << it.second << std::endl;
 }
void printTimingReport (std::ostream & os)
Examples:
Core/io/tests/tstGammaResourceIO.cpp, Core/io/tests/tstLibraryIO.cpp, Core/io/tests/tstStateSetIO.cpp, Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, Manager/mzd/tests/tstParallelDepletion.cpp, Solver/cram/tests/tstSolver_cram.cpp, and Solver/matrex/tests/tstSolver_matrex.cpp.
Referenced by LibraryIOTester::TearDown(), StateSetIOTester::TearDown(), TransitionSystemAdapterTesterJeff252::TearDown(), TEST(), and TEST_P().
 {
     const nemesis::Timing_Diagnostics::Map_Timers& timers =
         nemesis::Timing_Diagnostics::view_timers();
     if( !timers.empty() )
     {
         os << "             ---------------Detailed Timing "
               "Report---------------------"
            << std::endl;
         for( nemesis::Timing_Diagnostics::Map_Timers::const_iterator it =
                  timers.begin();
              it != timers.end();
              ++it )
         {
             os << std::setw( 60 ) << it->first << ": " << std::setprecision( 1 )
                << std::fixed << std::setw( 7 ) << ( it->second * 1000. ) << "ms"
                << std::endl;
         }
         os << "             "
               "----------------------------------------------------------"
            << std::endl;
     }
 }
void printTransitionSystemXs (const TransitionSystem & ts, std::ostream & os)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References auxiliary::nuclide(), TransitionSystem::nuclides(), and stringifyNuclide().
Referenced by TEST_F().
 {
     // header
     os << nprintf( "%12s %12s %4s %12s %11s  %s\n",
                    "nuclide",
                    "channel",
                    "mt",
                    "xs",
                    "branch",
                    "yield:nuclide" );
     // units
     os << nprintf( "%12s %12s %4s %12s %11s  %s\n",
                    "(-)",
                    "(-)",
                    "(-)",
                    "(barns)",
                    "(%)",
                    "(%:-)" );
     for( auto nuclide : ts.nuclides() )
     {
         int id = nuclide->id();
         double total_loss_xs = nuclide->loss_xs();
         std::stringstream ss;
         ss << nprintf( "%12s ", stringifyNuclide( id, "$Z-$ee-$A$m" ).c_str() );
         for( auto loss : nuclide->losses() )
         {
             auto ct = loss->channel_type();
             if( ct->is_decay() ) continue;
             int mt = ct->id();
             double xs = loss->xs();
             double branch = xs / total_loss_xs;
             os << ss.str()
                << nprintf( "%12s %4d %12.5g %11.4g  ",
                            ScaleData::Utils::mt_to_reaction( mt ).c_str(),
                            mt,
                            xs,
                            100 * branch );
             for( auto transition : loss->transitions() )
             {
                 int prodid = transition->product()->id();
                 os << nprintf( "%.4g:%s ",
                                100 * transition->yield(),
                                stringifyNuclide( prodid, "$ee-$A$m" ).c_str() );
             }
             os << std::endl;
         }
     }
 }
void Origen::printConcentrations_csv (const StateSet & f71, ConcentrationUnit concUnit, std::shared_ptr< Library > library = nullptr, const std::string & idform = "$S$I$ZZZ$AAA", std::ostream & os = std::cout)
void printLine_csv (std::string id, const std::vector< T > & vals, std::ostream & os = std::cout)
Referenced by printConcentrations_csv().
 {
     os << std::setw( 14 ) << id;
     for( size_t c = 0; c < vals.size(); c++ )
     {
         os << "," << std::setprecision( 7 ) << std::setw( 14 ) << vals[c];
     }
     os << std::endl;
 }
void printList (const char * name, T * list, std::ostream & os = std::cout)
 {
     if( list )
     {
         for( size_t i = 0; i < list->size(); ++i )
         {
             os << name << "[" << i << "]=" << list->at( i ) << std::endl;
         }
     }
     else
     {
         os << name << "=nullptr" << std::endl;
     }
 }
void Origen::printTable (bool transpose, ScaleUtils::IO::Table2D * table, std::ostream & os = std::cout)
void Origen::tabulateNuclideLabel (const Vec_Int & ids, int sizzzaaa, const std::string & idform, const std::string & units_row, Table2D * table)
References NuclideGroupFilter::filter(), and stringifyNuclide().
Referenced by tabulateFissionXs(), tabulateInitialNuclideColumns(), tabulateLossXs(), and tabulateNuclideInfo().
 {
     Require( table != nullptr );
     NuclideGroupFilter ngf( sizzzaaa );
     if( units_row != "" ) table->addY( units_row );
     // add nuclide rows (these ids are sizzzaaa format)
     for( int id : ids )
     {
         if( ngf.filter( id ) ) continue;
         std::stringstream ss;
         ss << stringifyNuclide( id, idform );
         table->addY( ss.str() );
     }
 }
void tabulateInitialNuclideColumns (const Vec_Int & ids, ScaleUtils::IO::Table2D * table)
References tabulateNuclideLabel().
Referenced by tabulateMaterialFission(), tabulateMaterialIsotopics(), and tabulateMaterialLoss().
 {
     table->clear();
     // nuclide column
     table->setTitle( "nuclide:sublib" );
     tabulateNuclideLabel( ids, 0, "$Z-$ee-$A$m:$TY", "(-)", table );
     // index column
     table->addX( "index" );
     std::string out_of( "/" + std::to_string( ids.size() ) );
     table->addRow();
     table->addCell( "(-)" );  // units
     for( size_t i = 0; i < ids.size(); ++i )
     {
         table->addRow();
         table->addCell( std::to_string( i + 1 ) + out_of );
     }
 }
std::vector<const TransitionCoeff*> Origen::getTransitionCoeffList (const Library & lib)
References Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by tabulateLossXs(), and tabulateTransitionCoeff().
 {
     std::vector<const TransitionCoeff*> tcoeff_list(
         lib.transition_coeff_size() );
     for( size_t i = 0; i < tcoeff_list.size(); ++i )
     {
         tcoeff_list[i] = &( lib.transition_coeff_at( i ) );
     }
     return tcoeff_list;
 }
void Origen::getPosRange (size_t max_size, int pos, size_t & first_index, size_t & last_index)
Referenced by tabulateFissionXs(), tabulateLossXs(), and tabulateTransitionCoeff().
 {
     first_index = pos - 1;
     last_index = pos;
     if( pos <= 0 )
     {
         first_index = 0;
         last_index = max_size;
     }
 }
void Origen::tabulateNuclideInfo (const Library & lib, int sizzzaaa, const std::string & idform, int prec, Table2D * table)
References DecayData::abund_of_lite_nuclides, kernel_matrex::decay(), DecayData::decay_constants, Library::decay_data(), Library::definition(), NuclideGroupFilter::filter(), NuclideSet::ids(), DecayData::masses, LibraryHeader::nuclide_set(), and tabulateNuclideLabel().
Referenced by printNuclideInfo().
 {
     Require( table != nullptr );
     // setup table
     table->setTitle( "nuclide" );
     // first column
     const Vec_Int& ids = lib.definition().nuclide_set().ids();
     tabulateNuclideLabel( ids, sizzzaaa, idform, "", table );
     NuclideGroupFilter ngf( sizzzaaa );
     // data columns
     table->addX( "mass [g/mol]" );
     table->addX( "abund [atom%]" );
     table->addX( "decay [1/s]" );
     for( size_t i = 0; i < ids.size(); ++i )
     {
         int id = ids[i];
         if( ngf.filter( id ) ) continue;
         table->addRow();
         const DecayData& decay_data = lib.decay_data();
         double mass = decay_data.masses.at( i );
         table->addCell_fixed( mass, prec );
         double abund = 0;
         if( i < decay_data.abund_of_lite_nuclides.size() )
             abund = decay_data.abund_of_lite_nuclides.at( i );
         table->addCell_fixed( abund, prec );
         double decay = decay_data.decay_constants.at( i );
         table->addCell_scientific( decay, prec );
     }
 }
void Origen::tabulateFissionXs (const Library & lib, int sizzzaaa, const std::string & idform, int prec, int pos, Table2D * table)
References TransitionCoeff::burnup(), Library::definition(), TransitionCoeff::fission_xs_at(), TransitionCoeff::fission_xs_index(), TransitionCoeff::fission_xs_size(), getPosRange(), NuclideSet::ids(), NuclideSet::ids_at(), NuclideSet::ids_size(), LibraryHeader::nuclide_set(), tabulateNuclideLabel(), Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by printFissionXs().
 {
     Require( table != nullptr );
     // setup table
     table->setTitle( "nuclide" );
     // first column of nuclide ids
     const NuclideSet& nucset = lib.definition().nuclide_set();
     tabulateNuclideLabel( nucset.ids(), sizzzaaa, idform, "", table );
     NuclideGroupFilter ngf( sizzzaaa );
     // determine positions
     size_t first_index, last_index;
     getPosRange( lib.transition_coeff_size(), pos, first_index, last_index );
     // burnup columns
     for( size_t i = first_index; i < last_index; ++i )
     {
         table->addX_scientific( lib.transition_coeff_at( i ).burnup(), prec );
     }
     // fission data columns
     for( size_t i = 0; i < nucset.ids_size(); ++i )
     {
         int id = nucset.ids_at( i );
         if( ngf.filter( id ) ) continue;
         table->addRow();
         for( size_t j = first_index; j < last_index; ++j )
         {
             double fission_xs = 0.0;
             const TransitionCoeff& tcoeff = lib.transition_coeff_at( j );
             size_t kf = tcoeff.fission_xs_index( i, nucset );
             if( kf < tcoeff.fission_xs_size() )
                 fission_xs = tcoeff.fission_xs_at( kf );
             if( pos < 0 )
             {
                 fission_xs /= lib.transition_coeff_at( abs( pos ) - 1 )
                                   .fission_xs_at( kf );
             }
             table->addCell_scientific( fission_xs, prec );
         }
     }
 }
void Origen::tabulateLossXs (const Library & lib, int sizzzaaa, const std::string & idform, int prec, int pos, const std::string & column_name, bool append_column, Table2D * table)
Examples:
Core/fn/tests/tsttabulate.cpp.
References Library::definition(), and getTransitionCoeffList().
Referenced by printLossXs(), and TEST().
 {
     tabulateLossXs( lib.definition(),
                     getTransitionCoeffList( lib ),
                     sizzzaaa,
                     idform,
                     prec,
                     pos,
                     column_name,
                     append_column,
                     table );
 }
void Origen::tabulateLossXs (const LibraryHeader & lh, const std::vector< const TransitionCoeff * > & tcoeff_list, int sizzzaaa, const std::string & idform, int prec, int pos, const std::string & column_name, bool append_column, Table2D * table)
References getPosRange(), NuclideSet::ids(), NuclideSet::ids_at(), NuclideSet::ids_size(), LibraryHeader::nuclide_set(), and tabulateNuclideLabel().
 {
     Require( table != nullptr );
     // setup table
     if( !append_column ) table->setTitle( "nuclide" );
     // first column of nuclide ids
     const NuclideSet& nucset = lh.nuclide_set();
     if( !append_column )
         tabulateNuclideLabel( nucset.ids(), sizzzaaa, idform, "", table );
     NuclideGroupFilter ngf( sizzzaaa );
     // determine positions
     size_t first_index, last_index;
     getPosRange( tcoeff_list.size(), pos, first_index, last_index );
     for( size_t i = first_index; i < last_index; ++i )
     {
         // arbitrary name
         if( column_name != "" )
         {
             table->addX( column_name );
         }
         // burnup columns
         else
         {
             table->addX_scientific( tcoeff_list[i]->burnup(), prec );
         }
     }
     // loss data columns
     for( size_t i = 0; i < nucset.ids_size(); ++i )
     {
         int id = nucset.ids_at( i );
         if( ngf.filter( id ) ) continue;
         // either add or select the proper row
         if( append_column )
         {
             table->selectRow( i );
         }
         else
         {
             table->addRow();
         }
         for( size_t j = first_index; j < last_index; ++j )
         {
             double loxs = tcoeff_list[j]->loss_xs().at( i );
             if( pos < 0 )
             {
                 loxs /= tcoeff_list[abs( pos ) - 1]->loss_xs_at( i );
             }
             table->addCell_scientific( loxs, prec );
         }
     }
 }
void Origen::tabulateReactionTransitions (const LibraryHeader & lh, const TransitionStructure & tm, bool output_zeros, const std::string & idform, Table2D * table)
References NuclideSet::i_at(), NuclideSet::ids_at(), NuclideSet::ids_size(), LibraryHeader::nuclide_set(), TransitionStructure::num_decay_parents(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), stringifyNuclide(), and TransitionStructure::transition_ids().
Referenced by printReactionTransitions().
 {
     Require( table != nullptr );
     // SIZZZAAA --> [mt1,mt2,mt3,....]
     std::map<int, std::set<int>> parent_to_reaction_map;
     // first column of nuclide ids
     const NuclideSet& nucset = lh.nuclide_set();
     // transition structure data columns
     const Vec_Int& num_parents = tm.num_parents();
     const Vec_Int& num_decay_parents = tm.num_decay_parents();
     int tind = -1;
     for( size_t i = 0; i < nucset.ids_size(); ++i )
     {
         int did = nucset.ids_at( i );
         if( output_zeros &&
             parent_to_reaction_map.find( did ) == parent_to_reaction_map.end() )
         {
             parent_to_reaction_map[did] = std::set<int>();
         }
         for( int count = 0; count < num_parents.at( i ); ++count )
         {
             ++tind;
             if( count < num_decay_parents.at( i ) )
                 continue;  // skip over decays
             int transition_id = tm.transition_ids().at( tind );
             int ppos = tm.parent_positions().at( tind );
             int pid = nucset.ids_at( ppos - 1 );
             transition_id *= 10;
             if( transition_id != 180 )
                 transition_id +=
                     nucset.i_at( i );  // combine mt & isomeric state
             parent_to_reaction_map[pid].insert( transition_id );
         }
     }
     table->setTitle( "nuclide" );
     table->addX( "reactions" );
     for( const auto& it : parent_to_reaction_map )
     {
         int pid = it.first;
         // add a new row
         table->addRow();
         table->addY( stringifyNuclide( pid, idform ) );
         std::stringstream ss;
         for( const auto& tid0 : it.second )
         {
             int tid = tid0 / 10;
             int m = tid0 % 10;
             std::string reaction = ScaleData::Utils::mt_to_reaction( tid );
             // only replace 3 metastable indices
             reaction = ScaleUtils::IO::findAndReplace( reaction, "(1)", "" );
             reaction = ScaleUtils::IO::findAndReplace( reaction, "(2)", "" );
             reaction = ScaleUtils::IO::findAndReplace( reaction, "(3)", "" );
             reaction =
                 ScaleUtils::IO::findAndReplace( reaction, "fission", "n,f" );
             if( !( reaction == "n,f" || m == 0 ) )
                 reaction += "[" + std::to_string( m ) + "]";
             ss << "(" << reaction << ") ";
         }
         table->addCell( ss.str() );
     }
 }
void Origen::tabulateTransitionCoeff (const LibraryHeader & lh, const TransitionStructure & tm, const std::vector< const TransitionCoeff * > & tcoeff_list, int sizzzaaa, int tid, bool output_zeros, double flux, bool output_transition_ids, const std::string & idform, int prec, int pos, Table2D * table)
References kernel_rksuite::f(), NuclideGroupFilter::filter(), getPosRange(), NuclideSet::ids_at(), NuclideSet::ids_size(), LibraryHeader::nuclide_set(), TransitionStructure::num_decay_parents(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), stringifyNuclide(), and TransitionStructure::transition_ids().
Referenced by printTransitionCoeff(), and tabulateTransitionCoeff().
 {
     Require( table != nullptr );
     for( const auto& tcoeff : tcoeff_list )
     {
         Check( tcoeff != nullptr );
     }
     // setup table
     if( output_transition_ids )
     {
         table->setTitle( "daughter<--[tid]--parent" );
     }
     else
     {
         table->setTitle( "daughter<----parent" );
     }
     // first column of nuclide ids
     const NuclideSet& nucset = lh.nuclide_set();
     NuclideGroupFilter ngf( sizzzaaa );
     // determine positions
     size_t first_index, last_index;
     getPosRange( tcoeff_list.size(), pos, first_index, last_index );
     // burnup columns
     for( size_t i = first_index; i < last_index; ++i )
     {
         table->addX_scientific( tcoeff_list[i]->burnup(), prec );
     }
     // transition coeff data columns
     const Vec_Int& num_parents = tm.num_parents();
     const Vec_Int& num_decay_parents = tm.num_decay_parents();
     int tind = -1;
     for( size_t i = 0; i < nucset.ids_size(); ++i )
     {
         int did = nucset.ids_at( i );
         for( int count = 0; count < num_parents.at( i ); ++count )
         {
             ++tind;
             int transition_id = tm.transition_ids().at( tind );
             if( tid != 0 && transition_id != tid ) continue;
             // skip zeroes if just outputting a single position
             if( pos > 0 && !output_zeros )
             {
                 double coeff =
                     tcoeff_list[static_cast<size_t>( abs( pos ) - 1 )]
                         ->matrix_at( tind );
                 if( coeff == 0.0 ) continue;
             }
             int ppos = tm.parent_positions().at( tind );
             int pid = nucset.ids_at( ppos - 1 );
             if( ngf.filter( pid ) ) continue;
             // add a new row
             table->addRow();
             std::stringstream ss;
             // add daughter
             ss << stringifyNuclide( did, idform );
             // add the transition id
             if( output_transition_ids )
             {
                 ss << "<--[" << transition_id << "]--";
             }
             else
             {
                 ss << "<----";
             }
             // add the parent
             ss << stringifyNuclide( pid, idform );
             table->addY( ss.str() );
             // now add all the coefficients
             double f = 1.0;
             if( count >= num_decay_parents.at( i ) && flux >= 0.0 )
                 f = flux * 1.0e-24;
             for( size_t k = first_index; k < last_index; ++k )
             {
                 double coeff = f * tcoeff_list[k]->matrix().at( tind );
                 // scale by coefficient at reference position
                 if( pos < 0 )
                 {
                     coeff /=
                         f *
                         tcoeff_list[( abs( pos ) - 1 )]->matrix().at( tind );
                 }
                 table->addCell_scientific( coeff, prec );
             }
         }
     }
 }
void Origen::tabulateTransitionCoeff (const Library & lib, int sizzzaaa, int tid, bool output_zeros, double flux, bool output_transition_ids, const std::string & idform, int prec, int pos, Table2D * table)
References Library::definition(), getTransitionCoeffList(), tabulateTransitionCoeff(), and Library::transition_structure().
 {
     Require( table != nullptr );
     tabulateTransitionCoeff( lib.definition(),
                              lib.transition_structure(),
                              getTransitionCoeffList( lib ),
                              sizzzaaa,
                              tid,
                              output_zeros,
                              flux,
                              output_transition_ids,
                              idform,
                              prec,
                              pos,
                              table );
 }
void Origen::tabulateBurnups (const Library & lib, int prec, Table2D * table)
References TransitionCoeff::burnup(), Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by printBurnups().
 {
     Require( table != nullptr );
     // setup table
     table->setTitle( "" );
     table->addX( "MWd/MTIHM" );
     for( int i = 0; i < static_cast<int>( lib.transition_coeff_size() ); ++i )
     {
         table->addY( i );
     }
     for( size_t i = 0; i < lib.transition_coeff_size(); ++i )
     {
         table->addRow();
         table->addCell_fixed( lib.transition_coeff_at( i ).burnup(), prec );
     }
 }
void tabulateMaterialIsotopics (const Material & mat, size_t point, ScaleUtils::IO::Table2D * table, SCP_Vec_Int & base_ids)
Examples:
Core/fn/tests/tsttabulate.cpp.
References Material::get_numden_at(), Material::library(), Material::name(), tabulateInitialNuclideColumns(), and auxiliary_erf_m::x.
Referenced by TEST_F().
 {
     // first column of nuclide ids
     // second column of nuclide indices
     if( base_ids == nullptr )
     {
         base_ids = mat.library()->definition().nuclide_set().scp_ids();
         tabulateInitialNuclideColumns( *base_ids, table );
     }
     Vec_Dbl numden;
     Check( base_ids != nullptr );
     mat.get_numden_at( &numden, point, *base_ids );
     // new column header
     table->addX( mat.name() );
     // 1 row for units
     size_t row = 0;
     table->selectRow( row );
     table->addCell( "(atoms/barn-cm)" );
     ++row;
     // 1 row for each value
     for( const auto& x : numden )
     {
         table->selectRow( row );
         table->addCell_scientific( x, 4 );
         ++row;
     }
 }
void tabulateMaterialTransitionRates (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, SCP_TransitionStructure & base_tstruct)
Examples:
Core/fn/tests/tsttabulate.cpp.
References Material::amount_at(), Material::flux_over(), NuclideSet::ids_at(), NuclideSet::ids_size(), Material::library(), Material::name(), stringifyNuclide(), Material::total_nuclides(), and Material::transition_matrix_over().
Referenced by TEST_F().
 {
     SCP_TransitionMatrixP trx = mat.transition_matrix_over( step );
     double flux = mat.flux_over( step );
     // generate average over step
     std::shared_ptr<const DoubleList> amount0 =
         mat.amount_at( step );  // beginning of step
     std::shared_ptr<const DoubleList> amount1 =
         mat.amount_at( step + 1 );  // end of step
     if( amount1 == nullptr ) amount1 = amount0;
     Vec_Dbl average_amount( mat.total_nuclides() );
     for( size_t i = 0; i < average_amount.size(); ++i )
     {
         average_amount[i] = 0.5 * ( amount0->at( i ) + amount1->at( i ) );
     }
     Check( trx != nullptr );
     // first column of transition definitions
     // second column of transition indices
     // third column of transition names
     if( base_tstruct == nullptr )
     {
         base_tstruct = mat.library()->scp_transition_structure();
         const NuclideSet& nucset = mat.library()->definition().nuclide_set();
         table->clear();
         bool has_mts = trx->has_valid_mts();
         // check if we have real decay modes (not just all -1)
         bool has_real_decay_modes = false;
         if( has_mts )
         {
             for( const auto& tid : *trx->get_mt() )
             {
                 if( tid < 0 && tid != -1 )
                 {
                     has_real_decay_modes = true;
                     break;
                 }
             }
         }
         // id form for everything
         const std::string idform( "$Z-$ee-$A$m:$TY" );
         // transition structure data columns
         const Vec_Int& num_parents = base_tstruct->num_parents();
         // first column of nuclide indices
         table->setTitle( "daughter<--[tid]--parent" );
         table->addY( "(-)" );  // units row
         int tind = -1;
         for( size_t i = 0; i < nucset.ids_size(); ++i )
         {
             int did = nucset.ids_at( i );
             for( int count = 0; count < num_parents.at( i ); ++count )
             {
                 ++tind;
                 int transition_id = base_tstruct->transition_ids().at( tind );
                 int ppos = base_tstruct->parent_positions().at( tind );
                 int pid = nucset.ids_at( ppos - 1 );
                 std::stringstream ss;
                 // add daughter
                 ss << stringifyNuclide( did, idform ) << "<--";
                 if( has_mts )
                 {
                     ss << "[" << transition_id << "]";
                 }
                 ss << "--" << stringifyNuclide( pid, idform );
                 table->addY( ss.str() );
             }
         }
         // second column of transition indices
         table->addX( "index" );
         table->addRow();
         table->addCell( "(-)" );  // units
         std::string out_of( "/" + std::to_string( tind + 1 ) );
         tind = 0;  // this loop outputs 1-based indices
         for( size_t i = 0; i < nucset.ids_size(); ++i )
         {
             for( int count = 0; count < num_parents.at( i ); ++count )
             {
                 ++tind;
                 table->addRow();
                 table->addCell( std::to_string( tind ) + out_of );
             }
         }
         // third column of transition names
         if( has_mts )
         {
             table->addX( "transition" );
             // add units row
             size_t row = 0;
             table->selectRow( row );
             table->addCell( "(-)" );  // units
             ++row;
             // add names row
             tind = -1;
             for( size_t i = 0; i < nucset.ids_size(); ++i )
             {
                 for( int count = 0; count < num_parents.at( i ); ++count )
                 {
                     ++tind;
                     table->selectRow( row );
                     ++row;
                     int transition_id =
                         base_tstruct->transition_ids().at( tind );
                     // resolve reaction name (decay modes are stored as <0 to
                     // distinguish, i.e. -decay_mode)
                     std::string name;
                     if( transition_id > 0 )
                     {
                         name =
                             ScaleData::Utils::mt_to_reaction( transition_id );
                     }
                     else
                     {
                         name = "DECAY";
                         if( has_real_decay_modes )
{
                             name = ScaleData::Utils::decay_mode_to_name(
                                 -transition_id );
                         }
                     }
                     table->addCell( name );
                 }
             }
         }
     }  // end first-time setup
     // add material name
     table->addX( mat.name() );
     // add units row
     size_t row = 0;
     table->selectRow( row );
     table->addCell( "(1/s)" );
     ++row;
     // transition structure data columns
     Check( base_tstruct != nullptr );
     const Vec_Int& num_parents = base_tstruct->num_parents();
     const Vec_Int& num_decay_parents = base_tstruct->num_decay_parents();
     // add actual coefficient row
     int tind = -1;
     for( size_t i = 0; i < num_parents.size(); ++i )
     {
         int decay_count = num_decay_parents.at( i );
         for( int count = 0; count < num_parents.at( i ); ++count )
         {
             ++tind;
             table->selectRow( row );
             ++row;
             double coeff = trx->get_a()->at( tind );
             // modify based on decay or reaction
             if( count < decay_count )
             {
                 coeff *= 1e24 * average_amount[i];
             }
             else
             {
                 coeff *= flux * average_amount[i];
             }
             table->addCell_scientific( coeff, 4 );
         }
     }
 }
void tabulateMaterialLoss (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append, int type)
References kernel_matrex::decay(), Material::flux(), Material::library(), Material::name(), tabulateInitialNuclideColumns(), Material::transition_matrix_over(), and auxiliary_erf_m::x.
Referenced by tabulateMaterialDecayConstant(), tabulateMaterialLossRate(), and tabulateMaterialLossXs().
 {
     Require( type >= 0 && type <= 3 );
     // type=0 is loss cross sections (barn)
     // type=1 is loss rate (barn/cm^2-s)
     // type=2 is decay constant (1/s)
     SCP_TransitionMatrixP trx = mat.transition_matrix_over( step );
     Check( trx != nullptr );
     // first column of nuclide ids
     // second column of nuclide indices
     if( !append )
     {
         auto base_ids = mat.library()->definition().nuclide_set().scp_ids();
         tabulateInitialNuclideColumns( *base_ids, table );
         append = true;
     }
     // new column header
     table->addX( mat.name() );
     // 1 row for units
     size_t row = 0;
     table->selectRow( row );
     if( type == 0 )
     {
         table->addCell( "(barn)" );
     }
     else if( type == 1 )
     {
         table->addCell( "(barn/cm^2-s)" );
     }
     else
     {
         table->addCell( "(1/s)" );
     }
     ++row;
     // 1 row for each value
     auto loxs = trx->get_tocap();
     auto decay = trx->get_dis();
     double flux = mat.flux();
     for( size_t i = 0; i < loxs->size(); ++i )
     {
         table->selectRow( row );
         double x = 0.0;
         if( type == 0 )
         {
             x = loxs->at( i );
         }
         else if( type == 1 )
         {
             x = loxs->at( i ) * flux + 1e24 * decay->at( i );
         }
         else
         {
             x = decay->at( i );
         }
         table->addCell_scientific( x, 4 );
         ++row;
     }
 }
void tabulateMaterialLossXs (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append)
References tabulateMaterialLoss().
 {
     tabulateMaterialLoss( mat, step, table, append, 0 );
 }
void tabulateMaterialLossRate (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append)
Examples:
Core/fn/tests/tsttabulate.cpp.
References tabulateMaterialLoss().
Referenced by TEST_F().
 {
     tabulateMaterialLoss( mat, step, table, append, 1 );
 }
void tabulateMaterialDecayConstant (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append)
References tabulateMaterialLoss().
 {
     tabulateMaterialLoss( mat, step, table, append, 2 );
 }
void tabulateMaterialFission (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append, int type)
References Material::flux(), NuclideSet::ids_at(), NuclideSet::ids_size(), Material::library(), Material::name(), NuclideSet::s_at(), SUBLIB_2AC, tabulateInitialNuclideColumns(), Material::transition_matrix_over(), and auxiliary_erf_m::x.
Referenced by tabulateMaterialFissionRate(), and tabulateMaterialFissionXs().
 {
     Require( type >= 0 && type <= 1 );
     // type=0 is fission xs (barn)
     // type=1 is fission rate (barn/cm^2-s)
     SCP_TransitionMatrixP trx = mat.transition_matrix_over( step );
     Check( trx != nullptr );
     // first column of nuclide ids
     // second column of nuclide indices
     if( !append )
     {
         const NuclideSet& nucset = mat.library()->definition().nuclide_set();
         Vec_Int ids;
         for( size_t i = 0; i < nucset.ids_size(); ++i )
         {
             if( nucset.s_at( i ) == SUBLIB_2AC )
             {
                 ids.push_back( nucset.ids_at( i ) );
             }
         }
         tabulateInitialNuclideColumns( ids, table );
         append = true;
     }
     // new column header
     table->addX( mat.name() );
     // 1 row for units
     size_t row = 0;
     table->selectRow( row );
     if( type == 0 )
     {
         table->addCell( "(barn)" );
     }
     else
     {
         table->addCell( "(barn/cm^2-s)" );
     }
     ++row;
     double flux = mat.flux();
     // 1 row for each value
     for( size_t i = 0; i < trx->get_iact(); ++i )
     {
         table->selectRow( row );
         double x = trx->get_fiss()->at( i );
         if( type == 1 ) x *= flux;
         table->addCell_scientific( x, 4 );
         ++row;
     }
 }
void tabulateMaterialFissionXs (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append)
References tabulateMaterialFission().
 {
     tabulateMaterialFission( mat, step, table, append, 0 );
 }
void tabulateMaterialFissionRate (const Material & mat, size_t step, ScaleUtils::IO::Table2D * table, bool & append)
Examples:
Core/fn/tests/tsttabulate.cpp.
References tabulateMaterialFission().
Referenced by TEST_F().
 {
     tabulateMaterialFission( mat, step, table, append, 1 );
 }
void Origen::tabulateNuclideLabel (const LibraryHeader & lh, int sizzzaaa, const std::string & idform, const std::string & units_row, ScaleUtils::IO::Table2D * table)
void Origen::tabulateNuclideInfo (const Library & lib, int sizzzaaa, const std::string & idform, int prec, ScaleUtils::IO::Table2D * table)
void Origen::tabulateFissionXs (const Library & lib, int sizzzaaa, const std::string & idform, int prec, int pos, ScaleUtils::IO::Table2D * table)
void Origen::tabulateLossXs (const Library & lib, int sizzzaaa, const std::string & idform, int prec, int pos, const std::string & column_name, bool append_column, ScaleUtils::IO::Table2D * table)
void Origen::tabulateLossXs (const LibraryHeader & lh, const std::vector< const TransitionCoeff * > & tcoeff_list, int sizzzaaa, const std::string & idform, int prec, int pos, const std::string & column_name, bool append_column, ScaleUtils::IO::Table2D * table)
void Origen::tabulateTransitionCoeff (const Library & lib, int sizzzaaa, int tid, bool output_zeros, double flux, bool transition_ids, const std::string & idform, int prec, int pos, ScaleUtils::IO::Table2D * table)
void Origen::tabulateTransitionCoeff (const LibraryHeader & lh, const TransitionStructure & tm, const std::vector< const TransitionCoeff * > & tcoeff_list, int sizzzaaa, int tid, bool output_zeros, double flux, bool transition_ids, const std::string & idform, int prec, int pos, ScaleUtils::IO::Table2D * table)
void Origen::tabulateBurnups (const Library & lib, int prec, ScaleUtils::IO::Table2D * table)
void Origen::tabulateReactionTransitions (const LibraryHeader & lh, const TransitionStructure & tm, bool output_zeros, const std::string & idform, ScaleUtils::IO::Table2D * table)
DecayResource* Origen::loadDecayResource (const Str path, ScaleUtils::IO::DB opts) inline
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by loadMulti(), and LibraryBuilderTester::SetUp().
 {
     return ScaleUtils::IO::load<DecayResource, DecayResourceIO>( path, opts );
 }
bool Origen::saveDecayResource (const DecayResource & obj, const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::save<DecayResource, DecayResourceIO>(
         obj, path, opts );
 }
GammaResource* Origen::loadGammaResource (const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::load<GammaResource, GammaResourceIO>( path, opts );
 }
bool Origen::saveGammaResource (const GammaResource & obj, const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::save<GammaResource, GammaResourceIO>(
         obj, path, opts );
 }
double Origen::guess_last_bin_energy (size_t nc, Vec_Dbl & e, size_t next)
Referenced by GammaResourceIO_cimg::read().
 {
     if( nc == 0 ) return 0.0;
     if( next < e.size() && e.size() > 2 )
     {
         return 2 * e[next] - e[next - 1];
     }
     else
     {
         return 0.0;
     }
 }
Library* Origen::loadLibrary (const Str path, ScaleUtils::IO::DB opts) inline
Examples:
Core/io/tests/tstLibraryIO.cpp, Manager/mzd/tests/tstParallelDepletion.cpp, and Solver/cram/src/tests/tstCRAM.cpp.
Referenced by Obiwan_interp::execute(), Obiwan_patch::execute(), interpLibraryND(), loadMulti(), main(), TEST(), TEST_F(), and tstCRAM::tstCRAM().
 {
     return ScaleUtils::IO::load<Library, LibraryIO>( path, opts );
 }
bool Origen::saveLibrary (const Library & obj, const Str path, ScaleUtils::IO::DB opts) inline
Examples:
Core/fn/tests/tstinterp.cpp, Core/io/tests/tstLibraryIO.cpp, Core/ut/tests/tstObiwan.cpp, Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by convertLibrary(), Obiwan_interp::execute(), Obiwan_patch::execute(), Obiwan_tag::execute(), main(), TEST(), and TEST_F().
 {
     return ScaleUtils::IO::save<Library, LibraryIO>( obj, path, opts );
 }
char Origen::endian_selector (const std::string & end)
Referenced by LibraryIO_s61::save().
 {
     char cend = 'N';  // native
     if( end == "big" )
     {
         cend = 'B';
     }
     else if( end == "little" )
     {
         cend = 'L';
     }
     return cend;
 }
NuclideResource* Origen::loadNuclideResource (const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::load<NuclideResource, NuclideResourceIO>( path,
                                                                      opts );
 }
bool Origen::saveNuclideResource (const NuclideResource & obj, const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::save<NuclideResource, NuclideResourceIO>(
         obj, path, opts );
 }
ReactionResource* Origen::loadReactionResource (const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::load<ReactionResource, ReactionResourceIO>( path,
                                                                        opts );
 }
bool Origen::saveReactionResource (const ReactionResource & obj, const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::save<ReactionResource, ReactionResourceIO>(
         obj, path, opts );
 }
StateSet* Origen::loadStateSet (const Str path, ScaleUtils::IO::DB opts) inline
Examples:
Core/fn/tests/tstio.cpp, and Core/io/tests/tstStateSetIO.cpp.
Referenced by loadMulti(), TEST(), TEST_F(), and TEST_P().
 {
     return ScaleUtils::IO::load<StateSet, StateSetIO>( path, opts );
 }
bool Origen::saveStateSet (const StateSet & obj, const Str path, ScaleUtils::IO::DB opts) inline
 {
     return ScaleUtils::IO::save<StateSet, StateSetIO>( obj, path, opts );
 }
YieldResource* Origen::loadYieldResource (const Str path, ScaleUtils::IO::DB opts) inline
Examples:
Core/io/tests/tstYieldResourceIO.cpp.
Referenced by loadMulti(), main(), and TEST().
 {
     return ScaleUtils::IO::load<YieldResource, YieldResourceIO>( path, opts );
 }
bool Origen::saveYieldResource (const YieldResource & obj, const Str path, ScaleUtils::IO::DB opts) inline
Examples:
Core/io/tests/tstYieldResourceIO.cpp.
Referenced by main(), and TEST().
 {
     return ScaleUtils::IO::save<YieldResource, YieldResourceIO>(
         obj, path, opts );
 }
std::string Origen::_to_id_string (int id)
Referenced by DecayResource::to_json().
 {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << id;
     return ss.str();
 }
void defaultNuclideResource (Origen::NuclideResource * nr)
add default contents to a nuclide resource
Examples:
Core/dc/tests/tstConcentrations.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References populateNuclideResource_StdComp().
Referenced by NuclideResource::NuclideResource(), LibraryBuilderTester::SetUp(), and TEST().
 {
     ScaleData::StdComp stdcomp;
     {
         InMemoryStdCompLibrary imscl;
         StdCompLibrary::convert( imscl, stdcomp );
     }
     Origen::populateNuclideResource_StdComp( nr, stdcomp );
 }
void get_default_kappas (const std::vector< int > & sizzzaaa_list, std::vector< float > & kappa_capture, std::vector< float > & kappa_fission)
grabs the default values for the energy release (MeV) per capture/fission NOTE: fission values are only for sublibrary, s == 2
References EnergyResource::getKappaValues().
Referenced by LibraryIO_bof::read(), LibraryIO_s62b::read(), and LibraryIO_s61::read().
 {
     kappa_capture.resize( sizzzaaa_list.size() );
     kappa_fission.clear();
     Origen::EnergyResource fiscap;
     size_t num_actinides = 0;
     for( size_t i = 0; i < sizzzaaa_list.size(); i++ )
     {
         double kapCap, kapFis;
         int s = sizzzaaa_list[i] / ScaleData::Utils::PIZZZAAA_P_OFFSET;
         int izzzaaa = sizzzaaa_list[i] % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         bool found = fiscap.getKappaValues( izzzaaa, kapCap, kapFis );
         if( !found )
         {
             // jDebugTaggedWarning("using default kappas for
             // sizzzaaa="<<sizzzaaa);
         }
         // everyone has capture
         kappa_capture[i] = kapCap;
         Check( kapCap >= 0.0 );
         if( s == 0 || s == 2 )
         {
             Check( kapFis >= 0.0 );
             kappa_fission.push_back( kapFis );
             num_actinides++;
         }
     }
     Ensure( num_actinides == kappa_fission.size() );
 }
bool Origen::id_matches (SP_Transition transition, int product_id)
 {
     return transition->id() == product_id;
 }
std::string yield_type_name (const YieldType yt)
References YIELD_DISTRIBUTED, YIELD_ISOMERIC, YIELD_MISSING, and YIELD_SIMPLE.
Referenced by ReactionResource::print().
 {
     if( yt == YIELD_SIMPLE )
     {
         return "SMPL";
     }
     else if( yt == YIELD_ISOMERIC )
     {
         return "ISOM";
     }
     else if( yt == YIELD_DISTRIBUTED )
     {
         return "DIST";
     }
     else if( yt == YIELD_MISSING )
     {
         return "MISS";
     }
     return "UNKN";
 }
ScaleUtils::IO::DB Origen::baseOptions (Standard::CommandLine & cmd)
References populateObiwan_dataType(), and version().
Referenced by Obiwan_convert::populate(), Obiwan_tag::populate(), Obiwan_patch::populate(), and Obiwan_interp::populate().
 {
     ScaleUtils::IO::DB base;
     // overwrite
     base.set( "overwrite", cmd.exists( "-i" ) ? true : false );
     // verbose
     base.set( "verbose", cmd.exists( "-verbose" ) ? true : false );
     if( cmd.getValue( "-format", "" ) != "" &&
         cmd.getValue( "-version" ) != "" )
     {
         base.appendError( "cannot specify both -format and -version" );
     }
     // default for version (always overridden by format if non-null)
     std::string version = cmd.getValue( "-version", "6.2" );
     base.set( "desiredTargetScaleVersion", version );
     // remove parts
     base.set( "removeMass", cmd.exists( "-remove_mass" ) );
     base.set( "removeAbundance", cmd.exists( "-remove_abund" ) );
     // desired format
     base.set( "desiredFileFormat", cmd.getValue( "-format", "" ) );
     // get data type to read
     populateObiwan_dataType( &base, cmd.getValue( "-type", "" ) );
     // default for targetEndian
     std::string endian = ( version == "6.1" ) ? "big" : "native";
     base.set( "targetEndian", cmd.getValue( "-endian", endian ) );
     base.set( "targetDirectory", cmd.getValue( "-dir", "." ) );
     base.set( "thinningEnabled", cmd.getValueAs( "-thin", false ) );
     if( base.get<bool>( "thinningEnabled" ) )
     {
         base.setFromJson<DoubleList*>( "timeValues",
                                        cmd.getValue( "-tvals", "[]" ) );
         base.set( "interpMethod", cmd.getValue( "-interp", "near" ) );
         //        base.set("deltaTimeMin",cmd.getValueAs("-dtmin",100.));
         //        base.set("deltaTimeMax",cmd.getValueAs("-dtmax",5000.));
         base.set( "responseVariable", cmd.getValue( "-rvar", "loxs" ) );
         base.set( "responseNuclide", cmd.getValue( "-rnuc", "pu240" ) );
         base.set( "verbose", true );
         //        base.set("responseTolerance",cmd.getValueAs("-rtol",1e-3));
     }
     if( cmd.exists( "-setbu" ) )
     {
         base.setFromJson<DoubleList*>( "newBurnups",
                                        cmd.getValue( "-setbu", "[]" ) );
     }
     return base;
 }
int Origen::info (const StateSet & state_set, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
Examples:
Core/dc/tests/tstGridView.cpp.
Referenced by StateSet::create_interp_times(), StateSet::create_interp_viewers(), Obiwan_info::execute(), StateSet::interpolate_internal(), kernel_cram(), StateSet::matching_states(), StateSet::nearest_time(), printConcentrations_csv(), printStateInfo(), printTags_json(), StateSetIO_s61::read(), and TEST().
 {
     return 0;
 }
int Origen::info (const Library & lib, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
 {
     return 0;
 }
int Origen::info (const DecayResource & dr, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
 {
     return 0;
 }
int Origen::info (const YieldResource & yr, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
 {
     return 0;
 }
static ScaleUtils::IO::DB Origen::baseOptions () static
 {
     ScaleUtils::IO::DB opts;
     // overwrite
     opts.set( "overwrite", true );
     opts.set( "targetDirectory", "." );
     return opts;
 }
std::string Origen::splash ()
Referenced by obiwan_main().
 {
     return R"OBIWAN(
 sydNNNMMNs+//++++sNMMMNNNMMNmdyso/:-------:::+ohmNNMMNNMMMMNNNNNNNNNNNNNmmmmmddh
 ossydMMMMh+///+/+odNNNdyo+:-.............-------:/ydNNMNMMNNNNNNNNNNNNNNNNNNmmdd
 ooooohNMMh+++///++ydy/.````````````   ```..........-+ymNNNNNNNNNNNNNNNNNNNNNmmmm
 s+:-:/odNd++//////:-`            ``      ```..........:odNNNNNNNNNNNNNNNNNNNNmmm
 :.`  `.:yd+/////:.``            `.....`   ``````........-sNNNNNNNNNNmNmmmNNNNNNN
 ```     .++//::.``             `..-::/:-`` ``````......`..omNNNNNNNNNNNmmNNNNNNN
 ````     ./+/-```              `--::++++/-`````````....``..oNNNNNNNNNNNNNNNNNNNm
 .```    ` ./.```              `-:///osssss+:.```````.`.```.-mNNNNNNNNNNNNNNNNNNN
 --.`       ````              `-:/+oossyyyyyhho. `````..```..dNNNNNNNNNNNNNNNNNNm
 ``...`    `````             `--:/+osysysyhhddds:`  ```````.-mNNNNNMMNNNNNNNNNNmd
 ``  `.`` `````             `.-://+oyyshoyyydhyyo/.   ````.-yNmmmNNMMMNNNNNNNNmdd
 ``    ````````             `-::///+osooosoyyysyso+:`   ``.+y/sdNNNMMMMNNNNNNNNNN
 ``    ``````               `.-::::::///o/+ooosssoo+-    ``..``-odNNNNNNNNNNNNNNN
 `` `` ``````               `.-:++::-.:+s/::-:/oo+++/`   ``````.-oNNNNNNNNNNNNNNN
   ``  `````              `...-:+o+/..:oso+:--:+//+++:`  `````./hmNNMMNNNNNNNNNNN
       ```````            .-:://++/:..-+o+o/:/+o++/++/.  ````.omNNNNNNNNNNNNNNNNN
       `````` `           `.:/+oo+:...:osooso+ooooo+//-   ````/ooooshdmNNNNNNNNNN
       `````````           `-:/+o+-..-/osoosyyyyso++/:-   ``  ``.....-:+syhdmNNmd
        ```````            `.-/+o:``.-/ssooosyhyso++//-   `    `````.````.-:/oo/-
          ````` `         ``.-:/+-```.:/++oo+osoo+++//-  `      ``````.```````.``
             ` ``        ``..--/+/:--:-/+ossso+++++///`  ```       ````````  ` ``
                `        `.---::-:::++///+oossoo+++//.   ```  ```````.`````   ```
                         `.::++/-..---::://++osso++/-    ``.-/+ooso+//-.`` ``````
 `                  `    `-/osso:--::////++++ooo/:-:` `...-/osyso++/++oo+/:.`````
 ```                     `.-/+yyo//+++++o++//:-..``....-:/+oo+::://osssyysso:````
 ``..`                   ```.-+hhs++++++/:-----.```:/-``-:--.``.-//:::/++osyy+```
 `....`  ``   `             ``.shso+//:-...---.`   `...-.```--:/:::/-....-/oss:
 ``-..``  ``` ``              ./oo/-....--:..``      `-/o: `::+syyssso+/-..-:/:`
 .`..````    ` `              ``:/:-.-/+++:.``        .:oo`  ./ossyyyyhhs/--..`
 .`-.`````   ```````           `````.:/-:-.```        `-+s:`.:++osysooo+/:.``
 ..---.```   ```````                 -o`  ```          `:o+//+++/::::---.``
 ..-...```   ````````            ``  .so`              `-/+/:--..````
 -..``  `     ```````                 ``.`               ``
 )OBIWAN";
 }
std::string Origen::random_line (std::string mode)
Referenced by obiwan_main().
 {
     std::vector<std::string> lines;
     lines.push_back(
         "               You don't need to see his identification." );
     lines.push_back(
         "               These aren't the droids you're looking for." );
     lines.push_back( "                     You can go about your business." );
     lines.push_back( "                              Move along." );
     for( const auto& line : lines )
     {
         if( line.find( mode ) != std::string::npos ) return line;
     }
     return lines.back();
 }
std::string Origen::help ()
Examples:
Core/ut/tests/tstObiwan.cpp.
Referenced by obiwan_main(), and TYPED_TEST_P().
 {
     const char* help = R"OBIWAN(
 //! [help]
  usage: obiwan <mode>
          <mode>   description
     -----------   ----------------------------------------
         convert   convert between versions of files
            diff   diff/compare two files
            info   print basic info about multiple files
          interp   interpolate files
           patch   patch data in files
             tag   manipulate tags on a file
            view   view a file
            help   this help screen
 //! [help]
     )OBIWAN";
     return ScaleUtils::IO::removeSubstring( help, "//! [help]" );
 }
int Origen::obiwan_main (Vec_Str args, std::ostream & out, std::ostream & err)
Examples:
Core/ut/tests/tstObiwan.cpp.
Referenced by main(), and TEST().
 {
     std::vector<char*> args2;
     for( auto& str : args )
     {
         args2.push_back( &str[0] );
     }
     args2.push_back( nullptr );
     return obiwan_main( static_cast<int>( args.size() ), &args2[0], out, err );
 }
int obiwan_main (int argc, char ** argv, std::ostream & out, std::ostream & err)
References Obiwan_convert::execute(), Obiwan_info::execute(), Obiwan_view::execute(), Obiwan_interp::execute(), Obiwan_tag::execute(), Obiwan_patch::execute(), Obiwan_diff::execute(), help(), random_line(), and splash().
 {
     if( argc <= 1 )
     {
         out << help() << std::endl;
         return 0;
     }
     // shift off first "mode" argument
     std::string mode( argv[1] );
     argc -= 1;
     for( int i = 1; i < argc; ++i ) argv[i] = argv[i + 1];
     CANONICALIZE_SCIENTIFIC_EXPONENT_LOCALLY();
     // switch
     int status = 0;
     if( mode == "convert" )
     {
         Origen::Obiwan_convert exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "diff" )
     {
         Origen::Obiwan_diff exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "info" )
     {
         Origen::Obiwan_info exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "interp" )
     {
         Origen::Obiwan_interp exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "patch" )
     {
         Origen::Obiwan_patch exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "tag" )
     {
         Origen::Obiwan_tag exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "view" )
     {
         Origen::Obiwan_view exe( argc, argv );
         status = exe.execute( out, err );
     }
     else if( mode == "help" )
     {
         out << help() << std::endl;
     }
     else
     {
         out << splash() << "\n";
         out << random_line( mode ) << "\n\n";
         err << "ERROR: found mode={" << mode
             << "} but mode must be (convert|diff|info|interp|tag|view|help)\n";
         status = 1;
     }
     return status;
 }
std::string Origen::applyPatch (SP_Library fromLib, IntegerList * coeffPosList, const std::string & coeffData, SP_Library lib, int pos)
Referenced by Obiwan_patch::execute().
 {
     // need to fill this many values
     size_t nSink = pos == 0 ? lib->transition_coeff_size() : 1;
     size_t nSource = fromLib == nullptr ? 1 : fromLib->transition_coeff_size();
     // single position for the user-defined patch so we just copy
     if( coeffPosList->size() == 1 )
     {
         auto single = coeffPosList->at( 0 );
         for( size_t i = 1; i < nSink; ++i ) coeffPosList->push_back( single );
     }
     // coeffPosList is empty and we need to create it
     else if( coeffPosList->size() == 0 )
     {
         // the source only has one position so we just copy
         if( nSource == 1 )
         {
             for( size_t i = 0; i < nSink; ++i ) coeffPosList->push_back( 1 );
         }
         // otherwise there should be 1-to-1 mapping
         else
         {
             for( size_t i = 0; i < nSource; ++i )
                 coeffPosList->push_back( i + 1 );
         }
     }
     // check correct sizes
     if( coeffPosList->size() != nSink )
     {
         return "the number of positions to extract for the patch (" +
                std::to_string( coeffPosList->size() ) +
                ") must match the number of positions on the target (" +
                std::to_string( nSink ) + ").";
     }
     // check coeffPosList positions are valid
     if( fromLib != nullptr )
     {
         for( auto j : *coeffPosList )
         {
             if( j < 1 || j > nSource )
                 return "the position on the -from library (" +
                        std::to_string( j ) + ") is not valid (>=1 and <=" +
                        std::to_string( nSource ) + ")";
         }
     }
     // start the patching
     for( size_t i = 0; i < nSink; ++i )
     {
         // patch this position on sink
         if( pos == 0 || pos == i + 1 )
         {
             // get copies
             auto tc = lib->transition_coeff_at( i );
             auto npxs = tc.neutron_yields();
             // fix nans
             for(auto& xs : npxs )
             {
                 if( std::isnan(xs) )xs=0;
             }
             size_t n = npxs.size();
             // replace with zeros if source was NULL
             if( fromLib == nullptr )
             {
                 npxs.clear();
                 npxs.resize( n, 0.0 );
             }
             // otherwise actually query source
             else
             {
                 // get index on the source
                 int fromPos =
                     pos > 0 ? coeffPosList->at( 0 ) : coeffPosList->at( i );
                 auto& fromTc = fromLib->transition_coeff_at( fromPos - 1 );
                 size_t fromN = fromTc.neutron_yields_size();
                 if( n != fromN )
                     return "sizes of the n_production_xs are not the same on "
                            "the -from library (" +
                            std::to_string( fromN ) + ") and the destination (" +
                            std::to_string( n ) + ")!";
                 //just replace neutron production xs
                 if( coeffData=="n_production_xs" )
                 {
                     npxs = fromTc.neutron_yields();
                 }
                 //only replace nu and hack it as n_production_xs/sigma_f
                 else if( coeffData=="nu" )
                 {
                     auto new_npxs = fromTc.neutron_yields();
                     // fix nans
                     for(auto& xs : new_npxs )
                     {
                         if( std::isnan(xs) )xs=0;
                     }
                     auto new_sigf = fromTc.fission_xs();
                     auto old_sigf = tc.fission_xs();
                     size_t sigf_offset = new_npxs.size()-new_sigf.size();
                     for(size_t i=sigf_offset; i<npxs.size(); ++i)
                     {
                         if( new_sigf[i-sigf_offset]>0.0 )
{
                             auto nu = 1+new_npxs[i]/new_sigf[i-sigf_offset];
                             npxs[i] = nu*old_sigf[i-sigf_offset];
                         }
                     }
                 }
             }
             tc.set_neutron_yields( npxs );
             lib->set_transition_coeff_at( tc, i );
         }
     }
     return "";
 }
static ScaleUtils::IO::DB Origen::baseOptions () static
 {
     ScaleUtils::IO::DB opts;
     // overwrite
     opts.set( "overwrite", true );
     opts.set( "targetDirectory", "." );
     return opts;
 }
int Origen::view (const Origen::Library & lib, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
Examples:
Core/dc/tests/tstLibrary.cpp.
References TransitionGroupFilter::allow_decay, TransitionGroupFilter::allow_fission, TransitionGroupFilter::allow_reaction, COPY_LIST, graphvizLibrary(), printBurnups(), printFissionXs(), printLossXs(), printNeutronProductionRatio(), printNeutronYields(), printNuclideInfo(), printReactionTransitions(), printTags_json(), printTransitionCoeff(), and Library::to_json().
Referenced by Obiwan_view::execute(), and TEST().
 {
     // format
     std::string format = opts.get( "format", "coeff" );
     std::string idform = opts.get<std::string>( "idform", "" );
     bool output_zeros = opts.get( "output_zeros", true );
     // output burnups
     if( format == "burnups" )
     {
         bool transpose = opts.get( "transpose", true );
         int prec = opts.get( "prec", 4 );
         printBurnups( lib, transpose, prec, out );
     }
     // output is JSON format
     else if( format == "json" )
     {
         out << lib.to_json().toStyledString();
     }
     // text output of coefficients
     else if( format == "" || format == "coeff" || format == "coefft" )
     {
         int sizzzaaa = opts.get( "sizzzaaa", 0 );
         int tid = opts.get( "tid", 0 );
         bool transpose = opts.get( "transpose", true );
         double flux = opts.get( "flux", 1.0 );
         bool coefft = format == "coefft" ? true : false;
         int prec = opts.get( "prec", 4 );
         int pos = opts.get( "pos", 1 );
         printTransitionCoeff( lib,
                               sizzzaaa,
                               tid,
                               transpose,
                               output_zeros,
                               flux,
                               coefft,
                               idform,
                               prec,
                               pos,
                               out );
     }
     // tags
     else if( format == "tags" )
     {
         std::string path = opts.get<std::string>( "path" );
         printTags_json( lib, path );
     }
     // reaction
     else if( format == "reaction" )
     {
         printReactionTransitions( lib, output_zeros, idform, out );
     }
     // text output of nuclide
     else if( format == "nucl" )
     {
         int sizzzaaa = opts.get( "sizzzaaa", 0 );
         bool transpose = opts.get( "transpose", true );
         int prec = opts.get( "prec", 4 );
         printNuclideInfo( lib, sizzzaaa, transpose, idform, prec, out );
     }
     // print data sources
     else if( format == "genneu" || format == "nprodr" || format == "fisxs" ||
              format == "loxs" )
     {
         int sizzzaaa = opts.get( "sizzzaaa", 0 );
         bool transpose = opts.get( "transpose", true );
         int prec = opts.get( "prec", 4 );
         int pos = opts.get( "pos", 1 );
         if( format == "fisxs" )
         {
             printFissionXs( lib, sizzzaaa, transpose, idform, prec, pos, out );
         }
         else if( format == "loxs" )
         {
             printLossXs( lib, sizzzaaa, transpose, idform, prec, pos, out );
         }
         else if( format == "genneu" )
         {
             printNeutronYields( lib, pos, out );
         }
         else if( format == "nprodr" )
         {
             printNeutronProductionRatio( lib, pos, out );
         }
     }
     // output transition system channel
     else if( format == "ts" )
     {
         opts.appendError(
             "TransitionSystem (ts) output is currently disabled" );
         return -3;
     }
     // output graph
     else if( format == "graphviz" )
     {
         Origen::TransitionGroupFilter tfilter;
         Origen::NuclideGroupFilter nfilter;
         COPY_LIST( opts, IntegerList, nfilter, allow_s );
         COPY_LIST( opts, IntegerList, nfilter, allow_i );
         COPY_LIST( opts, IntegerList, nfilter, allow_z );
         COPY_LIST( opts, IntegerList, nfilter, allow_a );
         COPY_LIST( opts, IntegerList, tfilter, allow_transition_id );
         tfilter.allow_decay = opts.get( "allow_decay", true );
         tfilter.allow_reaction = opts.get( "allow_reaction", true );
         tfilter.allow_fission = opts.get( "allow_fission", false );
         bool include_byproducts = opts.get( "include_byproducts", false );
         int pos = opts.get( "pos", 1 );
         // std::vector<double> nd = ndtest();
         // std::ofstream ofs("o.txt");
         // graphvizLibrary(*lib,pos,&nd,nfilter,tfilter);
         graphvizLibrary(
             lib, pos, nullptr, nfilter, tfilter, include_byproducts, out );
     }
     // error
     else
     {
         opts.appendError( "view format={" + format +
                           "} unknown for Origen::Library type (see help)" );
         return -4;
     }
     return 0;
 }
int Origen::view (const StateSet & state_set, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
References convertStringToConcUnit(), NOT_GIVEN, printConcentrations_csv(), printStateInfo(), and printTags_json().
 {
     // format
     std::string format = opts.get( "format", "info" );
     std::string idform = opts.get<std::string>( "idform", "" );
     if( format == "" || format == "info" )
     {
         printStateInfo( state_set, 1, out );
     }
     else if( format == "tags" )
     {
         printTags_json( state_set, out );
     }
     else if( format == "csv" )
     {
         std::string units = opts.get<std::string>( "units", "" );
         ConcentrationUnit conc_units;
         if( units.length() != 0 )
         {
             conc_units = convertStringToConcUnit( units );
             if( conc_units == NOT_GIVEN )
             {
                 opts.appendError(
                     "unknown units={" + units +
                     "} for Origen::StateSet csv format (see help)" );
                 return -5;
             }
         }
         else
         {
             conc_units = NOT_GIVEN;
         }
         printConcentrations_csv( state_set, conc_units, nullptr, idform, out );
     }
     // error
     else
     {
         opts.appendError( "view format={" + format +
                           "} unknown for Origen::StateSet type (see help)" );
         return -4;
     }
     return 0;
 }
int Origen::view (const DecayResource & decay_resource, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
References printDecayTable().
 {
     printDecayTable( decay_resource, out );
     return 0;
 }
int Origen::view (const YieldResource & yield_resource, ScaleUtils::IO::DB opts, std::ostream & out, std::ostream & err)
References printYields().
 {
     printYields( yield_resource, out );
     /*
         Vec_Str errors;
         yield_resource.check_consistency(errors);
         opts.writeErrorStack(err,errors);
     */
     return 0;
 }
const char* Origen::version ()
Referenced by baseOptions(), LibraryIO_bof::read(), and setAppVersionWrite().
const char* Origen::config (const char * field = "")
std::string Origen::doIndent (int indent)
Referenced by CompManager::toString().
 {
     std::stringstream ss;
     std::string in = "  ";
     for( int j = 1; j <= indent; j++ )
     {
         ss << in;
     }
     return ss.str();
 }
std::string Origen::toYesNo (bool yes_no)
Referenced by CompManager::toString().
 {
     if( yes_no )
     {
         return "yes";
     }
     else
     {
         return "no";
     }
 }
void Origen::setup_search_variables (const std::vector< NuclideId > & in_sizzzaaa_list, std::map< NuclideId, size_t > & nind_lookup)
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), and LibraryBuilder::search_reaction_transitions().
 {
     NuclideId sizzzaaa;
     for( size_t nind = 0; nind < in_sizzzaaa_list.size(); nind++ )
     {
         sizzzaaa = in_sizzzaaa_list[nind];
         nind_lookup[sizzzaaa] = nind;
     }
 }
bool Origen::check_sizes (size_t total_nuclides, size_t total_transitions, std::vector< int > & num_decay_parents, std::vector< int > & num_parents, std::vector< int > & parent_positions, std::vector< int > & transition_ids, std::vector< double > & transition_coeff)
Referenced by LibraryBuilder::create_decay_transitions(), and LibraryBuilder::create_reaction_transitions().
 {
     jDebugLine(
         "LibraryBuilder::check_sizes\n"
         "total_nuclides="
         << total_nuclides
         << "\n"
         << "total_transitions="
         << total_transitions
         << "\n"
         << "num_decay_parents.size()="
         << num_decay_parents.size()
         << "\n"
         << "num_parents.size()="
         << num_parents.size()
         << "\n"
         << "transition_ids.size()="
         << transition_ids.size()
         << "\n"
         << "parent_positions.size()="
         << parent_positions.size()
         << "\n"
         << "transition_coeff.size()="
         << transition_coeff.size()
         << "\n" );
     return num_decay_parents.size() == total_nuclides &&
            num_parents.size() == total_nuclides &&
            transition_ids.size() == total_transitions &&
            transition_coeff.size() == total_transitions &&
            parent_positions.size() == total_transitions;
 }
void Origen::vector_copy (size_t nelem, size_t start, const std::vector< T > * old_list, std::vector< T > & new_list)
Referenced by LibraryBuilder::create_reaction_transitions().
 {
     std::copy( old_list->begin() + start,
                old_list->begin() + start + nelem,
                std::back_inserter( new_list ) );
 }
void Origen::shrink_to_fit (std::vector< T > & x)
Referenced by LibraryBuilder::create_decay_transitions().
 {
     std::vector<T>( x.begin(), x.end() ).swap( x );
 }
double Origen::calculate_neutron_production_xs (SP_Nuclide residual)
References NEUTRON_FIELD.
Referenced by LibraryBuilder::create_reaction_transitions(), and LibraryBuilder::update_reaction_transitions().
 {
     double coeff = 0;
     for( auto loss : residual->losses() )
     {
         for( auto transition : loss->transitions() )
         {
             if( transition->product()->id() == NEUTRON_FIELD )
             {
                 coeff += transition->coeff();
             }
         }
     }
     return coeff;
 }
std::map<int, std::pair<CrossSection1d*, SP_Transition> > Origen::collect_direct_yields (SP_Field neutron_field, SP_Nuclide nuclide, int izzzaaa, TS_t ts, LibraryNuclide * ampx_nuclide, const DirectYields_t & direct_yields)
 {
     std::map<int, std::pair<CrossSection1d*, SP_Transition>> yield_map;
     // loop through now and collect cross sections
     int num_1dxs = ampx_nuclide->getNumNeutron1dData();
     for( int k = 0; k < num_1dxs; k++ )
     {
         CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
         int mt = xs->getMt();
         jDebugTaggedLine( "collect_direct_yields: mt=" << mt );
         // check for direct yields (e.g. nubar=452)
         auto itd = direct_yields.find( mt );
         if( itd != direct_yields.end() )
         {
             // evaluate target_mt (e.g. fission=18)
             int target_mt = itd->second.first;
             auto channeltype = ts->channel_type( neutron_field, target_mt );
             if( channeltype == nullptr )
             {
                 jDebugTaggedLine(
                     "collect_direct_yields: skipping nuclide id="
                     << ampx_nuclide->getId()
                     << " (izzzaaa="
                     << izzzaaa
                     << ") with direct_yield for mt="
                     << mt
                     << " to target_mt="
                     << target_mt
                     << " because target_mt does not exist in the system" );
                 continue;
             }
             // evaluate target_izzzaaa (e.g. neutron=1)
             int target_izzzaaa = itd->second.second;
             auto target = ts->nuclide( target_izzzaaa );
             if( target == nullptr )
             {
                 jDebugTaggedLine( "collect_direct_yields: skipping nuclide id="
                                   << ampx_nuclide->getId()
                                   << " (izzzaaa="
                                   << izzzaaa
                                   << ") with direct_yield for mt="
                                   << mt
                                   << " to target_mt="
                                   << target_mt
                                   << " because target_nuclide="
                                   << target_izzzaaa
                                   << " does not exist in the system" );
                 continue;
             }
             // evaluate channel
             auto channel = nuclide->loss( channeltype->id() );
             if( channel == nullptr )
             {
                 jDebugTaggedLine( "collect_direct_yields: skipping nuclide id="
                                   << ampx_nuclide->getId()
                                   << " (izzzaaa="
                                   << izzzaaa
                                   << ") with direct_yield for mt="
                                   << mt
                                   << " to target_mt="
                                   << target_mt
                                   << " with target_nuclide="
                                   << target_izzzaaa
                                   << " does not have the required channel" );
                 continue;
             }
             // evaluate target
             auto transition = channel->transition( target_izzzaaa );
             if( transition == nullptr )
             {
                 jDebugTaggedLine( "collect_direct_yields: skipping nuclide id="
                                   << ampx_nuclide->getId()
                                   << " (izzzaaa="
                                   << izzzaaa
                                   << ") with direct_yield for mt="
                                   << mt
                                   << " to target_mt="
                                   << target_mt
                                   << " does not have target_nuclide="
                                   << target_izzzaaa
                                   << " as a daughter" );
                 continue;
             }
             jDebugTaggedLine(
                 "collect_direct_yields: including direct yield for "
                 "nuclide id="
                 << ampx_nuclide->getId()
                 << " (izzzaaa="
                 << izzzaaa
                 << ") target_mt="
                 << target_mt
                 << " target_izzzaaa="
                 << target_izzzaaa );
             // save in map
             yield_map[target_mt] = std::make_pair( xs, transition );
         }
     }
     return yield_map;
 }
Variable Documentation
const int TIME_S = 1
const int TIME_M = 2
const int TIME_H = 3
const int TIME_D = 4
const int TIME_Y = 5
const int SUBLIB_LEGACY_ELEMENT = 4
const int INTERP_PREFERRED = 0 static
const int INTERP_HISTOGRAM = 1 static
const int INTERP_LINLIN = 2 static
Examples:
Core/io/tests/tstYieldResourceIO.cpp.
Referenced by TEST().
const int INTERP_LINLOG = 3 static
const int INTERP_LOGLIN = 4 static
const int INTERP_LOGLOG = 5 static
const int IMPLICIT_BYPRODUCT_MAX_MASSNUMBER = 4 static
Referenced by YieldResource::check_consistency().