ORIGEN API: Core/xf/tests/tstMultiZoneDepleter.cpp File Reference
tstMultiZoneDepleter.cpp File Reference
#include <algorithm>
#include <iostream>
#include <string>
#include <vector>
#include "Origen/Core/io/LibraryIO.h"
#include "Origen/Core/xf/MultiZoneDepleter.h"
#include "Origen/Core/xf/Solver_Fake.h"
#include "ScaleUtils/IO/DB.h"
#include "Nemesis/comm/Logger.hh"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Nemesis/harness/DBC.hh"
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/dc/TransitionMatrixP.h"
#include "ScaleSTL/Functions.h"
#include "Standard/Interface/AbstractWriter.h"
#include "Standard/Interface/BasicIOWriter.h"
#include "Standard/Interface/Communicator.h"
#include "Standard/Interface/jdebug.h"
Classes
class MultiZoneDepleterTester
class Stepper
class Stepper_fixed
class MultiZoneDepleterTesterP
Typedefs
typedef std::vector< std::string > Vec_Str
typedef Origen::Vec_Dbl Vec_Dbl
typedef std::shared_ptr< Stepper > SP_Stepper
Functions
TEST (MultiZoneDepleter, CommTest)
void get_name_id (int start, std::string &name, int &id)
Origen::SP_Material setup_material1 (Origen::SP_Library lib)
Origen::SP_Material setup_material2 (Origen::SP_Library lib)
void build_simple_data1 (Origen::SP_Library lib, DataContainer &dc, Origen::SP_MaterialMap matmap)
void build_simple_data2 (Origen::SP_Library lib, DataContainer &dc, Origen::SP_MaterialMap matmap)
TEST_F (MultiZoneDepleterTester, DepleteByFlux)
TEST_F (MultiZoneDepleterTester, DepleteByPower)
::std::ostream & operator<< (::std::ostream &os, const Stepper &s)
::std::ostream & operator<< (::std::ostream &os, const SP_Stepper &s)
TEST_P (MultiZoneDepleterTesterP, PowerConstraint0)
const Vec_Dbl dtrel_1 ({1.0})
const Vec_Dbl dtrel_3 ({0.1, 0.2, 0.7})
INSTANTIATE_TEST_CASE_P (StepperTesting, MultiZoneDepleterTesterP,::testing::ValuesIn(steppers))
Variables
Standard::Communicator world
const std::vector< SP_Stepper > steppers
Typedef Documentation
typedef std::vector<std::string> Vec_Str
typedef Origen::Vec_Dbl Vec_Dbl
typedef std::shared_ptr<Stepper> SP_Stepper
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
Function Documentation
TEST (MultiZoneDepleter , CommTest)
References world, and auxiliary_erf_m::x.
 {
     //    jDebugLine("Host: '" << world.host()
     //            << "', rank: " << world.rank()
     //            << ", size: " << world.size());
     double x = world.rank();
     std::vector<double> vecx;
     world.allgather( x, vecx );
     for( size_t i = 0; i < vecx.size(); ++i )
     {
         // pnout << nprintf("rank: %3d
         // val[%3d]=%8.2f\n",world.rank(),i,vecx[i]);
         EXPECT_EQ( i, vecx[i] );
     }
     world.barrier();
     std::ofstream ofs(
         nprintf( "%s_%04d", world.host().c_str(), world.rank() ) );
     ofs << world.host() << std::endl;
     ofs << world.rank() << std::endl;
     for( size_t i = 0; i < vecx.size(); ++i )
     {
         ofs << nprintf( "val[%3d]=%8.2f\n", i, vecx[i] );
     }
     ofs.close();
 }
void get_name_id (int start, std::string & name, int & id)
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
References world.
Referenced by MultiZoneDepleterTester::SetUp(), setup_material1(), and setup_material2().
 {
     id = 1000 * ( world.rank() + 1 ) + start;
     name = nprintf( "mix%05d", id );
 }
Origen::SP_Material setup_material1 (Origen::SP_Library lib)
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
References get_name_id().
Referenced by build_simple_data1().
 {
     // Don't be alarmed, this is all just approximate.
     double cm2_barn = 1e-24;              // cm^2/barn
     double at_mol = 6.022e23;             // at/mol
     double dens = 10.4;                   // g/cm^3
     double vol = 12.0;                    // cm^3
     double hm_dens = 0.8815 * dens;       // gHM/cm^3
     double mol_hm = hm_dens / 235.;       // moles/cm^3 HM
     double atom_hm = mol_hm * at_mol;     // atoms/cm^3 HM
     double abcm_hm = atom_hm * cm2_barn;  // atoms/barn*cm HM
     double amt_hm = abcm_hm * vol;        // atoms*cm^2/barn HM
     // library variables
     std::string name0;
     int id0;
     get_name_id( 5, name0, id0 );
     Origen::SP_Material mat(
         new Origen::Material( "GENERAL", lib, name0, id0, vol ) );
     jDebugTaggedLine( "material library assoc finished..." );
     // BOS numden
     std::vector<int> id{92235};
     std::vector<double> num{amt_hm};
     mat->set_amount_bos( num, id );
     jDebugTaggedLine( "set begin-of-step..." );
     // std::cout << mat->to_string() << std::endl;
     jDebugTaggedLine( "leaving setup_material1" );
     return mat;
 }
Origen::SP_Material setup_material2 (Origen::SP_Library lib)
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
References get_name_id().
Referenced by build_simple_data2().
 {
     // Don't be alarmed, this is all just approximate.
     double cm2_barn = 1e-24;              // cm^2/barn
     double at_mol = 6.022e23;             // at/mol
     double dens = 10.4;                   // g/cm^3
     double vol = 7.5;                     // cm^3
     double hm_dens = 0.8815 * dens;       // gHM/cm^3
     double mol_hm = hm_dens / 238.;       // moles/cm^3 HM
     double atom_hm = mol_hm * at_mol;     // atoms/cm^3 HM
     double abcm_hm = atom_hm * cm2_barn;  // atoms/barn*cm HM
     double amt_hm = abcm_hm * vol;        // atoms*cm^2/barn HM
     // library variables
     std::string name0;
     int id0;
     get_name_id( 4, name0, id0 );
     Origen::SP_Material mat(
         new Origen::Material( "GENERAL", lib, name0, id0, vol ) );
     jDebugTaggedLine( "material library assoc finished..." );
     // BOS numden
     std::vector<int> id{92235, 92238};
     std::vector<double> num{0.1 * amt_hm, 0.9 * amt_hm};
     mat->set_amount_bos( num, id );
     jDebugTaggedLine( "set begin-of-step..." );
     // std::cout << mat->to_string() << std::endl;
     jDebugTaggedLine( "leaving setup_material2" );
     return mat;
 }
void build_simple_data1 (Origen::SP_Library lib, DataContainer & dc, Origen::SP_MaterialMap matmap)
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
References setup_material1().
Referenced by build_simple_data2().
 {
     dc.addDouble( "backgroundPower", 0.0 );
     dc.addDouble( "systemPower", 0.0 );
     dc.addBool( "depleteByPower", false );
     dc.addInt( "numSubsteps", 1 );
     // setup material 1
     matmap->add( setup_material1( lib ) );
     jDebugTaggedLine( "leaving build_simple_data1..." );
 }
void build_simple_data2 (Origen::SP_Library lib, DataContainer & dc, Origen::SP_MaterialMap matmap)
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
References build_simple_data1(), and setup_material2().
Referenced by MultiZoneDepleterTester::SetUp().
 {
     build_simple_data1( lib, dc, matmap );
     // setup material 2
     matmap->add( setup_material2( lib ) );
     jDebugTaggedLine( "leaving build_simple_data2..." );
 }
TEST_F (MultiZoneDepleterTester , DepleteByFlux)
References print.
 {
     if( !created ) return;
     // set data for this step
     mzd.add_step( 86400.0 * 10 );
     mzd.update( dc );
     mzd.set_substep_dtrel( Origen::Vec_Dbl( 10, 0.1 ) );
     // set data on materials
     mat4->set_transition_matrix( trx );
     mat4->set_flux( 1.0e14 );
     mat5->set_transition_matrix( trx );
     mat5->set_flux( 2.0e14 );
     // execute
     ASSERT_TRUE( mzd.execute() );
     // extract material map
     matmap = mzd.sp_materials();
     ASSERT_FALSE( matmap == nullptr );
     print();
 }
TEST_F (MultiZoneDepleterTester , DepleteByPower)
References print, and world.
 {
     if( !created ) return;
     double stepTime = 86400.0;         // 1 day
     double systemPower = 4400 + 2715;  // material1+material2 assuming ~40 W/g
     // each worker prints
     std::string filename = nprintf( "matmap_rank%02d.txt", world.rank() );
     std::ofstream ofs( filename );
     int nnodes = world.size();
     size_t nstep = 1;
     for( size_t step = 0; step < nstep; ++step )
     {
         // add a new step if beyond the first (added in testing class)
         mzd.add_step( stepTime );
         // Add new step data.
         mat4->set_transition_matrix( trx );
         mat4->set_flux( 3.0e-1 );
         mat5->set_transition_matrix( trx );
         mat5->set_flux( 6.0e-1 );
         // Update with new step data (don't really have to because we aren't
         // changing anything on the dc, but it's how this will be
         // executed in most cases.
         dc.addInt( "numSubsteps", 1 );
         dc.addBool( "depleteByPower", true );
         dc.addDouble( "systemPower", systemPower );  // Watts
         mzd.update( dc );
         mzd.set_constraint_its_max( 2 );
         // check instantaneous powers at bos (trel=0.0)
         EXPECT_NEAR( 5.29545e-12, 0.3 * mat4->power_factor_bos(), 1e-17 );
         EXPECT_NEAR( 1.65698e-10, 0.6 * mat5->power_factor_bos(), 1e-15 );
         // Solve the problem.
         mzd.execute();
         Origen::Vec_Dbl scaling = mzd.scaling_factors();
         ASSERT_EQ( nstep + 1, scaling.size() );
         EXPECT_NEAR( 4.16098e13, scaling[0], 1e8 );
         // Get status.
         const ScaleUtils::IO::DB& stat = mzd.status();
         // Output status to a file.
         ofs << mzd.status() << std::endl;
         // We are replicating materials on all nodes.
         // So with power held constant we can check the following:
         // - local power will scale down proportional to nodes
         EXPECT_FLOAT_EQ( systemPower / nnodes,
                          stat.get( "localMaterialTotalPower", -1.0 ) );
         // - local flux will scale down proportional to nodes
         EXPECT_FLOAT_EQ( 2.4277535e+13 / nnodes,
                          stat.get( "localMaterialAverageFlux", -1.0 ) );
         // - local volume will stay the same
         EXPECT_FLOAT_EQ( 19.5, stat.get( "localMaterialTotalVolume", -1.0 ) );
         // - material 4 will always have half the flux of material 5
         EXPECT_FLOAT_EQ( 0.5, mat4->flux() / mat5->flux() );
         // - global volume will scale up proportionally
         EXPECT_FLOAT_EQ( 19.5 * nnodes,
                          stat.get( "globalMaterialTotalVolume", -1.0 ) );
         // - global average flux will scale down proportionally
         EXPECT_FLOAT_EQ( 2.4277535e+13 / nnodes,
                          stat.get( "globalMaterialAverageFlux", -1.0 ) );
         // - global total power will be constant
         EXPECT_FLOAT_EQ( systemPower,
                          stat.get( "globalMaterialTotalPower", -1.0 ) );
     }
     // print of the whole map
     print( ofs );
 }
::std::ostream& operator<< (::std::ostream & os, const Stepper & s)
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
References Stepper::guess_dtrel_size(), Stepper::resp_its_max(), and Stepper::resp_its_tol().
 {
     return os << " tol=" << s.resp_its_tol() << " max=" << s.resp_its_max()
               << " dtrel.size()=" << s.guess_dtrel_size();
 }
::std::ostream& operator<< (::std::ostream & os, const SP_Stepper & s)
 {
     return os << *s;
 }
TEST_P (MultiZoneDepleterTesterP , PowerConstraint0)
 {
     if( !created ) return;
     // time steps
     Origen::Vec_Dbl sys_dt( 10, 86400. * 10 );  // 10 day periods
     // power over each step
     Origen::Vec_Dbl sys_p( 10, 7000 );
     {
         size_t c = 0;
         for( auto& p : sys_p )
         {
             p *= ( c + 10. ) / 10.;
             ++c;
         }
     }
     Vec_Dbl dtrel;
     for( size_t n = 0; n < sys_dt.size(); ++n )
     {
         // Allocate memory on all materials for new step.
         // Set global time step (all materials).
         mzd.add_step( sys_dt[n] );
         // Add new step data for each material.
         mat4->set_transition_matrix( trx );
         mat4->set_flux( 0.6 );
         mat5->set_transition_matrix( trx );
         mat5->set_flux( 0.4 );
         // Set global power constraint
         mzd.set_power_constraint( sys_p[n] );
         // Set substep parameters.  Eventually we want to move this into
         // MZD such that it has its own stepper.
         EXPECT_TRUE( stepper->guess_dtrel( &dtrel ) );
         mzd.set_substep_dtrel( dtrel );
         mzd.set_constraint_its_max( stepper->resp_its_max() );
         mzd.set_constraint_its_tol( stepper->resp_its_tol() );
         // Solve the problem.
         mzd.execute();
         // Get & check status.
         const ScaleUtils::IO::DB& stat = mzd.status();
         EXPECT_EQ( stepper->guess_dtrel_size(),
                    stat.get<int>( "numSubsteps" ) );
         EXPECT_EQ( true, stat.get<bool>( "hasConstraint" ) );
         EXPECT_EQ( mzd.dt(), stat.get<double>( "stepTime" ) );
         EXPECT_EQ( "POWER", stat.get<std::string>( "constraintType" ) );
         EXPECT_EQ( sys_p[n], stat.get<double>( "constraintValue" ) );
         EXPECT_EQ( stepper->resp_its_max(),
                    stat.get<int>( "constraintItsMax" ) );
         EXPECT_EQ( stepper->resp_its_tol(),
                    stat.get<double>( "constraintItsTol" ) );
         // check power constraint is met
         EXPECT_FLOAT_EQ( sys_p[n], matmap->power() );
     }
 }
const Vec_Dbl dtrel_1 ({1.0})
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
const Vec_Dbl dtrel_3 ({0.1, 0.2, 0.7})
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.
INSTANTIATE_TEST_CASE_P (StepperTesting , MultiZoneDepleterTesterP , ::testing:: ValuesInsteppers)
Variable Documentation
Standard::Communicator world
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp, Manager/mzd/tests/tstParallelDepletion.cpp, Solver/cram/tests/tstSolver_cram.cpp, and Solver/matrex/tests/tstSolver_matrex.cpp.
Referenced by get_name_id(), MultiZoneDepleterTester::SetUp(), TEST(), and TEST_F().
const std::vector<SP_Stepper> steppers
Initial value:
= {
    std::make_shared<Stepper_fixed>(
        dtrel_1, 1, 1e-5 ),
    std::make_shared<Stepper_fixed>(
        dtrel_1, 2, 1e-5 ),
    std::make_shared<Stepper_fixed>(
        dtrel_1,
        2,
        1e-2 ),
    std::make_shared<Stepper_fixed>(
        dtrel_3, 1, 1e-5 ),
    std::make_shared<Stepper_fixed>(
        dtrel_3, 2, 1e-5 ),
    std::make_shared<Stepper_fixed>(
        dtrel_3,
        20,
        1e-5 ),
}
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp.