ORIGEN API: Energy Struct Reference
Energy Struct Reference
#include <Energy.h>
Public Types
enum UNITS {
UNKNOWN = -1, JOULE, EV, KWH,
MWD, GWD, GWYR, END
}
Static Public Member Functions
template<Energy::UNITS u>
static std::string name ()
static std::string name (Energy::UNITS u)
template<Energy::UNITS u>
static double base ()
static double base (Energy::UNITS u)
template<Energy::UNITS to, Energy::UNITS from>
static double factor ()
template<Energy::UNITS to>
static double factor (Energy::UNITS from)
static double factor (Energy::UNITS to, Energy::UNITS from)
static Energy::UNITS units (const char *s)
static constexpr Energy::UNITS units (int i)
Static Public Attributes
static const UNITS DEFAULT = JOULE
Detailed Description
Examples:
Core/dc/tests/tstEnergy.cpp.
Member Enumeration Documentation
enum UNITS
Enumerator
UNKNOWN
JOULE
EV
KWH
MWD
GWD
GWYR
END
     {
         UNKNOWN = -1,
         JOULE,
         EV,
         KWH,
         MWD,
         GWD,
         GWYR,
         END
     };
Member Function Documentation
static std::string name () static
std::string name (Energy::UNITS u) inline static
References Energy::EV, Energy::GWD, Energy::GWYR, Energy::JOULE, Energy::KWH, and Energy::MWD.
 {
     if( u == JOULE ) return name<JOULE>();
     if( u == EV ) return name<EV>();
     if( u == KWH ) return name<KWH>();
     if( u == MWD ) return name<MWD>();
     if( u == GWD ) return name<GWD>();
     if( u == GWYR ) return name<GWYR>();
     return "";
 }
static double base () static
Examples:
Core/dc/tests/tstEnergy.cpp.
Referenced by Energy::factor(), and TEST().
double base (Energy::UNITS u) inline static
References Energy::EV, Energy::GWD, Energy::GWYR, Energy::JOULE, Energy::KWH, and Energy::MWD.
 {
     if( u == JOULE ) return base<JOULE>();
     if( u == EV ) return base<EV>();
     if( u == KWH ) return base<KWH>();
     if( u == MWD ) return base<MWD>();
     if( u == GWD ) return base<GWD>();
     if( u == GWYR ) return base<GWYR>();
     return 0.0;
 }
double factor () inline static
 {
     return base<from>() / base<to>();
 }
double factor (Energy::UNITS from) inline static
References Energy::base().
 {
     return base( from ) / base<to>();
 }
double factor (Energy::UNITS to, Energy::UNITS from) inline static
References Energy::base().
 {
     return base( from ) / base( to );
 }
Energy::UNITS units (const char * s) inline static
References Energy::EV, Energy::GWD, Energy::GWYR, Energy::JOULE, Energy::KWH, Energy::MWD, and Energy::UNKNOWN.
 {
     if( s == name<JOULE>() ) return JOULE;
     if( s == name<EV>() ) return EV;
     if( s == name<KWH>() ) return KWH;
     if( s == name<MWD>() ) return MWD;
     if( s == name<GWD>() ) return GWD;
     if( s == name<GWYR>() ) return GWYR;
     return UNKNOWN;
 }
constexpr Energy::UNITS units (int i) inline static
 {
     return static_cast<Energy::UNITS>( i );
 }
Member Data Documentation
const UNITS DEFAULT = JOULE static
The documentation for this struct was generated from the following files:
Core/dc/Energy.h
Core/dc/Energy.i.h