ORIGEN API: Tester/tests/burstFission.cpp File Reference
burstFission.cpp File Reference
#include <cstring>
#include <sstream>
#include "Nemesis/gtest/gtest.h"
#include "Origen/Core/Definitions.h"
#include "Origen/Core/TestPaths.h"
#include "Origen/Core/dc/Material.h"
#include "Origen/Core/fn/diff.h"
#include "Origen/Core/io/StateSetIO.h"
#include "Origen/Core/io/YieldResourceIO.h"
#include "Origen/Manager/libld/TransitionMatrixUpdater.h"
#include "Origen/Solver/cram/Solver_cram.h"
#include "Origen/Solver/matrex/Solver_matrex.h"
#include "ScaleData/Core/Utils.h"
#include "Standard/Interface/CommandLine.h"
#include "Standard/Interface/Communicator.h"
#include "Standard/Interface/CommunicatorEnvironment.h"
#include "../test_utils.hh"
Classes
class yields_compare
class ft71_compare
Macros
#define EXPECT_NO_DIFF(CALL)
Functions
TEST_P (yields_compare, DISABLED_nuclide)
TEST_P (ft71_compare, DISABLED_nuclide)
INSTANTIATE_TEST_CASE_P (BurstFission, yields_compare,::testing::ValuesIn(fissionable_nuclides))
INSTANTIATE_TEST_CASE_P (BurstFission, ft71_compare,::testing::Values(std::string("u235")))
int main (int argc, char *argv[])
Variables
Standard::SP_CommandLine cmdLine = 0
burstFission test
std::vector< std::string > fissionable_nuclides
Macro Definition Documentation
#define EXPECT_NO_DIFF (CALL)
Value:
{                                          \
        std::string result = CALL;             \
        EXPECT_TRUE( result == "" ) << result; \
    }
Referenced by TEST_P().
Function Documentation
TEST_P (yields_compare , DISABLED_nuclide)
References Origen::diffConcentrations(), EXPECT_NO_DIFF, TransitionMatrixUpdater::get_errors(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), Concentrations::set_concs(), NuclideSet::set_ids(), dataTests::set_materials_given_id(), TransitionMatrixUpdater::sp_library(), and TransitionMatrixUpdater::update_mg_flux().
 {
     std::cout << "Yields A: " << yields_a << std::endl;
     std::cout << "Yields B: " << yields_b << std::endl;
     // Create two Origen libraries, one for each yields data file.
     Origen::TransitionMatrixUpdater tmu_a;
     tmu_a.load( Origen::pwrlib_filepath, Origen::jeff238_filepath, yields_a );
     Origen::SP_Library lib_a = tmu_a.sp_library();
     Origen::Vec_Str errors;
     tmu_a.get_errors( &errors );
     for( auto s : errors ) std::cout << s << std::endl;
     EXPECT_EQ( 0, errors.size() );
     ASSERT_TRUE( tmu_a.initialized() );
     Origen::TransitionMatrixUpdater tmu_b;
     tmu_b.load( Origen::pwrlib_filepath, Origen::jeff238_filepath, yields_b );
     Origen::SP_Library lib_b = tmu_b.sp_library();
     tmu_b.get_errors( &errors );
     for( auto s : errors ) std::cout << s << std::endl;
     EXPECT_EQ( 0, errors.size() );
     ASSERT_TRUE( tmu_b.initialized() );
     // Set the flux weight spectrum:
     Origen::Vec_Flt mg_flux( 238, 0.0 );
     mg_flux[13] = 1.25;
     mg_flux[14] = 0.3;
     tmu_a.update_mg_flux( mg_flux );
     tmu_b.update_mg_flux( mg_flux );
     std::shared_ptr<Origen::TrMatrix> tm_a( new Origen::TrMatrix );
     tmu_a.get_transition_matrix( &*tm_a );
     std::shared_ptr<Origen::TrMatrix> tm_b( new Origen::TrMatrix );
     tmu_b.get_transition_matrix( &*tm_b );
     // Create two materials (one for each library) that has 1 gram of whatever
     // fissionable material this test has been parameterized to run.
     Origen::SP_Material mat_a =
         dataTests::set_materials_given_id( lib_a, std::string( GetParam() ) );
     Origen::SP_Material mat_b =
         dataTests::set_materials_given_id( lib_b, std::string( GetParam() ) );
     std::vector<double> time{
         0.0,  1e-3, 1,    1.5,  2,   4,     6,   8,   10,  15,   20,
         40,   60,   80,   100,  150, 200,   400, 600, 800, 1000, 1500,
         2000, 4000, 6000, 8000, 1e4, 1.5e4, 2e4, 4e4, 6e4, 8e4,  1e5};
     std::vector<double> flux{3.08617e5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0,         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0,         0, 0, 0, 0, 0, 0, 0, 0, 0};
     size_t nsteps = flux.size();
     // Solve for material A:
     for( size_t j = 0; j < nsteps; ++j )
     {
         // Add a new time step to this material.
         double dt = time[j + 1] - time[j];
         //~ mat->add_step(flux[j],tm,dt);
         mat_a->add_step( dt );
         mat_a->set_flux( flux[j] );
         mat_a->set_transition_matrix( tm_a );
         // Solve the step using only data on the material, solve takes
         // the bos vector, time, flux, and pointer to eos.
         Origen::SP_Vec_Dbl n0 = mat_a->amount_bos();
         Origen::SP_Vec_Dbl n1 = mat_a->amount_eos();
         slv->set_transition_matrix( &*mat_a->transition_matrix() );
         slv->solve( *n0, mat_a->flux(), mat_a->dt(), &*n1 );
         slv->clear();
     }
     // Solve for material B:
     for( size_t j = 0; j < nsteps; ++j )
     {
         // Add a new time step to this material.
         double dt = time[j + 1] - time[j];
         //~ mat->add_step(flux[j],tm,dt);
         mat_b->add_step( dt );
         mat_b->set_flux( flux[j] );
         mat_b->set_transition_matrix( tm_b );
         // Solve the step using only data on the material, solve takes
         // the bos vector, time, flux, and pointer to eos.
         Origen::SP_Vec_Dbl n0 = mat_b->amount_bos();
         Origen::SP_Vec_Dbl n1 = mat_b->amount_eos();
         slv->set_transition_matrix( &*mat_b->transition_matrix() );
         slv->solve( *n0, mat_b->flux(), mat_b->dt(), &*n1 );
         slv->clear();
     }
     // Get nuclides off Library:
     Origen::SCP_Vec_Int nuclides_a = mat_a->sizzzaaa_list();
     Origen::SCP_Vec_Int nuclides_b = mat_b->sizzzaaa_list();
     for( size_t i = 0; i < mat_a->ntimes(); i++ )
     {
         std::cout << "Time Step[" << i << "]: " << mat_a->time_at( i )
                   << std::endl;
         // Use float even though double because ft71 stores as float
         // Yield A Gets
         // Get data (concs) from material (this solve):
         Origen::SP_DoubleList vals_a = mat_a->amount_at( i );
         // Create NuclideSet:
         Origen::NuclideSet nuc_set_a;
         nuc_set_a.set_ids( *nuclides_a );
         // Convert to Vector:
         Origen::Vec_Dbl vals_vec_a;
         for( size_t j = 0; j < vals_a->size(); j++ )
         {
             vals_vec_a.push_back( vals_a->at( j ) );
         }
         // Create a concentrations object
         Origen::Concentrations concs_a( nuc_set_a );
         concs_a.set_concs( *nuclides_a, vals_vec_a );
         // Yield B Gets
         // Get data (concs) from material (this solve):
         Origen::SP_DoubleList vals_b = mat_b->amount_at( i );
         // Create NuclideSet:
         Origen::NuclideSet nuc_set_b;
         nuc_set_b.set_ids( *nuclides_b );
         // Convert to Vector:
         Origen::Vec_Dbl vals_vec_b;
         for( int i = 0; i < vals_b->size(); i++ )
         {
             vals_vec_b.push_back( vals_b->at( i ) );
         }
         // Create a concentrations object
         Origen::Concentrations concs_b( nuc_set_b );
         concs_b.set_concs( *nuclides_b, vals_vec_b );
         // COMPARISONS
         EXPECT_NO_DIFF( diffConcentrations( concs_a, concs_b ) );
     }
 }
TEST_P (ft71_compare , DISABLED_nuclide)
References Origen::diffConcentrations(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::load(), Origen::loadStateSet(), Concentrations::set_concs(), NuclideSet::set_ids(), dataTests::set_materials_using_f71_file(), Concentrations::set_units(), TransitionMatrixUpdater::sp_library(), Concentrations::units(), and TransitionMatrixUpdater::update_mg_flux().
 {
     // Read in the "blessed" or baseline ft71 file for comparison:
     ScaleUtils::IO::DB opts;
     std::string ft71_name( "../baseline/burstFission." +
                            std::string( GetParam() ) + ".f71" );
     Origen::SP_StateSet ft71_data =
         Origen::SP_StateSet( Origen::loadStateSet( ft71_name, opts ) );
     // Get a general 2237-nuclide ORIGEN library:
     Origen::TransitionMatrixUpdater tmu;
     tmu.load( Origen::pwrlib_filepath,
               Origen::jeff238_filepath,
               Origen::yields_filepath );
     Origen::SP_Library lib = tmu.sp_library();
     // Set the flux weight spectrum:
     Origen::Vec_Flt mg_flux( 238, 0.0 );
     mg_flux[13] = 1.25;
     mg_flux[14] = 0.3;
     tmu.update_mg_flux( mg_flux );
     std::shared_ptr<Origen::TrMatrix> tm( new Origen::TrMatrix );
     tmu.get_transition_matrix( &*tm );
     // Create a material that has the same comp as the FT71 file to start
     Origen::SP_Material mat =
         dataTests::set_materials_using_f71_file( ft71_data, lib );
     std::vector<double> time{
         0.0,  1e-3, 1,    1.5,  2,   4,     6,   8,   10,  15,   20,
         40,   60,   80,   100,  150, 200,   400, 600, 800, 1000, 1500,
         2000, 4000, 6000, 8000, 1e4, 1.5e4, 2e4, 4e4, 6e4, 8e4,  1e5};
     std::vector<double> flux{3.08617e5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0,         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0,         0, 0, 0, 0, 0, 0, 0, 0, 0};
     size_t nsteps = flux.size();
     // Enter step loop.
     for( size_t j = 0; j < nsteps; ++j )
     {
         // Add a new time step to this material.
         double dt = time[j + 1] - time[j];
         //~ mat->add_step(flux[j],tm,dt);
         mat->add_step( dt );
         mat->set_flux( flux[j] );
         mat->set_transition_matrix( tm );
         // Solve the step using only data on the material, solve takes
         // the bos vector, time, flux, and pointer to eos.
         Origen::SP_Vec_Dbl n0 = mat->amount_bos();
         Origen::SP_Vec_Dbl n1 = mat->amount_eos();
         slv->set_transition_matrix( &*mat->transition_matrix() );
         slv->solve( *n0, mat->flux(), mat->dt(), &*n1 );
         slv->clear();
     }
     // Tests:
     // Check that number of times is the same:
     ASSERT_EQ( mat->ntimes(), ft71_data->states_size() );
     // Get nuclides off Library:
     Origen::SCP_Vec_Int nuclides = mat->sizzzaaa_list();
     // Check data:
     Origen::Vec_Dbl ft71_times = ft71_data->times();
     for( size_t i = 0; i < mat->ntimes(); i++ )
     {
         std::cout << "Time Step[" << i << "]: " << ft71_times.at( i )
                   << std::endl;
         // Use float even though double because ft71 stores as float
         ASSERT_FLOAT_EQ( mat->time_at( i ), ft71_times.at( i ) );
         // FT71 DATA GETS
         // Get list of nuclides that were on the ft71 file:
         const Origen::State& state = ft71_data->states_at( i );
         const Origen::Concentrations& concs = state.concs();
         // Units of concs:
         Origen::ConcentrationUnit ft71_units = concs.units();
         // TEST API DATA GETS
         // Get data (concs) from material (this solve):
         Origen::SP_DoubleList test_vals = mat->amount_at( i );
         // Create NuclideSet:
         Origen::NuclideSet test_nuc_set;
         test_nuc_set.set_ids( *nuclides );
         // Convert to Vector:
         Origen::Vec_Dbl test_vals_vec;
         for( int i = 0; i < test_vals->size(); i++ )
         {
             test_vals_vec.push_back( test_vals->at( i ) );
         }
         // Create a concentrations object for test data
         Origen::Concentrations test_concs( test_nuc_set );
         test_concs.set_units( ft71_units );
         test_concs.set_concs( *nuclides, test_vals_vec );
         // COMPARISONS
         EXPECT_EQ( "", diffConcentrations( concs, test_concs ) );
     }
 }
INSTANTIATE_TEST_CASE_P (BurstFission , yields_compare , ::testing:: ValuesInfissionable_nuclides)
INSTANTIATE_TEST_CASE_P (BurstFission , ft71_compare , ::testing:: Valuesstd::string("u235"))
int main (int argc, char * argv[])
References cmdLine, YieldResource::get_fissionable_ids(), and Origen::loadYieldResource().
 {
     // initialize MPI since a downstream package needs
     Standard::CommunicatorEnvironment env(argc, argv);
    Standard::Communicator World;
    if ( World.rank() != 0 ) return 0;
     // Get a list of fissionable nuclides.
     ScaleUtils::IO::DB opts;
     Origen::YieldResource* yield_resource =
         Origen::loadYieldResource( Origen::yields_filepath, opts );
     Origen::Vec_Int fis_ids;
     yield_resource->get_fissionable_ids( &fis_ids );
     fis_ids = {92235};
     for( auto id : fis_ids )
     {
         std::string id_str = ScaleData::Utils::pizzzaaa_to_symbol( id );
         fissionable_nuclides.push_back( id_str );
     }
     ::testing::InitGoogleTest( &argc, argv );
     cmdLine =
         Standard::SP_CommandLine( new Standard::CommandLine( argc, argv ) );
     int success = RUN_ALL_TESTS();
     delete yield_resource;
     return success;
 }
Variable Documentation
Standard::SP_CommandLine cmdLine = 0
burstFission test
Author
Shane Hart
A unit test that tests the ORIGEN solvers for a flash fission event. Material is only U-235 and the flux spectrum is only in groups 14 and 15 of a 238 MG library. Number density is calculated from 1 gram of U-235. Both Matrex and CRAM solvers are used.
Referenced by main(), and yields_compare::yields_compare().
std::vector<std::string> fissionable_nuclides