ORIGEN API: ProtonField Class Reference
ProtonField Class Reference
#include <Field_FunPart.h>
fundamental particle field class: proton field
Public Types
typedef SP_Field SP
strong pointer
typedef WP_Field WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Field>>
See Origen::Field for details.
double intensity () const
void get_intensity (double &intensity) const
void set_intensity (double intensity)
bool has_initialized_intensity () const
SP_Species species () const
void get_species (SP_Species &species) const
void set_species (SP_Species species)
bool has_initialized_species () const
Public Member Functions
ProtonField ()
Private Member Functions
std::string name_impl () const
int id_impl () const
Detailed Description
fundamental particle field class: proton field
See also
Origen::Field_Gen
Member Typedef Documentation
typedef SP_Field SP inherited
strong pointer
typedef WP_Field WP inherited
weak pointer
Constructor & Destructor Documentation
ProtonField ()
References Field::set_species().
 { set_species( SP_Species( new Proton() ) ); }
Member Function Documentation
std::string name_impl () const private virtual
Reimplemented from Field.
 { return "PROTON_FIELD"; }
int id_impl () const private virtual
Reimplemented from Field.
References Origen::PROTON_FIELD.
 { return PROTON_FIELD; }
double intensity () const inherited
Referenced by Field_Gen::set_intensity_impl().
 { return intensity_impl(); }
void get_intensity (double & intensity) const inherited
 {
     get_intensity_impl( intensity );
 }
void set_intensity (double intensity) inherited
Referenced by NullField::NullField().
 {
     set_intensity_impl( intensity );
 }
bool has_initialized_intensity () const inherited
 {
     return has_initialized_intensity_impl();
 }
SP_Species species () const inherited
Referenced by Field_Gen::set_species_impl().
 { return species_impl(); }
void get_species (SP_Species & species) const inherited
 {
     get_species_impl( species );
 }
void set_species (SP_Species species) inherited
Referenced by AlphaField::AlphaField(), DeuteronField::DeuteronField(), ElectronField::ElectronField(), HelionField::HelionField(), NeutrinoField::NeutrinoField(), NeutronField::NeutronField(), NullField::NullField(), PositronField::PositronField(), ProtonField::ProtonField(), and TritonField::TritonField().
 { set_species_impl( species ); }
bool has_initialized_species () const inherited
 {
     return has_initialized_species_impl();
 }
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Field_FunPart.h
Core/ts/Field_FunPart.cpp