OrigenAPI: MultiZoneDepleterTester Class Reference
MultiZoneDepleterTester Class Reference
Protected Member Functions
void SetUp ()
void WrapUp ()
void print (std::ostream &os=std::cout)
Protected Attributes
Origen::SP_TransitionMatrixP trx
Origen::SP_Library lib
DataContainer dc
Origen::MultiZoneDepleter mzd
Origen::SP_MaterialMap matmap
Origen::SP_Material mat4
Origen::SP_Material mat5
Standard::SP_Communicator comm
bool created
Detailed Description
Definition at line 157 of file tstMultiZoneDepleter.cpp.
Member Function Documentation
void MultiZoneDepleterTester::print (std::ostream & os = std::cout) inline protected
Definition at line 225 of file tstMultiZoneDepleter.cpp.
     {
         os << matmap->to_string() << std::endl;
     }
void MultiZoneDepleterTester::SetUp () inline protected
Definition at line 171 of file tstMultiZoneDepleter.cpp.
References build_simple_data2(), get_name_id(), Origen::FakeFactory::Library_scale_pwr(), Origen::MultiZoneDepleter::set_comm(), Origen::MultiZoneDepleter::set_materials(), Origen::MultiZoneDepleter::set_solver(), and world.
Referenced by MultiZoneDepleterTesterP::SetUp().
     {
         // other stuff
         matmap = Origen::SP_MaterialMap( new Origen::MaterialMap() );
         // get a library
         lib = std::make_shared<Origen::Library>();
         created = Origen::FakeFactory::Library_scale_pwr( *lib );
         trx = lib->newsp_transition_matrix_at( 0 );
         // set solver
         Origen::SP_Solver fake( new Origen::Solver_Fake() );
         mzd.set_solver( fake );
         // create a dc and matmap
         build_simple_data2( lib, dc, matmap );
         // comm = world.split(0); //make a comm with ALL processes
         // mzd.set_comm(comm);
         mzd.set_comm( &world );
         // associate materials
         ASSERT_FALSE( matmap == nullptr );
         mzd.set_materials( matmap );
         // make sure we have mass
         ASSERT_LT( 0.0, matmap->initial_mass() );
         ASSERT_LT( 0.0, matmap->initial_hm_mass() );
         // std::cout << matmap->to_string() << std::endl;
         std::string name0;
         int id0;
         get_name_id( 4, name0, id0 );
         mat4 = matmap->get( id0 );
         ASSERT_EQ( mat4->name(), name0 );
         nemesis::log_local() << name0 << endl;
         get_name_id( 5, name0, id0 );
         mat5 = matmap->get( id0 );
         ASSERT_EQ( mat5->name(), name0 );
         ASSERT_TRUE( mat4 != nullptr );
         ASSERT_TRUE( mat5 != nullptr );
         jDebugTaggedLine( "finished SetUp" );
     }
void MultiZoneDepleterTester::WrapUp () inline protected
Definition at line 219 of file tstMultiZoneDepleter.cpp.
     {
         dc.deepDelete();
         jDebugTaggedLine( "finished WrapUp" );
     }
Member Data Documentation
Standard::SP_Communicator MultiZoneDepleterTester::comm protected
Definition at line 167 of file tstMultiZoneDepleter.cpp.
bool MultiZoneDepleterTester::created protected
Definition at line 169 of file tstMultiZoneDepleter.cpp.
DataContainer MultiZoneDepleterTester::dc protected
Definition at line 163 of file tstMultiZoneDepleter.cpp.
Origen::SP_Library MultiZoneDepleterTester::lib protected
Definition at line 162 of file tstMultiZoneDepleter.cpp.
Origen::SP_Material MultiZoneDepleterTester::mat4 protected
Definition at line 166 of file tstMultiZoneDepleter.cpp.
Origen::SP_Material MultiZoneDepleterTester::mat5 protected
Definition at line 166 of file tstMultiZoneDepleter.cpp.
Origen::SP_MaterialMap MultiZoneDepleterTester::matmap protected
Definition at line 165 of file tstMultiZoneDepleter.cpp.
Referenced by MultiZoneDepleterTesterP::SetUp().
Origen::MultiZoneDepleter MultiZoneDepleterTester::mzd protected
Definition at line 164 of file tstMultiZoneDepleter.cpp.
Origen::SP_TransitionMatrixP MultiZoneDepleterTester::trx protected
Definition at line 161 of file tstMultiZoneDepleter.cpp.
The documentation for this class was generated from the following file:
Core/xf/tests/tstMultiZoneDepleter.cpp