ORIGEN API: Channel_Gen Class Reference
Channel_Gen Class Reference
#include <Channel_Gen.h>
General-purpose implementation of the Channel interface.
Public Types
typedef SP_Channel SP
strong pointer
typedef WP_Channel WP
weak pointer
typedef CWP_Channel CWP
const weak pointer
INTERFACE<<Origen::Channel>>
See Origen::Channel for details.
int num_transitions () const
SP_Transition transition (int transition_id) const
void get_transition (int transition_id, SP_Transition &transition) const
void set_transition (SP_Transition transition)
SP_Transition add_transition (int transition_id)
SP_Transition add_transition (int transition_id, double yield)
std::vector< SP_Transition > transitions () const
void get_transitions (std::vector< SP_Transition > &transitions) const
void set_transitions (std::vector< SP_Transition > transitions)
std::vector< SP_Transition > byproduct_transitions () const
void get_byproduct_transitions (std::vector< SP_Transition > &transitions) const
void update_byproduct_transitions ()
SP_ChannelType channel_type () const
void get_channel_type (SP_ChannelType &channel_type) const
void set_channel_type (SP_ChannelType channel_type)
bool has_initialized_channel_type () const
double decay_constant () const
Channel & set_decay_constant (double decay_constant)
bool has_initialized_decay_constant () const
double xs () const
Channel & set_xs (double xs)
bool has_initialized_xs () const
CWP_Nuclide parent () const
void get_parent (WP_Nuclide &parent) const
void set_parent (WP_Nuclide parent)
bool has_initialized_parent () const
int daughter_mass_number () const
int daughter_charge_number () const
double coeff () const
double rate () const
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
Public Member Functions
Channel_Gen ()
Channel_Gen (ChannelType::SP channel_type)
virtual ~Channel_Gen ()
Private Types
typedef std::map< int, SP_Transition > TransitionRegistry
typedef std::vector< SP_Transition > TransitionList
Private Member Functions
virtual int num_transitions_impl () const
virtual SP_Transition transition_impl (int transition_id) const
virtual void get_transition_impl (int transition_id, SP_Transition &transition) const
virtual void set_transition_impl (SP_Transition transition)
virtual CWP_Nuclide parent_impl () const
virtual void get_parent_impl (WP_Nuclide &parent) const
virtual void set_parent_impl (WP_Nuclide parent)
virtual double coeff_impl () const
virtual double rate_impl () const
virtual ChannelType::SP channel_type_impl () const
virtual void get_channel_type_impl (ChannelType::SP &channel_type) const
virtual void set_channel_type_impl (ChannelType::SP channel_type)
virtual double decay_constant_impl () const
virtual void set_decay_constant_impl (double decay_constant)
virtual double xs_impl () const
virtual void set_xs_impl (double xs)
virtual std::vector< SP_Transition > byproduct_transitions_impl () const
virtual void get_byproduct_transitions_impl (std::vector< SP_Transition > &transitions) const
virtual void update_byproduct_transitions_impl ()
virtual std::vector< SP_Transition > transitions_impl () const
virtual void get_transitions_impl (std::vector< SP_Transition > &transitions) const
virtual void set_transitions_impl (std::vector< SP_Transition > transitions)
virtual SP_Transition add_transition_impl (int transition_id)
virtual SP_Transition add_transition_impl (int transition_id, double yield)
TransitionRegistry::const_iterator search_for_transition_index (int transition_id) const
Private Attributes
ChannelType::SP b_channel_type
double b_xs
double b_decay_constant
Nuclide::WP b_parent
TransitionRegistry b_transition_list
TransitionList b_byproduct_transition_list
Detailed Description
General-purpose implementation of the Channel interface.
See also
Origen::Channel_Gen
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef std::map<int, SP_Transition> TransitionRegistry private
typedef std::vector<SP_Transition> TransitionList private
typedef SP_Channel SP inherited
strong pointer
typedef WP_Channel WP inherited
weak pointer
typedef CWP_Channel CWP inherited
const weak pointer
Constructor & Destructor Documentation
Channel_Gen ()
Channel_Gen (ChannelType::SP channel_type)
References Channel::set_channel_type().
~Channel_Gen () virtual
References Channel_Gen::b_transition_list.
Member Function Documentation
int num_transitions_impl () const private virtual
Implements Channel.
References Channel_Gen::b_transition_list.
Transition::SP transition_impl (int transition_id) const private virtual
Implements Channel.
References Channel_Gen::b_transition_list.
void get_transition_impl (int transition_id, SP_Transition & transition) const private virtual
Implements Channel.
References Channel::transition().
void set_transition_impl (SP_Transition transition) private virtual
Implements Channel.
References Channel_Gen::b_transition_list, Checkable::id(), and Channel::transition().
CWP_Nuclide parent_impl () const private virtual
Implements Channel.
References Channel_Gen::b_parent.
void get_parent_impl (WP_Nuclide & parent) const private virtual
Implements Channel.
References Channel_Gen::b_parent.
void set_parent_impl (WP_Nuclide parent) private virtual
Implements Channel.
References Channel_Gen::b_parent, Channel::parent(), and Channel::update_byproduct_transitions().
double coeff_impl () const inline private virtual
Implements Channel.
References Channel::channel_type(), Channel::decay_constant(), Channel::has_initialized_channel_type(), and Channel::xs().
double rate_impl () const private virtual
Implements Channel.
References Origen::BAD_DOUBLE, Channel::coeff(), Channel::has_initialized_parent(), Nuclide::num(), and Channel::parent().
ChannelType::SP channel_type_impl () const private virtual
Implements Channel.
References Channel_Gen::b_channel_type.
void get_channel_type_impl (ChannelType::SP & channel_type) const private virtual
Implements Channel.
References Channel_Gen::b_channel_type.
void set_channel_type_impl (ChannelType::SP channel_type) private virtual
Implements Channel.
References Channel_Gen::b_channel_type, Channel::channel_type(), and Channel::update_byproduct_transitions().
double decay_constant_impl () const private virtual
Implements Channel.
References Channel_Gen::b_decay_constant.
void set_decay_constant_impl (double decay_constant) private virtual
Implements Channel.
References Channel_Gen::b_decay_constant, and Channel::decay_constant().
double xs_impl () const private virtual
Implements Channel.
References Channel_Gen::b_xs.
void set_xs_impl (double xs) private virtual
Implements Channel.
References Channel_Gen::b_xs, and Channel::xs().
Channel_Gen::TransitionList byproduct_transitions_impl () const private virtual
Implements Channel.
References Channel_Gen::b_byproduct_transition_list.
void get_byproduct_transitions_impl (std::vector< SP_Transition > & transitions) const private virtual
Implements Channel.
References Channel_Gen::b_byproduct_transition_list.
void update_byproduct_transitions_impl () private virtual
Implements Channel.
References TransitionSystem::add_byproduct(), Channel_Gen::b_byproduct_transition_list, Channel::channel_type(), Nuclide::get_system(), Channel::has_initialized_channel_type(), Channel::has_initialized_parent(), Channel::parent(), and Channel::transition().
std::vector< Transition::SP > transitions_impl () const private virtual
Implements Channel.
References Channel_Gen::b_transition_list.
void get_transitions_impl (std::vector< SP_Transition > & transitions) const private virtual
Implements Channel.
References Channel_Gen::b_transition_list.
void set_transitions_impl (std::vector< SP_Transition > transitions) private virtual
Implements Channel.
References Channel_Gen::b_transition_list, and Checkable::has_initialized_id().
Transition::SP add_transition_impl (int transition_id) private virtual
Implements Channel.
References Channel_Gen::b_transition_list, Channel::channel_type(), Channel::daughter_charge_number(), Channel::daughter_mass_number(), Channel::get_parent(), Nuclide::get_system(), Channel::has_initialized_parent(), Nuclide::has_initialized_system(), Checkable::id(), Channel::parent(), and Channel::transition().
Transition::SP add_transition_impl (int transition_id, double yield) private virtual
Implements Channel.
References Channel::add_transition(), and Channel::transition().
TransitionRegistry::const_iterator search_for_transition_index (int transition_id) const private
int num_transitions () const inherited
SP_Transition transition (int transition_id) const inherited
Referenced by Channel_Gen::add_transition_impl(), LibraryBuilder::create_reaction_transitions(), Channel_Gen::get_transition_impl(), Channel_Gen::set_transition_impl(), and Channel_Gen::update_byproduct_transitions_impl().
void get_transition (int transition_id, SP_Transition & transition) const inherited
void set_transition (SP_Transition transition) inherited
Transition::SP add_transition (int transition_id) inherited
Referenced by Channel_Gen::add_transition_impl().
Transition::SP add_transition (int transition_id, double yield) inherited
std::vector< SP_Transition > transitions () const inherited
void get_transitions (std::vector< SP_Transition > & transitions) const inherited
void set_transitions (std::vector< SP_Transition > transitions) inherited
std::vector< SP_Transition > byproduct_transitions () const inherited
void get_byproduct_transitions (std::vector< SP_Transition > & transitions) const inherited
void update_byproduct_transitions () inherited
Referenced by Channel_Gen::set_channel_type_impl(), and Channel_Gen::set_parent_impl().
SP_ChannelType channel_type () const inherited
Referenced by Channel_Gen::add_transition_impl(), Channel_Gen::coeff_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Channel_Gen::set_channel_type_impl(), and Channel_Gen::update_byproduct_transitions_impl().
void get_channel_type (SP_ChannelType & channel_type) const inherited
void set_channel_type (SP_ChannelType channel_type) inherited
Referenced by Channel_Gen::Channel_Gen().
bool has_initialized_channel_type () const inherited
Referenced by Channel_Gen::coeff_impl(), and Channel_Gen::update_byproduct_transitions_impl().
double decay_constant () const inherited
Referenced by Channel_Gen::coeff_impl(), and Channel_Gen::set_decay_constant_impl().
Channel & set_decay_constant (double decay_constant) inherited
bool has_initialized_decay_constant () const inherited
double xs () const inherited
Referenced by Channel_Gen::coeff_impl(), and Channel_Gen::set_xs_impl().
Channel & set_xs (double xs) inherited
bool has_initialized_xs () const inherited
CWP_Nuclide parent () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Channel_Gen::add_transition_impl(), Nuclide_Gen::append_gain_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), Channel_Gen::rate_impl(), Channel_Gen::set_parent_impl(), TEST_F(), and Channel_Gen::update_byproduct_transitions_impl().
void get_parent (WP_Nuclide & parent) const inherited
Referenced by Channel_Gen::add_transition_impl().
void set_parent (WP_Nuclide parent) inherited
bool has_initialized_parent () const inherited
Referenced by Channel_Gen::add_transition_impl(), Channel_Gen::rate_impl(), and Channel_Gen::update_byproduct_transitions_impl().
int daughter_mass_number () const inherited
Referenced by Channel_Gen::add_transition_impl().
int daughter_charge_number () const inherited
Referenced by Channel_Gen::add_transition_impl().
double coeff () const inherited
Referenced by Channel_Gen::rate_impl().
double rate () const inherited
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
ChannelType::SP b_channel_type private
Referenced by Channel_Gen::channel_type_impl(), Channel_Gen::get_channel_type_impl(), and Channel_Gen::set_channel_type_impl().
double b_xs private
Referenced by Channel_Gen::set_xs_impl(), and Channel_Gen::xs_impl().
double b_decay_constant private
Referenced by Channel_Gen::decay_constant_impl(), and Channel_Gen::set_decay_constant_impl().
Nuclide::WP b_parent private
Referenced by Channel_Gen::get_parent_impl(), Channel_Gen::parent_impl(), and Channel_Gen::set_parent_impl().
TransitionRegistry b_transition_list private
Referenced by Channel_Gen::add_transition_impl(), Channel_Gen::get_transitions_impl(), Channel_Gen::num_transitions_impl(), Channel_Gen::set_transition_impl(), Channel_Gen::set_transitions_impl(), Channel_Gen::transition_impl(), Channel_Gen::transitions_impl(), and Channel_Gen::~Channel_Gen().
TransitionList b_byproduct_transition_list private
Referenced by Channel_Gen::byproduct_transitions_impl(), Channel_Gen::get_byproduct_transitions_impl(), and Channel_Gen::update_byproduct_transitions_impl().
The documentation for this class was generated from the following files:
Core/ts/Channel_Gen.h
Core/ts/Channel_Gen.cpp