ORIGEN API: Core/ut/endf_yield_reformatter.f90 File Reference
endf_yield_reformatter.f90 File Reference
Data Types
type fpytype
Functions/Subroutines
program main
subroutine rdfpyield
subroutine outfpyield (title)
character(11) function f2s (f1)
subroutine write_2float_4int (unit, f1, f2, i1, i2, i3, i4)
subroutine write_6float (unit, f1, f2, f3, f4, f5, f6)
Function/Subroutine Documentation
program main ()
subroutine main::rdfpyield ()
 !     --------------------------------------------------------------------------------
 !     Function   : Read fission product yields from endf/b f.p. yield data
 !     --------------------------------------------------------------------------------
 !
       integer :: i,ix,nid,j,k,k1,k2,ntot1,ntot2,iso
       real :: xval1,xval2
       real,allocatable :: datmp(:,:)
       character(80) :: ss80
       logical :: kr
 !
 !     [Memory allocation & initialization]
 !     ------------------------------------
       allocate(datmp(mxyld,mxegy))
       allocate(fpydata(mxfpy))
       do i=1,mxfpy
         allocate(fpydata(i)%numfp1(mxegy))
         allocate(fpydata(i)%numfp2(mxegy))
         allocate(fpydata(i)%einc1(mxegy))
         allocate(fpydata(i)%einc2(mxegy))
         allocate(fpydata(i)%nidyld1(mxegy,mxyld))
         allocate(fpydata(i)%nidyld2(mxegy,mxyld))
         allocate(fpydata(i)%fpyld1(mxegy,mxyld))
         allocate(fpydata(i)%fpyld2(mxegy,mxyld))
         fpydata(i)%nuclaid=' '
         fpydata(i)%mat=0
         fpydata(i)%nuclid=0
         fpydata(i)%numinc1=0
         fpydata(i)%numinc2=0
         fpydata(i)%numfp1(:)=0
         fpydata(i)%numfp2(:)=0
         fpydata(i)%einc1(:)=0.0
         fpydata(i)%einc2(:)=0.0
         fpydata(i)%nidyld1(:,:)=0.0
         fpydata(i)%nidyld2(:,:)=0.0
         fpydata(i)%fpyld1(:,:)=0.0
         fpydata(i)%fpyld2(:,:)=0.0
       enddo
 !
 !     [Open endf/b f.p. file]
 !     -----------------------
       open(itape1,file=fpylib,status='old')
 !
 !     [Read endf direct fission product yield data (mt=454)]
 !     ------------------------------------------------------
       rewind(itape1)
       ix=0
       do i=1,1000000
         read(itape1,'(a80)',end=10) ss80
         if (ss80(72:75).eq."1451") then
           ix=ix+1
           read(ss80,'(2e12.6,42x,i4)') xval1,xval2,nid
           fpydata(ix)%mat=nid
           read(itape1,'(33x,i11)')iso
           fpydata(ix)%nuclid=int(xval1)*10+iso
           read(itape1,*)
           read(itape1,*)
           read(itape1,'(x,a10)') fpydata(ix)%nuclaid
           do j=1,10000
             read(itape1,'(a80)',end=10) ss80
             if (ss80(72:75).eq."8454") then
               read(ss80,'(22x,i11)') fpydata(ix)%numinc1
               do k=1,fpydata(ix)%numinc1
                 read(itape1,'(e11.6,33x,2i11)') fpydata(ix)%einc1(k),nid,fpydata(ix)%numfp1(k)
                 read(itape1,'(6e11.6)') ((datmp(k1,k2),k2=1,4),k1=1,fpydata(ix)%numfp1(k))
                 do k1=1,fpydata(ix)%numfp1(k)
                   fpydata(ix)%nidyld1(k,k1)=int(datmp(k1,1))*10+int(datmp(k1,2))
                   fpydata(ix)%fpyld1(k,k1)=datmp(k1,3)
                 enddo
               enddo
               exit
             endif
           enddo
         endif
       enddo
    10 continue
 !
       ntot1=ix
       numfpy=ntot1
 !
 !     [Read endf cumulative fission product yield data (mt=459)]
 !     ----------------------------------------------------------
       rewind(itape1)
       ix=0
       do i=1,1000000
         read(itape1,'(a80)',end=20) ss80
         if (ss80(72:75).eq."1451") then
           ix=ix+1
           read(ss80,'(2e12.6,42x,i4)') xval1,xval2,nid
           if( fpydata(ix)%mat/=nid ) then
              scalereporterror(1,*)'consistency error for ',xval1 ; scalefinalizeerror()
           endif
           read(itape1,'(33x,i11)')iso
           if( fpydata(ix)%nuclid/=int(xval1)*10+iso ) then
              scalereporterror(1,*)'consistency error for ',xval1 ; scalefinalizeerror()
           endif
           read(itape1,*)
           read(itape1,*)
           read(itape1,*)
           do j=1,10000
             read(itape1,'(a80)',end=10) ss80
             if (ss80(72:75).eq."8459") then
               read(ss80,'(22x,i11)') fpydata(ix)%numinc2
               do k=1,fpydata(ix)%numinc2
                 read(itape1,'(e11.6,33x,2i11)') fpydata(ix)%einc2(k),nid,fpydata(ix)%numfp2(k)
                 read(itape1,'(6e11.6)') ((datmp(k1,k2),k2=1,4),k1=1,fpydata(ix)%numfp2(k))
                 do k1=1,fpydata(ix)%numfp2(k)
                   fpydata(ix)%nidyld2(k,k1)=int(datmp(k1,1))*10+int(datmp(k1,2))
                   fpydata(ix)%fpyld2(k,k1)=datmp(k1,3)
                 enddo
               enddo
               exit
             endif
           enddo
         endif
       enddo
    20 continue
 !
       ntot2=ix
 !
 !     [Check the data points: direct vs. cumulative]
 !     ----------------------------------------------
       kr=.true.
       if (ntot1.ne.ntot2) kr=.false.
       do i=1,numfpy
         if (fpydata(i)%numinc1.ne.fpydata(i)%numinc2) then
           kr=.false.
           exit
         endif
         do j=1,fpydata(i)%numinc1
           if (fpydata(i)%numfp1(j).ne.fpydata(i)%numfp2(j)) then
             kr=.false.
             goto 33
           endif
         enddo
       enddo
    33 continue
       if (.not.kr) then
         scalereporterror(1,'("Data mismatch error between Direct and Cumulative FPY.")') ; scalefinalizeerror()
         stop
       endif
 !
       close(itape1)
 !
       return
subroutine main::outfpyield (character(*), intent(in) title)
References write_2float_4int(), and write_6float().
 !
       character(*),intent(in) :: title
       integer :: i,nx,k,j
       !write direct yields
       write(ud,*)title,"(direct yields)"
       do i=1,numfpy
         call write_2float_4int(ud,real(fpydata(i)%nuclid),0.0,fpydata(i)%numinc1,0,0,0)
         do j=1,fpydata(i)%numinc1
             call write_2float_4int(ud,fpydata(i)%einc1(j),0.0,&
                               0,0,0,fpydata(i)%numfp1(j))
             do k=1,fpydata(i)%numfp1(j),3
               call write_6float(ud,&
                 real(fpydata(i)%nidyld1(j,k  )),fpydata(i)%fpyld1(j,k  ),&
                 real(fpydata(i)%nidyld1(j,k+1)),fpydata(i)%fpyld1(j,k+1),&
                 real(fpydata(i)%nidyld1(j,k+2)),fpydata(i)%fpyld1(j,k+2))
             end do
             call write_2float_4int(ud, 0.0,0.0, 0,0,0,0)
         end do
         call write_2float_4int(ud, 0.0,0.0, 0,0,0,0)
       end do
       call write_2float_4int(ud, 0.0,0.0, 0,0,0,0)
       !write cumulative yields
       write(uc,*)title,"(cumulative yields)"
       do i=1,numfpy
         call write_2float_4int(uc,real(fpydata(i)%nuclid),0.0,fpydata(i)%numinc2,0,0,0)
         do j=1,fpydata(i)%numinc2
             call write_2float_4int(uc,fpydata(i)%einc2(j),0.0,&
                               0,0,0,fpydata(i)%numfp2(j))
             do k=1,fpydata(i)%numfp2(j),3
               call write_6float(uc,&
                 real(fpydata(i)%nidyld2(j,k  )),fpydata(i)%fpyld2(j,k  ),&
                 real(fpydata(i)%nidyld2(j,k+1)),fpydata(i)%fpyld2(j,k+1),&
                 real(fpydata(i)%nidyld2(j,k+2)),fpydata(i)%fpyld2(j,k+2))
             end do
             call write_2float_4int(uc, 0.0,0.0, 0,0,0,0)
         end do
         call write_2float_4int(uc, 0.0,0.0, 0,0,0,0)
       end do
       call write_2float_4int(uc, 0.0,0.0, 0,0,0,0)
       return
character(11) function main::f2s (real, intent(in) f1)
Referenced by write_2float_4int(), and write_6float().
       real,intent(in) :: f1
       write(s1,'(ss,es11.5)')f1
       s1(8:10)=s1(9:11)
       s1(11:11)=''
       s1=adjustr(s1)
subroutine main::write_2float_4int (integer, intent(in) unit, real f1, real f2, integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) i3, integer, intent(in) i4)
References f2s().
Referenced by outfpyield().
       integer,intent(in) :: unit,i1,i2,i3,i4
       real :: f1,f2
       character(80) :: str
       write(unit,'(2a11,4i11)')f2s(f1),f2s(f2),i1,i2,i3,i4
subroutine main::write_6float (integer unit, real f1, real f2, real f3, real f4, real f5, real f6)
References f2s().
Referenced by outfpyield().
       integer :: unit
       real :: f1,f2,f3,f4,f5,f6
       character(80) :: str
       write(unit,'(6a11)')f2s(f1),f2s(f2),f2s(f3),f2s(f4),f2s(f5),f2s(f6)