ORIGEN API: constants
constants
C++ API
Variables
const double EMIN = 1e-99
const double EMAX = 1e+99
const double ETOL = 1e-11
const double ERR = 1.0e-44
const int BAD_INT = std::numeric_limits<int>::max()
const double BAD_DOUBLE = std::numeric_limits<double>::max()
const float BAD_FLOAT = std::numeric_limits<float>::max()
const size_t BAD_SIZE_T = std::numeric_limits<size_t>::max() / 2 - 1
const double BRANCH_RATIO_TOLERANCE
const double YIELD_TOLERANCE = 100 * std::numeric_limits<float>::epsilon()
const double MAXIMUM_MASSNUMBER_LOST = 0.3
const double MAXIMUM_MASS_LOST = 0.01
const double MAXIMUM_ZZZAAA_LOST = 0.5
const double NUCLEON_TOLERANCE = 1e-6
const double MINIMUM_HEAVY_PARTICLE_MASS = 0.5
const double NEUTRON_MASS = 1.00866491600
const double PROTON_MASS = 1.007276466812
const double ELECTRON_MASS = 5.4857990946e-4
const double DEUTERON_MASS = 2.013553212712
const double TRITON_MASS = 3.0155007134
const double HELION_MASS = 3.0149322468
const double ALPHA_MASS = 4.001506179125
const double POSITRON_MASS = 5.4857990946e-4
const double NEUTRINO_MASS = 1e-20
const double NULL_MASS = 0.0
Detailed Description
Variable Documentation
const double EMIN = 1e-99
Referenced by EmissionResource::energy_range(), DiscreteSpectrum::energy_range(), and Spectrum::energy_range().
const double EMAX = 1e+99
Referenced by EmissionResource::energy_range(), DiscreteSpectrum::energy_range(), and Spectrum::energy_range().
const double ETOL = 1e-11
const double ERR = 1.0e-44
const int BAD_INT = std::numeric_limits<int>::max()
These variables are used to indicate a bad state. For BAD_SIZE_T, we have to divide by two because Fortran C_SIZE_T will use a signed type and we need to be consistent on what is a bad index in C++ / Fortran also fortran indices will have 1 added to the C++ indices, hence the -1.
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species::charge_number_impl(), Channel::daughter_charge_number_impl(), Channel::daughter_mass_number_impl(), ChannelType_Fiss::delta_charge_number_impl(), ChannelType_Fiss::delta_mass_number_impl(), ChannelType_Fiss::delta_nucleus_neutrons_impl(), ChannelType_Fiss::delta_nucleus_protons_impl(), EmissionResource::emission(), STab1Reader::getIntValue(), ChannelType::has_followon_decay_impl(), Species::has_initialized_charge_number_impl(), ChannelType::has_initialized_decay_mode_impl(), Checkable::has_initialized_id_impl(), Species::has_initialized_mass_number_impl(), ChannelType::has_initialized_reaction_mt_impl(), Field::id_impl(), Checkable::id_impl(), Transition::id_impl(), Channel::id_impl(), Nuclide::id_impl(), ChannelType::is_decay_impl(), ChannelType::is_reaction_impl(), Species::mass_number_impl(), TEST(), and ChannelType_Reac::update_byproducts().
const double BAD_DOUBLE = std::numeric_limits<double>::max()
Examples:
tstConcentrations.cpp, tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, tstGammaResource.cpp, tstGammaResourceIO.cpp, and tstTransitionSystem_Gen.cpp.
Referenced by ConcentrationConverter::convert_to(), Concentrations::convert_units(), ConcentrationConverter::convertible_to(), STab1Reader::getRealValue(), Channel::has_initialized_decay_constant_impl(), Field::has_initialized_intensity_impl(), Species::has_initialized_mass_impl(), Channel::has_initialized_xs_impl(), Transition_Gen::has_initialized_yield_impl(), Field::intensity_impl(), Species::mass_impl(), ConcentrationConverter::mol2d(), ConcentrationConverter::mol2m(), ConcentrationConverter::mol2n(), Channel_Gen::rate_impl(), DiscreteSpectrum::search(), and TEST().
const float BAD_FLOAT = std::numeric_limits<float>::max()
const size_t BAD_SIZE_T = std::numeric_limits<size_t>::max() / 2 - 1
Referenced by EmissionResource::add_emission(), EmissionResource::emission(), EmissionResource::emission_index(), TransitionCoeff::fission_xs_index(), EmissionResource::has_emission(), Origen::saveLibraries(), and Origen::saveStateSet().
const double BRANCH_RATIO_TOLERANCE
Initial value:
=
    100 * std::numeric_limits<float>::epsilon()
The sum of branch ratios should be unity. Checks of this use this tolerance.
const double YIELD_TOLERANCE = 100 * std::numeric_limits<float>::epsilon()
The sum of non-byproduct yields should be 1.0 for simple transitions and 2.0 for fission transitions. Byproducts must have integer yields. Checks of this use this tolerance.
Referenced by YieldResource::check_consistency().
const double MAXIMUM_MASSNUMBER_LOST = 0.3
In case the actual mass is not provided, mass number lost still provides some consistency check of the transitions.
const double MAXIMUM_MASS_LOST = 0.01
const double MAXIMUM_ZZZAAA_LOST = 0.5
const double NUCLEON_TOLERANCE = 1e-6
Mass classification limit for particles used to differentiate proton from H-nucleus
const double MINIMUM_HEAVY_PARTICLE_MASS = 0.5
const double NEUTRON_MASS = 1.00866491600
These masses are from the NIST website http://physics.nist.gov/cgi-bin/cuu/Category?view=html&Atomic+and+nuclear.x=104&Atomic+and+nuclear.y=10
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Neutron::mass_impl(), and TEST().
const double PROTON_MASS = 1.007276466812
Referenced by Proton::mass_impl().
const double ELECTRON_MASS = 5.4857990946e-4
Referenced by Electron::mass_impl().
const double DEUTERON_MASS = 2.013553212712
Referenced by Deuteron::mass_impl().
const double TRITON_MASS = 3.0155007134
Referenced by Triton::mass_impl().
const double HELION_MASS = 3.0149322468
Referenced by Helion::mass_impl().
const double ALPHA_MASS = 4.001506179125
Referenced by Alpha::mass_impl().
const double POSITRON_MASS = 5.4857990946e-4
Referenced by Positron::mass_impl().
const double NEUTRINO_MASS = 1e-20
Referenced by Neutrino::mass_impl().
const double NULL_MASS = 0.0
Referenced by Null::mass_impl().