ORIGEN API: Species Class Reference
Species Class Reference abstract
#include <Species.h>
Defines the species interface for the TransitionSystem.
Public Member Functions
virtual ~Species ()
destructor
Detailed Description
Defines the species interface for the TransitionSystem.
The species, in the context of the transition system, manages three piece of data:
charge number (e)
mass number (neutrons+protons)
mass (grams/mole)
See also
Nuclide
Member Typedef Documentation
typedef SP_Species SP
strong pointer
typedef WP_Species WP
weak pointer
Constructor & Destructor Documentation
~Species () virtual
destructor
Member Function Documentation
int charge_number () const
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_charge_number_impl().
void get_charge_number (int & charge_number) const
Examples:
tstTransitionSystem_Gen.cpp.
void set_charge_number (int charge_number)
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_charge_number () const
int mass_number () const
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_number_impl().
void get_mass_number (int & mass_number) const
Examples:
tstTransitionSystem_Gen.cpp.
void set_mass_number (int mass_number)
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_mass_number () const
double mass () const
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Species_Gen::set_mass_impl().
void get_mass (double & mass) const
Examples:
tstTransitionSystem_Gen.cpp.
void set_mass (double mass)
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_mass () const
int charge_number_impl () const private pure virtual
Implemented in Null, Neutrino, Positron, Electron, Alpha, Helion, Triton, Species_Gen, Deuteron, Proton, and Neutron.
References Origen::BAD_INT.
void get_charge_number_impl (int & charge_number) const private virtual
Reimplemented in Species_Gen.
void set_charge_number_impl (int charge_number) private virtual
Reimplemented in Species_Gen.
bool has_initialized_charge_number_impl () const private virtual
References Origen::BAD_INT.
int mass_number_impl () const private pure virtual
Implemented in Null, Neutrino, Positron, Electron, Alpha, Helion, Triton, Species_Gen, Deuteron, Proton, and Neutron.
References Origen::BAD_INT.
void get_mass_number_impl (int & mass_number) const private virtual
Reimplemented in Species_Gen.
void set_mass_number_impl (int mass_number) private virtual
Reimplemented in Species_Gen.
bool has_initialized_mass_number_impl () const private virtual
References Origen::BAD_INT.
double mass_impl () const private pure virtual
Implemented in Null, Neutrino, Positron, Electron, Alpha, Helion, Triton, Species_Gen, Deuteron, Proton, and Neutron.
References Origen::BAD_DOUBLE.
void get_mass_impl (double & mass) const private virtual
Reimplemented in Species_Gen.
void set_mass_impl (double mass) private virtual
Reimplemented in Species_Gen.
bool has_initialized_mass_impl () const private virtual
References Origen::BAD_DOUBLE.
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
std::string name_impl () const private virtual
Reimplemented from Checkable.
Reimplemented in Null, Neutrino, Positron, Electron, Alpha, Helion, Triton, Deuteron, Proton, and Neutron.
int id_impl () const private virtual
Reimplemented from Checkable.
Reimplemented in Null, Neutrino, Positron, Electron, Alpha, Helion, Triton, Deuteron, Proton, and Neutron.
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
Reimplemented in Null, Neutrino, Positron, Electron, Alpha, Helion, Triton, Deuteron, Proton, and Neutron.
References ORIGEN_CHECKABLE_ERROR.
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), and ChannelType_Reac::good_impl().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), and Channel_Gen::set_transition_impl().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Species.h
Core/ts/Species.cpp