ORIGEN API: NuclideSet Class Reference
NuclideSet Class Reference
#include <NuclideSet.h>
Public Types
typedef std::shared_ptr< NuclideSet > SP
typedef std::shared_ptr< const NuclideSet > SCP
Public Member Functions
NuclideSet ()
NuclideSet (Vec_Int ids)
NuclideSet (Vec_Int ids, bool sort)
NuclideSet (int, int, int, Vec_Int)
NuclideSet (int, int, int, size_t, int *)
void set_ids_legacy (int, int, int, Vec_Int)
void set_ids_legacy (int, int, int, size_t, int *)
int sizzzaaa_at (size_t) const
int izzzaaa_at (size_t) const
int zzzaaai_at (size_t) const
std::string symbol_at (size_t) const
int s_at (size_t) const
int i_at (size_t) const
int z_at (size_t) const
int a_at (size_t) const
size_t lookup_index (int sizzzaaa, bool fortran_offset=false) const
size_t lookup_index_guess (int izzzaaa, bool fortran_offset=false) const
bool lookup_index_all (Vec_Int *index_list, int izzzaaa, bool fortran_offset=false) const
SP_IdMap sizzzaaa_lookup (bool fortran_offset=false) const
map of sizzzaaa to index;
bool mapping_sets (const Vec_Int &user_ids, Vec_Int *user_to_master, Vec_Int *master_to_user, bool fortran_offset=false) const
bool mapping_sets (size_t nu, int const *user_ids, int *user_to_master, size_t nm, int *master_to_user, bool fortran_offset=false) const
bool match (const NuclideSet &) const
bool operator== (const NuclideSet &) const
std::string print_compare (const NuclideSet &) const
Compares (and stores in string) comparison between two NuclideSets.
std::map< int, int > compare_nucl_lists (const NuclideSet &a, std::map< int, int > &loc_a, std::map< int, int > &loc_b) const
Construct a map comparing nuclides on this set with another set.
const Vec_Int & ids () const
return a const reference to ids
SCP_Vec_Int scp_ids () const
return a shared (read-only) ids pointer
int const * ids_array () const
return view of ids vector
size_t ids_size () const
return size of ids vector
bool has_ids () const
return whether the class has a non-null ids
void set_ids (const Vec_Int &)
set the ids (copy operation)
void get_ids (Vec_Int &) const
populate an existing Vec_Int with a copy of ids
void manageptr_ids (Vec_Int *&)
set the ids (ownership transfer)
void getptr_ids (Vec_Int const *&) const
retrieve pointer (read-only) to ids
void get_ids_array (size_t, int *) const
get array of ids vector (Fortran)
void set_ids_array (size_t, int *)
set ids vector from array (Fortran)
int ids_at (size_t) const
get element of ids vector by index
size_t total_nuclides () const
bool has_sublibs () const
bool has_sublib (int) const
size_t count_sublibs () const
size_t num_in_sublib (int) const
size_t sublib_begin (int, bool fortran_offset=false) const
size_t sublib_end (int) const
std::string to_string () const
Scale::Json::Value to_json () const
virtual int serialize (Standard::AbstractStream *stream) const
virtual int deserialize (Standard::AbstractStream *stream)
virtual unsigned long getSerializedSize () const
virtual NuclideSet * getCopy () const
virtual long getUID () const
virtual bool childOf (long parentUID) const
virtual std::string toString () const
Static Public Member Functions
static void convert_zzzaaai_to_sizzzaaa (int, int, int, Vec_Int *)
static void convert_zzzaaai_to_izzzaaa (Vec_Int *)
static void convert_symbol_to_izzzaaa (const Vec_Str &, Vec_Int *)
static void convert_izzzaaa_to_symbol (const Vec_Int &, Vec_Str *)
static void convert_sizzzaaa_to_zzzaaai (Vec_Int *ids)
static int symbol_to_izzzaaa (std::string)
static std::string izzzaaa_to_symbol (int)
static size_t NOT_FOUND (bool fortran_offset=false)
static SP_IdMap sizzzaaa_lookup (const Vec_Int &ids, bool fortran_offset=false)
map of sizzzaaa to index;
static SP_IdMap sizzzaaa_lookup (size_t n, const int *ids, bool fortran_offset=false)
static bool match (const NuclideSet &, const NuclideSet &)
static bool has_sublibs (const Vec_Int &)
static bool has_sublibs (size_t, int const *)
static bool get_sublibs (Vec_Int *, size_t, int const *)
static void sort_mass (Vec_Int *izzzaaa_list)
static void sort_isomeric (Vec_Int *izzzaaa_list)
static void sort_standard (Vec_Int *sizzzaaa_list)
static bool looks_like_zzzaaai (const Vec_Int &ids)
Static Public Attributes
static const long uid = 0x96516764f6b06c5d
Protected Member Functions
void canonicalize_ids ()
Static Protected Member Functions
static bool mapping_sets (const std::vector< int > &sublibs0, size_t nu, int const *user_ids, int *user_to_master, size_t nm, SCP_IdMap master_id_map, int *master_to_user, bool fortran_offset=false)
static bool sublib_search_standard (const std::vector< int > &sublibs0, size_t i, int *user_to_master, SCP_IdMap master_id_map, int *master_to_user, int offset, int id)
Protected Attributes
SP_Vec_Int b_ids
Private Attributes
bool b_has_sublibs
Vec_Int b_sublib_range
SCP_IdMap b_map
bool b_sort
Friends
class ScaleUtils::IO::Accessor< NuclideSet >
Detailed Description
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstNuclideSet.cpp, Core/dc/tests/tstStateSet.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<NuclideSet> SP
typedef std::shared_ptr<const NuclideSet> SCP
Constructor & Destructor Documentation
NuclideSet ()
     : b_ids( new Vec_Int() )
     , b_sublib_range( 10, 0 )
     , b_map( new IdMap() )
     , b_sort( false )
 {
 }
NuclideSet (Vec_Int ids)
References NuclideSet::b_ids, and NuclideSet::canonicalize_ids().
     : b_ids( new Vec_Int() )
     , b_sublib_range( 10, 0 )
     , b_map( new IdMap() )
     , b_sort( false )
 {
     b_ids->swap( ids );
     canonicalize_ids();
 }
NuclideSet (Vec_Int ids, bool sort)
References NuclideSet::b_ids, and NuclideSet::canonicalize_ids().
     : b_ids( new Vec_Int() )
     , b_sublib_range( 10, 0 )
     , b_map( new IdMap() )
     , b_sort( sort )
 {
     b_ids->swap( ids );
     canonicalize_ids();
 }
NuclideSet (int nlt, int nac, int nfp, Vec_Int ids)
References NuclideSet::b_sort, NuclideSet::b_sublib_range, and NuclideSet::set_ids_legacy().
 {
     b_sort = false;
     b_sublib_range.resize( 10 );
     set_ids_legacy( nlt, nac, nfp, ids );
 }
NuclideSet (int nlt, int nac, int nfp, size_t n, int * ids)
References NuclideSet::b_sort, NuclideSet::b_sublib_range, and NuclideSet::set_ids_legacy().
 {
     b_sort = false;
     b_sublib_range.resize( 10 );
     set_ids_legacy( nlt, nac, nfp, n, ids );
 }
Member Function Documentation
void set_ids_legacy (int nlt, int nac, int nfp, Vec_Int ids)
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by Origen::createNuclideSet_random1(), FakeFactory::newspLibrary_10nuclide(), FakeFactory::newspStateSet_10nuclide(), NuclideSet::NuclideSet(), StateSetIO_s62b::read(), and LibraryTest::SetUp().
 {
     set_ids_legacy( nlt, nac, nfp, ids.size(), &ids[0] );
 }
void set_ids_legacy (int nlt, int nac, int nfp, size_t n, int * ids)
References NuclideSet::b_ids, NuclideSet::canonicalize_ids(), and NuclideSet::convert_zzzaaai_to_sizzzaaa().
 {
     Require( static_cast<int>( n ) == ( nlt + nac + nfp ) );
     b_ids = SP_Vec_Int( new Vec_Int( n ) );
     for( size_t i = 0; i < n; ++i )
     {
         b_ids->at( i ) = ids[i];
     }
     convert_zzzaaai_to_sizzzaaa( nlt, nac, nfp, &*b_ids );
     canonicalize_ids();
 }
void convert_zzzaaai_to_sizzzaaa (int nlt, int nac, int nfp, Vec_Int * ids) static
Referenced by NuclideSet::set_ids_legacy().
 {
     Require( ids != nullptr );
     Require( static_cast<int>( ids->size() ) == ( nlt + nac + nfp ) );
     convert_zzzaaai_to_izzzaaa( ids );
     for( size_t i = 0; i < ids->size(); ++i )
     {
         if( i < nlt )
         {
             ( *ids )[i] += 1 * ScaleData::Utils::PIZZZAAA_P_OFFSET;
         }
         else if( i < ( nlt + nac ) )
         {
             ( *ids )[i] += 2 * ScaleData::Utils::PIZZZAAA_P_OFFSET;
         }
         else
         {
             ( *ids )[i] += 3 * ScaleData::Utils::PIZZZAAA_P_OFFSET;
         }
     }
 }
void convert_zzzaaai_to_izzzaaa (Vec_Int * ids) static
Referenced by TransitionMatrixP::find_nuclide(), TransitionMatrixP::find_nuclide_all(), and TransitionMatrixP::find_nuclide_guess().
 {
     Require( ids != nullptr );
     for( size_t i = 0; i < ids->size(); ++i )
     {
         ( *ids )[i] = ScaleData::Utils::zzzaaai_to_pizzzaaa( ( *ids )[i] );
     }
 }
void convert_symbol_to_izzzaaa (const Vec_Str & symbols, Vec_Int * ids) static
Referenced by Origen_NuclideSet_convert_symbol_to_izzzaaa().
 {
     Require( ids != nullptr );
     ids->resize( symbols.size() );
     for( size_t i = 0; i < ids->size(); ++i )
     {
         ( *ids )[i] = NuclideSet::symbol_to_izzzaaa( symbols[i] );
     }
 }
void convert_izzzaaa_to_symbol (const Vec_Int & ids, Vec_Str * symbols) static
 {
     Require( symbols != nullptr );
     symbols->resize( ids.size() );
     for( size_t i = 0; i < symbols->size(); ++i )
     {
         ( *symbols )[i] = NuclideSet::izzzaaa_to_symbol( ids[i] );
     }
 }
void convert_sizzzaaa_to_zzzaaai (Vec_Int * ids) static
Referenced by Origen_NuclideSet_convert_sizzzaaa_to_zzzaaai(), Origen::populateFissionables(), LibraryIO_s62b::write(), LibraryIO_s61::write(), and StateSetIO_s62b::write().
 {
     Require( ids != nullptr );
     for( auto& id : *ids )
     {
         id = id % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         id = ScaleData::Utils::pizzzaaa_to_zzzaaai( id );
     }
 }
int symbol_to_izzzaaa (std::string symbol) static
Referenced by Origen::thinLibrary().
 {
     return ScaleData::Utils::symbol_to_pizzzaaa( symbol );
 }
std::string izzzaaa_to_symbol (int id) static
Referenced by NuclideSet::symbol_at().
 {
     return ScaleData::Utils::pizzzaaa_to_symbol( id );
 }
int sizzzaaa_at (size_t i) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References NuclideSet::b_ids.
 {
     Require( i < b_ids->size() );
     return b_ids->at( i );
 }
int izzzaaa_at (size_t i) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References NuclideSet::b_ids.
Referenced by TransitionSystemAdapter_TransitionMatrix::extend(), gtestLibraryMasses(), Origen::populateLibraryHeader_YieldResource(), Origen::populateLibraryMass_NuclideResource(), and NuclideSet::symbol_at().
 {
     Require( i < b_ids->size() );
     return b_ids->at( i ) % ScaleData::Utils::PIZZZAAA_P_OFFSET;
 }
int zzzaaai_at (size_t i) const
References NuclideSet::b_ids.
Referenced by Origen::populateLibraryHeader_YieldResource().
 {
     Require( i < b_ids->size() );
     int id = b_ids->at( i ) % ScaleData::Utils::PIZZZAAA_P_OFFSET;
     id = ScaleData::Utils::pizzzaaa_to_zzzaaai( id );
     return id;
 }
std::string symbol_at (size_t j) const
References NuclideSet::izzzaaa_at(), and NuclideSet::izzzaaa_to_symbol().
 {
     return izzzaaa_to_symbol( izzzaaa_at( j ) );
 }
int s_at (size_t j) const
References NuclideSet::b_ids.
Referenced by LibraryBuilder::create_library(), Origen::populateLibraryHeader_YieldResource(), and Origen::tabulateMaterialFission().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( b_ids->at( j ), s, i, z, a );
     return s;
 }
int i_at (size_t j) const
References NuclideSet::b_ids.
Referenced by Origen::tabulateReactionTransitions().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( b_ids->at( j ), s, i, z, a );
     return i;
 }
int z_at (size_t j) const
References NuclideSet::b_ids.
Referenced by DecayData::mass().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( b_ids->at( j ), s, i, z, a );
     return z;
 }
int a_at (size_t j) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References NuclideSet::b_ids.
Referenced by gtestLibraryMasses().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( b_ids->at( j ), s, i, z, a );
     return a;
 }
size_t lookup_index (int sizzzaaa, bool fortran_offset = false) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References NuclideSet::b_map, and NuclideSet::NOT_FOUND().
Referenced by TEST_F().
 {
     auto it = b_map->find( sizzzaaa );
     size_t index;
     if( it != b_map->end() )
     {
         index = it->second + ( fortran_offset ? 1 : 0 );
     }
     else
     {
         index = NOT_FOUND( fortran_offset );
     }
     return index;
 }
size_t lookup_index_guess (int izzzaaa, bool fortran_offset = false) const
References NuclideSet::ids(), NuclideSet::mapping_sets(), and NuclideSet::NOT_FOUND().
Referenced by TEST(), and Origen::thinLibrary().
 {
     Vec_Int ids{id};
     Vec_Int u2m;
     Vec_Int m2u;
     bool found = mapping_sets( ids, &u2m, &m2u, fortran_offset );
     return ( found ? u2m[0] : NOT_FOUND( fortran_offset ) );
 }
bool lookup_index_all (Vec_Int * index_list, int izzzaaa, bool fortran_offset = false) const
References NuclideSet::ids(), and NuclideSet::mapping_sets().
 {
     Require( index_list != nullptr );
     Vec_Int ids{id};
     Vec_Int u2m;
     Vec_Int m2u;
     bool found = mapping_sets( ids, &u2m, &m2u, fortran_offset );
     index_list->clear();
     int min_index = fortran_offset ? 1 : 0;
     int j = min_index;
     for( int i : m2u )
     {
         if( i == min_index )
         {
             index_list->push_back( j );
         }
         ++j;
     }
     Check( found == !index_list->empty() );
     return found;
 }
size_t NOT_FOUND (bool fortran_offset = false) static
Referenced by NuclideSet::canonicalize_ids(), NuclideSet::lookup_index(), NuclideSet::lookup_index_guess(), Concentrations::lookup_val(), NuclideSet::mapping_sets(), TransitionMatrixP::NOT_FOUND(), and Origen_NuclideSet_NOT_FOUND().
 {
     size_t index = fortran_offset ? 1 : 0;
     index += 999999;
     return index;
 }
SP_IdMap sizzzaaa_lookup (bool fortran_offset = false) const
map of sizzzaaa to index;
References NuclideSet::b_ids.
Referenced by NuclideSet::canonicalize_ids(), get_transition_data(), inject_fission_yields(), NuclideSet::mapping_sets(), and NuclideSet::sizzzaaa_lookup().
 {
     return sizzzaaa_lookup( *b_ids, fortran_offset );
 }
SP_IdMap sizzzaaa_lookup (const Vec_Int & ids, bool fortran_offset = false) static
map of sizzzaaa to index;
References NuclideSet::sizzzaaa_lookup().
 {
     return sizzzaaa_lookup( ids.size(), &ids[0], fortran_offset );
 }
static SP_IdMap sizzzaaa_lookup (size_t n, const int * ids, bool fortran_offset = false) static
bool mapping_sets (const Vec_Int & user_ids, Vec_Int * user_to_master, Vec_Int * master_to_user, bool fortran_offset = false) const
master[user_to_master[u]] += user_izzzaaa[u]; master[m] += user[master_to_user[m]];
References NuclideSet::ids_size(), and NuclideSet::NOT_FOUND().
Referenced by NuclideSet::lookup_index_all(), NuclideSet::lookup_index_guess(), and NuclideSet::mapping_sets().
 {
     Require( user_to_master != nullptr );
     Require( master_to_user != nullptr );
     // sizes
     size_t nu = user_ids.size();
     size_t nm = ids_size();
     // resize user with handling of empty user list
     user_to_master->resize( nu );
     if( nu == 0 )
     {
         user_to_master->resize( nm, NOT_FOUND( fortran_offset ) );
         return true;
     }
     // resize master with handling of empty master list
     master_to_user->resize( nm );
     if( nm == 0 ) return false;
     // set up pointers
     int const* ui_ptr = &user_ids[0];
     int* u2m_ptr = &( *user_to_master )[0];
     int* m2u_ptr = &( *master_to_user )[0];
     // call pointer version
     return mapping_sets( nu, ui_ptr, u2m_ptr, nm, m2u_ptr, fortran_offset );
 }
bool mapping_sets (size_t nu, int const * user_ids, int * user_to_master, size_t nm, int * master_to_user, bool fortran_offset = false) const
master[user_to_master[u]] += user_izzzaaa[u]; master[m] += user[master_to_user[m]];
References NuclideSet::b_ids, NuclideSet::b_map, NuclideSet::get_sublibs(), NuclideSet::has_sublib(), NuclideSet::has_sublibs(), NuclideSet::ids_size(), NuclideSet::mapping_sets(), and NuclideSet::sizzzaaa_lookup().
 {
     Require( nm == ids_size() );
     std::vector<int> sublibs;
     // it's easy if we have sublibs because the user set has more or the same
     // level of nuclide specificity and we can use our internal map
     if( has_sublibs() )
     {
         // start off from back to front
         for( int s = 9; s >= 1; --s )
         {
             if( has_sublib( s ) ) sublibs.push_back( s );
         }
         return mapping_sets( sublibs,
                              nu,
                              user_ids,
                              user_to_master,
                              nm,
                              b_map,
                              master_to_user,
                              fortran_offset );
     }
     else
     {
         // in this case, the user library is more specific and we need to
         // reverse
         // the sets and make "user" into master
         get_sublibs( &sublibs, nu, user_ids );
         SCP_IdMap user_map = sizzzaaa_lookup( nu, user_ids );
         return mapping_sets( sublibs,
                              nm,
                              &( *b_ids )[0],
                              master_to_user,
                              nu,
                              user_map,
                              user_to_master,
                              fortran_offset );
     }
 }
bool match (const NuclideSet & a, const NuclideSet & b) static
References NuclideSet::match().
Referenced by NuclideSet::match().
 {
     return a.match( b );
 }
bool match (const NuclideSet & a) const
References NuclideSet::b_ids.
 {
     // make copies of the id vectors
     Vec_Int ivec1( *b_ids );
     Vec_Int ivec2( *a.b_ids );
     // sort them
     ScaleSTL::sort( &ivec1 );
     ScaleSTL::sort( &ivec2 );
     // compare them
     return ScaleSTL::eq_vec( ivec1, ivec2 );
 }
bool operator== (const NuclideSet & a) const
References NuclideSet::b_ids, and NuclideSet::ids().
 {
     ORIGEN_COMPARE_SP_VECTOR( ids, b_ids, a.b_ids );
     return true;
 }
std::string print_compare (const NuclideSet & a) const
Compares (and stores in string) comparison between two NuclideSets.
Parameters
The NuclideSet to compare to.
References NuclideSet::compare_nucl_lists().
 {
     std::stringstream ss;
     std::map<int, int> loc_a;
     std::map<int, int> loc_b;
     auto nucl_map = compare_nucl_lists( a, loc_a, loc_b );
     ss << std::setw( 35 ) << "Nuclide IDs:"
        << "     " << std::setw( 10 ) << "A" << std::setw( 15 ) << " "
        << std::setw( 10 ) << "B" << std::endl;
     ss << std::setw( 35 ) << "(* = Nuclide not on Library) "
        << "     "
        << "--------------------"
        << "     "
        << "--------------------" << std::endl;
     for( auto i : nucl_map )
     {
         if( i.first == i.second )
         {
             ss << std::setw( 40 ) << " " << std::setw( 20 ) << i.first
                << std::setw( 25 ) << i.second << std::endl;
         }
         else if( i.second == -1 )
         {
             ss << std::setw( 40 ) << " " << std::setw( 20 ) << i.first
                << std::setw( 25 ) << "*" << std::endl;
         }
         else if( i.second == -2 )
         {
             ss << std::setw( 40 ) << " " << std::setw( 20 ) << "*"
                << std::setw( 25 ) << i.first << std::endl;
         }
     }
     return ss.str();
 }
std::map< int, int > compare_nucl_lists (const NuclideSet & a, std::map< int, int > & loc_a, std::map< int, int > & loc_b) const
Construct a map comparing nuclides on this set with another set.
Parameters
a NuclideSet to compare to.
Returns
A map containing the results.
The resulting map will contain pairs that have the same IZA in the first and second position on if the nuclide exists on both sets. If it exists on only the first set, the second value on the pair will be -1. If it exists on only the second set, the second value on the pair will be -2.
References NuclideSet::b_ids.
Referenced by NuclideSet::print_compare().
 {
     std::vector<int> nucl_on_both;
     std::vector<int> nucl_on_a_only;
     std::vector<int> nucl_on_b_only;
     int ni = 0;
     for( auto i : *b_ids )
     {
         auto loc = std::find( a.b_ids->begin(), a.b_ids->end(), i );
         loc_a.insert( std::pair<int, int>( i, ni++ ) );
         if( loc == a.b_ids->end() )
         {
             nucl_on_a_only.push_back( i );
         }
         else
         {
             nucl_on_both.push_back( i );
         }
     }
     ni = 0;
     for( auto i : *( a.b_ids ) )
     {
         auto loc = std::find( b_ids->begin(), b_ids->end(), i );
         loc_b.insert( std::pair<int, int>( i, ni++ ) );
         if( loc == b_ids->end() )
         {
             nucl_on_b_only.push_back( i );
         }
     }
     std::map<int, int> nucl_map;
     for( auto i : nucl_on_both )
     {
         nucl_map.insert( std::pair<int, int>( i, i ) );
     }
     for( auto i : nucl_on_a_only )
     {
         nucl_map.insert( std::pair<int, int>( i, -1 ) );
     }
     for( auto i : nucl_on_b_only )
     {
         nucl_map.insert( std::pair<int, int>( i, -2 ) );
     }
     return nucl_map;
 }
const Vec_Int & ids () const
return a const reference to ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of NuclideSet goes out of scope.
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/dc/tests/tstNuclideSet.cpp, Core/dc/tests/tstStateSet.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by Concentrations::accumulate_concs(), NuclideSet::canonicalize_ids(), TransitionSystemAdapter_TransitionMatrix::extend(), Material::get_concs_at(), get_decay_data(), get_transition_data(), Origen::graphvizLibrary(), inject_fission_yields(), NuclideSet::lookup_index_all(), NuclideSet::lookup_index_guess(), NuclideSet::operator==(), Origen::populateLibraryAbundance_NuclideResource(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryMass(), Origen::populateLibraryToxicity_DecayResource(), LibraryIO_s61::read(), LibraryIO_bof::read(), LibraryIO_s62b::read(), Material::set_concs_at(), Origen::tabulateFissionXs(), Origen::tabulateLossXs(), Origen::tabulateNuclideInfo(), TEST(), timing_ref(), timing_ref_at(), StateSetIO_bof::write(), StateSetIO_s62b::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
SCP_Vec_Int scp_ids () const
return a shared (read-only) ids pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstNuclideSet.cpp.
Referenced by TEST().
Vec_Int::value_type const * ids_array () const
return view of ids vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t ids_size () const
return size of ids vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), LibraryBuilder::create_library(), gtestLibrarySizes(), NuclideSet::mapping_sets(), DecayData::mass(), Origen::populateLibraryHeader_YieldResource(), Origen::tabulateFissionXs(), Origen::tabulateLossXs(), Origen::tabulateMaterialFission(), Origen::tabulateMaterialTransitionRates(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), and LibraryIO_s62b::write().
bool has_ids () const
return whether the class has a non-null ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_ids (const Vec_Int & ids)
set the ids (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/dc/tests/tstNuclideSet.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by Origen::populateLibraryHeader_YieldResource(), StateSetIO_bof::read(), StateSetIO_s62b::read(), LibraryIO_bof::read(), TEST(), and TEST_P().
void get_ids (Vec_Int & ids) const
populate an existing Vec_Int with a copy of ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Origen::diffConcentrations(), TransitionMatrixUpdater::load(), and LibraryIO_s61::write().
void manageptr_ids (Vec_Int *& ids)
set the ids (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_ids (Vec_Int const *& ids) const
retrieve pointer (read-only) to ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstNuclideSet.cpp.
void get_ids_array (size_t , int *) const
get array of ids vector (Fortran)
void set_ids_array (size_t , int *)
set ids vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Int::value_type ids_at (size_t i) const
get element of ids vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/dc/tests/tstNuclideSet.cpp, Core/dc/tests/tstStateSet.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), Origen::construct_neutron_prod_map(), Origen::construct_neutron_yields_map(), DecayResource::DecayResource(), Origen::tabulateFissionXs(), Origen::tabulateLossXs(), Origen::tabulateMaterialFission(), Origen::tabulateMaterialTransitionRates(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), TEST(), and TEST_F().
size_t total_nuclides () const
Examples:
Core/dc/tests/tstNuclideSet.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by TransitionCoeff::capture_power(), Origen::createDecayData_random1(), Origen::createTransitionCoeff_random1(), Origen::createTransitionStructure_random1(), DecayResource::DecayResource(), TransitionCoeff::fission_power(), gtestLibraryMasses(), gtestLibrarySizes(), Origen::populateLibraryMass_NuclideResource(), TransitionCoeff::reaction_power(), TEST(), LibraryIO_s62b::write(), and LibraryIO_s61::write().
 { return b_ids->size(); }
bool has_sublibs () const
Examples:
Core/dc/tests/tstConcentrations.cpp, and Core/dc/tests/tstNuclideSet.cpp.
References NuclideSet::b_has_sublibs.
Referenced by NuclideSet::count_sublibs(), NuclideSet::has_sublibs(), NuclideSet::mapping_sets(), NuclideSet::num_in_sublib(), Origen::populateLibraryAbundance_NuclideResource(), NuclideSet::sublib_begin(), NuclideSet::sublib_end(), TEST(), and LibraryIO_s62b::write().
 { return b_has_sublibs; }
bool has_sublib (int s) const
Examples:
Core/dc/tests/tstNuclideSet.cpp.
References NuclideSet::num_in_sublib().
Referenced by TransitionCoeff::fission_xs_index(), NuclideSet::mapping_sets(), Origen::populateLibraryAbundance_NuclideResource(), and LibraryIO_s61::write().
 { return num_in_sublib( s ) > 0; }
size_t count_sublibs () const
References NuclideSet::has_sublibs(), and NuclideSet::num_in_sublib().
Referenced by Case::load_new_concentrations(), StateSetIO_s62b::write(), LibraryIO_s62b::write(), and LibraryIO_s61::write().
 {
     if( !has_sublibs() ) return 0;
     size_t n = 0;
     for( size_t s = 1; s <= 9; ++s )
     {
         if( num_in_sublib( s ) > 0 ) ++n;
     }
     return n;
 }
size_t num_in_sublib (int s) const
Examples:
Core/dc/tests/tstNuclideSet.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References NuclideSet::b_sublib_range, and NuclideSet::has_sublibs().
Referenced by NuclideSet::count_sublibs(), Origen::createDecayData_random1(), Origen::createTransitionCoeff_random1(), get_decay_data(), get_transition_data(), gtestLibrarySizes(), NuclideSet::has_sublib(), inject_fission_yields(), FakeFactory::newspLibrary_10nuclide(), Origen::populateLibraryAbundance_NuclideResource(), TEST(), LibraryIO_s61::write(), LibraryIO_s62b::write(), and StateSetIO_s62b::write().
 {
     Require( has_sublibs() );
     Require( s > 0 && s < 10 );
     return b_sublib_range[s] - b_sublib_range[s - 1];
 }
size_t sublib_begin (int s, bool fortran_offset = false) const
References NuclideSet::b_sublib_range, and NuclideSet::has_sublibs().
Referenced by TransitionSystemAdapter_TransitionMatrix::extend(), and TransitionCoeff::fission_xs_index().
 {
     Require( s > 0 && s < 10 );
     Require( has_sublibs() );
     return b_sublib_range[s - 1] + ( fortran_offset ? 1 : 0 );
 }
size_t sublib_end (int s) const
References NuclideSet::b_sublib_range, and NuclideSet::has_sublibs().
Referenced by TransitionCoeff::fission_xs_index().
 {
     Require( s > 0 && s < 10 );
     Require( has_sublibs() );
     return b_sublib_range[s];
 }
bool has_sublibs (const Vec_Int & ids) static
References NuclideSet::has_sublibs().
 {
     if( ids.size() == 0 ) return false;
     return has_sublibs( ids.size(), &ids[0] );
 }
bool has_sublibs (size_t n, int const * ids) static
 {
     for( size_t i = 0; i < n; ++i )
     {
         if( ids[i] / ScaleData::Utils::PIZZZAAA_P_OFFSET > 0 ) return true;
     }
     return false;
 }
bool get_sublibs (Vec_Int * sublibs, size_t n, int const * ids) static
Referenced by NuclideSet::mapping_sets().
 {
     Require( sublibs != nullptr );
     std::set<int> sublibs_set;
     for( size_t i = 0; i < n; ++i )
     {
         int s = ids[i] / ScaleData::Utils::PIZZZAAA_P_OFFSET;
         if( s > 0 ) sublibs_set.insert( s );
     }
     if( sublibs_set.size() > 0 )
     {
         sublibs->assign( sublibs_set.rbegin(), sublibs_set.rend() );
         return true;
     }
     return false;
 }
std::string to_string () const
Examples:
Core/dc/tests/tstNuclideSet.cpp.
References NuclideSet::to_json().
Referenced by TEST().
 { return to_json().toStyledString(); }
Json::Value to_json () const
References NuclideSet::b_ids, NuclideSet::b_sublib_range, and NuclideSet::uid.
Referenced by NuclideSet::to_string().
 {
     Json::Value root;
     root["uid"] = Json::Value::Int64( uid );
     Standard::Json::arrayToJson( root["ids"], *b_ids );
     Standard::Json::arrayToJson( root["sublib_range"], b_sublib_range );
     return root;
 }
int serialize (Standard::AbstractStream * stream) const virtual
Examples:
Core/dc/tests/tstNuclideSet.cpp.
Referenced by TEST().
int deserialize (Standard::AbstractStream * stream) virtual
Examples:
Core/dc/tests/tstNuclideSet.cpp.
Referenced by TEST().
unsigned long getSerializedSize () const virtual
NuclideSet * getCopy () const virtual
long getUID () const virtual
bool childOf (long parentUID) const virtual
std::string toString () const virtual
void sort_mass (Vec_Int * izzzaaa_list) static
Referenced by main().
 {
     Require( izzzaaa_list != nullptr );
     std::sort( izzzaaa_list->begin(),
                izzzaaa_list->end(),
                ScaleData::compare_nuclide_id_azi() );
 }
void sort_isomeric (Vec_Int * izzzaaa_list) static
 {
     Require( izzzaaa_list != nullptr );
     std::sort( izzzaaa_list->begin(),
                izzzaaa_list->end(),
                ScaleData::compare_nuclide_id_zai() );
 }
void sort_standard (Vec_Int * sizzzaaa_list) static
References Origen::SUBLIB_3FP.
Referenced by NuclideSet::canonicalize_ids().
 {
     Require( ids != nullptr );
     // first sort by zai (and s blocks)
     std::sort( ids->begin(), ids->end(), ScaleData::compare_nuclide_id_zai() );
     // remove duplicates
     ids->erase( std::unique( ids->begin(), ids->end() ), ids->end() );
     // the find the s=SUBLIB_3FP (3) block start and end
     int js = 0;
     int je = -1;
     for( size_t i = 0; i < ids->size(); ++i )
     {
         int id = ids->at( i );
         int s = id / ScaleData::Utils::PIZZZAAA_P_OFFSET;
         if( s == SUBLIB_3FP && je == -1 )
         {
             js = i;
             je = i + 1;
         }
         else if( s == SUBLIB_3FP )
         {
             je = i + 1;
         }
     }
     // sort just the s=SUBLIB_3FP block with azi
     if( je != -1 )
     {
         std::sort( ids->begin() + js,
                    ids->begin() + je,
                    ScaleData::compare_nuclide_id_azi() );
     }
 }
bool looks_like_zzzaaai (const Vec_Int & ids) static
Referenced by LibraryIO_s61::read(), StateSetIO_s62b::read(), and LibraryIO_s62b::read().
 {
     for( auto id : ids )
     {
         int i = id % 10;
         if( i > 3 ) return false;
     }
     return true;
 }
void canonicalize_ids () protected
References NuclideSet::b_has_sublibs, NuclideSet::b_ids, NuclideSet::b_map, NuclideSet::b_sort, NuclideSet::b_sublib_range, NuclideSet::ids(), NuclideSet::NOT_FOUND(), NuclideSet::sizzzaaa_lookup(), and NuclideSet::sort_standard().
Referenced by NuclideSet::NuclideSet(), Accessor< Origen::NuclideSet >::read(), and NuclideSet::set_ids_legacy().
 {
     // NOT_FOUND() static function sets the maximum number of ids at 1e6
     Require( b_ids->size() < NOT_FOUND() );
     // reset
     b_has_sublibs = false;
     for( size_t i = 0; i < 10; ++i )
     {
         b_sublib_range[i] = 0;
     }
     // quick return
     Check( b_ids != nullptr );
     if( b_ids->size() == 0 ) return;
     // dereference for fast operation
     Vec_Int& ids = *b_ids;
     // sort in standard ORIGEN way
     if( b_sort ) sort_standard( &ids );
     // count numbers
     std::vector<size_t> num_in_sublibs( 9, 0 );
     for( size_t i = 0; i < ids.size(); ++i )
     {
         int s = ids[i] / ScaleData::Utils::PIZZZAAA_P_OFFSET;
         Check( s >= 0 && s < 10 );
         if( s > 0 )
         {
             b_has_sublibs = true;
             ++num_in_sublibs[s - 1];
         }
     }
     // create the range
     for( size_t s = 1; s <= 9; ++s )
     {
         b_sublib_range[s] = b_sublib_range[s - 1] + num_in_sublibs[s - 1];
     }
     // create the map
     b_map = sizzzaaa_lookup();
 }
bool mapping_sets (const std::vector< int > & sublibs, size_t nu, int const * user_ids, int * user_to_master, size_t nm, SCP_IdMap master_id_map, int * master_to_user, bool fortran_offset = false) static protected
master[user_to_master[u]] += user_izzzaaa[u]; master[m] += user[master_to_user[m]];
References NuclideSet::has_sublibs(), NuclideSet::NOT_FOUND(), and NuclideSet::sublib_search_standard().
 {
     // initialize
     bool master_has_sublibs = sublibs.size() > 0;
     int offset = fortran_offset ? 1 : 0;
     for( size_t i = 0; i < nu; ++i )
         user_to_master[i] = NOT_FOUND( fortran_offset );
     for( size_t i = 0; i < nm; ++i )
         master_to_user[i] = NOT_FOUND( fortran_offset );
     // return after initialization
     if( nu == 0 ) return true;
     if( nm == 0 ) return false;
     // search for each id
     bool all_found = true;
     for( size_t i = 0; i < nu; ++i )
     {
         // nuclide id
         int id = user_ids[i];
         // sublibrary
         int s = id / ScaleData::Utils::PIZZZAAA_P_OFFSET;
         jDebugLine( "   trying to place index=" << i << " id=" << id
                                                 << " with sublib s="
                                                 << s );
         // if this NuclideSet does not have sublibs then things get a little
         // different
         if( !master_has_sublibs )
         {
             // user cannot have sublibs or it is more general and this procedure
             // will not work
             Check( !has_sublibs( nu, user_ids ) );
             int izzzaaa = id % ScaleData::Utils::PIZZZAAA_P_OFFSET;
             IdMap::const_iterator it = master_id_map->find( izzzaaa );
             if( it != master_id_map->end() )
             {
                 user_to_master[i] = it->second + offset;
                 master_to_user[it->second + offset] = i;
                 jDebugLine( "      directly placed" );
             }
             else
             {
                 SErrLine( 2,
                           "      nuclide id=" << id
                                               << " does not exist in sublib s="
                                               << s );
                 all_found = false;
             }
         }
         // s!=0 means we look up directly the nuclide in sublib s
         else if( s != 0 )
         {
             IdMap::const_iterator it = master_id_map->find( id );
             if( it != master_id_map->end() )
             {
                 user_to_master[i] = it->second + offset;
                 master_to_user[it->second + offset] = i;
                 jDebugLine( "      directly placed" );
             }
             else
             {
                 SErrLine( 2,
                           "      nuclide id=" << id
                                               << " does not exist in sublib s="
                                               << s );
                 all_found = false;
             }
         }
         // s==0 means we have to search for the first match (id is not sizzzaaa)
         else
         {
             bool found = sublib_search_standard( sublibs,
                                                  i,
                                                  user_to_master,
                                                  master_id_map,
                                                  master_to_user,
                                                  offset,
                                                  id );
             if( !found )
             {
                 SErrLine(
                     2,
                     "      could not place nuclide id=" << id
                                                         << " in any sublib" );
                 all_found = false;
             }
         }
     }
     return all_found;
 }
bool sublib_search_standard (const std::vector< int > & sublibs0, size_t i, int * user_to_master, SCP_IdMap master_id_map, int * master_to_user, int offset, int id) static protected
References Origen::SUBLIB_1LT.
Referenced by NuclideSet::mapping_sets().
 {
     Require( id < 9999999 );  // means it's an izzzaaa and not a sizzzaaa
     // construct the order in which to search sublibs
     std::deque<int> sublibs( sublibs0.begin(), sublibs0.end() );
     // special clause to make sure that really light nuclides get associated to
     // light elements first and not as tertiary fission products or alpha
     // byproducts
     // for the actinides, e.g. Li-6 must be associated to a light nuclide
     if( id < 26000 )
     {
         auto it = std::find( sublibs.begin(), sublibs.end(), SUBLIB_1LT );
         if( it != sublibs.end() )
         {
             sublibs.erase( it );
             sublibs.push_front( SUBLIB_1LT );
         }
     }
     // start searching
     bool first = true;
     for( int s : sublibs )
     {
         int test = s * ScaleData::Utils::PIZZZAAA_P_OFFSET + id;
         IdMap::const_iterator it = master_id_map->find( test );
         if( it != master_id_map->end() )
         {
             if( first )
             {
                 first = false;
                 user_to_master[i] = it->second + offset;
                 jDebugLine( "      searched and placed in sublib s=" << s );
             }
             jDebugLine(
                 "      master index=" << it->second + offset << " gets user="
                                       << static_cast<int>( i ) + offset );
             master_to_user[it->second] = static_cast<int>( i ) + offset;
         }
     }
     // return that we found it
     return !first;
 }
Friends And Related Function Documentation
friend class ScaleUtils::IO::Accessor< NuclideSet > friend
Member Data Documentation
const long uid = 0x96516764f6b06c5d static
Referenced by NuclideSet::to_json().
SP_Vec_Int b_ids protected
std::vector<int> - list of nuclide ids in SIZZZAAA format
Referenced by NuclideSet::a_at(), NuclideSet::canonicalize_ids(), NuclideSet::compare_nucl_lists(), NuclideSet::i_at(), NuclideSet::izzzaaa_at(), NuclideSet::mapping_sets(), NuclideSet::match(), NuclideSet::NuclideSet(), NuclideSet::operator==(), Accessor< Origen::NuclideSet >::read(), NuclideSet::s_at(), NuclideSet::set_ids_legacy(), NuclideSet::sizzzaaa_at(), NuclideSet::sizzzaaa_lookup(), NuclideSet::to_json(), NuclideSet::z_at(), and NuclideSet::zzzaaai_at().
bool b_has_sublibs private
Referenced by NuclideSet::canonicalize_ids(), and NuclideSet::has_sublibs().
Vec_Int b_sublib_range private
Referenced by NuclideSet::canonicalize_ids(), NuclideSet::NuclideSet(), NuclideSet::num_in_sublib(), NuclideSet::sublib_begin(), NuclideSet::sublib_end(), and NuclideSet::to_json().
SCP_IdMap b_map private
Referenced by NuclideSet::canonicalize_ids(), NuclideSet::lookup_index(), and NuclideSet::mapping_sets().
bool b_sort private
Referenced by NuclideSet::canonicalize_ids(), and NuclideSet::NuclideSet().
The documentation for this class was generated from the following files:
Core/dc/NuclideSet.h
Core/dc/NuclideSet.cpp