ORIGEN API: Solver/radau5/src/radau5.f90 File Reference
radau5.f90 File Reference
The 3rd party RADAU5 solver – the main module.
Functions/Subroutines
subroutine radau5 (N, FCN, X, Y, XEND, H, RTOL, ATOL, ITOL, JAC, IJAC, MLJAC, MUJAC, MAS, IMAS, MLMAS, MUMAS, SOLOUT, IOUT, WORK, LWORK, IWORK, LIWORK, RPAR, IPAR, IDID)
subroutine radcor (N, FCN, X, Y, XEND, HMAX, H, RTOL, ATOL, ITOL, JAC, IJAC, MLJAC, MUJAC, MAS, MLMAS, MUMAS, SOLOUT, IOUT, IDID, NMAX, UROUND, SAFE, THET, FNEWT, QUOT1, QUOT2, NIT, IJOB, STARTN, NIND1, NIND2, NIND3, PRED, FACL, FACR, M1, M2, NM1, IMPLCT, BANDED, LDJAC, LDE1, LDMAS, Z1, Z2, Z3, Y0, SCAL, F1, F2, F3, FJAC, E1, E2R, E2I, FMAS, IP1, IP2, IPHES, CONT, NFCN, NJAC, NSTEP, NACCPT, NREJCT, NDEC, NSOL, RPAR, IPAR)
double precision function contr5 (I, X, CONT, LRC)
Detailed Description
The 3rd party RADAU5 solver – the main module.
Function/Subroutine Documentation
subroutine radau5 (N, external FCN, X, dimension(n) Y, XEND, H, dimension(*) RTOL, dimension(*) ATOL, ITOL, external JAC, IJAC, MLJAC, MUJAC, external MAS, IMAS, MLMAS, MUMAS, external SOLOUT, IOUT, dimension(lwork) WORK, LWORK, dimension(liwork) IWORK, LIWORK, dimension(*) RPAR, dimension(*) IPAR, IDID)
References radcor().
Referenced by kernel_radau5::radau5_solve().
 !
 !     RPAR, IPAR  REAL AND INTEGER PARAMETERS (OR PARAMETER ARRAYS) WHIC
 !                 CAN BE USED FOR COMMUNICATION BETWEEN YOUR CALLING
 !                 PROGRAM AND THE FCN, JAC, MAS, SOLOUT SUBROUTINES.
 !
 ! ----------------------------------------------------------------------
 !
 !     SOPHISTICATED SETTING OF PARAMETERS
 !     -----------------------------------
 !              SEVERAL PARAMETERS OF THE CODE ARE TUNED TO MAKE IT WORK
 !              WELL. THEY MAY BE DEFINED BY SETTING WORK(1),...
 !              AS WELL AS IWORK(1),... DIFFERENT FROM ZERO.
 !              FOR ZERO INPUT, THE CODE CHOOSES DEFAULT VALUES:
 !
 !    IWORK(1)  IF IWORK(1).NE.0, THE CODE TRANSFORMS THE JACOBIAN
 !              MATRIX TO HESSENBERG FORM. THIS IS PARTICULARLY
 !              ADVANTAGEOUS FOR LARGE SYSTEMS WITH FULL JACOBIAN.
 !              IT DOES NOT WORK FOR BANDED JACOBIAN (MLJAC<N)
 !              AND NOT FOR IMPLICIT SYSTEMS (IMAS=1).
 !
 !    IWORK(2)  THIS IS THE MAXIMAL NUMBER OF ALLOWED STEPS.
 !              THE DEFAULT VALUE (FOR IWORK(2)=0) IS 100000.
 !
 !    IWORK(3)  THE MAXIMUM NUMBER OF NEWTON ITERATIONS FOR THE
 !              SOLUTION OF THE IMPLICIT SYSTEM IN EACH STEP.
 !              THE DEFAULT VALUE (FOR IWORK(3)=0) IS 7.
 !
 !    IWORK(4)  IF IWORK(4).EQ.0 THE EXTRAPOLATED COLLOCATION SOLUTION
 !              IS TAKEN AS STARTING VALUE FOR NEWTON'S METHOD.
 !              IF IWORK(4).NE.0 ZERO STARTING VALUES ARE USED.
 !              THE LATTER IS RECOMMENDED IF NEWTON'S METHOD HAS
 !              DIFFICULTIES WITH CONVERGENCE (THIS IS THE CASE WHEN
 !              NSTEP IS LARGER THAN NACCPT + NREJCT; SEE OUTPUT PARAM.).
 !              DEFAULT IS IWORK(4)=0.
 !
 !       THE FOLLOWING 3 PARAMETERS ARE IMPORTANT FOR
 !       DIFFERENTIAL-ALGEBRAIC SYSTEMS OF INDEX > 1.
 !       THE FUNCTION-SUBROUTINE SHOULD BE WRITTEN SUCH THAT
 !       THE INDEX 1,2,3 VARIABLES APPEAR IN THIS ORDER.
 !       IN ESTIMATING THE ERROR THE INDEX 2 VARIABLES ARE
 !       MULTIPLIED BY H, THE INDEX 3 VARIABLES BY H**2.
 !
 !    IWORK(5)  DIMENSION OF THE INDEX 1 VARIABLES (MUST BE > 0). FOR
 !              ODE'S THIS EQUALS THE DIMENSION OF THE SYSTEM.
 !              DEFAULT IWORK(5)=N.
 !
 !    IWORK(6)  DIMENSION OF THE INDEX 2 VARIABLES. DEFAULT IWORK(6)=0.
 !
 !    IWORK(7)  DIMENSION OF THE INDEX 3 VARIABLES. DEFAULT IWORK(7)=0.
 !
 !    IWORK(8)  SWITCH FOR STEP SIZE STRATEGY
 !              IF IWORK(8).EQ.1  MOD. PREDICTIVE CONTROLLER (GUSTAFSSON)
 !              IF IWORK(8).EQ.2  CLASSICAL STEP SIZE CONTROL
 !              THE DEFAULT VALUE (FOR IWORK(8)=0) IS IWORK(8)=1.
 !              THE CHOICE IWORK(8).EQ.1 SEEMS TO PRODUCE SAFER RESULTS;
 !              FOR SIMPLE PROBLEMS, THE CHOICE IWORK(8).EQ.2 PRODUCES
 !              OFTEN SLIGHTLY FASTER RUNS
 !
 !       IF THE DIFFERENTIAL SYSTEM HAS THE SPECIAL STRUCTURE THAT
 !            Y(I)' = Y(I+M2)   FOR  I=1,...,M1,
 !       WITH M1 A MULTIPLE OF M2, A SUBSTANTIAL GAIN IN COMPUTERTIME
 !       CAN BE ACHIEVED BY SETTING THE PARAMETERS IWORK(9) AND IWORK(10)
 !       E.G., FOR SECOND ORDER SYSTEMS P'=V, V'=G(P,V), WHERE P AND V AR
 !       VECTORS OF DIMENSION N/2, ONE HAS TO PUT M1=M2=N/2.
 !       FOR M1>0 SOME OF THE INPUT PARAMETERS HAVE DIFFERENT MEANINGS:
 !       - JAC: ONLY THE ELEMENTS OF THE NON-TRIVIAL PART OF THE
 !              JACOBIAN HAVE TO BE STORED
 !              IF (MLJAC.EQ.N-M1) THE JACOBIAN IS SUPPOSED TO BE FULL
 !                 DFY(I,J) = PARTIAL F(I+M1) / PARTIAL Y(J)
 !                FOR I=1,N-M1 AND J=1,N.
 !              ELSE, THE JACOBIAN IS BANDED ( M1 = M2 * MM )
 !                 DFY(I-J+MUJAC+1,J+K*M2) = PARTIAL F(I+M1) / PARTIAL Y(
 !                FOR I=1,MLJAC+MUJAC+1 AND J=1,M2 AND K=0,MM.
 !       - MLJAC: MLJAC=N-M1: IF THE NON-TRIVIAL PART OF THE JACOBIAN IS
 !                0<=MLJAC<N-M1: IF THE (MM+1) SUBMATRICES (FOR K=0,MM)
 !                     PARTIAL F(I+M1) / PARTIAL Y(J+K*M2),  I,J=1,M2
 !                    ARE BANDED, MLJAC IS THE MAXIMAL LOWER BANDWIDTH
 !                    OF THESE MM+1 SUBMATRICES
 !       - MUJAC: MAXIMAL UPPER BANDWIDTH OF THESE MM+1 SUBMATRICES
 !                NEED NOT BE DEFINED IF MLJAC=N-M1
 !       - MAS: IF IMAS=0 THIS MATRIX IS ASSUMED TO BE THE IDENTITY AND
 !              NEED NOT BE DEFINED. SUPPLY A DUMMY SUBROUTINE IN THIS CA
 !              IT IS ASSUMED THAT ONLY THE ELEMENTS OF RIGHT LOWER BLOCK
 !              DIMENSION N-M1 DIFFER FROM THAT OF THE IDENTITY MATRIX.
 !              IF (MLMAS.EQ.N-M1) THIS SUBMATRIX IS SUPPOSED TO BE FULL
 !                 AM(I,J) = M(I+M1,J+M1)     FOR I=1,N-M1 AND J=1,N-M1.
 !              ELSE, THE MASS MATRIX IS BANDED
 !                 AM(I-J+MUMAS+1,J) = M(I+M1,J+M1)
 !       - MLMAS: MLMAS=N-M1: IF THE NON-TRIVIAL PART OF M IS FULL
 !                0<=MLMAS<N-M1: LOWER BANDWIDTH OF THE MASS MATRIX
 !       - MUMAS: UPPER BANDWIDTH OF THE MASS MATRIX
 !                NEED NOT BE DEFINED IF MLMAS=N-M1
 !
 !    IWORK(9)  THE VALUE OF M1.  DEFAULT M1=0.
 !
 !    IWORK(10) THE VALUE OF M2.  DEFAULT M2=M1.
 !
 ! ----------
 !
 !    WORK(1)   UROUND, THE ROUNDING UNIT, DEFAULT 1.D-16.
 !
 !    WORK(2)   THE SAFETY FACTOR IN STEP SIZE PREDICTION,
 !              DEFAULT 0.9D0.
 !
 !    WORK(3)   DECIDES WHETHER THE JACOBIAN SHOULD BE RECOMPUTED;
 !              INCREASE WORK(3), TO 0.1 SAY, WHEN JACOBIAN EVALUATIONS
 !              ARE COSTLY. FOR SMALL SYSTEMS WORK(3) SHOULD BE SMALLER
 !              (0.001D0, SAY). NEGATIV WORK(3) FORCES THE CODE TO
 !              COMPUTE THE JACOBIAN AFTER EVERY ACCEPTED STEP.
 !              DEFAULT 0.001D0.
 !
 !    WORK(4)   STOPPING CRITERION FOR NEWTON'S METHOD, USUALLY CHOSEN <1
 !              SMALLER VALUES OF WORK(4) MAKE THE CODE SLOWER, BUT SAFER
 !              DEFAULT MIN(0.03D0,RTOL(1)**0.5D0)
 !
 !    WORK(5) AND WORK(6) : IF WORK(5) < HNEW/HOLD < WORK(6), THEN THE
 !              STEP SIZE IS NOT CHANGED. THIS SAVES, TOGETHER WITH A
 !              LARGE WORK(3), LU-DECOMPOSITIONS AND COMPUTING TIME FOR
 !              LARGE SYSTEMS. FOR SMALL SYSTEMS ONE MAY HAVE
 !              WORK(5)=1.D0, WORK(6)=1.2D0, FOR LARGE FULL SYSTEMS
 !              WORK(5)=0.99D0, WORK(6)=2.D0 MIGHT BE GOOD.
 !              DEFAULTS WORK(5)=1.D0, WORK(6)=1.2D0 .
 !
 !    WORK(7)   MAXIMAL STEP SIZE, DEFAULT XEND-X.
 !
 !    WORK(8), WORK(9)   PARAMETERS FOR STEP SIZE SELECTION
 !              THE NEW STEP SIZE IS CHOSEN SUBJECT TO THE RESTRICTION
 !                 WORK(8) <= HNEW/HOLD <= WORK(9)
 !              DEFAULT VALUES: WORK(8)=0.2D0, WORK(9)=8.D0
 !
 !-----------------------------------------------------------------------
 !
 !     OUTPUT PARAMETERS
 !     -----------------
 !     X           X-VALUE FOR WHICH THE SOLUTION HAS BEEN COMPUTED
 !                 (AFTER SUCCESSFUL RETURN X=XEND).
 !
 !     Y(N)        NUMERICAL SOLUTION AT X
 !
 !     H           PREDICTED STEP SIZE OF THE LAST ACCEPTED STEP
 !
 !     IDID        REPORTS ON SUCCESSFULNESS UPON RETURN:
 !                   IDID= 1  COMPUTATION SUCCESSFUL,
 !                   IDID= 2  COMPUT. SUCCESSFUL (INTERRUPTED BY SOLOUT)
 !                   IDID=-1  INPUT IS NOT CONSISTENT,
 !                   IDID=-2  LARGER NMAX IS NEEDED,
 !                   IDID=-3  STEP SIZE BECOMES TOO SMALL,
 !                   IDID=-4  MATRIX IS REPEATEDLY SINGULAR.
 !
 !   IWORK(14)  NFCN    NUMBER OF FUNCTION EVALUATIONS (THOSE FOR NUMERIC
 !                      EVALUATION OF THE JACOBIAN ARE NOT COUNTED)
 !   IWORK(15)  NJAC    NUMBER OF JACOBIAN EVALUATIONS (EITHER ANALYTICAL
 !                      OR NUMERICALLY)
 !   IWORK(16)  NSTEP   NUMBER OF COMPUTED STEPS
 !   IWORK(17)  NACCPT  NUMBER OF ACCEPTED STEPS
 !   IWORK(18)  NREJCT  NUMBER OF REJECTED STEPS (DUE TO ERROR TEST),
 !                      (STEP REJECTIONS IN THE FIRST STEP ARE NOT COUNTE
 !   IWORK(19)  NDEC    NUMBER OF LU-DECOMPOSITIONS OF BOTH MATRICES
 !   IWORK(20)  NSOL    NUMBER OF FORWARD-BACKWARD SUBSTITUTIONS, OF BOTH
 !                      SYSTEMS; THE NSTEP FORWARD-BACKWARD SUBSTITUTIONS
 !                      NEEDED FOR STEP SIZE SELECTION, ARE NOT COUNTED
 !-----------------------------------------------------------------------
 ! *** *** *** *** *** *** *** *** *** *** *** *** ***
 !          DECLARATIONS
 ! *** *** *** *** *** *** *** *** *** *** *** *** ***
       IMPLICIT DOUBLE PRECISION (a-h,o-z)
       dimension y(n),atol(*),rtol(*),work(lwork),iwork(liwork)
       dimension rpar(*),ipar(*)
       LOGICAL implct,jband,arret,startn,pred
       EXTERNAL fcn,jac,mas,solout
 ! *** *** *** *** *** *** ***
 !        SETTING THE PARAMETERS
 ! *** *** *** *** *** *** ***
        nfcn=0
        njac=0
        nstep=0
        naccpt=0
        nrejct=0
        ndec=0
        nsol=0
        arret=.false.
 ! -------- UROUND   SMALLEST NUMBER SATISFYING 1.0D0+UROUND>1.0D0
       IF (work(1).EQ.0.0d0) THEN
          uround=1.0d-16
       ELSE
          uround=work(1)
          IF (uround.LE.1.0d-19.OR.uround.GE.1.0d0) THEN
             WRITE(6,*)' COEFFICIENTS HAVE 20 DIGITS, UROUND=',work(1)
             arret=.true.
          END IF
       END IF
 ! -------- CHECK AND CHANGE THE TOLERANCES
       expm=2.0d0/3.0d0
       IF (itol.EQ.0) THEN
           IF (atol(1).LE.0.d0.OR.rtol(1).LE.10.d0*uround) THEN
               WRITE (6,*) ' TOLERANCES ARE TOO SMALL'
               arret=.true.
           ELSE
               quot=atol(1)/rtol(1)
               rtol(1)=0.1d0*rtol(1)**expm
               atol(1)=rtol(1)*quot
           END IF
       ELSE
           DO i=1,n
           IF (atol(i).LE.0.d0.OR.rtol(i).LE.10.d0*uround) THEN
               WRITE (6,*) ' TOLERANCES(',i,') ARE TOO SMALL'
               arret=.true.
           ELSE
               quot=atol(i)/rtol(i)
               rtol(i)=0.1d0*rtol(i)**expm
               atol(i)=rtol(i)*quot
           END IF
           END DO
       END IF
 ! -------- NMAX , THE MAXIMAL NUMBER OF STEPS -----
       IF (iwork(2).EQ.0) THEN
          nmax=100000
       ELSE
          nmax=iwork(2)
          IF (nmax.LE.0) THEN
             WRITE(6,*)' WRONG INPUT IWORK(2)=',iwork(2)
             arret=.true.
          END IF
       END IF
 ! -------- NIT    MAXIMAL NUMBER OF NEWTON ITERATIONS
       IF (iwork(3).EQ.0) THEN
          nit=7
       ELSE
          nit=iwork(3)
          IF (nit.LE.0) THEN
             WRITE(6,*)' CURIOUS INPUT IWORK(3)=',iwork(3)
             arret=.true.
          END IF
       END IF
 ! -------- STARTN  SWITCH FOR STARTING VALUES OF NEWTON ITERATIONS
       IF(iwork(4).EQ.0)THEN
          startn=.false.
       ELSE
          startn=.true.
       END IF
 ! -------- PARAMETER FOR DIFFERENTIAL-ALGEBRAIC COMPONENTS
       nind1=iwork(5)
       nind2=iwork(6)
       nind3=iwork(7)
       IF (nind1.EQ.0) nind1=n
       IF (nind1+nind2+nind3.NE.n) THEN
        WRITE(6,*)' CURIOUS INPUT FOR IWORK(5,6,7)=',nind1,nind2,nind3
        arret=.true.
       END IF
 ! -------- PRED   STEP SIZE CONTROL
       IF(iwork(8).LE.1)THEN
          pred=.true.
       ELSE
          pred=.false.
       END IF
 ! -------- PARAMETER FOR SECOND ORDER EQUATIONS
       m1=iwork(9)
       m2=iwork(10)
       nm1=n-m1
       IF (m1.EQ.0) m2=n
       IF (m2.EQ.0) m2=m1
       IF (m1.LT.0.OR.m2.LT.0.OR.m1+m2.GT.n) THEN
        WRITE(6,*)' CURIOUS INPUT FOR IWORK(9,10)=',m1,m2
        arret=.true.
       END IF
 ! --------- SAFE     SAFETY FACTOR IN STEP SIZE PREDICTION
       IF (work(2).EQ.0.0d0) THEN
          safe=0.9d0
       ELSE
          safe=work(2)
          IF (safe.LE.0.001d0.OR.safe.GE.1.0d0) THEN
             WRITE(6,*)' CURIOUS INPUT FOR WORK(2)=',work(2)
             arret=.true.
          END IF
       END IF
 ! ------ THET     DECIDES WHETHER THE JACOBIAN SHOULD BE RECOMPUTED;
       IF (work(3).EQ.0.d0) THEN
          thet=0.001d0
       ELSE
          thet=work(3)
          IF (thet.GE.1.0d0) THEN
             WRITE(6,*)' CURIOUS INPUT FOR WORK(3)=',work(3)
             arret=.true.
          END IF
       END IF
 ! --- FNEWT   STOPPING CRITERION FOR NEWTON'S METHOD, USUALLY CHOSEN <1.
       tolst=rtol(1)
       IF (work(4).EQ.0.d0) THEN
          fnewt=max(10*uround/tolst,min(0.03d0,tolst**0.5d0))
       ELSE
          fnewt=work(4)
          IF (fnewt.LE.uround/tolst) THEN
             WRITE(6,*)' CURIOUS INPUT FOR WORK(4)=',work(4)
             arret=.true.
          END IF
       END IF
 ! --- QUOT1 AND QUOT2: IF QUOT1 < HNEW/HOLD < QUOT2, STEP SIZE = CONST.
       IF (work(5).EQ.0.d0) THEN
          quot1=1.d0
       ELSE
          quot1=work(5)
       END IF
       IF (work(6).EQ.0.d0) THEN
          quot2=1.2d0
       ELSE
          quot2=work(6)
       END IF
       IF (quot1.GT.1.0d0.OR.quot2.LT.1.0d0) THEN
          WRITE(6,*)' CURIOUS INPUT FOR WORK(5,6)=',quot1,quot2
          arret=.true.
       END IF
 ! -------- MAXIMAL STEP SIZE
       IF (work(7).EQ.0.d0) THEN
          hmax=xend-x
       ELSE
          hmax=work(7)
       END IF
 ! -------  FACL,FACR     PARAMETERS FOR STEP SIZE SELECTION
       IF(work(8).EQ.0.d0)THEN
          facl=5.d0
       ELSE
          facl=1.d0/work(8)
       END IF
       IF(work(9).EQ.0.d0)THEN
          facr=1.d0/8.0d0
       ELSE
          facr=1.d0/work(9)
       END IF
       IF (facl.LT.1.0d0.OR.facr.GT.1.0d0) THEN
             WRITE(6,*)' CURIOUS INPUT WORK(8,9)=',work(8),work(9)
             arret=.true.
          END IF
 ! *** *** *** *** *** *** *** *** *** *** *** *** ***
 !         COMPUTATION OF ARRAY ENTRIES
 ! *** *** *** *** *** *** *** *** *** *** *** *** ***
 ! ---- IMPLICIT, BANDED OR NOT ?
       implct=imas.NE.0
       jband=mljac.LT.nm1
 ! -------- COMPUTATION OF THE ROW-DIMENSIONS OF THE 2-ARRAYS ---
 ! -- JACOBIAN  AND  MATRICES E1, E2
       IF (jband) THEN
          ldjac=mljac+mujac+1
          lde1=mljac+ldjac
       ELSE
          mljac=nm1
          mujac=nm1
          ldjac=nm1
          lde1=nm1
       END IF
 ! -- MASS MATRIX
       IF (implct) THEN
           IF (mlmas.NE.nm1) THEN
               ldmas=mlmas+mumas+1
               IF (jband) THEN
                  ijob=4
               ELSE
                  ijob=3
               END IF
           ELSE
               mumas=nm1
               ldmas=nm1
               ijob=5
           END IF
 ! ------ BANDWITH OF "MAS" NOT SMALLER THAN BANDWITH OF "JAC"
           IF (mlmas.GT.mljac.OR.mumas.GT.mujac) THEN
              WRITE (6,*) 'BANDWITH OF "MAS" NOT SMALLER THAN BANDWITH OF&
      & "JAC"'
             arret=.true.
           END IF
       ELSE
           ldmas=0
           IF (jband) THEN
              ijob=2
           ELSE
              ijob=1
              IF (n.GT.2.AND.iwork(1).NE.0) ijob=7
           END IF
       END IF
       ldmas2=max(1,ldmas)
 ! ------ HESSENBERG OPTION ONLY FOR EXPLICIT EQU. WITH FULL JACOBIAN
       IF ((implct.OR.jband).AND.ijob.EQ.7) THEN
          WRITE(6,*)' HESSENBERG OPTION ONLY FOR EXPLICIT EQUATIONS WITH &
      &FULL JACOBIAN'
          arret=.true.
       END IF
 ! ------- PREPARE THE ENTRY-POINTS FOR THE ARRAYS IN WORK -----
       iez1=21
       iez2=iez1+n
       iez3=iez2+n
       iey0=iez3+n
       iescal=iey0+n
       ief1=iescal+n
       ief2=ief1+n
       ief3=ief2+n
       iecon=ief3+n
       iejac=iecon+4*n
       iemas=iejac+n*ldjac
       iee1=iemas+nm1*ldmas
       iee2r=iee1+nm1*lde1
       iee2i=iee2r+nm1*lde1
 ! ------ TOTAL STORAGE REQUIREMENT -----------
       istore=iee2i+nm1*lde1-1
       IF(istore.GT.lwork)THEN
          WRITE(6,*)' INSUFFICIENT STORAGE FOR WORK, MIN. LWORK=',istore
          arret=.true.
       END IF
 ! ------- ENTRY POINTS FOR INTEGER WORKSPACE -----
       ieip1=21
       ieip2=ieip1+nm1
       ieiph=ieip2+nm1
 ! --------- TOTAL REQUIREMENT ---------------
       istore=ieiph+nm1-1
       IF (istore.GT.liwork) THEN
          WRITE(6,*)' INSUFF. STORAGE FOR IWORK, MIN. LIWORK=',istore
          arret=.true.
       END IF
 ! ------ WHEN A FAIL HAS OCCURED, WE RETURN WITH IDID=-1
       IF (arret) THEN
          idid=-1
          RETURN
       END IF
 ! -------- CALL TO CORE INTEGRATOR ------------
       CALL radcor(n,fcn,x,y,xend,hmax,h,rtol,atol,itol,                 &
      &   jac,ijac,mljac,mujac,mas,mlmas,mumas,solout,iout,idid,         &
      &   nmax,uround,safe,thet,fnewt,quot1,quot2,nit,ijob,startn,       &
      &   nind1,nind2,nind3,pred,facl,facr,m1,m2,nm1,                    &
      &   implct,jband,ldjac,lde1,ldmas2,work(iez1),work(iez2),          &
      &   work(iez3),work(iey0),work(iescal),work(ief1),work(ief2),      &
      &   work(ief3),work(iejac),work(iee1),work(iee2r),work(iee2i),     &
      &   work(iemas),iwork(ieip1),iwork(ieip2),iwork(ieiph),            &
      &   work(iecon),nfcn,njac,nstep,naccpt,nrejct,ndec,nsol,rpar,ipar)
       iwork(14)=nfcn
       iwork(15)=njac
       iwork(16)=nstep
       iwork(17)=naccpt
       iwork(18)=nrejct
       iwork(19)=ndec
       iwork(20)=nsol
 ! -------- RESTORE TOLERANCES
       expm=1.0d0/expm
       IF (itol.EQ.0) THEN
               quot=atol(1)/rtol(1)
               rtol(1)=(10.0d0*rtol(1))**expm
               atol(1)=rtol(1)*quot
       ELSE
           DO i=1,n
               quot=atol(i)/rtol(i)
               rtol(i)=(10.0d0*rtol(i))**expm
               atol(i)=rtol(i)*quot
           END DO
       END IF
 ! ----------- RETURN -----------
       RETURN
subroutine radcor (N, external FCN, X, dimension(n) Y, XEND, HMAX, H, dimension(*) RTOL, dimension(*) ATOL, ITOL, JAC, IJAC, MLJAC, MUJAC, MAS, MLMAS, MUMAS, SOLOUT, IOUT, IDID, NMAX, UROUND, SAFE, THET, FNEWT, QUOT1, QUOT2, NIT, IJOB, logical STARTN, NIND1, NIND2, NIND3, logical PRED, FACL, FACR, M1, M2, NM1, logical IMPLCT, logical BANDED, LDJAC, LDE1, LDMAS, dimension(n) Z1, dimension(n) Z2, dimension(n) Z3, dimension(n) Y0, dimension(n) SCAL, dimension(n) F1, dimension(n) F2, dimension(n) F3, dimension(ldjac,n) FJAC, dimension(lde1,nm1) E1, dimension(lde1,nm1) E2R, dimension(lde1,nm1) E2I, dimension(ldmas,nm1) FMAS, integer, dimension(nm1) IP1, integer, dimension(nm1) IP2, integer, dimension(nm1) IPHES, dimension(4*n) CONT, NFCN, NJAC, NSTEP, NACCPT, NREJCT, NDEC, NSOL, dimension(*) RPAR, dimension(*) IPAR)
References decomc(), decomr(), estrad(), and slvrad().
Referenced by radau5().
 ! ----------------------------------------------------------
 !     CORE INTEGRATOR FOR RADAU5
 !     PARAMETERS SAME AS IN RADAU5 WITH WORKSPACE ADDED
 ! ----------------------------------------------------------
 !         DECLARATIONS
 ! ----------------------------------------------------------
       IMPLICIT DOUBLE PRECISION (a-h,o-z)
       dimension y(n),z1(n),z2(n),z3(n),y0(n),scal(n),f1(n),f2(n),f3(n)
       dimension fjac(ldjac,n),fmas(ldmas,nm1),cont(4*n)
       dimension e1(lde1,nm1),e2r(lde1,nm1),e2i(lde1,nm1)
       dimension atol(*),rtol(*),rpar(*),ipar(*)
       INTEGER ip1(nm1),ip2(nm1),iphes(nm1)
       COMMON /conra5/nn,nn2,nn3,nn4,xsol,hsol,c2m1,c1m1
       common/linal/mle,mue,mbjac,mbb,mdiag,mdiff,mbdiag
       LOGICAL reject,first,implct,banded,caljac,startn,calhes
       LOGICAL index1,index2,index3,last,pred
       EXTERNAL fcn
 ! *** *** *** *** *** *** ***
 !  INITIALISATIONS
 ! *** *** *** *** *** *** ***
 ! --------- DUPLIFY N FOR COMMON BLOCK CONT -----
       nn=n
       nn2=2*n
       nn3=3*n
       lrc=4*n
 ! -------- CHECK THE INDEX OF THE PROBLEM -----
       index1=nind1.NE.0
       index2=nind2.NE.0
       index3=nind3.NE.0
 ! ------- COMPUTE MASS MATRIX FOR IMPLICIT CASE ----------
       IF (implct) CALL mas(nm1,fmas,ldmas,rpar,ipar)
 ! ---------- CONSTANTS ---------
       sq6=dsqrt(6.d0)
       c1=(4.d0-sq6)/10.d0
       c2=(4.d0+sq6)/10.d0
       c1m1=c1-1.d0
       c2m1=c2-1.d0
       c1mc2=c1-c2
       dd1=-(13.d0+7.d0*sq6)/3.d0
       dd2=(-13.d0+7.d0*sq6)/3.d0
       dd3=-1.d0/3.d0
       u1=(6.d0+81.d0**(1.d0/3.d0)-9.d0**(1.d0/3.d0))/30.d0
       alph=(12.d0-81.d0**(1.d0/3.d0)+9.d0**(1.d0/3.d0))/60.d0
       beta=(81.d0**(1.d0/3.d0)+9.d0**(1.d0/3.d0))*dsqrt(3.d0)/60.d0
       cno=alph**2+beta**2
       u1=1.0d0/u1
       alph=alph/cno
       beta=beta/cno
       t11=9.1232394870892942792d-02
       t12=-0.14125529502095420843d0
       t13=-3.0029194105147424492d-02
       t21=0.24171793270710701896d0
       t22=0.20412935229379993199d0
       t23=0.38294211275726193779d0
       t31=0.96604818261509293619d0
       ti11=4.3255798900631553510d0
       ti12=0.33919925181580986954d0
       ti13=0.54177053993587487119d0
       ti21=-4.1787185915519047273d0
       ti22=-0.32768282076106238708d0
       ti23=0.47662355450055045196d0
       ti31=-0.50287263494578687595d0
       ti32=2.5719269498556054292d0
       ti33=-0.59603920482822492497d0
       IF (m1.GT.0) ijob=ijob+10
       posneg=sign(1.d0,xend-x)
       hmaxn=min(abs(hmax),abs(xend-x))
       IF (abs(h).LE.10.d0*uround) h=1.0d-6
       h=min(abs(h),hmaxn)
       h=sign(h,posneg)
       hold=h
       reject=.false.
       first=.true.
       last=.false.
       IF ((x+h*1.0001d0-xend)*posneg.GE.0.d0) THEN
          h=xend-x
          last=.true.
       END IF
       hopt=h
       faccon=1.d0
       cfac=safe*(1+2*nit)
       nsing=0
       xold=x
       IF (iout.NE.0) THEN
           irtrn=1
           nrsol=1
           xosol=xold
           xsol=x
           DO i=1,n
              cont(i)=y(i)
           END DO
           nsolu=n
           hsol=hold
           CALL solout(nrsol,xosol,xsol,y,cont,lrc,nsolu,                &
      &                rpar,ipar,irtrn)
           IF (irtrn.LT.0) GOTO 179
       END IF
       mle=mljac
       mue=mujac
       mbjac=mljac+mujac+1
       mbb=mlmas+mumas+1
       mdiag=mle+mue+1
       mdiff=mle+mue-mumas
       mbdiag=mumas+1
       n2=2*n
       n3=3*n
       IF (itol.EQ.0) THEN
           DO i=1,n
              scal(i)=atol(1)+rtol(1)*abs(y(i))
           END DO
       ELSE
           DO i=1,n
              scal(i)=atol(i)+rtol(i)*abs(y(i))
           END DO
       END IF
       hhfac=h
       CALL fcn(n,x,y,y0,rpar,ipar)
       nfcn=nfcn+1
 ! --- BASIC INTEGRATION STEP
    10 CONTINUE
 ! *** *** *** *** *** *** ***
 !  COMPUTATION OF THE JACOBIAN
 ! *** *** *** *** *** *** ***
       njac=njac+1
       IF (ijac.EQ.0) THEN
 ! --- COMPUTE JACOBIAN MATRIX NUMERICALLY
          IF (banded) THEN
 ! --- JACOBIAN IS BANDED
             mujacp=mujac+1
             md=min(mbjac,m2)
             DO mm=1,m1/m2+1
                DO k=1,md
                   j=k+(mm-1)*m2
    12             f1(j)=y(j)
                   f2(j)=dsqrt(uround*max(1.d-5,abs(y(j))))
                   y(j)=y(j)+f2(j)
                   j=j+md
                   IF (j.LE.mm*m2) GOTO 12
                   CALL fcn(n,x,y,cont,rpar,ipar)
                   j=k+(mm-1)*m2
                   j1=k
                   lbeg=max(1,j1-mujac)+m1
    14             lend=min(m2,j1+mljac)+m1
                   y(j)=f1(j)
                   mujacj=mujacp-j1-m1
                   DO l=lbeg,lend
                      fjac(l+mujacj,j)=(cont(l)-y0(l))/f2(j)
                   END DO
                   j=j+md
                   j1=j1+md
                   lbeg=lend+1
                   IF (j.LE.mm*m2) GOTO 14
                END DO
             END DO
          ELSE
 ! --- JACOBIAN IS FULL
             DO i=1,n
                ysafe=y(i)
                delt=dsqrt(uround*max(1.d-5,abs(ysafe)))
                y(i)=ysafe+delt
                CALL fcn(n,x,y,cont,rpar,ipar)
                DO j=m1+1,n
                  fjac(j-m1,i)=(cont(j)-y0(j))/delt
                END DO
                y(i)=ysafe
             END DO
          END IF
       ELSE
 ! --- COMPUTE JACOBIAN MATRIX ANALYTICALLY
          CALL jac(n,x,y,fjac,ldjac,rpar,ipar)
       END IF
       caljac=.true.
       calhes=.true.
    20 CONTINUE
 ! --- COMPUTE THE MATRICES E1 AND E2 AND THEIR DECOMPOSITIONS
       fac1=u1/h
       alphn=alph/h
       betan=beta/h
       CALL decomr(n,fjac,ldjac,fmas,ldmas,mlmas,mumas,                  &
      &            m1,m2,nm1,fac1,e1,lde1,ip1,ier,ijob,calhes,iphes)
       IF (ier.NE.0) GOTO 78
       CALL decomc(n,fjac,ldjac,fmas,ldmas,mlmas,mumas,                  &
      &            m1,m2,nm1,alphn,betan,e2r,e2i,lde1,ip2,ier,ijob)
       IF (ier.NE.0) GOTO 78
       ndec=ndec+1
    30 CONTINUE
       nstep=nstep+1
       IF (nstep.GT.nmax) GOTO 178
       IF (0.1d0*abs(h).LE.abs(x)*uround) GOTO 177
           IF (index2) THEN
              DO i=nind1+1,nind1+nind2
                 scal(i)=scal(i)/hhfac
              END DO
           END IF
           IF (index3) THEN
              DO i=nind1+nind2+1,nind1+nind2+nind3
                 scal(i)=scal(i)/(hhfac*hhfac)
              END DO
           END IF
       xph=x+h
 ! *** *** *** *** *** *** ***
 !  STARTING VALUES FOR NEWTON ITERATION
 ! *** *** *** *** *** *** ***
       IF (first.OR.startn) THEN
          DO i=1,n
             z1(i)=0.d0
             z2(i)=0.d0
             z3(i)=0.d0
             f1(i)=0.d0
             f2(i)=0.d0
             f3(i)=0.d0
          END DO
       ELSE
          c3q=h/hold
          c1q=c1*c3q
          c2q=c2*c3q
          DO i=1,n
             ak1=cont(i+n)
             ak2=cont(i+n2)
             ak3=cont(i+n3)
             z1i=c1q*(ak1+(c1q-c2m1)*(ak2+(c1q-c1m1)*ak3))
             z2i=c2q*(ak1+(c2q-c2m1)*(ak2+(c2q-c1m1)*ak3))
             z3i=c3q*(ak1+(c3q-c2m1)*(ak2+(c3q-c1m1)*ak3))
             z1(i)=z1i
             z2(i)=z2i
             z3(i)=z3i
             f1(i)=ti11*z1i+ti12*z2i+ti13*z3i
             f2(i)=ti21*z1i+ti22*z2i+ti23*z3i
             f3(i)=ti31*z1i+ti32*z2i+ti33*z3i
          END DO
       END IF
 ! *** *** *** *** *** *** ***
 !  LOOP FOR THE SIMPLIFIED NEWTON ITERATION
 ! *** *** *** *** *** *** ***
             newt=0
             faccon=max(faccon,uround)**0.8d0
             theta=abs(thet)
    40       CONTINUE
             IF (newt.GE.nit) GOTO 78
 ! ---     COMPUTE THE RIGHT-HAND SIDE
             DO i=1,n
                cont(i)=y(i)+z1(i)
             END DO
             CALL fcn(n,x+c1*h,cont,z1,rpar,ipar)
             DO i=1,n
                cont(i)=y(i)+z2(i)
             END DO
             CALL fcn(n,x+c2*h,cont,z2,rpar,ipar)
             DO i=1,n
                cont(i)=y(i)+z3(i)
             END DO
             CALL fcn(n,xph,cont,z3,rpar,ipar)
             nfcn=nfcn+3
 ! ---     SOLVE THE LINEAR SYSTEMS
            DO i=1,n
               a1=z1(i)
               a2=z2(i)
               a3=z3(i)
               z1(i)=ti11*a1+ti12*a2+ti13*a3
               z2(i)=ti21*a1+ti22*a2+ti23*a3
               z3(i)=ti31*a1+ti32*a2+ti33*a3
            END DO
         CALL slvrad(n,fjac,ldjac,mljac,mujac,fmas,ldmas,mlmas,mumas,    &
      &          m1,m2,nm1,fac1,alphn,betan,e1,e2r,e2i,lde1,z1,z2,z3,    &
      &          f1,f2,f3,cont,ip1,ip2,iphes,ier,ijob)
             nsol=nsol+1
             newt=newt+1
             dyno=0.d0
             DO i=1,n
                denom=scal(i)
                dyno=dyno+(z1(i)/denom)**2+(z2(i)/denom)**2              &
      &          +(z3(i)/denom)**2
             END DO
             dyno=dsqrt(dyno/n3)
 ! ---     BAD CONVERGENCE OR NUMBER OF ITERATIONS TO LARGE
             IF (newt.GT.1.AND.newt.LT.nit) THEN
                 thq=dyno/dynold
                 IF (newt.EQ.2) THEN
                    theta=thq
                 ELSE
                    theta=sqrt(thq*thqold)
                 END IF
                 thqold=thq
                 IF (theta.LT.0.99d0) THEN
                     faccon=theta/(1.0d0-theta)
                     dyth=faccon*dyno*theta**(nit-1-newt)/fnewt
                     IF (dyth.GE.1.0d0) THEN
                          qnewt=dmax1(1.0d-4,dmin1(20.0d0,dyth))
                          hhfac=.8d0*qnewt**(-1.0d0/(4.0d0+nit-1-newt))
                          h=hhfac*h
                          reject=.true.
                          last=.false.
                          IF (caljac) GOTO 20
                          GOTO 10
                     END IF
                 ELSE
                     GOTO 78
                 END IF
             END IF
             dynold=max(dyno,uround)
             DO i=1,n
                f1i=f1(i)+z1(i)
                f2i=f2(i)+z2(i)
                f3i=f3(i)+z3(i)
                f1(i)=f1i
                f2(i)=f2i
                f3(i)=f3i
                z1(i)=t11*f1i+t12*f2i+t13*f3i
                z2(i)=t21*f1i+t22*f2i+t23*f3i
                z3(i)=t31*f1i+    f2i
             END DO
             IF (faccon*dyno.GT.fnewt) GOTO 40
 ! --- ERROR ESTIMATION
       CALL estrad (n,fjac,ldjac,mljac,mujac,fmas,ldmas,mlmas,mumas,     &
      &          h,dd1,dd2,dd3,fcn,nfcn,y0,y,ijob,x,m1,m2,nm1,           &
      &          e1,lde1,z1,z2,z3,cont,f1,f2,ip1,iphes,scal,err,         &
      &          first,reject,fac1,rpar,ipar)
 ! --- COMPUTATION OF HNEW
 ! --- WE REQUIRE .2<=HNEW/H<=8.
       fac=min(safe,cfac/(newt+2*nit))
       quot=max(facr,min(facl,err**.25d0/fac))
       hnew=h/quot
 ! *** *** *** *** *** *** ***
 !  IS THE ERROR SMALL ENOUGH ?
 ! *** *** *** *** *** *** ***
       IF (err.LT.1.d0) THEN
 ! --- STEP IS ACCEPTED
          first=.false.
          naccpt=naccpt+1
          IF (pred) THEN
 !       --- PREDICTIVE CONTROLLER OF GUSTAFSSON
             IF (naccpt.GT.1) THEN
                facgus=(hacc/h)*(err**2/erracc)**0.25d0/safe
                facgus=max(facr,min(facl,facgus))
                quot=max(quot,facgus)
                hnew=h/quot
             END IF
             hacc=h
             erracc=max(1.0d-2,err)
          END IF
          xold=x
          hold=h
          x=xph
          DO i=1,n
             y(i)=y(i)+z3(i)
             z2i=z2(i)
             z1i=z1(i)
             cont(i+n)=(z2i-z3(i))/c2m1
             ak=(z1i-z2i)/c1mc2
             acont3=z1i/c1
             acont3=(ak-acont3)/c2
             cont(i+n2)=(ak-cont(i+n))/c1m1
             cont(i+n3)=cont(i+n2)-acont3
          END DO
          IF (itol.EQ.0) THEN
              DO i=1,n
                 scal(i)=atol(1)+rtol(1)*abs(y(i))
              END DO
          ELSE
              DO i=1,n
                 scal(i)=atol(i)+rtol(i)*abs(y(i))
              END DO
          END IF
          IF (iout.NE.0) THEN
              nrsol=naccpt+1
              xsol=x
              xosol=xold
              DO i=1,n
                 cont(i)=y(i)
              END DO
              nsolu=n
              hsol=hold
              CALL solout(nrsol,xosol,xsol,y,cont,lrc,nsolu,             &
      &                   rpar,ipar,irtrn)
              IF (irtrn.LT.0) GOTO 179
          END IF
          caljac=.false.
          IF (last) THEN
             h=hopt
             idid=1
             RETURN
          END IF
          CALL fcn(n,x,y,y0,rpar,ipar)
          nfcn=nfcn+1
          hnew=posneg*min(abs(hnew),hmaxn)
          hopt=hnew
          hopt=min(h,hnew)
          IF (reject) hnew=posneg*min(abs(hnew),abs(h))
          reject=.false.
          IF ((x+hnew/quot1-xend)*posneg.GE.0.d0) THEN
             h=xend-x
             last=.true.
          ELSE
             qt=hnew/h
             hhfac=h
             IF (theta.LE.thet.AND.qt.GE.quot1.AND.qt.LE.quot2) GOTO 30
             h=hnew
          END IF
          hhfac=h
          IF (theta.LE.thet) GOTO 20
          GOTO 10
       ELSE
 ! --- STEP IS REJECTED
          reject=.true.
          last=.false.
          IF (first) THEN
              h=h*0.1d0
              hhfac=0.1d0
          ELSE
              hhfac=hnew/h
              h=hnew
          END IF
          IF (naccpt.GE.1) nrejct=nrejct+1
          IF (caljac) GOTO 20
          GOTO 10
       END IF
 ! --- UNEXPECTED STEP-REJECTION
    78 CONTINUE
       IF (ier.NE.0) THEN
           nsing=nsing+1
           IF (nsing.GE.5) GOTO 176
       END IF
       h=h*0.5d0
       hhfac=0.5d0
       reject=.true.
       last=.false.
       IF (caljac) GOTO 20
       GOTO 10
 ! --- FAIL EXIT
   176 CONTINUE
       WRITE(6,979)x
       WRITE(6,*) ' MATRIX IS REPEATEDLY SINGULAR, IER=',ier
       idid=-4
       RETURN
   177 CONTINUE
       WRITE(6,979)x
       WRITE(6,*) ' STEP SIZE T0O SMALL, H=',h
       idid=-3
       RETURN
   178 CONTINUE
       WRITE(6,979)x
       WRITE(6,*) ' MORE THAN NMAX =',nmax,'STEPS ARE NEEDED'
       idid=-2
       RETURN
 ! --- EXIT CAUSED BY SOLOUT
   179 CONTINUE
       WRITE(6,979)x
   979 FORMAT(' EXIT OF RADAU5 AT X=',e18.4)
       idid=2
       RETURN
double precision function contr5 (I, X, dimension(lrc) CONT, LRC)
 ! ----------------------------------------------------------
 !     THIS FUNCTION CAN BE USED FOR CONINUOUS OUTPUT. IT PROVIDES AN
 !     APPROXIMATION TO THE I-TH COMPONENT OF THE SOLUTION AT X.
 !     IT GIVES THE VALUE OF THE COLLOCATION POLYNOMIAL, DEFINED FOR
 !     THE LAST SUCCESSFULLY COMPUTED STEP (BY RADAU5).
 ! ----------------------------------------------------------
       IMPLICIT DOUBLE PRECISION (a-h,o-z)
       dimension cont(lrc)
       COMMON /conra5/nn,nn2,nn3,nn4,xsol,hsol,c2m1,c1m1
       s=(x-xsol)/hsol
       contr5=cont(i)+s*(cont(i+nn)+(s-c2m1)*(cont(i+nn2)                &
      &     +(s-c1m1)*cont(i+nn3)))
       RETURN