ORIGEN API: YieldResource Class Reference
YieldResource Class Reference
#include <YieldResource.h>
Public Member Functions
YieldResource ()
~YieldResource ()
YieldParent * fissionable (int izzzaaa)
get fissionable nuclide (null if not present)
const YieldParent * fissionable (int izzzaaa) const
get fissionable nuclide (null if not present)
YieldParent & add_fissionable (int izzzaaa)
add new fissionable nuclide (return if present)
int num_fissionables () const
num fissionable nuclides
bool has_fissionable (int izzzaaa) const
fissionable nuclide with that izzzaaa exists
int fissionable_index (int izzzaaa) const
index of fissionable (-1 if not present)
void get_fissionable_ids (Vec_Int *) const
get fissionable nuclide ids
const YieldParent & fissionable_at (int index) const
fissionable at
YieldParent & fissionable_at (int index)
fissionable at
void clear ()
clear contents
void get_all_energies (Vec_Dbl *energies) const
get all energies
int num_fps (int izzzaaa) const
num fission products
void get_interp_data (Vec_Int *fp_izzzaaa_list, Vec_Vec_Dbl *yields, const double energy, const int interp=INTERP_PREFERRED) const
compute fission yields for all isotopes from an energy
bool has_fp (int izzzaaa, const int fp_izzzaaa) const
fissionable nuclide has a yield defined
double interp_yield (int izzzaaa, int fp_izzzaaa, double energy, int interp_method=INTERP_PREFERRED) const
interp yield
bool remove_fissionable (int izzzaaa)
remove one fissionable
void set_fissionable_ids (const Vec_Int &ids)
keep only these fissionables
void set_fp_ids (const Vec_Int &ids)
keep only these fp across all fissionables
bool check (Vec_Str &errors) const
perform all checks
bool check_consistency (Vec_Str &errors) const
check consistency
bool check_ids (Vec_Str &errors) const
check ids
Scale::Json::Value to_json () const
deprecated
Protected Member Functions
const ParentMap_t & fissionable_map () const
get const parent map
ParentMap_t & fissionable_map ()
get parent map
const std::vector< YieldParent > & fissionables () const
get const fissionables vector
std::vector< YieldParent > & fissionables ()
get fissionables vector
Private Attributes
ParentMap_t b_fissionable_map
std::vector< YieldParent > b_fissionables
Detailed Description
Examples:
Core/io/tests/tstYieldResourceIO.cpp, Core/re/tests/tstYieldResource.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Constructor & Destructor Documentation
YieldResource ()
 {
     jDebugTaggedLine( "constructed YieldResource" );
 }
~YieldResource ()
 {
     jDebugTaggedLine( "destructed YieldResource" );
 }
Member Function Documentation
YieldParent * fissionable (int izzzaaa)
get fissionable nuclide (null if not present)
Examples:
Core/re/tests/tstYieldResource.cpp.
Referenced by YieldResource::has_fp(), inject_fission_yields(), YieldResource::interp_yield(), YieldResource::num_fps(), Origen::populateLibraryHeader_YieldResource(), Origen::printInterpolatedYields(), and TEST().
 {
     return const_cast<YieldParent*>(
         static_cast<const YieldResource*>( this )->fissionable( izzzaaa ) );
 }
const YieldParent * fissionable (int izzzaaa) const
get fissionable nuclide (null if not present)
References YieldResource::b_fissionables, and YieldResource::fissionable_index().
 {
     int k = fissionable_index( izzzaaa );
     if( k != -1 )
     {
         return &b_fissionables[k];
     }
     return nullptr;
 }
YieldParent & add_fissionable (int izzzaaa)
add new fissionable nuclide (return if present)
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldResource::b_fissionable_map, YieldResource::b_fissionables, YieldResource::fissionable_index(), and YieldResource::num_fissionables().
Referenced by main(), YieldResourceIO_stab1::read(), and TEST().
 {
     int k = fissionable_index( izzzaaa );
     // if doesn't exist add it
     if( k == -1 )
     {
         k = num_fissionables();
         b_fissionable_map[izzzaaa] = k;
         b_fissionables.push_back( YieldParent( izzzaaa ) );
     }
     return b_fissionables[k];
 }
int num_fissionables () const
num fissionable nuclides
References YieldResource::b_fissionables.
Referenced by YieldResource::add_fissionable(), YieldResource::fissionable_at(), YieldResource::get_all_energies(), ReactionResource::import_fission_yields(), Origen::loadMulti(), main(), print_yield_data(), Origen::printYieldEnergies(), Origen::printYields(), YieldResource::to_json(), and YieldResourceIO_stab1::write().
 { return b_fissionables.size(); }
bool has_fissionable (int izzzaaa) const
fissionable nuclide with that izzzaaa exists
References YieldResource::fissionable_index().
Referenced by Origen::printInterpolatedYields().
 {
     return fissionable_index( id ) != -1;
 }
int fissionable_index (int izzzaaa) const
index of fissionable (-1 if not present)
References YieldResource::b_fissionable_map.
Referenced by YieldResource::add_fissionable(), YieldResource::fissionable(), YieldResource::has_fissionable(), YieldResource::remove_fissionable(), and YieldResource::set_fissionable_ids().
 {
     auto it = b_fissionable_map.find( izzzaaa );
     if( it != b_fissionable_map.end() )
     {
         return it->second;
     }
     return -1;
 }
void get_fissionable_ids (Vec_Int * ids) const
get fissionable nuclide ids
References YieldResource::b_fissionable_map.
Referenced by main(), Origen::printYieldEnergies(), and Origen::printYields().
 {
     ids->resize( b_fissionable_map.size() );
     auto it = b_fissionable_map.begin();
     auto end = b_fissionable_map.end();
     while( it != end )
     {
         ( *ids )[it->second] = it->first;
         ++it;
     }
 }
const YieldParent & fissionable_at (int index) const
fissionable at
References YieldResource::b_fissionables, and YieldResource::num_fissionables().
Referenced by YieldResource::fissionable_at(), YieldResource::get_all_energies(), ReactionResource::import_fission_yields(), main(), print_yield_data(), Origen::printYieldEnergies(), Origen::printYields(), YieldResource::to_json(), and YieldResourceIO_stab1::write().
 {
     Require( index >= 0 && index < num_fissionables() );
     return b_fissionables[index];
 }
YieldParent & fissionable_at (int index)
fissionable at
References YieldResource::fissionable_at().
 {
     return const_cast<YieldParent&>(
         static_cast<const YieldResource*>( this )->fissionable_at( index ) );
 }
void clear ()
clear contents
References YieldResource::b_fissionable_map, and YieldResource::b_fissionables.
Referenced by YieldResourceIO_stab1::read().
 {
     ParentMap_t().swap( b_fissionable_map );
     std::vector<YieldParent>().swap( b_fissionables );
 }
void get_all_energies (Vec_Dbl * energies) const
get all energies
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldResource::fissionable_at(), YieldParent::get_energies(), and YieldResource::num_fissionables().
Referenced by TEST().
 {
     energies->clear();
     for( int i = 0; i < num_fissionables(); ++i )
     {
         Vec_Dbl e;
         fissionable_at( i ).get_energies( &e );
         for( size_t j = 0; j < e.size(); ++j )
         {
             energies->push_back( e[j] );
         }
     }
     ScaleSTL::reverse_unique( energies );
 }
int num_fps (int izzzaaa) const
num fission products
References YieldResource::fissionable(), and YieldParent::num_fps().
Referenced by YieldResource::set_fp_ids().
 {
     const YieldParent* yp = fissionable( id );
     if( yp != nullptr )
     {
         return yp->num_fps();
     }
     return -1;
 }
void get_interp_data (Vec_Int * fp_izzzaaa_list, Vec_Vec_Dbl * yields, const double energy, const int interp = INTERP_PREFERRED) const
compute fission yields for all isotopes from an energy
bool has_fp (int izzzaaa, const int fp_izzzaaa) const
fissionable nuclide has a yield defined
References YieldResource::fissionable(), and YieldParent::has_fp().
 {
     const YieldParent* yp = fissionable( id );
     if( yp == nullptr )
     {
         return false;
     }
     else
     {
         return yp->has_fp( fp_id );
     }
 }
double interp_yield (int izzzaaa, int fp_izzzaaa, double energy, int interp_method = INTERP_PREFERRED) const
interp yield
References YieldResource::fissionable(), and YieldParent::interp_yield().
 {
     const YieldParent* yn = fissionable( id );
     if( yn != nullptr )
     {
         return yn->interp_yield( fp_id, energy, interp );
     }
     else
     {
         return 0.0;
     }
 }
bool remove_fissionable (int izzzaaa)
remove one fissionable
References YieldResource::b_fissionable_map, YieldResource::b_fissionables, YieldResource::fissionable_index(), and YieldResource::fissionable_map().
 {
     int index = fissionable_index( izzzaaa );
     if( index == -1 ) return false;
     b_fissionables.erase( b_fissionables.begin() + index );
     // rebuild map
     ParentMap_t fissionable_map;
     for( size_t i = 0; i < b_fissionables.size(); ++i )
     {
         int id = b_fissionables[i].id();
         fissionable_map[id] = i;
     }
     b_fissionable_map.swap( fissionable_map );
     return true;
 }
void set_fissionable_ids (const Vec_Int & ids)
keep only these fissionables
References YieldResource::b_fissionable_map, YieldResource::b_fissionables, YieldResource::fissionable_index(), YieldResource::fissionable_map(), and YieldResource::fissionables().
 {
     // get indices of fission products & create new fp_map
     Vec_Int indices( ids.size(), 0 );
     ParentMap_t fissionable_map;
     for( size_t j = 0; j < ids.size(); ++j )
     {
         indices[j] = fissionable_index( ids[j] );
         fissionable_map[ids[j]] = j;
     }
     b_fissionable_map.swap( fissionable_map );
     std::vector<YieldParent> fissionables;
     // copy over old data to new
     for( size_t j = 0; j < ids.size(); ++j )
     {
         int k = indices[j];
         if( k != -1 )
         {
             fissionables.push_back( b_fissionables[k] );
         }
         else
         {
             fissionables.push_back( YieldParent( ids[j] ) );  // new id is empty
         }
     }
     b_fissionables.swap( fissionables );
     Ensure( b_fissionable_map.size() == ids.size() );
     Ensure( b_fissionables.size() == ids.size() );
 }
void set_fp_ids (const Vec_Int & ids)
keep only these fp across all fissionables
References YieldResource::b_fissionables, and YieldResource::num_fps().
Referenced by main().
 {
     for( size_t i = 0; i < b_fissionables.size(); ++i )
     {
         b_fissionables[i].set_fp_ids( ids );
         Check( b_fissionables[i].num_fps() == ids.size() );
     }
 }
bool check (Vec_Str & errors) const
perform all checks
References YieldResource::check_consistency(), and YieldResource::check_ids().
Referenced by main().
 {
     bool pass = true;
     pass = pass && this->check_ids( errors );
     pass = pass && this->check_consistency( errors );
     return pass;
 }
bool check_consistency (Vec_Str & errors) const
check consistency
References YieldResource::b_fissionable_map, YieldResource::b_fissionables, YieldParent::data(), YieldData::energy(), YieldParent::fp_map(), YieldParent::id(), Origen::IMPLICIT_BYPRODUCT_MAX_MASSNUMBER, Origen::YIELD_TOLERANCE, and YieldData::yields().
Referenced by YieldResource::check().
 {
     size_t nErr = errors.size();
     auto ite = b_fissionable_map.end();
     for( auto it = b_fissionable_map.begin(); it != ite; ++it )
     {
         int id = it->first;
         const YieldParent& parent = b_fissionables[it->second];
         if( parent.id() != id )
         {
             errors.push_back(
                 nprintf( "Resource fissionable id=%d is "
                          "inconsistent with the parent id=%d\n",
                          parent.id(),
                          id ) );
         }
         for( size_t i = 0; i < parent.data().size(); i++ )
         {
             const YieldData& data = parent.data()[i];
             if( parent.fp_map().size() != data.yields().size() )
             {
                 std::stringstream ss;
                 ss << "Parent id=" << id
                    << " has inconsistent yield data size. NFPs="
                    << parent.fp_map().size() << " but yield set i=" << i + 1
                    << " has NFPs=" << data.yields().size();
                 errors.push_back( ss.str() );
             }
             double sum = 0;
             FPMap_t::const_iterator fp_it;
             for( fp_it = parent.fp_map().begin();
                  fp_it != parent.fp_map().end();
                  ++fp_it )
             {
                 int fp_iza = fp_it->first;
                 size_t j = fp_it->second;
                 int a = fp_iza % ScaleData::Utils::PIZZZAAA_Z_OFFSET;
                 if( a > IMPLICIT_BYPRODUCT_MAX_MASSNUMBER )
                 {
                     sum += data.yields()[j];
                 }
             }
             if( std::abs( sum - 2.0 ) > YIELD_TOLERANCE )
             {
                 std::stringstream ss;
                 ss << "Parent id=" << id
                    << " fission yields for set i=" << i + 1
                    << " do not meet tolerance requirement std::abs(sum-2.0)="
                    << std::abs( sum - 2.0 ) << ">" << YIELD_TOLERANCE << ".";
                 errors.push_back( ss.str() );
             }
             Check( data.energy() > 0 );
             // check that energies are increasing
             if( i > 0 )
             {
                 if( data.energy() < parent.data()[i - 1].energy() )
                 {
                     std::stringstream ss;
                     ss << "Parent id=" << id
                        << " has lower fission yield energy for set i=" << i + 1
                        << "than previous set";
                 }
             }
         }
     }
     // no errors were introduced
     return errors.size() == nErr;
 }
bool check_ids (Vec_Str & errors) const
check ids
References YieldResource::b_fissionable_map.
Referenced by YieldResource::check().
 {
     size_t nErr = errors.size();
     for( auto it = b_fissionable_map.begin(); it != b_fissionable_map.end();
          ++it )
     {
         int p, i, z, a;
         int id = it->first;
         ScaleData::Utils::split_pizzzaaa( id, p, i, z, a );
         if( p != 0 )
         {
             std::stringstream ss;
             ss << "The id=" << id << " has an invalid PREFIX=" << p
                << " which should be 0.";
             errors.push_back( ss.str() );
         }
         if( !ScaleData::Utils::is_valid_nuclide( i, z, a ) )
         {
             std::stringstream ss;
             ss << "The IZZZAAA id=" << id << " is invalid.";
             errors.push_back( ss.str() );
         }
     }
     return errors.size() == nErr;
 }
Json::Value to_json () const
deprecated
References YieldParent::data(), YieldResource::fissionable_at(), YieldParent::get_fp_ids(), YieldParent::id(), YieldParent::interp_method(), and YieldResource::num_fissionables().
 {
     // root
     Json::Value j_root( Json::objectValue );
     // root["parents"]
     Json::Value j_parents( Json::objectValue );
     for( int i = 0; i < num_fissionables(); ++i )
     {
         const YieldParent& parent = fissionable_at( i );
         int id = parent.id();
         // root["parents"][ID]
         Json::Value j_parent( Json::objectValue );
         // root["parents"][ID]["interp_method"]
         j_parent["interp_method"] = parent.interp_method();
         // root["parents"][ID]["data"][I], I=1,NUM_SETS
         Json::Value j_data( Json::arrayValue );
         for( size_t j = 0; j < parent.data().size(); j++ )
         {
             Json::Value j_data( Json::objectValue );
             // root["parents"][ID]["data"]["energy"]
             j_data["energy"] = parent.data()[j].energy();
             // root["parents"][ID]["data"]["yields"][J], J=1,NUM_FPS
             Standard::Json::arrayToJson( j_data["yields"],
                                          parent.data()[j].yields() );
             j_data.append( j_data );
         }
         j_parent["data"] = j_data;
         // root["parents"][ID]["fission_products"][J], J=1,NUM_FPS
         Vec_Int ids;
         parent.get_fp_ids( &ids );
         Standard::Json::arrayToJson( j_parent["fission_products"], ids );
         j_parents[std::to_string( id )] = j_parent;
     }
     j_root["parents"] = j_parents;
     return j_root;
 }
const ParentMap_t & fissionable_map () const protected
get const parent map
References YieldResource::b_fissionable_map.
Referenced by YieldResource::remove_fissionable(), and YieldResource::set_fissionable_ids().
 {
     return b_fissionable_map;
 }
ParentMap_t & fissionable_map () protected
get parent map
References YieldResource::b_fissionable_map.
 { return b_fissionable_map; }
const std::vector< YieldParent > & fissionables () const protected
get const fissionables vector
References YieldResource::b_fissionables.
Referenced by YieldResource::set_fissionable_ids().
 {
     return b_fissionables;
 }
std::vector< YieldParent > & fissionables () protected
get fissionables vector
References YieldResource::b_fissionables.
 {
     return b_fissionables;
 }
Member Data Documentation
ParentMap_t b_fissionable_map private
Referenced by YieldResource::add_fissionable(), YieldResource::check_consistency(), YieldResource::check_ids(), YieldResource::clear(), YieldResource::fissionable_index(), YieldResource::fissionable_map(), YieldResource::get_fissionable_ids(), YieldResource::remove_fissionable(), and YieldResource::set_fissionable_ids().
std::vector<YieldParent> b_fissionables private
Referenced by YieldResource::add_fissionable(), YieldResource::check_consistency(), YieldResource::clear(), YieldResource::fissionable(), YieldResource::fissionable_at(), YieldResource::fissionables(), YieldResource::num_fissionables(), YieldResource::remove_fissionable(), YieldResource::set_fissionable_ids(), and YieldResource::set_fp_ids().
The documentation for this class was generated from the following files:
Core/re/YieldResource.h
Core/re/YieldResource.cpp