OrigenAPI: LibraryBuilderTester Class Reference
LibraryBuilderTester Class Reference
Public Member Functions
void SetUp ()
Public Attributes
Origen::SP_NuclideResource nr
Origen::SP_DecayResource dr
Origen::SP_TransitionSystem ts
Origen::LibraryBuilder bld
Detailed Description
Definition at line 212 of file tstTransitionSystemAdapter_DecayResource.cpp.
Member Function Documentation
void LibraryBuilderTester::SetUp () inline
Definition at line 215 of file tstTransitionSystemAdapter_DecayResource.cpp.
References bld, Origen::defaultNuclideResource(), dr, Origen::TransitionSystemAdapter_DecayResource::extend(), Origen::loadDecayResource(), nr, Origen::LibraryBuilder::set_decay_resource(), Origen::LibraryBuilder::set_nuclide_resource(), and ts.
     {
         //
         // load decay resource
         //
         ScaleUtils::IO::DB opts;
         std::string decay_resource( Origen::decay_filepath );
         dr = Origen::SP_DecayResource(
             Origen::loadDecayResource( decay_resource, opts ) );
         Insist( opts.numError() == 0, "decay resource had errors" );
         //
         // load nuclide resource
         //
         nr = std::make_shared<Origen::NuclideResource>();
         Origen::defaultNuclideResource( &*nr );
         //
         // set on library builder
         //
         bld.set_decay_resource( dr );
         bld.set_nuclide_resource( nr );
         // create a transition system adapter to create a general transition
         // system from this data
         // see TransitionSystem and friends to_string methods
         Origen::TransitionSystemAdapter_DecayResource tsa;
         ts = std::make_shared<Origen::TransitionSystem_Gen>();
         tsa.extend( &*ts, true, *dr );
     }
Member Data Documentation
Origen::LibraryBuilder LibraryBuilderTester::bld
Definition at line 249 of file tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by SetUp().
Origen::SP_DecayResource LibraryBuilderTester::dr
Definition at line 247 of file tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by SetUp().
Origen::SP_NuclideResource LibraryBuilderTester::nr
Definition at line 246 of file tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by SetUp().
Origen::SP_TransitionSystem LibraryBuilderTester::ts
Definition at line 248 of file tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp