ORIGEN API: ChannelType_Reac Class Reference
ChannelType_Reac Class Reference
#include <ChannelType_Reac.h>
Channel type for (non-fission) reactions.
Public Types
typedef SP_ChannelType SP
strong pointer
typedef WP_ChannelType WP
weak pointer
INTERFACE<<Origen::ChannelType>>
See Origen::ChannelType for details.
int reaction_mt () const
void set_reaction_mt (int reaction_mt)
std::string reaction_mt_name () const
bool has_initialized_reaction_mt () const
int decay_mode () const
void set_decay_mode (int decay_mode)
std::string decay_mode_name () const
bool has_initialized_decay_mode () const
SP_Field field () const
void get_field (SP_Field &field) const
void set_field (SP_Field field)
bool has_initialized_field () const
bool is_reaction () const
bool is_decay () const
bool has_followon_decay () const
bool has_distribution_of_daughters () const
double num_residuals_per_event () const
int num_byproduct (const ByproductId byproduct_id) const
bool has_byproduct (const ByproductId byproduct_id) const
ByproductCount_t num_byproducts () const
void increment_num_byproducts (ByproductCount_t &num_byproducts) const
int delta_nucleus_protons () const
int delta_nucleus_neutrons () const
int delta_mass_number () const
int delta_charge_number () const
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
Public Member Functions
ChannelType_Reac ()
ChannelType_Reac (Field::SP field, int reaction_mt)
Static Public Member Functions
static int channel_id (int decay_mode)
channel id for decay only
static int channel_id (SP_Field field, int reaction_mt, int decay_mode=0)
channel id for reaction+decay
Private Member Functions
virtual int reaction_mt_impl () const
virtual void set_reaction_mt_impl (int reaction_mt)
virtual int decay_mode_impl () const
virtual void set_decay_mode_impl (int decay_mode)
virtual Field::SP field_impl () const
virtual void set_field_impl (Field::SP field)
virtual bool is_reaction_impl () const
virtual bool is_decay_impl () const
virtual bool has_followon_decay_impl () const
virtual bool has_distribution_of_daughters_impl () const
virtual double num_residuals_per_event_impl () const
virtual ByproductCount_t num_byproducts_impl () const
virtual int delta_nucleus_protons_impl () const
virtual int delta_nucleus_neutrons_impl () const
virtual int delta_mass_number_impl () const
virtual int delta_charge_number_impl () const
virtual bool good_impl (Vec_Str &errors) const
useful to chain
void update_byproducts ()
Private Attributes
Field::SP b_field
int b_reaction_mt
int b_delta_mass_number
int b_delta_charge_number
int b_delta_nucleus_protons
int b_delta_nucleus_neutrons
ByproductCount_t b_num_byproducts
Detailed Description
Channel type for (non-fission) reactions.
See also
ChannelType
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef SP_ChannelType SP inherited
strong pointer
typedef WP_ChannelType WP inherited
weak pointer
Constructor & Destructor Documentation
ChannelType_Reac ()
     : b_field( nullptr )
     , b_reaction_mt( BAD_INT )
     , b_delta_mass_number( BAD_INT )
     , b_delta_charge_number( BAD_INT )
     , b_delta_nucleus_protons( BAD_INT )
     , b_delta_nucleus_neutrons( BAD_INT )
 {
 }
ChannelType_Reac (Field::SP field, int reaction_mt)
References ChannelType::set_field(), and ChannelType::set_reaction_mt().
     : b_field( nullptr )
     , b_reaction_mt( BAD_INT )
     , b_delta_mass_number( BAD_INT )
     , b_delta_charge_number( BAD_INT )
     , b_delta_nucleus_protons( BAD_INT )
     , b_delta_nucleus_neutrons( BAD_INT )
 {
     set_reaction_mt( reaction_mt );
     set_field( field );
 }
Member Function Documentation
int reaction_mt_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_reaction_mt.
 { return b_reaction_mt; }
void set_reaction_mt_impl (int reaction_mt) private virtual
Implements ChannelType.
References ChannelType_Reac::b_reaction_mt, ChannelType::reaction_mt(), and ChannelType_Reac::update_byproducts().
 {
     b_reaction_mt = reaction_mt;
     update_byproducts();
 }
int decay_mode_impl () const private virtual
Implements ChannelType.
 { return 0; }
void set_decay_mode_impl (int decay_mode) private virtual
Implements ChannelType.
 {
     Insist( false, "cannot set_decay_mode for ChannelType_Reac" );
 }
Field::SP field_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_field.
 { return b_field; }
void set_field_impl (Field::SP field) private virtual
Implements ChannelType.
References ChannelType_Reac::b_field, ChannelType::field(), and ChannelType_Reac::update_byproducts().
 {
     b_field = field;
     update_byproducts();
 }
bool is_reaction_impl () const private virtual
Reimplemented from ChannelType.
 { return true; }
bool is_decay_impl () const private virtual
Reimplemented from ChannelType.
 { return false; }
bool has_followon_decay_impl () const private virtual
Reimplemented from ChannelType.
 { return false; }
bool has_distribution_of_daughters_impl () const private virtual
Reimplemented from ChannelType.
 {
     return false;
 }
double num_residuals_per_event_impl () const private virtual
Reimplemented from ChannelType.
 { return 1.0; }
ByproductCount_t num_byproducts_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_num_byproducts.
 {
     return b_num_byproducts;
 }
int delta_nucleus_protons_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_delta_nucleus_protons.
 {
     return b_delta_nucleus_protons;
 }
int delta_nucleus_neutrons_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_delta_nucleus_neutrons.
 {
     return b_delta_nucleus_neutrons;
 }
int delta_mass_number_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_delta_mass_number.
 {
     return b_delta_mass_number;
 }
int delta_charge_number_impl () const private virtual
Implements ChannelType.
References ChannelType_Reac::b_delta_charge_number.
 {
     return b_delta_charge_number;
 }
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
References ChannelType::field(), Checkable::name(), and ChannelType::reaction_mt().
 {
     size_t nerr = 0;
     int mt = reaction_mt();
     // not allowed mts
     if( mt == 2 || mt == 101 || mt == 27 )
     {
         std::stringstream ss;
         ss << "channel_type=" << this->name() << " does not have a valid field";
         errors.push_back( ss.str() );
         ++nerr;
     }
     bool pass = ScaleData::Utils::is_valid_mt( mt );
     if( !pass )
     {
         std::stringstream ss;
         ss << "channel_type=" << this->name()
            << " does not have a valid reaction_mt=" << reaction_mt();
         errors.push_back( ss.str() );
         ++nerr;
     }
     if( field() == nullptr )
     {
         std::stringstream ss;
         ss << "channel_type=" << this->name() << " does not have a valid field";
         errors.push_back( ss.str() );
         ++nerr;
     }
     return nerr == 0;
 }
void update_byproducts () private
Numbers of various byproducts
References Origen::ALPHA_BYPRODUCT_ID, ChannelType_Reac::b_delta_charge_number, ChannelType_Reac::b_delta_mass_number, ChannelType_Reac::b_delta_nucleus_neutrons, ChannelType_Reac::b_delta_nucleus_protons, ChannelType_Reac::b_field, ChannelType_Reac::b_num_byproducts, ChannelType_Reac::b_reaction_mt, Origen::BAD_INT, Origen::DEUTERON_BYPRODUCT_ID, Origen::HELION_BYPRODUCT_ID, Origen::NEUTRON_BYPRODUCT_ID, Origen::PROTON_BYPRODUCT_ID, and Origen::TRITON_BYPRODUCT_ID.
Referenced by ChannelType_Reac::set_field_impl(), and ChannelType_Reac::set_reaction_mt_impl().
 {
     int num_neutron = 0;
     int num_proton = 0;
     int num_deuteron = 0;
     int num_triton = 0;
     int num_helion = 0;
     int num_alpha = 0;
     int incident_particle_charge_number = 0;
     int incident_particle_mass_number = 0;
     if( b_field != nullptr )
     {
         incident_particle_mass_number = b_field->species()->mass_number();
         incident_particle_charge_number = b_field->species()->charge_number();
     }
     b_delta_nucleus_protons = 0;
     b_delta_nucleus_neutrons = 0;
     if( b_reaction_mt != BAD_INT )
     {
         //! Numbers of various byproducts
         ScaleData::Utils::mt_to_num_byproducts( b_reaction_mt,
                                                 num_neutron,
                                                 num_proton,
                                                 num_deuteron,
                                                 num_triton,
                                                 num_helion,
                                                 num_alpha );
         // returns valid
         // Check(valid);  //want to pass through even if errors...
     }
     int byproduct_protons =
         ScaleData::Utils::num_byproducts_to_total_proton( num_neutron,
                                                           num_proton,
                                                           num_deuteron,
                                                           num_triton,
                                                           num_helion,
                                                           num_alpha );
     int byproduct_neutrons =
         ScaleData::Utils::num_byproducts_to_total_neutron( num_neutron,
                                                            num_proton,
                                                            num_deuteron,
                                                            num_triton,
                                                            num_helion,
                                                            num_alpha );
     // data to cache follows
     b_num_byproducts.clear();
     b_num_byproducts[NEUTRON_BYPRODUCT_ID] = num_neutron;
     b_num_byproducts[PROTON_BYPRODUCT_ID] = num_proton;
     b_num_byproducts[DEUTERON_BYPRODUCT_ID] = num_deuteron;
     b_num_byproducts[TRITON_BYPRODUCT_ID] = num_triton;
     b_num_byproducts[HELION_BYPRODUCT_ID] = num_helion;
     b_num_byproducts[ALPHA_BYPRODUCT_ID] = num_alpha;
     b_delta_charge_number = incident_particle_charge_number +
                             b_delta_nucleus_protons - byproduct_protons;
     b_delta_mass_number = incident_particle_mass_number +
                           b_delta_nucleus_neutrons + b_delta_nucleus_protons -
                           byproduct_protons - byproduct_neutrons;
 }
int reaction_mt () const inherited
Referenced by ChannelType_Fiss::good_impl(), ChannelType_Reac::good_impl(), ChannelType_Fiss::set_reaction_mt_impl(), and ChannelType_Reac::set_reaction_mt_impl().
 { return reaction_mt_impl(); }
void set_reaction_mt (int reaction_mt) inherited
Referenced by ChannelType_Fiss::ChannelType_Fiss(), and ChannelType_Reac::ChannelType_Reac().
 {
     set_reaction_mt_impl( reaction_mt );
 }
std::string reaction_mt_name () const inherited
 {
     return reaction_mt_name_impl();
 }
bool has_initialized_reaction_mt () const inherited
 {
     return has_initialized_reaction_mt_impl();
 }
int decay_mode () const inherited
Referenced by ChannelType_Decay::good_impl().
 { return decay_mode_impl(); }
void set_decay_mode (int decay_mode) inherited
Referenced by ChannelType_Decay::ChannelType_Decay().
 {
     set_decay_mode_impl( decay_mode );
 }
std::string decay_mode_name () const inherited
 {
     return decay_mode_name_impl();
 }
bool has_initialized_decay_mode () const inherited
 {
     return has_initialized_decay_mode_impl();
 }
SP_Field field () const inherited
Referenced by ChannelType_Fiss::good_impl(), ChannelType_Reac::good_impl(), ChannelType_Fiss::set_field_impl(), and ChannelType_Reac::set_field_impl().
 { return field_impl(); }
void get_field (SP_Field & field) const inherited
 {
     get_field_impl( field );
 }
void set_field (SP_Field field) inherited
Referenced by ChannelType_Fiss::ChannelType_Fiss(), and ChannelType_Reac::ChannelType_Reac().
 { set_field_impl( field ); }
bool has_initialized_field () const inherited
 {
     return has_initialized_field_impl();
 }
bool is_reaction () const inherited
 { return is_reaction_impl(); }
bool is_decay () const inherited
 { return is_decay_impl(); }
bool has_followon_decay () const inherited
 {
     return has_followon_decay_impl();
 }
bool has_distribution_of_daughters () const inherited
 {
     return has_distribution_of_daughters_impl();
 }
double num_residuals_per_event () const inherited
 {
     return num_residuals_per_event_impl();
 }
int num_byproduct (const ByproductId byproduct_id) const inherited
 {
     return num_byproduct_impl( byproduct_id );
 }
bool has_byproduct (const ByproductId byproduct_id) const inherited
 {
     return has_byproduct_impl( byproduct_id );
 }
ByproductCount_t num_byproducts () const inherited
 {
     return num_byproducts_impl();
 }
void increment_num_byproducts (ByproductCount_t & num_byproducts) const inherited
int delta_nucleus_protons () const inherited
 {
     return delta_nucleus_protons_impl();
 }
int delta_nucleus_neutrons () const inherited
 {
     return delta_nucleus_neutrons_impl();
 }
int delta_mass_number () const inherited
 { return delta_mass_number_impl(); }
int delta_charge_number () const inherited
 {
     return delta_charge_number_impl();
 }
int channel_id (int decay_mode) static inherited
channel id for decay only
Referenced by TransitionSystem_Gen::channel_type_impl(), and TransitionSystemAdapter_AmpxN::update().
 {
     return channel_id( nullptr, 0, decay_mode );
 }
int channel_id (SP_Field field, int reaction_mt, int decay_mode = 0) static inherited
channel id for reaction+decay
 {
     if( reaction_mt > 0 )
     {
         Check( decay_mode == 0 );
         int field_id = field == nullptr ? 11 : field->id();
         return ( field_id - 1 ) * 10000 + reaction_mt;
     }
     else
     {
         return -decay_mode;
     }
 }
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
Field::SP b_field private
Referenced by ChannelType_Reac::field_impl(), ChannelType_Reac::set_field_impl(), and ChannelType_Reac::update_byproducts().
int b_reaction_mt private
Referenced by ChannelType_Reac::reaction_mt_impl(), ChannelType_Reac::set_reaction_mt_impl(), and ChannelType_Reac::update_byproducts().
int b_delta_mass_number private
Referenced by ChannelType_Reac::delta_mass_number_impl(), and ChannelType_Reac::update_byproducts().
int b_delta_charge_number private
Referenced by ChannelType_Reac::delta_charge_number_impl(), and ChannelType_Reac::update_byproducts().
int b_delta_nucleus_protons private
Referenced by ChannelType_Reac::delta_nucleus_protons_impl(), and ChannelType_Reac::update_byproducts().
int b_delta_nucleus_neutrons private
Referenced by ChannelType_Reac::delta_nucleus_neutrons_impl(), and ChannelType_Reac::update_byproducts().
ByproductCount_t b_num_byproducts private
Referenced by ChannelType_Reac::num_byproducts_impl(), and ChannelType_Reac::update_byproducts().
The documentation for this class was generated from the following files:
Core/ts/ChannelType_Reac.h
Core/ts/ChannelType_Reac.cpp