ORIGEN API: Accessor< Origen::Concentrations > Class Template Reference
Accessor< Origen::Concentrations > Class Template Reference
#include <Accessor_Concentrations.h>
Static Public Member Functions
template<typename Archiver >
static size_t read (Archiver &a,::Origen::Concentrations &obj)
template<typename Archiver >
static size_t write (Archiver &a, const ::Origen::Concentrations &obj, bool only_size=false)
Member Function Documentation
static size_t read (Archiver & a, ::Origen::Concentrations & obj) inline static
References Concentrations::b_nuclide_set, Concentrations::b_vals, Origen::read(), and Concentrations::units().
     {
         size_t bytes = 0;
         bytes +=
             Acc<Origen::ConcentrationUnit>::read( a, "units", obj.units() );
         bytes += Acc<Origen::NuclideSet>::read(
             a, "nuclide_set", obj.b_nuclide_set );
         bytes += Acc<Vec_Dbl>::read( a, "vals", obj.b_vals );
         return bytes;
     }
static size_t write (Archiver & a, const ::Origen::Concentrations & obj, bool only_size = false) inline static
References Origen::write().
     {
         size_t bytes = 0;
         bytes += Acc<Origen::ConcentrationUnit>::write(
             a, "units", obj.units(), only_size );
         bytes += Acc<Origen::NuclideSet>::write(
             a, "nuclide_set", obj.b_nuclide_set, only_size );
         bytes += Acc<Vec_Dbl>::write( a, "vals", obj.b_vals, only_size );
         return bytes;
     }
The documentation for this class was generated from the following file:
Core/dc/Accessor_Concentrations.h