ORIGEN API: Nuclide_Gen Class Reference
Nuclide_Gen Class Reference
#include <Nuclide_Gen.h>
General-purpose implementation of the Nuclide interface.
Public Types
typedef SP_Nuclide SP
strong pointer
typedef WP_Nuclide WP
weak pointer
typedef CWP_Nuclide CWP
const weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Nuclide>>
See Origen::Nuclide for details.
std::vector< WP_Transition > gains () const
Return a vector of gains producing the nuclide.
void get_gains (std::vector< WP_Transition > &gains) const
Get a vector of gains producing the nuclide.
void set_gains (std::vector< WP_Transition > gains)
Set the gains producing the nuclide.
void append_gain (WP_Transition gain)
Append gain to list of gains.
void clear_gains ()
WP_Transition gain (int channel_id, int parent_id) const
retrieve a gain
int num_gains () const
Get the number of gains producing the nuclide.
std::vector< SP_Channel > losses () const
Return a vector of losses destroying the nuclide.
void get_losses (std::vector< SP_Channel > &losses) const
Get a vector of losses destroying the nuclide.
void set_losses (std::vector< SP_Channel > losses)
Set the losses destroying the nuclide.
SP_Channel loss (int channel_id) const
return loss channel
void get_loss (int channel_id, SP_Channel &loss) const
retrieve loss channel
void set_loss (SP_Channel loss)
SP_Channel add_loss (SP_ChannelType channel_type)
add a new loss channel to the nuclide by specifying ChannelType
SP_Channel add_loss (int field_id, int reaction_mt, int decay_mode=0)
add a new loss channel by specifying raw ids
SP_Channel add_loss (SP_Field field, int reaction_mt, int decay_mode=0)
add a new loss channel with Field and raw ids
SP_Channel add_loss (int decay_mode)
add a decay loss
int num_losses () const
Get the number of losses destroying the nuclide.
CWP_TransitionSystem system () const
void get_system (WP_TransitionSystem &system) const
void set_system (WP_TransitionSystem system)
bool has_initialized_system () const
int isomeric_state () const
void get_isomeric_state (int &isomeric_state) const
void set_isomeric_state (int isomeric_state)
SP_Species species () const
void get_species (SP_Species &species) const
void set_species (SP_Species species)
bool has_initialized_species () const
double num () const
void get_num (double &num) const
void set_num (double num)
double decay_constant () const
Return the decay constant.
double loss_xs () const
Public Member Functions
Nuclide_Gen ()
Nuclide_Gen (int isomeric_state, Species::SP species)
Nuclide_Gen (int isomeric_state, Species::SP species, double num)
virtual ~Nuclide_Gen ()
Private Types
typedef std::map< int, Channel::SP > ChannelRegistry
Private Member Functions
virtual std::vector< WP_Transition > gains_impl () const
virtual void get_gains_impl (std::vector< WP_Transition > &gains) const
virtual void set_gains_impl (std::vector< WP_Transition > gains)
virtual int num_gains_impl () const
virtual void append_gain_impl (WP_Transition gain)
virtual WP_Transition gain_impl (int channel_id, int parent_id) const
virtual void clear_gains_impl ()
virtual std::vector< Channel::SP > losses_impl () const
virtual void get_losses_impl (std::vector< Channel::SP > &losses) const
virtual void set_losses_impl (std::vector< Channel::SP > losses)
virtual Channel::SP loss_impl (int channel_id) const
virtual void get_loss_impl (int channel_id, Channel::SP &loss) const
virtual void set_loss_impl (Channel::SP loss)
virtual SP_Channel add_loss_impl (SP_ChannelType channel_type)
virtual int num_losses_impl () const
virtual double decay_constant_impl () const
virtual double num_impl () const
virtual void get_num_impl (double &num) const
virtual void set_num_impl (double num)
virtual int isomeric_state_impl () const
virtual void get_isomeric_state_impl (int &isomeric_state) const
virtual void set_isomeric_state_impl (int isomeric_state)
virtual double loss_xs_impl () const
virtual Species::SP species_impl () const
virtual void get_species_impl (Species::SP &species) const
virtual void set_species_impl (Species::SP species)
virtual bool has_initialized_species_impl () const
virtual CWP_TransitionSystem system_impl () const
virtual void get_system_impl (WP_TransitionSystem &system) const
virtual void set_system_impl (WP_TransitionSystem system)
virtual bool has_initialized_system_impl () const
Private Attributes
TransitionSystem::WP b_system
int b_isomeric_state
Species::SP b_species
double b_num
std::vector< WP_Transition > b_gains
ChannelRegistry b_loss_map
Detailed Description
General-purpose implementation of the Nuclide interface.
The general-purpose implementation of INTERFACE<<Origen::Nuclide>> that will be good when the use case is:
an initial intense setup operation adding loss channels followed by
repeated access losses without changing structure and
extraction of all gains in a group.
The gains are stored in a vector so the gain lookup is linear, whereas the losses are stored in a map.
Sometimes the best approach is to store the smart pointers to what you need in a structure that you can easily/quickly traverse.
See also
Origen::Transition_Gen, Origen::Channel_Gen
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef std::map<int, Channel::SP> ChannelRegistry private
typedef SP_Nuclide SP inherited
strong pointer
typedef WP_Nuclide WP inherited
weak pointer
typedef CWP_Nuclide CWP inherited
const weak pointer
Constructor & Destructor Documentation
Nuclide_Gen ()
     : b_system( nullptr )
     , b_isomeric_state( 0 )
     , b_species( nullptr )
     , b_num( 1.0 )
 {
     //#jDebugTaggedLine("creating TransitionSystem/Nuclide="<<this);
 }
Nuclide_Gen (int isomeric_state, Species::SP species)
References Nuclide::set_isomeric_state(), and Nuclide::set_species().
     : b_system( nullptr ), b_num( 1.0 )
 {
     //#jDebugTaggedLine("creating TransitionSystem/Nuclide="<<this);
     set_isomeric_state( isomeric_state );
     set_species( species );
 }
Nuclide_Gen (int isomeric_state, Species::SP species, double num)
References Nuclide::set_isomeric_state(), Nuclide::set_num(), and Nuclide::set_species().
     : b_system( nullptr )
 {
     //#jDebugTaggedLine("creating TransitionSystem/Nuclide="<<this);
     set_isomeric_state( isomeric_state );
     set_species( species );
     set_num( num );
 }
~Nuclide_Gen () virtual
 {
     //#jDebugTaggedLine("deleting TransitionSystem/Nuclide="<<this);
 }
Member Function Documentation
std::vector< WP_Transition > gains_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains.
 { return b_gains; }
void get_gains_impl (std::vector< WP_Transition > & gains) const private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains.
 {
     gains = b_gains;
 }
void set_gains_impl (std::vector< WP_Transition > gains) private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains, and Nuclide::gains().
 {
     b_gains = gains;
 }
int num_gains_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains.
 { return b_gains.size(); }
void append_gain_impl (WP_Transition gain) private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains, Transition::channel(), and Channel::parent().
 {
     Require( gain->channel() != nullptr );
     Require( gain->channel()->parent() != nullptr );
     b_gains.push_back( gain );
 }
Transition::WP gain_impl (int channel_id, int parent_id) const private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains, Checkable::id(), and Channel::parent().
 {
     for( size_t i = 0; i < b_gains.size(); ++i )
     {
         Check( b_gains[i]->channel() != nullptr );
         Channel::CWP c = b_gains[i]->channel();
         Check( c->parent() != nullptr );
         Nuclide::CWP p = c->parent();
         if( c->id() == channel_id && p->id() == parent_id )
         {
             return b_gains[i];
         }
     }
     return nullptr;
 }
void clear_gains_impl () private virtual
Implements Nuclide.
References Nuclide_Gen::b_gains, and Nuclide::num_gains().
 {
     b_gains.clear();
     Ensure( num_gains() == 0 );
 }
std::vector< Channel::SP > losses_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map, and Nuclide::losses().
 {
     std::vector<SP_Channel> losses;
     std::vector<int> ids;
     ScaleSTL::map_to_vectors( b_loss_map, &ids, &losses );
     return losses;
 }
void get_losses_impl (std::vector< Channel::SP > & losses) const private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map.
 {
     std::vector<int> ids;
     ScaleSTL::map_to_vectors( b_loss_map, &ids, &losses );
 }
void set_losses_impl (std::vector< Channel::SP > losses) private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map, Checkable::has_initialized_id(), and Checkable::id().
 {
     b_loss_map.clear();
     Remember( std::set<int> ids );
     for( size_t i = 0; i < losses.size(); ++i )
     {
         Check( false );
         Check( losses[i]->has_initialized_id() );
         // must put in unique ids
         int id = losses[i]->id();
         Ensure( ids.count( id ) == 0 );
         Remember( ids.insert( id ) );
         b_loss_map[id] = losses[i];
     }
 }
Channel::SP loss_impl (int channel_id) const private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map.
 {
     ChannelRegistry::const_iterator it = b_loss_map.find( channel_id );
     if( it != b_loss_map.end() )
     {
         return it->second;
     }
     return nullptr;
 }
void get_loss_impl (int channel_id, Channel::SP & loss) const private virtual
Implements Nuclide.
References Nuclide::loss().
 {
     loss = this->loss( channel_id );
 }
void set_loss_impl (Channel::SP loss) private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map, and Nuclide::loss().
 {
     Require( loss->has_initialized_id() );
     loss->set_parent( this );
     b_loss_map[loss->id()] = loss;
 }
SP_Channel add_loss_impl (SP_ChannelType channel_type) private virtual
Implements Nuclide.
References Nuclide::loss(), and Nuclide::set_loss().
 {
     Require( channel_type->has_initialized_id() );
     SP_Channel channel = this->loss( channel_type->id() );
     if( channel == nullptr )
     {
         channel = SP_Channel( new Channel_Gen( channel_type ) );
     }
     this->set_loss( channel );
     return channel;
 }
int num_losses_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map.
 { return b_loss_map.size(); }
double decay_constant_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map.
 {
     ChannelRegistry::const_iterator it = b_loss_map.begin();
     double dc = 0.0;
     while( it != b_loss_map.end() )
     {
         dc += it->second->decay_constant();
         ++it;
     }
     return dc;
 }
double num_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_num.
 { return b_num; }
void get_num_impl (double & num) const private virtual
Implements Nuclide.
References Nuclide::num().
 { num = this->num(); }
void set_num_impl (double num) private virtual
Implements Nuclide.
References Nuclide_Gen::b_num, and Nuclide::num().
 { b_num = num; }
int isomeric_state_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_isomeric_state.
 { return b_isomeric_state; }
void get_isomeric_state_impl (int & isomeric_state) const private virtual
Implements Nuclide.
References Nuclide::isomeric_state().
 {
     isomeric_state = this->isomeric_state();
 }
void set_isomeric_state_impl (int isomeric_state) private virtual
Implements Nuclide.
References Nuclide_Gen::b_isomeric_state, and Nuclide::isomeric_state().
 {
     b_isomeric_state = isomeric_state;
 }
double loss_xs_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_loss_map.
 {
     ChannelRegistry::const_iterator it = b_loss_map.begin();
     double xs = 0.0;
     while( it != b_loss_map.end() )
     {
         xs += it->second->xs();
         ++it;
     }
     return xs;
 }
Species::SP species_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_species.
 { return b_species; }
void get_species_impl (Species::SP & species) const private virtual
Implements Nuclide.
References Nuclide_Gen::b_species.
 {
     species = b_species;
 }
void set_species_impl (Species::SP species) private virtual
Implements Nuclide.
References Nuclide_Gen::b_species, and Nuclide::species().
 {
     b_species = species;
 }
bool has_initialized_species_impl () const private virtual
Implements Nuclide.
References Nuclide::species().
 {
     return species() != nullptr;
 }
CWP_TransitionSystem system_impl () const private virtual
Implements Nuclide.
References Nuclide_Gen::b_system.
 { return b_system; }
void get_system_impl (WP_TransitionSystem & system) const private virtual
Implements Nuclide.
References Nuclide_Gen::b_system.
 {
     system = b_system;
 }
void set_system_impl (WP_TransitionSystem system) private virtual
Implements Nuclide.
References Nuclide_Gen::b_system, and Nuclide::system().
 {
     b_system = system;
 }
bool has_initialized_system_impl () const private virtual
Implements Nuclide.
References Nuclide::system().
 {
     return system() != nullptr;
 }
std::vector< WP_Transition > gains () const inherited
Return a vector of gains producing the nuclide.
Returns
std::vector<WP_Transition> vector of gains.
Referenced by Nuclide_Gen::set_gains_impl().
 { return gains_impl(); }
void get_gains (std::vector< WP_Transition > & gains) const inherited
Get a vector of gains producing the nuclide.
The user vector is overwritten with the contents.
Returns
std::vector<WP_Transition> vector of gains.
 {
     get_gains_impl( gains );
 }
void set_gains (std::vector< WP_Transition > gains) inherited
Set the gains producing the nuclide.
The internal gains are overwritten with the contents.
Parameters
std::vector<WP_Transition> vector of gains.
 {
     set_gains_impl( gains );
 }
void append_gain (WP_Transition gain) inherited
Append gain to list of gains.
Parameters
gain to append.
 { append_gain_impl( gain ); }
void clear_gains () inherited
 { clear_gains_impl(); }
Transition::WP gain (int channel_id, int parent_id) const inherited
retrieve a gain
 {
     return gain_impl( channel_id, parent_id );
 }
int num_gains () const inherited
Get the number of gains producing the nuclide.
Returns
int number of gains.
Referenced by Nuclide_Gen::clear_gains_impl().
 { return num_gains_impl(); }
std::vector< Channel::SP > losses () const inherited
Return a vector of losses destroying the nuclide.
Returns
std::vector<Channel::SP> vector of losses.
Referenced by Nuclide_Gen::losses_impl().
 { return losses_impl(); }
void get_losses (std::vector< SP_Channel > & losses) const inherited
Get a vector of losses destroying the nuclide.
The user vector is overwritten with the contents.
Returns
std::vector<Channel::SP> vector of losses.
 {
     get_losses_impl( losses );
 }
void set_losses (std::vector< SP_Channel > losses) inherited
Set the losses destroying the nuclide.
The internal losses are overwritten with the contents.
Returns
std::vector<Channel::SP> vector of losses.
 {
     set_losses_impl( losses );
 }
Channel::SP loss (int channel_id) const inherited
return loss channel
Referenced by Nuclide_Gen::add_loss_impl(), Nuclide_Gen::get_loss_impl(), and Nuclide_Gen::set_loss_impl().
 {
     return loss_impl( channel_id );
 }
void get_loss (int channel_id, SP_Channel & loss) const inherited
retrieve loss channel
 {
     get_loss_impl( channel_id, loss );
 }
void set_loss (SP_Channel loss) inherited
Referenced by Nuclide_Gen::add_loss_impl().
 { set_loss_impl( loss ); }
Channel::SP add_loss (SP_ChannelType channel_type) inherited
add a new loss channel to the nuclide by specifying ChannelType
 {
     return add_loss_impl( channel_type );
 }
Channel::SP add_loss (int field_id, int reaction_mt, int decay_mode = 0) inherited
add a new loss channel by specifying raw ids
 {
     return add_loss_impl( field_id, reaction_mt, decay_mode );
 }
Channel::SP add_loss (SP_Field field, int reaction_mt, int decay_mode = 0) inherited
add a new loss channel with Field and raw ids
 {
     return add_loss_impl( field, reaction_mt, decay_mode );
 }
Channel::SP add_loss (int decay_mode) inherited
add a decay loss
 {
     return add_loss_impl( decay_mode );
 }
int num_losses () const inherited
Get the number of losses destroying the nuclide.
Returns
int number of losses.
 { return num_losses_impl(); }
CWP_TransitionSystem system () const inherited
Referenced by Nuclide_Gen::has_initialized_system_impl(), and Nuclide_Gen::set_system_impl().
 { return system_impl(); }
void get_system (WP_TransitionSystem & system) const inherited
Referenced by Channel_Gen::add_transition_impl(), and Channel_Gen::update_byproduct_transitions_impl().
 {
     get_system_impl( system );
 }
void set_system (WP_TransitionSystem system) inherited
 {
     set_system_impl( system );
 }
bool has_initialized_system () const inherited
Referenced by Channel_Gen::add_transition_impl().
 {
     return has_initialized_system_impl();
 }
int isomeric_state () const inherited
Referenced by Nuclide_Gen::get_isomeric_state_impl(), and Nuclide_Gen::set_isomeric_state_impl().
 { return isomeric_state_impl(); }
void get_isomeric_state (int & isomeric_state) const inherited
 {
     get_isomeric_state_impl( isomeric_state );
 }
void set_isomeric_state (int isomeric_state) inherited
Referenced by Nuclide_Gen::Nuclide_Gen().
 {
     set_isomeric_state_impl( isomeric_state );
 }
Species::SP species () const inherited
Referenced by Nuclide_Gen::has_initialized_species_impl(), and Nuclide_Gen::set_species_impl().
 { return species_impl(); }
void get_species (SP_Species & species) const inherited
 {
     get_species_impl( species );
 }
void set_species (SP_Species species) inherited
Referenced by Nuclide_Gen::Nuclide_Gen().
 {
     set_species_impl( species );
 }
bool has_initialized_species () const inherited
 {
     return has_initialized_species_impl();
 }
double num () const inherited
Referenced by Nuclide_Gen::get_num_impl(), Channel_Gen::rate_impl(), and Nuclide_Gen::set_num_impl().
 { return num_impl(); }
void get_num (double & num) const inherited
 { get_num_impl( num ); }
void set_num (double num) inherited
Referenced by Nuclide_Gen::Nuclide_Gen().
 { set_num_impl( num ); }
double decay_constant () const inherited
Return the decay constant.
This total decay constant is a sum of all channel decay constants.
Returns
double decay constant (1/s)
 { return decay_constant_impl(); }
double loss_xs () const inherited
 { return loss_xs_impl(); }
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
TransitionSystem::WP b_system private
Referenced by Nuclide_Gen::get_system_impl(), Nuclide_Gen::set_system_impl(), and Nuclide_Gen::system_impl().
int b_isomeric_state private
Referenced by Nuclide_Gen::isomeric_state_impl(), and Nuclide_Gen::set_isomeric_state_impl().
Species::SP b_species private
Referenced by Nuclide_Gen::get_species_impl(), Nuclide_Gen::set_species_impl(), and Nuclide_Gen::species_impl().
double b_num private
Referenced by Nuclide_Gen::num_impl(), and Nuclide_Gen::set_num_impl().
std::vector<WP_Transition> b_gains private
Referenced by Nuclide_Gen::append_gain_impl(), Nuclide_Gen::clear_gains_impl(), Nuclide_Gen::gain_impl(), Nuclide_Gen::gains_impl(), Nuclide_Gen::get_gains_impl(), Nuclide_Gen::num_gains_impl(), and Nuclide_Gen::set_gains_impl().
ChannelRegistry b_loss_map private
Referenced by Nuclide_Gen::decay_constant_impl(), Nuclide_Gen::get_losses_impl(), Nuclide_Gen::loss_impl(), Nuclide_Gen::loss_xs_impl(), Nuclide_Gen::losses_impl(), Nuclide_Gen::num_losses_impl(), Nuclide_Gen::set_loss_impl(), and Nuclide_Gen::set_losses_impl().
The documentation for this class was generated from the following files:
Core/ts/Nuclide_Gen.h
Core/ts/Nuclide_Gen.cpp