OrigenAPI: TransitionSystem_Gen_Setup Class Reference
TransitionSystem_Gen_Setup Class Reference
Public Member Functions
void SetUp ()
Public Attributes
Origen::TransitionSystem_Gen ts
std::vector< Origen::ChannelType::SP > ct_list
std::vector< int > ids
std::vector< int > fp_ids
int nt
int ref_num_transitions
int ref_num_nuclides
int max_isomeric_state
Detailed Description
Definition at line 894 of file tstTransitionSystem_Gen.cpp.
Member Function Documentation
void TransitionSystem_Gen_Setup::SetUp () inline
Definition at line 903 of file tstTransitionSystem_Gen.cpp.
References Origen::TransitionSystem::add_nuclide(), Origen::TransitionSystem::add_species(), kernel_rksuite::f(), fp_nuclides(), get_channel_type_list_10(), auxiliary::nuclide(), Origen::TransitionSystem::populate_gains(), and unique_nuclides().
     {
         get_channel_type_list_10( ct_list );
         unique_nuclides( ids );
         fp_nuclides( fp_ids );
         ref_num_transitions = 147089;
         ref_num_nuclides = 4164;
         max_isomeric_state = 1;
         nt = 0;
         int s, i, z, a;
         for( size_t j = 0; j < ids.size(); ++j )
         {
             ScaleData::Utils::split_pizzzaaa( ids[j], s, i, z, a );
             Check( s == 0 );
             Origen::Species::SP species = ts.add_species( z, a );
             Origen::Nuclide::SP nuclide = ts.add_nuclide( i, species );
             for( size_t k = 0; k < ct_list.size(); ++k )
             {
                 if( ct_list[k]->reaction_mt() == 18 )
                 {
                     if( z >= 90 )
                     {
                         Origen::Channel::SP channel =
                             nuclide->add_loss( ct_list[k] );
                         std::vector<Origen::Transition::SP> transitions;
                         transitions.reserve( fp_ids.size() );
                         for( size_t f = 0; f < fp_ids.size(); ++f )
{
                             ScaleData::Utils::split_pizzzaaa(
                                 fp_ids[f], s, i, z, a );
                             Origen::Species::SP pspecies =
                                 ts.add_species( z, a );
                             Origen::Nuclide::SP product =
                                 ts.add_nuclide( i, pspecies );
                             Origen::Transition::SP transition(
                                 new Origen::Transition_Gen( &*product ) );
                             transition->set_yield( 0.01 + f / 2000. );
                             transitions.push_back( transition );
                         }
                         channel->set_transitions( transitions );
                         EXPECT_EQ( static_cast<int>( transitions.size() ),
                                    channel->num_transitions() );
                         nt += channel->num_transitions();
                     }
                 }
                 else
                 {
                     // test this channel first to see it gives a physical result
                     Origen::Channel::SP channel(
                         new Origen::Channel_Gen( ct_list[k] ) );
                     channel->set_parent( &*nuclide );
                     if( channel->daughter_mass_number() >= 1 &&
                         channel->daughter_charge_number() >= 1 &&
                         channel->daughter_mass_number() >=
                             channel->daughter_charge_number() )
                     {
                         channel->add_transition( 0 )->set_yield( 0.6 );
                         channel->add_transition( 1 )->set_yield( 0.4 );
                         nuclide->set_loss( channel );
                         EXPECT_EQ( max_isomeric_state + 1,
                                    channel->num_transitions() )
                             << channel->to_string();
                         nt += channel->num_transitions();
                     }
                 }
             }
         }
         ts.populate_gains();
     }
Member Data Documentation
std::vector<Origen::ChannelType::SP> TransitionSystem_Gen_Setup::ct_list
Definition at line 898 of file tstTransitionSystem_Gen.cpp.
std::vector<int> TransitionSystem_Gen_Setup::fp_ids
Definition at line 899 of file tstTransitionSystem_Gen.cpp.
std::vector<int> TransitionSystem_Gen_Setup::ids
Definition at line 899 of file tstTransitionSystem_Gen.cpp.
int TransitionSystem_Gen_Setup::max_isomeric_state
Definition at line 901 of file tstTransitionSystem_Gen.cpp.
int TransitionSystem_Gen_Setup::nt
Definition at line 900 of file tstTransitionSystem_Gen.cpp.
int TransitionSystem_Gen_Setup::ref_num_nuclides
Definition at line 900 of file tstTransitionSystem_Gen.cpp.
int TransitionSystem_Gen_Setup::ref_num_transitions
Definition at line 900 of file tstTransitionSystem_Gen.cpp.
Origen::TransitionSystem_Gen TransitionSystem_Gen_Setup::ts
Definition at line 897 of file tstTransitionSystem_Gen.cpp.
The documentation for this class was generated from the following file:
Core/ts/tests/tstTransitionSystem_Gen.cpp