ORIGEN API: YieldParent Class Reference
YieldParent Class Reference
#include <YieldResource.h>
Public Member Functions
~YieldParent ()
int id () const
izzzaaa id of
int num_energies () const
number of energies
double energy_at (int index) const
get a specific energy
void get_energies (Vec_Dbl *energies) const
get all energies
bool has_energy (double energy) const
check if a specific energy is available
int energy_index (double energy) const
get the index to that energy
YieldData & data_at (int index)
get yield set by energy index
const YieldData & data_at (int index) const
get yield set by energy index
YieldData & add_data (double energy, const Vec_Int &id, const Vec_Dbl &val, bool append=false)
add a new yield set (overwrite existing by default)
bool has_fp (int fp_izzzaaa) const
this fissionable nuclide has fp id
int fp_index (int fp_izzzaaa) const
fission product index (-1 if not found)
int add_fp (int fp_izzzzaaa)
add a new fission product (if doesn't already exist)
int num_fps () const
number of fission products
void get_fp_ids (Vec_Int *ids) const
get all fission product ids
void get_yields (Vec_Dbl *yields, int energy_index) const
get yields
void get_interp_yields (Vec_Dbl *yields, double energy, int interp=INTERP_PREFERRED) const
interpolate all yields
double interp_yield (int fp_izzzaaa, double energy, int interp=INTERP_PREFERRED) const
interpolate a single yield (will return 0.0 if doesn't exist)
int interp_method () const
get interpolation method
void set_interp_method (int method)
set interpolation method
void remove_data_at (int index)
remove a set of yield data
bool remove_fp (int fp_izzzaaa)
remove one fp
void set_fp_ids (const Vec_Int &ids)
keep only these fp
Protected Member Functions
YieldParent (int id)
const std::vector< YieldData > & data () const
get const yield sets
std::vector< YieldData > * data ()
get yield sets
const FPMap_t & fp_map () const
get const fp map
FPMap_t & fp_map ()
get fp map
Private Member Functions
YieldParent ()
Private Attributes
int b_interp_method
FPMap_t b_fp_map
std::vector< YieldData > b_data
int b_id
Friends
class YieldResource
Detailed Description
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
Constructor & Destructor Documentation
~YieldParent ()
 {}
YieldParent (int id) explicit protected
 : b_interp_method( 0 ), b_id( id ) {}
YieldParent () private
Member Function Documentation
int id () const
izzzaaa id of
References YieldParent::b_id.
Referenced by YieldResource::check_consistency(), ReactionResource::import_fission_yields(), main(), print_yield_data(), YieldResource::to_json(), and YieldResourceIO_stab1::write().
 { return b_id; }
int num_energies () const
number of energies
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_data.
Referenced by YieldParent::data_at(), YieldParent::energy_at(), YieldParent::get_energies(), YieldParent::get_interp_yields(), get_yield(), YieldParent::get_yields(), ReactionResource::import_fission_yields(), main(), print_yield_data(), Origen::printInterpolatedYields(), Origen::printYieldEnergies(), Origen::printYields(), YieldParent::remove_data_at(), TEST(), TEST_F(), and YieldResourceIO_stab1::write().
 { return b_data.size(); }
double energy_at (int index) const
get a specific energy
References YieldParent::b_data, and YieldParent::num_energies().
Referenced by YieldParent::get_energies(), Origen::printInterpolatedYields(), and YieldResourceIO_stab1::write().
 {
     Require( index >= 0 && index < num_energies() );
     return b_data[index].energy();
 }
void get_energies (Vec_Dbl * energies) const
get all energies
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
References YieldParent::energy_at(), and YieldParent::num_energies().
Referenced by YieldParent::energy_index(), YieldResource::get_all_energies(), TEST(), and TEST_F().
 {
     Require( energies != nullptr );
     energies->resize( num_energies() );
     for( size_t i = 0; i < energies->size(); ++i )
     {
         energies->at( i ) = energy_at( i );
     }
 }
bool has_energy (double energy) const
check if a specific energy is available
References YieldParent::energy_index().
 {
     return energy_index( energy ) != -1;
 }
int energy_index (double energy) const
get the index to that energy
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::get_energies().
Referenced by YieldParent::add_data(), YieldParent::has_energy(), and TEST().
 {
     Vec_Dbl energies;
     get_energies( &energies );
     for( size_t i = 0; i < energies.size(); i++ )
     {
         if( ScaleSTL::approx_eq( energy, energies[i] ) )
         {
             return i;
         }
     }
     return -1;
 }
YieldData & data_at (int index)
get yield set by energy index
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
Referenced by YieldParent::get_interp_yields(), get_yield(), YieldParent::get_yields(), ReactionResource::import_fission_yields(), main(), print_yield_data(), Origen::printInterpolatedYields(), Origen::printYieldEnergies(), Origen::printYields(), and TEST().
 {
     return const_cast<YieldData&>(
         static_cast<const YieldParent*>( this )->data_at( index ) );
 }
const YieldData & data_at (int index) const
get yield set by energy index
References YieldParent::b_data, and YieldParent::num_energies().
 {
     Require( index >= 0 && index < num_energies() );
     return b_data[index];
 }
YieldData & add_data (double energy, const Vec_Int & id, const Vec_Dbl & val, bool append = false)
add a new yield set (overwrite existing by default)
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::add_fp(), YieldData::b_yields, YieldParent::data(), YieldParent::energy_index(), YieldParent::num_fps(), YieldData::reset_yields(), YieldData::set_energy(), YieldData::set_yield_at(), and auxiliary_erf_m::y.
Referenced by YieldResourceIO_stab1::read(), and TEST().
 {
     Require( id.size() == val.size() );
     int e = energy_index( energy );
     YieldData* y;
     // jDebugLine("energy="<<energy<<" with e="<<e);
     // yield doesn't exist already
     if( e == -1 )
     {
         // jDebugLine("  yield does not exist");
         // find the slot where the energy needs to be added
         std::vector<YieldData>* ys = this->data();
         bool found = false;
         size_t i;
         for( i = 0; i < ys->size(); i++ )
         {
             y = &( *ys )[i];
             if( energy < y->energy() )
             {
                 ys->insert( ys->begin() + i, YieldData() );
                 found = true;
                 break;
             }
         }
         // jDebugLine("  found="<<found);
         // if we didn't find the right energy slot, it must be at the end
         if( !found )
         {
             i = ys->size();
             ys->resize( ys->size() + 1 );
             y = &( *ys )[i];
         }
         // jDebugLine("  i="<<i<<" y="<<y);
         // energy is easy
         y->set_energy( energy );
         // we need the same number of fps as the other yields
         y->b_yields.resize( this->num_fps(), 0.0 );
     }
     else
     {
         y = &( ( *data() )[e] );
         // set existing yields to zero if not appending
         if( !append )
         {
             y->reset_yields();
         }
     }
     // now add the yields
     for( size_t j = 0; j < id.size(); ++j )
     {
         // jDebugLine("    adding id="<<id[j]<<" val="<<val[j]);
         // index in yields array for this fp
         int k = add_fp( id[j] );
         // jDebugLine("    setting k="<<k);
         // set yield index k
         y->set_yield_at( k, val[j] );
     }
     return *y;
 }
bool has_fp (int fp_izzzaaa) const
this fissionable nuclide has fp id
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
References YieldParent::fp_index().
Referenced by YieldResource::has_fp(), YieldParent::interp_yield(), TEST(), and TEST_F().
 { return fp_index( fp_id ) != -1; }
int fp_index (int fp_izzzaaa) const
fission product index (-1 if not found)
Examples:
Core/io/tests/tstYieldResourceIO.cpp, and Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_fp_map.
Referenced by YieldParent::add_fp(), get_yield(), YieldParent::has_fp(), YieldParent::interp_yield(), main(), YieldParent::remove_fp(), YieldParent::set_fp_ids(), and TEST().
 {
     auto it = b_fp_map.find( fp_izzzaaa );
     if( it != b_fp_map.end() )
     {
         return it->second;
     }
     return -1;
 }
int add_fp (int fp_izzzzaaa)
add a new fission product (if doesn't already exist)
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_data, YieldParent::b_fp_map, YieldParent::fp_index(), and YieldParent::num_fps().
Referenced by YieldParent::add_data(), and TEST().
 {
     // index in yields array for this fp
     int k = fp_index( fp_izzzaaa );
     // if doesn't exist add it
     if( k == -1 )
     {
         k = num_fps();
         b_fp_map[fp_izzzaaa] = k;
         // need to add zero to other yields
         for( size_t ii = 0; ii < b_data.size(); ++ii )
         {
             b_data[ii].yields().push_back( 0.0 );
         }
     }
     Ensure( k >= 0 && k < num_fps() );
     return k;
 }
int num_fps () const
number of fission products
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_fp_map.
Referenced by YieldParent::add_data(), YieldParent::add_fp(), YieldParent::get_interp_yields(), YieldParent::interp_yield(), YieldResource::num_fps(), print_yield_data(), YieldParent::set_fp_ids(), TEST_F(), and YieldResourceIO_stab1::write().
 { return b_fp_map.size(); }
void get_fp_ids (Vec_Int * ids) const
get all fission product ids
Examples:
Core/io/tests/tstYieldResourceIO.cpp.
References YieldParent::b_fp_map.
Referenced by ReactionResource::import_fission_yields(), print_yield_data(), Origen::printInterpolatedYields(), Origen::printYields(), TEST(), YieldResource::to_json(), and YieldResourceIO_stab1::write().
 {
     ids->resize( b_fp_map.size() );
     auto it = b_fp_map.begin();
     auto end = b_fp_map.end();
     while( it != end )
     {
         ( *ids )[it->second] = it->first;
         ++it;
     }
 }
void get_yields (Vec_Dbl * yields, int energy_index) const
get yields
References YieldParent::data_at(), YieldParent::num_energies(), and YieldData::yields().
Referenced by YieldResourceIO_stab1::write().
 {
     Require( energy_index >= 0 && energy_index < num_energies() );
     *yields = data_at( energy_index ).yields();
 }
void get_interp_yields (Vec_Dbl * yields, double energy, int interp = INTERP_PREFERRED) const
interpolate all yields
Examples:
Core/io/tests/tstYieldResourceIO.cpp.
References YieldParent::data_at(), YieldData::energy(), YieldParent::fp_map(), YieldParent::num_energies(), YieldParent::num_fps(), YieldData::yield_at(), and YieldData::yields().
Referenced by YieldParent::interp_yield(), Origen::printInterpolatedYields(), and TEST().
 {
     size_t nsets = this->num_energies();
     Check( nsets >= 1 && nsets <= 4 );
     if( nsets == 1 )
     {
         *interpolated_yields = data_at( 0 ).yields();
     }
     else if( nsets == 2 || nsets == 3 || nsets == 4 )
     {
         // handle extrapolation
         if( energy <= data_at( 0 ).energy() )
         {
             *interpolated_yields = Vec_Dbl( data_at( 0 ).yields() );
         }
         else if( energy > data_at( nsets - 1 ).energy() )
         {
             *interpolated_yields = Vec_Dbl( data_at( nsets - 1 ).yields() );
         }
         else
         {
             interpolated_yields->resize( num_fps() );
             // interpolation
             size_t ja = 0;
             size_t jb = 1;
             for( size_t iset = 0; iset < nsets - 1; ++iset )
             {
                 if( energy > data_at( iset ).energy() &&
                     energy <= data_at( iset + 1 ).energy() )
                     break;
                 ja++;
                 jb++;
             }
             double ea = data_at( ja ).energy();
             double eb = data_at( jb ).energy();
             const YieldData& dataA = this->data_at( ja );
             const YieldData& dataB = this->data_at( jb );
             size_t fp_size = fp_map().size();
             Check( fp_size == dataA.yields().size() );
             Check( fp_size == dataB.yields().size() );
             for( size_t i = 0; i < fp_size; ++i )
             {
                 double yield = endf::Tab1::interpolate( ea,
                                                         dataA.yield_at( i ),
                                                         eb,
                                                         dataB.yield_at( i ),
                                                         energy,
                                                         interp );
                 ( *interpolated_yields )[i] = yield;
             }
         }
     }
     else
     {
         Insist( false,
                 "Fatal error: number of fission yield sets must equal 1-4." );
     }
 }
double interp_yield (int fp_izzzaaa, double energy, int interp = INTERP_PREFERRED) const
interpolate a single yield (will return 0.0 if doesn't exist)
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::fp_index(), YieldParent::fp_map(), YieldParent::get_interp_yields(), YieldParent::has_fp(), and YieldParent::num_fps().
Referenced by inject_fission_yields(), YieldResource::interp_yield(), TEST(), and TEST_F().
 {
     if( has_fp( fp_id ) )
     {
         // yes I know this is (REALLY) inefficient
         int fp_index = this->fp_map().find( fp_id )->second;
         Check( fp_index >= 0 );
         Vec_Dbl yields( num_fps() );
         get_interp_yields( &yields, energy, interp );
         return yields[fp_index];
     }
     else
     {
         return 0.0;
     }
 }
int interp_method () const
get interpolation method
References YieldParent::b_interp_method.
Referenced by YieldResource::to_json().
 { return b_interp_method; }
void set_interp_method (int method)
set interpolation method
References YieldParent::b_interp_method.
 { b_interp_method = value; }
void remove_data_at (int index)
remove a set of yield data
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_data, and YieldParent::num_energies().
Referenced by TEST_F().
 {
     Require( index >= 0 && index < num_energies() );
     b_data.erase( b_data.begin() + index );
 }
bool remove_fp (int fp_izzzaaa)
remove one fp
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_data, YieldParent::b_fp_map, and YieldParent::fp_index().
Referenced by TEST_F().
 {
     int index = fp_index( fp_izzzaaa );
     if( index == -1 ) return false;
     b_fp_map.erase( fp_izzzaaa );
     for( size_t e = 0; e < b_data.size(); ++e )
     {
         Vec_Dbl& b_yields = b_data[e].yields();
         b_yields.erase( b_yields.begin() + index );
     }
     return true;
 }
void set_fp_ids (const Vec_Int & ids)
keep only these fp
Examples:
Core/re/tests/tstYieldResource.cpp.
References YieldParent::b_data, YieldParent::b_fp_map, YieldParent::fp_index(), YieldParent::fp_map(), and YieldParent::num_fps().
Referenced by TEST_F().
 {
     // get indices of fission products & create new fp_map
     Vec_Int indices( ids.size(), 0 );
     FPMap_t fp_map;
     for( size_t j = 0; j < ids.size(); ++j )
     {
         indices[j] = fp_index( ids[j] );
         fp_map[ids[j]] = j;
     }
     b_fp_map = fp_map;
     // copy over old data to new
     for( size_t e = 0; e < b_data.size(); ++e )
     {
         Vec_Dbl& b_yields = b_data[e].yields();
         Vec_Dbl yields( ids.size(), 0.0 );
         for( size_t j = 0; j < ids.size(); ++j )
         {
             int k = indices[j];
             if( k != -1 )
             {
                 yields[j] = b_yields[k];
             }
         }
         b_yields = yields;
     }
     Ensure( b_fp_map.size() == ids.size() );
 #ifdef ENSURE_ON
     for( size_t e = 0; e < b_data.size(); ++e )
     {
         Ensure( b_data[e].num_yields() == this->num_fps() );
     }
 #endif
 }
const std::vector< YieldData > & data () const protected
get const yield sets
References YieldParent::b_data.
Referenced by YieldParent::add_data(), YieldResource::check_consistency(), and YieldResource::to_json().
 { return b_data; }
std::vector< YieldData > * data () protected
get yield sets
References YieldParent::b_data.
 { return &b_data; }
const FPMap_t & fp_map () const protected
get const fp map
References YieldParent::b_fp_map.
Referenced by YieldResource::check_consistency(), YieldParent::get_interp_yields(), YieldParent::interp_yield(), and YieldParent::set_fp_ids().
 { return b_fp_map; }
FPMap_t & fp_map () protected
get fp map
References YieldParent::b_fp_map.
 { return b_fp_map; }
Friends And Related Function Documentation
friend class YieldResource friend
Member Data Documentation
int b_interp_method private
Referenced by YieldParent::interp_method(), and YieldParent::set_interp_method().
FPMap_t b_fp_map private
Referenced by YieldParent::add_fp(), YieldParent::fp_index(), YieldParent::fp_map(), YieldParent::get_fp_ids(), YieldParent::num_fps(), YieldParent::remove_fp(), and YieldParent::set_fp_ids().
std::vector<YieldData> b_data private
Referenced by YieldParent::add_fp(), YieldParent::data(), YieldParent::data_at(), YieldParent::energy_at(), YieldParent::num_energies(), YieldParent::remove_data_at(), YieldParent::remove_fp(), and YieldParent::set_fp_ids().
int b_id private
Referenced by YieldParent::id().
The documentation for this class was generated from the following files:
Core/re/YieldResource.h
Core/re/YieldResource.cpp