ORIGEN API: GridView_StateInfo Class Reference
GridView_StateInfo Class Reference
#include <GridView_StateInfo.h>
Public Types
typedef ScaleUtils::Math::GridData< float, float > GD_t
typedef StateInfo Type
Public Member Functions
GridView_StateInfo (SCP_StateInfo obj)
initialize
bool match (const StateInfo &other) const
Equality check.
const GD_t::Vec_Rptr & r () const
Return GridData responses.
const GD_t::Vec_I & rextents () const
Return GridData extents.
GD_t::I_t nr () const
Return the number of responses.
const StateInfo & obj () const
Return the StateInfo object of this view.
SP_StateInfo permute (const GD_t::Vec_Z &z) const
Produce a permutation (i.e. interpolation)
Private Attributes
SCP_StateInfo b_obj
GD_t::Vec_Rptr b_r
GD_t::Vec_I b_rextents
GD_t::SP_Vec_R b_tag_values
Detailed Description
Examples:
tstGridView.cpp.
Member Typedef Documentation
typedef ScaleUtils::Math::GridData<float, float> GD_t
typedef StateInfo Type
Constructor & Destructor Documentation
GridView_StateInfo (SCP_StateInfo obj)
initialize
References GridView_StateInfo::b_obj, GridView_StateInfo::b_r, GridView_StateInfo::b_rextents, and GridView_StateInfo::b_tag_values.
                                                           : b_obj( obj )
 {
     Require( obj != nullptr );
     // reserve space for everything
     // b_r.reserve(I_TAGS+1);
     auto tag_values = obj->tag_manager().listInterpValues();
     // set the first 5 that we always have
     b_r.resize( ( tag_values.size() > 0 ) ? I_TAGS + 1 : I_TAGS );
     b_r[I_TIME] = &( b_obj->b_time );
     b_r[I_ENERGY] = &( b_obj->b_energy );
     b_r[I_POWER] = &( b_obj->b_power );
     b_r[I_FLUX] = &( b_obj->b_flux );
     b_r[I_FLUENCE] = &( b_obj->b_fluence );
     b_tag_values = nullptr;
     if( tag_values.size() > 0 )
     {
         // only add tags if we have them
         b_tag_values = std::make_shared<GD_t::Vec_R>();
         b_tag_values->assign( tag_values.begin(), tag_values.end() );
         b_r[I_TAGS] = &( b_tag_values->at( 0 ) );
         b_rextents = {1, 1, 1, 1, 1, b_tag_values->size()};
     }
     else
     {
         b_rextents = {1, 1, 1, 1, 1};
     }
 }
Member Function Documentation
bool match (const StateInfo & other) const
Equality check.
Examples:
tstGridView.cpp.
References GridView_StateInfo::b_obj, and StateInfo::match().
Referenced by TEST().
 {
     return StateInfo::match( *b_obj, other );
 }
const GridView_StateInfo::GD_t::Vec_Rptr & r () const
Return GridData responses.
Examples:
tstGridView.cpp.
References GridView_StateInfo::b_r.
Referenced by TEST().
 {
     return b_r;
 }
const GridView_StateInfo::GD_t::Vec_I & rextents () const
Return GridData extents.
Examples:
tstGridView.cpp.
References GridView_StateInfo::b_rextents.
Referenced by TEST().
 {
     return b_rextents;
 }
GridView_StateInfo::GD_t::I_t nr () const
Return the number of responses.
Examples:
tstGridView.cpp.
References GridView_StateInfo::b_rextents.
Referenced by TEST().
 {
     return b_rextents.size();
 }
const StateInfo & obj () const
Return the StateInfo object of this view.
References GridView_StateInfo::b_obj.
Referenced by GridView_StateInfo::permute().
 { return *b_obj; }
SP_StateInfo permute (const GD_t::Vec_Z & z) const
Produce a permutation (i.e. interpolation)
Parameters
z Interpolated responses from which to reconstruct a StateInfo object
References GridView_StateInfo::b_obj, GridView_StateInfo::b_tag_values, GridView_StateInfo::obj(), and TagManager::setInterpValues().
 {
     SP_StateInfo obj( new StateInfo( *b_obj ) );
     obj->set_time( ( *z[I_TIME] )[0] );
     obj->set_energy( ( *z[I_ENERGY] )[0] );
     obj->set_power( ( *z[I_POWER] )[0] );
     obj->set_flux( ( *z[I_FLUX] )[0] );
     obj->set_fluence( ( *z[I_FLUENCE] )[0] );
     if( b_tag_values != nullptr )
     {
         GridView_StateInfo::GD_t::SP_Vec_R tags = z[I_TAGS];
         std::vector<double> values;  // convert to double
         values.assign( tags->begin(), tags->end() );
         // get a new TagManager, assign values, and reset
         TagManager tm = obj->tag_manager();
         tm.setInterpValues( values );
         obj->set_tag_manager( tm );
     }
     return obj;
 }
Member Data Documentation
SCP_StateInfo b_obj private
Referenced by GridView_StateInfo::GridView_StateInfo(), GridView_StateInfo::match(), GridView_StateInfo::obj(), and GridView_StateInfo::permute().
GD_t::Vec_Rptr b_r private
Referenced by GridView_StateInfo::GridView_StateInfo(), and GridView_StateInfo::r().
GD_t::Vec_I b_rextents private
Referenced by GridView_StateInfo::GridView_StateInfo(), GridView_StateInfo::nr(), and GridView_StateInfo::rextents().
GD_t::SP_Vec_R b_tag_values private
Referenced by GridView_StateInfo::GridView_StateInfo(), and GridView_StateInfo::permute().
The documentation for this class was generated from the following files:
Core/dc/GridView_StateInfo.h
Core/dc/GridView_StateInfo.cpp