ORIGEN API: GammaResource Class Reference
GammaResource Class Reference
#include <GammaResource.h>
Public Types
typedef std::shared_ptr< GammaResource > SP
typedef std::shared_ptr< const GammaResource > SCP
typedef std::shared_ptr< SP_Emission > SP_Vec_SP_Emission_t
typedef std::map< int, size_t > Map_t
typedef std::shared_ptr< Map_t > SP_Map_t
Public Member Functions
GammaResource ()
size_t emission_index (int id) const
EmissionSpectrum emission (int id) const
bool add_emission (EmissionSpectrum)
bool has_emission (int id) const
EmissionSpectrum emission_at (size_t i) const
size_t emission_size () const
EnergyRange_t energy_range () const
Public Attributes
std::vector< EmissionSpectrum > b_emission
std::map< int, size_t > b_map
int b_field_id
Detailed Description
Examples:
tstGammaResourceIO.cpp.
Member Typedef Documentation
typedef std::shared_ptr<GammaResource> SP
typedef std::shared_ptr<const GammaResource> SCP
typedef std::shared_ptr<SP_Emission> SP_Vec_SP_Emission_t inherited
typedef std::map<int, size_t> Map_t inherited
typedef std::shared_ptr<Map_t> SP_Map_t inherited
Constructor & Destructor Documentation
GammaResource ()
References EmissionResource::b_field_id, and Origen::PHOTON_FIELD.
 { b_field_id = PHOTON_FIELD; }
Member Function Documentation
size_t emission_index (int id) const inherited
References EmissionResource::b_map, and Origen::BAD_SIZE_T.
Referenced by EmissionResource::add_emission(), EmissionResource::emission(), and EmissionResource::has_emission().
 {
     auto it = b_map.find( id );
     if( it == b_map.end() ) return BAD_SIZE_T;
     return it->second;
 }
EmissionSpectrum emission (int id) const inherited
Examples:
tstEmissionResource.cpp, and tstGammaResourceIO.cpp.
References EmissionResource::b_emission, Origen::BAD_INT, Origen::BAD_SIZE_T, and EmissionResource::emission_index().
Referenced by TEST().
 {
     size_t i = emission_index( id );
     if( i < BAD_SIZE_T ) return b_emission[i];
     return EmissionSpectrum( BAD_INT );  // id is bad
 }
bool add_emission (EmissionSpectrum em) inherited
Examples:
tstEmissionResource.cpp.
References EmissionResource::b_emission, EmissionResource::b_map, Origen::BAD_SIZE_T, EmissionResource::emission_index(), and EmissionSpectrum::id().
Referenced by TEST().
 {
     size_t i = emission_index( em.id() );
     if( i < BAD_SIZE_T )
     {
         b_emission[i] = em;
         return true;
     }
     else
     {
         b_emission.emplace_back( em );
         b_map[em.id()] = b_emission.size() - 1;
         return false;
     }
 }
bool has_emission (int id) const inherited
Examples:
tstEmissionResource.cpp, and tstGammaResourceIO.cpp.
References Origen::BAD_SIZE_T, and EmissionResource::emission_index().
Referenced by TEST().
 {
     return emission_index( id ) != BAD_SIZE_T;
 }
EmissionSpectrum emission_at (size_t i) const inherited
Examples:
tstGammaResourceIO.cpp.
References EmissionResource::b_emission.
Referenced by TEST(), and TEST_P().
 {
     Require( i < b_emission.size() );
     return b_emission[i];
 }
size_t emission_size () const inherited
Examples:
tstGammaResourceIO.cpp.
References EmissionResource::b_emission.
Referenced by TEST(), and TEST_P().
 { return b_emission.size(); }
std::pair< double, double > energy_range () const inherited
References EmissionResource::b_emission, Origen::EMAX, Origen::EMIN, and auxiliary_erf_m::er.
 {
     double emin = EMIN;
     double emax = EMAX;
     for( const auto& em : b_emission )
     {
         auto er = em.energy_range();
         emin = std::min( emin, er.first );
         emax = std::max( emax, er.second );
     }
     return std::make_pair( emin, emax );
 }
Member Data Documentation
std::vector<EmissionSpectrum> b_emission inherited
Referenced by EmissionResource::add_emission(), EmissionResource::emission(), EmissionResource::emission_at(), EmissionResource::emission_size(), EmissionResource::energy_range(), and GammaResourceIO_cimg::read().
std::map<int, size_t> b_map inherited
Referenced by EmissionResource::add_emission(), EmissionResource::emission_index(), and GammaResourceIO_cimg::read().
int b_field_id inherited
Referenced by GammaResource::GammaResource(), and GammaResourceIO_cimg::read().
The documentation for this class was generated from the following files:
Core/re/GammaResource.h
Core/re/GammaResource.cpp