ORIGEN API: Core/dc/f/NuclideSetInterface.cpp File Reference
NuclideSetInterface.cpp File Reference
#include "NuclideSetInterface.h"
#include <string.h>
Functions
void * Origen_NuclideSet_initialize_copy (Origen_NuclideSet *orig)
void * Origen_NuclideSet_initialize_legacy_vec (int *nlt, int *nac, int *nfp, Vec_Int *ids)
void * Origen_NuclideSet_initialize_legacy (int *nlt, int *nac, int *nfp, size_t *ids_size, int *ids)
void Origen_NuclideSet_set_ids_legacy_vec (void *Origen_NuclideSet_ptr, int *nlt, int *nac, int *nfp, Vec_Int *ids)
void Origen_NuclideSet_set_ids_legacy (void *Origen_NuclideSet_ptr, int *nlt, int *nac, int *nfp, size_t *ids_size, int *ids)
size_t Origen_NuclideSet_ids_size (void *Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_ids (void *Origen_NuclideSet_ptr)
void Origen_NuclideSet_get_ids_vec (void *Origen_NuclideSet_ptr, Vec_Int *&ids)
void Origen_NuclideSet_set_ids_vec (void *Origen_NuclideSet_ptr, Vec_Int *ids)
void Origen_NuclideSet_manageptr_ids (void *Origen_NuclideSet_ptr, Vec_Int *&ids)
void Origen_NuclideSet_getptr_ids_vec (void *Origen_NuclideSet_ptr, Vec_Int const *&ids)
void Origen_NuclideSet_get_ids (void *Origen_NuclideSet_ptr, size_t *ids_size, int *ids)
void Origen_NuclideSet_set_ids (void *Origen_NuclideSet_ptr, size_t *ids_size, int *ids)
int Origen_NuclideSet_sizzzaaa_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_izzzaaa_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_zzzaaai_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_s_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_i_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_z_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_a_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_total_nuclides (void *Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_sublibs (void *Origen_NuclideSet_ptr)
size_t Origen_NuclideSet_count_sublibs (void *Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_sublib (void *Origen_NuclideSet_ptr, int *s)
int Origen_NuclideSet_ids_at (void *Origen_NuclideSet_ptr, size_t *index)
size_t Origen_NuclideSet_num_in_sublib (void *Origen_NuclideSet_ptr, int *s)
size_t Origen_NuclideSet_sublib_begin (void *Origen_NuclideSet_ptr, int *s, bool *fixed)
size_t Origen_NuclideSet_sublib_end (void *Origen_NuclideSet_ptr, int *s)
size_t Origen_NuclideSet_lookup_index (void *Origen_NuclideSet_ptr, int *id, bool *fixed)
size_t Origen_NuclideSet_lookup_index_guess (void *Origen_NuclideSet_ptr, int *izzzaaa, bool *fixed)
bool Origen_NuclideSet_lookup_index_all (void *Origen_NuclideSet_ptr, ScaleSTL_Vec_Int *&ids, int *izzzaaa, bool *fixed)
size_t Origen_NuclideSet_NOT_FOUND (bool *fixed)
void Origen_NuclideSet_convert_symbol_to_izzzaaa (ScaleSTL_Vec_Str *&symbols, ScaleSTL_Vec_Int *&ids)
void Origen_NuclideSet_convert_sizzzaaa_to_zzzaaai (ScaleSTL_Vec_Int *&ids)
void * Origen_NuclideSet_initialize ()
void Origen_NuclideSet_destroy (void *Origen_NuclideSet_ptr)
Function Documentation
void* Origen_NuclideSet_initialize_copy (Origen_NuclideSet * orig)
 {
     return new Origen_NuclideSet( *orig );
 }
void* Origen_NuclideSet_initialize_legacy_vec (int * nlt, int * nac, int * nfp, Vec_Int * ids)
 {
     return new Origen_NuclideSet( *nlt, *nac, *nfp, *ids );
 }
void* Origen_NuclideSet_initialize_legacy (int * nlt, int * nac, int * nfp, size_t * ids_size, int * ids)
 {
     return new Origen_NuclideSet( *nlt, *nac, *nfp, *ids_size, ids );
 }
void Origen_NuclideSet_set_ids_legacy_vec (void * Origen_NuclideSet_ptr, int * nlt, int * nac, int * nfp, Vec_Int * ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->set_ids_legacy( *nlt, *nac, *nfp, *ids );
 }
void Origen_NuclideSet_set_ids_legacy (void * Origen_NuclideSet_ptr, int * nlt, int * nac, int * nfp, size_t * ids_size, int * ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->set_ids_legacy( *nlt, *nac, *nfp, *ids_size, ids );
 }
size_t Origen_NuclideSet_ids_size (void * Origen_NuclideSet_ptr)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->ids_size();
 }
bool Origen_NuclideSet_has_ids (void * Origen_NuclideSet_ptr)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->has_ids();
 }
void Origen_NuclideSet_get_ids_vec (void * Origen_NuclideSet_ptr, Vec_Int *& ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->get_ids( *ids );
 }
void Origen_NuclideSet_set_ids_vec (void * Origen_NuclideSet_ptr, Vec_Int * ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->set_ids( *ids );
 }
void Origen_NuclideSet_manageptr_ids (void * Origen_NuclideSet_ptr, Vec_Int *& ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->manageptr_ids( ids );
 }
void Origen_NuclideSet_getptr_ids_vec (void * Origen_NuclideSet_ptr, Vec_Int const *& ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->getptr_ids( ids );
 }
void Origen_NuclideSet_get_ids (void * Origen_NuclideSet_ptr, size_t * ids_size, int * ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->get_ids_array( *ids_size, ids );
 }
void Origen_NuclideSet_set_ids (void * Origen_NuclideSet_ptr, size_t * ids_size, int * ids)
 {
     ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->set_ids_array( *ids_size, ids );
 }
int Origen_NuclideSet_sizzzaaa_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->sizzzaaa_at( *index );
 }
int Origen_NuclideSet_izzzaaa_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->izzzaaa_at( *index );
 }
int Origen_NuclideSet_zzzaaai_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->zzzaaai_at( *index );
 }
int Origen_NuclideSet_s_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->s_at( *index );
 }
int Origen_NuclideSet_i_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->i_at( *index );
 }
int Origen_NuclideSet_z_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->z_at( *index );
 }
int Origen_NuclideSet_a_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->a_at( *index );
 }
int Origen_NuclideSet_total_nuclides (void * Origen_NuclideSet_ptr)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->total_nuclides();
 }
bool Origen_NuclideSet_has_sublibs (void * Origen_NuclideSet_ptr)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->has_sublibs();
 }
size_t Origen_NuclideSet_count_sublibs (void * Origen_NuclideSet_ptr)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->count_sublibs();
 }
bool Origen_NuclideSet_has_sublib (void * Origen_NuclideSet_ptr, int * s)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->has_sublib( *s );
 }
int Origen_NuclideSet_ids_at (void * Origen_NuclideSet_ptr, size_t * index)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->ids_at( *index );
 }
size_t Origen_NuclideSet_num_in_sublib (void * Origen_NuclideSet_ptr, int * s)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->num_in_sublib( *s );
 }
size_t Origen_NuclideSet_sublib_begin (void * Origen_NuclideSet_ptr, int * s, bool * fixed)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->sublib_begin( *s, *fixed );
 }
size_t Origen_NuclideSet_sublib_end (void * Origen_NuclideSet_ptr, int * s)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )->sublib_end( *s );
 }
size_t Origen_NuclideSet_lookup_index (void * Origen_NuclideSet_ptr, int * id, bool * fixed)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->lookup_index( *id, *fixed );
 }
size_t Origen_NuclideSet_lookup_index_guess (void * Origen_NuclideSet_ptr, int * izzzaaa, bool * fixed)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->lookup_index_guess( *izzzaaa, *fixed );
 }
bool Origen_NuclideSet_lookup_index_all (void * Origen_NuclideSet_ptr, ScaleSTL_Vec_Int *& ids, int * izzzaaa, bool * fixed)
 {
     return ( (Origen_NuclideSet*)Origen_NuclideSet_ptr )
         ->lookup_index_all( ids, *izzzaaa, *fixed );
 }
size_t Origen_NuclideSet_NOT_FOUND (bool * fixed)
References NuclideSet::NOT_FOUND().
 {
     return Origen_NuclideSet::NOT_FOUND( *fixed );
 }
void Origen_NuclideSet_convert_symbol_to_izzzaaa (ScaleSTL_Vec_Str *& symbols, ScaleSTL_Vec_Int *& ids)
References NuclideSet::convert_symbol_to_izzzaaa().
 {
     Origen_NuclideSet::convert_symbol_to_izzzaaa( *symbols, ids );
 }
void Origen_NuclideSet_convert_sizzzaaa_to_zzzaaai (ScaleSTL_Vec_Int *& ids)
References NuclideSet::convert_sizzzaaa_to_zzzaaai().
 {
     Origen_NuclideSet::convert_sizzzaaa_to_zzzaaai( ids );
 }
void* Origen_NuclideSet_initialize ()
 { return new Origen_NuclideSet(); }
void Origen_NuclideSet_destroy (void * Origen_NuclideSet_ptr)
 {
     delete(Origen_NuclideSet*)Origen_NuclideSet_ptr;
 }