ORIGEN API: Core/dc/f/FakeFactoryInterface.h File Reference
FakeFactoryInterface.h File Reference
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/dc/f/DecayDataInterface.h"
#include "Origen/Core/dc/f/LibraryHeaderInterface.h"
#include "Origen/Core/dc/f/LibraryInterface.h"
#include "Origen/Core/dc/f/StateSetInterface.h"
#include "Origen/Core/dc/f/TransitionCoeffInterface.h"
#include "Origen/Core/dc/f/TransitionStructureInterface.h"
#include "ScaleSTL/Vec_FltInterface.h"
#include "ScaleSerialize/StringList.h"
Typedefs
typedef Origen::FakeFactory Origen_FakeFactory
Functions
bool Origen_FakeFactory_Library_random1 (Origen_Library *obj, int *seed)
bool Origen_FakeFactory_DecayData_random1 (Origen_DecayData *obj, Origen_LibraryHeader *lh, int *seed)
bool Origen_FakeFactory_TransitionStructure_random1 (Origen_TransitionStructure *obj, Origen_LibraryHeader *lh, int *seed)
bool Origen_FakeFactory_TransitionCoeff_random1 (Origen_TransitionCoeff *obj, Origen_LibraryHeader *lh, int *seed)
bool Origen_FakeFactory_StateSet_random1 (Origen_StateSet *obj, int *seed)
bool Origen_FakeFactory_DecayData_random2 (Origen_DecayData *obj, int *seed)
bool Origen_FakeFactory_TransitionCoeff_random2 (Origen_TransitionCoeff *obj, int *seed)
bool Origen_FakeFactory_getBounds_Scale6p2_56g (ScaleSTL_Vec_Flt *obj)
bool Origen_FakeFactory_getBounds_Scale6p2_252g (ScaleSTL_Vec_Flt *obj)
void Origen_FakeFactory_getUniformFlux (ScaleSTL_Vec_Flt *flux, ScaleSTL_Vec_Flt *bounds)
void * Origen_FakeFactory_initialize ()
void Origen_FakeFactory_destroy (void *Origen_FakeFactory_ptr)
Typedef Documentation
typedef Origen::FakeFactory Origen_FakeFactory
Function Documentation
bool Origen_FakeFactory_Library_random1 (Origen_Library * obj, int * seed)
References FakeFactory::Library_random1().
bool Origen_FakeFactory_DecayData_random1 (Origen_DecayData * obj, Origen_LibraryHeader * lh, int * seed)
References FakeFactory::DecayData_random1().
bool Origen_FakeFactory_TransitionStructure_random1 (Origen_TransitionStructure * obj, Origen_LibraryHeader * lh, int * seed)
References FakeFactory::TransitionStructure_random1().
bool Origen_FakeFactory_TransitionCoeff_random1 (Origen_TransitionCoeff * obj, Origen_LibraryHeader * lh, int * seed)
References FakeFactory::TransitionCoeff_random1().
bool Origen_FakeFactory_StateSet_random1 (Origen_StateSet * obj, int * seed)
References FakeFactory::StateSet_random1().
bool Origen_FakeFactory_DecayData_random2 (Origen_DecayData * obj, int * seed)
References FakeFactory::DecayData_random2().
bool Origen_FakeFactory_TransitionCoeff_random2 (Origen_TransitionCoeff * obj, int * seed)
References FakeFactory::TransitionCoeff_random2().
bool Origen_FakeFactory_getBounds_Scale6p2_56g (ScaleSTL_Vec_Flt * obj)
References FakeFactory::getBounds_Scale6p2_56g().
bool Origen_FakeFactory_getBounds_Scale6p2_252g (ScaleSTL_Vec_Flt * obj)
References FakeFactory::getBounds_Scale6p2_252g().
void Origen_FakeFactory_getUniformFlux (ScaleSTL_Vec_Flt * flux, ScaleSTL_Vec_Flt * bounds)
References FakeFactory::getUniformFlux().
void* Origen_FakeFactory_initialize ()
void Origen_FakeFactory_destroy (void * Origen_FakeFactory_ptr)