ORIGEN API: origen_betaspectra Type Reference
origen_betaspectra Type Reference
Typedefs
typedef std::shared_ptr< Spectrum > SP
typedef std::shared_ptr< const Spectrum > SCP
typedef std::function< SP_Vec_Dbl(const Vec_Dbl &, const Vec_Int &, const Vec_Dbl &)> Integrator_t
Basic Methods
const Vec_Dbl & bounds () const
return a const reference to bounds
void set_bounds (const Vec_Dbl &)
set the bounds (copy operation)
const Vec_Dbl & intensity () const
return a const reference to intensity
void set_intensity (const Vec_Dbl &)
set the intensity (copy operation)
Comparison
bool match (const Spectrum &) const
bool operator== (const Spectrum &) const
static bool match (const Spectrum &, const Spectrum &)
Convenience Methods
double total_intensity () const
EnergyRange_t energy_range () const
double mean_energy () const
double total_energy_intensity () const
SP_Vec_Dbl newsp_energy_intensity () const
Memory-usage Variants of Other Methods
Vec_Dbl * newptr_energy_intensity () const
SCP_Vec_Dbl scp_intensity () const
return a shared (read-only) intensity pointer
SCP_Vec_Dbl scp_bounds () const
return a shared (read-only) bounds pointer
Mapping Methods
bool map_intensity (const Vec_Dbl &new_bounds, Integrator_t integrator, Vec_Dbl *intensity, double wt=1.0, double tol=ETOL) const
bool map_intensity (const Vec_Dbl &new_bounds, Vec_Dbl *intensity, double wt=1.0, double tol=ETOL) const
void remap_intensity (Vec_Dbl *intensity, double wt=1.0) const
bool has_mapping_variables () const
void clear_mapping_variables () const
std::string print_bins () const
Additional Methods for Language Bindings (e.g. Fortran)
double bounds_at (size_t) const
get element of bounds vector by index
double const * bounds_array () const
return view of bounds vector
size_t bounds_size () const
return size of bounds vector
bool has_bounds () const
return whether the class has a non-null bounds
void get_bounds (Vec_Dbl &) const
populate an existing Vec_Dbl with a copy of bounds
void manageptr_bounds (Vec_Dbl *&)
set the bounds (ownership transfer)
void getptr_bounds (Vec_Dbl const *&) const
retrieve pointer (read-only) to bounds
void get_bounds_array (size_t, double *) const
get array of bounds vector (Fortran)
void set_bounds_array (size_t, double *)
set bounds vector from array (Fortran)
double intensity_at (size_t) const
get element of intensity vector by index
double const * intensity_array () const
return view of intensity vector
size_t intensity_size () const
return size of intensity vector
bool has_intensity () const
return whether the class has a non-null intensity
void get_intensity (Vec_Dbl &) const
populate an existing Vec_Dbl with a copy of intensity
void manageptr_intensity (Vec_Dbl *&)
set the intensity (ownership transfer)
void getptr_intensity (Vec_Dbl const *&) const
retrieve pointer (read-only) to intensity
void get_intensity_array (size_t, double *) const
get array of intensity vector (Fortran)
void set_intensity_array (size_t, double *)
set intensity vector from array (Fortran)
Static Helper Functions
returns true if the new and old bounds have the same min/max energy, i.e. the mapping will be conservative
static void map_intensity (const Vec_Dbl &old_bounds, const Vec_Dbl &new_bounds, const Vec_Int &union_to_old, const Vec_Int &union_to_new, const Vec_Dbl &union_grid, const Vec_Dbl &old_intensity, const Vec_Dbl &union_wts, Vec_Dbl *new_intensity, double wt=1.0)
static std::string print_bins (const Vec_Dbl &bounds, const Vec_Dbl &intensity)
static bool map_bins (const Vec_Dbl &old_bounds, const Vec_Dbl &new_bounds, Vec_Int *union_to_old, Vec_Int *union_to_new, Vec_Dbl *union_grid, double tol=ETOL)
static SP_Vec_Dbl computeUnionWts_1 (const Vec_Dbl &union_grid, const Vec_Int &union_to_old, const Vec_Dbl &old_flux)
Other
SP_Vec_Dbl b_bounds
SP_Vec_Dbl b_intensity
void canonicalize_bounds ()
void canonicalize_intensity ()
Public Member Functions
procedure, pass(this) set_nuclide_type => Origen_BetaSpectra_set_nuclide_type
procedure, pass(this) nuclide_type => Origen_BetaSpectra_nuclide_type
procedure, pass(this) initialize => Origen_BetaSpectra_initialize
procedure, pass(this) destroy => Origen_BetaSpectra_destroy
Member Typedef Documentation
typedef std::shared_ptr<Spectrum> SP inherited
typedef std::shared_ptr<const Spectrum> SCP inherited
typedef std::function<SP_Vec_Dbl(const Vec_Dbl &, const Vec_Int &, const Vec_Dbl &)> Integrator_t inherited
Member Function/Subroutine Documentation
procedure, pass(this) set_nuclide_type ()
procedure, pass(this) nuclide_type ()
procedure, pass(this) initialize ()
procedure, pass(this) destroy ()
const Vec_Dbl & bounds () const inherited
return a const reference to bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Spectrum goes out of scope.
Referenced by Spectrum::operator==(), and StateSetIO_bof::write().
void set_bounds (const Vec_Dbl & bounds) inherited
set the bounds (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstEmissionSpectrum.cpp, Core/re/tests/tstEmissionResource.cpp, and Core/re/tests/tstGammaResource.cpp.
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), GammaResourceIO_cimg::read(), StateSetIO_bof::read(), StateSetIO_s61::read(), FakeFactory::StateSet_random1(), and TEST().
const Vec_Dbl & intensity () const inherited
return a const reference to intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Spectrum goes out of scope.
Referenced by Spectrum::operator==(), and StateSetIO_bof::write().
void set_intensity (const Vec_Dbl & intensity) inherited
set the intensity (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), StateSetIO_bof::read(), GammaResourceIO_cimg::read(), and FakeFactory::StateSet_random1().
bool match (const Spectrum & b) const inherited
Referenced by NeutronSpectra::match(), BetaSpectra::match(), GammaSpectra::match(), and AlphaSpectra::match().
 { return match( *this, b ); }
bool match (const Spectrum & a, const Spectrum & b) static inherited
References Spectrum::b_bounds.
 {
     return approx_eq_vec( *a.b_bounds, *b.b_bounds );
 }
bool operator== (const Spectrum & b) const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, Spectrum::bounds(), and Spectrum::intensity().
Referenced by AlphaSpectra::operator==(), GammaSpectra::operator==(), and BetaSpectra::operator==().
 {
     ORIGEN_COMPARE_SP_VECTOR( bounds, b_bounds, b.b_bounds );
     ORIGEN_COMPARE_SP_VECTOR( intensity, b_intensity, b.b_intensity );
     return true;
 }
double total_intensity () const inherited
References Spectrum::b_intensity, and Spectrum::has_intensity().
Referenced by Spectrum::mean_energy(), and EmissionSpectrum::total_intensity().
 {
     Require( has_intensity() );
     return sum( *b_intensity );
 }
EnergyRange_t energy_range () const inherited
References Spectrum::b_bounds, Origen::EMAX, Origen::EMIN, and auxiliary_erf_m::er.
Referenced by EmissionSpectrum::energy_range().
 {
     EnergyRange_t er( EMIN, EMAX );
     if( b_bounds->size() > 0 )
     {
         er.first = b_bounds->back();
         er.second = b_bounds->front();
     }
     return er;
 }
double mean_energy () const inherited
References Spectrum::total_energy_intensity(), and Spectrum::total_intensity().
 {
     double tei = total_energy_intensity();
     if( tei == 0 ) return 0;
     return tei / total_intensity();
 }
double total_energy_intensity () const inherited
References Spectrum::newsp_energy_intensity().
Referenced by Spectrum::mean_energy(), and EmissionSpectrum::total_energy_intensity().
 {
     return sum( *newsp_energy_intensity() );
 }
SP_Vec_Dbl newsp_energy_intensity () const inherited
References Spectrum::newptr_energy_intensity().
Referenced by Spectrum::total_energy_intensity().
 {
     return SP_Vec_Dbl( newptr_energy_intensity() );
 }
Vec_Dbl * newptr_energy_intensity () const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, and Spectrum::intensity_size().
Referenced by Spectrum::newsp_energy_intensity().
 {
     Vec_Dbl* energy_intensity = new Vec_Dbl( intensity_size() );
     for( size_t i = 0; i < intensity_size(); ++i )
     {
         energy_intensity->at( i ) =
             b_intensity->at( i ) * 0.5 *
             ( b_bounds->at( i ) + b_bounds->at( i + 1 ) );
     }
     return energy_intensity;
 }
SCP_Vec_Dbl scp_intensity () const inherited
return a shared (read-only) intensity pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
SCP_Vec_Dbl scp_bounds () const inherited
return a shared (read-only) bounds pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool map_intensity (const Vec_Dbl & new_bounds, Integrator_t integrator, Vec_Dbl * intensity, double wt = 1.0, double tol = ETOL) const inherited
Referenced by EmissionSpectrum::bin(), Spectrum::map_intensity(), and Spectrum::remap_intensity().
bool map_intensity (const Vec_Dbl & new_bounds, Vec_Dbl * intensity, double wt = 1.0, double tol = ETOL) const inherited
References Spectrum::computeUnionWts_1(), and Spectrum::map_intensity().
 {
     // just use uniform integration
     return map_intensity( new_bounds, computeUnionWts_1, intensity, wt, tol );
 }
void map_intensity (const Vec_Dbl & old_bounds, const Vec_Dbl & new_bounds, const Vec_Int & union_to_old, const Vec_Int & union_to_new, const Vec_Dbl & union_grid, const Vec_Dbl & old_intensity, const Vec_Dbl & union_wts, Vec_Dbl * new_intensity, double wt = 1.0) static inherited
 {
     Require( new_intensity != nullptr );
     Require( new_intensity->size() == new_bounds.size() - 1 );
     // integrate with provided weight
     for( size_t iu = 0; iu < union_grid.size(); ++iu )
     {
         int io = union_to_old[iu];
         int in = union_to_new[iu];
         // TODO: change to different way of recognizing BAD INDEX
         if( io <= 0 || in <= 0 ) continue;
         ( *new_intensity )[in] += old_intensity[io] * wt * union_wts[iu];
     }
 }
void remap_intensity (Vec_Dbl * intensity, double wt = 1.0) const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, Spectrum::b_union_wts, Spectrum::has_mapping_variables(), and Spectrum::map_intensity().
 {
     Require( has_mapping_variables() );
     map_intensity( *b_bounds,
                    *b_new_bounds,
                    *b_union_to_old,
                    *b_union_to_new,
                    *b_union_grid,
                    *b_intensity,
                    *b_union_wts,
                    intensity,
                    wt );
 }
bool has_mapping_variables () const inherited
References Spectrum::b_intensity, Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, and Spectrum::b_union_wts.
Referenced by Spectrum::remap_intensity().
 {
     return b_new_bounds != nullptr && b_union_to_old != nullptr &&
            b_union_to_new != nullptr && b_union_grid != nullptr &&
            b_intensity != nullptr && b_union_wts != nullptr;
 }
void clear_mapping_variables () const inherited
References Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, and Spectrum::b_union_wts.
 {
     b_new_bounds = nullptr;
     b_union_to_old = nullptr;
     b_union_to_new = nullptr;
     b_union_grid = nullptr;
     b_union_wts = nullptr;
 }
std::string print_bins () const inherited
Examples:
Core/dc/tests/tstDiscreteSpectrum.cpp, Core/dc/tests/tstEmissionSpectrum.cpp, Core/io/tests/tstGammaResourceIO.cpp, Core/re/tests/tstEmissionResource.cpp, and Core/re/tests/tstGammaResource.cpp.
References Spectrum::b_bounds, and Spectrum::b_intensity.
Referenced by EmissionSpectrum::print_continuous(), TEST(), and TEST_P().
 {
     return print_bins( *b_bounds, *b_intensity );
 }
std::string print_bins (const Vec_Dbl & bounds, const Vec_Dbl & intensity) static inherited
 {
     Require( ( bounds.size() == 0 && intensity.size() == 0 ) ||
              ( bounds.size() > 1 && bounds.size() == intensity.size() + 1 ) );
     std::stringstream ss;
     double de;
     if( intensity.size() > 0 )
         ss << nprintf( "%21.11e %21.11e\n", bounds.front(), 0.0 );
     for( size_t i = 0; i < intensity.size(); ++i )
     {
         de = bounds[i] - bounds[i + 1];
         ss << nprintf( "%21.11e %21.11e\n", bounds[i], intensity[i] / de );
         ss << nprintf( "%21.11e %21.11e\n", bounds[i + 1], intensity[i] / de );
     }
     if( intensity.size() > 0 )
         ss << nprintf( "%21.11e %21.11e\n", bounds.back(), 0.0 );
     return ss.str();
 }
Vec_Dbl::value_type bounds_at (size_t i) const inherited
get element of bounds vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/io/tests/tstGammaResourceIO.cpp.
Referenced by TEST().
Vec_Dbl::value_type const * bounds_array () const inherited
return view of bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t bounds_size () const inherited
return size of bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by Spectrum::canonicalize_intensity().
bool has_bounds () const inherited
return whether the class has a non-null bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_bounds (Vec_Dbl & bounds) const inherited
populate an existing Vec_Dbl with a copy of bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_bounds (Vec_Dbl *& bounds) inherited
set the bounds (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_bounds (Vec_Dbl const *& bounds) const inherited
retrieve pointer (read-only) to bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_bounds_array (size_t , double *) const inherited
get array of bounds vector (Fortran)
void set_bounds_array (size_t , double *) inherited
set bounds vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type intensity_at (size_t i) const inherited
get element of intensity vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type const * intensity_array () const inherited
return view of intensity vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t intensity_size () const inherited
return size of intensity vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by NeutronSpectra::is_consistent(), Spectrum::newptr_energy_intensity(), EmissionSpectrum::num_continuous(), and NeutronSpectra::resum().
bool has_intensity () const inherited
return whether the class has a non-null intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Spectrum::total_intensity().
void get_intensity (Vec_Dbl & intensity) const inherited
populate an existing Vec_Dbl with a copy of intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_intensity (Vec_Dbl *& intensity) inherited
set the intensity (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_intensity (Vec_Dbl const *& intensity) const inherited
retrieve pointer (read-only) to intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_intensity_array (size_t , double *) const inherited
get array of intensity vector (Fortran)
void set_intensity_array (size_t , double *) inherited
set intensity vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
bool map_bins (const Vec_Dbl & old_bounds, const Vec_Dbl & new_bounds, Vec_Int * union_to_old, Vec_Int * union_to_new, Vec_Dbl * union_grid, double tol = ETOL) static inherited
 {
     return ScaleData::MGFluxMapper<double>::mapEnergyBins(
         old_bounds, new_bounds, union_to_old, union_to_new, union_grid, tol );
 }
SP_Vec_Dbl computeUnionWts_1 (const Vec_Dbl & union_grid, const Vec_Int & union_to_old, const Vec_Dbl & old_flux) static inherited
Referenced by Spectrum::map_intensity().
 {
     jDebugTaggedLine( "pass 1: integrate numerator" );
     Vec_Dbl* c = new Vec_Dbl( union_grid.size() - 1, 0.0 );
     for( size_t i = 0; i < union_grid.size() - 1; ++i )
     {
         ( *c )[i] += union_grid[i] - union_grid[i + 1];
     }
     jDebugTaggedLine( "pass 2: integrate denominator" );
     Vec_Dbl norm( old_flux.size(), 0.0 );
     for( size_t i = 0; i < union_grid.size() - 1; ++i )
     {
         int io = union_to_old[i];
         norm[io] += ( *c )[i];
     }
     jDebugTaggedLine( "pass 3: normalize" );
     for( size_t i = 0; i < union_grid.size() - 1; ++i )
     {
         int io = union_to_old[i];
         ( *c )[i] /= norm[io];
     }
     return SP_Vec_Dbl( c );
 }
void canonicalize_bounds () protected inherited
 {
     // none or 2+ energy boundaries
     Require( bounds_size() == 0 || bounds_size() > 1 );
     Require( decreasing( *b_bounds ) );
 }
void canonicalize_intensity () protected inherited
References Spectrum::b_intensity, and Spectrum::bounds_size().
 {
     Require( bounds_size() == 0 || b_intensity->size() < bounds_size() );
     if( bounds_size() == 0 ) return;
     // fill intensity with zeros for all thermal energies not present
     size_t orig_size = b_intensity->size();
     b_intensity->resize( bounds_size() - 1 );
     for( size_t i = orig_size; i < bounds_size() - 1; ++i )
     {
         ( *b_intensity )[i] = 0.0;
     }
 }
Member Data Documentation
SP_Vec_Dbl b_bounds protected inherited
Referenced by Spectrum::energy_range(), Spectrum::match(), Spectrum::newptr_energy_intensity(), Spectrum::operator==(), Spectrum::print_bins(), and Spectrum::remap_intensity().
SP_Vec_Dbl b_intensity protected inherited
Referenced by Spectrum::canonicalize_intensity(), Spectrum::has_mapping_variables(), NeutronSpectra::is_consistent(), Spectrum::newptr_energy_intensity(), Spectrum::operator==(), Spectrum::print_bins(), Spectrum::remap_intensity(), NeutronSpectra::resum(), and Spectrum::total_intensity().
The documentation for this type was generated from the following file:
Core/dc/f/BetaSpectra_M.f90