ORIGEN API: TransitionSystem Class Reference
TransitionSystem Class Reference abstract
#include <TransitionSystem.h>
Defines the interface TransitionSystem.
Public Types
typedef SP_TransitionSystem SP
typedef WP_TransitionSystem WP
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::TransitionSystem>>
See Origen::TransitionSystem for details.
SP_Nuclide add_nuclide (int isomeric_state, SP_Species species)
SP_Nuclide add_nuclide (int isomeric_state, int charge_number, int mass_number)
SP_Nuclide add_nuclide (int izzzaaa)
SP_Nuclide nuclide (int nuclide_id) const
void get_nuclide (int nuclide_id, SP_Nuclide &nuclide) const
void set_nuclide (SP_Nuclide nuclide)
std::vector< SP_Nuclide > nuclides () const
void get_nuclides (std::vector< SP_Nuclide > &nuclides) const
void set_nuclides (std::vector< SP_Nuclide > nuclides)
size_t num_nuclides () const
SP_Nuclide add_byproduct (int byproduct_id)
SP_Nuclide byproduct (int byproduct_id) const
std::vector< SP_Nuclide > byproducts () const
ByproductCount_t num_byproducts () const
SP_Species add_species (int charge_number, int mass_number)
SP_Species add_species (int charge_number, double mass)
SP_Species add_species (int charge_number, int mass_number, double mass)
SP_Species species (int species_id) const
void get_species (int species_id, SP_Species &species) const
void set_species (SP_Species species)
size_t num_species () const
SP_ChannelType add_channel_type (int field_id, int reaction_mt, int decay_mode=0)
SP_ChannelType add_channel_type (SP_Field field, int reaction_mt, int decay_mode=0)
SP_ChannelType add_channel_type (int decay_mode)
SP_ChannelType channel_type (SP_Field field, int reaction_mt, int decay_mode=0)
SP_ChannelType channel_type (int decay_mode)
SP_Field add_field (int field_id)
SP_Field field (int field_id) const
void populate_gains ()
void clear_gains ()
Public Member Functions
virtual ~TransitionSystem ()
Protected Member Functions
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual bool is_initialized_impl () const
useful to chain
Private Member Functions
virtual SP_Nuclide add_nuclide_impl (int isomeric_state, SP_Species species)
virtual SP_Nuclide add_nuclide_impl (int isomeric_state, int charge_number, int mass_number)=0
virtual SP_Species add_species_impl (int charge_number, int mass_number)=0
virtual SP_Species add_species_impl (int charge_number, double mass)
virtual SP_Species add_species_impl (int charge_number, int mass_number, double mass)
virtual SP_ChannelType add_channel_type_impl (int field_id, int reaction_mt, int decay_mode)=0
virtual SP_ChannelType add_channel_type_impl (SP_Field field, int reaction_mt, int decay_mode)=0
virtual SP_ChannelType add_channel_type_impl (int decay_mode)=0
virtual SP_ChannelType channel_type_impl (SP_Field field, int reaction_mt, int decay_mode)=0
virtual SP_ChannelType channel_type_impl (int decay_mode)=0
virtual std::vector< SP_Nuclide > nuclides_impl () const =0
virtual void get_nuclides_impl (std::vector< SP_Nuclide > &nuclides) const =0
virtual void set_nuclides_impl (std::vector< SP_Nuclide > nuclides)=0
virtual SP_Species species_impl (int species_id) const =0
virtual void get_species_impl (int species_id, SP_Species &species) const =0
virtual void set_species_impl (SP_Species species)=0
virtual SP_Nuclide nuclide_impl (int nuclide_id) const =0
virtual void get_nuclide_impl (int nuclide_id, SP_Nuclide &nuclide) const =0
virtual void set_nuclide_impl (SP_Nuclide nuclide)=0
virtual size_t num_nuclides_impl () const =0
virtual size_t num_species_impl () const =0
virtual void populate_gains_impl ()
virtual void clear_gains_impl ()
virtual SP_Field add_field_impl (int field_id)=0
virtual SP_Field field_impl (int field_id) const =0
virtual Scale::Json::Value to_json_impl () const
useful to chain
virtual SP_Nuclide add_byproduct_impl (int byproduct_id)=0
virtual SP_Nuclide byproduct_impl (int byproduct_id) const =0
virtual std::vector< SP_Nuclide > byproducts_impl () const =0
Detailed Description
Defines the interface TransitionSystem.
The transition system manages all the data.
See also
Nuclide, Channel, ChannelType, Field, Species, Transition
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Member Typedef Documentation
typedef SP_TransitionSystem SP
typedef WP_TransitionSystem WP
Constructor & Destructor Documentation
~TransitionSystem () virtual
 {}
Member Function Documentation
Nuclide::SP add_nuclide (int isomeric_state, SP_Species species)
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
References auxiliary::nuclide().
Referenced by TransitionSystemAdapter_DecayResource::extend(), TransitionSystemAdapter_TransitionMatrix::extend(), TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), TransitionMatrixUpdater::load(), TransitionSystem_Gen_Setup::SetUp(), and TEST().
 {
     Nuclide::SP nuclide = add_nuclide_impl( isomeric_state, species );
     nuclide->set_system( this );
     return nuclide;
 }
Nuclide::SP add_nuclide (int isomeric_state, int charge_number, int mass_number)
References auxiliary::nuclide().
 {
     Nuclide::SP nuclide =
         add_nuclide_impl( isomeric_state, charge_number, mass_number );
     nuclide->set_system( this );
     return nuclide;
 }
Nuclide::SP add_nuclide (int izzzaaa)
References auxiliary::nuclide().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( izzzaaa, s, i, z, a );
     Check( s == 0 );
     Nuclide::SP nuclide = add_nuclide_impl( i, z, a );
     nuclide->set_system( this );
     return nuclide;
 }
Nuclide::SP nuclide (int nuclide_id) const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp, Manager/libld/tests/tstTransitionMatrixUpdater.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by check_og_xs(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), TransitionMatrixUpdater::fetch_ts_nuclides(), TransitionSystem_Gen::get_nuclide_impl(), LibraryBuilder::search_reaction_transitions(), TransitionSystem_Gen::set_nuclide_impl(), Origen::test::TEST(), TEST_F(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     return nuclide_impl( nuclide_id );
 }
void get_nuclide (int nuclide_id, SP_Nuclide & nuclide) const
 {
     get_nuclide_impl( nuclide_id, nuclide );
 }
void set_nuclide (SP_Nuclide nuclide)
 {
     set_nuclide_impl( nuclide );
 }
std::vector< Nuclide::SP > nuclides () const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_reaction_transitions(), TransitionSystemAdapter_TransitionMatrix::extend(), TransitionSystem_Gen::get_nuclides_impl(), TransitionSystem_Gen::nuclides_impl(), and Origen::printTransitionSystemXs().
 {
     return nuclides_impl();
 }
void get_nuclides (std::vector< SP_Nuclide > & nuclides) const
 {
     get_nuclides_impl( nuclides );
 }
void set_nuclides (std::vector< SP_Nuclide > nuclides)
 {
     set_nuclides_impl( nuclides );
 }
size_t num_nuclides () const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
 { return num_nuclides_impl(); }
SP_Nuclide add_byproduct (int byproduct_id)
Referenced by Channel_Gen::update_byproduct_transitions_impl().
 {
     return add_byproduct_impl( byproduct_id );
 }
SP_Nuclide byproduct (int byproduct_id) const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_byproduct_impl().
 {
     return byproduct_impl( byproduct_id );
 }
std::vector< SP_Nuclide > byproducts () const
Referenced by TransitionSystem_Gen::byproducts_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), and LibraryBuilder::search_reaction_transitions().
 {
     return byproducts_impl();
 }
ByproductCount_t num_byproducts () const
Species::SP add_species (int charge_number, int mass_number)
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), and TransitionSystem_Gen_Setup::SetUp().
 {
     return add_species_impl( charge_number, mass_number );
 }
Species::SP add_species (int charge_number, double mass)
 {
     return add_species_impl( charge_number, mass );
 }
Species::SP add_species (int charge_number, int mass_number, double mass)
 {
     return add_species_impl( charge_number, mass_number, mass );
 }
Species::SP species (int species_id) const
Referenced by TransitionSystem_Gen::get_species_impl(), and TransitionSystem_Gen::set_species_impl().
 {
     return species_impl( species_id );
 }
void get_species (int species_id, SP_Species & species) const
 {
     get_species_impl( species_id, species );
 }
void set_species (SP_Species species)
 {
     set_species_impl( species );
 }
size_t num_species () const
 { return num_species_impl(); }
ChannelType::SP add_channel_type (int field_id, int reaction_mt, int decay_mode = 0)
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), Nuclide::add_loss_impl(), and TransitionSystemAdapter_DecayResource::extend().
 {
     return add_channel_type_impl( field_id, reaction_mt, decay_mode );
 }
ChannelType::SP add_channel_type (SP_Field field, int reaction_mt, int decay_mode = 0)
 {
     return add_channel_type_impl( field, reaction_mt, decay_mode );
 }
ChannelType::SP add_channel_type (int decay_mode)
 {
     return add_channel_type_impl( decay_mode );
 }
SP_ChannelType channel_type (SP_Field field, int reaction_mt, int decay_mode = 0)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), check_og_xs(), TEST_F(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     return channel_type_impl( field, reaction_mt, decay_mode );
 }
SP_ChannelType channel_type (int decay_mode)
 {
     return channel_type_impl( decay_mode );
 }
Field::SP add_field (int field_id)
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), TransitionSystem_Gen::channel_type_impl(), TransitionSystemAdapter_TransitionMatrix::extend(), and TEST_F().
 {
     return add_field_impl( field_id );
 }
Field::SP field (int field_id) const
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), TransitionSystem_Gen::add_field_impl(), check_og_xs(), TransitionMatrixUpdater::get_transition_matrix(), TEST_F(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     return field_impl( field_id );
 }
void populate_gains ()
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystemAdapter_DecayResource::extend(), TransitionSystemAdapter_TransitionMatrix::extend(), TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), and TransitionSystem_Gen_Setup::SetUp().
 { populate_gains_impl(); }
void clear_gains ()
 { clear_gains_impl(); }
Nuclide::SP add_nuclide_impl (int isomeric_state, SP_Species species) private virtual
 {
     Require( species->has_initialized_charge_number() );
     Require( species->has_initialized_mass_number() );
     Nuclide::SP n = add_nuclide(
         isomeric_state, species->charge_number(), species->mass_number() );
     n->set_species( species );
     return n;
 }
virtual SP_Nuclide add_nuclide_impl (int isomeric_state, int charge_number, int mass_number) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_Species add_species_impl (int charge_number, int mass_number) private pure virtual
Implemented in TransitionSystem_Gen.
Species::SP add_species_impl (int charge_number, double mass) private virtual
 {
     int mass_number = floor( mass + 0.5 );
     return add_species( charge_number, mass_number, mass );
 }
Species::SP add_species_impl (int charge_number, int mass_number, double mass) private virtual
 {
     Species::SP s = add_species( charge_number, mass_number );
     s->set_mass( mass );
     return s;
 }
virtual SP_ChannelType add_channel_type_impl (int field_id, int reaction_mt, int decay_mode) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_ChannelType add_channel_type_impl (SP_Field field, int reaction_mt, int decay_mode) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_ChannelType add_channel_type_impl (int decay_mode) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_ChannelType channel_type_impl (SP_Field field, int reaction_mt, int decay_mode) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_ChannelType channel_type_impl (int decay_mode) private pure virtual
Implemented in TransitionSystem_Gen.
virtual std::vector<SP_Nuclide> nuclides_impl () const private pure virtual
Implemented in TransitionSystem_Gen.
virtual void get_nuclides_impl (std::vector< SP_Nuclide > & nuclides) const private pure virtual
Implemented in TransitionSystem_Gen.
virtual void set_nuclides_impl (std::vector< SP_Nuclide > nuclides) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_Species species_impl (int species_id) const private pure virtual
Implemented in TransitionSystem_Gen.
virtual void get_species_impl (int species_id, SP_Species & species) const private pure virtual
Implemented in TransitionSystem_Gen.
virtual void set_species_impl (SP_Species species) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_Nuclide nuclide_impl (int nuclide_id) const private pure virtual
Implemented in TransitionSystem_Gen.
virtual void get_nuclide_impl (int nuclide_id, SP_Nuclide & nuclide) const private pure virtual
Implemented in TransitionSystem_Gen.
virtual void set_nuclide_impl (SP_Nuclide nuclide) private pure virtual
Implemented in TransitionSystem_Gen.
virtual size_t num_nuclides_impl () const private pure virtual
Implemented in TransitionSystem_Gen.
virtual size_t num_species_impl () const private pure virtual
Implemented in TransitionSystem_Gen.
void populate_gains_impl () private virtual
References kernel_rksuite::f(), and auxiliary::nuclide().
 {
     Origen::Nuclide::SP nuclide;
     Origen::Channel::SP channel;
     std::vector<Origen::Nuclide::SP> nuclides;
     std::vector<Origen::Channel::SP> losses;
     std::vector<Origen::Transition::SP> transitions;
     Origen::Transition::SP transition;
     this->clear_gains();
     nuclides = this->nuclides();
     for( size_t j = 0; j < nuclides.size(); ++j )
     {
         nuclide = nuclides[j];
         losses = nuclide->losses();
         for( size_t k = 0; k < losses.size(); ++k )
         {
             channel = losses[k];
             // residuals
             transitions = channel->transitions();
             for( size_t f = 0; f < transitions.size(); ++f )
             {
                 transition = transitions[f];
                 transition->product()->append_gain( &*transition );
             }
             // byproducts
             transitions = channel->byproduct_transitions();
             //            std::cout << " adding byp
             //            gains="<<transitions.size()<<std::endl;
             for( size_t f = 0; f < transitions.size(); ++f )
             {
                 transition = transitions[f];
                 transition->product()->append_gain( &*transition );
             }
         }
     }
 }
void clear_gains_impl () private virtual
 {
     std::vector<Origen::Nuclide::SP> nuclides = this->nuclides();
     for( size_t j = 0; j < nuclides.size(); ++j )
     {
         nuclides[j]->clear_gains();
     }
     std::vector<Origen::Nuclide::SP> byproducts = this->byproducts();
     for( size_t j = 0; j < byproducts.size(); ++j )
     {
         byproducts[j]->clear_gains();
     }
 }
virtual SP_Field add_field_impl (int field_id) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_Field field_impl (int field_id) const private pure virtual
Implemented in TransitionSystem_Gen.
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     Json::Value json( Json::objectValue );
     json = Checkable::to_json_impl();
     std::vector<Nuclide::SP> nuclides = this->nuclides();
     Json::Value json_nuclides( Json::arrayValue );
     for( size_t i = 0; i < nuclides.size(); ++i )
     {
         json_nuclides[static_cast<int>( i )] = nuclides[i]->to_json();
     }
     json["nuclides"] = json_nuclides;
     std::vector<Nuclide::SP> byproducts = this->byproducts();
     Json::Value json_byproducts( Json::arrayValue );
     for( size_t i = 0; i < byproducts.size(); ++i )
     {
         json_byproducts[static_cast<int>( i )] = byproducts[i]->to_json();
     }
     json["byproducts"] = json_byproducts;
     // don't have a species vector return
     //     std::vector<Species::SP> species = this->species();
     //     Json::Value json_species(Json::arrayValue);
     //     for(size_t i=0; i<species.size(); ++i){
     //         json_species[static_cast<int>(i)]=species[i]->to_json();
     //     }
     //     json["species"]=json_species;
     return json;
 }
virtual SP_Nuclide add_byproduct_impl (int byproduct_id) private pure virtual
Implemented in TransitionSystem_Gen.
virtual SP_Nuclide byproduct_impl (int byproduct_id) const private pure virtual
Implemented in TransitionSystem_Gen.
virtual std::vector<SP_Nuclide> byproducts_impl () const private pure virtual
Implemented in TransitionSystem_Gen.
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
bool good_impl (Vec_Str & errors) const protected virtual inherited
useful to chain
Reimplemented in Nuclide, Channel, Null, Neutrino, Positron, Species, Transition, Electron, Field, Alpha, ChannelType_Reac, ChannelType_Decay, ChannelType_Fiss, Helion, TransitionSystem_Gen, Triton, Deuteron, Proton, and Neutron.
References ORIGEN_CHECKABLE_ERROR.
 {
     std::stringstream ss;
     bool pass = true;
     if( !has_initialized_id() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized id", pass, errors );
     return pass;
 }
bool is_initialized_impl () const protected virtual inherited
useful to chain
Reimplemented in Nuclide, Channel, ChannelType, Species, Transition, Field, and TransitionSystem_Gen.
 { return has_initialized_id(); }
The documentation for this class was generated from the following files:
Core/ts/TransitionSystem.h
Core/ts/TransitionSystem.cpp