ORIGEN API: origen_iofunctions_m Module Reference
origen_iofunctions_m Module Reference
Data Types
type origen_exception
Functions/Subroutines
subroutine rstop (message, code)
subroutine origen_dumperrors (options, msg)
logical function origen_loadlibrary (lib, full_name, options)
logical function origen_savelibrary (lib, full_name)
logical function origen_appendlibrary (trx, full_name)
logical function origen_savestateset_options (state_set, full_name, options)
logical function origen_savestateset (state_set, full_name, file_format)
logical function origen_loadstateset (state_set, full_name)
logical function origen_appendstateset (state_set, full_name, file_format, appended)
logical function origen_loadstate (state, full_name, pos)
Function/Subroutine Documentation
subroutine origen_iofunctions_m::rstop (character(*), intent(in) message, integer, intent(in) code)
Referenced by kernel_matrex::decay(), depletion::deplete(), depletion::depletion_step(), kernel_matrex::equil(), origen_casewrapper_m::flip_time(), kernel_matrex::get_precision(), kernel_matrex::matrex(), depletion::powerflux(), kernel_radau5::radau5_solve(), kernel_rksuite::rksuite_solve(), and origen_librarywrapper::set_legacy_mass().
 use nemesis_comm
 !-----------------------------------------------
 !   D u m m y   A r g u m e n t s
 !-----------------------------------------------
 character(*), intent(in) :: message
 integer, intent(in) :: code
 !-----------------------------------------------
 !   L o c a l   V a r i a b l e s
 !-----------------------------------------------
 integer :: s
 scalereporterror(1, "(A)") trim(message) ; scalefinalizeerror()
 #ifndef ORIGEN_CONTINUE_WITH_ERRORS
 #ifdef SCALEMPI
       call abort( code )
 #else
       call exit ( code )
 #endif
     stop
 #endif
subroutine origen_iofunctions_m::origen_dumperrors (type(datacontainer), intent(in) options, character(*), intent(in) msg)
Referenced by origen_appendlibrary(), origen_loadlibrary(), origen_loadstate(), origen_loadstateset(), origen_savelibrary(), and origen_savestateset_options().
     type(datacontainer),intent(in) :: options
     character(*),intent(in) :: msg
     type(stringlist)  :: errors
     integer :: j
     character(1028) :: strbuffer
     if( options%contains("ERROR") )then
             scalereporterror(0,"(a)")msg ; scalefinalizeerror()
             call options % get(errors,"ERROR")
             do j=1,errors%size()
                     call errors % at(strbuffer,j)
                     scalereporterror(0,"(a)")trim(strbuffer) ; scalefinalizeerror()
             end do
     end if
logical function origen_iofunctions_m::origen_loadlibrary (type(origen_library), intent(inout) lib, character(*), intent(in) full_name, type(datacontainer), intent(inout), optional options)
References origen_dumperrors().
Referenced by origen_librarywrapper::set_legacy_mass().
     logical :: loaded
     type(origen_library),intent(inout) :: lib
     character(*),intent(in) :: full_name
     type(datacontainer),optional,intent(inout) :: options
     type(datacontainer) :: options0
     type(origen_libraryio) :: io
     if( .not. c_associated(lib%instance_ptr) )then
         call lib % initialize()
     end if
     if( present(options) )then
         check(c_associated(options%instance_ptr))
         options0%instance_ptr = options%instance_ptr
     else
         call options0 % initialize()
     end if
     call io % initialize()
     loaded = io % load(lib,full_name,options0)
     if( .not. loaded )then
         call origen_dumperrors(options0,"could not read library ft33='"//trim(full_name)//"'")
         call lib%destroy()
     end if
     !cleanup
     call io % destroy()
     if( .not.present(options) )call options0 % destroy()
logical function origen_iofunctions_m::origen_savelibrary (type(origen_library), intent(in) lib, character(*), intent(in) full_name)
References origen_dumperrors().
     logical :: saved
     type(origen_library),intent(in) :: lib
     character(*),intent(in) :: full_name
     type(datacontainer) :: options
     type(origen_libraryio) :: io
     require( c_associated(lib%instance_ptr) )
     call io % initialize()
     call options % initialize()
     saved = io % save(lib,full_name,options)
     if( .not. saved )then
         call origen_dumperrors(options,"could not save library ft33='"//trim(full_name)//"'")
     end if
     !cleanup
     call io % destroy()
     call options % destroy()
logical function origen_iofunctions_m::origen_appendlibrary (type(origen_transitionmatrixp), intent(in) trx, character(*), intent(in) full_name)
References origen_dumperrors().
     logical :: saved
     type(origen_transitionmatrixp),intent(in) :: trx
     type(origen_library) :: lib
     character(*),intent(in) :: full_name
     type(datacontainer) :: options
     type(origen_libraryio) :: io
     require( c_associated(trx%instance_ptr) )
     call io % initialize()
     call options % initialize()
     call options % addBool("appendExisting",.true._c_bool)
     call lib % initialize()
     call lib % add_transition_matrix(trx)
     saved = io % save(lib,full_name,options)
     if( .not. saved )then
         call origen_dumperrors(options,"could not append to library ft33='"//trim(full_name)//"'")
     end if
     !cleanup
     call lib % destroy()
     call io % destroy()
     call options % destroy()
logical function origen_iofunctions_m::origen_savestateset_options (type(origen_stateset), intent(in) state_set, character(*), intent(in) full_name, type(datacontainer), intent(inout) options)
References origen_dumperrors().
Referenced by origen_appendstateset(), and origen_savestateset().
     logical :: saved
     type(origen_stateset),intent(in) :: state_set
     character(*),intent(in) :: full_name
     type(datacontainer),intent(inout) :: options
     type(origen_statesetio) :: io
     require( c_associated(state_set%instance_ptr) )
     require( c_associated(options%instance_ptr) )
     call io % initialize()
     saved = io % save(state_set,full_name,options)
     if( .not. saved )then
         call origen_dumperrors(options,"could not save concentrations ft71='"//trim(full_name)//"'")
     end if
     call io % destroy()
logical function origen_iofunctions_m::origen_savestateset (type(origen_stateset), intent(in) state_set, character(*), intent(in) full_name, character(*), intent(in), optional file_format)
References origen_savestateset_options().
     logical :: saved
     type(origen_stateset),intent(in) :: state_set
     character(*),intent(in) :: full_name
     character(*),intent(in),optional :: file_format
     type(datacontainer) :: options
     type(origen_statesetio) :: io
     call options % initialize()
     saved = origen_savestateset_options(state_set,full_name,options)
     call options % destroy()
logical function origen_iofunctions_m::origen_loadstateset (type(origen_stateset), intent(inout) state_set, character(*), intent(in) full_name)
References origen_dumperrors().
Referenced by origen_casewrapper_m::flip_time(), test_append_file(), and tstmassconservation().
     logical :: loaded
     type(origen_stateset),intent(inout) :: state_set
     character(*),intent(in) :: full_name
     type(datacontainer) :: options
     type(origen_statesetio) :: io
     require( c_associated(state_set%instance_ptr) )
     call io % initialize()
     call options % initialize()
     loaded = io % load(state_set,full_name,options)
     if( .not. loaded )then
         call origen_dumperrors(options,"could not load concentrations ft71='"//trim(full_name)//"'")
     end if
     !cleanup
     call io % destroy()
     call options % destroy()
logical function origen_iofunctions_m::origen_appendstateset (type(origen_stateset), intent(in) state_set, character(*), intent(in) full_name, character(*), intent(in), optional file_format, logical, intent(out), optional appended)
References origen_savestateset_options().
Referenced by origen_casewrapper_m::flip_time().
     logical :: saved
     type(origen_stateset),intent(in) :: state_set
     character(*),intent(in) :: full_name
     character(*),intent(in),optional :: file_format
     logical,intent(out),optional :: appended
     type(datacontainer) :: options
     type(origen_statesetio) :: io
     call options % initialize()
     call options % addBool("appendExisting",.true._c_bool)
     if( present(file_format) )call options % addString("fileFormat",trim(file_format))
     saved = origen_savestateset_options(state_set,full_name,options)
     if( present(appended) )then
         if( options%containsBool("append") )then
             appended = options%getBool("append")
         else
             appended = .false.
         end if
     end if
     call options % destroy()
logical function origen_iofunctions_m::origen_loadstate (type(origen_state), intent(inout) state, character(*), intent(in) full_name, integer, intent(in) pos)
References origen_dumperrors().
     logical :: loaded
     type(origen_state),intent(inout) :: state
     character(*),intent(in) :: full_name
     integer,intent(in) :: pos
     type(datacontainer) :: options
     type(origen_statesetio) :: io
     type(origen_stateset) :: state_set
     character(3000) :: msg
     if( .not. c_associated(state_set%instance_ptr) )then
         call state % initialize()
     end if
     call io % initialize()
     call options % initialize()
     call state_set % initialize()
     ! ! \todo add something like firstPosition, lastPosition to StateSetIO so
     ! ! don"t have to load everything
     !call options.addInt("firstPosition",pos)
     !call options.addInt("lastPosition",pos)
     loaded = io % load(state_set,full_name,options)
     if( .not. loaded )then
         call origen_dumperrors(options,"could not read concentrations ft71='"//trim(full_name)//"'")
         call state%destroy()
     else if( pos>state_set % states_size() )then
         write(msg,"(a,i0,a,i0,a)")"position=",pos," is greater than the maximum position=",state_set%states_size()," on ft71 file='"//trim(full_name)//"'"
         scalereporterror(0,"(a)")trim(msg) ; scalefinalizeerror()
         loaded=.false.
         call state%destroy()
     else
         call state_set % get_states_at(state,int(pos,c_size_t))
     end if
     !cleanup
     call state_set % destroy()
     call io % destroy()
     call options % destroy()