ORIGEN API: Transition_GenByp Class Reference
Transition_GenByp Class Reference
#include <Transition_Gen.h>
Public Types
typedef SP_Transition SP
strong pointer
typedef WP_Transition WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Transition>>
See Origen::Transition for details.
WP_Nuclide product () const
return the product nuclide
void set_product (WP_Nuclide product)
set the product nuclide
WP_Channel channel () const
return the parent channel
void set_channel (WP_Channel channel)
set the channel
double yield () const
return the yield, i.e. number of product nuclides per transition
void set_yield (const double &yield)
set the yield
bool has_initialized_yield () const
whether yield has been initialized for this transition
double coeff () const
double rate () const
bool is_byproduct () const
whether this transition is a byproduct
Private Member Functions
virtual bool is_byproduct_impl () const
Member Typedef Documentation
typedef SP_Transition SP inherited
strong pointer
typedef WP_Transition WP inherited
weak pointer
Member Function Documentation
bool is_byproduct_impl () const private virtual
Reimplemented from Transition.
 { return true; }
Nuclide::WP product () const inherited
return the product nuclide
Referenced by Transition_Gen::set_product_impl().
 { return product_impl(); }
void set_product (WP_Nuclide product) inherited
set the product nuclide
Referenced by Transition_Gen::Transition_Gen().
 {
     set_product_impl( product );
 }
Channel::WP channel () const inherited
return the parent channel
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Nuclide_Gen::append_gain_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), LibraryBuilder::search_reaction_transitions(), Transition_Gen::set_channel_impl(), and TEST_F().
 { return channel_impl(); }
void set_channel (WP_Channel channel) inherited
set the channel
 {
     set_channel_impl( channel );
 }
double yield () const inherited
return the yield, i.e. number of product nuclides per transition
Referenced by Transition_Gen::set_yield_impl().
 { return yield_impl(); }
void set_yield (const double & yield) inherited
set the yield
 { set_yield_impl( yield ); }
bool has_initialized_yield () const inherited
whether yield has been initialized for this transition
 {
     return has_initialized_yield_impl();
 }
double coeff () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), and TEST_F().
 { return channel()->coeff() * yield(); }
double rate () const inherited
 { return channel()->rate() * yield(); }
bool is_byproduct () const inherited
whether this transition is a byproduct
 { return is_byproduct_impl(); }
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Transition_Gen.h
Core/ts/Transition_Gen.cpp