ORIGEN API: global identifiers
global identifiers
Fortran API
Variables
integer(c_int), parameter origen_sublib_1lt =1
ORIGEN sublib integer for light/activation products.
integer(c_int), parameter origen_sublib_2ac =2
ORIGEN sublib integer for actinide.
integer(c_int), parameter origen_sublib_3fp =3
ORIGEN sublib integer for fission product.
integer(c_int), parameter origen_sublib_4u1 =4
ORIGEN sublib integer for user group 1.
integer(c_int), parameter origen_sublib_5u2 =5
ORIGEN sublib integer for user group 2.
integer(c_int), parameter origen_sublib_6u3 =6
ORIGEN sublib integer for user group 3.
integer(c_int), parameter origen_sublib_7u4 =7
ORIGEN sublib integer for user group 4.
integer(c_int), parameter origen_sublib_8u5 =8
ORIGEN sublib integer for user group 5.
integer(c_int), parameter origen_sublib_9by =9
ORIGEN sublib integer for byproducts.
integer(c_int), parameter origen_concentrationunit_gatoms =0
integer(c_int), parameter origen_concentrationunit_atoms_b_cm =1
integer(c_int), parameter origen_concentrationunit_grams =2
integer(c_int), parameter origen_concentrationunit_moles =21
integer(c_int), parameter origen_concentrationunit_curies =3
integer(c_int), parameter origen_concentrationunit_cm_2_barn =22
integer(c_int), parameter origen_concentrationunit_becquerels =9
Detailed Description
Variable Documentation
integer(c_int), parameter origen_sublib_1lt =1
ORIGEN sublib integer for light/activation products.
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), tstlibrary(), and tststate().
 integer(C_INT), parameter :: origen_sublib_1lt=1 !< ORIGEN sublib integer for light/activation products
integer(c_int), parameter origen_sublib_2ac =2
ORIGEN sublib integer for actinide.
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), tstlibrary(), and tststate().
 integer(C_INT), parameter :: origen_sublib_2ac=2 !< ORIGEN sublib integer for actinide
integer(c_int), parameter origen_sublib_3fp =3
ORIGEN sublib integer for fission product.
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), tstlibrary(), tstlibrarybuilder(), and tststate().
 integer(C_INT), parameter :: origen_sublib_3fp=3 !< ORIGEN sublib integer for fission product
integer(c_int), parameter origen_sublib_4u1 =4
ORIGEN sublib integer for user group 1.
Referenced by tststate().
 integer(C_INT), parameter :: origen_sublib_4u1=4 !< ORIGEN sublib integer for user group 1
integer(c_int), parameter origen_sublib_5u2 =5
ORIGEN sublib integer for user group 2.
Referenced by tststate().
 integer(C_INT), parameter :: origen_sublib_5u2=5 !< ORIGEN sublib integer for user group 2
integer(c_int), parameter origen_sublib_6u3 =6
ORIGEN sublib integer for user group 3.
Referenced by tststate().
 integer(C_INT), parameter :: origen_sublib_6u3=6 !< ORIGEN sublib integer for user group 3
integer(c_int), parameter origen_sublib_7u4 =7
ORIGEN sublib integer for user group 4.
Referenced by tststate().
 integer(C_INT), parameter :: origen_sublib_7u4=7 !< ORIGEN sublib integer for user group 4
integer(c_int), parameter origen_sublib_8u5 =8
ORIGEN sublib integer for user group 5.
Referenced by tststate().
 integer(C_INT), parameter :: origen_sublib_8u5=8 !< ORIGEN sublib integer for user group 5
integer(c_int), parameter origen_sublib_9by =9
ORIGEN sublib integer for byproducts.
Referenced by tststate().
 integer(C_INT), parameter :: origen_sublib_9by=9 !< ORIGEN sublib integer for byproducts
integer(c_int), parameter origen_concentrationunit_gatoms =0
Referenced by origen_casewrapper_m::flip_time().
 integer(C_INT), parameter :: origen_concentrationunit_gatoms=0
integer(c_int), parameter origen_concentrationunit_atoms_b_cm =1
 integer(C_INT), parameter :: origen_concentrationunit_atoms_b_cm=1
integer(c_int), parameter origen_concentrationunit_grams =2
 integer(C_INT), parameter :: origen_concentrationunit_grams=2
integer(c_int), parameter origen_concentrationunit_moles =21
 integer(C_INT), parameter :: origen_concentrationunit_moles=21
integer(c_int), parameter origen_concentrationunit_curies =3
 integer(C_INT), parameter :: origen_concentrationunit_curies=3
integer(c_int), parameter origen_concentrationunit_cm_2_barn =22
 integer(C_INT), parameter :: origen_concentrationunit_cm_2_barn=22
integer(c_int), parameter origen_concentrationunit_becquerels =9
 integer(C_INT), parameter :: origen_concentrationunit_becquerels=9