ORIGEN API: StateSetIO_s61 Class Reference
StateSetIO_s61 Class Reference
#include <StateSetIO_s61.h>
Public Member Functions
bool read (StateSet &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const StateSet &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Member Function Documentation
bool read (StateSet & obj, std::istream & stream, ScaleUtils::IO::DB opts)
R01 :: state header variables
R02 :: state data variables
References StateSet::add_states(), Origen::info(), Origen::detail::read(), READ, Spectrum::set_bounds(), StateInfo::set_case_number(), State::set_concs(), State::set_definition(), StateInfo::set_flux(), State::set_gamma_spectra(), Spectrum::set_intensity(), NeutronSpectra::set_intensity_alphan(), NeutronSpectra::set_intensity_sf(), GammaSpectra::set_nuclide_type(), StateInfo::set_power(), StateInfo::set_step_number(), StateInfo::set_time(), Concentrations::set_vals(), Origen::detail::setupEndianness(), Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, and Origen::SUBLIB_3FP.
 {
     // require stream is good
     if( !stream.good() )
     {
         opts.appendError( "Failed to open stream for reading." );
         return false;
     }
     nemesis::Timer t;
     t.start();
     // binary stream manipulator
     ScaleUtils::IO::IStreamManipulator_FBin binsman( stream );
     // setup endianness on binsman and record in options
     detail::setupEndianness( binsman, opts );
     // rewind to beginning of file
     stream.seekg( 0, std::ios::beg );
     //! R01 :: state header variables
     int itxx = -1, ilite, iact, ifp, nrflag, msub1, nstepo, kasepo, jobpos,
         nocs, noblnd, ndset, ntype, ngrp, nelem, nvert, ng, mmn, mout, index,
         mstar, nunit, kblend, nenle, nenac, nenfp, l1, l2, l3, l4;
     float tmo, fracpw, tconst;
     std::string tunit;
     float twrite, pwrite, fwrite;
     //! R02 :: state data variables
     Vec_Int ivec;
     Vec_Flt fvec;
     // convenience
     const bool has_header = false;
     while( stream.good() )
     {
         binsman.readHeader( "definition" );
         StateInfo info;
         READ( itxx );
         if( itxx == 0 ) break;
         READ( ilite );
         READ( iact );
         READ( ifp );
         READ( nrflag );
         READ( msub1 );
         READ( nstepo );
         info.set_step_number( nstepo );
         READ( kasepo );
         info.set_case_number( kasepo );
         READ( jobpos );
         READ( nocs );
         READ( noblnd );
         READ( ndset );
         READ( ntype );
         READ( ngrp );
         READ( nelem );
         READ( nvert );
         READ( ng );
         READ( mmn );
         READ( mout );
         READ( index );
         READ( mstar );
         READ( nunit );
         READ( kblend );
         READ( nenle );
         READ( nenac );
         READ( nenfp );
         READ( l1 );
         READ( l2 );
         READ( l3 );
         READ( l4 );
         READ( tmo );
         READ( fracpw );
         READ( tconst );
         tunit = binsman.readString( 4 );
         jDebugTaggedLine( "tunit=" << tunit );
         READ( twrite );
         info.set_time( twrite * tconst );
         READ( pwrite );
         info.set_power( pwrite );
         READ( fwrite );
         info.set_flux( fwrite );
         binsman.readFooter();
         binsman.readHeader( "data" );
         ivec.resize( itxx );
         detail::read( binsman, "nucl", ivec, has_header );
         // create legacy nuclide set
         NuclideSet nuc_set( ilite, iact, ifp, ivec );
         fvec.resize( itxx );
         detail::read( binsman, "x", fvec, has_header );
         Concentrations concs( nuc_set );
         concs.set_vals( Vec_Dbl( fvec.begin(), fvec.end() ) );
         // add state for concentrations
         {
             State state;
             state.set_definition( info );
             state.set_concs( concs );
             obj.add_states( state );
         }
         std::string title = binsman.readString( 80 );
         jDebugTaggedLine( "title=" << title );
         std::string basis = binsman.readString( 40 );
         jDebugTaggedLine( "basis=" << basis );
         // this shortcut is necessary to handle Ian Gauld's GROUPR in
         // SCALE 6.1
         jDebugTaggedLine( "GROUPR test: getBytesRead=" << binsman.getBytesRead()
                                                        << " getHeader="
                                                        << binsman.getHeader() );
         if( nenle == 0 && nenac == 0 && nenfp == 0 &&
             64 == ( binsman.getHeader() - binsman.getBytesRead() ) )
         {
             jDebugTaggedLine( "GROUPR MODE CONFIRMED..." );
             binsman.readFooter();
             continue;
         }
         fvec.resize( nenle + 1 );
         detail::read( binsman, "egamle", fvec, has_header );
         GammaSpectra gamma_lt;
         if( nenle > 0 )
         {
             gamma_lt.set_nuclide_type( SUBLIB_1LT );
             gamma_lt.set_bounds( Vec_Dbl( fvec.begin(), fvec.end() ) );
         }
         fvec.resize( nenac + 1 );
         detail::read( binsman, "egamac", fvec, has_header );
         GammaSpectra gamma_ac;
         if( nenac > 0 )
         {
             gamma_ac.set_nuclide_type( SUBLIB_2AC );
             gamma_ac.set_bounds( Vec_Dbl( fvec.begin(), fvec.end() ) );
         }
         fvec.resize( nenfp + 1 );
         detail::read( binsman, "egamfp", fvec, has_header );
         GammaSpectra gamma_fp;
         if( nenfp > 0 )
         {
             gamma_fp.set_nuclide_type( SUBLIB_3FP );
             gamma_fp.set_bounds( Vec_Dbl( fvec.begin(), fvec.end() ) );
         }
         fvec.resize( l1 );
         detail::read( binsman, "specle", fvec, has_header );
         // add state for light nuclide gamma spec
         if( nenle > 0 )
         {
             gamma_lt.set_intensity( Vec_Dbl( fvec.begin(), fvec.end() ) );
             State state;
             state.set_definition( info );
             state.set_gamma_spectra( gamma_lt );
             obj.add_states( state );
         }
         fvec.resize( l2 );
         detail::read( binsman, "specac", fvec, has_header );
         // add state for actinide gamma spec
         if( nenle > 0 )
         {
             gamma_ac.set_intensity( Vec_Dbl( fvec.begin(), fvec.end() ) );
             State state;
             state.set_definition( info );
             state.set_gamma_spectra( gamma_ac );
             obj.add_states( state );
         }
         fvec.resize( l3 );
         detail::read( binsman, "specfp", fvec, has_header );
         // add state for light element gamma spec
         if( nenle > 0 )
         {
             gamma_fp.set_intensity( Vec_Dbl( fvec.begin(), fvec.end() ) );
             State state;
             state.set_definition( info );
             state.set_gamma_spectra( gamma_fp );
             obj.add_states( state );
         }
         fvec.resize( ng + 1 );
         detail::read( binsman, "ener", fvec, has_header );
         fvec.resize( ng );
         detail::read( binsman, "dsav", fvec, has_header );
         fvec.resize( ng );
         detail::read( binsman, "esav", fvec, has_header );
         // this shortcut is necessary to handle "f72" and "f73" files produced
         // by orella (Ian Gauld's spent fuel isotopics utility) in SCALE 6.1
         jDebugTaggedLine( "ORELLA test: getBytesRead=" << binsman.getBytesRead()
                                                        << " getHeader="
                                                        << binsman.getHeader() );
         if( binsman.getBytesRead() == binsman.getHeader() )
         {
             jDebugTaggedLine( "ORELLA MODE CONFIRMED..." );
             binsman.readFooter();
             continue;
         }
         std::string itsav = binsman.readString( 80 );
         jDebugTaggedLine( "itsav={" << itsav << "}" );
         fvec.resize( l4 );
         detail::read( binsman, "spnnuc", fvec, has_header );
         fvec.resize( l4 );
         detail::read( binsman, "alpnuc", fvec, has_header );
         fvec.resize( ngrp );
         detail::read( binsman, "spneut", fvec, has_header );
         Vec_Dbl neutron_total( fvec.begin(), fvec.end() );
         fvec.resize( ngrp );
         detail::read( binsman, "specan", fvec, has_header );
         Vec_Dbl neutron_alphan( fvec.begin(), fvec.end() );
         fvec.resize( ngrp );
         detail::read( binsman, "specsp", fvec, has_header );
         Vec_Dbl neutron_sf( fvec.begin(), fvec.end() );
         fvec.resize( ngrp + 1 );
         detail::read( binsman, "eneuts", fvec, has_header );
         if( ngrp > 0 )
         {
             NeutronSpectra neutron;
             neutron.set_bounds( Vec_Dbl( fvec.begin(), fvec.end() ) );
             neutron.set_intensity_alphan( neutron_alphan );
             neutron.set_intensity_sf( neutron_alphan );
         }
         binsman.readFooter();
     }  // end read states
     t.stop();
     opts.set( "loadTime", 1000 * t.wall_clock() );
     return true;
 }
bool write (const StateSet & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
 {
     nemesis::Timer t;
     t.start();
     opts.appendError(
         "no StateSet writer implemented for s61 (SCALE 6.1 format)" );
     t.stop();
     opts.set( "saveTime", 1000 * t.wall_clock() );
     return false;
 }
The documentation for this class was generated from the following files:
Core/io/StateSetIO_s61.h
Core/io/StateSetIO_s61.cpp