ORIGEN API: definitions
definitions
Fortran API
Variables
integer(c_int), parameter null_field = 0
integer(c_int), parameter neutron_field = 1
integer(c_int), parameter proton_field = 2
integer(c_int), parameter deuteron_field = 3
integer(c_int), parameter triton_field = 4
integer(c_int), parameter helion_field = 5
integer(c_int), parameter alpha_field = 6
integer(c_int), parameter electron_field = 7
integer(c_int), parameter positron_field = 8
integer(c_int), parameter photon_field = 9
integer(c_int), parameter neutrino_field = 10
integer(c_int), parameter end_field = 11
Detailed Description
Variable Documentation
integer(c_int), parameter null_field = 0
Referenced by origen_particleemitter_api::pe_get_particle_source(), and origen_particleemitter_api::pe_get_type_str().
integer(c_int), parameter neutron_field = 1
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by origen_particleemitter_api::pe_get_particle_source(), origen_particleemitter_api::pe_get_type_str(), origen_particleemitter_api::pe_load_data(), TEST(), tstneutron_api(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().
integer(c_int), parameter proton_field = 2
integer(c_int), parameter deuteron_field = 3
integer(c_int), parameter triton_field = 4
integer(c_int), parameter helion_field = 5
integer(c_int), parameter alpha_field = 6
Referenced by origen_particleemitter_api::pe_get_particle_source(), origen_particleemitter_api::pe_get_type_str(), and origen_particleemitter_api::pe_load_data().
integer(c_int), parameter electron_field = 7
Referenced by origen_particleemitter_api::pe_get_type_str().
integer(c_int), parameter positron_field = 8
integer(c_int), parameter photon_field = 9
Referenced by origen_particleemitter_api::pe_get_type_str().
integer(c_int), parameter neutrino_field = 10
integer(c_int), parameter end_field = 11
Referenced by origen_particleemitter_api::pe_get_particle_source().