ORIGEN API: kernel_rksuite Module Reference
kernel_rksuite Module Reference
Wrapper for the 3rd party RKSuite90 solver.
Functions/Subroutines
real(c_double) function, dimension(size(y)) f (t, y)
subroutine, public rksuite_solve (trx, itot, non, n0, n, delta_t, diag, a, b, zero_flux_step, is_adjoint)
Variables
type(origen_transitionmatrixp) xtrx
Library data.
real(c_double), dimension(:), allocatable xd
Diagonal elements of the transition matrix.
real(c_double), dimension(:), allocatable xa
Nondiagonal elements of the transition matrix.
real(c_double), dimension(:), allocatable xb
Right side of the equation (source term)
real(c_double) fake_flux
fake flux level to last_transition is decay if=0
integer, dimension(:), allocatable xloc
location array
Detailed Description
Wrapper for the 3rd party RKSuite90 solver.
Function/Subroutine Documentation
real(c_double) function, dimension(size(y)) kernel_rksuite::f (real(c_double), intent(in) t, real(c_double), dimension(:), intent(in) y) private
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstMaterial.cpp, Core/dc/tests/tstState.cpp, Core/dc/tests/tstStateSet.cpp, Core/dc/tests/tstTime.cpp, and Core/ts/tests/tstTransitionSystem_Gen.cpp.
References fake_flux, xa, xb, xd, xloc, and xtrx.
Referenced by DiscreteSpectrum::bin(), StateSet::create_interp_responses(), Obiwan_diff::diff(), Material::flux_hist(), get_decay_data(), Origen::graphvizLibrary(), Obiwan_diff::populate(), TransitionSystem::populate_gains_impl(), print_yield_data(), rksuite_solve(), GridData_TransitionCoeff::setr(), TransitionSystem_Gen_Setup::SetUp(), GridData_TransitionCoeff::setx(), Origen::tabulateTransitionCoeff(), TEST(), TEST_F(), LibraryIO_s61::write(), StateSetIO_s62b::write(), YieldResourceIO_stab1::write(), and STab1Writer::writeTerminatorLine().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in) :: t
     real(C_DOUBLE), dimension(:), intent(in) :: y
     real(C_DOUBLE), dimension(size(y)) :: f
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     integer :: i, j
     do i = 1, xtrx%get_itot()
       f(i) = y(i) * xd(i) + xb(i)
       do j = xtrx%first_transition(i), xtrx%last_transition(i,fake_flux)
         f(i) = f(i) + y(xloc(j)) * xa(j)
       end do
 !       if (f(i) > 0.1 .or. (abs(f(i)) > abs(y(i)) .and. f(i)<0) ) then
 !         SOutLine(1,*) f(i), y(i), xb(i), xd(i)
 !       end if
     end do
subroutine, public kernel_rksuite::rksuite_solve (type(origen_transitionmatrixp), intent(in) trx, integer, intent(in) itot, integer, intent(in) non, real(c_double), dimension(itot), intent(in) n0, real(c_double), dimension(itot), intent(out) n, real(c_double), intent(in) delta_t, real(c_double), dimension(itot), intent(in) diag, real(c_double), dimension(non), intent(in) a, real(c_double), dimension(itot), intent(in) b, logical, intent(in) zero_flux_step, logical, intent(in) is_adjoint)
Parameters
[in] trx Library data
[in] itot Total number of nuclides
[in] non Number of non-zero matrix elements
[in] diag Diagonal elements of the transition matrix
[in] a Nondiagonal elements of the transition matrix
[in] b Right side of the equation (source term)
[in] n0 initial concentrations
[out] n final concentrations
[in] delta_t Time step length in seconds
[in] zero_flux_step is this a zero-flux (=decay) step?
[in] is_adjoint is this an adjoint calculation?
References f(), fake_flux, origen_iofunctions_m::rstop(), xa, xb, xd, xloc, and xtrx.
     use rksuite_90
     use rksuite_90_prec
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Library data
     type(origen_transitionmatrixp), intent(in) :: trx
     !> Total number of nuclides
     integer, intent(in) :: itot
     !> Number of non-zero matrix elements
     integer, intent(in) :: non
     !> Diagonal elements of the transition matrix
     real(C_DOUBLE), intent(in) :: diag(itot)
     !> Nondiagonal elements of the transition matrix
     real(C_DOUBLE), intent(in) :: a(non)
     !> Right side of the equation (source term)
     real(C_DOUBLE), intent(in) :: b(itot)
     !> initial concentrations
     real(C_DOUBLE), intent(in) :: n0(itot)
     !> final concentrations
     real(C_DOUBLE), intent(out) :: n(itot)
     !> Time step length in seconds
     real(C_DOUBLE), intent(in) :: delta_t
     !> is this a zero-flux (=decay) step?
     logical, intent(in) :: zero_flux_step
     !> is this an adjoint calculation?
     logical, intent(in) :: is_adjoint
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     type(rk_comm_real_1d) :: comm
     real(C_DOUBLE) :: t_start, t_end, y_start(itot), tolerance, thresholds(itot), t_want, y_maxvals(itot), t_got, y_got(itot), yderiv_got(itot)
     integer :: flag
     t_start = 0.0d0
     t_end = delta_t
     y_start(:) = n0(:)
     t_want = delta_t
     tolerance = 1d-8
     thresholds(:) = 1d-15
     fake_flux = 1.0d0
     if( zero_flux_step )fake_flux = 0.0d0
     call setup(comm, t_start, y_start, t_end, tolerance, thresholds, 'H' )
     allocate(xa(non))
     allocate(xb(itot))
     allocate(xd(itot))
     xa(:) = a(:)
     xb(:) = b(:)
     xd(:) = diag(:)
     xtrx % instance_ptr = trx % instance_ptr
     call xtrx%get_loc_array(xloc)
     t_got = 0
     do while (t_got < delta_t * 0.9999)
       call range_integrate(comm, f, t_want, t_got, y_got, yderiv_got, flag=flag)
       soutline(1,*) t_want, t_got, flag
     end do
     deallocate(xa)
     deallocate(xb)
     deallocate(xd)
     if (flag > 4) call rstop("RK failure", 912)
     n(:) = y_got(:)
Variable Documentation
type(origen_transitionmatrixp) xtrx
Library data.
Referenced by f(), and rksuite_solve().
   type(origen_transitionmatrixp) :: xtrx
real(c_double), dimension(:), allocatable xd
Diagonal elements of the transition matrix.
Referenced by f(), and rksuite_solve().
   real(C_DOUBLE), allocatable :: xd(:)
real(c_double), dimension(:), allocatable xa
Nondiagonal elements of the transition matrix.
Referenced by f(), and rksuite_solve().
   real(C_DOUBLE), allocatable :: xa(:)
real(c_double), dimension(:), allocatable xb
Right side of the equation (source term)
Referenced by f(), and rksuite_solve().
   real(C_DOUBLE), allocatable :: xb(:)
real(c_double) fake_flux
fake flux level to last_transition is decay if=0
Referenced by f(), and rksuite_solve().
   real(C_DOUBLE) :: fake_flux
integer, dimension(:), allocatable xloc
location array
Referenced by f(), and rksuite_solve().
   integer, allocatable :: xloc(:)