ORIGEN API: Accessor< Origen::NuclideSet > Class Template Reference
Accessor< Origen::NuclideSet > Class Template Reference
#include <NuclideSet.h>
Static Public Member Functions
template<typename Archiver >
static size_t read (Archiver &a,::Origen::NuclideSet &obj)
template<typename Archiver >
static size_t write (Archiver &a, const ::Origen::NuclideSet &obj, bool only_size=false)
template<typename Archiver >
static size_t read (Archiver &a, std::string,::Origen::NuclideSet &obj)
template<typename Archiver >
static size_t write (Archiver &a, std::string, const ::Origen::NuclideSet &obj)
Private Types
typedef std::vector< int > Vec_Int
Member Typedef Documentation
typedef std::vector<int> Vec_Int private
Member Function Documentation
static size_t read (Archiver & a, ::Origen::NuclideSet & obj) inline static
References NuclideSet::b_ids, NuclideSet::canonicalize_ids(), and Origen::read().
     {
         size_t bytes = 0;
         obj.b_ids = std::make_shared<Vec_Int>();
         bytes +=
             ScaleUtils::IO::Accessor<Vec_Int>::read( a, "ids", *obj.b_ids );
         obj.canonicalize_ids();
         return bytes;
     }
static size_t write (Archiver & a, const ::Origen::NuclideSet & obj, bool only_size = false) inline static
References Origen::write().
     {
         size_t bytes = 0;
         bytes += ScaleUtils::IO::Accessor<Vec_Int>::write(
             a, "ids", *obj.b_ids, only_size );
         return bytes;
     }
static size_t read (Archiver & a, std::string , ::Origen::NuclideSet & obj) static
static size_t write (Archiver & a, std::string , const ::Origen::NuclideSet & obj) static
The documentation for this class was generated from the following file:
Core/dc/NuclideSet.h