ORIGEN API: Quantity< T > Class Template Reference
Quantity< T > Class Template Reference
#include <Quantity.h>
Public Types
typedef T::UNITS Units
typedef Quantity< T > Type
typedef std::shared_ptr< Type > SP
typedef std::shared_ptr< const Type > SCP
Public Member Functions
Quantity ()
Quantity (double v, Units u)
SP relativeTo () const
bool isRelative () const
bool isIncremental () const
SP incrementalFrom () const
double value () const
Units units () const
std::string name () const
double valueAs (Units u) const
double valueAs () const
Type & setValue (double value)
Type & setUnits (Units units)
Type & changeUnits (Units units)
Type & setRelativeTo (SP relativeTo)
Type & setIncrementalFrom (SP incrementalFrom)
Type & setName (std::string name)
std::string toString () const
Static Public Member Functions
static Type::SP sp (double v, Units u)
static Type::SP sp ()
Protected Attributes
double b_value
Units b_units
SP b_relativeTo
SP b_incrementalFrom
std::string b_name
Detailed Description
template<typename T>
class Origen::Quantity< T >
Examples:
Core/dc/tests/tstHistory.cpp, and Core/dc/tests/tstTime.cpp.
Member Typedef Documentation
typedef T::UNITS Units
typedef Quantity<T> Type
typedef std::shared_ptr<Type> SP
typedef std::shared_ptr<const Type> SCP
Constructor & Destructor Documentation
Quantity () inline
Quantity (double v, Units u) inline
Member Function Documentation
SP relativeTo () const inline
Referenced by Quantity< Time >::isRelative(), Quantity< Time >::setRelativeTo(), and Quantity< Time >::valueAs().
bool isRelative () const inline
Referenced by Quantity< Time >::valueAs().
bool isIncremental () const inline
Referenced by Quantity< Time >::valueAs().
SP incrementalFrom () const inline
Referenced by Quantity< Time >::isIncremental(), Quantity< Time >::setIncrementalFrom(), and Quantity< Time >::valueAs().
double value () const inline
Referenced by Quantity< Time >::setValue(), and TEST().
Units units () const inline
Referenced by Quantity< Time >::setUnits(), TEST(), and Quantity< Time >::toString().
std::string name () const inline
Referenced by Quantity< Time >::setName().
double valueAs (Units u) const inline
Referenced by TEST().
double valueAs () const inline
Referenced by Quantity< Time >::changeUnits(), Quantity< Time >::toString(), and Quantity< Time >::valueAs().
Type& setValue (double value) inline
Referenced by Quantity< Time >::changeUnits(), and TEST().
Type& setUnits (Units units) inline
Referenced by Quantity< Time >::changeUnits(), and TEST().
Type& changeUnits (Units units) inline
Type& setRelativeTo (SP relativeTo) inline
Referenced by TEST().
Type& setIncrementalFrom (SP incrementalFrom) inline
Type& setName (std::string name) inline
std::string toString () const inline
Referenced by TEST().
static Type::SP sp (double v, Units u) inline static
static Type::SP sp () inline static
Member Data Documentation
double b_value protected
Referenced by Quantity< Time >::value(), and Quantity< Time >::valueAs().
Units b_units protected
Referenced by Quantity< Time >::units().
SP b_relativeTo protected
Referenced by Quantity< Time >::relativeTo().
SP b_incrementalFrom protected
Referenced by Quantity< Time >::incrementalFrom().
std::string b_name protected
Referenced by Quantity< Time >::name().
The documentation for this class was generated from the following file:
Core/dc/Quantity.h