ORIGEN API: Manager/wrap/tests/tstMassConservation.f90 File Reference
tstMassConservation.f90 File Reference
Functions/Subroutines
subroutine test_append_file (file, libw, ns)
program tstmassconservation
subroutine convert_concentrations (this, concentrations, units)
Function/Subroutine Documentation
subroutine test_append_file (character(*), intent(in) file, type(origen_librarywrapper), intent(in) libw, integer, intent(in) ns)
References origen_iofunctions_m::origen_loadstateset().
Referenced by tstmassconservation().
 use origen_casewrapper_m
 use origen_librarywrapper_m
 use origen_iofunctions_m
 #include "ScaleSTL/FortranTestMacros.h"
 !
 character(*),intent(in) :: file
 integer,intent(in) :: ns
 type(origen_librarywrapper),intent(in) :: libw
 type(origen_casewrapper) :: casew2
 integer :: i
 type(origen_stateset) :: state_set
 logical :: loaded,saved
 real(C_DOUBLE), allocatable :: conc_end(:)
 real(C_DOUBLE), allocatable :: conc_begin(:)
 !read the f71, load last position
 call casew2 % initialize(libw)
 loaded = casew2 % set_initial_concentrations_from_file(file,ns)
 expect_eq(0,casew2%nsteps())
 call casew2 % set_times([0.d0])
 expect_true(loaded)
 !append to a.f71
 saved = casew2 % save_states("a.f71",667)
 expect_true(saved)
 write(*,*)'ns=',ns
 !load the current a.f71 and check it
 !{
     call state_set%initialize()
     loaded = origen_loadstateset(state_set,"a.f71")
     expect_true(loaded)
     expect_eq(ns+1,state_set%states_size())
     call state_set%destroy()
 !}
 !destroy
 call casew2 % destroy()
program tstmassconservation ()
References origen_definitions_m::avogadro, convert_concentrations(), cpu_time(), origen_iofunctions_m::origen_loadstateset(), and test_append_file().
subroutine tstmassconservation::convert_concentrations (type(origen_casewrapper), intent(in) this, real(c_double), dimension(:,:) concentrations, integer, intent(in) units)
Parameters
[in] this the receiver
concentrations existing concentrations [0:nsteps, itot]
Referenced by tstmassconservation().
     use auxiliary
     !> the receiver
     type(origen_casewrapper), intent(in) :: this
     !> existing concentrations [0:nsteps, itot]
     real(C_DOUBLE) :: concentrations(:,:)
     integer, intent(in) :: units
     real(C_DOUBLE),allocatable :: conc(:,:)
     integer:: i, n
     real(C_DOUBLE) :: wt
     integer,allocatable :: nucl(:)
     real,allocatable :: dis(:),m(:)
     !should verify bounds of concentrations are correct
     !0:this%nsteps(),1:this%libw%get_itot()
     call this % get_concentrations(conc)
     call this % libw % get_nucl(nucl)
     call this % libw % get_dis(dis)
     call this % libw % get_m(m)
     do i=1,this%libw%get_itot()
       select case(units)
          case(origen_concentrationunit_gatoms)
          !gram-atoms (old unit name for moles) are native units
          wt = 1.0
          case(origen_concentrationunit_atoms_b_cm)
          !Atoms/barn-cm
          wt = 1.0e24 / avogadro
          case(origen_concentrationunit_grams)
          !Grams
          wt = 1.0 / m(i)
          case(origen_concentrationunit_curies)
          !Curies
          wt = 1.6283e+13 * dis(i)
          !Insist( (wt > 0), "Curie input (units=4) not allow for stable nuclides in ORIGEN");
          case default
          write(error_unit,*)"*** Error: Invalid concentration units!"
          stop 1
       end select
       !convert
       do n=1,this%nsteps()+1
          concentrations(n,i)=conc(n-1,i) / wt !NOW WE DIVIDE TO UNDO
       end do
     end do