ORIGEN API: TransitionMatrixUpdater Class Reference
TransitionMatrixUpdater Class Reference
#include <TransitionMatrixUpdater.h>
Public Member Functions
TransitionMatrixUpdater ()
TransitionMatrixUpdater (const Vec_Flt &storage_bounds)
~TransitionMatrixUpdater ()
void load (std::string library_definition, std::string aux_mg_library, std::string fission_yields)
void load (std::string library_definition, std::string aux_mg_library, std::string fission_yields, const std::vector< int > &user_nuclide_list, const std::vector< int > &user_num_mts, const std::vector< int > &user_mt_list)
void clear ()
bool initialized () const
void set_user_bounds (const Vec_Flt &user_bounds)
void unset_user_bounds ()
float update_mg_flux (const Vec_Flt &mg_flux)
float update_by_mix (const AmpxLibrary &main, int mix_id, const Vec_Flt &flux)
void update_user_xs (std::string id_form, const std::vector< int > &nuclide_list, const std::vector< int > &num_mts, const std::vector< int > &mt_list, const Vec_Flt &xs)
void update_fission_absorption_xs (std::string id_form, const std::vector< int > &nuclide_list, const Vec_Flt &fission_xs, const Vec_Flt &absorption_xs)
void get_xs (std::string id_form, const std::vector< int > &nuclide_list, const std::vector< int > &num_mts, const std::vector< int > &mt_list, Vec_Flt *xs)
void get_transition_matrix (TransitionMatrixP *trx)
void get_data_container (const AbstractDC *dc)
int get_errors (std::vector< std::string > *errors)
const ScaleUtils::IO::DB & status () const
const Library * library () const
SP_Library sp_library ()
const TransitionSystem * transition_system () const
const ReactionResource * mg_database () const
int num_energy_groups () const
const Vec_Flt * storage_bounds () const
const Vec_Flt * storage_mg_flux () const
const Vec_Flt * user_bounds () const
const LibraryHeader * library_header () const
const TransitionStructure * transition_structure () const
SP_TransitionMatrixP base_transition_matrix ()
void fetch_ts_nuclides (std::vector< SP_Nuclide > *ts_nuclides, std::string id_form, const std::vector< int > &nuclide_list)
Static Public Member Functions
static void fetch_ts_nuclides (std::vector< SP_Nuclide > *ts_nuclides, const TransitionSystem &ts, std::string id_form, const std::vector< int > &nuclide_list)
Private Attributes
TransitionSystemAdapter_AmpxN b_tsa
TransitionSystem_Gen b_ts
SP_Library b_lib
LibraryBuilder b_bld
SP_TransitionMatrixP b_trx
bool b_initialized
Vec_Flt b_storage_bounds
SP_Vec_Flt b_user_bounds
Vec_Flt b_storage_mg_flux
SP_MGFluxMapper b_flux_mapper
std::vector< SP_Nuclide > b_nuclide_sequence
std::vector< std::vector< WP_Transition > > b_reaction_gain_sequence
std::vector< int > b_sizzzaaa_list
ScaleUtils::IO::DB b_status
Detailed Description
Examples:
tstTransitionMatrixUpdater.cpp.
Constructor & Destructor Documentation
TransitionMatrixUpdater ()
 {
     jDebugTaggedLine( "ctor" );
 }
TransitionMatrixUpdater (const Vec_Flt & storage_bounds)
     : b_storage_bounds( storage_bounds )
 {
     jDebugTaggedLine( "ctor(storage_bounds)" );
 }
~TransitionMatrixUpdater ()
 {
     jDebugTaggedLine( "dtor" );
 }
Member Function Documentation
void load (std::string library_definition, std::string aux_mg_library, std::string fission_yields)
Load resources and create a TransitionSystem.
See also
Overloaded version for a more detailed description.
Examples:
tstTransitionMatrixUpdater.cpp.
Referenced by Origen::test::TEST(), TEST(), and TEST_P().
 {
     // Allocate empty dummy vectors for user defined reaction list
     std::vector<int> user_nuclide_list;
     std::vector<int> user_num_mts;
     std::vector<int> user_mt_list;
     // Call the other overload version with actual implementation.
     this->load( library_definition,
                 aux_mg_library,
                 fission_yields,
                 user_nuclide_list,
                 user_num_mts,
                 user_mt_list );
 }
void load (std::string library_definition, std::string aux_mg_library, std::string fission_yields, const std::vector< int > & user_nuclide_list, const std::vector< int > & user_num_mts, const std::vector< int > & user_mt_list)
Load resources and create a TransitionSystem adding additional user defined reactions.
Additional reactions can be added by passing the user_* vectors.
-"Adding" a reaction that exists in the MG data has no effect. -This will never remove or alter existing reactions. -All daughters of new reactions are produced to ground state. -You cannot add reactions to nuclides that do not exist in the skeleton library. -If the daughter of a new reaction does not exist in the skeleton, it is added to the TransitionSystem, but will not be carried over to TransitionMatrix. The removal associated with such reactions is carried over to the TransitionMatrix, but will remove the nuclide without producing a daughter. -Fission may be added, but will have zero yields.
If fission is added for a nuclide that has no MG data but has yields in the skeleton library, inconsistencies will happen. This is supposed to never happen but there are some data concictency problems
An example of the user_* lists: -user_nuclide_list = {92235, 1092235, 94239, 54135}; -user_num_mts = {2, 1, 0, 2}; -user_mt_list = {MT1_92235, MT2_92235, MT1_92235m, MT1_Xe135, MT2_Xe135};
Parameters
[in] library_defienition Filepath to a skeleton Origen library.
[in] aux_mg_library Filepath to a multi-group library.
[in] fission_yields Filepath to a fission yield library.
[in] user_nuclide_list List of nuclide identifiers for which to add reactions in izzzaaa format.
[in] user_num_mts Number of reactions to add for each nuclide.
[in] user_mt_list List of the reaction MT numbers to add indexed so that the reactions for the first nuclide are first, then those for the second and so on.
References TransitionSystem::add_nuclide(), TransitionMatrixUpdater::b_bld, TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_lib, TransitionMatrixUpdater::b_nuclide_sequence, TransitionMatrixUpdater::b_reaction_gain_sequence, TransitionMatrixUpdater::b_sizzzaaa_list, TransitionMatrixUpdater::b_status, TransitionMatrixUpdater::b_storage_bounds, TransitionMatrixUpdater::b_trx, TransitionMatrixUpdater::b_ts, TransitionMatrixUpdater::b_tsa, TransitionMatrixUpdater::clear(), TransitionSystemAdapter_AmpxN::extend(), NuclideSet::get_ids(), Origen::NEUTRON_FIELD, LibraryHeader::nuclide_set(), TransitionStructure::num_decay_parents(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), LibraryBuilder::search_reaction_transitions(), TransitionSystemAdapter_AmpxN::set_reaction_resource(), and TransitionStructure::transition_ids().
 {
     Require( user_nuclide_list.size() == user_num_mts.size() );
     Require( std::accumulate( user_num_mts.begin(), user_num_mts.end(), 0 ) ==
              user_mt_list.size() );
     this->clear();
     // load up skeleton library (definition)
     LibraryIO lib_io;
     b_lib = Origen::SP_Library( new Origen::Library() );
     bool success_lib = lib_io.load( *b_lib, library_definition, b_status );
     if( !success_lib )
     {
         b_status.appendError( "Could not open library_definition=" +
                               library_definition +
                               " and therefore will not try to open "
                               "aux_mg_library or fission_yields" );
         return;
     }
     else
     {
         b_status.clear();
     }
     jDebugLine( "post-lib" );
     // load up AMPX JEFF
     ReactionResourceIO rr_io;
     SP_ReactionResource sp_rr;
     if( b_storage_bounds.size() != 0 )
     {
         sp_rr = std::make_shared<ReactionResource>( b_storage_bounds );
     }
     else
     {
         sp_rr = std::make_shared<ReactionResource>();
     }
     bool success_rr = rr_io.load( *sp_rr, aux_mg_library, b_status );
     if( !success_rr )
     {
         b_status.appendError(
             "Could not open aux_mg_library=" + aux_mg_library +
             " and therefore will not try to open fission_yields" );
         return;
     }
     else
     {
         b_status.clear();
     }
     jDebugLine( "post-rr" );
     // load up yields
     YieldResourceIO yr_io;
     YieldResource yr;
     bool success_yr = yr_io.load( yr, fission_yields, b_status );
     if( !success_yr )
     {
         b_status.appendError( "Could not open fission_yields=" +
                               fission_yields );
         return;
     }
     else
     {
         b_status.clear();
     }
     jDebugLine( "post-yield with success=" << success_yr );
     // import stuff--in the future the library definition
     // should influence what we import, but for now, just
     // get everything
     jDebugTaggedLine( "starting import of fission yields" );
     sp_rr->import_fission_yields( yr );
     b_tsa.set_reaction_resource( sp_rr );
     // >>> Add user requested additional nuclides and reactions.
     // Check that all nuclides exists in the Library
     {
         std::vector<int> user_to_master, master_to_user;
         b_lib->definition().nuclide_set().mapping_sets(
             user_nuclide_list, &user_to_master, &master_to_user );
         for( size_t i = 0; i < user_nuclide_list.size(); ++i )
         {
             bool exists_in_lib = ( user_to_master[i] != -1 );
             std::ostringstream ss;
             ss << "Trying to add user-defined reaction to "
                << "nuclide " << user_nuclide_list[i]
                << " which does not exist in the skeleton Origen library "
                << library_definition;
             Insist( exists_in_lib, ss.str().c_str() );
         }
     }
     // Loop over user nuclides to add reactions.
     int index_mt_first = 0;
     for( int i = 0; i < user_nuclide_list.size(); ++i )
     {
         // If the nuclide already exists, this only returns the pointer.
         Nuclide::SP nuc = b_ts.add_nuclide( user_nuclide_list[i] );
         // Loop over all user requested reactions for this nuclide.
         for( int j = 0; j < user_num_mts[i]; j++ )
         {
             int mt = user_mt_list[index_mt_first + j];
             // If the reaction already exists this only returns the ptr.
             Channel::SP channel = nuc->add_loss( NEUTRON_FIELD, mt, 0 );
             if( mt != 18 )
             {
                 // Add production of daughter, always ground state.
                 // If the reaction, and hence the transition already
                 // exists this merely returns the pointer.
                 Transition::SP transition = channel->add_transition( 0 );
                 transition->set_yield( 1 );
             }
         }
         index_mt_first += user_num_mts[i];
     }
     // extend the transition system
     b_tsa.extend( &b_ts );
     // get library components
     const TransitionStructure& tstr = b_lib->transition_structure();
     const LibraryHeader& lh = b_lib->definition();
     lh.nuclide_set().get_ids( b_sizzzaaa_list );
     // get skeleton transition matrix
     b_trx = b_lib->newsp_transition_matrix_at( 0 );
     // nuclide sequence & reaction_gain_sequence are what we need to update
     b_bld.search_reaction_transitions( &b_nuclide_sequence,
                                        &b_reaction_gain_sequence,
                                        tstr.num_decay_parents(),
                                        tstr.num_parents(),
                                        tstr.parent_positions(),
                                        tstr.transition_ids(),
                                        b_sizzzaaa_list,
                                        b_ts );
     b_initialized = true;
 }
void clear ()
Clear all class data.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_initialized, and TransitionMatrixUpdater::b_status.
Referenced by TransitionMatrixUpdater::load(), and Origen::test::TEST().
 {
     b_initialized = false;
     //     b_tsa = TransitionSystemAdapter_AmpxN();
     //     b_ts = TransitionSystem_Gen();
     //     b_lib = nullptr;
     //     b_bld = LibraryBuilder();
     //     b_trx = nullptr;
     //     b_storage_bounds.clear();
     //     b_user_bounds = nullptr;
     //     b_storage_mg_flux.clear();
     //     b_flux_mapper = nullptr;
     //     b_nuclide_sequence.clear();
     //     b_reaction_gain_sequence.clear();
     //     b_sizzzaaa_list.clear();
     b_status.clear();
 }
bool initialized () const
Return if data has been loaded correctly and initial setup performed, i.e. ready to calculate.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_initialized.
Referenced by Origen::test::TEST(), and TEST_P().
 { return b_initialized; }
void set_user_bounds (const Vec_Flt & user_bounds)
Set the group structure energy bounds when multi-group flux is supplied.
The default, if this function is not used, is to deliver the flux in the storage group structure for the reaction resource. A mapping is used to map the user flux to the storage flux, to then calculate energy integrated data. The mapping can be cancelled by calling unset_user_bounds.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_flux_mapper, TransitionMatrixUpdater::b_user_bounds, and TransitionMatrixUpdater::storage_bounds().
Referenced by Origen::test::TEST().
 {
     b_user_bounds = SP_Vec_Flt( new Vec_Flt( user_bounds ) );
     SP_Vec_Flt new_bounds( new Vec_Flt( *storage_bounds() ) );
     ScaleData::EnergyUnionizer<float> eu( b_user_bounds, new_bounds );
     SP_Vec_Flt fi( MGFluxMapper::fluxIntegrals_1OverE( *eu.cUnionGrid() ) );
     b_flux_mapper = SP_MGFluxMapper( new MGFluxMapper( eu, fi ) );
 }
void unset_user_bounds ()
Clear the mapping of user flux to storage flux.
References TransitionMatrixUpdater::b_flux_mapper, TransitionMatrixUpdater::b_storage_mg_flux, and TransitionMatrixUpdater::b_user_bounds.
 {
     b_flux_mapper = nullptr;
     b_user_bounds = nullptr;
     b_storage_mg_flux.clear();
 }
float update_mg_flux (const Vec_Flt & mg_flux)
Recalculate energy-integrated quantities using new flux.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_flux_mapper, TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_storage_mg_flux, TransitionMatrixUpdater::b_ts, TransitionMatrixUpdater::b_tsa, TransitionMatrixUpdater::num_energy_groups(), and TransitionSystemAdapter_AmpxN::update().
Referenced by Origen::test::TEST(), TEST(), and TEST_P().
 {
     jDebugTaggedLine( "entering TransitionMatrixUpdater::update_mg_flux" );
     Require( b_initialized );
     if( b_flux_mapper != nullptr )
     {
         b_storage_mg_flux.resize( num_energy_groups() );
         b_flux_mapper->mapFlux( mg_flux, b_storage_mg_flux );
     }
     else
     {
         b_storage_mg_flux = mg_flux;
     }
     float flux = b_tsa.update( &b_ts, b_storage_mg_flux );
     jDebugTaggedLine(
         "leaving TransitionMatrixUpdater::update_mg_flux[" << flux << "]" );
     return flux;
 }
float update_by_mix (const AmpxLibrary & main, int mix_id, const Vec_Flt & flux)
Update local data using a specific mixture's cross sections on an AMPX library.
References TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_ts, TransitionMatrixUpdater::b_tsa, and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     Require( b_initialized );
     return b_tsa.update_by_mix( &b_ts, main, mix_id, flux );
 }
void update_user_xs (std::string id_form, const std::vector< int > & nuclide_list, const std::vector< int > & num_mts, const std::vector< int > & mt_list, const Vec_Flt & xs)
Update the system with a list of user-provided cross sections.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_ts, and TransitionMatrixUpdater::fetch_ts_nuclides().
Referenced by TEST(), and Origen::test::TEST().
 {
     jDebugTaggedLine( "entering update_user_xs" );
     Require( b_initialized );
     Require( nuclide_list.size() == num_mts.size() );
     Require( mt_list.size() == xs.size() );
     std::vector<SP_Nuclide> ts_nuclides;
     fetch_ts_nuclides( &ts_nuclides, b_ts, id_form, nuclide_list );
     SP_Nuclide n;
     SP_Channel c;
     int total_mts = 0;
     for( size_t i = 0; i < ts_nuclides.size(); ++i )
     {
         n = ts_nuclides[i];
         jDebugTaggedLine( "nuclide id=" << nuclide_list[i] << " nuclide="
                                         << ( n == nullptr ? 0 : n->id() ) );
         if( n == nullptr ) continue;
         for( int j = 0 + total_mts; j < num_mts[i] + total_mts; ++j )
         {
             int mt = mt_list[j];
             c = n->loss( mt );
             jDebugTaggedLine(
                 "   channel id=" << mt << " channel="
                                  << ( c == nullptr ? 0 : c->id() ) );
             if( c != nullptr )
             {
                 jDebugTaggedLine(
                     "   setting xs for nuclide id=" << n->id() << " mt=" << mt
                                                     << " xs="
                                                     << c->xs()
                                                     << "-->"
                                                     << xs[j] );
                 c->set_xs( xs[j] );
             }
             else
             {
                 jDebugTaggedLine(
                     "   ERROR: no channel for nuclide id=" << n->id() << " mt="
                                                            << mt
                                                            << " xs="
                                                            << xs[j] );
             }
         }
         total_mts += num_mts[i];
     }
 }
void update_fission_absorption_xs (std::string id_form, const std::vector< int > & nuclide_list, const Vec_Flt & fission_xs, const Vec_Flt & absorption_xs)
Special update of fission and absorption cross sections only.
References TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_ts, and TransitionMatrixUpdater::fetch_ts_nuclides().
Referenced by TEST().
 {
     jDebugTaggedLine(
         "entering TransitionMatrixUpdater::update_fission_absorption_xs" );
     Require( b_initialized );
     Require( nuclide_list.size() == fission_xs.size() );
     Require( fission_xs.size() == absorption_xs.size() );
     std::vector<SP_Nuclide> ts_nuclides;
     fetch_ts_nuclides( &ts_nuclides, b_ts, id_form, nuclide_list );
     SP_Nuclide n;
     SP_Channel c;
     for( size_t i = 0; i < ts_nuclides.size(); ++i )
     {
         n = ts_nuclides[i];
         double abs_xs = absorption_xs[i];
         double fis_xs = fission_xs[i];
         double cap_xs = abs_xs - fis_xs;
         jDebugLine( "updating nuclide=" << ( n == nullptr ? 0 : n->id() )
                                         << " with abs_xs="
                                         << abs_xs
                                         << " fis_xs="
                                         << fis_xs
                                         << " cap_xs="
                                         << cap_xs );
         if( abs_xs < 0.0 )
         {
             jDebugLine( "   WARNING: " << ( n == nullptr ? 0 : n->id() )
                                        << " with abs_xs="
                                        << abs_xs
                                        << " < 0"
                                        << " will not be updated!" );
             continue;
         }
         // Check(abs_xs>=0);
         // Check(fis_xs>=0);
         // Check(abs_xs>=fis_xs);
         if( n == nullptr )
         {
             jDebugLine( "   ...failed to update id=" << nuclide_list[i] );
             continue;
         }
         std::vector<SP_Channel> losses = n->losses();
         // infinitely dilute capture xs
         std::vector<double> id_cap_xs( losses.size(), 0.0 );
         double total_id_cap_xs = 0.0;
         for( size_t j = 0; j < losses.size(); ++j )
         {
             int reaction_mt = losses[j]->id();
             // set fission
             if( reaction_mt == 18 )
             {
                 losses[j]->set_xs( fis_xs );
             }
             // sum the remainder
             else if( reaction_mt >= 102 && reaction_mt <= 117 )
             {
                 double this_cap = losses[j]->xs();
                 id_cap_xs[j] = this_cap;
                 total_id_cap_xs += this_cap;
             }
         }
         jDebugLine( "   infinitely-dilute cap_xs(" << n->id() << ")="
                                                    << total_id_cap_xs );
         if( total_id_cap_xs > 0.0 )
         {
             // calculate self-shielding factor for capture
             double f_ss_cap = cap_xs / ( total_id_cap_xs );
             jDebugLine(
                 "   self-shielding factor(" << n->id() << ")=" << f_ss_cap );
             // Check(cap_xs<=total_id_cap_xs); //self-shielding yields lower xs
             // loop again, this time modifying all the capture xs
             for( size_t j = 0; j < losses.size(); ++j )
             {
                 int reaction_mt = losses[j]->id();
                 if( reaction_mt >= 102 && reaction_mt <= 117 )
                 {
                     losses[j]->set_xs( id_cap_xs[j] * f_ss_cap );
                     continue;
                 }
                 Check( id_cap_xs[j] == 0.0 );
             }
         }
     }
     jDebugTaggedLine(
         "leaving TransitionMatrixUpdater::update_fission_absorption_xs" );
 }
void get_xs (std::string id_form, const std::vector< int > & nuclide_list, const std::vector< int > & num_mts, const std::vector< int > & mt_list, Vec_Flt * xs)
Get values of cross sections currently stored.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_ts, and TransitionMatrixUpdater::fetch_ts_nuclides().
Referenced by Origen::test::TEST().
 {
     jDebugTaggedLine( "entering TransitionMatrixUpdater::get_xs" );
     Require( b_initialized );
     Require( nuclide_list.size() == num_mts.size() );
     xs->clear();
     std::vector<SP_Nuclide> ts_nuclides;
     fetch_ts_nuclides( &ts_nuclides, b_ts, id_form, nuclide_list );
     SP_Nuclide n;
     SP_Channel c;
     int total_mts = 0;
     for( size_t i = 0; i < ts_nuclides.size(); ++i )
     {
         n = ts_nuclides[i];
         jDebugTaggedLine( " nuclide=" << ( n == nullptr ? 0 : n->id() ) );
         if( n == nullptr )
         {
             xs->push_back( -1.0 );
             continue;
         }
         for( int j = 0 + total_mts; j < num_mts[i] + total_mts; ++j )
         {
             c = n->loss( mt_list[j] );
             jDebugTaggedLine(
                 "   channel id=" << mt_list[j] << " channel="
                                  << ( c == nullptr ? 0 : c->id() ) );
             if( c != nullptr )
             {
                 xs->push_back( c->xs() );
                 jDebugTaggedLine( "   getting xs for nuclide id=" << n->id()
                                                                   << " mt="
                                                                   << mt_list[j]
                                                                   << " xs="
                                                                   << c->xs() );
             }
             else
             {
                 xs->push_back( -1.0 );
                 jDebugTaggedLine(
                     "   ERROR: no channel for nuclide id=" << n->id() << " mt="
                                                            << mt_list[j]
                                                            << " xs="
                                                            << -1.0 );
             }
         }
         total_mts += num_mts[i];
     }
     jDebugTaggedLine( "leaving TransitionMatrixUpdater::get_xs" );
 }
void get_transition_matrix (TransitionMatrixP * trx)
Pass non-null pointer to have it filled with current cross section data based on loaded transition definition.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_bld, TransitionMatrixUpdater::b_initialized, TransitionMatrixUpdater::b_nuclide_sequence, TransitionMatrixUpdater::b_reaction_gain_sequence, TransitionMatrixUpdater::b_sizzzaaa_list, TransitionMatrixUpdater::b_trx, TransitionMatrixUpdater::b_ts, TransitionSystem::field(), TransitionMatrixP::get_a(), TransitionMatrixP::get_fiss(), TransitionMatrixP::get_genneu(), TransitionMatrixP::get_iact(), TransitionMatrixP::get_kd_(), TransitionMatrixP::get_loc(), TransitionMatrixP::get_mt(), TransitionMatrixP::get_non0_(), TransitionMatrixP::get_tocap(), Origen::NEUTRON_FIELD, and LibraryBuilder::update_reaction_transitions().
Referenced by Origen::test::TEST(), TEST(), and TEST_P().
 {
     Require( b_initialized );
     Require( trx != nullptr );
     // reset to base transition matrix
     ( *trx ) = *b_trx;
     Check( trx->get_iact() == static_cast<int>( trx->get_fiss()->size() ) );
     // The coeff update requires intensity=1.0 currently, although we
     // should think about whether this is absolutely necessary
     SP_Field field = b_ts.field( NEUTRON_FIELD );
     double saved_intensity = field->intensity();
     field->set_intensity( 1.0 );
     b_bld.update_reaction_transitions( trx->get_a(),
                                        trx->get_tocap(),
                                        trx->get_fiss(),
                                        trx->get_genneu(),
                                        b_nuclide_sequence,
                                        b_reaction_gain_sequence,
                                        *trx->get_kd_(),
                                        *trx->get_non0_(),
                                        *trx->get_loc(),
                                        *trx->get_mt(),
                                        b_sizzzaaa_list );
     field->set_intensity( saved_intensity );
 }
void get_data_container (const AbstractDC * dc)
Get internal status data container.
References TransitionMatrixUpdater::b_status.
 {
     dc = &b_status.data();
 }
int get_errors (std::vector< std::string > * errors)
Get list of errors.
References TransitionMatrixUpdater::b_status.
Referenced by TEST_P().
 {
     Require( errors != nullptr );
     b_status.getErrorStack( errors );
     return errors->size();
 }
const ScaleUtils::IO::DB & status () const
Return status.
References TransitionMatrixUpdater::b_status.
 {
     return b_status;
 }
const Library * library () const
Return a pointer to the skeleton library definition.
 { return &( *b_lib ); }
SP_Library sp_library ()
Return mutable shared pointer to skeleton library definition.
References TransitionMatrixUpdater::b_lib.
Referenced by TEST(), and TEST_P().
 { return b_lib; }
const TransitionSystem * transition_system () const
Return a pointer to the transition system.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_ts.
Referenced by Origen::test::TEST().
 {
     return &b_ts;
 }
const ReactionResource * mg_database () const
Return a pointer to reaction resource.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_tsa, TransitionSystemAdapter_AmpxN::has_reaction_resource(), and TransitionSystemAdapter_AmpxN::reaction_resource().
Referenced by TransitionMatrixUpdater::num_energy_groups(), TransitionMatrixUpdater::storage_bounds(), and Origen::test::TEST().
 {
     Require( b_tsa.has_reaction_resource() );
     return &*b_tsa.reaction_resource();
 }
int num_energy_groups () const
Return number of energy groups for stored cross sections.
References TransitionMatrixUpdater::mg_database(), and ReactionResource::storage_bounds().
Referenced by TransitionMatrixUpdater::update_mg_flux().
 {
     return mg_database()->storage_bounds().size() - 1;
 }
const Vec_Flt * storage_bounds () const
Return stored energy bounds.
References TransitionMatrixUpdater::mg_database(), and ReactionResource::storage_bounds().
Referenced by TransitionMatrixUpdater::set_user_bounds().
 {
     return &( mg_database()->storage_bounds() );
 }
const Vec_Flt * storage_mg_flux () const
Return stored multi-group flux.
References TransitionMatrixUpdater::b_storage_mg_flux.
 {
     return &b_storage_mg_flux;
 }
const Vec_Flt * user_bounds () const
Return user bounds.
 {
     return &( *b_user_bounds );
 }
const LibraryHeader * library_header () const
Return library header on skeleton library (convenience method).
References TransitionMatrixUpdater::b_lib.
 {
     return &( b_lib->definition() );
 }
const TransitionStructure * transition_structure () const
Return transition structure on skeleton library (convenience method).
References TransitionMatrixUpdater::b_lib.
 {
     return &( b_lib->transition_structure() );
 }
SP_TransitionMatrixP base_transition_matrix ()
Return base transition matrix.
Every transition matrix produced by this updater will have this format as the base.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_trx.
Referenced by Origen::test::TEST().
 {
     Require( b_trx != nullptr );
     return b_trx;
 }
void fetch_ts_nuclides (std::vector< SP_Nuclide > * ts_nuclides, std::string id_form, const std::vector< int > & nuclide_list)
Return a list of mutable nuclide objects on the transition system from a list of nuclide ids.
Examples:
tstTransitionMatrixUpdater.cpp.
References TransitionMatrixUpdater::b_initialized, and TransitionMatrixUpdater::b_ts.
Referenced by TransitionMatrixUpdater::get_xs(), Origen::test::TEST(), TransitionMatrixUpdater::update_fission_absorption_xs(), and TransitionMatrixUpdater::update_user_xs().
 {
     Require( b_initialized );
     fetch_ts_nuclides( ts_nuclides, b_ts, id_form, nuclide_list );
 }
void fetch_ts_nuclides (std::vector< SP_Nuclide > * ts_nuclides, const TransitionSystem & ts, std::string id_form, const std::vector< int > & nuclide_list) static
Return a list of mutable nuclide objects on the transition system from a list of nuclide ids.
References TransitionSystem::nuclide().
 {
     jDebugTaggedLine( "entering TransitionMatrixUpdater::fetch_ts_nuclides" );
     ts_nuclides->clear();
     ts_nuclides->resize( nuclide_list.size() );
     int id;
     for( size_t i = 0; i < nuclide_list.size(); ++i )
     {
         id = nuclide_list[i];
         if( id_form == "ZZZAAAI" )
         {
             id = ScaleData::Utils::zzzaaai_to_pizzzaaa( id );
         }
         else if( id_form == "ZZZAAAI+FP5000" )
         {
             if( id % 10000 > 5000 )
             {
                 id -= 5000;
             }
             id = ScaleData::Utils::zzzaaai_to_pizzzaaa( id );
         }
         jDebugLine( "   translated " << id_form << "=" << nuclide_list[i]
                                      << " --> "
                                      << id );
         ( *ts_nuclides )[i] = ts.nuclide( id );
     }
     Ensure( ts_nuclides->size() == nuclide_list.size() );
     jDebugTaggedLine( "leaving TransitionMatrixUpdater::fetch_ts_nuclides" );
 }
Member Data Documentation
TransitionSystemAdapter_AmpxN b_tsa private
Referenced by TransitionMatrixUpdater::load(), TransitionMatrixUpdater::mg_database(), TransitionMatrixUpdater::update_by_mix(), and TransitionMatrixUpdater::update_mg_flux().
TransitionSystem_Gen b_ts private
Referenced by TransitionMatrixUpdater::fetch_ts_nuclides(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::get_xs(), TransitionMatrixUpdater::load(), TransitionMatrixUpdater::transition_system(), TransitionMatrixUpdater::update_by_mix(), TransitionMatrixUpdater::update_fission_absorption_xs(), TransitionMatrixUpdater::update_mg_flux(), and TransitionMatrixUpdater::update_user_xs().
SP_Library b_lib private
Referenced by TransitionMatrixUpdater::library_header(), TransitionMatrixUpdater::load(), TransitionMatrixUpdater::sp_library(), and TransitionMatrixUpdater::transition_structure().
LibraryBuilder b_bld private
Referenced by TransitionMatrixUpdater::get_transition_matrix(), and TransitionMatrixUpdater::load().
SP_TransitionMatrixP b_trx private
Referenced by TransitionMatrixUpdater::base_transition_matrix(), TransitionMatrixUpdater::get_transition_matrix(), and TransitionMatrixUpdater::load().
bool b_initialized private
Referenced by TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::fetch_ts_nuclides(), TransitionMatrixUpdater::get_transition_matrix(), TransitionMatrixUpdater::get_xs(), TransitionMatrixUpdater::initialized(), TransitionMatrixUpdater::load(), TransitionMatrixUpdater::update_by_mix(), TransitionMatrixUpdater::update_fission_absorption_xs(), TransitionMatrixUpdater::update_mg_flux(), and TransitionMatrixUpdater::update_user_xs().
Vec_Flt b_storage_bounds private
Referenced by TransitionMatrixUpdater::load().
SP_Vec_Flt b_user_bounds private
Referenced by TransitionMatrixUpdater::set_user_bounds(), and TransitionMatrixUpdater::unset_user_bounds().
Vec_Flt b_storage_mg_flux private
Referenced by TransitionMatrixUpdater::storage_mg_flux(), TransitionMatrixUpdater::unset_user_bounds(), and TransitionMatrixUpdater::update_mg_flux().
SP_MGFluxMapper b_flux_mapper private
Referenced by TransitionMatrixUpdater::set_user_bounds(), TransitionMatrixUpdater::unset_user_bounds(), and TransitionMatrixUpdater::update_mg_flux().
std::vector<SP_Nuclide> b_nuclide_sequence private
Referenced by TransitionMatrixUpdater::get_transition_matrix(), and TransitionMatrixUpdater::load().
std::vector<std::vector<WP_Transition> > b_reaction_gain_sequence private
Referenced by TransitionMatrixUpdater::get_transition_matrix(), and TransitionMatrixUpdater::load().
std::vector<int> b_sizzzaaa_list private
Referenced by TransitionMatrixUpdater::get_transition_matrix(), and TransitionMatrixUpdater::load().
ScaleUtils::IO::DB b_status private
Referenced by TransitionMatrixUpdater::clear(), TransitionMatrixUpdater::get_data_container(), TransitionMatrixUpdater::get_errors(), TransitionMatrixUpdater::load(), and TransitionMatrixUpdater::status().
The documentation for this class was generated from the following files:
Manager/libld/TransitionMatrixUpdater.h
Manager/libld/TransitionMatrixUpdater.cpp