ORIGEN API: dataTests Namespace Reference
dataTests Namespace Reference
Convenience functions used in data tests.
Functions
std::shared_ptr< Origen::Solver > determine_solver (Standard::CommandLine *cmdLine)
Origen::SP_Material set_materials_using_f71_file (Origen::SP_StateSet ft71_data, Origen::SP_Library lib)
Origen::SP_Material set_materials_given_id (Origen::SP_Library lib, std::string param)
bool get_data_path (std::string &data_path)
Detailed Description
Convenience functions used in data tests.
Function Documentation
std::shared_ptr< Origen::Solver > determine_solver (Standard::CommandLine * cmdLine)
Determines the solver to use based on command parameters.
Parameters
cmdLine The command line to process.
Returns
A shared pointer to the solver.
Referenced by decay_compare::decay_compare(), and yields_compare::yields_compare().
 {
     std::shared_ptr<Origen::Solver> slv;
     std::string solver = cmdLine->getValue( "solver", "matrex" );
     if( solver == "matrex" )
         slv = std::make_shared<Origen::Solver_matrex>();
     else if( solver == "cram" )
         slv = std::make_shared<Origen::Solver_cram>();
     else
         slv = std::make_shared<Origen::Solver_matrex>();
     return slv;
 }
Origen::SP_Material set_materials_using_f71_file (Origen::SP_StateSet ft71_data, Origen::SP_Library lib)
Sets the materials based on what is on the ft71 data.
Parameters
mat The material that will be set to the ft71 concentrations.
ft71_data The ft71 file data.
lib The library that the material will be initialized with.
Referenced by TEST(), and TEST_P().
 {
     std::vector<int> ids;        // nuclide ids in IZZZAAA format
     std::vector<double> numden;  // atoms/barn-cm
     double volume = 1.0;         // cm^3
     int id = 1;                  // material id
     std::string name = "ft71";   // material name
     Origen::SCP_State state = ft71_data->scp_states_at( 0 );
     Origen::SCP_Concentrations concs = state->scp_concs();
     Origen::SCP_NuclideSet nuc_set = concs->scp_nuclide_set();
     Origen::Vec_Int nucs;
     nuc_set->get_ids( nucs );
     Origen::Vec_Dbl vals;
     concs->get_vals( vals );
     for( int i = 0; i < nucs.size(); i++ )
     {
         if( vals.at( i ) > 0.0 )
         {
             ids.push_back( nucs.at( i ) );
             numden.push_back( vals.at( i ) );
         }
     }
     // Initialize the material.
     Origen::SP_Material mat =
         Origen::SP_Material( new Origen::Material( lib, name, id, volume ) );
     // Set the beginning of step number densities.
     mat->set_numden_bos( numden, ids );
     return mat;
 }
Origen::SP_Material set_materials_given_id (Origen::SP_Library lib, std::string param)
Sets a material to have 1.0 number density of one isotope.
Parameters
mat The material that will be set.
lib The library that the material will be initialized with.
param The string with the name of the isotope to be used.
Referenced by TEST_P().
 {
     std::vector<int> ids;        // nuclide ids in IZZZAAA format
     std::vector<double> numden;  // atoms/barn-cm
     double volume = 1.0;         // cm^3
     int id = 1;                  // material id
     std::string name = "param";  // material name
     int id_int = ScaleData::Utils::symbol_to_pizzzaaa( param );
     ids.push_back( id_int );
     numden.push_back( 1.0 );
     // Initialize the material.
     std::cout << "Material: " << id_int << " (" << param << ")\n";
     Origen::SP_Material mat =
         Origen::SP_Material( new Origen::Material( lib, name, id, volume ) );
     // Set the beginning of step number densities.
     mat->set_numden_bos( numden, ids );
     return mat;
 }
bool get_data_path (std::string & data_path)
Gets the path to the Scale data from the environment variable DATA.
Parameters
data_path Will be set to the path to Scale data if it exists.
Returns
Whether or not the DATA environment variable was found.
Referenced by TEST(), and TEST_P().
 {
     char* dpath = std::getenv( "DATA" );
     if( dpath == 0 )
     {
         return false;
     }
     else
     {
         data_path = dpath;
         return true;
     }
 }