ORIGEN API: TagManager Class Reference
TagManager Class Reference
#include <TagManager.h>
TagManager class definition.
Public Types
typedef std::shared_ptr< TagManager > SP
TagManager smart pointer typedef.
typedef std::shared_ptr< const TagManager > SCP
TagManger constant smart pointer typedef.
Public Member Functions
TagManager ()
Constructor.
TagManager (const TagManager &orig)
Copy constructor.
virtual ~TagManager ()
Destructor.
bool hasTag (std::string name) const
This function uses the containsType functions from DataContainer and just checks both types.
std::string getIdTag (std::string name) const
This returns the string value of the tag passed as the parameter.
double getInterpTag (std::string name) const
This returns the double value of the tag passed as the parameter.
Vec_Str listIdTags () const
Overrides the getNames function in DataContainer and is used specifically to return the names of the ID tags (of type string values). There is no order.
Vec_Str listInterpTags () const
Overrides the getNames function in DataContainer and is used specifically to return the names of the interpolatable tags (of type double values). There is no order.
Vec_Str listIdValues () const
Return vector of id tag values in the DataContainer.
Vec_Dbl listInterpValues () const
Return vector of interpolatable tag values in the DataContainer.
void setInterpValues (Vec_Dbl &values)
Set interpolatable tag values by a vector.
void setIdTag (std::string name, std::string strValue)
Set new string value to ID tag. Create new ID tag if that tag isn't already present in the current DataContainer.
void setInterpTag (std::string name, double dblValue)
This function checks if the name provided is already in the interpolatable tags. If yes, it applies the new value to that tag name. If no, it adds the tag name and matching value.
bool deleteTag (std::string name, std::ostream &os=std::cerr)
This function currently just uses the remove functions built into DataContainer to put the values into temporary variables and then returns void. Does this rather ham-handedly by just calling the remove functions for both types that the tag could be, abusing the inherent checks in the remove functions. In the future, could return the value, requiring that this function be split by type.
void deleteAll ()
This function should clear out all of the tags on this tag manager.
SP clone () const
< Deep copy method
bool operator== (const TagManager &other) const
Equality comparison operator.
bool match (const TagManager &other) const
This function should check the provided tag manager against the current tag manager to ensure a perfect match of tag names. This is achieved by calling the internal compare function twice, switching the arguments. If the internal compare function returns a null set both times, the two match. Otherwise, they don't match.
bool interpolationCompare (const TagManager &other) const
Function to compare the values of a set of ID tags to ensure the two TagManagers are describing the same type of Library with different interp tags for interpolation.
Vec_Str compare (const TagManager &sp_other) const
This function accepts a TagManager and uses the internalCompare function and returns a list of the tags that don't match between the provided TagManager and the current TagManager.
Vec_Str compare (Vec_Str desired) const
This function is one of the overloaded compare functions that accepts a vector of tag names. It then sends the internalCompare function that vector of strings and a dereferenced pointer to this tag manager.
Scale::Json::Value to_json () const
write to JSON
std::string to_string () const
write to std::string
virtual Standard::Serializable::UID getUID () const
Get serializable UID.
virtual TagManager * getCopy () const
Clone method.
std::string toString () const
Static Public Attributes
static const Standard::Serializable::UID uid = 0x11111152b5b56031
Serializable UID.
Private Member Functions
Vec_Str internalCompare (Vec_Str desired, const TagManager &other) const
Internal compare function.
bool checkMaps ()
This function should check all of the DataContainer types that are not string and double and ensure that they are all empty.
Friends
class ScaleUtils::IO::Accessor< TagManager >
Detailed Description
TagManager class definition.
Author
Nicholas C. Sly
Date
March 11, 2014
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstTagManager.cpp, and Core/fn/tests/tstinterp.cpp.
Member Typedef Documentation
typedef std::shared_ptr<TagManager> SP
TagManager smart pointer typedef.
typedef std::shared_ptr<const TagManager> SCP
TagManger constant smart pointer typedef.
Constructor & Destructor Documentation
TagManager ()
Constructor.
Referenced by TagManager::clone(), and TagManager::getCopy().
 {}
TagManager (const TagManager & orig)
Copy constructor.
 : DataContainer( orig ) {}
~TagManager () virtual
Destructor.
References TagManager::checkMaps().
 { Check( this->checkMaps() ); }
Member Function Documentation
bool hasTag (std::string name) const
This function uses the containsType functions from DataContainer and just checks both types.
Parameters
name - Name of the tag being searched for (ID or interpolatable).
Returns
bool - True if a tag with that name is present. False otherwise.
Examples:
Core/fn/tests/tstinterp.cpp.
Referenced by Origen::checkImplicitTags(), TagManager::deleteTag(), TagManager::interpolationCompare(), and TEST().
 {
     return ( this->containsString( name ) || this->containsDouble( name ) );
 }  // hasTag
std::string getIdTag (std::string name) const
This returns the string value of the tag passed as the parameter.
Parameters
name Name of the ID tag being searched for.
Returns
Value of the ID tag being searched for.
Examples:
Core/fn/tests/tstinterp.cpp.
Referenced by TagManager::clone(), TagManager::interpolationCompare(), TagManager::listIdValues(), Origen::printIdTags_json(), and TEST().
 {
     return getString( name );
 }  // getIdTag
double getInterpTag (std::string name) const
This returns the double value of the tag passed as the parameter.
Parameters
name Name of the interpolatable tag being searched for.
Returns
Value of the interpolatable tag being searched for.
Examples:
Core/fn/tests/tstinterp.cpp.
Referenced by TagManager::clone(), GridData_TransitionCoeff::getWts(), TagManager::listInterpValues(), Origen::printInterpTags_json(), and TEST().
 {
     return getDouble( name );
 }  // getInterpTag
Vec_Str listIdTags () const
Overrides the getNames function in DataContainer and is used specifically to return the names of the ID tags (of type string values). There is no order.
Returns
A list of the names of all ID tags on the TagManager.
Referenced by TagManager::clone(), TagManager::compare(), TagManager::deleteAll(), TagManager::internalCompare(), TagManager::interpolationCompare(), TagManager::listIdValues(), TagManager::match(), TagManager::operator==(), Origen::printIdTags_json(), Origen::printInterpTags_json(), TagManager::to_json(), and Origen::write().
 {
     return this->getStringNames();
 }  // listIdTags
Vec_Str listInterpTags () const
Overrides the getNames function in DataContainer and is used specifically to return the names of the interpolatable tags (of type double values). There is no order.
Returns
A list of the names of all interpolatable tags on the TagManager.
Referenced by TagManager::clone(), TagManager::compare(), TagManager::deleteAll(), TagManager::internalCompare(), Origen::interpLibraryND(), TagManager::interpolationCompare(), TagManager::listInterpValues(), TagManager::match(), TagManager::operator==(), Origen::printInterpTags_json(), TagManager::setInterpValues(), TagManager::to_json(), and Origen::write().
 {
     return this->getDoubleNames();
 }  // listInterpTags
Vec_Str listIdValues () const
Return vector of id tag values in the DataContainer.
Returns
Vec_Str - list of id tag names.
References TagManager::getIdTag(), and TagManager::listIdTags().
Referenced by TagManager::operator==(), TagManager::to_json(), and Origen::write().
 {
     Vec_Str tags = listIdTags();
     Vec_Str values;
     values.reserve( tags.size() );
     for( auto& it : tags )
     {
         values.push_back( getIdTag( it ) );
     }
     return values;
 }  // listIdValues
Vec_Dbl listInterpValues () const
Return vector of interpolatable tag values in the DataContainer.
Returns
Vec_Dbl - list of interpolatable tag values.
References TagManager::getInterpTag(), and TagManager::listInterpTags().
Referenced by TagManager::operator==(), TagManager::to_json(), and Origen::write().
 {
     Vec_Str tags = listInterpTags();
     Vec_Dbl values;
     values.reserve( tags.size() );
     for( auto& it : tags )
     {
         values.push_back( getInterpTag( it ) );
     }
     return values;
 }  // listInterpValues
void setInterpValues (Vec_Dbl & values)
Set interpolatable tag values by a vector.
Parameters
values list of interpolatable tag values (order same as listInterpTags would return).
References TagManager::listInterpTags(), and TagManager::setInterpTag().
Referenced by GridView_StateInfo::permute().
 {
     Vec_Str tags = listInterpTags();
     size_t i = 0;
     for( auto& it : tags )
     {
         setInterpTag( it, values[i] );
         ++i;
     }
 }  // setInterpValues
void setIdTag (std::string name, std::string strValue)
Set new string value to ID tag. Create new ID tag if that tag isn't already present in the current DataContainer.
This function checks if the name provided is already in the ID tags. If yes, it applies the new value to that tag name. If no, it adds the tag name and matching value.
Parameters
name - Name of the ID tag.
strValue - String value of the ID tag.
Examples:
Core/dc/tests/tstLibrary.cpp, and Core/fn/tests/tstinterp.cpp.
Referenced by Origen::collectLibraries(), Obiwan_tag::execute(), Obiwan_interp::execute(), Origen::read(), Accessor< Origen::TagManager >::read(), Origen::saveStateSet(), LibraryTest::SetUp(), and TEST().
 {
     this->addString( name, strValue );
 }  // setIdTag
void setInterpTag (std::string name, double dblValue)
This function checks if the name provided is already in the interpolatable tags. If yes, it applies the new value to that tag name. If no, it adds the tag name and matching value.
Parameters
name - Name of the interpolatable tag.
dblValue - Double value of the interpolatable tag.
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstLibrary.cpp, and Core/fn/tests/tstinterp.cpp.
Referenced by Origen::addImpliedTags(), Obiwan_interp::execute(), Obiwan_tag::execute(), FakeFactory::Library_linear2D(), Origen::read(), Accessor< Origen::TagManager >::read(), TagManager::setInterpValues(), LibraryTest::SetUp(), and TEST().
 {
     this->addDouble( name, dblValue );
 }  // setInterpTag
bool deleteTag (std::string name, std::ostream & os = std::cerr)
This function currently just uses the remove functions built into DataContainer to put the values into temporary variables and then returns void. Does this rather ham-handedly by just calling the remove functions for both types that the tag could be, abusing the inherent checks in the remove functions. In the future, could return the value, requiring that this function be split by type.
Parameters
name Name of the tag that you're looking to delete.
os Output stream to which an error can be sent.
Returns
bool - True if the tag was found and deleted. False otherwise (i.e., tag not present).
Examples:
Core/fn/tests/tstinterp.cpp.
References TagManager::hasTag().
Referenced by TagManager::deleteAll(), Obiwan_tag::execute(), and TEST().
 {
     if( !this->hasTag( name ) )
     {
         os << "TagManager: Deleted tag that was not present\n";
         return false;
     }
     if( this->containsString( name ) ) this->removeString( name );
     if( this->containsDouble( name ) ) this->removeDouble( name );
     return true;
 }  // deleteTag
void deleteAll ()
This function should clear out all of the tags on this tag manager.
References TagManager::deleteTag(), TagManager::listIdTags(), and TagManager::listInterpTags().
 {
     Vec_Str names;
     names = this->listIdTags();
     Vec_Str::const_iterator nit;
     for( nit = names.begin(); nit != names.end(); ++nit )
     {
         this->deleteTag( *nit );
     }
     names.clear();
     names = this->listInterpTags();
     for( nit = names.begin(); nit != names.end(); ++nit )
     {
         this->deleteTag( *nit );
     }
 }  // deleteAll
SP_TagManager clone () const
< Deep copy method
Examples:
Core/fn/tests/tstinterp.cpp.
References TagManager::getIdTag(), TagManager::getInterpTag(), TagManager::listIdTags(), TagManager::listInterpTags(), and TagManager::TagManager().
Referenced by TEST().
 {
     SP_TagManager tm = SP_TagManager( new TagManager() );
     for( auto& tag : this->listIdTags() )
         tm->setIdTag( tag, this->getIdTag( tag ) );
     for( auto& tag : this->listInterpTags() )
         tm->setInterpTag( tag, this->getInterpTag( tag ) );
     return tm;
 }
bool operator== (const TagManager & other) const
Equality comparison operator.
Parameters
other Other TagManager object to compare against
other Other TagManager object to compare against
other Other TagManager object to compare against
Returns
bool - True if match. False otherwise.
Remarks
Does approximate comparison on doubles and exact match on strings.
References TagManager::listIdTags(), TagManager::listIdValues(), TagManager::listInterpTags(), and TagManager::listInterpValues().
 {
     return eq_vec( listIdTags(), other.listIdTags() ) &&
            eq_vec( listInterpTags(), other.listInterpTags() ) &&
            eq_vec( listIdValues(), other.listIdValues() ) &&
            eq_vec( listInterpValues(), other.listInterpValues() );
 }  //==
bool match (const TagManager & other) const
This function should check the provided tag manager against the current tag manager to ensure a perfect match of tag names. This is achieved by calling the internal compare function twice, switching the arguments. If the internal compare function returns a null set both times, the two match. Otherwise, they don't match.
Parameters
other Another TagManager to compare against the current TagManager.
Returns
bool - True if all of the tag names on the provided TagManager perfectly match those on the current TagManager. False otherwise.
References TagManager::internalCompare(), TagManager::listIdTags(), and TagManager::listInterpTags().
Referenced by StateInfo::match().
 {
     Vec_Str tagsPresent;
     Vec_Str holder;
     Vec_Str otherTags;
     Vec_Str::const_iterator hit;
     tagsPresent = this->listIdTags();
     holder = this->listInterpTags();
     for( hit = holder.begin(); hit != holder.end(); ++hit )
     {
         tagsPresent.push_back( *hit );
     }
     holder.clear();
     otherTags = other.listIdTags();
     holder = other.listInterpTags();
     for( hit = holder.begin(); hit != holder.end(); ++hit )
     {
         otherTags.push_back( *hit );
     }
     if( !internalCompare( tagsPresent, other ).empty() ) return false;
     if( !internalCompare( otherTags, *this ).empty() ) return false;
     return true;
 }  // match
bool interpolationCompare (const TagManager & other) const
Function to compare the values of a set of ID tags to ensure the two TagManagers are describing the same type of Library with different interp tags for interpolation.
Parameters
other - TagManager to which the current TagManager will be compared. If the current TagManager does not contain all of the same ID and Interp tag names and all of the same ID tag values as other, this function will return false.
Returns
bool - True if the current TagManager contains all of the ID and Interp tag names found in other as well as the same matching ID tag values found in other. False otherwise.
References TagManager::compare(), TagManager::getIdTag(), TagManager::hasTag(), TagManager::listIdTags(), and TagManager::listInterpTags().
 {
     if( other.compare( *this ).size() != 0 ) return false;
     for( auto& tag : other.listIdTags() )
     {
         if( this->getIdTag( tag ) != other.getIdTag( tag ) ) return false;
     }
     for( auto& tag : other.listInterpTags() )
     {
         if( !this->hasTag( tag ) ) return false;
         // if(this->getInterpTag(tag)==other.getInterpTag(tag)) return false;
     }
     return true;
 }  // interpolationCompare
Vec_Str compare (const TagManager & sp_other) const
This function accepts a TagManager and uses the internalCompare function and returns a list of the tags that don't match between the provided TagManager and the current TagManager.
Parameters
sp_other Another tag manager to be compared against the current one.
Returns
A list of the tag names on the current TagManager not found on the provided TagManager.
References TagManager::internalCompare(), TagManager::listIdTags(), and TagManager::listInterpTags().
Referenced by Origen::checkImplicitTags(), and TagManager::interpolationCompare().
 {
     Vec_Str tagsPresent;
     Vec_Str holder;
     Vec_Str::const_iterator hit;
     tagsPresent = this->listIdTags();
     holder = this->listInterpTags();
     for( hit = holder.begin(); hit != holder.end(); ++hit )
     {
         tagsPresent.push_back( *hit );
     }
     return internalCompare( tagsPresent, sp_other );
 }  // compare
Vec_Str compare (Vec_Str desired) const
This function is one of the overloaded compare functions that accepts a vector of tag names. It then sends the internalCompare function that vector of strings and a dereferenced pointer to this tag manager.
Parameters
desired A list of tag names that one is looking for on the current TagManager.
Returns
A list of tag names that were in desired but not on the current TagManager.
References TagManager::internalCompare().
 {
     return internalCompare( desired, *this );
 }  // compare
Json::Value to_json () const
write to JSON
References TagManager::listIdTags(), TagManager::listIdValues(), TagManager::listInterpTags(), and TagManager::listInterpValues().
Referenced by TagManager::to_string().
 {
     Json::Value root;
     {
         Vec_Str keys = listIdTags();
         Vec_Str vals = listIdValues();
         for( size_t i = 0; i < keys.size(); ++i )
         {
             root[keys[i]] = vals[i];
         }
     }
     {
         Vec_Str keys = listInterpTags();
         Vec_Dbl vals = listInterpValues();
         for( size_t i = 0; i < keys.size(); ++i )
         {
             root[keys[i]] = vals[i];
         }
     }
     return root;
 }
std::string to_string () const
write to std::string
References TagManager::to_json().
Referenced by TagManager::toString().
 { return to_json().toStyledString(); }
long getUID () const virtual
Get serializable UID.
References TagManager::uid.
 { return TagManager::uid; }
TagManager * getCopy () const virtual
Clone method.
References TagManager::TagManager().
 { return new TagManager(); }
std::string toString () const
References TagManager::to_string().
 { return to_string(); }
Vec_Str internalCompare (Vec_Str desired, const TagManager & other) const private
Internal compare function.
Checks for missing tags on a Library's TagManager object, based on a set of desired tag names.
This private function accepts a vector of strings that are desired tag names and a full TagManager instance from a Library. The names of the tags are taken from the full TagManager instance into a vector of strings that are the tag names present. The list of the desired tags is iterated through and if no match is found in the tags present, it is added to the list of missing tags. The list of missing tags is then returned.
Parameters
desired List of desired tag names that we are hoping to find in the other library.
other TagManager from the library we are checking for the desired tags.
Returns
List of tag names that were desired but not found on the library in question.
References TagManager::listIdTags(), and TagManager::listInterpTags().
Referenced by TagManager::compare(), and TagManager::match().
 {
     Vec_Str present;
     Vec_Str missing;
     Vec_Str holder;
     Vec_Str::const_iterator pit;
     Vec_Str::const_iterator dit;
     Vec_Str::const_iterator hit;
     present = other.listIdTags();
     holder = other.listInterpTags();
     for( hit = holder.begin(); hit != holder.end(); ++hit )
     {
         present.push_back( *hit );
     }
     for( dit = desired.begin(); dit != desired.end(); ++dit )
     {
         bool found = false;
         for( pit = present.begin(); pit != present.end(); ++pit )
         {
             if( ( *dit ).compare( *pit ) == 0 )
             {
                 found = true;
                 break;
             }
         }
         if( !found ) missing.push_back( *dit );
     }
     return ( missing );
 }  // internalCompare
bool checkMaps () private
This function should check all of the DataContainer types that are not string and double and ensure that they are all empty.
Returns
bool - True if all are empty. False otherwise.
Referenced by TagManager::~TagManager().
 {
     if( !this->getNames().empty() ) return false;
     if( !this->getIntNames().empty() ) return false;
     if( !this->getFloatNames().empty() ) return false;
     if( !this->getLongNames().empty() ) return false;
     if( !this->getBoolNames().empty() ) return false;
     return true;
 }  // checkMaps
Friends And Related Function Documentation
friend class ScaleUtils::IO::Accessor< TagManager > friend
Member Data Documentation
const Standard::Serializable::UID uid = 0x11111152b5b56031 static
Serializable UID.
Referenced by Library::deserialize(), and TagManager::getUID().
The documentation for this class was generated from the following files:
Core/dc/TagManager.h
Core/dc/TagManager.cpp