ORIGEN API: MultiZoneDepleter Class Reference
MultiZoneDepleter Class Reference
#include <MultiZoneDepleter.h>
Performs one step of irradiation (potentially many substeps) for many materials, with a fixed transition matrix which resides on each material.
Public Member Functions
MultiZoneDepleter ()
Constructor.
~MultiZoneDepleter ()
Destructor.
void set_solver (SP_Solver solver)
void set_comm (Standard::Communicator *comm)
void set_materials (SP_MaterialMap mats)
const MaterialMap & materials () const
MaterialMap & materials ()
SP_MaterialMap sp_materials ()
void add_step (double)
size_t nsteps () const
void allocate_step ()
void set_dt (double)
double dt () const
void unset_constraint ()
void set_power_constraint (double, double bg_power=0)
void set_flux_constraint (double, double bg_flux=0, double bg_volume=0)
void set_substep_dtrel (const Vec_Dbl &)
void set_basis_ids (const Vec_Int &)
void set_constraint_its_max (size_t)
void set_constraint_its_tol (double)
double constraint_hist (double) const
bool has_constraint () const
Vec_Dbl scaling_factors () const
void clear ()
Clears data (same as constructor) but leaves solver and comm.
bool update (const ScaleUtils::IO::DB &data)
Updates data from dc (same end result as setters).
bool execute ()
Execute this module.
const ScaleUtils::IO::DB & status () const
Protected Member Functions
virtual void allreduce (Vec_Dbl &x) const
virtual void pre_transmute ()
virtual double global_scaling_factor (size_t s, size_t itran)
virtual void transmute (size_t s, size_t itran)
virtual void post_transmute ()
Protected Attributes
Standard::Communicator * b_comm
SP_Solver b_solver
SP_MaterialMap b_mats
ScaleUtils::IO::UP_DB b_status
bool b_has_constraint
double b_dt
double b_bg
double b_bg_volume
double b_constraint
Material::FluxParameter b_constraint_type
Vec_Dbl b_trel
Vec_Dbl b_scaling
size_t b_constraint_its_max
double b_constraint_its_tol
std::set< int > b_basis_ids
std::vector< bool > b_is_basis
Detailed Description
Performs one step of irradiation (potentially many substeps) for many materials, with a fixed transition matrix which resides on each material.
Examples:
tstMultiZoneDepleter.cpp, tstParallelDepletion.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
Constructor & Destructor Documentation
MultiZoneDepleter ()
Constructor.
References MultiZoneDepleter::clear().
     : b_comm( nullptr )
     , b_solver( nullptr )
     , b_status( new ScaleUtils::IO::DB() )
 {
     clear();  // initializes variables
 }
~MultiZoneDepleter ()
Destructor.
References MultiZoneDepleter::b_status.
 { b_status->clear(); }
Member Function Documentation
void set_solver (SP_Solver solver)
Examples:
tstMultiZoneDepleter.cpp, tstParallelDepletion.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References MultiZoneDepleter::b_solver.
Referenced by MultiZoneDepleterTester::SetUp(), and TEST().
 { b_solver = solver; }
void set_comm (Standard::Communicator * comm)
Examples:
tstMultiZoneDepleter.cpp, and tstParallelDepletion.cpp.
References MultiZoneDepleter::b_comm.
Referenced by MultiZoneDepleterTester::SetUp(), and TEST().
 {
     b_comm = comm;
 }
void set_materials (SP_MaterialMap mats)
Examples:
tstMultiZoneDepleter.cpp, tstParallelDepletion.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References MultiZoneDepleter::b_mats, and MultiZoneDepleter::b_solver.
Referenced by MultiZoneDepleterTester::SetUp(), and TEST().
 {
     b_mats = mats;
     if( b_mats == nullptr ) return;
     for( auto& id_mat : *b_mats )
     {
         if( id_mat.second->solver() == nullptr )
         {
             jDebugLine( "    associate default solver to material id="
                         << id_mat.first );
             id_mat.second->set_solver( b_solver );
         }
     }
 }
const MaterialMap & materials () const
References MultiZoneDepleter::b_mats.
 { return *b_mats; }
MaterialMap & materials ()
References MultiZoneDepleter::b_mats.
 { return *b_mats; }
SP_MaterialMap sp_materials ()
Examples:
tstMultiZoneDepleter.cpp.
References MultiZoneDepleter::b_mats.
 { return b_mats; }
void add_step (double dt)
Examples:
tstMultiZoneDepleter.cpp, tstParallelDepletion.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References MultiZoneDepleter::b_dt, MultiZoneDepleter::b_mats, and MultiZoneDepleter::dt().
Referenced by TEST().
 {
     Require( dt != 0.0 );  // adjoint could have dt<0?
     Require( b_mats != nullptr );
     for( auto& id_mat : *b_mats )
     {
         jDebugLine( "  adding step for id=" << id_mat.first );
         id_mat.second->add_step( dt );
     }
     jDebugLine( "  setting global dt=" << dt );
     b_dt = dt;
 }
size_t nsteps () const
References MultiZoneDepleter::b_mats.
 {
     size_t n = 0;
     for( auto& id_mat : *b_mats )
     {
         if( n == 0 ) n = id_mat.second->nsteps();
         Check( n == id_mat.second->nsteps() );  // all materials must have same
                                                 // number of steps
     }
     return n;
 }
void allocate_step ()
References MultiZoneDepleter::b_mats.
 {
     Require( b_mats != nullptr );
     for( auto& id_mat : *b_mats )
     {
         jDebugLine( "  allocating new step for id=" << id_mat.first );
         id_mat.second->allocate_step();
     }
 }
void set_dt (double dt)
References MultiZoneDepleter::b_dt, MultiZoneDepleter::b_mats, and MultiZoneDepleter::dt().
Referenced by MultiZoneDepleter::update().
 {
     Require( dt != 0.0 );  // adjoint could have dt<0?
     for( auto& id_mat : *b_mats )
     {
         id_mat.second->set_dt( dt );
     }
     jDebugLine( "  setting global dt=" << dt );
     b_dt = dt;
 }
double dt () const
Examples:
tstMultiZoneDepleter.cpp.
References MultiZoneDepleter::b_dt.
Referenced by MultiZoneDepleter::add_step(), and MultiZoneDepleter::set_dt().
 { return b_dt; }
void unset_constraint ()
References MultiZoneDepleter::b_bg, MultiZoneDepleter::b_bg_volume, MultiZoneDepleter::b_constraint, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_has_constraint, and Material::UNKNOWN.
Referenced by TEST(), and MultiZoneDepleter::update().
 {
     b_has_constraint = false;
     b_constraint = 0;
     b_bg = 0;
     b_bg_volume = 0;
     b_constraint_type = Material::UNKNOWN;
 }
void set_power_constraint (double power, double bg_power = 0)
Examples:
tstMultiZoneDepleter.cpp, and tstParallelDepletion.cpp.
References MultiZoneDepleter::b_bg, MultiZoneDepleter::b_bg_volume, MultiZoneDepleter::b_constraint, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_has_constraint, and Material::POWER.
Referenced by TEST(), and MultiZoneDepleter::update().
 {
     b_has_constraint = true;
     b_constraint = power;
     b_bg = bg_power;
     b_bg_volume = 0.0;
     b_constraint_type = Material::POWER;
 }
void set_flux_constraint (double flux, double bg_flux = 0, double bg_volume = 0)
References MultiZoneDepleter::b_bg, MultiZoneDepleter::b_bg_volume, MultiZoneDepleter::b_constraint, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_has_constraint, and Material::FLUX.
Referenced by MultiZoneDepleter::update().
 {
     b_has_constraint = true;
     b_constraint = flux;
     b_bg = bg_flux;
     b_bg_volume = bg_volume;
     b_constraint_type = Material::FLUX;
 }
void set_substep_dtrel (const Vec_Dbl & substep_dtrel)
Examples:
tstMultiZoneDepleter.cpp, and tstParallelDepletion.cpp.
References MultiZoneDepleter::b_trel.
Referenced by TEST(), and MultiZoneDepleter::update().
 {
     Require( substep_dtrel.size() > 0 );
     Require( ScaleSTL::approx_eq(
         1.0, std::fabs( ScaleSTL::sum( substep_dtrel ) ) ) );
     // first pass gets all the values there
     b_trel.clear();
     b_trel.resize( substep_dtrel.size() + 1, 0.0 );
     for( size_t i = 1; i < substep_dtrel.size() + 1; ++i )
     {
         b_trel[i] = b_trel[i - 1] + substep_dtrel[i - 1];
     }
     // second pass makes sure we end on 1.0 exactly
     double idt = 1.0 / ( b_trel.back() - b_trel.front() );
     for( auto& trel : b_trel ) trel *= idt;
 }
void set_basis_ids (const Vec_Int & basis_ids)
References MultiZoneDepleter::b_basis_ids.
Referenced by MultiZoneDepleter::update().
 {
     b_basis_ids.clear();
     b_basis_ids.insert( basis_ids.begin(), basis_ids.end() );
 }
void set_constraint_its_max (size_t its_max)
Examples:
tstMultiZoneDepleter.cpp.
References MultiZoneDepleter::b_constraint_its_max.
Referenced by TEST(), and MultiZoneDepleter::update().
 {
     Require( its_max > 0 );
     b_constraint_its_max = its_max;
 }
void set_constraint_its_tol (double its_tol)
Examples:
tstMultiZoneDepleter.cpp.
References MultiZoneDepleter::b_constraint_its_tol.
Referenced by MultiZoneDepleter::update().
 {
     Require( its_tol > 0 );
     b_constraint_its_tol = its_tol;
 }
double constraint_hist (double trel) const
References MultiZoneDepleter::b_constraint.
Referenced by MultiZoneDepleter::global_scaling_factor().
 {
     return b_constraint;
 }
bool has_constraint () const
References MultiZoneDepleter::b_has_constraint.
Referenced by MultiZoneDepleter::execute(), and MultiZoneDepleter::global_scaling_factor().
 { return b_has_constraint; }
Vec_Dbl scaling_factors () const
Examples:
tstMultiZoneDepleter.cpp.
References MultiZoneDepleter::b_scaling.
 { return b_scaling; }
void clear ()
Clears data (same as constructor) but leaves solver and comm.
References MultiZoneDepleter::b_basis_ids, MultiZoneDepleter::b_bg, MultiZoneDepleter::b_bg_volume, MultiZoneDepleter::b_constraint, MultiZoneDepleter::b_constraint_its_max, MultiZoneDepleter::b_constraint_its_tol, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_dt, MultiZoneDepleter::b_has_constraint, MultiZoneDepleter::b_status, MultiZoneDepleter::b_trel, and Material::FLUX.
Referenced by MultiZoneDepleter::MultiZoneDepleter().
 {
     // reset all variables
     b_has_constraint = false;
     b_dt = 86400.;
     b_bg = 0.0;
     b_bg_volume = 0.0;
     b_constraint = 0.0;
     b_constraint_type = Material::FLUX;
     b_trel = {0.0, 1.0};
     b_basis_ids = {};
     b_constraint_its_max = 1;
     b_constraint_its_tol = 1e-5;
     // clear the status object
     b_status->clear();
 }
bool update (const ScaleUtils::IO::DB & data)
Updates data from dc (same end result as setters).
Returns
bool false if errors were found–check with status().
Examples:
tstMultiZoneDepleter.cpp, tstParallelDepletion.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References MultiZoneDepleter::b_constraint, MultiZoneDepleter::b_constraint_its_max, MultiZoneDepleter::b_constraint_its_tol, MultiZoneDepleter::b_dt, MultiZoneDepleter::b_status, Material::decay_substep_dtrel(), MultiZoneDepleter::set_basis_ids(), MultiZoneDepleter::set_constraint_its_max(), MultiZoneDepleter::set_constraint_its_tol(), MultiZoneDepleter::set_dt(), MultiZoneDepleter::set_flux_constraint(), MultiZoneDepleter::set_power_constraint(), MultiZoneDepleter::set_substep_dtrel(), and MultiZoneDepleter::unset_constraint().
Referenced by TEST().
 {
     jDebugLine( "##MultiZoneDepleter::update()" );
     // clear existing status
     b_status->clear();
     // assign constraint
     bool dbp = data.get( "depleteByPower", false );
     bool dbf = data.get( "depleteByFlux", false );
     if( dbp )
     {
         double sp = data.get( "systemPower", 0.0 );
         double bp = data.get( "backgroundPower", 0.0 );
         set_power_constraint( sp, bp );
     }
     else if( dbf )
     {
         double sf = data.get( "systemFlux", 0.0 );
         double bf = data.get( "backgroundFlux", 0.0 );
         double bv = data.get( "backgroundVolume", 0.0 );
         set_flux_constraint( sf, bf, bv );
     }
     else
     {
         unset_constraint();
     }
     // resolve basis ids
     auto ids = data.get<IntegerList*>( "basisIds" );
     if( ids != nullptr ) set_basis_ids( *ids );
     // resolve substep relative time
     int ns = data.get( "numSubsteps", 0 );
     if( ns <= 0 )
     {
         set_substep_dtrel( {1.0} );
     }
     else if( b_constraint == 0.0 )
     {
         // decay with power of 3 spacing
         size_t sns = static_cast<size_t>( ns );
         set_substep_dtrel( Material::decay_substep_dtrel( sns ) );
     }
     else
     {
         // normal evenly spaced substeps
         set_substep_dtrel( Vec_Dbl( ns, 1.0 / ns ) );
     }
     // step time
     set_dt( data.get( "stepTime", b_dt ) );
     // calculation control
     set_constraint_its_max(
         data.get<int>( "constraintItsMax", b_constraint_its_max ) );
     set_constraint_its_tol(
         data.get( "constraintItsTol", b_constraint_its_tol ) );
     jDebugLine( "   leaving MultiZoneDepleter::update()" );
     return b_status->numError() == 0;
 }
bool execute ()
Execute this module.
Returns
bool true on success, false otherwise
Examples:
tstMultiZoneDepleter.cpp, tstParallelDepletion.cpp, tstSolver_cram.cpp, and tstSolver_matrex.cpp.
References MultiZoneDepleter::b_constraint_its_max, MultiZoneDepleter::b_constraint_its_tol, MultiZoneDepleter::b_scaling, MultiZoneDepleter::b_status, MultiZoneDepleter::b_trel, MultiZoneDepleter::global_scaling_factor(), MultiZoneDepleter::has_constraint(), MultiZoneDepleter::post_transmute(), MultiZoneDepleter::pre_transmute(), and MultiZoneDepleter::transmute().
Referenced by TEST().
 {
     jDebugLine( "##MultiZoneDepleter::execute()" );
     // setup for transmutation
     pre_transmute();
     // perform an initial scaling at s=0 itran=0
     b_scaling[0] = global_scaling_factor( 0, 0 );
     Check( b_constraint_its_max > 0 );
     for( size_t s = 0; s < b_trel.size() - 1; ++s )
     {
         jDebugLine( "   substep(" << s << ") with trel0=" << b_trel[s]
                                   << " --> trel1="
                                   << b_trel[s + 1]
                                   << " old scaling s0="
                                   << b_scaling[s] );
         // enter constraint iteration loop
         // if no constraints, we pop out after one iteration
         double last_scaling = b_scaling[s];
         size_t itran = 0;
         double relchange = 1.0;
         while( itran < b_constraint_its_max )
         {
             // transmute
             transmute( s, itran );
             jDebugLine( "     transmute(" << s << "," << itran
                                           << ") complete." );
             // calculate new scaling factor
             b_scaling[s + 1] = global_scaling_factor( s + 1, itran );
             jDebugLine( "       new scaling s1(" << s << "," << itran << ")="
                                                  << b_scaling[s + 1] );
             // check tolerance
             relchange = std::fabs( b_scaling[s + 1] / last_scaling - 1.0 );
             jDebugLine( "       new/old-1(" << s << "," << itran << ")/tol="
                                             << relchange
                                             << "/"
                                             << b_constraint_its_tol );
             // final check
             if( relchange <= b_constraint_its_tol ) break;
             // prepare for next iteration
             last_scaling = b_scaling[s + 1];
             ++itran;
         }
         Check( !has_constraint() ? itran == 0 : itran <= b_constraint_its_max );
         Check( !has_constraint() ? relchange == 0.0 : true );
         jDebugLine( "   substep(" << s << ") complete with " << itran + 1
                                   << " transmutes." );
     }
     // wrapup operations
     post_transmute();
     return b_status->numError() == 0;
 }  // execute
const ScaleUtils::IO::DB & status () const
Examples:
tstMultiZoneDepleter.cpp.
References MultiZoneDepleter::allreduce(), MultiZoneDepleter::b_bg, MultiZoneDepleter::b_bg_volume, MultiZoneDepleter::b_constraint, MultiZoneDepleter::b_constraint_its_max, MultiZoneDepleter::b_constraint_its_tol, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_dt, MultiZoneDepleter::b_has_constraint, MultiZoneDepleter::b_mats, MultiZoneDepleter::b_status, MultiZoneDepleter::b_trel, and Material::POWER.
Referenced by TEST().
 {
     // add some stuff
     b_status->set( "numSubsteps", static_cast<int>( b_trel.size() - 1 ) );
     b_status->set( "hasConstraint", b_has_constraint );
     if( b_has_constraint )
     {
         b_status->set(
             "constraintType",
             b_constraint_type == Material::POWER ? "POWER" : "FLUX" );
         b_status->set( "constraintValue", b_constraint );
         b_status->set( "backgroundValue", b_bg );
         b_status->set( "backgroundVolume", b_bg_volume );
     }
     b_status->set( "stepTime", b_dt );
     // calculation control
     b_status->set( "constraintItsMax", (int)b_constraint_its_max );
     b_status->set( "constraintItsTol", b_constraint_its_tol );
     //
     // Update the status data container with powers and fluxes
     // for all materials in the material map.
     //
     ScaleUtils::IO::DB powers =
         *b_status->acquire<DataContainer*>( "localMaterialPowers" );
     ScaleUtils::IO::DB fluxes =
         *b_status->acquire<DataContainer*>( "localMaterialFluxes" );
     ScaleUtils::IO::DB volumes =
         *b_status->acquire<DataContainer*>( "localMaterialVolumes" );
     double sum_power = 0;
     double sum_volume = 0;
     double sum_flux_volume = 0;
     for( auto it = b_mats->begin(); it != b_mats->end(); ++it )
     {
         SP_Material mat = it->second;
         double power = mat->power();
         double volume = mat->cold_volume();  //!\todo: replace with real volume
         double flux = mat->flux();
         sum_power += power;
         sum_flux_volume += flux * volume;
         sum_volume += volume;
         powers.set( mat->name(), power );
         fluxes.set( mat->name(), flux );
         volumes.set( mat->name(), volume );
     }
     //
     // Local totals
     //
     double avg_flux;
     avg_flux = sum_flux_volume / sum_volume;
     b_status->set( "localMaterialAverageFlux", avg_flux );
     b_status->set( "localMaterialTotalVolume", sum_volume );
     b_status->set( "localMaterialTotalPower", sum_power );
     //
     // Global totals
     //
     Vec_Dbl sums( {sum_power, sum_flux_volume, sum_volume} );
     allreduce( sums );
     avg_flux = sums[1] / sums[2];
     b_status->set( "globalMaterialAverageFlux", avg_flux );
     b_status->set( "globalMaterialTotalVolume", sums[2] );
     b_status->set( "globalMaterialTotalPower", sums[0] );
     return *b_status;
 }
void allreduce (Vec_Dbl & x) const protected virtual
References MultiZoneDepleter::b_comm.
Referenced by MultiZoneDepleter::global_scaling_factor(), and MultiZoneDepleter::status().
 {
     // null-op if comm is null
     if( b_comm == nullptr ) return;
     // actually globally communicate
     std::vector<double> vecx;
     for( auto& e : x )
     {
         b_comm->allgather( e, vecx );
         e = sum( vecx );
     }
 }
void pre_transmute () protected virtual
References MultiZoneDepleter::b_basis_ids, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_dt, MultiZoneDepleter::b_is_basis, MultiZoneDepleter::b_mats, MultiZoneDepleter::b_scaling, MultiZoneDepleter::b_trel, Material::FLUX, and Material::POWER.
Referenced by MultiZoneDepleter::execute().
 {
     // num substeps
     size_t ns = b_trel.size() - 1;
     // reset basis ids
     // default is true (all materials in basis) if basis_ids are empty
     // otherwise let basis_ids dictate and therefore default is false
     bool def = true;
     if( b_basis_ids.size() > 0 ) def = false;
     b_is_basis.clear();
     b_is_basis.resize( b_mats->size(), def );
     // reset scale
     b_scaling.clear();
     b_scaling.resize( ns + 1, 1.0 );
     // make sure all the basis ids get distributed
     Remember( std::set<int> basis_ids( b_basis_ids ) );
     size_t i = 0;
     for( auto it = b_mats->begin(); it != b_mats->end(); ++it )
     {
         // base variables
         SP_Material mat = it->second;
         int id = it->first;
         jDebugLine( "   checking material i=" << i << " name=" << mat->name()
                                               << " id="
                                               << id );
         // verify sizes
         Check( mat->good() );
         // all materials must be updated in lock step
         jDebugLine(
             "   checking material dt=" << mat->dt() << " global dt=" << b_dt );
         Require( ScaleSTL::approx_eq( mat->dt(), b_dt ) );
         // basis
         auto idf = b_basis_ids.find( id );
         if( idf != b_basis_ids.end() )
         {
             Remember( basis_ids.erase( idf ) );
             b_is_basis[i] = true;
         }
         // initialize one of the history variables for each material by handling
         // 4 combinations of global constraints and what was provided on
         // material
         double param = mat->param_hist( 0.0 );
         // SET T=0 POWER HISTORY
         if( b_constraint_type == Material::POWER )
         {
             if( mat->flux_parameter() == Material::POWER )
             {
                 mat->set_power_hist( 0.0, param );
             }
             else if( mat->flux_parameter() == Material::FLUX )
             {
                 mat->set_power_hist( 0.0, param * mat->power_factor_bos() );
             }
         }
         // SET T=0 FLUX HISTORY
         else if( b_constraint_type == Material::FLUX )
         {
             if( mat->flux_parameter() == Material::POWER )
             {
                 mat->set_flux_hist( 0.0, param / mat->power_factor_bos() );
             }
             else if( mat->flux_parameter() == Material::FLUX )
             {
                 mat->set_flux_hist( 0.0, param );
             }
         }
         // increment
         ++i;
     }
     Ensure( basis_ids.empty() );
 }
double global_scaling_factor (size_t s, size_t itran) protected virtual
References MultiZoneDepleter::allreduce(), MultiZoneDepleter::b_bg, MultiZoneDepleter::b_bg_volume, MultiZoneDepleter::b_constraint_type, MultiZoneDepleter::b_is_basis, MultiZoneDepleter::b_mats, MultiZoneDepleter::b_trel, MultiZoneDepleter::constraint_hist(), Material::FLUX, MultiZoneDepleter::has_constraint(), and Material::POWER.
Referenced by MultiZoneDepleter::execute().
 {
     jDebugLine( "##MultiZoneDepleter::global_scaling_factor(" << s << ","
                                                               << itran
                                                               << ")" );
     Require( s < b_trel.size() );
     Require( b_mats->size() == b_is_basis.size() );
     // choose beginning or end-of-step for constraint relative time
     double trel = b_trel[s];
     double global_constraint = constraint_hist( trel );
     double global_sum = 1.0;
     // handle power constraint
     if( global_constraint == 0.0 || !has_constraint() )
     {
         global_sum = 1.0;
     }
     else if( b_constraint_type == Material::POWER )
     {
         double cmat = 0.0;  // local value for constraint
         size_t i = 0;
         for( auto it = b_mats->begin(); it != b_mats->end(); ++it )
         {
             SP_Material mat = it->second;
             if( mat->is_decay() )
             {
                 ++i;
                 continue;
             }
             if( b_is_basis[i] )
             {
                 double ph = mat->power_hist( trel );
                 cmat += ph;
             }
             ++i;
         }
         double ctot = cmat + b_bg;
         // global communication
         Vec_Dbl cx( {ctot} );
         allreduce( cx );
         global_sum = cx[0];
     }
     // handle flux constraint
     else if( b_constraint_type == Material::FLUX )
     {
         double cmat = 0.0;
         double vmat = 0.0;
         size_t i = 0;
         for( auto it = b_mats->begin(); it != b_mats->end(); ++it )
         {
             SP_Material mat = it->second;
             if( mat->is_decay() )
             {
                 ++i;
                 continue;
             }
             if( b_is_basis[i] )
             {
                 vmat += mat->volume_hist( trel );
                 cmat += mat->flux_hist( trel );
             }
             ++i;
         }
         // constraint / ( cmat*volm/(volm+volbg) + cbg*volbg/(volm+volbg) )
         double vtot = b_bg_volume + vmat;
         double ctot = cmat * vmat + b_bg * b_bg_volume;
         // global communication
         Vec_Dbl cx( {ctot, vtot} );
         allreduce( cx );
         // volume should be >0
         Check( cx[1] > 0.0 );
         global_sum = cx[0] / cx[1];
     }
     double scale = 1.0;
     if( global_constraint > 0.0 )
     {
         Check( global_sum > 0.0 );
         scale = global_constraint / global_sum;
     }
     return scale;
 }
void transmute (size_t s, size_t itran) protected virtual
References MultiZoneDepleter::b_mats, MultiZoneDepleter::b_scaling, and MultiZoneDepleter::b_trel.
Referenced by MultiZoneDepleter::execute().
 {
     jDebugLine( "##MultiZoneDepleter::transmute(" << s << "," << itran << ")" );
     Require( s < b_trel.size() - 1 );
     // get relative times on this substep
     double trel0 = b_trel[s];
     double trel1 = b_trel[s + 1];
     double z0 = b_scaling[s];
     double z1 = itran == 0 ? b_scaling[s] : b_scaling[s + 1];
     jDebugLine( "     global scaling z0=" << z0 << " z1=" << z1 );
     size_t i = 0;
     for( auto it = b_mats->begin(); it != b_mats->end(); ++it )
     {
         int id = it->first;
         SP_Material mat = it->second;
         Check( id == mat->id() );
         jDebugLine( "       transmuting material i=" << i << " name="
                                                      << mat->name()
                                                      << " id="
                                                      << id );
         double flux, power;
         mat->solve_inplace( itran, trel0, trel1, z0, z1, &flux, &power );
         jDebugLine(
             "         point fluxes[-]: boss(" << trel0 << ")="
                                               << mat->flux_hist( trel0 )
                                               << " eoss("
                                               << trel1
                                               << ")="
                                               << mat->flux_hist( trel1 ) );
         jDebugLine(
             "         point powers[-]: boss(" << trel0 << ")="
                                               << mat->power_hist( trel0 )
                                               << " eoss("
                                               << trel1
                                               << ")="
                                               << mat->power_hist( trel1 ) );
         jDebugLine( "         substep-average scaled values: flux[n/cm^2s]="
                     << flux
                     << " power[W]="
                     << power );
         ++i;
     }
 }
void post_transmute () protected virtual
References MultiZoneDepleter::b_mats, and MultiZoneDepleter::b_scaling.
Referenced by MultiZoneDepleter::execute().
 {
     size_t i = 0;
     for( auto it = b_mats->begin(); it != b_mats->end(); ++it )
     {
         SP_Material mat = it->second;
         mat->record_average_flux( b_scaling );
         mat->record_average_power( b_scaling );
         jDebugLine( "     recording material=" << mat->id() << " flux="
                                                << mat->flux() );
         jDebugLine( "     recording material=" << mat->id() << " power="
                                                << mat->power() );
         ++i;
     }
 }
Member Data Documentation
Standard::Communicator* b_comm protected
Referenced by MultiZoneDepleter::allreduce(), and MultiZoneDepleter::set_comm().
SP_Solver b_solver protected
Referenced by MultiZoneDepleter::set_materials(), and MultiZoneDepleter::set_solver().
SP_MaterialMap b_mats protected
Referenced by MultiZoneDepleter::add_step(), MultiZoneDepleter::allocate_step(), MultiZoneDepleter::global_scaling_factor(), MultiZoneDepleter::materials(), MultiZoneDepleter::nsteps(), MultiZoneDepleter::post_transmute(), MultiZoneDepleter::pre_transmute(), MultiZoneDepleter::set_dt(), MultiZoneDepleter::set_materials(), MultiZoneDepleter::sp_materials(), MultiZoneDepleter::status(), and MultiZoneDepleter::transmute().
ScaleUtils::IO::UP_DB b_status protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::execute(), MultiZoneDepleter::status(), MultiZoneDepleter::update(), and MultiZoneDepleter::~MultiZoneDepleter().
bool b_has_constraint protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::has_constraint(), MultiZoneDepleter::set_flux_constraint(), MultiZoneDepleter::set_power_constraint(), MultiZoneDepleter::status(), and MultiZoneDepleter::unset_constraint().
double b_dt protected
Referenced by MultiZoneDepleter::add_step(), MultiZoneDepleter::clear(), MultiZoneDepleter::dt(), MultiZoneDepleter::pre_transmute(), MultiZoneDepleter::set_dt(), MultiZoneDepleter::status(), and MultiZoneDepleter::update().
double b_bg protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::global_scaling_factor(), MultiZoneDepleter::set_flux_constraint(), MultiZoneDepleter::set_power_constraint(), MultiZoneDepleter::status(), and MultiZoneDepleter::unset_constraint().
double b_bg_volume protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::global_scaling_factor(), MultiZoneDepleter::set_flux_constraint(), MultiZoneDepleter::set_power_constraint(), MultiZoneDepleter::status(), and MultiZoneDepleter::unset_constraint().
double b_constraint protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::constraint_hist(), MultiZoneDepleter::set_flux_constraint(), MultiZoneDepleter::set_power_constraint(), MultiZoneDepleter::status(), MultiZoneDepleter::unset_constraint(), and MultiZoneDepleter::update().
Material::FluxParameter b_constraint_type protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::global_scaling_factor(), MultiZoneDepleter::pre_transmute(), MultiZoneDepleter::set_flux_constraint(), MultiZoneDepleter::set_power_constraint(), MultiZoneDepleter::status(), and MultiZoneDepleter::unset_constraint().
Vec_Dbl b_trel protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::execute(), MultiZoneDepleter::global_scaling_factor(), MultiZoneDepleter::pre_transmute(), MultiZoneDepleter::set_substep_dtrel(), MultiZoneDepleter::status(), and MultiZoneDepleter::transmute().
Vec_Dbl b_scaling protected
Referenced by MultiZoneDepleter::execute(), MultiZoneDepleter::post_transmute(), MultiZoneDepleter::pre_transmute(), MultiZoneDepleter::scaling_factors(), and MultiZoneDepleter::transmute().
size_t b_constraint_its_max protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::execute(), MultiZoneDepleter::set_constraint_its_max(), MultiZoneDepleter::status(), and MultiZoneDepleter::update().
double b_constraint_its_tol protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::execute(), MultiZoneDepleter::set_constraint_its_tol(), MultiZoneDepleter::status(), and MultiZoneDepleter::update().
std::set<int> b_basis_ids protected
Referenced by MultiZoneDepleter::clear(), MultiZoneDepleter::pre_transmute(), and MultiZoneDepleter::set_basis_ids().
std::vector<bool> b_is_basis protected
Referenced by MultiZoneDepleter::global_scaling_factor(), and MultiZoneDepleter::pre_transmute().
The documentation for this class was generated from the following files:
Core/xf/MultiZoneDepleter.h
Core/xf/MultiZoneDepleter.cpp