ORIGEN API: Solver/radau5/src/radaua.f90 File Reference
radaua.f90 File Reference
The 3rd party RADAU5 solver – the additional routines.
Functions/Subroutines
subroutine decomr (N, FJAC, LDJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, E1, LDE1, IP1, IER, IJOB, CALHES, IPHES)
subroutine decomc (N, FJAC, LDJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, ALPHN, BETAN, E2R, E2I, LDE1, IP2, IER, IJOB)
subroutine slvrar (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, E1, LDE1, Z1, F1, IP1, IPHES, IER, IJOB)
subroutine slvrai (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, ALPHN, BETAN, E2R, E2I, LDE1, Z2, Z3, F2, F3, CONT, IP2, IPHES, IER, IJOB)
subroutine slvrad (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, ALPHN, BETAN, E1, E2R, E2I, LDE1, Z1, Z2, Z3, F1, F2, F3, CONT, IP1, IP2, IPHES, IER, IJOB)
subroutine estrad (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, H, DD1, DD2, DD3, FCN, NFCN, Y0, Y, IJOB, X, M1, M2, NM1, E1, LDE1, Z1, Z2, Z3, CONT, F1, F2, IP1, IPHES, SCAL, ERR, FIRST, REJECT, FAC1, RPAR, IPAR)
subroutine estrav (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, H, DD, FCN, NFCN, Y0, Y, IJOB, X, M1, M2, NM1, NS, NNS, E1, LDE1, ZZ, CONT, FF, IP1, IPHES, SCAL, ERR, FIRST, REJECT, FAC1, RPAR, IPAR)
subroutine slvrod (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, E, LDE, IP, DY, AK, FX, YNEW, HD, IJOB, STAGE1)
subroutine slvseu (N, FJAC, LDJAC, MLJAC, MUJAC, FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, E, LDE, IP, IPHES, DEL, IJOB)
subroutine dec (N, NDIM, A, IP, IER)
subroutine sol (N, NDIM, A, B, IP)
subroutine dech (N, NDIM, A, LB, IP, IER)
subroutine solh (N, NDIM, A, LB, B, IP)
subroutine decc (N, NDIM, AR, AI, IP, IER)
subroutine solc (N, NDIM, AR, AI, BR, BI, IP)
subroutine dechc (N, NDIM, AR, AI, LB, IP, IER)
subroutine solhc (N, NDIM, AR, AI, LB, BR, BI, IP)
subroutine decb (N, NDIM, A, ML, MU, IP, IER)
subroutine solb (N, NDIM, A, ML, MU, B, IP)
subroutine decbc (N, NDIM, AR, AI, ML, MU, IP, IER)
subroutine solbc (N, NDIM, AR, AI, ML, MU, BR, BI, IP)
subroutine elmhes (nm, n, low, igh, a, int)
Detailed Description
The 3rd party RADAU5 solver – the additional routines.
Function/Subroutine Documentation
subroutine decomr (N, dimension(ldjac,n) FJAC, LDJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, dimension(lde1,nm1) E1, LDE1, dimension(nm1) IP1, IER, IJOB, logical CALHES, dimension(n) IPHES)
References dec(), decb(), dech(), and elmhes().
Referenced by radcor().
subroutine decomc (N, dimension(ldjac,n) FJAC, LDJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, ALPHN, BETAN, dimension(lde1,nm1) E2R, dimension(lde1,nm1) E2I, LDE1, dimension(nm1) IP2, IER, IJOB)
References decbc(), decc(), and dechc().
Referenced by radcor().
subroutine slvrar (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, dimension(lde1,nm1) E1, LDE1, dimension(n) Z1, dimension(n) F1, dimension(nm1) IP1, dimension(n) IPHES, IER, IJOB)
References sol(), solb(), and solh().
subroutine slvrai (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, ALPHN, BETAN, dimension(lde1,nm1) E2R, dimension(lde1,nm1) E2I, LDE1, dimension(n) Z2, dimension(n) Z3, dimension(n) F2, dimension(n) F3, CONT, dimension(nm1) IP2, dimension(n) IPHES, IER, IJOB)
References solbc(), solc(), and solhc().
subroutine slvrad (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, ALPHN, BETAN, dimension(lde1,nm1) E1, dimension(lde1,nm1) E2R, dimension(lde1,nm1) E2I, LDE1, dimension(n) Z1, dimension(n) Z2, dimension(n) Z3, dimension(n) F1, dimension(n) F2, dimension(n) F3, dimension(4*n) CONT, dimension(nm1) IP1, dimension(nm1) IP2, dimension(n) IPHES, IER, IJOB)
References sol(), solb(), solbc(), solc(), solh(), and solhc().
Referenced by radcor().
subroutine estrad (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, H, DD1, DD2, DD3, FCN, NFCN, dimension(n) Y0, dimension(n) Y, IJOB, X, M1, M2, NM1, dimension(lde1,nm1) E1, LDE1, dimension(n) Z1, dimension(n) Z2, dimension(n) Z3, dimension(n) CONT, dimension(n) F1, dimension(n) F2, dimension(nm1) IP1, dimension(n) IPHES, dimension(n) SCAL, ERR, logical FIRST, logical REJECT, FAC1, dimension(1) RPAR, dimension(1) IPAR)
References sol(), solb(), and solh().
Referenced by radcor().
subroutine estrav (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, H, dimension(ns) DD, FCN, NFCN, dimension(n) Y0, dimension(n) Y, IJOB, X, M1, M2, NM1, NS, NNS, dimension(lde1,nm1) E1, LDE1, dimension(nns) ZZ, dimension(n) CONT, dimension(nns) FF, dimension(nm1) IP1, dimension(n) IPHES, dimension(n) SCAL, ERR, logical FIRST, logical REJECT, FAC1, dimension(1) RPAR, dimension(1) IPAR)
References sol(), solb(), and solh().
subroutine slvrod (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, dimension(lde,nm1) E, LDE, dimension(nm1) IP, dimension(n) DY, dimension(n) AK, dimension(n) FX, dimension(n) YNEW, HD, IJOB, logical STAGE1)
References sol(), and solb().
subroutine slvseu (N, dimension(ldjac,n) FJAC, LDJAC, MLJAC, MUJAC, dimension(ldmas,nm1) FMAS, LDMAS, MLMAS, MUMAS, M1, M2, NM1, FAC1, dimension(lde,nm1) E, LDE, dimension(nm1) IP, dimension(n) IPHES, dimension(n) DEL, IJOB)
References sol(), solb(), and solh().
subroutine dec (integer N, integer NDIM, double precision, dimension(ndim,n) A, integer, dimension(n) IP, integer IER)
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by decomr().
subroutine sol (integer N, integer NDIM, double precision, dimension(ndim,n) A, double precision, dimension(n) B, integer, dimension(n) IP)
Referenced by estrad(), estrav(), slvrad(), slvrar(), slvrod(), and slvseu().
subroutine dech (integer N, integer NDIM, double precision, dimension(ndim,n) A, integer LB, integer, dimension(n) IP, integer IER)
Referenced by decomr().
subroutine solh (integer N, integer NDIM, double precision, dimension(ndim,n) A, integer LB, double precision, dimension(n) B, integer, dimension(n) IP)
Referenced by estrad(), estrav(), slvrad(), slvrar(), and slvseu().
subroutine decc (integer N, integer NDIM, dimension(ndim,n) AR, dimension(ndim,n) AI, integer, dimension(n) IP, integer IER)
Referenced by decomc().
subroutine solc (integer N, integer NDIM, dimension(ndim,n) AR, dimension(ndim,n) AI, dimension(n) BR, dimension(n) BI, integer, dimension(n) IP)
Referenced by slvrad(), and slvrai().
subroutine dechc (integer N, integer NDIM, dimension(ndim,n) AR, dimension(ndim,n) AI, LB, integer, dimension(n) IP, integer IER)
Referenced by decomc().
subroutine solhc (integer N, integer NDIM, dimension(ndim,n) AR, dimension(ndim,n) AI, LB, dimension(n) BR, dimension(n) BI, integer, dimension(n) IP)
Referenced by slvrad(), and slvrai().
subroutine decb (N, NDIM, real*8, dimension(ndim,n) A, ML, MU, dimension(n) IP, IER)
Referenced by decomr().
subroutine solb (N, NDIM, real*8, dimension(ndim,n) A, ML, MU, real*8, dimension(n) B, dimension(n) IP)
Referenced by estrad(), estrav(), slvrad(), slvrar(), slvrod(), and slvseu().
subroutine decbc (N, NDIM, dimension(ndim,n) AR, dimension(ndim,n) AI, ML, MU, dimension(n) IP, IER)
Referenced by decomc().
subroutine solbc (N, NDIM, dimension(ndim,n) AR, dimension(ndim,n) AI, ML, MU, dimension(n) BR, dimension(n) BI, dimension(n) IP)
Referenced by slvrad(), and slvrai().
subroutine elmhes (integer nm, integer n, integer low, integer igh, real*8, dimension(nm,n) a, integer, dimension(igh) int)
Referenced by decomr().