ORIGEN API: NuclideGroupFilter Class Reference
NuclideGroupFilter Class Reference
#include <NuclideGroupFilter.h>
Public Member Functions
NuclideGroupFilter ()
NuclideGroupFilter (int target_id)
bool filter (int sizzzaaa) const
Static Public Member Functions
static bool filter (int sizzzaaa, void *obji)
Public Attributes
std::set< int > allow_s
std::set< int > allow_i
std::set< int > allow_z
std::set< int > allow_a
int min_z
Constructor & Destructor Documentation
NuclideGroupFilter () inline
 : min_z( 0 ) {}
NuclideGroupFilter (int target_id) inline
                                         : min_z( 0 )
     {
         if( target_id > 0 )
         {
             int s, i, z, a;
             ScaleData::Utils::split_pizzzaaa( target_id, s, i, z, a );
             if( s != 0 ) allow_s.insert( s );
             if( s > 0 ) allow_i.insert( i );
             if( z != 0 ) allow_z.insert( z );
             if( a != 0 ) allow_a.insert( a );
         }
     }
Member Function Documentation
bool filter (int sizzzaaa) const inline
Referenced by NuclideGroupFilter::filter(), Origen::graphvizLibrary(), Origen::tabulateNuclideInfo(), Origen::tabulateNuclideLabel(), and Origen::tabulateTransitionCoeff().
     {
         int s, i, z, a;
         ScaleData::Utils::split_pizzzaaa( sizzzaaa, s, i, z, a );
         bool keep_this_s = allow_s.empty() || allow_s.count( s );
         bool keep_this_i = allow_i.empty() || allow_i.count( i );
         bool keep_this_z =
             ( allow_z.empty() || allow_z.count( z ) ) && z >= min_z;
         bool keep_this_a = allow_a.empty() || allow_a.count( a );
         bool keep_this =
             keep_this_s && keep_this_i && keep_this_z && keep_this_a;
         return !keep_this;
     }
static bool filter (int sizzzaaa, void * obji) inline static
References NuclideGroupFilter::filter().
     {
         NuclideGroupFilter *obj = static_cast<NuclideGroupFilter *>( obji );
         return obj->filter( sizzzaaa );
     }
Member Data Documentation
std::set<int> allow_s
std::set<int> allow_i
std::set<int> allow_z
std::set<int> allow_a
int min_z
The documentation for this class was generated from the following file:
Core/dc/NuclideGroupFilter.h