ORIGEN API: Library Class Reference
Library Class Reference
#include <Library.h>
Public Types
typedef std::shared_ptr< Library > SP
typedef std::shared_ptr< const Library > SCP
typedef bool(* InterpFunction) (const std::vector< float > &, float, std::vector< float > *)
typedef std::vector< SP_TransitionCoeff > Vec_SP_TransitionCoeff
typedef std::vector< SCP_TransitionCoeff > Vec_SCP_TransitionCoeff
typedef std::shared_ptr< Vec_SP_TransitionCoeff > SP_Vec_SP_TransitionCoeff
typedef std::shared_ptr< const Vec_SP_TransitionCoeff > SCP_Vec_SCP_TransitionCoeff
Public Member Functions
Library ()
std::string to_string () const
Scale::Json::Value to_json () const
bool operator== (const Library &a) const
std::string print_compare (const Library &a) const
const LibraryHeader & definition () const
return a const reference to definition
SCP_LibraryHeader scp_definition () const
return a shared (read-only) definition pointer
bool has_definition () const
return whether the class has a non-null definition
void get_definition (LibraryHeader &) const
populate an existing LibraryHeader with a copy of definition
void set_definition (const LibraryHeader &)
set the definition (copy operation)
void getptr_definition (const LibraryHeader *&) const
retrieve pointer (read-only) to definition
void manageptr_definition (LibraryHeader *&)
set the definition (ownership transfer)
const TagManager & tag_manager () const
return a const reference to tag_manager
SCP_TagManager scp_tag_manager () const
return a shared (read-only) tag_manager pointer
bool has_tag_manager () const
return whether the class has a non-null tag_manager
void get_tag_manager (TagManager &) const
populate an existing TagManager with a copy of tag_manager
void set_tag_manager (const TagManager &)
set the tag_manager (copy operation)
void getptr_tag_manager (const TagManager *&) const
retrieve pointer (read-only) to tag_manager
void manageptr_tag_manager (TagManager *&)
set the tag_manager (ownership transfer)
const DecayData & decay_data () const
return a const reference to decay_data
SCP_DecayData scp_decay_data () const
return a shared (read-only) decay_data pointer
bool has_decay_data () const
return whether the class has a non-null decay_data
void get_decay_data (DecayData &) const
populate an existing DecayData with a copy of decay_data
void set_decay_data (const DecayData &)
set the decay_data (copy operation)
void getptr_decay_data (const DecayData *&) const
retrieve pointer (read-only) to decay_data
void manageptr_decay_data (DecayData *&)
set the decay_data (ownership transfer)
const TransitionStructure & transition_structure () const
return a const reference to transition_structure
SCP_TransitionStructure scp_transition_structure () const
return a shared (read-only) transition_structure pointer
bool has_transition_structure () const
return whether the class has a non-null transition_structure
void get_transition_structure (TransitionStructure &) const
populate an existing TransitionStructure with a copy of transition_structure
void set_transition_structure (const TransitionStructure &)
set the transition_structure (copy operation)
void getptr_transition_structure (const TransitionStructure *&) const
retrieve pointer (read-only) to transition_structure
void manageptr_transition_structure (TransitionStructure *&)
set the transition_structure (ownership transfer)
bool has_transition_coeff () const
has a non-null transition_coeff vector
size_t transition_coeff_size () const
size of transition_coeff vector
const TransitionCoeff & transition_coeff_at (size_t) const
return a const element for read-only access
SCP_TransitionCoeff scp_transition_coeff_at (size_t) const
return a const std::shared_ptr for read-only access
bool has_transition_coeff_at (size_t) const
has a non-null element of transition_coeff vector
void getptr_transition_coeff_at (const TransitionCoeff *&, size_t) const
get a read-only pointer by index
void resize_transition_coeff (size_t)
resize the vector
void get_transition_coeff_at (TransitionCoeff &, size_t) const
get a copy of the element in-place
void set_transition_coeff_at (const TransitionCoeff &, size_t)
set a new element by index
void add_transition_coeff (const TransitionCoeff &)
add a new element to the end
void delete_transition_coeff_at (size_t)
delete an element
void manageptr_transition_coeff_at (TransitionCoeff *&, size_t)
manage an existing pointer in this class
TransitionMatrixP * newptr_transition_matrix_at (size_t) const
TransitionMatrixP::SP newsp_transition_matrix_at (size_t) const
void add_transition_matrix (const TransitionMatrixP &)
size_t total_nuclides () const
SP clone () const
virtual int serialize (Standard::AbstractStream *stream) const
virtual int deserialize (Standard::AbstractStream *stream)
virtual unsigned long getSerializedSize () const
Obtain the size in bytes of this object when serialized This size does not contain the uid b_definition component size which each Standard::Serializable object MUST contain in its serialized definition.
virtual Standard::Serializable * getCopy () const
virtual Standard::Serializable::UID getUID () const
Obtain the universal version identifier the uid should be unique for all Standard::Serializable objects such that an object factory can retrieve prototypes of the desired Standard::Serializable object and inflate the serial object into a manageable object.
virtual std::string toString () const
SP interpolate (std::vector< float > newBurnups)
Return a new Library interpolated to the provided burnup grid.
SP interpolate_Interp1D (std::vector< double > newBurnups)
void regrid (std::vector< float > newBurnups)
void regrid_Interp1D (std::vector< double > newBurnups)
void set_interpolator (InterpFunction)
Static Public Attributes
static const Standard::Serializable::UID uid = 0x99359452b5b56031
Protected Member Functions
void canonicalize_definition ()
void canonicalize_tag_manager ()
void canonicalize_decay_data ()
void canonicalize_transition_structure ()
void canonicalize_transition_coeff_at (size_t)
void populate_transition_matrix (TransitionMatrixP *, size_t) const
void populate_transition_matrix_reaction (TransitionMatrixP *, size_t) const
Protected Attributes
SP_LibraryHeader b_definition
SP_TagManager b_tag_manager
SP_DecayData b_decay_data
SP_TransitionStructure b_transition_structure
SP_Vec_SP_TransitionCoeff b_transition_coeff
InterpFunction b_interp_func
Function pointer to interpolator function to use.
Detailed Description
Examples:
tstGridView.cpp, tstinterp.cpp, tstKernelMatrexC.cpp, tstKernelRadau5C.cpp, tstLibrary.cpp, tstLibraryIO.cpp, tstMaterial.cpp, tstMaterialBuffer.cpp, tstNuclideSet.cpp, tstSolver_cram.cpp, tstSolver_matrex.cpp, tstTransitionMatrixP.cpp, tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<Library> SP
typedef std::shared_ptr<const Library> SCP
typedef bool(* InterpFunction) (const std::vector< float > &, float, std::vector< float > *)
Examples:
tstLibrary.cpp.
typedef std::vector<SP_TransitionCoeff> Vec_SP_TransitionCoeff
typedef std::vector<SCP_TransitionCoeff> Vec_SCP_TransitionCoeff
typedef std::shared_ptr<Vec_SP_TransitionCoeff> SP_Vec_SP_TransitionCoeff
typedef std::shared_ptr<const Vec_SP_TransitionCoeff> SCP_Vec_SCP_TransitionCoeff
Constructor & Destructor Documentation
Library ()
Referenced by Library::getCopy(), Library::interpolate(), and Library::interpolate_Interp1D().
     : b_definition( new LibraryHeader() )
     , b_tag_manager( new TagManager() )
     , b_decay_data( new DecayData() )
     , b_transition_structure( new TransitionStructure() )
     , b_transition_coeff( new Vec_SP_TransitionCoeff() )
     , b_interp_func(
           &(ScaleUtils::Math::interpwts_lin<std::vector<float>, float>))
 {
 }
Member Function Documentation
std::string to_string () const
Examples:
tstLibraryIO.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
References Library::to_json().
Referenced by TEST_F(), and Library::toString().
 { return to_json().toStyledString(); }
Json::Value to_json () const
Examples:
tstLibrary.cpp.
References Library::b_decay_data, Library::b_definition, Library::b_transition_coeff, Library::b_transition_structure, and Library::has_transition_coeff().
Referenced by TEST_F(), Library::to_string(), and Origen::view().
 {
     Json::Value root;
     root["definition"] = b_definition->to_json();
     root["decay_data"] = b_decay_data->to_json();
     root["transition_structure"] = b_transition_structure->to_json();
     root["transition_coeff"] = Json::Value( Json::arrayValue );
     if( !has_transition_coeff() ) return root;
     char buf[40];
     for( size_t index = 0; index < b_transition_coeff->size(); ++index )
     {
         root["transition_coeff"][(int)index] =
             ( *b_transition_coeff )[index]->to_json();
         // add comments to show the start and end of the large reaction set
         // blocks
         sprintf( buf, "/* %s %d */", "begin reaction set ", (int)index );
         root["transition_coeff"][(int)index].setComment( buf,
                                                          Json::commentBefore );
         sprintf( buf, "/* %s %d */", "end reaction set ", (int)index );
         root["transition_coeff"][(int)index].setComment( buf,
                                                          Json::commentAfter );
     }
     return root;
 }
bool operator== (const Library & a) const
References Library::b_decay_data, Library::b_definition, Library::b_tag_manager, Library::b_transition_coeff, Library::b_transition_structure, Library::decay_data(), Library::definition(), Library::tag_manager(), Library::transition_coeff_size(), and Library::transition_structure().
 {
     // compare objects
     ORIGEN_COMPARE_SP( definition, b_definition, a.b_definition );
     ORIGEN_COMPARE_SP( tag_manager, b_tag_manager, a.b_tag_manager );
     ORIGEN_COMPARE_SP( decay_data, b_decay_data, a.b_decay_data );
     ORIGEN_COMPARE_SP( transition_structure,
                        b_transition_structure,
                        a.b_transition_structure );
     // check that either both lists are nullptr or both exist
     ORIGEN_CHECK_SP(
         transition_coeff, b_transition_coeff, a.b_transition_coeff );
     // compare elements in list
     ORIGEN_COMPARE_SCALAR( transition_coeff_size,
                            b_transition_coeff->size(),
                            a.b_transition_coeff->size() );
     for( size_t i = 0; i < b_transition_coeff->size(); ++i )
     {
         ORIGEN_COMPARE_SP( transition_coeff[i],
                            ( *b_transition_coeff )[i],
                            ( *a.b_transition_coeff )[i] );
     }
     return true;
 }
std::string print_compare (const Library & a) const
References Library::b_decay_data, Library::b_definition, Library::b_transition_coeff, and Library::b_transition_structure.
 {
     std::stringstream ss;
     ss << b_definition->print_compare( *( a.b_definition ) );
     std::map<int, int> nucl_list_loc_a;
     std::map<int, int> nucl_list_loc_b;
     std::map<int, int> nucl_list =
         b_definition->nuclide_set().compare_nucl_lists(
             a.b_definition->nuclide_set(), nucl_list_loc_a, nucl_list_loc_b );
     ss << b_decay_data->print_compare(
         *( a.b_decay_data ), nucl_list, nucl_list_loc_a, nucl_list_loc_b );
     ss << b_transition_structure.get()->print_compare(
         *( a.b_transition_structure ) );
     ss << std::endl;
     ss << "Transition Coeff Size A: " << b_transition_coeff->size()
        << std::endl;
     ss << "Transition Coeff Size B: " << a.b_transition_coeff->size()
        << std::endl;
     if( b_transition_coeff->size() == a.b_transition_coeff->size() )
     {
         for( unsigned int i = 0; i < b_transition_coeff->size(); i++ )
         {
             ss << b_transition_coeff->at( i )->print_compare(
                 *( a.b_transition_coeff->at( i ) ), i );
         }
     }
     return ss.str();
 }
const LibraryHeader & definition () const
return a const reference to definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Library goes out of scope.
Examples:
tstLibraryIO.cpp, tstNuclideSet.cpp, tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), Origen::construct_neutron_prod_map(), Origen::construct_neutron_yields_map(), DecayResource::DecayResource(), Library::deserialize(), Origen::graphvizLibrary(), gtestLibraryMasses(), gtestLibrarySizes(), inject_fission_yields(), FakeFactory::Library_random1(), Library::operator==(), Origen::populateLibraryAbundance_NuclideResource(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryMass(), Origen::populateLibraryMass_NuclideResource(), Origen::populateLibraryToxicity_DecayResource(), Origen::printReactionTransitions(), scale61_fixup(), Origen::tabulateFissionXs(), Origen::tabulateLossXs(), Origen::tabulateNuclideInfo(), Origen::tabulateTransitionCoeff(), TEST(), TEST_F(), Origen::thinLibrary(), LibraryIO_bof::write(), LibraryIO_s61::write(), and LibraryIO_s62b::write().
SCP_LibraryHeader scp_definition () const
return a shared (read-only) definition pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_definition () const
return whether the class has a non-null definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::clone(), and Library::total_nuclides().
void get_definition (LibraryHeader & definition) const
populate an existing LibraryHeader with a copy of definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_definition (const LibraryHeader & definition)
set the definition (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstLibraryIO.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::Library_random1(), LibraryIO_bof::read(), LibraryIO_s62b::read(), LibraryIO_s61::read(), scale61_fixup(), and TEST().
void getptr_definition (const LibraryHeader *&) const
retrieve pointer (read-only) to definition
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_definition (LibraryHeader *& definition)
set the definition (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const TagManager & tag_manager () const
return a const reference to tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Library goes out of scope.
Referenced by Library::deserialize(), Library::operator==(), Origen::printIdTags_json(), Origen::printInterpTags_json(), and LibraryIO_bof::write().
SCP_TagManager scp_tag_manager () const
return a shared (read-only) tag_manager pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_tag_manager () const
return whether the class has a non-null tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::clone().
void get_tag_manager (TagManager & tag_manager) const
populate an existing TagManager with a copy of tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_tag_manager (const TagManager & tag_manager)
set the tag_manager (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstinterp.cpp.
Referenced by LibraryIO_bof::read(), and TEST().
void getptr_tag_manager (const TagManager *&) const
retrieve pointer (read-only) to tag_manager
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_tag_manager (TagManager *& tag_manager)
set the tag_manager (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const DecayData & decay_data () const
return a const reference to decay_data
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Library goes out of scope.
Examples:
tstLibrary.cpp, tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by DecayResource::DecayResource(), Library::deserialize(), gtestLibraryMasses(), gtestLibrarySizes(), Library::operator==(), Origen::populateLibraryAbundance(), Origen::populateLibraryAbundance_NuclideResource(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryMass(), Origen::populateLibraryMass_NuclideResource(), Origen::populateLibraryToxicity_DecayResource(), Origen::tabulateNuclideInfo(), TEST(), TEST_F(), LibraryIO_s61::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
SCP_DecayData scp_decay_data () const
return a shared (read-only) decay_data pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_decay_data () const
return whether the class has a non-null decay_data
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::clone().
void get_decay_data (DecayData & decay_data) const
populate an existing DecayData with a copy of decay_data
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_decay_data (const DecayData & decay_data)
set the decay_data (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::Library_random1(), Origen::populateLibraryAbundance_NuclideResource(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryMass(), Origen::populateLibraryMass_NuclideResource(), Origen::populateLibraryToxicity_DecayResource(), LibraryIO_s62b::read(), LibraryIO_bof::read(), LibraryIO_s61::read(), and TEST().
void getptr_decay_data (const DecayData *&) const
retrieve pointer (read-only) to decay_data
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_decay_data (DecayData *& decay_data)
set the decay_data (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
const TransitionStructure & transition_structure () const
return a const reference to transition_structure
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Library goes out of scope.
Examples:
tstLibraryIO.cpp, tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), gtestLibrarySizes(), inject_fission_yields(), Library::operator==(), Origen::printReactionTransitions(), scale61_fixup(), Origen::tabulateTransitionCoeff(), TEST(), TEST_F(), LibraryIO_bof::write(), LibraryIO_s62b::write(), and LibraryIO_s61::write().
SCP_TransitionStructure scp_transition_structure () const
return a shared (read-only) transition_structure pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_transition_structure () const
return whether the class has a non-null transition_structure
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::clone().
void get_transition_structure (TransitionStructure & transition_structure) const
populate an existing TransitionStructure with a copy of transition_structure
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_transition_structure (const TransitionStructure & transition_structure)
set the transition_structure (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstLibraryIO.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::Library_random1(), LibraryIO_bof::read(), LibraryIO_s62b::read(), LibraryIO_s61::read(), scale61_fixup(), and TEST().
void getptr_transition_structure (const TransitionStructure *&) const
retrieve pointer (read-only) to transition_structure
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_transition_structure (TransitionStructure *& transition_structure)
set the transition_structure (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_transition_coeff () const
has a non-null transition_coeff vector
Referenced by Library::to_json().
size_t transition_coeff_size () const
size of transition_coeff vector
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
tstinterp.cpp, tstLibrary.cpp, tstLibraryIO.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::getTransitionCoeffList(), gtestLibrarySizes(), Library::interpolate(), Library::interpolate_Interp1D(), FakeFactory::Library_linear1D(), FakeFactory::Library_linear2D(), Origen::loadMulti(), Library::newptr_transition_matrix_at(), Library::operator==(), Origen::populateLossXsValues(), Origen::setbuLibrary(), Origen::tabulateBurnups(), Origen::tabulateFissionXs(), TEST(), TEST_F(), Origen::thinLibrary(), LibraryIO_bof::write(), LibraryIO_s62b::write(), and LibraryIO_s61::write().
const TransitionCoeff & transition_coeff_at (size_t i) const
return a const element for read-only access
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
tstinterp.cpp, tstLibrary.cpp, tstLibraryIO.cpp, tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), Origen::construct_neutron_prod_map(), Origen::construct_neutron_yields_map(), Origen::getTransitionCoeffList(), gtestLibrarySizes(), inject_fission_yields(), FakeFactory::Library_linear1D(), Library::populate_transition_matrix_reaction(), Origen::populateLossXsValues(), scale61_fixup(), Origen::setbuLibrary(), Origen::tabulateBurnups(), Origen::tabulateFissionXs(), TEST(), TEST_F(), Origen::thinLibrary(), LibraryIO_s62b::write(), LibraryIO_s61::write(), and LibraryIO_bof::write().
SCP_TransitionCoeff scp_transition_coeff_at (size_t i) const
return a const std::shared_ptr for read-only access
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
tstLibrary.cpp.
Referenced by Library::interpolate(), Library::interpolate_Interp1D(), and TEST().
bool has_transition_coeff_at (size_t i) const
has a non-null element of transition_coeff vector
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Referenced by Library::populate_transition_matrix_reaction().
void getptr_transition_coeff_at (const TransitionCoeff *& , size_t) const
get a read-only pointer by index
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void resize_transition_coeff (size_t n)
resize the vector
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Referenced by Origen::saveLibraries().
void get_transition_coeff_at (TransitionCoeff & element, size_t i) const
get a copy of the element in-place
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void set_transition_coeff_at (const TransitionCoeff & element, size_t i)
set a new element by index
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
tstLibraryIO.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by inject_fission_yields(), scale61_fixup(), Origen::setbuLibrary(), and TEST().
void add_transition_coeff (const TransitionCoeff & element)
add a new element to the end
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
tstinterp.cpp, tstLibrary.cpp, and tstLibraryIO.cpp.
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), FakeFactory::Library_linear1D(), FakeFactory::Library_random1(), LibraryIO_s62b::read(), LibraryIO_bof::read(), LibraryIO_s61::read(), TEST(), and TEST_F().
void delete_transition_coeff_at (size_t i)
delete an element
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Referenced by Origen::thinLibrary().
void manageptr_transition_coeff_at (TransitionCoeff *& element, size_t i)
manage an existing pointer in this class
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
TransitionMatrixP * newptr_transition_matrix_at (size_t index) const
References Library::populate_transition_matrix(), and Library::transition_coeff_size().
Referenced by Library::newsp_transition_matrix_at().
 {
     jDebugLine( "index=" << index << "/" << transition_coeff_size() );
     Require( index < transition_coeff_size() );
     TransitionMatrixP* trx = new TransitionMatrixP();
     populate_transition_matrix( trx, index );
     return trx;
 }
TransitionMatrixP::SP newsp_transition_matrix_at (size_t index) const
Examples:
tstKernelMatrexC.cpp, tstKernelRadau5C.cpp, tstSolver_cram.cpp, tstSolver_matrex.cpp, and tstTransitionMatrixP.cpp.
References Library::newptr_transition_matrix_at().
Referenced by Origen::graphvizLibrary(), and TEST().
 {
     return TransitionMatrixP::SP( newptr_transition_matrix_at( index ) );
 }
void add_transition_matrix (const TransitionMatrixP & trx)
References TransitionMatrixP::a, Library::add_transition_coeff(), TransitionMatrixP::b_kappa_capture, TransitionMatrixP::b_kappa_fission, TransitionMatrixP::burnup, TransitionMatrixP::fiss, TransitionMatrixP::genneu, TransitionCoeff::set_burnup(), TransitionCoeff::set_fission_xs(), TransitionCoeff::set_flux(), TransitionCoeff::set_kappa_capture(), TransitionCoeff::set_kappa_fission(), TransitionCoeff::set_loss_xs(), TransitionCoeff::set_matrix(), TransitionCoeff::set_neutron_yields(), TransitionMatrixP::spectrum, and TransitionMatrixP::tocap.
 {
     TransitionCoeff tco;
     tco.set_flux( trx.spectrum );
     tco.set_burnup( trx.burnup );
     tco.set_matrix( Vec_Flt( trx.a.begin(), trx.a.end() ) );
     tco.set_loss_xs( Vec_Flt( trx.tocap.begin(), trx.tocap.end() ) );
     tco.set_fission_xs( Vec_Flt( trx.fiss.begin(), trx.fiss.end() ) );
     tco.set_neutron_yields( trx.genneu );
     tco.set_kappa_capture( trx.b_kappa_capture );
     tco.set_kappa_fission( trx.b_kappa_fission );
     this->add_transition_coeff( tco );
 }
size_t total_nuclides () const
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
References Library::b_definition, and Library::has_definition().
Referenced by gtestLibrarySizes(), and Origen::thinLibrary().
 {
     return has_definition() ? b_definition->total_nuclides() : 0;
 }
SP_Library clone () const
Examples:
tstinterp.cpp.
References Library::b_decay_data, Library::b_definition, Library::b_tag_manager, Library::b_transition_coeff, Library::b_transition_structure, Library::has_decay_data(), Library::has_definition(), Library::has_tag_manager(), and Library::has_transition_structure().
Referenced by FakeFactory::Library_linear2D(), and TEST().
 {
     SP_Library copyLib = SP_Library( new Library );
     if( this->has_definition() ) copyLib->set_definition( *b_definition );
     if( this->has_tag_manager() ) copyLib->set_tag_manager( *b_tag_manager );
     if( this->has_decay_data() ) copyLib->set_decay_data( *b_decay_data );
     if( this->has_transition_structure() )
         copyLib->set_transition_structure( *b_transition_structure );
     for( size_t i = 0; i < b_transition_coeff->size(); ++i )
     {
         copyLib->add_transition_coeff( *b_transition_coeff->at( i )->clone() );
     }
     return copyLib;
 }
int serialize (Standard::AbstractStream * stream) const virtual
References Library::b_decay_data, Library::b_definition, Library::b_tag_manager, Library::b_transition_coeff, Library::b_transition_structure, Library::getSerializedSize(), and Library::getUID().
 {
     Require( stream != nullptr );
     // write Library universal version id
     long classUID = this->getUID();
     stream->write( (char*)&classUID, sizeof( classUID ) );
     // write the size of this object
     unsigned long serializedSize = getSerializedSize();
     stream->write( (char*)&serializedSize, sizeof( serializedSize ) );
     // DBC=4 - capture the oldWriteHead for checksumming later
     Remember( long oldWriteHead = stream->getWriteHead() );
     bool headerPresent = b_definition != nullptr;
     stream->write( (char*)&headerPresent, sizeof( headerPresent ) );
     if( headerPresent )
     {
         int rtncode = b_definition->serialize( stream );
         if( rtncode != 0 ) return rtncode;
     }
     bool tag_manager_present = b_tag_manager != nullptr;
     stream->write( (char*)&tag_manager_present, sizeof( tag_manager_present ) );
     if( tag_manager_present )
     {
         int rtncode = b_tag_manager->serialize( stream );
         if( rtncode != 0 ) return rtncode;
     }
     int tcoeffCount = b_transition_coeff->size();
     stream->write( (char*)&tcoeffCount, sizeof( tcoeffCount ) );
     for( int i = 0; i < tcoeffCount; ++i )
     {
         int rtncode = ( *b_transition_coeff )[i]->serialize( stream );
         if( rtncode != 0 ) return rtncode;
     }
     bool decayDataPresent = b_decay_data != nullptr;
     stream->write( (char*)&decayDataPresent, sizeof( decayDataPresent ) );
     if( decayDataPresent )
     {
         int rtncode = b_decay_data->serialize( stream );
         if( rtncode != 0 ) return rtncode;
     }
     bool transitionMatrixPresent = b_decay_data != nullptr;
     stream->write( (char*)&transitionMatrixPresent,
                    sizeof( transitionMatrixPresent ) );
     if( transitionMatrixPresent )
     {
         int rtncode = b_transition_structure->serialize( stream );
         if( rtncode != 0 ) return rtncode;
     }
     // DBC=4 - checksum the expected serialized size and the actual serialized
     // size
     Ensure( ( stream->getWriteHead() - oldWriteHead ) ==
             static_cast<int>( this->getSerializedSize() ) );
     return 0;
 }
int deserialize (Standard::AbstractStream * stream) virtual
Examples:
tstLibrary.cpp.
References Library::b_decay_data, Library::b_definition, Library::b_tag_manager, Library::b_transition_coeff, Library::b_transition_structure, Library::decay_data(), Library::definition(), Library::getUID(), Library::tag_manager(), LibraryHeader::uid, DecayData::uid, TagManager::uid, TransitionStructure::uid, and TransitionCoeff::uid.
Referenced by TEST_F().
 {
     long read_uid = stream->getNextUID();
     // make sure we know how to parse the object in the stream
     if( read_uid != this->getUID() )
         return Standard::Serializable::TypeMismatch;
     // skip over uid
     stream->ignore( sizeof( read_uid ) );
     // read objects serialized size
     unsigned long serializedSize;
     stream->read( (char*)&serializedSize, sizeof( serializedSize ) );
     Check( serializedSize > 0 );
     // DBC=4 - capture the oldWriteHead for checksumming later
     Remember( long oldWriteHead = stream->getWriteHead() );
     // deserialize the header
     bool headerPresent = false;
     stream->read( (char*)&headerPresent, sizeof( headerPresent ) );
     if( headerPresent )
     {
         if( !stream->isNext( LibraryHeader::uid ) )
             return Standard::Serializable::ChildTypeMismatch;
         // get the serialized object
         Standard::Serializable* obj = stream->deserializeNext();
         Check( obj != nullptr );
         // set the library b_definition
         LibraryHeader* definition = (LibraryHeader*)obj;
         b_definition = SP_LibraryHeader( definition );
         Check( b_definition != 0 );
     }
     bool tag_manager_present = false;
     stream->read( (char*)&tag_manager_present, sizeof( tag_manager_present ) );
     if( tag_manager_present )
     {
         if( !stream->isNext( TagManager::uid ) )
             return Standard::Serializable::ChildTypeMismatch;
         // get the serialized object
         Standard::Serializable* obj = stream->deserializeNext();
         Check( obj != nullptr );
         // set the library b_definition
         TagManager* tag_manager = (TagManager*)obj;
         b_tag_manager = SP_TagManager( tag_manager );
         Check( b_tag_manager != 0 );
     }
     // deserialize the burnup data
     int tcoeffCount = 0;
     stream->read( (char*)&tcoeffCount, sizeof( tcoeffCount ) );
     for( int i = 0; i < tcoeffCount; ++i )
     {
         if( !stream->isNext( TransitionCoeff::uid ) )
             return Standard::Serializable::ChildTypeMismatch;
         // get the serialized object
         Standard::Serializable* obj = stream->deserializeNext();
         Check( obj != nullptr );
         // set the burnup data
         SP_TransitionCoeff sp( (TransitionCoeff*)obj );
         b_transition_coeff->push_back( sp );
     }
     // deserialize the decay data
     bool decayDataPresent = false;
     stream->read( (char*)&decayDataPresent, sizeof( decayDataPresent ) );
     if( decayDataPresent )
     {
         if( !stream->isNext( DecayData::uid ) )
             return Standard::Serializable::ChildTypeMismatch;
         // get the serialized object
         Standard::Serializable* obj = stream->deserializeNext();
         Check( obj != nullptr );
         // set the decay data
         DecayData* decay_data = (DecayData*)obj;
         b_decay_data = SP_DecayData( decay_data );
     }
     // deserialize the transition matrix
     bool transitionMatrixPresent = false;
     stream->read( (char*)&transitionMatrixPresent,
                   sizeof( transitionMatrixPresent ) );
     if( transitionMatrixPresent )
     {
         if( !stream->isNext( TransitionStructure::uid ) )
             return Standard::Serializable::ChildTypeMismatch;
         // get the serialized object
         Standard::Serializable* obj = stream->deserializeNext();
         Check( obj != nullptr );
         // set the transition b_transition_structure
         TransitionStructure* tstruct = (TransitionStructure*)obj;
         b_transition_structure = SP_TransitionStructure( tstruct );
     }
     // DBC=4 - check that the buffer is empty
     Ensure( ( stream->getWriteHead() - oldWriteHead ) == 0 );
     return 0;
 }
unsigned long getSerializedSize () const virtual
Obtain the size in bytes of this object when serialized This size does not contain the uid b_definition component size which each Standard::Serializable object MUST contain in its serialized definition.
Returns
unsigned long - the size in bytes of the object when serialized
References Library::b_decay_data, Library::b_definition, Library::b_tag_manager, Library::b_transition_coeff, and Library::b_transition_structure.
Referenced by Library::serialize().
 {
     unsigned long serializedSize = 0;
     bool headerPresent = ( b_definition != nullptr );
     serializedSize += sizeof( headerPresent );
     if( headerPresent )
     {
         unsigned long size = b_definition->getSerializedSize();
         serializedSize += size;
         serializedSize += sizeof( size );
         serializedSize += sizeof( b_definition->getUID() );
     }
     bool tag_manager_present = ( b_tag_manager != nullptr );
     serializedSize += sizeof( tag_manager_present );
     if( tag_manager_present )
     {
         unsigned long size = b_tag_manager->getSerializedSize();
         serializedSize += size;
         serializedSize += sizeof( size );
         serializedSize += sizeof( b_tag_manager->getUID() );
     }
     int tcoeffCount = b_transition_coeff->size();
     serializedSize += sizeof( tcoeffCount );
     for( int i = 0; i < tcoeffCount; i++ )
     {
         unsigned long size = ( *b_transition_coeff )[i]->getSerializedSize();
         serializedSize += size;
         serializedSize += sizeof( size );
         serializedSize += sizeof( ( *b_transition_coeff )[i]->getUID() );
     }
     bool decayDataPresent = ( b_decay_data != nullptr );
     serializedSize += sizeof( decayDataPresent );
     if( decayDataPresent )
     {
         unsigned long size = b_decay_data->getSerializedSize();
         serializedSize += size;
         serializedSize += sizeof( size );
         serializedSize += sizeof( b_decay_data->getUID() );
     }
     bool transitionMatrixPresent = ( b_transition_structure != nullptr );
     serializedSize += sizeof( transitionMatrixPresent );
     if( transitionMatrixPresent )
     {
         unsigned long size = b_transition_structure->getSerializedSize();
         serializedSize += size;
         serializedSize += sizeof( size );
         serializedSize += sizeof( b_transition_structure->getUID() );
     }
     return serializedSize;
 }
Standard::Serializable * getCopy () const virtual
References Library::Library().
 { return new Library(); }
long getUID () const virtual
Obtain the universal version identifier the uid should be unique for all Standard::Serializable objects such that an object factory can retrieve prototypes of the desired Standard::Serializable object and inflate the serial object into a manageable object.
Returns
long - the uid of the object
References Library::uid.
Referenced by Library::deserialize(), and Library::serialize().
 { return Library::uid; }
std::string toString () const virtual
References Library::to_string().
 { return to_string(); }
SP_Library interpolate (std::vector< float > newBurnups)
Return a new Library interpolated to the provided burnup grid.
References Library::b_decay_data, Library::b_definition, Library::b_interp_func, Library::b_tag_manager, Library::b_transition_structure, Library::Library(), r, Library::scp_transition_coeff_at(), and Library::transition_coeff_size().
Referenced by Library::regrid().
 {
     // \todo Refactor this function to use the new GridData_TransitionCoeff
     // object
     typedef ScaleUtils::Math::GridData<float, float> GD_t;
     Require( newBurnups.size() > 0 );
     Require( this->b_interp_func != nullptr );
     // Ensure burnups are increasing order
     std::sort( newBurnups.begin(), newBurnups.end() );
     size_t numBU = transition_coeff_size();  // Number of burnups in library
     std::vector<float> burnupOld;            // list of burnups in old library
     std::vector<GridView_TransitionCoeff>
         tCoeffViewVec;  // viewer for tcoeff objects
     tCoeffViewVec.reserve( numBU );
     // Push Transition coeffs into a vector of viewers
     for( int position = 0; position < numBU; position++ )
     {
         SCP_TransitionCoeff tcCopy = scp_transition_coeff_at( position );
         // make list of old burnups to interp to the new ones
         burnupOld.push_back( tcCopy->burnup() );
         // putting coefficient vectors into viewer
         tCoeffViewVec.emplace_back( tcCopy );
     }
     Check( increasing( burnupOld ) );
     // Set up Grid data
     GD_t gdObj;
     GD_t::Vec_I extents = {numBU};
     GD_t::Vec_Xptr grid = {&burnupOld[0]};
     gdObj.setx( extents, grid );
     // Setup responses for locations in Grid Data gdObj
     GD_t::I_t numR = tCoeffViewVec[0].nr();
     GD_t::Vec_Rptr responses;
     for( auto& v : tCoeffViewVec )
     {
         // get response pointers from each viewer
         const GD_t::Vec_Rptr& resp = v.r();
         // take response and make a single vector with all responses pointers
         for( size_t r = 0; r < numR; r++ ) responses.push_back( resp[r] );
     }
     // put responses into grid data at locations
     gdObj.setr( tCoeffViewVec[0].rextents(), responses );
     SP_Library libNew( new Library() );
     for( auto& bu : newBurnups )
     {
         GD_t::Vec_X wgts;
         // make weights for new burnup #bu
         b_interp_func( burnupOld, bu, &wgts );
         GD_t::Vec_Xptr buWts = {&wgts[0]};
         // make new transition object
         GD_t::Vec_Z z = gdObj.rgridsum( buWts );
         SP_TransitionCoeff tempTCoeff = tCoeffViewVec[0].permute( z );
         // with "nearest" interpolator this is not true
         // Check( tempTCoeff->burnup() == bu );
         // by definition, this is the interpolated burnup
         tempTCoeff->set_burnup( bu );
         // put transition coefficient into the library
         libNew->b_transition_coeff->push_back( tempTCoeff );
     }
     // copy data from libOld that doesn't change (shallow copy for now)
     libNew->b_definition = b_definition;
     libNew->b_tag_manager = b_tag_manager;
     libNew->b_decay_data = b_decay_data;
     libNew->b_transition_structure = b_transition_structure;
     return ( libNew );
 }
SP_Library interpolate_Interp1D (std::vector< double > newBurnups)
Return a new Library interpolated to the provided burnup grid using SplineFit
References Library::b_decay_data, Library::b_definition, Library::b_tag_manager, Library::b_transition_structure, Library::Library(), Library::scp_transition_coeff_at(), and Library::transition_coeff_size().
Referenced by Library::regrid_Interp1D().
 {
     Require( newBurnups.size() > 0 );
     using ScaleUtils::Math::Numeric::Interp1D_CubicSpline_SF;
     // Require(interpolator != nullptr);
     // Ensure burnups are increasing order
     std::sort( newBurnups.begin(), newBurnups.end() );
     size_t numBU = transition_coeff_size();  // Number of burnups in library
     std::vector<double> burnupOld;           // interpolation x-values
     std::vector<std::vector<double>> tCoeffData;  // interpolation y-values
     std::vector<double> tmpVec;
     // Push Transition coeffs into a vector of viewers
     for( size_t position = 0; position < numBU; ++position )
     {
         SCP_TransitionCoeff tcCopy = scp_transition_coeff_at( position );
         // make list of old burnups to interp to the new ones
         burnupOld.push_back( tcCopy->burnup() );
         // In terms of the interpolation, the burnups will be the x-values
         // and the rest of the data will be the vectors of y-data.
         // Constructing that y-data now out of all the TC data.
         for( auto& matrix : *( tcCopy->scp_matrix() ) )
             tmpVec.push_back( matrix );
         for( auto& loss_xs : *( tcCopy->scp_loss_xs() ) )
             tmpVec.push_back( loss_xs );
         for( auto& fission_xs : *( tcCopy->scp_fission_xs() ) )
             tmpVec.push_back( fission_xs );
         for( auto& neutron_yields : *( tcCopy->scp_neutron_yields() ) )
             tmpVec.push_back( neutron_yields );
         for( auto& flux : *( tcCopy->scp_flux() ) ) tmpVec.push_back( flux );
         if( tcCopy->scp_kappa_capture() != nullptr )
         {
             for( auto& kappa_capture : *( tcCopy->scp_kappa_capture() ) )
                 tmpVec.push_back( kappa_capture );
         }
         if( tcCopy->scp_kappa_fission() != nullptr )
         {
             for( auto& kappa_fission : *( tcCopy->scp_kappa_fission() ) )
                 tmpVec.push_back( kappa_fission );
         }
         tCoeffData.push_back( tmpVec );
         tmpVec.resize( 0 );
     }
     Check( increasing( burnupOld ) );
     // Interpolate the TransitionCoeff data on the new burnup grid
     Interp1D_CubicSpline_SF<double> interpolator;
     std::vector<std::vector<double>> newTCs =
         interpolator.interp_multi_list( newBurnups, burnupOld, tCoeffData );
     SP_Library libNew( new Library() );
     SCP_TransitionCoeff oldTC = this->scp_transition_coeff_at( 0 );
     for( size_t bu = 0; bu < newBurnups.size(); ++bu )
     {
         SP_TransitionCoeff tempTC = SP_TransitionCoeff( new TransitionCoeff() );
         size_t start = 0;
         size_t stop = oldTC->matrix_size();
         std::vector<float> tmpMatrix( newTCs[bu].begin(),
                                       newTCs[bu].begin() + stop );
         tempTC->set_matrix( tmpMatrix );
         Check( tempTC->matrix_size() == oldTC->matrix_size() );
         start = stop;
         stop += oldTC->loss_xs_size();
         std::vector<float> tmpLossXS( newTCs[bu].begin() + start,
                                       newTCs[bu].begin() + stop );
         tempTC->set_loss_xs( tmpLossXS );
         Check( tempTC->loss_xs_size() == oldTC->loss_xs_size() );
         start = stop;
         stop += oldTC->fission_xs_size();
         std::vector<float> tmpFissionXS( newTCs[bu].begin() + start,
                                          newTCs[bu].begin() + stop );
         tempTC->set_fission_xs( tmpFissionXS );
         Check( tempTC->fission_xs_size() == oldTC->fission_xs_size() );
         start = stop;
         stop += oldTC->neutron_yields_size();
         std::vector<float> tmpNeutronYields( newTCs[bu].begin() + start,
                                              newTCs[bu].begin() + stop );
         tempTC->set_neutron_yields( tmpNeutronYields );
         Check( tempTC->neutron_yields_size() == oldTC->neutron_yields_size() );
         start = stop;
         stop += oldTC->flux_size();
         std::vector<float> tmpFlux( newTCs[bu].begin() + start,
                                     newTCs[bu].begin() + stop );
         tempTC->set_flux( tmpFlux );
         Check( tempTC->flux_size() == oldTC->flux_size() );
         if( oldTC->scp_kappa_capture() != nullptr )
         {
             start = stop;
             stop += oldTC->kappa_capture_size();
             std::vector<float> tmpKC( newTCs[bu].begin() + start,
                                       newTCs[bu].begin() + stop );
             tempTC->set_kappa_capture( tmpKC );
             Check( tempTC->kappa_capture_size() ==
                    oldTC->kappa_capture_size() );
         }
         if( oldTC->scp_kappa_fission() != nullptr )
         {
             start = stop;
             stop += oldTC->kappa_fission_size();
             std::vector<float> tmpKF( newTCs[bu].begin() + start,
                                       newTCs[bu].begin() + stop );
             tempTC->set_kappa_fission( tmpKF );
             Check( tempTC->kappa_fission_size() ==
                    oldTC->kappa_fission_size() );
         }
         tempTC->set_burnup( newBurnups[bu] );
         // put transition coefficient into the library
         libNew->b_transition_coeff->push_back( tempTC );
     }
     // copy data from libOld that doesn't change (shallow copy for now)
     libNew->b_definition = b_definition;
     libNew->b_tag_manager = b_tag_manager;
     libNew->b_decay_data = b_decay_data;
     libNew->b_transition_structure = b_transition_structure;
     return ( libNew );
 }
void regrid (std::vector< float > newBurnups)
Re-grid this library to the given burnup grid by interpolating from the old grid
Examples:
tstLibrary.cpp.
References Library::interpolate().
Referenced by TEST(), and Origen::thinLibrary().
 {
     SP_Library newLib = this->interpolate( newBurnups );
     Ensure( newLib.get() != nullptr );
     std::swap( *newLib, *this );
 }
void regrid_Interp1D (std::vector< double > newBurnups)
References Library::interpolate_Interp1D().
Referenced by Origen::thinLibrary().
 {
     SP_Library newLib = this->interpolate_Interp1D( newBurnups );
     Ensure( newLib.get() != nullptr );
     std::swap( *newLib, *this );
 }
void set_interpolator (Library::InterpFunction func)
Examples:
tstLibrary.cpp.
References Library::b_interp_func.
Referenced by TEST(), and Origen::thinLibrary().
 {
     this->b_interp_func = func;
 }
void canonicalize_definition () protected
 {
     // null op
 }
void canonicalize_tag_manager () protected
 {
     // null op
 }
void canonicalize_decay_data () protected
 {
     // null op
 }
void canonicalize_transition_structure () protected
 {
     // null op
 }
void canonicalize_transition_coeff_at (size_t i) protected
 {
     // null op
 }
void populate_transition_matrix (TransitionMatrixP * trx, size_t index) const protected
References DecayData::abund_of_lite_nuclides, LibraryHeader::day_made(), DecayData::decay_constants, DecayData::fissionable_nuclide_ids, LibraryHeader::has_nuclide_set(), DecayData::masses, LibraryHeader::month_made(), LibraryHeader::nuclide_set(), TransitionStructure::num_decay_parents(), TransitionStructure::num_parents(), TransitionStructure::parent_positions_at(), TransitionStructure::parent_positions_size(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, DecayData::recoverable_energy_values, Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, Origen::SUBLIB_3FP, LibraryHeader::title(), TransitionStructure::transition_ids_at(), and LibraryHeader::year_made().
Referenced by Library::newptr_transition_matrix_at().
 {
     Require( has_definition() );
     Require( transition_coeff_size() > 0 );
     Require( has_decay_data() );
     Require( has_transition_structure() );
     trx->set_filename( "in-memory" );
     trx->nti = 0;
     trx->_cached_has_valid_mts = false;
     trx->clear_transition_ids_cache();
     // get const references
     Check( has_definition() );
     LibraryHeader const& def = definition();
     Check( def.has_nuclide_set() );
     NuclideSet const& nucset = def.nuclide_set();
     Check( has_transition_structure() );
     TransitionStructure const& tstruct = transition_structure();
     Check( has_decay_data() );
     DecayData const& dd = decay_data();
     // set the general library information
     // nti = def.title.size();
     if( !def.title().empty() )
     {
         trx->nti = 1;
         std::string title_card = def.title();
         std::vector<std::string> title_cards( 1, title_card );
         trx->titles = StringList( title_cards );
     }
     trx->nmonth = def.month_made();
     trx->nday = def.day_made();
     trx->nyear = def.year_made();
     // set the nuclide inventory parameters
     trx->ilite = nucset.num_in_sublib( SUBLIB_1LT );
     trx->iact = nucset.num_in_sublib( SUBLIB_2AC );
     trx->ifp = nucset.num_in_sublib( SUBLIB_3FP );
     trx->itot = nucset.total_nuclides();
     trx->nfiso = dd.fissionable_nuclide_ids.size();
     trx->nucl.resize( trx->itot );
     for( size_t i = 0; i < trx->itot; ++i )
     {
         trx->nucl[i] = nucset.zzzaaai_at( i );
     }
     trx->sizes[0] = trx->ilite;
     trx->sizes[1] = trx->iact;
     trx->sizes[2] = trx->ifp;
     trx->init_bounds();
     Require( trx->nfiso >= 0 );
     Require( static_cast<int>( trx->nucl.size() ) == trx->itot );
     Require( trx->bounds[3][1] == trx->bounds[0][1] );
     // build the nuclide type vector
     trx->typ_nuc = IntegerList( std::vector<int>( trx->itot, 1 ) );
     trx->init_typ_nuc();
     // set the burnup parameters
     trx->numLibs = transition_coeff_size();
     Require( trx->numLibs > 0 );
     // set the transition matrix parameters
     trx->non = tstruct.parent_positions_size();
     trx->kd_ = tstruct.num_decay_parents();
     trx->non0_ = tstruct.num_parents();
     Require( trx->non > 0 );
     Require( static_cast<int>( trx->kd_.size() ) == trx->itot );
     Require( static_cast<int>( trx->non0_.size() ) == trx->itot );
     // set the parent position index.  There is a convention that anything
     // called a "position" should begin at 1 (in either C++ or Fortran) and
     // something called an "index" should begin at 1 in Fortran and 0 in C++.
     trx->loc.resize( trx->non );
     trx->mt.resize( trx->non );
     for( int i = 0; i < trx->non; ++i )
     {
         trx->loc[i] = tstruct.parent_positions_at( i ) - 1;
         trx->mt[i] = tstruct.transition_ids_at( i );
     }
     trx->dis = dd.decay_constants;
     trx->q = dd.recoverable_energy_values;
     trx->fg = dd.q_fractions_from_photons;
     trx->nucfis = dd.fissionable_nuclide_ids;
     Require( static_cast<int>( trx->loc.size() ) == trx->non );
     Require( static_cast<int>( trx->dis.size() ) == trx->itot );
     Require( static_cast<int>( trx->q.size() ) == trx->itot );
     Require( static_cast<int>( trx->fg.size() ) == trx->itot );
     Require( static_cast<int>( trx->mt.size() ) == trx->non );
     Require( static_cast<int>( trx->nucfis.size() ) == trx->nfiso );
     // expend the matrix pointers and set cached valid mts flag
     trx->expand_matrix_pointers();
     Require( static_cast<int>( trx->kd.size() ) == trx->itot );
     Require( static_cast<int>( trx->non0.size() ) == trx->itot );
     // set nuclide information
     trx->ampc = dd.rcg_for_air;
     trx->wmpc = dd.rcg_for_water;
     trx->abund = dd.abund_of_lite_nuclides;
     Require( static_cast<int>( trx->ampc.size() ) == trx->itot );
     Require( static_cast<int>( trx->wmpc.size() ) == trx->itot );
     Require( static_cast<int>( trx->abund.size() ) == trx->ilite );
     // calculate the atomic masses
     Check( static_cast<int>( trx->nucl.size() ) == trx->itot );
     trx->m = dd.masses;
     if( (int)trx->m.size() != trx->itot )
     {
         trx->m.clear();
         for( int i = 0; i < trx->itot; i++ )
         {
             trx->m.push_back( ( trx->nucl[i] / 10 ) % 1000 );
         }
     }
     Require( static_cast<int>( trx->m.size() ) == trx->itot );
     // calculate abundances in wt%
     trx->convert_abundances();
     populate_transition_matrix_reaction( trx, index );
     trx->b_nuclide_set = this->definition().scp_nuclide_set();
 #ifdef ENSURE_ON
     trx->check_library();
 #endif
 }
void populate_transition_matrix_reaction (TransitionMatrixP * trx, size_t index) const protected
References TransitionMatrixP::a, TransitionMatrixP::b_kappa_capture, TransitionMatrixP::b_kappa_fission, TransitionCoeff::burnup(), TransitionMatrixP::burnup, TransitionMatrixP::fiss, TransitionCoeff::fission_xs(), TransitionCoeff::fission_xs_size(), TransitionCoeff::flux(), TransitionCoeff::flux_size(), TransitionMatrixP::genneu, Library::has_transition_coeff_at(), TransitionMatrixP::iact, TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionCoeff::kappa_capture(), TransitionCoeff::kappa_fission(), TransitionCoeff::loss_xs(), TransitionCoeff::loss_xs_size(), TransitionCoeff::matrix(), TransitionCoeff::matrix_size(), TransitionCoeff::neutron_yields(), TransitionCoeff::neutron_yields_size(), TransitionMatrixP::nfluxgrp, TransitionMatrixP::non, TransitionMatrixP::set_pos(), TransitionMatrixP::spectrum, TransitionMatrixP::tocap, and Library::transition_coeff_at().
 {
     // load an index
     Require( trx != nullptr );
     Check( has_transition_coeff_at( index ) );
     const Origen::TransitionCoeff& tco = transition_coeff_at( index );
     // set position
     trx->set_pos( index + 1 );
     // get the spectrum and burnup
     trx->nfluxgrp = tco.flux_size();
     Require( trx->nfluxgrp >= 0 );
     trx->spectrum = tco.flux();
     trx->burnup = tco.burnup();
     Require( static_cast<int>( trx->spectrum.size() ) == trx->nfluxgrp );
     Require( trx->burnup >= 0.0 );
     Require( static_cast<int>( tco.matrix_size() ) == trx->non );
     Require( static_cast<int>( tco.loss_xs_size() ) == trx->itot );
     Require( static_cast<int>( tco.fission_xs_size() ) == trx->iact );
     Require( static_cast<int>( tco.neutron_yields_size() ) ==
              trx->ilite + trx->iact );
     trx->a.assign( tco.matrix().begin(), tco.matrix().end() );
     trx->tocap.assign( tco.loss_xs().begin(), tco.loss_xs().end() );
     trx->fiss.assign( tco.fission_xs().begin(), tco.fission_xs().end() );
     trx->genneu.assign( tco.neutron_yields().begin(),
                         tco.neutron_yields().end() );
     trx->b_kappa_capture.assign( tco.kappa_capture().begin(),
                                  tco.kappa_capture().end() );
     trx->b_kappa_fission.assign( tco.kappa_fission().begin(),
                                  tco.kappa_fission().end() );
 }
Member Data Documentation
const Standard::Serializable::UID uid = 0x99359452b5b56031 static
Referenced by Library::getUID().
SP_LibraryHeader b_definition protected
Referenced by Library::clone(), Library::deserialize(), Library::getSerializedSize(), Library::interpolate(), Library::interpolate_Interp1D(), Library::operator==(), Library::print_compare(), Library::serialize(), Library::to_json(), and Library::total_nuclides().
SP_TagManager b_tag_manager protected
Referenced by Library::clone(), Library::deserialize(), Library::getSerializedSize(), Library::interpolate(), Library::interpolate_Interp1D(), Library::operator==(), and Library::serialize().
SP_DecayData b_decay_data protected
Referenced by Library::clone(), Library::deserialize(), Library::getSerializedSize(), Library::interpolate(), Library::interpolate_Interp1D(), Library::operator==(), Library::print_compare(), Library::serialize(), and Library::to_json().
SP_TransitionStructure b_transition_structure protected
Referenced by Library::clone(), Library::deserialize(), Library::getSerializedSize(), Library::interpolate(), Library::interpolate_Interp1D(), Library::operator==(), Library::print_compare(), Library::serialize(), and Library::to_json().
SP_Vec_SP_TransitionCoeff b_transition_coeff protected
Vector of smart pointers
Referenced by Library::clone(), Library::deserialize(), Library::getSerializedSize(), Library::operator==(), Library::print_compare(), Library::serialize(), and Library::to_json().
InterpFunction b_interp_func protected
Function pointer to interpolator function to use.
to transition coefficients.
Referenced by Library::interpolate(), and Library::set_interpolator().
The documentation for this class was generated from the following files:
Core/dc/Library.h
Core/dc/Library.cpp