ORIGEN API: origen_containerfunctions_m Module Reference
origen_containerfunctions_m Module Reference
Functions/Subroutines
subroutine origen_copynativetovec_int (a, b)
subroutine origen_copynativetointegerlist (a, b)
subroutine origen_copynativetovec_flt (a, b)
subroutine origen_copynativetovec_dbl (a, b)
subroutine origen_copynativetotransitioncoeff (ax, capx, fisx, genx, flxx, b)
subroutine origen_copytransitioncoefftonative (a, ax, capx, fisx, genx, flxx)
subroutine origen_copyvec_flttonative (a, b)
subroutine origen_copyvec_dbltonative (a, b)
subroutine origen_copyvec_inttonative (a, b)
subroutine origen_copyserialtovec_flt (a, b)
subroutine origen_copyserialtovec_int (a, b)
subroutine origen_copyserialtovec_dbl (a, b)
subroutine origen_copyintegerlist (a, b)
subroutine origen_copyfloatlist (a, b)
subroutine origen_copydoublelist (a, b)
Function/Subroutine Documentation
subroutine origen_containerfunctions_m::origen_copynativetovec_int (integer, dimension(:), intent(in) a, type(scalestl_vec_int) b)
     integer,intent(in) :: a(:)
     type(scalestl_vec_int) :: b
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize_size(size(a,1,c_size_t))
     end if
     call b%resize(size(a,1,c_size_t))
     do i=1,b%size()
         call b%set(i,a(i))
     end do
subroutine origen_containerfunctions_m::origen_copynativetointegerlist (integer, dimension(:), intent(in) a, type(integerlist) b)
Referenced by tsttransitionmatrixp().
     integer,intent(in) :: a(:)
     type(integerlist) :: b
     integer :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize()
     end if
     call b%resize(size(a,1))
     do i=1,b%size()
         call b%set(i,a(i))
     end do
subroutine origen_containerfunctions_m::origen_copynativetovec_flt (real(c_float), dimension(:), intent(in) a, type(scalestl_vec_flt) b)
Referenced by origen_copynativetotransitioncoeff().
     real(C_FLOAT),intent(in) :: a(:)
     type(scalestl_vec_flt) :: b
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize_size(size(a,1,c_size_t))
     end if
     call b%resize(size(a,1,c_size_t))
     do i=1,b%size()
         call b%set(i,a(i))
     end do
subroutine origen_containerfunctions_m::origen_copynativetovec_dbl (real(c_double), dimension(:), intent(in) a, type(scalestl_vec_dbl) b)
     real(C_DOUBLE),intent(in) :: a(:)
     type(scalestl_vec_dbl) :: b
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize_size(size(a,1,c_size_t))
     end if
     call b%resize(size(a,1,c_size_t))
     do i=1,b%size()
         call b%set(i,a(i))
     end do
subroutine origen_containerfunctions_m::origen_copynativetotransitioncoeff (real(c_float), dimension(:), intent(in) ax, real(c_float), dimension(:), intent(in) capx, real(c_float), dimension(:), intent(in) fisx, real(c_float), dimension(:), intent(in) genx, real(c_float), dimension(:), intent(in) flxx, type(origen_transitioncoeff) b)
References origen_copynativetovec_flt().
     real(C_FLOAT),intent(in) :: ax(:),capx(:),fisx(:),genx(:),flxx(:)
     type(origen_transitioncoeff) :: b
     type(scalestl_vec_flt) :: fvec
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize()
     end if
     call b % getptr_matrix_vec(fvec)
     call origen_copynativetovec_flt(ax,fvec)
     call b % getptr_loss_xs_vec(fvec)
     call origen_copynativetovec_flt(capx,fvec)
     call b % getptr_fission_xs_vec(fvec)
     call origen_copynativetovec_flt(fisx,fvec)
     call b % getptr_neutron_yields_vec(fvec)
     call origen_copynativetovec_flt(genx,fvec)
     call b % getptr_flux_vec(fvec)
     call origen_copynativetovec_flt(flxx,fvec)
subroutine origen_containerfunctions_m::origen_copytransitioncoefftonative (type(origen_transitioncoeff) a, real(c_float), dimension(:), intent(inout) ax, real(c_float), dimension(:), intent(inout) capx, real(c_float), dimension(:), intent(inout) fisx, real(c_float), dimension(:), intent(inout) genx, real(c_float), dimension(:), intent(inout) flxx)
References origen_copyvec_flttonative().
     type(origen_transitioncoeff) :: a
     real(C_FLOAT),intent(inout) :: ax(:),capx(:),fisx(:),genx(:),flxx(:)
     type(scalestl_vec_flt) :: fvec
     integer(C_SIZE_T) :: i
     require( c_associated(a%instance_ptr) )
     call a % getptr_matrix_vec(fvec)
     call origen_copyvec_flttonative(fvec,ax)
     call a % getptr_loss_xs_vec(fvec)
     call origen_copyvec_flttonative(fvec,capx)
     call a % getptr_fission_xs_vec(fvec)
     call origen_copyvec_flttonative(fvec,fisx)
     call a % getptr_neutron_yields_vec(fvec)
     call origen_copyvec_flttonative(fvec,genx)
     call a % getptr_flux_vec(fvec)
     call origen_copyvec_flttonative(fvec,flxx)
subroutine origen_containerfunctions_m::origen_copyvec_flttonative (type(scalestl_vec_flt) a, real(c_float), dimension(:), intent(out) b)
Referenced by origen_copytransitioncoefftonative().
     type(scalestl_vec_flt) :: a
     real(C_FLOAT),intent(out) :: b(:)
     integer(C_SIZE_T) :: i
     require(c_associated(a%instance_ptr) )
     require(size(b,1,c_size_t)==a%size())
     do i=1,a%size()
         b(i) = a%at(i)
     end do
subroutine origen_containerfunctions_m::origen_copyvec_dbltonative (type(scalestl_vec_dbl) a, real(c_double), dimension(:), intent(out) b)
     type(scalestl_vec_dbl) :: a
     real(C_DOUBLE),intent(out) :: b(:)
     integer(C_SIZE_T) :: i
     require(c_associated(a%instance_ptr) )
     require(size(b,1,c_size_t)==a%size())
     do i=1,a%size()
         b(i) = a%at(i)
     end do
subroutine origen_containerfunctions_m::origen_copyvec_inttonative (type(scalestl_vec_int) a, integer, dimension(:), intent(out) b)
     type(scalestl_vec_int) :: a
     integer,intent(out) :: b(:)
     integer(C_SIZE_T) :: i
     require(c_associated(a%instance_ptr) )
     require(size(b,1,c_size_t)==a%size())
     do i=1,a%size()
         b(i) = a%at(i)
     end do
subroutine origen_containerfunctions_m::origen_copyserialtovec_flt (type(floatlist), intent(in) a, type(scalestl_vec_flt) b)
     type(floatlist),intent(in) :: a
     type(scalestl_vec_flt) :: b
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize_size(int(a%size(),c_size_t))
     end if
     call b%resize(int(a%size(),c_size_t))
     do i=1,b%size()
         call b%set(i,a%at(int(i)))
     end do
subroutine origen_containerfunctions_m::origen_copyserialtovec_int (type(integerlist), intent(in) a, type(scalestl_vec_int) b)
     type(integerlist),intent(in) :: a
     type(scalestl_vec_int) :: b
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
       call b%initialize_size(int(a%size(),c_size_t))
     end if
     call b%resize(int(a%size(),c_size_t))
     do i=1,b%size()
         call b%set(i,a%at(int(i)))
     end do
subroutine origen_containerfunctions_m::origen_copyserialtovec_dbl (type(doublelist), intent(in) a, type(scalestl_vec_dbl) b)
     type(doublelist),intent(in) :: a
     type(scalestl_vec_dbl) :: b
     integer(C_SIZE_T) :: i
     if( .NOT. c_associated(b%instance_ptr) )then
         call b%initialize_size(int(a%size(),c_size_t))
     end if
     call b%resize(int(a%size(),c_size_t))
     do i=1,b%size()
         call b%set(i,a%at(int(i)))
     end do
subroutine origen_containerfunctions_m::origen_copyintegerlist (type(integerlist) a, type(integerlist) b)
     type(integerlist) :: a,b
     integer :: i
     !call b%reserve(a%size())
     call b%clear()
     do i=1,a%size()
         call b%push_back(a%at(i))
     end do
     ensure(a%size()==b%size())
subroutine origen_containerfunctions_m::origen_copyfloatlist (type(floatlist) a, type(floatlist) b)
     type(floatlist) :: a,b
     integer :: i
     !call b%reserve(a%size())
     call b%clear()
     do i=1,a%size()
         call b%push_back(a%at(i))
     end do
     ensure(a%size()==b%size())
subroutine origen_containerfunctions_m::origen_copydoublelist (type(doublelist) a, type(doublelist) b)
     type(doublelist) :: a,b
     integer :: i
     !call b%reserve(a%size())
     call b%clear()
     do i=1,a%size()
         call b%push_back(a%at(i))
     end do
     ensure(a%size()==b%size())