ORIGEN API: Core/dc/f/NuclideSetInterface.h File Reference
NuclideSetInterface.h File Reference
#include "Origen/Core/dc/NuclideSet.h"
#include "ScaleSTL/Vec_IntInterface.h"
#include "ScaleSTL/Vec_StrInterface.h"
Typedefs
typedef std::vector< int > Vec_Int
typedef std::vector< std::string > Vec_Str
typedef Origen::NuclideSet Origen_NuclideSet
Functions
void * Origen_NuclideSet_initialize_copy (Origen_NuclideSet *orig)
void * Origen_NuclideSet_initialize_legacy_vec (int *nlt, int *nac, int *nfp, Vec_Int *ids)
void * Origen_NuclideSet_initialize_legacy (int *nlt, int *nac, int *nfp, size_t *ids_size, int *ids)
void Origen_NuclideSet_set_ids_legacy_vec (void *Origen_NuclideSet_ptr, int *nlt, int *nac, int *nfp, Vec_Int *ids)
void Origen_NuclideSet_set_ids_legacy (void *Origen_NuclideSet_ptr, int *nlt, int *nac, int *nfp, size_t *ids_size, int *ids)
size_t Origen_NuclideSet_ids_size (void *Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_ids (void *Origen_NuclideSet_ptr)
void Origen_NuclideSet_get_ids_vec (void *Origen_NuclideSet_ptr, Vec_Int *&ids)
void Origen_NuclideSet_set_ids_vec (void *Origen_NuclideSet_ptr, Vec_Int *ids)
void Origen_NuclideSet_manageptr_ids (void *Origen_NuclideSet_ptr, Vec_Int *&ids)
void Origen_NuclideSet_getptr_ids_vec (void *Origen_NuclideSet_ptr, Vec_Int const *&ids)
void Origen_NuclideSet_get_ids (void *Origen_NuclideSet_ptr, size_t *ids_size, int *ids)
void Origen_NuclideSet_set_ids (void *Origen_NuclideSet_ptr, size_t *ids_size, int *ids)
int Origen_NuclideSet_sizzzaaa_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_izzzaaa_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_zzzaaai_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_s_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_i_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_z_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_a_at (void *Origen_NuclideSet_ptr, size_t *index)
int Origen_NuclideSet_total_nuclides (void *Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_sublibs (void *Origen_NuclideSet_ptr)
size_t Origen_NuclideSet_count_sublibs (void *Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_sublib (void *Origen_NuclideSet_ptr, int *s)
int Origen_NuclideSet_ids_at (void *Origen_NuclideSet_ptr, size_t *index)
size_t Origen_NuclideSet_num_in_sublib (void *Origen_NuclideSet_ptr, int *s)
size_t Origen_NuclideSet_sublib_begin (void *Origen_NuclideSet_ptr, int *s, bool *fixed)
size_t Origen_NuclideSet_sublib_end (void *Origen_NuclideSet_ptr, int *s)
size_t Origen_NuclideSet_lookup_index (void *Origen_NuclideSet_ptr, int *id, bool *fixed)
size_t Origen_NuclideSet_lookup_index_guess (void *Origen_NuclideSet_ptr, int *izzzaaa, bool *fixed)
bool Origen_NuclideSet_lookup_index_all (void *Origen_NuclideSet_ptr, ScaleSTL_Vec_Int *&ids, int *izzzaaa, bool *fixed)
size_t Origen_NuclideSet_NOT_FOUND (bool *fixed)
void Origen_NuclideSet_convert_symbol_to_izzzaaa (ScaleSTL_Vec_Str *&symbols, ScaleSTL_Vec_Int *&ids)
void Origen_NuclideSet_convert_sizzzaaa_to_zzzaaai (ScaleSTL_Vec_Int *&ids)
void * Origen_NuclideSet_initialize ()
void Origen_NuclideSet_destroy (void *Origen_NuclideSet_ptr)
Typedef Documentation
typedef std::vector<int> Vec_Int
Examples:
Solver/matrex/src/tests/tstKernelMatrexC.cpp, and Solver/radau5/src/tests/tstKernelRadau5C.cpp.
typedef std::vector<std::string> Vec_Str
typedef Origen::NuclideSet Origen_NuclideSet
Function Documentation
void* Origen_NuclideSet_initialize_copy (Origen_NuclideSet * orig)
void* Origen_NuclideSet_initialize_legacy_vec (int * nlt, int * nac, int * nfp, Vec_Int * ids)
void* Origen_NuclideSet_initialize_legacy (int * nlt, int * nac, int * nfp, size_t * ids_size, int * ids)
void Origen_NuclideSet_set_ids_legacy_vec (void * Origen_NuclideSet_ptr, int * nlt, int * nac, int * nfp, Vec_Int * ids)
void Origen_NuclideSet_set_ids_legacy (void * Origen_NuclideSet_ptr, int * nlt, int * nac, int * nfp, size_t * ids_size, int * ids)
size_t Origen_NuclideSet_ids_size (void * Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_ids (void * Origen_NuclideSet_ptr)
void Origen_NuclideSet_get_ids_vec (void * Origen_NuclideSet_ptr, Vec_Int *& ids)
void Origen_NuclideSet_set_ids_vec (void * Origen_NuclideSet_ptr, Vec_Int * ids)
void Origen_NuclideSet_manageptr_ids (void * Origen_NuclideSet_ptr, Vec_Int *& ids)
void Origen_NuclideSet_getptr_ids_vec (void * Origen_NuclideSet_ptr, Vec_Int const *& ids)
void Origen_NuclideSet_get_ids (void * Origen_NuclideSet_ptr, size_t * ids_size, int * ids)
void Origen_NuclideSet_set_ids (void * Origen_NuclideSet_ptr, size_t * ids_size, int * ids)
int Origen_NuclideSet_sizzzaaa_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_izzzaaa_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_zzzaaai_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_s_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_i_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_z_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_a_at (void * Origen_NuclideSet_ptr, size_t * index)
int Origen_NuclideSet_total_nuclides (void * Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_sublibs (void * Origen_NuclideSet_ptr)
size_t Origen_NuclideSet_count_sublibs (void * Origen_NuclideSet_ptr)
bool Origen_NuclideSet_has_sublib (void * Origen_NuclideSet_ptr, int * s)
int Origen_NuclideSet_ids_at (void * Origen_NuclideSet_ptr, size_t * index)
size_t Origen_NuclideSet_num_in_sublib (void * Origen_NuclideSet_ptr, int * s)
size_t Origen_NuclideSet_sublib_begin (void * Origen_NuclideSet_ptr, int * s, bool * fixed)
size_t Origen_NuclideSet_sublib_end (void * Origen_NuclideSet_ptr, int * s)
size_t Origen_NuclideSet_lookup_index (void * Origen_NuclideSet_ptr, int * id, bool * fixed)
size_t Origen_NuclideSet_lookup_index_guess (void * Origen_NuclideSet_ptr, int * izzzaaa, bool * fixed)
bool Origen_NuclideSet_lookup_index_all (void * Origen_NuclideSet_ptr, ScaleSTL_Vec_Int *& ids, int * izzzaaa, bool * fixed)
size_t Origen_NuclideSet_NOT_FOUND (bool * fixed)
References NuclideSet::NOT_FOUND().
void Origen_NuclideSet_convert_symbol_to_izzzaaa (ScaleSTL_Vec_Str *& symbols, ScaleSTL_Vec_Int *& ids)
References NuclideSet::convert_symbol_to_izzzaaa().
void Origen_NuclideSet_convert_sizzzaaa_to_zzzaaai (ScaleSTL_Vec_Int *& ids)
References NuclideSet::convert_sizzzaaa_to_zzzaaai().
void* Origen_NuclideSet_initialize ()
void Origen_NuclideSet_destroy (void * Origen_NuclideSet_ptr)