ORIGEN API: CompManager Class Reference
CompManager Class Reference
#include <CompManager.h>
Class for mixing up sweet materials.
Public Types
typedef std::map< std::string, int, ScaleUtils::IO::CaseInsensitiveLessThan > CiMap_t
case insensitive map type
Public Member Functions
CompManager (const ScaleData::StdComp &stdComp)
create a new CompManager
virtual ~CompManager ()
destroy
bool isAutomatic (const std::string &name, bool *isElement=nullptr) const
bool isEle (const std::string &name) const
bool isNuc (const std::string &name) const
std::string addPart (const std::string &name, const std::string &part, double value)
std::string initComp (const std::string &name, const std::string &inputTypeString, const std::string &inputScaleString, bool inputNorm=false)
std::string createEle (const std::string &elementName)
std::string finalizeComp (const std::string &name)
bool isFinalizedComp (const std::string &name) const
double getMolarMass (int id) const
std::vector< double > getMolarMasses (const std::vector< int > &id) const
double getMolarMass (const std::string &name) const
int getCompIndex (const std::string &name) const
CompContainer * getComp (const std::string &name) const
std::string getCompName (int index) const
std::string toString (const std::string &name, int indent=0) const
std::string getNumMap (const std::string &name, std::map< int, double > &map_out) const
std::string getWtMap (const std::string &name, std::map< int, double > &map_out) const
std::string getConcMap (const std::string &name, double density, std::map< int, double > &map_out) const
std::string getElementalAbundances (int id, std::vector< int > &ids_out, std::vector< double > &nums_out) const
int getNumComps () const
std::string getDC (DataContainer *dcCompositionList, bool flatten=true) const
double getReferenceDensity (const std::string &name) const
void setReferenceDensity (const std::string &name, double density)
bool renameComp (const std::string &oldName, const std::string &newName)
bool removeComp (const std::string &name)
Static Public Member Functions
static std::string printDC (DataContainer *dcCompositionList)
Protected Types
typedef ScaleUtils::Math::CompositionMethods cm
Protected Member Functions
std::string checkKnown (const std::string &part, int &id, bool &ele) const
Protected Attributes
std::map< int, CompContainer * > b_comps
map of elements and mixture ids to child mixtures
CiMap_t b_id_lookup
const ScaleData::StdComp & b_lib
std comp library used for molar masses and isotopic content of elements
Detailed Description
Class for mixing up sweet materials.
Examples:
Core/xf/tests/tstCompManager.cpp.
Member Typedef Documentation
typedef std::map<std::string, int, ScaleUtils::IO::CaseInsensitiveLessThan> CiMap_t
case insensitive map type
typedef ScaleUtils::Math::CompositionMethods cm protected
Constructor & Destructor Documentation
CompManager (const ScaleData::StdComp & stdComp)
create a new CompManager
~CompManager () virtual
destroy
References CompManager::b_comps.
Member Function Documentation
std::string checkKnown (const std::string & part, int & id, bool & ele) const protected
References CompManager::b_lib, and CompManager::getCompIndex().
Referenced by CompManager::addPart(), CompManager::createEle(), CompManager::isAutomatic(), CompManager::isEle(), and CompManager::isNuc().
bool isAutomatic (const std::string & name, bool * isElement = nullptr) const
References CompManager::checkKnown().
bool isEle (const std::string & name) const
References CompManager::checkKnown().
bool isNuc (const std::string & name) const
References CompManager::checkKnown().
std::string addPart (const std::string & name, const std::string & part, double value)
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::checkKnown(), CompManager::createEle(), CompManager::getComp(), and CompManager::getCompIndex().
Referenced by CompManager::createEle(), and TEST().
std::string initComp (const std::string & name, const std::string & inputTypeString, const std::string & inputScaleString, bool inputNorm = false)
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::b_comps, CompManager::b_id_lookup, CompManager::getCompIndex(), and CompManager::getNumComps().
Referenced by CompManager::createEle(), and TEST().
std::string createEle (const std::string & elementName)
References CompManager::addPart(), CompManager::checkKnown(), CompManager::finalizeComp(), CompManager::getCompIndex(), CompManager::getElementalAbundances(), and CompManager::initComp().
Referenced by CompManager::addPart().
std::string finalizeComp (const std::string & name)
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::b_comps, CompManager::getComp(), CompManager::getMolarMass(), CompContainer::name, and origen_beta::normalize().
Referenced by CompManager::createEle(), and TEST().
bool isFinalizedComp (const std::string & name) const
References CompManager::getComp().
double getMolarMass (int id) const
References CompManager::b_comps, CompManager::b_lib, and auxiliary::nuclide().
Referenced by CompManager::finalizeComp(), CompManager::getConcMap(), CompManager::getDC(), CompManager::getMolarMass(), and CompManager::getMolarMasses().
std::vector< double > getMolarMasses (const std::vector< int > & id) const
References CompManager::getMolarMass().
Referenced by CompManager::getWtMap().
double getMolarMass (const std::string & name) const
References CompManager::getCompIndex(), and CompManager::getMolarMass().
int getCompIndex (const std::string & name) const
References CompManager::b_id_lookup.
Referenced by CompManager::addPart(), CompManager::checkKnown(), CompManager::createEle(), CompManager::getComp(), CompManager::getMolarMass(), and CompManager::initComp().
CompContainer * getComp (const std::string & name) const
References CompManager::b_comps, and CompManager::getCompIndex().
Referenced by CompManager::addPart(), CompManager::finalizeComp(), CompManager::getDC(), CompManager::getNumMap(), CompManager::getReferenceDensity(), CompManager::isFinalizedComp(), CompManager::setReferenceDensity(), and CompManager::toString().
std::string getCompName (int index) const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::b_comps, and CompManager::getNumComps().
Referenced by CompManager::getDC(), and TEST().
std::string toString (const std::string & name, int indent = 0) const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::b_comps, Origen::doIndent(), CompManager::getComp(), and Origen::toYesNo().
Referenced by TEST().
std::string getNumMap (const std::string & name, std::map< int, double > & map_out) const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::b_comps, and CompManager::getComp().
Referenced by CompManager::getConcMap(), CompManager::getDC(), CompManager::getWtMap(), and TEST().
std::string getWtMap (const std::string & name, std::map< int, double > & map_out) const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::getMolarMasses(), and CompManager::getNumMap().
Referenced by TEST().
std::string getConcMap (const std::string & name, double density, std::map< int, double > & map_out) const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::getMolarMass(), and CompManager::getNumMap().
Referenced by TEST().
std::string getElementalAbundances (int id, std::vector< int > & ids_out, std::vector< double > & nums_out) const
References CompManager::b_lib.
Referenced by CompManager::createEle().
int getNumComps () const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::b_comps.
Referenced by CompManager::getCompName(), CompManager::getDC(), CompManager::initComp(), and TEST().
std::string getDC (DataContainer * dcCompositionList, bool flatten = true) const
Examples:
Core/xf/tests/tstCompManager.cpp.
References CompManager::getComp(), CompManager::getCompName(), CompManager::getMolarMass(), CompManager::getNumComps(), and CompManager::getNumMap().
Referenced by TEST().
std::string printDC (DataContainer * dcCompositionList) static
double getReferenceDensity (const std::string & name) const
References CompManager::getComp().
void setReferenceDensity (const std::string & name, double density)
References CompManager::getComp().
bool renameComp (const std::string & oldName, const std::string & newName)
References CompManager::b_id_lookup.
bool removeComp (const std::string & name)
References CompManager::b_comps, and CompManager::b_id_lookup.
Member Data Documentation
std::map<int, CompContainer*> b_comps protected
map of elements and mixture ids to child mixtures
Referenced by CompManager::finalizeComp(), CompManager::getComp(), CompManager::getCompName(), CompManager::getMolarMass(), CompManager::getNumComps(), CompManager::getNumMap(), CompManager::initComp(), CompManager::removeComp(), CompManager::toString(), and CompManager::~CompManager().
CiMap_t b_id_lookup protected
Referenced by CompManager::getCompIndex(), CompManager::initComp(), CompManager::removeComp(), and CompManager::renameComp().
const ScaleData::StdComp& b_lib protected
std comp library used for molar masses and isotopic content of elements
Referenced by CompManager::checkKnown(), CompManager::getElementalAbundances(), and CompManager::getMolarMass().
The documentation for this class was generated from the following files:
Core/xf/CompManager.h
Core/xf/CompManager.cpp