ORIGEN API: Stepper Class Reference
Stepper Class Reference abstract
Public Member Functions
virtual void initialize (Vec_Str)=0
virtual bool done () const =0
virtual void begin ()=0
virtual bool done_resp_its () const =0
virtual void begin_resp_its ()=0
virtual void set_done_resp_its (bool)=0
virtual size_t resp_its_max () const =0
virtual double resp_its_tol () const =0
virtual size_t step () const =0
virtual double time0 () const =0
virtual double time1 () const =0
virtual double dtime () const =0
virtual size_t resp_its_count () const =0
virtual void update_resp (const Vec_Dbl &)=0
virtual void get_last_resp (Vec_Dbl *) const =0
virtual void get_resp (Vec_Dbl *) const =0
virtual void get_delta_resp (Vec_Dbl *) const =0
virtual void get_rel_delta_resp (Vec_Dbl *) const =0
virtual bool guess_r (double t, Vec_Dbl *) const =0
virtual bool guess_dtrel (Vec_Dbl *dtrel) const =0
virtual size_t guess_dtrel_size () const =0
Friends
std::ostream & operator<< (std::ostream &os, const Stepper &s)
Detailed Description
Examples:
tstMultiZoneDepleter.cpp.
Member Function Documentation
virtual void initialize (Vec_Str) pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual bool done () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void begin () pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual bool done_resp_its () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void begin_resp_its () pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void set_done_resp_its (bool) pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual size_t resp_its_max () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
Referenced by operator<<().
virtual double resp_its_tol () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
Referenced by operator<<().
virtual size_t step () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual double time0 () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual double time1 () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual double dtime () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual size_t resp_its_count () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void update_resp (const Vec_Dbl &) pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void get_last_resp (Vec_Dbl *) const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void get_resp (Vec_Dbl *) const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void get_delta_resp (Vec_Dbl *) const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual void get_rel_delta_resp (Vec_Dbl *) const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual bool guess_r (double t, Vec_Dbl *) const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual bool guess_dtrel (Vec_Dbl * dtrel) const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
virtual size_t guess_dtrel_size () const pure virtual
Implemented in Stepper_fixed.
Examples:
tstMultiZoneDepleter.cpp.
Referenced by operator<<().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Stepper & s) friend
Examples:
tstMultiZoneDepleter.cpp.
The documentation for this class was generated from the following file:
Core/xf/tests/tstMultiZoneDepleter.cpp