ORIGEN API: FakeFactory Class Reference
FakeFactory Class Reference
#include <FakeFactory.h>
Public Member Functions
std::vector< SP_Library > Library_linear2D (Library &obj, std::vector< float > x1_list, std::vector< float > x2_list, float scaleFactor1, float scaleFactor2, std::string name, int seed=164)
Static Public Member Functions
static bool Library_random1 (Library &obj, const int seed=32)
static bool DecayData_random1 (DecayData &obj, const LibraryHeader &def, const int seed=164)
static bool TransitionStructure_random1 (TransitionStructure &obj, const LibraryHeader &def, const int seed=64)
static bool TransitionCoeff_random1 (TransitionCoeff &obj, const LibraryHeader &def, const int seed=164)
static bool StateSet_random1 (StateSet &obj, const int seed=32)
static LibraryHeader createLibraryHeader_random1 ()
static bool DecayData_random2 (DecayData &obj, const int seed=164)
static bool TransitionCoeff_random2 (TransitionCoeff &obj, const int seed=164)
static void Library_linear1D (Library &obj, std::vector< float > x1_list, float scaleFactor, int seed=164)
static bool Library_scale_pwr (Library &obj)
static bool YieldResource_scale (YieldResource &obj)
static bool DecayResource_scale (DecayResource &obj)
static void nuclide_set_addnux1 (Vec_Int &ids)
static void nuclide_set_addnux2 (Vec_Int &ids)
static void nuclide_set_addnux3 (Vec_Int &ids)
static void nuclide_set_addnux4 (Vec_Int &ids)
static void vera_uox_e310 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_uox_e360 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_cool_565 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_cool_600 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_zrb2_e50 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_pyrex_e125 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_uox_e310_gd180 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_waba (Vec_Int &ids, Vec_Dbl &numden)
static void vera_zirc4 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_ss304 (Vec_Int &ids, Vec_Dbl &numden)
static void vera_aic (Vec_Int &ids, Vec_Dbl &numden)
static void vera_b4c (Vec_Int &ids, Vec_Dbl &numden)
static void energy_bounds_mpact_47g (Vec_Dbl &bounds)
static void energy_bounds_master_photon_brems (Vec_Dbl &bounds)
static Vec_Flt createBounds_Scale6p2_56g ()
static Vec_Flt createBounds_Scale6p2_252g ()
static void getUniformFlux (Vec_Flt *flux, const Vec_Flt &bounds)
template<typename T >
static bool getBounds_Scale6p2_56g (T &bounds)
template<typename T >
static bool getBounds_Scale6p2_252g (T &bounds)
static Vec_Str create_melmaccs_ac_activity ()
static Vec_Str create_melmaccs_ac_mass ()
static Vec_Str create_melmaccs_fp_activity ()
static Vec_Str create_melmaccs_fp_mass ()
static Vec_Str create_melmaccs_lt_activity ()
static Vec_Str create_melmaccs_lt_mass ()
static Vec_Int createNuclideIds_scale62 ()
static Vec_Dbl createBounds_revlin (size_t n, double mult)
static Vec_Dbl createIntensity_gprop (size_t n, double mult)
static SP_StateSet newspStateSet_10nuclide ()
static SP_Library newspLibrary_10nuclide ()
static SP_Material newspMaterial_scale_pwr ()
Detailed Description
Examples:
Core/dc/tests/tstLibrary.cpp.
Member Function Documentation
bool Library_random1 (Origen::Library & obj, const int seed = 32) static
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstLibrary.cpp, and Core/dc/tests/tstMaterial.cpp.
References Library::add_transition_coeff(), Origen::createDecayData_random1(), FakeFactory::createLibraryHeader_random1(), Origen::createTransitionCoeff_random1(), Origen::createTransitionStructure_random1(), Library::definition(), Library::set_decay_data(), Library::set_definition(), and Library::set_transition_structure().
Referenced by Origen_FakeFactory_Library_random1(), and TEST().
 {
     //
     // Initialize random number generator
     //
     rand.seed( seed );
     // set library definition by dereferencing smart pointer to new data
     obj.set_definition( createLibraryHeader_random1() );
     // set decay data
     obj.set_decay_data( createDecayData_random1( obj.definition() ) );
     // set transition structure data by dereferencing smart pointer to new data
     obj.set_transition_structure(
         createTransitionStructure_random1( obj.definition() ) );
     //
     // Add 3 burnups by actual smart pointer
     //
     for( int index = 0; index < 3; index++ )
     {
         obj.add_transition_coeff(
             createTransitionCoeff_random1( obj.definition() ) );
     }
     return true;
 }
bool DecayData_random1 (DecayData & obj, const LibraryHeader & def, const int seed = 164) static
Examples:
Core/dc/tests/tstDecayData.cpp, and Core/dc/tests/tstLibrary.cpp.
References Origen::createDecayData_random1().
Referenced by Origen_FakeFactory_DecayData_random1(), LibraryTest::SetUp(), and TEST().
 {
     rand.seed( seed );
     obj = createDecayData_random1( def );
     return true;
 }
bool TransitionStructure_random1 (TransitionStructure & obj, const LibraryHeader & def, const int seed = 64) static
Examples:
Core/dc/tests/tstLibrary.cpp, and Core/dc/tests/tstTransitionStructure.cpp.
References Origen::createTransitionStructure_random1().
Referenced by Origen_FakeFactory_TransitionStructure_random1(), LibraryTest::SetUp(), and TEST().
 {
     rand.seed( seed );
     obj = createTransitionStructure_random1( def );
     return true;
 }
bool TransitionCoeff_random1 (TransitionCoeff & obj, const LibraryHeader & def, const int seed = 164) static
Examples:
Core/dc/tests/tstLibrary.cpp, and Core/dc/tests/tstTransitionCoeff.cpp.
References Origen::createTransitionCoeff_random1().
Referenced by Origen_FakeFactory_TransitionCoeff_random1(), LibraryTest::SetUp(), and TEST().
 {
     rand.seed( seed );
     obj = createTransitionCoeff_random1( def );
     return true;
 }
bool StateSet_random1 (Origen::StateSet & obj, const int seed = 32) static
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstState.cpp, Core/dc/tests/tstStateSet.cpp, and Core/io/tests/tstStateSetIO.cpp.
References StateSet::add_states(), Origen::create_zzzaaai_seq1(), Origen::GATOMS, State::set_alpha_spectra(), State::set_beta_spectra(), Spectrum::set_bounds(), StateInfo::set_case_number(), State::set_concs(), State::set_definition(), StateInfo::set_energy(), StateInfo::set_flux(), State::set_gamma_spectra(), Spectrum::set_intensity(), NeutronSpectra::set_intensity_alphan(), NeutronSpectra::set_intensity_delayn(), NeutronSpectra::set_intensity_sf(), StateInfo::set_library_position(), State::set_neutron_spectra(), Concentrations::set_nuclide_set(), BetaSpectra::set_nuclide_type(), GammaSpectra::set_nuclide_type(), AlphaSpectra::set_nuclide_type(), StateInfo::set_power(), StateInfo::set_step_number(), StateInfo::set_time(), Concentrations::set_units(), and Concentrations::set_vals().
Referenced by Origen_FakeFactory_StateSet_random1(), StateSetIOTester::SetUp(), and TEST().
 {
     //
     // Initialize random number generator
     //
     rand.seed( seed );
     size_t total_nuclides = 2226;
     size_t num_lite_nuclides = 903;
     size_t num_actinide_nuclides = 174;
     size_t num_fission_product_nuclides = 1149;
     size_t num_neutron_groups = 238;
     size_t num_alpha_groups = 252;
     size_t num_gamma_groups = 44;
     size_t num_beta_groups = 200;
     // construct ids
     Vec_Int ids = create_zzzaaai_seq1( total_nuclides );
     // legacy ZZZAAAI format
     NuclideSet nuc_set( num_lite_nuclides,
                         num_actinide_nuclides,
                         num_fission_product_nuclides,
                         ids );
     //
     // Generate one case with 44 steps
     //
     double b0 = 0;
     double t0 = 0;
     for( size_t i = 0; i < 44; i++ )
     {
         State state;
         StateInfo header;
         Concentrations concs;
         NeutronSpectra neutron_spectra;
         GammaSpectra gamma_spectra;
         AlphaSpectra alpha_spectra;
         BetaSpectra beta_spectra;
         //
         // Set header information
         //
         header.set_case_number( 1 );
         header.set_step_number( i );
         header.set_library_position( 1 );
         header.set_power( randomVal<float>( 10, 20 ) );
         header.set_energy( b0 );
         header.set_flux( randomVal<float>( 1e12, 1e15 ) );
         header.set_time( t0 );
         state.set_definition( header );
         // increment
         b0 += randomVal<float>( 1, 2 );
         t0 += randomVal<float>( 1, 2 );
         //
         // Set concentrations data
         //
         concs.set_nuclide_set( nuc_set );
         concs.set_units( Origen::GATOMS );
         Vec_Dbl vals( total_nuclides );
         for( size_t n = 0; n < total_nuclides; n++ )
         {
             if( ( ( n % 3 == 1 ) && ( i % 2 == 0 ) ) ||
                 ( n % 3 == 2 && i % 2 == 1 ) || ( n % 3 == 0 ) )
             {
                 vals[n] = 1.0;
             }
             else
             {
                 vals[n] = 0.0;
             }
         }
         concs.set_vals( vals );
         state.set_concs( concs );
         //
         // Set neutron spectra
         //
         if( i % 4 == 0 )
         {
             Vec_Dbl intensity( num_neutron_groups );
             Vec_Dbl intensity_sf( num_neutron_groups );
             Vec_Dbl intensity_alphan( num_neutron_groups );
             Vec_Dbl intensity_delayn( num_neutron_groups );
             Vec_Dbl bounds( num_neutron_groups + 1 );
             fillRandomVec( intensity, 1e2, 1e3 );
             fillRandomVecDecreasing( bounds, 1e-5, 1e8 );
             fillRandomVec( intensity_sf, 1e1, 1e2 );
             fillRandomVec( intensity_alphan, 1e1, 1e2 );
             fillRandomVec( intensity_delayn, 1e1, 1e2 );
             neutron_spectra.set_bounds( bounds );
             neutron_spectra.set_intensity( intensity );
             neutron_spectra.set_intensity_sf( intensity_sf );
             neutron_spectra.set_intensity_alphan( intensity_alphan );
             neutron_spectra.set_intensity_delayn( intensity_delayn );
             state.set_neutron_spectra( neutron_spectra );
         }
         //
         // Set gamma spectra
         //
         if( i % 4 == 1 )
         {
             Vec_Dbl intensity( num_gamma_groups );
             Vec_Dbl bounds( num_gamma_groups + 1 );
             fillRandomVec( intensity, 1e2, 1e3 );
             fillRandomVecDecreasing( bounds, 1e-5, 1e8 );
             gamma_spectra.set_bounds( bounds );
             gamma_spectra.set_intensity( intensity );
             gamma_spectra.set_nuclide_type( randomVal<int>( 1, 4 ) );
             state.set_gamma_spectra( gamma_spectra );
         }
         //
         // Set alpha spectra
         //
         if( i % 4 == 2 )
         {
             Vec_Dbl intensity( num_alpha_groups );
             Vec_Dbl bounds( num_alpha_groups + 1 );
             fillRandomVec( intensity, 1e2, 1e3 );
             fillRandomVecDecreasing( bounds, 1e-5, 1e8 );
             alpha_spectra.set_bounds( bounds );
             alpha_spectra.set_intensity( intensity );
             alpha_spectra.set_nuclide_type( randomVal<int>( 1, 4 ) );
             state.set_alpha_spectra( alpha_spectra );
         }
         //
         // Set beta spectra
         //
         if( i % 4 == 3 )
         {
             Vec_Dbl intensity( num_beta_groups );
             Vec_Dbl bounds( num_beta_groups + 1 );
             fillRandomVec( intensity, 1e2, 1e3 );
             fillRandomVecDecreasing( bounds, 1e-5, 1e8 );
             beta_spectra.set_bounds( bounds );
             beta_spectra.set_intensity( intensity );
             beta_spectra.set_nuclide_type( randomVal<int>( 1, 4 ) );
             state.set_beta_spectra( beta_spectra );
         }
         //
         // Save state
         //
         obj.add_states( state );
     }  // loop step number
     return true;
 }
LibraryHeader createLibraryHeader_random1 () static
Examples:
Core/dc/tests/tstDecayData.cpp, Core/dc/tests/tstLibraryHeader.cpp, Core/dc/tests/tstTransitionCoeff.cpp, and Core/dc/tests/tstTransitionStructure.cpp.
References Origen::createNuclideSet_random1(), LibraryHeader::set_day_made(), LibraryHeader::set_month_made(), LibraryHeader::set_nuclide_set(), LibraryHeader::set_title(), and LibraryHeader::set_year_made().
Referenced by FakeFactory::Library_random1(), and TEST().
 {
     LibraryHeader obj;
     obj.set_nuclide_set( createNuclideSet_random1() );
     obj.set_day_made( 29 );
     obj.set_month_made( 9 );
     obj.set_year_made( 2012 );
     obj.set_title(
         "Jordan's randomly generated OrigenLibrary object with even length**" );
     return obj;
 }
bool DecayData_random2 (Origen::DecayData & obj, const int seed = 164) static
Examples:
Core/dc/tests/tstDecayData.cpp.
References DecayData::abund_of_lite_nuclides, CREATE_INT_VEC_DIRECT, DecayData::decay_constants, DecayData::fissionable_nuclide_ids, DecayData::masses, DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, and DecayData::recoverable_energy_values.
Referenced by Origen_FakeFactory_DecayData_random2(), and TEST().
 {
     rand.seed( seed );
     int total_nuclides = 100;
     int nfn = 30;  // nuclides with fission yields
     int total_lite_nuclides = 30;
     obj.decay_constants.resize( total_nuclides );
     obj.recoverable_energy_values.resize( total_nuclides );
     obj.q_fractions_from_photons.resize( total_nuclides );
     obj.rcg_for_air.resize( total_nuclides );
     obj.rcg_for_water.resize( total_nuclides );
     obj.abund_of_lite_nuclides.resize( total_lite_nuclides );
     obj.fissionable_nuclide_ids.resize( nfn );
     obj.masses.resize( total_nuclides );
     fillRandomVec<float>( obj.decay_constants, 0, 1.0e-3 );
     fillRandomVec<float>( obj.recoverable_energy_values, 0, 10.0 );
     fillRandomVec<float>( obj.q_fractions_from_photons, 0, 1.0 );
     fillRandomVec<float>( obj.rcg_for_air, 0, 13. );
     fillRandomVec<float>( obj.rcg_for_water, 0, 17. );
     fillRandomVec<float>( obj.abund_of_lite_nuclides, 0, 1.0 );
     CREATE_INT_VEC_DIRECT( fissionable_nuclide_ids, nfn, 922330, 962550 )
     fillRandomVec<float>( obj.masses, 1., 240. );
     return true;
 }
bool TransitionCoeff_random2 (Origen::TransitionCoeff & obj, const int seed = 164) static
Examples:
Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstTransitionCoeff.cpp, and Core/fn/tests/tstinterp.cpp.
References CREATE_FLOAT_VEC, and TransitionCoeff::set_burnup().
Referenced by Origen_FakeFactory_TransitionCoeff_random2(), and TEST().
 {
     rand.seed( seed );
     size_t itran = 4000;
     size_t igrp = 44;
     size_t ilite = 100;
     size_t iact = 20;
     size_t ineu = ilite + iact;
     size_t ifp = 300;
     size_t itot = ilite + iact + ifp;
     obj.set_burnup( randomVal<float>( 0, 60000 ) );
     CREATE_FLOAT_VEC( matrix, itran, 0, 1e-1 )
     CREATE_FLOAT_VEC( fission_xs, iact, 0, 23.0 )
     CREATE_FLOAT_VEC( flux, igrp, 0, 1.0 )
     CREATE_FLOAT_VEC( neutron_yields, ineu, 0, 2.5 )
     CREATE_FLOAT_VEC( loss_xs, itot, 0, 43.0 )
     CREATE_FLOAT_VEC( kappa_capture, itot, 0, 5.0 )
     CREATE_FLOAT_VEC( kappa_fission, iact, 0, 200.0 )
     return true;
 }
void Library_linear1D (Library & obj, std::vector< float > x1_list, float scaleFactor, int seed = 164) static
Examples:
Core/dc/tests/tstLibrary.cpp, and Core/fn/tests/tstinterp.cpp.
References Library::add_transition_coeff(), TransitionCoeff::scale(), Library::transition_coeff_at(), and Library::transition_coeff_size().
Referenced by FakeFactory::Library_linear2D(), and TEST().
 {
     Require( scaleFactor > 0 );
     Require( x1_list.size() > 0 && increasing( x1_list ) );
     // Should expect exactly one TC on the Library, which will be used as the
     // basis
     // for linear extrapolation
     Require( obj.transition_coeff_size() == 1 );
     std::srand( seed );
     // Create numTC transitionCoeffs, linearly scaled, wherein the last TC is
     // the original scaled by scaleFactor
     for( size_t i = 1; i != x1_list.size(); ++i )
     {
         double scaleThis = ( scaleFactor - 1 ) *
                                ( x1_list[i] - x1_list.front() ) /
                                ( x1_list.back() - x1_list.front() ) +
                            1;
         auto newTC = obj.transition_coeff_at( 0 );
         newTC.scale( scaleThis );
         newTC.set_burnup( x1_list[i] );
         obj.add_transition_coeff( newTC );
     }
 }
std::vector< SP_Library > Library_linear2D (Library & obj, std::vector< float > x1_list, std::vector< float > x2_list, float scaleFactor1, float scaleFactor2, std::string name, int seed = 164)
Examples:
Core/dc/tests/tstLibrary.cpp.
References TransitionCoeff::burnup(), Library::clone(), FakeFactory::Library_linear1D(), TransitionCoeff::scale(), TransitionCoeff::set_burnup(), TagManager::setInterpTag(), and Library::transition_coeff_size().
Referenced by TEST().
 {
     Require( scaleFactor1 > 0 && scaleFactor2 > 0 );
     Require( x1_list.size() > 0 && x2_list.size() > 0 );
     Require( increasing( x1_list ) && increasing( x2_list ) );
     Require( obj.transition_coeff_size() == 1 );
     // Base library modification
     Library_linear1D( obj, x1_list, scaleFactor1, seed );
     std::vector<SP_Library> objVec;
     for( size_t j = 0; j < x2_list.size(); j++ )
     {
         double scaleThis2 = ( scaleFactor2 - 1 ) *
                                 ( x2_list[j] - x2_list.front() ) /
                                 ( x2_list.back() - x2_list.front() ) +
                             1;
         //!\todo: remove need for this clone operation
         SP_Library scaledLib = obj.clone();
         TagManager tmTmp = scaledLib->tag_manager();
         tmTmp.setInterpTag( name, double( x2_list[j] ) );
         scaledLib->set_tag_manager( tmTmp );
         for( size_t i = 0; i < scaledLib->transition_coeff_size(); ++i )
         {
             TransitionCoeff newTC = scaledLib->transition_coeff_at( i );
             float buOrig = newTC.burnup();
             newTC.scale( scaleThis2 );
             newTC.set_burnup(
                 buOrig );  // don't want to scale burnup, just responses
             scaledLib->set_transition_coeff_at( newTC, i );
         }
         objVec.push_back( scaledLib );
     }
     return ( objVec );
 }
bool Library_scale_pwr (Origen::Library & obj) static
Examples:
Core/dc/tests/tstMaterial.cpp, Core/dc/tests/tstNuclideSet.cpp, Core/dc/tests/tstTransitionMatrixP.cpp, Core/io/tests/tstLibraryIO.cpp, Core/io/tests/tstMaterialBuffer.cpp, Core/xf/tests/tstMultiZoneDepleter.cpp, Solver/cram/tests/tstSolver_cram.cpp, Solver/matrex/src/tests/tstKernelMatrexC.cpp, Solver/matrex/tests/tstSolver_matrex.cpp, and Solver/radau5/src/tests/tstKernelRadau5C.cpp.
Referenced by FakeFactory::newspMaterial_scale_pwr(), LibraryIOTester::SetUp(), MultiZoneDepleterTester::SetUp(), MaterialTester::SetUp(), and TEST().
 {
     ScaleUtils::IO::DB opts;
     Origen::LibraryIO io;
     // load mass as mass numbers (A) instead of actual
     opts.set<bool>( "legacyMass", true );
     bool status = io.load( obj, pwrlib_filepath, opts );
     jDebugBlock( std::cerr << "Origen::FakeFactory::Library_scale_pwr:\n";
                  opts.writeToJson( std::cerr ); );
     return status;
 }
bool YieldResource_scale (Origen::YieldResource & obj) static
Examples:
Core/re/tests/tstYieldResource.cpp.
Referenced by YieldResourceTester::SetUp().
 {
     ScaleUtils::IO::DB opts;
     Origen::YieldResourceIO io;
     bool status = io.load( obj, yields_filepath, opts );
     jDebugBlock( std::cerr << "Origen::FakeFactory::YieldResource_scale:\n";
                  opts.writeToJson( std::cerr ); );
     return status;
 }
bool DecayResource_scale (Origen::DecayResource & obj) static
Examples:
Core/dc/tests/tstConcentrationConverter.cpp.
Referenced by TEST().
 {
     ScaleUtils::IO::DB opts;
     Origen::DecayResourceIO io;
     bool status = io.load( obj, decay_filepath, opts );
     jDebugBlock( std::cerr << "Origen::FakeFactory::DecayResource_scale:\n";
                  opts.writeToJson( std::cerr ); );
     return status;
 }
void nuclide_set_addnux1 (Vec_Int & ids) static
 {
     ScaleData::AdditionalNuclide nuc;
     std::shared_ptr<IntegerList> nucs = nuc.getAdditionalNuclides( 1 );
     ids.insert( ids.end(), nucs->begin(), nucs->end() );
 }
void nuclide_set_addnux2 (Vec_Int & ids) static
 {
     ScaleData::AdditionalNuclide nuc;
     std::shared_ptr<IntegerList> nucs = nuc.getAdditionalNuclides( 2 );
     ids.insert( ids.end(), nucs->begin(), nucs->end() );
 }
void nuclide_set_addnux3 (Vec_Int & ids) static
 {
     ScaleData::AdditionalNuclide nuc;
     std::shared_ptr<IntegerList> nucs = nuc.getAdditionalNuclides( 3 );
     ids.insert( ids.end(), nucs->begin(), nucs->end() );
 }
void nuclide_set_addnux4 (Vec_Int & ids) static
Examples:
Core/dc/tests/tstConcentrations.cpp, Solver/cram/tests/tstSolver_cram.cpp, and Solver/matrex/tests/tstSolver_matrex.cpp.
Referenced by print_summary_1(), and TEST().
 {
     ScaleData::AdditionalNuclide nuc;
     std::shared_ptr<IntegerList> nucs = nuc.getAdditionalNuclides( 4 );
     ids.insert( ids.end(), nucs->begin(), nucs->end() );
 }
void vera_uox_e310 (Vec_Int & ids, Vec_Dbl & numden) static
Examples:
Core/dc/tests/tstConcentrations.cpp.
Referenced by TEST().
 {
     std::map<int, double> map_numden;
     map_numden[8016] = 4.57642E-02;
     map_numden[92234] = 6.11864E-06;
     map_numden[92235] = 7.18132E-04;
     map_numden[92236] = 3.29861E-06;
     map_numden[92238] = 2.21546E-02;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_uox_e360 (Vec_Int & ids, Vec_Dbl & numden) static
Examples:
Core/dc/tests/tstMaterial.cpp, Core/fn/tests/tsttabulate.cpp, Core/io/tests/tstMaterialBuffer.cpp, Manager/mzd/tests/tstParallelDepletion.cpp, Solver/cram/tests/tstSolver_cram.cpp, and Solver/matrex/tests/tstSolver_matrex.cpp.
Referenced by TabulateMaterial::SetUp(), MaterialTester::SetUp(), and TEST().
 {
     std::map<int, double> map_numden;
     map_numden[92234] = 7.21203E-06;
     map_numden[92235] = 8.33952E-04;
     map_numden[92236] = 3.82913E-06;
     map_numden[92238] = 2.20384E-02;
     map_numden[8016] = 4.57669E-02;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_cool_565 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[1001] = 4.96224E-02;
     map_numden[8016] = 2.48112E-02;
     map_numden[5010] = 1.07070E-05;
     map_numden[5011] = 4.30971E-05;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_cool_600 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[1001] = 4.41459E-02;
     map_numden[8016] = 2.20729E-02;
     map_numden[5010] = 9.52537E-06;
     map_numden[5011] = 3.83408E-05;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_zrb2_e50 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[5010] = 2.16410E-02;
     map_numden[5011] = 1.96824E-02;
     map_numden[40090] = 1.06304E-02;
     map_numden[40091] = 2.31824E-03;
     map_numden[40092] = 3.54348E-03;
     map_numden[40094] = 3.59100E-03;
     map_numden[40096] = 5.78528E-04;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_pyrex_e125 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[5010] = 9.63266E-04;
     map_numden[5011] = 3.90172E-03;
     map_numden[8016] = 4.67761E-02;
     map_numden[14028] = 1.81980E-02;
     map_numden[14029] = 9.24474E-04;
     map_numden[14030] = 6.10133E-04;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_uox_e310_gd180 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[92234] = 3.18096E-06;
     map_numden[92235] = 3.90500E-04;
     map_numden[92236] = 1.79300E-06;
     map_numden[92238] = 2.10299E-02;
     map_numden[64152] = 3.35960E-06;
     map_numden[64154] = 3.66190E-05;
     map_numden[64155] = 2.48606E-04;
     map_numden[64156] = 3.43849E-04;
     map_numden[64157] = 2.62884E-04;
     map_numden[64158] = 4.17255E-04;
     map_numden[64160] = 3.67198E-04;
     map_numden[8016] = 4.53705E-02;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_waba (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[5010] = 2.98553E-03;
     map_numden[5011] = 1.21192E-02;
     map_numden[6012] = 3.77001E-03;
     map_numden[8016] = 5.85563E-02;
     map_numden[13027] = 3.90223E-02;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_zirc4 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[24050] = 3.30121E-06;
     map_numden[24052] = 6.36606E-05;
     map_numden[24053] = 7.21860E-06;
     map_numden[24054] = 1.79686E-06;
     map_numden[26054] = 8.68307E-06;
     map_numden[26056] = 1.36306E-04;
     map_numden[26057] = 3.14789E-06;
     map_numden[26058] = 4.18926E-07;
     map_numden[40090] = 2.18865E-02;
     map_numden[40091] = 4.77292E-03;
     map_numden[40092] = 7.29551E-03;
     map_numden[40094] = 7.39335E-03;
     map_numden[40096] = 1.19110E-03;
     map_numden[50112] = 4.68066E-06;
     map_numden[50114] = 3.18478E-06;
     map_numden[50115] = 1.64064E-06;
     map_numden[50116] = 7.01616E-05;
     map_numden[50117] = 3.70592E-05;
     map_numden[50118] = 1.16872E-04;
     map_numden[50119] = 4.14504E-05;
     map_numden[50120] = 1.57212E-04;
     map_numden[50122] = 2.23417E-05;
     map_numden[50124] = 2.79392E-05;
     map_numden[72174] = 3.54138E-09;
     map_numden[72176] = 1.16423E-07;
     map_numden[72177] = 4.11686E-07;
     map_numden[72178] = 6.03806E-07;
     map_numden[72179] = 3.01460E-07;
     map_numden[72180] = 7.76449E-07;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_ss304 (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[6012] = 3.20895E-04;
     map_numden[14028] = 1.58197E-03;
     map_numden[14029] = 8.03653E-05;
     map_numden[14030] = 5.30394E-05;
     map_numden[15031] = 6.99938E-05;
     map_numden[24050] = 7.64915E-04;
     map_numden[24052] = 1.47506E-02;
     map_numden[24053] = 1.67260E-03;
     map_numden[24054] = 4.16346E-04;
     map_numden[25055] = 1.75387E-03;
     map_numden[26054] = 3.44776E-03;
     map_numden[26056] = 5.41225E-02;
     map_numden[26057] = 1.24992E-03;
     map_numden[26058] = 1.66342E-04;
     map_numden[28058] = 5.30854E-03;
     map_numden[28060] = 2.04484E-03;
     map_numden[28061] = 8.88879E-05;
     map_numden[28062] = 2.83413E-04;
     map_numden[28064] = 7.21770E-05;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_aic (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[47107] = 2.36159E-02;
     map_numden[47109] = 2.19403E-02;
     map_numden[48106] = 3.41523E-05;
     map_numden[48108] = 2.43165E-05;
     map_numden[48110] = 3.41250E-04;
     map_numden[48111] = 3.49720E-04;
     map_numden[48112] = 6.59276E-04;
     map_numden[48113] = 3.33873E-04;
     map_numden[48114] = 7.84957E-04;
     map_numden[48116] = 2.04641E-04;
     map_numden[49113] = 3.44262E-04;
     map_numden[49115] = 7.68050E-03;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void vera_b4c (Vec_Int & ids, Vec_Dbl & numden) static
 {
     std::map<int, double> map_numden;
     map_numden[5010] = 1.52689E-02;
     map_numden[5011] = 6.14591E-02;
     map_numden[6012] = 1.91820E-02;
     ScaleSTL::map_to_vectors( map_numden, &ids, &numden );
 }
void energy_bounds_mpact_47g (Vec_Dbl & bounds) static
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
Referenced by Origen::test::TEST().
 {
     Vec_Dbl eb(
         {2.000000E+07, 6.065300E+06, 3.678800E+06, 2.231299E+06, 1.353400E+06,
          8.208500E+05, 4.978702E+05, 1.831601E+05, 6.737900E+04, 9.118801E+03,
          2.034700E+03, 1.300704E+02, 7.889325E+01, 4.785117E+01, 2.902291E+01,
          1.371000E+01, 1.209903E+01, 8.315287E+00, 7.338215E+00, 6.476017E+00,
          5.715008E+00, 5.043477E+00, 4.450897E+00, 3.927903E+00, 2.382393E+00,
          1.855391E+00, 1.457402E+00, 1.235105E+00, 1.166404E+00, 1.125397E+00,
          1.072203E+00, 1.013699E+00, 9.710043E-01, 9.099967E-01, 7.820830E-01,
          6.250621E-01, 5.032318E-01, 3.576701E-01, 2.705213E-01, 1.844302E-01,
          1.457206E-01, 1.115699E-01, 8.196816E-02, 5.692194E-02, 4.275520E-02,
          3.061288E-02, 1.239596E-02, 1.000000E-05} );
     Ensure( eb.size() == 48 );
     bounds.swap( eb );
 }
void energy_bounds_master_photon_brems (Vec_Dbl & bounds) static
 {
     Vec_Dbl eb( {1.40e+01, 1.30e+01, 1.20e+01, 1.10e+01, 1.00e+01, 9.00e+00,
                  8.00e+00, 7.00e+00, 6.00e+00, 5.00e+00, 4.00e+00, 3.60e+00,
                  3.20e+00, 2.80e+00, 2.40e+00, 2.00e+00, 1.90e+00, 1.80e+00,
                  1.70e+00, 1.60e+00, 1.50e+00, 1.40e+00, 1.30e+00, 1.20e+00,
                  1.10e+00, 1.00e+00, 9.00e-01, 8.00e-01, 7.00e-01, 6.00e-01,
                  5.00e-01, 4.40e-01, 3.80e-01, 3.20e-01, 2.60e-01, 2.00e-01,
                  1.80e-01, 1.60e-01, 1.40e-01, 1.20e-01, 1.00e-01, 9.00e-02,
                  8.00e-02, 7.00e-02, 6.00e-02, 5.00e-02, 4.60e-02, 4.20e-02,
                  3.80e-02, 3.40e-02, 3.00e-02, 2.80e-02, 2.60e-02, 2.40e-02,
                  2.20e-02, 2.00e-02, 1.90e-02, 1.80e-02, 1.70e-02, 1.60e-02,
                  1.50e-02, 1.40e-02, 1.30e-02, 1.20e-02, 1.10e-02, 1.00e-02,
                  9.00e-03, 8.00e-03, 7.00e-03, 6.00e-03, 5.00e-03} );
     Ensure( eb.size() == 71 );
     bounds.swap( eb );
 }
Vec_Flt createBounds_Scale6p2_56g () static
Referenced by FakeFactory::getBounds_Scale6p2_56g().
 {
     Vec_Flt eb{2.000e+07, 6.434e+06, 4.304e+06, 3.000e+06, 1.850e+06, 1.500e+06,
                1.200e+06, 8.611e+05, 7.500e+05, 6.000e+05, 4.700e+05, 3.300e+05,
                2.700e+05, 2.000e+05, 5.000e+04, 2.000e+04, 1.700e+04, 3.740e+03,
                2.250e+03, 1.915e+02, 1.877e+02, 1.175e+02, 1.160e+02, 1.050e+02,
                1.012e+02, 6.750e+01, 6.500e+01, 3.713e+01, 3.600e+01, 2.175e+01,
                2.120e+01, 2.050e+01, 7.000e+00, 6.875e+00, 6.500e+00, 6.250e+00,
                5.000e+00, 1.130e+00, 1.080e+00, 1.010e+00, 6.250e-01, 4.500e-01,
                3.750e-01, 3.500e-01, 3.250e-01, 2.500e-01, 2.000e-01, 1.500e-01,
                1.000e-01, 8.000e-02, 6.000e-02, 5.000e-02, 4.000e-02, 2.530e-02,
                1.000e-02, 4.000e-03, 1.000e-05};
     Ensure( eb.size() == 57 );
     return eb;
 }
Vec_Flt createBounds_Scale6p2_252g () static
Referenced by FakeFactory::getBounds_Scale6p2_252g().
 {
     Vec_Flt eb{2.000e+07, 1.733e+07, 1.568e+07, 1.455e+07, 1.384e+07, 1.284e+07,
                1.000e+07, 8.187e+06, 6.434e+06, 4.800e+06, 4.304e+06, 3.000e+06,
                2.479e+06, 2.354e+06, 1.850e+06, 1.500e+06, 1.400e+06, 1.356e+06,
                1.317e+06, 1.250e+06, 1.200e+06, 1.100e+06, 1.010e+06, 9.200e+05,
                9.000e+05, 8.750e+05, 8.611e+05, 8.200e+05, 7.500e+05, 6.790e+05,
                6.700e+05, 6.000e+05, 5.730e+05, 5.500e+05, 4.920e+05, 4.700e+05,
                4.400e+05, 4.200e+05, 4.000e+05, 3.300e+05, 2.700e+05, 2.000e+05,
                1.490e+05, 1.283e+05, 1.000e+05, 8.500e+04, 8.200e+04, 7.500e+04,
                7.300e+04, 6.000e+04, 5.200e+04, 5.000e+04, 4.500e+04, 3.000e+04,
                2.000e+04, 1.700e+04, 1.300e+04, 9.500e+03, 8.030e+03, 5.700e+03,
                3.900e+03, 3.740e+03, 3.000e+03, 2.500e+03, 2.250e+03, 2.200e+03,
                1.800e+03, 1.550e+03, 1.500e+03, 1.150e+03, 9.500e+02, 6.830e+02,
                6.700e+02, 5.500e+02, 3.050e+02, 2.850e+02, 2.400e+02, 2.200e+02,
                2.095e+02, 2.074e+02, 2.020e+02, 1.930e+02, 1.915e+02, 1.885e+02,
                1.877e+02, 1.800e+02, 1.700e+02, 1.430e+02, 1.220e+02, 1.190e+02,
                1.175e+02, 1.160e+02, 1.130e+02, 1.080e+02, 1.050e+02, 1.012e+02,
                9.700e+01, 9.000e+01, 8.170e+01, 8.000e+01, 7.600e+01, 7.200e+01,
                6.750e+01, 6.500e+01, 6.300e+01, 6.100e+01, 5.800e+01, 5.340e+01,
                5.060e+01, 4.830e+01, 4.520e+01, 4.400e+01, 4.240e+01, 4.100e+01,
                3.960e+01, 3.910e+01, 3.800e+01, 3.763e+01, 3.727e+01, 3.713e+01,
                3.700e+01, 3.600e+01, 3.550e+01, 3.500e+01, 3.375e+01, 3.325e+01,
                3.175e+01, 3.125e+01, 3.000e+01, 2.750e+01, 2.500e+01, 2.250e+01,
                2.175e+01, 2.120e+01, 2.050e+01, 2.000e+01, 1.940e+01, 1.850e+01,
                1.700e+01, 1.600e+01, 1.440e+01, 1.290e+01, 1.190e+01, 1.150e+01,
                1.000e+01, 9.100e+00, 8.100e+00, 7.150e+00, 7.000e+00, 6.875e+00,
                6.750e+00, 6.500e+00, 6.250e+00, 6.000e+00, 5.400e+00, 5.000e+00,
                4.700e+00, 4.100e+00, 3.730e+00, 3.500e+00, 3.200e+00, 3.100e+00,
                3.000e+00, 2.970e+00, 2.870e+00, 2.770e+00, 2.670e+00, 2.570e+00,
                2.470e+00, 2.380e+00, 2.300e+00, 2.210e+00, 2.120e+00, 2.000e+00,
                1.940e+00, 1.860e+00, 1.770e+00, 1.680e+00, 1.590e+00, 1.500e+00,
                1.450e+00, 1.400e+00, 1.350e+00, 1.300e+00, 1.250e+00, 1.225e+00,
                1.200e+00, 1.175e+00, 1.150e+00, 1.140e+00, 1.130e+00, 1.120e+00,
                1.110e+00, 1.100e+00, 1.090e+00, 1.080e+00, 1.070e+00, 1.060e+00,
                1.050e+00, 1.040e+00, 1.030e+00, 1.020e+00, 1.010e+00, 1.000e+00,
                9.750e-01, 9.500e-01, 9.250e-01, 9.000e-01, 8.500e-01, 8.000e-01,
                7.500e-01, 7.000e-01, 6.500e-01, 6.250e-01, 6.000e-01, 5.500e-01,
                5.000e-01, 4.500e-01, 4.000e-01, 3.750e-01, 3.500e-01, 3.250e-01,
                3.000e-01, 2.750e-01, 2.500e-01, 2.250e-01, 2.000e-01, 1.750e-01,
                1.500e-01, 1.250e-01, 1.000e-01, 9.000e-02, 8.000e-02, 7.000e-02,
                6.000e-02, 5.000e-02, 4.000e-02, 3.000e-02, 2.530e-02, 1.000e-02,
                7.500e-03, 5.000e-03, 4.000e-03, 3.000e-03, 2.500e-03, 2.000e-03,
                1.500e-03, 1.200e-03, 1.000e-03, 7.500e-04, 5.000e-04, 1.000e-04,
                1.000e-05};
     Ensure( eb.size() == 253 );
     return eb;
 }
void getUniformFlux (Vec_Flt * flux, const Vec_Flt & bounds) static
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
Referenced by Origen_FakeFactory_getUniformFlux(), and Origen::test::TEST().
 {
     Require( flux != nullptr );
     Require( bounds.size() > 1 );
     flux->resize( bounds.size() - 1 );
     for( size_t i = 0; i < flux->size(); ++i )
     {
         ( *flux )[i] = bounds[i] - bounds[i + 1];
     }
 }
static bool getBounds_Scale6p2_56g (T & bounds) inline static
References FakeFactory::createBounds_Scale6p2_56g().
Referenced by Origen_FakeFactory_getBounds_Scale6p2_56g().
     {
         Vec_Flt eb( createBounds_Scale6p2_56g() );
         bounds.assign( eb.begin(), eb.end() );
         return true;
     }
static bool getBounds_Scale6p2_252g (T & bounds) inline static
References FakeFactory::createBounds_Scale6p2_252g().
Referenced by Origen_FakeFactory_getBounds_Scale6p2_252g().
     {
         Vec_Flt eb( createBounds_Scale6p2_252g() );
         bounds.assign( eb.begin(), eb.end() );
         return true;
     }
Vec_Str create_melmaccs_ac_activity () static
 {
     Vec_Str ac_activity = {
         "TL207",  "TL208", "PB211",  "PB212",  "BI211",  "BI212", "PO212",
         "PO215",  "PO216", "RN219",  "RN220",  "RA223",  "RA224", "AC227",
         "TH227",  "TH228", "TH230",  "TH231",  "TH233",  "TH234", "PA231",
         "PA232",  "PA233", "PA234M", "PA234",  "U232",   "U233",  "U234",
         "U235",   "U236",  "U237",   "U238",   "U239",   "U240",  "NP235",
         "NP236M", "NP237", "NP238",  "NP239",  "NP240M", "NP240", "PU236",
         "PU237",  "PU238", "PU239",  "PU240",  "PU241",  "PU242", "PU243",
         "PU245",  "AM240", "AM241",  "AM242M", "AM242",  "AM243", "AM244M",
         "AM244",  "AM245", "CM241",  "CM242",  "CM243",  "CM244", "CM245",
         "CM246",  "CM249", "BK249"};
     return ac_activity;
 }
Vec_Str create_melmaccs_ac_mass () static
 {
     Vec_Str ac_mass = {"HE4",    "TH230", "TH232", "PA231",  "U232",  "U233",
                        "U234",   "U235",  "U236",  "U237",   "U238",  "U239",
                        "NP236",  "NP237", "NP238", "NP239",  "NP240", "PU236",
                        "PU237",  "PU238", "PU239", "PU240",  "PU241", "PU242",
                        "PU243",  "PU244", "AM241", "AM242M", "AM242", "AM243",
                        "AM244M", "AM244", "CM242", "CM243",  "CM244", "CM245",
                        "CM246",  "CM247"};
     return ac_mass;
 }
Vec_Str create_melmaccs_fp_activity () static
 {
     Vec_Str fp_activity = {
         "H3",     "C14",    "ZN69",   "CO72",   "NI72",   "CU72",   "ZN72",
         "GA72",   "CO73",   "NI73",   "CU73",   "ZN73",   "GA73",   "GE73M",
         "CO74",   "NI74",   "CU74",   "ZN74",   "GA74",   "NI75",   "CU75",
         "ZN75",   "GA75",   "GE75",   "GE75M",  "NI76",   "CU76",   "ZN76",
         "GA76",   "AS76",   "NI77",   "CU77",   "ZN77",   "GA77",   "GE77",
         "GE77M",  "AS77",   "SE77M",  "NI78",   "CU78",   "ZN78",   "GA78",
         "GE78",   "AS78",   "CU79",   "ZN79",   "GA79",   "GE79",   "AS79",
         "SE79",   "SE79M",  "BR79M",  "CU80",   "ZN80",   "GA80",   "GE80",
         "AS80",   "BR80",   "BR80M",  "CU81",   "ZN81",   "GA81",   "GE81",
         "AS81",   "SE81",   "SE81M",  "KR81M",  "ZN82",   "GA82",   "GE82",
         "AS82",   "AS82M",  "BR82",   "BR82M",  "ZN83",   "GA83",   "GE83",
         "AS83",   "SE83",   "SE83M",  "BR83",   "KR83M",  "GA84",   "GE84",
         "AS84",   "SE84",   "BR84",   "BR84M",  "GE85",   "AS85",   "SE85",
         "SE85M",  "BR85",   "KR85",   "KR85M",  "GE86",   "AS86",   "SE86",
         "BR86",   "BR86M",  "RB86",   "RB86M",  "GE87",   "AS87",   "SE87",
         "BR87",   "KR87",   "SR87M",  "GE88",   "AS88",   "SE88",   "BR88",
         "KR88",   "RB88",   "AS89",   "SE89",   "BR89",   "KR89",   "RB89",
         "SR89",   "Y89M",   "SE90",   "BR90",   "KR90",   "RB90",   "RB90M",
         "SR90",   "Y90",    "Y90M",   "SE91",   "BR91",   "KR91",   "RB91",
         "SR91",   "Y91",    "Y91M",   "SE92",   "BR92",   "KR92",   "RB92",
         "SR92",   "Y92",    "BR93",   "KR93",   "RB93",   "SR93",   "Y93",
         "ZR93",   "NB93M",  "BR94",   "KR94",   "RB94",   "SR94",   "Y94",
         "NB94",   "NB94M",  "BR95",   "KR95",   "RB95",   "SR95",   "Y95",
         "ZR95",   "NB95",   "NB95M",  "BR96",   "KR96",   "RB96",   "SR96",
         "Y96",    "NB96",   "KR97",   "RB97",   "SR97",   "Y97",    "ZR97",
         "NB97",   "NB97M",  "KR98",   "RB98",   "SR98",   "Y98",    "ZR98",
         "NB98",   "NB98M",  "RB99",   "SR99",   "Y99",    "ZR99",   "NB99",
         "NB99M",  "MO99",   "TC99",   "TC99M",  "RB100",  "SR100",  "Y100",
         "ZR100",  "NB100",  "NB100M", "TC100",  "SR101",  "Y101",   "ZR101",
         "NB101",  "MO101",  "TC101",  "SR102",  "Y102",   "ZR102",  "NB102",
         "MO102",  "TC102",  "TC102M", "RH102",  "SR103",  "Y103",   "ZR103",
         "NB103",  "MO103",  "TC103",  "RU103",  "RH103M", "SR104",  "Y104",
         "ZR104",  "NB104",  "MO104",  "TC104",  "RH104",  "RH104M", "Y105",
         "ZR105",  "NB105",  "MO105",  "TC105",  "RU105",  "RH105",  "RH105M",
         "ZR106",  "NB106",  "MO106",  "TC106",  "RU106",  "RH106",  "RH106M",
         "ZR107",  "NB107",  "MO107",  "TC107",  "RU107",  "RH107",  "PD107",
         "PD107M", "ZR108",  "NB108",  "MO108",  "TC108",  "RU108",  "RH108",
         "RH108M", "AG108",  "ZR109",  "NB109",  "MO109",  "TC109",  "RU109",
         "RH109",  "RH109M", "PD109",  "PD109M", "AG109M", "CD109",  "NB110",
         "MO110",  "TC110",  "RU110",  "RH110",  "RH110M", "AG110",  "AG110M",
         "NB111",  "MO111",  "TC111",  "RU111",  "RH111",  "PD111",  "PD111M",
         "AG111",  "AG111M", "CD111M", "MO112",  "TC112",  "RU112",  "RH112",
         "PD112",  "AG112",  "MO113",  "TC113",  "RU113",  "RH113",  "PD113",
         "AG113",  "AG113M", "CD113M", "MO114",  "TC114",  "RU114",  "RH114",
         "PD114",  "AG114",  "IN114",  "IN114M", "MO115",  "TC115",  "RU115",
         "RH115",  "PD115",  "AG115",  "AG115M", "CD115",  "CD115M", "IN115M",
         "TC116",  "RU116",  "RH116",  "PD116",  "AG116",  "AG116M", "IN116",
         "IN116M", "TC117",  "RU117",  "RH117",  "PD117",  "AG117",  "AG117M",
         "CD117",  "CD117M", "IN117",  "IN117M", "SN117M", "RU118",  "RH118",
         "PD118",  "AG118",  "AG118M", "CD118",  "IN118",  "IN118M", "RH119",
         "PD119",  "AG119",  "CD119",  "CD119M", "IN119",  "IN119M", "SN119M",
         "RU120",  "RH120",  "PD120",  "AG120",  "CD120",  "IN120",  "IN120M",
         "RH121",  "PD121",  "AG121",  "CD121",  "IN121",  "IN121M", "SN121",
         "SN121M", "RH122",  "PD122",  "AG122",  "CD122",  "IN122",  "IN122M",
         "SB122",  "SB122M", "RH123",  "PD123",  "AG123",  "CD123",  "IN123",
         "IN123M", "SN123",  "SN123M", "TE123M", "PD124",  "AG124",  "CD124",
         "IN124",  "SB124",  "SB124M", "AG125",  "CD125",  "IN125",  "IN125M",
         "SN125",  "SN125M", "SB125",  "TE125M", "PD126",  "AG126",  "CD126",
         "IN126",  "SN126",  "SB126",  "SB126M", "CD127",  "IN127",  "IN127M",
         "SN127",  "SN127M", "SB127",  "TE127",  "TE127M", "XE127",  "AG128",
         "CD128",  "IN128",  "SN128",  "SB128",  "SB128M", "I128",   "CD129",
         "IN129",  "SN129",  "SN129M", "SB129",  "TE129",  "TE129M", "I129",
         "XE129M", "CD130",  "IN130",  "SN130",  "SB130",  "SB130M", "I130",
         "I130M",  "CD131",  "IN131",  "SN131",  "SB131",  "TE131",  "TE131M",
         "I131",   "XE131M", "CD132",  "IN132",  "SN132",  "SB132",  "SB132M",
         "TE132",  "I132",   "CS132",  "IN133",  "SN133",  "SB133",  "TE133",
         "TE133M", "I133",   "I133M",  "XE133",  "XE133M", "IN134",  "SN134",
         "SB134",  "SB134M", "TE134",  "I134",   "I134M",  "XE134M", "CS134",
         "CS134M", "SN135",  "SB135",  "TE135",  "I135",   "XE135",  "XE135M",
         "CS135",  "CS135M", "BA135M", "SN136",  "SB136",  "TE136",  "I136",
         "I136M",  "CS136",  "BA136M", "SB137",  "TE137",  "I137",   "XE137",
         "CS137",  "BA137M", "SB138",  "TE138",  "I138",   "XE138",  "CS138",
         "CS138M", "SB139",  "TE139",  "I139",   "XE139",  "CS139",  "BA139",
         "TE140",  "I140",   "XE140",  "CS140",  "BA140",  "LA140",  "PR140",
         "TE141",  "I141",   "XE141",  "CS141",  "BA141",  "LA141",  "CE141",
         "TE142",  "I142",   "XE142",  "CS142",  "BA142",  "LA142",  "PR142",
         "PR142M", "I143",   "XE143",  "CS143",  "BA143",  "LA143",  "CE143",
         "PR143",  "I144",   "XE144",  "CS144",  "BA144",  "LA144",  "CE144",
         "PR144",  "PR144M", "XE145",  "CS145",  "BA145",  "LA145",  "CE145",
         "PR145",  "XE146",  "CS146",  "BA146",  "LA146",  "CE146",  "PR146",
         "PM146",  "XE147",  "CS147",  "BA147",  "LA147",  "CE147",  "PR147",
         "ND147",  "PM147",  "CS148",  "BA148",  "LA148",  "CE148",  "PR148",
         "PM148",  "PM148M", "BA149",  "LA149",  "CE149",  "PR149",  "ND149",
         "PM149",  "CS150",  "BA150",  "LA150",  "CE150",  "PR150",  "PM150",
         "LA151",  "CE151",  "PR151",  "ND151",  "PM151",  "SM151",  "BA152",
         "LA152",  "CE152",  "PR152",  "ND152",  "PM152",  "PM152M", "EU152",
         "EU152M", "LA153",  "CE153",  "PR153",  "ND153",  "PM153",  "SM153",
         "GD153",  "LA154",  "CE154",  "PR154",  "ND154",  "PM154",  "PM154M",
         "EU154",  "CE155",  "PR155",  "ND155",  "PM155",  "SM155",  "EU155",
         "GD155M", "CE156",  "PR156",  "ND156",  "PM156",  "SM156",  "EU156",
         "CE157",  "PR157",  "ND157",  "PM157",  "SM157",  "EU157",  "PR158",
         "ND158",  "PM158",  "SM158",  "EU158",  "PR159",  "ND159",  "PM159",
         "SM159",  "EU159",  "GD159",  "ND160",  "PM160",  "SM160",  "EU160",
         "TB160",  "ND161",  "PM161",  "SM161",  "EU161",  "GD161",  "TB161",
         "PM162",  "SM162",  "EU162",  "GD162",  "TB162",  "TB162M", "SM163",
         "EU163",  "GD163",  "TB163",  "SM164",  "EU164",  "GD164",  "TB164",
         "SM165",  "EU165",  "GD165",  "TB165",  "DY165",  "DY165M", "DY166",
         "HO166",  "HO166M", "ER167M", "ER169",  "TM170",  "TM171"};
     return fp_activity;
 }
Vec_Str create_melmaccs_fp_mass () static
 {
     Vec_Str fp_mass = {
         "H3",     "LI6",    "LI7",    "BE9",    "BE10",   "C14",    "ZN68",
         "ZN70",   "ZN72",   "GA72",   "GE72",   "GA73",   "GE73",   "GE74",
         "GE75",   "AS75",   "GE76",   "AS76",   "SE76",   "GE77",   "AS77",
         "SE77",   "GE78",   "AS78",   "SE78",   "GE79",   "AS79",   "SE79",
         "SE79M",  "BR79",   "GE80",   "AS80",   "SE80",   "KR80",   "GE81",
         "AS81",   "SE81",   "SE81M",  "BR81",   "KR81",   "AS82",   "AS82M",
         "SE82",   "BR82",   "BR82M",  "KR82",   "AS83",   "SE83",   "SE83M",
         "BR83",   "KR83",   "KR83M",  "AS84",   "SE84",   "BR84",   "BR84M",
         "KR84",   "SE85",   "SE85M",  "BR85",   "KR85",   "KR85M",  "RB85",
         "SE86",   "BR86",   "BR86M",  "KR86",   "RB86",   "SR86",   "SE87",
         "BR87",   "KR87",   "RB87",   "SR87",   "BR88",   "KR88",   "RB88",
         "SR88",   "BR89",   "KR89",   "RB89",   "SR89",   "Y89",    "BR90",
         "KR90",   "RB90",   "RB90M",  "SR90",   "Y90",    "ZR90",   "KR91",
         "RB91",   "SR91",   "Y91",    "Y91M",   "ZR91",   "KR92",   "RB92",
         "SR92",   "Y92",    "ZR92",   "KR93",   "RB93",   "SR93",   "Y93",
         "ZR93",   "NB93",   "NB93M",  "RB94",   "SR94",   "Y94",    "ZR94",
         "NB94",   "SR95",   "Y95",    "ZR95",   "NB95",   "NB95M",  "MO95",
         "SR96",   "Y96",    "ZR96",   "NB96",   "MO96",   "Y97",    "ZR97",
         "NB97",   "NB97M",  "MO97",   "SR98",   "Y98",    "ZR98",   "NB98",
         "NB98M",  "MO98",   "TC98",   "Y99",    "ZR99",   "NB99",   "NB99M",
         "MO99",   "TC99",   "TC99M",  "RU99",   "Y100",   "ZR100",  "NB100",
         "NB100M", "MO100",  "TC100",  "RU100",  "ZR101",  "NB101",  "MO101",
         "TC101",  "RU101",  "ZR102",  "NB102",  "MO102",  "TC102",  "TC102M",
         "RU102",  "RH102",  "ZR103",  "NB103",  "MO103",  "TC103",  "RU103",
         "RH103",  "RH103M", "ZR104",  "NB104",  "MO104",  "TC104",  "RU104",
         "RH104",  "RH104M", "PD104",  "NB105",  "MO105",  "TC105",  "RU105",
         "RH105",  "RH105M", "PD105",  "MO106",  "TC106",  "RU106",  "RH106",
         "RH106M", "PD106",  "MO107",  "TC107",  "RU107",  "RH107",  "PD107",
         "AG107",  "TC108",  "RU108",  "RH108",  "RH108M", "PD108",  "CD108",
         "TC109",  "RU109",  "RH109",  "RH109M", "PD109",  "PD109M", "AG109",
         "AG109M", "RU110",  "RH110",  "PD110",  "AG110",  "AG110M", "CD110",
         "RU111",  "RH111",  "PD111",  "PD111M", "AG111",  "AG111M", "CD111",
         "PD112",  "AG112",  "CD112",  "PD113",  "AG113",  "AG113M", "CD113",
         "CD113M", "IN113",  "PD114",  "CD114",  "IN114M", "SN114",  "PD115",
         "AG115",  "CD115",  "CD115M", "IN115",  "IN115M", "SN115",  "PD116",
         "AG116",  "CD116",  "IN116M", "SN116",  "AG117",  "CD117",  "CD117M",
         "IN117",  "IN117M", "SN117",  "SN117M", "CD118",  "SN118",  "CD119",
         "CD119M", "IN119",  "IN119M", "SN119",  "SN119M", "CD120",  "IN120",
         "SN120",  "CD121",  "IN121",  "IN121M", "SN121",  "SN121M", "SB121",
         "IN122",  "SN122",  "SB122",  "TE122",  "IN123M", "SN123",  "SN123M",
         "SB123",  "TE123",  "TE123M", "CD124",  "SN124",  "SB124",  "TE124",
         "SN125",  "SN125M", "SB125",  "TE125",  "TE125M", "SN126",  "SB126",
         "SB126M", "TE126",  "SN127",  "SN127M", "SB127",  "TE127",  "TE127M",
         "I127",   "SN128",  "SB128",  "SB128M", "TE128",  "I128",   "XE128",
         "SN129",  "SN129M", "SB129",  "TE129",  "TE129M", "I129",   "XE129",
         "XE129M", "SN130",  "SB130",  "SB130M", "TE130",  "I130",   "I130M",
         "XE130",  "SN131",  "SB131",  "TE131",  "TE131M", "I131",   "XE131",
         "XE131M", "SN132",  "SB132",  "SB132M", "TE132",  "I132",   "XE132",
         "CS132",  "BA132",  "SB133",  "TE133",  "TE133M", "I133",   "I133M",
         "XE133",  "XE133M", "CS133",  "SB134",  "SB134M", "TE134",  "I134",
         "I134M",  "XE134",  "CS134",  "CS134M", "BA134",  "TE135",  "I135",
         "XE135",  "XE135M", "CS135",  "CS135M", "BA135",  "BA135M", "TE136",
         "I136",   "I136M",  "XE136",  "CS136",  "BA136",  "TE137",  "I137",
         "XE137",  "CS137",  "BA137",  "BA137M", "I138",   "XE138",  "CS138",
         "CS138M", "BA138",  "LA138",  "I139",   "XE139",  "CS139",  "BA139",
         "LA139",  "XE140",  "CS140",  "BA140",  "LA140",  "CE140",  "XE141",
         "CS141",  "BA141",  "LA141",  "CE141",  "PR141",  "XE142",  "CS142",
         "BA142",  "LA142",  "CE142",  "PR142",  "PR142M", "ND142",  "CS143",
         "BA143",  "LA143",  "CE143",  "PR143",  "ND143",  "CS144",  "BA144",
         "LA144",  "CE144",  "PR144",  "PR144M", "ND144",  "BA145",  "LA145",
         "CE145",  "PR145",  "ND145",  "BA146",  "LA146",  "CE146",  "PR146",
         "ND146",  "PM146",  "SM146",  "BA147",  "LA147",  "CE147",  "PR147",
         "ND147",  "PM147",  "SM147",  "LA148",  "CE148",  "PR148",  "ND148",
         "PM148",  "PM148M", "SM148",  "CE149",  "PR149",  "ND149",  "PM149",
         "SM149",  "CE150",  "PR150",  "ND150",  "PM150",  "SM150",  "PR151",
         "ND151",  "PM151",  "SM151",  "EU151",  "CE152",  "PR152",  "ND152",
         "PM152",  "PM152M", "SM152",  "EU152",  "EU152M", "GD152",  "PR153",
         "ND153",  "PM153",  "SM153",  "EU153",  "GD153",  "ND154",  "PM154",
         "PM154M", "SM154",  "EU154",  "GD154",  "ND155",  "PM155",  "SM155",
         "EU155",  "GD155",  "ND156",  "PM156",  "SM156",  "EU156",  "GD156",
         "PM157",  "SM157",  "EU157",  "GD157",  "SM158",  "EU158",  "GD158",
         "SM159",  "EU159",  "GD159",  "TB159",  "SM160",  "GD160",  "TB160",
         "DY160",  "GD161",  "TB161",  "DY161",  "GD162",  "TB162",  "DY162",
         "TB163",  "DY163",  "DY164",  "DY165",  "HO165",  "DY166",  "HO166",
         "HO166M", "ER166",  "ER167",  "ER168",  "TM169",  "TM170",  "YB170"};
     return fp_mass;
 }
Vec_Str create_melmaccs_lt_activity () static
 {
     Vec_Str lt_activity = {
         "H3",     "H4",     "HE6",    "LI8",    "BE8",    "BE10",   "BE11",
         "B12",    "C14",    "C15",    "N16",    "O19",    "F20",    "NE23",
         "NA24",   "NA24M",  "NA25",   "MG27",   "AL28",   "AL29",   "AL30",
         "SI31",   "P32",    "P34",    "S35",    "S37",    "CL36",   "CL38",
         "CL38M",  "AR37",   "AR39",   "AR41",   "K42",    "K43",    "K44",
         "CA41",   "CA45",   "CA47",   "CA49",   "SC46",   "SC46M",  "SC47",
         "SC48",   "SC49",   "SC50",   "TI51",   "V50",    "V52",    "V53",
         "V54",    "CR51",   "CR55",   "MN54",   "MN56",   "MN57",   "MN58",
         "FE55",   "FE59",   "CO58",   "CO60",   "CO60M",  "CO61",   "CO62",
         "NI59",   "NI63",   "NI65",   "NI66",   "CU64",   "CU66",   "CU67",
         "ZN65",   "ZN69",   "ZN69M",  "ZN71",   "ZN71M",  "GA70",   "GA72",
         "GA72M",  "GE71",   "GE71M",  "Y89M",   "Y90",    "Y92",    "ZR89",
         "ZR95",   "ZR97",   "NB92",   "NB94",   "NB95",   "NB95M",  "NB96",
         "NB97",   "NB97M",  "NB98",   "NB100",  "MO93M",  "MO93",   "MO99",
         "MO101",  "TC99",   "TC100",  "TC101",  "RU103",  "RH104",  "RH104M",
         "RH106",  "PD109",  "PD109M", "PD111",  "PD111M", "AG106",  "AG108",
         "AG108M", "AG109M", "AG110",  "AG110M", "AG111",  "AG111M", "AG112",
         "CD107",  "CD109",  "CD111M", "CD115",  "CD115M", "CD117",  "CD117M",
         "CD119",  "IN113M", "IN114",  "IN114M", "IN115",  "IN116",  "IN116M",
         "IN117",  "IN117M", "IN118",  "IN119",  "IN119M", "SN113",  "SN113M",
         "SN117M", "SN119M", "SN121",  "SN121M", "SN123",  "SN123M", "SN125",
         "SN125M", "SB122",  "SB122M", "SB124",  "SB124M", "SB125",  "SB126",
         "SB126M", "TE123M", "TE125M", "TE127",  "TE127M", "I128",   "PM150",
         "PM151",  "SM153",  "EU152",  "EU154",  "EU155",  "EU156",  "GD152",
         "GD153",  "GD155M", "GD159",  "GD161",  "GD162",  "TB160",  "TB161",
         "TB162",  "DY165",  "DY165M", "DY166",  "HO166",  "HO166M", "ER167M",
         "ER169",  "TA182",  "TA182M", "TA183",  "W181",   "W183M",  "W185",
         "W185M",  "W187",   "W188",   "RE186",  "RE188",  "RE188M", "RE189",
         "OS190M", "OS191",  "OS191M", "IR192",  "IR194",  "IR194M", "PT193M",
         "PB204",  "PB209",  "BI210",  "PO210",  "PO211"};
     return lt_activity;
 }
Vec_Str create_melmaccs_lt_mass () static
 {
     Vec_Str lt_mass = {
         "H1",     "H3",     "HE3",    "HE4",    "LI6",    "LI7",    "BE9",
         "BE10",   "B10",    "B11",    "C12",    "C13",    "C14",    "N14",
         "N15",    "O16",    "O17",    "O18",    "F19",    "NE20",   "NE22",
         "NA23",   "NA24",   "MG24",   "MG25",   "MG26",   "AL27",   "SI28",
         "SI29",   "SI30",   "P31",    "P32",    "S32",    "S35",    "CL35",
         "CL36",   "CL37",   "AR38",   "K40",    "K41",    "CA40",   "CA41",
         "CA42",   "CA43",   "CA44",   "CA45",   "CA46",   "CA48",   "SC45",
         "TI46",   "TI47",   "TI48",   "TI49",   "TI50",   "V50",    "V51",
         "CR50",   "CR51",   "CR52",   "CR53",   "CR54",   "MN54",   "MN55",
         "FE54",   "FE55",   "FE56",   "FE57",   "FE58",   "FE59",   "CO58",
         "CO59",   "CO60",   "NI58",   "NI59",   "NI60",   "NI61",   "NI62",
         "NI63",   "NI64",   "CU63",   "CU65",   "ZN64",   "ZN65",   "ZN66",
         "ZN67",   "ZN68",   "ZN70",   "GA69",   "GA71",   "GE70",   "ZR92",
         "MO92",   "MO93",   "MO94",   "MO95",   "MO96",   "MO97",   "MO98",
         "MO99",   "MO100",  "TC99",   "RU100",  "RU101",  "RU102",  "PD108",
         "PD110",  "AG107",  "AG108M", "AG109",  "AG110M", "CD106",  "CD108",
         "CD109",  "CD110",  "CD111",  "CD112",  "CD113",  "CD114",  "CD115",
         "CD115M", "CD116",  "IN113",  "IN114M", "IN115",  "IN116M", "SN112",
         "SN113",  "SN114",  "SN115",  "SN116",  "SN117",  "SN117M", "SN118",
         "SN119",  "SN119M", "SN120",  "SN122",  "SN123",  "SN124",  "SN125",
         "SB121",  "SB123",  "SB125",  "TE122",  "TE125",  "TE125M", "TE126",
         "EU153",  "EU154",  "EU155",  "GD152",  "GD153",  "GD154",  "GD155",
         "GD156",  "GD157",  "GD158",  "GD159",  "GD160",  "TB159",  "TB160",
         "TB161",  "DY160",  "DY161",  "DY162",  "DY163",  "DY164",  "HO165",
         "ER166",  "TA181",  "W180",   "W181",   "W182",   "W183",   "W184",
         "W185",   "W186",   "W187",   "W188",   "RE185",  "RE186",  "RE187",
         "RE188",  "OS186",  "OS188",  "OS189",  "OS190",  "PB204",  "PB205",
         "PB206",  "PB207",  "PB208",  "BI209",  "BI210M"};
     return lt_mass;
 }
Vec_Int createNuclideIds_scale62 () static
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by TEST_F().
 {
     return Vec_Int(
         {10000001, 10001001, 10001002, 10001003, 10002003, 10002004, 10002005, 10002006,
          10003006, 10003007, 10003008, 10004007, 10004008, 10004009, 10004010,
          10004011, 10005010, 10005011, 10005012, 10006012, 10006013, 10006014,
          10006015, 10007013, 10007014, 10007015, 10007016, 10008016, 10008017,
          10008018, 10008019, 10009019, 10009020, 10010020, 10010021, 10010022,
          10010023, 10011022, 10011023, 10011024, 11011024, 10011025, 10012024,
          10012025, 10012026, 10012027, 10012028, 10013026, 10013027, 10013028,
          10013029, 10013030, 10014028, 10014029, 10014030, 10014031, 10014032,
          10015031, 10015032, 10015033, 10015034, 10016032, 10016033, 10016034,
          10016035, 10016036, 10016037, 10017035, 10017036, 10017037, 10017038,
          11017038, 10018036, 10018037, 10018038, 10018039, 10018040, 10018041,
          10018042, 10019039, 10019040, 10019041, 10019042, 10019043, 10019044,
          10020040, 10020041, 10020042, 10020043, 10020044, 10020045, 10020046,
          10020047, 10020048, 10020049, 10021044, 11021044, 10021045, 11021045,
          10021046, 11021046, 10021047, 10021048, 10021049, 10021050, 10022044,
          10022045, 10022046, 10022047, 10022048, 10022049, 10022050, 10022051,
          10023048, 10023049, 10023050, 10023051, 10023052, 10023053, 10023054,
          10024048, 10024049, 10024050, 10024051, 10024052, 10024053, 10024054,
          10024055, 10025052, 10025053, 10025054, 10025055, 10025056, 10025057,
          10025058, 10026054, 10026055, 10026056, 10026057, 10026058, 10026059,
          10026060, 10027055, 10027056, 10027057, 11027058, 10027058, 10027059,
          10027060, 11027060, 10027061, 10027062, 10028056, 10028057, 10028058,
          10028059, 10028060, 10028061, 10028062, 10028063, 10028064, 10028065,
          10028066, 10029062, 10029063, 10029064, 10029065, 10029066, 10029067,
          10030063, 10030064, 10030065, 10030066, 10030067, 10030068, 10030069,
          11030069, 10030070, 10030071, 11030071, 10030072, 10031067, 10031068,
          10031069, 10031070, 10031071, 10031072, 11031072, 10032068, 10032069,
          10032070, 10032071, 11032071, 10032072, 10032073, 11032073, 10032074,
          10032075, 11032075, 10032076, 10032077, 11032077, 10033071, 10033072,
          10033073, 10033074, 10033075, 11033075, 10033076, 10033077, 10034072,
          10034073, 10034074, 10034075, 10034076, 10034077, 11034077, 10034078,
          10034079, 11034079, 10034080, 10034081, 11034081, 10034082, 10034083,
          11034083, 10035076, 10035077, 11035077, 10035078, 10035079, 10035080,
          11035080, 10035081, 10035082, 11035082, 10035083, 10036076, 10036077,
          10036078, 10036079, 11036079, 10036080, 10036081, 11036081, 10036082,
          10036083, 11036083, 10036084, 10036085, 11036085, 10036086, 10036087,
          10036088, 10037082, 10037083, 10037084, 10037085, 10037086, 11037086,
          10037087, 10037088, 10037089, 10038082, 10038083, 10038084, 10038085,
          11038085, 10038086, 10038087, 11038087, 10038088, 10038089, 10038090,
          10038091, 10038093, 10039086, 10039087, 11039087, 10039088, 10039089,
          11039089, 10039090, 11039090, 10039091, 11039091, 10039092, 10039093,
          11039093, 10039094, 10039096, 10040086, 10040087, 10040088, 10040089,
          10040090, 11040090, 10040091, 10040092, 10040093, 10040094, 10040095,
          10040096, 10040097, 10041090, 11041090, 10041091, 11041091, 10041092,
          11041092, 10041093, 11041093, 10041094, 11041094, 10041095, 11041095,
          10041096, 10041097, 11041097, 10041098, 10041100, 10042092, 11042093,
          10042093, 10042094, 10042095, 10042096, 10042097, 10042098, 10042099,
          10042100, 10042101, 10043095, 11043095, 10043096, 10043097, 11043097,
          10043098, 10043099, 11043099, 10043100, 10043101, 10044096, 10044097,
          10044098, 10044099, 10044100, 10044101, 10044102, 10044103, 10044104,
          10044105, 10044106, 10044107, 10045099, 11045099, 10045100, 10045101,
          11045101, 10045102, 11045102, 10045103, 11045103, 10045104, 11045104,
          10045105, 11045105, 10045106, 11045106, 10045107, 10046100, 10046101,
          10046102, 10046103, 10046104, 10046105, 10046106, 10046107, 11046107,
          10046108, 10046109, 11046109, 10046110, 10046111, 11046111, 10046112,
          10047105, 10047106, 11047106, 10047107, 11047107, 10047108, 11047108,
          10047109, 11047109, 10047110, 11047110, 10047111, 11047111, 10047112,
          10048106, 10048107, 10048108, 10048109, 10048110, 10048111, 11048111,
          10048112, 10048113, 11048113, 10048114, 10048115, 11048115, 10048116,
          10048117, 11048117, 10048119, 10048121, 10049111, 10049112, 10049113,
          11049113, 10049114, 11049114, 10049115, 11049115, 10049116, 11049116,
          10049117, 11049117, 10049118, 10049119, 11049119, 10049120, 11049120,
          10049121, 11049121, 10050112, 10050113, 11050113, 10050114, 10050115,
          10050116, 10050117, 11050117, 10050118, 10050119, 11050119, 10050120,
          10050121, 11050121, 10050122, 10050123, 11050123, 10050124, 10050125,
          11050125, 10050126, 10051118, 10051119, 10051120, 11051120, 10051121,
          10051122, 11051122, 10051123, 10051124, 11051124, 10051125, 10051126,
          11051126, 10051127, 10052118, 10052119, 11052119, 10052120, 10052121,
          11052121, 10052122, 10052123, 11052123, 10052124, 10052125, 11052125,
          10052126, 10052127, 11052127, 10052128, 10052129, 11052129, 10052130,
          10052131, 11052131, 10052132, 10053122, 10053123, 10053124, 10053125,
          10053126, 10053127, 10053128, 10053129, 10053130, 11053130, 10053131,
          10053132, 10053133, 10054122, 10054123, 10054124, 10054125, 11054125,
          10054126, 10054127, 11054127, 10054128, 10054129, 11054129, 10054130,
          10054131, 11054131, 10054132, 10054133, 11054133, 10054134, 10054135,
          11054135, 10054136, 10054137, 10055128, 10055129, 10055130, 10055131,
          10055132, 10055133, 10055134, 11055134, 10055135, 10055136, 10055137,
          10055138, 10056128, 10056129, 10056130, 10056131, 11056131, 10056132,
          10056133, 11056133, 10056134, 10056135, 11056135, 10056136, 11056136,
          10056137, 11056137, 10056138, 10056139, 10056140, 10056141, 10057134,
          10057135, 10057136, 10057137, 10057138, 10057139, 10057140, 10057141,
          10058134, 10058135, 10058136, 10058137, 11058137, 10058138, 10058139,
          11058139, 10058140, 10058141, 10058142, 10058143, 10058144, 10058145,
          10059140, 10059141, 10059142, 11059142, 10059143, 10059144, 11059144,
          10059145, 10060140, 10060141, 11060141, 10060142, 10060143, 10060144,
          10060145, 10060146, 10060147, 10060148, 10060149, 10060150, 10060151,
          10061143, 10061144, 10061145, 10061146, 10061147, 10061148, 11061148,
          10061149, 10061150, 10061151, 10061152, 10062144, 10062145, 10062146,
          10062147, 10062148, 10062149, 10062150, 10062151, 10062152, 10062153,
          10062154, 10062155, 10063145, 10063146, 10063147, 10063148, 10063149,
          10063150, 11063150, 10063151, 10063152, 11063152, 10063153, 10063154,
          10063155, 10063156, 10063157, 10064146, 10064147, 10064148, 10064149,
          10064150, 10064151, 10064152, 10064153, 10064154, 11064155, 10064155,
          10064156, 10064157, 10064158, 10064159, 10064160, 10064161, 10064162,
          10065152, 10065153, 10065154, 11065154, 10065155, 10065156, 11065156,
          10065157, 10065158, 10065159, 10065160, 10065161, 10065162, 10066154,
          10066155, 10066156, 10066157, 10066158, 10066159, 10066160, 10066161,
          10066162, 10066163, 10066164, 10066165, 11066165, 10066166, 10067160,
          11067160, 10067161, 10067163, 11067163, 10067164, 11067164, 10067165,
          10067166, 11067166, 10068160, 10068161, 10068162, 10068163, 10068164,
          10068165, 10068166, 10068167, 11068167, 10068168, 10068169, 10068170,
          10068171, 10068172, 10069165, 10069166, 10069167, 10069168, 10069169,
          10069170, 10069171, 10069172, 10069173, 10070166, 10070167, 10070168,
          10070169, 10070170, 10070171, 10070172, 10070173, 10070174, 10070175,
          11070175, 10070176, 10070177, 10071169, 10071170, 10071171, 10071172,
          11071172, 10071173, 10071174, 11071174, 10071175, 10071176, 11071176,
          10071177, 11071177, 10072170, 10072171, 10072172, 10072173, 10072174,
          10072175, 10072176, 10072177, 11072177, 10072178, 11072178, 10072179,
          11072179, 10072180, 11072180, 10072181, 10072182, 10073177, 10073178,
          10073179, 11073180, 10073180, 10073181, 10073182, 11073182, 10073183,
          10074178, 10074180, 10074181, 10074182, 11074183, 10074183, 10074184,
          10074185, 11074185, 10074186, 10074187, 10074188, 10074189, 10075181,
          10075182, 11075182, 10075183, 10075184, 11075184, 10075185, 10075186,
          11075186, 10075187, 10075188, 11075188, 10075189, 10076182, 10076183,
          10076184, 10076185, 10076186, 10076187, 10076188, 10076189, 11076189,
          10076190, 11076190, 10076191, 11076191, 10076192, 10076193, 10076194,
          10077185, 10077186, 10077188, 10077189, 11077189, 10077190, 10077191,
          11077191, 10077192, 11077192, 10077193, 11077193, 10077194, 11077194,
          10077196, 11077196, 10078188, 10078189, 10078190, 10078191, 10078192,
          10078193, 11078193, 10078194, 10078195, 11078195, 10078196, 10078197,
          11078197, 10078198, 10078199, 11078199, 10078200, 10079193, 10079194,
          10079195, 11079195, 10079196, 10079197, 11079197, 10079198, 11079198,
          10079199, 10079200, 11079200, 10080193, 11080193, 10080194, 10080195,
          11080195, 10080196, 10080197, 11080197, 10080198, 10080199, 11080199,
          10080200, 10080201, 10080202, 10080203, 10080204, 10080205, 10080206,
          10081200, 10081201, 10081202, 10081203, 10081204, 10081205, 10081206,
          10081207, 10082200, 10082202, 10082203, 10082204, 10082205, 11082205,
          10082206, 10082207, 11082207, 10082208, 10082209, 10082210, 10083205,
          10083206, 10083207, 10083208, 10083209, 10083210, 11083210, 10083211,
          10084206, 10084207, 10084208, 10084209, 10084210, 10084211, 11084211,
          20000001, 20002003, 20002004, 20003006, 20003007, 20004007, 20006012, 20080206,
          20081203, 20081205, 20081206, 20081207, 20081208, 20081209, 20081210,
          20082203, 20082204, 20082205, 20082206, 20082207, 21082207, 20082208,
          20082209, 20082210, 20082211, 20082212, 20082214, 20083206, 20083207,
          20083208, 20083209, 21083210, 20083210, 20083211, 20083212, 21083212,
          20083213, 20083214, 20084207, 20084208, 20084209, 20084210, 21084211,
          20084211, 20084212, 20084213, 20084214, 20084215, 20084216, 20084218,
          20085216, 20085217, 20085218, 20086216, 20086217, 20086218, 20086219,
          20086220, 20086222, 20087220, 20087221, 20087222, 20087223, 20088220,
          20088222, 20088223, 20088224, 20088225, 20088226, 20088227, 20088228,
          20089224, 20089225, 20089226, 20089227, 20089228, 20090226, 20090227,
          20090228, 20090229, 20090230, 20090231, 20090232, 20090233, 20090234,
          20091228, 20091229, 20091230, 20091231, 20091232, 20091233, 21091234,
          20091234, 20091235, 20092230, 20092231, 20092232, 20092233, 20092234,
          20092235, 21092235, 20092236, 20092237, 20092238, 20092239, 20092240,
          20092241, 20093234, 20093235, 21093236, 20093236, 20093237, 20093238,
          20093239, 21093240, 20093240, 20093241, 20094236, 21094237, 20094237,
          20094238, 20094239, 20094240, 20094241, 20094242, 20094243, 20094244,
          20094245, 20094246, 20094247, 20095239, 20095240, 20095241, 21095242,
          20095242, 20095243, 21095244, 20095244, 20095245, 20095246, 21095246,
          20095247, 20096240, 20096241, 20096242, 20096243, 20096244, 20096245,
          20096246, 20096247, 20096248, 20096249, 20096250, 20096251, 20097245,
          20097246, 20097247, 20097248, 21097248, 20097249, 20097250, 20097251,
          20098246, 20098248, 20098249, 20098250, 20098251, 20098252, 20098253,
          20098254, 20098255, 20099251, 20099252, 20099253, 21099254, 20099254,
          20099255, 30000001, 30001003, 30002003, 30002004, 30026065, 30027065, 30028065,
          30029065, 30024066, 30025066, 30026066, 30027066, 30028066, 30029066,
          30030066, 30031066, 30032066, 30024067, 30025067, 30026067, 30027067,
          30028067, 30029067, 30030067, 30031067, 30032067, 30025068, 30026068,
          30027068, 30028068, 30029068, 31029068, 30030068, 30031068, 30032068,
          30025069, 30026069, 30027069, 30028069, 30029069, 30030069, 31030069,
          30031069, 30032069, 30033069, 30026070, 30027070, 30028070, 30029070,
          31029070, 30030070, 30031070, 30032070, 30026071, 30027071, 30028071,
          30029071, 30030071, 31030071, 30031071, 30032071, 31032071, 30033071,
          30026072, 30027072, 30028072, 30029072, 30030072, 30031072, 31031072,
          30032072, 30033072, 30034072, 30027073, 30028073, 30029073, 30030073,
          30031073, 30032073, 31032073, 30033073, 30034073, 31034073, 30027074,
          30028074, 30029074, 30030074, 30031074, 31031074, 30032074, 30033074,
          30034074, 30027075, 30028075, 30029075, 30030075, 30031075, 30032075,
          31032075, 30033075, 31033075, 30034075, 30035075, 30028076, 30029076,
          30030076, 30031076, 30032076, 30033076, 30034076, 30028077, 30029077,
          30030077, 30031077, 30032077, 31032077, 30033077, 30034077, 31034077,
          30035077, 31035077, 30036077, 30028078, 30029078, 30030078, 30031078,
          30032078, 30033078, 30034078, 30035078, 30036078, 30029079, 30030079,
          30031079, 30032079, 31032079, 30033079, 30034079, 31034079, 30035079,
          31035079, 30036079, 31036079, 30037079, 30029080, 30030080, 30031080,
          30032080, 30033080, 30034080, 30035080, 31035080, 30036080, 30030081,
          30031081, 30032081, 31032081, 30033081, 30034081, 31034081, 30035081,
          30036081, 31036081, 30037081, 30030082, 30031082, 30032082, 30033082,
          31033082, 30034082, 30035082, 31035082, 30036082, 30030083, 30031083,
          30032083, 30033083, 30034083, 31034083, 30035083, 30036083, 31036083,
          30037083, 30038083, 30031084, 30032084, 30033084, 30034084, 30035084,
          31035084, 30036084, 30037084, 30038084, 30031085, 30032085, 30033085,
          30034085, 30035085, 30036085, 31036085, 30037085, 30038085, 31038085,
          30039085, 30031086, 30032086, 30033086, 30034086, 30035086, 30036086,
          30037086, 31037086, 30038086, 30032087, 30033087, 30034087, 30035087,
          30036087, 30037087, 30038087, 31038087, 30039087, 31039087, 30040087,
          30032088, 30033088, 30034088, 30035088, 30036088, 30037088, 30038088,
          30039088, 30040088, 30032089, 30033089, 30034089, 30035089, 30036089,
          30037089, 30038089, 30039089, 31039089, 30040089, 31040089, 30041089,
          30033090, 30034090, 30035090, 30036090, 30037090, 31037090, 30038090,
          30039090, 31039090, 30040090, 31040090, 30041090, 31041090, 30042090,
          30033091, 30034091, 30035091, 30036091, 30037091, 30038091, 30039091,
          31039091, 30040091, 30041091, 31041091, 30042091, 30033092, 30034092,
          30035092, 30036092, 30037092, 30038092, 30039092, 30040092, 30041092,
          31041092, 30042092, 30034093, 30035093, 30036093, 30037093, 30038093,
          30039093, 31039093, 30040093, 30041093, 31041093, 30042093, 31042093,
          30043093, 30034094, 30035094, 30036094, 30037094, 30038094, 30039094,
          30040094, 30041094, 31041094, 30042094, 30035095, 30036095, 30037095,
          30038095, 30039095, 30040095, 30041095, 31041095, 30042095, 30043095,
          31043095, 30044095, 30035096, 30036096, 30037096, 30038096, 30039096,
          31039096, 30040096, 30041096, 30042096, 30043096, 30044096, 30035097,
          30036097, 30037097, 30038097, 30039097, 31039097, 30040097, 30041097,
          31041097, 30042097, 30043097, 31043097, 30044097, 30036098, 30037098,
          30038098, 30039098, 31039098, 30040098, 30041098, 31041098, 30042098,
          30043098, 30044098, 30036099, 30037099, 30038099, 30039099, 30040099,
          30041099, 31041099, 30042099, 30043099, 31043099, 30044099, 30045099,
          31045099, 30046099, 30036100, 30037100, 30038100, 30039100, 30040100,
          30041100, 31041100, 30042100, 30043100, 30044100, 30037101, 30038101,
          30039101, 30040101, 30041101, 30042101, 30043101, 30044101, 30045101,
          31045101, 30046101, 30037102, 30038102, 30039102, 30040102, 30041102,
          31041102, 30042102, 30043102, 31043102, 30044102, 30045102, 31045102,
          30046102, 30038103, 30039103, 30040103, 30041103, 30042103, 30043103,
          30044103, 30045103, 31045103, 30046103, 30047103, 30038104, 30039104,
          30040104, 30041104, 31041104, 30042104, 30043104, 30044104, 30045104,
          31045104, 30046104, 30038105, 30039105, 30040105, 30041105, 30042105,
          30043105, 30044105, 30045105, 31045105, 30046105, 30047105, 31047105,
          30048105, 30039106, 30040106, 30041106, 30042106, 30043106, 30044106,
          30045106, 31045106, 30046106, 30047106, 31047106, 30048106, 30039107,
          30040107, 30041107, 30042107, 30043107, 30044107, 30045107, 30046107,
          31046107, 30047107, 31047107, 30048107, 30049107, 30039108, 30040108,
          30041108, 30042108, 30043108, 30044108, 30045108, 31045108, 30046108,
          30047108, 31047108, 30048108, 30040109, 30041109, 30042109, 30043109,
          30044109, 30045109, 30046109, 31046109, 30047109, 31047109, 30048109,
          30049109, 30040110, 30041110, 30042110, 30043110, 30044110, 30045110,
          31045110, 30046110, 30047110, 31047110, 30048110, 30041111, 30042111,
          30043111, 30044111, 30045111, 30046111, 31046111, 30047111, 31047111,
          30048111, 31048111, 30049111, 31049111, 30050111, 30041112, 30042112,
          30043112, 30044112, 30045112, 30046112, 30047112, 30048112, 30049112,
          31049112, 30050112, 30041113, 30042113, 30043113, 30044113, 30045113,
          30046113, 30047113, 31047113, 30048113, 31048113, 30049113, 31049113,
          30050113, 31050113, 30051113, 30042114, 30043114, 30044114, 30045114,
          30046114, 30047114, 30048114, 30049114, 31049114, 30050114, 30042115,
          30043115, 30044115, 30045115, 30046115, 30047115, 31047115, 30048115,
          31048115, 30049115, 31049115, 30050115, 30051115, 30052115, 30043116,
          30044116, 30045116, 30046116, 30047116, 31047116, 30048116, 30049116,
          31049116, 30050116, 30043117, 30044117, 30045117, 30046117, 30047117,
          31047117, 30048117, 31048117, 30049117, 31049117, 30050117, 31050117,
          30051117, 30052117, 30043118, 30044118, 30045118, 30046118, 30047118,
          31047118, 30048118, 30049118, 31049118, 30050118, 30051118, 31051118,
          30052118, 30044119, 30045119, 30046119, 30047119, 30048119, 31048119,
          30049119, 31049119, 30050119, 31050119, 30051119, 30052119, 30044120,
          30045120, 30046120, 30047120, 31047120, 30048120, 30049120, 31049120,
          30050120, 30051120, 31051120, 30052120, 30045121, 30046121, 30047121,
          30048121, 31048121, 30049121, 31049121, 30050121, 31050121, 30051121,
          30052121, 31052121, 30053121, 30045122, 30046122, 30047122, 31047122,
          30048122, 30049122, 31049122, 30050122, 30051122, 31051122, 30052122,
          30046123, 30047123, 30048123, 31048123, 30049123, 31049123, 30050123,
          31050123, 30051123, 30052123, 31052123, 30053123, 30046124, 30047124,
          30048124, 30049124, 31049124, 30050124, 30051124, 31051124, 30052124,
          30053124, 30054124, 30047125, 30048125, 30049125, 31049125, 30050125,
          31050125, 30051125, 30052125, 31052125, 30053125, 30054125, 31054125,
          30047126, 30048126, 30049126, 31049126, 30050126, 30051126, 31051126,
          30052126, 30053126, 30054126, 30047127, 30048127, 30049127, 31049127,
          30050127, 31050127, 30051127, 30052127, 31052127, 30053127, 30054127,
          31054127, 30055127, 30047128, 30048128, 30049128, 31049128, 30050128,
          31050128, 30051128, 31051128, 30052128, 30053128, 30054128, 30047129,
          30048129, 30049129, 31049129, 30050129, 31050129, 30051129, 31051129,
          30052129, 31052129, 30053129, 30054129, 31054129, 30055129, 30056129,
          30047130, 30048130, 30049130, 31049130, 30050130, 31050130, 30051130,
          31051130, 30052130, 30053130, 31053130, 30054130, 30048131, 30049131,
          31049131, 30050131, 31050131, 30051131, 30052131, 31052131, 30053131,
          30054131, 31054131, 30055131, 30056131, 30048132, 30049132, 30050132,
          30051132, 31051132, 30052132, 30053132, 31053132, 30054132, 30055132,
          30056132, 30049133, 30050133, 30051133, 30052133, 31052133, 30053133,
          31053133, 30054133, 31054133, 30055133, 30056133, 30057133, 30049134,
          30050134, 30051134, 31051134, 30052134, 30053134, 31053134, 30054134,
          31054134, 30055134, 31055134, 30056134, 30049135, 30050135, 30051135,
          30052135, 30053135, 30054135, 31054135, 30055135, 31055135, 30056135,
          31056135, 30057135, 30058135, 30050136, 30051136, 30052136, 30053136,
          31053136, 30054136, 30055136, 31055136, 30056136, 31056136, 30050137,
          30051137, 30052137, 30053137, 30054137, 30055137, 30056137, 31056137,
          30057137, 30058137, 30051138, 30052138, 30053138, 30054138, 30055138,
          31055138, 30056138, 30057138, 30058138, 30051139, 30052139, 30053139,
          30054139, 30055139, 30056139, 30057139, 30058139, 31058139, 30059139,
          30052140, 30053140, 30054140, 30055140, 30056140, 30057140, 30058140,
          30059140, 30060140, 30052141, 30053141, 30054141, 30055141, 30056141,
          30057141, 30058141, 30059141, 30060141, 31060141, 30061141, 30052142,
          30053142, 30054142, 30055142, 30056142, 30057142, 30058142, 30059142,
          31059142, 30060142, 30053143, 30054143, 30055143, 30056143, 30057143,
          30058143, 30059143, 30060143, 30061143, 30062143, 31062143, 30053144,
          30054144, 30055144, 30056144, 30057144, 30058144, 30059144, 31059144,
          30060144, 30061144, 30062144, 30054145, 30055145, 30056145, 30057145,
          30058145, 30059145, 30060145, 30061145, 30062145, 30054146, 30055146,
          30056146, 30057146, 31057146, 30058146, 30059146, 30060146, 30061146,
          30062146, 30054147, 30055147, 30056147, 30057147, 30058147, 30059147,
          30060147, 30061147, 30062147, 30063147, 30064147, 30055148, 30056148,
          30057148, 30058148, 30059148, 31059148, 30060148, 30061148, 31061148,
          30062148, 30055149, 30056149, 30057149, 30058149, 30059149, 30060149,
          30061149, 30062149, 30063149, 30064149, 30055150, 30056150, 30057150,
          30058150, 30059150, 30060150, 30061150, 30062150, 30055151, 30056151,
          30057151, 30058151, 30059151, 30060151, 30061151, 30062151, 30063151,
          30064151, 30065151, 30056152, 30057152, 30058152, 30059152, 30060152,
          30061152, 31061152, 30062152, 30063152, 31063152, 30064152, 30056153,
          30057153, 30058153, 30059153, 30060153, 30061153, 30062153, 30063153,
          30064153, 30065153, 30057154, 30058154, 30059154, 30060154, 30061154,
          31061154, 30062154, 30063154, 31063154, 30064154, 30057155, 30058155,
          30059155, 30060155, 30061155, 30062155, 30063155, 30064155, 31064155,
          30065155, 30066155, 30058156, 30059156, 30060156, 30061156, 30062156,
          30063156, 30064156, 30065156, 31065156, 30066156, 30058157, 30059157,
          30060157, 30061157, 30062157, 30063157, 30064157, 30065157, 30066157,
          30059158, 30060158, 30061158, 30062158, 30063158, 30064158, 30065158,
          31065158, 30066158, 30059159, 30060159, 30061159, 30062159, 30063159,
          30064159, 30065159, 30066159, 30067159, 31067159, 30060160, 30061160,
          30062160, 30063160, 30064160, 30065160, 30066160, 30060161, 30061161,
          30062161, 30063161, 30064161, 30065161, 30066161, 30067161, 31067161,
          30068161, 30061162, 30062162, 30063162, 30064162, 30065162, 30066162,
          30067162, 31067162, 30068162, 30061163, 30062163, 30063163, 30064163,
          30065163, 30066163, 30067163, 31067163, 30068163, 30062164, 30063164,
          30064164, 30065164, 30066164, 30067164, 31067164, 30068164, 30062165,
          30063165, 30064165, 30065165, 30066165, 31066165, 30067165, 30068165,
          30069165, 30063166, 30064166, 30065166, 30066166, 30067166, 31067166,
          30068166, 30069166, 30070166, 30063167, 30064167, 30065167, 30066167,
          30067167, 30068167, 31068167, 30069167, 30070167, 30064168, 30065168,
          30066168, 30067168, 30068168, 30069168, 30070168, 30064169, 30065169,
          30066169, 30067169, 30068169, 30069169, 30070169, 31070169, 30071169,
          31071169, 30065170, 30066170, 30067170, 31067170, 30068170, 30069170,
          30070170, 30065171, 30066171, 30067171, 30068171, 30069171, 30070171,
          30071171, 31071171, 30072171, 30066172, 30067172, 30068172, 30069172,
          30070172, 30071172, 31071172, 30072172} );
 }
Vec_Dbl createBounds_revlin (size_t n, double mult) static
Referenced by FakeFactory::newspStateSet_10nuclide().
 {
     Vec_Dbl bounds( n + 1 );
     for( size_t g = 0; g <= n; ++g )
     {
         bounds[g] = mult * ( n - g );
     }
     return bounds;
 }
Vec_Dbl createIntensity_gprop (size_t n, double mult) static
Referenced by FakeFactory::newspStateSet_10nuclide().
 {
     Vec_Dbl intensity( n );
     for( size_t g = 0; g < n; ++g )
     {
         intensity[g] = g * mult;
     }
     return intensity;
 }
SP_StateSet newspStateSet_10nuclide () static
Examples:
Core/ut/tests/tstObiwan.cpp.
References FakeFactory::createBounds_revlin(), FakeFactory::createIntensity_gprop(), Origen::GATOMS, State::set_alpha_spectra(), State::set_beta_spectra(), Spectrum::set_bounds(), StateInfo::set_case_number(), State::set_concs(), State::set_definition(), StateInfo::set_flux(), State::set_gamma_spectra(), NuclideSet::set_ids_legacy(), Spectrum::set_intensity(), NeutronSpectra::set_intensity_alphan(), NeutronSpectra::set_intensity_delayn(), NeutronSpectra::set_intensity_sf(), StateInfo::set_library_position(), State::set_neutron_spectra(), Concentrations::set_nuclide_set(), StateInfo::set_time(), Concentrations::set_units(), and Concentrations::set_vals().
Referenced by TEST().
 {
     jDebugLine( "Setting up StateSet" );
     SP_StateSet set( new StateSet() );
     // some reasonable ids
     Vec_Int base_zai( {80160,
                        922340,
                        922350,
                        922380,
                        942380,
                        942390,
                        942400,
                        942410,
                        942420,
                        601480} );
     Vec_Int base_iza(
         {8016, 92234, 92235, 92238, 94238, 94239, 94240, 94241, 94242, 60148} );
     // build nuclide set
     NuclideSet n1;
     n1.set_ids_legacy( 1, 8, 1, base_zai );
     for( int i = 1; i <= 20; ++i )
     {
         jDebugLine( "Setting up State " << i );
         State c1;
         // build state info
         StateInfo i1;
         i1.set_time( i * 10 * 24 * 3600 );
         i1.set_library_position( ( i - 1 ) / 2 + 1 );
         i1.set_case_number( i <= 10 ? 1 : 2 );
         i1.set_flux( 1e13 * ( i + 1.0 ) / 10.0 );
         c1.set_definition( i1 );
         // build concentrations
         Concentrations x1;
         x1.set_nuclide_set( n1 );
         x1.set_units( GATOMS );
         Vec_Dbl vals;
         vals.push_back( 1 );
         vals.push_back( 0.02 + i * 0.0001 );
         vals.push_back( 0.2 - i * 0.005 );
         vals.push_back( 1.8 - i * 0.05 );
         vals.push_back( i * 0.0001 );
         vals.push_back( i * 0.0002 );
         vals.push_back( i * 0.0003 );
         vals.push_back( i * 0.0004 );
         vals.push_back( 1e-300 );
         vals.push_back( i * 0.005 );
         x1.set_vals( vals );
         c1.set_concs( x1 );
         // build alpha
         AlphaSpectra a1;
         a1.set_bounds( createBounds_revlin( 10, 1.0 ) );
         a1.set_intensity( createIntensity_gprop( 10, 0.3 ) );
         c1.set_alpha_spectra( a1 );
         // build beta
         BetaSpectra b1;
         b1.set_bounds( createBounds_revlin( 10, 1.0 ) );
         b1.set_intensity( createIntensity_gprop( 10, 0.3 ) );
         c1.set_beta_spectra( b1 );
         // build gamma
         GammaSpectra g1;
         g1.set_bounds( createBounds_revlin( 10, 1.0 ) );
         g1.set_intensity( createIntensity_gprop( 10, 0.3 ) );
         c1.set_gamma_spectra( g1 );
         // build neutron
         NeutronSpectra n1;
         n1.set_bounds( createBounds_revlin( 10, 1.0 ) );
         n1.set_intensity( createIntensity_gprop( 10, 0.3 ) );
         n1.set_intensity_sf( createIntensity_gprop( 10, 0.31 ) );
         n1.set_intensity_alphan( createIntensity_gprop( 10, 0.32 ) );
         n1.set_intensity_delayn( createIntensity_gprop( 10, 0.33 ) );
         c1.set_neutron_spectra( n1 );
         jDebugLine( "Adding to StateSet" );
         set->add_states( c1 );
     }
     return set;
 }
SP_Library newspLibrary_10nuclide () static
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/fn/tests/tstio.cpp, Core/fn/tests/tsttabulate.cpp, and Core/ut/tests/tstObiwan.cpp.
References DecayData::abund_of_lite_nuclides, kernel_matrex::decay(), DecayData::decay_constants, DecayData::masses, NuclideSet::num_in_sublib(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, DecayData::recoverable_energy_values, TransitionCoeff::set_fission_xs(), NuclideSet::set_ids_legacy(), TransitionCoeff::set_loss_xs(), and Origen::SUBLIB_2AC.
Referenced by TEST().
 {
     jDebugLine( "Setting up library" );
     SP_Library lib( new Library );
     // some reasonable ids
     Vec_Int base_zai( {80160,
                        922340,
                        922350,
                        922380,
                        942380,
                        942390,
                        942400,
                        942410,
                        942420,
                        601480} );
     // setup header
     LibraryHeader header;
     NuclideSet lib_nucset;
     lib_nucset.set_ids_legacy( 1, 8, 1, base_zai );
     header.set_nuclide_set( lib_nucset );
     lib->set_definition( header );
     // setup decay data
     DecayData decay;
     Vec_Flt ones( lib->total_nuclides(), 1.0 );
     decay.decay_constants = ones;
     decay.recoverable_energy_values = ones;
     decay.q_fractions_from_photons = ones;
     decay.rcg_for_air = ones;
     decay.rcg_for_water = ones;
     decay.abund_of_lite_nuclides = ones;
     decay.masses = ones;
     lib->set_decay_data( decay );
     Vec_Flt ac_ones( lib_nucset.num_in_sublib( SUBLIB_2AC ), 1.0 );
     for( int i = 0; i < 20; ++i )
     {
         TransitionCoeff tc;
         tc.set_loss_xs( ones );
         tc.set_fission_xs( ac_ones );
         lib->add_transition_coeff( tc );
     }
     return lib;
 }
SP_Material newspMaterial_scale_pwr () static
Examples:
Core/fn/tests/tsttabulate.cpp.
References FakeFactory::Library_scale_pwr().
Referenced by TabulateMaterial::SetUp().
 {
     // create library
     SP_Library library = SP_Library( new Library() );
     bool created = FakeFactory::Library_scale_pwr( *library );
     if( !created ) return nullptr;
     string library_type = "pwr.*.orglib";
     std::string name = "mix1";
     int id = 1;
     double volume = 1.0;
     SP_Material mat( new Material( library_type, library, name, id, volume ) );
     return mat;
 }
The documentation for this class was generated from the following files:
Core/dc/FakeFactory.h
Core/dc/FakeFactory.cpp