ORIGEN API: AlphaSpectra Class Reference
AlphaSpectra Class Reference
#include <AlphaSpectra.h>
Container for alpha spectrum data.
Public Types
typedef std::shared_ptr< AlphaSpectra > SP
typedef std::shared_ptr< const AlphaSpectra > SCP
Typedefs
typedef std::function< SP_Vec_Dbl(const Vec_Dbl &, const Vec_Int &, const Vec_Dbl &)> Integrator_t
Basic Methods
const Vec_Dbl & bounds () const
return a const reference to bounds
void set_bounds (const Vec_Dbl &)
set the bounds (copy operation)
const Vec_Dbl & intensity () const
return a const reference to intensity
void set_intensity (const Vec_Dbl &)
set the intensity (copy operation)
Comparison
bool match (const Spectrum &) const
bool operator== (const Spectrum &) const
static bool match (const Spectrum &, const Spectrum &)
Convenience Methods
double total_intensity () const
EnergyRange_t energy_range () const
double mean_energy () const
double total_energy_intensity () const
SP_Vec_Dbl newsp_energy_intensity () const
Memory-usage Variants of Other Methods
Vec_Dbl * newptr_energy_intensity () const
SCP_Vec_Dbl scp_intensity () const
return a shared (read-only) intensity pointer
SCP_Vec_Dbl scp_bounds () const
return a shared (read-only) bounds pointer
Mapping Methods
bool map_intensity (const Vec_Dbl &new_bounds, Integrator_t integrator, Vec_Dbl *intensity, double wt=1.0, double tol=ETOL) const
bool map_intensity (const Vec_Dbl &new_bounds, Vec_Dbl *intensity, double wt=1.0, double tol=ETOL) const
void remap_intensity (Vec_Dbl *intensity, double wt=1.0) const
bool has_mapping_variables () const
void clear_mapping_variables () const
std::string print_bins () const
Additional Methods for Language Bindings (e.g. Fortran)
double bounds_at (size_t) const
get element of bounds vector by index
double const * bounds_array () const
return view of bounds vector
size_t bounds_size () const
return size of bounds vector
bool has_bounds () const
return whether the class has a non-null bounds
void get_bounds (Vec_Dbl &) const
populate an existing Vec_Dbl with a copy of bounds
void manageptr_bounds (Vec_Dbl *&)
set the bounds (ownership transfer)
void getptr_bounds (Vec_Dbl const *&) const
retrieve pointer (read-only) to bounds
void get_bounds_array (size_t, double *) const
get array of bounds vector (Fortran)
void set_bounds_array (size_t, double *)
set bounds vector from array (Fortran)
double intensity_at (size_t) const
get element of intensity vector by index
double const * intensity_array () const
return view of intensity vector
size_t intensity_size () const
return size of intensity vector
bool has_intensity () const
return whether the class has a non-null intensity
void get_intensity (Vec_Dbl &) const
populate an existing Vec_Dbl with a copy of intensity
void manageptr_intensity (Vec_Dbl *&)
set the intensity (ownership transfer)
void getptr_intensity (Vec_Dbl const *&) const
retrieve pointer (read-only) to intensity
void get_intensity_array (size_t, double *) const
get array of intensity vector (Fortran)
void set_intensity_array (size_t, double *)
set intensity vector from array (Fortran)
Static Helper Functions
returns true if the new and old bounds have the same min/max energy, i.e. the mapping will be conservative
static void map_intensity (const Vec_Dbl &old_bounds, const Vec_Dbl &new_bounds, const Vec_Int &union_to_old, const Vec_Int &union_to_new, const Vec_Dbl &union_grid, const Vec_Dbl &old_intensity, const Vec_Dbl &union_wts, Vec_Dbl *new_intensity, double wt=1.0)
static std::string print_bins (const Vec_Dbl &bounds, const Vec_Dbl &intensity)
static bool map_bins (const Vec_Dbl &old_bounds, const Vec_Dbl &new_bounds, Vec_Int *union_to_old, Vec_Int *union_to_new, Vec_Dbl *union_grid, double tol=ETOL)
static SP_Vec_Dbl computeUnionWts_1 (const Vec_Dbl &union_grid, const Vec_Int &union_to_old, const Vec_Dbl &old_flux)
Other
SP_Vec_Dbl b_bounds
SP_Vec_Dbl b_intensity
void canonicalize_bounds ()
void canonicalize_intensity ()
Public Member Functions
AlphaSpectra ()
AlphaSpectra (const AlphaSpectra &orig)
virtual ~AlphaSpectra ()
int nuclide_type () const
void set_nuclide_type (int nuclide_type)
virtual bool match (const AlphaSpectra &) const
virtual bool operator== (const AlphaSpectra &) const
Static Public Member Functions
static bool match (const AlphaSpectra &, const AlphaSpectra &)
Protected Attributes
int d_nuclide_type
Detailed Description
Container for alpha spectrum data.
The AlphaSpectra data container manages the alpha intensity and the group structure.
Examples:
Core/dc/tests/tstAlphaSpectra.cpp.
Member Typedef Documentation
typedef std::shared_ptr<AlphaSpectra> SP
typedef std::shared_ptr<const AlphaSpectra> SCP
typedef std::function<SP_Vec_Dbl(const Vec_Dbl &, const Vec_Int &, const Vec_Dbl &)> Integrator_t inherited
Constructor & Destructor Documentation
AlphaSpectra ()
AlphaSpectra (const AlphaSpectra & orig)
virtual ~AlphaSpectra () inline virtual
Member Function Documentation
int nuclide_type () const
References AlphaSpectra::d_nuclide_type.
Referenced by AlphaSpectra::set_nuclide_type(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
void set_nuclide_type (int nuclide_type)
References AlphaSpectra::d_nuclide_type, and AlphaSpectra::nuclide_type().
Referenced by StateSetIO_bof::read(), StateSetIO_s62b::read(), and FakeFactory::StateSet_random1().
bool match (const AlphaSpectra & a, const AlphaSpectra & b) static
References AlphaSpectra::d_nuclide_type, and Spectrum::match().
Referenced by AlphaSpectra::match().
bool match (const AlphaSpectra & b) const virtual
References AlphaSpectra::match().
bool operator== (const AlphaSpectra & b) const virtual
References AlphaSpectra::d_nuclide_type, and Spectrum::operator==().
const Vec_Dbl & bounds () const inherited
return a const reference to bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Spectrum goes out of scope.
Referenced by Spectrum::operator==(), and StateSetIO_bof::write().
void set_bounds (const Vec_Dbl & bounds) inherited
set the bounds (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstEmissionSpectrum.cpp, Core/re/tests/tstEmissionResource.cpp, and Core/re/tests/tstGammaResource.cpp.
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), GammaResourceIO_cimg::read(), StateSetIO_bof::read(), StateSetIO_s61::read(), FakeFactory::StateSet_random1(), and TEST().
const Vec_Dbl & intensity () const inherited
return a const reference to intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Spectrum goes out of scope.
Referenced by Spectrum::operator==(), and StateSetIO_bof::write().
void set_intensity (const Vec_Dbl & intensity) inherited
set the intensity (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), StateSetIO_bof::read(), GammaResourceIO_cimg::read(), and FakeFactory::StateSet_random1().
bool match (const Spectrum & b) const inherited
Referenced by NeutronSpectra::match(), BetaSpectra::match(), GammaSpectra::match(), and AlphaSpectra::match().
bool match (const Spectrum & a, const Spectrum & b) static inherited
References Spectrum::b_bounds.
bool operator== (const Spectrum & b) const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, Spectrum::bounds(), and Spectrum::intensity().
Referenced by AlphaSpectra::operator==(), GammaSpectra::operator==(), and BetaSpectra::operator==().
double total_intensity () const inherited
References Spectrum::b_intensity, and Spectrum::has_intensity().
Referenced by Spectrum::mean_energy(), and EmissionSpectrum::total_intensity().
EnergyRange_t energy_range () const inherited
References Spectrum::b_bounds, Origen::EMAX, Origen::EMIN, and auxiliary_erf_m::er.
Referenced by EmissionSpectrum::energy_range().
double mean_energy () const inherited
References Spectrum::total_energy_intensity(), and Spectrum::total_intensity().
double total_energy_intensity () const inherited
References Spectrum::newsp_energy_intensity().
Referenced by Spectrum::mean_energy(), and EmissionSpectrum::total_energy_intensity().
SP_Vec_Dbl newsp_energy_intensity () const inherited
References Spectrum::newptr_energy_intensity().
Referenced by Spectrum::total_energy_intensity().
Vec_Dbl * newptr_energy_intensity () const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, and Spectrum::intensity_size().
Referenced by Spectrum::newsp_energy_intensity().
SCP_Vec_Dbl scp_intensity () const inherited
return a shared (read-only) intensity pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
SCP_Vec_Dbl scp_bounds () const inherited
return a shared (read-only) bounds pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool map_intensity (const Vec_Dbl & new_bounds, Integrator_t integrator, Vec_Dbl * intensity, double wt = 1.0, double tol = ETOL) const inherited
Referenced by EmissionSpectrum::bin(), Spectrum::map_intensity(), and Spectrum::remap_intensity().
bool map_intensity (const Vec_Dbl & new_bounds, Vec_Dbl * intensity, double wt = 1.0, double tol = ETOL) const inherited
References Spectrum::computeUnionWts_1(), and Spectrum::map_intensity().
void map_intensity (const Vec_Dbl & old_bounds, const Vec_Dbl & new_bounds, const Vec_Int & union_to_old, const Vec_Int & union_to_new, const Vec_Dbl & union_grid, const Vec_Dbl & old_intensity, const Vec_Dbl & union_wts, Vec_Dbl * new_intensity, double wt = 1.0) static inherited
void remap_intensity (Vec_Dbl * intensity, double wt = 1.0) const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, Spectrum::b_union_wts, Spectrum::has_mapping_variables(), and Spectrum::map_intensity().
bool has_mapping_variables () const inherited
References Spectrum::b_intensity, Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, and Spectrum::b_union_wts.
Referenced by Spectrum::remap_intensity().
void clear_mapping_variables () const inherited
References Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, and Spectrum::b_union_wts.
std::string print_bins () const inherited
Examples:
Core/dc/tests/tstDiscreteSpectrum.cpp, Core/dc/tests/tstEmissionSpectrum.cpp, Core/io/tests/tstGammaResourceIO.cpp, Core/re/tests/tstEmissionResource.cpp, and Core/re/tests/tstGammaResource.cpp.
References Spectrum::b_bounds, and Spectrum::b_intensity.
Referenced by EmissionSpectrum::print_continuous(), TEST(), and TEST_P().
std::string print_bins (const Vec_Dbl & bounds, const Vec_Dbl & intensity) static inherited
Vec_Dbl::value_type bounds_at (size_t i) const inherited
get element of bounds vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/io/tests/tstGammaResourceIO.cpp.
Referenced by TEST().
Vec_Dbl::value_type const * bounds_array () const inherited
return view of bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t bounds_size () const inherited
return size of bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by Spectrum::canonicalize_intensity().
bool has_bounds () const inherited
return whether the class has a non-null bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_bounds (Vec_Dbl & bounds) const inherited
populate an existing Vec_Dbl with a copy of bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_bounds (Vec_Dbl *& bounds) inherited
set the bounds (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_bounds (Vec_Dbl const *& bounds) const inherited
retrieve pointer (read-only) to bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_bounds_array (size_t , double *) const inherited
get array of bounds vector (Fortran)
void set_bounds_array (size_t , double *) inherited
set bounds vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type intensity_at (size_t i) const inherited
get element of intensity vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type const * intensity_array () const inherited
return view of intensity vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t intensity_size () const inherited
return size of intensity vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by NeutronSpectra::is_consistent(), Spectrum::newptr_energy_intensity(), EmissionSpectrum::num_continuous(), and NeutronSpectra::resum().
bool has_intensity () const inherited
return whether the class has a non-null intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Spectrum::total_intensity().
void get_intensity (Vec_Dbl & intensity) const inherited
populate an existing Vec_Dbl with a copy of intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_intensity (Vec_Dbl *& intensity) inherited
set the intensity (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_intensity (Vec_Dbl const *& intensity) const inherited
retrieve pointer (read-only) to intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_intensity_array (size_t , double *) const inherited
get array of intensity vector (Fortran)
void set_intensity_array (size_t , double *) inherited
set intensity vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
bool map_bins (const Vec_Dbl & old_bounds, const Vec_Dbl & new_bounds, Vec_Int * union_to_old, Vec_Int * union_to_new, Vec_Dbl * union_grid, double tol = ETOL) static inherited
SP_Vec_Dbl computeUnionWts_1 (const Vec_Dbl & union_grid, const Vec_Int & union_to_old, const Vec_Dbl & old_flux) static inherited
Referenced by Spectrum::map_intensity().
void canonicalize_bounds () protected inherited
void canonicalize_intensity () protected inherited
References Spectrum::b_intensity, and Spectrum::bounds_size().
Member Data Documentation
int d_nuclide_type protected
sources nuclide type (0/1/2/3/4 === none/lite/act/fp/all)
Referenced by AlphaSpectra::match(), AlphaSpectra::nuclide_type(), AlphaSpectra::operator==(), and AlphaSpectra::set_nuclide_type().
SP_Vec_Dbl b_bounds protected inherited
Referenced by Spectrum::energy_range(), Spectrum::match(), Spectrum::newptr_energy_intensity(), Spectrum::operator==(), Spectrum::print_bins(), and Spectrum::remap_intensity().
SP_Vec_Dbl b_intensity protected inherited
Referenced by Spectrum::canonicalize_intensity(), Spectrum::has_mapping_variables(), NeutronSpectra::is_consistent(), Spectrum::newptr_energy_intensity(), Spectrum::operator==(), Spectrum::print_bins(), Spectrum::remap_intensity(), NeutronSpectra::resum(), and Spectrum::total_intensity().
The documentation for this class was generated from the following files:
Core/dc/AlphaSpectra.h
Core/dc/AlphaSpectra.cpp