OrigenAPI: LibraryTest Class Reference
LibraryTest Class Reference
Protected Member Functions
virtual void SetUp ()
Protected Attributes
Library lib
Detailed Description
Definition at line 32 of file tstLibrary.cpp.
Member Function Documentation
virtual void LibraryTest::SetUp () inline protected virtual
Definition at line 35 of file tstLibrary.cpp.
References Origen::FakeFactory::DecayData_random1(), Origen::LibraryHeader::set_day_made(), Origen::NuclideSet::set_ids_legacy(), Origen::LibraryHeader::set_month_made(), Origen::LibraryHeader::set_nuclide_set(), Origen::LibraryHeader::set_title(), Origen::LibraryHeader::set_year_made(), Origen::TagManager::setIdTag(), Origen::TagManager::setInterpTag(), Origen::FakeFactory::TransitionCoeff_random1(), and Origen::FakeFactory::TransitionStructure_random1().
     {
         // nuclide set
         NuclideSet nucSet;
         nucSet.set_ids_legacy( 2, 2, 1, {1, 2, 235, 128, 135} );
         // header
         LibraryHeader header;
         header.set_nuclide_set( nucSet );
         header.set_month_made( 3 );
         header.set_day_made( 29 );
         header.set_year_made( 2013 );
         header.set_title( "TestHeader" );
         lib.set_definition( header );
         // tag manager
         TagManager tagMan;
         tagMan.setIdTag( "Lattice type", "Westinghouse 17x17" );
         tagMan.setIdTag( "Pin location", "Corner" );
         tagMan.setIdTag( "Fuel type", "UO2" );
         tagMan.setInterpTag( "Enrichment", 4.5 );
         tagMan.setInterpTag( "Number of Gadolinium Rods", 8 );
         lib.set_tag_manager( tagMan );
         // transition structure
         TransitionStructure tStruct;
         FakeFactory::TransitionStructure_random1( tStruct, header );
         lib.set_transition_structure( tStruct );
         // decay data
         DecayData decayDat;
         FakeFactory::DecayData_random1( decayDat, header );
         lib.set_decay_data( decayDat );
         // transition coeff
         TransitionCoeff transCoeff;
         FakeFactory::TransitionCoeff_random1( transCoeff, header );
         lib.set_transition_coeff_at( transCoeff, 0 );
     }
Member Data Documentation
Library LibraryTest::lib protected
Definition at line 75 of file tstLibrary.cpp.
The documentation for this class was generated from the following file:
Core/dc/tests/tstLibrary.cpp