ORIGEN API: YieldData Class Reference
YieldData Class Reference
#include <YieldResource.h>
Public Member Functions
YieldData ()
~YieldData ()
double energy () const
get energy
void set_energy (double value)
set energy
int num_yields () const
get number of yields
double yield_at (int index) const
get yields
void set_yield_at (int index, double yield)
set a yield by index
void clear ()
clear the data
void reset_yields ()
set all yields to zero
Protected Member Functions
Vec_Dbl & yields ()
get yields as a vector
const Vec_Dbl & yields () const
get yields as a const vector
Private Attributes
double b_energy
Vec_Dbl b_yields
Friends
class YieldParent
class YieldResource
Detailed Description
Examples:
tstYieldResource.cpp.
Constructor & Destructor Documentation
YieldData ()
~YieldData ()
Member Function Documentation
double energy () const
get energy
Examples:
tstYieldResource.cpp.
References YieldData::b_energy.
Referenced by YieldResource::check_consistency(), YieldParent::get_interp_yields(), ReactionResource::import_fission_yields(), print_yield_data(), Origen::printYieldEnergies(), Origen::printYields(), and TEST().
void set_energy (double value)
set energy
References YieldData::b_energy.
Referenced by YieldParent::add_data().
int num_yields () const
get number of yields
Examples:
tstYieldResource.cpp.
References YieldData::b_yields.
Referenced by ReactionResource::import_fission_yields(), YieldData::set_yield_at(), TEST(), YieldResourceIO_ampx::write(), and YieldData::yield_at().
double yield_at (int index) const
get yields
Examples:
tstYieldResource.cpp.
References YieldData::b_yields, and YieldData::num_yields().
Referenced by YieldParent::get_interp_yields(), get_yield(), ReactionResource::import_fission_yields(), print_yield_data(), Origen::printInterpolatedYields(), Origen::printYields(), TEST(), Origen::test::TEST_F(), and YieldResourceIO_ampx::write().
void set_yield_at (int index, double yield)
set a yield by index
References YieldData::b_yields, and YieldData::num_yields().
Referenced by YieldParent::add_data(), and main().
void clear ()
clear the data
References YieldData::b_yields.
void reset_yields ()
set all yields to zero
References YieldData::b_yields.
Referenced by YieldParent::add_data().
Vec_Dbl & yields () protected
get yields as a vector
References YieldData::b_yields.
Referenced by YieldResource::check_consistency(), YieldParent::get_interp_yields(), and YieldParent::get_yields().
const Vec_Dbl & yields () const protected
get yields as a const vector
References YieldData::b_yields.
Friends And Related Function Documentation
friend class YieldParent friend
friend class YieldResource friend
Member Data Documentation
double b_energy private
Referenced by YieldData::energy(), and YieldData::set_energy().
Vec_Dbl b_yields private
Referenced by YieldParent::add_data(), YieldData::clear(), YieldData::num_yields(), YieldData::reset_yields(), YieldData::set_yield_at(), YieldData::yield_at(), and YieldData::yields().
The documentation for this class was generated from the following files:
Core/re/YieldResource.h
Core/re/YieldResource.cpp