ORIGEN API: Unitless Struct Reference
Unitless Struct Reference
#include <History.h>
Public Types
enum UNITS { UNKNOWN = -1, ONE = 0, END }
Static Public Member Functions
template<Unitless::UNITS u>
static std::string name ()
static std::string name (Unitless::UNITS u)
template<Unitless::UNITS u>
static double base ()
static double base (Unitless::UNITS u)
template<Unitless::UNITS to, Unitless::UNITS from>
static double factor ()
template<Unitless::UNITS to>
static double factor (Unitless::UNITS from)
static double factor (Unitless::UNITS to, Unitless::UNITS from)
static Unitless::UNITS units (const char *s)
static constexpr Unitless::UNITS units (int i)
Static Public Attributes
static const UNITS DEFAULT = ONE
Member Enumeration Documentation
enum UNITS
Enumerator
UNKNOWN
ONE
END
     {
         UNKNOWN = -1,
         ONE = 0,
         END
     };
Member Function Documentation
static std::string name () static
std::string name (Unitless::UNITS u) inline static
References Unitless::ONE.
 {
     if( u == ONE ) return name<ONE>();
     return "";
 }
static double base () static
Referenced by Unitless::factor().
double base (Unitless::UNITS u) inline static
References Unitless::ONE.
 {
     if( u == ONE ) return base<ONE>();
     return 0.0;
 }
static double factor () inline static
     {
         return base<from>() / base<to>();
     }
static double factor (Unitless::UNITS from) inline static
References Unitless::base().
     {
         return base( from ) / base<to>();
     }
static double factor (Unitless::UNITS to, Unitless::UNITS from) inline static
References Unitless::base().
     {
         return base( from ) / base( to );
     }
Unitless::UNITS units (const char * s) inline static
References Unitless::ONE, and Unitless::UNKNOWN.
 {
     if( s == name<ONE>() ) return ONE;
     return UNKNOWN;
 }
static constexpr Unitless::UNITS units (int i) inline static
     {
         return static_cast<Unitless::UNITS>( i );
     }
Member Data Documentation
const UNITS DEFAULT = ONE static
The documentation for this struct was generated from the following files:
Core/dc/History.h
Core/dc/History.i.h