ORIGEN API: Obiwan_convert Class Reference
Obiwan_convert Class Reference
#include <Obiwan_convert.h>
execute obiwan in convert mode
Public Member Functions
Obiwan_convert (int argc, char **argv)
Obiwan_convert (ScaleUtils::IO::DB opts)
~Obiwan_convert () noexcept(false)
int execute (std::ostream &out, std::ostream &err)
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in convert mode
Examples:
Core/ut/tests/tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_convert (int argc, char ** argv)
References Obiwan_convert::b_opts, and Obiwan_convert::populate().
 {
     b_opts = populate( argc, argv );
 }
Obiwan_convert (ScaleUtils::IO::DB opts)
 : b_opts( opts ) {}
~Obiwan_convert () inline noexcept
 {}
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_convert::execute().
 {
     const char* help = R"help(
 //! [help]
  PURPOSE: convert ORIGEN binary files to a different format
  USAGE: obiwan convert -version=String(V) [opts]  file1 file2
         -flag=Type(DefaultValue)       DESCRIPTION
         ________________________       ____________________________
         -version=String(6.2)           target output version (6.1|6.2)
                                          6.1: sets -format=s61
                                          6.2: sets -format=bof
         -format=String()               target output format (mutually exclusive with -version)
                                          s61: SCALE 6.1 fortran binary
                                         s62b: SCALE 6.2 beta fortran binary
                                          bof: SCALE 6.2+ Binary Object Format
         -type=String()                 load only a partciular type
                                           f33: Origen::Library
                                           f71: Origen::StateSet
                                           yld: Origen::YieldResource
                                           dec: Origen::DecayResource
         -dir=String(.)                 existing directory for converted files
         -i                             overwrite existing files
         -remove_mass                   remove masses on a library
         -remove_abund                  remove abundances on a library
         -verbose                       verbose mode (extra output to STDERR)
         -endian=String()               request for endianness of converted files
                                          big: big endian
                                          little: little endian
                                          otherwise: native endian
                                          (will not be possible in all scenarios)
         -thin=Int(0)                   enable thinning if equal 1 (0|1)
         THINNING OPTIONS (only valid if -thin=1)
         -interp=String(near)           time interpolation method (near|lin|cubic)
         -tvals=Array()                 list of times (MWD/MTHM) to keep/interpolate to (default is all)
                                        in JSON array format, e.g. "[0,100,250,1000,50000]"
         -rvar=String(loxs)             response variable to base thinning on (loxs)
                                        loxs : total loss cross section
         -rnuc=String(pu240)            which nuclide's yvar to use (pu240)
         -setbu=Array()                 set burnups on the library
  NOTE: all non-essential output goes to STDERR
  EXAMPLE 1 (converting file formats):
     $ mkdir new
     $ obiwan convert -version=6.2 -dir=new $DATA/arplibs/a10_e15w01.arplib 2>log
               originalFile            dataType             convertedFile fileFormat    ms errors
          a10_e15w01.arplib     Origen::Library            a10_e15w01.f33        bof 1e+01      -
  EXAMPLE 2 (keep only these burnups or those nearest):
     $ mkdir test
     $ obiwan convert -thin=1 -i -tvals="[0,100,250,500,1000,1500,2000]" -dir=test $DATA/arplibs/a10_e15w01.arplib 2>log
               originalFile            dataType             convertedFile fileFormat    ms errors
          a10_e15w01.arplib     Origen::Library            a10_e15w01.f33        bof 6e+01      -
     #test sizes on disk
     $ du -h $DATA/arplibs/a10_e15w01.arplib
             1.9M    /Users/ww5/lib/scale_dev_data/arplibs/a10_e15w01.arplib
     $ du -h test/a10_e15w01.f33
             1.3M    test/a10_e15w01.f33
     #check with obiwan info
     $ obiwan info $DATA/arplibs/a10_e15w01.arplib test/a10_e15w01.f33 2>log
                   fileName            dataType numSets fileFormat fileType file/sysEndian appVersion    ms   directory
          a10_e15w01.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
             a10_e15w01.f33     Origen::Library       7        bof   binary  little/little 6.2.pre-b5 2e+01   test
     #verify burnups
     $ obiwan view -format=burnups $DATA/arplibs/a10_e15w01.arplib 2>log
                MWd/MTIHM
            0      0.0000
            1   1500.0000
            2   4500.0000
            3   7500.0000
            4  10500.0000
            5  13500.0000
            6  16500.0000
            7  31500.0000
            8  46500.0000
            9  58500.0000
           10  70500.0000
     $ obiwan view -format=burnups test/a10_e15w01.f33 2>log
                MWd/MTIHM
            0      0.0000
            1    100.0000
            2    250.0000
            3    500.0000
            4   1000.0000
            5   1500.0000
            6   2000.0000
 //! [help]
     )help";
     // break up tag so Doxygen doesn't think this is a 3rd tag
     return ScaleUtils::IO::removeSubstring( help,
                                             "//! ["
                                             ""
                                             "help"
                                             ""
                                             "]" );
 }
ScaleUtils::IO::DB populate (int argc, char ** argv) static
References Origen::baseOptions().
Referenced by Obiwan_convert::Obiwan_convert().
 {
     Standard::CommandLine cmd( argc, argv );
     // get files
     Origen::Vec_Str files = cmd.arguments();
     ScaleUtils::IO::DB base;
     // output error message
     if( files.size() == 0 )
     {
         base.set( "help", true );
     }
     else
     {
         // expand globs (e.g. *.txt)
         ScaleUtils::IO::expandPaths( files );
         // debugging echo
         jDebugLine( cmd.toString() );
         // set
         base = baseOptions( cmd );
         base.set( "paths", new StringList( files ) );
         jDebugLine( base.toString() );  // debugging
     }
     return base;
 }
int execute (std::ostream & out, std::ostream & err)
References Obiwan_convert::b_opts, Origen::convertLibrary(), Origen::convertStateSet(), Obiwan_convert::help(), and Origen::loadMulti().
Referenced by Origen::obiwan_main().
 {
     // quick returns
     if( b_opts.get( "help", false ) )
     {
         out << help() << std::endl;
         return 1;
     }
     else if( b_opts.numError() > 0 )
     {
         out << b_opts.dumpErrorStack();
         return -1;
     }
     auto files = b_opts.get<StringList*>( "paths" );
     ScaleUtils::IO::Table2D table;
     table.setTitle( "originalFile" );
     table.addX( "dataType" );
     table.addX( "loadedFormat" );
     table.addX( "convertedFile" );
     table.addX( "savedFormat" );
     table.addX( "runtime(ms)" );
     table.addX( "errors" );
     // Loop over files.
     for( const auto& path : *files )
     {
         // variables
         SP_Library lib;
         SP_StateSet mat;
         ScaleUtils::IO::DB opts = b_opts.clone();
         bool verbose = opts.get<bool>( "verbose", false );
         // load data
         void* obj_ptr = loadMulti( path, opts );
         // perform conversion
         std::string loadedDataType = opts.get( "loadedDataType", "UNKNOWN" );
         if( opts.numError() == 0 )
         {
             // update what to write
             opts.set( "fileFormat", opts.get( "desiredFileFormat", "" ) );
             opts.set( "targetScaleVersion",
                       opts.get( "desiredTargetScaleVersion", "" ) );
             if( loadedDataType == "Origen::Library" )
             {
                 lib = Origen::SP_Library( (Library*)( obj_ptr ) );
                 Check( lib );
                 convertLibrary( *lib, path, opts );
             }
             else if( loadedDataType == "Origen::StateSet" )
             {
                 mat = Origen::SP_StateSet( (StateSet*)( obj_ptr ) );
                 Check( mat );
                 convertStateSet( *mat, path, opts );
             }
         }
         // new row of table
         table.addRow();
         table.addY( ScaleUtils::IO::getBaseName( path ) );
         table.addCell( loadedDataType );
         table.addCell( opts.get( "loadedFileFormat", "-" ) );
         table.addCell( opts.numError() == 0 ? opts.get( "fileName", "-" )
                                             : "-" );
         table.addCell( opts.get( "savedFileFormat", "-" ) );
         // output options in JSON
         if( verbose ) err << opts << std::endl;
         // add runtime
         table.addCell( nprintf( " %.0e",
                                 opts.get<double>( "loadTime", 0.0 ) +
                                     opts.get<double>( "saveTime", 0.0 ) ) );
         // add errors
         if( opts.numError() == 1 )
         {
             table.addCell( opts.errorStack()[0] );
         }
         else if( opts.numError() > 1 )
         {
             std::string file =
                 opts.get( "fileName", "obiwan-convert" ) + ".err";
             table.addCell( "see file='" + file + "'" );
             std::ofstream ofs( file );
             ofs << opts.dumpErrorStack();
         }
         else
         {
             table.addCell( "-" );
         }
         // clear everything so we don't get a throw
         opts.clear();
     }
     out << table.straight().text( 12, 8 );
     return 0;
 }
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_convert::execute(), and Obiwan_convert::Obiwan_convert().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_convert.h
Core/ut/Obiwan_convert.cpp