ORIGEN API: Core/dc/tests/tstEmissionSpectrum.cpp File Reference
tstEmissionSpectrum.cpp File Reference
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <istream>
#include <sstream>
#include <string>
#include <vector>
#include "Origen/Core/dc/EmissionSpectrum.h"
#include "Origen/Core/dc/FakeFactory.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Nemesis/harness/DBC.hh"
Functions
TEST (EmissionSpectrum, Binning)
Function Documentation
TEST (EmissionSpectrum , Binning)
Examples:
tstEmissionSpectrum.cpp.
References DiscreteSpectrum::add_line(), EmissionSpectrum::bin(), Spectrum::print_bins(), Spectrum::set_bounds(), EmissionSpectrum::set_continuous(), and EmissionSpectrum::set_discrete().