ORIGEN API: Obiwan_view Class Reference
Obiwan_view Class Reference
#include <Obiwan_view.h>
execute obiwan in view mode
Public Member Functions
Obiwan_view (int argc, char **argv)
Obiwan_view (ScaleUtils::IO::DB opts)
~Obiwan_view () noexcept(false)
int execute (std::ostream &out, std::ostream &err)
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in view mode
Examples:
Core/ut/tests/tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_view (int argc, char ** argv)
References Obiwan_view::b_opts, and Obiwan_view::populate().
 {
     b_opts = populate( argc, argv );
 }
Obiwan_view (ScaleUtils::IO::DB opts)
 : b_opts( opts ) {}
~Obiwan_view () inline noexcept
 {}
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_view::execute().
 {
     const char* help = R"help(
 //! [help]
  purpose: display detailed contents of ORIGEN binary files
  usage: obiwan view  -format=String()  [opts]  file
         -flag=Type(DefaultValue)       DESCRIPTION
         ________________________       ____________________________
         -prec=Int(4)                   number of significant digits to output
         -zeros=Bool(1)                 whether to output zero values
         -symbols=Bool(0)               whether to output numeric ids (1001) or symbols (H-1)
                                        same as -idform='$S:$ee$AAA$m'
         -transpose=Bool(0)             whether to transpose table
         -pos=Int(1)                    position in library to output (0 is all positions)
                                        <0 means NORMALIZE output to that position
                                        this is very useful for viewing xs data
                                        across many scales
         -sizzzaaa=Int(0)               nuclide identifier s=sublibrary 1|2|3
                                        e.g. u235 as an actinide is 20092235
                                                                    SIZZZAAA
         -idform=String($S$I$ZZZ$AAA)   controls printout of ids, the following
                                        are subsituted
                                          $S - sublib integer
                                          $I - isomeric state integer
                                        $ZZZ - up to 3 digits of atomic number (also Z, ZZ)
                                        $AAA - up to 3 digits of mass number (also A, AA)
                                         $EE - up to 2 characters elemental symbol (also Ee,ee for different case)
                                          $M - metastable indicator 'M' for first, 'M2' for second, etc. (also m)
                                        DEFAULT with -symbols=0 -> -idform='$S$I$ZZZ$AAA'
                                                with -symbols=1 -> -idform='$S:$ee$AAA$m'
         -units=String()                when printing, choose units
                                          type  format  units
                                           f71     csv  abso|fiss|capt|airm|apel|
                                                        atom|becq|curi|gamw|gamm|
                                                        gato|gper|gram|h2om|kilo|
                                                        wpel|watt|mevs|part|inte|
                                                        ener
         -type=String()                 load only a partciular type
                                           f33: Origen::Library
                                           f71: Origen::StateSet
                                           yld: Origen::YieldResource
                                           dec: Origen::DecayResource
         -tid=Int(0)                    otherwise uses trial and error
                                        transition id: dk mode (<0) or reaction MT number (>0)
         -flux=Real(1.0)                multiply reaction matrix coefficients by flux (n/cm^2s)
         Filter input (NOTE: with -format=graphviz only)
         -allow_s=Array(2)              JSON-formatted list of sublibs integers (1,2,3)
         -allow_i=Array()               JSON-formatted list of isomeric states ()
         -allow_z=Array()               JSON-formatted list of atomic numbers ()
         -allow_a=Array()               JSON-formatted list of mass numbers ()
         -allow_decay=Bool(true)        whether to display decay transitions
         -allow_fission=Bool(false)     whether to display fission transitions
         -allow_reaction=Bool(true)     whether to display reaction transitions
         -allow_transition_id()         JSON-formatted list of transition ids
         -include_byproducts            whether to include byproduct reactions arrows
         -format=String()               format for output
                                        Origen::Library formats
                                            coeff   - output tabular transition coefficients
                                            coefft  - same as coeff but with transition ids (dk/mts)
                                            json    - output in JSON format
                                            tags    - output file tags
                                            nucl    - nuclide list
                                            nprodr  - neutron production ratio
                                            genneu  - neutron generation
                                            loxs    - loss xs
                                            fisxs   - fission xs
                                            ts      - transition system
                                            burnups - output burnup list
                                           reaction - allowed reactions
                                           graphviz - output dot file of transitions to STDOUT
                                       Origen::StateSet
                                            csv     - comma-separated values
                                            info    - information table
                                            tags    - tags stored on each state
  NOTE: all non-essential output goes to STDERR
  example:
     #display a table of loss cross section data
     #pos=0 is for all positions (burnups) on library
     $ obiwan view -format=loxs -pos=0 ./a10_e15w01.bof 2>/dev/null
      nuclide  0.0000e+00  1.5000e+03  4.5000e+03  7.5000e+03  1.0500e+04  1.3500e+04  1.6500e+04  3.1500e+04  4.6500e+04  5.8500e+04  7.0500e+04
     10001001  2.5724e-01  2.6172e-01  2.6315e-01  2.6400e-01  2.6582e-01  2.6731e-01  2.6850e-01  2.7275e-01  2.7622e-01  2.7860e-01  2.8056e-01
     10001002  8.9254e-03  9.6637e-03  9.8350e-03  9.9177e-03  1.0278e-02  1.0590e-02  1.0853e-02  1.1883e-02  1.2778e-02  1.3409e-02  1.3945e-02
     10001003  2.3025e-04  2.4988e-04  2.5428e-04  2.5635e-04  2.6587e-04  2.7415e-04  2.8111e-04  3.0845e-04  3.3223e-04  3.4898e-04  3.6325e-04
     10001004  1.2445e+11  1.3507e+11  1.3744e+11  1.3856e+11  1.4371e+11  1.4818e+11  1.5194e+11  1.6672e+11  1.7957e+11  1.8863e+11  1.9634e+11
     ...
     #you could always pipe through grep, e.g. | grep 20092235 to get a
     #particular line, but in many cases, the transpose table is better
     #note normalization to first position value
     $ obiwan view -format=loxs -sizzzaaa=20092235 -pos=-1 -transpose=1 ./a10_e15w01.bof 2>/dev/null
              nuclide    20092235
           0.0000e+00  1.0000e+00
           1.5000e+03  9.9738e-01
           4.5000e+03  1.0177e+00
           7.5000e+03  1.0398e+00
           1.0500e+04  1.0466e+00
           1.3500e+04  1.0517e+00
           1.6500e+04  1.0560e+00
           3.1500e+04  1.0677e+00
           4.6500e+04  1.0709e+00
           5.8500e+04  1.0711e+00
           7.0500e+04  1.0707e+00
     #output transitions (neato from graphviz works best)
     obiwan view -format=graphviz -allow_s="[1,2,3]" -include_byproducts=0 \
         $DATA/origen_library/pwr.rev03.orglib >transitions.dot
     neato -n1 transitions.dot -T pdf >transitions.pdf
 //! [help]
     )help";
     // break up tag so Doxygen doesn't think this is a 3rd tag
     return ScaleUtils::IO::removeSubstring( help,
                                             "//! ["
                                             ""
                                             "help"
                                             ""
                                             "]" );
 }
ScaleUtils::IO::DB populate (int argc, char ** argv) static
References Origen::populateObiwan_dataType().
Referenced by Obiwan_view::Obiwan_view().
 {
     Standard::CommandLine cmd( argc, argv );
     // get files
     Origen::Vec_Str files = cmd.arguments();
     ScaleUtils::IO::DB base;
     // output error message
     if( files.size() == 0 )
     {
         base.set( "help", true );
     }
     else if( files.size() != 1 )
     {
         base.appendError( "Please provide 1 and only 1 filenames" );
     }
     else
     {
         // debugging echo
         jDebugLine( cmd.toString() );
         // expand globs (e.g. *.txt)
         ScaleUtils::IO::expandPaths( files );
         // main file
         base.set( "path", files[0] );
         // get data type to read
         populateObiwan_dataType( &base, cmd.getValue( "-type", "" ) );
         // output format
         // (json|coeff|coefft|nucl|ts|all_tags|id_tags|interp_tags)
         base.set( "format", cmd.getValue( "-format", "" ) );
         // other parameters
         base.set( "prec", cmd.getValueAs( "-prec", 4 ) );
         base.set( "zeros", cmd.getValueAs( "-zeros", 1 ) == 1 );
         base.set( "pos", cmd.getValueAs( "-pos", 1 ) );
         base.set( "sizzzaaa", cmd.getValueAs( "-sizzzaaa", 0 ) );
         std::string idform = "$S$I$ZZZ$AAA";
         if( cmd.getValueAs( "-symbols", 0 ) == 1 ) idform = "$S:$ee$AAA$m";
         base.set( "units", cmd.getValue( "-units", "" ) );
         base.set( "idform", cmd.getValueAs( "-idform", idform ) );
         base.set( "tid", cmd.getValueAs( "-tid", 0 ) );
         base.set( "transpose", cmd.getValueAs( "-transpose", 0 ) == 1 );
         base.set( "flux", cmd.getValueAs( "-flux", -1.0 ) );
         // options for graphviz
         base.setFromJson<IntegerList*>( "allow_s",
                                         cmd.getValue( "-allow_s", "[2]" ) );
         base.setFromJson<IntegerList*>( "allow_i",
                                         cmd.getValue( "-allow_i", "[]" ) );
         base.setFromJson<IntegerList*>( "allow_z",
                                         cmd.getValue( "-allow_z", "[]" ) );
         base.setFromJson<IntegerList*>( "allow_a",
                                         cmd.getValue( "-allow_a", "[]" ) );
         base.set( "allow_decay", cmd.getValueAs( "-allow_decay", 1 ) == 1 );
         base.set( "allow_fission", cmd.getValueAs( "-allow_fission", 0 ) == 1 );
         base.set( "allow_reaction",
                   cmd.getValueAs( "-allow_reaction", 1 ) == 1 );
         base.setFromJson<IntegerList*>(
             "allow_transition_id",
             cmd.getValue( "-allow_transition_id", "[]" ) );
         base.set( "include_byproducts",
                   cmd.getValueAs( "-include_byproducts", 0 ) == 1 );
     }
     return base;
 }
int execute (std::ostream & out, std::ostream & err)
References Obiwan_view::b_opts, Obiwan_view::help(), ORIGEN_MACRO_loadMulti, and Origen::view().
Referenced by Origen::obiwan_main().
 {
     // quick returns
     if( b_opts.get( "help", false ) )
     {
         out << help() << std::endl;
         return 1;
     }
     else if( b_opts.numError() > 0 )
     {
         return -1;
     }
     // ORIGEN_MACRO_loadMulti requires:
     // - string path
     // - DB opts
     // - int status
     auto path = b_opts.get( "path", "" );
     ScaleUtils::IO::DB opts = b_opts.clone();
     int status = 0;
     ORIGEN_MACRO_loadMulti( view );
     // opts dump after everything
     err << opts.toString();
     // error out
     if( opts.numError() > 0 )
     {
         out << opts.dumpErrorStack();
         status = -3;
     }
     return status;
 }
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_view::execute(), and Obiwan_view::Obiwan_view().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_view.h
Core/ut/Obiwan_view.cpp