ORIGEN API: Core/dc/tests/tstDecayData.cpp File Reference
tstDecayData.cpp File Reference
#include <cstdlib>
#include <iostream>
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Nemesis/harness/DBC.hh"
#include "Origen/Core/dc/DecayData.h"
#include "Origen/Core/dc/FakeFactory.h"
#include "Standard/Interface/SerialStream.h"
Functions
bool does_serialization_roundtrip (DecayData &d1)
TEST (DecayData, Serialization)
Function Documentation
bool does_serialization_roundtrip (DecayData & d1)
Examples:
tstDecayData.cpp.
References DecayData::deserialize(), DecayData::serialize(), and DecayData::toString().
Referenced by TEST().
 {
     //
     // Serialize
     //
     SerialStream ss;
     int return_code = d1.serialize( &ss );
     if( return_code != 0 )
     {
         std::cout << "Failed to serialize DecayData." << std::endl;
         return return_code;
     }
     //
     // Deserialize
     //
     DecayData d2;
     return_code = d2.deserialize( &ss );
     if( return_code != 0 )
     {
         std::cout << "Failed to deserialize DecayData." << std::endl;
         return return_code;
     }
     jDebugLine( d1.toString() );
     if( d1 == d2 )
     {
         std::cout << " PASSED" << std::endl;
         return true;
     }
     else
     {
         std::cout << " FAILED" << std::endl;
         return false;
     }
 }
TEST (DecayData , Serialization)
Examples:
tstDecayData.cpp.
References FakeFactory::createLibraryHeader_random1(), FakeFactory::DecayData_random1(), FakeFactory::DecayData_random2(), and does_serialization_roundtrip().
 {
     LibraryHeader lh = FakeFactory::createLibraryHeader_random1();
     bool all_pass = true;
     std::cout << "1. set without masses: ";
     {
         DecayData d1;
         FakeFactory::DecayData_random1( d1, lh );
         bool pass = does_serialization_roundtrip( d1 );
         all_pass = pass && all_pass;
     }
     std::cout << "2. set with masses: ";
     {
         DecayData d1;
         FakeFactory::DecayData_random2( d1 );
         bool pass = does_serialization_roundtrip( d1 );
         all_pass = pass && all_pass;
     }
     EXPECT_TRUE( all_pass );
 }