ORIGEN API: origen_output Module Reference
origen_output Module Reference
origen output class Contains auxiliary routines for the concentrations output.
Data Types
type origen_output_class
Exposure table printing functions; needed for Origami.
Functions/Subroutines
subroutine, public convert_concentrations (nsteps, lib, itot, units, x, volume)
convert concentrations from gram-atoms to something else
subroutine removal_rates_sort (this)
subroutine, public print_element_table (lib, nsteps, nnucs, anucs, bnucs, cutoff_relative, cutoff_step, cutoff_value, times, time_unit, high_precision, x)
Wrapper over print_table, sums data (x array) over isotopes to get element-based data.
subroutine, public print_nuclide_table (lib, nsteps, nnucs, anucs, bnucs, cutoff_relative, cutoff_step, cutoff_value, times, time_unit, high_precision, x)
Wrapper over print_table, sums data (x array) over isotopes to get element-based data.
subroutine print_table (lib, nsteps, nnucs, noffset, cutoff_relative, cutoff_step, cutoff_value, times, time_unit, high_precision, is_element, x)
subroutine sortpn (xe, l, n)
Sort two parallel arrays by the elements of one of thems.
Variables
character(2048), dimension(2048), private rbuffer
character buffer
integer, private rstatus
status flag
integer, parameter ot_nuclide = 1
Concentration table type: nuclides.
integer, parameter ot_element = 2
Concentration table type: elements.
integer, parameter ou_gramatoms = 1
Concentration table units: gram-atoms.
integer, parameter ou_grams = 2
Concentration table units: grams.
integer, parameter ou_curies = 3
Concentration table units: curies.
integer, parameter ou_watts = 4
Concentration table units: a+b+g watts.
integer, parameter ou_gwatts = 5
Concentration table units: gamma watts.
integer, parameter ou_ampc = 6
Concentration table units: m3 air.
integer, parameter ou_wmpc = 7
Concentration table units: m3 water.
integer, parameter ou_wppm = 8
Concentration table units: weight ppm.
integer, parameter ou_appm = 9
Concentration table units: atoms ppm.
integer, parameter ou_abcm = 10
Concentration table units: atoms/barn.cm.
integer, parameter ou_bq = 11
Concentration table units: becquerels.
Detailed Description
origen output class Contains auxiliary routines for the concentrations output.
Function/Subroutine Documentation
subroutine, public origen_output::convert_concentrations (integer, intent(in) nsteps, type(origen_librarywrapper), intent(in) lib, integer, intent(in) itot, integer, intent(in) units, real(c_double), dimension(0:nsteps, 1:itot), intent(inout) x, real(c_double), intent(in) volume)
convert concentrations from gram-atoms to something else
Parameters
[in] nsteps number of steps
[in] lib library data
[in] itot Total number of nuclides on the libary
[in] units units to which the conversion should be made
[in,out] x concentration buffer
[in] volume volume (only used for number density)
cycle variable
summary counter
Containers for library arrays from C++
References origen_definitions_m::avogadro, origen_definitions_m::curie_to_becquerel, origen_definitions_m::joule_to_mev, ou_abcm, ou_ampc, ou_appm, ou_bq, ou_curies, ou_gramatoms, ou_grams, ou_gwatts, ou_watts, ou_wmpc, and ou_wppm.
Referenced by origen_output_class::evaluate_rates_and_balances().
     use const
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> number of steps
     integer, intent(in) :: nsteps
     !> library data
     type(origen_librarywrapper), intent(in) :: lib
     !> Total number of nuclides on the libary
     integer, intent(in) :: itot
     !> units to which the conversion should be made
     integer, intent(in) :: units
     !> concentration buffer
     real(C_DOUBLE), intent(inout) :: x(0:nsteps, 1:itot)
     !> volume (only used for number density)
     real(C_DOUBLE), intent(in) :: volume
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> cycle variable
     integer :: i
     !> summary counter
     real (C_DOUBLE) :: s
     !> Containers for library arrays from C++
     real, allocatable :: m(:)
     real, allocatable :: dis(:)
     real, allocatable :: q(:)
     real, allocatable :: fg(:)
     real, allocatable :: ampc(:)
     real, allocatable :: wmpc(:)
     call lib%get_m(m)
     call lib%get_dis(dis)
     call lib%get_q(q)
     call lib%get_fg(fg)
     call lib%get_ampc(ampc)
     call lib%get_wmpc(wmpc)
     if (units == ou_gramatoms) then
       ! do nothing
     else if (units == ou_grams) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * m(:)
       end do
     else if (units == ou_curies) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * dis(:) * avogadro / curie_to_becquerel
       end do
     else if (units == ou_watts) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * dis(:) * q(:) * avogadro / joule_to_mev
       end do
     else if (units == ou_gwatts) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * dis(:) * q(:) * fg(:) * avogadro / joule_to_mev
       end do
     else if (units == ou_ampc) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * dis(:) / ampc(:) * avogadro / curie_to_becquerel
       end do
     else if (units == ou_wmpc) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * dis(:) / wmpc(:) * avogadro / curie_to_becquerel
       end do
     else if (units == ou_appm) then
       do i = 0, nsteps
         s = sum(x(i,:))
         x(i,:) = x(i,:) / s * 1d6
       end do
     else if (units == ou_wppm) then
       do i = 0, nsteps
         s = sum(x(i,:) * m(:))
         x(i,:) = x(i,:) * m(:) / s * 1d6
       end do
     else if (units == ou_abcm) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * avogadro * 1d-24 / volume
       end do
     else if (units == ou_bq) then
       do i = 0, nsteps
         x(i,:) = x(i,:) * dis(:) * avogadro
       end do
     end if
     deallocate(m)
     deallocate(dis)
     deallocate(q)
     deallocate(fg)
     deallocate(ampc)
     deallocate(wmpc)
subroutine origen_output::removal_rates_sort (class(origen_output_class), intent(inout) this) private
   class(origen_output_class), intent(inout) :: this
   integer :: i
   integer :: j
   integer :: n_rates
   integer :: n_max_ele
   n_rates = size(this%removal_elements,1)
   n_max_ele = size(this%removal_elements,2)
   this%removal_sorted = 0.0
   do i = 1,n_rates
     do j = 1,n_max_ele
     if (this%removal_elements(i,j) == 0) exit
         this%removal_sorted(this%removal_elements(i,j)) = this%removal_rates(i)
     end do
   end do
subroutine, public origen_output::print_element_table (type(origen_librarywrapper), intent(in) lib, integer, intent(in) nsteps, integer, intent(in) nnucs, integer, intent(in) anucs, integer, intent(in) bnucs, logical, intent(in) cutoff_relative, integer, intent(in) cutoff_step, real(c_double), intent(in) cutoff_value, real(c_double), dimension(0:nsteps), intent(in) times, character(4), intent(in) time_unit, logical, intent(in) high_precision, real(c_double), dimension(0:nsteps, 1:nnucs), intent(in) x)
Wrapper over print_table, sums data (x array) over isotopes to get element-based data.
Parameters
[in] lib Library data
[in] nsteps number of time steps
[in] nnucs number of nuclides/elements/...
[in] anucs first index of the nuclide/element
[in] bnucs last index of the nuclide/element
[in] x data
[in] cutoff_relative true -> cutoff is relative to total, false -> cutoff is absolute
[in] cutoff_step -1 => cutoff by sum, otherwise cutoff by one step
[in] cutoff_value cutoff treshold
[in] times time values
[in] time_unit time units
[in] high_precision 4 / 6 digits
buffer for element data
nuclide index
References const::n_elements, and print_table().
Referenced by origen_output_class::evaluate_rates_and_balances().
     use const
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Library data
     type(origen_librarywrapper), intent(in) :: lib
     !>
     !> number of time steps
     integer, intent(in) :: nsteps
     !> number of nuclides/elements/...
     integer, intent(in) :: nnucs
     !> first index of the nuclide/element
     integer, intent(in) :: anucs
     !> last index of the nuclide/element
     integer, intent(in) :: bnucs
     !> data
     real(C_DOUBLE), intent(in) :: x(0:nsteps, 1:nnucs)
     !> true -> cutoff is relative to total, false -> cutoff is absolute
     logical, intent(in) :: cutoff_relative
     !> -1 => cutoff by sum, otherwise cutoff by one step
     integer, intent(in) :: cutoff_step
     !> cutoff treshold
     real(C_DOUBLE), intent(in) :: cutoff_value
     !> time values
     real(C_DOUBLE), intent(in) :: times(0:nsteps)
     !> time units
     character(4), intent(in) :: time_unit
     !> 4 / 6 digits
     logical, intent(in) :: high_precision
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> buffer for element data
     real(C_DOUBLE) :: xx(0:nsteps, 1:n_elements)
     !> nuclide index
     integer :: n
     ! sum over elements
     xx = 0.0d0
     do n = anucs, bnucs
       xx(:,(lib%nucl(n)/10000)) = xx(:,(lib%nucl(n)/10000)) + x(:,n)
     end do
     ! print the table now
     call print_table(lib, nsteps, n_elements, 0, cutoff_relative, cutoff_step, cutoff_value, times, time_unit, high_precision, .true., xx)
subroutine, public origen_output::print_nuclide_table (type(origen_librarywrapper), intent(in) lib, integer, intent(in) nsteps, integer, intent(in) nnucs, integer, intent(in) anucs, integer, intent(in) bnucs, logical, intent(in) cutoff_relative, integer, intent(in) cutoff_step, real(c_double), intent(in) cutoff_value, real(c_double), dimension(0:nsteps), intent(in) times, character(4), intent(in) time_unit, logical, intent(in) high_precision, real(c_double), dimension(0:nsteps, 1:nnucs), intent(in) x)
Wrapper over print_table, sums data (x array) over isotopes to get element-based data.
Parameters
[in] lib Library data
[in] nsteps number of time steps
[in] nnucs number of nuclides/elements/...
[in] anucs first index of the nuclide/element
[in] bnucs last index of the nuclide/element
[in] x data
[in] cutoff_relative true -> cutoff is relative to total, false -> cutoff is absolute
[in] cutoff_step -1 => cutoff by sum, otherwise cutoff by one step
[in] cutoff_value cutoff treshold
[in] times time values
[in] time_unit time units
[in] high_precision 4 / 6 digits
References print_table().
Referenced by origen_output_class::evaluate_rates_and_balances().
    !-----------------------------------------------
    !   D u m m y   A r g u m e n t s
    !-----------------------------------------------
    !> Library data
    type(origen_librarywrapper), intent(in) :: lib
    !>
    !> number of time steps
    integer, intent(in) :: nsteps
    !> number of nuclides/elements/...
    integer, intent(in) :: nnucs
    !> first index of the nuclide/element
    integer, intent(in) :: anucs
    !> last index of the nuclide/element
    integer, intent(in) :: bnucs
    !> data
    real(C_DOUBLE), intent(in) :: x(0:nsteps, 1:nnucs)
    !> true -> cutoff is relative to total, false -> cutoff is absolute
    logical, intent(in) :: cutoff_relative
    !> -1 => cutoff by sum, otherwise cutoff by one step
    integer, intent(in) :: cutoff_step
    !> cutoff treshold
    real(C_DOUBLE), intent(in) :: cutoff_value
    !> time values
    real(C_DOUBLE), intent(in) :: times(0:nsteps)
    !> time units
    character(4), intent(in) :: time_unit
    !> 4 / 6 digits
    logical, intent(in) :: high_precision
    ! print the table now
    if (anucs <= bnucs) call print_table(lib, nsteps, bnucs-anucs+1, anucs-1, cutoff_relative, cutoff_step, cutoff_value, times, time_unit, high_precision, .false., x(:,anucs:bnucs))
subroutine origen_output::print_table (type(origen_librarywrapper), intent(in) lib, integer, intent(in) nsteps, integer, intent(in) nnucs, integer, intent(in) noffset, logical, intent(in) cutoff_relative, integer, intent(in) cutoff_step, real(c_double), intent(in) cutoff_value, real(c_double), dimension(0:nsteps), intent(in) times, character(4), intent(in) time_unit, logical, intent(in) high_precision, logical, intent(in) is_element, real(c_double), dimension(0:nsteps, 1:nnucs), intent(in) x) private
Parameters
[in] lib Library data
[in] nsteps number of time steps
[in] nnucs number of nuclides/elements/...
[in] noffset index of the first nuclide in the x array
[in] x data
[in] cutoff_relative true -> cutoff is relative to total, false -> cutoff is absolute
[in] cutoff_step -1 => cutoff by sum, otherwise cutoff by one step
[in] cutoff_value cutoff treshold
[in] times time values
[in] time_unit time units
[in] high_precision 4 / 6 digits
[in] is_element print the row header as an element or as a nuclide?
References const::elements, origen_definitions_m::err, and auxiliary::nuclide_compact().
Referenced by print_element_table(), and print_nuclide_table().
     use const
     use auxiliary
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Library data
     type(origen_librarywrapper), intent(in) :: lib
     !> number of time steps
     integer, intent(in) :: nsteps
     !> number of nuclides/elements/...
     integer, intent(in) :: nnucs
     !> index of the first nuclide in the \p x array
     integer, intent(in) :: noffset
     !> data
     real(C_DOUBLE), intent(in) :: x(0:nsteps, 1:nnucs)
     !> true -> cutoff is relative to total, false -> cutoff is absolute
     logical, intent(in) :: cutoff_relative
     !> -1 => cutoff by sum, otherwise cutoff by one step
     integer, intent(in) :: cutoff_step
     !> cutoff treshold
     real(C_DOUBLE), intent(in) :: cutoff_value
     !> time values
     real(C_DOUBLE), intent(in) :: times(0:nsteps)
     !> time units
     character(4), intent(in) :: time_unit
     !> 4 / 6 digits
     logical, intent(in) :: high_precision
     !> print the row header as an element or as a nuclide?
     logical, intent(in) :: is_element
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     ! cycle over nuclides
     integer :: n
     ! displayed nuclides
     integer :: m
     ! cycle over steps
     integer :: s
     ! will this nuclide be displayed?
     logical :: display(nnucs)
     ! total for each step
     real(C_DOUBLE) :: total_s(0:nsteps)
     ! total for each nuclide
     real(C_DOUBLE) :: total_n(1:nnucs)
     ! minimum limit to display nuclide
     real(C_DOUBLE) :: co_limit
     ! achieved value to display nuclide
     real(C_DOUBLE) :: co_x
     ! buffer for nuclide name string
     character(7) :: nuclide_name
     ! calculate the totals
     do s = 0, nsteps
       total_s(s) = sum(x(s,:))
     end do
     if( nsteps>0 )then
         do n = 1, nnucs
           total_n(n) = 0
           do s = 1, nsteps
             total_n(n) = total_n(n) + (x(s-1,n) + x(s,n)) / 2.0 * (times(s) - times(s-1))
           end do
         end do
     else
         total_n = x(0,:)
     end if
     ! assume that no line will get displayed
     display(:) = .false.
     if (cutoff_relative) then
       if (cutoff_step >= 0) then
         soutline(1,'(a,i6,a,es10.2,a)') '  (relative cutoff; concentration at step ', cutoff_step, " > ", cutoff_value, " % of sum of all concentrations at that step)"
       else
         soutline(1,'(a,es10.2,a)') '  (relative cutoff; integral of concentrations over time > ', cutoff_value, " % of integral of all concentrations over time)"
       end if
     else
       if (cutoff_step >= 0) then
         soutline(1,'(a,i6,a,es10.2,a)') '  (absolute cutoff; concentration at step ', cutoff_step, " > ", cutoff_value, ')'
       else
         soutline(1,'(a,es10.2,a)') '  (absolute cutoff; integral of concentrations over time > ', cutoff_value, ')'
       end if
     end if
     soutline(1, '(a)') '.'
     ! find what lines do get displayed
     do n = 1, nnucs
       if (cutoff_relative) then
         if (cutoff_step >= 0) then
           co_x = x(cutoff_step, n)
           co_limit = cutoff_value * 0.01 * total_s(cutoff_step)
         else
           co_x = total_n(n)
           co_limit = cutoff_value * 0.01 * sum(total_n(:))
         end if
       else
         if (cutoff_step >= 0) then
           co_x = x(cutoff_step, n)
           co_limit = cutoff_value
         else
           co_x = total_n(n)
           co_limit = cutoff_value
         end if
       end if
       display(n) = (co_x >= co_limit)
     end do
     if (sum(total_s(0:nsteps)) > err) then
       !--- print step header
       if (high_precision) then
         if ((times(0) > err .and. times(0) < 0.002) .or. (nsteps > 1 .and. times(1) < 0.002) .or. times(nsteps) > 99999) then
           soutline(1, '(14x,999(es10.3,a4))') (times(s), time_unit, s=0,nsteps)
         else
           soutline(1, '(14x,999(f10.3,a4))') (times(s), time_unit, s=0,nsteps)
         end if
       else
         if ((times(0) > err .and. times(0) < 0.2) .or. (nsteps > 1 .and. times(1) < 0.2) .or. times(nsteps) > 99999) then
           soutline(1, '(15x,999(es8.1,a4))') (times(s), time_unit, s=0,nsteps)
         else
           soutline(1, '(16x,999(f8.3,a4))') (times(s), time_unit, s=0,nsteps)
         end if
       end if
       m = 0
       do n = 1, nnucs
         if (display(n)) then
           m = m + 1
           if (is_element) then
             sout(1, '(4x,a2,6x)') elements(n)
           else
             call nuclide_compact(lib%nucl(n+noffset), nuclide_name)
             sout(1, '(2x,a7,4x)') nuclide_name
           end if
           if (high_precision) then
             soutline(1, '(999(es14.6))') (x(s,n),s=0,nsteps)
           else
             soutline(1, '(999(es12.4))') (x(s,n),s=0,nsteps)
           end if
         end if
       end do
       ! print totals
       soutline(1,'(a12)') '------------'
       if (high_precision) then
         soutline(1, '(2x,a6,5x,999(es14.6))') 'totals', total_s(0:nsteps)
       else
         soutline(1, '(2x,a6,5x,999(es12.4))') 'totals', total_s(0:nsteps)
       end if
     else
       soutline(1, '(a)') '.'
       soutline(1, '(a)') 'All concentrations are zero in this table'
     end if
subroutine origen_output::sortpn (real(c_double), dimension(n), intent(inout) xe, integer, dimension(n), intent(inout) l, integer, intent(in) n)
Sort two parallel arrays by the elements of one of thems.
Parameters
[in] n number of elements
[in,out] xe data (key) array
[in,out] l pointer (value) array
Referenced by origen_output_class::evaluate_rates_and_balances().
    !-----------------------------------------------
    !   D u m m y   A r g u m e n t s
    !-----------------------------------------------
    !> number of elements
    integer, intent(in) :: n
    !> data (key) array
    real(C_DOUBLE), intent(inout) :: xe(n)
    !> pointer (value) array
    integer, intent(inout) :: l(n)
    !-----------------------------------------------
    !   L o c a l   V a r i a b l e s
    !-----------------------------------------------
    integer :: m, k, j, i, im, lp
    real(C_DOUBLE) :: xt
    !-----------------------------------------------
    m = n
    100 continue
    m = m/2
    if (m <= 0) return
    k = n - m
    l120: do j = 1, k
       i = j
       im = i + m
       if (xe(i) <= xe(im)) cycle  l120
       xt     = xe(i)
       xe(i)  = xe(im)
       xe(im) = xt
       lp     = l(i)
       l(i)   = l(im)
       l(im)  = lp
       i      = i - m
       do while(i > 0)
          im = i + m
          if (xe(i) <= xe(im)) cycle  l120
          xt     = xe(i)
          xe(i)  = xe(im)
          xe(im) = xt
          lp     = l(i)
          l(i)   = l(im)
          l(im)  = lp
          i      = i - m
       end do
    end do l120
    go to 100
Variable Documentation
character(2048), dimension(2048), private rbuffer
character buffer
Referenced by origen_output_class::evaluate_rates_and_balances().
   character(2048), private :: rbuffer(2048)
integer, private rstatus
status flag
   integer, private :: rstatus
integer, parameter ot_nuclide = 1
Concentration table type: nuclides.
Referenced by origen_output_class::evaluate_rates_and_balances().
   integer, parameter :: ot_nuclide = 1
integer, parameter ot_element = 2
Concentration table type: elements.
   integer, parameter :: ot_element = 2
integer, parameter ou_gramatoms = 1
Concentration table units: gram-atoms.
Referenced by convert_concentrations().
   integer, parameter :: ou_gramatoms = 1
integer, parameter ou_grams = 2
Concentration table units: grams.
Referenced by convert_concentrations().
   integer, parameter :: ou_grams = 2
integer, parameter ou_curies = 3
Concentration table units: curies.
Referenced by convert_concentrations().
   integer, parameter :: ou_curies = 3
integer, parameter ou_watts = 4
Concentration table units: a+b+g watts.
Referenced by convert_concentrations().
   integer, parameter :: ou_watts = 4
integer, parameter ou_gwatts = 5
Concentration table units: gamma watts.
Referenced by convert_concentrations().
   integer, parameter :: ou_gwatts = 5
integer, parameter ou_ampc = 6
Concentration table units: m3 air.
Referenced by convert_concentrations().
   integer, parameter :: ou_ampc = 6
integer, parameter ou_wmpc = 7
Concentration table units: m3 water.
Referenced by convert_concentrations().
   integer, parameter :: ou_wmpc = 7
integer, parameter ou_wppm = 8
Concentration table units: weight ppm.
Referenced by convert_concentrations().
   integer, parameter :: ou_wppm = 8
integer, parameter ou_appm = 9
Concentration table units: atoms ppm.
Referenced by convert_concentrations().
   integer, parameter :: ou_appm = 9
integer, parameter ou_abcm = 10
Concentration table units: atoms/barn.cm.
Referenced by convert_concentrations().
   integer, parameter :: ou_abcm = 10
integer, parameter ou_bq = 11
Concentration table units: becquerels.
Referenced by convert_concentrations().
   integer, parameter :: ou_bq = 11