ORIGEN API: origen_beta Module Reference
origen_beta Module Reference
beta emission calculations
Data Types
type origen_beta_class
Beta source calculation and printout class. Use this class to evaluate beta source and beta spectra based on the nuclide concentrations.
type origen_beta_options
options for beta printout
Functions/Subroutines
real(c_double) function cosimp (a, b, aux, eps, isub, emax, z)
cosimp is a routine for evaluating definite integrals using an adaptive simpsons algorithm. integral estimated over interval (a,b) of function aux, where eps is the error tolerance and isub is the number of subdivisions within (a,b) used in evaluation. cosimp makes two evaluations using isub and isub+1 and and compares values for agreement within eps. estimates made using est1 = f(a)+4*f(a+b/2)+f(b) and est2 = f(a)+4*f(3a+b/4)+ 2*f(a+b/2)+4*f(a+3b/4)+f(b)
subroutine normalize (v1, v2, a, b, dist2, dist1, eps, isub, emax, z)
return normalizing factors v1 and v2
real(c_double) function dist1f (e, emax, z)
beta energy distribution for first forbidden transitions
real(c_double) function dist2f (e, emax, z)
beta energy distribution of second forbidden transitions
real(c_double) function dist3f (e, emax, z)
beta energy distribution of third forbidden transitions
real(c_double) function dista (e, emax, z)
beta energy distribution for allowed transitions
real(c_double) function diste1f (e, emax, z)
energy-weighted distribution first forbidden unique transition
real(c_double) function diste2f (e, emax, z)
energy-weighted distribution second forbidden unique transition
real(c_double) function diste3f (e, emax, z)
energy-weighted dist for third forbidden unique transitions
real(c_double) function distea (e, emax, z)
energy-weighted distribution for allowed transitions
Variables
real(c_double), dimension(100, 3) aaa
integer iii
integer jjj
character(1024), dimension(256), private rbuffer
buffer for Reporter
Detailed Description
beta emission calculations
Function/Subroutine Documentation
real(c_double) function origen_beta::cosimp (real(c_double), intent(in) a, real(c_double), intent(in) b, real(c_double), external aux, real(c_double), intent(in) eps, integer, intent(inout) isub, real(c_double), intent(in) emax, integer, intent(in) z)
cosimp is a routine for evaluating definite integrals using an adaptive simpsons algorithm. integral estimated over interval (a,b) of function aux, where eps is the error tolerance and isub is the number of subdivisions within (a,b) used in evaluation. cosimp makes two evaluations using isub and isub+1 and and compares values for agreement within eps. estimates made using est1 = f(a)+4*f(a+b/2)+f(b) and est2 = f(a)+4*f(3a+b/4)+ 2*f(a+b/2)+4*f(a+3b/4)+f(b)
Parameters
[in] a lower integration limit
[in] b upper integration limit
aux the integrand f(x, emax, z)
[in] eps required relative error tolerance
[in] emax integrand parameter
[in] z integrand parameter
Referenced by distea(), and normalize().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !>
     integer, intent(inout) :: isub
     !> lower integration limit
     real(C_DOUBLE), intent(in)  :: a
     !> upper integration limit
     real(C_DOUBLE), intent(in)  :: b
     !> the integrand f(x, emax, z)
     real(C_DOUBLE), external :: aux
     !> required relative error tolerance
     real(C_DOUBLE), intent(in) :: eps
     !> integrand parameter
     real(C_DOUBLE), intent(in) :: emax
     !> integrand parameter
     integer, intent(in) :: z
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     integer , dimension(20) :: nr
     integer :: iflag, iflog, iprint, nsub, ll, nd, n, l, m, ne
     real(C_DOUBLE) , dimension(20) :: p
     real(C_DOUBLE) , dimension(41) :: y
     real(C_DOUBLE) :: c, x, summ, ak, aj, ajj, s, ss, er, pb, pa1, pb1, subsum, suber
     integer :: kount, ints
     real(C_DOUBLE) :: err
     !-----------------------------------------------
     !
     !   isub - specification of the minimum number of divisions
     !   required returns the number of divisions used ( negative if
     !   not converged) in each case the number of divisions is 2**isub.
     !   isub may be entered negative to activate error messages
     !
     !   err - estimate of the maximum error in the integral
     !   kount - number of function evaluations
     !   ints - number of intervals used
     !
     !   y - real(C_DOUBLE) array stores values of f(x) to avoid recalculation
     !   s, ss - two estimates for a given subinterval
     !   summ - cumulative estimate of the integral over the accepted
     !   subintervals (unscaled)
     !   pa1, pb1 - limits of interval not satisfying error requirement
     !   subsum - estimate of integral over the above interval
     !
     !   if isub is outside the acceptable range, this message is printed
     !   error in isub, 0 < isub < 18. isub set to 0
     !   cosimp is evaluated with isub = 0.
     !   the function cosimp returns the best estimate of the integral.
     !   the finest subdivision allowed is (b-a)/2**20.  if the error
     !   requirement is still not satisfied, an error message is printed
     !   giving the bounds of the unacceptable region, the estimated
     !   integral over this interval, and an estimate of the error there.
     !   the value of cosimp returned is still the best estimate over the
     !   entire range.
     !   isub is returned negative when convergence is not complete.
     !   from atomic energy of canada mathematics and computation fortran
     !   library
     !
     !      programmed by    d howden  in apex language        jul 1965
     !      translated by    c j johnson                       nov 1969
     !      revised    by    valerie jones                     aug 1976
     !
     !
       cosimp = 0.0
       err    = 0.0
       kount  = 0
       ints   = 0
       iflag  = 0
       iflog  = 0
       if (a == b) return
       if (isub < 0) iprint = 1
       isub = min0(18,max0(0,isub))
       nsub = isub
 !
       ll   = isub + 2
       ints = 0
       err  = 0.
       nd   = 20
       p(1) = 1.
       do n = 2, nd
          p(n) = p(n-1)*2.0
       end do
       c     = b - a
       x     = .5
       l     = 1
       n     = 2
 !
       y(1)  = aux(a, emax, z)
       y(2)  = aux(b, emax, z)
       y(3)  = aux(c*x + a, emax, z)
       kount = 3
       summ  = 0
       m     = 3
       nr(n) = 2
       ak    = .5
 !
 !  ***next subdivision
 !
    50 continue
       aj       = c*ak/2.
       nsub     = max0(nsub,n)
       ajj      = c*x + a
       y(n+n)   = aux(ajj - aj, emax, z)
       y(n+n+1) = aux(ajj + aj, emax, z)
       kount    = kount + 2
 !
 !  *** if minimum number of subdivisions (isub) has not been met,
 !      the interval is divided in half
 !
       if (n < ll) go to 125
 !
 !  *** two estimates of the interval are made and the error estimate is
 !      compared to the required error tolerance
 !
       s  = y(l) + 4.0*y(m) + y(nr(n))
       ss = s + 2.*(2.*(y(n+n)+y(n+n+1))-y(m))
       er = (aj*(ss - 2.*s))/45.
       if (abs(er) > aj*eps*(abs(ss) + abs(s))/4.5) go to 100
       if (iflag == 1) go to 200
 !
 !      if the error requirement is met the interval is accepted.  the
 !      estimates are added on to their respective sums, the count of
 !      the number of intervals used (ints) is increased by one, and
 !      the next interval on the right is considered
 !
    75 continue
       summ = summ + ss*ak
       err  = err + er
       ints = ints + 1
       if (nr(n) <= 2) go to 225
       l     = nr(n)
       ne    = l/2
       ak    = 1./p(ne+2)
       x     = x + ak + 1./p(n)
       n     = ne + 2
       nr(n) = nr(n-1)
       m     = 2*ne + 3
       go to 50
 !
 !  ***error recognition criterion
 !
   100 continue
       if (n >= nd) go to 150
 !
 !      if the error requirement is not satisfied and the maximum
 !      number of subdivisions has not been reached, the interval is
 !      divided in half.
 !
   125 continue
       nr(n+1) = m
       m       = 2*n
       ak      = 1./p(n+1)
       x       = x - ak
       n       = n + 1
       go to 50
 !
 !      if the maximum number of subdivisions has been reached without
 !      the error requirement being met, the bounds of the offending
 !      interval are stored with the estimate of the integral and the
 !      error flag is set.
 !
   150 continue
       pb = ajj + 2.*aj
       if (iflag == 1) go to 175
       pa1    = ajj - 2.0*aj
       pb1    = pb
       subsum = ss*ak
       suber  = er
       iflag  = 1
       iflog  = 1
       go to 75
 !
 !      consecutive intervals where the error requirement is not met are
 !      combined for readability.
 !
   175 continue
       pb1    = pb
       subsum = subsum + ss*ak
       suber  = suber + er
       go to 75
 !
 !      when the non-convergent interval has been completely determined
 !      a message is printed giving the bounds, integral, and error.
 !
   200 continue
       iflog = 1
       iflag = 0
       if (iprint == 0) go to 75
       soutline(1,fmt=2000) pa1, pb1, subsum*(c/6.0), abs(suber)
       go to 75
 !
 !      when the entire interval has been considered the answer is
 !      returned along with an estimate of the error.
 !
   225 continue
       cosimp = summ*(c/6.)
       err    = abs(err)
       isub   = nsub
       if (iflog == 1) isub = -nsub
       return
       2000 format(/' *** cosimp - trouble integrating over (',e13.5,',',e13.5,')',/,&
          ' estimated integral and error are ',e23.14,' and ',e13.5,' ***'/)
subroutine origen_beta::normalize (real(c_double), intent(out) v1, real(c_double), intent(out) v2, real(c_double), intent(in) a, real(c_double), intent(in) b, real(c_double), external dist2, real(c_double), external dist1, real(c_double), intent(in) eps, integer, intent(inout) isub, real(c_double), intent(in) emax, integer, intent(in) z)
return normalizing factors v1 and v2
References cosimp().
Referenced by distea(), and CompManager::finalizeComp().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     integer, intent(inout)  :: isub
     real(C_DOUBLE), intent(out) :: v1
     real(C_DOUBLE), intent(out) :: v2
     real(C_DOUBLE), intent(in)  :: a
     real(C_DOUBLE), intent(in)  :: b
     real(C_DOUBLE), intent(in)  :: eps
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     !-----------------------------------------------
     !   E x t e r n a l   F u n c t i o n s
     !-----------------------------------------------
     real(C_DOUBLE), external :: dist2
     real(C_DOUBLE), external :: dist1
     v1 = cosimp(a,b,dist1,eps,isub,emax,z)
     v2 = cosimp(a,b,dist2,eps,isub,emax,z)
real(c_double) function origen_beta::dist1f (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
beta energy distribution for first forbidden transitions
References aaa.
Referenced by diste1f(), and distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in) :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     real(C_DOUBLE) :: emc, a0, a1, a2, w, wmax
     emc = 0.511
     a0  = aaa(z+1,1)
     a1  = aaa(z+1,2)
     a2  = aaa(z+1,3)
     if (e <= emax) then
        w      = e/emc + 1.0
        wmax   = emax/emc + 1.0
        dist1f = ((w*w - 1) + (wmax - w)**2) * (a0 + a1*e + a2*e*e) * (emax - e)**2
     else
        dist1f = 0.0
     endif
real(c_double) function origen_beta::dist2f (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
beta energy distribution of second forbidden transitions
References aaa.
Referenced by diste2f(), and distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in) :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     real(C_DOUBLE) :: emc, a0, a1, a2, w, wmax
     emc = 0.511
     a0  = aaa(z+1,1)
     a1  = aaa(z+1,2)
     a2  = aaa(z+1,3)
     if (e <= emax) then
        w      = e/emc + 1.0
        wmax   = emax/emc + 1.0
        dist2f = ((w*w - 1)**2 + (wmax - w)**4 + 10./3.*(w*w - 1)*(wmax - w)**&
           2)*(a0 + a1*e + a2*e*e)*(emax - e)**2
     else
        dist2f = 0.0
     endif
real(c_double) function origen_beta::dist3f (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
beta energy distribution of third forbidden transitions
References aaa.
Referenced by diste3f(), and distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in) :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     real(C_DOUBLE) :: emc, a0, a1, a2, w, wmax
     emc = 0.511
     a0  = aaa(z+1,1)
     a1  = aaa(z+1,2)
     a2  = aaa(z+1,3)
     if (e <= emax) then
        w      = e/emc + 1.0
        wmax   = emax/emc + 1.0
        dist3f = ((w*w - 1)**3 + (wmax - w)**6 + 7.0*(w*w - 1)*(wmax - w)**2*(&
           (w*w - 1) + (wmax - w)**2))*(a0 + a1*e + a2*e*e)*(emax - e)**2
     else
        dist3f = 0.0
     endif
real(c_double) function origen_beta::dista (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
beta energy distribution for allowed transitions
References aaa.
Referenced by distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in) :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     real(C_DOUBLE) :: a0, a1, a2
     a0 = aaa(z+1,1)
     a1 = aaa(z+1,2)
     a2 = aaa(z+1,3)
     if (e <= emax) then
        dista = (a0 + a1*e + a2*e*e)*(emax - e)**2
     else
        dista = 0.0
     endif
real(c_double) function origen_beta::diste1f (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
energy-weighted distribution first forbidden unique transition
References dist1f().
Referenced by distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in)  :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     diste1f = e * dist1f(e, emax, z)
real(c_double) function origen_beta::diste2f (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
energy-weighted distribution second forbidden unique transition
References dist2f().
Referenced by distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in)  :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     diste2f = e * dist2f(e, emax, z)
real(c_double) function origen_beta::diste3f (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
energy-weighted dist for third forbidden unique transitions
References dist3f().
Referenced by distea().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in)  :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     diste3f = e * dist3f(e, emax, z)
real(c_double) function origen_beta::distea (real(c_double), intent(in) e, real(c_double), intent(in) emax, integer, intent(in) z)
energy-weighted distribution for allowed transitions
References origen_definitions_m::avogadro, cosimp(), dist1f(), dist2f(), dist3f(), dista(), diste1f(), diste2f(), diste3f(), origen_definitions_m::err, auxiliary::flip(), normalize(), auxiliary::nuclide_compact(), origen_definitions_m::origen_sublib_1lt, origen_definitions_m::origen_sublib_2ac, origen_definitions_m::origen_sublib_3fp, auxiliary::output(), auxiliary::print_break(), auxiliary::print_hrule(), auxiliary::print_multigroup_time_table(), auxiliary::print_time_table(), auxiliary::table_banner(), and auxiliary::table_tail().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     real(C_DOUBLE), intent(in)  :: e
     real(C_DOUBLE), intent(in) :: emax
     integer, intent(in) :: z
     distea = e * dista(e, emax, z)
Variable Documentation
real(c_double), dimension(100,3) aaa
Referenced by dist1f(), dist2f(), dist3f(), and dista().
   real(C_DOUBLE), dimension(100,3) :: aaa
integer iii
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
   integer :: iii, jjj
integer jjj
character(1024), dimension(256), private rbuffer
buffer for Reporter
   character(1024), private :: rbuffer(256)