ORIGEN API: const Module Reference
const Module Reference
Set of data, physics and string constants.
Variables
integer, parameter time_s = 1
Time units :: seconds.
integer, parameter time_m = 2
Time units :: minutes.
integer, parameter time_h = 3
Time units :: hours.
integer, parameter time_d = 4
Time units :: days.
integer, parameter time_y = 5
Time units :: years.
character(4), dimension(5) time_units = (/ 'sec ', 'min ', 'hr ', 'd ', 'y '/)
time unit name constants (short)
character(4), dimension(5) time_units_long = (/ 'sec ', 'min ', 'hrs ', 'days', 'yrs '/)
time unit name constants (long)
real(c_double), dimension(5) time_factors = (/1.0d0, 60.0d0, 3600.0d0, 86400.0d0, 3.156d7/)
number of seconds per time unit (NUNIT)
character(16), dimension(4), parameter library_titles = (/ ' light elements', ' actinides', 'fission products',' all nuclides'/)
Library titles.
integer, parameter n_elements = 112
Number of elements supported by ORIGEN.
character(2), dimension(n_elements) elements = (/ ' h', 'he', 'li', 'be', ' b', ' c', ' n', ' o', ' f', 'ne', 'na', 'mg', 'al', 'si', ' p', ' s', 'cl', 'ar', ' k', 'ca', 'sc', 'ti', ' v', 'cr', 'mn', 'fe', 'co', 'ni', 'cu', 'zn', 'ga', 'ge', 'as', 'se', 'br', 'kr', 'rb', 'sr', ' y', 'zr', 'nb', 'mo', 'tc', 'ru', 'rh', 'pd', 'ag', 'cd', 'in', 'sn', 'sb', 'te', ' i', 'xe', 'cs', 'ba', 'la', 'ce', 'pr', 'nd', 'pm', 'sm', 'eu', 'gd', 'tb', 'dy', 'ho', 'er', 'tm', 'yb', 'lu', 'hf', 'ta', ' w', 're', 'os', 'ir', 'pt', 'au', 'hg', 'tl', 'pb', 'bi', 'po', 'at', 'rn', 'fr', 'ra', 'ac', 'th', 'pa', ' u', 'np', 'pu', 'am', 'cm', 'bk', 'cf', 'es', 'fm', 'md', 'no', 'lr', 'rf', 'db', 'sg', 'bh', 'hs', 'mt', 'ds', 'rg', 'cn'/)
Element symbols (corresponding to Z numbers)
character(2), dimension(2) sta = (/ ' ', 'm '/)
metastable symbols (corresponding to I+1-number)
real(c_double), dimension(99) amass = (/ 1.0079d0,4.0026d0,6.941d0,9.012d0,10.81d0,12.011d0,14.007d0,16.d0,19.d0, 20.18d0,22.99d0,24.31d0,26.98d0,28.09d0,30.97d0,32.06d0,35.45d0,39.95d0,39.10d0,40.08d0, 44.96d0,47.9d0,50.94d0,52.d0,54.94d0,55.85d0,58.93d0,58.7d0,63.55d0,65.38d0,69.72d0, 72.59d0,74.92d0,78.96d0,79.9d0,83.8d0,85.47d0,87.62d0,88.91d0,91.22d0,92.91d0,95.94d0, 99.d0,101.07d0,102.91d0,106.4d0,107.87d0,112.41d0,114.82d0,118.69d0,121.75d0,127.6d0, 126.90d0,131.3d0,132.9d0,137.33d0,138.91d0,140.1d0,140.9d0,144.2d0, 147.d0,150.4d0,151.96d0,157.25d0,158.9d0,162.5d0,164.9d0,167.3d0,168.9d0,173.d0,175.d0, 178.d0,181.d0,184.d0,186.d0,190.d0,192.d0,195.d0,196.d0,201.d0,204.d0,207.d0,209.d0,209.d0, 217.d0,222.d0,223.d0,226.d0,227.d0,232.d0,231.d0,238.d0,238.d0,239.d0,241.d0,243.d0,249.d0, 249.d0,252.d0 /)
Atomic masses for all elements.
character(13), dimension(11), parameter unit_titles = (/'gram-atoms ', 'grams ', 'curies ', 'watts ', 'gamma watts ', 'm3 air ', 'm3 water ', 'grams ppm ', 'atoms ppm ', 'atoms/barn-cm', 'becquerels '/)
Concentration table units titles.
character(7), dimension(2), parameter table_titles = (/'Nuclide', 'Element'/)
Concentration table type titles.
real(c_double), parameter high = huge(1.0)*0.5
value close to highest, high 1.00d+38
real(c_double), parameter hi1 = high*0.1
value usually about 0.1d0 times high, hi1 1.00d+37
real(c_double), parameter hi2 = high*1.01
value slightly more, hi2 1.01d+38
real(c_double), parameter xlow = tiny(1.0)*2.0
value close to lowest, xlow 2.00d-38
real(c_double), parameter xlo1 = xlow*10.0
value usually about 10 times xlow, xlo1 1.00d-37
real(c_double), parameter xlo2 = xlow*1.01
value slightly more, xlo2 2.01d-38
real(c_double), parameter hineg = -high
value negative of high, hineg -1.00d+38
real(c_double), parameter xlneg = -xlow
value negative of xlow, xlneg -2.00d-38
real(c_double), parameter alow = 1.0d-31
value usually a good low, alow 1.00d-31
real(c_double), parameter alo2 = 1.01d-31
value slightly more, alow2 1.01d-31
real(c_double), parameter ahi = 1.0d31
value usually a good high, ahi 1.00d+31
real(c_double), parameter ahi2 = 1.01d31
value slighly more than ahi 1.01d+31
Detailed Description
Set of data, physics and string constants.
Variable Documentation
integer, parameter time_s = 1
Time units :: seconds.
   integer, parameter :: time_s = 1
integer, parameter time_m = 2
Time units :: minutes.
   integer, parameter :: time_m = 2
integer, parameter time_h = 3
Time units :: hours.
   integer, parameter :: time_h = 3
integer, parameter time_d = 4
Time units :: days.
   integer, parameter :: time_d = 4
integer, parameter time_y = 5
Time units :: years.
   integer, parameter :: time_y = 5
character(4), dimension(5) time_units = (/ 'sec ', 'min ', 'hr ', 'd ', 'y '/)
time unit name constants (short)
Referenced by DecayResourceIO_cimg::read().
   character(4) :: time_units(5) = (/ 'sec ', 'min ', 'hr  ', 'd   ', 'y   '/)
character(4), dimension(5) time_units_long = (/ 'sec ', 'min ', 'hrs ', 'days', 'yrs '/)
time unit name constants (long)
   character(4) :: time_units_long(5) = (/ 'sec ', 'min ', 'hrs ', 'days', 'yrs '/)
real(c_double), dimension(5) time_factors = (/1.0d0, 60.0d0, 3600.0d0, 86400.0d0, 3.156d7/)
number of seconds per time unit (NUNIT)
   real(C_DOUBLE) :: time_factors(5) = (/1.0d0, 60.0d0, 3600.0d0, 86400.0d0, 3.156d7/)
character(16), dimension(4), parameter library_titles = (/ ' light elements', ' actinides', 'fission products',' all nuclides'/)
Library titles.
Referenced by origen_output_class::evaluate_rates_and_balances().
   character(16), parameter :: library_titles(4) = (/ '  light elements', '       actinides', 'fission products','    all nuclides'/)
integer, parameter n_elements = 112
Number of elements supported by ORIGEN.
Referenced by origen_output::print_element_table().
   integer, parameter :: n_elements = 112
character(2), dimension(n_elements) elements = (/ ' h', 'he', 'li', 'be', ' b', ' c', ' n', ' o', ' f', 'ne', 'na', 'mg', 'al', 'si', ' p', ' s', 'cl', 'ar', ' k', 'ca', 'sc', 'ti', ' v', 'cr', 'mn', 'fe', 'co', 'ni', 'cu', 'zn', 'ga', 'ge', 'as', 'se', 'br', 'kr', 'rb', 'sr', ' y', 'zr', 'nb', 'mo', 'tc', 'ru', 'rh', 'pd', 'ag', 'cd', 'in', 'sn', 'sb', 'te', ' i', 'xe', 'cs', 'ba', 'la', 'ce', 'pr', 'nd', 'pm', 'sm', 'eu', 'gd', 'tb', 'dy', 'ho', 'er', 'tm', 'yb', 'lu', 'hf', 'ta', ' w', 're', 'os', 'ir', 'pt', 'au', 'hg', 'tl', 'pb', 'bi', 'po', 'at', 'rn', 'fr', 'ra', 'ac', 'th', 'pa', ' u', 'np', 'pu', 'am', 'cm', 'bk', 'cf', 'es', 'fm', 'md', 'no', 'lr', 'rf', 'db', 'sg', 'bh', 'hs', 'mt', 'ds', 'rg', 'cn'/)
Element symbols (corresponding to Z numbers)
Referenced by auxiliary::nuclide(), auxiliary::nuclide_compact(), and origen_output::print_table().
   character(2) ::  elements(n_elements) = (/ &
       ' h', 'he', 'li', 'be', ' b', ' c', ' n', ' o', ' f', 'ne', 'na', &
       'mg', 'al', 'si', ' p', ' s', 'cl', 'ar', ' k', 'ca', 'sc', 'ti', &
       ' v', 'cr', 'mn', 'fe', 'co', 'ni', 'cu', 'zn', 'ga', 'ge', 'as', &
       'se', 'br', 'kr', 'rb', 'sr', ' y', 'zr', 'nb', 'mo', 'tc', 'ru', &
       'rh', 'pd', 'ag', 'cd', 'in', 'sn', 'sb', 'te', ' i', 'xe', 'cs', &
       'ba', 'la', 'ce', 'pr', 'nd', 'pm', 'sm', 'eu', 'gd', 'tb', 'dy', &
       'ho', 'er', 'tm', 'yb', 'lu', 'hf', 'ta', ' w', 're', 'os', 'ir', &
       'pt', 'au', 'hg', 'tl', 'pb', 'bi', 'po', 'at', 'rn', 'fr', 'ra', &
       'ac', 'th', 'pa', ' u', 'np', 'pu', 'am', 'cm', 'bk', 'cf', 'es', &
       'fm', 'md', 'no', 'lr', 'rf', 'db', 'sg', 'bh', 'hs', 'mt', 'ds', &
       'rg', 'cn'/)
character(2), dimension(2) sta = (/ ' ', 'm '/)
metastable symbols (corresponding to I+1-number)
Referenced by auxiliary::nuclide(), and auxiliary::nuclide_compact().
   character(2) ::  sta(2) = (/ '  ', 'm '/)
real(c_double), dimension(99) amass = (/ 1.0079d0,4.0026d0,6.941d0,9.012d0,10.81d0,12.011d0,14.007d0,16.d0,19.d0, 20.18d0,22.99d0,24.31d0,26.98d0,28.09d0,30.97d0,32.06d0,35.45d0,39.95d0,39.10d0,40.08d0, 44.96d0,47.9d0,50.94d0,52.d0,54.94d0,55.85d0,58.93d0,58.7d0,63.55d0,65.38d0,69.72d0, 72.59d0,74.92d0,78.96d0,79.9d0,83.8d0,85.47d0,87.62d0,88.91d0,91.22d0,92.91d0,95.94d0, 99.d0,101.07d0,102.91d0,106.4d0,107.87d0,112.41d0,114.82d0,118.69d0,121.75d0,127.6d0, 126.90d0,131.3d0,132.9d0,137.33d0,138.91d0,140.1d0,140.9d0,144.2d0, 147.d0,150.4d0,151.96d0,157.25d0,158.9d0,162.5d0,164.9d0,167.3d0,168.9d0,173.d0,175.d0, 178.d0,181.d0,184.d0,186.d0,190.d0,192.d0,195.d0,196.d0,201.d0,204.d0,207.d0,209.d0,209.d0, 217.d0,222.d0,223.d0,226.d0,227.d0,232.d0,231.d0,238.d0,238.d0,239.d0,241.d0,243.d0,249.d0, 249.d0,252.d0 /)
Atomic masses for all elements.
Referenced by origen_neutron::totaln().
   real(C_DOUBLE) :: amass(99) = (/ &
      1.0079d0,4.0026d0,6.941d0,9.012d0,10.81d0,12.011d0,14.007d0,16.d0,19.d0,  &
      20.18d0,22.99d0,24.31d0,26.98d0,28.09d0,30.97d0,32.06d0,35.45d0,39.95d0,39.10d0,40.08d0,&
      44.96d0,47.9d0,50.94d0,52.d0,54.94d0,55.85d0,58.93d0,58.7d0,63.55d0,65.38d0,69.72d0,    &
      72.59d0,74.92d0,78.96d0,79.9d0,83.8d0,85.47d0,87.62d0,88.91d0,91.22d0,92.91d0,95.94d0,  &
      99.d0,101.07d0,102.91d0,106.4d0,107.87d0,112.41d0,114.82d0,118.69d0,121.75d0,127.6d0, &
      126.90d0,131.3d0,132.9d0,137.33d0,138.91d0,140.1d0,140.9d0,144.2d0,               &
      147.d0,150.4d0,151.96d0,157.25d0,158.9d0,162.5d0,164.9d0,167.3d0,168.9d0,173.d0,175.d0, &
      178.d0,181.d0,184.d0,186.d0,190.d0,192.d0,195.d0,196.d0,201.d0,204.d0,207.d0,209.d0,209.d0, &
      217.d0,222.d0,223.d0,226.d0,227.d0,232.d0,231.d0,238.d0,238.d0,239.d0,241.d0,243.d0,249.d0, &
      249.d0,252.d0 /)
character(13), dimension(11), parameter unit_titles = (/'gram-atoms ', 'grams ', 'curies ', 'watts ', 'gamma watts ', 'm3 air ', 'm3 water ', 'grams ppm ', 'atoms ppm ', 'atoms/barn-cm', 'becquerels '/)
Concentration table units titles.
Referenced by origen_output_class::evaluate_rates_and_balances().
   character(13), parameter :: unit_titles(11) = &
     (/'gram-atoms   ', &
       'grams        ', &
       'curies       ', &
       'watts        ', &
       'gamma watts  ', &
       'm3 air       ', &
       'm3 water     ', &
       'grams ppm    ', &
       'atoms ppm    ', &
       'atoms/barn-cm', &
       'becquerels   '/)
character(7), dimension(2), parameter table_titles = (/'Nuclide', 'Element'/)
Concentration table type titles.
Referenced by origen_output_class::evaluate_rates_and_balances().
   character(7), parameter :: table_titles(2) = (/'Nuclide', 'Element'/)
real(c_double), parameter high = huge(1.0)*0.5
value close to highest, high 1.00d+38
   real(C_DOUBLE), parameter :: high = huge(1.0)*0.5
real(c_double), parameter hi1 = high*0.1
value usually about 0.1d0 times high, hi1 1.00d+37
   real(C_DOUBLE), parameter :: hi1 = high*0.1
real(c_double), parameter hi2 = high*1.01
value slightly more, hi2 1.01d+38
   real(C_DOUBLE), parameter :: hi2 = high*1.01
real(c_double), parameter xlow = tiny(1.0)*2.0
value close to lowest, xlow 2.00d-38
   real(C_DOUBLE), parameter :: xlow = tiny(1.0)*2.0
real(c_double), parameter xlo1 = xlow*10.0
value usually about 10 times xlow, xlo1 1.00d-37
   real(C_DOUBLE), parameter :: xlo1 = xlow*10.0
real(c_double), parameter xlo2 = xlow*1.01
value slightly more, xlo2 2.01d-38
   real(C_DOUBLE), parameter :: xlo2 = xlow*1.01
real(c_double), parameter hineg = -high
value negative of high, hineg -1.00d+38
   real(C_DOUBLE), parameter :: hineg = -high
real(c_double), parameter xlneg = -xlow
value negative of xlow, xlneg -2.00d-38
   real(C_DOUBLE), parameter :: xlneg = -xlow
real(c_double), parameter alow = 1.0d-31
value usually a good low, alow 1.00d-31
   real(C_DOUBLE), parameter :: alow = 1.0d-31
real(c_double), parameter alo2 = 1.01d-31
value slightly more, alow2 1.01d-31
   real(C_DOUBLE), parameter :: alo2 = 1.01d-31
real(c_double), parameter ahi = 1.0d31
value usually a good high, ahi 1.00d+31
   real(C_DOUBLE), parameter :: ahi = 1.0d31
real(c_double), parameter ahi2 = 1.01d31
value slighly more than ahi 1.01d+31
   real(C_DOUBLE), parameter :: ahi2 = 1.01d31