ORIGEN API: Obiwan_info Class Reference
Obiwan_info Class Reference
#include <Obiwan_info.h>
execute obiwan in info mode
Public Member Functions
Obiwan_info (int argc, char **argv)
Obiwan_info (ScaleUtils::IO::DB opts)
~Obiwan_info () noexcept(false)
int execute (std::ostream &out, std::ostream &err)
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in info mode
Examples:
tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_info (int argc, char ** argv)
References Obiwan_info::b_opts, and Obiwan_info::populate().
 {
     b_opts = populate( argc, argv );
 }
Obiwan_info (ScaleUtils::IO::DB opts)
 : b_opts( opts ) {}
~Obiwan_info () inline noexcept
 {}
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_info::execute().
 {
     const char* help = R"help(
 //! [help]
  PURPOSE: display info about ORIGEN binary files
  USAGE: obiwan info [-type=f33|f71|yld] file1 file2 ...
         -flag=Type(DefaultValue)       DESCRIPTION
         ________________________       ____________________________
         -type=String()                 load only a partciular type
                                           f33: Origen::Library
                                           f71: Origen::StateSet
                                           yld: Origen::YieldResource
         -verbose                       verbose mode (extra output to STDERR)
  NOTE: all non-essential output goes to STDERR
  COLUMN          DESCRIPTION
  ---------       -----------
  fileName        path without the directory
  dataType        type/class of the object
  numSets         number of "sets" of data (e.g. burnups)
  fileFormat      the format of the dataType in this file
  fileType        "binary" or "text"
  file/sysEndian  endian-ness for the file itself and the system
                  (mismatches have I/O performance penalties)
  appVersion      version of the application which wrote this file
                  (some formats cannot store this and it appears as "-")
  ms              time in milliseconds to load the file
  directory       directory portion of path
  EXAMPLE:
     #display info for all w17 assemblies in SCALE's $DATA/arplibs directory
     $ obiwan info $DATA/arplibs/w17* 2>log
                   fileName            dataType numSets fileFormat fileType file/sysEndian appVersion    ms   directory
             w17_e15.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
             w17_e20.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
             w17_e30.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
             w17_e40.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
             w17_e50.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
             w17_e60.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
         w17_ofa_e15.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
         w17_ofa_e20.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
         w17_ofa_e30.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
         w17_ofa_e40.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
         w17_ofa_e50.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
         w17_ofa_e60.arplib     Origen::Library      11       s62b   binary     big/little          - 1e+01   /Users/ww5/lib/scale_dev_data/arplibs
 //! [help]
     )help";
     // break up tag so Doxygen doesn't think this is a 3rd tag
     return ScaleUtils::IO::removeSubstring( help,
                                             "//! ["
                                             ""
                                             "help"
                                             ""
                                             "]" );
 }
ScaleUtils::IO::DB populate (int argc, char ** argv) static
Referenced by Obiwan_info::Obiwan_info().
 {
     Standard::CommandLine cmd( argc, argv );
     // get files
     Origen::Vec_Str files = cmd.arguments();
     ScaleUtils::IO::DB base;
     // output error message
     if( files.size() == 0 )
     {
         base.set( "help", true );
     }
     else
     {
         // expand globs (e.g. *.txt)
         ScaleUtils::IO::expandPaths( files );
         // debugging echo
         jDebugLine( cmd.toString() );
         // get data type to read
         std::string dataType;
         {
             std::string type = cmd.getValue( "-type", "" );
             if( type == "Origen::Library" || type == "ft33" || type == "f33" )
             {
                 dataType = "Origen::Library";
             }
             else if( type == "Origen::StateSet" || type == "ft71" ||
                      type == "f71" )
             {
                 dataType = "Origen::StateSet";
             }
             else if( type == "yld" || type == "Origen::YieldResource" )
             {
                 dataType = "Origen::YieldResource";
             }
             else if( type != "" )
             {
                 base.appendError(
                     "Values for type are 'f33' or 'f71' or 'yld' \n"
                     "  f33 - read as Origen::Library types\n"
                     "  f71 - read as Origen::StateSet types\n"
                     "  yld - read as Origen::YieldResource types\n" );
             }
         }
         base.set( "dataType", dataType );
         // verbose
         base.set( "verbose", cmd.exists( "-verbose" ) ? true : false );
         base.set( "paths", new StringList( files ) );
         jDebugLine( base.toString() );  // debugging
     }
     return base;
 }
int execute (std::ostream & out, std::ostream & err)
References Obiwan_info::b_opts, Obiwan_info::help(), Origen::info(), and ORIGEN_MACRO_loadMulti.
Referenced by Origen::obiwan_main().
 {
     // quick returns
     if( b_opts.get( "help", false ) )
     {
         out << help() << std::endl;
         return 1;
     }
     else if( b_opts.numError() > 0 )
     {
         out << b_opts.writeErrorStack();
         return -1;
     }
     // table header
     out << std::setw( 26 ) << "fileName" << std::setw( 20 ) << "dataType"
         << std::setw( 8 ) << "numSets" << std::setw( 11 ) << "fileFormat"
         << std::setw( 9 ) << "fileType" << std::setw( 15 ) << "file/sysEndian"
         << std::setw( 11 ) << "appVersion" << std::setw( 6 ) << "ms"
         << "   "
         << "directory" << std::endl
         << std::flush;
     std::string sysEndian =
         ScaleUtils::IO::EndianUtils::system_is_big_endian() ? "big" : "little";
     // Loop over files.
     auto files = b_opts.get<StringList*>( "paths" );
     for( auto path : *files )
     {
         // ORIGEN_MACRO_loadMulti requires:
         // - string path
         // - DB opts
         // - int status
         ScaleUtils::IO::DB opts = b_opts.clone();
         int status = 0;
         ORIGEN_MACRO_loadMulti( info );
         // output options in JSON
         if( opts.get<bool>( "verbose", false ) ) err << opts << std::endl;
         // just skip misread
         if( status != 0 ) opts.clearErrorStack();
         out << std::setw( 26 ) << opts.get( "fileName", "-" ) << std::setw( 20 )
             << opts.get( "loadedDataType", "-" ) << std::setw( 8 )
             << opts.get( "loadedSets", 0 ) << std::setw( 11 )
             << opts.get( "loadedFileFormat", "-" ) << std::setw( 9 )
             << opts.get( "loadedFileType", "-" ) << std::setw( 15 )
             << opts.get( "readFileEndian", "-" ) + "/" + sysEndian
             << std::setw( 11 ) << opts.get( "readAppVersion", "-" )
             << nprintf( " %.0e", opts.get<double>( "loadTime", 0.0 ) ) << "   "
             << opts.get( "directory", "-" ) << std::endl
             << std::flush;
     }
     return 0;
 }
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_info::execute(), and Obiwan_info::Obiwan_info().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_info.h
Core/ut/Obiwan_info.cpp