ORIGEN API: StateSetIO_bof Class Reference
StateSetIO_bof Class Reference
#include <StateSetIO_bof.h>
Public Member Functions
bool read (StateSet &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const StateSet &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Detailed Description
Examples:
tstStateSetIO.cpp.
Member Function Documentation
bool read (StateSet & obj, std::istream & stream, ScaleUtils::IO::DB opts)
References StateSet::add_states(), StateInfo::case_number(), Origen::convertConcUnitToPrettyString(), StateInfo::energy(), StateInfo::flux(), Origen::intAsUnit(), StateInfo::library_position(), State::num_alpha_groups(), State::num_beta_groups(), State::num_gamma_groups(), State::num_neutron_groups(), StateInfo::power(), Origen::read(), State::set_alpha_spectra(), State::set_beta_spectra(), Spectrum::set_bounds(), State::set_concs(), State::set_definition(), State::set_gamma_spectra(), NuclideSet::set_ids(), Spectrum::set_intensity(), NeutronSpectra::set_intensity_alphan(), NeutronSpectra::set_intensity_delayn(), NeutronSpectra::set_intensity_sf(), State::set_neutron_spectra(), GammaSpectra::set_nuclide_type(), BetaSpectra::set_nuclide_type(), AlphaSpectra::set_nuclide_type(), StateInfo::step_number(), StateInfo::time(), and State::total_nuclides().
 {
     //
     // Insist we can read from this istream
     //
     if( !stream.good() )
     {
         opts.appendError( "Failed to open stream for reading." );
         return false;
     }
     nemesis::Timer t;
     t.start();
     //
     // BOFF reader for disk to memory communications
     //
     std::stringstream errmsg;
     try
     {
         bof::BOFReader reader( stream, errmsg );
         if( !reader.loadHeader() )
         {
             opts.appendError( "file is either corrupt or not BOF format" );
             return false;
         }
         bool check1 =
             opts.checkAppName( "ORIGEN_F71", reader.getAppName().c_str() );
         if( !check1 )
         {
             // second chance
             bool check2 =
                 opts.checkAppName( "ORIGENBM  ", reader.getAppName().c_str() );
             if( check2 )
             {
                 opts.clearErrorStack();
             }
             else
             {
                 return false;
             }
         }
         int appMajor = reader.getAppMajor();
         int appMinor = reader.getAppMinor();
         int appMicro = reader.getAppMicro();
         // This file was not written by SCALE if all these are 0.
         // This must be in some other system, e.g. a unit test of someone using
         // the ORIGEN API, so we don't enforce the versioning.
         if( !( appMajor == 0 && appMinor == 0 && appMicro == 0 ) )
         {
             bool check2 =
                 opts.checkAppVersion( Version( appMajor, appMinor, appMicro ),
                                       Version( "6.2.pre-b1" ) );
             if( !check2 ) return false;
         }
         // add file endianness
         opts.set( "readFileEndian",
                   ScaleUtils::IO::EndianUtils::file_is_big_endian(
                       reader.isNativeEndian() )
                       ? "big"
                       : "little" );
         //
         // Loop over cases
         // if header states size=0, then no more cases
         //
         for( int i = 0;; i++ )
         {
             jDebugTaggedLine( "Processing case " << i + 1 << "..." );
             //
             // Peek ahead to ensure not at eof
             //
             stream.peek();
             if( stream.good() == false ) break;
             //
             // BOF Object type and byte count for use during reading
             //
             bof::BOFType objType;
             size_t objByteCount;
             //
             // expect the case object
             //
             if( !reader.nextType( objType, objByteCount ) )
             {
                 std::stringstream ss;
                 ss << " failed to acquire the bof case object type and byte "
                       "count! ";
                 throw std::istream::failure( errmsg.str() + ss.str() );
             }
             jDebugTaggedLine( "reading BOFF objType=" << (int)objType );
             //
             // New State.
             //
             State state;
             //
             // Process header
             //
             StateInfo def;
             //
             // read the library header object
             //
             bof::BOFObject obj;
             if( !reader.read( objByteCount, obj ) )
             {
                 throw std::istream::failure(
                     "Failed to read bof case object data!" );
             }
             ::Origen::read( obj, def );
             state.set_definition( def );
             jDebugLine( "Case number: " << def.case_number()
                                         << ", Step number: "
                                         << def.step_number()
                                         << ", Library position: "
                                         << def.library_position()
                                         << ", power: "
                                         << def.power()
                                         << ", energy: "
                                         << def.energy()
                                         << ", flux: "
                                         << def.flux()
                                         << ", time: "
                                         << def.time() );
             // int nln  = obj.getInt("nl");
             // int nan  = obj.getInt("na");
             // int nfpn = obj.getInt("nf");
             //
             // Read Case concentrations
             // OPTIONAL based on concentrations (co)
             //          nuclide ids (ni)
             //          units (un)
             //          volume (vo)
             if( obj.containsKey( "co" ) && obj.containsKey( "ni" ) &&
                 obj.containsKey( "un" ) && obj.containsKey( "vo" ) )
             {
                 // get data
                 const bof::BOFArray<bof::bof_int>& bof_ids =
                     obj.get<bof::BOFArray<bof::bof_int>>( "ni" );
                 const bof::BOFArray<bof::bof_double>& bof_concs =
                     obj.get<bof::BOFArray<bof::bof_double>>( "co" );
                 int units = obj.getInt( "un" );
                 double volume = obj.getDouble( "vo" );
                 Check( (int)bof_concs.size() == bof_ids.size() );
                 Concentrations concs;
                 Vec_Int ids( bof_ids.size() );
                 Vec_Dbl vals( bof_ids.size() );
                 for( size_t n = 0; n < bof_ids.size(); ++n )
                 {
                     ids[n] = int( bof_ids[n] );
                     vals[n] = double( bof_concs[n] );
                 }
                 NuclideSet nucset;
                 nucset.set_ids( ids );
                 concs.set_nuclide_set( nucset );
                 concs.set_units( intAsUnit( units ) );
                 concs.set_volume( volume );
                 concs.set_vals( vals );
                 jDebugLine( "Read "
                             << convertConcUnitToPrettyString( concs.units() )
                             << " <- "
                             << units
                             << " as units on BOFFF71" );
                 state.set_concs( concs );
                 jDebugLine( "--Concentrations.units:"
                             << convertConcUnitToPrettyString( concs.units() )
                             << ", number concentrations:"
                             << state.total_nuclides() );
             }  // though was no concentrations record
             else
             {
                 jDebugLine( "--No Concentrations record." );
             }
             //
             // Read Case neutron spectra
             // OPTIONAL based on energy group bounds (eg)
             //          spectrum (sp)
             //          alpha spectrum (as)
             //          delayed neutron spectrum (dn)
             //          spontaneous fission spectrum (sf)
             if( obj.containsKey( "eg" ) && obj.containsKey( "sp" ) &&
                 obj.containsKey( "as" ) && obj.containsKey( "dn" ) &&
                 obj.containsKey( "sf" ) )
             {
                 Vec_Dbl dvec;
                 NeutronSpectra nspec;
                 ::bof::read( obj, "eg", dvec );
                 nspec.set_bounds( dvec );
                 ::bof::read( obj, "sp", dvec );
                 nspec.set_intensity( dvec );
                 ::bof::read( obj, "as", dvec );
                 nspec.set_intensity_alphan( dvec );
                 ::bof::read( obj, "dn", dvec );
                 nspec.set_intensity_delayn( dvec );
                 ::bof::read( obj, "sf", dvec );
                 nspec.set_intensity_sf( dvec );
                 // set in state
                 state.set_neutron_spectra( nspec );
                 jDebugLine( "--Read Neutron spectra" );
             }
             else
             {
                 jDebugLine( "--No Neutron spectra record." );
             }
             //
             // Read Case gamma spectra
             // OPTIONAL based on gamma energy bounds (ge)
             //          gamma spectrum (gs)
             //          nuclide type (nt)
             if( obj.containsKey( "ge" ) && obj.containsKey( "gs" ) &&
                 obj.containsKey( "nt" ) )
             {
                 Vec_Dbl dvec;
                 GammaSpectra gspec;
                 ::bof::read( obj, "ge", dvec );
                 gspec.set_bounds( dvec );
                 int nt;
                 ::bof::read( obj, "nt", nt );
                 gspec.set_nuclide_type( nt );
                 ::bof::read( obj, "gs", dvec );
                 gspec.set_intensity( dvec );
                 state.set_gamma_spectra( gspec );
                 jDebugLine( "--Read Gamma spectra." );
             }
             else
             {
                 jDebugLine( "--No Gamma spectra record." );
             }
             //
             // Read Case alpha spectra
             // OPTIONAL based on alpha group bounds (ab)
             //          alpha spectrum (al)
             //          alpha nuclide type (at)
             // Read fortran header of record
             if( obj.containsKey( "ab" ) && obj.containsKey( "al" ) &&
                 obj.containsKey( "at" ) )
             {
                 Vec_Dbl dvec;
                 AlphaSpectra aspec;
                 ::bof::read( obj, "ab", dvec );
                 aspec.set_bounds( dvec );
                 int nt;
                 ::bof::read( obj, "at", nt );
                 aspec.set_nuclide_type( nt );
                 ::bof::read( obj, "al", dvec );
                 aspec.set_intensity( dvec );
                 state.set_alpha_spectra( aspec );
                 jDebugLine( "--Read Alpha spectra." );
             }
             else
             {
                 jDebugLine( "--No Alpha spectra record." );
             }
             //
             // Read Case beta spectra
             // OPTIONAL based on beta group bounds (bb)
             //          beta spectrum (be)
             //          beta nuclide type (bt)
             if( obj.containsKey( "bb" ) && obj.containsKey( "be" ) &&
                 obj.containsKey( "bt" ) )
             {
                 Vec_Dbl dvec;
                 BetaSpectra bspec;
                 ::bof::read( obj, "bb", dvec );
                 bspec.set_bounds( dvec );
                 int nt;
                 ::bof::read( obj, "bt", nt );
                 bspec.set_nuclide_type( nt );
                 ::bof::read( obj, "be", dvec );
                 bspec.set_intensity( dvec );
                 state.set_beta_spectra( bspec );
                 jDebugLine( "--Read Beta spectra." );
             }
             else
             {
                 jDebugLine( "--No Beta spectra record." );
             }
             jDebugLine( ", total nuclides: " << state.total_nuclides()
                                              << ", num neutron groups: "
                                              << state.num_neutron_groups()
                                              << ", num gamma groups: "
                                              << state.num_gamma_groups()
                                              << ", num alpha groups: "
                                              << state.num_alpha_groups()
                                              << ", num beta groups: "
                                              << state.num_beta_groups() );
             //
             //
             // Save the case we just read
             //
             set.add_states( state );
         }  // infinite loop
     }
     catch( std::ios_base::failure& e )
     {
         opts.appendError( e.what() );
         return false;
     }
     t.stop();
     opts.set( "loadTime", 1000 * t.wall_clock() );
     return true;
 }
bool write (const StateSet & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
Examples:
tstStateSetIO.cpp.
References State::alpha_spectra(), State::beta_spectra(), Spectrum::bounds(), State::concs(), State::definition(), State::gamma_spectra(), State::has_alpha_spectra(), State::has_beta_spectra(), State::has_concs(), State::has_definition(), State::has_gamma_spectra(), NeutronSpectra::has_intensity_alphan(), NeutronSpectra::has_intensity_delayn(), NeutronSpectra::has_intensity_sf(), State::has_neutron_spectra(), NuclideSet::ids(), Spectrum::intensity(), NeutronSpectra::intensity_alphan(), NeutronSpectra::intensity_delayn(), NeutronSpectra::intensity_sf(), State::neutron_spectra(), Concentrations::nuclide_set(), AlphaSpectra::nuclide_type(), BetaSpectra::nuclide_type(), GammaSpectra::nuclide_type(), Origen::setAppVersionWrite(), StateSet::states_at(), StateSet::states_size(), Origen::unitAsInt(), Concentrations::units(), Concentrations::vals(), Concentrations::volume(), and Origen::write().
Referenced by TEST_F().
 {
     Vec_Str errors;
     //
     // Insist we can write to this stream
     //
     if( !stream.good() )
     {
         opts.appendError( "Failed to open stream for writing." );
         return false;
     }
     nemesis::Timer t;
     t.start();
     //
     // handle append
     //
     bool append = opts.get( "append", false );
     if( append )
     {
         jDebugLine(
             "StateSetIO_bof is appending data because data already exists" );
     }
     else
     {
         jDebugLine(
             "StateSetIO_bof is not appending data because it either doesn't "
             "exist or wasn't asked for" );
     }
     bof::BOFWriter writer( stream, append );
     if( !append )
     {
         setAppVersionWrite( writer, opts, "ORIGEN_F71" );
         // add file endianness
         opts.set( "wroteFileEndian",
                   ScaleUtils::IO::EndianUtils::system_is_big_endian()
                       ? "big"
                       : "little" );
         if( !writer.writeHeader() ) return false;
     }
     for( size_t index = 0; index < set.states_size(); ++index )
     {
         jDebugTaggedLine( "Writing case " << index + 1 << "..." );
         const State& state = set.states_at( index );
         bof::BOFObject obj;
         //
         // Write header
         //
         const StateInfo& def = state.definition();
         ::Origen::write( obj, def );
         if( !state.has_definition() )
         {
             opts.appendError( "No header information for bof file!" );
             return false;
         }
         //
         // Write concentrations
         //
         if( state.has_concs() )
         {
             const Concentrations& concs = state.concs();
             const Vec_Int& ids = concs.nuclide_set().ids();
             const Vec_Dbl& vals = concs.vals();
             ::bof::write( obj, "ni", ids );
             ::bof::write( obj, "un", unitAsInt( concs.units() ) );
             ::bof::write( obj, "vo", concs.volume() );
             ::bof::write( obj, "co", vals );
         }
         //
         // Write neutron spectra
         //
         if( state.has_neutron_spectra() )
         {
             const NeutronSpectra& nspec = state.neutron_spectra();
             ::bof::write( obj, "eg", nspec.bounds() );
             ::bof::write( obj, "sp", nspec.intensity() );
             if( nspec.has_intensity_sf() )
                 ::bof::write( obj, "sf", nspec.intensity_sf() );
             if( nspec.has_intensity_alphan() )
                 ::bof::write( obj, "as", nspec.intensity_alphan() );
             if( nspec.has_intensity_delayn() )
                 ::bof::write( obj, "dn", nspec.intensity_delayn() );
         }
         //
         // Write gamma spectra
         //
         if( state.has_gamma_spectra() )
         {
             const GammaSpectra& gspec = state.gamma_spectra();
             ::bof::write( obj, "ge", gspec.bounds() );
             ::bof::write( obj, "nt", gspec.nuclide_type() );
             ::bof::write( obj, "gs", gspec.intensity() );
         }
         //
         // Write alpha spectra
         //
         if( state.has_alpha_spectra() )
         {
             const AlphaSpectra& aspec = state.alpha_spectra();
             ::bof::write( obj, "ab", aspec.bounds() );
             ::bof::write( obj, "at", aspec.nuclide_type() );
             ::bof::write( obj, "al", aspec.intensity() );
         }
         //
         // Write beta spectra
         //
         if( state.has_beta_spectra() )
         {
             const BetaSpectra& bspec = state.beta_spectra();
             ::bof::write( obj, "bb", bspec.bounds() );
             ::bof::write( obj, "bt", bspec.nuclide_type() );
             ::bof::write( obj, "be", bspec.intensity() );
         }
         //
         // BIG WRITE
         //
         writer.write( obj );
     }  // loop
     t.stop();
     opts.set( "saveTime", 1000 * t.wall_clock() );
     return true;
 }
The documentation for this class was generated from the following files:
Core/io/StateSetIO_bof.h
Core/io/StateSetIO_bof.cpp