ORIGEN API: TransitionSystem_Gen Class Reference
TransitionSystem_Gen Class Reference
#include <TransitionSystem_Gen.h>
General-purpose implementation of the TransitionSystem interface.
Public Types
typedef SP_TransitionSystem SP
typedef WP_TransitionSystem WP
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::TransitionSystem>>
See Origen::TransitionSystem for details.
SP_Nuclide add_nuclide (int isomeric_state, SP_Species species)
SP_Nuclide add_nuclide (int isomeric_state, int charge_number, int mass_number)
SP_Nuclide add_nuclide (int izzzaaa)
SP_Nuclide nuclide (int nuclide_id) const
void get_nuclide (int nuclide_id, SP_Nuclide &nuclide) const
void set_nuclide (SP_Nuclide nuclide)
std::vector< SP_Nuclide > nuclides () const
void get_nuclides (std::vector< SP_Nuclide > &nuclides) const
void set_nuclides (std::vector< SP_Nuclide > nuclides)
size_t num_nuclides () const
SP_Nuclide add_byproduct (int byproduct_id)
SP_Nuclide byproduct (int byproduct_id) const
std::vector< SP_Nuclide > byproducts () const
ByproductCount_t num_byproducts () const
SP_Species add_species (int charge_number, int mass_number)
SP_Species add_species (int charge_number, double mass)
SP_Species add_species (int charge_number, int mass_number, double mass)
SP_Species species (int species_id) const
void get_species (int species_id, SP_Species &species) const
void set_species (SP_Species species)
size_t num_species () const
SP_ChannelType add_channel_type (int field_id, int reaction_mt, int decay_mode=0)
SP_ChannelType add_channel_type (SP_Field field, int reaction_mt, int decay_mode=0)
SP_ChannelType add_channel_type (int decay_mode)
SP_ChannelType channel_type (SP_Field field, int reaction_mt, int decay_mode=0)
SP_ChannelType channel_type (int decay_mode)
SP_Field add_field (int field_id)
SP_Field field (int field_id) const
void populate_gains ()
void clear_gains ()
Public Member Functions
virtual ~TransitionSystem_Gen ()
Private Types
typedef std::map< int, Nuclide::SP > NuclideRegistry
typedef std::map< int, Species::SP > SpeciesRegistry
typedef std::map< int, ChannelType::SP > ChannelTypeRegistry
typedef std::map< int, Field::SP > FieldRegistry
typedef std::map< int, Nuclide::SP > ByproductRegistry
Private Member Functions
virtual Nuclide::SP add_nuclide_impl (int isomeric_state, int charge_number, int mass_number)
virtual Species::SP add_species_impl (int charge_number, int mass_number)
virtual Nuclide::SP add_byproduct_impl (int byproduct_id)
virtual Nuclide::SP byproduct_impl (int byproduct_id) const
virtual std::vector< Nuclide::SP > byproducts_impl () const
virtual bool is_initialized_impl () const
useful to chain
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual std::vector< Nuclide::SP > nuclides_impl () const
virtual void get_nuclides_impl (std::vector< Nuclide::SP > &nuclides) const
virtual void set_nuclides_impl (std::vector< Nuclide::SP > nuclides)
virtual Nuclide::SP nuclide_impl (int nuclide_id) const
virtual void get_nuclide_impl (int nuclide_id, Nuclide::SP &nuclide) const
virtual void set_nuclide_impl (Nuclide::SP nuclide)
virtual Species::SP species_impl (int species_id) const
virtual void get_species_impl (int species_id, Species::SP &species) const
virtual void set_species_impl (Species::SP species)
virtual size_t num_nuclides_impl () const
virtual size_t num_species_impl () const
virtual ChannelType::SP add_channel_type_impl (int field_id, int reaction_mt, int decay_mode=0)
virtual ChannelType::SP add_channel_type_impl (SP_Field field, int reaction_mt, int decay_mode=0)
virtual ChannelType::SP add_channel_type_impl (int decay_mode)
virtual SP_ChannelType channel_type_impl (SP_Field field, int reaction_mt, int decay_mode)
virtual SP_ChannelType channel_type_impl (int decay_mode)
virtual Field::SP add_field_impl (int field_id)
virtual Field::SP field_impl (int field_id) const
Private Attributes
NuclideRegistry b_nuclide_map
SpeciesRegistry b_species_map
ChannelTypeRegistry b_channel_type_map
FieldRegistry b_field_map
ByproductRegistry b_byproduct_map
Detailed Description
General-purpose implementation of the TransitionSystem interface.
See also
Origen::Nuclide_Gen
Examples:
tstTransitionMatrixUpdater.cpp, tstTransitionSystem_Gen.cpp, tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::map<int, Nuclide::SP> NuclideRegistry private
typedef std::map<int, Species::SP> SpeciesRegistry private
typedef std::map<int, ChannelType::SP> ChannelTypeRegistry private
typedef std::map<int, Field::SP> FieldRegistry private
typedef std::map<int, Nuclide::SP> ByproductRegistry private
typedef SP_TransitionSystem SP inherited
typedef WP_TransitionSystem WP inherited
Constructor & Destructor Documentation
~TransitionSystem_Gen () virtual
 {}
Member Function Documentation
Nuclide::SP add_nuclide_impl (int isomeric_state, int charge_number, int mass_number) private virtual
Implements TransitionSystem.
References TransitionSystem::add_species(), TransitionSystem_Gen::b_nuclide_map, and Checkable::id().
 {
     //         Check(isomeric_state>=0);
     //         Check(charge_number>0);
     //         Check(mass_number>0);
     int id = isomeric_state * 1000000 + charge_number * 1000 + mass_number;
     NuclideRegistry::iterator it = b_nuclide_map.find( id );
     if( it == b_nuclide_map.end() )
     {
         Species::SP s = add_species( charge_number, mass_number );
         Nuclide::SP n( new Nuclide_Gen( isomeric_state, s ) );
         n->set_system( this );
         b_nuclide_map[id] = n;
         return n;
     }
     return it->second;
 }
Species::SP add_species_impl (int charge_number, int mass_number) private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_species_map, and Checkable::id().
 {
     int id = charge_number * 1000 + mass_number;
     SpeciesRegistry::iterator it = b_species_map.find( id );
     if( it == b_species_map.end() )
     {
         Species::SP s( new Species_Gen( charge_number, mass_number ) );
         b_species_map[id] = s;
         return s;
     }
     return it->second;
 }
Nuclide::SP add_byproduct_impl (int byproduct_id) private virtual
Implements TransitionSystem.
References Origen::ALPHA_BYPRODUCT_ID, TransitionSystem_Gen::b_byproduct_map, TransitionSystem::byproduct(), Origen::DEUTERON_BYPRODUCT_ID, Origen::ELECTRON_BYPRODUCT_ID, Origen::HELION_BYPRODUCT_ID, Origen::NEUTRON_BYPRODUCT_ID, Origen::POSITRON_BYPRODUCT_ID, Origen::PROTON_BYPRODUCT_ID, and Origen::TRITON_BYPRODUCT_ID.
 {
     Nuclide::SP byproduct = this->byproduct( byproduct_id );
     if( byproduct == nullptr )
     {
         Species::SP byproduct_species;
         if( byproduct_id == NEUTRON_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Neutron() );
         }
         else if( byproduct_id == PROTON_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Proton() );
         }
         else if( byproduct_id == DEUTERON_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Deuteron() );
         }
         else if( byproduct_id == TRITON_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Triton() );
         }
         else if( byproduct_id == HELION_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Helion() );
         }
         else if( byproduct_id == ALPHA_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Alpha() );
         }
         else if( byproduct_id == ELECTRON_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Electron() );
         }
         else if( byproduct_id == POSITRON_BYPRODUCT_ID )
         {
             byproduct_species = Species::SP( new Positron() );
         }
         else
         {
             byproduct_species = Species::SP( new Species_Gen() );
         }
         byproduct = Nuclide::SP( new Nuclide_Gen( 0, byproduct_species ) );
         byproduct->set_system( this );
         b_byproduct_map[byproduct_id] = byproduct;
     }
     return byproduct;
 }
Nuclide::SP byproduct_impl (int byproduct_id) const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_byproduct_map.
 {
     ByproductRegistry::const_iterator it = b_byproduct_map.find( byproduct_id );
     if( it != b_byproduct_map.end() )
     {
         return it->second;
     }
     return nullptr;
 }
std::vector< Nuclide::SP > byproducts_impl () const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_byproduct_map, and TransitionSystem::byproducts().
 {
     std::vector<Nuclide::SP> byproducts;
     byproducts.reserve( b_byproduct_map.size() );
     ByproductRegistry::const_iterator it = b_byproduct_map.begin();
     while( it != b_byproduct_map.end() )
     {
         byproducts.push_back( it->second );
         ++it;
     }
     return byproducts;
 }
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 { return true; }
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
 { return true; }
std::vector< Nuclide::SP > nuclides_impl () const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_nuclide_map, and TransitionSystem::nuclides().
 {
     std::vector<Nuclide::SP> nuclides;
     nuclides.reserve( b_nuclide_map.size() );
     NuclideRegistry::const_iterator it = b_nuclide_map.begin();
     while( it != b_nuclide_map.end() )
     {
         nuclides.push_back( it->second );
         ++it;
     }
     return nuclides;
 }
void get_nuclides_impl (std::vector< Nuclide::SP > & nuclides) const private virtual
Implements TransitionSystem.
References TransitionSystem::nuclides().
 {
     nuclides = this->nuclides();
 }
void set_nuclides_impl (std::vector< Nuclide::SP > nuclides) private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_nuclide_map, TransitionSystem_Gen::b_species_map, and Checkable::has_initialized_id().
 {
     for( size_t i = 0; i < nuclides.size(); ++i )
     {
         Check( nuclides[i]->has_initialized_id() );
         b_nuclide_map[nuclides[i]->id()] = nuclides[i];
         Check( nuclides[i]->has_initialized_species() );
         nuclides[i]->set_system( this );
         b_species_map[nuclides[i]->species()->id()] = nuclides[i]->species();
     }
 }
Nuclide::SP nuclide_impl (int nuclide_id) const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_nuclide_map.
 {
     NuclideRegistry::const_iterator it = b_nuclide_map.find( nuclide_id );
     if( it != b_nuclide_map.end() ) return it->second;
     return nullptr;
 }
void get_nuclide_impl (int nuclide_id, Nuclide::SP & nuclide) const private virtual
Implements TransitionSystem.
References TransitionSystem::nuclide().
 {
     nuclide = this->nuclide( nuclide_id );
 }
void set_nuclide_impl (Nuclide::SP nuclide) private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_nuclide_map, and TransitionSystem::nuclide().
 {
     Require( nuclide->has_initialized_id() );
     nuclide->set_system( this );
     b_nuclide_map[nuclide->id()] = nuclide;
 }
Species::SP species_impl (int species_id) const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_species_map.
 {
     SpeciesRegistry::const_iterator it = b_species_map.find( species_id );
     if( it != b_species_map.end() ) return it->second;
     return nullptr;
 }
void get_species_impl (int species_id, Species::SP & species) const private virtual
Implements TransitionSystem.
References TransitionSystem::species().
 {
     species = this->species( species_id );
 }
void set_species_impl (Species::SP species) private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_species_map, and TransitionSystem::species().
 {
     Require( species->has_initialized_id() );
     b_species_map[species->id()] = species;
 }
size_t num_nuclides_impl () const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_nuclide_map.
 {
     return b_nuclide_map.size();
 }
size_t num_species_impl () const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_species_map.
 {
     return b_species_map.size();
 }
ChannelType::SP add_channel_type_impl (int field_id, int reaction_mt, int decay_mode = 0) private virtual
Implements TransitionSystem.
References TransitionSystem::add_channel_type(), TransitionSystem::add_field(), and TransitionSystem::field().
 {
     Field::SP field = add_field( field_id );
     return add_channel_type( field, reaction_mt, decay_mode );
 }
ChannelType::SP add_channel_type_impl (SP_Field field, int reaction_mt, int decay_mode = 0) private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_channel_type_map, and TransitionSystem::channel_type().
 {
     Require( field != nullptr );
     // create a channel type to get the id
     ChannelType::SP channel_type =
         this->channel_type( field, reaction_mt, decay_mode );
     if( channel_type == nullptr )
     {
         if( reaction_mt == 18 )
         {
             Check( decay_mode == 0 );
             channel_type = ChannelType::SP( new ChannelType_Fiss( field ) );
         }
         else if( reaction_mt != 0 )
         {
             channel_type =
                 ChannelType::SP( new ChannelType_Reac( field, reaction_mt ) );
         }
         else
         {
             channel_type =
                 ChannelType::SP( new ChannelType_Decay( decay_mode ) );
         }
         b_channel_type_map[channel_type->id()] = channel_type;
     }
     return channel_type;
 }
ChannelType::SP add_channel_type_impl (int decay_mode) private virtual
Implements TransitionSystem.
References TransitionSystem::add_channel_type(), TransitionSystem::add_field(), and Origen::NULL_FIELD.
 {
     return add_channel_type( add_field( NULL_FIELD ), 0, decay_mode );
 }
SP_ChannelType channel_type_impl (SP_Field field, int reaction_mt, int decay_mode) private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_channel_type_map, and ChannelType::channel_id().
Referenced by TransitionSystem_Gen::channel_type_impl().
 {
     int channel_id = ChannelType::channel_id( field, reaction_mt, decay_mode );
     ChannelTypeRegistry::iterator it = b_channel_type_map.find( channel_id );
     return it == b_channel_type_map.end() ? nullptr : it->second;
 }
SP_ChannelType channel_type_impl (int decay_mode) private virtual
Implements TransitionSystem.
References TransitionSystem::add_field(), TransitionSystem_Gen::channel_type_impl(), and Origen::NULL_FIELD.
 {
     return channel_type_impl( add_field( NULL_FIELD ), 0, decay_mode );
 }
Field::SP add_field_impl (int field_id) private virtual
Implements TransitionSystem.
References Origen::ALPHA_FIELD, TransitionSystem_Gen::b_field_map, Origen::DEUTERON_FIELD, Origen::ELECTRON_FIELD, TransitionSystem::field(), Origen::HELION_FIELD, Origen::NEUTRON_FIELD, Origen::NULL_FIELD, Origen::POSITRON_FIELD, Origen::PROTON_FIELD, and Origen::TRITON_FIELD.
 {
     Field::SP field = this->field( field_id );
     if( field == nullptr )
     {
         if( field_id == NULL_FIELD )
         {
             field = Field::SP( new NullField() );
         }
         else if( field_id == NEUTRON_FIELD )
         {
             field = Field::SP( new NeutronField() );
         }
         else if( field_id == PROTON_FIELD )
         {
             field = Field::SP( new ProtonField() );
         }
         else if( field_id == DEUTERON_FIELD )
         {
             field = Field::SP( new DeuteronField() );
         }
         else if( field_id == TRITON_FIELD )
         {
             field = Field::SP( new TritonField() );
         }
         else if( field_id == HELION_FIELD )
         {
             field = Field::SP( new HelionField() );
         }
         else if( field_id == ALPHA_FIELD )
         {
             field = Field::SP( new AlphaField() );
         }
         else if( field_id == ELECTRON_FIELD )
         {
             field = Field::SP( new ElectronField() );
         }
         else if( field_id == POSITRON_FIELD )
         {
             field = Field::SP( new PositronField() );
         }
         else
         {
             field = Field::SP( new Field_Gen() );
         }
         b_field_map[field_id] = field;
     }
     return field;
 }
Field::SP field_impl (int field_id) const private virtual
Implements TransitionSystem.
References TransitionSystem_Gen::b_field_map.
 {
     FieldRegistry::const_iterator it = b_field_map.find( field_id );
     if( it != b_field_map.end() )
     {
         return it->second;
     }
     return nullptr;
 }
Nuclide::SP add_nuclide (int isomeric_state, SP_Species species) inherited
Examples:
tstTransitionSystem_Gen.cpp.
References auxiliary::nuclide().
Referenced by TransitionSystemAdapter_DecayResource::extend(), TransitionSystemAdapter_TransitionMatrix::extend(), TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), TransitionMatrixUpdater::load(), TransitionSystem_Gen_Setup::SetUp(), and TEST().
 {
     Nuclide::SP nuclide = add_nuclide_impl( isomeric_state, species );
     nuclide->set_system( this );
     return nuclide;
 }
Nuclide::SP add_nuclide (int isomeric_state, int charge_number, int mass_number) inherited
References auxiliary::nuclide().
 {
     Nuclide::SP nuclide =
         add_nuclide_impl( isomeric_state, charge_number, mass_number );
     nuclide->set_system( this );
     return nuclide;
 }
Nuclide::SP add_nuclide (int izzzaaa) inherited
References auxiliary::nuclide().
 {
     int s, i, z, a;
     ScaleData::Utils::split_pizzzaaa( izzzaaa, s, i, z, a );
     Check( s == 0 );
     Nuclide::SP nuclide = add_nuclide_impl( i, z, a );
     nuclide->set_system( this );
     return nuclide;
 }
Nuclide::SP nuclide (int nuclide_id) const inherited
Examples:
tstTransitionMatrixUpdater.cpp, tstTransitionSystem_Gen.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by check_og_xs(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), TransitionMatrixUpdater::fetch_ts_nuclides(), TransitionSystem_Gen::get_nuclide_impl(), LibraryBuilder::search_reaction_transitions(), TransitionSystem_Gen::set_nuclide_impl(), Origen::test::TEST(), TEST_F(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     return nuclide_impl( nuclide_id );
 }
void get_nuclide (int nuclide_id, SP_Nuclide & nuclide) const inherited
 {
     get_nuclide_impl( nuclide_id, nuclide );
 }
void set_nuclide (SP_Nuclide nuclide) inherited
 {
     set_nuclide_impl( nuclide );
 }
std::vector< Nuclide::SP > nuclides () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_reaction_transitions(), TransitionSystemAdapter_TransitionMatrix::extend(), TransitionSystem_Gen::get_nuclides_impl(), TransitionSystem_Gen::nuclides_impl(), and Origen::printTransitionSystemXs().
 {
     return nuclides_impl();
 }
void get_nuclides (std::vector< SP_Nuclide > & nuclides) const inherited
 {
     get_nuclides_impl( nuclides );
 }
void set_nuclides (std::vector< SP_Nuclide > nuclides) inherited
 {
     set_nuclides_impl( nuclides );
 }
size_t num_nuclides () const inherited
Examples:
tstTransitionSystem_Gen.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
 { return num_nuclides_impl(); }
SP_Nuclide add_byproduct (int byproduct_id) inherited
Referenced by Channel_Gen::update_byproduct_transitions_impl().
 {
     return add_byproduct_impl( byproduct_id );
 }
SP_Nuclide byproduct (int byproduct_id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_byproduct_impl().
 {
     return byproduct_impl( byproduct_id );
 }
std::vector< SP_Nuclide > byproducts () const inherited
Referenced by TransitionSystem_Gen::byproducts_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), and LibraryBuilder::search_reaction_transitions().
 {
     return byproducts_impl();
 }
ByproductCount_t num_byproducts () const inherited
Species::SP add_species (int charge_number, int mass_number) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), and TransitionSystem_Gen_Setup::SetUp().
 {
     return add_species_impl( charge_number, mass_number );
 }
Species::SP add_species (int charge_number, double mass) inherited
 {
     return add_species_impl( charge_number, mass );
 }
Species::SP add_species (int charge_number, int mass_number, double mass) inherited
 {
     return add_species_impl( charge_number, mass_number, mass );
 }
Species::SP species (int species_id) const inherited
Referenced by TransitionSystem_Gen::get_species_impl(), and TransitionSystem_Gen::set_species_impl().
 {
     return species_impl( species_id );
 }
void get_species (int species_id, SP_Species & species) const inherited
 {
     get_species_impl( species_id, species );
 }
void set_species (SP_Species species) inherited
 {
     set_species_impl( species );
 }
size_t num_species () const inherited
 { return num_species_impl(); }
ChannelType::SP add_channel_type (int field_id, int reaction_mt, int decay_mode = 0) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), Nuclide::add_loss_impl(), and TransitionSystemAdapter_DecayResource::extend().
 {
     return add_channel_type_impl( field_id, reaction_mt, decay_mode );
 }
ChannelType::SP add_channel_type (SP_Field field, int reaction_mt, int decay_mode = 0) inherited
 {
     return add_channel_type_impl( field, reaction_mt, decay_mode );
 }
ChannelType::SP add_channel_type (int decay_mode) inherited
 {
     return add_channel_type_impl( decay_mode );
 }
SP_ChannelType channel_type (SP_Field field, int reaction_mt, int decay_mode = 0) inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), check_og_xs(), TEST_F(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     return channel_type_impl( field, reaction_mt, decay_mode );
 }
SP_ChannelType channel_type (int decay_mode) inherited
 {
     return channel_type_impl( decay_mode );
 }
Field::SP add_field (int field_id) inherited
Examples:
tstTransitionSystem_Gen.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), TransitionSystem_Gen::channel_type_impl(), TransitionSystemAdapter_TransitionMatrix::extend(), and TEST_F().
 {
     return add_field_impl( field_id );
 }
Field::SP field (int field_id) const inherited
Examples:
tstTransitionSystem_Gen.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionSystem_Gen::add_channel_type_impl(), TransitionSystem_Gen::add_field_impl(), check_og_xs(), TransitionMatrixUpdater::get_transition_matrix(), TEST_F(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().
 {
     return field_impl( field_id );
 }
void populate_gains () inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystemAdapter_DecayResource::extend(), TransitionSystemAdapter_TransitionMatrix::extend(), TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), and TransitionSystem_Gen_Setup::SetUp().
 { populate_gains_impl(); }
void clear_gains () inherited
 { clear_gains_impl(); }
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
NuclideRegistry b_nuclide_map private
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::nuclide_impl(), TransitionSystem_Gen::nuclides_impl(), TransitionSystem_Gen::num_nuclides_impl(), TransitionSystem_Gen::set_nuclide_impl(), and TransitionSystem_Gen::set_nuclides_impl().
SpeciesRegistry b_species_map private
Referenced by TransitionSystem_Gen::add_species_impl(), TransitionSystem_Gen::num_species_impl(), TransitionSystem_Gen::set_nuclides_impl(), TransitionSystem_Gen::set_species_impl(), and TransitionSystem_Gen::species_impl().
ChannelTypeRegistry b_channel_type_map private
Referenced by TransitionSystem_Gen::add_channel_type_impl(), and TransitionSystem_Gen::channel_type_impl().
FieldRegistry b_field_map private
Referenced by TransitionSystem_Gen::add_field_impl(), and TransitionSystem_Gen::field_impl().
ByproductRegistry b_byproduct_map private
Referenced by TransitionSystem_Gen::add_byproduct_impl(), TransitionSystem_Gen::byproduct_impl(), and TransitionSystem_Gen::byproducts_impl().
The documentation for this class was generated from the following files:
Core/ts/TransitionSystem_Gen.h
Core/ts/TransitionSystem_Gen.cpp