ORIGEN API: Concentrations Class Reference
Concentrations Class Reference
#include <Concentrations.h>
Container for Concentrations data.
Public Types
typedef std::shared_ptr< Concentrations > SP
typedef std::shared_ptr< const Concentrations > SCP
Public Member Functions
Concentrations ()
default constructor (default MOLE units, 0.0 cm^3 volume)
Concentrations (ConcentrationUnit units)
constructor with units (1.0 cm^3 volume)
Concentrations (NuclideSet nucset)
std::string to_string () const
Scale::Json::Value to_json () const
const NuclideSet & nuclide_set () const
return a const reference to nuclide_set
SCP_NuclideSet scp_nuclide_set () const
return a shared (read-only) nuclide_set pointer
bool has_nuclide_set () const
return whether the class has a non-null nuclide_set
void set_nuclide_set (const NuclideSet &)
set the nuclide_set (copy operation)
void get_nuclide_set (NuclideSet &) const
populate an existing NuclideSet with a copy of nuclide_set
void manageptr_nuclide_set (NuclideSet *&)
set the nuclide_set (ownership transfer)
void getptr_nuclide_set (NuclideSet const *&) const
retrieve pointer (read-only) to nuclide_set
size_t total_nuclides () const
void set_vals (double)
SCP_Vec_Dbl scp_vals () const
return a shared (read-only) vals pointer
const Vec_Dbl & vals () const
return a const reference to vals
double const * vals_array () const
return view of vals vector
size_t vals_size () const
return size of vals vector
bool has_vals () const
return whether the class has a non-null vals
void set_vals (const Vec_Dbl &)
set the vals (copy operation)
void get_vals (Vec_Dbl &) const
populate an existing Vec_Dbl with a copy of vals
void manageptr_vals (Vec_Dbl *&)
set the vals (ownership transfer)
void getptr_vals (Vec_Dbl const *&) const
retrieve pointer (read-only) to vals
void get_vals_array (size_t, double *) const
get array of vals vector (Fortran)
void set_vals_array (size_t, double *)
set vals vector from array (Fortran)
double vals_at (size_t) const
get element of vals vector by index
double lookup_val (int id, double not_found=BAD_DOUBLE) const
bool match (const Concentrations &b) const
bool approx_eq (const Concentrations &b, double tol=1e-12) const
bool set_units (ConcentrationUnit)
ConcentrationUnit units () const
bool convert_units (ConcentrationUnit, Vec_Dbl *) const
bool convert_units (ConcentrationUnit, double volume, Vec_Dbl *) const
void set_volume (double)
set the scalar volume
double volume () const
return the scalar volume
void get_volume (double &) const
void scale (double wt)
double sum () const
double sum_hm (int min_z=90, double *total_hm=nullptr) const
void normalize (double target_total=1.0)
void normalize_hm (double target_hm_total=1.0, int min_z=90)
void accumulate (const Vec_Dbl &vals, double wt=1.0)
void accumulate (size_t n, const double *vals, double wt=1.0)
bool accumulate_concs (const Vec_Int &ids, const Vec_Dbl &vals, double wt=1.0)
bool accumulate_concs (size_t, const int *, const double *, double wt=1.0)
bool accumulate_concs (const Concentrations &, double wt=1.0)
bool set_concs (const Vec_Int &ids, const Vec_Dbl &vals, double wt=1.0)
bool set_concs (size_t, const int *, const double *, double wt=1.0)
bool set_concs (const Concentrations &, double wt=1.0)
SCP_NuclideResource nuclide_resource () const
return shared (read-only) nuclide_resource resource \
bool has_nuclide_resource () const
whether this instantiation of class has the nuclide_resource resource \
void set_nuclide_resource (SCP_NuclideResource)
set a new shared (read-only) nuclide_resource resource (non-const version) \
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
void set_decay_resource (SCP_DecayResource)
set a new shared (read-only) decay_resource resource (non-const version) \
virtual int serialize (Standard::AbstractStream *stream) const
virtual int deserialize (Standard::AbstractStream *stream)
virtual unsigned long getSerializedSize () const
virtual Concentrations * getCopy () const
virtual long getUID () const
virtual std::string toString () const
Static Public Member Functions
static bool match (const Concentrations &a, const Concentrations &b)
Static Public Attributes
static const long uid = 0x96425654f6b06c5d
Protected Member Functions
bool isEqualConcentrations (const Concentrations &a) const
virtual bool isEqual (const Standard::Serializable &b) const
void canonicalize_vals ()
void canonicalize_nuclide_set ()
Protected Attributes
ConcentrationUnit b_units
SP_NuclideSet b_nuclide_set
SP_Vec_Dbl b_vals
double b_volume
SCP_NuclideResource r_nuclide_resource
SCP_DecayResource r_decay_resource
Friends
class ScaleUtils::IO::Accessor< Concentrations >
class State
class StateSet
Detailed Description
Container for Concentrations data.
The conc data container manages a set of nuclide ids and their respective values in a given set of units.
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/dc/tests/tstState.cpp, and Core/dc/tests/tstStateSet.cpp.
Member Typedef Documentation
typedef std::shared_ptr<Concentrations> SP
typedef std::shared_ptr<const Concentrations> SCP
Constructor & Destructor Documentation
Concentrations ()
default constructor (default MOLE units, 0.0 cm^3 volume)
Referenced by Concentrations::getCopy().
     : b_units( GATOMS )
     , b_nuclide_set( new NuclideSet() )
     , b_vals( new Vec_Dbl() )
     , b_volume( 0.0 )
     , r_nuclide_resource( Origen::NuclideResource::default_resource() )
     , r_decay_resource( nullptr )
 {
 }
Concentrations (ConcentrationUnit units)
constructor with units (1.0 cm^3 volume)
     : b_units( units )
     , b_nuclide_set( new NuclideSet() )
     , b_vals( new Vec_Dbl() )
     , b_volume( 0.0 )
     , r_nuclide_resource( Origen::NuclideResource::default_resource() )
     , r_decay_resource( nullptr )
 {
 }
Concentrations (NuclideSet nucset)
constructor with nuclide set (default MOLE units, 1.0 cm^3 volume) this constructor will let you pass a nuclide set where a concentrations
     : b_units( GATOMS )
     , b_nuclide_set( new NuclideSet( nucset ) )
     , b_vals( new Vec_Dbl() )
     , b_volume( 0.0 )
     , r_nuclide_resource( Origen::NuclideResource::default_resource() )
     , r_decay_resource( nullptr )
 {
 }
Member Function Documentation
std::string to_string () const
References Concentrations::to_json().
Referenced by Concentrations::toString().
 {
     return to_json().toStyledString();
 }
Json::Value to_json () const
References Concentrations::b_nuclide_set, Concentrations::b_units, Concentrations::b_volume, and Origen::convertConcUnitToPrettyString().
Referenced by Concentrations::to_string().
 {
     Json::Value root;
     root["nuclide_set"] = b_nuclide_set->to_json();
     root["units"] = convertConcUnitToPrettyString( b_units );
     root["volume"] = b_volume;
     Standard::Json::arrayToJson( root["vals"], *b_vals );
     return root;
 }
const NuclideSet & nuclide_set () const
return a const reference to nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Concentrations goes out of scope.
Examples:
Core/dc/tests/tstConcentrations.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by Concentrations::accumulate_concs(), Origen::diffConcentrations(), Material::get_concs_at(), Material::set_concs_at(), TEST(), timing_ref(), timing_ref_at(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_NuclideSet scp_nuclide_set () const
return a shared (read-only) nuclide_set pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Origen::printConcentrations_csv().
bool has_nuclide_set () const
return whether the class has a non-null nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Concentrations::total_nuclides().
void set_nuclide_set (const NuclideSet & nuclide_set)
set the nuclide_set (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstConcentrations.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), Origen::saveStateSet(), FakeFactory::StateSet_random1(), and TEST().
void get_nuclide_set (NuclideSet & nuclide_set) const
populate an existing NuclideSet with a copy of nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_nuclide_set (NuclideSet *& nuclide_set)
set the nuclide_set (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_nuclide_set (NuclideSet const *& nuclide_set) const
retrieve pointer (read-only) to nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
size_t total_nuclides () const
References Concentrations::b_nuclide_set, and Concentrations::has_nuclide_set().
Referenced by Concentrations::accumulate(), Origen::printConcentrations_csv(), and StateSetIO_s62b::write().
 {
     return has_nuclide_set() ? b_nuclide_set->total_nuclides() : 0;
 }
void set_vals (double val)
Examples:
Core/dc/tests/tstConcentrations.cpp, and Core/dc/tests/tstStateSet.cpp.
References Concentrations::b_nuclide_set, Concentrations::b_vals, and Concentrations::canonicalize_vals().
Referenced by Concentrations::accumulate(), Material::get_concs_at(), FakeFactory::newspStateSet_10nuclide(), GridView_State::permute(), StateSetIO_s61::read(), StateSetIO_s62b::read(), Concentrations::set_concs(), FakeFactory::StateSet_random1(), and TEST().
 {
     b_vals = SP_Vec_Dbl( new Vec_Dbl( b_nuclide_set->total_nuclides(), val ) );
     canonicalize_vals();
 }
SCP_Vec_Dbl scp_vals () const
return a shared (read-only) vals pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TEST().
const Vec_Dbl & vals () const
return a const reference to vals
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Concentrations goes out of scope.
Examples:
Core/dc/tests/tstConcentrations.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by Concentrations::accumulate_concs(), Origen::printConcentrations_csv(), Concentrations::scale(), Concentrations::set_units(), TEST(), timing_ref(), timing_ref_at(), and StateSetIO_bof::write().
Vec_Dbl::value_type const * vals_array () const
return view of vals vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t vals_size () const
return size of vals vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by Concentrations::accumulate_concs(), and Concentrations::approx_eq().
bool has_vals () const
return whether the class has a non-null vals
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_vals (const Vec_Dbl & vals)
set the vals (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_vals (Vec_Dbl & vals) const
populate an existing Vec_Dbl with a copy of vals
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstStateSet.cpp.
Referenced by Origen::diffConcentrations(), and TEST().
void manageptr_vals (Vec_Dbl *& vals)
set the vals (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_vals (Vec_Dbl const *& vals) const
retrieve pointer (read-only) to vals
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_vals_array (size_t , double *) const
get array of vals vector (Fortran)
void set_vals_array (size_t , double *)
set vals vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type vals_at (size_t i) const
get element of vals vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstConcentrations.cpp, Core/dc/tests/tstState.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by TEST().
double lookup_val (int id, double not_found = BAD_DOUBLE) const
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_nuclide_set, Concentrations::b_vals, and NuclideSet::NOT_FOUND().
Referenced by TEST().
 {
     size_t i = b_nuclide_set->lookup_index( id );
     if( i == NuclideSet::NOT_FOUND() ) return not_found;
     return b_vals->at( i );
 }
bool match (const Concentrations & a, const Concentrations & b) static
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_nuclide_set.
Referenced by Concentrations::approx_eq(), Concentrations::isEqualConcentrations(), State::match(), Concentrations::match(), and TEST().
 {
     return eq_sp_obj( a.b_nuclide_set, b.b_nuclide_set );
 }
bool match (const Concentrations & b) const
References Concentrations::match().
 {
     return match( *this, b );
 }
bool approx_eq (const Concentrations & b, double tol = 1e-12) const
References Concentrations::convert_units(), Origen::GATOMS, Concentrations::match(), and Concentrations::vals_size().
 {
     // quick return if not matching ids
     if( !match( b ) ) return false;
     // check values (in same units)
     Vec_Dbl vals_this( vals_size() );
     convert_units( GATOMS, &vals_this );
     Vec_Dbl vals_b( b.vals_size() );
     b.convert_units( GATOMS, &vals_b );
     return approx_eq_vec( vals_this, vals_b, tol );
 }
bool set_units (ConcentrationUnit units)
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_units, Concentrations::convert_units(), Concentrations::units(), and Concentrations::vals().
Referenced by Material::get_concs_at(), FakeFactory::newspStateSet_10nuclide(), Origen::printConcentrations_csv(), StateSetIO_s62b::read(), FakeFactory::StateSet_random1(), TEST(), and TEST_P().
 {
     SP_Vec_Dbl vals( new Vec_Dbl() );
     bool convertible = convert_units( units, &*vals );
     if( !convertible )
     {
         jDebugTaggedLine( "conversion failed!" );
     }
     b_units = units;
     b_vals = vals;
     return convertible;
 }
ConcentrationUnit units () const
Examples:
Core/dc/tests/tstStateSet.cpp.
References Concentrations::b_units.
Referenced by Concentrations::accumulate_concs(), StateSetIO_s62b::read(), Accessor< Origen::Concentrations >::read(), Concentrations::set_units(), TEST(), TEST_P(), timing_ref(), timing_ref_at(), StateSetIO_bof::write(), and StateSetIO_s62b::write().
 { return b_units; }
bool convert_units (ConcentrationUnit units, Vec_Dbl * vals) const
References Concentrations::b_volume.
Referenced by Concentrations::accumulate_concs(), Concentrations::approx_eq(), Material::set_concs_at(), and Concentrations::set_units().
 {
     return convert_units( units, b_volume, vals );
 }
bool convert_units (ConcentrationUnit units, double volume, Vec_Dbl * vals) const
References Concentrations::b_nuclide_set, Concentrations::b_units, Concentrations::b_volume, Origen::BAD_DOUBLE, ConcentrationConverter::convert_to(), Concentrations::r_decay_resource, Concentrations::r_nuclide_resource, ConcentrationConverter::set_decay_resource(), and ConcentrationConverter::set_nuclide_resource().
 {
     Require( vals != nullptr );
     ConcentrationConverter converter;
     bool convertible = true;
     converter.set_decay_resource( r_decay_resource );
     converter.set_nuclide_resource( r_nuclide_resource );
     vals->resize( b_vals->size() );
     for( size_t i = 0; i < b_vals->size(); ++i )
     {
         // if we start with garbage, don't even try to convert
         if( b_vals->at( i ) == BAD_DOUBLE )
         {
             convertible = false;
             vals->at( i ) = b_vals->at( i );
             continue;
         }
         else if( b_vals->at( i ) == 0.0 )
         {
             vals->at( i ) = 0.0;
             // don't waste time on conversion
             continue;
         }
         vals->at( i ) =
             converter.convert_to( units,
                                   b_nuclide_set->izzzaaa_at( i ),
                                   b_units,
                                   b_vals->at( i ),
                                   volume > 0.0 ? volume : b_volume );
         if( vals->at( i ) == BAD_DOUBLE ) convertible = false;
     }
     return convertible;
 }
void set_volume (double scalar)
set the scalar volume
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstConcentrations.cpp, and Core/dc/tests/tstState.cpp.
Referenced by Material::get_concs_at(), Concentrations::set_concs(), and TEST().
double volume () const
return the scalar volume
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstState.cpp.
Referenced by Concentrations::accumulate_concs(), Origen::printConcentrations_csv(), TEST(), and StateSetIO_bof::write().
void get_volume (double &) const
void scale (double wt)
References Concentrations::b_vals, Concentrations::b_volume, and Concentrations::vals().
Referenced by Concentrations::normalize().
 {
     // new data
     SP_Vec_Dbl vals( new Vec_Dbl( b_vals->size() ) );
     for( size_t i = 0; i < b_vals->size(); ++i )
     {
         vals->at( i ) = b_vals->at( i ) * wt;
     }
     // modify values
     b_vals = vals;
     // modify the volume
     if( wt != 0 ) b_volume /= wt;
 }
double sum () const
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_vals.
Referenced by Concentrations::normalize(), and TEST().
 { return ScaleSTL::sum( *b_vals ); }
double sum_hm (int min_z = 90, double * total_hm = nullptr) const
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_nuclide_set, Concentrations::b_vals, and auxiliary_erf_m::x.
Referenced by Concentrations::normalize_hm(), and TEST().
 {
     double total_hm = 0.0;
     double total = 0.0;
     for( size_t i = 0; i < b_vals->size(); ++i )
     {
         double x = b_vals->at( i );
         if( b_nuclide_set->z_at( i ) >= min_z )
         {
             total_hm += x;
         }
         total += x;
     }
     if( sum != nullptr ) *sum = total;
     return total_hm;
 }
void normalize (double target_total = 1.0)
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_volume, Concentrations::scale(), and Concentrations::sum().
Referenced by Concentrations::normalize_hm(), and TEST().
 {
     double z = sum();
     if( z != 0.0 )
     {
         b_volume /= ( z * z );
         scale( target_sum / z );
     }
 }
void normalize_hm (double target_hm_total = 1.0, int min_z = 90)
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::normalize(), and Concentrations::sum_hm().
Referenced by TEST().
 {
     double total;
     double total_hm = sum_hm( min_z, &total );
     if( total_hm > 0 ) normalize( total * target_hm / total_hm );
 }
void accumulate (const Vec_Dbl & vals, double wt = 1.0)
References Concentrations::b_vals, Concentrations::set_vals(), and Concentrations::total_nuclides().
 {
     Require( vals.size() == total_nuclides() );
     if( b_vals->size() == 0 ) set_vals( 0.0 );
     accumulate( vals.size(), &vals[0], wt );
 }
void accumulate (size_t n, const double * vals, double wt = 1.0)
References Concentrations::b_vals.
 {
     Require( n == b_vals->size() );
     // new data
     SP_Vec_Dbl temp( new Vec_Dbl( b_vals->size() ) );
     for( size_t i = 0; i < b_vals->size(); ++i )
     {
         temp->at( i ) = b_vals->at( i ) + wt * vals[i];
     }
     b_vals = temp;
 }
bool accumulate_concs (const Vec_Int & ids, const Vec_Dbl & vals, double wt = 1.0)
Examples:
Core/dc/tests/tstConcentrations.cpp.
Referenced by Concentrations::accumulate_concs(), Concentrations::set_concs(), and TEST().
 {
     Require( ids.size() == vals.size() );
     if( ids.size() == 0 ) return true;
     return accumulate_concs( ids.size(), &ids[0], &vals[0], wt );
 }
bool accumulate_concs (size_t , const int * , const double * , double wt = 1.0)
bool accumulate_concs (const Concentrations & concs, double wt = 1.0)
References Concentrations::accumulate_concs(), Concentrations::b_volume, Concentrations::convert_units(), NuclideSet::ids(), Origen::isVolumetric(), Concentrations::nuclide_set(), Concentrations::units(), Concentrations::vals(), Concentrations::vals_size(), and Concentrations::volume().
 {
     // create a new vals with units converted
     Vec_Dbl vals( concs.vals_size() );
     concs.convert_units( this->units(), &vals );
     // if volumetric we want result of this operation to be average
     // and not sum.
     bool volumetric = isVolumetric( this->units() );
     if( volumetric )
     {
         // scale up by volumes
         for( size_t i = 0; i < vals.size(); ++i ) vals[i] *= concs.volume();
         for( size_t i = 0; i < b_vals->size(); ++i ) ( *b_vals )[i] *= b_volume;
     }
     // increase this volume by weight
     b_volume += concs.volume() * wt;
     bool all_found = accumulate_concs( concs.nuclide_set().ids(), vals, wt );
     // reconstruct average
     if( volumetric )
     {
         for( size_t i = 0; i < b_vals->size(); ++i ) ( *b_vals )[i] /= b_volume;
     }
     return all_found;
 }
bool set_concs (const Vec_Int & ids, const Vec_Dbl & vals, double wt = 1.0)
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::accumulate_concs(), Concentrations::b_volume, Concentrations::set_vals(), and Concentrations::set_volume().
Referenced by TEST(), and TEST_P().
 {
     set_vals( 0.0 );
     double v = b_volume;
     bool conserved = accumulate_concs( ids, vals, wt );
     set_volume( v );
     return conserved;
 }
bool set_concs (size_t , const int * , const double * , double wt = 1.0)
bool set_concs (const Concentrations & concs, double wt = 1.0)
References Concentrations::accumulate_concs(), Concentrations::set_vals(), and Concentrations::set_volume().
 {
     set_vals( 0.0 );
     set_volume( 0.0 );
     return accumulate_concs( concs, wt );
 }
SCP_NuclideResource nuclide_resource () const
return shared (read-only) nuclide_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_nuclide_resource () const
whether this instantiation of class has the nuclide_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
void set_nuclide_resource (SCP_NuclideResource nuclide_resource)
set a new shared (read-only) nuclide_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Examples:
Core/dc/tests/tstConcentrations.cpp.
Referenced by TEST().
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
void set_decay_resource (SCP_DecayResource decay_resource)
set a new shared (read-only) decay_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Referenced by Origen::printConcentrations_csv().
int serialize (Standard::AbstractStream * stream) const virtual
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_nuclide_set, Concentrations::b_units, Concentrations::b_volume, Concentrations::getSerializedSize(), and Origen::write().
Referenced by TEST().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "writing Origen::Concentrations::uid..." );
     Standard::write( stream, Concentrations::uid );
     jDebugTaggedLine( "writing Origen::Concentrations::SerializedSize..." );
     Standard::write( stream, getSerializedSize() );
     Remember( size_t checkpoint = stream->getWriteHead() );
     jDebugTaggedLine( "writing Origen::Concentrations::b_nuclide_set..." );
     Standard::write( stream, b_nuclide_set );
     jDebugTaggedLine( "reading Origen::Concentrations::b_units..." );
     Standard::write( stream, b_units );
     jDebugTaggedLine( "writing Origen::Concentrations::b_vals..." );
     Standard::write( stream, b_vals );
     jDebugTaggedLine( "writing Origen::Concentrations::b_volume..." );
     Standard::write( stream, b_volume );
     Ensure( stream->getWriteHead() == checkpoint + getSerializedSize() );
     return 0;
 }
int deserialize (Standard::AbstractStream * stream) virtual
Examples:
Core/dc/tests/tstConcentrations.cpp.
References Concentrations::b_nuclide_set, Concentrations::b_units, Concentrations::b_volume, Concentrations::canonicalize_nuclide_set(), Concentrations::canonicalize_vals(), Concentrations::getSerializedSize(), and Origen::read().
Referenced by TEST().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "reading Origen::Concentrations::uid..." );
     int return_code = read( stream, Concentrations::uid );
     if( return_code != 0 ) return return_code;
     jDebugTaggedLine( "reading Origen::Concentrations::SerializedSize..." );
     unsigned long size;
     read( stream, size );
     size_t bytes = 0;
     jDebugTaggedLine( "reading Origen::Concentrations::b_nuclide_set..." );
     b_nuclide_set = std::make_shared<NuclideSet>();
     bytes += read( stream, b_nuclide_set );
     canonicalize_nuclide_set();
     jDebugTaggedLine( "reading Origen::Concentrations::b_units..." );
     bytes += read( stream, b_units );
     jDebugTaggedLine( "reading Origen::Concentrations::b_vals..." );
     b_vals = std::make_shared<Vec_Dbl>();
     bytes += read( stream, b_vals );
     canonicalize_vals();
     jDebugTaggedLine( "reading Origen::Concentrations::b_volume..." );
     bytes += read( stream, b_volume );
     Ensure( size == getSerializedSize() && size == bytes );
     if( size != getSerializedSize() || size != bytes ) return 1;
     return 0;
 }
unsigned long getSerializedSize () const virtual
References Concentrations::b_nuclide_set, Concentrations::b_units, and Concentrations::b_volume.
Referenced by Concentrations::deserialize(), and Concentrations::serialize().
 {
     SerialStream a;
     return Standard::bytes( &a, b_nuclide_set ) +
            Standard::bytes( &a, b_units ) + Standard::bytes( &a, b_vals ) +
            Standard::bytes( &a, b_volume );
 }
Concentrations * getCopy () const virtual
References Concentrations::Concentrations().
 {
     return new Concentrations( *this );
 }
long getUID () const virtual
References Concentrations::uid.
 { return Concentrations::uid; }
std::string toString () const virtual
References Concentrations::to_string().
 { return to_string(); }
bool isEqualConcentrations (const Concentrations & a) const protected
References Concentrations::b_units, Concentrations::b_vals, Concentrations::b_volume, and Concentrations::match().
Referenced by Concentrations::isEqual().
 {
     return match( *this, a ) && b_units == a.b_units &&
            eq_sp_vec( b_vals, a.b_vals ) && b_volume == a.b_volume;
 }
bool isEqual (const Standard::Serializable & b) const protected virtual
References Concentrations::isEqualConcentrations().
 {
     return isEqualConcentrations( static_cast<const Concentrations&>( a ) );
 }
void canonicalize_vals () protected
References Concentrations::b_nuclide_set, and Concentrations::b_volume.
Referenced by Concentrations::deserialize(), and Concentrations::set_vals().
 {
     Require( b_vals->size() == b_nuclide_set->ids_size() );
     //set uninitialized volume
     if( b_volume == 0.0 )
     {
         b_volume = 1.0;
     }
 }
void canonicalize_nuclide_set () protected
Referenced by Concentrations::deserialize().
 {
     // null op
 }
Friends And Related Function Documentation
friend class ScaleUtils::IO::Accessor< Concentrations > friend
friend class State friend
friend class StateSet friend
Member Data Documentation
const Standard::Serializable::UID uid = 0x96425654f6b06c5d static
Referenced by Concentrations::getUID().
ConcentrationUnit b_units protected
Referenced by Concentrations::convert_units(), Concentrations::deserialize(), Concentrations::getSerializedSize(), Concentrations::isEqualConcentrations(), Concentrations::serialize(), Concentrations::set_units(), Concentrations::to_json(), and Concentrations::units().
SP_NuclideSet b_nuclide_set protected
Referenced by Concentrations::canonicalize_vals(), Concentrations::convert_units(), Concentrations::deserialize(), Concentrations::getSerializedSize(), Concentrations::lookup_val(), Concentrations::match(), Accessor< Origen::Concentrations >::read(), Concentrations::serialize(), Concentrations::set_vals(), Concentrations::sum_hm(), Concentrations::to_json(), and Concentrations::total_nuclides().
SP_Vec_Dbl b_vals protected
Referenced by Concentrations::accumulate(), Concentrations::isEqualConcentrations(), Concentrations::lookup_val(), Accessor< Origen::Concentrations >::read(), Concentrations::scale(), Concentrations::set_vals(), Concentrations::sum(), and Concentrations::sum_hm().
double b_volume protected
Referenced by Concentrations::accumulate_concs(), Concentrations::canonicalize_vals(), Concentrations::convert_units(), Concentrations::deserialize(), Concentrations::getSerializedSize(), Concentrations::isEqualConcentrations(), Concentrations::normalize(), Concentrations::scale(), Concentrations::serialize(), Concentrations::set_concs(), and Concentrations::to_json().
SCP_NuclideResource r_nuclide_resource protected
Referenced by Concentrations::convert_units().
SCP_DecayResource r_decay_resource protected
Referenced by Concentrations::convert_units().
The documentation for this class was generated from the following files:
Core/dc/Concentrations.h
Core/dc/Concentrations.cpp