ORIGEN API: Core/re/tests/tstYieldResource.cpp File Reference
tstYieldResource.cpp File Reference
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <istream>
#include <sstream>
#include <string>
#include <vector>
#include "Origen/Core/Definitions.h"
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/fn/print.h"
#include "Origen/Core/re/YieldResource.h"
#include "ScaleSTL/Functions.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
Classes
class YieldResourceTester
Functions
TEST (YieldResource, BasicAccessors)
TEST (YieldResource, AllEnergy)
TEST_F (YieldResourceTester, IOFunctions)
TEST_F (YieldResourceTester, Removal)
Function Documentation
TEST (YieldResource , BasicAccessors)
Examples:
tstYieldResource.cpp.
References YieldParent::add_data(), YieldResource::add_fissionable(), YieldParent::add_fp(), YieldParent::data_at(), YieldData::energy(), YieldParent::energy_index(), YieldResource::fissionable(), YieldParent::fp_index(), YieldParent::interp_yield(), YieldParent::num_energies(), YieldData::num_yields(), and YieldData::yield_at().
TEST (YieldResource , AllEnergy)
References YieldParent::add_data(), YieldResource::add_fissionable(), and YieldResource::get_all_energies().
TEST_F (YieldResourceTester , IOFunctions)
Examples:
tstYieldResource.cpp.
References Origen::printInterpolatedYields(), Origen::printYieldEnergies(), and Origen::printYields().
TEST_F (YieldResourceTester , Removal)
References YieldParent::get_energies(), YieldParent::has_fp(), YieldParent::interp_yield(), YieldParent::num_energies(), YieldParent::num_fps(), YieldParent::remove_data_at(), YieldParent::remove_fp(), and YieldParent::set_fp_ids().