ORIGEN API: expokit Module Reference
expokit Module Reference
Expokit (University of Queensland) solver module.
Functions/Subroutines
subroutine dgcoov (x, y, n, nz, ia, ja, a)
subroutine dgpadm (ideg, m, t, H, ldh, wsp, lwsp, ipiv, iexph, ns, iflag)
subroutine dnchbv (m, t, H, ldh, y, zwsp)
subroutine dgexpv (n, nz, m, t, v, w, tol, anorm, ia, ja, a, wsp, lwsp, zwsp, lzwsp, iwsp, liwsp, itrace, iflag)
subroutine dgphiv (n, nz, m, t, u, v, w, tol, anorm, ia, ja, a, wsp, lwsp, zwsp, lzwsp, iwsp, liwsp, matvec, itrace, iflag)
Variables
integer, parameter nmax = 5000
integer, parameter nzmax = 600000
Detailed Description
Expokit (University of Queensland) solver module.
Function/Subroutine Documentation
subroutine expokit::dgcoov (real(c_double), dimension(nmax) x, real(c_double), dimension(nmax) y, integer n, integer nz, integer, dimension(nzmax), intent(in) ia, integer, dimension(nzmax), intent(in) ja, real(c_double), dimension(nzmax), intent(in) a)
Referenced by dgexpv().
   implicit none
   real(C_DOUBLE) :: x(nmax), y(nmax)
   integer :: n, nz
   integer, intent(in) :: ia(nzmax), ja(nzmax)
   real(C_DOUBLE), intent(in) :: a(nzmax)
   integer ::i, j
   do j = 1,n
      y(j) = 0.0d0
   end do
   do i = 1,nz
      y(ia(i)) = y(ia(i)) + a(i)*x(ja(i))
   end do
subroutine expokit::dgpadm (integer ideg, integer m, real(c_double) t, real(c_double), dimension(ldh,m) H, integer ldh, real(c_double), dimension(lwsp) wsp, integer lwsp, integer, dimension(m) ipiv, integer iexph, integer ns, integer iflag)
iexph : (output) number such that wsp(iexph) points to exp(tH)
Referenced by dgexpv(), and dgphiv().
       implicit none
       integer ideg, m, ldh, lwsp, iexph, ns, iflag, ipiv(m)
       real(C_DOUBLE) t, h(ldh,m), wsp(lwsp)
 !-----Purpose----------------------------------------------------------|
 !
 !     Computes exp(t*H), the matrix exponential of a general matrix in
 !     full, using the irreducible rational Pade approximation to the
 !     exponential function exp(x) = r(x) = (+/-)( I + 2*(q(x)/p(x)) ),
 !     combined with scaling-and-squaring.
 !
 !-----Arguments--------------------------------------------------------|
 !
 !     ideg      : (input) the degre of the diagonal Pade to be used.
 !                 a value of 6 is generally satisfactory.
 !
 !     m         : (input) order of H.
 !
 !     H(ldh,m)  : (input) argument matrix.
 !
 !     t         : (input) time-scale (can be < 0).
 !
 !     wsp(lwsp) : (workspace/output) lwsp .ge. 4*m*m+ideg+1.
 !
 !     ipiv(m)   : (workspace)
 !
 !>>>> iexph     : (output) number such that wsp(iexph) points to exp(tH)
 !                 i.e., exp(tH) is located at wsp(iexph ... iexph+m*m-1)
 !                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 !                 NOTE: if the routine was called with wsp(iptr),
 !                       then exp(tH) will start at wsp(iptr+iexph-1).
 !
 !     ns        : (output) number of scaling-squaring used.
 !
 !     iflag     : (output) exit flag.
 !                      0 - no problem
 !                     <0 - problem
 !
 !----------------------------------------------------------------------|
 !     Roger B. Sidje (rbs@maths.uq.edu.au)
 !     EXPOKIT: Software Package for Computing Matrix Exponentials.
 !     ACM - Transactions On Mathematical Software, 24(1):130-156, 1998
 !----------------------------------------------------------------------|
 !
       integer mm,i,j,k,ih2,ip,iq,iused,ifree,iodd,icoef,iput,iget
       real(C_DOUBLE) hnorm,scale,scale2,cp,cq
 !---  check restrictions on input parameters ...
       mm = m*m
       iflag = 0
       if ( ldh.lt.m ) iflag = -1
       if ( lwsp.lt.4*mm+ideg+1 ) iflag = -2
       if ( iflag.ne.0 ) stop 'bad sizes (in input of DGPADM)'
 !
 !---  initialise pointers ...
 !
       icoef = 1
       ih2 = icoef + (ideg+1)
       ip  = ih2 + mm
       iq  = ip + mm
       ifree = iq + mm
 !
 !---  scaling: seek ns such that ||t*H/2^ns|| < 1/2;
 !     and set scale = t/2^ns ...
 !
       do i = 1,m
          wsp(i) = 0.0d0
       enddo
       do j = 1,m
          do i = 1,m
             wsp(i) = wsp(i) + abs( h(i,j) )
          enddo
       enddo
       hnorm = 0.0d0
       do i = 1,m
          hnorm = max( hnorm,wsp(i) )
       enddo
       hnorm = abs( t*hnorm )
       if ( hnorm.eq.0.0d0 ) stop 'Error - null H in input of DGPADM.'
       ns = max( 0,int(log(hnorm)/log(2.0d0))+2 )
       scale = t / REAL(2**ns,c_double)
       scale2 = scale*scale
 !
 !---  compute Pade coefficients ...
 !
       i = ideg+1
       j = 2*ideg+1
       wsp(icoef) = 1.0d0
       do k = 1,ideg
          wsp(icoef+k) = (wsp(icoef+k-1)*REAL( i-k ,c_double))/REAL( k*(j-k), c_double )
       enddo
 !
 !---  H2 = scale2*H*H ...
 !
       call dgemm( 'n','n',m,m,m,scale2,h,ldh,h,ldh,0.0d0,wsp(ih2),m )
 !
 !---  initialize p (numerator) and q (denominator) ...
 !
       cp = wsp(icoef+ideg-1)
       cq = wsp(icoef+ideg)
       do j = 1,m
          do i = 1,m
             wsp(ip + (j-1)*m + i-1) = 0.0d0
             wsp(iq + (j-1)*m + i-1) = 0.0d0
          enddo
          wsp(ip + (j-1)*(m+1)) = cp
          wsp(iq + (j-1)*(m+1)) = cq
       enddo
 !
 !---  Apply Horner rule ...
 !
       iodd = 1
       k = ideg - 1
   100 continue
       iused = iodd*iq + (1-iodd)*ip
       call dgemm( 'n','n',m,m,m, 1.0d0,wsp(iused),m,                    &
      &             wsp(ih2),m, 0.0d0,wsp(ifree),m )
       do j = 1,m
          wsp(ifree+(j-1)*(m+1)) = wsp(ifree+(j-1)*(m+1))+wsp(icoef+k-1)
       enddo
       ip = (1-iodd)*ifree + iodd*ip
       iq = iodd*ifree + (1-iodd)*iq
       ifree = iused
       iodd = 1-iodd
       k = k-1
       if ( k.gt.0 )  goto 100
 !
 !---  Obtain (+/-)(I + 2*(p\q)) ...
 !
       if ( iodd .eq. 1 ) then
          call dgemm( 'n','n',m,m,m, scale,wsp(iq),m,                    &
      &                h,ldh, 0.0d0,wsp(ifree),m )
          iq = ifree
       else
          call dgemm( 'n','n',m,m,m, scale,wsp(ip),m,                    &
      &                h,ldh, 0.0d0,wsp(ifree),m )
          ip = ifree
       endif
       call daxpy( mm, -1.0d0,wsp(ip),1, wsp(iq),1 )
       call dgesv( m,m, wsp(iq),m, ipiv, wsp(ip),m, iflag )
       if ( iflag.ne.0 ) then
         soutline(1,*) "mn", iflag
         stop 'Problem in DGESV (within DGPADM)'
       end if
       call dscal( mm, 2.0d0, wsp(ip), 1 )
       do j = 1,m
          wsp(ip+(j-1)*(m+1)) = wsp(ip+(j-1)*(m+1)) + 1.0d0
       enddo
       iput = ip
       if ( ns.eq.0 .and. iodd.eq.1 ) then
          call dscal( mm, -1.0d0, wsp(ip), 1 )
          goto 200
       endif
 !
 !--   squaring : exp(t*H) = (exp(t*H))^(2^ns) ...
 !
       iodd = 1
       do k = 1,ns
          iget = iodd*ip + (1-iodd)*iq
          iput = (1-iodd)*ip + iodd*iq
          call dgemm( 'n','n',m,m,m, 1.0d0,wsp(iget),m, wsp(iget),m,     &
      &                0.0d0,wsp(iput),m )
          iodd = 1-iodd
       enddo
   200 continue
       iexph = iput
subroutine expokit::dnchbv (integer m, real(c_double) t, real(c_double), dimension(ldh,m) H, integer ldh, real(c_double), dimension(m) y, complex(c_double), dimension(m*(m+2)) zwsp)
Referenced by dgexpv().
       implicit none
       integer          m, ldh
       real(C_DOUBLE) t, h(ldh,m), y(m)
       complex(C_DOUBLE)       zwsp(m*(m+2))
 !-----Purpose----------------------------------------------------------|
 !
 !---  DNCHBV computes y = exp(t*H)*y using the partial fraction
 !     expansion of the uniform rational Chebyshev approximation
 !     to exp(-x) of type (14,14). H is assumed to be upper-Hessenberg.
 !     About 14-digit accuracy is expected if the matrix H is negative
 !     definite. The algorithm may behave poorly otherwise.
 !
 !-----Arguments--------------------------------------------------------|
 !
 !     m       : (input) order of the Hessenberg matrix H
 !
 !     t       : (input) time-scaling factor (can be < 0).
 !
 !     H(ldh,m): (input) upper Hessenberg matrix.
 !
 !     y(m)    : (input/output) on input the operand vector,
 !               on output the resulting vector exp(t*H)*y.
 !
 !     zwsp     : (workspace). Observe that a real(C_DOUBLE) vector of
 !               length 2*m*(m+2) can be used as well when calling this
 !               routine (thus avoiding an idle complex array elsewhere)
 !
 !----------------------------------------------------------------------|
 !     Roger B. Sidje (rbs@maths.uq.edu.au)
 !     EXPOKIT: Software Package for Computing Matrix Exponentials.
 !     ACM - Transactions On Mathematical Software, 24(1):130-156, 1998
 !----------------------------------------------------------------------|
 !
       complex(C_DOUBLE) zero
       integer ndeg, i, j, k, ip, ih, iy, iz
       parameter( ndeg=7, zero=(0.0d0,0.0d0) )
       real(C_DOUBLE) alpha0
       complex(C_DOUBLE) alpha(ndeg), theta(ndeg), tmpc
 !---  Pointers ...
       ih = 1
       iy = ih + m*m
       iz = iy + m
 !---  Coefficients and poles of the partial fraction expansion...
       alpha0  =  0.183216998528140087d-11
       alpha(1)=( 0.557503973136501826d+02,-0.204295038779771857d+03)
       alpha(2)=(-0.938666838877006739d+02, 0.912874896775456363d+02)
       alpha(3)=( 0.469965415550370835d+02,-0.116167609985818103d+02)
       alpha(4)=(-0.961424200626061065d+01,-0.264195613880262669d+01)
       alpha(5)=( 0.752722063978321642d+00, 0.670367365566377770d+00)
       alpha(6)=(-0.188781253158648576d-01,-0.343696176445802414d-01)
       alpha(7)=( 0.143086431411801849d-03, 0.287221133228814096d-03)
       theta(1)=(-0.562314417475317895d+01, 0.119406921611247440d+01)
       theta(2)=(-0.508934679728216110d+01, 0.358882439228376881d+01)
       theta(3)=(-0.399337136365302569d+01, 0.600483209099604664d+01)
       theta(4)=(-0.226978543095856366d+01, 0.846173881758693369d+01)
       theta(5)=( 0.208756929753827868d+00, 0.109912615662209418d+02)
       theta(6)=( 0.370327340957595652d+01, 0.136563731924991884d+02)
       theta(7)=( 0.889777151877331107d+01, 0.166309842834712071d+02)
 !
 !---  Accumulation of the contribution of each pole ...
 !
       do j = 1,m
          zwsp(iz+j-1) = y(j)
          y(j) = y(j)*alpha0
       enddo
       do ip = 1,ndeg
 !---     Solve each fraction using Gaussian elimination with pivoting...
          do j = 1,m
             zwsp(iy+j-1) = zwsp(iz+j-1)
             do i = 1,min( j+1,m )
                zwsp(ih+(j-1)*m+i-1) = -t*h(i,j)
             enddo
             zwsp(ih+(j-1)*m+j-1) = zwsp(ih+(j-1)*m+j-1)-theta(ip)
             do k = i,m
                zwsp(ih+(j-1)*m+k-1) = zero
             enddo
          enddo
          do i = 1,m-1
 !---        Get pivot and exchange rows ...
             if (abs(zwsp(ih+(i-1)*m+i-1)).lt.abs(zwsp(ih+(i-1)*m+i))) then
                call zswap( m-i+1, zwsp(ih+(i-1)*m+i-1),m,                &
      &                     zwsp(ih+(i-1)*m+i),m )
                call zswap( 1, zwsp(iy+i-1),1, zwsp(iy+i),1 )
             endif
 !---        Forward eliminiation ...
             tmpc = zwsp(ih+(i-1)*m+i) / zwsp(ih+(i-1)*m+i-1)
             call zaxpy( m-i, -tmpc, zwsp(ih+i*m+i-1),m, zwsp(ih+i*m+i),m )
             zwsp(iy+i) = zwsp(iy+i) - tmpc*zwsp(iy+i-1)
          enddo
 !---     Backward substitution ...
          do i = m,1,-1
             tmpc = zwsp(iy+i-1)
             do j = i+1,m
                tmpc = tmpc - zwsp(ih+(j-1)*m+i-1)*zwsp(iy+j-1)
             enddo
             zwsp(iy+i-1) = tmpc / zwsp(ih+(i-1)*m+i-1)
          enddo
 !---     Accumulate the partial result in y ...
          do j = 1,m
             y(j) = y(j) + REAL( alpha(ip)*zwsp(iy+j-1), c_double )
          enddo
       enddo
subroutine expokit::dgexpv (integer, intent(in) n, integer, intent(in) nz, integer m, real(c_double) t, real(c_double), dimension(n) v, real(c_double), dimension(n) w, real(c_double) tol, real(c_double) anorm, integer, dimension(nzmax), intent(in) ia, integer, dimension(nzmax), intent(in) ja, real(c_double), dimension(nzmax), intent(in) a, real(c_double), dimension(lwsp) wsp, integer lwsp, complex(c_double_complex), dimension(lzwsp) zwsp, integer lzwsp, integer, dimension(liwsp) iwsp, integer liwsp, integer itrace, integer iflag)
break_tol = tol break_tol = anorm*tol
References dgcoov(), dgpadm(), dnchbv(), and print.
Referenced by kernel_expokit::expokit_solver().
       implicit none
       integer :: m, lwsp, lzwsp, liwsp, itrace, iflag, iwsp(liwsp)
       real(C_DOUBLE) :: t, tol, anorm, v(n), w(n), wsp(lwsp)
       integer, intent(in) ::  n, nz, ia(nzmax), ja(nzmax)
       real(C_DOUBLE), intent(in) :: a(nzmax)
       complex(C_DOUBLE_COMPLEX) zwsp(lzwsp)
 !-----Purpose----------------------------------------------------------|
 !
 !---  DGEXPV computes w = exp(t*A)*v - for a General matrix A.
 !
 !     It does not compute the matrix exponential in isolation but
 !     instead, it computes directly the action of the exponential
 !     operator on the operand vector. This way of doing so allows
 !     for addressing large sparse problems.
 !
 !     The method used is based on Krylov subspace projection
 !     techniques and the matrix under consideration interacts only
 !     via the external routine `matvec' performing the matrix-vector
 !     product (matrix-free method).
 !
 !-----Arguments--------------------------------------------------------|
 !
 !     n      : (input) order of the principal matrix A.
 !
 !     m      : (input) maximum size for the Krylov basis.
 !
 !     t      : (input) time at wich the solution is needed (can be < 0).
 !
 !     v(n)   : (input) given operand vector.
 !
 !     w(n)   : (output) computed approximation of exp(t*A)*v.
 !
 !     tol    : (input/output) the requested accuracy tolerance on w.
 !              If on input tol=0.0d0 or tol is too small (tol.le.eps)
 !              the internal value sqrt(eps) is used, and tol is set to
 !              sqrt(eps) on output (`eps' denotes the machine epsilon).
 !              (`Happy breakdown' is assumed if h(j+1,j) .le. anorm*tol)
 !
 !     anorm  : (input) an approximation of some norm of A.
 !
 !   wsp(lwsp): (workspace) lwsp .ge. n*(m+1)+n+(m+2)^2+4*(m+2)^2+ideg+1
 !                                   +---------+-------+---------------+
 !              (actually, ideg=6)        V        H      wsp for PADE
 !
 ! iwsp(liwsp): (workspace) liwsp .ge. m+2
 !
 !     matvec : external subroutine for matrix-vector multiplication.
 !              synopsis: matvec( x, y )
 !                        real(C_DOUBLE) x(*), y(*)
 !              computes: y(1:n) <- A*x(1:n)
 !                        where A is the principal matrix.
 !
 !     itrace : (input) running mode. 0=silent, 1=print step-by-step info
 !
 !     iflag  : (output) exit flag.
 !              <0 - bad input arguments
 !               0 - no problem
 !               1 - maximum number of steps reached without convergence
 !               2 - requested tolerance was too high
 !
 !-----Accounts on the computation--------------------------------------|
 !     Upon exit, an interested user may retrieve accounts on the
 !     computations. They are located in wsp and iwsp as indicated below:
 !
 !     location  mnemonic                 description
 !     -----------------------------------------------------------------|
 !     iwsp(1) = nmult, number of matrix-vector multiplications used
 !     iwsp(2) = nexph, number of Hessenberg matrix exponential evaluated
 !     iwsp(3) = nscale, number of repeated squaring involved in Pade
 !     iwsp(4) = nstep, number of integration steps used up to completion
 !     iwsp(5) = nreject, number of rejected step-sizes
 !     iwsp(6) = ibrkflag, set to 1 if `happy breakdown' and 0 otherwise
 !     iwsp(7) = mbrkdwn, if `happy brkdown', basis-size when it occured
 !     -----------------------------------------------------------------|
 !     wsp(1)  = step_min, minimum step-size used during integration
 !     wsp(2)  = step_max, maximum step-size used during integration
 !     wsp(3)  = dummy
 !     wsp(4)  = dummy
 !     wsp(5)  = x_error, maximum among all local truncation errors
 !     wsp(6)  = s_error, global sum of local truncation errors
 !     wsp(7)  = tbrkdwn, if `happy breakdown', time when it occured
 !     wsp(8)  = t_now, integration domain successfully covered
 !     wsp(9)  = hump, i.e., max||exp(sA)||, s in [0,t] (or [t,0] if t<0)
 !     wsp(10) = ||w||/||v||, scaled norm of the solution w.
 !     -----------------------------------------------------------------|
 !     The `hump' is a measure of the conditioning of the problem. The
 !     matrix exponential is well-conditioned if hump = 1, whereas it is
 !     poorly-conditioned if hump >> 1. However the solution can still be
 !     relatively fairly accurate even when the hump is large (the hump
 !     is an upper bound), especially when the hump and the scaled norm
 !     of w [this is also computed and returned in wsp(10)] are of the
 !     same order of magnitude (further details in reference below).
 !
 !----------------------------------------------------------------------|
 !-----The following parameters may also be adjusted herein-------------|
 !
       integer mxstep, mxreject, ideg
       real(C_DOUBLE) delta, gamma
       parameter( mxstep   = 0,                                          &
      &           mxreject = 0,                                          &
      &           ideg     = 0,                                          &
      &           delta    = 1.2d0,                                      &
      &           gamma    = 0.9d0 )
 !     mxstep  : maximum allowable number of integration steps.
 !               The value 0 means an infinite number of steps.
 !
 !     mxreject: maximum allowable number of rejections at each step.
 !               The value 0 means an infinite number of rejections.
 !
 !     ideg    : the Pade approximation of type (ideg,ideg) is used as
 !               an approximation to exp(H). The value 0 switches to the
 !               uniform rational Chebyshev approximation of type (14,14)
 !
 !     delta   : local truncation error `safety factor'
 !
 !     gamma   : stepsize `shrinking factor'
 !
 !----------------------------------------------------------------------|
 !     Roger B. Sidje (rbs@maths.uq.edu.au)
 !     EXPOKIT: Software Package for Computing Matrix Exponentials.
 !     ACM - Transactions On Mathematical Software, 24(1):130-156, 1998
 !----------------------------------------------------------------------|
 !
       integer i, j, k1, mh, mx, iv, ih, j1v, ns, ifree, lfree, iexph,   &
      &        ireject,ibrkflag,mbrkdwn, nmult, nreject, nexph, nscale,  &
      &        nstep, last_percent
       real(C_DOUBLE) sgn, t_out, tbrkdwn, step_min,step_max, err_loc, &
      &                 s_error, x_error, t_now, t_new, t_step, t_old,   &
      &                 xm, beta, break_tol, p1, p2, p3, eps, rndoff,    &
      &                 vnorm, avnorm, hj1j, hij, hump, SQR1
       real(C_DOUBLE) ddot, dnrm2
 !---  check restrictions on input parameters ...
       iflag = 0
       if ( lwsp.lt.n*(m+2)+5*(m+2)**2+ideg+1 ) iflag = -1
       if ( liwsp.lt.m+2 ) iflag = -2
       if ( m.ge.n .or. m.le.0 ) iflag = -3
       if ( iflag.ne.0 ) stop 'bad sizes (in input of DGEXPV)'
 !
 !---  initialisations ...
 !
       k1 = 2
       mh = m + 2
       iv = 1
       ih = iv + n*(m+1) + n
       ifree = ih + mh*mh
       lfree = lwsp - ifree + 1
       ibrkflag = 0
       mbrkdwn  = m
       nmult    = 0
       nreject  = 0
       nexph    = 0
       nscale   = 0
       last_percent = 0
       ns = 0 !?
       t_out    = abs( t )
       tbrkdwn  = 0.0d0
       step_min = t_out
       step_max = 0.0d0
       nstep    = 0
       s_error  = 0.0d0
       x_error  = 0.0d0
       t_now    = 0.0d0
       t_new    = 0.0d0
       p1 = 4.0d0/3.0d0
     1 p2 = p1 - 1.0d0
       p3 = p2 + p2 + p2
       eps = abs( p3-1.0d0 )
       if ( eps.eq.0.0d0 ) go to 1
       if ( tol.le.eps ) tol = sqrt( eps )
       rndoff = eps*anorm
       break_tol = 1.0d-10
 !>>>  break_tol = tol
 !>>>  break_tol = anorm*tol
       sgn = sign( 1.0d0,t )
       call dcopy( n, v,1, w,1 )
       beta = dnrm2( n, w,1 )
       vnorm = beta
       hump = beta
 !
 !---  obtain the very first stepsize ...
 !
       sqr1 = sqrt( 0.1d0 )
       xm = 1.0d0/REAL( m ,c_double)
       p1 = tol*(((m+1)/2.72d0)**(m+1))*sqrt(2.0d0*3.14d0*(m+1))
       t_new = (1.0d0/anorm)*(p1/(4.0d0*beta*anorm))**xm
       p1 = 10.0d0**(nint( log10( t_new )-sqr1 )-1)
       t_new = aint( t_new/p1 + 0.55d0 ) * p1
 !
 !---  step-by-step integration ...
 !
   100 if ( t_now.ge.t_out ) goto 500
       nstep = nstep + 1
       t_step = min( t_out-t_now, t_new )
       p1 = 1.0d0/beta
       do i = 1,n
          wsp(iv + i-1) = p1*w(i)
       enddo
       do i = 1,mh*mh
          wsp(ih+i-1) = 0.0d0
       enddo
 !
 !---  Arnoldi loop ...
 !
       j1v = iv + n
       do 200 j = 1,m
          nmult = nmult + 1
          call dgcoov( wsp(j1v-n), wsp(j1v), n, nz, ia, ja, a )
          do i = 1,j
             hij = ddot( n, wsp(iv+(i-1)*n),1, wsp(j1v),1 )
             call daxpy( n, -hij, wsp(iv+(i-1)*n),1, wsp(j1v),1 )
             wsp(ih+(j-1)*mh+i-1) = hij
          enddo
          hj1j = dnrm2( n, wsp(j1v),1 )
 !---     if `happy breakdown' go straightforward at the end ...
          if ( hj1j.le.break_tol ) then
             soutline(1,*)'happy breakdown: mbrkdwn =',j,' h =',hj1j
             k1 = 0
             ibrkflag = 1
             mbrkdwn = j
             tbrkdwn = t_now
             t_step = t_out-t_now
             goto 300
          endif
          wsp(ih+(j-1)*mh+j) = hj1j
          call dscal( n, 1.0d0/hj1j, wsp(j1v),1 )
          j1v = j1v + n
   200 continue
       nmult = nmult + 1
       call dgcoov( wsp(j1v-n), wsp(j1v), n, nz, ia, ja, a )
       avnorm = dnrm2( n, wsp(j1v),1 )
 !
 !---  set 1 for the 2-corrected scheme ...
 !
   300 continue
       wsp(ih+m*mh+m+1) = 1.0d0
 !
 !---  loop while ireject<mxreject until the tolerance is reached ...
 !
       ireject = 0
   401 continue
 !
 !---  compute w = beta*V*exp(t_step*H)*e1 ...
 !
       nexph = nexph + 1
       mx = mbrkdwn + k1
       if ( ideg.ne.0 ) then
 !---     irreducible rational Pade approximation ...
          call dgpadm( ideg, mx, sgn*t_step, wsp(ih),mh,                 &
      &                wsp(ifree),lfree, iwsp, iexph, ns, iflag )
          iexph = ifree + iexph - 1
          nscale = nscale + ns
       else
 !---     uniform rational Chebyshev approximation ...
          iexph = ifree
          do i = 1,mx
             wsp(iexph+i-1) = 0.0d0
          enddo
          wsp(iexph) = 1.0d0
          call dnchbv(mx,sgn*t_step,wsp(ih),mh,wsp(iexph),zwsp(ifree+mx))
       endif
 !
 !---  error estimate ...
 !
       if ( k1.eq.0 ) then
          err_loc = tol
       else
          p1 = abs( wsp(iexph+m) )   * beta
          p2 = abs( wsp(iexph+m+1) ) * beta * avnorm
          if ( p1.gt.10.0d0*p2 ) then
             err_loc = p2
             xm = 1.0d0/REAL( m ,c_double)
          elseif ( p1.gt.p2 ) then
             err_loc = (p1*p2)/(p1-p2)
             xm = 1.0d0/REAL( m ,c_double)
          else
             err_loc = p1
             xm = 1.0d0/REAL( m-1 ,c_double)
          endif
       endif
 !
 !---  reject the step-size if the error is not acceptable ...
 !
       if ( (k1.ne.0) .and. (err_loc.gt.delta*t_step*tol) .and.          &
      &     (mxreject.eq.0 .or. ireject.lt.mxreject) ) then
          t_old = t_step
          t_step = gamma * t_step * (t_step*tol/err_loc)**xm
          p1 = 10.0d0**(nint( log10( t_step )-sqr1 )-1)
          t_step = aint( t_step/p1 + 0.55d0 ) * p1
          if ( .false. .and. itrace.ne.0 ) then
             soutline(1,*)'t_step =',t_old
             soutline(1,*)'err_loc =',err_loc
             soutline(1,*)'err_required =',delta*t_old*tol
             soutline(1,*)'stepsize rejected, stepping down to:',t_step
          endif
          ireject = ireject + 1
          nreject = nreject + 1
          if ( mxreject.ne.0 .and. ireject.gt.mxreject ) then
             soutline(1,*)"Failure in DGEXPV: ---"
             soutline(1,*)"The requested tolerance is too high."
             print*,"Rerun with a smaller value."
             iflag = 2
             return
          endif
          goto 401
       endif
 !
 !---  now update w = beta*V*exp(t_step*H)*e1 and the hump ...
 !
       mx = mbrkdwn + max( 0,k1-1 )
       call dgemv( 'n', n,mx,beta,wsp(iv),n,wsp(iexph),1,0.0d0,w,1 )
       beta = dnrm2( n, w,1 )
       hump = max( hump, beta )
 !
 !---  suggested value for the next stepsize ...
 !
       t_new = gamma * t_step * (t_step*tol/err_loc)**xm
       p1 = 10.0d0**(nint( log10( t_new )-sqr1 )-1)
       t_new = aint( t_new/p1 + 0.55d0 ) * p1
       err_loc = max( err_loc,rndoff )
 !
 !---  update the time covered ...
 !
       t_now = t_now + t_step
 !
 !---  display and keep some information ...
 !
       if ( itrace.ne.0 .and. t_now/t_out*100 > last_percent) then
          soutline(1,*)'integration',nstep,'-----------', last_percent, '% -------------'
          soutline(1,*)'scale-square =',ns
          soutline(1,*)'step_size =',t_step
          soutline(1,*)'err_loc   =',err_loc
          soutline(1,*)'next_step =',t_new
          soutline(1,*)'t =',t_now, t_out
          last_percent = last_percent + 1
       endif
       step_min = min( step_min, t_step )
       step_max = max( step_max, t_step )
       s_error = s_error + err_loc
       x_error = max( x_error, err_loc )
       if ( mxstep.eq.0 .or. nstep.lt.mxstep ) goto 100
       iflag = 1
   500 continue
       iwsp(1) = nmult
       iwsp(2) = nexph
       iwsp(3) = nscale
       iwsp(4) = nstep
       iwsp(5) = nreject
       iwsp(6) = ibrkflag
       iwsp(7) = mbrkdwn
       wsp(1)  = step_min
       wsp(2)  = step_max
       wsp(3)  = 0.0d0
       wsp(4)  = 0.0d0
       wsp(5)  = x_error
       wsp(6)  = s_error
       wsp(7)  = tbrkdwn
       wsp(8)  = sgn*t_now
       wsp(9)  = hump/vnorm
       wsp(10) = beta/vnorm
       if ( itrace.ne.0) then
         soutline(1,*) iwsp(1:7)
         soutline(1,*) wsp(1:10)
       end if
subroutine expokit::dgphiv (integer, intent(in) n, integer, intent(in) nz, integer m, real(c_double) t, real(c_double), dimension(n) u, real(c_double), dimension(n) v, real(c_double), dimension(n) w, real(c_double) tol, real(c_double) anorm, integer, dimension(nzmax), intent(in) ia, integer, dimension(nzmax), intent(in) ja, real(c_double), dimension(nzmax), intent(in) a, real(c_double), dimension(lwsp) wsp, integer lwsp, complex(c_double_complex), dimension(lzwsp) zwsp, integer lzwsp, integer, dimension(liwsp) iwsp, integer liwsp, matvec, integer itrace, integer iflag)
break_tol = tol break_tol = anorm*tol
References dgpadm(), and print.
       implicit none
       integer :: m, lwsp, lzwsp, liwsp, itrace, iflag, iwsp(liwsp)
       real(C_DOUBLE) :: t, tol, anorm, u(n), v(n), w(n), wsp(lwsp)
       integer, intent(in) ::  n, nz, ia(nzmax), ja(nzmax)
       real(C_DOUBLE), intent(in) :: a(nzmax)
       complex(C_DOUBLE_COMPLEX) zwsp(lzwsp)
 !-----Purpose----------------------------------------------------------|
 !
 !---  DGPHIV computes w = exp(t*A)v + t*phi(tA)u which is the solution
 !     of the nonhomogeneous linear ODE problem w' = Aw + u, w(0) = v.
 !     phi(z) = (exp(z)-1)/z and A is a General matrix.
 !
 !     The method used is based on Krylov subspace projection
 !     techniques and the matrix under consideration interacts only
 !     via the external routine `matvec' performing the matrix-vector
 !     product (matrix-free method).
 !
 !-----Arguments--------------------------------------------------------|
 !
 !     n      : (input) order of the principal matrix A.
 !
 !     m      : (input) maximum size for the Krylov basis.
 !
 !     t      : (input) time at wich the solution is needed (can be < 0).
 !
 !     u(n)   : (input) operand vector with respect to the phi function
 !              (forcing term of the ODE problem).
 !
 !     v(n)   : (input) operand vector with respect to the exp function
 !              (initial condition of the ODE problem).
 !
 !     w(n)   : (output) computed approximation of exp(t*A)v + t*phi(tA)u
 !
 !     tol    : (input/output) the requested accuracy tolerance on w.
 !              If on input tol=0.0d0 or tol is too small (tol.le.eps)
 !              the internal value sqrt(eps) is used, and tol is set to
 !              sqrt(eps) on output (`eps' denotes the machine epsilon).
 !              (`Happy breakdown' is assumed if h(j+1,j) .le. anorm*tol)
 !
 !     anorm  : (input) an approximation of some norm of A.
 !
 !   wsp(lwsp): (workspace) lwsp .ge. n*(m+1)+n+(m+3)^2+4*(m+3)^2+ideg+1
 !                                   +---------+-------+---------------+
 !              (actually, ideg=6)        V        H      wsp for PADE
 !
 ! iwsp(liwsp): (workspace) liwsp .ge. m+3
 !
 !     matvec : external subroutine for matrix-vector multiplication.
 !              synopsis: matvec( x, y )
 !                        double precision x(*), y(*)
 !              computes: y(1:n) <- A*x(1:n)
 !                        where A is the principal matrix.
 !
 !     itrace : (input) running mode. 0=silent, 1=print step-by-step info
 !
 !     iflag  : (output) exit flag.
 !              <0 - bad input arguments
 !               0 - no problem
 !               1 - maximum number of steps reached without convergence
 !               2 - requested tolerance was too high
 !
 !-----Accounts on the computation--------------------------------------|
 !     Upon exit, an interested user may retrieve accounts on the
 !     computations. They are located in the workspace arrays wsp and
 !     iwsp as indicated below:
 !
 !     location  mnemonic                 description
 !     -----------------------------------------------------------------|
 !     iwsp(1) = nmult, number of matrix-vector multiplications used
 !     iwsp(2) = nexph, number of Hessenberg matrix exponential evaluated
 !     iwsp(3) = nscale, number of repeated squaring involved in Pade
 !     iwsp(4) = nstep, number of integration steps used up to completion
 !     iwsp(5) = nreject, number of rejected step-sizes
 !     iwsp(6) = ibrkflag, set to 1 if `happy breakdown' and 0 otherwise
 !     iwsp(7) = mbrkdwn, if `happy brkdown', basis-size when it occured
 !     -----------------------------------------------------------------|
 !     wsp(1)  = step_min, minimum step-size used during integration
 !     wsp(2)  = step_max, maximum step-size used during integration
 !     wsp(3)  = dummy
 !     wsp(4)  = dummy
 !     wsp(5)  = x_error, maximum among all local truncation errors
 !     wsp(6)  = s_error, global sum of local truncation errors
 !     wsp(7)  = tbrkdwn, if `happy breakdown', time when it occured
 !     wsp(8)  = t_now, integration domain successfully covered
 !
 !----------------------------------------------------------------------|
 !-----The following parameters may also be adjusted herein-------------|
 !
       integer mxstep, mxreject, ideg
       real(C_DOUBLE) delta, gamma
       parameter( mxstep   = 0,   &
                  mxreject = 0,  &
                  ideg     = 6,   &
                  delta    = 1.2d0,  &
                  gamma    = 0.9d0 )
 !     mxstep  : maximum allowable number of integration steps.
 !               The value 0 means an infinite number of steps.
 !
 !     mxreject: maximum allowable number of rejections at each step.
 !               The value 0 means an infinite number of rejections.
 !
 !     ideg    : the Pade approximation of type (ideg,ideg) is used as
 !               an approximation to exp(H).
 !
 !     delta   : local truncation error `safety factor'
 !
 !     gamma   : stepsize `shrinking factor'
 !
 !----------------------------------------------------------------------|
 !     Roger B. Sidje (rbs@maths.uq.edu.au)
 !     EXPOKIT: Software Package for Computing Matrix Exponentials.
 !     ACM - Transactions On Mathematical Software, 24(1):130-156, 1998
 !----------------------------------------------------------------------|
 !
       integer i, j, k1, mh, mx, iv, ih, j1v, ns, ifree, lfree, iexph,  &
               ireject,ibrkflag,mbrkdwn, nmult, nreject, nexph, nscale,  &
               nstep, iphih, last_percent
       real(C_DOUBLE) sgn, t_out, tbrkdwn, step_min,step_max, err_loc,  &
                        s_error, x_error, t_now, t_new, t_step, t_old,  &
                        xm, beta, break_tol, p1, p2, p3, eps, rndoff,  &
                        avnorm, hj1j, hij, sqr1
       real(C_DOUBLE) ddot, dnrm2
 !---  check restrictions on input parameters ...
       iflag = 0
       if ( lwsp.lt.n*(m+3)+5*(m+3)**2+ideg+1 ) iflag = -1
       if ( liwsp.lt.m+3 ) iflag = -2
       if ( m.ge.n .or. m.le.0 ) iflag = -3
       if ( iflag.ne.0 ) stop 'bad sizes (in input of DGPHIV)'
 !
 !---  initialisations ...
 !
       k1 = 3
       mh = m + 3
       iv = 1
       ih = iv + n*(m+1) + n
       ifree = ih + mh*mh
       lfree = lwsp - ifree + 1
       ibrkflag = 0
       mbrkdwn  = m
       nmult    = 0
       nreject  = 0
       nexph    = 0
       nscale   = 0
       ns = 0 !?
       last_percent = 0
       t_out    = abs( t )
       tbrkdwn  = 0.0d0
       step_min = t_out
       step_max = 0.0d0
       nstep    = 0
       s_error  = 0.0d0
       x_error  = 0.0d0
       t_now    = 0.0d0
       t_new    = 0.0d0
       p1 = 4.0d0/3.0d0
  1    p2 = p1 - 1.0d0
       p3 = p2 + p2 + p2
       eps = abs( p3-1.0d0 )
       if ( eps.eq.0.0d0 ) go to 1
       if ( tol.le.eps ) tol = sqrt( eps )
       rndoff = eps*anorm
       break_tol = 1.0d-10
 !>>>  break_tol = tol
 !>>>  break_tol = anorm*tol
 !
 !---  step-by-step integration ...
 !
       sgn = sign( 1.0d0,t )
       sqr1 = sqrt( 0.1d0 )
       call dcopy( n, v,1, w,1 )
  100  if ( t_now.ge.t_out ) goto 500
       nmult =  nmult + 1
       call matvec( w, wsp(iv) )
       call daxpy( n, 1.0d0, u,1, wsp(iv),1 )
       beta = dnrm2( n, wsp(iv),1 )
       if ( beta.eq.0.0d0 ) goto 500
       call dscal( n, 1.0d0/beta, wsp(iv),1 )
       do i = 1,mh*mh
          wsp(ih+i-1) = 0.0d0
       enddo
       if ( nstep.eq.0 ) then
 !---     obtain the very first stepsize ...
          xm = 1.0d0/dble( m )
          p1 = tol*(((m+1)/2.72d0)**(m+1))*sqrt(2.0d0*3.14d0*(m+1))
          t_new = (1.0d0/anorm)*(p1/(4.0d0*beta*anorm))**xm
          p1 = 10.0d0**(nint( log10( t_new )-sqr1 )-1)
          t_new = aint( t_new/p1 + 0.55d0 ) * p1
       endif
       nstep = nstep + 1
       t_step = min( t_out-t_now, t_new )
 !
 !---  Arnoldi loop ...
 !
       j1v = iv + n
       do 200 j = 1,m
          nmult = nmult + 1
          call matvec( wsp(j1v-n), wsp(j1v) )
          do i = 1,j
             hij = ddot( n, wsp(iv+(i-1)*n),1, wsp(j1v),1 )
             call daxpy( n, -hij, wsp(iv+(i-1)*n),1, wsp(j1v),1 )
             wsp(ih+(j-1)*mh+i-1) = hij
          enddo
          hj1j = dnrm2( n, wsp(j1v),1 )
 !---     if `happy breakdown' go straightforward at the end ...
          if ( hj1j.le.break_tol ) then
             soutline(1,*)'happy breakdown: mbrkdwn =',j,' h =',hj1j
             k1 = 0
             ibrkflag = 1
             mbrkdwn = j
             tbrkdwn = t_now
             t_step = t_out-t_now
             goto 300
          endif
          wsp(ih+(j-1)*mh+j) = hj1j
          call dscal( n, 1.0d0/hj1j, wsp(j1v),1 )
          j1v = j1v + n
  200  continue
       nmult = nmult + 1
       call matvec( wsp(j1v-n), wsp(j1v) )
       avnorm = dnrm2( n, wsp(j1v),1 )
 !
 !---  set 1's for the 3-extended scheme ...
 !
  300  continue
       wsp(ih+mh*mbrkdwn) = 1.0d0
       wsp(ih+(m-1)*mh+m) = 0.0d0
       do i = 1,k1-1
          wsp(ih+(m+i)*mh+m+i-1) = 1.0d0
       enddo
 !
 !---  loop while ireject<mxreject until the tolerance is reached ...
 !
       ireject = 0
  401  continue
 !
 !---  compute w = beta*t_step*V*phi(t_step*H)*e1 + w
 !
       nexph = nexph + 1
 !---  irreducible rational Pade approximation ...
       mx = mbrkdwn + max( 1,k1 )
       call dgpadm( ideg, mx, sgn*t_step, wsp(ih),mh,  &
                    wsp(ifree),lfree, iwsp, iexph, ns, iflag )
       iexph = ifree + iexph - 1
       iphih = iexph + mbrkdwn*mx
       nscale = nscale + ns
       wsp(iphih+mbrkdwn)   = hj1j*wsp(iphih+mx+mbrkdwn-1)
       wsp(iphih+mbrkdwn+1) = hj1j*wsp(iphih+2*mx+mbrkdwn-1)
  402  continue
 !---  error estimate ...
       if ( k1.eq.0 ) then
          err_loc = tol
       else
          p1 = abs( wsp(iphih+m) )   * beta
          p2 = abs( wsp(iphih+m+1) ) * beta * avnorm
          if ( p1.gt.10.0d0*p2 ) then
             err_loc = p2
             xm = 1.0d0/dble( m+1 )
          elseif ( p1.gt.p2 ) then
             err_loc = (p1*p2)/(p1-p2)
             xm = 1.0d0/dble( m+1 )
          else
             err_loc = p1
             xm = 1.0d0/dble( m )
          endif
       endif
 !---  reject the step-size if the error is not acceptable ...
       if ( (k1.ne.0) .and. (err_loc.gt.delta*t_step*tol) .and.   &
            (mxreject.eq.0 .or. ireject.lt.mxreject) ) then
          t_old = t_step
          t_step = gamma * t_step * (t_step*tol/err_loc)**xm
          p1 = 10.0d0**(nint( log10( t_step )-sqr1 )-1)
          t_step = aint( t_step/p1 + 0.55d0 ) * p1
          if ( .false. .and. itrace.ne.0 ) then
             soutline(1,*)'t_step =',t_old
             soutline(1,*)'err_loc =',err_loc
             soutline(1,*)'err_required =',delta*t_old*tol
             soutline(1,*)'stepsize rejected, stepping down to:',t_step
          endif
          ireject = ireject + 1
          nreject = nreject + 1
          if ( mxreject.ne.0 .and. ireject.gt.mxreject ) then
             soutline(1,*)"Failure in DGPHIV: ---"
             soutline(1,*)"The requested tolerance is too high."
             print*,"Rerun with a smaller value."
             iflag = 2
             return
          endif
          goto 401
       endif
 !
       mx = mbrkdwn + max( 0,k1-2 )
       call dgemv( 'n', n,mx,beta,wsp(iv),n,wsp(iphih),1,1.0d0,w,1 )
 !
 !---  suggested value for the next stepsize ...
 !
       t_new = gamma * t_step * (t_step*tol/err_loc)**xm
       p1 = 10.0d0**(nint( log10( t_new )-sqr1 )-1)
       t_new = aint( t_new/p1 + 0.55d0 ) * p1
       err_loc = max( err_loc,rndoff )
 !
 !---  update the time covered ...
 !
       t_now = t_now + t_step
 !
 !---  display and keep some information ...
 !
       if ( itrace.ne.0 .and. t_now/t_out*100 > last_percent) then
          soutline(1,*)'integration',nstep,'-----------', last_percent, '% -------------'
          soutline(1,*)'scale-square =',ns
          soutline(1,*)'step_size =',t_step
          soutline(1,*)'err_loc   =',err_loc
          soutline(1,*)'next_step =',t_new
          soutline(1,*)'t =',t_now, t_out
          last_percent = last_percent + 1
       endif
       step_min = min( step_min, t_step )
       step_max = max( step_max, t_step )
       s_error = s_error + err_loc
       x_error = max( x_error, err_loc )
       if ( mxstep.eq.0 .or. nstep.lt.mxstep ) goto 100
       iflag = 1
  500  continue
       iwsp(1) = nmult
       iwsp(2) = nexph
       iwsp(3) = nscale
       iwsp(4) = nstep
       iwsp(5) = nreject
       iwsp(6) = ibrkflag
       iwsp(7) = mbrkdwn
       wsp(1)  = step_min
       wsp(2)  = step_max
       wsp(3)  = 0.0d0
       wsp(4)  = 0.0d0
       wsp(5)  = x_error
       wsp(6)  = s_error
       wsp(7)  = tbrkdwn
       wsp(8)  = sgn*t_now
Variable Documentation
integer, parameter nmax = 5000
Referenced by kernel_expokit::expokit_solver().
 integer, parameter :: nmax = 5000, nzmax = 600000
integer, parameter nzmax = 600000
Referenced by kernel_expokit::expokit_solver().