ORIGEN API: Core/ut/slmaker.cpp File Reference
slmaker.cpp File Reference
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <vector>
#include "Origen/Core/fn/populate.h"
#include "Origen/Core/fn/print.h"
#include "Origen/Core/io/DecayResourceIO.h"
#include "Origen/Core/io/LibraryIO.h"
#include "Origen/Core/io/YieldResourceIO.h"
#include "Origen/Core/dc/TransitionMatrixP.h"
#include "Standard/Interface/CommandLine.h"
Typedefs
typedef std::map< int, YieldDef > YieldDefMap_t
Functions
void print_yield_data (YieldResource &yr, YieldDefMap_t &yield_def_map, std::vector< int > &sizzzaaa_list, std::ostream &os)
float get_yield (YieldParent &yp, int izzzaaa, int k)
float choose_yield (YieldDef &yield_data, int yield_type, YieldParent &ypd, YieldParent &ypc, int izzzaaa, int k)
void get_decay_data (SP_Library lib, SP_Library new_lib)
void get_transition_data (SP_Library lib, SP_Library new_lib)
void inject_fission_yields (const YieldResource &yrf, double energy, Library *new_lib)
int main (int argc, char **argv)
Variables
const int DIRECT_STABLE_PLUS_METASTABLE = -1
const int DIRECT = 1
const int NONE = 0
const int CUMULATIVE = 2
const int SPECIAL = 3
Typedef Documentation
typedef std::map<int, YieldDef> YieldDefMap_t
Function Documentation
void print_yield_data (YieldResource & yr, YieldDefMap_t & yield_def_map, std::vector< int > & sizzzaaa_list, std::ostream & os)
References YieldParent::data_at(), YieldData::energy(), kernel_rksuite::f(), YieldResource::fissionable_at(), YieldParent::get_fp_ids(), YieldParent::id(), YieldParent::num_energies(), YieldResource::num_fissionables(), YieldParent::num_fps(), and YieldData::yield_at().
Referenced by main().
float get_yield (YieldParent & yp, int izzzaaa, int k)
References YieldParent::data_at(), YieldParent::fp_index(), YieldParent::num_energies(), and YieldData::yield_at().
Referenced by choose_yield().
float choose_yield (YieldDef & yield_data, int yield_type, YieldParent & ypd, YieldParent & ypc, int izzzaaa, int k)
References CUMULATIVE, DIRECT, DIRECT_STABLE_PLUS_METASTABLE, get_yield(), NONE, and SPECIAL.
Referenced by main().
void get_decay_data (SP_Library lib, SP_Library new_lib)
References DecayData::abund_of_lite_nuclides, DecayData::decay_constants, kernel_rksuite::f(), NuclideSet::ids(), DecayData::masses, LibraryHeader::nuclide_set(), NuclideSet::num_in_sublib(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, DecayData::recoverable_energy_values, Origen::SUBLIB_1LT, and LibraryHeader::total_nuclides().
Referenced by main().
void get_transition_data (SP_Library lib, SP_Library new_lib)
References TransitionCoeff::fission_xs(), NuclideSet::ids(), TransitionCoeff::kappa_capture(), TransitionCoeff::kappa_fission(), TransitionCoeff::loss_xs(), TransitionCoeff::matrix(), LibraryHeader::nuclide_set(), NuclideSet::num_in_sublib(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), TransitionCoeff::set_burnup(), TransitionCoeff::set_fission_xs(), TransitionCoeff::set_flux(), TransitionCoeff::set_kappa_capture(), TransitionCoeff::set_kappa_fission(), TransitionCoeff::set_loss_xs(), TransitionCoeff::set_matrix(), TransitionCoeff::set_neutron_yields(), TransitionStructure::set_num_decay_parents(), TransitionStructure::set_num_parents(), TransitionStructure::set_parent_positions(), TransitionStructure::set_transition_ids(), NuclideSet::sizzzaaa_lookup(), Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, LibraryHeader::total_nuclides(), and TransitionStructure::transition_ids().
Referenced by main().
void inject_fission_yields (const YieldResource & yrf, double energy, Library * new_lib)
References Library::definition(), TransitionCoeff::fission_xs(), YieldResource::fissionable(), NuclideSet::ids(), YieldParent::interp_yield(), TransitionCoeff::matrix(), LibraryHeader::nuclide_set(), NuclideSet::num_in_sublib(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), TransitionCoeff::set_matrix(), Library::set_transition_coeff_at(), NuclideSet::sizzzaaa_lookup(), Origen::SUBLIB_1LT, LibraryHeader::total_nuclides(), Library::transition_coeff_at(), TransitionStructure::transition_ids(), and Library::transition_structure().
Referenced by main().
int main (int argc, char ** argv)
References YieldResource::add_fissionable(), YieldResource::check(), choose_yield(), YieldParent::data_at(), YieldResource::fissionable_at(), DecayData::fissionable_nuclide_ids, YieldParent::fp_index(), get_decay_data(), get_transition_data(), YieldParent::id(), inject_fission_yields(), Origen::loadLibrary(), Origen::loadYieldResource(), YieldParent::num_energies(), YieldResource::num_fissionables(), Origen::populateLibraryHeader_YieldResource(), print_yield_data(), Origen::printYields(), Origen::saveLibrary(), Origen::saveYieldResource(), YieldResource::set_fp_ids(), YieldData::set_yield_at(), NuclideSet::sort_mass(), and SPECIAL.
Variable Documentation
const int DIRECT_STABLE_PLUS_METASTABLE = -1
Referenced by choose_yield().
const int DIRECT = 1
Referenced by choose_yield().
const int NONE = 0
Referenced by choose_yield().
const int CUMULATIVE = 2
Referenced by choose_yield().
const int SPECIAL = 3
Referenced by choose_yield(), and main().