ORIGEN API: TransitionStructure Class Reference
TransitionStructure Class Reference
#include <TransitionStructure.h>
Container for transition structure data.
Public Types
typedef std::shared_ptr< TransitionStructure > SP
typedef std::shared_ptr< const TransitionStructure > SCP
Public Member Functions
Scale::Json::Value to_json () const
std::string to_string () const
TransitionStructure ()
bool operator== (const TransitionStructure &a) const
std::string print_compare (const TransitionStructure &) const
int field_id () const
return the scalar field_id
void set_field_id (int field_id)
set the scalar field_id
size_t total_transitions () const
const Vec_Int & num_decay_parents () const
return a const reference to num_decay_parents
SCP_Vec_Int scp_num_decay_parents () const
return a shared (read-only) num_decay_parents pointer
int const * num_decay_parents_array () const
return view of num_decay_parents vector
size_t num_decay_parents_size () const
return size of num_decay_parents vector
bool has_num_decay_parents () const
return whether the class has a non-null num_decay_parents
void get_num_decay_parents (Vec_Int &) const
populate an existing Vec_Int with a copy of num_decay_parents
void getptr_num_decay_parents (Vec_Int const *&) const
retrieve pointer (read-only) to num_decay_parents
void get_num_decay_parents_array (size_t, int *) const
get array of num_decay_parents vector (Fortran)
int num_decay_parents_at (size_t) const
get element of num_decay_parents vector by index
void set_num_decay_parents (const Vec_Int &)
set the num_decay_parents (copy operation)
void manageptr_num_decay_parents (Vec_Int *&)
set the num_decay_parents (ownership transfer)
void set_num_decay_parents_array (size_t, int *)
set num_decay_parents vector from array (Fortran)
const Vec_Int & num_parents () const
return a const reference to num_parents
SCP_Vec_Int scp_num_parents () const
return a shared (read-only) num_parents pointer
int const * num_parents_array () const
return view of num_parents vector
size_t num_parents_size () const
return size of num_parents vector
bool has_num_parents () const
return whether the class has a non-null num_parents
void get_num_parents (Vec_Int &) const
populate an existing Vec_Int with a copy of num_parents
void getptr_num_parents (Vec_Int const *&) const
retrieve pointer (read-only) to num_parents
void get_num_parents_array (size_t, int *) const
get array of num_parents vector (Fortran)
int num_parents_at (size_t) const
get element of num_parents vector by index
void set_num_parents (const Vec_Int &)
set the num_parents (copy operation)
void manageptr_num_parents (Vec_Int *&)
set the num_parents (ownership transfer)
void set_num_parents_array (size_t, int *)
set num_parents vector from array (Fortran)
const Vec_Int & parent_positions () const
return a const reference to parent_positions
SCP_Vec_Int scp_parent_positions () const
return a shared (read-only) parent_positions pointer
int const * parent_positions_array () const
return view of parent_positions vector
size_t parent_positions_size () const
return size of parent_positions vector
bool has_parent_positions () const
return whether the class has a non-null parent_positions
void get_parent_positions (Vec_Int &) const
populate an existing Vec_Int with a copy of parent_positions
void getptr_parent_positions (Vec_Int const *&) const
retrieve pointer (read-only) to parent_positions
void get_parent_positions_array (size_t, int *) const
get array of parent_positions vector (Fortran)
int parent_positions_at (size_t) const
get element of parent_positions vector by index
void set_parent_positions (const Vec_Int &)
set the parent_positions (copy operation)
void manageptr_parent_positions (Vec_Int *&)
set the parent_positions (ownership transfer)
void set_parent_positions_array (size_t, int *)
set parent_positions vector from array (Fortran)
const Vec_Int & transition_ids () const
return a const reference to transition_ids
SCP_Vec_Int scp_transition_ids () const
return a shared (read-only) transition_ids pointer
int const * transition_ids_array () const
return view of transition_ids vector
size_t transition_ids_size () const
return size of transition_ids vector
bool has_transition_ids () const
return whether the class has a non-null transition_ids
void get_transition_ids (Vec_Int &) const
populate an existing Vec_Int with a copy of transition_ids
void getptr_transition_ids (Vec_Int const *&) const
retrieve pointer (read-only) to transition_ids
void get_transition_ids_array (size_t, int *) const
get array of transition_ids vector (Fortran)
int transition_ids_at (size_t) const
get element of transition_ids vector by index
void set_transition_ids (const Vec_Int &)
set the transition_ids (copy operation)
void manageptr_transition_ids (Vec_Int *&)
set the transition_ids (ownership transfer)
void set_transition_ids_array (size_t, int *)
set transition_ids vector from array (Fortran)
int serialize (Standard::AbstractStream *stream) const
int deserialize (Standard::AbstractStream *stream)
unsigned long getSerializedSize () const
Standard::Serializable * getCopy () const
virtual Standard::Serializable::UID getUID () const
std::string toString () const
Static Public Member Functions
static bool match (const TransitionStructure &, const TransitionStructure &)
Static Public Attributes
static const Standard::Serializable::UID uid = 0x99251432e5a53064
Protected Member Functions
void canonicalize_num_decay_parents ()
void canonicalize_num_parents ()
void canonicalize_parent_positions ()
void canonicalize_transition_ids ()
Protected Attributes
FieldId b_field_id
SP_Vec_Int b_num_decay_parents
SP_Vec_Int b_num_parents
SP_Vec_Int b_parent_positions
SP_Vec_Int b_transition_ids
Detailed Description
Container for transition structure data.
The TransititonStructure data container manages the description of the transitions contained in a library or portion of a library.
Examples:
tstLibrary.cpp, tstLibraryIO.cpp, tstMaterialBuffer.cpp, tstTransitionStructure.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<TransitionStructure> SP
typedef std::shared_ptr<const TransitionStructure> SCP
Constructor & Destructor Documentation
TransitionStructure ()
Referenced by TransitionStructure::getCopy().
     : b_field_id( NEUTRON_FIELD )
     , b_num_decay_parents( new Vec_Int() )
     , b_num_parents( new Vec_Int() )
     , b_parent_positions( new Vec_Int() )
     , b_transition_ids( new Vec_Int() )
 {
 }
Member Function Documentation
Json::Value to_json () const
References TransitionStructure::b_num_decay_parents, TransitionStructure::b_num_parents, TransitionStructure::b_parent_positions, TransitionStructure::b_transition_ids, and TransitionStructure::uid.
Referenced by TransitionStructure::to_string().
 {
     Json::Value root;
     root["uid"] = Json::Value::Int64( uid );
     Standard::Json::arrayToJson( root["num_decay_parents"],
                                  *b_num_decay_parents );
     Standard::Json::arrayToJson( root["num_parents"], *b_num_parents );
     Standard::Json::arrayToJson( root["parent_positions"],
                                  *b_parent_positions );
     Standard::Json::arrayToJson( root["transition_ids"], *b_transition_ids );
     return root;
 }
std::string to_string () const
References TransitionStructure::to_json().
Referenced by TransitionStructure::toString().
 {
     return to_json().toStyledString();
 }
static bool match (const TransitionStructure & , const TransitionStructure &) static
bool operator== (const TransitionStructure & a) const
References TransitionStructure::b_field_id, TransitionStructure::b_num_decay_parents, TransitionStructure::b_num_parents, TransitionStructure::b_parent_positions, TransitionStructure::b_transition_ids, TransitionStructure::field_id(), TransitionStructure::num_decay_parents(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), and TransitionStructure::transition_ids().
 {
     ORIGEN_COMPARE_SCALAR( field_id, b_field_id, a.b_field_id );
     ORIGEN_COMPARE_SP_VECTOR(
         num_decay_parents, b_num_decay_parents, a.b_num_decay_parents );
     ORIGEN_COMPARE_SP_VECTOR( num_parents, b_num_parents, a.b_num_parents );
     ORIGEN_COMPARE_SP_VECTOR(
         parent_positions, b_parent_positions, a.b_parent_positions );
     ORIGEN_COMPARE_SP_VECTOR(
         transition_ids, b_transition_ids, a.b_transition_ids );
     return true;
 }
std::string print_compare (const TransitionStructure & a) const
References TransitionStructure::b_num_decay_parents, TransitionStructure::b_num_parents, TransitionStructure::b_parent_positions, and TransitionStructure::b_transition_ids.
 {
     std::stringstream ss;
     ss << std::setw( 75 ) << "TransitionStructure" << std::endl;
     ss << std::setw( 75 ) << "=-=-=-=-=-=-=-=-=-=";
     ss << std::endl << std::endl;
     ss << std::setw( 40 ) << " " << std::setw( 10 ) << "A" << std::setw( 15 )
        << " " << std::setw( 10 ) << "B" << std::endl;
     ss << std::setw( 40 ) << " "
        << "--------------------"
        << "     "
        << "--------------------" << std::endl;
     ss << std::setw( 35 ) << "No. Parents from Decay Size:" << std::setw( 25 )
        << b_num_decay_parents->size() << std::setw( 25 )
        << a.b_num_decay_parents->size() << std::endl;
     ss << std::setw( 35 ) << "No. Parents Size:" << std::setw( 25 )
        << b_num_parents->size() << std::setw( 25 ) << a.b_num_parents->size()
        << std::endl;
     ss << std::setw( 35 ) << "Parent Positions Size:" << std::setw( 25 )
        << b_parent_positions->size() << std::setw( 25 )
        << a.b_parent_positions->size() << std::endl;
     ss << std::setw( 35 ) << "Transition IDs Size:" << std::setw( 25 )
        << b_transition_ids->size() << std::setw( 25 )
        << a.b_transition_ids->size() << std::endl;
     ss << std::endl;
     return ss.str();
 }
int field_id () const
return the scalar field_id
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Referenced by TransitionStructure::operator==().
void set_field_id (int scalar)
set the scalar field_id
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
size_t total_transitions () const
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
References TransitionStructure::b_parent_positions, and TransitionStructure::b_transition_ids.
Referenced by gtestLibrarySizes(), LibraryIO_s61::write(), LibraryIO_s62b::write(), and LibraryIO_bof::write().
 {
     Check( b_parent_positions->size() == b_transition_ids->size() );
     return b_parent_positions->size();
 }
const Vec_Int & num_decay_parents () const
return a const reference to num_decay_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionStructure goes out of scope.
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by TransitionMatrixUpdater::load(), TransitionStructure::operator==(), Library::populate_transition_matrix(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), TEST_F(), LibraryIO_s61::write(), LibraryIO_s62b::write(), and LibraryIO_bof::write().
SCP_Vec_Int scp_num_decay_parents () const
return a shared (read-only) num_decay_parents pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Int::value_type const * num_decay_parents_array () const
return view of num_decay_parents vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t num_decay_parents_size () const
return size of num_decay_parents vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), and LibraryIO_s62b::write().
bool has_num_decay_parents () const
return whether the class has a non-null num_decay_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_num_decay_parents (Vec_Int & num_decay_parents) const
populate an existing Vec_Int with a copy of num_decay_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_num_decay_parents (Vec_Int const *& num_decay_parents) const
retrieve pointer (read-only) to num_decay_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_num_decay_parents_array (size_t , int *) const
get array of num_decay_parents vector (Fortran)
Vec_Int::value_type num_decay_parents_at (size_t i) const
get element of num_decay_parents vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
void set_num_decay_parents (const Vec_Int & num_decay_parents)
set the num_decay_parents (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by LibraryBuilder::create_library(), get_transition_data(), LibraryIO_s61::read(), LibraryIO_s62b::read(), and LibraryIO_bof::read().
void manageptr_num_decay_parents (Vec_Int *& num_decay_parents)
set the num_decay_parents (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_num_decay_parents_array (size_t , int *)
set num_decay_parents vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Int & num_parents () const
return a const reference to num_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionStructure goes out of scope.
Referenced by Origen::construct_coeff_map(), get_transition_data(), inject_fission_yields(), TransitionMatrixUpdater::load(), TransitionStructure::operator==(), Library::populate_transition_matrix(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), LibraryIO_s61::write(), LibraryIO_s62b::write(), and LibraryIO_bof::write().
SCP_Vec_Int scp_num_parents () const
return a shared (read-only) num_parents pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Int::value_type const * num_parents_array () const
return view of num_parents vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t num_parents_size () const
return size of num_parents vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), and LibraryIO_s62b::write().
bool has_num_parents () const
return whether the class has a non-null num_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_num_parents (Vec_Int & num_parents) const
populate an existing Vec_Int with a copy of num_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_num_parents (Vec_Int const *& num_parents) const
retrieve pointer (read-only) to num_parents
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_num_parents_array (size_t , int *) const
get array of num_parents vector (Fortran)
Vec_Int::value_type num_parents_at (size_t i) const
get element of num_parents vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
void set_num_parents (const Vec_Int & num_parents)
set the num_parents (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstLibrary.cpp.
Referenced by LibraryBuilder::create_library(), Origen::createTransitionStructure_random1(), get_transition_data(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and TEST().
void manageptr_num_parents (Vec_Int *& num_parents)
set the num_parents (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_num_parents_array (size_t , int *)
set num_parents vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Int & parent_positions () const
return a const reference to parent_positions
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionStructure goes out of scope.
Examples:
tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), get_transition_data(), inject_fission_yields(), TransitionMatrixUpdater::load(), TransitionStructure::operator==(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), TEST(), TEST_F(), LibraryIO_s61::write(), LibraryIO_s62b::write(), and LibraryIO_bof::write().
SCP_Vec_Int scp_parent_positions () const
return a shared (read-only) parent_positions pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Int::value_type const * parent_positions_array () const
return view of parent_positions vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t parent_positions_size () const
return size of parent_positions vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
tstMaterialBuffer.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), h5_write_library_registry(), Library::populate_transition_matrix(), and LibraryIO_s62b::write().
bool has_parent_positions () const
return whether the class has a non-null parent_positions
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_parent_positions (Vec_Int & parent_positions) const
populate an existing Vec_Int with a copy of parent_positions
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_parent_positions (Vec_Int const *& parent_positions) const
retrieve pointer (read-only) to parent_positions
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_parent_positions_array (size_t , int *) const
get array of parent_positions vector (Fortran)
Vec_Int::value_type parent_positions_at (size_t i) const
get element of parent_positions vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by Library::populate_transition_matrix().
void set_parent_positions (const Vec_Int & parent_positions)
set the parent_positions (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by LibraryBuilder::create_library(), get_transition_data(), LibraryIO_s61::read(), LibraryIO_s62b::read(), and LibraryIO_bof::read().
void manageptr_parent_positions (Vec_Int *& parent_positions)
set the parent_positions (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_parent_positions_array (size_t , int *)
set parent_positions vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Int & transition_ids () const
return a const reference to transition_ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionStructure goes out of scope.
Examples:
tstLibraryIO.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by get_transition_data(), inject_fission_yields(), TransitionMatrixUpdater::load(), TransitionStructure::operator==(), scale61_fixup(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), TEST_F(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
SCP_Vec_Int scp_transition_ids () const
return a shared (read-only) transition_ids pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Int::value_type const * transition_ids_array () const
return view of transition_ids vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t transition_ids_size () const
return size of transition_ids vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), TEST_F(), and LibraryIO_s62b::write().
bool has_transition_ids () const
return whether the class has a non-null transition_ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_transition_ids (Vec_Int & transition_ids) const
populate an existing Vec_Int with a copy of transition_ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_transition_ids (Vec_Int const *& transition_ids) const
retrieve pointer (read-only) to transition_ids
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_transition_ids_array (size_t , int *) const
get array of transition_ids vector (Fortran)
Vec_Int::value_type transition_ids_at (size_t i) const
get element of transition_ids vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Library::populate_transition_matrix(), and TEST_F().
void set_transition_ids (const Vec_Int & transition_ids)
set the transition_ids (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstLibraryIO.cpp.
Referenced by LibraryBuilder::create_library(), get_transition_data(), LibraryIO_s61::read(), LibraryIO_bof::read(), LibraryIO_s62b::read(), and scale61_fixup().
void manageptr_transition_ids (Vec_Int *& transition_ids)
set the transition_ids (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_transition_ids_array (size_t , int *)
set transition_ids vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
int serialize (Standard::AbstractStream * stream) const
Examples:
tstTransitionStructure.cpp.
References TransitionStructure::b_field_id, TransitionStructure::b_num_decay_parents, TransitionStructure::b_num_parents, TransitionStructure::b_parent_positions, TransitionStructure::b_transition_ids, TransitionStructure::getSerializedSize(), and Origen::write().
Referenced by TEST().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "writing Origen::TransitionStructure::uid..." );
     Standard::write( stream, TransitionStructure::uid );
     jDebugTaggedLine(
         "writing Origen::TransitionStructure::SerializedSize..." );
     Standard::write( stream, getSerializedSize() );
     Remember( size_t checkpoint = stream->getWriteHead() );
     jDebugTaggedLine( "writing Origen::TransitionStructure::b_field_id..." );
     Standard::write( stream, b_field_id );
     jDebugTaggedLine(
         "writing Origen::TransitionStructure::b_num_decay_parents..." );
     Standard::write( stream, b_num_decay_parents );
     jDebugTaggedLine( "writing Origen::TransitionStructure::b_num_parents..." );
     Standard::write( stream, b_num_parents );
     jDebugTaggedLine(
         "writing Origen::TransitionStructure::b_parent_positions..." );
     Standard::write( stream, b_parent_positions );
     jDebugTaggedLine(
         "writing Origen::TransitionStructure::b_transition_ids..." );
     Standard::write( stream, b_transition_ids );
     Ensure( stream->getWriteHead() == checkpoint + getSerializedSize() );
     return 0;
 }
int deserialize (Standard::AbstractStream * stream)
Examples:
tstTransitionStructure.cpp.
References TransitionStructure::b_field_id, TransitionStructure::b_num_decay_parents, TransitionStructure::b_num_parents, TransitionStructure::b_parent_positions, TransitionStructure::b_transition_ids, TransitionStructure::canonicalize_num_decay_parents(), TransitionStructure::canonicalize_num_parents(), TransitionStructure::canonicalize_parent_positions(), TransitionStructure::canonicalize_transition_ids(), TransitionStructure::getSerializedSize(), and Origen::read().
Referenced by TEST().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "reading Origen::TransitionStructure::uid..." );
     int return_code = Standard::read( stream, TransitionStructure::uid );
     if( return_code != 0 ) return return_code;
     jDebugTaggedLine(
         "reading Origen::TransitionStructure::SerializedSize..." );
     unsigned long size;
     Standard::read( stream, size );
     size_t bytes = 0;
     jDebugTaggedLine( "reading Origen::TransitionStructure::b_field_id..." );
     bytes += Standard::read( stream, b_field_id );
     jDebugTaggedLine(
         "reading Origen::TransitionStructure::b_num_decay_parents..." );
     b_num_decay_parents = std::make_shared<Vec_Int>();
     bytes += Standard::read( stream, b_num_decay_parents );
     canonicalize_num_decay_parents();
     jDebugTaggedLine( "reading Origen::TransitionStructure::b_num_parents..." );
     b_num_parents = std::make_shared<Vec_Int>();
     bytes += Standard::read( stream, b_num_parents );
     canonicalize_num_parents();
     jDebugTaggedLine(
         "reading Origen::TransitionStructure::b_parent_positions..." );
     b_parent_positions = std::make_shared<Vec_Int>();
     bytes += Standard::read( stream, b_parent_positions );
     canonicalize_parent_positions();
     jDebugTaggedLine(
         "reading Origen::TransitionStructure::b_transition_ids..." );
     b_transition_ids = std::make_shared<Vec_Int>();
     bytes += Standard::read( stream, b_transition_ids );
     canonicalize_transition_ids();
     Ensure( size == getSerializedSize() && size == bytes );
     if( size != getSerializedSize() || size != bytes ) return 1;
     return 0;
 }
unsigned long getSerializedSize () const
References TransitionStructure::b_field_id, TransitionStructure::b_num_decay_parents, TransitionStructure::b_num_parents, TransitionStructure::b_parent_positions, and TransitionStructure::b_transition_ids.
Referenced by TransitionStructure::deserialize(), and TransitionStructure::serialize().
 {
     Standard::AbstractStream* a = nullptr;
     return Standard::bytes( a, b_field_id ) +
            Standard::bytes( a, b_num_decay_parents ) +
            Standard::bytes( a, b_num_parents ) +
            Standard::bytes( a, b_parent_positions ) +
            Standard::bytes( a, b_transition_ids );
 }
Standard::Serializable * getCopy () const
References TransitionStructure::TransitionStructure().
 {
     return new TransitionStructure( *this );
 }
Standard::Serializable::UID getUID () const virtual
References TransitionStructure::uid.
 {
     return TransitionStructure::uid;
 }
std::string toString () const
References TransitionStructure::to_string().
 { return to_string(); }
void canonicalize_num_decay_parents () protected
Referenced by TransitionStructure::deserialize().
 {
     // null op
 }
void canonicalize_num_parents () protected
Referenced by TransitionStructure::deserialize().
 {
     // null op
 }
void canonicalize_parent_positions () protected
Referenced by TransitionStructure::deserialize().
 {
     // null op
 }
void canonicalize_transition_ids () protected
Referenced by TransitionStructure::deserialize().
 {
     // null op
 }
Member Data Documentation
const Standard::Serializable::UID uid = 0x99251432e5a53064 static
Referenced by Library::deserialize(), TransitionStructure::getUID(), Origen_TransitionStructure_uid(), and TransitionStructure::to_json().
FieldId b_field_id protected
Referenced by TransitionStructure::deserialize(), TransitionStructure::getSerializedSize(), TransitionStructure::operator==(), and TransitionStructure::serialize().
SP_Vec_Int b_num_decay_parents protected
KD(I) is the number of parents for production of nuclide I by decay transitions, size=total_nuclides
Referenced by TransitionStructure::deserialize(), TransitionStructure::getSerializedSize(), TransitionStructure::operator==(), TransitionStructure::print_compare(), TransitionStructure::serialize(), and TransitionStructure::to_json().
SP_Vec_Int b_num_parents protected
NON0(I) is the total number of parents for nuclide I, size=total nuclides
Referenced by TransitionStructure::deserialize(), TransitionStructure::getSerializedSize(), TransitionStructure::operator==(), TransitionStructure::print_compare(), TransitionStructure::serialize(), and TransitionStructure::to_json().
SP_Vec_Int b_parent_positions protected
LOC(J) is the position in array NUCL of the parent of the transition store in position J of the compressed transition matrix (LOC starts at 1)
Referenced by TransitionStructure::deserialize(), TransitionStructure::getSerializedSize(), TransitionStructure::operator==(), TransitionStructure::print_compare(), TransitionStructure::serialize(), TransitionStructure::to_json(), and TransitionStructure::total_transitions().
SP_Vec_Int b_transition_ids protected
Reaction MT identifiers
Referenced by TransitionStructure::deserialize(), TransitionStructure::getSerializedSize(), TransitionStructure::operator==(), TransitionStructure::print_compare(), TransitionStructure::serialize(), TransitionStructure::to_json(), and TransitionStructure::total_transitions().
The documentation for this class was generated from the following files:
Core/dc/TransitionStructure.h
Core/dc/TransitionStructure.cpp