ORIGEN API: origen_neutron Module Reference
origen_neutron Module Reference
perform neutron calculations
Data Types
type origen_neutron_class
Class handling the neutron calculations.
type origen_neutron_options
options for neutron calculations printout
Functions/Subroutines
subroutine totaln (tot, array, nsteps, do_not_clear)
Called from wrneut, to sum arrays for printing column total.
Variables
character(2048), dimension(2048), private rbuffer
character buffer
integer, private rstatus
status flag
Detailed Description
perform neutron calculations
Function/Subroutine Documentation
subroutine origen_neutron::totaln (real(c_double), dimension(0:nsteps), intent(inout) tot, real(c_double), dimension(:,:), intent(in) array, integer, intent(in) nsteps, logical, intent(in) do_not_clear)
Called from wrneut, to sum arrays for printing column total.
References const::amass, origen_definitions_m::avogadro, auxiliary_erf_m::double_erf(), auxiliary::nuclide_compact(), auxiliary::output(), origen_definitions_m::pi, auxiliary::print_break(), auxiliary::print_hrule(), auxiliary::print_multigroup_table(), auxiliary::table_banner(), auxiliary::table_tail(), and auxiliary_erf_m::x.
Referenced by origen_neutron_class::order_target().
    !-----------------------------------------------
    !   D u m m y   A r g u m e n t s
    !-----------------------------------------------
    integer, intent(in) :: nsteps
    logical, intent(in) :: do_not_clear
    real(C_DOUBLE), intent(inout) :: tot(0:nsteps)
    real(C_DOUBLE), intent(in) :: array(:,:)
    !-----------------------------------------------
    !   L o c a l   V a r i a b l e s
    !-----------------------------------------------
    integer :: m
    !-----------------------------------------------
    if (.not. do_not_clear) then
      tot(0:nsteps) = 0.0d0
    end if
    do m = 0, nsteps
       tot(m) = tot(m) + sum(array(:,m+1))
    end do
    return
Variable Documentation
character(2048), dimension(2048), private rbuffer
character buffer
   character(2048), private :: rbuffer(2048)
integer, private rstatus
status flag
   integer, private :: rstatus