ORIGEN API: Nuclide Class Reference
Nuclide Class Reference abstract
#include <Nuclide.h>
Defines the nuclide interface for the TransitionSystem.
Public Types
typedef SP_Nuclide SP
strong pointer
typedef WP_Nuclide WP
weak pointer
typedef CWP_Nuclide CWP
const weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Nuclide>>
See Origen::Nuclide for details.
std::vector< WP_Transition > gains () const
Return a vector of gains producing the nuclide.
void get_gains (std::vector< WP_Transition > &gains) const
Get a vector of gains producing the nuclide.
void set_gains (std::vector< WP_Transition > gains)
Set the gains producing the nuclide.
void append_gain (WP_Transition gain)
Append gain to list of gains.
void clear_gains ()
WP_Transition gain (int channel_id, int parent_id) const
retrieve a gain
int num_gains () const
Get the number of gains producing the nuclide.
std::vector< SP_Channel > losses () const
Return a vector of losses destroying the nuclide.
void get_losses (std::vector< SP_Channel > &losses) const
Get a vector of losses destroying the nuclide.
void set_losses (std::vector< SP_Channel > losses)
Set the losses destroying the nuclide.
SP_Channel loss (int channel_id) const
return loss channel
void get_loss (int channel_id, SP_Channel &loss) const
retrieve loss channel
void set_loss (SP_Channel loss)
SP_Channel add_loss (SP_ChannelType channel_type)
add a new loss channel to the nuclide by specifying ChannelType
SP_Channel add_loss (int field_id, int reaction_mt, int decay_mode=0)
add a new loss channel by specifying raw ids
SP_Channel add_loss (SP_Field field, int reaction_mt, int decay_mode=0)
add a new loss channel with Field and raw ids
SP_Channel add_loss (int decay_mode)
add a decay loss
int num_losses () const
Get the number of losses destroying the nuclide.
CWP_TransitionSystem system () const
void get_system (WP_TransitionSystem &system) const
void set_system (WP_TransitionSystem system)
bool has_initialized_system () const
int isomeric_state () const
void get_isomeric_state (int &isomeric_state) const
void set_isomeric_state (int isomeric_state)
SP_Species species () const
void get_species (SP_Species &species) const
void set_species (SP_Species species)
bool has_initialized_species () const
double num () const
void get_num (double &num) const
void set_num (double num)
double decay_constant () const
Return the decay constant.
double loss_xs () const
Public Member Functions
virtual ~Nuclide ()
Destructor.
Protected Member Functions
Nuclide ()
Private Member Functions
virtual std::vector< WP_Transition > gains_impl () const =0
virtual void get_gains_impl (std::vector< WP_Transition > &gains) const =0
virtual void set_gains_impl (std::vector< WP_Transition > gains)=0
virtual void append_gain_impl (WP_Transition gain)=0
virtual WP_Transition gain_impl (int channel_id, int parent_id) const =0
virtual int num_gains_impl () const =0
virtual void clear_gains_impl ()=0
virtual std::vector< SP_Channel > losses_impl () const =0
virtual void get_losses_impl (std::vector< SP_Channel > &losses) const =0
virtual void set_losses_impl (std::vector< SP_Channel > losses)=0
virtual SP_Channel loss_impl (int channel_id) const =0
virtual void get_loss_impl (int channel_id, SP_Channel &loss) const =0
virtual void set_loss_impl (SP_Channel loss)=0
virtual SP_Channel add_loss_impl (SP_ChannelType channel_type)=0
virtual SP_Channel add_loss_impl (int field_id, int reaction_mt, int decay_mode=0)
virtual SP_Channel add_loss_impl (SP_Field field, int reaction_mt, int decay_mode=0)
virtual SP_Channel add_loss_impl (int decay_mode)
virtual int num_losses_impl () const =0
virtual CWP_TransitionSystem system_impl () const =0
virtual void get_system_impl (WP_TransitionSystem &system) const =0
virtual void set_system_impl (WP_TransitionSystem system)=0
virtual bool has_initialized_system_impl () const =0
virtual int isomeric_state_impl () const =0
virtual void get_isomeric_state_impl (int &isomeric_state) const =0
virtual void set_isomeric_state_impl (int isomeric_state)=0
virtual SP_Species species_impl () const =0
virtual void get_species_impl (SP_Species &species) const =0
virtual void set_species_impl (SP_Species species)=0
virtual bool has_initialized_species_impl () const =0
virtual double num_impl () const =0
virtual void get_num_impl (double &num) const =0
virtual void set_num_impl (double num)=0
virtual double decay_constant_impl () const =0
virtual double loss_xs_impl () const =0
virtual std::string name_impl () const
virtual int id_impl () const
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual bool is_initialized_impl () const
useful to chain
virtual Scale::Json::Value to_json_impl () const
useful to chain
Detailed Description
Defines the nuclide interface for the TransitionSystem.
The nuclide, in the context of the transition system, manages five main pieces of data:
identification
decay constant
total loss xs
loss channels (Channel)
gain transitions (Transition)
The nuclide also has
a strong pointer to a Species
a weak pointer to a TransitionSystem
a number of this nuclide (to calculate reaction rates)
See also
Channel, Transition, Species, TransitionSystem
Member Typedef Documentation
typedef SP_Nuclide SP
strong pointer
typedef WP_Nuclide WP
weak pointer
typedef CWP_Nuclide CWP
const weak pointer
Constructor & Destructor Documentation
~Nuclide () virtual
Destructor.
 {}
Nuclide () inline protected
 {}
Member Function Documentation
std::vector< WP_Transition > gains () const
Return a vector of gains producing the nuclide.
Returns
std::vector<WP_Transition> vector of gains.
Referenced by Nuclide_Gen::set_gains_impl().
 { return gains_impl(); }
void get_gains (std::vector< WP_Transition > & gains) const
Get a vector of gains producing the nuclide.
The user vector is overwritten with the contents.
Returns
std::vector<WP_Transition> vector of gains.
 {
     get_gains_impl( gains );
 }
void set_gains (std::vector< WP_Transition > gains)
Set the gains producing the nuclide.
The internal gains are overwritten with the contents.
Parameters
std::vector<WP_Transition> vector of gains.
 {
     set_gains_impl( gains );
 }
void append_gain (WP_Transition gain)
Append gain to list of gains.
Parameters
gain to append.
 { append_gain_impl( gain ); }
void clear_gains ()
 { clear_gains_impl(); }
Transition::WP gain (int channel_id, int parent_id) const
retrieve a gain
 {
     return gain_impl( channel_id, parent_id );
 }
int num_gains () const
Get the number of gains producing the nuclide.
Returns
int number of gains.
Referenced by Nuclide_Gen::clear_gains_impl().
 { return num_gains_impl(); }
std::vector< Channel::SP > losses () const
Return a vector of losses destroying the nuclide.
Returns
std::vector<Channel::SP> vector of losses.
Referenced by Nuclide_Gen::losses_impl().
 { return losses_impl(); }
void get_losses (std::vector< SP_Channel > & losses) const
Get a vector of losses destroying the nuclide.
The user vector is overwritten with the contents.
Returns
std::vector<Channel::SP> vector of losses.
 {
     get_losses_impl( losses );
 }
void set_losses (std::vector< SP_Channel > losses)
Set the losses destroying the nuclide.
The internal losses are overwritten with the contents.
Returns
std::vector<Channel::SP> vector of losses.
 {
     set_losses_impl( losses );
 }
Channel::SP loss (int channel_id) const
return loss channel
Referenced by Nuclide_Gen::add_loss_impl(), Nuclide_Gen::get_loss_impl(), and Nuclide_Gen::set_loss_impl().
 {
     return loss_impl( channel_id );
 }
void get_loss (int channel_id, SP_Channel & loss) const
retrieve loss channel
 {
     get_loss_impl( channel_id, loss );
 }
void set_loss (SP_Channel loss)
Referenced by Nuclide_Gen::add_loss_impl().
 { set_loss_impl( loss ); }
Channel::SP add_loss (SP_ChannelType channel_type)
add a new loss channel to the nuclide by specifying ChannelType
 {
     return add_loss_impl( channel_type );
 }
Channel::SP add_loss (int field_id, int reaction_mt, int decay_mode = 0)
add a new loss channel by specifying raw ids
 {
     return add_loss_impl( field_id, reaction_mt, decay_mode );
 }
Channel::SP add_loss (SP_Field field, int reaction_mt, int decay_mode = 0)
add a new loss channel with Field and raw ids
 {
     return add_loss_impl( field, reaction_mt, decay_mode );
 }
Channel::SP add_loss (int decay_mode)
add a decay loss
 {
     return add_loss_impl( decay_mode );
 }
int num_losses () const
Get the number of losses destroying the nuclide.
Returns
int number of losses.
 { return num_losses_impl(); }
CWP_TransitionSystem system () const
Referenced by Nuclide_Gen::has_initialized_system_impl(), and Nuclide_Gen::set_system_impl().
 { return system_impl(); }
void get_system (WP_TransitionSystem & system) const
Referenced by Channel_Gen::add_transition_impl(), and Channel_Gen::update_byproduct_transitions_impl().
 {
     get_system_impl( system );
 }
void set_system (WP_TransitionSystem system)
 {
     set_system_impl( system );
 }
bool has_initialized_system () const
Referenced by Channel_Gen::add_transition_impl().
 {
     return has_initialized_system_impl();
 }
int isomeric_state () const
Referenced by Nuclide_Gen::get_isomeric_state_impl(), and Nuclide_Gen::set_isomeric_state_impl().
 { return isomeric_state_impl(); }
void get_isomeric_state (int & isomeric_state) const
 {
     get_isomeric_state_impl( isomeric_state );
 }
void set_isomeric_state (int isomeric_state)
Referenced by Nuclide_Gen::Nuclide_Gen().
 {
     set_isomeric_state_impl( isomeric_state );
 }
Species::SP species () const
Referenced by Nuclide_Gen::has_initialized_species_impl(), and Nuclide_Gen::set_species_impl().
 { return species_impl(); }
void get_species (SP_Species & species) const
 {
     get_species_impl( species );
 }
void set_species (SP_Species species)
Referenced by Nuclide_Gen::Nuclide_Gen().
 {
     set_species_impl( species );
 }
bool has_initialized_species () const
 {
     return has_initialized_species_impl();
 }
double num () const
Referenced by Nuclide_Gen::get_num_impl(), Channel_Gen::rate_impl(), and Nuclide_Gen::set_num_impl().
 { return num_impl(); }
void get_num (double & num) const
 { get_num_impl( num ); }
void set_num (double num)
Referenced by Nuclide_Gen::Nuclide_Gen().
 { set_num_impl( num ); }
double decay_constant () const
Return the decay constant.
This total decay constant is a sum of all channel decay constants.
Returns
double decay constant (1/s)
 { return decay_constant_impl(); }
double loss_xs () const
 { return loss_xs_impl(); }
virtual std::vector<WP_Transition> gains_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_gains_impl (std::vector< WP_Transition > & gains) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_gains_impl (std::vector< WP_Transition > gains) private pure virtual
Implemented in Nuclide_Gen.
virtual void append_gain_impl (WP_Transition gain) private pure virtual
Implemented in Nuclide_Gen.
virtual WP_Transition gain_impl (int channel_id, int parent_id) const private pure virtual
Implemented in Nuclide_Gen.
virtual int num_gains_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void clear_gains_impl () private pure virtual
Implemented in Nuclide_Gen.
virtual std::vector<SP_Channel> losses_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_losses_impl (std::vector< SP_Channel > & losses) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_losses_impl (std::vector< SP_Channel > losses) private pure virtual
Implemented in Nuclide_Gen.
virtual SP_Channel loss_impl (int channel_id) const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_loss_impl (int channel_id, SP_Channel & loss) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_loss_impl (SP_Channel loss) private pure virtual
Implemented in Nuclide_Gen.
virtual SP_Channel add_loss_impl (SP_ChannelType channel_type) private pure virtual
Implemented in Nuclide_Gen.
Channel::SP add_loss_impl (int field_id, int reaction_mt, int decay_mode = 0) private virtual
References TransitionSystem::add_channel_type().
 {
     Insist( has_initialized_system(),
             "Cannot add loss directly from nuclide without TransitionSystem."
             " Need to set_system()." );
     TransitionSystem::WP ts;
     this->get_system( ts );
     ChannelType::SP channel_type =
         ts->add_channel_type( field_id, reaction_mt, decay_mode );
     return this->add_loss( channel_type );
 }
Channel::SP add_loss_impl (SP_Field field, int reaction_mt, int decay_mode = 0) private virtual
References TransitionSystem::add_channel_type().
 {
     Insist( has_initialized_system(),
             "Cannot add loss directly from nuclide without TransitionSystem."
             " Need to set_system()." );
     TransitionSystem::WP ts;
     this->get_system( ts );
     ChannelType::SP channel_type =
         ts->add_channel_type( field, reaction_mt, decay_mode );
     return this->add_loss( channel_type );
 }
Channel::SP add_loss_impl (int decay_mode) private virtual
References TransitionSystem::add_channel_type().
 {
     Insist( has_initialized_system(),
             "Cannot add loss directly from nuclide without TransitionSystem."
             " Need to set_system()." );
     TransitionSystem::WP ts;
     this->get_system( ts );
     ChannelType::SP channel_type = ts->add_channel_type( decay_mode );
     return this->add_loss( channel_type );
 }
virtual int num_losses_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual CWP_TransitionSystem system_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_system_impl (WP_TransitionSystem & system) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_system_impl (WP_TransitionSystem system) private pure virtual
Implemented in Nuclide_Gen.
bool has_initialized_system_impl () const private pure virtual
Implemented in Nuclide_Gen.
 {
     return system() != nullptr;
 }
virtual int isomeric_state_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_isomeric_state_impl (int & isomeric_state) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_isomeric_state_impl (int isomeric_state) private pure virtual
Implemented in Nuclide_Gen.
virtual SP_Species species_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_species_impl (SP_Species & species) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_species_impl (SP_Species species) private pure virtual
Implemented in Nuclide_Gen.
bool has_initialized_species_impl () const private pure virtual
Implemented in Nuclide_Gen.
 {
     return species() != nullptr;
 }
virtual double num_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual void get_num_impl (double & num) const private pure virtual
Implemented in Nuclide_Gen.
virtual void set_num_impl (double num) private pure virtual
Implemented in Nuclide_Gen.
virtual double decay_constant_impl () const private pure virtual
Implemented in Nuclide_Gen.
virtual double loss_xs_impl () const private pure virtual
Implemented in Nuclide_Gen.
std::string name_impl () const private virtual
Reimplemented from Checkable.
 {
     std::stringstream ss;
     ss << "NUCLIDE(" << id() << ")";
     return ss.str();
 }
int id_impl () const private virtual
Reimplemented from Checkable.
References Origen::BAD_INT.
 {
     if( species() == nullptr )
     {
         return BAD_INT;
     }
     else
     {
         int id = 0;
         ScaleData::Utils::join_pizzzaaa( id,
                                          0,
                                          isomeric_state(),
                                          species()->charge_number(),
                                          species()->mass_number() );
         return id;
     }
 }
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
References ORIGEN_CHECKABLE_ERROR.
 {
     bool pass = Checkable::good_impl( errors );
     if( !has_initialized_species() )
     {
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized species", pass, errors );
     }
     else
     {
         if( species()->mass_number() <= 0 )
             ORIGEN_CHECKABLE_ERROR(
                 name() << " has species with mass_number<=0", pass, errors );
         if( species()->charge_number() < 0 )
             ORIGEN_CHECKABLE_ERROR(
                 name() << " has species with charge_number<0", pass, errors );
     }
     if( isomeric_state() < 0 )
     {
         ORIGEN_CHECKABLE_ERROR(
             name() << " has isomeric_state<0 ", pass, errors );
     }
     if( !has_initialized_system() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized system", pass, errors );
     // Checks if two gains have same target AND channel
     std::vector<Transition::WP> gains = this->gains();
     std::set<std::pair<int, int>> found;
     for( size_t i = 0; i < gains.size(); ++i )
     {
         std::pair<int, int> cp_id( gains[i]->channel()->id(),
                                    gains[i]->channel()->parent()->id() );
         if( found.count( cp_id ) > 0 )
         {
             ORIGEN_CHECKABLE_ERROR(
                 name() << " has two or more instances of channel="
                        << gains[i]->channel()->name()
                        << " parent="
                        << gains[i]->channel()->parent()->name(),
                 pass,
                 errors );
         }
         else
         {
             found.insert( cp_id );
         }
     }
     return pass;
 }
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     return has_initialized_system() && has_initialized_species() &&
            Checkable::has_initialized_id();
 }
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     Json::Value json( Json::objectValue );
     json = Checkable::to_json_impl();
     json["species"] = "NULL";
     json["has_initialized_species"] = has_initialized_species();
     if( has_initialized_species() )
     {
         json["species"] = species()->to_json();
     }
     json["has_initialized_system"] = has_initialized_system();
     json["num"] = num();
     json["isomeric_state"] = isomeric_state();
     json["loss_xs"] = loss_xs();
     json["decay_constant"] = decay_constant();
     std::vector<WP_Transition> gains = this->gains();
     std::vector<std::string> names( gains.size() );
     for( size_t i = 0; i < gains.size(); ++i )
     {
         names[i] = gains[i]->name();
     }
     Standard::Json::arrayToJson( json["gains"], names );
     Json::Value jlosses( Json::arrayValue );
     std::vector<Channel::SP> losses = this->losses();
     for( size_t i = 0; i < losses.size(); ++i )
     {
         jlosses[static_cast<int>( i )] = losses[i]->to_json();
     }
     json["losses"] = jlosses;
     return json;
 }
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Nuclide.h
Core/ts/Nuclide.cpp