ORIGEN API: TransitionSystemAdapter_DecayResource Class Reference
TransitionSystemAdapter_DecayResource Class Reference
#include <TransitionSystemAdapter_DecayResource.h>
Public Member Functions
TransitionSystemAdapter_DecayResource ()
virtual ~TransitionSystemAdapter_DecayResource ()
virtual void extend (TransitionSystem *ts, bool update, const DecayResource &dr) const
Detailed Description
Examples:
tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Constructor & Destructor Documentation
TransitionSystemAdapter_DecayResource ()
 {
 }
~TransitionSystemAdapter_DecayResource () virtual
 {
 }
Member Function Documentation
void extend (TransitionSystem * ts, bool update, const DecayResource & dr) const virtual
Examples:
tstTransitionSystemAdapter_AmpxN.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
References TransitionSystem::add_channel_type(), TransitionSystem::add_nuclide(), DecayChannel::get_branch_ratio(), DecayParent::get_const_channel_map(), DecayResource::get_const_parent_map(), DecayChannel::get_const_yield_map(), DecayParent::get_decay_constant(), and TransitionSystem::populate_gains().
Referenced by TSA_DecayResourceTester::SetUp(), LibraryBuilderTester::SetUp(), and TEST_F().
 {
     std::map<int, DecayParent>::const_iterator ip;
     std::map<int, DecayChannel>::const_iterator ic;
     std::map<int, double>::const_iterator iy;
     for( ip = dr.get_const_parent_map().begin();
          ip != dr.get_const_parent_map().end();
          ip++ )
     {
         int izzzaaa = ip->first;
         const DecayParent& p = ip->second;
         double total_decay_constant = p.get_decay_constant();
         SP_Nuclide parent = ts->add_nuclide( izzzaaa );
         for( ic = p.get_const_channel_map().begin();
              ic != p.get_const_channel_map().end();
              ic++ )
         {
             int decay_mode = ic->first;
             const DecayChannel& c = ic->second;
             double decay_constant = total_decay_constant * c.get_branch_ratio();
             // skip criteria
             //            if( decay_constant < 1e-20 )continue;
             SP_ChannelType type = ts->add_channel_type( decay_mode );
             SP_Channel channel = parent->add_loss( type );
             channel->set_decay_constant( decay_constant );
             for( iy = c.get_const_yield_map().begin();
                  iy != c.get_const_yield_map().end();
                  iy++ )
             {
                 int id = iy->first;
                 double yield = iy->second;
                 // Check(c.get_yield_type() == DecayResource::ISOMERIC_YIELDS);
                 auto trans = channel->add_transition( id, yield );
             }
         }
     }
     if( update )
     {
         ts->populate_gains();
     }
 }
The documentation for this class was generated from the following files:
Manager/libld/TransitionSystemAdapter_DecayResource.h
Manager/libld/TransitionSystemAdapter_DecayResource.cpp