ORIGEN API: Core/io/tests/tstGammaResourceIO.cpp File Reference
tstGammaResourceIO.cpp File Reference
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <istream>
#include <sstream>
#include <string>
#include <vector>
#include "Origen/Core/fn/print.h"
#include "Origen/Core/io/GammaResourceIO.h"
#include "Origen/Core/io/GammaResourceIO_cimg.h"
#include "Origen/Core/re/GammaResource.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "ScaleData/Core/Utils.h"
#include "ScaleUtils/IO/Utils.h"
#include "Origen/Core/config.h"
#include "Origen/Core/TestPaths.h"
Classes
class GammaResourceData
Functions
void gnuplot_binning_output (std::string prefix, double emax, double emin, const EmissionSpectrum &em)
TEST_P (GammaResourceData, DISABLED_BinningPerformance)
INSTANTIATE_TEST_CASE_P (Ndiv, GammaResourceData,::testing::Values(1, 1e1, 1e2, 1e3, 1e4, 1e5))
TEST (GammaResourceIO, cimg)
Variables
const std::string snippet
Function Documentation
void gnuplot_binning_output (std::string prefix, double emax, double emin, const EmissionSpectrum & em)
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::print_continuous(), and EmissionSpectrum::print_discrete().
Referenced by TEST_P().
 {
     std::string dtxt( prefix + "_discrete.txt" );
     std::string ctxt( prefix + "_continuous.txt" );
     // output discrete line spectrum
     {
         std::ofstream ofs( dtxt );
         ofs << em.print_discrete();
     }
     // output continuous spectrum
     {
         std::ofstream ofs( ctxt );
         ofs << em.print_continuous();
     }
     // output driver
     {
         std::ofstream ofs( prefix + "_spectrum.gpt" );
         ofs << "set logscale xy\n";
         ofs << "set xrange [" << emin << ":" << emax << "] reverse\n";
         ofs << "plot '" << dtxt << "' u 1:2:(0):(-$2) w vectors nohead,";
         ofs << "     '" << ctxt << "' u 1:2 w l\n";
     }
 }
TEST_P (GammaResourceData , DISABLED_BinningPerformance)
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::bin(), EmissionSpectrum::create_bounds_log(), EmissionResource::emission_at(), EmissionResource::emission_size(), gnuplot_binning_output(), EmissionSpectrum::id(), Spectrum::print_bins(), and Origen::printTimingReport().
 {
     // get an energy grid
     double emax = 1e+1;
     double emin = 1e-4;
     size_t ndiv = GetParam();
     Vec_Dbl e2 = EmissionSpectrum::create_bounds_log( emax, emin, ndiv );
     Vec_Dbl b2( ndiv + 1, 0.0 );
     // request a special print of an id
     int print_id = 27060;  // 52137;
     // weighting map
     std::map<int, double> map;
     map[37094] = 1.0;
     map[92235] = 1.0;
     // running sum
     double running_sum = 0;
     for( auto entry : resource_map )
     {
         const GammaResource& resource = *entry.second;
         const std::string& path = entry.first;
         for( size_t i = 0; i < resource.emission_size(); ++i )
         {
             EmissionSpectrum em = resource.emission_at( i );
             if( em.id() == print_id )
             {
                 std::string out( path + "_" + std::to_string( em.id() ) );
                 std::cerr << "printing " << out << std::endl;
                 gnuplot_binning_output( out, emax, emin, em );
             }
             {
                 // bin with weight in map or something small
                 // if not found so is not a null op
                 double id_wt = map.count( em.id() ) > 0 ? map[em.id()] : 1e-20;
                 em.bin( e2, &b2, id_wt );
                 // check that we are always increasing the total intensity
                 double this_sum = ScaleSTL::sum( b2 );
                 jDebugLine( "  intensity sum=" << this_sum );
                 EXPECT_GT( this_sum, running_sum )
                     << " failed to increase intensity with id=" << em.id();
                 if( this_sum <= running_sum )
                 {
                     std::string out( path + "_" + std::to_string( em.id() ) );
                     jDebugLine( "   printing " << out );
                     gnuplot_binning_output( out, emax, emin, em );
                 }
                 running_sum = this_sum;
             }
         }
     }
     printTimingReport();
     // print out complete bins
     {
         std::ofstream ofs( "bins" + std::to_string( ndiv ) + ".txt" );
         ofs << Spectrum::print_bins( e2, b2 );
     }
     {
         std::ofstream ofs( "bins" + std::to_string( ndiv ) + ".gpt" );
         ofs << "set logscale xy\n";
         ofs << "set xrange [" << emin << ":" << emax << "] reverse\n";
         ofs << "plot 'bins" + std::to_string( ndiv ) + ".txt' u 1:2 w l\n";
     }
     return;
 }
INSTANTIATE_TEST_CASE_P (Ndiv , GammaResourceData , ::testing:: Values1, 1e1, 1e2, 1e3, 1e4, 1e5)
Examples:
tstGammaResourceIO.cpp.
TEST (GammaResourceIO , cimg)
Examples:
tstGammaResourceIO.cpp.
References Origen::BAD_DOUBLE, EmissionSpectrum::bin(), Spectrum::bounds_at(), EmissionSpectrum::continuous(), EmissionSpectrum::discrete(), EmissionResource::emission(), EmissionResource::emission_at(), EmissionResource::emission_size(), EmissionResource::has_emission(), EmissionSpectrum::num_continuous(), EmissionSpectrum::num_discrete(), Origen::read(), GammaResourceIO_cimg::read(), and snippet.
 {
     GammaResource resource;
     bool test_local_full = false;
     if( test_local_full )
     {
         std::string path(
             "/Users/ww5/lib/scale_dev_data/origen_data/"
             "origen.rev04.mpdkxgam.data" );
         GammaResourceIO io;
         DataContainer opts;
         bool read = io.load( resource, path, opts );
         EXPECT_TRUE( read );
     }
     else
     {
         GammaResourceIO_cimg io;
         DataContainer opts;
         std::istringstream stream( snippet );
         bool read = io.read( resource, stream, opts );
         EXPECT_TRUE( read );
     }
     EXPECT_TRUE( resource.has_emission( 4007 ) );
     EXPECT_TRUE( resource.has_emission( 11025 ) );
     EXPECT_TRUE( resource.has_emission( 92238 ) );
     EXPECT_TRUE( resource.has_emission( 58151 ) );
     EXPECT_TRUE( resource.has_emission( 1071171 ) );
     EXPECT_FALSE( resource.has_emission( 1001 ) );
     // Lines test
     {
         EmissionSpectrum emission = resource.emission( 92238 );
         EXPECT_EQ( 0, emission.num_continuous() );
         EXPECT_EQ( 17, emission.num_discrete() );
         DiscreteSpectrum lines = emission.discrete();
         EXPECT_DOUBLE_EQ( 1.0808E-02, lines.search( 3.0613E-03 ) );
         EXPECT_DOUBLE_EQ( BAD_DOUBLE, lines.search( 3.0615E-03 ) );
     }
     // Continuum test
     {
         EmissionSpectrum emission = resource.emission( 58151 );
         EXPECT_EQ( 138, emission.num_continuous() );
         EXPECT_EQ( 0, emission.num_discrete() );
         Spectrum continuous = emission.continuous();
         EXPECT_EQ( 139, continuous.bounds_size() );
         double e1 = continuous.bounds_at( 1 );
         EXPECT_FLOAT_EQ( 5.4862E+00, e1 );
         double e2 = continuous.bounds_at( 2 );
         EXPECT_FLOAT_EQ( 5.4625E+00, e2 );
         double e0 = continuous.bounds_at( 0 );
         double e0_ref = e1 + ( e1 - e2 );  // use delta to get last bound
         EXPECT_FLOAT_EQ( e0_ref, e0 );
     }
     // accumulate source between 1.0 and 0.1 MeV
     Vec_Dbl bounds( {1.0, 0.1} );
     Vec_Dbl intensity( 1, 0.0 );
     for( size_t i = 0; i < resource.emission_size(); ++i )
     {
         EmissionSpectrum emission = resource.emission_at( i );
         emission.bin( bounds, &intensity, 1.2 );
     }
 }
Variable Documentation
const std::string snippet
Examples:
tstGammaResourceIO.cpp.
Referenced by TEST().