ORIGEN API: EmissionResource Class Reference
EmissionResource Class Reference
#include <EmissionResource.h>
Public Types
typedef std::shared_ptr< EmissionResource > SP
typedef std::shared_ptr< const EmissionResource > SCP
typedef std::shared_ptr< SP_Emission > SP_Vec_SP_Emission_t
typedef std::map< int, size_t > Map_t
typedef std::shared_ptr< Map_t > SP_Map_t
Public Member Functions
size_t emission_index (int id) const
EmissionSpectrum emission (int id) const
bool add_emission (EmissionSpectrum)
bool has_emission (int id) const
EmissionSpectrum emission_at (size_t i) const
size_t emission_size () const
EnergyRange_t energy_range () const
Public Attributes
std::vector< EmissionSpectrum > b_emission
std::map< int, size_t > b_map
int b_field_id
Detailed Description
Examples:
tstEmissionResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<EmissionResource> SP
typedef std::shared_ptr<const EmissionResource> SCP
typedef std::shared_ptr<SP_Emission> SP_Vec_SP_Emission_t
typedef std::map<int, size_t> Map_t
typedef std::shared_ptr<Map_t> SP_Map_t
Member Function Documentation
size_t emission_index (int id) const
References EmissionResource::b_map, and Origen::BAD_SIZE_T.
Referenced by EmissionResource::add_emission(), EmissionResource::emission(), and EmissionResource::has_emission().
EmissionSpectrum emission (int id) const
Examples:
tstEmissionResource.cpp, and tstGammaResourceIO.cpp.
References EmissionResource::b_emission, Origen::BAD_INT, Origen::BAD_SIZE_T, and EmissionResource::emission_index().
Referenced by TEST().
bool add_emission (EmissionSpectrum em)
Examples:
tstEmissionResource.cpp.
References EmissionResource::b_emission, EmissionResource::b_map, Origen::BAD_SIZE_T, EmissionResource::emission_index(), and EmissionSpectrum::id().
Referenced by TEST().
bool has_emission (int id) const
Examples:
tstEmissionResource.cpp, and tstGammaResourceIO.cpp.
References Origen::BAD_SIZE_T, and EmissionResource::emission_index().
Referenced by TEST().
EmissionSpectrum emission_at (size_t i) const
Examples:
tstGammaResourceIO.cpp.
References EmissionResource::b_emission.
Referenced by TEST(), and TEST_P().
size_t emission_size () const
Examples:
tstGammaResourceIO.cpp.
References EmissionResource::b_emission.
Referenced by TEST(), and TEST_P().
std::pair< double, double > energy_range () const
References EmissionResource::b_emission, Origen::EMAX, and Origen::EMIN.
Member Data Documentation
std::vector<EmissionSpectrum> b_emission
Referenced by EmissionResource::add_emission(), EmissionResource::emission(), EmissionResource::emission_at(), EmissionResource::emission_size(), EmissionResource::energy_range(), and GammaResourceIO_cimg::read().
std::map<int, size_t> b_map
Referenced by EmissionResource::add_emission(), EmissionResource::emission_index(), and GammaResourceIO_cimg::read().
int b_field_id
Referenced by GammaResource::GammaResource(), and GammaResourceIO_cimg::read().
The documentation for this class was generated from the following files:
Core/re/EmissionResource.h
Core/re/EmissionResource.cpp