ORIGEN API: LibraryIO_bof Class Reference
LibraryIO_bof Class Reference
#include <LibraryIO_bof.h>
Public Member Functions
bool read (Library &obj, std::istream &stream, ScaleUtils::IO::DB opts)
The read function opens the Origen library file on the disk and pulls all of the data off and converts it from the BOF data format into the appropriate format for the library object and creates that library object. This is done for both the burn-up dependent and independent data.
bool write (const Library &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
The write function opens the objects on an Origen library and puts them into the appropriate BOF data type and adds them to the library object. Once all of the parts are added, the object is written to the file. The burnup steps are written as a separate object from the rest.
Member Function Documentation
bool read (Library & lib, std::istream & stream, ScaleUtils::IO::DB opts)
The read function opens the Origen library file on the disk and pulls all of the data off and converts it from the BOF data format into the appropriate format for the library object and creates that library object. This is done for both the burn-up dependent and independent data.
Parameters
lib - Reference to the library object into which the data will be loaded.
stream - Output stream.
opts - Object into which errors and information about the library is stored.
Returns
bool - True if read was successful. False otherwise.
All data tags are the same as the write function.
References DecayData::abund_of_lite_nuclides, Library::add_transition_coeff(), TransitionCoeff::burnup(), DecayData::decay_constants, DecayData::fissionable_nuclide_ids, Origen::get_default_kappas(), NuclideSet::ids(), DecayData::masses, LibraryHeader::nuclide_set(), Origen::populateLibraryAbundance(), Origen::populateLibraryMass(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, Origen::read(), DecayData::recoverable_energy_values, TransitionCoeff::set_burnup(), LibraryHeader::set_day_made(), Library::set_decay_data(), Library::set_definition(), TransitionCoeff::set_fission_xs(), TransitionCoeff::set_flux(), NuclideSet::set_ids(), TransitionCoeff::set_kappa_capture(), TransitionCoeff::set_kappa_fission(), TransitionCoeff::set_loss_xs(), TransitionCoeff::set_matrix(), LibraryHeader::set_month_made(), TransitionCoeff::set_neutron_yields(), LibraryHeader::set_nuclide_set(), TransitionStructure::set_num_decay_parents(), TransitionStructure::set_num_parents(), TransitionStructure::set_parent_positions(), Library::set_tag_manager(), LibraryHeader::set_title(), TransitionStructure::set_transition_ids(), Library::set_transition_structure(), LibraryHeader::set_year_made(), and Origen::version().
 {
     //
     // Insist we can read from this istream
     //
     if( !stream.good() )
     {
         opts.appendError( "Failed to open stream for reading." );
         return false;
     }
     nemesis::Timer t;
     t.start();
     // buffers
     Vec_Int ivec;
     Vec_Flt fvec;
     //
     // BOFF reader for disk to memory communications
     //
     std::stringstream errmsg;
     try
     {
         // If we don't give the BOFReader the errmsg, it writes to std::cerr,
         // which muddies up the output.
         bof::BOFReader reader( stream, errmsg );
         if( !reader.loadHeader() )
         {
             opts.appendError( "file is either corrupt or not BOF format" );
             return false;
         }
         bool check1 =
             opts.checkAppName( "ORIGEN_F33", reader.getAppName().c_str() );
         if( !check1 )
         {
             // second chance
             bool check2 =
                 opts.checkAppName( "ORIGENBL  ", reader.getAppName().c_str() );
             if( check2 )
             {
                 opts.clearErrorStack();
             }
             else
             {
                 return false;
             }
         }
         // set up version
         int appMajor = reader.getAppMajor();
         int appMinor = reader.getAppMinor();
         int appMicro = reader.getAppMicro();
         opts.set( "readAppMajor", appMajor );
         opts.set( "readAppMinor", appMinor );
         opts.set( "readAppMicro", appMicro );
         Version version( appMajor, appMinor, appMicro );
         opts.set( "readAppVersion", version.asString() );
         // This file was not written by SCALE if all these are 0.
         // This must be in some other system, e.g. a unit test of someone using
         // the ORIGEN API, so we don't enforce the versioning.
         if( !( appMajor == 0 && appMinor == 0 && appMicro == 0 ) )
         {
             bool check2 =
                 opts.checkAppVersion( version, Version( "6.2.pre-b1" ) );
             if( !check2 ) return false;
         }
         //
         // BOF Object type and byte count for use during reading
         //
         bof::BOFType objType;
         size_t objByteCount;
         //
         // expect the case object
         //
         if( !reader.nextType( objType, objByteCount ) )
         {
             std::stringstream ss;
             ss << " failed to acquire the Library BOFF object type and byte "
                   "count! ";
             throw std::istream::failure( errmsg.str() + ss.str() );
         }
         bof::BOFObject obj;
         if( !reader.read( objByteCount, obj ) )
         {
             throw std::istream::failure(
                 "Failed to read Library BOFF object data!" );
         }
         // add file endianness
         opts.set( "readFileEndian",
                   ScaleUtils::IO::EndianUtils::file_is_big_endian(
                       reader.isNativeEndian() )
                       ? "big"
                       : "little" );
         // LibraryHeader
         LibraryHeader header;
         // add ids
         {
             NuclideSet nucset;
             ::bof::read( obj, "nid", ivec );
             nucset.set_ids( ivec );
             header.set_nuclide_set( nucset );
         }
         // header title
         {
             std::string str;
             ::bof::read( obj, "ttl", str );
             header.set_title( str );
         }
         // add other parameters
         {
             int i;
             ::bof::read( obj, "ntc", i );
             ::bof::read( obj, "mon", i );
             header.set_month_made( i );
             ::bof::read( obj, "day", i );
             header.set_day_made( i );
             ::bof::read( obj, "yrm", i );
             header.set_year_made( i );
             ::bof::read( obj, "nne", i );
             ::bof::read( obj, "nfn", i );
         }
         //::IO::Accessor< ::Origen::LibraryHeader>::read(obj,header);
         lib.set_definition( header );
         // TagManager
         if( obj.contains<bof::BOFObject>( "TagManager" ) )
         {
             TagManager tag_manager;
             ::Origen::read( obj, "TagManager", tag_manager );
             lib.set_tag_manager( tag_manager );
         }
         DecayData decay_data;
         //
         // Switch over to nuclide data
         // Record #5 NFISO and nuclides ids of fissionable nuclides
         // DecayData
         ::bof::read( obj, "fni", decay_data.fissionable_nuclide_ids );
         //
         // Record #6 itot, KD  num decay parents
         // TransitionStructureData
         TransitionStructure tstruct;
         ::bof::read( obj, "nnp", ivec );
         tstruct.set_num_decay_parents( ivec );
         //
         // Record #7 itot, NON0 (all parents #)
         // TransitionStructureData
         ::bof::read( obj, "tpn", ivec );
         tstruct.set_num_parents( ivec );
         //
         // Record #8 NON, LOC (A tstruct parent points)
         // TransitionStructureData
         ::bof::read( obj, "ppl", ivec );
         tstruct.set_parent_positions( ivec );
         //
         // Record #9 NON, MT (a tstruct reaction identifiers)
         // TransitionStructureData
         ::bof::read( obj, "mtl", ivec );
         tstruct.set_transition_ids( ivec );
         lib.set_transition_structure( tstruct );
         //
         // Record #10 ITOT, DIS decay constants
         // DecayData
         ::bof::read( obj, "dcc", decay_data.decay_constants );
         //
         // Record #11 ITOT, Q (recov. energy)
         // DecayData
         ::bof::read( obj, "rev", decay_data.recoverable_energy_values );
         //
         // Record #12 ITOT, FG (Q fractions due to photons)
         // DecayData
         ::bof::read( obj, "qfp", decay_data.q_fractions_from_photons );
         //
         // Record #13 ITOT, RCG-air
         // DecayData
         ::bof::read( obj, "rfa", decay_data.rcg_for_air );
         //
         // Record #14 ITOT, RCG-water
         // DecayData
         ::bof::read( obj, "rfw", decay_data.rcg_for_water );
         //
         // Record #15 ILITE ABUND (abundances)
         //
         ::bof::read( obj, "aap", decay_data.abund_of_lite_nuclides );
         // Get the ids as SIZZZAA.
         const Vec_Int& ids = header.nuclide_set().ids();
         // NEW Record ITOT, MASSES initialize masses to A (g/mol)
         ::bof::read( obj, "mas", decay_data.masses );
         // done reading decay data
         lib.set_decay_data( decay_data );
         // Resource to load kappa-capture/kappa-fission data
         Vec_Flt ref_kappa_capture;
         Vec_Flt ref_kappa_fission;
         get_default_kappas( ids, ref_kappa_capture, ref_kappa_fission );
         //
         // Get base coefficients with fixed kappas
         //
         TransitionCoeff tcoeff_base;
         tcoeff_base.set_kappa_capture( ref_kappa_capture );
         tcoeff_base.set_kappa_fission( ref_kappa_fission );
         jDebugLine( "Starting to read burnups..." );
         //
         // Start reading burnups
         // for each burnup
         //
         for( size_t i = 0;; i++ )
         {
             //
             // Peek ahead to ensure not at eof
             //
             stream.peek();
             if( stream.good() == false ) break;
             //
             // expect the burnup object
             //
             if( !reader.nextType( objType, objByteCount ) )
             {
                 std::stringstream ss;
                 ss << " failed to acquire the Library burnup object type and "
                       "byte count! ";
                 throw std::istream::failure( errmsg.str() + ss.str() );
             }
             jDebugTaggedLine( "Extracting burnup " << i
                                                    << " with bof object type "
                                                    << ( objType + 0 )
                                                    << " and byte count "
                                                    << objByteCount );
             bof::BOFObject bob;
             if( !reader.read( objByteCount, bob ) )
             {
                 throw std::istream::failure(
                     "Failed to read Library burnup data!" );
             }
             //
             // Create a new burnup data object
             //
             TransitionCoeff tcoeff( tcoeff_base );
             //
             // Read burnup
             // #1
             float bu;
             ::bof::read( bob, "bu", bu );
             tcoeff.set_burnup( bu );
             jDebugLine( "\tburnup: " << tcoeff.burnup() );
             //
             // Read A tstruct
             // #2
             ::bof::read( bob, "ma", fvec );
             tcoeff.set_matrix( fvec );
             //
             // Read capture xs TOCAP
             // #3
             ::bof::read( bob, "tr", fvec );
             tcoeff.set_loss_xs( fvec );
             //
             // Read fission xs FISS
             // #4
             ::bof::read( bob, "fx", fvec );
             tcoeff.set_fission_xs( fvec );
             //
             // Read neutron yields GENNEU
             // #5
             ::bof::read( bob, "ny", fvec );
             tcoeff.set_neutron_yields( fvec );
             //
             // Read spectrum used to generate the library FLUX
             // #6
             ::bof::read( bob, "fl", fvec );
             tcoeff.set_flux( fvec );
             jDebugLine( "" );
             //
             // Save this burnup step
             //
             lib.add_transition_coeff( tcoeff );
         }  // loop over burnups
         // NEW Record ITOT, MASSES initialize masses to A (g/mol) or actual
         populateLibraryMass( &lib, opts );
         populateLibraryAbundance( &lib, opts );
     }
     catch( std::ios_base::failure& e )
     {
         opts.appendError( e.what() );
         return false;
     }
     t.stop();
     opts.set( "loadTime", 1000 * t.wall_clock() );
     return true;
 }
bool write (const Library & lib, std::ostream & stream, ScaleUtils::IO::DB opts)
The write function opens the objects on an Origen library and puts them into the appropriate BOF data type and adds them to the library object. Once all of the parts are added, the object is written to the file. The burnup steps are written as a separate object from the rest.
Parameters
lib - A reference to the library object to be written.
stream - Output stream.
opts - A central point for errors and information about the file and operations in this function.
Returns
- True if successful write. False otherwise.
Burnup Independent Data:
Record 1 -
"tnu" - [int] Total number of nuclides.
"nle" - [int] Number of light nuclides.
"nan" - [int] Number of actinide nuclides.
"nfp" - [int] Number of fission product nuclides.
"ntc" - [int] Total number of transitions.
"mon" - [int] Month that the library was made.
"day" - [int] Day that the library was made.
"yrm" - [int] Year that the library was made.
"nne" - [int] Number of neutron energy groups.
"nfn" - [int] Number of fissionable nuclides.
Record 2 -
"ttl" - [string] Title as found on the library header.
Record 3 -
"nid" - [array[int]] List of nuclide IDs.
Record 4 -
"TagManager" "idn" - [array[string]] List of ID tag names.
"idv" - [array[string]] List of ID tag values.
"itn" - [array[string]] List of interpolatable tag names.
"itv" - [array[double]] List of interpolatable tag values.
Record 5 -
"fni" - [array[int]] List of fissionable nuclides.
Record 6 -
"nnp" - [array[int]] List of decay parent nuclides.
Record 7 -
"tpn" - [array[int]] Complete list of parent nuclides.
Record 8 -
"ppl" - [array[int]] Location of parents, tstruct of parent positions.
Record 9 -
"mtl" - [array[int]]
Record 10 -
"dcc" - [array[float]] List of decay constants.
Record 11 -
"rev" - [array[float]] List of recoverable energies.
Record 12 -
"qfp" - [array[float]]
Record 13 -
"rfa" - [array[float]] RCG for air.
Record 14 -
"rfw" - [array[float]] RCG for water.
Record 15 -
"aap" - [array[float]] Abundances.
Burnup Dependent Data:
Record 1 -
"bu" - [float] Burnup.
Record 2 -
"ma" - [array[float]] tstruct transitions.
Record 3 -
"tr" - [array[float]] Total capture cross sections.
Record 4 -
"fx" - [array[float]] Fission cross sections.
Record 5 -
"ny" - [array[float]] Neutron yields.
Record 6 -
"fl" - [array[float]] Flux spectrum used to generate the library.
References DecayData::abund_of_lite_nuclides, TransitionCoeff::burnup(), LibraryHeader::day_made(), DecayData::decay_constants, Library::decay_data(), Library::definition(), TransitionCoeff::fission_xs(), DecayData::fissionable_nuclide_ids, TransitionCoeff::flux(), TransitionCoeff::flux_size(), NuclideSet::ids(), TransitionCoeff::loss_xs(), DecayData::masses, TransitionCoeff::matrix(), LibraryHeader::month_made(), TransitionCoeff::neutron_yields(), LibraryHeader::nuclide_set(), TransitionStructure::num_decay_parents(), TransitionStructure::num_parents(), TransitionStructure::parent_positions(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, DecayData::recoverable_energy_values, Origen::setAppVersionWrite(), Library::tag_manager(), LibraryHeader::title(), TransitionStructure::total_transitions(), Library::transition_coeff_at(), Library::transition_coeff_size(), TransitionStructure::transition_ids(), Library::transition_structure(), Origen::write(), and LibraryHeader::year_made().
 {
     //
     // Insist we can write to this stream
     //
     if( !stream.good() )
     {
         opts.appendError( "Failed to open stream for writing." );
         return false;
     }
     nemesis::Timer t;
     t.start();
     const LibraryHeader& header = lib.definition();
     const TagManager& tag_manager = lib.tag_manager();
     const DecayData& decay_data = lib.decay_data();
     const TransitionStructure& tstruct = lib.transition_structure();
     size_t ntc = tstruct.total_transitions();
     size_t nne = 0;
     if( lib.transition_coeff_size() > 0 )
     {
         nne = lib.transition_coeff_at( 0 ).flux_size();
     }
     size_t nfn = decay_data.fissionable_nuclide_ids.size();
     // whether to append
     bool append = opts.get( "append", false );
     if( append )
     {
         jDebugLine(
             "LibraryIO_bof is appending data because data already exists" );
     }
     else
     {
         jDebugLine(
             "LibraryIO_bof is not appending data because it either doesn't "
             "exist or wasn't asked for" );
     }
     bof::BOFWriter writer( stream, append );
     if( !append )
     {
         //
         // set application name and version information
         //
         setAppVersionWrite( writer, opts, "ORIGEN_F33" );
         // add file endianness
         opts.set( "wroteFileEndian",
                   ScaleUtils::IO::EndianUtils::system_is_big_endian()
                       ? "big"
                       : "little" );
         if( !writer.writeHeader() )
         {
             opts.appendError( "Could not write Origen::LibraryIO header." );
             return false;
         }
     }
     bof::BOFObject obj;
     if( !append )
     {
         //
         // Record #1 itot, ilite, ifp, iact, NON, nmonth, nday, nyear,
         //    nfluxgrp, nfiso
         //
         //
         // Write record content
         //
         obj.add( "ntc", bof::bof_int( ntc ) );
         obj.add( "mon", bof::bof_int( header.month_made() ) );
         obj.add( "day", bof::bof_int( header.day_made() ) );
         obj.add( "yrm", bof::bof_int( header.year_made() ) );
         obj.add( "nne", bof::bof_int( nne ) );
         obj.add( "nfn", bof::bof_int( nfn ) );
         //
         // Record #2 NTI titles
         //
         obj.add( "ttl", bof::BOFString( header.title() ) );
         //
         // Record #3 nuclide ids
         //
         ::bof::write( obj, "nid", header.nuclide_set().ids() );
         //
         // Record #4 Tag Manager
         //
         ::Origen::write( obj, "TagManager", tag_manager );
         //
         // Record #5 nuclide ids of fissionable nuclides
         //
         ::bof::write( obj, "fni", decay_data.fissionable_nuclide_ids );
         //
         // Record #6 decay parents
         //
         ::bof::write( obj, "nnp", tstruct.num_decay_parents() );
         //
         // Record #7 all parents
         //
         ::bof::write( obj, "tpn", tstruct.num_parents() );
         //
         // Record #8 locations of parents, tstruct of parent pointers
         //
         ::bof::write( obj, "ppl", tstruct.parent_positions() );
         //
         // Record #9 mt list
         //
         ::bof::write( obj, "mtl", tstruct.transition_ids() );
         //
         // Record #10 decay constants
         //
         ::bof::write( obj, "dcc", decay_data.decay_constants );
         //
         // Record #11 Q recoverable energy
         //
         ::bof::write( obj, "rev", decay_data.recoverable_energy_values );
         //
         // Record #12 FG Q fractions due to photons
         //
         ::bof::write( obj, "qfp", decay_data.q_fractions_from_photons );
         //
         // Record #13 RCG for air
         //
         ::bof::write( obj, "rfa", decay_data.rcg_for_air );
         //
         // Record #14 RCG for water
         //
         ::bof::write( obj, "rfw", decay_data.rcg_for_water );
         //
         // Record #15 abundances
         //
         if( opts.get<bool>( "removeAbundance", false ) )
         {
             ::bof::write( obj, "aap", Vec_Flt() );
         }
         else
         {
             ::bof::write( obj, "aap", decay_data.abund_of_lite_nuclides );
         }
         //
         // Record #16 masses
         //
         if( opts.get<bool>( "removeMass", false ) )
         {
             ::bof::write( obj, "mas", Vec_Flt() );
         }
         else
         {
             ::bof::write( obj, "mas", decay_data.masses );
         }
         Insist( writer.write( obj ),
                 "***Error: Binary Header failed to write to disk!" );
     }
     // =====================
     // =====BURNUP STEPS====
     // =====================
     for( size_t index = 0; index < lib.transition_coeff_size(); index++ )
     {
         const TransitionCoeff& tcoeff = lib.transition_coeff_at( index );
         bof::BOFObject bob;
         //
         // #1 burnup
         //
         float bu = tcoeff.burnup();
         bof::write( bob, "bu", bu );
         Check( bob.containsKey( "bu" ) );
         //
         // #2 A tstruct transitions
         //
         ::bof::write( bob, "ma", tcoeff.matrix() );
         //
         // #3 TOCAP capture cross section
         //
         ::bof::write( bob, "tr", tcoeff.loss_xs() );
         //
         // #4 FISS fission cross section
         //
         ::bof::write( bob, "fx", tcoeff.fission_xs() );
         //
         // #5 GENNEU neutron yields
         //
         ::bof::write( bob, "ny", tcoeff.neutron_yields() );
         //
         // #6 FLUX spectrm used to generate the library
         //
         ::bof::write( bob, "fl", tcoeff.flux() );
         Insist( writer.write( bob ),
                 "***Error : Binary burnup failed to be written to disk!" );
     }  // burnups loop
     t.stop();
     opts.set( "saveTime", 1000 * t.wall_clock() );
     return true;
 }
The documentation for this class was generated from the following files:
Core/io/LibraryIO_bof.h
Core/io/LibraryIO_bof.cpp