ORIGEN API: STab1Writer Class Reference
STab1Writer Class Reference
Public Member Functions
std::string write (std::ostream &os)
write it
Static Public Member Functions
static std::string as_string (double value)
Public Attributes
SP_STab1 stab1
data that was write in
Static Protected Member Functions
static void setRealValue (std::string *line, double value, int index)
set the index of 6 values as a double on line
static void setIntValue (std::string *line, int value, int index)
set the index of 6 values as an integer on line
static void setLineValues_2Real_4Int (std::string *line, double f1, double f2, int i1, int i2, int i3, int i4)
set 2 floats and 4 ints a line
static void setLineValues_6Real (std::string *line, double f1, double f2, double f3, double f4, double f5, double f6)
set 6 floats on a line
static void writeTerminatorLine (std::ostream &os)
write a terminator to a string
static std::string writeTitle (std::ostream &os, const std::string &title)
write the one line title
static std::string writeData (std::ostream &os, const STab1::Data &data)
write a data set
static std::string writeBlock (std::ostream &os, const STab1::Block &block)
write a data block (contains 1 or more data sets)
static std::string writeFile (std::ostream &os, const STab1 &stab1)
write the simplified tab1 data
Member Function Documentation
static std::string as_string (double value) inline static
Examples:
tstYieldResourceIO.cpp.
References STab1Writer::setRealValue().
std::string write (std::ostream & os) inherited
write it
References STab1Writer::stab1, and STab1Writer::writeFile().
Referenced by YieldResourceIO_stab1::write().
void setRealValue (std::string * line, double value, int index) static protected inherited
set the index of 6 values as a double on line
Examples:
tstYieldResourceIO.cpp.
References STab1::ENDF_FIELD_LENGTH.
Referenced by STab1Writer::as_string(), STab1Writer::setLineValues_2Real_4Int(), STab1Writer::setLineValues_6Real(), and STab1Writer::writeData().
void setIntValue (std::string * line, int value, int index) static protected inherited
set the index of 6 values as an integer on line
References STab1::ENDF_FIELD_LENGTH.
Referenced by STab1Writer::setLineValues_2Real_4Int().
void setLineValues_2Real_4Int (std::string * line, double f1, double f2, int i1, int i2, int i3, int i4) static protected inherited
set 2 floats and 4 ints a line
References STab1Writer::setIntValue(), and STab1Writer::setRealValue().
Referenced by STab1Writer::writeTerminatorLine().
void setLineValues_6Real (std::string * line, double f1, double f2, double f3, double f4, double f5, double f6) static protected inherited
set 6 floats on a line
References STab1Writer::setRealValue().
void writeTerminatorLine (std::ostream & os) static protected inherited
write a terminator to a string
References kernel_rksuite::f(), and STab1Writer::setLineValues_2Real_4Int().
Referenced by STab1Writer::writeBlock(), STab1Writer::writeData(), and STab1Writer::writeFile().
std::string writeTitle (std::ostream & os, const std::string & title) static protected inherited
write the one line title
Referenced by STab1Writer::writeFile().
std::string writeData (std::ostream & os, const STab1::Data & data) static protected inherited
write a data set
References STab1::Data::cr, STab1::Data::id, STab1Writer::setRealValue(), STab1::Data::val, and STab1Writer::writeTerminatorLine().
Referenced by STab1Writer::writeBlock().
std::string writeBlock (std::ostream & os, const STab1::Block & block) static protected inherited
write a data block (contains 1 or more data sets)
References STab1::Block::cr, STab1::Block::set, STab1Writer::writeData(), and STab1Writer::writeTerminatorLine().
Referenced by STab1Writer::writeFile().
std::string writeFile (std::ostream & os, const STab1 & stab1) static protected inherited
write the simplified tab1 data
References STab1::block, STab1::title, STab1Writer::writeBlock(), STab1Writer::writeTerminatorLine(), and STab1Writer::writeTitle().
Referenced by STab1Writer::write().
Member Data Documentation
SP_STab1 stab1 inherited
data that was write in
Referenced by YieldResourceIO_stab1::write(), and STab1Writer::write().
The documentation for this class was generated from the following file:
Core/io/tests/tstYieldResourceIO.cpp