ORIGEN API: scale_libraries Module Reference
scale_libraries Module Reference
basic IO subroutines for reading neutron and gamma energy groups from SCALE master libraries
Functions/Subroutines
subroutine binlib_read_g_egs (filename, number_of_groups, ary)
Read gamma energy group structure from binary library.
subroutine binlib_read_n_egs (filename, number_of_groups, ary)
Read neutron energy group structure from binary library.
integer function binlib_get_n_ng (filename)
Read number of neutron groups from binary library.
integer function binlib_get_n_gg (filename)
Read number of gamma groups from binary library.
Variables
integer, parameter binary_unit = 26
type(fileutils), private resolver
Detailed Description
basic IO subroutines for reading neutron and gamma energy groups from SCALE master libraries
Function/Subroutine Documentation
subroutine scale_libraries::binlib_read_g_egs (character(len=*), intent(in) filename, integer, intent(in) number_of_groups, real(c_double), dimension(:), intent(out), allocatable ary)
Read gamma energy group structure from binary library.
Parameters
[in] filename File name of the library
[in] number_of_groups Number of energy groups to be read
[out] ary Output buffer for the energy group boundaries
References resolver.
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> File name of the library
     character(len=*), intent(in) :: filename
     !> Number of energy groups to be read
     integer, intent(in) :: number_of_groups
     !> Output buffer for the energy group boundaries
     real(C_DOUBLE), allocatable, intent(out) :: ary(:)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     real, allocatable :: buffer(:)
     integer :: i, number_of_nuclides, dummy, neutron_flag
     type(ampxlibrary)   :: ampxlib
     type(libraryheader) :: header
     type(ampxloader)    ::loader
     type(libraryenergybounds)::ampxbounds
     character(1024) :: full_name
     allocate(ary(number_of_groups + 1))
     allocate(buffer(number_of_groups + 1))
     call resolver%resolve(full_name, trim(filename))
     call loader%initialize()
     if (loader%loadHeaderInfo(trim(full_name)))then
           call loader%getLibrary(ampxlib)
           call ampxlib%getLibraryHeader(header)
           call ampxlib%getGammaEnergyBounds(ampxbounds)
           do i = 1, number_of_groups + 1
               if( i.gt.header%getIPM() +1) exit
               buffer(i) = ampxbounds%getAt(i)
           end do
           call loader%destroy()
      end if
    ! copy to doubles
     ary(:number_of_groups + 1) = buffer(:number_of_groups + 1) * 1.0d-6 ! convert to MeV
     ! clean up
     deallocate(buffer)
subroutine scale_libraries::binlib_read_n_egs (character(len=*), intent(in) filename, integer, intent(in) number_of_groups, real(c_double), dimension(:), intent(out), allocatable ary)
Read neutron energy group structure from binary library.
Parameters
[in] filename File name of the library
[in] number_of_groups Number of energy groups to be read
[out] ary Output buffer for the energy group boundaries
References resolver.
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> File name of the library
     character(len=*), intent(in) :: filename
     !> Number of energy groups to be read
     integer, intent(in) :: number_of_groups
     !> Output buffer for the energy group boundaries
     real(C_DOUBLE), allocatable, intent(out) :: ary(:)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     real, allocatable :: buffer(:)
     integer :: i, number_of_nuclides, dummy
     character(1024) :: full_name
     type(ampxlibrary)   :: ampxlib
     type(libraryheader) :: header
     type(ampxloader)    ::loader
     type(libraryenergybounds)::ampxbounds
     call resolver%resolve(full_name, trim(filename))
     !open(unit=binary_unit, file=full_name, status='old', form='unformatted', action='read', convert='big_endian')
     allocate(ary(number_of_groups + 1))
     allocate(buffer(number_of_groups + 1))
     call loader%initialize()
     if (loader%loadHeaderInfo(trim(full_name)))then
           call loader%getLibrary(ampxlib)
           call ampxlib%getLibraryHeader(header)
           call ampxlib%getNeutronEnergyBounds(ampxbounds)
           do i = 1, number_of_groups + 1
               if( i.gt.header%getIGM() +1) exit
               buffer(i) = ampxbounds%getAt(i)
           end do
           call loader%destroy()
      end if
     ! copy to doubles
     ary(:number_of_groups + 1) = buffer(:number_of_groups + 1)*1.0d-6 ! convert to MeV
     ! clean up
     deallocate(buffer)
integer function scale_libraries::binlib_get_n_ng (character(len=*), intent(in) filename)
Read number of neutron groups from binary library.
Parameters
[in] filename File name of the library
References resolver.
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> File name of the library
     character(len=*), intent(in) :: filename
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !>
     real :: dum1, dum2
     !>
     character(1024) :: full_name
     type(ampxlibrary)   :: ampxlib
     type(libraryheader) :: header
     type(ampxloader)    ::loader
     call resolver%resolve(full_name, trim(filename))
     call loader%initialize()
     if (loader%loadHeaderInfo(trim(full_name)))then
           call loader%getLibrary(ampxlib)
           call ampxlib%getLibraryHeader(header)
            binlib_get_n_ng = header%getIGM()
      end if
integer function scale_libraries::binlib_get_n_gg (character(len=*), intent(in) filename)
Read number of gamma groups from binary library.
Parameters
[in] filename File name of the library
References resolver.
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> File name of the library
     character(len=*), intent(in) :: filename
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !>
     real :: d1, d2, d3, d4, d5
     character(1024) :: full_name
     type(ampxlibrary)   :: ampxlib
     type(libraryheader) :: header
     type(ampxloader)    ::loader
     call resolver%resolve(full_name, trim(filename))
     call loader%initialize()
     if (loader%loadHeaderInfo(trim(full_name)))then
           call loader%getLibrary(ampxlib)
           call ampxlib%getLibraryHeader(header)
            binlib_get_n_gg = header%getIPM()
      end if
Variable Documentation
integer, parameter binary_unit = 26
   integer, parameter :: binary_unit = 26
type(fileutils), private resolver
Referenced by binlib_get_n_gg(), binlib_get_n_ng(), binlib_read_g_egs(), and binlib_read_n_egs().
   type(fileutils), private :: resolver