ORIGEN API: DiscreteSpectrum Class Reference
DiscreteSpectrum Class Reference
#include <DiscreteSpectrum.h>
defines a set of lines (energy points and intensities)
Public Member Functions
double search (double e, double tol=1.e-3)
void add_line (double e, double f)
double intensity_at (size_t i) const
double total_intensity () const
double total_energy_intensity () const
double mean_energy () const
double energy_at (size_t i) const
Set_Line lines () const
size_t num_lines () const
Vec_Dbl energies () const
Vec_Dbl intensities () const
EnergyRange_t energy_range () const
std::string print_lines () const
void bin (const Vec_Dbl &bounds, Vec_Dbl *intensity, double wt=1.0) const
Public Attributes
Set_Line b_line
Detailed Description
defines a set of lines (energy points and intensities)
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, tstEmissionSpectrum.cpp, tstGammaResource.cpp, and tstGammaResourceIO.cpp.
Member Function Documentation
double search (double e, double tol = 1.e-3)
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, and tstGammaResource.cpp.
References DiscreteSpectrum::b_line, and Origen::BAD_DOUBLE.
Referenced by TEST().
void add_line (double e, double f)
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, tstEmissionSpectrum.cpp, and tstGammaResource.cpp.
References DiscreteSpectrum::b_line.
Referenced by GammaResourceIO_cimg::read(), and TEST().
double intensity_at (size_t i) const
References DiscreteSpectrum::b_line.
double total_intensity () const
References DiscreteSpectrum::b_line.
Referenced by DiscreteSpectrum::mean_energy(), and EmissionSpectrum::total_intensity().
double total_energy_intensity () const
References DiscreteSpectrum::b_line.
Referenced by DiscreteSpectrum::mean_energy(), and EmissionSpectrum::total_energy_intensity().
double mean_energy () const
References DiscreteSpectrum::total_energy_intensity(), and DiscreteSpectrum::total_intensity().
double energy_at (size_t i) const
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, and tstGammaResource.cpp.
References DiscreteSpectrum::b_line.
Referenced by TEST().
Set_Line lines () const
References DiscreteSpectrum::b_line.
size_t num_lines () const
References DiscreteSpectrum::b_line.
Referenced by DiscreteSpectrum::energies(), and DiscreteSpectrum::intensities().
Vec_Dbl energies () const
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, and tstGammaResource.cpp.
References DiscreteSpectrum::b_line, and DiscreteSpectrum::num_lines().
Referenced by TEST().
Vec_Dbl intensities () const
References DiscreteSpectrum::b_line, and DiscreteSpectrum::num_lines().
EnergyRange_t energy_range () const
References DiscreteSpectrum::b_line, Origen::EMAX, and Origen::EMIN.
Referenced by EmissionSpectrum::energy_range().
std::string print_lines () const
References DiscreteSpectrum::b_line.
Referenced by EmissionSpectrum::print_discrete().
void bin (const Vec_Dbl & bounds, Vec_Dbl * intensity, double wt = 1.0) const
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, and tstGammaResource.cpp.
References DiscreteSpectrum::b_line, and kernel_rksuite::f().
Referenced by EmissionSpectrum::bin(), and TEST().
Member Data Documentation
Set_Line b_line
Referenced by DiscreteSpectrum::add_line(), DiscreteSpectrum::bin(), DiscreteSpectrum::energies(), DiscreteSpectrum::energy_at(), DiscreteSpectrum::energy_range(), DiscreteSpectrum::intensities(), DiscreteSpectrum::intensity_at(), DiscreteSpectrum::lines(), EmissionSpectrum::num_discrete(), DiscreteSpectrum::num_lines(), DiscreteSpectrum::print_lines(), DiscreteSpectrum::search(), DiscreteSpectrum::total_energy_intensity(), and DiscreteSpectrum::total_intensity().
The documentation for this class was generated from the following files:
Core/dc/DiscreteSpectrum.h
Core/dc/DiscreteSpectrum.cpp