ORIGEN API: Core/xf/tests/tstCompManager.cpp File Reference
tstCompManager.cpp File Reference
#include "Origen/Core/xf/CompManager.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include <cmath>
#include <cstdlib>
#include <functional>
#include <memory>
#include <numeric>
#include <sstream>
#include "Nemesis/harness/DBC.hh"
#include "ScaleInput/Parser/ScaleParser.h"
#include "Standard/Interface/jdebug.h"
#include "ScaleData/Core/StdComp.h"
Classes
class FakeStdComp
Namespaces
ScaleData
Macros
#define EXPECT_EMPTY_STR(action_and_result_str) EXPECT_EQ("", action_and_result_str)
Functions
TEST (CompManager, test_water)
TEST (CompManager, FailNotValidNuclide)
TEST (CompManager, Fail8001)
Macro Definition Documentation
#define EXPECT_EMPTY_STR (action_and_result_str) EXPECT_EQ("", action_and_result_str)
Examples:
tstCompManager.cpp.
Referenced by TEST().
Function Documentation
TEST (CompManager , test_water)
Examples:
tstCompManager.cpp.
References CompManager::addPart(), EXPECT_EMPTY_STR, CompManager::finalizeComp(), CompManager::getCompName(), CompManager::getConcMap(), CompManager::getDC(), CompManager::getNumComps(), CompManager::getNumMap(), CompManager::getWtMap(), CompManager::initComp(), and CompManager::toString().
 {
     // Main testing procedure.
     FakeStdComp fakeStdComp;
     Origen::CompManager mCompMan = CompManager( fakeStdComp );
     // evaluate elemental H2O
     EXPECT_EMPTY_STR(
         mCompMan.initComp( "elemental_h2o", "FORM", "ABS", true ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "elemental_h2o", "H", 2.0 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "elemental_h2o", "O", 1.0 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "elemental_h2o" ) );
     std::cout << mCompMan.toString( "elemental_h2o" ) << std::endl;
     // double H2O
     EXPECT_EMPTY_STR( mCompMan.initComp( "double_h2o", "FORM", "ABS", true ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "double_h2o", "elemental_h2o", 1.5 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "double_h2o", "elemental_h2o", 1.5 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "double_h2o" ) );
     jDebugLine( mCompMan.toString( "double_h2o" ) );
     {
         std::map<int, double> map_out;
         EXPECT_EMPTY_STR( mCompMan.getNumMap( "elemental_h2o", map_out ) );
         double dens = 1.0;
         EXPECT_EMPTY_STR(
             mCompMan.getConcMap( "elemental_h2o", dens, map_out ) );
         EXPECT_EMPTY_STR( mCompMan.getNumMap( "double_h2o", map_out ) );
         EXPECT_EMPTY_STR( mCompMan.getConcMap( "double_h2o", dens, map_out ) );
     }
     // evaluate simple H2O
     EXPECT_EMPTY_STR( mCompMan.initComp( "simple_h2o", "FORM", "ABS", true ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "simple_h2o", "1001", 2.0 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "simple_h2o", "8016", 1.0 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "simple_h2o" ) );
     jDebugLine( mCompMan.toString( "simple_h2o" ) );
     // borated H2O
     double ppmbor = 1300;
     EXPECT_EMPTY_STR( mCompMan.initComp( "borated_h2o", "WT", "PPM", true ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "borated_h2o", "elemental_h2o", 1e6 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "borated_h2o", "B", ppmbor ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "borated_h2o" ) );
     jDebugLine( mCompMan.toString( "borated_h2o" ) );
     // test ppm boron
     {
         std::map<int, double> map_out;
         mCompMan.getWtMap( "borated_h2o", map_out );
         double ppmbor_check = 1e6 * ( map_out[5010] + map_out[5011] ) /
                               ( map_out[1001] + map_out[1002] + map_out[8016] +
                                 map_out[8017] + map_out[8018] );
         EXPECT_SOFTEQ( ppmbor, ppmbor_check, 5.e-7 );
     }
     // natural UO2
     EXPECT_EMPTY_STR( mCompMan.initComp( "UO2[nat]", "NUM", "ABS", true ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "UO2[nat]", "U", 1.0 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "UO2[nat]", "O", 2.0 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "UO2[nat]" ) );
     jDebugLine( mCompMan.toString( "UO2[nat]" ) );
     // AIC control rods
     EXPECT_EMPTY_STR( mCompMan.initComp( "aic", "WT", "PCT", false ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "aic", "Ag", 80.0 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "aic", "In", 15.0 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "aic", "Cd", 5.0 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "aic" ) );
     jDebugLine( mCompMan.toString( "aic" ) );
     // enriched UO2
     EXPECT_EMPTY_STR( mCompMan.initComp( "U[2.5]", "WT", "PCT", false ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "U[2.5]", "U-235", 2.5 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "U[2.5]", "U-238", -100.0 ) );
     EXPECT_EMPTY_STR( mCompMan.initComp( "UO2[2.5]", "NUM", "ABS", true ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "UO2[2.5]", "U[2.5]", 1.0 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "UO2[2.5]", "O", 2.0 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "UO2[2.5]" ) );
     jDebugLine( mCompMan.toString( "UO2[2.5]" ) );
     // using metastable
     EXPECT_EMPTY_STR( mCompMan.initComp( "myAm", "WT", "PCT", false ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "myAm", "Am-242m", 2.5 ) );
     EXPECT_EMPTY_STR( mCompMan.addPart( "myAm", "Am-242", -100.0 ) );
     EXPECT_EMPTY_STR( mCompMan.finalizeComp( "myAm" ) );
     jDebugLine( mCompMan.toString( "myAm" ) );
     std::map<int, double> map_out;
     EXPECT_EMPTY_STR( mCompMan.getNumMap( "borated_h2o", map_out ) );
     double dens = 1.0;
     EXPECT_EMPTY_STR( mCompMan.getConcMap( "borated_h2o", dens, map_out ) );
     dens = 10.16;
     EXPECT_EMPTY_STR( mCompMan.getConcMap( "aic", dens, map_out ) );
     // test getDataContainer
     DataContainer dcCompositionList;
     EXPECT_EMPTY_STR( mCompMan.getDC( &dcCompositionList, false ) );
     EXPECT_EQ( 16, mCompMan.getNumComps() );
     // test getName
     EXPECT_EQ( "elemental_h2o", mCompMan.getCompName( 1 ) );
     // test ppm boron by number (instead of by weight)
     {
         std::map<int, double> map_out;
         mCompMan.getNumMap( "borated_h2o", map_out );
         double ppmbor_check = 1e6 * ( map_out[5010] + map_out[5011] ) /
                               ( map_out[1001] + map_out[1002] + map_out[8016] +
                                 map_out[8017] + map_out[8018] );
         EXPECT_SOFTEQ( 722.098, ppmbor_check, 5.e-7 );
     }
     dcCompositionList.deepDelete();
 }
TEST (CompManager , FailNotValidNuclide)
References CompManager::addPart(), EXPECT_EMPTY_STR, CompManager::finalizeComp(), and CompManager::initComp().
 {
     // Main testing procedure.
     FakeStdComp fakeStdComp;
     Origen::CompManager mCompMan = CompManager( fakeStdComp );
     EXPECT_EMPTY_STR( mCompMan.initComp( "x", "WT", "PCT", false ) );
     EXPECT_EQ(
         "part='u2' --> 92002 is not a valid NUCLIDE in this StdCompLibrary",
         mCompMan.addPart( "x", "u2", 100 ) );
     EXPECT_EQ(
         "cannot finalize composition name=x unless number fractions >=0 and "
         "sum to 1.0 (sum=0.00000e+00)",
         mCompMan.finalizeComp( "x" ) );
 }
TEST (CompManager , Fail8001)
References CompManager::addPart(), EXPECT_EMPTY_STR, CompManager::finalizeComp(), and CompManager::initComp().
 {
     // Main testing procedure.
     FakeStdComp fakeStdComp;
     Origen::CompManager mCompMan = CompManager( fakeStdComp );
     EXPECT_EMPTY_STR( mCompMan.initComp( "x", "WT", "PCT", false ) );
     // 8008 is first allowed "oxygen" by ZA rules that A>=Z because A=Z+N
     EXPECT_EQ( "part='8001' is not a valid NUCLIDE/ELEMENT id",
                mCompMan.addPart( "x", "8001", 100 ) );
     EXPECT_EQ(
         "cannot finalize composition name=x unless number fractions >=0 and "
         "sum to 1.0 (sum=0.00000e+00)",
         mCompMan.finalizeComp( "x" ) );
 }