ORIGEN API: Core/dc/f/tests/tstStateSet.f90 File Reference
tstStateSet.f90 File Reference
Functions/Subroutines
program tststateset
subroutine loop_time_vec (repeat, state_set)
subroutine loop_time_ptr (repeat, state_set)
subroutine loop_time_vec_at (repeat, state_set)
subroutine loop_time_native (repeat, state_set)
Function/Subroutine Documentation
program tststateset ()
References cpu_time(), loop_time_native(), loop_time_ptr(), loop_time_vec(), and loop_time_vec_at().
subroutine tststateset::loop_time_vec (integer, intent(in) repeat, type(origen_stateset), intent(in) state_set)
Referenced by tststateset().
 integer,intent(in) :: repeat
 type(origen_stateset),intent(in) :: state_set
 type(origen_state)            :: state
 type(origen_concentrations)   :: concs
 type(origen_nuclideset)       :: nuclide_set
 type(scalestl_vec_int)        :: ids
 type(scalestl_vec_dbl)        :: vals
 integer(C_INT)                :: units
 integer(C_SIZE_T) :: i,j
 integer :: n
 integer(C_INT) :: isum
 real(C_DOUBLE) :: dsum
 call ids % initialize()
 call nuclide_set % initialize()
 call vals % initialize()
 call concs % initialize()
 call state % initialize()
 do n=1,repeat
     isum=0
     dsum=0.d0
     do i=1,state_set % states_size()
         !state
         call state_set % get_states_at(state,i)
         !state.concs
         call state % get_concs(concs)
         !state.concs.units
         units = concs % units()
         call concs % get_vals_vec(vals)
         !state.concs.nuclide_set
         call concs % get_nuclide_set(nuclide_set)
         call nuclide_set % get_ids_vec(ids)
         do j=1,vals%size()
             isum=isum+ids%at(j)   !state.concs.nuclide_set.ids
             dsum=dsum+vals%at(j)  !state.concs.vals
         end do
     end do
     !write(*,*)'isum=',isum,'dsum=',dsum
 end do
 call ids % destroy()
 call nuclide_set % destroy()
 call vals % destroy()
 call concs % destroy()
 call state % destroy()
subroutine tststateset::loop_time_ptr (integer, intent(in) repeat, type(origen_stateset), intent(in) state_set)
Referenced by tststateset().
 integer,intent(in) :: repeat
 type(origen_stateset),intent(in) :: state_set
 type(origen_state)            :: state
 type(origen_concentrations)   :: concs
 type(origen_nuclideset)       :: nuclide_set
 type(scalestl_vec_int)        :: ids
 type(scalestl_vec_dbl)        :: vals
 integer(C_INT)                :: units
 integer(C_SIZE_T) :: i,j
 integer :: n
 integer(C_INT) :: isum
 real(C_DOUBLE) :: dsum
 do n=1,repeat
     isum=0
     dsum=0.d0
     do i=1,state_set % states_size()
         !state
         call state_set % getptr_states_at(state,i)
         !state.concs
         call state % getptr_concs(concs)
         !state.concs.units
         units = concs % units()
         call concs % getptr_vals_vec(vals)
         !state.concs.nuclide_set
         call concs % getptr_nuclide_set(nuclide_set)
         call nuclide_set % getptr_ids_vec(ids)
         do j=1,vals%size()
             isum=isum+ids%at(j)   !state.concs.nuclide_set.ids
             dsum=dsum+vals%at(j)  !state.concs.vals
         end do
     end do
     !write(*,*)'isum=',isum,'dsum=',dsum
 end do
subroutine tststateset::loop_time_vec_at (integer, intent(in) repeat, type(origen_stateset), intent(in) state_set)
Referenced by tststateset().
 integer,intent(in) :: repeat
 type(origen_stateset),intent(in) :: state_set
 type(origen_state)            :: state
 type(origen_concentrations)   :: concs
 type(origen_nuclideset)       :: nuclide_set
 integer(C_INT)                :: units
 integer(C_SIZE_T) :: i,j
 integer :: n
 integer(C_INT) :: isum
 real(C_DOUBLE) :: dsum
 call nuclide_set % initialize()
 call concs % initialize()
 call state % initialize()
 do n=1,repeat
     isum=0
     dsum=0.d0
     do i=1,state_set % states_size()
         !state
         call state_set % get_states_at(state,i)
         !state.concs
         call state % get_concs(concs)
         !state.concs.units
         units = concs % units()
         !state.concs.nuclide_set
         call concs % get_nuclide_set(nuclide_set)
         do j=1,nuclide_set%total_nuclides()
             isum=isum+nuclide_set%ids_at(j)   !state.concs.nuclide_set.ids
             dsum=dsum+concs%vals_at(j)        !state.concs.vals
         end do
     end do
     !write(*,*)'isum=',isum,'dsum=',dsum
 end do
 call nuclide_set % destroy()
 call concs % destroy()
 call state % destroy()
subroutine tststateset::loop_time_native (integer, intent(in) repeat, type(origen_stateset), intent(in) state_set)
Referenced by tststateset().
 integer,intent(in) :: repeat
 type(origen_stateset),intent(in) :: state_set
 type(origen_state)            :: state
 type(origen_concentrations)   :: concs
 type(origen_nuclideset)       :: nuclide_set
 integer(C_INT),allocatable        :: ids(:)
 real(C_DOUBLE),allocatable        :: vals(:)
 integer(C_INT)                :: units
 integer(C_SIZE_T) :: i,j
 integer :: n
 integer(C_INT) :: isum
 real(C_DOUBLE) :: dsum
 call nuclide_set % initialize()
 call concs % initialize()
 call state % initialize()
 do n=1,repeat
     isum=0
     dsum=0.d0
     do i=1,state_set % states_size()
         !state
         call state_set % get_states_at(state,i)
         !state.concs
         call state % get_concs(concs)
         !state.concs.units
         units = concs % units()
         call concs % get_vals(vals)
         !state.concs.nuclide_set
         call concs % get_nuclide_set(nuclide_set)
         call nuclide_set % get_ids(ids)
         do j=1,size(vals,1)
             isum=isum+ids(j)   !state.concs.nuclide_set.ids
             dsum=dsum+vals(j)  !state.concs.vals
         end do
     end do
     !write(*,*)'isum=',isum,'dsum=',dsum
 end do
 call nuclide_set % destroy()
 call concs % destroy()
 call state % destroy()