ORIGEN API: depletion Module Reference
depletion Module Reference
The predictor-corrector mechanism and solver encapsulation.
Functions/Subroutines
subroutine deplete (solver_opts, lib, itot, n0, n, delta_t, source_term, flux, power, input_by_flux, is_adjoint, fixed_fission_energy, reprocessing_rate, feed_rate, adjoint_source_term_reaction, adjoint_source_term_decay)
Perform a single depletion step (including the predictor/corrector mechanism).
subroutine depletion_step (solver_opts, lib, itot, n0, n, delta_t, corrector, powrst, fluxst, source_term, flux, power, input_by_flux, is_adjoint, fixed_fission_energy, reprocessing_rate, feed_rate, adjoint_source_term_reaction, adjoint_source_term_decay)
Run the solver once.
subroutine powerflux (lib, itot, power, flux, concentrations, input_by_flux, fixed_fission_energy, is_adjoint)
Convert power to flux or vice versa.
subroutine fluxo (corrector, powrst, fluxst, flux, power, zero_flux_step, input_by_flux)
Computes the average flux over a time interval using predictor corrector method, build the diagonal of the transition matrix (DIAG array), convert flux to power or vice versa, multiply A matrix off-diagoal elements by flux.
subroutine powerf (lib, itot, factor, fission_rate, concentrations, zero_flux_step)
Calculate the power-flux conversion factor, based on given fission rate and given concentrations.
Detailed Description
The predictor-corrector mechanism and solver encapsulation.
This module encapsulates the predictor-corrector mechanism of depletion and provides the parts of the depletion mechanism which are common to all solvers.
The deplete subroutine executes two solver runs for predictor and corrector steps.
The depletion_step subroutine calculates the flux (or power) integrated over the time step, builds the transition matrix A for the solver (by folding the reaction and decay data together using the evaluated flux), builds up the source vector B (consisting of the user-specified constant feed term and from the terms arising from the adjoint solution, if applicable) and runs the solver itself.
Function/Subroutine Documentation
subroutine depletion::deplete (type(solver_options), intent(in) solver_opts, type(origen_librarywrapper), intent(in) lib, integer, intent(in) itot, real(c_double), dimension(itot), intent(in) n0, real(c_double), dimension(itot), intent(out) n, real(c_double), intent(in) delta_t, real(c_double), dimension(itot), intent(inout) source_term, real(c_double), intent(inout) flux, real(c_double), intent(inout) power, logical, intent(in) input_by_flux, logical, intent(in) is_adjoint, logical, intent(in) fixed_fission_energy, real(c_double), dimension(itot), intent(in) reprocessing_rate, real(c_double), dimension(itot), intent(in) feed_rate, real(c_double), dimension(itot), intent(in) adjoint_source_term_reaction, real(c_double), dimension(itot), intent(in) adjoint_source_term_decay)
Perform a single depletion step (including the predictor/corrector mechanism).
Parameters
[in] solver_opts solver settings
[in] lib Library data
[in] itot Number of nuclides in the library
[in] n0 initial concentrations
[out] n final concentrations
[in,out] source_term Continuous processing feed rate / source term from the adjoint calculation
[in] delta_t Time step length in seconds
[in] input_by_flux flux is used for input? or power?
[in] is_adjoint is this an adjoint calculation?
[in] fixed_fission_energy is the fission energy fixed or problem dependent?
[in] reprocessing_rate continuous reprocessing rates
[in] feed_rate continuous feed rates
[in] adjoint_source_term_reaction reaction component of the adjoint source term
[in] adjoint_source_term_decay decay component of the adjoint source term
buffers for predictor-corrector power and flux
References depletion_step(), and origen_iofunctions_m::rstop().
Referenced by origen_casewrapper_m::flip_time().
     implicit none
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> solver settings
     type(solver_options), intent(in) :: solver_opts
     !> Library data
     type(origen_librarywrapper), intent(in) :: lib
     !> Number of nuclides in the library
     integer, intent(in) :: itot
     !> initial concentrations
     real(C_DOUBLE), intent(in) :: n0(itot) ! [itot]
     !> final concentrations
     real(C_DOUBLE), intent(out) :: n(itot) ! [itot]
     !> Continuous processing feed rate / source term from the adjoint calculation
     real(C_DOUBLE), intent(inout) :: source_term(itot) ! [itot]
     !> Time step length in seconds
     real(C_DOUBLE), intent(in) :: delta_t
     !> flux
     real(C_DOUBLE), intent(inout) :: flux
     !> power
     real(C_DOUBLE), intent(inout) :: power
     !> flux is used for input? or power?
     logical, intent(in) :: input_by_flux
     !> is this an adjoint calculation?
     logical, intent(in) :: is_adjoint
     !> is the fission energy fixed or problem dependent?
     logical, intent(in) :: fixed_fission_energy
     !> continuous reprocessing rates
     real(C_DOUBLE), intent(in) :: reprocessing_rate(itot) ! [itot]
     !> continuous feed rates
     real(C_DOUBLE), intent(in) :: feed_rate(itot) ! [itot]
     !> reaction component of the adjoint source term
     real(C_DOUBLE), intent(in) :: adjoint_source_term_reaction(itot) ! [itot]
     !> decay component of the adjoint source term
     real(C_DOUBLE), intent(in) :: adjoint_source_term_decay(itot) ! [itot]
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> buffers for predictor-corrector power and flux
     real(C_DOUBLE) :: powrst, fluxst
     powrst = 0.d0
     fluxst = 0.d0
     if (delta_t < 0.0) call rstop("Time step length for depletion is negative." ,505)
     jdebugline2("Depletion :: initial concentration sum is ", sum(n0))
     jdebugline2("Depletion :: feed rate sum is ", sum(reprocessing_rate))
     ! run the solution (predictor step)
     call depletion_step(solver_opts, lib, lib%get_itot(), n0, n, delta_t, .false., powrst, fluxst, source_term, flux, power, input_by_flux, is_adjoint, fixed_fission_energy, reprocessing_rate, feed_rate, adjoint_source_term_reaction, adjoint_source_term_decay)
     jdebugline2("Depletion :: intermediate concentration sum is ", sum(n))
     jdebugline2("Depletion :: predicted flux is ", fluxst)
     ! run the solution (corrector step)
     call depletion_step(solver_opts, lib, lib%get_itot(), n0, n, delta_t, .true. , powrst, fluxst, source_term, flux, power, input_by_flux, is_adjoint, fixed_fission_energy, reprocessing_rate, feed_rate, adjoint_source_term_reaction, adjoint_source_term_decay)
     jdebugline2("Depletion :: actual flux is ", flux)
     jdebugline2("Depletion :: final concentration sum is ", sum(n))
     jdebugline("Depletion is finished")
subroutine depletion::depletion_step (type(solver_options), intent(in) solver_opts, type(origen_librarywrapper), intent(in) lib, integer, intent(in) itot, real(c_double), dimension(itot), intent(in) n0, real(c_double), dimension(itot), intent(inout) n, real(c_double), intent(in) delta_t, logical, intent(in) corrector, real(c_double), intent(inout) powrst, real(c_double), intent(inout) fluxst, real(c_double), dimension(itot), intent(inout) source_term, real(c_double), intent(inout) flux, real(c_double), intent(inout) power, logical, intent(in) input_by_flux, logical, intent(in) is_adjoint, logical, intent(in) fixed_fission_energy, real(c_double), dimension(itot), intent(in) reprocessing_rate, real(c_double), dimension(itot), intent(in) feed_rate, real(c_double), dimension(itot), intent(in) adjoint_source_term_reaction, real(c_double), dimension(itot), intent(in) adjoint_source_term_decay)
Run the solver once.
Parameters
[in] solver_opts solver type identifier
[in] lib Library data
[in] itot Total number of nuclides
[in] n0 initial concentrations
[in,out] n final concentrations
[in] delta_t Time step length in seconds
[in] corrector is this a corrector step?
[in,out] powrst saved power for predictor-corrector
[in,out] fluxst saved flux for predictor-corrector
[in,out] source_term Continuous processing feed rate / source term from the adjoint calculation
[in] input_by_flux flux is used for input? or power?
[in] is_adjoint is this an adjoint calculation?
[in] fixed_fission_energy is the fission energy fixed or problem dependent?
[in] reprocessing_rate continuous reprocessing rates
[in] feed_rate continuous feed rates
[in] adjoint_source_term_reaction reaction component of the adjoint source term
[in] adjoint_source_term_decay decay component of the adjoint source term
Diagonal elements of the transition matrix
Nondiagonal elements of the transition matrix
is this a zero-flux (=decay) step?
References fluxo(), kernel_matrex::matrex_solve(), powerflux(), kernel_radau5::radau5_solve(), and origen_iofunctions_m::rstop().
Referenced by deplete().
     !-----------------------------------------------
     !   M o d u l e s
     !-----------------------------------------------
     use kernel_matrex
     use kernel_rksuite
     use kernel_radau5
     implicit none
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> solver type identifier
     type(solver_options), intent(in) :: solver_opts
     !> Library data
     type(origen_librarywrapper), intent(in) :: lib
     !> Total number of nuclides
     integer, intent(in) :: itot
     !> initial concentrations
     real(C_DOUBLE), intent(in) :: n0(itot)
     !> final concentrations
     real(C_DOUBLE), intent(inout) :: n(itot)
     !> Time step length in seconds
     real(C_DOUBLE), intent(in) :: delta_t
     !> is this a corrector step?
     logical, intent(in) :: corrector
     !> saved power for predictor-corrector
     real(C_DOUBLE), intent(inout) :: powrst
     !> saved flux for predictor-corrector
     real(C_DOUBLE), intent(inout) :: fluxst
     !> Continuous processing feed rate / source term from the adjoint calculation
     real(C_DOUBLE), intent(inout) :: source_term(itot)
     !> flux
     real(C_DOUBLE), intent(inout) :: flux
     !> power
     real(C_DOUBLE), intent(inout) :: power
     !> flux is used for input? or power?
     logical, intent(in) :: input_by_flux
     !> is this an adjoint calculation?
     logical, intent(in) :: is_adjoint
     !> is the fission energy fixed or problem dependent?
     logical, intent(in) :: fixed_fission_energy
     !> continuous reprocessing rates
     real(C_DOUBLE), intent(in) :: reprocessing_rate(itot)
     !> continuous feed rates
     real(C_DOUBLE), intent(in) :: feed_rate(itot)
     !> reaction component of the adjoint source term
     real(C_DOUBLE), intent(in) :: adjoint_source_term_reaction(itot)
     !> decay component of the adjoint source term
     real(C_DOUBLE), intent(in) :: adjoint_source_term_decay(itot)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> Diagonal elements of the transition matrix
     real(C_DOUBLE), allocatable :: diag(:) ! allocated/set by fold_flux
     !> Nondiagonal elements of the transition matrix
     real(C_DOUBLE), allocatable :: a(:) ! allocated/set by fold_flux
     !> is this a zero-flux (=decay) step?
     logical :: zero_flux_step
     ! Temporary storage for compositions in MATREX substep loop
     real(C_DOUBLE) :: n0_tmp(itot)
     ! Substep length in MATREX substep loop
     real(C_DOUBLE) :: t_ss
     integer :: i
     integer, allocatable :: non0(:) ! extra variables for the CRAM solver (AIs)
     integer, allocatable :: kd(:)
     integer, allocatable :: loc(:)
     integer, allocatable :: zai(:)
     integer :: i_zero_flux_step, i_is_adjoint, source_order
     integer :: status
     ! is this a zero-flux (decay-only) step?
     if (.not. input_by_flux) then
       zero_flux_step = (power < err)
     else
       zero_flux_step = (flux < err)
     end if
     if (zero_flux_step) then
       flux = 0.0
       power = 0.0
     else
       ! evaluate the flux/power
       ! choose the right 'starting' concentrations
       if (corrector) then
         call powerflux (lib, lib%get_itot(), power, flux, n, input_by_flux, fixed_fission_energy, is_adjoint)
         jdebugline2("Corrector flux is ", flux)
       else
         call powerflux (lib, lib%get_itot(), power, flux, n0, input_by_flux, fixed_fission_energy, is_adjoint)
         jdebugline2("Predictor flux is ", flux)
       end if
     end if
     ! integrate flux over time step
     call fluxo (corrector, powrst, fluxst, flux, power, zero_flux_step, input_by_flux)
     ! get the A and diag
     call lib%fold_flux (flux, diag, a)
     ! adjust diagonal by reprocessing
     diag(:) = diag(:) - reprocessing_rate(:)
     ! prepare source term (for adjoint calculations -- compensation for stable nuclides)
     if (is_adjoint .and. (solver_opts%solver .ne. 2)) then
       source_term = adjoint_source_term_decay + flux * 1e-24 * adjoint_source_term_reaction
       jdebugline2("Adjoint :: extra source term sum is ", sum(source_term(:)))
     else
       source_term = feed_rate
     end if
     ! solve the equation dN/dt = AN+B for t = t0 + delta_t
     if (solver_opts%solver == 0) then
       ! MATREX solver (Now with a substep loop)
 ! Can use rule of 3s to make different time steps.
 ! This seems to fall apart when time steps are very small (either numerical instabilities or other problems)
 ! resulting in concentrations of zero.  Commenting out for now, but leaving in in case it is revisited in the future.
 !~       if (zero_flux_step) then
 !~         ! Decay step. Each substep is 3x longer than the previous
 !~         t_ss = -2*delta_t / (1-3**solver_opts%internal_steps)
 !~         call matrex_solve(lib%b_trx, lib%get_itot(), lib%get_non(), n0, n, t_ss, diag, a, source_term, zero_flux_step, is_adjoint, solver_opts%nterm, solver_opts%nshrt, 0.0d0)
 !~         do i=2,solver_opts%internal_steps
 !~           n0_tmp = n    ! copy n to n0_tmp
 !~           t_ss = t_ss*3 ! increment step length by a factor of three
 !~           call matrex_solve(lib%b_trx, lib%get_itot(), lib%get_non(), n0_tmp, n, t_ss, diag, a, source_term, zero_flux_step, is_adjoint, solver_opts%nterm, solver_opts%nshrt, 0.0d0)
 !~         end do
 !~       else
         ! Depletion step. Equidistant substeps
         t_ss = delta_t / solver_opts%internal_steps
         call matrex_solve(lib%b_trx, lib%get_itot(), lib%get_non(), n0, n, t_ss, diag, a, source_term, zero_flux_step, is_adjoint, solver_opts%nterm, solver_opts%nshrt, 0.0d0)
         do i=2,solver_opts%internal_steps
           n0_tmp = n    ! copy n to n0_tmp
           call matrex_solve(lib%b_trx, lib%get_itot(), lib%get_non(), n0_tmp, n, t_ss, diag, a, source_term, zero_flux_step, is_adjoint, solver_opts%nterm, solver_opts%nshrt, 0.0d0)
         end do
 !~       end if
     else if (solver_opts%solver == 1) then
       call radau5_solve(lib%b_trx, lib%get_itot(), lib%get_non(), n0, n, delta_t, diag, a, source_term, zero_flux_step, is_adjoint, solver_opts%abstol, solver_opts%reltol)
 !    else if (solver_opts%solver == 2) then
 !       call volterra_solve(lib, lib%get_itot(), lib%get_non(), n0, n, delta_t, diag, a, source_term, zero_flux_step, is_adjoint, solver_opts)
 !    else if (solver_opts%solver == 3) then
 !      call rksuite_solve(lib%b_trx, lib%get_itot(), lib%get_non(), n0, n, delta_t, diag, a, source_term, zero_flux_step, is_adjoint)
 !   else if (solver_opts%solver == 4) then
 !     call expokit_solver(lib, lib%get_itot, n0, nx, t, flux)
     else if (solver_opts%solver == 2) then
       ! The new CRAM solver (i5q)
 #ifdef ORIGEN_DISABLE_CRAM
       serrline(1,*)"ORIGEN's CRAM solver is disabled in this build so you cannot use it."
       stop 868
 #else
       call lib%get_non0_(non0)
       call lib%get_kd_(kd)
       call lib%get_loc(loc)
       call lib%get_nucl(zai)
       ! CRAM solver expects C indexing but lib%get_loc adds + 1 for Fortran
       loc = loc - 1;
       ! Convert logicals to integers for sending to c++
       if (zero_flux_step) then
         i_zero_flux_step = 1
       else
         i_zero_flux_step = 0
       endif
       if (is_adjoint) then
         i_is_adjoint = 1
       else
         i_is_adjoint = 0
       endif
       ! NOTE: this assumes that the source is (at most) constant
       if (any(source_term /= 0)) then
         source_order = 0;
       else
         source_order = -1;
       endif
       status = kernel_cram_from_fortran(n, n0, source_term, source_order, delta_t, lib%get_itot(), lib%get_non(), non0, kd, diag, a, loc, i_zero_flux_step, i_is_adjoint, solver_opts%cram_order, solver_opts%internal_steps, 2, 0.0d0, zai)
       if (status.ne.0) then
         call rstop("CRAM solution failed",666)
       endif
       deallocate(non0)
       deallocate(kd)
       deallocate(loc)
 #endif
     end if
     deallocate(diag)
     deallocate(a)
subroutine depletion::powerflux (type(origen_librarywrapper), intent(in) lib, integer, intent(in) itot, real(c_double), intent(inout) power, real(c_double), intent(inout) flux, real(c_double), dimension(itot), intent(in) concentrations, logical, intent(in) input_by_flux, logical, intent(in) fixed_fission_energy, logical, intent(in) is_adjoint)
Convert power to flux or vice versa.
Parameters
[in] lib Library data
[in] itot Total number of nuclides
[in,out] flux user-given flux (if index is 0; otherwise not used)
[in,out] power user-given power (if index is 1; otherwise not used)
[in] concentrations Concentrations to be used
[in] input_by_flux depletion by flux or by power?
[in] fixed_fission_energy is the fission energy fixed or problem-dependent?
[in] is_adjoint is this an adjoint calculation?
Local holder for fiss array
References powerf(), and origen_iofunctions_m::rstop().
Referenced by depletion_step().
     implicit none
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Library data
     type(origen_librarywrapper), intent(in) :: lib
     !> Total number of nuclides
     integer, intent(in) :: itot
     !> user-given flux (if index is 0; otherwise not used)
     real(C_DOUBLE), intent(inout) :: flux
     !> user-given power (if index is 1; otherwise not used)
     real(C_DOUBLE), intent(inout) :: power
     !> Concentrations to be used
     real(C_DOUBLE), intent(in) :: concentrations(itot)
     !> depletion by flux or by power?
     logical, intent(in) :: input_by_flux
     !> is the fission energy fixed or problem-dependent?
     logical, intent(in) :: fixed_fission_energy
     !> is this an adjoint calculation?
     logical, intent(in) :: is_adjoint
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     ! estimated fission rate
     real(C_DOUBLE) :: fission_rate
     ! FLUX/POWER conversion factor
     real(C_DOUBLE) :: factor
     !> Local holder for fiss array
     real(C_DOUBLE), allocatable :: fiss(:)
     integer :: ilite, iact
     ilite = lib%get_ilite()
     iact = lib%get_iact()
     call lib%get_fiss(fiss)
     ! calculate fission rate
     if (iact > 0) then
       fission_rate = 1.0d0 !hack
        if (.not. is_adjoint) fission_rate = dot_product(concentrations(1+ilite:iact+ilite),fiss(:iact))
     else
       jdebugline("IACT is zero, so is the fission rate")
       fission_rate = 0.0d0
     end if
     ! get the flux-power conversion factor
     if (fixed_fission_energy) then
       ! fixed 200 MeV per fission
       if (fission_rate < err) call rstop ('Fixed fission energy release (JOPT(12)=1) requires nonzero fission rate.', 11)
       factor = (200.0*fission_rate)/1.0364e+19
     else
       ! explicit fission energy release
       if (.not. is_adjoint) then
         call powerf (lib, lib%get_itot(), factor, fission_rate, concentrations, .false.)
       else
         ! HACK for adjoint
         factor = 1.0
       end if
     end if
     ! convert flux and power
     if (.not. input_by_flux) then
       flux = power / factor
     else
       power = flux * factor
       ! HACK for adjoint :: nonsense, of course
       if (is_adjoint) power = 1.0
     end if
     deallocate(fiss)
subroutine depletion::fluxo (logical, intent(in) corrector, real(c_double), intent(inout) powrst, real(c_double), intent(inout) fluxst, real(c_double), intent(inout) flux, real(c_double), intent(inout) power, logical, intent(in) zero_flux_step, logical, intent(in) input_by_flux)
Computes the average flux over a time interval using predictor corrector method, build the diagonal of the transition matrix (DIAG array), convert flux to power or vice versa, multiply A matrix off-diagoal elements by flux.
Given an input value for the specific power, XFLUXO solves for the average flux over the time interval by using Eq. (F7.2.30) and energy per fission data. Given an input value for the neutron flux, XFLUXO solves for the specific power by Eq. (F7.2.32). Having obtained a value for the neutron flux, XFLUXO generates the first-order rate constants for neutron-induced reactions. Then the diagonal matrix element is formed for each nuclide by combining the disintegration constant, the rate constant for neutron-induced reactions, and the rate constant for removal processes that are proportional to the nuclide concentration. The diagonal matrix elements are stored in the D array.
Parameters
[in] corrector false => save flux (fluxst/powrst), true => average saved and actual flux
[in,out] powrst saved power from predictor to corrector
[in,out] fluxst saved flux from predictor to corrector
[in,out] flux user-given flux (if index is 0; otherwise not used)
[in,out] power user-given power (if index is 1; otherwise not used)
[in] zero_flux_step is this a zero-flux step?
[in] input_by_flux depletion by flux or by power?
Referenced by depletion_step().
     !-----------------------------------------------
     !   M o d u l e s
     !-----------------------------------------------
     use const
     implicit none
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> false => save flux (fluxst/powrst), true => average saved and actual flux
     logical, intent(in) :: corrector
     !> saved power from predictor to corrector
     real(C_DOUBLE), intent(inout) :: powrst
     !> saved flux from predictor to corrector
     real(C_DOUBLE), intent(inout) :: fluxst
     !> user-given flux (if index is 0; otherwise not used)
     real(C_DOUBLE), intent(inout) :: flux
     !> user-given power (if index is 1; otherwise not used)
     real(C_DOUBLE), intent(inout) :: power
     !> is this a zero-flux step?
     logical, intent(in) :: zero_flux_step
     !> depletion by flux or by power?
     logical, intent(in) :: input_by_flux
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     ! relative saved/actual flux difference
     real(C_DOUBLE) :: delf
     !-----------------------------------------------
     if (.not. zero_flux_step) then
       if (corrector) then
         if (.not. input_by_flux) then
           delf   = abs(1.0 - flux/fluxst)
           if (delf > 0.2d0) then
              scalereportwarning(1,*)'The flux over a step has changed by more than 20%.' ; scalefinalizewarning()
           end if
           flux = (flux + fluxst)/2.0
         else
           power = (power + powrst)/2.0
         end if
       else
         fluxst = flux
         powrst = power
       end if
     end if
subroutine depletion::powerf (type(origen_librarywrapper), intent(in) lib, integer, intent(in) itot, real(c_double), intent(out) factor, real(c_double), intent(in) fission_rate, real(c_double), dimension(itot), intent(in) concentrations, logical, intent(in) zero_flux_step)
Calculate the power-flux conversion factor, based on given fission rate and given concentrations.
Parameters
[in] lib Library data
[in] itot Total number of nuclides
[out] factor power-flux factor to be calculated
[in] fission_rate normalization factor
[in] concentrations used concentrations (usually XTEMP)
[in] zero_flux_step is this a zero-flux step?
Cycle variables
Temporary local copies of library data objects
Energy library size
Nuclide IDs in energy library
Fission energy in energy library
Prompt gamma capture energy (mev) fission energy in energy library
Populate local array copies
Garbage collection
Referenced by powerflux().
     !-----------------------------------------------
     !   M o d u l e s
     !-----------------------------------------------
     use iso_c_binding, only: c_double
     implicit none
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Library data
     type(origen_librarywrapper), intent(in) :: lib
     !> Total number of nuclides
     integer, intent(in) :: itot
     !> power-flux factor to be calculated
     real(C_DOUBLE), intent(out) :: factor
     !> normalization factor
     real(C_DOUBLE), intent(in) :: fission_rate
     !> used concentrations (usually XTEMP)
     real(C_DOUBLE), intent(in) :: concentrations(itot)
     !> is this a zero-flux step?
     logical, intent(in) :: zero_flux_step
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> Cycle variables
     integer :: i, k
     !>
     real(C_DOUBLE) :: total_capture_energy
     !>
     real(C_DOUBLE) :: capture_energy
     !>
     real(C_DOUBLE) :: total_absorption
     !>
     real(C_DOUBLE) :: total_fission_energy
     !>
     real(C_DOUBLE) :: fission_energy
     !> Temporary local copies of library data objects
     integer, allocatable :: nucl(:)
     integer, allocatable :: typ_nuc(:)
     real(C_DOUBLE), allocatable :: fiss(:)
     real(C_DOUBLE), allocatable :: tocap(:)
     !> Energy library size
     integer , parameter :: nl = 56
     !> Nuclide IDs in energy library
     integer , dimension(nl) :: iza = (/&
                 10010,  50100,  80160, 260560, 280580, 400900, 400910, &
        400920, 400960, 420950, 430950, 441010, 451030, 451050, 471090, &
        541310, 541350, 551330, 551340, 601430, 601450, 611470, 611480, &
        611481, 621470, 621490, 621500, 621510, 621520, 631530, 631540, &
        631550, 902300, 902320, 902330, 912310, 912330, 922320, 922330, &
        922340, 922350, 922360, 922380, 932370, 932390, 942380, 942390, &
        942400, 942410, 942420, 942430, 952410, 952421, 952430, 962440, &
        962450 /)
     !> Fission energy in energy library
     real(C_DOUBLE) , dimension(nl) :: fission_energy_table =  (/  &
                  0.0d0,    0.0d0,    0.0d0,     0.0d0,    0.0d0,    0.0d0,    0.0d0,    &
        0.0d0,    0.0d0,    0.0d0,    0.0d0,     0.0d0,    0.0d0,    0.0d0,    0.0d0,    &
        0.0d0,    0.0d0,    0.0d0,    0.0d0,     0.0d0,    0.0d0,    0.0d0,    0.0d0,    &
        0.0d0,    0.0d0,    0.0d0,    0.0d0,     0.0d0,    0.0d0,    0.0d0,    0.0d0,    &
        0.0d0,    190.0d0,  189.21d0, 190.0d0,   190.0d0,  189.1d0,  200.0d0,  191.29d0, &
        190.30d0, 194.02d0, 192.80d0, 198.122d0, 195.10d0, 200.0d0,  197.80d0, 200.05d0, &
        199.79d0, 202.22d0, 200.62d0, 200.0d0,   202.3d0,  202.29d0, 202.1d0,  200.0d0, &
        200.0d0 /)
     !> Prompt gamma capture energy (mev) fission energy in energy library
     real(C_DOUBLE) , dimension(nl) :: capture_energy_table = (/ &
                   2.2246d0, 2.79d0,   4.143d0,  7.60d0,   9.02d0,   7.2026d0, 8.6351d0, &
        6.758d0,   5.571d0,  9.1542d0, 7.71d0,   9.2161d0, 6.9993d0, 7.0941d0, 6.825d0,  &
        8.9363d0,  7.880d0,  6.7044d0, 6.550d0,  7.8174d0, 7.5654d0, 5.90d0,   7.266d0,  &
        7.266d0,   8.1402d0, 7.9824d0, 5.596d0,  8.258d0,  5.867d0,  6.444d0,  8.167d0,  &
        6.490d0,   5.01d0,   4.786d0,  6.08d0,   5.66d0,   5.197d0,  5.93d0,   6.841d0,  &
        5.297d0,   6.5451d0, 5.124d0,  4.804d0,  5.49d0,   4.97d0,   5.55d0,   6.533d0,  &
        5.241d0,   6.301d0,  5.071d0,  6.02d0,   5.529d0,  6.426d0,  5.363d0,  6.451d0,  &
        6.11d0 /)
     factor = 1.0d0
     if (zero_flux_step) return
     jdebugline2("Fission rate = ", fission_rate)
     !> Populate local array copies
     call lib%get_nucl(nucl)
     call lib%get_typ_nuc(typ_nuc)
     call lib%get_fiss(fiss)
     call lib%get_tocap(tocap)
     total_capture_energy = 0.d0
     total_fission_energy = 0.d0
     do i = 1, lib%get_itot()
       capture_energy = 5.0d0  ! default prompt gamma capture energy (mev)
       fission_energy = 200.d0 ! default fission energy
       ! find capture_energy and fission_energy
       find_fission: do k = 1, nl
         if (nucl(i) == iza(k)) then
           capture_energy = capture_energy_table(k)
           fission_energy = fission_energy_table(k)
           exit find_fission
         end if
       end do find_fission
       if (concentrations(i) > err) then
         ! calculate absorption XS
         total_absorption = tocap(i)
         if (typ_nuc(i) == 2) total_absorption = tocap(i) - fiss(i-lib%get_ilite())
         ! add to total energy release due to capture
         total_capture_energy = total_capture_energy + total_absorption * concentrations(i) * capture_energy
         ! add to total energy release due to fission
         if (typ_nuc(i) == 2 ) then
           total_fission_energy = total_fission_energy + fiss(i-lib%get_ilite()) * concentrations(i) * fission_energy
         end if
       end if
     end do
     ! calculate the power-flux factor
     factor = (total_capture_energy + total_fission_energy) * 9.6483d-20  !MW.s
     !> Garbage collection
     deallocate(nucl)
     deallocate(typ_nuc)
     deallocate(fiss)
     deallocate(tocap)