ORIGEN API: kernel_radau5 Module Reference
kernel_radau5 Module Reference
Wrapper for the 3rd party RADAU5 solver.
Functions/Subroutines
subroutine fcn (n, t, y, f)
subroutine jac ()
subroutine solout ()
subroutine radau5_solve (trx, itot, non, n0, n, delta_t, diag, a, b, zero_flux_step, is_adjoint, abstol, reltol)
Variables
type(origen_transitionmatrixp) xtrx
Library data (NOTE: THIS CLASS IS NOT THREAD SAFE!)
integer, dimension(:), allocatable xloc
parent locations
real(c_double), dimension(:), allocatable xd
Diagonal elements of the transition matrix.
real(c_double), dimension(:), allocatable xa
Nondiagonal elements of the transition matrix.
real(c_double), dimension(:), allocatable xb
Right side of the equation (source term)
real(c_double) fake_flux
fake flux level to last_transition is decay if=0
Detailed Description
Wrapper for the 3rd party RADAU5 solver.
Function/Subroutine Documentation
subroutine kernel_radau5::fcn (integer, intent(in) n, real(c_double), intent(in) t, real(c_double), dimension(n), intent(in) y, real(c_double), dimension(n), intent(out) f)
References fake_flux, xa, xb, xd, xloc, and xtrx.
Referenced by radau5_solve().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     integer, intent(in) :: n
     real(C_DOUBLE), intent(in) :: t
     real(C_DOUBLE), dimension(n), intent(in) :: y
     real(C_DOUBLE), dimension(n), intent(out) :: f
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     integer :: i, j
     do i = 1, xtrx % get_itot()
       f(i) = y(i) * xd(i) + xb(i)
       do j = xtrx%first_transition(i), xtrx%last_transition(i,fake_flux)
         f(i) = f(i) + y(xloc(j)) * xa(j)
       end do
     end do
subroutine kernel_radau5::jac ()
Referenced by radau5_solve().
subroutine kernel_radau5::solout ()
Referenced by radau5_solve().
subroutine kernel_radau5::radau5_solve (type(origen_transitionmatrixp), intent(in) trx, integer, intent(in) itot, integer, intent(in) non, real(c_double), dimension(itot), intent(in) n0, real(c_double), dimension(itot), intent(out) n, real(c_double), intent(in) delta_t, real(c_double), dimension(itot), intent(in) diag, real(c_double), dimension(non), intent(in) a, real(c_double), dimension(itot), intent(in) b, logical, intent(in) zero_flux_step, logical, intent(in) is_adjoint, real(c_double), intent(in) abstol, real(c_double), intent(in) reltol)
Parameters
[in] trx Library data
[in] itot Total number of nuclides
[in] non Number of non-zero matrix elements
[in] diag Diagonal elements of the transition matrix
[in] a Nondiagonal elements of the transition matrix
[in] b Right side of the equation (source term)
[in] n0 initial concentrations
[out] n final concentrations
[in] delta_t Time step length in seconds
[in] zero_flux_step is this a zero-flux (=decay) step?
[in] is_adjoint is this an adjoint calculation?
[in] abstol solver options
[in] reltol solver options
References fake_flux, fcn(), jac(), radau5(), origen_iofunctions_m::rstop(), solout(), xa, xb, xd, xloc, and xtrx.
Referenced by depletion::depletion_step().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Library data
     type(origen_transitionmatrixp), intent(in) :: trx
     !> Total number of nuclides
     integer, intent(in) :: itot
     !> Number of non-zero matrix elements
     integer, intent(in) :: non
     !> Diagonal elements of the transition matrix
     real(C_DOUBLE), intent(in) :: diag(itot)
     !> Nondiagonal elements of the transition matrix
     real(C_DOUBLE), intent(in) :: a(non)
     !> Right side of the equation (source term)
     real(C_DOUBLE), intent(in) :: b(itot)
     !> initial concentrations
     real(C_DOUBLE), intent(in) :: n0(itot)
     !> final concentrations
     real(C_DOUBLE), intent(out) :: n(itot)
     !> Time step length in seconds
     real(C_DOUBLE), intent(in) :: delta_t
     !> is this a zero-flux (=decay) step?
     logical, intent(in) :: zero_flux_step
     !> is this an adjoint calculation?
     logical, intent(in) :: is_adjoint
     !> solver options
     real(C_DOUBLE), intent(in) :: abstol,reltol
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     integer :: lwork, liwork, ijac, mljac, mujac, i
     real(C_DOUBLE) :: t, rtol(itot), atol(itot), rpar(1)
     integer :: ipar(1)
     real(C_DOUBLE), allocatable :: work(:)
     integer, allocatable :: iwork(:)
     integer :: idid
     lwork = itot*(itot*4+12) *10
     liwork = 3*itot+20           *10
     allocate(xa(non))
     allocate(xb(itot))
     allocate(xd(itot))
     allocate(work(lwork))
     allocate(iwork(liwork))
     xa(:) = a(:)
     xb(:) = b(:)
     xd(:) = diag(:)
     xtrx  = trx
     call xtrx % get_loc_array(xloc)
     fake_flux = 1.0d0
     if( zero_flux_step )fake_flux = 0.0d0
     t = 0
     n = n0
     atol = abstol
     rtol = reltol
     work(:20) = 0.0d0
     iwork(:) = 0
     iwork(5) = itot
     ijac = 0
     mljac=itot
     mujac = 0
     jdebugline("Running RADAU5 solver")
     jdebugline2("Sum of transition matrix is", sum(xa(:non)))
     jdebugline2("Absolute tolerance is ", abstol)
     jdebugline2("Relative tolerance is ", reltol)
     call radau5(itot, fcn, t, n, delta_t, t/1000, &
          rtol,atol,1,jac,ijac,mljac,mujac,&
          solout,0,0,0,solout,0,work,lwork,iwork,liwork,rpar,ipar,idid)
     jdebugline("Finished")
     deallocate(xa)
     deallocate(xb)
     deallocate(xd)
     deallocate(work)
     deallocate(iwork)
     if (idid .ne. 1) call rstop("RADAU5 failure", 913)
Variable Documentation
type(origen_transitionmatrixp) xtrx
Library data (NOTE: THIS CLASS IS NOT THREAD SAFE!)
Referenced by fcn(), and radau5_solve().
   type(origen_transitionmatrixp) :: xtrx
integer, dimension(:), allocatable xloc
parent locations
Referenced by fcn(), and radau5_solve().
   integer, allocatable :: xloc(:)
real(c_double), dimension(:), allocatable xd
Diagonal elements of the transition matrix.
Referenced by fcn(), and radau5_solve().
   real(C_DOUBLE), allocatable :: xd(:)
real(c_double), dimension(:), allocatable xa
Nondiagonal elements of the transition matrix.
Referenced by fcn(), and radau5_solve().
   real(C_DOUBLE), allocatable :: xa(:)
real(c_double), dimension(:), allocatable xb
Right side of the equation (source term)
Referenced by fcn(), and radau5_solve().
   real(C_DOUBLE), allocatable :: xb(:)
real(c_double) fake_flux
fake flux level to last_transition is decay if=0
Referenced by fcn(), and radau5_solve().
   real(C_DOUBLE) :: fake_flux