ORIGEN API: History< Q > Class Template Reference
History< Q > Class Template Reference
#include <History.h>
Public Types
typedef Quantity< Time > T
typedef History< Q > Type
Public Member Functions
T::SCP t (size_t i) const
T::SCP t0 () const
T::SCP tn () const
double dt (size_t i, typename T::Units u) const
Q::SCP q (size_t i) const
double dq (size_t i, typename Q::Units u) const
size_t n () const
void add (typename T::SP t, typename Q::SP q, Representation rep=Representation::CONSTANT)
bool good () const
virtual bool good (std::vector< std::string > &errors) const
virtual std::string toString () const
Protected Member Functions
virtual void synchronize ()
Protected Attributes
std::vector< typename Q::SP > b_quantities
std::vector< Representation > b_reps
std::vector< T::SP > b_times
Detailed Description
template<typename Q = U::SP>
class Origen::History< Q >
Examples:
Core/dc/tests/tstHistory.cpp.
Member Typedef Documentation
typedef Quantity<Time> T
typedef History<Q> Type
Member Function Documentation
T::SCP t (size_t i) const inline
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     if( b_times.size() == 0 ) return nullptr;
     if( i >= b_times.size() ) return nullptr;
     return b_times[i];
 }
T::SCP t0 () const inline
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     return t( 0 );
 }
T::SCP tn () const inline
 {
     return t( n() - 1 );
 }
double dt (size_t i, typename T::Units u) const inline
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     if( i + 1 < n() )
     {
         return t( i + 1 )->valueAs( u ) - t( i )->valueAs( u );
     }
     return 0.0;
 }
Q::SCP q (size_t i) const inline
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     if( b_quantities.size() == 0 ) return nullptr;
     if( i >= b_quantities.size() ) return nullptr;
     return b_quantities[i];
 }
double dq (size_t i, typename Q::Units u) const inline
 {
     if( i + 1 < n() )
     {
         return q( i + 1 )->valueAs( u ) - q( i )->valueAs( u );
     }
     return 0.0;
 }
size_t n () const inline
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     return b_times.size();
 }
void add (typename T::SP t, typename Q::SP q, Representation rep = Representation::CONSTANT) inline
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     // fix the incremental association on way in
     if( !t->isIncremental() && b_times.size() > 0 )
         t->setIncrementalFrom( b_times[0] );
     b_times.push_back( t );
     b_quantities.push_back( q );
     b_reps.push_back( rep );
     synchronize();
 }
bool good () const inline
 {
     Vec_Str v;
     return good( v );
 }
bool good (std::vector< std::string > & errors) const inline virtual
References Time::SECONDS.
 {
     size_t nerr = errors.size();
     for( size_t i = 0; i < n() - 1; ++i )
     {
         double t1 = t( i )->valueAs( Time::SECONDS );
         double t2 = t( i + 1 )->valueAs( Time::SECONDS );
         if( t1 > t2 )
         {
             errors.push_back(
                 nprintf( "time[%d]=%8s > time[%d]=%8s in time list",
                          i,
                          t( i )->toString().c_str(),
                          i + 1,
                          t( i + 1 )->toString().c_str() ) );
         }
     }
     return nerr == errors.size();
 }
std::string toString () const inline virtual
Examples:
Core/dc/tests/tstHistory.cpp.
Referenced by TEST().
 {
     std::string s = nprintf( "%12s %12s\n", "time", "quantity" );
     for( size_t i = 0; i < b_times.size(); ++i )
     {
         std::string tstr( t( i )->toString() );
         std::string qstr( q( i )->toString() );
         s += nprintf( "%12s %12s\n", tstr.c_str(), qstr.c_str() );
     }
     return s;
 }
void synchronize () inline protected virtual
 {
     // null-op
     // just to possibly extend the class
 }
Member Data Documentation
std::vector<typename Q::SP> b_quantities protected
std::vector<Representation> b_reps protected
std::vector<T::SP> b_times protected
The documentation for this class was generated from the following files:
Core/dc/History.h
Core/dc/History.i.h