ORIGEN API: LibraryIO_s62b Class Reference
LibraryIO_s62b Class Reference
#include <LibraryIO_s62b.h>
Public Member Functions
bool read (Library &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const Library &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Member Function Documentation
bool read (Library & obj, std::istream & stream, ScaleUtils::IO::DB opts)
References DecayData::abund_of_lite_nuclides, Library::add_transition_coeff(), TransitionCoeff::burnup(), DecayData::decay_constants, DecayData::fissionable_nuclide_ids, Origen::get_default_kappas(), NuclideSet::ids(), NuclideSet::looks_like_zzzaaai(), LibraryHeader::nuclide_set(), Origen::populateLibraryAbundance(), Origen::populateLibraryMass(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, Origen::detail::read(), DecayData::recoverable_energy_values, TransitionCoeff::set_burnup(), LibraryHeader::set_day_made(), Library::set_decay_data(), Library::set_definition(), TransitionCoeff::set_fission_xs(), TransitionCoeff::set_flux(), TransitionCoeff::set_kappa_capture(), TransitionCoeff::set_kappa_fission(), TransitionCoeff::set_loss_xs(), TransitionCoeff::set_matrix(), LibraryHeader::set_month_made(), TransitionCoeff::set_neutron_yields(), LibraryHeader::set_nuclide_set(), TransitionStructure::set_num_decay_parents(), TransitionStructure::set_num_parents(), TransitionStructure::set_parent_positions(), LibraryHeader::set_title(), TransitionStructure::set_transition_ids(), Library::set_transition_structure(), LibraryHeader::set_year_made(), and Origen::detail::setupEndianness().
bool write (const Library & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
References DecayData::abund_of_lite_nuclides, TransitionCoeff::burnup(), NuclideSet::convert_sizzzaaa_to_zzzaaai(), NuclideSet::count_sublibs(), LibraryHeader::day_made(), DecayData::decay_constants, Library::decay_data(), Library::definition(), TransitionCoeff::fission_xs(), TransitionCoeff::fission_xs_size(), DecayData::fissionable_nuclide_ids, TransitionCoeff::flux(), TransitionCoeff::flux_size(), NuclideSet::has_sublibs(), NuclideSet::ids(), NuclideSet::ids_size(), TransitionCoeff::loss_xs(), TransitionCoeff::loss_xs_size(), TransitionCoeff::matrix(), TransitionCoeff::matrix_size(), LibraryHeader::month_made(), TransitionCoeff::neutron_yields(), TransitionCoeff::neutron_yields_size(), LibraryHeader::nuclide_set(), TransitionStructure::num_decay_parents(), TransitionStructure::num_decay_parents_size(), NuclideSet::num_in_sublib(), TransitionStructure::num_parents(), TransitionStructure::num_parents_size(), TransitionStructure::parent_positions(), TransitionStructure::parent_positions_size(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, DecayData::recoverable_energy_values, Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, Origen::SUBLIB_3FP, LibraryHeader::title(), NuclideSet::total_nuclides(), TransitionStructure::total_transitions(), Library::transition_coeff_at(), Library::transition_coeff_size(), TransitionStructure::transition_ids(), TransitionStructure::transition_ids_size(), Library::transition_structure(), Origen::detail::writeScale61Title(), and LibraryHeader::year_made().
The documentation for this class was generated from the following files:
Core/io/LibraryIO_s62b.h
Core/io/LibraryIO_s62b.cpp