ORIGEN API: Removal Class Reference
Removal Class Reference
#include <Removal.h>
Stores removal constants.
Public Types
typedef std::shared_ptr< Removal > SP
Public Member Functions
Removal (const Vec_Int &ids, const Vec_Dbl &vals)
int size () const
const int & ids (int i) const
const double & vals (int i) const
void to_nuclides (const Vec_Int &sizzzaaa_list, Vec_Dbl *vals_list, bool use_cached=false) const
Static Public Member Functions
static SP create (const Vec_Int &ids, const Vec_Dbl &vals)
Protected Attributes
Vec_Int b_ids
Vec_Dbl b_vals
Vec_Int b_map_ids_to_nuclides
Detailed Description
Stores removal constants.
Member Typedef Documentation
typedef std::shared_ptr<Removal> SP
Constructor & Destructor Documentation
Removal (const Vec_Int & ids, const Vec_Dbl & vals)
References Removal::b_ids, and Removal::b_vals.
Member Function Documentation
Removal::SP create (const Vec_Int & ids, const Vec_Dbl & vals) static
Examples:
tstMaterial.cpp.
References Removal::ids(), and Removal::vals().
Referenced by Origen::test::TEST().
int size () const
References Removal::b_ids.
Referenced by Removal::to_nuclides().
const int & ids (int i) const
References Removal::b_ids.
Referenced by Removal::create().
const double & vals (int i) const
References Removal::b_vals.
Referenced by Removal::create().
void to_nuclides (const Vec_Int & sizzzaaa_list, Vec_Dbl * vals_list, bool use_cached = false) const
References Removal::b_ids, Removal::b_map_ids_to_nuclides, Removal::b_vals, and Removal::size().
Member Data Documentation
Vec_Int b_ids protected
Referenced by Removal::ids(), Removal::Removal(), Removal::size(), and Removal::to_nuclides().
Vec_Dbl b_vals protected
Referenced by Removal::Removal(), Removal::to_nuclides(), and Removal::vals().
Vec_Int b_map_ids_to_nuclides mutable protected
Referenced by Removal::to_nuclides().
The documentation for this class was generated from the following files:
Core/dc/Removal.h
Core/dc/Removal.cpp