ORIGEN API: Power Struct Reference
Power Struct Reference
#include <Power.h>
Public Types
enum UNITS { UNKNOWN = -1, WATT , END }
Static Public Member Functions
template<Power::UNITS u>
static std::string name ()
static std::string name (Power::UNITS u)
template<Power::UNITS u>
static double base ()
static double base (Power::UNITS u)
template<Power::UNITS to, Power::UNITS from>
static double factor ()
template<Power::UNITS to>
static double factor (Power::UNITS from)
static double factor (Power::UNITS to, Power::UNITS from)
static Power::UNITS units (const char *s)
static constexpr Power::UNITS units (int i)
Static Public Attributes
static const UNITS DEFAULT = WATT
Detailed Description
Examples:
Core/dc/tests/tstPower.cpp.
Member Enumeration Documentation
enum UNITS
Enumerator
UNKNOWN
WATT
END
Member Function Documentation
static std::string name () static
std::string name (Power::UNITS u) inline static
static double base () static
Examples:
Core/dc/tests/tstPower.cpp.
Referenced by Power::base(), Power::factor(), and TEST().
double base (Power::UNITS u) inline static
References Power::base().
static double factor () inline static
static double factor (Power::UNITS from) inline static
static double factor (Power::UNITS to, Power::UNITS from) inline static
References Power::base().
Power::UNITS units (const char * s) inline static
static constexpr Power::UNITS units (int i) inline static
Member Data Documentation
const UNITS DEFAULT = WATT static
The documentation for this struct was generated from the following files:
Core/dc/Power.h
Core/dc/Power.i.h