ORIGEN API: origen_neutron_class Type Reference
origen_neutron_class Type Reference
Class handling the neutron calculations.
Public Member Functions
procedure, public init => orgneut__init
Constructor.
procedure, public destroy => orgneut__destroy
Destructor.
procedure nucalc => orgneut__nucalc
Perform the neutron calculations.
procedure, public output => orgneut__output
Print the neutron output tables.
procedure, public output_detailed_source => orgneut__output_detailed_source
Print the detailed neutron source data.
procedure output_source => orgneut__output_source
Prints the neutron source tables.
procedure output_spectra => orgneut__output_spectra
Print neutron spectra: alpha-n, spon-fiss, delayed neutron, total.
procedure define_matrix_uo2 => orgneut__define_matrix_uo2
Define UO2 (a,n) source matrix.
procedure define_matrix_glass => orgneut__define_matrix_glass
Define borosilicate glass (a,n) source matrix.
procedure define_arbitrary_matrix => orgneut__define_arbitrary_matrix
Define (a,n) source matrix based on actual concentrations in the NSTAR step.
procedure order_sources => orgneut__order_sources
procedure order_target => orgneut__order_target
Detailed Description
Class handling the neutron calculations.
Member Function/Subroutine Documentation
procedure, public init ()
Constructor.
procedure, public destroy ()
Destructor.
procedure nucalc ()
Perform the neutron calculations.
procedure, public output ()
Print the neutron output tables.
procedure, public output_detailed_source ()
Print the detailed neutron source data.
procedure output_source ()
Prints the neutron source tables.
procedure output_spectra ()
Print neutron spectra: alpha-n, spon-fiss, delayed neutron, total.
procedure define_matrix_uo2 ()
Define UO2 (a,n) source matrix.
procedure define_matrix_glass ()
Define borosilicate glass (a,n) source matrix.
procedure define_arbitrary_matrix ()
Define (a,n) source matrix based on actual concentrations in the NSTAR step.
procedure order_sources ()
procedure order_target ()
References auxiliary::flip(), auxiliary::nuclide_compact(), auxiliary::output(), auxiliary::print_break(), auxiliary::print_hrule(), auxiliary::print_multigroup_table(), auxiliary::print_multigroup_time_table(), auxiliary::print_time_table(), auxiliary::table_banner(), auxiliary::table_tail(), and origen_neutron::totaln().
Member Data Documentation
integer nsteps
Number of steps.
type(origen_librarywrapper), pointer lib => NULL()
associated ORIGEN library
type(neutron_library_class), pointer nlib => NULL()
associated neutron library
type(origen_neutron_options) opts
set of options
real(c_double), dimension(:,:), allocatable source_sf
final spontaneous fission source by nuclide [libiact * 0:nsteps]
real(c_double), dimension(:,:), allocatable source_an
alpha,n source term by nuclide [libiact+libifp * 0:nsteps]
real(c_double), dimension(:,:), allocatable source_dn
delayed neutron sources [libifp * 0:nsteps]
real(c_double), dimension(:,:), allocatable spectrum_an
alpha,n neutron spectra [ngroups * 0:nsteps]
real(c_double), dimension(:,:), allocatable spectrum_sf
spontaneous fission neutron spectra [ngroups * 0:nsteps]
real(c_double), dimension(:,:), allocatable spectrum_dn
delayed neutron spectra [ngroups * 0:nsteps]
real(c_double), dimension(:,:), allocatable spectrum
final total neutron spectra [ngroups * 0:nsteps]
integer n_source_nuclides
number of sources nuclides
integer, dimension(:), allocatable source_nuclides
list of source nuclides - ZAI [n_source_nuclides]
integer, dimension(:), allocatable source_nuclide_indexes
list of source nuclides - M [n_source_nuclides]
real(c_double), dimension(:), allocatable source_branching
source nuclide total alpha branching ratios [n_source_nuclides]
real(c_double), dimension(:), allocatable source_lambdas
decay constants of source nuclides [n_source_nuclides]
real(c_double), dimension(:,:), allocatable source_concentrations
concentrations of the source nuclides [n_source_nuclides,0:nsteps]
integer sf_source_n
number of SF neutron sources
character(len=20), dimension(:), allocatable sf_source_nuclides
spontaneous fission neutron source nuclides [itot]
real(c_double), dimension(:,:), allocatable sf_source_data
spontaneous fission neutron source data [itot, 6]
real(c_double), dimension(:,:), allocatable sf_source_spectra
spontaneous fission neutron spectra by source nuclide [ngroups, itot]
integer dn_source_n
number of delayed neutron source nuclides
character(20), dimension(:), allocatable dn_source_nuclides
delayed neutron source nuclides [itot]
real(c_double), dimension(:,:), allocatable dn_source_data
delayed neutron source [itot, 5]
real(c_double), dimension(:,:), allocatable dn_source_spectra
delayed neutron spectra by source nuclide [ngroups, itot]
real(c_double) average_energy_an
average neutron energy (a,n)
real(c_double) average_energy_sf
average neutron energy (SF)
real(c_double) average_energy_dn
average neutron energy (DN)
real(c_double) average_energy
average neutron energy (total)
real(c_double), dimension(:,:), allocatable an_target_spectra
[ngroups, n_target]
integer n_matrix
integer, dimension(:), allocatable matrix_z
real(c_double), dimension(:), allocatable matrix_x
integer n_target
integer, dimension(:), allocatable target_n
real(c_double), dimension(:), allocatable target_x
logical noneut
flag for lack of neutron calculations data
The documentation for this type was generated from the following file:
Manager/emit/origen_neutron.f90