ORIGEN API: gamma_library Module Reference
gamma_library Module Reference
gamma emission source reader
Data Types
type gamma_library_class
Gamma library; provides a wrapper around the gamma data libraries.
type origen_gamma_options
Options for gamma calculation and output.
Functions/Subroutines
real(c_double) function next_larger_brem_continuum_energy (index, e_target)
real(c_double) function min_brem_continuum_energy ()
real(c_double) function max_brem_continuum_energy ()
subroutine setup_brem_continuum_e_bounds ()
subroutine dump_orig_spectra_de (title, unit, energy, tally, nuc_id)
subroutine dump_orig_spectra (title, unit, energy, tally, nuc_id)
subroutine dump_binned_spectra_de (title, unit, energy, tally, nuc_id)
subroutine dump_binned_spectra (title, unit, energy, tally, nuc_id)
Variables
integer, parameter gamma_library_unit = 10
default IO unit for the library
type(fileutils), private resolver
integer, private pass_number = 0
real(c_double), dimension(:), allocatable, private brem_continuum_e_bounds
real(c_double), private bin_boundary_match_tol =1d-5
Detailed Description
gamma emission source reader
Function/Subroutine Documentation
real(c_double) function gamma_library::next_larger_brem_continuum_energy (integer, intent(inout) index, real(c_double), intent(in) e_target)
References bin_boundary_match_tol, brem_continuum_e_bounds, max_brem_continuum_energy(), min_brem_continuum_energy(), and setup_brem_continuum_e_bounds().
Referenced by setup_brem_continuum_e_bounds().
   integer,intent(inout) :: index
   real(C_DOUBLE) :: e
   real(C_DOUBLE),intent(in) :: e_target
   integer :: i
   call setup_brem_continuum_e_bounds()
   if( approx_ge(e_target,max_brem_continuum_energy(),bin_boundary_match_tol) )then
     index = 1
     e = max_brem_continuum_energy()
     return
   else if( approx_lt(e_target,min_brem_continuum_energy(),bin_boundary_match_tol) )then
     index = size(brem_continuum_e_bounds,1)
     e = min_brem_continuum_energy()
     return
   end if
   !look for a match starting from the top
   !!!0SErrLine(1,*)'searching for e_target=',e_target
   do i=1,size(brem_continuum_e_bounds,1)
     !matches target energy
     if( approx_le(brem_continuum_e_bounds(i),e_target,bin_boundary_match_tol) )then
       index = i - 1
       e = brem_continuum_e_bounds(index)
       return
     end if
   end do
   !fail condition
   index = 0
   e = 0.0
real(c_double) function gamma_library::min_brem_continuum_energy ()
References brem_continuum_e_bounds, and setup_brem_continuum_e_bounds().
Referenced by dump_orig_spectra(), dump_orig_spectra_de(), and next_larger_brem_continuum_energy().
     real(C_DOUBLE) :: e
     call setup_brem_continuum_e_bounds()
     e=brem_continuum_e_bounds(size(brem_continuum_e_bounds,1))
real(c_double) function gamma_library::max_brem_continuum_energy ()
References brem_continuum_e_bounds, and setup_brem_continuum_e_bounds().
Referenced by dump_orig_spectra(), dump_orig_spectra_de(), and next_larger_brem_continuum_energy().
     real(C_DOUBLE) :: e
     call setup_brem_continuum_e_bounds()
     e=brem_continuum_e_bounds(1)
subroutine gamma_library::setup_brem_continuum_e_bounds ()
References brem_continuum_e_bounds, dump_binned_spectra(), dump_binned_spectra_de(), dump_orig_spectra(), dump_orig_spectra_de(), gamma_library_unit, next_larger_brem_continuum_energy(), pass_number, and resolver.
Referenced by max_brem_continuum_energy(), min_brem_continuum_energy(), and next_larger_brem_continuum_energy().
     if( .not. allocated(brem_continuum_e_bounds) )then
       allocate(brem_continuum_e_bounds(71))
       brem_continuum_e_bounds( 1)=1.40d+01
       brem_continuum_e_bounds( 2)=1.30d+01
       brem_continuum_e_bounds( 3)=1.20d+01
       brem_continuum_e_bounds( 4)=1.10d+01
       brem_continuum_e_bounds( 5)=1.00d+01
       brem_continuum_e_bounds( 6)=9.00d+00
       brem_continuum_e_bounds( 7)=8.00d+00
       brem_continuum_e_bounds( 8)=7.00d+00
       brem_continuum_e_bounds( 9)=6.00d+00
       brem_continuum_e_bounds(10)=5.00d+00
       brem_continuum_e_bounds(11)=4.00d+00
       brem_continuum_e_bounds(12)=3.60d+00
       brem_continuum_e_bounds(13)=3.20d+00
       brem_continuum_e_bounds(14)=2.80d+00
       brem_continuum_e_bounds(15)=2.40d+00
       brem_continuum_e_bounds(16)=2.00d+00
       brem_continuum_e_bounds(17)=1.90d+00
       brem_continuum_e_bounds(18)=1.80d+00
       brem_continuum_e_bounds(19)=1.70d+00
       brem_continuum_e_bounds(20)=1.60d+00
       brem_continuum_e_bounds(21)=1.50d+00
       brem_continuum_e_bounds(22)=1.40d+00
       brem_continuum_e_bounds(23)=1.30d+00
       brem_continuum_e_bounds(24)=1.20d+00
       brem_continuum_e_bounds(25)=1.10d+00
       brem_continuum_e_bounds(26)=1.00d+00
       brem_continuum_e_bounds(27)=9.00d-01
       brem_continuum_e_bounds(28)=8.00d-01
       brem_continuum_e_bounds(29)=7.00d-01
       brem_continuum_e_bounds(30)=6.00d-01
       brem_continuum_e_bounds(31)=5.00d-01
       brem_continuum_e_bounds(32)=4.40d-01
       brem_continuum_e_bounds(33)=3.80d-01
       brem_continuum_e_bounds(34)=3.20d-01
       brem_continuum_e_bounds(35)=2.60d-01
       brem_continuum_e_bounds(36)=2.00d-01
       brem_continuum_e_bounds(37)=1.80d-01
       brem_continuum_e_bounds(38)=1.60d-01
       brem_continuum_e_bounds(39)=1.40d-01
       brem_continuum_e_bounds(40)=1.20d-01
       brem_continuum_e_bounds(41)=1.00d-01
       brem_continuum_e_bounds(42)=9.00d-02
       brem_continuum_e_bounds(43)=8.00d-02
       brem_continuum_e_bounds(44)=7.00d-02
       brem_continuum_e_bounds(45)=6.00d-02
       brem_continuum_e_bounds(46)=5.00d-02
       brem_continuum_e_bounds(47)=4.60d-02
       brem_continuum_e_bounds(48)=4.20d-02
       brem_continuum_e_bounds(49)=3.80d-02
       brem_continuum_e_bounds(50)=3.40d-02
       brem_continuum_e_bounds(51)=3.00d-02
       brem_continuum_e_bounds(52)=2.80d-02
       brem_continuum_e_bounds(53)=2.60d-02
       brem_continuum_e_bounds(54)=2.40d-02
       brem_continuum_e_bounds(55)=2.20d-02
       brem_continuum_e_bounds(56)=2.00d-02
       brem_continuum_e_bounds(57)=1.90d-02
       brem_continuum_e_bounds(58)=1.80d-02
       brem_continuum_e_bounds(59)=1.70d-02
       brem_continuum_e_bounds(60)=1.60d-02
       brem_continuum_e_bounds(61)=1.50d-02
       brem_continuum_e_bounds(62)=1.40d-02
       brem_continuum_e_bounds(63)=1.30d-02
       brem_continuum_e_bounds(64)=1.20d-02
       brem_continuum_e_bounds(65)=1.10d-02
       brem_continuum_e_bounds(66)=1.00d-02
       brem_continuum_e_bounds(67)=9.00d-03
       brem_continuum_e_bounds(68)=8.00d-03
       brem_continuum_e_bounds(69)=7.00d-03
       brem_continuum_e_bounds(70)=6.00d-03
       brem_continuum_e_bounds(71)=5.00d-03
     end if
subroutine gamma_library::dump_orig_spectra_de (character(*), intent(in) title, integer unit, real, dimension(:), intent(in) energy, real, dimension(:), intent(in) tally, integer nuc_id)
References max_brem_continuum_energy(), and min_brem_continuum_energy().
Referenced by setup_brem_continuum_e_bounds().
     character(*),intent(in) :: title
     integer :: unit
     real,intent(in) :: energy(:)
     real,intent(in) :: tally(:)
     integer :: g,gindex
     integer :: nuc_id
     real(C_DOUBLE) :: de,e_next
     real(C_DOUBLE) :: mysum
     integer,save :: dataset=1
     mysum=sum(tally)
     !with division by de
     write(unit,1000)dataset,nuc_id,mysum,title
     do g=1,size(tally)
         de=energy(g+1)-energy(g)
         write(unit,*)energy(g),tally(g)/de
         write(unit,*)energy(g+1),tally(g)/de
     end do
     if( size(tally)==0 )then
         write(unit,*)min_brem_continuum_energy(),0.0
         write(unit,*)max_brem_continuum_energy(),0.0
     endif
     write(unit,*)
     write(unit,*)
     !!!0SErrLine(1,*)'*** ',unit,' sum tally=',mysum
     dataset=dataset+1
     1000 format('# dataset: ',i7,' #nuc_id: ',i7,' # totalcounts: ',es9.3, ' # datatype: ',a)
subroutine gamma_library::dump_orig_spectra (character(*), intent(in) title, integer unit, real, dimension(:), intent(in) energy, real, dimension(:), intent(in) tally, integer nuc_id)
References max_brem_continuum_energy(), and min_brem_continuum_energy().
Referenced by setup_brem_continuum_e_bounds().
     character(*),intent(in) :: title
     integer :: unit
     real,intent(in) :: energy(:)
     real,intent(in) :: tally(:)
     integer :: g,gindex
     integer :: nuc_id
     real(C_DOUBLE) :: de,e_next
     real(C_DOUBLE) :: mysum
     integer,save :: dataset=1
     mysum=sum(tally)
     !without division by de
     write(unit,1000)dataset,nuc_id,mysum,title
     do g=1,size(tally)
         write(unit,*)energy(g),tally(g)
         write(unit,*)energy(g+1),tally(g)
     end do
     if( size(tally)==0 )then
         write(unit,*)min_brem_continuum_energy(),0.0
         write(unit,*)max_brem_continuum_energy(),0.0
     end if
     write(unit,*)
     write(unit,*)
     !!!0SErrLine(1,*)'*** ',unit,' sum tally=',mysum
     dataset=dataset+1
     1000 format('# dataset: ',i7,' #nuc_id: ',i7,' # totalcounts: ',es9.3, ' # datatype: ',a)
subroutine gamma_library::dump_binned_spectra_de (character(*), intent(in) title, integer unit, real(c_double), dimension(:), intent(in) energy, real(c_double), dimension(:), intent(in) tally, integer nuc_id)
Referenced by setup_brem_continuum_e_bounds().
     character(*),intent(in) :: title
     integer :: unit
     real(C_DOUBLE),intent(in) :: energy(:)
     real(C_DOUBLE),intent(in) :: tally(:)
     integer :: nuc_id
     integer :: g
     real(C_DOUBLE) :: de
     real(C_DOUBLE) :: mysum
     integer,save :: dataset=1
     require(size(energy)==size(tally)+1)
     mysum=sum(tally)
     !with division by de
     write(unit,1000)dataset,nuc_id,mysum,title
     do g=1,size(tally)
         de=energy(g)-energy(g+1)
         write(unit,*)energy(g),tally(g)/de
         write(unit,*)energy(g+1),tally(g)/de
     end do
     write(unit,*)
     write(unit,*)
     !!!0SErrLine(1,*)'*** ',unit,' sum tally=',mysum
     dataset=dataset+1
     1000 format('# dataset: ',i7,' #nuc_id: ',i7,' # totalcounts: ',es9.3, ' # datatype: ',a)
subroutine gamma_library::dump_binned_spectra (character(*), intent(in) title, integer unit, real(c_double), dimension(:), intent(in) energy, real(c_double), dimension(:), intent(in) tally, integer nuc_id)
References bin_boundary_match_tol.
Referenced by setup_brem_continuum_e_bounds().
     character(*),intent(in) :: title
     integer :: unit
     real(C_DOUBLE),intent(in) :: energy(:)
     real(C_DOUBLE),intent(in) :: tally(:)
     integer :: nuc_id
     integer :: g
     real(C_DOUBLE) :: de
     real(C_DOUBLE) :: mysum
     integer,save :: dataset=1
     require(size(energy)==size(tally)+1)
     mysum=sum(tally)
     !without division by de
     write(unit,1000)dataset,nuc_id,mysum,title
     do g=1,size(tally)
         write(unit,*)energy(g),tally(g)
         write(unit,*)energy(g+1),tally(g)
     end do
     write(unit,*)
     write(unit,*)
     !!!0SErrLine(1,*)'*** ',unit,' sum tally=',mysum
     dataset=dataset+1
     1000 format('# dataset: ',i7,' #nuc_id: ',i7,' # totalcounts: ',es9.3, ' # datatype: ',a)
Variable Documentation
integer, parameter gamma_library_unit = 10
default IO unit for the library
Referenced by setup_brem_continuum_e_bounds().
   integer, parameter :: gamma_library_unit = 10
type(fileutils), private resolver
Referenced by setup_brem_continuum_e_bounds().
   type(fileutils), private :: resolver
integer, private pass_number = 0
Referenced by setup_brem_continuum_e_bounds().
   integer, private :: pass_number = 0
real(c_double), dimension(:), allocatable, private brem_continuum_e_bounds
Referenced by max_brem_continuum_energy(), min_brem_continuum_energy(), next_larger_brem_continuum_energy(), and setup_brem_continuum_e_bounds().
   real(C_DOUBLE), allocatable, private :: brem_continuum_e_bounds(:)
real(c_double), private bin_boundary_match_tol =1d-5
Referenced by dump_binned_spectra(), and next_larger_brem_continuum_energy().
   real(C_DOUBLE), private :: bin_boundary_match_tol=1d-5