ORIGEN API: Manager/libld/f/tests/tstTransitionMatrixUpdater.f90 File Reference
tstTransitionMatrixUpdater.f90 File Reference
Functions/Subroutines
program tsttransitionmatrixupdater
subroutine load_transition_matrix (trx, path)
Function/Subroutine Documentation
program tsttransitionmatrixupdater ()
References cpu_time(), and load_transition_matrix().
subroutine tsttransitionmatrixupdater::load_transition_matrix (type(origen_transitionmatrixp), intent(out) trx, character(*), intent(in) path)
Referenced by tsttransitionmatrixupdater().
 type(origen_transitionmatrixp),intent(out) :: trx
 character(*),intent(in) :: path
 type(origen_library) :: lib
 type(origen_libraryio) :: lib_io
 type(datacontainer) :: options
 logical :: status
 call lib_io % initialize()
 call options % initialize()
 call lib % initialize()
 status = lib_io % load(lib,path,options)
 call lib_io % destroy()
 call lib % newptr_transition_matrix_at(trx,1_c_size_t)
 call lib%destroy()
 call lib_io%destroy()
 call options%destroy()