ORIGEN API: LibraryBuilder Class Reference
LibraryBuilder Class Reference
#include <LibraryBuilder.h>
Public Member Functions
LibraryBuilder ()
virtual ~LibraryBuilder ()
SCP_NuclideResource nuclide_resource () const
return shared (read-only) nuclide_resource resource \
bool has_nuclide_resource () const
whether this instantiation of class has the nuclide_resource resource \
void set_nuclide_resource (SCP_NuclideResource)
set a new shared (read-only) nuclide_resource resource (non-const version) \
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
void set_decay_resource (SCP_DecayResource)
set a new shared (read-only) decay_resource resource (non-const version) \
virtual void create_decay_transitions (std::vector< int > *num_decay_parents, std::vector< int > *num_parents, std::vector< int > *parent_positions, std::vector< int > *transition_ids, std::vector< double > *decay_constants, std::vector< double > *transition_coeff, const std::vector< int > &sizzzaaa_list, bool update, const TransitionSystem &ts) const
void create_decay_library (Library *lib, const std::vector< int > &sizzzaaa_list, bool update, const TransitionSystem &ts) const
void create_library (Library *lib, const std::vector< int > &num_decay_parents, const std::vector< int > &num_parents, const std::vector< int > &parent_positions, const std::vector< int > &transition_ids, const std::vector< double > &decay_constants, const std::vector< double > &fission_xs, const std::vector< double > &loss_xs, const std::vector< double > &transition_coeff, const std::vector< float > &n_production_xs, const std::vector< float > &flux, const std::vector< int > &sizzzaaa_list) const
virtual void create_reaction_transitions (std::vector< int > *num_decay_parents, std::vector< int > *num_parents, std::vector< int > *parent_positions, std::vector< int > *transition_ids, std::vector< double > *transition_coeff, std::vector< double > *fission_xs, std::vector< double > *loss_xs, std::vector< float > *n_production_xs, std::vector< float > *flux, std::vector< std::vector< WP_Transition >> *reaction_gain_sequence, const std::vector< int > &sizzzaaa_list, bool update, const TransitionSystem &ts) const
virtual void update_reaction_transitions (std::vector< double > *transition_coeff, std::vector< double > *loss_xs, std::vector< double > *fission_xs, std::vector< float > *n_production_xs, const std::vector< SP_Nuclide > &nuclide_sequence, const std::vector< std::vector< WP_Transition >> &reaction_gain_sequence, const std::vector< int > &num_decay_parents, const std::vector< int > &num_parents, const std::vector< int > &parent_positions, const std::vector< int > &transition_ids, const std::vector< int > &sizzzaaa_list) const
virtual void search_reaction_transitions (std::vector< SP_Nuclide > *nuclide_sequence, std::vector< std::vector< WP_Transition >> *reaction_gain_sequence, const std::vector< int > &num_decay_parents, const std::vector< int > &num_parents, const std::vector< int > &parent_positions, const std::vector< int > &transition_ids, const std::vector< int > &sizzzaaa_list, const TransitionSystem &ts) const
void set_minimum_decay_coeff (double)
double minimum_decay_coeff () const
void set_minimum_reaction_coeff (double)
double minimum_reaction_coeff () const
Static Public Member Functions
static size_t get_start (const Vec_Int &sizzzaaa_list, int sublib)
Public Attributes
std::vector< std::string > b_warnings
Protected Attributes
SCP_NuclideResource r_nuclide_resource
SCP_DecayResource r_decay_resource
bool b_accumulate_warnings
double b_minimum_decay_coeff
double b_minimum_reaction_coeff
Detailed Description
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Constructor & Destructor Documentation
LibraryBuilder ()
References LibraryBuilder::b_accumulate_warnings, LibraryBuilder::b_minimum_decay_coeff, and LibraryBuilder::b_minimum_reaction_coeff.
~LibraryBuilder () virtual
References LibraryBuilder::b_warnings.
Member Function Documentation
SCP_NuclideResource nuclide_resource () const
return shared (read-only) nuclide_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_nuclide_resource () const
whether this instantiation of class has the nuclide_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
void set_nuclide_resource (SCP_NuclideResource nuclide_resource)
set a new shared (read-only) nuclide_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by LibraryBuilderTester::SetUp().
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
void set_decay_resource (SCP_DecayResource decay_resource)
set a new shared (read-only) decay_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by LibraryBuilderTester::SetUp().
void create_decay_transitions (std::vector< int > * num_decay_parents, std::vector< int > * num_parents, std::vector< int > * parent_positions, std::vector< int > * transition_ids, std::vector< double > * decay_constants, std::vector< double > * transition_coeff, const std::vector< int > & sizzzaaa_list, bool update, const TransitionSystem & ts) const virtual
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References LibraryBuilder::b_minimum_decay_coeff, LibraryBuilder::b_warnings, TransitionSystem::byproducts(), Transition::channel(), Channel::channel_type(), Origen::check_sizes(), Transition::coeff(), Checkable::id(), Checkable::name(), TransitionSystem::nuclide(), Channel::parent(), Origen::setup_search_variables(), and Origen::shrink_to_fit().
Referenced by LibraryBuilder::create_decay_library(), and TEST_F().
void create_decay_library (Library * lib, const std::vector< int > & sizzzaaa_list, bool update, const TransitionSystem & ts) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_library(), Origen::populateLibraryAbundance_NuclideResource(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryMass_NuclideResource(), Origen::populateLibraryToxicity_DecayResource(), LibraryBuilder::r_decay_resource, and LibraryBuilder::r_nuclide_resource.
Referenced by TEST_F().
void create_library (Library * lib, const std::vector< int > & num_decay_parents, const std::vector< int > & num_parents, const std::vector< int > & parent_positions, const std::vector< int > & transition_ids, const std::vector< double > & decay_constants, const std::vector< double > & fission_xs, const std::vector< double > & loss_xs, const std::vector< double > & transition_coeff, const std::vector< float > & n_production_xs, const std::vector< float > & flux, const std::vector< int > & sizzzaaa_list) const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References Library::add_transition_coeff(), DecayData::decay_constants, DecayData::fissionable_nuclide_ids, NuclideSet::ids_size(), Origen::populateCurrentTimes(), Origen::populateFissionables(), NuclideSet::s_at(), TransitionCoeff::set_burnup(), LibraryHeader::set_day_made(), Library::set_decay_data(), Library::set_definition(), TransitionCoeff::set_fission_xs(), TransitionCoeff::set_flux(), TransitionCoeff::set_loss_xs(), TransitionCoeff::set_matrix(), LibraryHeader::set_month_made(), TransitionCoeff::set_neutron_yields(), LibraryHeader::set_nuclide_set(), TransitionStructure::set_num_decay_parents(), TransitionStructure::set_num_parents(), TransitionStructure::set_parent_positions(), TransitionStructure::set_transition_ids(), Library::set_transition_structure(), LibraryHeader::set_year_made(), Origen::SUBLIB_1LT, and Origen::SUBLIB_2AC.
Referenced by LibraryBuilder::create_decay_library(), and TEST_F().
void create_reaction_transitions (std::vector< int > * num_decay_parents, std::vector< int > * num_parents, std::vector< int > * parent_positions, std::vector< int > * transition_ids, std::vector< double > * transition_coeff, std::vector< double > * fission_xs, std::vector< double > * loss_xs, std::vector< float > * n_production_xs, std::vector< float > * flux, std::vector< std::vector< WP_Transition >> * reaction_gain_sequence, const std::vector< int > & sizzzaaa_list, bool update, const TransitionSystem & ts) const virtual
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References LibraryBuilder::b_accumulate_warnings, LibraryBuilder::b_minimum_reaction_coeff, LibraryBuilder::b_warnings, TransitionSystem::byproducts(), Origen::calculate_neutron_production_xs(), Transition::channel(), Channel::channel_type(), Origen::check_sizes(), Transition::coeff(), Checkable::id(), Checkable::name(), TransitionSystem::nuclide(), TransitionSystem::nuclides(), Channel::parent(), Origen::setup_search_variables(), Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, Channel::transition(), and Origen::vector_copy().
Referenced by TEST_F().
void update_reaction_transitions (std::vector< double > * transition_coeff, std::vector< double > * loss_xs, std::vector< double > * fission_xs, std::vector< float > * n_production_xs, const std::vector< SP_Nuclide > & nuclide_sequence, const std::vector< std::vector< WP_Transition >> & reaction_gain_sequence, const std::vector< int > & num_decay_parents, const std::vector< int > & num_parents, const std::vector< int > & parent_positions, const std::vector< int > & transition_ids, const std::vector< int > & sizzzaaa_list) const virtual
References Origen::calculate_neutron_production_xs(), LibraryBuilder::get_start(), Origen::SUBLIB_2AC, and Origen::SUBLIB_3FP.
Referenced by TransitionMatrixUpdater::get_transition_matrix().
void search_reaction_transitions (std::vector< SP_Nuclide > * nuclide_sequence, std::vector< std::vector< WP_Transition >> * reaction_gain_sequence, const std::vector< int > & num_decay_parents, const std::vector< int > & num_parents, const std::vector< int > & parent_positions, const std::vector< int > & transition_ids, const std::vector< int > & sizzzaaa_list, const TransitionSystem & ts) const virtual
References LibraryBuilder::b_accumulate_warnings, LibraryBuilder::b_warnings, TransitionSystem::byproducts(), Transition::channel(), Checkable::id(), TransitionSystem::nuclide(), and Origen::setup_search_variables().
Referenced by TransitionMatrixUpdater::load().
size_t get_start (const Vec_Int & sizzzaaa_list, int sublib) static
Referenced by LibraryBuilder::update_reaction_transitions().
void set_minimum_decay_coeff (double minimum_decay_coeff)
References LibraryBuilder::b_minimum_decay_coeff, and LibraryBuilder::minimum_decay_coeff().
double minimum_decay_coeff () const
References LibraryBuilder::b_minimum_decay_coeff.
Referenced by LibraryBuilder::set_minimum_decay_coeff().
void set_minimum_reaction_coeff (double minimum_reaction_coeff)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References LibraryBuilder::b_minimum_reaction_coeff, and LibraryBuilder::minimum_reaction_coeff().
Referenced by TEST_F().
double minimum_reaction_coeff () const
References LibraryBuilder::b_minimum_reaction_coeff.
Referenced by LibraryBuilder::set_minimum_reaction_coeff().
Member Data Documentation
std::vector<std::string> b_warnings mutable
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), LibraryBuilder::search_reaction_transitions(), and LibraryBuilder::~LibraryBuilder().
SCP_NuclideResource r_nuclide_resource protected
Referenced by LibraryBuilder::create_decay_library().
SCP_DecayResource r_decay_resource protected
Referenced by LibraryBuilder::create_decay_library().
bool b_accumulate_warnings protected
Referenced by LibraryBuilder::create_reaction_transitions(), LibraryBuilder::LibraryBuilder(), and LibraryBuilder::search_reaction_transitions().
double b_minimum_decay_coeff protected
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::LibraryBuilder(), LibraryBuilder::minimum_decay_coeff(), and LibraryBuilder::set_minimum_decay_coeff().
double b_minimum_reaction_coeff protected
Referenced by LibraryBuilder::create_reaction_transitions(), LibraryBuilder::LibraryBuilder(), LibraryBuilder::minimum_reaction_coeff(), and LibraryBuilder::set_minimum_reaction_coeff().
The documentation for this class was generated from the following files:
Manager/libld/LibraryBuilder.h
Manager/libld/LibraryBuilder.cpp