ORIGEN API: Obiwan_diff Class Reference
Obiwan_diff Class Reference
#include <Obiwan_diff.h>
execute obiwan in diff mode
Public Member Functions
Obiwan_diff (int argc, char **argv)
Obiwan_diff (ScaleUtils::IO::DB opts)
~Obiwan_diff () noexcept(false)
int diff (const Origen::Library &liba, const Origen::Library &libb, std::ostream &out, std::ostream &err)
int diff (const Origen::StateSet &liba, const Origen::StateSet &libb, std::ostream &out, std::ostream &err)
int execute (std::ostream &out, std::ostream &err)
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in diff mode
Examples:
Core/ut/tests/tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_diff (int argc, char ** argv)
References Obiwan_diff::b_opts, and Obiwan_diff::populate().
Obiwan_diff (ScaleUtils::IO::DB opts)
~Obiwan_diff () inline noexcept
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_diff::execute().
ScaleUtils::IO::DB populate (int argc, char ** argv) static
References kernel_rksuite::f().
Referenced by Obiwan_diff::Obiwan_diff().
int diff (const Origen::Library & liba, const Origen::Library & libb, std::ostream & out, std::ostream & err)
References Obiwan_diff::b_opts, Origen::construct_neutron_yields_map(), Origen::diffLibrary(), and kernel_rksuite::f().
Referenced by Obiwan_diff::execute().
int diff (const Origen::StateSet & liba, const Origen::StateSet & libb, std::ostream & out, std::ostream & err)
References Obiwan_diff::b_opts, State::concs(), Origen::diffConcentrations(), Origen::diffHalfLine(), Origen::diffLine(), StateSet::energies(), kernel_rksuite::f(), StateSet::fluxes(), StateSet::powers(), StateSet::states_at(), StateSet::states_size(), and StateSet::times().
int execute (std::ostream & out, std::ostream & err)
References Obiwan_diff::b_opts, Obiwan_diff::diff(), Obiwan_diff::help(), and Origen::loadMulti().
Referenced by Origen::obiwan_main().
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_diff::diff(), Obiwan_diff::execute(), and Obiwan_diff::Obiwan_diff().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_diff.h
Core/ut/Obiwan_diff.cpp