ORIGEN API: origen_particleemitter_api Module Reference
origen_particleemitter_api Module Reference
Data Types
type origen_particleemitter
Functions/Subroutines
subroutine pe_initialize (this, lib, origen_data_dir)
logical function pe_load_data (this, field_id)
subroutine pe_set_library (this, lib)
subroutine pe_set_energy_bounds (this, bounds, energy_units)
subroutine pe_get_particle_source (this, source, units, field_id, numden, opt_in)
subroutine pe_destroy (this)
character(:) function, allocatable pe_get_type_str (this, typ)
type(origen_neutron_options) function pe_process_neutron_options (this, opt)
type(origen_alpha_options) function pe_process_alpha_options (this, opt)
Function/Subroutine Documentation
subroutine origen_particleemitter_api::pe_initialize (class(origen_particleemitter), intent(inout) this, type(origen_librarywrapper), intent(in), target lib, character(len=*), intent(in), optional origen_data_dir)
logical function origen_particleemitter_api::pe_load_data (class(origen_particleemitter), intent(inout) this, integer field_id) private
References origen_definitions_m::alpha_field, origen_definitions_m::neutron_field, and origen_iofunctions_m::rstop().
subroutine origen_particleemitter_api::pe_set_library (class(origen_particleemitter), intent(inout) this, type(origen_librarywrapper), intent(in), target lib) private
subroutine origen_particleemitter_api::pe_set_energy_bounds (class(origen_particleemitter), intent(inout) this, real(c_double), dimension(:), intent(in) bounds, character(*), intent(in), optional energy_units) private
References origen_iofunctions_m::rstop().
subroutine origen_particleemitter_api::pe_get_particle_source (class(origen_particleemitter), intent(in) this, real(c_double), dimension(:), intent(out), allocatable source, character(len=*), intent(in) units, integer, intent(in) field_id, real(c_double), dimension(:), intent(in) numden, type(datacontainer), intent(in), optional, target opt_in) private
References origen_definitions_m::alpha_field, origen_definitions_m::end_field, origen_definitions_m::neutron_field, origen_definitions_m::null_field, and origen_iofunctions_m::rstop().
subroutine origen_particleemitter_api::pe_destroy (class(origen_particleemitter), intent(inout) this) private
character(:) function, allocatable origen_particleemitter_api::pe_get_type_str (class(origen_particleemitter), intent(in) this, integer, intent(in) typ) private
References origen_definitions_m::alpha_field, origen_definitions_m::electron_field, origen_definitions_m::neutron_field, origen_definitions_m::null_field, and origen_definitions_m::photon_field.
type(origen_neutron_options) function origen_particleemitter_api::pe_process_neutron_options (class(origen_particleemitter), intent(in) this, type(datacontainer), intent(in) opt) private
type(origen_alpha_options) function origen_particleemitter_api::pe_process_alpha_options (class(origen_particleemitter), intent(in) this, type(datacontainer), intent(in) opt) private