ORIGEN API: DecayResourceIO_cimg Class Reference
DecayResourceIO_cimg Class Reference
#include <DecayResourceIO_cimg.h>
Public Member Functions
bool read (DecayResource &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const DecayResource &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Member Function Documentation
bool read (DecayResource & obj, std::istream & stream, ScaleUtils::IO::DB opts)
References DecayResource::calculate_decay_constants(), DecayChannel::get_branch_ratio(), DecayParent::get_channel_map(), DecayResource::get_parent_map(), DecayChannel::get_yield_map(), DecayResource::ISOMERIC_YIELDS, DecayResource::MISSING_YIELDS, DecayChannel::set_branch_ratio(), DecayParent::set_half_life(), DecayParent::set_q_fraction_from_photons(), DecayParent::set_rcg_for_air(), DecayParent::set_rcg_for_water(), DecayParent::set_recoverable_energy_value(), DecayParent::set_time_units(), DecayChannel::set_yield_type(), and const::time_units.
bool write (const DecayResource & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
The documentation for this class was generated from the following files:
Core/io/DecayResourceIO_cimg.h
Core/io/DecayResourceIO_cimg.cpp