ORIGEN API: TransitionSystemAdapter_TransitionMatrix Class Reference
TransitionSystemAdapter_TransitionMatrix Class Reference
#include <TransitionSystemAdapter_TransitionMatrix.hh>
Public Member Functions
void set_transition_structure (SCP_TransitionStructure tm)
void set_transition_coeff (SCP_TransitionCoeff tc)
void set_library_header (SCP_LibraryHeader h)
void extend (TransitionSystem *ts, const std::vector< int > &sublibs) const
Private Attributes
SCP_TransitionStructure b_trans_struc
SCP_TransitionCoeff b_trans_coeff
SCP_LibraryHeader b_lib_header
Member Function Documentation
void set_transition_structure (SCP_TransitionStructure tm) inline
References TransitionSystemAdapter_TransitionMatrix::b_trans_struc.
     {
         b_trans_struc = tm;
     }
void set_transition_coeff (SCP_TransitionCoeff tc) inline
References TransitionSystemAdapter_TransitionMatrix::b_trans_coeff.
 { b_trans_coeff = tc; }
void set_library_header (SCP_LibraryHeader h) inline
References TransitionSystemAdapter_TransitionMatrix::b_lib_header.
 { b_lib_header = h; }
void extend (TransitionSystem * ts, const std::vector< int > & sublibs) const
References TransitionSystem::add_field(), TransitionSystem::add_nuclide(), TransitionSystemAdapter_TransitionMatrix::b_lib_header, TransitionSystemAdapter_TransitionMatrix::b_trans_coeff, TransitionSystemAdapter_TransitionMatrix::b_trans_struc, NuclideSet::ids(), NuclideSet::izzzaaa_at(), TransitionSystem::nuclides(), TransitionSystem::populate_gains(), Origen::SUBLIB_2AC, and NuclideSet::sublib_begin().
 {
     Ensure( ts );
     Ensure( b_trans_struc );
     Ensure( b_lib_header );
     Ensure( b_trans_coeff );
     const Origen::NuclideSet& ns = b_lib_header->nuclide_set();
     const Origen::Vec_Int& nuclide_ids = ns.ids();
     const FieldId field_id = b_trans_struc->field_id();
     SP_Field field = ts->add_field( field_id );
     field->set_intensity( 1.0 );
     const Origen::Vec_Int& num_decay_parents =
         b_trans_struc->num_decay_parents();
     const Origen::Vec_Int& num_parents = b_trans_struc->num_parents();
     const Origen::Vec_Int& parent_positions = b_trans_struc->parent_positions();
     const Origen::Vec_Int& transition_ids = b_trans_struc->transition_ids();
     const Origen::Vec_Flt& matrix = b_trans_coeff->matrix();
     const Origen::Vec_Flt& loss_xs = b_trans_coeff->loss_xs();
     const Origen::Vec_Flt& fission_xs = b_trans_coeff->fission_xs();
     const Origen::Vec_Flt& neutron_yields = b_trans_coeff->neutron_yields();
     const Origen::Vec_Flt& flux = b_trans_coeff->flux();
     unsigned int loc = 0;
     for( unsigned int i = 0; i < nuclide_ids.size(); i++ )
     {
         // Only process this nuclide if it's in one of the desired sublibs
         bool add_transitions = true;
         int sublib = nuclide_ids.at( i ) / ScaleData::Utils::PIZZZAAA_P_OFFSET;
         if( std::find( sublibs.cbegin(), sublibs.cend(), sublib ) ==
             sublibs.cend() )
             add_transitions = false;  // Still need to go through to update loc.
         SP_Nuclide daughter = ts->add_nuclide( ns.izzzaaa_at( i ) );
         for( int j = 0; j < num_parents.at( i ); j++ )
         {
             if( add_transitions )
             {
                 SP_Nuclide parent = ts->add_nuclide(
                     ns.izzzaaa_at( parent_positions.at( loc ) - 1 ) );
                 // If the transition is negative, then add as decay:
                 if( transition_ids.at( loc ) < 0 )
                 {
                     SP_Channel channel = parent->add_loss(
                         std::abs( transition_ids.at( loc ) ) );
                     channel->add_transition( daughter->isomeric_state(),
                                              matrix.at( loc ) );
                 }
                 else if( transition_ids.at( loc ) == 18 )
                 {
                     SP_Channel channel =
                         parent->add_loss( field_id, transition_ids.at( loc ) );
                     channel->set_xs( fission_xs.at(
                         parent_positions.at( loc ) - 1 -
                         ns.sublib_begin( Origen::SUBLIB_2AC ) ) );
                     channel->add_transition(
                         ns.izzzaaa_at( i ),
                         matrix.at( loc ) /
                             fission_xs.at(
                                 parent_positions.at( loc ) - 1 -
                                 ns.sublib_begin( Origen::SUBLIB_2AC ) ) );
                 }
                 else if( transition_ids.at( loc ) == 0 )
                 {
                     // Do nothing
                 }
                 else
                 {
                     SP_Channel channel =
                         parent->add_loss( field_id, transition_ids.at( loc ) );
                     SP_Transition t = channel->add_transition(
                         daughter->isomeric_state(), matrix.at( loc ) );
                 }
             }
             loc++;
         }
     }
     // Now loop through transition system to fix stuff
     for( auto& n : ts->nuclides() )
     {
         for( auto& channel : n->losses() )
         {
             if( channel->channel_type()->is_decay() ||
                 ( channel->channel_type()->is_reaction() &&
                   channel->channel_type()->reaction_mt() != 18 ) )
             {
                 double sum = 0.0;
                 for( auto& transition : channel->transitions() )
                 {
                     sum += transition->yield();
                 }
                 if( channel->channel_type()->is_decay() )
                 {
                     channel->set_decay_constant( sum );
                 }
                 else
                 {
                     channel->set_xs( sum );
                 }
                 if( sum == 0.0 ) continue;
                 for( auto& transition : channel->transitions() )
                 {
                     transition->set_yield( transition->yield() / sum );
                 }
             }
         }
     }
     ts->populate_gains();
 }
Member Data Documentation
SCP_TransitionStructure b_trans_struc private
Referenced by TransitionSystemAdapter_TransitionMatrix::extend(), and TransitionSystemAdapter_TransitionMatrix::set_transition_structure().
SCP_TransitionCoeff b_trans_coeff private
Referenced by TransitionSystemAdapter_TransitionMatrix::extend(), and TransitionSystemAdapter_TransitionMatrix::set_transition_coeff().
SCP_LibraryHeader b_lib_header private
Referenced by TransitionSystemAdapter_TransitionMatrix::extend(), and TransitionSystemAdapter_TransitionMatrix::set_library_header().
The documentation for this class was generated from the following files:
Manager/libld/TransitionSystemAdapter_TransitionMatrix.hh
Manager/libld/TransitionSystemAdapter_TransitionMatrix.cpp