ORIGEN API: Tester/tests/compareCoupleAndTMUpdater.cpp File Reference
compareCoupleAndTMUpdater.cpp File Reference
#include "Nemesis/gtest/gtest.h"
#include "Origen/Core/TestPaths.h"
#include "Origen/Core/dc/Library.h"
#include "Origen/Core/io/LibraryIO.h"
#include "Origen/Core/re/ReactionResource.h"
#include "Origen/Manager/libld/TransitionMatrixUpdater.h"
#include "ScaleUtils/IO/DB.h"
#include "Standard/Interface/CommandLine.h"
#include "../test_utils.hh"
Functions
TEST (couple, DISABLED_origen01)
int main (int argc, char *argv[])
Variables
Standard::SP_CommandLine cmdLine = 0
TMU Test.
Function Documentation
TEST (couple , DISABLED_origen01)
References TransitionMatrixUpdater::load(), TransitionMatrixUpdater::sp_library(), and TransitionMatrixUpdater::update_mg_flux().
 {
     // Load library produced by COUPLE:
     Origen::LibraryIO ol_io;
     ScaleUtils::IO::DB opts;
     Origen::SP_Library clib = Origen::SP_Library( new Origen::Library() );
     bool pass = ol_io.load( *clib, "u235_fast_heatlib", opts );
     ASSERT_TRUE( pass ) << "COUPLE Library had errors.";
     // Create a TMU class and get the library from it:
     Origen::TransitionMatrixUpdater tmu;
     tmu.load( Origen::pwrlib_filepath,
               Origen::jeff238_filepath,
               Origen::yields_filepath );
     // Set the flux weight spectrum:
     Origen::Vec_Flt mg_flux( 238, 0.0 );
     mg_flux[13] = 1.25;
     mg_flux[14] = 0.3;
     tmu.update_mg_flux( mg_flux );
     Origen::SP_Library tmulib = tmu.sp_library();
     std::cout << clib->print_compare( *tmulib );
     //~ std::string lib_diffs = clib->diff(*tmulib);
     //~ std::cout << lib_diffs;
 }
int main (int argc, char * argv[])
References cmdLine.
 {
     ::testing::InitGoogleTest( &argc, argv );
     cmdLine =
         Standard::SP_CommandLine( new Standard::CommandLine( argc, argv ) );
     return RUN_ALL_TESTS();
 }
Variable Documentation
Standard::SP_CommandLine cmdLine = 0
TMU Test.
Author
Shane Hart
This unit test loads a ORIGEN library created by couple and compares it to the library created by the TransitionMatrixUpdater class. The current test is based on origen01.inp in the regression test directory.
Referenced by main().