ORIGEN API: Transition_Gen Class Reference
Transition_Gen Class Reference
#include <Transition_Gen.h>
Public Member Functions
Transition_Gen ()
Transition_Gen (Nuclide::WP nuclide)
virtual ~Transition_Gen ()
Detailed Description
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef SP_Transition SP inherited
strong pointer
typedef WP_Transition WP inherited
weak pointer
Constructor & Destructor Documentation
Transition_Gen ()
Transition_Gen (Nuclide::WP nuclide)
References Transition::set_product().
~Transition_Gen () virtual
Member Function Documentation
Nuclide::WP product_impl () const private virtual
Implements Transition.
References Transition_Gen::b_product.
Channel::WP channel_impl () const private virtual
Implements Transition.
References Transition_Gen::b_channel.
double yield_impl () const private virtual
Implements Transition.
References Transition_Gen::b_yield.
Referenced by Transition_Gen::get_yield_impl().
void get_yield_impl (double & yield) const private virtual
References Transition_Gen::yield_impl().
void set_yield_impl (const double & yield) private virtual
Implements Transition.
References Transition_Gen::b_yield, and Transition::yield().
void set_product_impl (Nuclide::WP product) private virtual
Implements Transition.
References Transition_Gen::b_product, and Transition::product().
void set_channel_impl (Channel::WP channel) private virtual
Implements Transition.
References Transition_Gen::b_channel, and Transition::channel().
bool has_initialized_yield_impl () const private virtual
Implements Transition.
References Transition_Gen::b_yield, and Origen::BAD_DOUBLE.
Nuclide::WP product () const inherited
return the product nuclide
Referenced by Transition_Gen::set_product_impl().
void set_product (WP_Nuclide product) inherited
set the product nuclide
Referenced by Transition_Gen::Transition_Gen().
Channel::WP channel () const inherited
return the parent channel
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Nuclide_Gen::append_gain_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), LibraryBuilder::search_reaction_transitions(), and Transition_Gen::set_channel_impl().
void set_channel (WP_Channel channel) inherited
set the channel
double yield () const inherited
return the yield, i.e. number of product nuclides per transition
Referenced by Transition_Gen::set_yield_impl().
void set_yield (const double & yield) inherited
set the yield
bool has_initialized_yield () const inherited
whether yield has been initialized for this transition
double coeff () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), and LibraryBuilder::create_reaction_transitions().
double rate () const inherited
bool is_byproduct () const inherited
whether this transition is a byproduct
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), and ChannelType_Reac::good_impl().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), and Channel_Gen::set_transition_impl().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
Nuclide::WP b_product private
Referenced by Transition_Gen::product_impl(), and Transition_Gen::set_product_impl().
Channel::WP b_channel private
Referenced by Transition_Gen::channel_impl(), and Transition_Gen::set_channel_impl().
double b_yield private
Referenced by Transition_Gen::has_initialized_yield_impl(), Transition_Gen::set_yield_impl(), and Transition_Gen::yield_impl().
The documentation for this class was generated from the following files:
Core/ts/Transition_Gen.h
Core/ts/Transition_Gen.cpp