ORIGEN API: origen_librarywrapper Type Reference
origen_librarywrapper Type Reference
Public Member Functions
procedure, public initialize => Origen_LibraryWrapper__initialize
Construct from file.
procedure, public initialize_manageptr => Origen_LibraryWrapper__initialize_manageptr
Construct from in-memory Origen_Library.
procedure, public ref_count => Origen_LibraryWrapper__ref_count
Reference counter for shared data inside wrapper.
procedure, public destroy => Origen_LibraryWrapper__destroy
Destructor.
procedure, public build_coo_matrix => Origen_LibraryWrapper__build_coo_matrix
Build the full transition matrix (A+D) in the COO compressed format.
procedure, public build_full_matrix => Origen_LibraryWrapper__build_full_matrix
build the full transition matrix (A+D) as an uncompressed 2D array
procedure, public expand_matrix_pointers => Origen_LibraryWrapper__expand_matrix_pointers
Convert KD and NON0 arrays to "pointer" style (they point to the last parent in the A matrix)
procedure, public check_library => Origen_LibraryWrapper__check_library
Run library consistency check.
procedure, public print_transitions_for => Origen_LibraryWrapper__print_transitions_for
Print list of transitions for a given reaction.
procedure, public not_found => Origen_LibraryWrapper__NOT_FOUND
Index for a nuclide that was not found by find_*.
procedure, public find_nuclide_guess => Origen_LibraryWrapper__find_nuclide_guess
Find a nuclide by six-digit id; guess the nuclide type.
procedure, public find_nuclide => Origen_LibraryWrapper__find_nuclide
Find a nuclide by six-digit id and nuclide type.
procedure, public print_info => Origen_LibraryWrapper__print_info
Print library info.
procedure, public library_printout => Origen_LibraryWrapper__library_printout
Print the library contents.
procedure, public get_xs => Origen_LibraryWrapper__get_xs
Get a cross-section from the library.
procedure, public set_xs => Origen_LibraryWrapper__set_xs
Set a cross-section in the library.
procedure, public perturb_xs => Origen_LibraryWrapper__perturb_xs
Multiply a given cross-section in the library by a factor.
procedure, public collect_xs => Origen_LibraryWrapper__collect_xs
Get all reactions which involve a given set of nuclides.
procedure, public convert_abundances => Origen_LibraryWrapper__convert_abundances
Calculate wt% natural abundances.
procedure, public transpose_transition_matrix => Origen_LibraryWrapper__transpose_transition_matrix
Transpose the compressed transition matrix A.
procedure, public cleanup_transitions_for_adjoint => Origen_LibraryWrapper__cleanup_transitions_for_adjoint
Remove stable nuclides from the transition matrix and establish them as a fixed source term.
procedure, public fold_flux => Origen_LibraryWrapper__fold_flux
Produce the compressed transition matrix A and the diagonal vector D, applying the given flux.
procedure, public first_transition => Origen_LibraryWrapper__first_transition
Return the index (in A) of the first transition of the nuclide with index n (in N)
procedure, public last_transition => Origen_LibraryWrapper__last_transition
Return the index (in A) of the last transition of the nuclide with index n (in N)
procedure, public remove_fp_reactions => Origen_LibraryWrapper__remove_fp_reactions
Remove fission product absorptions.
procedure, public has_valid_mts => Origen_LibraryWrapper__has_valid_mts
Whether a library has valid MTs.
procedure, public is_mts_properly_ordered => Origen_LibraryWrapper__is_mts_properly_ordered
Whether the MTs on a library are ordered correctly.
procedure, public find_all_mts => Origen_LibraryWrapper__find_all_mts
Return a list of MTs on the library.
procedure, public num_massive_daughters => Origen_LibraryWrapper__num_massive_daughters
Number of massive daughters from a reaction.
procedure, public find_parents => Origen_LibraryWrapper__find_parents
Return a list of parents for a given nuclide.
procedure, public find_daughters => Origen_LibraryWrapper__find_daughters
Return a list of daughters for a given nuclide.
procedure, public setup_fast_transition_access => Origen_LibraryWrapper__setup_fast_transition_access
Setup fast transition access.
procedure, public fast_set_xs => Origen_LibraryWrapper__fast_set_xs
Use fast transition access to set cross sections.
procedure, public clear_tinds_2d => Origen_LibraryWrapper__clear_tinds_2d
Clear transition index variable (use after last fast_set_xs to free memory).
procedure, public get_ilite => Origen_LibraryWrapper__get_ilite
Data retriever methods.
procedure, public get_iact => Origen_LibraryWrapper__get_iact
procedure, public get_ifp => Origen_LibraryWrapper__get_ifp
procedure, public get_itot => Origen_LibraryWrapper__get_itot
procedure, public get_non => Origen_LibraryWrapper__get_non
procedure, public get_nfluxgrp => Origen_LibraryWrapper__get_nfluxgrp
procedure, public get_nti => Origen_LibraryWrapper__get_nti
procedure, public get_nfiso => Origen_LibraryWrapper__get_nfiso
procedure, public get_pos => Origen_LibraryWrapper__get_pos
procedure, public get_nmonth => Origen_LibraryWrapper__get_nmonth
procedure, public get_nday => Origen_LibraryWrapper__get_nday
procedure, public get_nyear => Origen_LibraryWrapper__get_nyear
procedure, public get_burnup => Origen_LibraryWrapper__get_burnup
procedure, public get_filename => Origen_LibraryWrapper__get_filename
procedure, public get_typ_nuc => Origen_LibraryWrapper__get_typ_nuc
procedure, public get_nucl => Origen_LibraryWrapper__get_nucl
procedure, public get_kd_ => Origen_LibraryWrapper__get_kd_
procedure, public get_non0_ => Origen_LibraryWrapper__get_non0_
procedure, public get_kd => Origen_LibraryWrapper__get_kd
procedure, public get_non0 => Origen_LibraryWrapper__get_non0
procedure, public get_loc => Origen_LibraryWrapper__get_loc
procedure, public get_mt => Origen_LibraryWrapper__get_mt
procedure, public get_nucfis => Origen_LibraryWrapper__get_nucfis
procedure, public get_dis => Origen_LibraryWrapper__get_dis
procedure, public get_genneu => Origen_LibraryWrapper__get_genneu
procedure, public get_q => Origen_LibraryWrapper__get_q
procedure, public get_fg => Origen_LibraryWrapper__get_fg
procedure, public get_ampc => Origen_LibraryWrapper__get_ampc
procedure, public get_wmpc => Origen_LibraryWrapper__get_wmpc
procedure, public get_abund => Origen_LibraryWrapper__get_abund
procedure, public get_wabund => Origen_LibraryWrapper__get_wabund
procedure, public get_spectrum => Origen_LibraryWrapper__get_spectrum
procedure, public get_a => Origen_LibraryWrapper__get_a
procedure, public get_tocap => Origen_LibraryWrapper__get_tocap
procedure, public get_fiss => Origen_LibraryWrapper__get_fiss
procedure, public get_m => Origen_LibraryWrapper__get_m
procedure, public get_titles => Origen_LibraryWrapper__get_titles
procedure, public get_sizes => Origen_LibraryWrapper__get_sizes
procedure, public get_bounds => Origen_LibraryWrapper__get_bounds
Get library boundaries.
procedure, public typ_nuc => Origen_LibraryWrapper__get_typ_nuc_at
Single-ement get methods (get array element at i)
procedure, public nucl => Origen_LibraryWrapper__get_nucl_at
procedure, public kd_ => Origen_LibraryWrapper__get_kd__at
procedure, public non0_ => Origen_LibraryWrapper__get_non0__at
procedure, public kd => Origen_LibraryWrapper__get_kd_at
procedure, public non0 => Origen_LibraryWrapper__get_non0_at
procedure, public loc => Origen_LibraryWrapper__get_loc_at
procedure, public mt => Origen_LibraryWrapper__get_mt_at
procedure, public nucfis => Origen_LibraryWrapper__get_nucfis_at
procedure, public dis => Origen_LibraryWrapper__get_dis_at
procedure, public genneu => Origen_LibraryWrapper__get_genneu_at
procedure, public q => Origen_LibraryWrapper__get_q_at
procedure, public fg => Origen_LibraryWrapper__get_fg_at
procedure, public ampc => Origen_LibraryWrapper__get_ampc_at
procedure, public wmpc => Origen_LibraryWrapper__get_wmpc_at
procedure, public abund => Origen_LibraryWrapper__get_abund_at
procedure, public wabund => Origen_LibraryWrapper__get_wabund_at
procedure, public spectrum => Origen_LibraryWrapper__get_spectrum_at
procedure, public a => Origen_LibraryWrapper__get_a_at
procedure, public tocap => Origen_LibraryWrapper__get_tocap_at
procedure, public fiss => Origen_LibraryWrapper__get_fiss_at
procedure, public m => Origen_LibraryWrapper__get_m_at
procedure, public set_ilite => Origen_LibraryWrapper__set_ilite
Data setter methods.
procedure, public set_iact => Origen_LibraryWrapper__set_iact
procedure, public set_ifp => Origen_LibraryWrapper__set_ifp
procedure, public set_itot => Origen_LibraryWrapper__set_itot
procedure, public set_non => Origen_LibraryWrapper__set_non
procedure, public set_nfluxgrp => Origen_LibraryWrapper__set_nfluxgrp
procedure, public set_nti => Origen_LibraryWrapper__set_nti
procedure, public set_nfiso => Origen_LibraryWrapper__set_nfiso
procedure, public set_pos => Origen_LibraryWrapper__set_pos
procedure, public set_nmonth => Origen_LibraryWrapper__set_nmonth
procedure, public set_nday => Origen_LibraryWrapper__set_nday
procedure, public set_nyear => Origen_LibraryWrapper__set_nyear
procedure, public set_burnup => Origen_LibraryWrapper__set_burnup
procedure, public set_filename => Origen_LibraryWrapper__set_filename
procedure, public set_spectrum => Origen_LibraryWrapper__set_spectrum
procedure, public initialize_copy => Origen_LibraryWrapper__initialize_copy
procedure, public disallow_assignment => Origen_LibraryWrapper__disallow_assignment
generic assignment => initialize_copy
procedure, public stdcomp_abund => Origen_LibraryWrapper__stdcomp_abund
load abundance
procedure, public set_stdcomp_abund => Origen_LibraryWrapper__set_stdcomp_abund
procedure, public legacy_mass => Origen_LibraryWrapper__legacy_mass
load legacy mass (mass number)
procedure, public set_legacy_mass => Origen_LibraryWrapper__set_legacy_mass
Public Attributes
character(2048) b_fullpath
logical b_initialized = .false.
type(origen_library) b_lib
type(origen_transitionmatrixp) b_trx
integer b_pos =0
integer, pointer b_ref_count => NULL()
logical b_stdcomp_abund = .false.
logical b_legacy_mass = .false.
Member Function/Subroutine Documentation
procedure, public initialize ()
Construct from file.
procedure, public initialize_manageptr ()
Construct from in-memory Origen_Library.
procedure, public ref_count ()
Reference counter for shared data inside wrapper.
procedure, public destroy ()
Destructor.
procedure, public build_coo_matrix ()
Build the full transition matrix (A+D) in the COO compressed format.
procedure, public build_full_matrix ()
build the full transition matrix (A+D) as an uncompressed 2D array
procedure, public expand_matrix_pointers ()
Convert KD and NON0 arrays to "pointer" style (they point to the last parent in the A matrix)
procedure, public check_library ()
Run library consistency check.
procedure, public print_transitions_for ()
Print list of transitions for a given reaction.
procedure, public not_found ()
Index for a nuclide that was not found by find_*.
procedure, public find_nuclide_guess ()
Find a nuclide by six-digit id; guess the nuclide type.
procedure, public find_nuclide ()
Find a nuclide by six-digit id and nuclide type.
procedure, public print_info ()
Print library info.
procedure, public library_printout ()
Print the library contents.
procedure, public get_xs ()
Get a cross-section from the library.
procedure, public set_xs ()
Set a cross-section in the library.
procedure, public perturb_xs ()
Multiply a given cross-section in the library by a factor.
procedure, public collect_xs ()
Get all reactions which involve a given set of nuclides.
procedure, public convert_abundances ()
Calculate wt% natural abundances.
procedure, public transpose_transition_matrix ()
Transpose the compressed transition matrix A.
procedure, public cleanup_transitions_for_adjoint ()
Remove stable nuclides from the transition matrix and establish them as a fixed source term.
procedure, public fold_flux ()
Produce the compressed transition matrix A and the diagonal vector D, applying the given flux.
procedure, public first_transition ()
Return the index (in A) of the first transition of the nuclide with index n (in N)
procedure, public last_transition ()
Return the index (in A) of the last transition of the nuclide with index n (in N)
procedure, public remove_fp_reactions ()
Remove fission product absorptions.
procedure, public has_valid_mts ()
Whether a library has valid MTs.
procedure, public is_mts_properly_ordered ()
Whether the MTs on a library are ordered correctly.
procedure, public find_all_mts ()
Return a list of MTs on the library.
procedure, public num_massive_daughters ()
Number of massive daughters from a reaction.
procedure, public find_parents ()
Return a list of parents for a given nuclide.
procedure, public find_daughters ()
Return a list of daughters for a given nuclide.
procedure, public setup_fast_transition_access ()
Setup fast transition access.
procedure, public fast_set_xs ()
Use fast transition access to set cross sections.
procedure, public clear_tinds_2d ()
Clear transition index variable (use after last fast_set_xs to free memory).
procedure, public get_ilite ()
Data retriever methods.
procedure, public get_iact ()
procedure, public get_ifp ()
procedure, public get_itot ()
procedure, public get_non ()
procedure, public get_nfluxgrp ()
procedure, public get_nti ()
procedure, public get_nfiso ()
procedure, public get_pos ()
procedure, public get_nmonth ()
procedure, public get_nday ()
procedure, public get_nyear ()
procedure, public get_burnup ()
procedure, public get_filename ()
procedure, public get_typ_nuc ()
procedure, public get_nucl ()
procedure, public get_kd_ ()
procedure, public get_non0_ ()
procedure, public get_kd ()
procedure, public get_non0 ()
procedure, public get_loc ()
procedure, public get_mt ()
procedure, public get_nucfis ()
procedure, public get_dis ()
procedure, public get_genneu ()
procedure, public get_q ()
procedure, public get_fg ()
procedure, public get_ampc ()
procedure, public get_wmpc ()
procedure, public get_abund ()
procedure, public get_wabund ()
procedure, public get_spectrum ()
procedure, public get_a ()
procedure, public get_tocap ()
procedure, public get_fiss ()
procedure, public get_m ()
procedure, public get_titles ()
procedure, public get_sizes ()
procedure, public get_bounds ()
Get library boundaries.
procedure, public typ_nuc ()
Single-ement get methods (get array element at i)
procedure, public nucl ()
procedure, public kd_ ()
procedure, public non0_ ()
procedure, public kd ()
procedure, public non0 ()
procedure, public loc ()
procedure, public mt ()
procedure, public nucfis ()
procedure, public dis ()
procedure, public genneu ()
procedure, public q ()
procedure, public fg ()
procedure, public ampc ()
procedure, public wmpc ()
procedure, public abund ()
procedure, public wabund ()
procedure, public spectrum ()
procedure, public a ()
procedure, public tocap ()
procedure, public fiss ()
procedure, public m ()
procedure, public set_ilite ()
Data setter methods.
procedure, public set_iact ()
procedure, public set_ifp ()
procedure, public set_itot ()
procedure, public set_non ()
procedure, public set_nfluxgrp ()
procedure, public set_nti ()
procedure, public set_nfiso ()
procedure, public set_pos ()
procedure, public set_nmonth ()
procedure, public set_nday ()
procedure, public set_nyear ()
procedure, public set_burnup ()
procedure, public set_filename ()
procedure, public set_spectrum ()
procedure, public initialize_copy ()
procedure, public disallow_assignment ()
generic assignment ()
procedure, public stdcomp_abund ()
load abundance
procedure, public set_stdcomp_abund ()
procedure, public legacy_mass ()
load legacy mass (mass number)
procedure, public set_legacy_mass ()
References origen_librarywrapper_m::copyorigen_librarywrapper(), origen_iofunctions_m::origen_loadlibrary(), and origen_iofunctions_m::rstop().
Member Data Documentation
character(2048) b_fullpath
logical b_initialized = .false.
type(origen_library) b_lib
type(origen_transitionmatrixp) b_trx
integer b_pos =0
integer, pointer b_ref_count => NULL()
logical b_stdcomp_abund = .false.
logical b_legacy_mass = .false.
The documentation for this type was generated from the following file:
Manager/wrap/LibraryWrapper_M.f90