ORIGEN API: Material Class Reference
Material Class Reference
#include <Material.h>
Container for an ORIGEN depletable material.
Public Types
enum FluxParameter { UNKNOWN = -1, FLUX = 0, POWER = 1, LAST_FLUX_PARAMETER }
typedef std::map< double, double, ScaleSTL::ApproxLt< double > > History_t
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
virtual bool good (Vec_Str &errors) const
virtual bool good () const
virtual bool is_initialized () const
virtual Scale::Json::Value to_json () const
virtual std::string to_string (int level=1) const
virtual bool has_initialized_id () const
virtual int id () const
virtual void get_id (int &id) const
virtual void set_id (int id)
virtual std::string name () const
virtual void set_name (std::string name)
virtual void get_name (std::string &name) const
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string to_string () const
Public Member Functions
Material (std::string library_type, SP_Library library, std::string name, int id, double cold_volume)
standard material setup
Material (SP_Library library, std::string name, int id, double cold_volume=-1.0)
material (without library type)
virtual ~Material ()
void register_buffer (SP_MaterialBuffer mbuf)
void add_step (double dt)
allocate and set delta-time
void allocate_step ()
allocate space for a new time step
void repeat_step_doubled ()
repeat the step but with time doubled
std::string library_type () const
get library type
SP_Library library () const
get library
size_t total_nuclides () const
total number of nuclides
SCP_Vec_Int sizzzaaa_list () const
nuclide ids
void mapping_sets (const Vec_Int &user_ids, Vec_Int *user_to_master, Vec_Int *master_to_user, int offset=0) const
SP_IdMap sizzzaaa_lookup (int offset=0) const
map of sizzzaaa to index;
void clear ()
clear all class memory
void flush_oldest ()
flush all but most recent
void flush_newest ()
flush newest
double initial_mass () const
get initial mass (g)
double initial_hm_mass () const
get initial hm mass (gIHM)
void set_initial_hm_mass_multiplier (double)
set an initial hm mass factor
double mass_at (size_t p, double *hm) const
mass at any time point
double mass (double *hm) const
mass at last time point
double cold_volume () const
get cold volume (cm^3), volume at room temperature
void set_cold_volume (double)
set cold volume (cm^3), volume at room temperature
void get_cold_volume (double &) const
get cold volume (cm^3), volume at room temperature
size_t step () const
get current step (starts at 0)
size_t point_bos () const
get point index at begin-of-step
size_t point_eos () const
get point index at end-of-step
size_t ntimes () const
get the number of times stored (including on disk)
size_t nsteps () const
get the number of steps
double dt_over (size_t i) const
get time (s) step length
double dt () const
get current step length (s)
void set_dt (double dt)
set time step length for current step
double time_at (size_t p) const
get a time (s) value (0 to nsteps)
double time_bos () const
get begin of step time (s)
double time_eos () const
get end of step time (s)
SP_DoubleList amount_at (size_t p) const
get amount (cm^2/barn) at a time point
SP_DoubleList amount_bos () const
get amount (cm^2/barn) at begin of step
SP_DoubleList amount_eos () const
get amount (cm^2/barn) at end of step
void set_amount_at (const Vec_Dbl &amount, size_t p)
set amount (cm^2/barn) at a time point
void set_amount_bos (const Vec_Dbl &amount)
set amount (cm^2/barn) at begin of step
void set_amount_eos (const Vec_Dbl &amount)
set amount (cm^2/barn) at end of step
void set_amount_at (const Vec_Dbl &amount, size_t p, const Vec_Int &ids)
set amount (cm^2/barn) at a time point
void set_amount_bos (const Vec_Dbl &amount, const Vec_Int &ids)
set amount (cm^2/barn) at begin of step
void set_amount_eos (const Vec_Dbl &amount, const Vec_Int &ids)
set amount (cm^2/barn) at end of step
void get_amount_at (Vec_Dbl *amount, size_t p) const
get amount (cm^2/barn) at a time point
void get_amount_bos (Vec_Dbl *amount) const
get amount (cm^2/barn) at begin of step
void get_amount_eos (Vec_Dbl *amount) const
get amount (cm^2/barn) at end of step
void get_amount_at (Vec_Dbl *amount, size_t p, const Vec_Int &ids) const
get amount (cm^2/barn) at a time point
void get_amount_bos (Vec_Dbl *amount, const Vec_Int &ids) const
get amount (cm^2/barn) at begin of step
void get_amount_eos (Vec_Dbl *amount, const Vec_Int &ids) const
get amount (cm^2/barn) at end of step
void set_numden_at (const Vec_Dbl &numden, size_t p, double volume)
set number density (#/barn-cm) at a time point
void set_numden_bos (const Vec_Dbl &numden, double volume)
set number density (#/barn-cm) at begin of step
void set_numden_eos (const Vec_Dbl &numden, double volume)
set number density (#/barn-cm) at end of step
void set_numden_at (const Vec_Dbl &numden, size_t p, const Vec_Int &ids, double volume)
set number density (#/barn-cm) at a time point
void set_numden_bos (const Vec_Dbl &numden, const Vec_Int &ids, double volume)
set number density (#/barn-cm) at begin of step
void set_numden_eos (const Vec_Dbl &numden, const Vec_Int &ids, double volume)
set number density (#/barn-cm) at end of step
void get_numden_at (Vec_Dbl *numden, size_t p, double volume) const
get number density (#/barn-cm) at a time point
void get_numden_bos (Vec_Dbl *numden, double volume) const
get number density (#/barn-cm) at begin of step
void get_numden_eos (Vec_Dbl *numden, double volume) const
get number density (#/barn-cm) at end of step
void get_numden_at (Vec_Dbl *numden, size_t p, const Vec_Int &ids, double volume) const
get number density (#/barn-cm) at a time point
void get_numden_bos (Vec_Dbl *numden, const Vec_Int &ids, double volume) const
get number density (#/barn-cm) at begin of step
void get_numden_eos (Vec_Dbl *numden, const Vec_Int &ids, double volume) const
get number density (#/barn-cm) at end of step
void set_numden_at (const Vec_Dbl &numden, size_t p)
set number density (#/barn-cm) at a time point
void set_numden_bos (const Vec_Dbl &numden)
set number density (#/barn-cm) at begin of step
void set_numden_eos (const Vec_Dbl &numden)
set number density (#/barn-cm) at end of step
void set_numden_at (const Vec_Dbl &numden, size_t p, const Vec_Int &ids)
set number density (#/barn-cm) at a time point
void set_numden_bos (const Vec_Dbl &numden, const Vec_Int &ids)
set number density (#/barn-cm) at begin of step
void set_numden_eos (const Vec_Dbl &numden, const Vec_Int &ids)
set number density (#/barn-cm) at end of step
void get_numden_at (Vec_Dbl *numden, size_t p) const
get number density (#/barn-cm) at a time point
void get_numden_bos (Vec_Dbl *numden) const
get number density (#/barn-cm) at begin of step
void get_numden_eos (Vec_Dbl *numden) const
get number density (#/barn-cm) at end of step
void get_numden_at (Vec_Dbl *numden, size_t p, const Vec_Int &ids) const
get number density (#/barn-cm) at a time point
void get_numden_bos (Vec_Dbl *numden, const Vec_Int &ids) const
get number density (#/barn-cm) at begin of step
void get_numden_eos (Vec_Dbl *numden, const Vec_Int &ids) const
get number density (#/barn-cm) at end of step
SP_TrMatrix transition_matrix_over (size_t i) const
get a transition matrix over a step
SP_TrMatrix transition_matrix () const
get the current transition matrix
void set_transition_matrix (SP_TrMatrix trx)
set transition matrix of current step
double power_over (size_t i) const
get power (W) over a step
double power () const
get power (W) over current step
void set_power (double power)
set power (W) over current step
void set_power_over (size_t i, double power)
set power (W) over any step
double flux_over (size_t i) const
get flux (#/cm^2-s) over a step
double flux () const
get flux (#/cm^2-s) over current step
void set_flux (double flux)
set flux (#/cm^2-s) over current step
void set_flux_over (size_t i, double flux)
set flux (#/cm^2-s) over any step
double fluence_at (size_t p) const
get fluence (#/cm^2) at a point
double fluence_bos () const
get fluence (#/cm^2) at begin-of-step
double fluence_eos () const
get fluence (#/cm^2) at end-of-step
double burnup_at (size_t p) const
get burnup (MWd/MTIHM) at a point
double burnup_bos () const
get burnup (MWd/MTIHM) at begin-of-step
double burnup_eos () const
get burnup (MWd/MTIHM) at end-of-step
void get_concs_at (Concentrations *, size_t p) const
get/set concentrations at a particular time point
void set_concs_at (const Concentrations &, size_t p)
double volume_hist (double trel) const
FluxParameter flux_parameter () const
History_t param_hist () const
void set_param_hist (double, double)
double param_hist (double trel) const
History_t flux_hist () const
void set_flux_hist (double, double)
double flux_hist (double trel) const
History_t power_hist () const
void set_power_hist (double, double)
double power_hist (double trel) const
void record_average_flux (const Vec_Dbl &scaling)
void record_average_power (const Vec_Dbl &scaling)
bool is_decay () const
double power_factor (double trel, const DoubleList &) const
double decay_power (double trel, const DoubleList &) const
double power_factor_bos () const
double power_factor_mos () const
double power_factor_eos () const
double trel_bos () const
double trel_mos () const
double trel_eos () const
SP_DoubleList amount_mos () const
void set_solver (SP_Solver)
SCP_Solver solver () const
void solve (Vec_Dbl &dtrel, Vec_Dbl *flux, Vec_Dbl *power)
bool solve_inplace (size_t nlit, double trel1, double trel2, double z0, double z1, double *flux, double *power)
void solve_kernel (double trel1, double trel2, double z0, double z1, double *flux, double *power)
Static Public Member Functions
static Vec_Dbl decay_substep_dtrel (size_t ns)
Protected Member Functions
void init_mos ()
void clear_mos ()
void swap_mos_bos ()
void swap_mos_eos ()
void initialize_mass ()
mass initializer function
void internal_initialize (std::string library_type, SP_Library library, std::string name, int id, double cold_volume)
everything initializer function
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual bool is_initialized_impl () const
useful to chain
virtual Scale::Json::Value to_json_impl () const
useful to chain
Protected Attributes
std::string b_library_type
library type for general book-keeping
SP_Library b_library
actual library for reference values
double b_mass
total mass (g) at time=0
double b_initial_hm_mass
total mass in heavy metal (g) at time=0
double b_initial_hm_mass_multiplier
SP_Solver b_solver
solver
double b_trel_bos
SP_DoubleList b_amount_bos
double b_trel_mos
SP_DoubleList b_amount_mos
double b_trel_eos
SP_DoubleList b_amount_eos
History_t b_flux_hist
History_t b_power_hist
History_t b_param_hist
std::string b_name
saved name for this material
int b_id
saved id
double b_cold_volume
volume (cm^3) at cold conditions
Deq_Dbl b_step_flux_cm2s
average flux magnitude (#/cm^2-s) over each step
Deq_Dbl b_step_power_watt
average power (W) over each step
Deq_TrMatrix b_step_trx
transition matrix over each step
std::deque< FluxParameter > b_flux_parameter
provided "flux" parameter over each step
Deq_Dbl b_point_time_s
time (s) at each point
Deq_Amt b_point_amount_cm2barn
nuclide amount (cm^2/barn)
Detailed Description
Container for an ORIGEN depletable material.
The Origen::Material uses deques because you can pop off the front element as you write to a file. So the heavy parts of the material, the transition matrix and number densities, can be flushed every so often without a full reallocate.
The internal units are:
amount of nuclides \({cm^2}/{barn} \)
time in \(s \)
flux in \({\#}/{cm^2 s} \)
power in \(W \)
The accessors use the following terminology:
'bos' for begin-of-step
'eos' for end-of-step
'amount' for amount (cm^s/barn)
'numden' for number density (#/barn-cm)
'at' for a value at a particular
'over' for an average value over a time interval
There are generally two ways to 'get' something.
Get value of x as return value of function, v=x(). This is used when v is a simple scalar or smart pointer.
Get value of x with argument value of function get_x(T& v). This is used in all other cases.
There is only a single way to 'set' something, set_x(const T& v).
Using set always implies a copy. To manipulate data directly, which is not recommended, use the getters that return smart pointers, e.g. trx_over(), amount_at().
Examples:
tstMaterial.cpp, tstMaterialBuffer.cpp, tstMultiZoneDepleter.cpp, and tstParallelDepletion.cpp.
Member Typedef Documentation
typedef std::map<double, double, ScaleSTL::ApproxLt<double> > History_t
Member Enumeration Documentation
enum FluxParameter
Enumerator
UNKNOWN
FLUX
POWER
LAST_FLUX_PARAMETER
     {
         UNKNOWN = -1,
         FLUX = 0,
         POWER = 1,
         LAST_FLUX_PARAMETER
     };
Constructor & Destructor Documentation
Material (std::string library_type, SP_Library library, std::string name, int id, double cold_volume)
standard material setup
 {
     internal_initialize( library_type, library, name, id, volume );
 }
Material (SP_Library library, std::string name, int id, double cold_volume = -1.0)
material (without library type)
 {
     internal_initialize( "UNKNOWN", library, name, id, volume );
 }
~Material () virtual
 {
     jDebugTaggedLine( "destroyed Origen::Material("
                       << "id="
                       << b_id
                       << ",name="
                       << b_name
                       << ")" );
 }
Member Function Documentation
void register_buffer (SP_MaterialBuffer mbuf)
void add_step (double dt)
allocate and set delta-time
add new time step
Examples:
tstMaterialBuffer.cpp.
 {
     allocate_step();
     set_dt( dt );
 }
void allocate_step ()
allocate space for a new time step
 {
     Require( is_initialized() );
     jDebugLine( "    adding step for material=" << this->name() );
     // set bos
     b_trel_bos = 0.0;
     b_amount_bos = b_point_amount_cm2barn.back();
     // make eos a copy of bos initially
     b_trel_eos = 0.0;
     b_amount_eos = std::make_shared<DoubleList>( *b_amount_bos );
     // clear mos
     clear_mos();
     // add values
     b_step_trx.push_back( nullptr );
     b_point_time_s.push_back( 0.0 );
     b_flux_parameter.push_back( UNKNOWN );
     b_step_flux_cm2s.push_back( -1.0 );
     b_step_power_watt.push_back( -1.0 );
     b_point_amount_cm2barn.push_back( b_amount_eos );
     // reset histories
     b_param_hist.clear();
     b_flux_hist.clear();
     b_power_hist.clear();
 }
void repeat_step_doubled ()
repeat the step but with time doubled
prepare to perform a new step with double the time
Returns
 {
     double dt0 = dt();
     const bool wrong_way( true );
     if( wrong_way )
     {
         // save end as middle
         b_amount_mos = b_amount_eos;
         // flush newest step
         flush_newest();
         // add step back
         add_step( 2 * dt0 );
     }
     else
     {
         // double time
         set_dt( 2 * dt0 );
         // set bos pointer
         b_trel_bos = 0.0;
         b_amount_bos = amount_bos();
         // set mos to previous final
         b_trel_mos = 0.0;
         b_amount_mos = b_amount_eos;
         // make eos a copy of mos
         b_trel_eos = 0.0;
         b_amount_eos = std::make_shared<DoubleList>( *b_amount_mos );
         b_point_amount_cm2barn.back() = b_amount_eos;
         // reset histories
         b_param_hist.clear();
         b_flux_hist.clear();
         b_power_hist.clear();
     }
 }
std::string library_type () const
get library type
get library type
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material().
 { return b_library_type; }
SP_Library library () const
get library
get library
Examples:
tstMaterialBuffer.cpp.
Referenced by Origen::saveLibraries(), Origen::saveStateSet(), Origen::tabulateMaterialFission(), Origen::tabulateMaterialIsotopics(), Origen::tabulateMaterialLoss(), and Origen::tabulateMaterialTransitionRates().
 { return b_library; }
size_t total_nuclides () const
total number of nuclides
get total number of nuclides
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step(), and Origen::tabulateMaterialTransitionRates().
 { return b_library->total_nuclides(); }
SCP_Vec_Int sizzzaaa_list () const
nuclide ids
nuclide ids in sublib,isomeric state,atom number, mass number format
 {
     return b_library->definition().nuclide_set().scp_ids();
 }
void mapping_sets (const Vec_Int & user_ids, Vec_Int * user_to_master, Vec_Int * master_to_user, int offset = 0) const
master[user_to_master[u]] += user_ids[u]; master[m] += user[master_to_user[m]];
 {
     b_library->definition().nuclide_set().mapping_sets(
         user_ids, user_to_master, master_to_user, offset );
 }
SP_IdMap sizzzaaa_lookup (int offset = 0) const
map of sizzzaaa to index;
map of sizzzaaa to index
 {
     return b_library->definition().nuclide_set().sizzzaaa_lookup();
 }
void clear ()
clear all class memory
All in-memory data is cleared. Data on disk remains.
 {
     b_library_type = "";
     b_library = nullptr;
     b_mass = -1.0;
     b_initial_hm_mass = -1.0;
     b_initial_hm_mass_multiplier = 1.0;
     b_name = "";
     b_id = -1;
     b_cold_volume = -1.0;
     Deq_Dbl().swap( b_step_flux_cm2s );
     Deq_Dbl().swap( b_step_power_watt );
     Deq_TrMatrix().swap( b_step_trx );
     std::deque<FluxParameter>().swap( b_flux_parameter );
     Deq_Dbl().swap( b_point_time_s );
     Deq_Amt().swap( b_point_amount_cm2barn );
     b_solver = nullptr;
     b_trel_bos = 0.0;
     b_trel_mos = 0.0;
     b_trel_eos = 0.0;
     b_amount_bos = nullptr;
     b_amount_mos = nullptr;
     b_amount_eos = nullptr;
     History_t().swap( b_flux_hist );
     History_t().swap( b_power_hist );
     History_t().swap( b_param_hist );
 }
void flush_oldest ()
flush all but most recent
flush all the oldest (before this step) information
 {
     for( size_t i = 0; i < nsteps() - 1; ++i )
     {
         b_step_trx[i] = nullptr;
         b_point_amount_cm2barn[i] = nullptr;
     }
 }
void flush_newest ()
flush newest
flush newest step of information (including times)
Returns
 {
     // pop off everything
     b_step_flux_cm2s.pop_back();
     b_step_power_watt.pop_back();
     b_step_trx.pop_back();
     b_point_time_s.pop_back();
     b_point_amount_cm2barn.pop_back();
     b_flux_parameter.pop_back();
     // reset relative time pointers
     b_trel_bos = 0.0;
     b_trel_mos = 0.0;
     b_trel_eos = 0.0;
     // reset amount pointers
     b_amount_bos = b_point_amount_cm2barn.front();
     b_amount_mos = nullptr;
     b_amount_eos = nullptr;
     // re-associate amount pointers
     size_t n = nsteps();
     if( n > 0 )
     {
         b_amount_bos = b_point_amount_cm2barn[n - 1];
         b_amount_eos = b_point_amount_cm2barn[n];
     }
     // reset histories
     b_param_hist.clear();
     b_flux_hist.clear();
     b_power_hist.clear();
 }
double initial_mass () const
get initial mass (g)
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material().
 { return b_mass; }
double initial_hm_mass () const
get initial hm mass (gIHM)
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material().
 {
     return b_initial_hm_mass * b_initial_hm_mass_multiplier;
 }
void set_initial_hm_mass_multiplier (double multiplier)
set an initial hm mass factor
 {
     Require( multiplier > 0.0 );
     b_initial_hm_mass_multiplier = multiplier;
 }
double mass_at (size_t p, double * hm) const
mass at any time point
 {
     SP_DoubleList internal_amount = amount_at( p );
     if( internal_amount != nullptr )
     {
         return b_library->decay_data().mass(
             *internal_amount,
             1.66053892103, /* reciprocal of atoms/mol-barn=0.6022141290007942 */
             b_library->definition().nuclide_set(),
             *hm );
     }
     return -1.0;
 }
double mass (double * hm) const
mass at last time point
 { return mass_at( point_eos(), hm ); }
double cold_volume () const
get cold volume (cm^3), volume at room temperature
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material().
 { return b_cold_volume; }
void set_cold_volume (double volume)
set cold volume (cm^3), volume at room temperature
 { b_cold_volume = volume; }
void get_cold_volume (double & volume) const
get cold volume (cm^3), volume at room temperature
 {
     volume = b_cold_volume;
 }
size_t step () const
get current step (starts at 0)
 { return nsteps() - 1; }
size_t point_bos () const
get point index at begin-of-step
 {
     if( ntimes() > 1 )
         return ntimes() - 2;
     else
         return ntimes() - 1;
 }
size_t point_eos () const
get point index at end-of-step
 {
     if( ntimes() > 1 )
         return ntimes() - 1;
     else
         return static_cast<size_t>( -1 );
 }
size_t ntimes () const
get the number of times stored (including on disk)
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material(), Origen::saveLibraries(), and Origen::saveStateSet().
 { return b_point_time_s.size(); }
size_t nsteps () const
get the number of steps
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step().
 { return ntimes() - 1; }
double dt_over (size_t i) const
get time (s) step length
 {
     if( i < nsteps() )
     {
         return b_point_time_s.at( i + 1 ) - b_point_time_s.at( i );
     }
     else
     {
         return -1.0;
     }
 }
double dt () const
get current step length (s)
 { return dt_over( nsteps() - 1 ); }
void set_dt (double dt)
set time step length for current step
Set the time step size (overwriting add_step time)
 {
     Require( ntimes() >= 2 );
     b_point_time_s.back() = time_at( ntimes() - 2 ) + dt;
 }
double time_at (size_t p) const
get a time (s) value (0 to nsteps)
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step(), and Origen::saveStateSet().
 {
     if( p < ntimes() )
     {
         Check( p < b_point_time_s.size() );
         return b_point_time_s.at( p );
     }
     else
     {
         return -1.0;
     }
 }
double time_bos () const
get begin of step time (s)
 { return time_at( point_bos() ); }
double time_eos () const
get end of step time (s)
 { return time_at( point_eos() ); }
SP_DoubleList amount_at (size_t p) const
get amount (cm^2/barn) at a time point
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step(), and Origen::tabulateMaterialTransitionRates().
 {
     if( p < ntimes() )
     {
         return b_point_amount_cm2barn.at( p );
     }
     else
     {
         return nullptr;
     }
 }
SP_DoubleList amount_bos () const
get amount (cm^2/barn) at begin of step
 { return b_amount_bos; }
SP_DoubleList amount_eos () const
get amount (cm^2/barn) at end of step
 { return b_amount_eos; }
void set_amount_at (const Vec_Dbl & amount, size_t p)
set amount (cm^2/barn) at a time point
 {
     Require( p < ntimes() );
     Require( amount.size() == total_nuclides() );
     SP_DoubleList internal_amount = amount_at( p );
     if( internal_amount != nullptr )
     {
         for( size_t j = 0; j < amount.size(); ++j )
         {
             internal_amount->at( j ) = amount[j];
         }
         if( p == 0 ) initialize_mass();
     }
 }
void set_amount_bos (const Vec_Dbl & amount)
set amount (cm^2/barn) at begin of step
 {
     set_amount_at( amount, point_bos() );
 }
void set_amount_eos (const Vec_Dbl & amount)
set amount (cm^2/barn) at end of step
 {
     set_amount_at( amount, point_eos() );
 }
void set_amount_at (const Vec_Dbl & amount, size_t p, const Vec_Int & ids)
set amount (cm^2/barn) at a time point
 {
     Require( p < ntimes() );
     SP_DoubleList internal_amount = amount_at( p );
     // this code is effectively the same as in
     // Concentrations::accumulate_subset
     if( internal_amount != nullptr )
     {
         std::vector<int> user_to_master, master_to_user;
         mapping_sets( ids, &user_to_master, &master_to_user );
         for( size_t j = 0; j < internal_amount->size(); ++j )
         {
             internal_amount->at( j ) = 0.0;
         }
         for( size_t j = 0; j < amount.size(); ++j )
         {
             int jm = user_to_master.at( j );
             if( jm != NuclideSet::NOT_FOUND() )
             {
                 internal_amount->at( jm ) += amount.at( j );
             }
         }
         if( p == 0 ) initialize_mass();
     }
 }
void set_amount_bos (const Vec_Dbl & amount, const Vec_Int & ids)
set amount (cm^2/barn) at begin of step
 {
     set_amount_at( amount, point_bos(), ids );
 }
void set_amount_eos (const Vec_Dbl & amount, const Vec_Int & ids)
set amount (cm^2/barn) at end of step
 {
     set_amount_at( amount, point_eos(), ids );
 }
void get_amount_at (Vec_Dbl * amount, size_t p) const
get amount (cm^2/barn) at a time point
 {
     Require( amount != nullptr );
     Require( amount->size() == total_nuclides() );
     SP_DoubleList internal_amount = amount_at( p );
     if( internal_amount != nullptr )
     {
         for( size_t j = 0; j < internal_amount->size(); ++j )
         {
             amount->at( j ) = ( *internal_amount )[j];
         }
     }
 }
void get_amount_bos (Vec_Dbl * amount) const
get amount (cm^2/barn) at begin of step
 {
     get_amount_at( amount, point_bos() );
 }
void get_amount_eos (Vec_Dbl * amount) const
get amount (cm^2/barn) at end of step
 {
     get_amount_at( amount, point_eos() );
 }
void get_amount_at (Vec_Dbl * amount, size_t p, const Vec_Int & ids) const
get amount (cm^2/barn) at a time point
 {
     Require( ids.size() == amount->size() );
     SP_DoubleList internal_amount = amount_at( p );
     if( internal_amount != nullptr )
     {
         std::vector<int> user_to_master, master_to_user;
         mapping_sets( ids, &user_to_master, &master_to_user );
         for( size_t ju = 0; ju < amount->size(); ++ju )
         {
             amount->at( ju ) = 0.0;
         }
         for( size_t j = 0; j < internal_amount->size(); ++j )
         {
             int ju = master_to_user.at( j );
             if( ju != NuclideSet::NOT_FOUND() )
             {
                 amount->at( ju ) += internal_amount->at( j );
             }
         }
     }
 }
void get_amount_bos (Vec_Dbl * amount, const Vec_Int & ids) const
get amount (cm^2/barn) at begin of step
 {
     get_amount_at( amount, point_bos(), ids );
 }
void get_amount_eos (Vec_Dbl * amount, const Vec_Int & ids) const
get amount (cm^2/barn) at end of step
 {
     get_amount_at( amount, point_eos(), ids );
 }
void set_numden_at (const Vec_Dbl & numden, size_t p, double volume)
set number density (#/barn-cm) at a time point
 {
     Require( p < ntimes() );
     Require( numden.size() == total_nuclides() );
     SP_DoubleList amount = amount_at( p );
     if( amount != nullptr )
     {
         for( size_t j = 0; j < numden.size(); ++j )
         {
             amount->at( j ) = numden[j] * volume;
         }
         if( p == 0 ) initialize_mass();
     }
 }
void set_numden_bos (const Vec_Dbl & numden, double volume)
set number density (#/barn-cm) at begin of step
Examples:
tstMaterialBuffer.cpp.
 {
     set_numden_at( numden, point_bos(), volume );
 }
void set_numden_eos (const Vec_Dbl & numden, double volume)
set number density (#/barn-cm) at end of step
 {
     set_numden_at( numden, point_eos(), volume );
 }
void set_numden_at (const Vec_Dbl & numden, size_t p, const Vec_Int & ids, double volume)
set number density (#/barn-cm) at a time point
 {
     Require( p < ntimes() );
     SP_DoubleList amount = amount_at( p );
     if( amount != nullptr )
     {
         std::vector<int> user_to_master, master_to_user;
         mapping_sets( ids, &user_to_master, &master_to_user );
         for( size_t jm = 0; jm < amount->size(); ++jm )
         {
             amount->at( jm ) = 0.0;
         }
         for( size_t j = 0; j < numden.size(); ++j )
         {
             int jm = user_to_master.at( j );
             if( jm != NuclideSet::NOT_FOUND() )
             {
                 amount->at( jm ) += numden[j] * volume;
             }
         }
         if( p == 0 ) initialize_mass();
     }
 }
void set_numden_bos (const Vec_Dbl & numden, const Vec_Int & ids, double volume)
set number density (#/barn-cm) at begin of step
 {
     set_numden_at( numden, point_bos(), ids, volume );
 }
void set_numden_eos (const Vec_Dbl & numden, const Vec_Int & ids, double volume)
set number density (#/barn-cm) at end of step
 {
     set_numden_at( numden, point_eos(), ids, volume );
 }
void get_numden_at (Vec_Dbl * numden, size_t p, double volume) const
get number density (#/barn-cm) at a time point
Referenced by Origen::tabulateMaterialIsotopics().
 {
     Require( numden != nullptr );
     numden->resize( total_nuclides() );
     SP_DoubleList amount = amount_at( p );
     if( amount != nullptr )
     {
         for( size_t j = 0; j < numden->size(); ++j )
         {
             numden->at( j ) = amount->at( j ) / volume;
         }
     }
 }
void get_numden_bos (Vec_Dbl * numden, double volume) const
get number density (#/barn-cm) at begin of step
 {
     get_numden_at( numden, point_bos(), volume );
 }
void get_numden_eos (Vec_Dbl * numden, double volume) const
get number density (#/barn-cm) at end of step
 {
     get_numden_at( numden, point_eos(), volume );
 }
void get_numden_at (Vec_Dbl * numden, size_t p, const Vec_Int & ids, double volume) const
get number density (#/barn-cm) at a time point
 {
     numden->resize( ids.size() );
     SP_DoubleList amount = amount_at( p );
     if( amount != nullptr )
     {
         std::vector<int> user_to_master, master_to_user;
         mapping_sets( ids, &user_to_master, &master_to_user );
         for( size_t ju = 0; ju < numden->size(); ++ju )
         {
             numden->at( ju ) = 0.0;
         }
         for( size_t j = 0; j < amount->size(); ++j )
         {
             int ju = master_to_user.at( j );
             if( ju != NuclideSet::NOT_FOUND() )
             {
                 numden->at( ju ) += amount->at( j ) / volume;
             }
         }
     }
 }
void get_numden_bos (Vec_Dbl * numden, const Vec_Int & ids, double volume) const
get number density (#/barn-cm) at begin of step
 {
     get_numden_at( numden, point_bos(), ids, volume );
 }
void get_numden_eos (Vec_Dbl * numden, const Vec_Int & ids, double volume) const
get number density (#/barn-cm) at end of step
 {
     get_numden_at( numden, point_eos(), ids, volume );
 }
void set_numden_at (const Vec_Dbl & numden, size_t p)
set number density (#/barn-cm) at a time point
 {
     set_numden_at( numden, p, b_cold_volume );
 }
void set_numden_bos (const Vec_Dbl & numden)
set number density (#/barn-cm) at begin of step
 {
     set_numden_at( numden, point_bos(), b_cold_volume );
 }
void set_numden_eos (const Vec_Dbl & numden)
set number density (#/barn-cm) at end of step
 {
     set_numden_at( numden, point_eos(), b_cold_volume );
 }
void set_numden_at (const Vec_Dbl & numden, size_t p, const Vec_Int & ids)
set number density (#/barn-cm) at a time point
 {
     set_numden_at( numden, p, ids, b_cold_volume );
 }
void set_numden_bos (const Vec_Dbl & numden, const Vec_Int & ids)
set number density (#/barn-cm) at begin of step
 {
     set_numden_bos( numden, ids, b_cold_volume );
 }
void set_numden_eos (const Vec_Dbl & numden, const Vec_Int & ids)
set number density (#/barn-cm) at end of step
 {
     set_numden_eos( numden, ids, b_cold_volume );
 }
void get_numden_at (Vec_Dbl * numden, size_t p) const
get number density (#/barn-cm) at a time point
 {
     get_numden_at( numden, p, b_cold_volume );
 }
void get_numden_bos (Vec_Dbl * numden) const
get number density (#/barn-cm) at begin of step
 {
     get_numden_bos( numden, b_cold_volume );
 }
void get_numden_eos (Vec_Dbl * numden) const
get number density (#/barn-cm) at end of step
 {
     get_numden_eos( numden, b_cold_volume );
 }
void get_numden_at (Vec_Dbl * numden, size_t p, const Vec_Int & ids) const
get number density (#/barn-cm) at a time point
 {
     get_numden_at( numden, p, ids, b_cold_volume );
 }
void get_numden_bos (Vec_Dbl * numden, const Vec_Int & ids) const
get number density (#/barn-cm) at begin of step
 {
     get_numden_bos( numden, ids, b_cold_volume );
 }
void get_numden_eos (Vec_Dbl * numden, const Vec_Int & ids) const
get number density (#/barn-cm) at end of step
 {
     get_numden_eos( numden, ids, b_cold_volume );
 }
SP_TrMatrix transition_matrix_over (size_t i) const
get a transition matrix over a step
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step(), Origen::saveLibraries(), Origen::tabulateMaterialFission(), Origen::tabulateMaterialLoss(), and Origen::tabulateMaterialTransitionRates().
 {
     if( i < nsteps() )
     {
         return b_step_trx.at( i );
     }
     else
     {
         return nullptr;
     }
 }
SP_TrMatrix transition_matrix () const
get the current transition matrix
 {
     return transition_matrix_over( nsteps() - 1 );
 }
void set_transition_matrix (SP_TrMatrix trx)
set transition matrix of current step
Examples:
tstMaterialBuffer.cpp.
 {
     Require( nsteps() >= 1 );
     b_step_trx.back() = trx;
 }
double power_over (size_t i) const
get power (W) over a step
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step(), and Origen::saveStateSet().
 {
     if( i < nsteps() )
     {
         return b_step_power_watt.at( i );
     }
     else
     {
         return -1.0;
     }
 }
double power () const
get power (W) over current step
 { return power_over( nsteps() - 1 ); }
void set_power (double power)
set power (W) over current step
 {
     Require( nsteps() > 0 );
     // reset this history
     b_step_power_watt.back() = power;
     b_param_hist.clear();
     b_param_hist[0.0] = power;
     b_param_hist[1.0] = power;
     b_flux_parameter.back() = POWER;
     // clear accumlating histories
     b_power_hist.clear();
     b_flux_hist.clear();
     // reset interval flux
     b_step_flux_cm2s.back() = 0.0;
 }
void set_power_over (size_t i, double power)
set power (W) over any step
double flux_over (size_t i) const
get flux (#/cm^2-s) over a step
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_step(), Origen::saveStateSet(), and Origen::tabulateMaterialTransitionRates().
 {
     if( i < nsteps() )
     {
         return b_step_flux_cm2s.at( i );
     }
     else
     {
         return -1.0;
     }
 }
double flux () const
get flux (#/cm^2-s) over current step
Referenced by Origen::tabulateMaterialFission(), and Origen::tabulateMaterialLoss().
 { return flux_over( nsteps() - 1 ); }
void set_flux (double flux)
set flux (#/cm^2-s) over current step
Examples:
tstMaterialBuffer.cpp.
 {
     Require( nsteps() > 0 );
     // reset this history
     b_step_flux_cm2s.back() = flux;
     b_param_hist.clear();
     b_param_hist[0.0] = flux;
     b_param_hist[1.0] = flux;
     b_flux_parameter.back() = FLUX;
     // clear accumulating histories
     b_power_hist.clear();
     b_flux_hist.clear();
     // reset interval power
     b_step_power_watt.back() = 0.0;
 }
void set_flux_over (size_t i, double flux)
set flux (#/cm^2-s) over any step
double fluence_at (size_t p) const
get fluence (#/cm^2) at a point
 {
     Require( p < ntimes() );
     double fluence = 0.0;
     if( p == 0 ) return fluence;
     for( size_t i = 0; i < p; ++i )
     {
         fluence += flux_over( i ) * dt_over( i );
     }
     return fluence;
 }
double fluence_bos () const
get fluence (#/cm^2) at begin-of-step
 { return fluence_at( point_bos() ); }
double fluence_eos () const
get fluence (#/cm^2) at end-of-step
 { return fluence_at( point_eos() ); }
double burnup_at (size_t p) const
get burnup (MWd/MTIHM) at a point
 {
     Require( p < ntimes() );
     double joules = 0.0;
     double hm0 = initial_hm_mass();
     if( hm0 == 0.0 ) return 0.0;
     for( size_t i = 0; i < p; ++i )
     {
         joules += power_over( i ) * dt_over( i );
     }
     double mwd_mtihm = joules / ( 86400. * hm0 );  // convert
     return mwd_mtihm;
 }
double burnup_bos () const
get burnup (MWd/MTIHM) at begin-of-step
 { return burnup_at( point_bos() ); }
double burnup_eos () const
get burnup (MWd/MTIHM) at end-of-step
 { return burnup_at( point_eos() ); }
void get_concs_at (Concentrations * concs, size_t p) const
get/set concentrations at a particular time point
References Origen::ATOMS_B_CM, NuclideSet::ids(), Concentrations::nuclide_set(), Concentrations::set_units(), Concentrations::set_vals(), and Concentrations::set_volume().
Referenced by Origen::saveStateSet().
 {
     const auto& ids = concs->nuclide_set().ids();
     Vec_Dbl numden( ids.size(), 0.0 );
     get_numden_at( &numden, p, ids );
     concs->set_volume( cold_volume() );
     concs->set_units( ATOMS_B_CM );
     concs->set_vals( numden );
 }
void set_concs_at (const Concentrations & concs, size_t p)
References Origen::ATOMS_B_CM, Concentrations::convert_units(), NuclideSet::ids(), and Concentrations::nuclide_set().
 {
     const auto& ids = concs.nuclide_set().ids();
     Vec_Dbl numden;
     concs.convert_units( ATOMS_B_CM, &numden );
     set_numden_at( numden, p, ids );
 }
bool good (Vec_Str & errors) const virtual
 {
     size_t expected_times = ntimes();
     size_t expected_steps = expected_times - 1;
     size_t initial_errors = errors.size();
     if( !is_initialized() )
     {
         errors.push_back( "not initialized" );
     }
     // step variables
     if( b_step_flux_cm2s.size() != expected_steps )
     {
         std::stringstream ss;
         ss << "expected_steps=" << expected_steps
            << " != step_flux.size()=" << b_step_flux_cm2s.size() << std::endl;
         errors.push_back( ss.str() );
     }
     if( b_step_power_watt.size() != expected_steps )
     {
         std::stringstream ss;
         ss << "expected_steps=" << expected_steps
            << " != step_power.size()=" << b_step_power_watt.size() << std::endl;
         errors.push_back( ss.str() );
     }
     if( b_step_trx.size() != expected_steps )
     {
         std::stringstream ss;
         ss << "expected_steps=" << expected_steps
            << " != step_trx.size()=" << b_step_trx.size() << std::endl;
         errors.push_back( ss.str() );
     }
     // point variables
     if( b_point_amount_cm2barn.size() != expected_times )
     {
         std::stringstream ss;
         ss << "expected_times=" << expected_times
            << " != point_numden.size()=" << b_point_amount_cm2barn.size()
            << std::endl;
         errors.push_back( ss.str() );
     }
     if( b_point_time_s.size() != expected_times )
     {
         std::stringstream ss;
         ss << "expected_times=" << expected_times
            << " != point_time_s.size()=" << b_point_time_s.size() << std::endl;
         errors.push_back( ss.str() );
     }
     jDebugBlock( for( size_t i = initial_errors; i < errors.size(); ++i ) {
         jDebugLine( "Origen::Material ERROR: " << errors[i] );
     } );
     return errors.size() == initial_errors;
 }
bool good () const virtual
 {
     Vec_Str errors;
     return good( errors );
 }
bool is_initialized () const virtual
 {
     jDebugLine( this->to_string() );
     if( b_mass <= 0.0 ) return false;
     if( b_initial_hm_mass < 0.0 ) return false;
     if( b_name == "" ) return false;
     if( b_id <= -1 ) return false;
     if( b_library == nullptr ) return false;
     if( b_library_type == "" ) return false;
     return true;
 }
Json::Value to_json () const virtual
 {
     Json::Value json( Json::objectValue );
     return json;
 }
std::string to_string (int level = 1) const virtual
References Origen::h2string().
 {
     std::stringstream ss;
     ss << "name: " << b_name << std::endl;
     ss << "id: " << b_id << std::endl;
     ss << "library_type: " << b_library_type << std::endl;
     ss << "mass(g): " << b_mass << std::endl;
     ss << "hm_mass(g): " << b_initial_hm_mass << std::endl;
     ss << "cold_volume(cm^3): " << b_cold_volume << std::endl;
     ss << "step_data: " << std::endl;
     int width = 14;
     for( int j = 0; j < nsteps(); ++j )
     {
         ss << "   step:" << ( j + 1 ) << std::endl;
         ss << "      bos_time(s): " << b_point_time_s[j] << std::endl;
         ss << "      eos_time(s): " << b_point_time_s[j + 1] << std::endl;
         ss << "      flux(n/cm2s): " << b_step_flux_cm2s[j] << std::endl;
         ss << "      power(W): " << b_step_power_watt[j] << std::endl;
     }
     ss << "  power_hist: " << h2string( b_power_hist ) << std::endl;
     ss << "  flux_hist: " << h2string( b_flux_hist ) << std::endl;
     ss << "  param_hist: " << h2string( b_param_hist ) << std::endl;
     if( level < 1 ) return ss.str();
     ss << "nuclide_data(cm2/barn): " << std::endl;
     SCP_Vec_Int nucl = sizzzaaa_list();
     ss << std::setw( width ) << "index" << std::setw( width ) << "id";
     for( int j = 0; j < ntimes(); ++j )
     {
         ss << std::setw( width ) << b_point_time_s.at( j );
     }
     ss << std::endl;
     for( size_t i = 0; i < nucl->size(); ++i )
     {
         ss << std::fixed << std::setw( width ) << i << std::setw( width )
            << nucl->at( i );
         for( int j = 0; j < ntimes(); ++j )
         {
             ss << std::scientific << std::setw( width )
                << std::setprecision( 5 ) << b_point_amount_cm2barn[j]->at( i );
         }
         ss << std::fixed << std::endl;
     }
     ss << std::endl;
     return ss.str();
 }
bool has_initialized_id () const virtual
 { return b_id >= 0; }
int id () const virtual
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material().
 { return b_id; }
void get_id (int & id) const virtual
 { id = b_id; }
void set_id (int id) virtual
 { b_id = id; }
std::string name () const virtual
Examples:
tstMaterialBuffer.cpp.
Referenced by h5_write_material(), Origen::saveLibraries(), Origen::saveStateSet(), Origen::tabulateMaterialFission(), Origen::tabulateMaterialIsotopics(), Origen::tabulateMaterialLoss(), and Origen::tabulateMaterialTransitionRates().
 { return b_name; }
void set_name (std::string name) virtual
 { b_name = name; }
void get_name (std::string & name) const virtual
 { name = b_name; }
double volume_hist (double trel) const
 { return cold_volume(); }
Material::FluxParameter flux_parameter () const
 {
     if( nsteps() == 0 ) return UNKNOWN;
     return b_flux_parameter.back();
 }
Material::History_t param_hist () const
 { return b_param_hist; }
void set_param_hist (double , double)
double param_hist (double trel) const
 {
     Vec_Dbl t, p;
     ScaleSTL::map_to_vectors( b_param_hist, &t, &p );
     ScaleUtils::Math::Interp1D_FastLinear<double> fun;
     fun.set_data( t, p );
     return fun( trel );
 }
Material::History_t flux_hist () const
 { return b_flux_hist; }
void set_flux_hist (double trel, double flux)
 {
     Require( trel >= 0.0 && trel <= 1.0 );
     b_flux_hist[trel] = flux;
 }
double flux_hist (double trel) const
References kernel_rksuite::f().
 {
     Vec_Dbl t, f;
     ScaleSTL::map_to_vectors( b_flux_hist, &t, &f );
     ScaleUtils::Math::Interp1D_FastLinear<double> fun;
     fun.set_data( t, f );
     return fun( trel );
 }
Material::History_t power_hist () const
 { return b_power_hist; }
void set_power_hist (double trel, double power)
 {
     Require( trel >= 0.0 && trel <= 1.0 );
     b_power_hist[trel] = power;
 }
double power_hist (double trel) const
 {
     Vec_Dbl t, p;
     ScaleSTL::map_to_vectors( b_power_hist, &t, &p );
     ScaleUtils::Math::Interp1D_FastLinear<double> fun;
     fun.set_data( t, p );
     return fun( trel );
 }
void record_average_flux (const Vec_Dbl & scaling)
References Origen::integrate_history().
 {
     Require( nsteps() >= 1 );
     b_step_flux_cm2s.back() = integrate_history( scaling, b_flux_hist );
 }
void record_average_power (const Vec_Dbl & scaling)
References Origen::integrate_history().
 {
     Require( nsteps() >= 1 );
     b_step_power_watt.back() = integrate_history( scaling, b_power_hist );
 }
bool is_decay () const
 {
     if( power() == 0.0 && flux() == 0.0 ) return true;
     return false;
 }
double power_factor (double trel, const DoubleList & amount) const
The power factor is returned in units that could be multiplied by the flux to get the power in Watts produced in this material. It is basically Watts per unit scalar flux, so multiplying by scalar flux in (n/cm^2-s), which should be the average for this system, yields the Watts produced in this material. Note that this is the absolute Watts because the material is defined with a total amount proportional to number of atoms or moles (atoms-cm^2/barn).
amount (atoms-cm^2/barn) cold_volume x numden x sigma_a x kappa_a x C x 1 flux cm^3 x (atoms/cm-barn) x barn x MeV x J/MeV x 1 n/cm^2-s
 {
     SP_TrMatrix trx = transition_matrix();
     Check( trx != nullptr );
     return 1.60217657e-13 * trx->get_reaction_power( amount, 1.0, 1.0 );
 }
double decay_power (double trel, const DoubleList & amount) const
 {
     SP_TrMatrix trx = transition_matrix();
     Check( trx != nullptr );
     return 1.60217657e-13 * trx->get_decay_power( amount, 1.0 );
 }
double power_factor_bos () const
begin-of-step power factor (Watts per unit flux) produced by this material
 {
     return power_factor( 0.0, *b_amount_bos );
 }
double power_factor_mos () const
middle-of-step power factor (Watts per unit flux) produced by this material
 {
     return power_factor( 0.0, *b_amount_mos );
 }
double power_factor_eos () const
end-of-step power factor (Watts per unit flux) produced by this material
 {
     return power_factor( 1.0, *b_amount_eos );
 }
double trel_bos () const
 { return b_trel_bos; }
double trel_mos () const
 { return b_trel_mos; }
double trel_eos () const
 { return b_trel_eos; }
SP_DoubleList amount_mos () const
 { return b_amount_mos; }
void set_solver (SP_Solver solver)
 { b_solver = solver; }
SCP_Solver solver () const
 { return b_solver; }
void solve (Vec_Dbl & dtrel, Vec_Dbl * flux, Vec_Dbl * power)
 {
     flux->resize( dtrel.size() );
     power->resize( dtrel.size() );
     double trel0 = 0.0;
     double trel1;
     bool done = false;
     for( size_t i = 0; i < dtrel.size(); ++i )
     {
         trel1 = trel0 + dtrel[i];
         done = solve_inplace(
             0, trel0, trel1, 1.0, 1.0, &( *flux )[i], &( *power )[i] );
         Check( done ? i == dtrel.size() - 1 : i < dtrel.size() - 1 );
         trel0 = trel1;
     }
     Ensure( ScaleSTL::approx_eq( 1.0, b_trel_eos ) );
 }
bool solve_inplace (size_t nlit, double trel1, double trel2, double z0, double z1, double * flux, double * power)
 {
     Check( b_amount_eos.get() == b_point_amount_cm2barn.back().get() );
     // initialize swapping and set trels
     init_mos();
     if( nlit == 0 ) swap_mos_eos();
     //              nlit==0  | nlit>0
     // slot mos    : a(trel0) | a(trel-1)
     // slot bos    : a(0)
     // slot eos    : garbage
     swap_mos_bos();
     //              nlit==0  | nlit>0
     // slot mos    : a(0)     |
     // slot bos    : a(trel0) | a(trel-1)
     // slot eos    : garbage
     b_trel_bos = trel0;
     b_trel_eos = trel1;
     // check
     Check( ScaleSTL::approx_eq( 0.0, b_trel_mos ) );
     // solve
     solve_kernel( trel0, trel1, z0, z1, flux, power );
     // slot eos    : a(trel1)
     swap_mos_bos();
     // slot bos    : a(0)
     // slot mos    : a(trel0)
     // ensure we are leaving in the right state
     Ensure( ScaleSTL::approx_eq( 0.0, b_trel_bos ) );
     Ensure( ScaleSTL::approx_eq( trel0, b_trel_mos ) );
     Ensure( ScaleSTL::approx_eq( trel1, b_trel_eos ) );
     jDebugLine( "         amounts[at*cm^2/barn]:"
                 << " bos("
                 << b_trel_bos
                 << ")="
                 << ScaleSTL::sum( *b_amount_bos )
                 << " boss("
                 << b_trel_mos
                 << ")="
                 << ScaleSTL::sum( *b_amount_mos )
                 << " eoss("
                 << b_trel_eos
                 << ")="
                 << ScaleSTL::sum( *b_amount_eos ) );
     Check( b_amount_eos.get() == b_point_amount_cm2barn.back().get() );
     return ScaleSTL::approx_eq( 1.0, b_trel_eos );
 }
void solve_kernel (double trel1, double trel2, double z0, double z1, double * flux, double * power)
 {
     Require( z0 > 0.0 );
     Require( z1 > 0.0 );
     // z0,z1 are scaling factors for values at trel0 and trel1
     Require( this->dt() > 0.0 );
     // Checks to see if times were fed in a cumulative manner, as is expected,
     // or in terms of dt.
     // get change in time
     double dt = this->dt() * ( trel1 - trel0 );
     // set transition matrix on solver
     b_solver->set_transition_matrix( &*transition_matrix() );
     double f0 = 0.0;
     double f1 = 0.0;
     double p0 = 0.0;
     double p1 = 0.0;
     double pm = 0.0;
     double fm = 0.0;
     // decay
     if( is_decay() )
     {
         jDebugLine( "         Material::solve_kernel(decay)" );
         b_solver->solve( *b_amount_bos, 0.0, dt, &*b_amount_eos );
         p0 = decay_power( trel0, *b_amount_bos );
         p1 = decay_power( trel1, *b_amount_eos );
         pm = 0.5 * ( p0 + p1 );
     }
     // power
     else if( flux_parameter() == POWER )
     {
         jDebugLine( "         Material::solve_kernel(power)" );
         // get knowns
         p0 = z0 * param_hist( trel0 );
         p1 = z1 * param_hist( trel1 );
         // solve first time
         f0 = p0 / power_factor( trel0, *b_amount_bos );
         b_solver->solve( *b_amount_bos, f0, dt, &*b_amount_eos );
         // get new normalization based on eos
         f1 = p1 / power_factor( trel1, *b_amount_eos );
         // solve second time into temp eos vector
         DoubleList ntemp;
         ntemp.resize( b_amount_bos->size() );
         b_solver->solve( *b_amount_bos, f1, dt, &ntemp );
         // average results (true predictor/corrector)
         for( size_t i = 0; i < ntemp.size(); ++i )
         {
             ( *b_amount_eos )[i] = 0.5 * ( ( *b_amount_eos )[i] + ntemp[i] );
         }
         // better estimate for f1
         f1 = p1 / power_factor( trel1, *b_amount_eos );
         // update midpoints
         pm = 0.5 * ( p0 + p1 );
         fm = 0.5 * ( f0 + f1 );
     }
     // flux
     else if( flux_parameter() == FLUX )
     {
         jDebugLine( "         Material::solve_kernel(flux)" );
         // get knowns
         f0 = z0 * param_hist( trel0 );
         f1 = z1 * param_hist( trel1 );
         fm = 0.5 * ( f0 + f1 );
         // solve with average flux
         b_solver->solve( *b_amount_bos, fm, dt, &*b_amount_eos );
         // update powers
         p0 = f0 * power_factor( trel0, *b_amount_bos );
         p1 = f1 * power_factor( trel1, *b_amount_eos );
         pm = 0.5 * ( p0 + p1 );
     }
     // set histories
     set_power_hist( trel0, p0 / z0 );
     set_power_hist( trel1, p1 / z1 );
     set_flux_hist( trel0, f0 / z0 );
     set_flux_hist( trel1, f1 / z1 );
     *flux = fm;
     *power = pm;
 }
Vec_Dbl decay_substep_dtrel (size_t ns) static
Referenced by MultiZoneDepleter::update().
 {
     Vec_Dbl reltime( ns );
     for( size_t s = 0; s < ns; ++s )
     {
         reltime[s] = 1.0 / ( std::pow( 3, ( ns - s ) ) ) * 2.0;
         if( s == 0 ) reltime[s] *= 1.5;
     }
     return reltime;
 }
void init_mos () protected
 {
     if( b_amount_mos == nullptr )
     {
         b_amount_mos = SP_DoubleList( new DoubleList() );
         b_amount_mos->resize( total_nuclides() );
     }
     b_trel_mos = 0.0;
 }
void clear_mos () protected
 {
     b_amount_mos = nullptr;
     b_trel_mos = -1.0;
 }
void swap_mos_bos () protected
 {
     Require( nsteps() > 0 );
     init_mos();
     std::swap( b_amount_bos, b_amount_mos );
     std::swap( b_trel_bos, b_trel_mos );
     size_t p = point_bos();
     b_point_amount_cm2barn.at( p ) = b_amount_bos;
     Check( b_amount_bos.get() == b_point_amount_cm2barn.at( p ).get() );
 }
void swap_mos_eos () protected
 {
     Require( nsteps() > 0 );
     init_mos();
     std::swap( b_amount_eos, b_amount_mos );
     std::swap( b_trel_eos, b_trel_mos );
     size_t p = point_eos();
     b_point_amount_cm2barn.at( p ) = b_amount_eos;
     Check( b_amount_eos.get() == b_point_amount_cm2barn.back().get() );
 }
void initialize_mass () protected
mass initializer function
 {
     SP_DoubleList internal_amount = amount_at( 0 );
     if( internal_amount != nullptr )
     {
         b_mass = b_library->decay_data().mass(
             *internal_amount,
             1.66053892103, /* reciprocal of atoms/mol-barn=0.6022141290007942 */
             b_library->definition().nuclide_set(),
             b_initial_hm_mass );
     }
 }
void internal_initialize (std::string library_type, SP_Library library, std::string name, int id, double volume) protected
everything initializer function
The existing material storage is cleared and an initial time point and BOS amount vector is initialized. All libraries of the same library_type should share the same SP_Library.
Parameters
library_type - a type of the library
library - smart pointer to an Origen::Library
name - material name (unique)
id - material identification integer (unique)
 {
     clear();
     b_library_type = library_type;
     Check( library != nullptr );
     b_library = library;
     b_name = name;
     b_id = id;
     b_cold_volume = volume;
     b_initial_hm_mass_multiplier = 1.0;
     b_point_time_s.push_back( 0.0 );
     size_t n = b_library == nullptr ? 0 : b_library->total_nuclides();
     b_amount_bos = std::make_shared<DoubleList>();
     b_amount_bos->resize( n, 0.0 );
     b_point_amount_cm2barn.push_back( b_amount_bos );
     jDebugTaggedLine( "created Origen::Material("
                       << "id="
                       << b_id
                       << ",name="
                       << b_name
                       << ")" );
 }
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good_impl (Vec_Str & errors) const protected virtual inherited
useful to chain
Reimplemented in Nuclide, Channel, Null, Neutrino, Positron, Species, Transition, Electron, Field, Alpha, ChannelType_Reac, ChannelType_Decay, ChannelType_Fiss, Helion, TransitionSystem_Gen, Triton, Deuteron, Proton, and Neutron.
References ORIGEN_CHECKABLE_ERROR.
 {
     std::stringstream ss;
     bool pass = true;
     if( !has_initialized_id() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized id", pass, errors );
     return pass;
 }
bool is_initialized_impl () const protected virtual inherited
useful to chain
Reimplemented in Nuclide, Channel, ChannelType, Species, Transition, Field, and TransitionSystem_Gen.
 { return has_initialized_id(); }
Json::Value to_json_impl () const protected virtual inherited
useful to chain
Reimplemented in Nuclide, Channel, TransitionSystem, ChannelType, Species, Transition, and Field.
 {
     Json::Value json( Json::objectValue );
     json["name"] = name();
     json["id"] = id();
     json["is_initialized"] = is_initialized();
     json["has_initialized_id"] = has_initialized_id();
     Vec_Str errors;
     json["good"] = good( errors );
     Standard::Json::arrayToJson( json["errors"], errors );
     return json;
 }
Member Data Documentation
std::string b_library_type protected
library type for general book-keeping
SP_Library b_library protected
actual library for reference values
double b_mass protected
total mass (g) at time=0
double b_initial_hm_mass protected
total mass in heavy metal (g) at time=0
double b_initial_hm_mass_multiplier protected
SP_Solver b_solver protected
solver
double b_trel_bos protected
SP_DoubleList b_amount_bos protected
double b_trel_mos protected
SP_DoubleList b_amount_mos protected
double b_trel_eos protected
SP_DoubleList b_amount_eos protected
History_t b_flux_hist protected
History_t b_power_hist protected
History_t b_param_hist protected
std::string b_name protected
saved name for this material
int b_id protected
saved id
double b_cold_volume protected
volume (cm^3) at cold conditions
Deq_Dbl b_step_flux_cm2s protected
average flux magnitude (#/cm^2-s) over each step
Deq_Dbl b_step_power_watt protected
average power (W) over each step
Deq_TrMatrix b_step_trx protected
transition matrix over each step
std::deque<FluxParameter> b_flux_parameter protected
provided "flux" parameter over each step
Deq_Dbl b_point_time_s protected
time (s) at each point
Deq_Amt b_point_amount_cm2barn protected
nuclide amount (cm^2/barn)
The documentation for this class was generated from the following files:
Core/dc/Material.h
Core/dc/Material.cpp