ORIGEN API: Field Class Reference
Field Class Reference abstract
#include <Field.h>
Defines the field interface for the TransitionSystem.
Public Types
typedef SP_Field SP
strong pointer
typedef WP_Field WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Field>>
See Origen::Field for details.
double intensity () const
void get_intensity (double &intensity) const
void set_intensity (double intensity)
bool has_initialized_intensity () const
SP_Species species () const
void get_species (SP_Species &species) const
void set_species (SP_Species species)
bool has_initialized_species () const
Public Member Functions
virtual ~Field ()
destructor
Private Member Functions
virtual double intensity_impl () const =0
virtual void get_intensity_impl (double &intensity) const
virtual void set_intensity_impl (double intensity)=0
virtual bool has_initialized_intensity_impl () const
virtual SP_Species species_impl () const =0
virtual void get_species_impl (SP_Species &species) const
virtual void set_species_impl (SP_Species species)=0
virtual bool has_initialized_species_impl () const
virtual std::string name_impl () const
virtual int id_impl () const
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual bool is_initialized_impl () const
useful to chain
virtual Scale::Json::Value to_json_impl () const
useful to chain
Detailed Description
Defines the field interface for the TransitionSystem.
The field, in the context of the transition system, manages two piece of data:
intensity of the field (e.g. n/cm^2-s for neutrons)
species composing the field
See also
Species
Member Typedef Documentation
typedef SP_Field SP
strong pointer
typedef WP_Field WP
weak pointer
Constructor & Destructor Documentation
~Field () virtual
destructor
 {}
Member Function Documentation
double intensity () const
Referenced by Field_Gen::set_intensity_impl().
 { return intensity_impl(); }
void get_intensity (double & intensity) const
 {
     get_intensity_impl( intensity );
 }
void set_intensity (double intensity)
Referenced by NullField::NullField().
 {
     set_intensity_impl( intensity );
 }
bool has_initialized_intensity () const
 {
     return has_initialized_intensity_impl();
 }
SP_Species species () const
Referenced by Field_Gen::set_species_impl().
 { return species_impl(); }
void get_species (SP_Species & species) const
 {
     get_species_impl( species );
 }
void set_species (SP_Species species)
Referenced by AlphaField::AlphaField(), DeuteronField::DeuteronField(), ElectronField::ElectronField(), HelionField::HelionField(), NeutrinoField::NeutrinoField(), NeutronField::NeutronField(), NullField::NullField(), PositronField::PositronField(), ProtonField::ProtonField(), and TritonField::TritonField().
 { set_species_impl( species ); }
bool has_initialized_species () const
 {
     return has_initialized_species_impl();
 }
double intensity_impl () const private pure virtual
Implemented in Field_Gen.
References Origen::BAD_DOUBLE.
 { return BAD_DOUBLE; }
void get_intensity_impl (double & intensity) const private virtual
Reimplemented in Field_Gen.
 {
     Insist( false,
             "void Field::get_intensity_impl(double& intensity) const NOT "
             "IMPLEMENTED" );
 }
void set_intensity_impl (double intensity) private pure virtual
Implemented in Field_Gen.
 {
     Insist(
         false,
         "void Field::set_intensity_impl(double  intensity) NOT IMPLEMENTED" );
 }
bool has_initialized_intensity_impl () const private virtual
References Origen::BAD_DOUBLE.
 {
     return intensity() != BAD_DOUBLE;
 }
SP_Species species_impl () const private pure virtual
Implemented in Field_Gen.
 { return nullptr; }
void get_species_impl (SP_Species & species) const private virtual
Reimplemented in Field_Gen.
 {
     Insist( false,
             "void Field::get_species_impl(SP_Species& species) const NOT "
             "IMPLEMENTED" );
 }
void set_species_impl (SP_Species species) private pure virtual
Implemented in Field_Gen.
 {
     Insist(
         false,
         "void Field::set_species_impl(SP_Species  species) NOT IMPLEMENTED" );
 }
bool has_initialized_species_impl () const private virtual
 {
     return species() != nullptr;
 }
std::string name_impl () const private virtual
Reimplemented from Checkable.
Reimplemented in NullField, NeutrinoField, PositronField, ElectronField, AlphaField, HelionField, TritonField, DeuteronField, ProtonField, and NeutronField.
 {
     std::stringstream ss;
     ss << "FIELD(" << id() << ")";
     return ss.str();
 }
int id_impl () const private virtual
Reimplemented from Checkable.
Reimplemented in NullField, NeutrinoField, PositronField, ElectronField, AlphaField, HelionField, TritonField, DeuteronField, ProtonField, and NeutronField.
References Origen::BAD_INT.
 {
     if( species() == nullptr )
     {
         return BAD_INT;
     }
     else
     {
         return species()->id();
     }
 }
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
References ORIGEN_CHECKABLE_ERROR.
 {
     bool pass = Checkable::good_impl( errors );
     if( !has_initialized_species() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized species", pass, errors );
     if( !has_initialized_intensity() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized intensity", pass, errors );
     return pass;
 }
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     return has_initialized_species() && has_initialized_intensity() &&
            Checkable::is_initialized_impl();
 }
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     Json::Value json( Json::objectValue );
     json = Checkable::to_json_impl();
     json["species"] = "NULL";
     if( has_initialized_species() )
     {
         json["species"] = species()->to_json();
     }
     json["has_initialized_species"] = has_initialized_species();
     json["intensity"] = intensity();
     json["has_initialized_intensity"] = has_initialized_intensity();
     return json;
 }
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Field.h
Core/ts/Field.cpp