ORIGEN API: Core/io/tests/tstYieldResourceIO.cpp File Reference
tstYieldResourceIO.cpp File Reference
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <istream>
#include <string>
#include <vector>
#include "Origen/Core/io/YieldResourceIO.h"
#include "ScaleData/Core/Utils.h"
#include "ScaleFileUtils/FileUtils.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Origen/Core/fn/print.h"
#include "Origen/Core/TestPaths.h"
#include "Origen/Core/io/STab1Reader.h"
#include "Origen/Core/io/STab1Writer.h"
Classes
class STab1WriterTester
Macros
#define SEXPECT_EQ(a, b) EXPECT_EQ(a, STab1WriterTester::as_string(b))
Functions
TEST (YieldResourceIOTester, Data)
TEST (YieldResourceIOTester, AmpxFloatWriting)
TEST (YieldResourceIOTester, Rebaseline)
TEST (YieldResourceIOTester, ExperimentalCumulativeYields)
TEST (YieldResourceIOTester, RoundTrip)
TEST (YieldResourceIOTester, ErrorTryingToLoadDecay)
Macro Definition Documentation
#define SEXPECT_EQ (a, b) EXPECT_EQ(a, STab1WriterTester::as_string(b))
Examples:
Core/io/tests/tstYieldResourceIO.cpp.
Referenced by TEST().
Function Documentation
TEST (YieldResourceIOTester , Data)
References YieldParent::data_at(), YieldParent::fp_index(), YieldParent::get_energies(), YieldParent::get_fp_ids(), YieldParent::get_interp_yields(), YieldParent::has_fp(), Origen::loadYieldResource(), Origen::printYields(), and YieldData::yield_at().
TEST (YieldResourceIOTester , AmpxFloatWriting)
References SEXPECT_EQ.
TEST (YieldResourceIOTester , Rebaseline)
References Origen::INTERP_LINLIN, Origen::loadYieldResource(), Origen::printInterpolatedYields(), Origen::printYieldEnergies(), and Origen::printYields().
TEST (YieldResourceIOTester , ExperimentalCumulativeYields)
References Origen::INTERP_LINLIN, Origen::loadYieldResource(), Origen::printInterpolatedYields(), Origen::printYieldEnergies(), and Origen::printYields().
TEST (YieldResourceIOTester , RoundTrip)
References Origen::loadYieldResource(), and Origen::saveYieldResource().
TEST (YieldResourceIOTester , ErrorTryingToLoadDecay)