ORIGEN API: Transition Class Reference
Transition Class Reference abstract
#include <Transition.h>
Defines the transition interface for the TransitionSystem.
Public Types
typedef SP_Transition SP
strong pointer
typedef WP_Transition WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Transition>>
See Origen::Transition for details.
WP_Nuclide product () const
return the product nuclide
void set_product (WP_Nuclide product)
set the product nuclide
WP_Channel channel () const
return the parent channel
void set_channel (WP_Channel channel)
set the channel
double yield () const
return the yield, i.e. number of product nuclides per transition
void set_yield (const double &yield)
set the yield
bool has_initialized_yield () const
whether yield has been initialized for this transition
double coeff () const
double rate () const
bool is_byproduct () const
whether this transition is a byproduct
Private Member Functions
virtual WP_Nuclide product_impl () const =0
virtual void set_product_impl (WP_Nuclide product)=0
virtual WP_Channel channel_impl () const =0
virtual void set_channel_impl (WP_Channel channel)=0
virtual double yield_impl () const =0
virtual void set_yield_impl (const double &yield)=0
virtual bool has_initialized_yield_impl () const =0
virtual bool is_byproduct_impl () const
virtual bool is_initialized_impl () const
useful to chain
virtual std::string name_impl () const
virtual int id_impl () const
virtual bool good_impl (Vec_Str &errors) const
useful to chain
virtual Scale::Json::Value to_json_impl () const
useful to chain
Detailed Description
Defines the transition interface for the TransitionSystem.
The transition, in the context of the transition system, manages one piece of data:
yield (number of products produced per transition)
It has
a weak pointer to its parent channel
a weak pointer to the product of the transition
See also
Channel, Nuclide
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef SP_Transition SP
strong pointer
typedef WP_Transition WP
weak pointer
Member Function Documentation
Nuclide::WP product () const
return the product nuclide
Referenced by Transition_Gen::set_product_impl().
 { return product_impl(); }
void set_product (WP_Nuclide product)
set the product nuclide
Referenced by Transition_Gen::Transition_Gen().
 {
     set_product_impl( product );
 }
Channel::WP channel () const
return the parent channel
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by Nuclide_Gen::append_gain_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), LibraryBuilder::search_reaction_transitions(), Transition_Gen::set_channel_impl(), and TEST_F().
 { return channel_impl(); }
void set_channel (WP_Channel channel)
set the channel
 {
     set_channel_impl( channel );
 }
double yield () const
return the yield, i.e. number of product nuclides per transition
Referenced by Transition_Gen::set_yield_impl().
 { return yield_impl(); }
void set_yield (const double & yield)
set the yield
 { set_yield_impl( yield ); }
bool has_initialized_yield () const
whether yield has been initialized for this transition
 {
     return has_initialized_yield_impl();
 }
double coeff () const
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), and TEST_F().
 { return channel()->coeff() * yield(); }
double rate () const
 { return channel()->rate() * yield(); }
bool is_byproduct () const
whether this transition is a byproduct
 { return is_byproduct_impl(); }
Nuclide::WP product_impl () const private pure virtual
Implemented in Transition_Gen.
 { return nullptr; }
virtual void set_product_impl (WP_Nuclide product) private pure virtual
Implemented in Transition_Gen.
Channel::WP channel_impl () const private pure virtual
Implemented in Transition_Gen.
 { return nullptr; }
virtual void set_channel_impl (WP_Channel channel) private pure virtual
Implemented in Transition_Gen.
double yield_impl () const private pure virtual
Implemented in Transition_Gen.
 { return 0.0; }
virtual void set_yield_impl (const double & yield) private pure virtual
Implemented in Transition_Gen.
virtual bool has_initialized_yield_impl () const private pure virtual
Implemented in Transition_Gen.
bool is_byproduct_impl () const private virtual
Reimplemented in Transition_GenByp.
 { return false; }
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     return has_initialized_yield() && Checkable::is_initialized_impl();
 }
std::string name_impl () const private virtual
Reimplemented from Checkable.
 {
     std::stringstream ss;
     if( this->channel() == nullptr )
     {
         ss << "TRANSITION(BAD," << this->id() << ")";
     }
     else
     {
         Check( channel() != nullptr );
         ss << "TRANSITION(" << channel()->name() << "," << this->id() << ")";
     }
     return ss.str();
 }
int id_impl () const private virtual
Reimplemented from Checkable.
References Origen::BAD_INT.
 {
     // NOTE: this switch should only need to be here
     if( product() != nullptr && channel() != nullptr )
     {
         if( channel()->channel_type()->has_distribution_of_daughters() )
         {
             return product()->id();
         }
         else
         {
             return product()->isomeric_state();
         }
     }
     return BAD_INT;
 }
bool good_impl (Vec_Str & errors) const private virtual
useful to chain
Reimplemented from Checkable.
 {
     bool pass = Checkable::good_impl( errors );
     return pass;
 }
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     Json::Value json( Json::objectValue );
     json = Checkable::to_json_impl();
     if( product() != nullptr )
     {
         json["product"] = product()->id();
     }
     else
     {
         json["product"] = 0;
     }
     if( channel() != nullptr )
     {
         json["channel"] = channel()->id();
     }
     else
     {
         json["channel"] = 0;
     }
     json["yield"] = yield();
     json["coeff"] = coeff();
     json["rate"] = rate();
     json["is_byproduct"] = is_byproduct();
     return json;
 }
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
The documentation for this class was generated from the following files:
Core/ts/Transition.h
Core/ts/Transition.cpp