ORIGEN API: origen_neutronspectra Type Reference
origen_neutronspectra Type Reference
Public Member Functions
procedure, pass(this) intensity_sf_size => Origen_NeutronSpectra_intensity_sf_size
procedure, pass(this) has_intensity_sf => Origen_NeutronSpectra_has_intensity_sf
procedure, pass(this) get_intensity_sf_vec => Origen_NeutronSpectra_get_intensity_sf_vec
procedure, pass(this) set_intensity_sf_vec => Origen_NeutronSpectra_set_intensity_sf_vec
procedure, pass(this) manageptr_intensity_sf => Origen_NeutronSpectra_manageptr_intensity_sf
procedure, pass(this) getptr_intensity_sf_vec => Origen_NeutronSpectra_getptr_intensity_sf_vec
procedure, pass(this) get_intensity_sf => Origen_NeutronSpectra_get_intensity_sf
procedure, pass(this) intensity_sf_at => Origen_NeutronSpectra_intensity_sf_at
procedure, pass(this) set_intensity_sf => Origen_NeutronSpectra_set_intensity_sf
procedure, pass(this) intensity_alphan_size => Origen_NeutronSpectra_intensity_alphan_size
procedure, pass(this) has_intensity_alphan => Origen_NeutronSpectra_has_intensity_alphan
procedure, pass(this) get_intensity_alphan_vec => Origen_NeutronSpectra_get_intensity_alphan_vec
procedure, pass(this) set_intensity_alphan_vec => Origen_NeutronSpectra_set_intensity_alphan_vec
procedure, pass(this) manageptr_intensity_alphan => Origen_NeutronSpectra_manageptr_intensity_alphan
procedure, pass(this) getptr_intensity_alphan_vec => Origen_NeutronSpectra_getptr_intensity_alphan_vec
procedure, pass(this) get_intensity_alphan => Origen_NeutronSpectra_get_intensity_alphan
procedure, pass(this) intensity_alphan_at => Origen_NeutronSpectra_intensity_alphan_at
procedure, pass(this) set_intensity_alphan => Origen_NeutronSpectra_set_intensity_alphan
procedure, pass(this) intensity_delayn_size => Origen_NeutronSpectra_intensity_delayn_size
procedure, pass(this) has_intensity_delayn => Origen_NeutronSpectra_has_intensity_delayn
procedure, pass(this) get_intensity_delayn_vec => Origen_NeutronSpectra_get_intensity_delayn_vec
procedure, pass(this) set_intensity_delayn_vec => Origen_NeutronSpectra_set_intensity_delayn_vec
procedure, pass(this) manageptr_intensity_delayn => Origen_NeutronSpectra_manageptr_intensity_delayn
procedure, pass(this) getptr_intensity_delayn_vec => Origen_NeutronSpectra_getptr_intensity_delayn_vec
procedure, pass(this) get_intensity_delayn => Origen_NeutronSpectra_get_intensity_delayn
procedure, pass(this) intensity_delayn_at => Origen_NeutronSpectra_intensity_delayn_at
procedure, pass(this) set_intensity_delayn => Origen_NeutronSpectra_set_intensity_delayn
procedure, pass(this) initialize => Origen_NeutronSpectra_initialize
procedure, pass(this) destroy => Origen_NeutronSpectra_destroy
Member Typedef Documentation
typedef std::shared_ptr<Spectrum> SP inherited
typedef std::shared_ptr<const Spectrum> SCP inherited
typedef std::function<SP_Vec_Dbl(const Vec_Dbl &, const Vec_Int &, const Vec_Dbl &)> Integrator_t inherited
Member Function/Subroutine Documentation
procedure, pass(this) intensity_sf_size ()
procedure, pass(this) has_intensity_sf ()
procedure, pass(this) get_intensity_sf_vec ()
procedure, pass(this) set_intensity_sf_vec ()
procedure, pass(this) manageptr_intensity_sf ()
procedure, pass(this) getptr_intensity_sf_vec ()
procedure, pass(this) get_intensity_sf ()
procedure, pass(this) intensity_sf_at ()
procedure, pass(this) set_intensity_sf ()
procedure, pass(this) intensity_alphan_size ()
procedure, pass(this) has_intensity_alphan ()
procedure, pass(this) get_intensity_alphan_vec ()
procedure, pass(this) set_intensity_alphan_vec ()
procedure, pass(this) manageptr_intensity_alphan ()
procedure, pass(this) getptr_intensity_alphan_vec ()
procedure, pass(this) get_intensity_alphan ()
procedure, pass(this) intensity_alphan_at ()
procedure, pass(this) set_intensity_alphan ()
procedure, pass(this) intensity_delayn_size ()
procedure, pass(this) has_intensity_delayn ()
procedure, pass(this) get_intensity_delayn_vec ()
procedure, pass(this) set_intensity_delayn_vec ()
procedure, pass(this) manageptr_intensity_delayn ()
procedure, pass(this) getptr_intensity_delayn_vec ()
procedure, pass(this) get_intensity_delayn ()
procedure, pass(this) intensity_delayn_at ()
procedure, pass(this) set_intensity_delayn ()
procedure, pass(this) initialize ()
procedure, pass(this) destroy ()
const Vec_Dbl & bounds () const inherited
return a const reference to bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Spectrum goes out of scope.
Referenced by Spectrum::operator==(), and StateSetIO_bof::write().
void set_bounds (const Vec_Dbl & bounds) inherited
set the bounds (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
tstEmissionResource.cpp, tstEmissionSpectrum.cpp, and tstGammaResource.cpp.
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), StateSetIO_bof::read(), GammaResourceIO_cimg::read(), and FakeFactory::StateSet_random1().
const Vec_Dbl & intensity () const inherited
return a const reference to intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of Spectrum goes out of scope.
Referenced by Spectrum::operator==(), and StateSetIO_bof::write().
void set_intensity (const Vec_Dbl & intensity) inherited
set the intensity (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by FakeFactory::newspStateSet_10nuclide(), StateSetIO_s62b::read(), StateSetIO_s61::read(), StateSetIO_bof::read(), GammaResourceIO_cimg::read(), and FakeFactory::StateSet_random1().
bool match (const Spectrum & b) const inherited
Referenced by NeutronSpectra::match(), BetaSpectra::match(), GammaSpectra::match(), and AlphaSpectra::match().
bool match (const Spectrum & a, const Spectrum & b) static inherited
References Spectrum::b_bounds.
bool operator== (const Spectrum & b) const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, Spectrum::bounds(), and Spectrum::intensity().
Referenced by AlphaSpectra::operator==(), GammaSpectra::operator==(), and BetaSpectra::operator==().
double total_intensity () const inherited
References Spectrum::b_intensity, and Spectrum::has_intensity().
Referenced by Spectrum::mean_energy(), and EmissionSpectrum::total_intensity().
EnergyRange_t energy_range () const inherited
References Spectrum::b_bounds, Origen::EMAX, Origen::EMIN, and auxiliary_erf_m::er.
Referenced by EmissionSpectrum::energy_range().
double mean_energy () const inherited
References Spectrum::total_energy_intensity(), and Spectrum::total_intensity().
double total_energy_intensity () const inherited
References Spectrum::newsp_energy_intensity().
Referenced by Spectrum::mean_energy(), and EmissionSpectrum::total_energy_intensity().
SP_Vec_Dbl newsp_energy_intensity () const inherited
References Spectrum::newptr_energy_intensity().
Referenced by Spectrum::total_energy_intensity().
Vec_Dbl * newptr_energy_intensity () const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, and Spectrum::intensity_size().
Referenced by Spectrum::newsp_energy_intensity().
SCP_Vec_Dbl scp_intensity () const inherited
return a shared (read-only) intensity pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
SCP_Vec_Dbl scp_bounds () const inherited
return a shared (read-only) bounds pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool map_intensity (const Vec_Dbl & new_bounds, Integrator_t integrator, Vec_Dbl * intensity, double wt = 1.0, double tol = ETOL) const inherited
Referenced by EmissionSpectrum::bin(), Spectrum::map_intensity(), and Spectrum::remap_intensity().
bool map_intensity (const Vec_Dbl & new_bounds, Vec_Dbl * intensity, double wt = 1.0, double tol = ETOL) const inherited
References Spectrum::computeUnionWts_1(), and Spectrum::map_intensity().
void map_intensity (const Vec_Dbl & old_bounds, const Vec_Dbl & new_bounds, const Vec_Int & union_to_old, const Vec_Int & union_to_new, const Vec_Dbl & union_grid, const Vec_Dbl & old_intensity, const Vec_Dbl & union_wts, Vec_Dbl * new_intensity, double wt = 1.0) static inherited
void remap_intensity (Vec_Dbl * intensity, double wt = 1.0) const inherited
References Spectrum::b_bounds, Spectrum::b_intensity, Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, Spectrum::b_union_wts, Spectrum::has_mapping_variables(), and Spectrum::map_intensity().
bool has_mapping_variables () const inherited
References Spectrum::b_intensity, Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, and Spectrum::b_union_wts.
Referenced by Spectrum::remap_intensity().
void clear_mapping_variables () const inherited
References Spectrum::b_new_bounds, Spectrum::b_union_grid, Spectrum::b_union_to_new, Spectrum::b_union_to_old, and Spectrum::b_union_wts.
std::string print_bins () const inherited
Examples:
tstDiscreteSpectrum.cpp, tstEmissionResource.cpp, tstEmissionSpectrum.cpp, tstGammaResource.cpp, and tstGammaResourceIO.cpp.
References Spectrum::b_bounds, and Spectrum::b_intensity.
Referenced by EmissionSpectrum::print_continuous().
std::string print_bins (const Vec_Dbl & bounds, const Vec_Dbl & intensity) static inherited
Vec_Dbl::value_type bounds_at (size_t i) const inherited
get element of bounds vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
tstGammaResourceIO.cpp.
Vec_Dbl::value_type const * bounds_array () const inherited
return view of bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t bounds_size () const inherited
return size of bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by Spectrum::canonicalize_intensity().
bool has_bounds () const inherited
return whether the class has a non-null bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_bounds (Vec_Dbl & bounds) const inherited
populate an existing Vec_Dbl with a copy of bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_bounds (Vec_Dbl *& bounds) inherited
set the bounds (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_bounds (Vec_Dbl const *& bounds) const inherited
retrieve pointer (read-only) to bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_bounds_array (size_t , double *) const inherited
get array of bounds vector (Fortran)
void set_bounds_array (size_t , double *) inherited
set bounds vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type intensity_at (size_t i) const inherited
get element of intensity vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Vec_Dbl::value_type const * intensity_array () const inherited
return view of intensity vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by StateSetIO_s62b::write().
size_t intensity_size () const inherited
return size of intensity vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by NeutronSpectra::is_consistent(), Spectrum::newptr_energy_intensity(), EmissionSpectrum::num_continuous(), and NeutronSpectra::resum().
bool has_intensity () const inherited
return whether the class has a non-null intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Spectrum::total_intensity().
void get_intensity (Vec_Dbl & intensity) const inherited
populate an existing Vec_Dbl with a copy of intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_intensity (Vec_Dbl *& intensity) inherited
set the intensity (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_intensity (Vec_Dbl const *& intensity) const inherited
retrieve pointer (read-only) to intensity
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_intensity_array (size_t , double *) const inherited
get array of intensity vector (Fortran)
void set_intensity_array (size_t , double *) inherited
set intensity vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
bool map_bins (const Vec_Dbl & old_bounds, const Vec_Dbl & new_bounds, Vec_Int * union_to_old, Vec_Int * union_to_new, Vec_Dbl * union_grid, double tol = ETOL) static inherited
SP_Vec_Dbl computeUnionWts_1 (const Vec_Dbl & union_grid, const Vec_Int & union_to_old, const Vec_Dbl & old_flux) static inherited
Referenced by Spectrum::map_intensity().
void canonicalize_bounds () protected inherited
void canonicalize_intensity () protected inherited
References Spectrum::b_intensity, and Spectrum::bounds_size().
Member Data Documentation
SP_Vec_Dbl b_bounds protected inherited
Referenced by Spectrum::energy_range(), Spectrum::match(), Spectrum::newptr_energy_intensity(), Spectrum::operator==(), Spectrum::print_bins(), and Spectrum::remap_intensity().
SP_Vec_Dbl b_intensity protected inherited
Referenced by Spectrum::canonicalize_intensity(), Spectrum::has_mapping_variables(), NeutronSpectra::is_consistent(), Spectrum::newptr_energy_intensity(), Spectrum::operator==(), Spectrum::print_bins(), Spectrum::remap_intensity(), NeutronSpectra::resum(), and Spectrum::total_intensity().
The documentation for this type was generated from the following file:
Core/dc/f/NeutronSpectra_M.f90