ORIGEN API: Obiwan_tag Class Reference
Obiwan_tag Class Reference
#include <Obiwan_tag.h>
execute obiwan in tag mode
Public Member Functions
Obiwan_tag (int argc, char **argv)
Obiwan_tag (ScaleUtils::IO::DB opts)
~Obiwan_tag () noexcept(false)
int execute (std::ostream &out, std::ostream &err)
Tag management operations (add/delete tags from TagManager)
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in tag mode
Examples:
Core/ut/tests/tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_tag (int argc, char ** argv)
References Obiwan_tag::b_opts, and Obiwan_tag::populate().
 {
     b_opts = populate( argc, argv );
 }
Obiwan_tag (ScaleUtils::IO::DB opts)
 : b_opts( opts ) {}
~Obiwan_tag () inline noexcept
 {}
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_tag::execute().
 {
     const char* help = R"help(
 //! [help]
  purpose: modify tags on ORIGEN binary files
  usage: obiwan tag [-idtags='tag1=[v1],tag2=[v2]']
                    [-interptags='tag3=[v3],tag4=[v4]'] file
        to list all tags:     no -idtags or -interptags
                              EXAMPLE:
                              obiwan tag file
        to add/modify a tag:  list the tag and value (comma-separated)
                              EXAMPLE:
                              obiwan tag -idtags='assembly=W17x17'
                                       -interptags='temp=900,mod=0.7' file
        to delete a tag:      list the tag with empty value
                              obiwan tag -idtags='assembly='
        NOTE: obiwan tag modifies an ORIGEN binary in place
  example:
     #add size, vendor, and enrichment tags to all w17* assemblies
     $ mkdir -p new
     $ cp $DATA/arplibs/w17* new
     $ obiwan tag new/\* -idtags='size=17,vendor=W' 2>log
     $ obiwan tag new/\*e60.arplib -interptags='enr=6.0' 2>log
     $ obiwan tag new/\*e50.arplib -interptags='enr=5.0' 2>log
     $ obiwan tag new/\*e40.arplib -interptags='enr=4.0' 2>log
     $ obiwan tag new/\*e30.arplib -interptags='enr=3.0' 2>log
     $ obiwan tag new/\*e20.arplib -interptags='enr=2.0' 2>log
     $ obiwan tag new/\*e15.arplib -interptags='enr=1.5' 2>log
     $ obiwan tag new/\*.arplib 2>log
         new/w17_e15.arplib: {
            idtags: {
               size: 17,
               vendor: W   }
            interptags: {
               enr: 1.5,    }
         }
         new/w17_e20.arplib: {
            idtags: {
               size: 17,
               vendor: W   }
            interptags: {
               enr: 2,    }
         }
         ...
 //! [help]
     )help";
     // break up tag so Doxygen doesn't think this is a 3rd tag
     return ScaleUtils::IO::removeSubstring( help,
                                             "//! ["
                                             ""
                                             "help"
                                             ""
                                             "]" );
 }
ScaleUtils::IO::DB populate (int argc, char ** argv) static
References Origen::baseOptions(), and Origen::parseTags().
Referenced by Obiwan_tag::Obiwan_tag().
 {
     Standard::CommandLine cmd( argc, argv );
     // get files
     Origen::Vec_Str files = cmd.arguments();
     ScaleUtils::IO::DB base;
     // output error message
     if( files.size() == 0 )
     {
         base.set( "help", true );
     }
     else
     {
         // debugging echo
         jDebugLine( cmd.toString() );
         // expand globs (e.g. *.txt)
         ScaleUtils::IO::expandPaths( files );
         base = baseOptions();
         // set files
         base.set<StringList*>( "paths", new StringList( files ) );
         // we will do the same thing for id and interp tags so we
         // will loop through and do the same thing twice
         const std::map<std::string, std::string> tag_sets = {
             {"-idtags", "id"}, {"-interptags", "interp"}};
         for( auto& tag_pair : tag_sets )
         {
             std::string flag = tag_pair.first;
             std::string key = tag_pair.second;
             // parse the command line argument that has tags of the form
             // tag1,tag2=,tag3=val3,...
             Origen::Vec_Str tags;
             Origen::Vec_Str values;
             Origen::Vec_Bool modify;
             std::string error =
                 parseTags( cmd.getValue( flag, "" ), &tags, &values, &modify );
             if( error != "" ) base.appendError( error );
             // create a data container with the tags/values/whether to modify
             base.set<StringList*>( key + "tags", new StringList( tags ) );
             base.set<StringList*>( key + "values", new StringList( values ) );
             base.set<LogicalList*>( key + "modify", new LogicalList( modify ) );
         }
     }
     return base;
 }
int execute (std::ostream & out, std::ostream & err)
Tag management operations (add/delete tags from TagManager)
manageTags takes arguments from a command line argument for tag type (either -idtags or -interptags); for each tag following the tag type,
If the tag does not exist, it will add the tag to the TagManager If the tag exists and a value is provided, it will replace the value of of the tag on TagManager If the tag exists and no value is provided, the tag is deleted
References Obiwan_tag::b_opts, TagManager::deleteTag(), Obiwan_tag::help(), Origen::loadMulti(), Origen::printTags_json(), Origen::saveLibrary(), TagManager::setIdTag(), and TagManager::setInterpTag().
Referenced by Origen::obiwan_main().
 {
     // quick returns
     if( b_opts.get( "help", false ) )
     {
         out << help() << std::endl;
         return 1;
     }
     else if( b_opts.numError() > 0 )
     {
         return -1;
     }
     // Loop over files.
     Require( b_opts.has<StringList*>( "paths" ) );
     for( auto path : *b_opts.get<StringList*>( "paths" ) )
     {
         jDebugLine( "   reading file=" << path );
         // variables;
         Origen::SP_Library lib;
         // load
         ScaleUtils::IO::DB opts( b_opts );
         void* obj_ptr = loadMulti( path, opts );
         jDebugLine( opts.toString() );
         std::string foundDataType = opts.get<std::string>( "loadedDataType" );
         if( foundDataType == "Origen::Library" )
         {
             lib = Origen::SP_Library( (Library*)( obj_ptr ) );
             jDebugLine( "read lib from path=" << path );
             Check( lib );
         }
         else
         {
             err << "path=" << path << " is not an Origen::Library\n";
         }
         TagManager tagman = lib->tag_manager();
         // set up id tags
         auto idtags = b_opts.get<StringList*>( "idtags" );
         auto idvalues = b_opts.get<StringList*>( "idvalues" );
         auto idmodify = b_opts.get<LogicalList*>( "idmodify" );
         size_t nid = idtags->size();
         for( size_t i = 0; i < nid; ++i )
         {
             if( idmodify->at( i ) )
             {
                 if( std::string( idvalues->at( i ) ) != "" )
                 {
                     tagman.setIdTag( idtags->at( i ), idvalues->at( i ) );
                 }
                 else
                 {
                     tagman.deleteTag( idtags->at( i ) );
                 }
             }
         }
         // set up interp tags
         auto interptags = b_opts.get<StringList*>( "interptags" );
         auto interpvalues = b_opts.get<StringList*>( "interpvalues" );
         auto interpmodify = b_opts.get<LogicalList*>( "interpmodify" );
         size_t ninterp = interptags->size();
         for( size_t i = 0; i < ninterp; ++i )
         {
             if( interpmodify->at( i ) )
             {
                 if( std::string( interpvalues->at( i ) ) != "" )
                 {
                     double value = std::stod( interpvalues->at( i ) );
                     tagman.setInterpTag( interptags->at( i ), value );
                 }
                 else
                 {
                     tagman.deleteTag( interptags->at( i ) );
                 }
             }
         }
         lib->set_tag_manager( tagman );
         opts.clearErrorStack();
         opts.set( "fileFormat", "bof" );
         bool pass = saveLibrary( *lib, path, opts );
         if( !pass ) err << opts.dumpErrorStack();
         // print the tags
         printTags_json( *lib, path );
     }
     return 0;
 }
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_tag::execute(), and Obiwan_tag::Obiwan_tag().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_tag.h
Core/ut/Obiwan_tag.cpp