ORIGEN API: Obiwan_interp Class Reference
Obiwan_interp Class Reference
#include <Obiwan_interp.h>
execute obiwan in interp mode
Public Member Functions
Obiwan_interp (int argc, char **argv)
Obiwan_interp (ScaleUtils::IO::DB opts)
~Obiwan_interp () noexcept(false)
int execute (std::ostream &out, std::ostream &err)
Provide a multi-dimensional Library interpolation capability based on interpolated tag values provided on the command line.
Static Public Member Functions
static std::string help ()
provide a help message
static ScaleUtils::IO::DB populate (int argc, char **argv)
Protected Attributes
ScaleUtils::IO::DB b_opts
Detailed Description
execute obiwan in interp mode
Examples:
tstObiwan.cpp.
Constructor & Destructor Documentation
Obiwan_interp (int argc, char ** argv)
References Obiwan_interp::b_opts, and Obiwan_interp::populate().
 {
     b_opts = populate( argc, argv );
 }
Obiwan_interp (ScaleUtils::IO::DB opts)
 : b_opts( opts ) {}
~Obiwan_interp () inline noexcept
 {}
Member Function Documentation
std::string help () static
provide a help message
Take care to not mess up the formatting below. We are using doxygen snippets to get that text to appear as-is in the doxygen documentation for this script.
Referenced by Obiwan_interp::execute().
 {
     const char* help = R"help(
 //! [help]
  purpose: interpolate between ORIGEN libraries to generate a new library.
  usage: obiwan interp
                [-idtags='tag1=[v1],tag2=[v2]']
                [-interptags='tag3=[v3],tag4=[v4]'] file
        EXAMPLE:
        obiwan interp
               -idtags='Assembly Type=w17x17,Fuel Type=MOX'
               -interptags='Enrichment=4.5,Moderator Density=0.55' /path/to/libraries
        NOTE: obiwan modifies an ORIGEN binary in place when modifying tags.
        NOTE: when interpolating, obiwan will produce a new library file called InterpLib.bof.
  example:
     #add size, vendor, and enrichment tags to all w17* assemblies
     $ mkdir -p new
     $ cp $DATA/arplibs/w17* new
     $ obiwan interp new/w* -idtags='size=17,vendor=W' 2>log
     $ obiwan interp new/w*e60.arplib -interptags='enr=6.0' 2>log
     $ obiwan interp new/w*e50.arplib -interptags='enr=5.0' 2>log
     $ obiwan interp new/w*e40.arplib -interptags='enr=4.0' 2>log
     $ obiwan interp new/w*e30.arplib -interptags='enr=3.0' 2>log
     $ obiwan interp new/w*e20.arplib -interptags='enr=2.0' 2>log
     $ obiwan interp new/w*e15.arplib -interptags='enr=1.5' 2>log
     $ obiwan interp new/w*.arplib 2>log
         new/w17_e15.arplib: {
            idtags: {
               size: 17,
               vendor: W   }
            interptags: {
               enr: 1.5,    }
         }
         new/w17_e20.arplib: {
            idtags: {
               size: 17,
               vendor: W   }
            interptags: {
               enr: 2,    }
         }
         ...
 //! [help]
     )help";
     // break up tag so Doxygen doesn't think this is a 3rd tag
     return ScaleUtils::IO::removeSubstring( help,
                                             "//! ["
                                             ""
                                             "help"
                                             ""
                                             "]" );
 }
ScaleUtils::IO::DB populate (int argc, char ** argv) static
References Origen::baseOptions(), and Origen::parseTags().
Referenced by Obiwan_interp::Obiwan_interp().
 {
     Standard::CommandLine cmd( argc, argv );
     // get files
     Origen::Vec_Str files = cmd.arguments();
     ScaleUtils::IO::DB base;
     // output error message
     if( files.size() == 0 )
     {
         base.set( "help", true );
     }
     else
     {
         // debugging echo
         jDebugLine( cmd.toString() );
         // expand globs (e.g. *.txt)
         ScaleUtils::IO::expandPaths( files );
         base = baseOptions();
         if( !cmd.exists( "-idtags" ) && !cmd.exists( "-interptags" ) )
         {
             base.appendError(
                 "idtags & interp tags must be specified for interpolation" );
         }
         // we will do the same thing for id and interp tags so we
         // will loop through and do the same thing twice
         const std::map<std::string, std::string> tag_sets = {
             {"-idtags", "id"}, {"-interptags", "interp"}};
         for( auto& tag_pair : tag_sets )
         {
             std::string flag = tag_pair.first;
             std::string key = tag_pair.second;
             // parse the command line argument that has tags of the form
             // tag1,tag2=,tag3=val3,...
             Origen::Vec_Str tags;
             Origen::Vec_Str values;
             Origen::Vec_Bool modify;
             std::string error =
                 parseTags( cmd.getValue( flag, "" ), &tags, &values, &modify );
             if( error != "" ) base.appendError( error );
             // check and make sure we're modifying everything
             for( auto mod : modify )
             {
                 if( !mod )
                     base.appendError(
                         "interpolation requires tag values be specified, e.g. "
                         "tag=val" );
             }
             // create a data container with the tags/values/whether to modify
             base.set<StringList*>( key + "tags", new StringList( tags ) );
             base.set<StringList*>( key + "values", new StringList( values ) );
         }
         base.set<StringList*>( "paths", new StringList( files ) );
     }
     return base;
 }
int execute (std::ostream & out, std::ostream & err)
Provide a multi-dimensional Library interpolation capability based on interpolated tag values provided on the command line.
This methods provides support for N-dimensional interpolation, given a set of user-provided interpolable tags (identified through the -interptags flag in conjunction with the -interpolate argument).
This function will interpolate to the value for each interpolable tag provided (e.g., if the user provides enrichment and moderator density, interpolate will interpolate all libraries with the specified ID tags along the ENR/MOD dimensions, creating a new Library based on the provided interptag values. See the help function for more details.
References Obiwan_interp::b_opts, Obiwan_interp::help(), Origen::interpLibraryND(), Origen::loadLibrary(), Origen::printTags_json(), Origen::saveLibrary(), Origen::selectLibraries(), TagManager::setIdTag(), and TagManager::setInterpTag().
Referenced by Origen::obiwan_main().
 {
     // quick returns
     if( b_opts.get( "help", false ) )
     {
         out << help() << std::endl;
         return 1;
     }
     else if( b_opts.numError() > 0 )
     {
         return -1;
     }
     // Build a reference TagManager based on the provided ID tags
     // and a set of interpolable tags to interpolate to.
     TagManager tagman;
     // set up id tags
     auto idtags = b_opts.get<StringList*>( "idtags" );
     auto idvalues = b_opts.get<StringList*>( "idvalues" );
     size_t nid = idtags->size();
     for( size_t i = 0; i < nid; ++i )
     {
         tagman.setIdTag( idtags->at( i ), idvalues->at( i ) );
     }
     // set up interp tags
     auto interptags = b_opts.get<StringList*>( "interptags" );
     auto interpvalues = b_opts.get<StringList*>( "interpvalues" );
     size_t ninterp = interptags->size();
     for( size_t i = 0; i < ninterp; ++i )
     {
         double value = std::stod( interpvalues->at( i ) );
         tagman.setInterpTag( interptags->at( i ), value );
     }
     /* Now, open up the list of Libraries and grab up on-disk Library objects
     ** with ID tags matching those in the assembled ID tag list. These Library
     ** objects will be used for the ND interpolation on the specified interp
     *tags.
     **
     ** For more details on the ND interpolation method, see the Library &
     *GridView
     ** classes in Origen/Core
     */
     std::vector<TagManager> tagman_list;
     ScaleUtils::IO::DB opts;
     opts.set( "fileFormat", "bof" );
     jDebugLine( "Opening Libraries." );
     for( auto path : *b_opts.get<StringList*>( "paths" ) )
     {
         jDebugLine( "    reading from path=" << path );
         auto lib = Origen::SP_Library( Origen::loadLibrary( path, opts ) );
         // Add the filename to the Library as an ID tag with name "Filename".
         auto temp = lib->tag_manager();
         temp.setIdTag( "Filename", path );
         lib->set_tag_manager( temp );
         tagman_list.push_back( temp );
     }
     err << "Libraries opened and TagManagers collected." << std::endl;
     // Interpolate the list of Library objects and generate a new on-disk
     // Library
     // saving the new Library to disk as InterpLib.bof
     std::vector<Origen::TagManager> interp_list;
     interp_list = selectLibraries( tagman_list, tagman );
     err << "Interpolating..." << std::endl;
     Origen::SP_Library result = interpLibraryND( interp_list, tagman );
     std::string path = b_opts.get( "Filename", "InterpLib.bof" );
     tagman.setIdTag( "Filename", path );
     result->set_tag_manager( tagman );
     bool pass = saveLibrary( *result, path, opts );
     if( !pass )
     {
         err << "Error writing the library." << std::endl;
         return -1;
     }
     // print out the tags for the resulting library.
     printTags_json( *result, path, out );
     out << std::endl;
     return 0;
 }
Member Data Documentation
ScaleUtils::IO::DB b_opts protected
Referenced by Obiwan_interp::execute(), and Obiwan_interp::Obiwan_interp().
The documentation for this class was generated from the following files:
Core/ut/Obiwan_interp.h
Core/ut/Obiwan_interp.cpp