ORIGEN API: Solver/matrex/src/kernel_matrex.hpp File Reference
kernel_matrex.hpp File Reference
Header for calling the fortran function origen_solve() from c.
#include "Origen/Core/dc/TransitionMatrixP.h"
#include "Standard/Interface/Reporter.h"
Functions
void F_kernel_matrex (unsigned long *cp_lib, int itot, int non, double *n0, double *n, double delta_t, double *diag, double *a, double *source_term, int i_zero_flux_step, int i_is_adjoint, int nterm, int nshrt, double cutoff)
void kernel_matrex (TransitionMatrixP *cp_lib, int itot, int non, double *n0, double *n, double delta_t, double *diag, double *a, double *source_term, int i_zero_flux_step, int i_is_adjoint, int nterm, int nshrt, double cutoff)
Detailed Description
Header for calling the fortran function origen_solve() from c.
Author
Aarno Isotalo
Function Documentation
void F_kernel_matrex (unsigned long * cp_lib, int itot, int non, double * n0, double * n, double delta_t, double * diag, double * a, double * source_term, int i_zero_flux_step, int i_is_adjoint, int nterm, int nshrt, double cutoff)
Referenced by kernel_matrex().
void kernel_matrex (TransitionMatrixP * cp_lib, int itot, int non, double * n0, double * n, double delta_t, double * diag, double * a, double * source_term, int i_zero_flux_step, int i_is_adjoint, int nterm, int nshrt, double cutoff)
Call the matrex solver (origen_solve() in fortran) from c. Note that some arguments differ from the fortran origan_solve()
Examples:
Solver/matrex/src/tests/tstKernelMatrexC.cpp.
References F_kernel_matrex().
Referenced by Solver_matrex::solve_impl(), and TEST().