ORIGEN API: Core/dc/tests/tstState.cpp File Reference
tstState.cpp File Reference
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/dc/StateSet.h"
#include "Origen/Core/Definitions.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Nemesis/harness/DBC.hh"
#include "Origen/Core/fn/print.h"
#include "Origen/Core/config.h"
Functions
TEST (State, Accumulate)
Function Documentation
TEST (State , Accumulate)
Examples:
tstState.cpp.
References State::concs(), State::definition(), kernel_rksuite::f(), StateInfo::flux(), StateInfo::power(), State::set_concs(), State::set_definition(), StateInfo::set_flux(), StateInfo::set_power(), Concentrations::set_volume(), StateSet::states_at(), FakeFactory::StateSet_random1(), Concentrations::vals_at(), and Concentrations::volume().