ORIGEN API: myhelpers Module Reference
myhelpers Module Reference
Functions/Subroutines
integer function search_daughter (this, n)
subroutine super_daughter_check (this, parent_id)
Function/Subroutine Documentation
integer function myhelpers::search_daughter (type(origen_librarywrapper), intent(inout) this, integer, intent(in) n)
Referenced by super_daughter_check().
   type(origen_librarywrapper),intent(inout) :: this
   integer, intent(in) :: n
   integer :: i,last_reaction
   !keep searching until we go past
   do i=1,this%get_itot()
     if( this%non0(i) > n )then
       exit
     end if
   end do
   if( i>this%get_itot() )then
   write(error_unit,*)'error finding this daughter'
   stop 7
   end if
subroutine myhelpers::super_daughter_check (type(origen_librarywrapper), intent(inout) this, integer parent_id)
References search_daughter().
Referenced by tstxs().
   implicit none
   type(origen_librarywrapper),intent(inout) :: this
   integer :: parent_id
   integer :: idaughter,adiff,z
   logical :: was_alpha_decay,was_fp_decay
   real(C_DOUBLE) :: myfsum,mydsum,mycsum,factor
   real(C_DOUBLE) :: afy,libc,libd,libf
   integer :: i,ilite
   integer,allocatable :: nucl(:), mt(:),loc(:),typ(:)
   real(C_DOUBLE),allocatable :: a(:),fiss(:),tocap(:)
   real,allocatable :: dis(:)
   ilite=this%get_ilite()
   call this%get_mt(mt)
   call this%get_nucl(nucl)
   call this%get_loc(loc)
   call this%get_typ_nuc(typ)
   call this%get_a(a)
   call this%get_fiss(fiss)
   call this%get_tocap(tocap)
   call this%get_dis(dis)
 !  write(ERROR_UNIT,'(3a12,a12,2a6,a5)')'id','type','mt','coeff','alpha','fpdec','mult'
   myfsum=0
   mydsum=0
   mycsum=0
   do i=1,this%get_non()
     if( loc(i)==parent_id )then
       idaughter=search_daughter(this,i)
       !in order for the sums to be correct, we need to assign a factor
       !to reactions which produce more than one "nuclide"
       !for example, alpha-particles appear to be accumulated as id 40020 type=2 (actinide)
       !thus there needs to be a 0.5 factor to account for alpha + residual heavy nuclide
       was_alpha_decay=.false.
       was_fp_decay=.false.
       factor=1
       if( mt(i)==18 )then
         z=floor(nucl(idaughter)/10000.d0)
         if( z==1 .OR. z==2 )then
           was_fp_decay=.true.
         else
           factor=0.5d0
           myfsum=myfsum+a(i)*factor
         end if
       else if ( mt(i)==-1 )then
         adiff=nucl(loc(i))-nucl(idaughter)
         !write(ERROR_UNIT,*)'adiff=',adiff
         if( nucl(idaughter)==20040 .OR. adiff==20040 )then
           was_alpha_decay=.true.
           factor=0.5d0
         else
           factor=1
         end if
           mydsum=mydsum+factor*a(i)
       else
         select case(mt(i))
           case(16,17,28,37,51,102,103,111); factor = 1; mycsum=mycsum+a(i)*factor
           case(22,24,25,32,33,34,104,105,106,107,112); factor = 1.d0/2.d0; mycsum=mycsum+a(i)*factor
           case(29,108); factor = 1.d0/3.d0; mycsum=mycsum+a(i)*factor
           case default
           write(error_unit,*)'error in reaction handling with unknown mt=',mt(i)
           stop 6
         end select
       end if
 !      write(ERROR_UNIT,'(3i12,es12.5,2g6.6,f5.2)')nucl(idaughter),typ(idaughter),mt(i),a(i),was_alpha_decay,was_fp_decay,factor
     end if
   end do
   libd=dis(parent_id)
   libc=tocap(parent_id)-fiss(parent_id-ilite)
   libf=fiss(parent_id-ilite)
   afy=myfsum/(0.5d0*fiss(parent_id-ilite))
 !  write(ERROR_UNIT,*)'********************'
 !  write(ERROR_UNIT,*)'LIBRARY CONSISTENCY'
 !  write(ERROR_UNIT,*)'********************'
 !  write(ERROR_UNIT,'(a10,3a12)')'source|','disint.','capture','fission'
 !  write(ERROR_UNIT,'(a10,3es12.5)')'summed|',mydsum,mycsum,myfsum
 !  write(ERROR_UNIT,'(a10,3es12.5)')'stored|',libd,libc,libf
 !  write(ERROR_UNIT,*)
 !  write(ERROR_UNIT,'(a,es12.5)')'average fission yield: ',afy
 !  write(ERROR_UNIT,*)'********************'
   expect_near(libd, mydsum, 1.0d-4)
   expect_near(libc, mycsum, 1.0d-5)
   expect_near(libf, myfsum, 1.0d-5)
   expect_near(2.d0, afy, 1.d-5)