ORIGEN API: Core/ut/mgfluxmapper.cpp File Reference
mgfluxmapper.cpp File Reference
#include <fstream>
#include "ScaleData/Core/EnergyUnionizer.h"
#include "ScaleData/Core/MGFluxMapper.h"
#include "Standard/Interface/CommandLine.h"
Typedefs
typedef std::vector< double > Vec_Dbl
typedef std::shared_ptr< Vec_Dbl > SP_Vec_Dbl
Functions
void read_data (std::string path, int &ng_old, Vec_Dbl &flux_old, SP_Vec_Dbl e_old, int &ng_new, SP_Vec_Dbl e_new)
void flux_mapper ()
int main ()
Typedef Documentation
typedef std::vector<double> Vec_Dbl
typedef std::shared_ptr<Vec_Dbl> SP_Vec_Dbl
Function Documentation
void read_data (std::string path, int & ng_old, Vec_Dbl & flux_old, SP_Vec_Dbl e_old, int & ng_new, SP_Vec_Dbl e_new)
Referenced by flux_mapper().
 {
     std::ifstream file;
     file.open( path.c_str(), std::ios::in );
     file >> ng_old;
     jDebugLine( "read ng_old=" << ng_old );
     e_old->resize( ng_old + 1 );
     for( int i = 0; i < ng_old + 1; i++ ) file >> e_old->at( i );
     flux_old.resize( ng_old );
     for( int i = 0; i < ng_old; i++ ) file >> flux_old.at( i );
     file >> ng_new;
     e_new->resize( ng_new + 1 );
     for( int i = 0; i < ng_new + 1; i++ ) file >> e_new->at( i );
     file.close();
 }
void flux_mapper ()
References read_data().
Referenced by main().
 {
     int ng_old, ng_new;
     Vec_Dbl flux_old;
     SP_Vec_Dbl e_old( new Vec_Dbl() );
     SP_Vec_Dbl e_new( new Vec_Dbl() );
     read_data( "flux_data.txt", ng_old, flux_old, e_old, ng_new, e_new );
     EnergyUnionizer<double> eu( e_old, e_new );
     SP_Vec_Dbl fi( MGFluxMapper<double>::fluxIntegrals_1( *eu.cUnionGrid() ) );
     MGFluxMapper<double> dm( eu, fi );
     Vec_Dbl flux_new;
     flux_new.resize( ng_new );
     dm.mapFlux( flux_old, flux_new );
     jDebugTaggedLine( "\n" << dm.printFlux( flux_old, flux_new ) );
     std::cout << dm.toString() << std::endl;
     std::cout << "---new--hist---" << std::endl;
     for( int i = 0; i < ng_new; i++ )
     {
         double leth = log( e_new->at( i ) / e_new->at( i + 1 ) );
         double del = e_new->at( i ) / e_new->at( i + 1 );
         std::cout << i << " " << e_new->at( i ) << " " << flux_new[i] << " "
                   << flux_new[i] / leth << " " << flux_new[i] / del
                   << std::endl;
         std::cout << i << " " << e_new->at( i + 1 ) << " " << flux_new[i] << " "
                   << flux_new[i] / leth << " " << flux_new[i] / del
                   << std::endl;
     }
     std::cout << "---old--hist---" << std::endl;
     for( int i = 0; i < ng_old; i++ )
     {
         double leth = log( e_old->at( i ) / e_old->at( i + 1 ) );
         double del = e_old->at( i ) / e_old->at( i + 1 );
         std::cout << i << " " << e_old->at( i ) << " " << flux_old[i] << " "
                   << flux_old[i] / leth << " " << flux_old[i] / del
                   << std::endl;
         std::cout << i << " " << e_old->at( i + 1 ) << " " << flux_old[i] << " "
                   << flux_old[i] / leth << " " << flux_old[i] / del
                   << std::endl;
     }
     std::cout << "---new---" << std::endl;
     for( int i = 0; i < ng_new; i++ )
     {
         std::cout << i << " " << e_new->at( i ) << " " << flux_new[i]
                   << std::endl;
     }
     std::cout << "---old---" << std::endl;
     for( int i = 0; i < ng_old; i++ )
     {
         std::cout << i << " " << e_old->at( i ) << " " << flux_old[i]
                   << std::endl;
     }
 }
int main ()
References flux_mapper().
 {
     flux_mapper();
     return 0;
 }