ORIGEN API: constants
constants
Fortran API
Variables
real(c_double) err = 1.0e-44_C_DOUBLE
Small value threshold below this value, isotopics should be set to zero formerly block 4.
real(c_double), parameter avogadro = 6.022140857e+23_C_DOUBLE
Avogadro number (same as ScaleUtils/Math/Constants.h)
real(c_double), parameter curie_to_becquerel = 3.7e+10_C_DOUBLE
Curies to Becquerels (same as ScaleUtils/Math/Constants.h)
real(c_double), parameter joule_to_mev = 6.24150647996e+12_C_DOUBLE
Joules to MeV (same as ScaleUtils/Math/Constants.h)
real(c_double), parameter pi = 3.14159265358979323846_C_DOUBLE
Ludolf number.
integer(c_size_t), parameter origen_bad_size_t =HUGE(1_C_SIZE_T)
indicates an error in a size_t Because this is an index, and fortran indices add one to C++ indices, it must correspond to C++ Origen::BAD_SIZE_T+1 which has been set to std::numeric_limits<size_t>::max/2+1
real(c_double), parameter origen_bad_double =HUGE(1_C_DOUBLE)
indicates an error in a double
real(c_float), parameter origen_bad_float =HUGE(1_C_FLOAT)
indicates an error in a float
integer(c_int), parameter origen_bad_int =HUGE(1_C_INT)
indicates an error in an int
Detailed Description
Variable Documentation
real(c_double) err = 1.0e-44_C_DOUBLE
Small value threshold below this value, isotopics should be set to zero formerly block 4.
Examples:
tstObiwan.cpp.
Referenced by kernel_matrex::decay(), origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_alpha_class::output(), auxiliary::print_multigroup_table(), auxiliary::print_multigroup_time_table(), origen_output::print_table(), auxiliary::print_time_table(), LibraryIO_s61::read(), ObiwanTester< T >::SetUp(), kernel_matrex::term(), TEST(), and LibraryIO_s61::write().
 real(C_DOUBLE) :: err = 1.0e-44_c_double
real(c_double), parameter avogadro = 6.022140857e+23_C_DOUBLE
Avogadro number (same as ScaleUtils/Math/Constants.h)
Referenced by origen_output::convert_concentrations(), origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_alpha_class::output(), origen_neutron::totaln(), and tstmassconservation().
 real(C_DOUBLE), parameter :: avogadro = 6.022140857e+23_c_double
real(c_double), parameter curie_to_becquerel = 3.7e+10_C_DOUBLE
Curies to Becquerels (same as ScaleUtils/Math/Constants.h)
Referenced by origen_output::convert_concentrations().
 real(C_DOUBLE), parameter :: curie_to_becquerel = 3.7e+10_c_double
real(c_double), parameter joule_to_mev = 6.24150647996e+12_C_DOUBLE
Joules to MeV (same as ScaleUtils/Math/Constants.h)
Referenced by origen_output::convert_concentrations().
 real(C_DOUBLE), parameter :: joule_to_mev = 6.24150647996e+12_c_double
real(c_double), parameter pi = 3.14159265358979323846_C_DOUBLE
Ludolf number.
Referenced by origen_neutron::totaln().
 real(C_DOUBLE), parameter :: pi = 3.14159265358979323846_c_double
integer(c_size_t), parameter origen_bad_size_t =HUGE(1_C_SIZE_T)
indicates an error in a size_t Because this is an index, and fortran indices add one to C++ indices, it must correspond to C++ Origen::BAD_SIZE_T+1 which has been set to std::numeric_limits<size_t>::max/2+1
 integer(C_SIZE_T),parameter :: origen_bad_size_t=huge(1_c_size_t)
real(c_double), parameter origen_bad_double =HUGE(1_C_DOUBLE)
indicates an error in a double
 real(C_DOUBLE)   ,parameter :: origen_bad_double=huge(1_c_double)
real(c_float), parameter origen_bad_float =HUGE(1_C_FLOAT)
indicates an error in a float
 real(C_FLOAT)    ,parameter :: origen_bad_float=huge(1_c_float)
integer(c_int), parameter origen_bad_int =HUGE(1_C_INT)
indicates an error in an int
 integer(C_INT)   ,parameter :: origen_bad_int=huge(1_c_int)