ORIGEN API: Solver/rksuite/src/rksuite_90.f90 File Reference
rksuite_90.f90 File Reference
Data Types
type rk_comm_real_1d
interface setup
interface range_integrate
interface step_integrate
interface statistics
interface global_error
interface reset_t_end
interface interpolate
interface set_stop_on_fatal
interface get_saved_fatal
interface collect_garbage
Modules
module rksuite_90_prec
The 3rd party RKSuite90 solver.
module rksuite_90
Functions/Subroutines
subroutine machine_const (round_off, sqrrmc, cubrmc, sqtiny, outch)
subroutine method_const (rk_method, a, b, c, bhat, r, e, ptr, no_of_stages, intrp_degree, intrp_able, intrp_needs_stages, cost, safety, expon, stability_radius, tan_angle, rs, rs1, rs2, rs3, rs4, order, last_stage, max_stiff_iters, no_of_ge_steps, fsal, cdiff)
subroutine setup_r1 (comm, t_start, y_start, t_end, tolerance, thresholds, method, task, error_assess, h_start, message)
subroutine setup_global_stuff
subroutine collect_garbage_r1 (comm)
recursive subroutine range_integrate_r1 (comm, f, t_want, t_got, y_got, yderiv_got, flag)
recursive subroutine step_integrate_r1 (comm, f, t_now, y_now, yderiv_now, flag)
subroutine truerr_r1 (comm, f, ier)
subroutine step_r1 (comm, f, tnow, y, yp, stages, tol, htry, y_new, errest, err, hmin, phase_2)
subroutine stepa (ypnew, htry, cutbak)
subroutine stepb
subroutine stiff_r1 (comm, f, toomch, sure_stiff)
real(kind=wp) function, dimension(size(v, 1)) approx_jacobian (f, v, vdotv)
complex(kind=wp) function, dimension(2) quadratic_roots (alpha, beta)
logical function dominant_eigenvalue (v1v1, v1v0, v0v0)
real(kind=wp) function wt_inner_prod (vec_1, vec_2)
real(kind=wp) function rev_wt_inner_prod (value)
subroutine statistics_r1 (comm, total_f_calls, step_cost, waste, num_succ_steps, h_next, y_maxvals)
subroutine global_error_r1 (comm, rms_error, max_error, t_max_error)
subroutine reset_t_end_r1 (comm, t_end_new)
subroutine interpolate_r1 (comm, f, t_want, y_want, yderiv_want)
subroutine form_intrp (f, p)
subroutine evaluate_intrp (p, y_want, yderiv_want)
subroutine extra_stages (f, ytemp, xstage)
subroutine rkmsg_r1 (ier, srname, nrec, comm, flag)
subroutine set_saved_state_r1 (srname, state, comm)
integer function get_saved_state_r1 (srname, save_states)
logical function get_saved_fatal_r1 (comm)
subroutine set_stop_on_fatal_r1 (comm, action)
logical function get_stop_on_fatal_r1 (comm)
Variables
integer, parameter wp = C_DOUBLE
Function/Subroutine Documentation
subroutine setup_r1::setup_global_stuff () private
Referenced by rksuite_90::setup_r1().
 !
 comm%h_start=0.0_wp; comm%h_old=0.0_wp
 comm%f_count=0; comm%full_f_count=0; comm%step_count=0; comm%bad_step_count=0
 comm%at_t_start=.true.;  comm%at_t_end=.false.
 comm%rk_method=2;
 comm%ge_max_contrib=0.0_wp; comm%ge_f_count=0
 comm%erason=.false.;  comm%erasfl=.false.
 comm%print_message=.true.;  comm%use_range=.true.
 comm%stiff_bad_step_count=0;  comm%hit_t_end_count=0
 comm%errold=0.0_wp;  comm%h_average=0.0_wp
 comm%chkeff=.false.;  comm%phase2=.true.
 comm%save_states(1:7)=not_ready
 comm%stop_on_fatal=.true.;  comm%saved_fatal_err=.false.
 !
 end subroutine setup_global_stuff
subroutine step_r1::stepa (real(kind=wp), dimension(:), intent(in) ypnew, real(kind=wp), intent(inout) htry, logical, intent(out) cutbak)
Referenced by rksuite_90::step_r1().
 !
    real(kind=wp), intent(inout) :: htry                              !indep!
    real(kind=wp), dimension(:), intent(in) :: ypnew                  !dep!
    logical, intent(out) :: cutbak
 !
    real(kind=wp) :: argdif, fdiff, scl, tdiff, twt, ynrm, ystgnm
 !
 !  Update the weights to account for the current intermediate solution
 !  approximation Y_NEW.  Compute the sizes of Y and Y_NEW in the
 !  new norm.  The size of the Lipschitz constant is assessed by a difference
 !  in the arguments Y, Y_NEW and a difference in the function evaluated
 !  at these arguments.
 !
    weights = max(weights,abs(y_new))
    ynrm = maxval(abs(y)/weights)                                     !spec-ar!
    ystgnm = maxval(abs(y_new)/weights)                               !spec-ar!
    argdif = maxval(abs(y_new-y)/weights)                             !spec-ar!
    fdiff = maxval(abs(ypnew-yp)/weights)                             !spec-ar!
 !
 !  The transformation of the equation to autonomous form is done
 !  implicitly.  The difference of the arguments must take into account
 !  the difference between the values of the independent variable T and
 !  TSTG. The difference of the corresponding component of the function
 !  is zero because of the way the standard transformation is done.
 !
    tdiff = tstg - tnow
    twt = abs(comm%t_end-tnow)
    ynrm = max(ynrm,abs(tnow)/twt)
    ystgnm = max(ystgnm,abs(tstg)/twt)
    argdif = max(argdif,abs(tdiff)/twt)
 !
 !  The ratio FDIFF/ARGDIF is a lower bound for, and an approximation to,
 !  a Lipschitz constant L for the differential equation written in
 !  autonomous form.  First we must ask if the difference ARGDIF is
 !  significant in the precision available.  If it appears to be, we insist
 !  that abs(HTRY)*L be less than an approximate radius, STABILITY_RADIUS,
 !  of the stability region of the method.  This is more stringent than
 !  necessary for stability, possibly a lot more stringent, but the aim is
 !  to get an HTRY small enough that the error estimate for the step is
 !  credible.  The reduction is required to be at least as much as the step
 !  control parameter RS1. It is necessary to limit the reduction of HTRY
 !  at any one time because we may be misled in the size of the reduction
 !  that is appropriate due to nonlinearity of the differential equation
 !  and to inaccurate weights caused by HTRY much too large.  The reduction
 !  is not permitted to be more than the step control parameter RS4.
 !
    cutbak = .false.
    if (argdif > comm%round_off*max(ynrm,ystgnm)) then
       if ((abs(htry)*fdiff) > (comm%stability_radius*argdif)) then
          scl = max(comm%rs4,min(comm%rs1, &
                    (comm%stability_radius*argdif)/(abs(htry)*fdiff)))
          htry = scl*htry; cutbak = .true.
       end if
    end if
 !
subroutine step_r1::stepb () private
Referenced by rksuite_90::step_r1().
 !
    real(kind=wp), dimension(:), pointer :: e                         !real!
 !
    e => comm%e
 !
    if (main) then
       err = maxval( abs( e(1)*yp + e(3)*stages(:,ptr(3)) + &         !spec-ar!
                          e(4)*stages(:,ptr(4)) + e(5)*stages(:,ptr(5)) + &
                          e(6)*stages(:,ptr(6)) ) /  &
                     max( half*(abs(y)+abs(y_new)), thresh ) )
    else
       err = maxval( abs( e(1)*yp + e(3)*stages(:,ptr(3)) + &         !spec-ar!
                          e(4)*stages(:,ptr(4)) + e(5)*stages(:,ptr(5)) + &
                          e(6)*stages(:,ptr(6)) ) / weights )
    end if
 !
    err = abs(comm%h)*err
 !
    end subroutine stepb
 !
real(kind=wp) function, dimension(size(v,1)) stiff_r1::approx_jacobian (f, real(kind=wp), dimension(:), intent(in) v, real(kind=wp), intent(in) vdotv)
References rksuite_90_prec::wp.
Referenced by rksuite_90::stiff_r1().
complex(kind=wp) function, dimension(2) stiff_r1::quadratic_roots (real(kind=wp), intent(in) alpha, real(kind=wp), intent(in) beta)
Referenced by rksuite_90::stiff_r1().
 !
 real(kind=wp), intent(in) :: alpha, beta                             !dep!
 complex(kind=wp), dimension(2) :: quadratic_roots
 !
 complex(kind=wp) :: temp, sqdisc, r1, r2
 !
 !  For types other than real/complex, this procedure must be constructed
 !  such that temp and sqdisc are evaluated as compelx quantities
 !
 temp = alpha/two; sqdisc = sqrt(temp**2 - beta)
 !
 ! Do we have double root?
 !
 if (sqdisc==zero) then
    quadratic_roots = (/ -temp, -temp /)
 !
 ! Distinct roots
 !
 else
    r1 = -temp + sqdisc; r2 = -temp + sqdisc
    if (abs(r1) > abs(r2)) then
       quadratic_roots = (/ r1, r2 /)
    else
       quadratic_roots = (/ r2, r1 /)
    end if
 end if
 !
logical function stiff_r1::dominant_eigenvalue (real(kind=wp), intent(in) v1v1, real(kind=wp), intent(in) v1v0, real(kind=wp), intent(in) v0v0) private
References rev_wt_inner_prod().
Referenced by rksuite_90::stiff_r1().
 !
 real(kind=wp), intent(in) :: v0v0, v1v1
 real(kind=wp), intent(in) :: v1v0                                    !dep!
 logical :: dominant_eigenvalue
 !
 real(kind=wp) :: ratio                                               !dep!
 real(kind=wp) :: res, det
 logical :: big
 !
 ratio = v1v0/v0v0; rho = abs(ratio)
 det = v0v0*v1v1 - v1v0*rev_wt_inner_prod(v1v0); res = abs(det/v0v0)
 !
 big = det == zero .or. &
                   (res<=abs(v1v1)*pt001**2 .and. abs(ratio-rold)<=pt001*rho)
 !
 if (big) then
    root_pair(bigr) = cmplx(ratio)
    root_pair(smlr) = cmplx(zero)
 end if
 !
 rold = ratio
 dominant_eigenvalue = big
 !
real(kind=wp) function stiff_r1::wt_inner_prod (real(kind=wp), dimension(:), intent(in) vec_1, real(kind=wp), dimension(:), intent(in) vec_2) private
Referenced by rksuite_90::stiff_r1().
 !
 real(kind=wp), dimension(:), intent(in) :: vec_1, vec_2              !dep!
 real(kind=wp) :: wt_inner_prod                                       !dep!
 !
 !
 wt_inner_prod = sum( (vec_1/weights) * (vec_2/weights) )            !spec-ar!
 !
real(kind=wp) function stiff_r1::rev_wt_inner_prod (real(kind=wp), intent(in) value) private
Referenced by dominant_eigenvalue(), and rksuite_90::stiff_r1().
 !
 real(kind=wp), intent(in) :: value                                   !dep!
 real(kind=wp) :: rev_wt_inner_prod                                   !dep!
 !
 ! given result of inner product value = v1.v0
 ! must return the reverse, ie v0.v1
 !
 ! for real variables the value is the same
 ! for complex need to conjugate
 !
 rev_wt_inner_prod = value                                            !spec-line!
 !
 end function rev_wt_inner_prod
subroutine interpolate_r1::form_intrp (f, real(kind=wp), dimension(:,:), intent(out) p)
References extra_stages(), and rksuite_90_prec::wp.
Referenced by rksuite_90::interpolate_r1().
subroutine interpolate_r1::evaluate_intrp (real(kind=wp), dimension(:,:), intent(in) p, real(kind=wp), dimension(:), intent(out), optional y_want, real(kind=wp), dimension(:), intent(out), optional yderiv_want)
Referenced by rksuite_90::interpolate_r1().
 !
 real(kind=wp), dimension(:), optional, intent(out) :: y_want         !dep!
 real(kind=wp), dimension(:), optional, intent(out) :: yderiv_want    !dep!
 real(kind=wp), dimension(:,:), intent(in) :: p                       !dep!
 !
 real :: sigma
 integer :: i
 !
 sigma = (t_want-comm%t)/comm%h_old
 !
 if (present(y_want)) then
    y_want = p(:,comm%intrp_degree-1)*sigma
    do i = comm%intrp_degree - 2, 1, -1
       y_want = (y_want+p(:,i))*sigma
    end do
    y_want = (y_want+comm%h_old*comm%yp)*sigma + comm%y
 end if
 !
 if (present(yderiv_want)) then
    yderiv_want = comm%intrp_degree*p(:,comm%intrp_degree-1)*sigma
    do i = comm%intrp_degree - 1, 2, -1
       yderiv_want = (yderiv_want+i*p(:,i-1))*sigma
    end do
    yderiv_want = (yderiv_want+comm%h_old*comm%yp)/comm%h_old
 end if
 !
subroutine interpolate_r1::extra_stages (f, real(kind=wp), dimension(:), intent(out) ytemp, real(kind=wp), dimension(:), intent(out) xstage) private
References rksuite_90_prec::wp.
Referenced by form_intrp().