OrigenAPI: GammaResourceData Class Reference
GammaResourceData Class Reference
Protected Member Functions
void SetUp ()
Protected Attributes
std::map< std::string, SP_GammaResource > resource_map
Detailed Description
Definition at line 129 of file tstGammaResourceIO.cpp.
Member Function Documentation
void GammaResourceData::SetUp () inline protected
Definition at line 132 of file tstGammaResourceIO.cpp.
References Origen::EmissionSpectrum::id(), Origen::EmissionSpectrum::mean_energy(), Origen::EmissionSpectrum::num_continuous(), Origen::EmissionSpectrum::num_discrete(), Origen::read(), Origen::EmissionSpectrum::total_energy_intensity(), and Origen::EmissionSpectrum::total_intensity().
     {
         SCOPED_TIMER( "load" );
         Vec_Str paths( {"origen.rev00.mpbrh2om.data",
                         "origen.rev00.mpbrh2op.data",
                         "origen.rev00.mpbruo2m.data",
                         "origen.rev00.mpbruo2p.data",
                         "origen.rev00.mpsfangm.data",
                         "origen.rev04.mpdkxgam.data"} );
         std::string scale_data = "/Users/ww5/lib/scale_dev_data/origen_data/";
         std::cout << nprintf( "%30s %7s %3s %3s %1s %7s %7s %7s\n",
                               "file",
                               "id",
                               "nc",
                               "nd",
                               "?",
                               "totI",
                               "totEI",
                               "meanE" );
         for( auto path : paths )
         {
             std::string full_path( scale_data + path );
             GammaResourceIO io;
             DataContainer opts;
             SP_GammaResource resource( new GammaResource() );
             bool read = io.load( *resource, full_path, opts );
             EXPECT_TRUE( read );
             resource_map[path] = resource;
             for( size_t i = 0; i < resource->emission_size(); ++i )
             {
                 EmissionSpectrum em = resource->emission_at( i );
                 std::cout << nprintf(
                     "%30s %7d %7s %3d %3d %1s %7.1e %7.1e %7.1e\n",
                     path.c_str(),
                     em.id(),
                     ScaleData::Utils::pizzzaaa_to_symbol( em.id() ).c_str(),
                     em.num_continuous(),
                     em.num_discrete(),
                     ( em.num_continuous() == 0 || em.num_discrete() == 0 )
                         ? "N"
                         : "Y",
                     em.total_intensity(),
                     em.total_energy_intensity(),
                     em.mean_energy() );
             }
         }
     }
Member Data Documentation
std::map<std::string, SP_GammaResource> GammaResourceData::resource_map protected
Definition at line 184 of file tstGammaResourceIO.cpp.
The documentation for this class was generated from the following file:
Core/io/tests/tstGammaResourceIO.cpp