ORIGEN API: GridData_TransitionCoeff Class Reference
GridData_TransitionCoeff Class Reference
#include <GridData_TransitionCoeff.h>
Creates a GridData object for TransitionCoeff-based responses, used to interpolate TransitionCoeff objects.
Public Types
typedef std::vector< TagManager > Vec_TagManager
typedef std::vector< SP_TransitionCoeff > Vec_SP_TransCoeff
typedef std::shared_ptr< Vec_X > SP_Vec_X
typedef GridData_TransitionCoeff GdTC
Public Member Functions
~GridData_TransitionCoeff ()
void setx (const Vec_TagManager &, const std::vector< std::string >, const size_t)
void setr (std::vector< GridView_TransitionCoeff > &)
SP_TransitionCoeff interpolate_transition_coeff (Vec_Xptr)
std::vector< size_t > get_tm_indexMap ()
Get the flat-index map of where each tagManager is in GridData space.
Vec_Xptr getWts (const TagManager &)
Protected Member Functions
void clear_gridWts ()
Private Attributes
std::vector< size_t > b_tm_indexMap
Flat index map of where each TagManager lives in GridData space.
std::vector< std::string > b_extentTags
Interpolated tags defining the grid extents.
std::vector< SP_Vec_X > b_xGrids
The xgrid values for each dimension.
std::vector< GridView_TransitionCoeff > b_gvResponses
The response vectors to interpolate on.
std::vector< Vec_X * > b_gridWts
Grid weights.
Detailed Description
Creates a GridData object for TransitionCoeff-based responses, used to interpolate TransitionCoeff objects.
Author
Steven E. Skutnik
Date
May 20, 2015
This class is used to initialize a GridData object for interpolating TransitionCoeff-based responses, starting from a set of TagManagers used to define the Grid extents.
The purposes of this class are to:
Provide a simplified means of creating an interpolation grid for TransitionCoeff objects, based on a set of TagManagers that will define the extents (interpolation dimensions)
Provide a means of "ownership" for the grid extents (i.e., the vector references that define the grid extents), including ensuring their destruction when no longer in use
This is done by making an interface to GridData that "owns" the grid extents and responses.
Examples:
tstGridView.cpp.
Member Typedef Documentation
typedef std::vector<TagManager> Vec_TagManager
typedef std::vector<SP_TransitionCoeff> Vec_SP_TransCoeff
typedef std::shared_ptr<Vec_X> SP_Vec_X
typedef GridData_TransitionCoeff GdTC
Constructor & Destructor Documentation
~GridData_TransitionCoeff ()
References GridData_TransitionCoeff::clear_gridWts().
 { clear_gridWts(); }
Member Function Documentation
void setx (const Vec_TagManager & , const std::vector< std::string > , const size_t)
Examples:
tstGridView.cpp.
References GridData_TransitionCoeff::b_extentTags, GridData_TransitionCoeff::b_tm_indexMap, GridData_TransitionCoeff::b_xGrids, kernel_rksuite::f(), and auxiliary_erf_m::x.
Referenced by Origen::interpLibraryND(), and TEST().
 {
     // Grids defined by each unique tag value in each dimension
     Vec_Xptr tag_xgrids;
     // number of unique tag values for each dimension
     Vec_I tag_extents;
     // Fake responses for each GridData point
     Vec_Rptr fake_responses;
     // Fake set of responses; used as a memory placeholder
     Vec_R faker( 1, 0.0 );
     // Push fake responses for each point only for the first tag
     bool firstTag = true;
     // Need to calculate number of UNIQUE tags for each extent
     /* \todo It would be nice if we had a function that took a list of
      * TagManager
      *       objects & list of tags and returned a list of unique tag-value
      *       combinations
      */
     for( auto& it : interpTags )
     {
         // Push back an x-grid extent
         SP_Vec_X xgrid = SP_Vec_X( new Vec_X );
         for( auto& tm : tagManList )
         {
             // First check that the tags of interest exist on all the
             // TagManagers
             Require( tm.hasTag( it ) );
             // Second, check that the tag is an interp tag on all the
             // TagManagers
             Vec_Str tmp_check( tm.listInterpTags() );
             Require( std::find( tmp_check.begin(), tmp_check.end(), it ) !=
                      tmp_check.end() );
             // Push back unique values onto the extent
             float tagVal = (float)tm.getInterpTag( it );
             bool unique = true;
             for( float xVal : *xgrid )
             {
                 if( ScaleSTL::approx_eq( xVal, tagVal ) ) unique = false;
             }
             if( unique )
             {
                 xgrid->push_back( tagVal );
             }
             // Can we reverse the loop order?
             if( firstTag )
             {
                 // Push back a fake response for each point
                 for( size_t i = 0; i < nr; ++i )
                     fake_responses.push_back( &faker.at( 0 ) );
             }
         }
         // Skip this x-grid if it contains one or fewer x-values
         // i.e., no interpolation to be performed for this dimension
         if( !( xgrid->size() > 1 ) ) continue;
         std::sort( xgrid->begin(), xgrid->end() );
         // Push on our xgrid extent onto the grid
         // Note that only this way works; push_back(&xgrid[0]) does NOT work!
         tag_xgrids.push_back( &xgrid->at( 0 ) );
         tag_extents.push_back( xgrid->size() );
         this->b_extentTags.push_back( it );
         this->b_xGrids.push_back( xgrid );
         firstTag = false;
     }
     // Set up the x-grid dimensions
     GridData::setx( tag_extents, tag_xgrids );
     // Set the fake responses
     Vec_I fake_rextents( nr, 1 );
     GridData::setr( fake_rextents, fake_responses );
     /*
      *  Create an indexMap to map the TagManager objects to each GridData flat
      *  index location
      *
      *  Here, our job is to identify where each combination of tags on each
      *  TagManager resides in GridData space - i.e., the LOC value. To do this,
      *  we loop through each extent and find the location on the xgrid of each
      *  individual tag value in the tag combination. We then build an LOC index
      *  based on the xgrid locations of each tag. Then, we translate that LOC
      *  index into a flat index value to give the flat position of the response
      *  vector, such that we can construct the response vector from GridView
      *  objects - i.e., this is the tagIndex we return.
      */
     size_t tag_idx;  // index on the extent where the tag is found
     size_t f_idx;  // flat index corresponding to the LOC of the tag combination
     for( auto& tm : tagManList )
     {
         Vec_I loc;
         for( size_t i = 0; i != this->b_extentTags.size(); ++i )
         {
             const X_t* xvRef = GridData::x( i );
             Vec_X xVec( xvRef, xvRef + GridData::nx( i ) );
             for( size_t j = 0; j != xVec.size(); ++j )
             {
                 if( ScaleSTL::approx_eq(
                         xVec[j],
                         (float)tm.getInterpTag( this->b_extentTags[i] ) ) )
                     tag_idx = j;
             }
             Check( tag_idx >= 0 );
             loc.push_back( tag_idx );
         }
         /* GridData stores all of the responses for each point sequentially on
          * the flat vector
          * Thus, to go from the flat index to the library order, simply divide
          * by the number of
          * responses
          */
         f_idx = GridData::f( loc, 0 ) / nr;
         this->b_tm_indexMap.push_back( f_idx );
         loc.clear();
     }
 }
void setr (std::vector< GridView_TransitionCoeff > & gridResponses)
Examples:
tstGridView.cpp.
References GridData_TransitionCoeff::b_gvResponses, kernel_rksuite::f(), and r.
Referenced by Origen::interpLibraryND(), and TEST().
 {
     /*
      * Need to create a single flat vector of responses from a list of
      * GridView_TC
      * objects. So, loop through each response and push it onto a big, single
      * flat-index vector where each response for a single xgrid point is
      * adjacent
      */
     this->b_gvResponses.clear();  // Clear out the vector of any old responses
     this->b_gvResponses = gridResponses;
     Vec_Rptr response( GridData::totalr() );
     size_t f = 0;
     // Refactor this to the internal reference
     for( auto& gr : this->b_gvResponses )
     {
         // get response grid
         const Vec_Rptr& r = gr.r();
         for( size_t j = 0; j < GridData::nr(); ++j )
         {
             response[f] = r[j];
             ++f;
         }
     }
     Check( response.size() == totalr() );
     // Set the responses for the interpolation grid to those for THIS burnup
     GridData::setr( this->b_gvResponses[0].rextents(), response );
 }
SP_TransitionCoeff interpolate_transition_coeff (Vec_Xptr wts)
Examples:
tstGridView.cpp.
References GridData_TransitionCoeff::b_gvResponses.
Referenced by Origen::interpLibraryND(), and TEST().
 {
     // Interpolate on the provided grid weights and return a new
     // TransitionCoeff via the permute method on the GridView object
     Vec_Z z = GridData::rgridsum( wts );
     // Should permute be a static function? Probably.
     return SP_TransitionCoeff( this->b_gvResponses[0].permute( z ) );
 }
std::vector<size_t> get_tm_indexMap () inline
Get the flat-index map of where each tagManager is in GridData space.
Examples:
tstGridView.cpp.
References GridData_TransitionCoeff::b_tm_indexMap.
Referenced by Origen::interpLibraryND(), and TEST().
 { return this->b_tm_indexMap; };
GridData_TransitionCoeff::Vec_Xptr getWts (const TagManager & tm)
References GridData_TransitionCoeff::b_extentTags, GridData_TransitionCoeff::b_gridWts, GridData_TransitionCoeff::clear_gridWts(), and TagManager::getInterpTag().
Referenced by Origen::interpLibraryND().
 {
     clear_gridWts();
     Vec_Xptr wts;
     X_t i = 0;
     for( auto& tag : this->b_extentTags )
     {
         std::vector<float> grid_pts;
         for( size_t k = 0; k < this->nx( i ); k++ )
             grid_pts.push_back( this->x( i )[k] );
         Vec_X* dim_wts = new Vec_X;
         ScaleUtils::Math::interpwts_lin(
             grid_pts, tm.getInterpTag( tag ), dim_wts );
         Insist(
             grid_pts.size() == dim_wts->size(),
             "Did not get the same number of dimension weights out of interpwts_lin \
                 as grid points were put in." );
         wts.push_back( &( dim_wts->at( 0 ) ) );
         this->b_gridWts.push_back( dim_wts );
         i++;
     }
     return ( wts );
 }
void clear_gridWts () protected
References GridData_TransitionCoeff::b_gridWts.
Referenced by GridData_TransitionCoeff::getWts(), and GridData_TransitionCoeff::~GridData_TransitionCoeff().
 {
     // Delete any old weights if they exist
     for( auto wt : this->b_gridWts )
     {
         if( wt != nullptr ) delete wt;
     }
     this->b_gridWts.clear();
 }
Member Data Documentation
std::vector<size_t> b_tm_indexMap private
Flat index map of where each TagManager lives in GridData space.
Referenced by GridData_TransitionCoeff::get_tm_indexMap(), and GridData_TransitionCoeff::setx().
std::vector<std::string> b_extentTags private
Interpolated tags defining the grid extents.
Referenced by GridData_TransitionCoeff::getWts(), and GridData_TransitionCoeff::setx().
std::vector<SP_Vec_X> b_xGrids private
The xgrid values for each dimension.
Referenced by GridData_TransitionCoeff::setx().
std::vector<GridView_TransitionCoeff> b_gvResponses private
The response vectors to interpolate on.
Referenced by GridData_TransitionCoeff::interpolate_transition_coeff(), and GridData_TransitionCoeff::setr().
std::vector<Vec_X*> b_gridWts private
Grid weights.
Referenced by GridData_TransitionCoeff::clear_gridWts(), and GridData_TransitionCoeff::getWts().
The documentation for this class was generated from the following files:
Core/dc/GridData_TransitionCoeff.h
Core/dc/GridData_TransitionCoeff.cpp