ORIGEN API: TransitionCoeff Class Reference
TransitionCoeff Class Reference
#include <TransitionCoeff.h>
Container for transition coefficient data.
Public Types
typedef std::shared_ptr< TransitionCoeff > SP
typedef std::shared_ptr< const TransitionCoeff > SCP
Public Member Functions
TransitionCoeff ()
SP clone () const
bool operator== (const TransitionCoeff &) const
void operator+= (const TransitionCoeff &)
std::string print_compare (const TransitionCoeff &, int) const
template<typename T >
T reaction_power (const std::vector< T > &numden, T vol, T flux, const NuclideSet &) const
template<typename T >
T capture_power (const std::vector< T > &numden, T vol, T flux, const NuclideSet &) const
template<typename T >
T fission_power (const std::vector< T > &numden, T vol, T flux, const NuclideSet &) const
float burnup () const
return the scalar burnup
void set_burnup (float)
set the scalar burnup
const Vec_Flt & matrix () const
return a const reference to matrix
float matrix_at (size_t) const
get element of matrix vector by index
SCP_Vec_Flt scp_matrix () const
return a shared (read-only) matrix pointer
float const * matrix_array () const
return view of matrix vector
size_t matrix_size () const
return size of matrix vector
bool has_matrix () const
return whether the class has a non-null matrix
void set_matrix (const Vec_Flt &)
set the matrix (copy operation)
void get_matrix (Vec_Flt &) const
populate an existing Vec_Flt with a copy of matrix
void manageptr_matrix (Vec_Flt *&)
set the matrix (ownership transfer)
void getptr_matrix (Vec_Flt const *&) const
retrieve pointer (read-only) to matrix
void get_matrix_array (size_t, float *) const
get array of matrix vector (Fortran)
void set_matrix_array (size_t, float *)
set matrix vector from array (Fortran)
const Vec_Flt & loss_xs () const
return a const reference to loss_xs
float loss_xs_at (size_t) const
get element of loss_xs vector by index
SCP_Vec_Flt scp_loss_xs () const
return a shared (read-only) loss_xs pointer
float const * loss_xs_array () const
return view of loss_xs vector
size_t loss_xs_size () const
return size of loss_xs vector
bool has_loss_xs () const
return whether the class has a non-null loss_xs
void set_loss_xs (const Vec_Flt &)
set the loss_xs (copy operation)
void get_loss_xs (Vec_Flt &) const
populate an existing Vec_Flt with a copy of loss_xs
void manageptr_loss_xs (Vec_Flt *&)
set the loss_xs (ownership transfer)
void getptr_loss_xs (Vec_Flt const *&) const
retrieve pointer (read-only) to loss_xs
void get_loss_xs_array (size_t, float *) const
get array of loss_xs vector (Fortran)
void set_loss_xs_array (size_t, float *)
set loss_xs vector from array (Fortran)
const Vec_Flt & fission_xs () const
return a const reference to fission_xs
float fission_xs_at (size_t) const
get element of fission_xs vector by index
SCP_Vec_Flt scp_fission_xs () const
return a shared (read-only) fission_xs pointer
float const * fission_xs_array () const
return view of fission_xs vector
size_t fission_xs_size () const
return size of fission_xs vector
bool has_fission_xs () const
return whether the class has a non-null fission_xs
void set_fission_xs (const Vec_Flt &)
set the fission_xs (copy operation)
void get_fission_xs (Vec_Flt &) const
populate an existing Vec_Flt with a copy of fission_xs
void manageptr_fission_xs (Vec_Flt *&)
set the fission_xs (ownership transfer)
void getptr_fission_xs (Vec_Flt const *&) const
retrieve pointer (read-only) to fission_xs
void get_fission_xs_array (size_t, float *) const
get array of fission_xs vector (Fortran)
void set_fission_xs_array (size_t, float *)
set fission_xs vector from array (Fortran)
const Vec_Flt & neutron_yields () const
return a const reference to neutron_yields
float neutron_yields_at (size_t) const
get element of neutron_yields vector by index
SCP_Vec_Flt scp_neutron_yields () const
return a shared (read-only) neutron_yields pointer
float const * neutron_yields_array () const
return view of neutron_yields vector
size_t neutron_yields_size () const
return size of neutron_yields vector
bool has_neutron_yields () const
return whether the class has a non-null neutron_yields
void set_neutron_yields (const Vec_Flt &)
set the neutron_yields (copy operation)
void get_neutron_yields (Vec_Flt &) const
populate an existing Vec_Flt with a copy of neutron_yields
void manageptr_neutron_yields (Vec_Flt *&)
set the neutron_yields (ownership transfer)
void getptr_neutron_yields (Vec_Flt const *&) const
retrieve pointer (read-only) to neutron_yields
void get_neutron_yields_array (size_t, float *) const
get array of neutron_yields vector (Fortran)
void set_neutron_yields_array (size_t, float *)
set neutron_yields vector from array (Fortran)
const Vec_Flt & flux () const
return a const reference to flux
float flux_at (size_t) const
get element of flux vector by index
SCP_Vec_Flt scp_flux () const
return a shared (read-only) flux pointer
float const * flux_array () const
return view of flux vector
size_t flux_size () const
return size of flux vector
bool has_flux () const
return whether the class has a non-null flux
void set_flux (const Vec_Flt &)
set the flux (copy operation)
void get_flux (Vec_Flt &) const
populate an existing Vec_Flt with a copy of flux
void manageptr_flux (Vec_Flt *&)
set the flux (ownership transfer)
void getptr_flux (Vec_Flt const *&) const
retrieve pointer (read-only) to flux
void get_flux_array (size_t, float *) const
get array of flux vector (Fortran)
void set_flux_array (size_t, float *)
set flux vector from array (Fortran)
const Vec_Flt & kappa_fission () const
return a const reference to kappa_fission
float kappa_fission_at (size_t) const
get element of kappa_fission vector by index
SCP_Vec_Flt scp_kappa_fission () const
return a shared (read-only) kappa_fission pointer
float const * kappa_fission_array () const
return view of kappa_fission vector
size_t kappa_fission_size () const
return size of kappa_fission vector
bool has_kappa_fission () const
return whether the class has a non-null kappa_fission
void set_kappa_fission (const Vec_Flt &)
set the kappa_fission (copy operation)
void get_kappa_fission (Vec_Flt &) const
populate an existing Vec_Flt with a copy of kappa_fission
void manageptr_kappa_fission (Vec_Flt *&)
set the kappa_fission (ownership transfer)
void getptr_kappa_fission (Vec_Flt const *&) const
retrieve pointer (read-only) to kappa_fission
void get_kappa_fission_array (size_t, float *) const
get array of kappa_fission vector (Fortran)
void set_kappa_fission_array (size_t, float *)
set kappa_fission vector from array (Fortran)
const Vec_Flt & kappa_capture () const
return a const reference to kappa_capture
float kappa_capture_at (size_t) const
get element of kappa_capture vector by index
SCP_Vec_Flt scp_kappa_capture () const
return a shared (read-only) kappa_capture pointer
float const * kappa_capture_array () const
return view of kappa_capture vector
size_t kappa_capture_size () const
return size of kappa_capture vector
bool has_kappa_capture () const
return whether the class has a non-null kappa_capture
void set_kappa_capture (const Vec_Flt &)
set the kappa_capture (copy operation)
void get_kappa_capture (Vec_Flt &) const
populate an existing Vec_Flt with a copy of kappa_capture
void manageptr_kappa_capture (Vec_Flt *&)
set the kappa_capture (ownership transfer)
void getptr_kappa_capture (Vec_Flt const *&) const
retrieve pointer (read-only) to kappa_capture
void get_kappa_capture_array (size_t, float *) const
get array of kappa_capture vector (Fortran)
void set_kappa_capture_array (size_t, float *)
set kappa_capture vector from array (Fortran)
int serialize (Standard::AbstractStream *stream) const
int deserialize (Standard::AbstractStream *stream)
unsigned long getSerializedSize () const
Standard::Serializable * getCopy () const
virtual Standard::Serializable::UID getUID () const
std::string toString () const
Scale::Json::Value to_json () const
std::string to_string () const
void scale (double wt)
bool approx_eq (const TransitionCoeff &, double tol=1e-12) const
template<>
double reaction_power (const std::vector< double > &numden, double vol, double flux, const NuclideSet &nucset) const
template<>
float reaction_power (const std::vector< float > &numden, float vol, float flux, const NuclideSet &nucset) const
template<>
double capture_power (const std::vector< double > &numden, double vol, double flux, const NuclideSet &nucset) const
template<>
float capture_power (const std::vector< float > &numden, float vol, float flux, const NuclideSet &nucset) const
template<>
double fission_power (const std::vector< double > &numden, double vol, double flux, const NuclideSet &nucset) const
template<>
float fission_power (const std::vector< float > &numden, float vol, float flux, const NuclideSet &nucset) const
Static Public Member Functions
static bool match (const TransitionCoeff &, const TransitionCoeff &)
static size_t fission_xs_index (size_t, const NuclideSet &)
Static Public Attributes
static const Standard::Serializable::UID uid = 0x99152462a5c56032
Protected Member Functions
void canonicalize_matrix ()
void canonicalize_neutron_yields ()
void canonicalize_flux ()
void canonicalize_loss_xs ()
void canonicalize_fission_xs ()
void canonicalize_kappa_capture ()
void canonicalize_kappa_fission ()
Protected Attributes
float b_burnup
SP_Vec_Flt b_matrix
SP_Vec_Flt b_loss_xs
SP_Vec_Flt b_fission_xs
SP_Vec_Flt b_neutron_yields
SP_Vec_Flt b_flux
SP_Vec_Flt b_kappa_capture
SP_Vec_Flt b_kappa_fission
Friends
class ScaleUtils::IO::Accessor< TransitionCoeff >
class GridView_TransitionCoeff
Detailed Description
Container for transition coefficient data.
The TransititonCoeff data container manages the coefficient data for transitions.
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstTransitionCoeff.cpp, Core/fn/tests/tstinterp.cpp, Core/io/tests/tstLibraryIO.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<TransitionCoeff> SP
typedef std::shared_ptr<const TransitionCoeff> SCP
Constructor & Destructor Documentation
TransitionCoeff ()
Referenced by TransitionCoeff::getCopy().
     : b_burnup( BAD_FLOAT )
     , b_matrix( new Vec_Flt() )
     , b_loss_xs( new Vec_Flt() )
     , b_fission_xs( new Vec_Flt() )
     , b_neutron_yields( new Vec_Flt() )
     , b_flux( new Vec_Flt() )
     , b_kappa_capture( new Vec_Flt() )
     , b_kappa_fission( new Vec_Flt() )
 {
 }
Member Function Documentation
SP_TransitionCoeff clone () const
Examples:
Core/dc/tests/tstTransitionCoeff.cpp, and Core/fn/tests/tstinterp.cpp.
References TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, and TransitionCoeff::burnup().
Referenced by TEST().
 {
     SP_TransitionCoeff tcClone = SP_TransitionCoeff( new TransitionCoeff );
     tcClone->set_burnup( burnup() );
     tcClone->set_matrix( *b_matrix );
     tcClone->set_loss_xs( *b_loss_xs );
     tcClone->set_fission_xs( *b_fission_xs );
     tcClone->set_neutron_yields( *b_neutron_yields );
     tcClone->set_flux( *b_flux );
     tcClone->set_kappa_fission( *b_kappa_fission );
     tcClone->set_kappa_capture( *b_kappa_capture );
     return tcClone;
 }
static bool match (const TransitionCoeff & , const TransitionCoeff &) static
bool operator== (const TransitionCoeff & orig) const
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, TransitionCoeff::burnup(), TransitionCoeff::fission_xs(), TransitionCoeff::flux(), TransitionCoeff::kappa_capture(), TransitionCoeff::kappa_fission(), TransitionCoeff::loss_xs(), TransitionCoeff::matrix(), and TransitionCoeff::neutron_yields().
 {
     ORIGEN_COMPARE_SCALAR( burnup, b_burnup, orig.b_burnup );
     ORIGEN_COMPARE_SP_VECTOR( matrix, b_matrix, orig.b_matrix );
     ORIGEN_COMPARE_SP_VECTOR(
         neutron_yields, b_neutron_yields, orig.b_neutron_yields );
     ORIGEN_COMPARE_SP_VECTOR( flux, b_flux, orig.b_flux );
     ORIGEN_COMPARE_SP_VECTOR( loss_xs, b_loss_xs, orig.b_loss_xs );
     ORIGEN_COMPARE_SP_VECTOR( fission_xs, b_fission_xs, orig.b_fission_xs );
     ORIGEN_COMPARE_SP_VECTOR(
         kappa_capture, b_kappa_capture, orig.b_kappa_capture );
     ORIGEN_COMPARE_SP_VECTOR(
         kappa_fission, b_kappa_fission, orig.b_kappa_fission );
     return true;
 }
void operator+= (const TransitionCoeff & tcAdd)
 {
     Require( b_matrix->size() == tcAdd.matrix_size() );
     Require( b_loss_xs->size() == tcAdd.loss_xs_size() );
     Require( b_fission_xs->size() == tcAdd.fission_xs_size() );
     Require( b_neutron_yields->size() == tcAdd.neutron_yields_size() );
     Require( b_flux->size() == tcAdd.flux_size() );
     b_burnup += tcAdd.burnup();
     for( size_t i = 0; i != b_matrix->size(); ++i )
     {
         ( *b_matrix )[i] += ( *tcAdd.b_matrix )[i];
     }
     for( size_t i = 0; i != b_loss_xs->size(); ++i )
     {
         ( *b_loss_xs )[i] += ( *tcAdd.b_loss_xs )[i];
     }
     for( size_t i = 0; i != b_fission_xs->size(); ++i )
     {
         ( *b_fission_xs )[i] += ( *tcAdd.b_fission_xs )[i];
     }
     for( size_t i = 0; i != b_neutron_yields->size(); ++i )
     {
         ( *b_neutron_yields )[i] += ( *tcAdd.b_neutron_yields )[i];
     }
     for( size_t i = 0; i != b_flux->size(); ++i )
     {
         ( *b_flux )[i] += ( *tcAdd.b_flux )[i];
     }
     if( b_kappa_capture != nullptr && tcAdd.has_kappa_capture() )
     {
         Check( b_kappa_capture->size() == tcAdd.kappa_capture_size() );
         for( size_t i = 0; i != b_kappa_capture->size(); ++i )
         {
             ( *b_kappa_capture )[i] += ( *tcAdd.b_kappa_capture )[i];
         }
     }
     if( b_kappa_fission != nullptr && tcAdd.has_kappa_fission() )
     {
         Check( b_kappa_fission->size() == tcAdd.kappa_fission_size() );
         for( size_t i = 0; i != b_kappa_fission->size(); ++i )
         {
             ( *b_kappa_fission )[i] += ( *tcAdd.b_kappa_fission )[i];
         }
     }
 }
std::string print_compare (const TransitionCoeff & a, int nt) const
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, and TransitionCoeff::b_neutron_yields.
 {
     std::stringstream ss;
     ss << std::setw( 75 ) << "TransitionCoeff[" << nt << "]" << std::endl;
     ss << std::setw( 77 ) << "=-=-=-=-=-=-=-=-=-";
     ss << std::endl << std::endl;
     ss << std::setw( 40 ) << " " << std::setw( 10 ) << "A" << std::setw( 15 )
        << " " << std::setw( 10 ) << "B" << std::endl;
     ss << std::setw( 40 ) << " "
        << "--------------------"
        << "     "
        << "--------------------" << std::endl;
     ss << std::setw( 35 ) << "Burnup:" << std::setw( 25 ) << b_burnup
        << std::setw( 25 ) << a.b_burnup << std::endl;
     ss << std::setw( 35 ) << "Matrix Size:" << std::setw( 25 )
        << b_matrix->size() << std::setw( 25 ) << a.b_matrix->size()
        << std::endl;
     ss << std::setw( 35 ) << "Dissappearance XS Size:" << std::setw( 25 )
        << b_loss_xs->size() << std::setw( 25 ) << a.b_loss_xs->size()
        << std::endl;
     ss << std::setw( 35 ) << "Fission XS Size:" << std::setw( 25 )
        << b_fission_xs->size() << std::setw( 25 ) << a.b_fission_xs->size()
        << std::endl;
     ss << std::setw( 35 ) << "Neutron Yields Size:" << std::setw( 25 )
        << b_neutron_yields->size() << std::setw( 25 )
        << a.b_neutron_yields->size() << std::endl;
     ss << std::setw( 35 ) << "Flux Size:" << std::setw( 25 ) << b_flux->size()
        << std::setw( 25 ) << a.b_flux->size() << std::endl;
     ss << std::setw( 35 ) << "Kappa Capture Size:" << std::setw( 25 )
        << b_kappa_capture->size() << std::setw( 25 )
        << a.b_kappa_capture->size() << std::endl;
     ss << std::setw( 35 ) << "Kappa Fission Size:" << std::setw( 25 )
        << b_kappa_fission->size() << std::setw( 25 )
        << a.b_kappa_fission->size() << std::endl;
     ss << std::endl;
     ss << std::setw( 35 ) << "Flux:"
        << "     " << std::setw( 10 ) << "A" << std::setw( 15 ) << " "
        << std::setw( 10 ) << "B" << std::setw( 15 ) << " " << std::setw( 12 )
        << "Diff:" << std::endl;
     ss << std::setw( 40 ) << " "
        << "--------------------"
        << "     "
        << "--------------------"
        << "     "
        << "--------------------" << std::endl;
     if( b_flux->size() == a.b_flux->size() )
     {
         for( unsigned int i = 0; i < b_flux->size(); i++ )
         {
             ss << std::setw( 34 ) << i + 1 << ":" << std::setw( 25 )
                << b_flux->at( i ) << std::setw( 25 ) << a.b_flux->at( i )
                << std::endl;
         }
     }
     else
     {
         ss << std::setw( 40 ) << " "
            << "WARNING: Not printed because flux sizes aren't equal!\n";
     }
     return ss.str();
 }
T reaction_power (const std::vector< T > & numden, T vol, T flux, const NuclideSet & nucset) const
References TransitionCoeff::b_fission_xs, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::fission_xs_index(), TransitionCoeff::flux(), and NuclideSet::total_nuclides().
 {
     size_t itot = nucset.total_nuclides();
     Require( itot == numden.size() );
     Require( itot == b_kappa_capture->size() );
     Require( vol >= 0.0 );
     Require( flux >= 0.0 );
     T power = 0.0;
     for( size_t i = 0; i < itot; ++i )
     {
         size_t j = fission_xs_index( i, nucset );
         float sigd = b_loss_xs->at( i );
         float sigf = b_fission_xs->at( j );
         float sigc = sigd - sigf;
         float kapc = b_kappa_capture->at( i );
         float kapf = b_kappa_fission->at( j );
         power += ( kapf * sigf + kapc * sigc ) * numden[i];
     }
     power *= vol * flux;
     Ensure( power >= 0.0 );
     return power;
 }
T capture_power (const std::vector< T > & numden, T vol, T flux, const NuclideSet & nucset) const
References TransitionCoeff::b_fission_xs, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_loss_xs, TransitionCoeff::fission_xs_index(), TransitionCoeff::flux(), and NuclideSet::total_nuclides().
 {
     size_t itot = nucset.total_nuclides();
     Require( itot == numden.size() );
     Require( itot == b_kappa_capture->size() );
     Require( vol >= 0.0 );
     Require( flux >= 0.0 );
     T power = 0.0;
     for( size_t i = 0; i < itot; ++i )
     {
         size_t j = fission_xs_index( i, nucset );
         float sigd = b_loss_xs->at( i );
         float sigf = b_fission_xs->at( j );
         float sigc = sigd - sigf;
         float kapc = b_kappa_capture->at( i );
         power += kapc * sigc * numden[i];
     }
     power *= vol * flux;
     Ensure( power >= 0.0 );
     return power;
 }
T fission_power (const std::vector< T > & numden, T vol, T flux, const NuclideSet & nucset) const
References TransitionCoeff::b_fission_xs, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::fission_xs_index(), TransitionCoeff::flux(), and NuclideSet::total_nuclides().
 {
     size_t itot = nucset.total_nuclides();
     Require( itot == numden.size() );
     Require( itot == b_kappa_capture->size() );
     Require( vol >= 0.0 );
     Require( flux >= 0.0 );
     T power = 0.0;
     for( size_t i = 0; i < itot; i++ )
     {
         size_t j = fission_xs_index( i, nucset );
         float sigf = b_fission_xs->at( j );
         float kapf = b_kappa_fission->at( j );
         power += kapf * sigf * numden[i];
     }
     power *= vol * flux;
     Ensure( power >= 0.0 );
     return power;
 }
float burnup () const
return the scalar burnup
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstTransitionCoeff.cpp, Core/fn/tests/tstinterp.cpp, and Core/io/tests/tstLibraryIO.cpp.
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::clone(), FakeFactory::Library_linear2D(), TransitionCoeff::operator==(), Library::populate_transition_matrix_reaction(), Origen::populateLossXsValues(), LibraryIO_s62b::read(), LibraryIO_bof::read(), TransitionCoeff::scale(), scale61_fixup(), Origen::tabulateBurnups(), Origen::tabulateFissionXs(), TEST(), test_addEqOp(), Origen::thinLibrary(), LibraryIO_s62b::write(), and LibraryIO_bof::write().
void set_burnup (float scalar)
set the scalar burnup
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstLibrary.cpp, Core/fn/tests/tstinterp.cpp, and Core/io/tests/tstLibraryIO.cpp.
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), Origen::createTransitionCoeff_random1(), get_transition_data(), FakeFactory::Library_linear2D(), LibraryIO_bof::read(), LibraryIO_s62b::read(), TransitionCoeff::scale(), scale61_fixup(), Origen::setbuLibrary(), TEST(), TEST_F(), and FakeFactory::TransitionCoeff_random2().
const Vec_Flt & matrix () const
return a const reference to matrix
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Examples:
Core/dc/tests/tstLibrary.cpp, Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), get_transition_data(), inject_fission_yields(), TransitionCoeff::operator==(), Library::populate_transition_matrix_reaction(), TEST(), TEST_F(), LibraryIO_bof::write(), LibraryIO_s62b::write(), and LibraryIO_s61::write().
Vec_Flt::value_type matrix_at (size_t i) const
get element of matrix vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by TEST_F().
SCP_Vec_Flt scp_matrix () const
return a shared (read-only) matrix pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * matrix_array () const
return view of matrix vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t matrix_size () const
return size of matrix vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), Library::populate_transition_matrix_reaction(), TEST(), test_addEqOp(), and LibraryIO_s62b::write().
bool has_matrix () const
return whether the class has a non-null matrix
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_matrix (const Vec_Flt & matrix)
set the matrix (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), get_transition_data(), inject_fission_yields(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and TransitionCoeff::scale().
void get_matrix (Vec_Flt & matrix) const
populate an existing Vec_Flt with a copy of matrix
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_matrix (Vec_Flt *& matrix)
set the matrix (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_matrix (Vec_Flt const *& matrix) const
retrieve pointer (read-only) to matrix
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_matrix_array (size_t , float *) const
get array of matrix vector (Fortran)
void set_matrix_array (size_t , float *)
set matrix vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & loss_xs () const
return a const reference to loss_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Referenced by Origen::construct_neutron_prod_map(), get_transition_data(), TransitionCoeff::operator==(), Library::populate_transition_matrix_reaction(), Origen::populateLossXsValues(), LibraryIO_s62b::write(), LibraryIO_bof::write(), and LibraryIO_s61::write().
Vec_Flt::value_type loss_xs_at (size_t i) const
get element of loss_xs vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_loss_xs () const
return a shared (read-only) loss_xs pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * loss_xs_array () const
return view of loss_xs vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t loss_xs_size () const
return size of loss_xs vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), Library::populate_transition_matrix_reaction(), TEST(), test_addEqOp(), and LibraryIO_s62b::write().
bool has_loss_xs () const
return whether the class has a non-null loss_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_loss_xs (const Vec_Flt & loss_xs)
set the loss_xs (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), get_transition_data(), FakeFactory::newspLibrary_10nuclide(), LibraryIO_s61::read(), LibraryIO_bof::read(), LibraryIO_s62b::read(), and TransitionCoeff::scale().
void get_loss_xs (Vec_Flt & loss_xs) const
populate an existing Vec_Flt with a copy of loss_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_loss_xs (Vec_Flt *& loss_xs)
set the loss_xs (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_loss_xs (Vec_Flt const *& loss_xs) const
retrieve pointer (read-only) to loss_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_loss_xs_array (size_t , float *) const
get array of loss_xs vector (Fortran)
void set_loss_xs_array (size_t , float *)
set loss_xs vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & fission_xs () const
return a const reference to fission_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Referenced by get_transition_data(), inject_fission_yields(), TransitionCoeff::operator==(), Library::populate_transition_matrix_reaction(), LibraryIO_s61::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
Vec_Flt::value_type fission_xs_at (size_t i) const
get element of fission_xs vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by Origen::tabulateFissionXs().
SCP_Vec_Flt scp_fission_xs () const
return a shared (read-only) fission_xs pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * fission_xs_array () const
return view of fission_xs vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t fission_xs_size () const
return size of fission_xs vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), Library::populate_transition_matrix_reaction(), Origen::tabulateFissionXs(), TEST(), test_addEqOp(), and LibraryIO_s62b::write().
bool has_fission_xs () const
return whether the class has a non-null fission_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_fission_xs (const Vec_Flt & fission_xs)
set the fission_xs (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), get_transition_data(), FakeFactory::newspLibrary_10nuclide(), LibraryIO_s61::read(), LibraryIO_bof::read(), LibraryIO_s62b::read(), and TransitionCoeff::scale().
void get_fission_xs (Vec_Flt & fission_xs) const
populate an existing Vec_Flt with a copy of fission_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_fission_xs (Vec_Flt *& fission_xs)
set the fission_xs (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_fission_xs (Vec_Flt const *& fission_xs) const
retrieve pointer (read-only) to fission_xs
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_fission_xs_array (size_t , float *) const
get array of fission_xs vector (Fortran)
void set_fission_xs_array (size_t , float *)
set fission_xs vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & neutron_yields () const
return a const reference to neutron_yields
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Referenced by Origen::construct_neutron_prod_map(), Origen::construct_neutron_yields_map(), TransitionCoeff::operator==(), Library::populate_transition_matrix_reaction(), LibraryIO_s62b::write(), LibraryIO_s61::write(), and LibraryIO_bof::write().
Vec_Flt::value_type neutron_yields_at (size_t i) const
get element of neutron_yields vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_neutron_yields () const
return a shared (read-only) neutron_yields pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * neutron_yields_array () const
return view of neutron_yields vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t neutron_yields_size () const
return size of neutron_yields vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), Library::populate_transition_matrix_reaction(), TEST(), test_addEqOp(), and LibraryIO_s62b::write().
bool has_neutron_yields () const
return whether the class has a non-null neutron_yields
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_neutron_yields (const Vec_Flt & neutron_yields)
set the neutron_yields (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), get_transition_data(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and TransitionCoeff::scale().
void get_neutron_yields (Vec_Flt & neutron_yields) const
populate an existing Vec_Flt with a copy of neutron_yields
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_neutron_yields (Vec_Flt *& neutron_yields)
set the neutron_yields (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_neutron_yields (Vec_Flt const *& neutron_yields) const
retrieve pointer (read-only) to neutron_yields
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_neutron_yields_array (size_t , float *) const
get array of neutron_yields vector (Fortran)
void set_neutron_yields_array (size_t , float *)
set neutron_yields vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & flux () const
return a const reference to flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Examples:
Core/io/tests/tstLibraryIO.cpp.
Referenced by TransitionCoeff::capture_power(), TransitionCoeff::fission_power(), TransitionCoeff::operator==(), Library::populate_transition_matrix_reaction(), TransitionCoeff::reaction_power(), scale61_fixup(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
Vec_Flt::value_type flux_at (size_t i) const
get element of flux vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_flux () const
return a shared (read-only) flux pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * flux_array () const
return view of flux vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t flux_size () const
return size of flux vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by gtestLibrarySizes(), Library::populate_transition_matrix_reaction(), TEST(), test_addEqOp(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
bool has_flux () const
return whether the class has a non-null flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_flux (const Vec_Flt & flux)
set the flux (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/io/tests/tstLibraryIO.cpp.
Referenced by Library::add_transition_matrix(), LibraryBuilder::create_library(), get_transition_data(), LibraryIO_s61::read(), LibraryIO_s62b::read(), LibraryIO_bof::read(), TransitionCoeff::scale(), and scale61_fixup().
void get_flux (Vec_Flt & flux) const
populate an existing Vec_Flt with a copy of flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_flux (Vec_Flt *& flux)
set the flux (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_flux (Vec_Flt const *& flux) const
retrieve pointer (read-only) to flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_flux_array (size_t , float *) const
get array of flux vector (Fortran)
void set_flux_array (size_t , float *)
set flux vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & kappa_fission () const
return a const reference to kappa_fission
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Referenced by get_transition_data(), TransitionCoeff::operator==(), and Library::populate_transition_matrix_reaction().
Vec_Flt::value_type kappa_fission_at (size_t i) const
get element of kappa_fission vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_kappa_fission () const
return a shared (read-only) kappa_fission pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * kappa_fission_array () const
return view of kappa_fission vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t kappa_fission_size () const
return size of kappa_fission vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TransitionCoeff::approx_eq(), Origen::interpLibraryND(), TEST(), and test_addEqOp().
bool has_kappa_fission () const
return whether the class has a non-null kappa_fission
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq(), and Origen::interpLibraryND().
void set_kappa_fission (const Vec_Flt & kappa_fission)
set the kappa_fission (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::add_transition_matrix(), get_transition_data(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and TransitionCoeff::scale().
void get_kappa_fission (Vec_Flt & kappa_fission) const
populate an existing Vec_Flt with a copy of kappa_fission
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_kappa_fission (Vec_Flt *& kappa_fission)
set the kappa_fission (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_kappa_fission (Vec_Flt const *& kappa_fission) const
retrieve pointer (read-only) to kappa_fission
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_kappa_fission_array (size_t , float *) const
get array of kappa_fission vector (Fortran)
void set_kappa_fission_array (size_t , float *)
set kappa_fission vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & kappa_capture () const
return a const reference to kappa_capture
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of TransitionCoeff goes out of scope.
Referenced by get_transition_data(), TransitionCoeff::operator==(), and Library::populate_transition_matrix_reaction().
Vec_Flt::value_type kappa_capture_at (size_t i) const
get element of kappa_capture vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_kappa_capture () const
return a shared (read-only) kappa_capture pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq().
Vec_Flt::value_type const * kappa_capture_array () const
return view of kappa_capture vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TEST(), and test_addEqOp().
size_t kappa_capture_size () const
return size of kappa_capture vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
Referenced by TransitionCoeff::approx_eq(), Origen::interpLibraryND(), TEST(), and test_addEqOp().
bool has_kappa_capture () const
return whether the class has a non-null kappa_capture
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by TransitionCoeff::approx_eq(), and Origen::interpLibraryND().
void set_kappa_capture (const Vec_Flt & kappa_capture)
set the kappa_capture (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::add_transition_matrix(), get_transition_data(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and TransitionCoeff::scale().
void get_kappa_capture (Vec_Flt & kappa_capture) const
populate an existing Vec_Flt with a copy of kappa_capture
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_kappa_capture (Vec_Flt *& kappa_capture)
set the kappa_capture (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_kappa_capture (Vec_Flt const *& kappa_capture) const
retrieve pointer (read-only) to kappa_capture
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_kappa_capture_array (size_t , float *) const
get array of kappa_capture vector (Fortran)
void set_kappa_capture_array (size_t , float *)
set kappa_capture vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
int serialize (Standard::AbstractStream * stream) const
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, TransitionCoeff::getSerializedSize(), and Origen::write().
Referenced by serialization_roundtrip().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::uid..." );
     Standard::write( stream, TransitionCoeff::uid );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::SerializedSize..."
                       << getSerializedSize() );
     Standard::write( stream, getSerializedSize() );
     Remember( size_t checkpoint = stream->getWriteHead() );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_burnup..." );
     Standard::write( stream, b_burnup );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_matrix..." );
     Standard::write( stream, b_matrix );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_loss_xs..." );
     Standard::write( stream, b_loss_xs );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_fission_xs..." );
     Standard::write( stream, b_fission_xs );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_neutron_yields..." );
     Standard::write( stream, b_neutron_yields );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_flux..." );
     Standard::write( stream, b_flux );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_kappa_capture..." );
     Standard::write( stream, b_kappa_capture );
     jDebugTaggedLine( "writing Origen::TransitionCoeff::b_kappa_fission..." );
     Standard::write( stream, b_kappa_fission );
     Ensure( stream->getWriteHead() == checkpoint + getSerializedSize() );
     return 0;
 }
int deserialize (Standard::AbstractStream * stream)
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, TransitionCoeff::canonicalize_fission_xs(), TransitionCoeff::canonicalize_flux(), TransitionCoeff::canonicalize_kappa_capture(), TransitionCoeff::canonicalize_kappa_fission(), TransitionCoeff::canonicalize_loss_xs(), TransitionCoeff::canonicalize_matrix(), TransitionCoeff::canonicalize_neutron_yields(), TransitionCoeff::getSerializedSize(), and Origen::read().
Referenced by serialization_roundtrip().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "reading Origen::TransitionCoeff::uid..." );
     int return_code = Standard::read( stream, TransitionCoeff::uid );
     if( return_code != 0 ) return return_code;
     unsigned long size;
     Standard::read( stream, size );
     jDebugTaggedLine( "reading Origen::TransitionCoeff::SerializedSize..."
                       << size );
     size_t bytes = 0;
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_burnup..." );
     bytes += Standard::read( stream, b_burnup );
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_matrix..." );
     b_matrix = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_matrix );
     canonicalize_matrix();
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_loss_xs..." );
     b_loss_xs = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_loss_xs );
     canonicalize_loss_xs();
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_fission_xs..." );
     b_fission_xs = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_fission_xs );
     canonicalize_fission_xs();
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_neutron_yields..." );
     b_neutron_yields = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_neutron_yields );
     canonicalize_neutron_yields();
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_flux..." );
     b_flux = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_flux );
     canonicalize_flux();
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_kappa_capture..." );
     b_kappa_capture = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_kappa_capture );
     canonicalize_kappa_capture();
     jDebugTaggedLine( "reading Origen::TransitionCoeff::b_kappa_fission..." );
     b_kappa_fission = std::make_shared<Vec_Flt>();
     bytes += Standard::read( stream, b_kappa_fission );
     canonicalize_kappa_fission();
     jDebugTaggedLine( "finished reading Origen::TransitionCoeff bytes="
                       << bytes
                       << " size="
                       << size
                       << " getSerializedSize="
                       << getSerializedSize() );
     Ensure( size == bytes );
     if( size != bytes ) return 1;
     return 0;
 }
unsigned long getSerializedSize () const
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, and TransitionCoeff::b_neutron_yields.
Referenced by TransitionCoeff::deserialize(), and TransitionCoeff::serialize().
 {
     Standard::AbstractStream* a = nullptr;
     return Standard::bytes( a, b_burnup ) + Standard::bytes( a, b_matrix ) +
            Standard::bytes( a, b_loss_xs ) +
            Standard::bytes( a, b_fission_xs ) +
            Standard::bytes( a, b_neutron_yields ) +
            Standard::bytes( a, b_flux ) +
            Standard::bytes( a, b_kappa_capture ) +
            Standard::bytes( a, b_kappa_fission );
 }
Standard::Serializable * getCopy () const
References TransitionCoeff::TransitionCoeff().
 {
     return new TransitionCoeff( *this );
 }
Standard::Serializable::UID getUID () const virtual
References TransitionCoeff::uid.
 {
     return TransitionCoeff::uid;
 }
std::string toString () const
Examples:
Core/dc/tests/tstTransitionCoeff.cpp.
References TransitionCoeff::to_string().
Referenced by serialization_roundtrip().
 { return to_string(); }
size_t fission_xs_index (size_t i, const NuclideSet & nucset) static
References Origen::BAD_SIZE_T, NuclideSet::has_sublib(), Origen::SUBLIB_2AC, NuclideSet::sublib_begin(), and NuclideSet::sublib_end().
Referenced by TransitionCoeff::capture_power(), TransitionCoeff::fission_power(), TransitionCoeff::reaction_power(), and Origen::tabulateFissionXs().
 {
     if( nucset.has_sublib( SUBLIB_2AC ) )
     {
         size_t js = nucset.sublib_begin( SUBLIB_2AC );
         size_t je = nucset.sublib_end( SUBLIB_2AC );
         return i >= js && i < je ? i - js : BAD_SIZE_T;
     }
     else
     {
         return i;
     }
 }
Json::Value to_json () const
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, and TransitionCoeff::uid.
Referenced by TransitionCoeff::to_string().
 {
     Json::Value root;
     root["uid"] = Json::Value::Int64( uid );
     root["burnup"] = b_burnup;
     Standard::Json::arrayToJson( root["matrix"], *b_matrix );
     Standard::Json::arrayToJson( root["loss_xs"], *b_loss_xs );
     Standard::Json::arrayToJson( root["fission_xs"], *b_fission_xs );
     Standard::Json::arrayToJson( root["neutron_yields"], *b_neutron_yields );
     Standard::Json::arrayToJson( root["flux"], *b_flux );
     Standard::Json::arrayToJson( root["kappa_fission"], *b_kappa_fission );
     Standard::Json::arrayToJson( root["kappa_capture"], *b_kappa_capture );
     return root;
 }
std::string to_string () const
References TransitionCoeff::to_json().
Referenced by TransitionCoeff::toString().
 {
     return to_json().toStyledString();
 }
void scale (double wt)
Examples:
Core/fn/tests/tstinterp.cpp.
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, TransitionCoeff::burnup(), TransitionCoeff::set_burnup(), TransitionCoeff::set_fission_xs(), TransitionCoeff::set_flux(), TransitionCoeff::set_kappa_capture(), TransitionCoeff::set_kappa_fission(), TransitionCoeff::set_loss_xs(), TransitionCoeff::set_matrix(), and TransitionCoeff::set_neutron_yields().
Referenced by FakeFactory::Library_linear1D(), FakeFactory::Library_linear2D(), and TEST().
 {
     // first make copies
     set_burnup( burnup() );
     set_matrix( *b_matrix );
     set_loss_xs( *b_loss_xs );
     set_fission_xs( *b_fission_xs );
     set_neutron_yields( *b_neutron_yields );
     set_flux( *b_flux );
     set_kappa_fission( *b_kappa_fission );
     set_kappa_capture( *b_kappa_capture );
     // then scale
     b_burnup *= wt;
     ScaleSTL::scale_vec( *b_matrix, wt );
     ScaleSTL::scale_vec( *b_loss_xs, wt );
     ScaleSTL::scale_vec( *b_fission_xs, wt );
     ScaleSTL::scale_vec( *b_neutron_yields, wt );
     ScaleSTL::scale_vec( *b_flux, wt );
     ScaleSTL::scale_vec( *b_kappa_capture, wt );
     ScaleSTL::scale_vec( *b_kappa_fission, wt );
 }
bool approx_eq (const TransitionCoeff & other, double tol = 1e-12) const
Examples:
Core/dc/tests/tstLibrary.cpp, and Core/dc/tests/tstTransitionCoeff.cpp.
References TransitionCoeff::b_burnup, TransitionCoeff::b_fission_xs, TransitionCoeff::b_flux, TransitionCoeff::b_kappa_capture, TransitionCoeff::b_kappa_fission, TransitionCoeff::b_loss_xs, TransitionCoeff::b_matrix, TransitionCoeff::b_neutron_yields, TransitionCoeff::burnup(), TransitionCoeff::has_kappa_capture(), TransitionCoeff::has_kappa_fission(), TransitionCoeff::kappa_capture_size(), TransitionCoeff::kappa_fission_size(), TransitionCoeff::scp_fission_xs(), TransitionCoeff::scp_flux(), TransitionCoeff::scp_kappa_capture(), TransitionCoeff::scp_kappa_fission(), TransitionCoeff::scp_loss_xs(), TransitionCoeff::scp_matrix(), TransitionCoeff::scp_neutron_yields(), and SP_CAST_VF.
Referenced by TEST().
 {
     using ScaleSTL::approx_eq;
     using ScaleSTL::approx_eq_sp_vec;
     bool final =
         approx_eq( b_burnup, other.burnup() ) &&
         approx_eq_sp_vec( SP_CAST_VF( b_matrix ), other.scp_matrix() ) &&
         approx_eq_sp_vec( SP_CAST_VF( b_loss_xs ), other.scp_loss_xs() ) &&
         approx_eq_sp_vec( SP_CAST_VF( b_fission_xs ),
                           other.scp_fission_xs() ) &&
         approx_eq_sp_vec( SP_CAST_VF( b_neutron_yields ),
                           other.scp_neutron_yields() ) &&
         approx_eq_sp_vec( SP_CAST_VF( b_flux ), other.scp_flux() );
     if( has_kappa_capture() && other.has_kappa_capture() &&
         kappa_capture_size() > 0 && other.kappa_capture_size() > 0 )
     {
         final = final && approx_eq_sp_vec( SP_CAST_VF( b_kappa_capture ),
                                            other.scp_kappa_capture() );
     }
     if( has_kappa_fission() && other.has_kappa_fission() &&
         kappa_fission_size() > 0 && other.kappa_fission_size() > 0 )
     {
         final = final && approx_eq_sp_vec( SP_CAST_VF( b_kappa_fission ),
                                            other.scp_kappa_fission() );
     }
     return final;
 }
void canonicalize_matrix () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
void canonicalize_neutron_yields () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
void canonicalize_flux () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
void canonicalize_loss_xs () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
void canonicalize_fission_xs () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
void canonicalize_kappa_capture () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
void canonicalize_kappa_fission () protected
Referenced by TransitionCoeff::deserialize().
 {
     // null op
 }
double reaction_power (const std::vector< double > & numden, double vol, double flux, const NuclideSet & nucset) const
float reaction_power (const std::vector< float > & numden, float vol, float flux, const NuclideSet & nucset) const
double capture_power (const std::vector< double > & numden, double vol, double flux, const NuclideSet & nucset) const
float capture_power (const std::vector< float > & numden, float vol, float flux, const NuclideSet & nucset) const
double fission_power (const std::vector< double > & numden, double vol, double flux, const NuclideSet & nucset) const
float fission_power (const std::vector< float > & numden, float vol, float flux, const NuclideSet & nucset) const
Friends And Related Function Documentation
friend class ScaleUtils::IO::Accessor< TransitionCoeff > friend
friend class GridView_TransitionCoeff friend
Member Data Documentation
const Standard::Serializable::UID uid = 0x99152462a5c56032 static
Referenced by Library::deserialize(), TransitionCoeff::getUID(), Origen_TransitionCoeff_uid(), and TransitionCoeff::to_json().
float b_burnup protected
Burnup value (MWd/MTIHM)
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::deserialize(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_matrix protected
Transition structure (describes allowed transitions/contains library header)
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_loss_xs protected
Loss cross section (tocap), size=itot
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::capture_power(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), TransitionCoeff::reaction_power(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_fission_xs protected
Fission cross section (fiss), size=iact
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::capture_power(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::fission_power(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), TransitionCoeff::reaction_power(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_neutron_yields protected
Neutron yields (genneu), size=ilite+iact
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_flux protected
Spectrum used for the XS collapse (header num neutron energy groups)
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_kappa_capture protected
List of kappa capture values (MeV/reaction) size=itot
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::capture_power(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::fission_power(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), TransitionCoeff::reaction_power(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
SP_Vec_Flt b_kappa_fission protected
List of kappa fission values (MeV/reaction) size=iact
Referenced by TransitionCoeff::approx_eq(), TransitionCoeff::clone(), TransitionCoeff::deserialize(), TransitionCoeff::fission_power(), TransitionCoeff::getSerializedSize(), TransitionCoeff::operator==(), TransitionCoeff::print_compare(), TransitionCoeff::reaction_power(), Accessor< Origen::TransitionCoeff >::read(), TransitionCoeff::scale(), TransitionCoeff::serialize(), and TransitionCoeff::to_json().
The documentation for this class was generated from the following files:
Core/dc/TransitionCoeff.h
Core/dc/TransitionCoeff.cpp
Core/dc/TransitionCoeff.i.h