ORIGEN API: Solver/radau5/src/kernel_radau5.hpp File Reference
kernel_radau5.hpp File Reference
Header for calling the fortran function radau5_solve() from c.
#include "Origen/Core/dc/TransitionMatrixP.h"
#include "Standard/Interface/Reporter.h"
Functions
void F_kernel_radau5 (unsigned long *cp_lib, int itot, int non, double *n0, double *n, double delta_t, double *diag, double *a, double *source_term, int i_zero_flux_step, int i_is_adjoint, double abstol, double reltol)
void kernel_radau5 (TransitionMatrixP *cp_lib, int itot, int non, double *n0, double *n, double delta_t, double *diag, double *a, double *source_term, int i_zero_flux_step, int i_is_adjoint, double abstol, double reltol)
Detailed Description
Header for calling the fortran function radau5_solve() from c.
Author
Aarno Isotalo
Function Documentation
void F_kernel_radau5 (unsigned long * cp_lib, int itot, int non, double * n0, double * n, double delta_t, double * diag, double * a, double * source_term, int i_zero_flux_step, int i_is_adjoint, double abstol, double reltol)
Referenced by kernel_radau5().
void kernel_radau5 (TransitionMatrixP * cp_lib, int itot, int non, double * n0, double * n, double delta_t, double * diag, double * a, double * source_term, int i_zero_flux_step, int i_is_adjoint, double abstol, double reltol)
Call the radau5 solver (radau_solve() in fortran) from c. Note that some arguments differ from the fortran origan_solve()
Examples:
Solver/radau5/src/tests/tstKernelRadau5C.cpp.
References F_kernel_radau5().
Referenced by TEST().