ORIGEN API: STab1Reader Class Reference
STab1Reader Class Reference
#include <STab1Reader.h>
simplified Tab1 reader
Public Member Functions
std::string read (std::istream &is)
read it
STab1Reader ()
construct it
Public Attributes
SP_STab1 stab1
data that was read in
Static Protected Member Functions
static void getline (std::istream &is, std::string *buffer)
put a line into buffer
static double getRealValue (const std::string &line, int index)
get the index of 6 values as a double on line
static int getIntValue (const std::string &line, int index)
get the index of 6 values as an integer on line
static void getLineValues_2Real_4Int (const std::string &line, double &f1, double &f2, int &i1, int &i2, int &i3, int &i4)
get 2 floats and 4 ints a line
static void getLineValues_6Real (const std::string &line, double &f1, double &f2, double &f3, double &f4, double &f5, double &f6)
get 6 floats on a line
static bool isTerminatorLine (const std::string &line)
check if a line is a terminator (all zeros)
static std::string readTitle (std::istream &is, std::string *title)
rad the one line title
static std::string readData (std::istream &is, STab1::Data *data)
read a data set
static std::string readBlock (std::istream &is, STab1::Block *block)
read a data block (contains 1 or more data sets)
static std::string readFile (std::istream &is, STab1 *stab1)
read the simplified tab1 data
Detailed Description
simplified Tab1 reader
Constructor & Destructor Documentation
STab1Reader () inline
construct it
 : stab1( new STab1() ) {}
Member Function Documentation
std::string read (std::istream & is)
read it
References STab1Reader::readFile(), and STab1Reader::stab1.
Referenced by YieldResourceIO_stab1::read().
 {
     return readFile( is, &*( this->stab1 ) );
 }
void getline (std::istream & is, std::string * buffer) static protected
put a line into buffer
Referenced by STab1Reader::readBlock(), STab1Reader::readData(), STab1Reader::readFile(), and STab1Reader::readTitle().
 {
     Require( buffer != nullptr );
     std::getline( is, *buffer );
     // jDebugLine("STab1Reader::getline("<<*buffer<<")");
 }
double getRealValue (const std::string & line, int index) static protected
get the index of 6 values as a double on line
References Origen::BAD_DOUBLE, and STab1::ENDF_FIELD_LENGTH.
Referenced by STab1Reader::getLineValues_2Real_4Int(), STab1Reader::getLineValues_6Real(), and STab1Reader::readData().
 {
     int start = ( index - 1 ) * STab1::ENDF_FIELD_LENGTH;
     int end = start + STab1::ENDF_FIELD_LENGTH;
     double value = endfendf::Record::getDoubleValue(
         line.c_str(), line.length(), start, end, BAD_DOUBLE );
     // jDebugTaggedLine("read value="<<value<<" from start="<<start<<" to
     // end="<<end);
     return value;
 }
int getIntValue (const std::string & line, int index) static protected
get the index of 6 values as an integer on line
References Origen::BAD_INT, and STab1::ENDF_FIELD_LENGTH.
Referenced by STab1Reader::getLineValues_2Real_4Int().
 {
     int start = ( index - 1 ) * STab1::ENDF_FIELD_LENGTH;
     int end = start + STab1::ENDF_FIELD_LENGTH;
     int value = endfendf::Record::getIntValue(
         line.c_str(), line.length(), start, end, BAD_INT );
     // jDebugTaggedLine("read value="<<value<<" from start="<<start<<" to
     // end="<<end);
     return value;
 }
void getLineValues_2Real_4Int (const std::string & line, double & f1, double & f2, int & i1, int & i2, int & i3, int & i4) static protected
get 2 floats and 4 ints a line
References STab1Reader::getIntValue(), and STab1Reader::getRealValue().
Referenced by STab1Reader::isTerminatorLine().
 {
     f1 = getRealValue( line, 1 );
     f2 = getRealValue( line, 2 );
     i1 = getIntValue( line, 3 );
     i2 = getIntValue( line, 4 );
     i3 = getIntValue( line, 5 );
     i4 = getIntValue( line, 6 );
     // jDebugTaggedLine("read f1="<<f1<<" f2="<<f2<<" i1="<<i1<<" i2="<<i2<<"
     // i3="<<i3<<" i4="<<i4);
 }
void getLineValues_6Real (const std::string & line, double & f1, double & f2, double & f3, double & f4, double & f5, double & f6) static protected
get 6 floats on a line
References STab1Reader::getRealValue().
 {
     f1 = getRealValue( line, 1 );
     f2 = getRealValue( line, 2 );
     f3 = getRealValue( line, 3 );
     f4 = getRealValue( line, 4 );
     f5 = getRealValue( line, 5 );
     f6 = getRealValue( line, 6 );
     // jDebugTaggedLine("read f1="<<f1<<" f2="<<f2<<" f3="<<f3<<" f4="<<f4<<"
     // f5="<<f5<<" f6="<<f6);
 }
bool isTerminatorLine (const std::string & line) static protected
check if a line is a terminator (all zeros)
References STab1Reader::getLineValues_2Real_4Int().
Referenced by STab1Reader::readBlock(), STab1Reader::readData(), and STab1Reader::readFile().
 {
     double f1, f2;
     int i1, i2, i3, i4;
     getLineValues_2Real_4Int( line, f1, f2, i1, i2, i3, i4 );
     return f1 == 0.0 && f2 == 0.0 && i1 == 0 && i2 == 0 && i3 == 0 && i4 == 0;
 }
std::string readTitle (std::istream & is, std::string * title) static protected
rad the one line title
References STab1Reader::getline().
Referenced by STab1Reader::readFile().
 {
     if( !is.good() ) return "premature end of file";
     getline( is, title );
     return "";
 }
std::string readData (std::istream & is, STab1::Data * data) static protected
read a data set
References STab1::Data::cr, STab1Reader::getline(), STab1Reader::getRealValue(), STab1::Data::id, STab1Reader::isTerminatorLine(), and STab1::Data::val.
Referenced by STab1Reader::readBlock().
 {
     Require( data != nullptr );
     int status = data->cr.readData( is );
     if( status != 0 )
     {
         return "expected Data header";
     }
     std::string buffer;
     int pairs = 0;
     while( is.good() )
     {
         // lookahead to check for termination
         getline( is, &buffer );
         if( isTerminatorLine( buffer ) ) break;
         for( size_t j = 0; j < 3; j++ )
         {
             pairs++;
             int id1 = getRealValue( buffer, 2 * j + 1 );
             double f1 = getRealValue( buffer, 2 * j + 2 );
             // jDebugLine("    i="<<pairs<<" id="<<id1<<" yield="<<f1);
             data->id.push_back( id1 );
             data->val.push_back( f1 );
         }
     }
     if( !is.good() ) return "premature end of file";
     if( !isTerminatorLine( buffer ) ) return "missing terminator line";
     return "";
 }
std::string readBlock (std::istream & is, STab1::Block * block) static protected
read a data block (contains 1 or more data sets)
References STab1::Block::cr, STab1Reader::getline(), STab1Reader::isTerminatorLine(), STab1Reader::readData(), and STab1::Block::set.
Referenced by STab1Reader::readFile().
 {
     int status = block->cr.readData( is );
     if( status != 0 )
     {
         return "expected Block header";
     }
     std::string buffer;
     int nsets = 0;
     while( is.good() )
     {
         // lookahead to check for termination
         int pos = is.tellg();
         getline( is, &buffer );
         if( isTerminatorLine( buffer ) ) break;
         is.seekg( pos );
         ++nsets;
         // jDebugBlock("reading set="<<nsets);
         block->set.resize( nsets );
         std::string error = readData( is, &( block->set.back() ) );
         if( error != "" )
         {
             return error;
         }
     }
     if( !is.good() ) return "premature end of file";
     if( !isTerminatorLine( buffer ) ) return "missing terminator line";
     return "";
 }
std::string readFile (std::istream & is, STab1 * stab1) static protected
read the simplified tab1 data
References STab1::block, STab1Reader::getline(), STab1Reader::isTerminatorLine(), STab1Reader::readBlock(), STab1Reader::readTitle(), and STab1::title.
Referenced by STab1Reader::read().
 {
     std::string error = readTitle( is, &( stab1->title ) );
     if( error != "" )
     {
         return error;
     }
     std::string buffer;
     int nblocks = 0;
     while( is.good() )
     {
         // lookahead to check for termination
         int pos = is.tellg();
         getline( is, &buffer );
         if( isTerminatorLine( buffer ) ) break;
         is.seekg( pos );
         ++nblocks;
         // jDebugLine("reading block="<<nblocks);
         stab1->block.resize( nblocks );
         error = readBlock( is, &( stab1->block.back() ) );
         if( error != "" )
         {
             return error;
         }
     }
     if( !is.good() ) return "premature end of file";
     if( !isTerminatorLine( buffer ) ) return "missing terminator line";
     return "";
 }
Member Data Documentation
SP_STab1 stab1
data that was read in
Referenced by YieldResourceIO_stab1::read(), and STab1Reader::read().
The documentation for this class was generated from the following files:
Core/io/STab1Reader.h
Core/io/STab1Reader.cpp