ORIGEN API: ChannelType Class Reference
ChannelType Class Reference abstract
#include <ChannelType.h>
Defines the channel type interface for the TransitionSystem.
Public Types
typedef SP_ChannelType SP
strong pointer
typedef WP_ChannelType WP
weak pointer
INTERFACE<<Origen::ChannelType>>
See Origen::ChannelType for details.
int reaction_mt () const
void set_reaction_mt (int reaction_mt)
std::string reaction_mt_name () const
bool has_initialized_reaction_mt () const
int decay_mode () const
void set_decay_mode (int decay_mode)
std::string decay_mode_name () const
bool has_initialized_decay_mode () const
SP_Field field () const
void get_field (SP_Field &field) const
void set_field (SP_Field field)
bool has_initialized_field () const
bool is_reaction () const
bool is_decay () const
bool has_followon_decay () const
bool has_distribution_of_daughters () const
double num_residuals_per_event () const
int num_byproduct (const ByproductId byproduct_id) const
bool has_byproduct (const ByproductId byproduct_id) const
ByproductCount_t num_byproducts () const
void increment_num_byproducts (ByproductCount_t &num_byproducts) const
int delta_nucleus_protons () const
int delta_nucleus_neutrons () const
int delta_mass_number () const
int delta_charge_number () const
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
Static Public Member Functions
static int channel_id (int decay_mode)
channel id for decay only
static int channel_id (SP_Field field, int reaction_mt, int decay_mode=0)
channel id for reaction+decay
Protected Member Functions
virtual bool good_impl (Vec_Str &errors) const
useful to chain
Private Member Functions
virtual int reaction_mt_impl () const =0
virtual void set_reaction_mt_impl (int reaction_mt)=0
virtual std::string reaction_mt_name_impl () const
virtual int decay_mode_impl () const =0
virtual void set_decay_mode_impl (int decay_mode)=0
virtual std::string decay_mode_name_impl () const
virtual SP_Field field_impl () const =0
virtual void get_field_impl (SP_Field &field) const
virtual void set_field_impl (SP_Field field)=0
virtual bool is_reaction_impl () const
virtual bool is_decay_impl () const
virtual bool has_followon_decay_impl () const
virtual bool is_initialized_impl () const
useful to chain
virtual bool has_initialized_field_impl () const
virtual bool has_initialized_decay_mode_impl () const
virtual bool has_initialized_reaction_mt_impl () const
virtual bool has_distribution_of_daughters_impl () const
virtual double num_residuals_per_event_impl () const
virtual int num_byproduct_impl (const ByproductId byproduct_id) const
virtual bool has_byproduct_impl (const ByproductId byproduct_id) const
virtual ByproductCount_t num_byproducts_impl () const =0
virtual int delta_nucleus_protons_impl () const =0
virtual int delta_nucleus_neutrons_impl () const =0
virtual int delta_mass_number_impl () const =0
virtual int delta_charge_number_impl () const =0
virtual std::string name_impl () const
virtual int id_impl () const
virtual Scale::Json::Value to_json_impl () const
useful to chain
Detailed Description
Defines the channel type interface for the TransitionSystem.
The channel type, in the context of the transition system, manages three piece of data:
field
reaction mt
decay mode
It provides information for each type of channel, e.g.
the number of residuals/byproducts produced per event
the change in number of protons/neutrons/mass/number charge number
See also
Channel
Member Typedef Documentation
typedef SP_ChannelType SP
strong pointer
typedef WP_ChannelType WP
weak pointer
Member Function Documentation
int reaction_mt () const
Referenced by ChannelType_Fiss::good_impl(), ChannelType_Reac::good_impl(), ChannelType_Fiss::set_reaction_mt_impl(), and ChannelType_Reac::set_reaction_mt_impl().
 { return reaction_mt_impl(); }
void set_reaction_mt (int reaction_mt)
Referenced by ChannelType_Fiss::ChannelType_Fiss(), and ChannelType_Reac::ChannelType_Reac().
 {
     set_reaction_mt_impl( reaction_mt );
 }
std::string reaction_mt_name () const
 {
     return reaction_mt_name_impl();
 }
bool has_initialized_reaction_mt () const
 {
     return has_initialized_reaction_mt_impl();
 }
int decay_mode () const
Referenced by ChannelType_Decay::good_impl().
 { return decay_mode_impl(); }
void set_decay_mode (int decay_mode)
Referenced by ChannelType_Decay::ChannelType_Decay().
 {
     set_decay_mode_impl( decay_mode );
 }
std::string decay_mode_name () const
 {
     return decay_mode_name_impl();
 }
bool has_initialized_decay_mode () const
 {
     return has_initialized_decay_mode_impl();
 }
SP_Field field () const
Referenced by ChannelType_Fiss::good_impl(), ChannelType_Reac::good_impl(), ChannelType_Fiss::set_field_impl(), and ChannelType_Reac::set_field_impl().
 { return field_impl(); }
void get_field (SP_Field & field) const
 {
     get_field_impl( field );
 }
void set_field (SP_Field field)
Referenced by ChannelType_Fiss::ChannelType_Fiss(), and ChannelType_Reac::ChannelType_Reac().
 { set_field_impl( field ); }
bool has_initialized_field () const
 {
     return has_initialized_field_impl();
 }
bool is_reaction () const
 { return is_reaction_impl(); }
bool is_decay () const
 { return is_decay_impl(); }
bool has_followon_decay () const
 {
     return has_followon_decay_impl();
 }
bool has_distribution_of_daughters () const
 {
     return has_distribution_of_daughters_impl();
 }
double num_residuals_per_event () const
 {
     return num_residuals_per_event_impl();
 }
int num_byproduct (const ByproductId byproduct_id) const
 {
     return num_byproduct_impl( byproduct_id );
 }
bool has_byproduct (const ByproductId byproduct_id) const
 {
     return has_byproduct_impl( byproduct_id );
 }
ByproductCount_t num_byproducts () const
 {
     return num_byproducts_impl();
 }
void increment_num_byproducts (ByproductCount_t & num_byproducts) const
int delta_nucleus_protons () const
 {
     return delta_nucleus_protons_impl();
 }
int delta_nucleus_neutrons () const
 {
     return delta_nucleus_neutrons_impl();
 }
int delta_mass_number () const
 { return delta_mass_number_impl(); }
int delta_charge_number () const
 {
     return delta_charge_number_impl();
 }
int channel_id (int decay_mode) static
channel id for decay only
Referenced by TransitionSystem_Gen::channel_type_impl(), and TransitionSystemAdapter_AmpxN::update().
 {
     return channel_id( nullptr, 0, decay_mode );
 }
int channel_id (SP_Field field, int reaction_mt, int decay_mode = 0) static
channel id for reaction+decay
 {
     if( reaction_mt > 0 )
     {
         Check( decay_mode == 0 );
         int field_id = field == nullptr ? 11 : field->id();
         return ( field_id - 1 ) * 10000 + reaction_mt;
     }
     else
     {
         return -decay_mode;
     }
 }
virtual int reaction_mt_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
virtual void set_reaction_mt_impl (int reaction_mt) private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
std::string reaction_mt_name_impl () const private virtual
 {
     std::string name = "UNDEFINED";
     if( has_initialized_reaction_mt() )
     {
         name = ScaleData::Utils::mt_to_reaction( reaction_mt() );
     }
     return name;
 }
virtual int decay_mode_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
virtual void set_decay_mode_impl (int decay_mode) private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
std::string decay_mode_name_impl () const private virtual
 {
     std::string name = "UNDEFINED";
     if( has_initialized_decay_mode() )
     {
         name = ScaleData::Utils::decay_mode_to_name( decay_mode() );
     }
     return name;
 }
virtual SP_Field field_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
void get_field_impl (SP_Field & field) const private virtual
 {
     field = this->field();
 }
virtual void set_field_impl (SP_Field field) private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
bool is_reaction_impl () const private virtual
Reimplemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
References Origen::BAD_INT.
 { return reaction_mt() != BAD_INT; }
bool is_decay_impl () const private virtual
Reimplemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
References Origen::BAD_INT.
 {
     return !is_reaction() && decay_mode() != BAD_INT;
 }
bool has_followon_decay_impl () const private virtual
Reimplemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
References Origen::BAD_INT.
 {
     return is_reaction() && decay_mode() != BAD_INT;
 }
bool is_initialized_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     return has_initialized_reaction_mt() && has_initialized_decay_mode() &&
            has_initialized_field() && Checkable::is_initialized_impl();
 }
bool has_initialized_field_impl () const private virtual
 {
     return field() != nullptr;
 }
bool has_initialized_decay_mode_impl () const private virtual
References Origen::BAD_INT.
 {
     return decay_mode() != BAD_INT;
 }
bool has_initialized_reaction_mt_impl () const private virtual
References Origen::BAD_INT.
 {
     return reaction_mt() != BAD_INT;
 }
bool has_distribution_of_daughters_impl () const private virtual
Reimplemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
 { return false; }
double num_residuals_per_event_impl () const private virtual
Reimplemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
 { return 1.0; }
int num_byproduct_impl (const ByproductId byproduct_id) const private virtual
Reimplemented in ChannelType_Fiss.
 {
     ByproductCount_t byproduct_map = num_byproducts();
     ByproductCount_t::const_iterator it = byproduct_map.find( byproduct_id );
     return it == byproduct_map.end() ? 0 : it->second;
 }
bool has_byproduct_impl (const ByproductId byproduct_id) const private virtual
Reimplemented in ChannelType_Fiss.
 {
     return num_byproduct( byproduct_id ) > 0;
 }
virtual ByproductCount_t num_byproducts_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
virtual int delta_nucleus_protons_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
virtual int delta_nucleus_neutrons_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
virtual int delta_mass_number_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
virtual int delta_charge_number_impl () const private pure virtual
Implemented in ChannelType_Reac, ChannelType_Decay, and ChannelType_Fiss.
std::string name_impl () const private virtual
Reimplemented from Checkable.
 {
     std::stringstream ss;
     ss << "CHANNELTYPE(" << id() << ")";
     return ss.str();
 }
int id_impl () const private virtual
Reimplemented from Checkable.
 {
     return channel_id( field(), reaction_mt(), decay_mode() );
 }
Json::Value to_json_impl () const private virtual
useful to chain
Reimplemented from Checkable.
 {
     Json::Value json( Json::objectValue );
     json = Checkable::to_json_impl();
     json["field"] = "NULL";
     if( has_initialized_field() )
     {
         json["field"] = field()->to_json();
     }
     json["reaction_mt"] = reaction_mt();
     json["decay_mode"] = decay_mode();
     json["is_reaction"] = is_reaction();
     json["is_decay"] = is_decay();
     json["has_followon_decay"] = has_followon_decay();
     json["has_initialized_reaction_mt"] = has_initialized_reaction_mt();
     json["has_initialized_decay_mode"] = has_initialized_decay_mode();
     json["has_initialized_field"] = has_initialized_field();
     json["reaction_mt_name"] = reaction_mt_name();
     json["decay_mode_name"] = decay_mode_name();
     json["has_distribution_of_daughters"] = has_distribution_of_daughters();
     json["num_residuals_per_event"] = num_residuals_per_event();
     Json::Value byproducts( Json::objectValue );
     ByproductCount_t byproduct_map = num_byproducts();
     ByproductCount_t::const_iterator it = byproduct_map.begin();
     while( it != byproduct_map.end() )
     {
         // std::cout << it->first << ": " << it->second<<std::endl;
         std::stringstream ss;
         ss << std::setw( 4 ) << std::setfill( '0' ) << it->first;
         byproducts[ss.str()] = it->second;
         ++it;
     }
     json["byproducts"] = byproducts;
     json["delta_nucleus_protons"] = delta_nucleus_protons();
     json["delta_nucleus_neutrons"] = delta_nucleus_neutrons();
     json["delta_mass_number"] = delta_mass_number();
     json["delta_charge_number"] = delta_charge_number();
     //        json["delta_zzzaaa"]=delta_zzzaaa();
     return json;
 }
std::string name () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
Core/ts/tests/tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
bool good_impl (Vec_Str & errors) const protected virtual inherited
useful to chain
Reimplemented in Nuclide, Channel, Null, Neutrino, Positron, Species, Transition, Electron, Field, Alpha, ChannelType_Reac, ChannelType_Decay, ChannelType_Fiss, Helion, TransitionSystem_Gen, Triton, Deuteron, Proton, and Neutron.
References ORIGEN_CHECKABLE_ERROR.
 {
     std::stringstream ss;
     bool pass = true;
     if( !has_initialized_id() )
         ORIGEN_CHECKABLE_ERROR(
             name() << " has uninitialized id", pass, errors );
     return pass;
 }
The documentation for this class was generated from the following files:
Core/ts/ChannelType.h
Core/ts/ChannelType.cpp