ORIGEN API: TransitionSystemAdapter_AmpxN Class Reference
TransitionSystemAdapter_AmpxN Class Reference
#include <TransitionSystemAdapter_AmpxN.h>
Public Types
typedef std::map< int, int > NuclideTranslation_t
Public Member Functions
TransitionSystemAdapter_AmpxN ()
virtual ~TransitionSystemAdapter_AmpxN ()
virtual void set_nuclide_translation (const Vec_Int &ampx_id, const Vec_Int &izzzaaa, bool union_with=true)
Set id translation, e.g. 8001->8016.
virtual void get_nuclide_translation (Vec_Int *ampx_id, Vec_Int *izzzaaa) const
Get current id translation.
virtual const NuclideTranslation_t & nuclide_translation () const
Return current id translation.
virtual void extend (TransitionSystem *ts, bool add_byproducts_and_relink=true) const
virtual float update (TransitionSystem *ts, const Vec_Flt &flux) const
virtual float update (TransitionSystem *ts, const CrossSection1d *flux) const
virtual void extend_by_mix (TransitionSystem *ts, const AmpxLibrary &main, int mix_id=-1, bool extend_internal=false, bool skip_not_present=false) const
virtual float update_by_mix (TransitionSystem *ts, const AmpxLibrary &main, int mix_id, int flux_nuclide_id=-1, int flux_mt=1099) const
virtual float update_by_mix (TransitionSystem *ts, const AmpxLibrary &main, int mix_id, const Vec_Flt &flux) const
SCP_ReactionResource reaction_resource () const
return shared (read-only) reaction_resource resource \
bool has_reaction_resource () const
whether this instantiation of class has the reaction_resource resource \
void set_reaction_resource (SCP_ReactionResource)
set a new shared (read-only) reaction_resource resource (non-const version) \
void print (const AmpxLibrary &main, std::ostream &os=std::cout)
Print the AMPX library contents this class cares about.
Protected Attributes
NuclideTranslation_t d_nuclide_translation
Map an AMPX nuclide id to an IZZZAAA.
SCP_ReactionResource d_reaction_resource
Detailed Description
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Member Typedef Documentation
typedef std::map<int, int> NuclideTranslation_t
Constructor & Destructor Documentation
TransitionSystemAdapter_AmpxN ()
 {}
~TransitionSystemAdapter_AmpxN () virtual
 {}
Member Function Documentation
void set_nuclide_translation (const Vec_Int & ampx_id, const Vec_Int & izzzaaa, bool union_with = true) virtual
Set id translation, e.g. 8001->8016.
 {
     Require( ampx_id.size() == izzzaaa.size() );
     if( !union_with ) d_nuclide_translation.clear();
     for( size_t i = 0; i < ampx_id.size(); ++i )
     {
         d_nuclide_translation[ampx_id[i]] = izzzaaa[i];
     }
 }
void get_nuclide_translation (Vec_Int * ampx_id, Vec_Int * izzzaaa) const virtual
Get current id translation.
References TransitionSystemAdapter_AmpxN::d_nuclide_translation.
 {
     Require( ampx_id != nullptr );
     Require( izzzaaa != nullptr );
     ampx_id->clear();
     ampx_id->reserve( d_nuclide_translation.size() );
     izzzaaa->clear();
     izzzaaa->reserve( d_nuclide_translation.size() );
     NuclideTranslation_t::const_iterator it;
     for( it = d_nuclide_translation.begin(); it != d_nuclide_translation.end();
          ++it )
     {
         ampx_id->push_back( it->first );
         izzzaaa->push_back( it->second );
     }
 }
const TransitionSystemAdapter_AmpxN::NuclideTranslation_t & nuclide_translation () const virtual
Return current id translation.
References TransitionSystemAdapter_AmpxN::d_nuclide_translation.
 {
     return d_nuclide_translation;
 }
void extend (TransitionSystem * ts, bool add_byproducts_and_relink = true) const virtual
Extend a transition system (i.e. create new nuclides/reactions) using the internal multi-group database.
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References TransitionSystem::add_nuclide(), TransitionSystemAdapter_AmpxN::d_reaction_resource, auxiliary::nuclide(), TransitionSystem::populate_gains(), Origen::YIELD_ISOMERIC, and Origen::YIELD_SIMPLE.
Referenced by TransitionSystemAdapter_AmpxN::extend_by_mix(), TransitionMatrixUpdater::load(), Origen::test::TEST(), and TEST_F().
 {
     SCOPED_TIMER( "TransitionSystemAdapter_AmpxN.extend" );
     Require( ts != nullptr );
     ReactionResource::const_iterator it1;
     ReactionResource::Nuclide::const_iterator it2;
     Check( d_reaction_resource != nullptr );
     int field_id = d_reaction_resource->field_id();
     for( it1 = d_reaction_resource->begin(); it1 != d_reaction_resource->end();
          ++it1 )
     {
         int izzzaaa = it1->first;
         auto nuclide = ts->add_nuclide( izzzaaa );
         jDebugTaggedLine( "adding nuclide=" << izzzaaa );
         const ReactionResource::Nuclide& a_nd = it1->second;
         for( it2 = a_nd.begin(); it2 != a_nd.end(); ++it2 )
         {
             int mt = it2->first;
             jDebugTaggedLine( "   adding mt=" << mt );
             const ReactionResource::Nuclide::Xs& a_xs = it2->second;
             if( a_xs.yield_type == YIELD_ISOMERIC )
             {
                 auto channel = nuclide->add_loss( field_id, mt );
                 size_t num_isomeric = a_xs.pyield.size();
                 for( size_t i = 0; i < num_isomeric; ++i )
                 {
                     jDebugTaggedLine( "      adding isomeric=" << i );
                     channel->add_transition( i );
                 }
             }
             else if( a_xs.yield_type == YIELD_SIMPLE )
             {
                 auto channel = nuclide->add_loss( field_id, mt );
                 jDebugTaggedLine( "      adding simple" );
                 channel->add_transition( 0 );
             }
             else
             {
                 Check( mt == 18 );
                 auto channel = nuclide->add_loss( field_id, mt );
                 // extend for data like nubar
                 std::map<int, Vec_Flt>::const_iterator itd;
                 for( itd = a_xs.dyield.begin(); itd != a_xs.dyield.end();
                      ++itd )
                 {
                     jDebugTaggedLine( "      adding byproduct=" << itd->first );
                     channel->add_transition( itd->first );
                 }
                 // extend for data like fp yields
                 typedef ScaleUtils::Math::Interp1D_FastLinear<float> Interp;
                 std::map<int, Interp>::const_iterator iti;
                 for( iti = a_xs.iyield.begin(); iti != a_xs.iyield.end();
                      ++iti )
                 {
                     jDebugTaggedLine( "         adding fp=" << iti->first );
                     channel->add_transition( iti->first );
                 }
             }
         }
     }
     // allows us to avoid this update if extending by mixture
     if( add_byproducts_and_relink )
     {
         ts->populate_gains();
     }
 }
float update (TransitionSystem * ts, const Vec_Flt & flux) const virtual
Update a transition system with a new flux (STL format) using the internal multi-group database.
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References ChannelType::channel_id(), TransitionSystemAdapter_AmpxN::d_reaction_resource, TransitionSystem::field(), TransitionSystem::nuclide(), and auxiliary::nuclide().
Referenced by Origen::test::TEST(), TEST_F(), TransitionSystemAdapter_AmpxN::update(), TransitionSystemAdapter_AmpxN::update_by_mix(), and TransitionMatrixUpdater::update_mg_flux().
 {
     jDebugLine( "entering TransitionSystemAdapter_AmpxN::update" );
     SCOPED_TIMER( "TransitionSystemAdapter_AmpxN.update" );
     Require( d_reaction_resource != nullptr );
     Require( d_reaction_resource->has_storage_bounds() );
     int field_id = d_reaction_resource->field_id();
     float sumflux =
         std::accumulate( flux.begin(), flux.end(), static_cast<float>( 0 ) );
     Check( sumflux >= 0.0 );
     SP_Field neutron_field = ts->field( field_id );
     Check( neutron_field != nullptr );
     neutron_field->set_intensity( 1.0 );
     jDebugTaggedLine( "sumflux=" << sumflux );
     if( sumflux == 0.0 ) return sumflux;
     // iterators used below
     ReactionResource::const_iterator it1, it1e;
     ReactionResource::Nuclide::const_iterator it2, it2e;
     // variables used below
     float sig = 0.0;
     Vec_Int yield_ids;
     yield_ids.reserve( 2000 );  // lots of space
     Vec_Flt yield_vals;
     yield_vals.reserve( 2000 );
     std::vector<Transition::SP> transitions;
     jDebugTaggedLine( "update: entering loop..." );
     it1e = d_reaction_resource->end();
     for( it1 = d_reaction_resource->begin(); it1 != it1e; ++it1 )
     {
         int izzzaaa = it1->first;
         jDebugTaggedLine( "update: izzzaaa=" << izzzaaa );
         // uses internal map (change to hashtable?)
         auto nuclide = ts->nuclide( izzzaaa );
         if( nuclide == nullptr )
         {
             jDebugTaggedLine( "update: skipping parent nuclide=" << izzzaaa );
             continue;
         }
         const ReactionResource::Nuclide& a_nd = it1->second;
         it2e = a_nd.end();
         for( it2 = a_nd.begin(); it2 != it2e; ++it2 )
         {
             int mt = it2->first;
             jDebugTaggedLine( "update: mt=" << mt );
             // uses internal map (change to hashtable?)
             int channel_id = ChannelType::channel_id( neutron_field, mt );
             auto channel = nuclide->loss( channel_id );
             if( channel == nullptr )
             {
                 jDebugTaggedLine(
                     "update: skipping channel for nuclide=" << izzzaaa << " mt="
                                                             << mt );
                 continue;
             }
             const ReactionResource::Nuclide::Xs& a_xs = it2->second;
             a_xs.evaluate( d_reaction_resource->storage_bounds(),
                            flux,
                            sumflux,
                            &sig,
                            &yield_ids,
                            &yield_vals );
             channel->set_xs( sig );
             // todo: get eavg from evaluate call above---only tricky part is how
             // not to incur extra cost sometimes when speed is most important--
             // currently only need to calculate average energy for fission xs
             // channel->set_average_energy(eavg);
             channel->get_transitions( transitions );
             // If there is only one transition, but multiple yield_vals,
             // set to 10.0 (convert all yields to -> ground state) just
             if (transitions.size() == 1 &&
                 transitions.size() < yield_ids.size())
             {
                 yield_vals[0] = 1.0;
             }
             if (channel->id() == 18) // Fission, do lookup to ignore neutron
                 for (const auto & t : transitions) // vector of SP_Transition
                 {
                     auto itr = std::find(yield_ids.cbegin(), yield_ids.cend(),
                                          t->product()->id());
                     auto loc = itr - yield_ids.cbegin();
                     t->set_yield(yield_vals[loc]);
                 }
             else // Not fission, just go through array.
             {
                 for( size_t i = 0; i < transitions.size(); ++i )
                 {
                     transitions[i]->set_yield( yield_vals[i] );
                 }
             }
         }
     }
     return sumflux;
 }
float update (TransitionSystem * ts, const CrossSection1d * flux) const virtual
Update a transition system with a new flux (AMPX format) using the internal multi-group database.
References Origen::populateVec_CrossSection1d(), and TransitionSystemAdapter_AmpxN::update().
 {
     Vec_Flt flux;
     populateVec_CrossSection1d( &flux, *flux_ptr );
     return this->update( ts, flux );
 }
void extend_by_mix (TransitionSystem * ts, const AmpxLibrary & main, int mix_id = -1, bool extend_internal = false, bool skip_not_present = false) const virtual
Extend a transition system (i.e. create new nuclides/reactions) from an AMPX library for a specific or all mixtures.
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionSystem::add_nuclide(), TransitionSystemAdapter_AmpxN::d_nuclide_translation, TransitionSystemAdapter_AmpxN::d_reaction_resource, TransitionSystemAdapter_AmpxN::extend(), auxiliary::nuclide(), and TransitionSystem::populate_gains().
Referenced by Origen::test::TEST().
 {
     Require( d_reaction_resource != nullptr );
     int field_id = d_reaction_resource->field_id();
     const auto& direct_yields = d_reaction_resource->direct_yields();
     // extend with internal data first
     if( extend_internal )
     {
         bool add_byproducts_and_relink = false;
         this->extend( ts, add_byproducts_and_relink );
     }
     // iterators used below
     std::map<int, ReactionResource::Nuclide>::const_iterator it1;
     std::map<int, ReactionResource::Nuclide::Xs>::const_iterator it2;
     // variables used below
     int initial_isomeric_state, final_isomeric_state;
     bool partial;
     // loop over passed in data--we will use maps to get the
     // supplemental data
     int num_ampx_nuclides = lib.getNumberNuclides();
     for( int j = 0; j < num_ampx_nuclides; j++ )
     {
         LibraryNuclide* ampx_nuclide = lib.getNuclideAt( j );
         if( mix_id > -1 && ampx_nuclide->getMixture() != mix_id ) continue;
         int id = ampx_nuclide->getId();
         NuclideTranslation_t::const_iterator it =
             d_nuclide_translation.find( id );
         int izzzaaa = id;
         if( it != d_nuclide_translation.end() )
         {
             jDebugTaggedLine(
                 "extend_by_mix: translated AMPX id=" << id << " to izzzaaa="
                                                      << it->second );
             izzzaaa = it->second;
             // should verify is izzzaaa here
         }
         jDebugTaggedLine(
             "extend_by_mix: id=" << id << " (translated izzzaaa=" << izzzaaa );
         auto nuclide = ts->add_nuclide( izzzaaa );
         if (skip_not_present)  // Does this make sense, above ADDS nuclide!
         {
             if (! nuclide)
             {
                 continue;
             }
         }
         int num_1dxs = ampx_nuclide->getNumNeutron1dData();
         for( int k = 0; k < num_1dxs; k++ )
         {
             CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
             int mt = xs->getMt();
             jDebugTaggedLine( "extend_by_mix: mt=" << mt );
             // check for direct yields (e.g. nubar=452)
             auto itd = direct_yields.find( mt );
             if( itd != direct_yields.end() )
             {
                 // evaluate target_mt (e.g. fission=18)
                 int target_mt = itd->second.first;
                 // evaluate target_izzzaaa (e.g. neutron=1)
                 int target_izzzaaa = itd->second.second;
                 if (target_izzzaaa == 1) continue;
                 // evaluate channel
                 auto channel = nuclide->add_loss( field_id, target_mt );
                 channel->add_transition( target_izzzaaa );
                 continue;
             }
             // deconstructs and modifies MT in place
             ScaleData::Utils::transform_mt(
                 mt, partial, final_isomeric_state, initial_isomeric_state );
             Check( !partial );  // partials not allowed in this extend
             // TODO: handle mt=51, 52, etc.
             // filter MTs user doesn't want
             const auto& allowed_mts = d_reaction_resource->allowed_mts();
             auto ita = allowed_mts.find( mt );
             if( ita == allowed_mts.end() || !ita->second )
             {
                 jDebugTaggedLine( "extend_by_mix: disallowing izzzaaa="
                                   << izzzaaa
                                   << " mt="
                                   << mt
                                   << " by established rule" );
                 continue;
             }
             auto channel = nuclide->add_loss( field_id, mt );
             // Handle MT=51 -> MT=5<max_isomeric_state> (on default RR = 1)
             if (mt >= 51 && mt <= 51 + d_reaction_resource->max_isomeric_state())
             {
                 channel->add_transition(mt - 50, 1.0); // Add yield as 100%
             }
             else  // Add a transition with 100% yield to ground state if
                   // transitions don't exist.
             {
                 if (channel->num_transitions() == 0 &&
                     ! channel->channel_type()->has_distribution_of_daughters())
                 {
                     channel->add_transition(0, 1.0);
                 }
             }
         }
     }
     ts->populate_gains();
 }
float update_by_mix (TransitionSystem * ts, const AmpxLibrary & lib, int mix_id, int flux_nuclide_id = -1, int flux_mt = 1099) const virtual
Update a transition system with mixture-specific xs data and multi-group flux both from an AMPX library.
A search is performed to find all nuclides with a specific mixture id. A nuclide id translation layer is provided to interpret an AMPX id as a specific IZZZAAA id (set_nuclide_translation).
The cross sections for these nuclides are then iterated through, and if the mt is acceptable, it is collapsed to 1-group with the provided flux and set on the TransitionSystem.
The provided flux is found on a specified nuclide and specified id. -1.0 will be returned if the flux cannot be found. Otherwise the total flux (sum over all groups) will be returned. This is useful for having a single parameter to check that an update has occurred.
See also
set_nuclide_translation
Parameters
mix_id - mixture id
flux_nuclide_id - nuclide id where the flux can be found
flux_mt - reaction mt id on the flux nuclide which contains the MG flux
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References Origen::populateFlux_AmpxLibrary().
Referenced by Origen::test::TEST(), and TransitionMatrixUpdater::update_by_mix().
 {
     Vec_Flt flux;
     populateFlux_AmpxLibrary( &flux, lib, mix_id, flux_nuclide_id, flux_mt );
     // this means we did not find the flux
     if( flux.size() == 0 ) return -1;
     return update_by_mix( ts, lib, mix_id, flux );
 }
float update_by_mix (TransitionSystem * ts, const AmpxLibrary & main, int mix_id, const Vec_Flt & flux) const virtual
Update a transition system with mixture-specific xs data from an AMPX library but use a given multi-group flux vector.
References TransitionSystem::channel_type(), Origen::collect_direct_yields(), TransitionSystemAdapter_AmpxN::d_nuclide_translation, TransitionSystemAdapter_AmpxN::d_reaction_resource, TransitionSystem::field(), TransitionSystem::nuclide(), auxiliary::nuclide(), and TransitionSystemAdapter_AmpxN::update().
 {
     Require( d_reaction_resource != nullptr );
     int field_id = d_reaction_resource->field_id();
     const auto& direct_yields = d_reaction_resource->direct_yields();
     const auto& allowed_mts = d_reaction_resource->allowed_mts();
     // perform update using internal xs data
     float sumflux = update( ts, flux );  // ts,sumflux changed on return
     if( sumflux <= 0.0 ) return sumflux;
     auto neutron_field = ts->field( field_id );
     Check( neutron_field );
     // variables used below
     float yield, sig;
     int initial_isomeric_state, final_isomeric_state;
     bool partial;
     SCOPED_TIMER( "TransitionSystemAdapter_AmpxN.update_by_mix" );
     // loop over passed in data--we will use maps to get the
     // supplemental data
     int num_ampx_nuclides = lib.getNumberNuclides();
     jDebugTaggedLine(
         "update_by_mix: num_ampx_nuclides=" << num_ampx_nuclides );
     for( int j = 0; j < num_ampx_nuclides; j++ )
     {
         LibraryNuclide* ampx_nuclide = lib.getNuclideAt( j );
         if( ampx_nuclide->getMixture() != mix_id )
         {
             jDebugTaggedLine( "update_by_mix: skipping nuclide id="
                               << ampx_nuclide->getId()
                               << " with mixture="
                               << ampx_nuclide->getMixture()
                               << " because it doesn't match user mix_id="
                               << mix_id );
             continue;
         }
         int id = ampx_nuclide->getId();
         auto it = d_nuclide_translation.find( id );
         int izzzaaa = id;
         if( it != d_nuclide_translation.end() )
         {
             jDebugTaggedLine(
                 "update_by_mix: translated AMPX id=" << id << " to izzzaaa="
                                                      << it->second );
             izzzaaa = it->second;
             // should verify is izzzaaa here
         }
         jDebugTaggedLine(
             "update_by_mix: id=" << id << " translated izzzaaa=" << izzzaaa );
         auto nuclide = ts->nuclide( izzzaaa );
         if( nuclide == nullptr )
         {
             jDebugTaggedLine( "update_by_mix: skipping nuclide id="
                               << id
                               << " (izzzaaa="
                               << izzzaaa
                               << ") because it does not exist in the system" );
             continue;
         }
         // loop through first time and collect any direct yields
         auto yield_map = collect_direct_yields(
             neutron_field, nuclide, izzzaaa, ts, ampx_nuclide, direct_yields );
         // loop through now and collect cross sections
         int num_1dxs = ampx_nuclide->getNumNeutron1dData();
         for( int k = 0; k < num_1dxs; k++ )
         {
             CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
             int mt = xs->getMt();
             jDebugTaggedLine( "update_by_mix: mt=" << mt );
             // deconstructs and modifies MT in place
             ScaleData::Utils::transform_mt(
                 mt, partial, final_isomeric_state, initial_isomeric_state );
             Check( !partial );  // partials not allowed in this update
             // TODO: handle mt=51, 52, etc.
             // filter MTs user doesn't want
             auto ita = allowed_mts.find( mt );
             if( ita == allowed_mts.end() || !ita->second )
             {
                 jDebugTaggedLine( "update_by_mix: disallowing izzzaaa="
                                   << izzzaaa
                                   << " mt="
                                   << mt
                                   << " by established rule" );
                 continue;
             }
             auto channeltype = ts->channel_type( neutron_field, mt );
             if( channeltype == nullptr )
             {
                 jDebugTaggedLine(
                     "update_by_mix: skipping unknown channeltype with mt="
                     << mt );
                 continue;
             }
             auto channel = nuclide->loss( channeltype->id() );
             if( channel == nullptr )
             {
                 jDebugTaggedLine( "update_by_mix: skipping channel for nuclide="
                                   << izzzaaa
                                   << " mt="
                                   << mt );
                 continue;
             }
             // set new channel cross section
             sig = 0;
             for( size_t g = 0; g < flux.size(); ++g )
             {
                 sig += flux[g] * xs->getValues()[g];
             }
             sig /= sumflux;
             jDebugTaggedLine( "update_by_mix: updating channel xs for nuclide="
                               << izzzaaa
                               << " mt="
                               << mt
                               << " xs="
                               << sig );
             channel->set_xs( sig );
             // set new channel yield
             auto direct = yield_map.find( mt );
             if( direct != yield_map.end() )
             {
                 auto nu = direct->second.first;
                 auto transition = direct->second.second;
                 float yield = 0;
                 // NOTE: The treatment of nubar below does not allow us to
                 // use the Aux library (JEFF) nubar with AMPX fission xs.
                 // It is complicated because the JEFF nubar and fisxs could
                 // be stored in a different group structure.
                 for( size_t g = 0; g < flux.size(); ++g )
                 {
                     yield += nu->getValues()[g] * flux[g] * xs->getValues()[g];
                 }
                 yield /= ( sumflux * sig );
                 jDebugTaggedLine(
                     "update_by_mix: updating transition yield xs for nuclide="
                     << izzzaaa
                     << " mt="
                     << mt
                     << " yield="
                     << yield );
                 transition->set_yield( yield );
             }
         }
         jDebugTaggedLine(
             "update_by_mix: finished nuclide izzzaaa=" << izzzaaa );
     }
     return sumflux;
 }
SCP_ReactionResource reaction_resource () const
return shared (read-only) reaction_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
Referenced by TransitionMatrixUpdater::mg_database().
bool has_reaction_resource () const
whether this instantiation of class has the reaction_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Referenced by TransitionMatrixUpdater::mg_database().
void set_reaction_resource (SCP_ReactionResource reaction_resource)
set a new shared (read-only) reaction_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TransitionMatrixUpdater::load(), Origen::test::TEST(), and TEST_F().
void print (const AmpxLibrary & main, std::ostream & os = std::cout)
Print the AMPX library contents this class cares about.
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionSystemAdapter_AmpxN::d_nuclide_translation.
Referenced by Origen::test::TEST().
 {
     int num_ampx_nuclides = lib.getNumberNuclides();
     for( int j = 0; j < num_ampx_nuclides; j++ )
     {
         LibraryNuclide* ampx_nuclide = lib.getNuclideAt( j );
         int mix_id = ampx_nuclide->getMixture();
         int id = ampx_nuclide->getId();
         NuclideTranslation_t::const_iterator it =
             d_nuclide_translation.find( id );
         int izzzaaa = id;
         if( it != d_nuclide_translation.end() )
         {
             izzzaaa = it->second;
         }
         int num_1dxs = ampx_nuclide->getNumNeutron1dData();
         os << mix_id << " " << id << " (" << izzzaaa << ") " << num_1dxs;
         for( int k = 0; k < num_1dxs; k++ )
         {
             CrossSection1d* xs = ampx_nuclide->getNeutron1dDataAt( k );
             int mt = xs->getMt();
             os << " " << mt;
         }
         os << std::endl;
     }
 }
Member Data Documentation
NuclideTranslation_t d_nuclide_translation protected
Map an AMPX nuclide id to an IZZZAAA.
Referenced by TransitionSystemAdapter_AmpxN::extend_by_mix(), TransitionSystemAdapter_AmpxN::get_nuclide_translation(), TransitionSystemAdapter_AmpxN::nuclide_translation(), TransitionSystemAdapter_AmpxN::print(), and TransitionSystemAdapter_AmpxN::update_by_mix().
SCP_ReactionResource d_reaction_resource protected
Referenced by TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), TransitionSystemAdapter_AmpxN::update(), and TransitionSystemAdapter_AmpxN::update_by_mix().
The documentation for this class was generated from the following files:
Manager/libld/TransitionSystemAdapter_AmpxN.h
Manager/libld/TransitionSystemAdapter_AmpxN.cpp