OrigenAPI: STab1WriterTester Class Reference
STab1WriterTester Class Reference
Public Member Functions
std::string write (std::ostream &os)
write it
Static Public Member Functions
static std::string as_string (double value)
Public Attributes
SP_STab1 stab1
data that was write in
Static Protected Member Functions
static void setRealValue (std::string *line, double value, int index)
set the index of 6 values as a double on line
static void setIntValue (std::string *line, int value, int index)
set the index of 6 values as an integer on line
static void setLineValues_2Real_4Int (std::string *line, double f1, double f2, int i1, int i2, int i3, int i4)
set 2 floats and 4 ints a line
static void setLineValues_6Real (std::string *line, double f1, double f2, double f3, double f4, double f5, double f6)
set 6 floats on a line
static void writeTerminatorLine (std::ostream &os)
write a terminator to a string
static std::string writeTitle (std::ostream &os, const std::string &title)
write the one line title
static std::string writeData (std::ostream &os, const STab1::Data &data)
write a data set
static std::string writeBlock (std::ostream &os, const STab1::Block &block)
write a data block (contains 1 or more data sets)
static std::string writeFile (std::ostream &os, const STab1 &stab1)
write the simplified tab1 data
Detailed Description
Definition at line 25 of file tstYieldResourceIO.cpp.
Member Function Documentation
static std::string STab1WriterTester::as_string (double value) inline static
Definition at line 28 of file tstYieldResourceIO.cpp.
     {
         std::string line;
         STab1Writer::setRealValue( &line, value, 1 );
         line.resize( 11 );
         return line;
     }
void Origen::STab1Writer::setIntValue (std::string * line, int value, int index) static protected inherited
set the index of 6 values as an integer on line
Definition at line 29 of file STab1Writer.cpp.
References Origen::STab1::ENDF_FIELD_LENGTH.
Referenced by Origen::STab1Writer::setLineValues_2Real_4Int().
 {
     Require( line != nullptr );
     line->resize( 6 * STab1::ENDF_FIELD_LENGTH );
     int start = ( index - 1 ) * STab1::ENDF_FIELD_LENGTH;
     // int end = start+STab1::ENDF_FIELD_LENGTH;
     char buffer[12];
     endfendf::Record::setIntValue( buffer, value, 11 );
     // comes back as blanks when value is zero
     if( value == 0 )
     {
         buffer[10] = '0';
     }
     line->replace( start, STab1::ENDF_FIELD_LENGTH, buffer );
 }
void Origen::STab1Writer::setLineValues_2Real_4Int (std::string * line, double f1, double f2, int i1, int i2, int i3, int i4) static protected inherited
set 2 floats and 4 ints a line
Definition at line 45 of file STab1Writer.cpp.
References Origen::STab1Writer::setIntValue(), and Origen::STab1Writer::setRealValue().
Referenced by Origen::STab1Writer::writeTerminatorLine().
 {
     setRealValue( line, f1, 1 );
     setRealValue( line, f2, 2 );
     setIntValue( line, i1, 3 );
     setIntValue( line, i2, 4 );
     setIntValue( line, i3, 5 );
     setIntValue( line, i4, 6 );
 }
void Origen::STab1Writer::setLineValues_6Real (std::string * line, double f1, double f2, double f3, double f4, double f5, double f6) static protected inherited
set 6 floats on a line
Definition at line 56 of file STab1Writer.cpp.
References Origen::STab1Writer::setRealValue().
 {
     setRealValue( line, f1, 1 );
     setRealValue( line, f2, 2 );
     setRealValue( line, f3, 3 );
     setRealValue( line, f4, 4 );
     setRealValue( line, f5, 5 );
     setRealValue( line, f6, 6 );
 }
void Origen::STab1Writer::setRealValue (std::string * line, double value, int index) static protected inherited
set the index of 6 values as a double on line
Definition at line 17 of file STab1Writer.cpp.
References Origen::STab1::ENDF_FIELD_LENGTH.
Referenced by Origen::STab1Writer::setLineValues_2Real_4Int(), Origen::STab1Writer::setLineValues_6Real(), and Origen::STab1Writer::writeData().
 {
     Require( line != nullptr );
     line->resize( 6 * STab1::ENDF_FIELD_LENGTH );
     int start = ( index - 1 ) * STab1::ENDF_FIELD_LENGTH;
     // int end = start+STab1::ENDF_FIELD_LENGTH;
     char buffer[12];
     // double dvalue = value;
     endfendf::Record::setDoubleValue( buffer, value );
     line->replace( start, STab1::ENDF_FIELD_LENGTH, buffer );
 }
std::string Origen::STab1Writer::write (std::ostream & os) inherited
write it
Definition at line 8 of file STab1Writer.cpp.
References Origen::STab1Writer::stab1, and Origen::STab1Writer::writeFile().
Referenced by Origen::YieldResourceIO_stab1::write().
 {
     return writeFile( os, *( this->stab1 ) );
 }
std::string Origen::STab1Writer::writeBlock (std::ostream & os, const STab1::Block & block) static protected inherited
write a data block (contains 1 or more data sets)
Definition at line 108 of file STab1Writer.cpp.
References Origen::STab1::Block::cr, Origen::STab1::Block::set, Origen::STab1Writer::writeData(), and Origen::STab1Writer::writeTerminatorLine().
Referenced by Origen::STab1Writer::writeFile().
 {
     int status = block.cr.writeData( os );
     if( status != 0 )
     {
         return "problem writing Block header";
     }
     std::string error;
     for( size_t iset = 0; iset < block.set.size(); ++iset )
     {
         error = writeData( os, block.set[iset] );
         if( error != "" ) return error;
     }
     writeTerminatorLine( os );
     if( !os.good() ) return "premature end of file";
     return "";
 }
std::string Origen::STab1Writer::writeData (std::ostream & os, const STab1::Data & data) static protected inherited
write a data set
Definition at line 79 of file STab1Writer.cpp.
References Origen::STab1::Data::cr, Origen::STab1::Data::id, Origen::STab1Writer::setRealValue(), Origen::STab1::Data::val, and Origen::STab1Writer::writeTerminatorLine().
Referenced by Origen::STab1Writer::writeBlock().
 {
     int status = data.cr.writeData( os );
     if( status != 0 )
     {
         return "problem writing Data header";
     }
     int ipairs = 0;
     int npairs = data.id.size();
     while( ipairs < npairs )
     {
         std::string buffer;
         for( size_t j = 0; j < 3; j++ )
         {
             if( ipairs >= npairs ) break;
             int id1 = data.id[ipairs];
             double f1 = data.val[ipairs];
             setRealValue( &buffer, id1, 2 * j + 1 );
             setRealValue( &buffer, f1, 2 * j + 2 );
             ++ipairs;
         }
         os << buffer << std::endl;
     }
     writeTerminatorLine( os );
     return "";
 }
std::string Origen::STab1Writer::writeFile (std::ostream & os, const STab1 & stab1) static protected inherited
write the simplified tab1 data
Definition at line 138 of file STab1Writer.cpp.
References Origen::STab1::block, Origen::STab1::title, Origen::STab1Writer::writeBlock(), Origen::STab1Writer::writeTerminatorLine(), and Origen::STab1Writer::writeTitle().
Referenced by Origen::STab1Writer::write().
 {
     std::string error = writeTitle( os, stab1.title );
     if( error != "" )
     {
         return error;
     }
     for( size_t iblock = 0; iblock < stab1.block.size(); ++iblock )
     {
         error = writeBlock( os, stab1.block[iblock] );
         if( error != "" ) return error;
     }
     writeTerminatorLine( os );
     if( !os.good() ) return "premature end of file";
     return "";
 }
void Origen::STab1Writer::writeTerminatorLine (std::ostream & os) static protected inherited
write a terminator to a string
Definition at line 72 of file STab1Writer.cpp.
References kernel_rksuite::f(), and Origen::STab1Writer::setLineValues_2Real_4Int().
Referenced by Origen::STab1Writer::writeBlock(), Origen::STab1Writer::writeData(), and Origen::STab1Writer::writeFile().
 {
     std::string line;
     setLineValues_2Real_4Int( &line, 0.0f, 0.0f, 0, 0, 0, 0 );
     os << line << std::endl;
 }
std::string Origen::STab1Writer::writeTitle (std::ostream & os, const std::string & title) static protected inherited
write the one line title
Definition at line 130 of file STab1Writer.cpp.
Referenced by Origen::STab1Writer::writeFile().
 {
     if( !os.good() ) return "premature end of file";
     os << title << std::endl;
     return "";
 }
Member Data Documentation
SP_STab1 Origen::STab1Writer::stab1 inherited
data that was write in
Definition at line 17 of file STab1Writer.h.
Referenced by Origen::YieldResourceIO_stab1::write(), and Origen::STab1Writer::write().
The documentation for this class was generated from the following file:
Core/io/tests/tstYieldResourceIO.cpp