ORIGEN API: origen_librarywrapper_m Module Reference
origen_librarywrapper_m Module Reference
Provides everything you need to do with ORIGEN libraries from Fortran.
Data Types
type origen_librarywrapper
Functions/Subroutines
subroutine, public copyorigen_librarywrapper (from, to)
Copies the library.
Detailed Description
Provides everything you need to do with ORIGEN libraries from Fortran.
The Origen_LibraryWrapper, wraps the Origen_Library for the main purpose of providing accessors in native Fortran types, i.e. a Fortran allocatable array instead of a ScaleSTL_Vec.
Function/Subroutine Documentation
subroutine, public origen_librarywrapper_m::copyorigen_librarywrapper (type(origen_librarywrapper) from, type(origen_librarywrapper) to)
Copies the library.
locals
References auxiliary::nuclide(), auxiliary::print_dhrule(), auxiliary::print_hrule(), and auxiliary::table_tail().
Referenced by origen_librarywrapper::set_legacy_mass().
     !-----------------------------------------------
     !   M o d u l e s
     !-----------------------------------------------
     implicit none
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> to
     type(origen_librarywrapper) :: to
     !> from
     type(origen_librarywrapper) :: from
     !> locals
     type(origen_library) :: lib
     !start out clean
     call to % destroy()
     !make a copy of library
     call lib % initialize_copy( from % b_lib )
     !initialize and manage this new data
     call to % initialize_manageptr(lib)
     !set position properly
     call to % set_pos( from%get_pos() )