ORIGEN API: ReactionResource Class Reference
ReactionResource Class Reference
#include <ReactionResource.h>
Multi-group cross section/yields resource.
Public Types
typedef detail::RRNuclide< float > Nuclide
typedef std::map< int, bool > YieldNuclides_t
typedef std::map< int, bool > AllowedMts_t
typedef std::shared_ptr< ReactionResource > SP
typedef std::shared_ptr< const ReactionResource > SCP
typedef std::map< int, std::pair< int, int > > DirectYields_t
Public Member Functions
ReactionResource ()
ReactionResource (const Vec_Flt &storage_bounds)
virtual ~ReactionResource ()
virtual FieldId field_id () const
field id for this data set, e.g. NEUTRON_FIELD
virtual void print (std::ostream &os=std::cout) const
print contents
virtual void set_max_isomeric_state (int i)
set max isomeric state
virtual int max_isomeric_state () const
get max isomeric state
virtual void set_allowed_mts (const Vec_Int &allowed_mts, bool union_with=false)
set allowed mts
virtual void set_disallowed_mts (const Vec_Int &disallowed_mts, bool union_with=true)
set disallowed mts
virtual void get_allowed_mts (Vec_Int *allowed_mts) const
get allowed mts
virtual void get_disallowed_mts (Vec_Int *disallowed_mts) const
get disallowed mts
virtual const AllowedMts_t & allowed_mts () const
direct return of allowed mts
virtual void set_yield_nuclides (const Vec_Int &nuclides, bool union_with=false)
set nuclides with allowed fission yields (used only in import)
virtual void get_yield_nuclides (Vec_Int *nuclides) const
get nuclides with allowed fission yields (used only in import)
virtual const YieldNuclides_t & yield_nuclides () const
direct return of allowed fission yields (used only in import)
virtual const DirectYields_t & direct_yields () const
direct yields
virtual void set_direct_yields (int mt, int target_mt, int izzzaaa)
set new direct yields
virtual void delete_direct_yields (int mt)
remove direct yields
void import_fission_yields (const YieldResource &yr)
const Vec_Flt & storage_bounds () const
return a const reference to storage_bounds
float storage_bounds_at (size_t) const
get element of storage_bounds vector by index
SCP_Vec_Flt scp_storage_bounds () const
return a shared (read-only) storage_bounds pointer
float const * storage_bounds_array () const
return view of storage_bounds vector
size_t storage_bounds_size () const
return size of storage_bounds vector
bool has_storage_bounds () const
return whether the class has a non-null storage_bounds
void set_storage_bounds (const Vec_Flt &)
set the storage_bounds (copy operation)
void get_storage_bounds (Vec_Flt &) const
populate an existing Vec_Flt with a copy of storage_bounds
void manageptr_storage_bounds (Vec_Flt *&)
set the storage_bounds (ownership transfer)
void getptr_storage_bounds (Vec_Flt const *&) const
retrieve pointer (read-only) to storage_bounds
void get_storage_bounds_array (size_t, float *) const
get array of storage_bounds vector (Fortran)
void set_storage_bounds_array (size_t, float *)
set storage_bounds vector from array (Fortran)
const Vec_Flt & storage_flux () const
return a const reference to storage_flux
float storage_flux_at (size_t) const
get element of storage_flux vector by index
SCP_Vec_Flt scp_storage_flux () const
return a shared (read-only) storage_flux pointer
float const * storage_flux_array () const
return view of storage_flux vector
size_t storage_flux_size () const
return size of storage_flux vector
bool has_storage_flux () const
return whether the class has a non-null storage_flux
void get_storage_flux (Vec_Flt &) const
populate an existing Vec_Flt with a copy of storage_flux
void getptr_storage_flux (Vec_Flt const *&) const
retrieve pointer (read-only) to storage_flux
void get_storage_flux_array (size_t, float *) const
get array of storage_flux vector (Fortran)
const Vec_Flt & library_bounds () const
return a const reference to library_bounds
float library_bounds_at (size_t) const
get element of library_bounds vector by index
SCP_Vec_Flt scp_library_bounds () const
return a shared (read-only) library_bounds pointer
float const * library_bounds_array () const
return view of library_bounds vector
size_t library_bounds_size () const
return size of library_bounds vector
bool has_library_bounds () const
return whether the class has a non-null library_bounds
void set_library_bounds (const Vec_Flt &)
set the library_bounds (copy operation)
void get_library_bounds (Vec_Flt &) const
populate an existing Vec_Flt with a copy of library_bounds
void manageptr_library_bounds (Vec_Flt *&)
set the library_bounds (ownership transfer)
void getptr_library_bounds (Vec_Flt const *&) const
retrieve pointer (read-only) to library_bounds
void get_library_bounds_array (size_t, float *) const
get array of library_bounds vector (Fortran)
void set_library_bounds_array (size_t, float *)
set library_bounds vector from array (Fortran)
const Vec_Flt & library_flux () const
return a const reference to library_flux
float library_flux_at (size_t) const
get element of library_flux vector by index
SCP_Vec_Flt scp_library_flux () const
return a shared (read-only) library_flux pointer
float const * library_flux_array () const
return view of library_flux vector
size_t library_flux_size () const
return size of library_flux vector
bool has_library_flux () const
return whether the class has a non-null library_flux
void set_library_flux (const Vec_Flt &)
set the library_flux (copy operation)
void get_library_flux (Vec_Flt &) const
populate an existing Vec_Flt with a copy of library_flux
void manageptr_library_flux (Vec_Flt *&)
set the library_flux (ownership transfer)
void getptr_library_flux (Vec_Flt const *&) const
retrieve pointer (read-only) to library_flux
void get_library_flux_array (size_t, float *) const
get array of library_flux vector (Fortran)
void set_library_flux_array (size_t, float *)
set library_flux vector from array (Fortran)
void map_xs (Vec_Flt *xs) const
void map_flux (Vec_Flt *flux) const
bool using_data_mapper () const
Public Attributes
K keys
STL member.
T elements
STL member.
Protected Member Functions
void set_storage_flux (const Vec_Flt &)
set the storage_flux (copy operation)
void manageptr_storage_flux (Vec_Flt *&)
set the storage_flux (ownership transfer)
void set_storage_flux_array (size_t, float *)
set storage_flux vector from array (Fortran)
void canonicalize_storage_bounds ()
void canonicalize_storage_flux ()
void canonicalize_library_bounds ()
void canonicalize_library_flux ()
Static Protected Member Functions
static void default_allowed_mts (AllowedMts_t &allowed_mts)
static void default_isomeric_states (int max_isomeric_state, AllowedMts_t &allowed_mts)
static void default_direct_yields (DirectYields_t &direct_yields)
Protected Attributes
SP_Vec_Flt d_storage_bounds
int d_max_isomeric_state
bool d_using_data_mapper
SP_Vec_Flt d_storage_flux
SP_Vec_Flt d_library_flux
SP_Vec_Flt d_library_bounds
ScaleData::MGXS1DMapper< float > d_data_mapper
YieldNuclides_t d_yield_nuclides
AllowedMts_t d_allowed_mts
DirectYields_t d_direct_yields
Detailed Description
Multi-group cross section/yields resource.
ReactionResource uses is a simple map of nuclide ids to ReactionResource::Nuclide, a sub-class used to manage ReactionResource::Nuclide::Xs, multi-group cross section and yields data.
See also
ReactionResource::Nuclide, ReactionResource::Nuclide::Xs
Member Typedef Documentation
typedef detail::RRNuclide<float> Nuclide
typedef std::map<int, bool> YieldNuclides_t
typedef std::map<int, bool> AllowedMts_t
typedef std::shared_ptr<ReactionResource> SP
typedef std::shared_ptr<const ReactionResource> SCP
typedef std::map<int, std::pair<int, int> > DirectYields_t
Constructor & Destructor Documentation
ReactionResource ()
References ReactionResource::d_allowed_mts, ReactionResource::d_direct_yields, ReactionResource::d_max_isomeric_state, ReactionResource::default_allowed_mts(), ReactionResource::default_direct_yields(), and ReactionResource::default_isomeric_states().
ReactionResource (const Vec_Flt & storage_bounds)
References ReactionResource::d_allowed_mts, ReactionResource::d_direct_yields, ReactionResource::d_max_isomeric_state, ReactionResource::default_allowed_mts(), ReactionResource::default_direct_yields(), ReactionResource::default_isomeric_states(), and ReactionResource::set_storage_bounds().
virtual ~ReactionResource () inline virtual
Member Function Documentation
FieldId field_id () const virtual
field id for this data set, e.g. NEUTRON_FIELD
References Origen::NEUTRON_FIELD.
void print (std::ostream & os = std::cout) const virtual
print contents
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References Origen::yield_type_name().
Referenced by Origen::test::TEST().
void set_max_isomeric_state (int i) virtual
set max isomeric state
References ReactionResource::d_max_isomeric_state.
int max_isomeric_state () const virtual
get max isomeric state
References ReactionResource::d_max_isomeric_state.
Referenced by ReactionResource::default_isomeric_states(), and Origen::populateReactionResource_AmpxLibrary().
void set_allowed_mts (const Vec_Int & allowed_mts, bool union_with = false) virtual
set allowed mts
References ReactionResource::d_allowed_mts.
void set_disallowed_mts (const Vec_Int & disallowed_mts, bool union_with = true) virtual
set disallowed mts
References ReactionResource::d_allowed_mts.
Referenced by Origen::populateReactionResource_AmpxLibrary().
void get_allowed_mts (Vec_Int * allowed_mts) const virtual
get allowed mts
References ReactionResource::d_allowed_mts.
void get_disallowed_mts (Vec_Int * disallowed_mts) const virtual
get disallowed mts
References ReactionResource::d_allowed_mts.
const ReactionResource::AllowedMts_t & allowed_mts () const virtual
direct return of allowed mts
References ReactionResource::d_allowed_mts.
Referenced by Origen::populateReactionResource_AmpxLibrary().
void set_yield_nuclides (const Vec_Int & nuclides, bool union_with = false) virtual
set nuclides with allowed fission yields (used only in import)
References ReactionResource::d_yield_nuclides.
void get_yield_nuclides (Vec_Int * nuclides) const virtual
get nuclides with allowed fission yields (used only in import)
References ReactionResource::d_yield_nuclides.
const ReactionResource::YieldNuclides_t & yield_nuclides () const virtual
direct return of allowed fission yields (used only in import)
References ReactionResource::d_yield_nuclides.
const ReactionResource::DirectYields_t & direct_yields () const virtual
direct yields
References ReactionResource::d_direct_yields.
Referenced by Origen::populateReactionResource_AmpxLibrary().
void set_direct_yields (int mt, int target_mt, int izzzaaa) virtual
set new direct yields
References ReactionResource::d_direct_yields.
void delete_direct_yields (int mt) virtual
remove direct yields
References ReactionResource::d_direct_yields.
void import_fission_yields (const YieldResource & yr)
References ReactionResource::d_yield_nuclides, YieldParent::data_at(), YieldData::energy(), YieldResource::fissionable_at(), YieldParent::get_fp_ids(), YieldParent::id(), YieldParent::num_energies(), YieldResource::num_fissionables(), YieldData::num_yields(), YieldData::yield_at(), Origen::YIELD_DISTRIBUTED, and Origen::YIELD_ISOMERIC.
const Vec_Flt & storage_bounds () const
return a const reference to storage_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of ReactionResource goes out of scope.
Referenced by TransitionMatrixUpdater::num_energy_groups(), and TransitionMatrixUpdater::storage_bounds().
Vec_Flt::value_type storage_bounds_at (size_t i) const
get element of storage_bounds vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_storage_bounds () const
return a shared (read-only) storage_bounds pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Flt::value_type const * storage_bounds_array () const
return view of storage_bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t storage_bounds_size () const
return size of storage_bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by ReactionResource::canonicalize_library_flux(), and ReactionResource::canonicalize_storage_flux().
bool has_storage_bounds () const
return whether the class has a non-null storage_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by ReactionResource::canonicalize_library_bounds(), and ReactionResource::canonicalize_storage_flux().
void set_storage_bounds (const Vec_Flt & storage_bounds)
set the storage_bounds (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by ReactionResource::ReactionResource().
void get_storage_bounds (Vec_Flt & storage_bounds) const
populate an existing Vec_Flt with a copy of storage_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_storage_bounds (Vec_Flt *& storage_bounds)
set the storage_bounds (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_storage_bounds (Vec_Flt const *& storage_bounds) const
retrieve pointer (read-only) to storage_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_storage_bounds_array (size_t , float *) const
get array of storage_bounds vector (Fortran)
void set_storage_bounds_array (size_t , float *)
set storage_bounds vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & storage_flux () const
return a const reference to storage_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of ReactionResource goes out of scope.
Referenced by ReactionResource::canonicalize_library_flux().
Vec_Flt::value_type storage_flux_at (size_t i) const
get element of storage_flux vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_storage_flux () const
return a shared (read-only) storage_flux pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Flt::value_type const * storage_flux_array () const
return view of storage_flux vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t storage_flux_size () const
return size of storage_flux vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
bool has_storage_flux () const
return whether the class has a non-null storage_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_storage_flux (Vec_Flt & storage_flux) const
populate an existing Vec_Flt with a copy of storage_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_storage_flux (Vec_Flt const *& storage_flux) const
retrieve pointer (read-only) to storage_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_storage_flux_array (size_t , float *) const
get array of storage_flux vector (Fortran)
const Vec_Flt & library_bounds () const
return a const reference to library_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of ReactionResource goes out of scope.
Vec_Flt::value_type library_bounds_at (size_t i) const
get element of library_bounds vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_library_bounds () const
return a shared (read-only) library_bounds pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Flt::value_type const * library_bounds_array () const
return view of library_bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t library_bounds_size () const
return size of library_bounds vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
Referenced by ReactionResource::canonicalize_library_bounds(), and ReactionResource::canonicalize_library_flux().
bool has_library_bounds () const
return whether the class has a non-null library_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by ReactionResource::canonicalize_library_flux().
void set_library_bounds (const Vec_Flt & library_bounds)
set the library_bounds (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Origen::populateReactionResource_AmpxLibrary().
void get_library_bounds (Vec_Flt & library_bounds) const
populate an existing Vec_Flt with a copy of library_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_library_bounds (Vec_Flt *& library_bounds)
set the library_bounds (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_library_bounds (Vec_Flt const *& library_bounds) const
retrieve pointer (read-only) to library_bounds
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_library_bounds_array (size_t , float *) const
get array of library_bounds vector (Fortran)
void set_library_bounds_array (size_t , float *)
set library_bounds vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
const Vec_Flt & library_flux () const
return a const reference to library_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of ReactionResource goes out of scope.
Vec_Flt::value_type library_flux_at (size_t i) const
get element of library_flux vector by index
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
SCP_Vec_Flt scp_library_flux () const
return a shared (read-only) library_flux pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Vec_Flt::value_type const * library_flux_array () const
return view of library_flux vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
size_t library_flux_size () const
return size of library_flux vector
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
bool has_library_flux () const
return whether the class has a non-null library_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_library_flux (const Vec_Flt & library_flux)
set the library_flux (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Origen::populateReactionResource_AmpxLibrary().
void get_library_flux (Vec_Flt & library_flux) const
populate an existing Vec_Flt with a copy of library_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_library_flux (Vec_Flt *& library_flux)
set the library_flux (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void getptr_library_flux (Vec_Flt const *& library_flux) const
retrieve pointer (read-only) to library_flux
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void get_library_flux_array (size_t , float *) const
get array of library_flux vector (Fortran)
void set_library_flux_array (size_t , float *)
set library_flux vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
void map_xs (Vec_Flt * xs) const
References ReactionResource::d_data_mapper, ReactionResource::d_storage_bounds, and ReactionResource::d_using_data_mapper.
Referenced by Origen::populateReactionResource_AmpxLibrary().
void map_flux (Vec_Flt * flux) const
References ReactionResource::d_data_mapper, ReactionResource::d_storage_bounds, and ReactionResource::d_using_data_mapper.
bool using_data_mapper () const
References ReactionResource::d_using_data_mapper.
void default_allowed_mts (AllowedMts_t & allowed_mts) static protected
Referenced by ReactionResource::ReactionResource().
void default_isomeric_states (int max_isomeric_state, AllowedMts_t & allowed_mts) static protected
References ReactionResource::max_isomeric_state().
Referenced by ReactionResource::ReactionResource().
void default_direct_yields (DirectYields_t & direct_yields) static protected
Referenced by ReactionResource::ReactionResource().
void set_storage_flux (const Vec_Flt & storage_flux) protected
set the storage_flux (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by ReactionResource::canonicalize_library_flux().
void manageptr_storage_flux (Vec_Flt *& storage_flux) protected
set the storage_flux (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_storage_flux_array (size_t , float *) protected
set storage_flux vector from array (Fortran)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_VECTOR().
void canonicalize_storage_bounds () protected
void canonicalize_storage_flux () protected
References ReactionResource::d_storage_flux, ReactionResource::has_storage_bounds(), and ReactionResource::storage_bounds_size().
void canonicalize_library_bounds () protected
References ReactionResource::d_library_bounds, ReactionResource::d_storage_bounds, ReactionResource::d_using_data_mapper, ReactionResource::has_storage_bounds(), and ReactionResource::library_bounds_size().
void canonicalize_library_flux () protected
References ReactionResource::d_data_mapper, ReactionResource::d_library_bounds, ReactionResource::d_library_flux, ReactionResource::d_storage_bounds, ReactionResource::d_storage_flux, ReactionResource::d_using_data_mapper, ReactionResource::has_library_bounds(), ReactionResource::library_bounds_size(), ReactionResource::set_storage_flux(), ReactionResource::storage_bounds_size(), and ReactionResource::storage_flux().
Member Data Documentation
SP_Vec_Flt d_storage_bounds protected
Referenced by ReactionResource::canonicalize_library_bounds(), ReactionResource::canonicalize_library_flux(), ReactionResource::map_flux(), and ReactionResource::map_xs().
int d_max_isomeric_state protected
Referenced by ReactionResource::max_isomeric_state(), ReactionResource::ReactionResource(), and ReactionResource::set_max_isomeric_state().
bool d_using_data_mapper protected
Referenced by ReactionResource::canonicalize_library_bounds(), ReactionResource::canonicalize_library_flux(), ReactionResource::map_flux(), ReactionResource::map_xs(), and ReactionResource::using_data_mapper().
SP_Vec_Flt d_storage_flux protected
Referenced by ReactionResource::canonicalize_library_flux(), and ReactionResource::canonicalize_storage_flux().
SP_Vec_Flt d_library_flux protected
Referenced by ReactionResource::canonicalize_library_flux().
SP_Vec_Flt d_library_bounds protected
Referenced by ReactionResource::canonicalize_library_bounds(), and ReactionResource::canonicalize_library_flux().
ScaleData::MGXS1DMapper<float> d_data_mapper protected
Referenced by ReactionResource::canonicalize_library_flux(), ReactionResource::map_flux(), and ReactionResource::map_xs().
YieldNuclides_t d_yield_nuclides protected
Referenced by ReactionResource::get_yield_nuclides(), ReactionResource::import_fission_yields(), ReactionResource::set_yield_nuclides(), and ReactionResource::yield_nuclides().
AllowedMts_t d_allowed_mts protected
Referenced by ReactionResource::allowed_mts(), ReactionResource::get_allowed_mts(), ReactionResource::get_disallowed_mts(), ReactionResource::ReactionResource(), ReactionResource::set_allowed_mts(), and ReactionResource::set_disallowed_mts().
DirectYields_t d_direct_yields protected
Referenced by ReactionResource::delete_direct_yields(), ReactionResource::direct_yields(), ReactionResource::ReactionResource(), and ReactionResource::set_direct_yields().
K keys inherited
STL member.
T elements inherited
STL member.
The documentation for this class was generated from the following files:
Core/re/ReactionResource.h
Core/re/ReactionResource.cpp