ORIGEN API: TransitionMatrixP Class Reference
TransitionMatrixP Class Reference
#include <TransitionMatrixP.h>
Public Types
typedef std::shared_ptr< TransitionMatrixP > SP
typedef std::shared_ptr< const TransitionMatrixP > SCP
Public Member Functions
TransitionMatrixP ()
Default constructor.
TransitionMatrixP & operator= (const TransitionMatrixP &other)
Assignment operator.
~TransitionMatrixP ()
Destructor.
void finish_init ()
Wrap-up initialization - called by TransitionMatrixPWrapper.
void build_coo_matrix (double flux, IntegerList &ia, IntegerList &ja, DoubleList &a_in)
Build the full transition matrix (A+D) in the COO compressed format.
void build_full_matrix (double flux, Double2dList &matrix)
Build the full transition matrix (A+D) as an uncompressed 2D array.
void expand_matrix_pointers ()
void check_library ()
Run library consistency check.
bool check (std::vector< std::string > &errors)
void print_transitions_for (const int parent_id, const int mt_in)
Print list of transitions for a given reaction.
int find_nuclide_guess (const int id)
bool find_nuclide_all (Vec_Int *indices, const int id)
int find_nuclide (const int sublib, const int id)
void print_info ()
Print the library contents.
double get_xs (const int n, const int mt_in)
Get a cross-section from the library.
void set_xs (const int n, const int mt_in, const double new_xs)
Update a reaction cross-section in the library.
void perturb_xs (const int n, const int mt_in, const double factor)
Multiply a given cross-section in the library by a factor.
void collect_xs (const IntegerList nuclist, Integer2dList &xslist)
Get all reactions which involve a given set of nuclides.
void convert_abundances ()
Calculate wt% of natural abundances on library object (populate wabund)
void transpose_transition_matrix ()
Transpose compressed transition matrix A.
void cleanup_transitions_for_adjoint (DoubleList concentrations, DoubleList &adjoint_source_term_reaction, DoubleList &adjoint_source_term_decay)
void fold_flux (double flux, DoubleList &d, DoubleList &a_fold)
int first_transition (const int n, bool fortran_offset=false)
int last_transition (const int n, double flux=0.0)
int num_massive_daughters (const int mt_in)
bool has_valid_mts () const
Does this library have valid MTs?
bool is_mts_properly_ordered (const IntegerList &mts)
void find_all_mts (IntegerList &mts)
Find all MTs on the library.
void find_parents (const int nind, IntegerList &parents, IntegerList &mts, IntegerList &tinds)
void find_daughters (const int nind, IntegerList &daughters, IntegerList &mts, IntegerList &tinds)
void clear_tinds_2d (Integer2dList &tinds_2d)
Clear transition indices, e.g. created by setup_fast_transition_access.
void setup_fast_transition_access (const IntegerList &ninds, const IntegerList &mts, Integer2dList &tinds_2d)
void fast_set_xs (const IntegerList &ninds, const IntegerList &mts, const Integer2dList &tinds_2d, const DoubleList &new_xs)
Fast setting of cross sections with generated tinds_2d.
void remove_fp_reactions ()
Remove fission product absorptions.
int get_ilite () const
int get_iact () const
int get_ifp () const
int get_itot () const
int get_non () const
int get_nfluxgrp () const
int get_nti () const
int get_nfiso () const
int get_pos () const
int get_nmonth () const
int get_nday () const
int get_nyear () const
float get_burnup () const
const char * get_filename () const
const IntegerList * get_typ_nuc () const
const IntegerList * get_nucl () const
IntegerList * get_nucl ()
const IntegerList * get_kd_ () const
IntegerList * get_kd_ ()
const IntegerList * get_non0_ () const
IntegerList * get_non0_ ()
const IntegerList * get_kd () const
IntegerList * get_kd ()
const IntegerList * get_non0 () const
IntegerList * get_non0 ()
const IntegerList * get_loc () const
IntegerList * get_loc ()
void get_kd_array (size_t, int *) const
void get_non0_array (size_t, int *) const
void get_loc_array (size_t, int *, bool) const
size_t kd_size () const
size_t non0_size () const
size_t loc_size () const
const IntegerList * get_mt () const
const IntegerList * get_nucfis () const
const FloatList * get_dis () const
FloatList * get_dis ()
const FloatList * get_genneu () const
FloatList * get_genneu ()
const FloatList * get_q () const
const FloatList * get_fg () const
const FloatList * get_ampc () const
const FloatList * get_wmpc () const
const FloatList * get_abund () const
const FloatList * get_wabund () const
const FloatList * get_spectrum () const
const DoubleList * get_a () const
DoubleList * get_a ()
const DoubleList * get_tocap () const
DoubleList * get_tocap ()
const DoubleList * get_fiss () const
DoubleList * get_fiss ()
const FloatList * get_m () const
const StringList * get_titles () const
void split_id (const int nind, int &S, int &I, int &Z, int &A)
std::vector< double > get_xs_stdvec (const int mt_in)
QString toQString_title ()
QString toQString_sizzzaaa (const int nind)
QString toQString (const int sigdigs, const char *trans_sort, const double eps_sigma, const double eps_decay)
QString toQString_mts ()
QString toQString_info ()
QString toQString_sizes ()
QString toQString_nuclides (const int sigdigs)
QString toQString_transitions (const int sigdigs, const char *trans_sort, double const eps_sigma=0.0, double const eps_decay=0.0)
QString toQString_cross_section_mt (const int mt_in, const int sigdigs, double const eps_sigma)
QString toQString_cross_sections (const int sigdigs, double const eps_sigma)
void set_itot (int _itot)
void set_ilite (int _ilite)
void set_iact (int _iact)
void set_ifp (int _ifp)
void set_non (int _non)
void set_nmonth (int _month)
void set_nday (int _day)
void set_nyear (int _year)
void set_nfluxgrp (int _nfluxgrp)
void set_nti (int _nti)
void set_nfiso (int _nfiso)
void set_pos (int _pos)
void set_burnup (float _bu)
void set_filename (std::string _fn)
void set_nucl (IntegerList)
void set_kd_ (IntegerList)
void set_non0_ (IntegerList)
void set_kd (IntegerList)
void set_non0 (IntegerList)
void set_loc (IntegerList)
void set_a (DoubleList)
void set_mt (IntegerList)
void set_dis (FloatList)
void set_q (FloatList)
void set_fg (FloatList)
void set_ampc (FloatList)
void set_wmpc (FloatList)
void set_abund (FloatList)
void set_wabund (FloatList)
void set_tocap (DoubleList)
void set_fiss (DoubleList)
void set_genneu (FloatList)
void set_spectrum (FloatList)
void set_nucfis (IntegerList)
void set_titles (StringList)
void populate_transition_ids_cache ()
void clear_transition_ids_cache ()
void get_transition_ids (const int nind, Vec_Int &tids)
void get_possible_transition_ids (Vec_Int &tids)
void filter_reaction_mts (Vec_Int::const_iterator tids_begin, Vec_Int::const_iterator tids_end, Vec_Int &mts) const
void set_kappa_fission (const FloatList &)
void set_kappa_capture (const FloatList &)
const FloatList * get_kappa_capture () const
const FloatList * get_kappa_fission () const
double get_decay_power (const DoubleList &numden, double vol)
double get_reaction_power (const DoubleList &numden, double vol, double flux)
double get_fission_power (const DoubleList &numden, double vol, double flux)
double get_capture_power (const DoubleList &numden, double vol, double flux)
int add_tally_nuclide (const std::vector< double > &tally_dw, const std::vector< int > &tally_di, const std::vector< double > &tally_rw, const std::vector< int > &tally_ri)
int add_tally_nuclide (const std::vector< double > &tally_dw, const std::vector< int > &tally_di, const std::vector< double > &tally_rw, const std::vector< int > &tally_ri, int zaid)
int add_energy_tally (double flux)
int add_num_fissions_tally ()
int add_num_captures_tally ()
int add_concentration_tallies (std::vector< int > &zaids)
const NuclideSet & nuclide_set () const
Static Public Member Functions
static int NOT_FOUND ()
Protected Member Functions
void init_bounds ()
Initialize library boundaries (for internal function use)
void init_typ_nuc ()
Initialize typ_nuc array on class.
Protected Attributes
int non
Number of non-zero off-diagonal elements of the transition matrix A.
int ilite
Number of light-element activation product nuclides in the library.
int iact
Number of actinide nuclides in the library.
int ifp
Number of fission product nuclides in the library.
int itot
Total number of nuclides in the library.
int nfluxgrp
Number of energy groups in the collapse spectrum.
int nti
Number of title cards.
int nfiso
Number of fissionable isotopes.
float burnup
Burnup [MWd/tU] of the library.
std::string filename
Base filename of the library.
int pos
Position number of the burnup-dependent XS set in the library.
int numLibs
Number of available burnup positions in the library.
int sizes [3]
[ilite, iact, ifp] array
int bounds [4][2]
ilo/ihi for each library (0=all; 1,2,3 = lite/act/fp)
IntegerList typ_nuc
Gives the nuclide type for each nuclide [1/2/3] [itot].
IntegerList nucl
NUCL array (ZAID for all nuclides in the library) [itot].
IntegerList kd_
Total number of parents for nuclide I by decay transitions [itot].
IntegerList non0_
Total number of parents for nuclide I [itot].
IntegerList kd
Pointer [NON] to last decay parent of nuclide I in A [itot].
IntegerList non0
Pointer [NON] to last parent of nuclide I in A [itot].
IntegerList loc
LOC array.
FloatList dis
DIS array (Radioactive decay constants) [itot].
FloatList q
Q array (Recoverable energy values from decay) [itot].
FloatList fg
FG array (Fractions of Q-values due to photons) [itot].
FloatList ampc
AMPC array (RCG values for air) [itot].
FloatList wmpc
WMPC array (RCG values for water) [itot].
FloatList abund
FloatList wabund
Natural abundances of nuclides in wt% [ilite].
IntegerList mt
MT numbers for every transition (A-matrix elements) [non].
IntegerList nucfis
List of fissionable nuclides [nfiso].
FloatList spectrum
Fluxes used for library collapse [nfluxgrp].
FloatList m
Atomic masses in grams/mol [itot].
StringList titles
Title cards container.
FloatList b_kappa_capture
FloatList b_kappa_fission
Kappa-fission values in MeV [iact].
DoubleList a
A array [non].
DoubleList tocap
TOCAP array (Effective one-group capture cross-sections) [itot].
DoubleList fiss
FISS array (Effective one-group fission cross-sections) [iact].
FloatList genneu
GENNEU array (Effective one-group neutron yields) [ilite + act].
int nmonth
Month the library was made.
int nday
Day the library was made.
int nyear
Year the library was made.
bool _cached_has_valid_mts
whether the library has valid MTs or not (used internally for checking)
std::map< int, std::vector< int > > d_transition_ids_cache
std::set< int > d_possible_transition_ids_cache
int num_tallies
Number of tally nuclides added to the system.
SCP_NuclideSet b_nuclide_set
nuclide set for the future
Private Member Functions
template<typename V1 , typename V2 >
std::string emsgn (const int i, const std::string v1msg, const V1 val1, const std::string v2msg, const V2 val2)
template<typename V1 , typename V2 >
std::string emsgs (const std::string v1msg, const V1 val1, const std::string v2msg, const V2 val2)
Friends
class Origen::Library
Detailed Description
Examples:
Core/dc/tests/tstCase.cpp, Core/dc/tests/tstTransitionMatrixP.cpp, Core/io/tests/tstMaterialBuffer.cpp, and Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
Member Typedef Documentation
typedef std::shared_ptr<TransitionMatrixP> SP
typedef std::shared_ptr<const TransitionMatrixP> SCP
Constructor & Destructor Documentation
TransitionMatrixP ()
Default constructor.
     : non( 0 )
     , ilite( 0 )
     , iact( 0 )
     , ifp( 0 )
     , itot( 0 )
     , nfluxgrp( 0 )
     , nti( 0 )
     , nfiso( 0 )
     , burnup( 0.0 )
     , pos( 0 )
     , _cached_has_valid_mts( false )
     , num_tallies( 0 )
 {
     jDebugLine( "leaving TransitionMatrixP ctor" );
 }
~TransitionMatrixP ()
Destructor.
 {}
Member Function Documentation
TransitionMatrixP & operator= (const TransitionMatrixP & other)
Assignment operator.
References TransitionMatrixP::a, TransitionMatrixP::abund, TransitionMatrixP::ampc, TransitionMatrixP::b_kappa_capture, TransitionMatrixP::b_kappa_fission, TransitionMatrixP::b_nuclide_set, TransitionMatrixP::bounds, TransitionMatrixP::burnup, TransitionMatrixP::dis, TransitionMatrixP::fg, TransitionMatrixP::filename, TransitionMatrixP::fiss, TransitionMatrixP::genneu, TransitionMatrixP::iact, TransitionMatrixP::ifp, TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::kd_, TransitionMatrixP::loc, TransitionMatrixP::m, TransitionMatrixP::mt, TransitionMatrixP::nday, TransitionMatrixP::nfiso, TransitionMatrixP::nfluxgrp, TransitionMatrixP::nmonth, TransitionMatrixP::non, TransitionMatrixP::non0, TransitionMatrixP::non0_, TransitionMatrixP::nti, TransitionMatrixP::nucfis, TransitionMatrixP::nucl, TransitionMatrixP::numLibs, TransitionMatrixP::nyear, TransitionMatrixP::pos, TransitionMatrixP::q, TransitionMatrixP::sizes, TransitionMatrixP::spectrum, TransitionMatrixP::titles, TransitionMatrixP::tocap, TransitionMatrixP::typ_nuc, TransitionMatrixP::wabund, and TransitionMatrixP::wmpc.
 {
     if( this != &orig )
     {  // self-assignment check
         non = orig.non;
         ilite = orig.ilite;
         iact = orig.iact;
         ifp = orig.ifp;
         itot = orig.itot;
         nfluxgrp = orig.nfluxgrp;
         nti = orig.nti;
         nfiso = orig.nfiso;
         burnup = orig.burnup;
         filename = orig.filename;
         pos = orig.pos;
         numLibs = orig.numLibs;
         memcpy( sizes, orig.sizes, 3 * sizeof( int ) );
         memcpy( bounds, orig.bounds, 2 * 4 * sizeof( int ) );
         typ_nuc = orig.typ_nuc;
         nucl = orig.nucl;
         kd_ = orig.kd_;
         non0_ = orig.non0_;
         kd = orig.kd;
         non0 = orig.non0;
         loc = orig.loc;
         dis = orig.dis;
         q = orig.q;
         fg = orig.fg;
         ampc = orig.ampc;
         wmpc = orig.wmpc;
         abund = orig.abund;
         wabund = orig.wabund;
         mt = orig.mt;
         nucfis = orig.nucfis;
         spectrum = orig.spectrum;
         m = orig.m;
         titles = orig.titles;
         b_kappa_capture = orig.b_kappa_capture;
         b_kappa_fission = orig.b_kappa_fission;
         a = orig.a;
         tocap = orig.tocap;
         fiss = orig.fiss;
         genneu = orig.genneu;
         nmonth = orig.nmonth;
         nday = orig.nday;
         nyear = orig.nyear;
         b_nuclide_set = orig.b_nuclide_set;
     }
     return *this;
 }
void finish_init ()
Wrap-up initialization - called by TransitionMatrixPWrapper.
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::b_kappa_capture, TransitionMatrixP::b_kappa_fission, TransitionMatrixP::convert_abundances(), TransitionMatrixP::expand_matrix_pointers(), EnergyResource::getKappaValues(), TransitionMatrixP::iact, TransitionMatrixP::ifp, TransitionMatrixP::ilite, TransitionMatrixP::init_bounds(), TransitionMatrixP::init_typ_nuc(), TransitionMatrixP::itot, TransitionMatrixP::m, TransitionMatrixP::nucl, and TransitionMatrixP::split_id().
Referenced by TEST().
 {
     // Basic sanity check to ensure we've initialized
     Insist( ( ( itot > 0 ) && ( ilite > 0 ) && ( iact > 0 ) && ( ifp > 0 ) ),
             "Error: TransitionMatrixP not yet initialized!" );
     expand_matrix_pointers();
     init_bounds();
     init_typ_nuc();
     Check( static_cast<int>( nucl.size() ) == itot );
     // fall back calculation of molar masses
     if( static_cast<int>( m.size() ) != itot )
     {
         m.resize( itot );
         for( int i = 0; i < itot; i++ )
         {
             m[i] = ( nucl[i] / 10 ) % 1000;
         }
     }
     Check( static_cast<int>( m.size() ) == itot );
     // load up kappas (this code is inefficient but it is only needed
     // temporarily to avoid having
     // to modify lots of arp stuff (which will go away soon with general
     // interpolation is online)
     // which are the OTHER path for a library to get in memory-->through
     // interpolation in arp.
     // Arp does something very evil and uses all deprecated IO routines.  If
     // there was a single
     // pack/unpack on the transition matrix/library/whatever, then arp could
     // work seemlessly.
     bool fix_kappa_c = static_cast<int>( b_kappa_capture.size() ) != itot;
     bool fix_kappa_f = static_cast<int>( b_kappa_fission.size() ) != iact;
     if( fix_kappa_c || fix_kappa_f )
     {
         EnergyResource fc;
         if( fix_kappa_c ) b_kappa_capture.resize( itot );
         if( fix_kappa_f ) b_kappa_fission.resize( iact );
         for( int i = 0; i < itot; i++ )
         {
             int S, I, Z, A;
             split_id( i, S, I, Z, A );
             int izzzaaa = I * 1000000 + Z * 1000 + A;
             double kappa_c, kappa_f;
             fc.getKappaValues( izzzaaa, kappa_c, kappa_f );
             if( fix_kappa_c ) b_kappa_capture[i] = kappa_c;
             if( fix_kappa_f && S == 2 ) b_kappa_fission[i - ilite] = kappa_f;
         }
     }
     Check( static_cast<int>( b_kappa_capture.size() ) == itot );
     Check( static_cast<int>( b_kappa_fission.size() ) == iact );
     convert_abundances();
 }
void build_coo_matrix (double flux, IntegerList & ia, IntegerList & ja, DoubleList & a_in)
Build the full transition matrix (A+D) in the COO compressed format.
Parameters
flux flux in [n/cm^2*s]
ia row indices of non-zero matrix elements
ja column indices of non-zero matrix elements
a_in values of non-zero matrix elements
See also
: build_full_matrix()
References TransitionMatrixP::build_full_matrix().
 {
     /*
        flux:  flux in [n/cm^2*s]
        ia[]:  row indices of non-zero matrix elements
        ja[]:  column indices of non-zero matrix elements
        a_in[]:   values of non-zero matrix elements
     */
     Double2dList matrix;  // The full transition matrix
     // Initialize list of non-zero elements
     a_in.clear();
     // Initialize row and column indices
     ia.clear();
     ja.clear();
     // Build the full matrix
     this->build_full_matrix( flux, matrix );
     // Go through the full matrix
     for( size_t i = 0; i < matrix.size(); i++ )
     {
         for( size_t j = 0; j < matrix[i]->size(); j++ )
         {
             // Select nonzero elements
             if( std::abs( matrix[i]->at( j ) ) > 0.0 )
             {
                 ia.push_back( i );
                 ja.push_back( j );
                 a_in.push_back( matrix[i]->at( j ) );
             }
         }
     }
     // Garbage collection
     for( size_t i = 0; i < matrix.size(); i++ )
     {
         delete matrix[i];
     }
     Ensure( ia.size() == ja.size() );
     Ensure( a_in.size() == ia.size() );
 }
void build_full_matrix (double flux, Double2dList & matrix)
Build the full transition matrix (A+D) as an uncompressed 2D array.
Parameters
flux flux in [n/cm^2*s]
matrix full transition matrix [itot, itot]
See also
: build_coo_matrix()
References TransitionMatrixP::a, TransitionMatrixP::dis, TransitionMatrixP::first_transition(), TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::last_transition(), TransitionMatrixP::loc, TransitionMatrixP::non0, and TransitionMatrixP::tocap.
Referenced by TransitionMatrixP::build_coo_matrix(), and TransitionMatrixP::check().
 {
     /*
        flux: flux in [n/cm^2*s]
        mat:  full transition matrix ( dimension itot x itot )
      */
     matrix.clear();
     DoubleList row;
     for( int i = 0; i < itot; i++ )
     {
         row.clear();
         row.resize( itot, 0.0 );  // initialize a row of 0.0 values
         // Handle diagonal elements (matrix[i][i]) - decay and capture
         // Diagonal - decay
         row[i] -= dis[i];
         // Diagonal - capture
         row[i] -= tocap[i] * flux * 1e-24;
         // Decay parents
         for( int j = first_transition( i ); j < last_transition( i, flux );
              j++ )
         {
             row[loc[j]] += a[j];
         }
         // Reaction parents
         for( int j = kd[i]; j < non0[i]; j++ )
         {
             row[loc[j]] += a[j] * flux * 1e-24;
         }
         // Push back newly modified row
         matrix.push_back( (DoubleList*)row.getCopy() );
     }
 }
void expand_matrix_pointers ()
Convert KD and non0 arrays to "pointer" style (they point to the last parent in the A matrix)
References TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::kd_, TransitionMatrixP::non, TransitionMatrixP::non0, and TransitionMatrixP::non0_.
Referenced by TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::finish_init(), and TransitionMatrixP::transpose_transition_matrix().
 {
     Require( static_cast<int>( kd_.size() ) == itot );
     Require( static_cast<int>( non0_.size() ) == itot );
     non0.clear();
     kd.clear();
     // the first pointers are the same
     non0.push_back( non0_[0] );
     kd.push_back( kd_[0] );
     for( int i = 1; i < itot; i++ )
     {
         // and then they just add up
         non0.push_back( non0_[i] + non0[i - 1] );
         kd.push_back( kd_[i] + non0[i - 1] );
     }
     Ensure( non0[itot - 1] == non );
 }
void check_library ()
Run library consistency check.
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::a, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::loc, TransitionMatrixP::non, and TransitionMatrixP::non0.
Referenced by TEST().
 {
     SErrLine( 2, "Checking library..." );
     // verify that the number of parents is reasonable
     int n = 0;
     for( int i = 0; i < itot; i++ )
     {
         Insist( kd[i] >= n, "Negative number of decay parents?" );
         Insist( non0[i] >= kd[i], "Negative number of reaction parents?" );
         n = non0[i];
     }
     if( n != non )
     {
         ScaleReportError(
             1,
             "Last pointer goes to: " << n << std::endl
                                      << "Given number of transitions is: "
                                      << non
                                      << std::endl
                                      << "Incomplete matrix." );
         Insist( n == non, "Incomplete matrix." );  // Throw our exception...
     }
     for( int i = 0; i < non; i++ )
     {
         Insist( loc[i] >= 0, "Points under matrix." );
         Insist( loc[i] < itot, "Points above matrix." );
     }
     for( int i = 0; i < non; i++ )
     {
         Insist( a[i] >= 0,
                 "Invalid (negative) values in library compressed transition "
                 "matrix (A)." );
     }
     SErrLine( 2, "Library OK." );
     // need some kind of test on positivity of cross sections
     // if( !(xs>=0) ){
     //  reporter->write("error","val<0 for requested xs of parent nucl=" +
     //    QString::number(nucl[n]) + "mt=" + QString::number(mt_in));
     //  Insist( xs>=0 ,"val<0 for requested xs");
     // }
 }
bool check (std::vector< std::string > & errors)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::a, TransitionMatrixP::build_full_matrix(), TransitionMatrixP::dis, TransitionMatrixP::emsgn(), TransitionMatrixP::emsgs(), TransitionMatrixP::first_transition(), TransitionMatrixP::fiss, TransitionMatrixP::iact, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::kd_, TransitionMatrixP::last_transition(), TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::non, TransitionMatrixP::non0, TransitionMatrixP::non0_, and TransitionMatrixP::tocap.
Referenced by TEST().
 {
     size_t num_original_errors = errors.size();
     // check size parameters first
     // transition structure stuff
     if( kd.size() != (size_t)itot )
         errors.push_back( emsgs( " decay parents pointer array kd.size()=",
                                  kd.size(),
                                  " should satisfy kd.size() == itot=",
                                  itot ) );
     if( non0.size() != (size_t)itot )
         errors.push_back( emsgs( " total parents pointer array non0.size()=",
                                  non0.size(),
                                  " should satisfy non0.size() == itot=",
                                  itot ) );
     if( kd_.size() != (size_t)itot )
         errors.push_back( emsgs( " decay parents pointer array kd_.size()=",
                                  kd_.size(),
                                  " should satisfy kd_.size() == itot=",
                                  itot ) );
     if( non0_.size() != (size_t)itot )
         errors.push_back( emsgs( " total parents pointer array non0_.size()=",
                                  non0_.size(),
                                  " should satisfy non0_.size() == itot=",
                                  itot ) );
     if( loc.size() != (size_t)non )
         errors.push_back( emsgs( " parent location index array loc.size()=",
                                  loc.size(),
                                  " should satisfy loc.size() == non=",
                                  non ) );
     if( mt.size() != (size_t)non )
         errors.push_back( emsgs( " reaction mt array mt.size()=",
                                  mt.size(),
                                  " should satisfy mt.size() == non=",
                                  non ) );
     // transition matrix stuff
     if( dis.size() != (size_t)itot )
         errors.push_back( emsgs( " decay constant array dis.size()=",
                                  dis.size(),
                                  " should satisfy dis.size() == itot=",
                                  itot ) );
     if( tocap.size() != (size_t)itot )
         errors.push_back( emsgs( " total capture array tocap.size()=",
                                  tocap.size(),
                                  " should satisfy tocap.size() == itot=",
                                  itot ) );
     if( fiss.size() != (size_t)iact )
         errors.push_back( emsgs( " fission xs array fission.size()=",
                                  tocap.size(),
                                  " should satisfy fission.size() == iact=",
                                  iact ) );
     if( a.size() != (size_t)non )
         errors.push_back( emsgs( " matrix coefficient array a.size()=",
                                  a.size(),
                                  " should satisfy a.size() == non=",
                                  non ) );
     // quick return when size checks fail
     if( errors.size() != (size_t)num_original_errors ) return false;
     // check transition structure stuff
     for( int i = 0; i < itot; ++i )
     {
         if( !( kd_[i] >= 0 ) )
             errors.push_back( emsgn( i,
                                      " number of decay parents kd_[nind]=",
                                      kd_[i],
                                      " should satisfy kd_[nind] >= ",
                                      0 ) );
         if( !( non0_[i] >= kd_[i] ) )
             errors.push_back(
                 emsgn( i,
                        " number of total parents non0_[nind]=",
                        non0_[i],
                        " should satisfy non0_[nind] >= kd_[nind]=",
                        kd_[i] ) );
     }
     // check consistency
     if( non0[itot - 1] != non )
         errors.push_back( emsgs(
             " inconsistent parents pointer array: last entry non0[itot-1]=",
             non0[itot - 1],
             " should be the same as total number of nonzeros: non0[itot-1] == "
             "non=",
             non ) );
     // check locations validity: bounds
     for( int i = 0; i < non; i++ )
     {
         if( !( loc[i] >= 0 && loc[i] < itot ) )
             errors.push_back( emsgs( " at transition index tind=",
                                      i,
                                      " the parent nuclide index (0<=nind<" +
                                          ScaleUtils::IO::toString( itot ) +
                                          ") is out of bounds nind=",
                                      loc[i] ) );
     }
     // quick return because can't check if loc are wrong
     if( errors.size() != (size_t)num_original_errors ) return false;
     // check locations validity: parent can't be daughter
     for( int i = 0; i < itot; i++ )
     {
         int daughter_id = i;
         for( int j = first_transition( i ); j < last_transition( i, 1.0 ); ++j )
         {
             int parent_id = loc[j];
             if( parent_id == daughter_id )
                 errors.push_back(
                     emsgs( " at transition index tind=",
                            j,
                            " the parent nuclide index=" +
                                ScaleUtils::IO::toString( parent_id ) +
                                " was same as daughter nind=",
                            daughter_id ) );
         }
     }
     // quick return because can't check if loc are wrong
     if( errors.size() != (size_t)num_original_errors ) return false;
     // check a-matrix positivity
     for( int i = 0; i < non; i++ )
     {
         if( !( a[i] >= 0 ) )
             errors.push_back( emsgs(
                 " at transition index tind=",
                 i,
                 " the transition matrix coefficient is negative a[tind]=",
                 a[i] ) );
     }
     // quick return when a-matrix is wrong
     if( errors.size() != num_original_errors ) return false;
     // first, build out a full matrix with only decay
     Double2dList matrix;
     build_full_matrix( 0.0, matrix );
     // check a-matrix diagonal dominance with only decay
     // part 1 accumulate
     std::vector<double> off_diag( itot, 0.0 );
     std::vector<double> diag( itot, 0.0 );
     for( int i = 0; i < itot; i++ )
     {
         for( int j = 0; j < itot; j++ )
         {
             if( i != j ) off_diag[j] += matrix.at( i )->at( j );
         }
         diag[i] = matrix.at( i )->at( i );
     }
     // free row pointers
     for( int i = 0; i < itot; i++ )
     {
         delete matrix.at( i );
     }
     // part 2 check
     for( int i = 0; i < itot; i++ )
     {
         if( diag[i] > 0.0 )
         {
             errors.push_back(
                 emsgn( i,
                        " the diagonal total decay term lambda[nind]=",
                        diag[i],
                        " cannot be >",
                        0.0 ) );
         }
         if( -diag[i] < off_diag[i] )
         {
             errors.push_back(
                 emsgn( i,
                        " the column sum of decay terms off_diag[nind]=",
                        off_diag[i],
                        " must be less than or equal to -diag[nind]=",
                        -diag[i] ) );
         }
     }
     // now build out a full matrix with decay and reaction terms
     build_full_matrix( 1.0, matrix );
     // check a-matrix diagonal dominance with reaction terms included
     // part 1 accumulate
     for( int i = 0; i < itot; i++ )
     {
         for( int j = 0; j < itot; j++ )
         {
             if( i != j ) off_diag[j] += matrix.at( i )->at( j );
         }
         diag[i] = matrix.at( i )->at( i );
     }
     // free row pointers
     for( int i = 0; i < itot; i++ )
     {
         delete matrix.at( i );
     }
     // part 2 check
     for( int i = 0; i < itot; i++ )
     {
         if( diag[i] > 0.0 )
         {
             errors.push_back( emsgn( i,
                                      " the diagonal total decay+reaction term "
                                      "reaction+lambda[nind]=",
                                      diag[i],
                                      " cannot be >",
                                      0.0 ) );
         }
         if( -diag[i] < off_diag[i] )
         {
             errors.push_back( emsgn(
                 i,
                 " the column sum of decay+reaction terms off_diag[nind]=",
                 off_diag[i],
                 " must be less than or equal to -diag[nind]=",
                 -diag[i] ) );
         }
     }
     return errors.size() == num_original_errors;
 }
void print_transitions_for (const int parent_id, const int mt_in)
Print list of transitions for a given reaction.
Parameters
parent_id Parent nuclide ID (ZZAAAI)
mt_in MT number for reaction
References TransitionMatrixP::a, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::loc, TransitionMatrixP::m, TransitionMatrixP::mt, TransitionMatrixP::non0, and TransitionMatrixP::nucl.
 {
     // parent_id:  Parent nuclide ID (ZZAAAI)
     // mt_in:      MT number for the reaction
     for( int m = 0; m < itot; m++ )
     {
         for( int k = kd[m] + 1; k < non0[m]; k++ )
         {
             if( ( nucl[loc[k]] == parent_id ) && ( this->mt[k] == mt_in ) )
             {
                 SOutLine(
                     1,
                     "Transition " << k << " -> " << m << " :: " << parent_id
                                   << "=>"
                                   << nucl[m]
                                   << " MT="
                                   << mt_in
                                   << " a="
                                   << a[k] );
             }
         }
     }
 }
int NOT_FOUND () static
References NuclideSet::NOT_FOUND().
 {
     // TODO: fix it so we actually pass back the fortran offset indices
     // it has been the understanding in the API that you must apply to offset
     // of one on your side for these kinds of indices---but we don't need to
     // do that anymore
     size_t not_found = NuclideSet::NOT_FOUND( false );
     Check( not_found < static_cast<size_t>( std::numeric_limits<int>::max() ) );
     return static_cast<int>( not_found );
 }
int find_nuclide_guess (const int id)
Find nuclide by ZZZAAAI id, guessing which sublib
Parameters
id Nuclide ID in ZZZAAAI format
Returns
Index in nucl array (returns NOT_FOUND() if not found)
See also
find_nuclide(), find_nuclide_all()
References TransitionMatrixP::b_nuclide_set, and NuclideSet::convert_zzzaaai_to_izzzaaa().
 {
     Require( b_nuclide_set != nullptr );
     Vec_Int ids{id};
     NuclideSet::convert_zzzaaai_to_izzzaaa( &ids );
     int izzzaaa = ids[0];
     size_t j = b_nuclide_set->lookup_index_guess( izzzaaa );
     Check( j < static_cast<size_t>( std::numeric_limits<int>::max() ) );
     return static_cast<int>( j );
 }
bool find_nuclide_all (Vec_Int * indices, const int id)
Find all instances of nuclide by ZZZAAAI id
Parameters
id Nuclide ID in ZZZAAAI format
Returns
Index in nucl array (returns NOT_FOUND() if not found)
See also
find_nuclide(), find_nuclide_guess()
References TransitionMatrixP::b_nuclide_set, and NuclideSet::convert_zzzaaai_to_izzzaaa().
 {
     Require( nuclides != nullptr );
     Require( b_nuclide_set != nullptr );
     Vec_Int ids{id};
     NuclideSet::convert_zzzaaai_to_izzzaaa( &ids );
     int izzzaaa = ids[0];
     bool found = b_nuclide_set->lookup_index_all( nuclides, izzzaaa );
     return found;
 }
int find_nuclide (const int sublib, const int id)
Find nuclide by id ZZZAAAI and sublib
Parameters
sublib Nuclide sublibrary number (1/2/3 - LT/AC/FP)
id Nuclide ID in ZZZAAAI format
Returns
Index in nucl array for ZAID (returns NOT_FOUND() if not found)
See also
find_nuclide_guess(), find_nuclide_all()
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::b_nuclide_set, and NuclideSet::convert_zzzaaai_to_izzzaaa().
Referenced by Case::load_new_concentrations(), and Origen::test::TEST().
 {
     Require( b_nuclide_set != nullptr );
     Vec_Int ids{id};
     NuclideSet::convert_zzzaaai_to_izzzaaa( &ids );
     int sizzzaaa = ids[0] + ScaleData::Utils::PIZZZAAA_P_OFFSET * sublib;
     size_t j = b_nuclide_set->lookup_index( sizzzaaa );
     Check( j < static_cast<size_t>( std::numeric_limits<int>::max() ) );
     return static_cast<int>( j );
 }
void print_info ()
Print the library contents.
References TransitionMatrixP::filename, TransitionMatrixP::iact, TransitionMatrixP::ifp, TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionMatrixP::nday, TransitionMatrixP::nmonth, TransitionMatrixP::non, TransitionMatrixP::nti, TransitionMatrixP::nyear, TransitionMatrixP::pos, and TransitionMatrixP::titles.
 {
     QString titleString;
     // filename
     // Consider using a QString here with trimmed()
     SOutLine( 1,
               "filename: " << filename
                            << " cross-section data taken from position number: "
                            << pos );
     SOut( 1, "library title delimited by {}: \n{" );
     titleString = "";
     for( int i = 0; i < nti; i++ )
     {
         // Insert a line break for extended spaces
         if( titles[i].compare( "    " ) == 0 )
         {
             if( ( i > 0 ) && ( titles[i - 1].compare( "    " ) != 0 ) )
             {
                 // titleString.append("\n");
                 SOut( 1, titleString.toStdString() );
                 titleString.clear();
             }
         }
         else
         {
             titleString.append( titles[i].c_str() );
         }
     }
     SOutLine( 1, "}" );
     SOutLine( 1,
               "date library was produced: "
                   << nmonth
                   << "/"
                   << nday
                   << "/"
                   << nyear
                   << std::endl
                   << "total number of nuclides in library: "
                   << itot
                   << std::endl
                   << "number of light-element nuclides: "
                   << ilite
                   << std::endl
                   << "number of actinide nuclides: "
                   << iact
                   << std::endl
                   << "number of fission product nuclides: "
                   << ifp
                   << std::endl
                   << "number of nonzero off-diagonal matrix elements: "
                   << non );
 }
double get_xs (const int n, const int mt_in)
Get a cross-section from the library.
Parameters
n Parent index
mt_in Reaction MT value
Returns
Reaction cross-section
References TransitionMatrixP::a, TransitionMatrixP::bounds, TransitionMatrixP::fiss, TransitionMatrixP::has_valid_mts(), TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::non, TransitionMatrixP::nucl, Origen::nuclide_in_bounds(), TransitionMatrixP::num_massive_daughters(), Origen::SUBLIB_2AC, and TransitionMatrixP::tocap.
Referenced by TransitionMatrixP::perturb_xs().
 {
     // n:  parent of the reaction (index)
     // mt: MT of the reaction
     // xs: cross section to be returned
     Require( has_valid_mts() );
     Require( nuclide_in_bounds( n, itot ) );
     Require( n < static_cast<int>( tocap.size() ) );
     double xs = 0;
     int count = 0;
     switch( mt_in )
     {
         case( 27 ):
             count++;
             xs = tocap[n];
             break;
         case( 101 ):
             count++;
             // subtract fission if it is an actinide
             if( ( n >= bounds[SUBLIB_2AC][0] ) &&
                 ( n < bounds[SUBLIB_2AC][1] ) )
             {
                 xs = tocap[n] - fiss[n - ilite];
             }
             else
             {
                 xs = tocap[n];
             }
             break;
         case( 18 ):
             count++;
             // allow non-actinide in get_xs and just return 0 (but not set_xs)
             if( ( n >= bounds[SUBLIB_2AC][0] ) &&
                 ( n < bounds[SUBLIB_2AC][1] ) )
             {
                 xs = fiss[n - ilite];
             }
             break;
         // must do a full search for any non-fiss xs
         default:
             Require( static_cast<int>( loc.size() ) == non );
             Require( static_cast<int>( a.size() ) == non );
             for( int k = 0; k < non; k++ )
             {
                 if( ( loc[k] == n ) && ( mt[k] == mt_in ) )
                 {
                     count++;
                     xs += a[k];
                 }
             }
             Check( num_massive_daughters( mt_in ) > 0 );
             xs /= num_massive_daughters(
                 mt_in );  // normalize by number of massive daughters
                           // not the same as number of times we found
                           // this reaction
     }
     // issue warning if we don't change anything
     if( count == 0 )
     {
         SOutLine( 2,
                   "get_xs passed nuclide=" << nucl[n] << " and mt=" << mt_in
                                            << " was not found" );
     }
     return xs;
 }
void set_xs (const int n, const int mt_in, const double new_xs)
Update a reaction cross-section in the library.
Parameters
n Parent index
mt_in Reaction MT value
new_xs New reaction cross-section
References TransitionMatrixP::a, TransitionMatrixP::bounds, TransitionMatrixP::fiss, TransitionMatrixP::has_valid_mts(), TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::non, TransitionMatrixP::nucl, Origen::nuclide_in_bounds(), TransitionMatrixP::num_massive_daughters(), Origen::only_set_component(), Origen::SUBLIB_2AC, and TransitionMatrixP::tocap.
Referenced by TransitionMatrixP::perturb_xs().
 {
     // n:       index of parent nuclide of the reaction (index in N)
     // MT:      MT of the reaction
     // new_xs:  new cross-section
     Require( nuclide_in_bounds( n, itot ) );
     Require( only_set_component( mt_in ) );
     // result is cached but important to always check
     Insist( has_valid_mts(),
             "library MTS are not defined properly and so you can't use "
             "set_xs---you probably need to generate a new library" );
     // keep a running count of changes
     int count = 0;
     // Fission
     if( mt_in == 18 )
     {
         // only actinides have fission xs
         Check( ( n >= bounds[SUBLIB_2AC][0] ) &&
                ( n < bounds[SUBLIB_2AC][1] ) );
         // only allow perturbations for nonzero existing xs on library
         double old_fiss = fiss[n - ilite];
         if( old_fiss > 0.0 )
         {
             // must search whole matrix to change xs for all fps
             for( int k = 0; k < non; k++ )
             {
                 if( ( loc[k] == n ) && ( mt[k] == mt_in ) )
                 {
                     count++;
                     a[k] *= new_xs /
                             old_fiss;  // implicitly keep fission yield the same
                 }
             }
             // issue warning when no fission products are found
             if( count == 0 )
             {
                 SOutLine(
                     2,
                     "fissionable isotope n=" << n
                                              << " has no fission products" );
             }
             // update vectors
             fiss[n - ilite] = new_xs;
             tocap[n] += new_xs - old_fiss;
         }
         // the old fission xs was 0 and we can't do much about it
         else
         {
             SOutLine(
                 2,
                 "cannot change yields properly because old fission xs was "
                 "zero for nucl="
                     << nucl[n] );
         }
     }
     // Everything but Fission
     else
     {
         // must do a full loop to properly accumulate the partial cross section
         IntegerList kfound;
         double old_xs = 0;
         for( int k = 0; k < non; k++ )
         {
             if( ( loc[k] == n ) && ( mt[k] == mt_in ) )
             {
                 count++;
                 kfound.push_back( k );
                 old_xs += a[k];
             }
         }
         // normalize by number of massive daughters (important for alpha
         // producing reactions)
         old_xs /= num_massive_daughters( mt_in );
         for( size_t j = 0; j < kfound.size(); j++ )
         {
             int k = kfound[j];
             a[k] *= new_xs / old_xs;  // implicitly keep branching ratio the
                                       // same
         }
         // update total capture
         tocap[n] += new_xs - old_xs;
     }
     // issue warning if we don't change anything
     if( count == 0 )
     {
         SOutLine( 2,
                   "set_xs passed nuclide=" << nucl[n] << " and mt=" << mt_in
                                            << " was not found" );
     }
 }
void perturb_xs (const int n, const int mt_in, const double factor)
Multiply a given cross-section in the library by a factor.
Parameters
n Parent index
mt_in Reaction MT value
factor Perturbation factor for cross-section
References TransitionMatrixP::get_xs(), and TransitionMatrixP::set_xs().
 {
     // n:      parent of the reaction (index)
     // mt:     MT of the reaction
     // factor: new/old cross section ratio
     double old_xs, new_xs = 0;  // original and perturbed xs
     old_xs = get_xs( n, mt );
     new_xs = factor * old_xs;
     set_xs( n, mt, new_xs );
 }
void collect_xs (const IntegerList nuclist, Integer2dList & xslist)
Get all reactions which involve a given set of nuclides.
Parameters
nuclist List of nuclides (indices in N)
xslist Array of triplets [parent index, reaction MT, parent ZAID]
References TransitionMatrixP::kd, TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::non, TransitionMatrixP::non0, and TransitionMatrixP::nucl.
 {
     /*
        nuclist[]:       List of nuclides (indices in N)
        xslist:          Array of triplets [parent index, reaction MT, parent
        ZZAAAI]
        nuclist.size():  Number of nuclides provided
        xslist.size():   Number of reactions returned
     */
     Integer2dList buffer;  // buffer of dimension [non][3]
     IntegerList
         triplet;  // triplet stores nuclide index, MT number, and nuclide ID
     size_t k = 0;
     // Go through the requested list
     for( size_t i = 0; i < nuclist.size(); i++ )
     {
         // Get the daughters
         for( int j = 0; j < non; j++ )
         {
             if( ( loc[j] == nuclist[i] ) && ( mt[j] > 0 ) )
             {
                 triplet.clear();
                 triplet.push_back( loc[j] );  // paraent nuclide index
                 triplet.push_back( mt[j] );   //  MT number
                 triplet.push_back( nucl[loc[j]] / 10 );  // parent nuclide ZAID
                 // Check to see if the daughter is already in the buffer
                 for( k = 0; k < buffer.size(); k++ )
                 {
                     if( ( buffer[k]->at( 0 ) == triplet[0] ) &&
                         ( buffer[k]->at( 1 ) == triplet[1] ) )
                         break;
                 }
                 // If not present, add the triplet for the daughter
                 if( k == buffer.size() )
                     buffer.push_back( (IntegerList*)triplet.getCopy() );
             }
         }
         // Get the parents
         for( int j = kd[nuclist[i]]; j < non0[nuclist[i]]; j++ )
         {
             if( mt[j] > 0 )
             {
                 triplet.clear();
                 triplet.push_back( loc[j] );             // parent index
                 triplet.push_back( mt[j] );              // parent MT number
                 triplet.push_back( nucl[loc[j]] / 10 );  // parent nuclide ZAID
                 // Check to see if the parent is already in the buffer
                 for( k = 0; k < buffer.size(); k++ )
                 {
                     if( ( buffer[k]->at( 0 ) == triplet[0] ) &&
                         ( buffer[k]->at( 1 ) == triplet[1] ) )
                         break;
                 }
                 // If not present, add the triplet for the parent
                 if( k == buffer.size() )
                     buffer.push_back( (IntegerList*)triplet.getCopy() );
                 // cout << "Pushing back parent ZAID: " << nucl[loc[j]/10]
             }
         }
     }
     // Copy collected triplets over to xslist
     xslist = buffer;
 }
void convert_abundances ()
Calculate wt% of natural abundances on library object (populate wabund)
References TransitionMatrixP::abund, TransitionMatrixP::ilite, TransitionMatrixP::m, TransitionMatrixP::nucl, and TransitionMatrixP::wabund.
Referenced by TransitionMatrixP::finish_init().
 {
     // Ensure abund is still current (i.e., size matches ilite)
     Require( static_cast<int>( abund.size() ) == ilite );
     wabund.clear();
     wabund.resize( ilite, 0.0 );
     // initialize weight fraction accumulator
     std::vector<float> wsum;
     wsum.resize( 200, 0.0 );  // stupid 200 maximum
     // accumulate abundance totals
     for( int i = 0; i < ilite; i++ )
     {
         int Z = nucl[i] / 10000;  // atomic number
         Check( (size_t)Z < wsum.size() );
         wsum[Z] += m[i] * abund[i];  // weight accumulator
     }
     // calculate abundances
     for( int i = 0; i < ilite; i++ )
     {
         int Z = nucl[i] / 10000;  // atomic number
         if( wsum[Z] > 0 )
         {
             wabund[i] = 100 * m[i] * abund[i] / wsum[Z];
         }
         else
         {
             wabund[i] = 0;
         }
     }
     wsum.clear();
     // Make sure wabund lines up with abund
     Ensure( wabund.size() == abund.size() );
 }
void transpose_transition_matrix ()
Transpose compressed transition matrix A.
References TransitionMatrixP::a, TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::itot, TransitionMatrixP::kd_, TransitionMatrixP::loc, TransitionMatrixP::non, and TransitionMatrixP::non0_.
 {
     int nd, noni;
     int kd_index = 0;
     int decayCount;
     IntegerList loc_0;
     IntegerList loc_t;
     IntegerList non0_t;
     IntegerList kd_t;
     DoubleList a_t;
     loc_0.resize( non, 0 );
     SErrLine( 2, "Transposing the transition matrix." );
     // Transpose the parent-daughter relationship
     // Loop over parents
     int n = 0;
     for( int i = 0; i < itot; i++ )
     {
         // count the number of nuclides that have i as a parent
         decayCount = count( loc.begin(), loc.end(), i );
         // number of daughters for each parent
         non0_t.push_back( decayCount );
         // construct nuclide-by-transition array
         Check( ( n + non0_[i] ) <= static_cast<int>( loc_0.size() ) );
         for( int k = n; k < ( n + non0_[i] ); k++ )
         {
             loc_0[k] = i + 1;  // To deal with C++ offset (with i)
         }
         // Find decay transitions in the transition array
         if( kd_[i] > 0 )
         {
             kd_index = n + kd_[i];
             // Indicate decay transitions by negative entry in the loc_0 array
             for( int k = n; k < kd_index; k++ )
             {
                 loc_0[k] = -loc_0[k];
             }
         }
         n += non0_[i];
     }
     // Get number of *decay* transitions for each parent
     for( int i = 0; i < itot; i++ )
     {
         decayCount = 0;
         for( int j = 0; j < non; j++ )
         {
             if( ( loc[j] == i ) && ( loc_0[j] < 0 ) ) decayCount++;
         }
         kd_t.push_back( decayCount );
     }
     n = 0;
     noni = 0;
     // Loop over parents
     for( int i = 0; i < itot; i++ )
     {
         noni += non0_t[i];
         // first transpose all decay transitions
         if( kd_t[i] > 0 )
         {
             nd = 0;
             for( int j = 0; j < non; j++ )
             {
                 if( ( loc[j] == i ) && ( ( loc_0[j] ) < 0 ) )
                 {
                     ++nd;
                     ++n;
                     loc_t.push_back( abs( loc_0[j] ) -
                                      1 );  // account for offset in loc_0
                     a_t.push_back( a[j] );
                     if( nd >= kd_t[i] ) break;
                 }
             }
         }
         // Now transpose all reaction transitions
         if( n < noni )
         {
             for( int j = 0; j < non; j++ )
             {
                 if( ( loc[j] == i ) && loc_0[j] > 0 )
                 {
                     ++n;
                     loc_t.push_back( loc_0[j] -
                                      1 );  // account for offset in loc_0
                     a_t.push_back( a[j] );
                     if( n == noni ) break;
                 }
             }
         }
     }
     // Copy over the transposed matrices
     non0_.clear();
     kd_.clear();
     for( int i = 0; i < itot; i++ )
     {
         non0_.push_back( non0_t[i] );
         kd_.push_back( kd_t[i] );
     }
     non0_t.clear();
     kd_t.clear();
     // Reverse order of members in transmutation chains
     // to make bateman more efficient
     nd = 0;
     for( int i = 0; i < itot; i++ )
     {
         n = nd + kd_[i];
         Check( ( non0_[i] < static_cast<int>( a.size() ) ) &&
                ( non0_[i] < static_cast<int>( loc.size() ) ) );
         for( int j = 0; j < non0_[i]; j++ )
         {
             if( j == kd_[i] ) n += non0_[i];
             Check( ( ( nd + j ) < static_cast<int>( loc.size() ) ) &&
                    ( ( nd + j ) < static_cast<int>( a.size() ) ) );
             loc[nd + j] = loc_t[n - j - 1];
             a[nd + j] = a_t[n - j - 1];
         }
         nd += non0_[i];
     }
     a_t.clear();
     loc_t.clear();
     // Rebuild KD, NON0
     expand_matrix_pointers();
 }
void cleanup_transitions_for_adjoint (DoubleList concentrations, DoubleList & adjoint_source_term_reaction, DoubleList & adjoint_source_term_decay)
Remove stable nuclides from the transition matrix and establish them as a fixed source term
Parameters
concentrations Nuclide concentrations [itot]
adjoint_source_term_reaction Reaction components of source term [itot]
adjoint_source_term_decay Decay components of source term [itot]
References TransitionMatrixP::a, TransitionMatrixP::dis, TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::itot, TransitionMatrixP::kd_, TransitionMatrixP::loc, TransitionMatrixP::non, TransitionMatrixP::non0_, and TransitionMatrixP::tocap.
 {
     // concentrations[itot]:                nuclide concentrations
     // adjoint_source_term_reaction[itot]:  reaction component of the adjoint
     // source term
     // adjoint_source_term_decay[itot]:     decay component of the adjoint
     // source term
     // Buffer for array reallocation (integer) [non]
     IntegerList lib_non_buffer_int;
     // Buffer for array reallocation (float) [non]
     DoubleList lib_non_buffer_dbl;
     // Pointer to the end of the "old" A-matrix
     int onon;
     // Pointer to the end of the "new" A-matrix
     int nnon;
     // daughter nuclide
     // int n;
     // parent nuclide
     int l;
     // flux/decay multiplier
     double fx;
     // variable for holding invariant loop condition
     int loopMax;
     SErrLine( 2, "Calculating adjoint source terms" );
     Require( static_cast<int>( concentrations.size() ) == itot );
     // Initialize outbound arrays
     adjoint_source_term_decay.clear();
     // adjoint_source_term_decay.resize(itot, 0.0);
     adjoint_source_term_reaction.clear();
     // adjoint_source_term_reaction.resize(itot, 0.0);
     nnon = -1;
     onon = -1;
     fx = 1.0;
     // Go through all daughter nuclides
     for( int n = 0; n < itot; n++ )
     {
         adjoint_source_term_decay.push_back( 0.0 );
         adjoint_source_term_reaction.push_back( 0.0 );
         // All decay parents
         loopMax = kd_[n];  // keep invariant, even when kd_[n] changes
         for( int i = 0; i < loopMax; i++ )
         {
             ++onon;
             l = loc[onon];
             if( std::fabs( dis[l] + tocap[l] * fx ) < DBL_MIN )
             {
                 Check( l < static_cast<int>( concentrations.size() ) );
                 adjoint_source_term_decay[n] += a[onon] * concentrations[l];
                 non0_[n] = non0_[n] - 1;
                 kd_[n] = kd_[n] - 1;
             }
             else
             {
                 // Ok, copy
                 ++nnon;
                 a[nnon] = a[onon];
                 loc[nnon] = loc[onon];
             }
         }
         // all non-decay parents
         loopMax =
             ( non0_[n] - kd_[n] );  // Keep invariant, even when kd_[n] changes
         for( int i = 0; i < loopMax; i++ )
         {
             ++onon;
             l = loc[onon];
             if( std::fabs( dis[l] + tocap[l] ) < DBL_MIN )
             {
                 Check( l < static_cast<int>( concentrations.size() ) );
                 adjoint_source_term_reaction[n] +=
                     a[onon] * concentrations[l] * fx;
                 non0_[n] = non0_[n] - 1;
             }
             else
             {
                 // Ok, copy
                 ++nnon;
                 a[nnon] = a[onon];
                 loc[nnon] = loc[onon];
             }
         }
     }
     // Set the new matrix sizes
     non = nnon + 1;
     // Rebuild KD and NON0
     expand_matrix_pointers();
     lib_non_buffer_int.clear();
     lib_non_buffer_dbl.clear();
     // Copy A-matrix and LOC to temporary buffers
     for( int i = 0; i < non; i++ )
     {
         lib_non_buffer_dbl.push_back( a[i] );
         lib_non_buffer_int.push_back( loc[i] );
     }
     Check( static_cast<int>( lib_non_buffer_dbl.size() ) == non );
     Check( static_cast<int>( lib_non_buffer_int.size() ) == non );
     // Reallocate the NON-sized arrays (a_matrix and loc_ary) so their allocated
     // sizes matches their true sizes
     a.clear();
     loc.clear();
     // Copy back from buffer into resized arrays
     for( int i = 0; i < non; i++ )
     {
         a.push_back( lib_non_buffer_dbl[i] );
         loc.push_back( lib_non_buffer_int[i] );
     }
     Check( static_cast<int>( a.size() ) == non );
     Check( static_cast<int>( loc.size() ) == non );
     lib_non_buffer_dbl.clear();
     lib_non_buffer_int.clear();
     // Debug output
     float astdSum = std::accumulate( adjoint_source_term_decay.begin(),
                                      adjoint_source_term_decay.end(),
                                      0.0 );
     float astrSum = std::accumulate( adjoint_source_term_reaction.begin(),
                                      adjoint_source_term_reaction.end(),
                                      0.0 );
     SErrLine( 2,
               "Total decay adjoint source term is: "
                   << astdSum
                   << std::endl
                   << "Total reaction adjoint source term is: "
                   << astrSum );
 }
void fold_flux (double flux, DoubleList & d, DoubleList & a_fold)
Produce the compressed transition matrix A and the diagonal array D, applying the given flux
Parameters
flux Flux in [n/cm^2*s]
d Diagonal array D [itot]
a_fold Compressed transition matrix A [non]
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::a, TransitionMatrixP::dis, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::non, TransitionMatrixP::non0, and TransitionMatrixP::tocap.
Referenced by GetDenseMatrix(), Solver_cram::solve_impl(), Solver_matrex::solve_impl(), and Origen::test::TEST().
 {
     Require( flux >= 0.0 );
     // flux:         incident flux in n/cm^2*s
     // d[itot]:      Diagonal array D
     // a_fold[non]:  Compressed transition matrix A
     // Converted flux to n/bcms (flux[n/cm^2*s] * 1e-24)
     double flx = flux * 1.0e-24;
     // Initialize vectors
     d.resize( itot );
     a_fold.assign( a.begin(),
                    a.end() );  // Initialize to the A matrix of this class
     Check( static_cast<int>( a_fold.size() ) == non );
     Check( static_cast<int>( d.size() ) == itot );
     Check( static_cast<int>( tocap.size() ) == itot );
     Check( static_cast<int>( kd.size() ) == itot );
     Check( static_cast<int>( non0.size() ) == itot );
     Check( static_cast<int>( dis.size() ) == itot );
     for( int i = 0; i < itot; ++i )
     {
         d[i] = -( dis[i] + tocap[i] * flx );
         // Go through all reaction matrix elements
         int n = kd[i];
         const int n_end = non0[i];
         Check( n >= 0 );
         Check( n <= n_end );
         Check( n_end <= static_cast<int>( a_fold.size() ) );
         for( ; n != n_end; ++n )
         {
             a_fold[n] = a[n] * flx;
         }
     }
     Ensure( static_cast<int>( a_fold.size() ) == non );
     Ensure( static_cast<int>( d.size() ) == itot );
 }
int first_transition (const int n, bool fortran_offset = false)
Return the index (in A) of the first transition of the nuclide with index n (in N)
Parameters
n Nuclide index in nucl
Returns
Index (in A) of first transition of the nuclide with index n (in nucl)
References TransitionMatrixP::itot, TransitionMatrixP::non, TransitionMatrixP::non0, and TransitionMatrixP::non0_.
Referenced by TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::find_parents(), and TransitionMatrixP::toQString_transitions().
 {
     int transition = -1;
     Insist( n >= 0, "Range index given to first_transition is negative!" );
     Insist( n < itot, "Range index given to first_transition is too high!" );
     if( n == 0 )
     {
         transition = 0;
     }
     else
     {
         transition = non0[n - 1];
     }
     if( non0_[n] == 0 ) transition = non;
     // Check the range of the result
     Insist( transition >= 0,
             "Transition index (FTI) for first_transition is negative! NON0 is "
             "probably corrupted." );
     Insist( transition < non + 1,
             "Transition index (FTI) is for first_transition is too high! NON0 "
             "is probably corrupted." );
     if( fortran_offset ) transition += 1;
     return transition;
 }
int last_transition (const int n, double flux = 0.0)
Return the index (in A) of the last transition of the nuclide with index n (in N)
Parameters
n Nuclide index in nucl
flux [OPTIONAL] Flux in [n/cm^2*s]
Returns
Index (in A) of last transition of nuclide with index n (in nucl)
References TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::non, and TransitionMatrixP::non0.
Referenced by TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::find_parents(), and TransitionMatrixP::toQString_transitions().
 {
     int transition = -1;
     Insist( n >= 0, "Range index given to last_transition is negative!" );
     Insist( n < itot, "Range index given to last_transition is too high!" );
     // Assign the pointer; use only decay for zero flux, otherwise all reactions
     if( flux > 0.0 )
     {
         transition = non0[n];
     }
     else
     {
         transition = kd[n];
     }
     // Check the range of the result
     Insist( transition >= 0,
             "Transition index (FTI) for last_transition is negative! NON0 is "
             "probably corrupted." );
     Insist( transition <= non,
             "Transition index (FTI) for last_transition is too high! NON0 is "
             "probably corrupted." );
     return transition;
 }
int num_massive_daughters (const int mt_in)
Number of massive daughters resulting from a given reaction (used to normalize set_xs/get_xs)
Parameters
mt reaction MT
Returns
number of daughters with mass
Referenced by TransitionMatrixP::fast_set_xs(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), and TransitionMatrixP::set_xs().
 {
     // MT:      MT of the reaction
     int num = 0;
     switch( mt_in )
     {
         // a single massive daughter product
         case 16:
         case 17:
         case 28:
         case 37:
         case 51:
         case 102:
         case 103:
         case 111:
             num = 1;
             break;
         // two  massive daughter products
         case 22:
         case 23:
         case 24:
         case 25:
         case 32:
         case 33:
         case 34:
         case 104:
         case 105:
         case 106:
         case 107:
         case 112:
             num = 2;
             break;
         // three massive daughters
         case 29:
         case 41:
         case 108:
             num = 3;
             break;
         default:
             std::stringstream ss;
             ss << "developer error: num_massive daughters not known for mt="
                << mt_in;
             Insist( false, ss.str() );
     }
     return num;
 }
bool has_valid_mts () const
Does this library have valid MTs?
Returns
true or false
References TransitionMatrixP::_cached_has_valid_mts, TransitionMatrixP::mt, and TransitionMatrixP::non.
Referenced by TransitionMatrixP::fast_set_xs(), TransitionMatrixP::get_xs(), TransitionMatrixP::set_xs(), and TransitionMatrixP::setup_fast_transition_access().
 {
     Require( static_cast<int>( mt.size() ) == non );
     if( !_cached_has_valid_mts )
     {
         bool innocent = false;
         for( int k = 0; k < non; k++ )
         {
             innocent = ( mt[k] <= -1 ) || ( mt[k] > 1 && mt[k] < 99999 );
             if( !innocent )
             {
                 break;
             }
         }
         _cached_has_valid_mts = innocent;
     }
     return _cached_has_valid_mts;
 }
bool is_mts_properly_ordered (const IntegerList & mts)
Are the MTs properly ordered in a transition list (decays then reactions)?
Returns
true or false
References kernel_matrex::decay().
Referenced by TransitionMatrixP::find_parents().
 {
     bool proper = true;
     int decay = 0, reaction = 0;
     for( size_t k = 0; k < mts.size(); k++ )
     {
         if( mts.at( k ) < 0 )
         {
             decay++;
             // decays must come first
             if( reaction > 0 )
             {
                 proper = false;
                 break;
             }
         }
         else if( mts.at( k ) > 0 )
         {
             reaction++;
         }
         else
         {
             // can't have a 0
             proper = false;
             break;
         }
     }
     return proper;
 }
void find_all_mts (IntegerList & mts)
Find all MTs on the library.
Parameters
mts list of MTs [OUTPUT]
References TransitionMatrixP::mt, and TransitionMatrixP::non.
Referenced by TransitionMatrixP::toQString_cross_sections(), and TransitionMatrixP::toQString_mts().
 {
     // get set of all MTs
     QSet<int> set;
     for( int k = 0; k < non; k++ )
     {
         if( mt[k] > 0 )
         {
             set.insert( mt[k] );
         }
     }
     // convert to list and sort
     QList<int> list = set.toList();
     qSort( list );
     // assemble IntegerList to return
     mts.clear();
     for( int k = 0; k < list.size(); k++ )
     {
         mts.push_back( list[k] );
     }
     return;
 }
void find_parents (const int nind, IntegerList & parents, IntegerList & mts, IntegerList & tinds)
Determine from a target nuclide, all parents and transitions creating the target.
Parameters
nind target nuclide (index)
parents list of parents of the target [OUTPUT]
mts list of MTs for those transitions to the target [OUTPUT]
tinds list of transition matrix indices for the transitions [OUTPUT]
References TransitionMatrixP::first_transition(), TransitionMatrixP::is_mts_properly_ordered(), TransitionMatrixP::itot, TransitionMatrixP::last_transition(), TransitionMatrixP::loc, and TransitionMatrixP::mt.
 {
     Require( nind >= 0 && nind < itot );
     // nind:          target nuclide (index)
     parents.clear();
     mts.clear();
     tinds.clear();
     for( int k = this->first_transition( nind );
          k < this->last_transition( nind, 1.0 );
          k++ )
     {
         parents.push_back( loc[k] );
         mts.push_back( mt[k] );
         tinds.push_back( k );
     }
     Ensure( is_mts_properly_ordered( mts ) );
     return;
 }
void find_daughters (const int nind, IntegerList & daughters, IntegerList & mts, IntegerList & tinds)
Determine from a target nuclide, all daughters and transitions to those daughters.
Parameters
nind target nuclide (index)
daughters list of daughters of the target [OUTPUT]
mts list of MTs for those transitions from the target [OUTPUT]
tinds list of transition matrix indices for the transitions [OUTPUT]
References TransitionMatrixP::itot, TransitionMatrixP::loc, TransitionMatrixP::mt, and TransitionMatrixP::non0_.
Referenced by TransitionMatrixP::setup_fast_transition_access(), and TransitionMatrixP::toQString_nuclides().
 {
     Require( nind >= 0 && nind < itot );
     // nind:          target nuclide (index)
     daughters.clear();
     mts.clear();
     tinds.clear();
     // must iterate through entire A matrix but do it a daughter at a time
     int k = -1;
     for( int j = 0; j < itot; j++ )
     {
         for( int i = 0; i < non0_[j]; i++ )
         {
             k++;
             if( loc[k] == nind )
             {
                 daughters.push_back( j );
                 mts.push_back( mt[k] );
                 tinds.push_back( k );
             }
         }
     }
     // daughters don't have a good order we can ensure
     return;
 }
void clear_tinds_2d (Integer2dList & tinds_2d)
Clear transition indices, e.g. created by setup_fast_transition_access.
Parameters
tinds_2d lists the indices of the transitions (Integer2dList)
Referenced by TransitionMatrixP::setup_fast_transition_access().
 {
     for( size_t i = 0; i < tinds_2d.size(); i++ )
     {
         IntegerList* tinds1 = tinds_2d[i];
         delete tinds1;
     }
     tinds_2d.clear();
 }
void setup_fast_transition_access (const IntegerList & ninds, const IntegerList & mts, Integer2dList & tinds_2d)
Setup fast transitions for accessing cross sections by nuclide index and MT.
Parameters
ninds target nuclides (index)
mts target MTs
tinds_2d for each ninds[i] and mts[i], lists the indices of the transitions [OUTPUT]
References TransitionMatrixP::bounds, TransitionMatrixP::clear_tinds_2d(), TransitionMatrixP::find_daughters(), TransitionMatrixP::fiss, TransitionMatrixP::has_valid_mts(), TransitionMatrixP::ilite, TransitionMatrixP::nucl, Origen::SUBLIB_2AC, and Origen::toQString_tinds_2d().
 {
     Insist( has_valid_mts(),
             "library must have valid MTs to setup_fast_transition_access" );
     Require( ninds.size() == mts.size() );
     this->clear_tinds_2d( tinds_2d );
     IntegerList trash_daughters, trash_mts;  // dummies
     for( size_t i = 0; i < ninds.size(); i++ )
     {
         int n = ninds[i];
         int mt_in = mts[i];
         // special checks for fission
         if( mt_in == 18 )
         {
             // only actinides have fission xs
             Check( ( n >= bounds[SUBLIB_2AC][0] ) &&
                    ( n < bounds[SUBLIB_2AC][1] ) );
             // only allow perturbations for nonzero existing xs on library
             double old_fiss = fiss[n - ilite];
             if( old_fiss == 0.0 )
             {
                 SOutLine( 2,
                           "will not change xs because old fission xs was zero "
                           "for nucl="
                               << nucl[n] );
             }
         }
         // setup locals
         trash_mts.clear();
         trash_daughters.clear();
         IntegerList tinds0;
         // lets find daughters do all the heavy lifting
         this->find_daughters( n, trash_daughters, trash_mts, tinds0 );
         if( tinds0.size() == 0 )
         {
             SOutLine( 2, "no daughters for nucl=" << nucl[n] );
         }
         // then we filter based on mts
         IntegerList* tinds1 =
             new IntegerList;  // needs to be on the heap so we can save it
         for( size_t k = 0; k < trash_mts.size(); k++ )
         {
             if( mt_in == trash_mts[k] )
             {
                 tinds1->push_back( tinds0[k] );
             }
         }
         // finally we push back the pointer
         tinds_2d.push_back( tinds1 );
     }
     jDebugBlock(
         std::cerr << "---" << std::endl;
         std::cerr << "transitions leaving setup_fast_transition_access: "
                   << std::endl;
         toQString_tinds_2d( ninds, mts, tinds_2d );
         std::cerr << "---" << std::endl; );
     return;
 }
void fast_set_xs (const IntegerList & ninds, const IntegerList & mts, const Integer2dList & tinds_2d, const DoubleList & new_xs)
Fast setting of cross sections with generated tinds_2d.
Parameters
ninds list of target nuclides (index)
mts list of target MTs
tinds_2d created from setup_fast_transition_access
new_xs list of new cross sections
References TransitionMatrixP::a, TransitionMatrixP::fiss, TransitionMatrixP::has_valid_mts(), TransitionMatrixP::ilite, TransitionMatrixP::num_massive_daughters(), TransitionMatrixP::tocap, and Origen::toQString_tinds_2d().
 {
     Insist( has_valid_mts(), "library must have valid MTs to fast_set_xs" );
     Require( ninds.size() == mts.size() );
     Require( mts.size() == tinds_2d.size() );
     Require( new_xs.size() == tinds_2d.size() );
     jDebugBlock( std::cout << "---" << std::endl;
                  std::cout << "transitions entering fast_set_xs: " << std::endl;
                  toQString_tinds_2d( ninds, mts, tinds_2d );
                  std::cout << "---" << std::endl; );
     for( size_t i = 0; i < ninds.size(); i++ )
     {
         int n = ninds[i];
         int mt_in = mts[i];
         IntegerList* tinds1 = tinds_2d[i];
         if( mt_in == 18 )
         {
             double old_fiss = fiss[n - ilite];
             if( old_fiss != 0.0 )
             {
                 // must search whole matrix to change yields
                 for( size_t j = 0; j < tinds1->size(); j++ )
                 {
                     int k = tinds1->at( j );
                     a[k] *= new_xs[i] /
                             old_fiss;  // implicitly keep fission yield the same
                 }
                 // update vectors
                 fiss[n - ilite] = new_xs[i];
                 tocap[n] += new_xs[i] - old_fiss;
             }
         }
         else
         {
             // must do a loop first to properly accumulate the old cross section
             double old_xs = 0;
             for( size_t j = 0; j < tinds1->size(); j++ )
             {
                 int k = tinds1->at( j );
                 old_xs += a[k];
             }
             // normalize by number of massive daughters (important for alpha
             // producing reactions)
             old_xs /= num_massive_daughters( mt_in );
             for( size_t j = 0; j < tinds1->size(); j++ )
             {
                 int k = tinds1->at( j );
                 a[k] *= new_xs[i] /
                         old_xs;  // implicitly keep branching ratio the same
             }
             // update total capture
             tocap[n] += new_xs[i] - old_xs;
         }
     }
     return;
 }
void remove_fp_reactions ()
Remove fission product absorptions.
References TransitionMatrixP::a, TransitionMatrixP::bounds, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::loc, TransitionMatrixP::non0, Origen::SUBLIB_3FP, TransitionMatrixP::tocap, and TransitionMatrixP::typ_nuc.
 {
     for( int i = 0; i < itot; i++ )
     {
         // All reactions
         for( int n = kd[i]; n < non0[i]; n++ )
         {
             // Remove entry from A-matrix for F.P. nuclide type
             if( typ_nuc[loc[n]] == ( SUBLIB_3FP ) )
             {
                 a[n] = 0.0;
             }
         }
     }
     // Zero out capture
     for( int idx = bounds[SUBLIB_3FP][0]; idx < bounds[SUBLIB_3FP][1]; idx++ )
     {
         tocap[idx] = 0.0;
     }
 }
int get_ilite () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::ilite.
Referenced by h5_write_trx(), Case::load_new_concentrations(), and TEST().
 { return ilite; }
int get_iact () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::iact.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), h5_write_trx(), and TEST().
 { return iact; }
int get_ifp () const inline
Examples:
Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::ifp.
Referenced by h5_write_trx().
 { return ifp; }
int get_itot () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, Core/io/tests/tstMaterialBuffer.cpp, and Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::itot.
Referenced by Case::Case(), GetDenseMatrix(), h5_write_trx(), Case::load_new_concentrations(), Case::set_conc(), Case::set_conc0(), Case::set_feed_rate(), Case::set_feed_rates_by_vector(), Case::set_initial_concentrations_by_vector(), Case::set_reprocessing_rate(), Solver_cram::solve_impl(), Solver_matrex::solve_impl(), TEST(), and Origen::test::TEST().
 { return itot; }
int get_non () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::non.
Referenced by Solver_cram::solve_impl(), Solver_matrex::solve_impl(), TEST(), and Origen::test::TEST().
 { return non; }
int get_nfluxgrp () const inline
Examples:
Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::nfluxgrp.
Referenced by h5_write_trx().
 { return nfluxgrp; }
int get_nti () const inline
References TransitionMatrixP::nti.
 { return nti; }
int get_nfiso () const inline
References TransitionMatrixP::nfiso.
 { return nfiso; }
int get_pos () const inline
References TransitionMatrixP::pos.
 { return pos; }
int get_nmonth () const inline
References TransitionMatrixP::nmonth.
 { return nmonth; }
int get_nday () const inline
References TransitionMatrixP::nday.
 { return nday; }
int get_nyear () const inline
References TransitionMatrixP::nyear.
 { return nyear; }
float get_burnup () const inline
References TransitionMatrixP::burnup.
 { return burnup; }
const char* get_filename () const inline
References TransitionMatrixP::filename.
 { return filename.c_str(); }
const IntegerList* get_typ_nuc () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::typ_nuc.
Referenced by Case::set_feed_rates_by_vector(), Case::set_initial_concentrations_by_vector(), and TEST().
 { return &typ_nuc; }
const IntegerList* get_nucl () const inline
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::nucl.
Referenced by Case::load_new_concentrations(), Case::set_feed_rates_by_vector(), Case::set_initial_concentrations_by_vector(), Solver_cram::solve_impl(), and Origen::test::TEST().
 { return &nucl; }
IntegerList* get_nucl () inline
References TransitionMatrixP::nucl.
 { return &nucl; }
const IntegerList* get_kd_ () const inline
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::kd_.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), Solver_cram::solve_impl(), and Origen::test::TEST().
 { return &kd_; }
IntegerList* get_kd_ () inline
References TransitionMatrixP::kd_.
 { return &kd_; }
const IntegerList* get_non0_ () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::non0_.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), GetDenseMatrix(), Solver_cram::solve_impl(), and Origen::test::TEST().
 { return &non0_; }
IntegerList* get_non0_ () inline
References TransitionMatrixP::non0_.
 { return &non0_; }
const IntegerList* get_kd () const inline
References TransitionMatrixP::kd.
 { return &kd; }
IntegerList* get_kd () inline
References TransitionMatrixP::kd.
 { return &kd; }
const IntegerList* get_non0 () const inline
References TransitionMatrixP::non0.
 { return &non0; }
IntegerList* get_non0 () inline
References TransitionMatrixP::non0.
 { return &non0; }
const IntegerList* get_loc () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::loc.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), GetDenseMatrix(), Solver_cram::solve_impl(), TEST(), and Origen::test::TEST().
 { return &loc; }
IntegerList* get_loc () inline
References TransitionMatrixP::loc.
 { return &loc; }
void get_kd_array (size_t n, int * out) const
References TransitionMatrixP::itot, and TransitionMatrixP::kd.
 {
     Require( n == itot );
     std::memcpy( out, &kd[0], n * sizeof( int ) );
 }
void get_non0_array (size_t n, int * out) const
References TransitionMatrixP::itot, and TransitionMatrixP::non0.
 {
     Require( n == itot );
     std::memcpy( out, &non0[0], n * sizeof( int ) );
 }
void get_loc_array (size_t n, int * out, bool fortran_offset) const
References TransitionMatrixP::loc, and TransitionMatrixP::non.
 {
     Require( n == non );
     std::memcpy( out, &loc[0], n * sizeof( int ) );
     if( fortran_offset )
         for( size_t i = 0; i < n; ++i ) ++out[i];
 }
size_t kd_size () const inline
References TransitionMatrixP::itot.
 { return static_cast<size_t>( itot ); }
size_t non0_size () const inline
References TransitionMatrixP::itot.
 { return static_cast<size_t>( itot ); }
size_t loc_size () const inline
References TransitionMatrixP::non.
 { return static_cast<size_t>( non ); }
const IntegerList* get_mt () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::mt.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), and TEST().
 { return &mt; }
const IntegerList* get_nucfis () const inline
References TransitionMatrixP::nucfis.
 { return &nucfis; }
const FloatList* get_dis () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::dis.
Referenced by Case::load_new_concentrations(), and TEST().
 { return &dis; }
FloatList* get_dis () inline
References TransitionMatrixP::dis.
 { return &dis; }
const FloatList* get_genneu () const inline
Examples:
Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::genneu.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), and h5_write_trx().
 { return &genneu; }
FloatList* get_genneu () inline
References TransitionMatrixP::genneu.
 { return &genneu; }
const FloatList* get_q () const inline
References TransitionMatrixP::q.
 { return &q; }
const FloatList* get_fg () const inline
References TransitionMatrixP::fg.
 { return &fg; }
const FloatList* get_ampc () const inline
References TransitionMatrixP::ampc.
 { return &ampc; }
const FloatList* get_wmpc () const inline
References TransitionMatrixP::wmpc.
 { return &wmpc; }
const FloatList* get_abund () const inline
References TransitionMatrixP::abund.
Referenced by Case::load_new_concentrations().
 { return &abund; }
const FloatList* get_wabund () const inline
References TransitionMatrixP::wabund.
Referenced by Case::load_new_concentrations().
 { return &wabund; }
const FloatList* get_spectrum () const inline
Examples:
Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::spectrum.
Referenced by h5_write_trx().
 { return &spectrum; }
const DoubleList* get_a () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::a.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), h5_write_trx(), and TEST().
 { return &a; }
DoubleList* get_a () inline
References TransitionMatrixP::a.
 { return &a; }
const DoubleList* get_tocap () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::tocap.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), h5_write_trx(), and TEST().
 { return &tocap; }
DoubleList* get_tocap () inline
References TransitionMatrixP::tocap.
 { return &tocap; }
const DoubleList* get_fiss () const inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp, and Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::fiss.
Referenced by TransitionMatrixUpdater::get_transition_matrix(), h5_write_trx(), and TEST().
 { return &fiss; }
DoubleList* get_fiss () inline
References TransitionMatrixP::fiss.
 { return &fiss; }
const FloatList* get_m () const inline
References TransitionMatrixP::m.
Referenced by Case::load_new_concentrations().
 { return &m; }
const StringList* get_titles () const inline
References TransitionMatrixP::titles.
 { return &titles; }
void split_id (const int nind, int & S, int & I, int & Z, int & A)
References TransitionMatrixP::nucl, and TransitionMatrixP::typ_nuc.
Referenced by TransitionMatrixP::finish_init(), TransitionMatrixP::toQString_nuclides(), and TransitionMatrixP::toQString_sizzzaaa().
 {
     Require( (size_t)nind < nucl.size() );
     Require( (size_t)nind < typ_nuc.size() );
     int zam = nucl[nind];
     Z = zam / 10000;          // atomic number
     A = zam / 10 - 1000 * Z;  // atomic weight
     I = zam % 10;             // meta-stable state
     S = typ_nuc[nind];
 }
std::vector< double > get_xs_stdvec (const int mt_in)
References TransitionMatrixP::a, TransitionMatrixP::fiss, TransitionMatrixP::iact, TransitionMatrixP::ilite, TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::nucl, TransitionMatrixP::num_massive_daughters(), and TransitionMatrixP::tocap.
Referenced by TransitionMatrixP::toQString_cross_section_mt().
 {
     std::vector<double> xs( nucl.size(), 0.0 );
     if( mt_in == 18 )
     {
         for( int i = ilite; i < ilite + iact; i++ )
         {
             xs[i] = fiss[i - ilite];
         }
     }
     else if( mt_in == 27 )
     {
         xs = tocap;
     }
     else
     {
         for( size_t tind = 0; tind < a.size(); tind++ )
         {
             if( mt[tind] == mt_in )
             {
                 xs[loc[tind]] += a[tind];
             }
         }
         for( size_t i = 0; i < nucl.size(); i++ )
         {
             xs[i] /= num_massive_daughters( mt_in );
         }
     }
     return xs;
 }
QString toQString_title ()
References TransitionMatrixP::nti, and TransitionMatrixP::titles.
Referenced by TransitionMatrixP::toQString_info().
 {
     QString tit;
     for( int i = 0; i < nti; i++ )
     {
         if( titles[i].compare( "    " ) != 0 )
         {
             if( i > 0 && ( titles[i - 1].compare( "    " ) == 0 ) )
             {
                 tit.append( "\n" );
             }
             tit.append( titles[i].c_str() );
         }
     }
     return tit;
 }
QString toQString_sizzzaaa (const int nind)
References TransitionMatrixP::split_id().
Referenced by TransitionMatrixP::emsgn(), TransitionMatrixP::toQString_cross_section_mt(), TransitionMatrixP::toQString_nuclides(), and TransitionMatrixP::toQString_transitions().
 {
     int S, Z, A, I;
     split_id( nind, S, I, Z, A );
     QString sizzzaaa;
     if( S == 1 )
     {
         sizzzaaa += QString( "1LT" );
     }
     else if( S == 2 )
     {
         sizzzaaa += QString( "2AC" );
     }
     else if( S == 3 )
     {
         sizzzaaa += QString( "3FP" );
     }
     else
     {
         std::cout << "ERROR: nuclide type unknown" << std::endl;
     }
     sizzzaaa += QString( ":%1:%2:%3" )
                     .arg( I, 1 )
                     .arg( Z, 3, 10, QChar( '0' ) )
                     .arg( A, 3, 10, QChar( '0' ) );
     return sizzzaaa;
 }
QString toQString (const int sigdigs, const char * trans_sort, const double eps_sigma, const double eps_decay)
Examples:
Manager/libld/tests/tstTransitionMatrixUpdater.cpp.
References TransitionMatrixP::toQString_cross_sections(), TransitionMatrixP::toQString_info(), TransitionMatrixP::toQString_mts(), TransitionMatrixP::toQString_nuclides(), TransitionMatrixP::toQString_sizes(), and TransitionMatrixP::toQString_transitions().
Referenced by Origen::test::TEST().
 {
     QString str;  // output string
     str += toQString_info();
     str += toQString_sizes();
     str += toQString_mts();
     str += toQString_nuclides( sigdigs );
     str += toQString_cross_sections( sigdigs, eps_sigma );
     str += toQString_transitions( sigdigs,
                                   trans_sort,
                                   eps_sigma,
                                   eps_decay );  // all in one list
     return str;
 }
QString toQString_mts ()
References TransitionMatrixP::find_all_mts().
Referenced by TransitionMatrixP::toQString().
 {
     QString str;  // output string
     // OrigenLibrary does not store this mt list so we need to generate it
     // on-the-fly
     IntegerList mts;
     this->find_all_mts( mts );
     str += QString( "MTS %1\n" ).arg( mts.size() + 1 );
     str += QString( "%1   ### %2 %3 %4 %5 %6 %7 %8 %9\n" )
                .arg( "mt", 7 )
                .arg( "mind", 7 )
                .arg( "reaction", 12 )
                .arg( "n", 1 )
                .arg( "p", 1 )
                .arg( "d", 1 )
                .arg( "t", 1 )
                .arg( "3he", 3 )
                .arg( "a", 3 );
     int num_n, num_p, num_d, num_t, num_3he, num_a;
     for( size_t i = 0; i < mts.size(); i++ )
     {
         ScaleData::Utils::mt_to_num_byproducts(
             mts[i], num_n, num_p, num_d, num_t, num_3he, num_a );
         QString qreaction( ScaleData::Utils::mt_to_reaction( mts[i] ).c_str() );
         str += QString( "%1   ### %2 %3 %4 %5 %6 %7 %8 %9\n" )
                    .arg( mts[i], 7 )
                    .arg( i, 7 )
                    .arg( qreaction, 12 )
                    .arg( num_n, 1 )
                    .arg( num_p, 1 )
                    .arg( num_d, 1 )
                    .arg( num_t, 1 )
                    .arg( num_3he, 3 )
                    .arg( num_a, 3 );
     }
     // std::cout << str.toStdString();
     return str;
 }
QString toQString_info ()
References TransitionMatrixP::burnup, TransitionMatrixP::filename, TransitionMatrixP::nti, TransitionMatrixP::pos, and TransitionMatrixP::toQString_title().
Referenced by TransitionMatrixP::toQString().
 {
     QString str;  // output string
     QString tit = this->toQString_title();
     QString sp =
         QString( " " ).repeated( 26 + 1 );  // 1 for the space between %1 and %2
     sp.append( "   ### " );
     tit.prepend( sp );
     tit.replace( "\n", "\n" + sp );
     tit.append( "\n" );
     int nc = tit.count( "\n" );
     str += QString( "INFO %1\n" ).arg( 7 + nc );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "variable", 16 )
                .arg( "value", -10 )
                .arg( "description" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "pos", 16 )
                .arg( pos, -10 )
                .arg(
                    "Position number of the burnup-dependent XS set in the "
                    "library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "burnup", 16 )
                .arg( burnup, -10, 'f', 3 )
                .arg( "Burnup [MWd/tU] of the library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "nti", 16 )
                .arg( nti, -10 )
                .arg( "Number of title card chunks" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "filename", 16 )
                .arg( filename.c_str(), -10 )
                .arg( "Base filename of the library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "nc", 16 )
                .arg( nc, -10 )
                .arg( "Number of title card lines" );
     str += QString(
                "%1 %2   ### follows on the remaining %3 lines preprended with "
                "{### }\n" )
                .arg( "title", 16 )
                .arg( "-", -10 )
                .arg( nc );
     str += tit;
     // std::cout << str.toStdString();
     return str;
 }
QString toQString_sizes ()
References TransitionMatrixP::iact, TransitionMatrixP::ifp, TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionMatrixP::nfiso, TransitionMatrixP::nfluxgrp, TransitionMatrixP::non, and TransitionMatrixP::nti.
Referenced by TransitionMatrixP::toQString().
 {
     QString str;  // output string
     str += QString( "SIZES %1\n" ).arg( 15 );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "variable", 16 )
                .arg( "value", -10 )
                .arg( "description" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "non", 16 )
                .arg( non, -10 )
                .arg(
                    "Number of non-zero off-diagonal elements of the transition "
                    "matrix A" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "ilite", 16 )
                .arg( ilite, -10 )
                .arg(
                    "Number of light-element activation product nuclides in the "
                    "library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "iact", 16 )
                .arg( iact, -10 )
                .arg( "Number of actinide nuclides in the library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "ifp", 16 )
                .arg( ifp, -10 )
                .arg( "Number of fission product nuclides in the library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "itot", 16 )
                .arg( itot, -10 )
                .arg( "Total number of nuclides in the library" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "nfluxgrp", 16 )
                .arg( nfluxgrp, -10 )
                .arg( "Number of energy groups in the collapse spectrum" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "nti", 16 )
                .arg( nti, -10 )
                .arg( "Number of title cards" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "nfiso", 16 )
                .arg( nfiso, -10 )
                .arg( "Number of fissionable isotopes" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "first_lite", 16 )
                .arg( 0, -10 )
                .arg( "First nuclide index of light-elements" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "last_lite", 16 )
                .arg( ilite - 1, -10 )
                .arg( "Last nuclide index of light-elements" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "first_act", 16 )
                .arg( ilite, -10 )
                .arg( "First nuclide index of actinides" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "last_act", 16 )
                .arg( ilite + iact - 1, -10 )
                .arg( "Last nuclide index of actinides" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "first_fp", 16 )
                .arg( ilite + iact, -10 )
                .arg( "First nuclide index of fission products" );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "last_fp", 16 )
                .arg( ilite + iact + ifp - 1, -10 )
                .arg( "Last nuclide index of fission products" );
     // std::cout << str.toStdString();
     return str;
 }
QString toQString_nuclides (const int sigdigs)
References TransitionMatrixP::find_daughters(), TransitionMatrixP::m, TransitionMatrixP::nucl, TransitionMatrixP::split_id(), and TransitionMatrixP::toQString_sizzzaaa().
Referenced by TransitionMatrixP::toQString().
 {
     QString str;  // output string
     str += QString( "NULCIDES %1\n" ).arg( nucl.size() + 1 );
     const int qprec =
         sigdigs - 1;  // precision in QString is according to number of decimals
     str += QString( "%1 %2 ### %3 %4 %5\n" )
                .arg( "S:I:ZZZ:AAA", 13 )
                .arg( "mass", 7 )
                .arg( "nind", 5 )
                .arg( "sym", 6 )
                .arg( " mt-list", 8 );
     for( size_t i = 0; i < nucl.size(); i++ )
     {
         QString id = toQString_sizzzaaa( i );
         IntegerList dds, ddm, tdd;
         this->find_daughters( i, dds, ddm, tdd );
         std::list<int> ddmu;
         for( size_t k = 0; k < dds.size(); k++ )
         {
             ddmu.push_back( ddm[k] );
         }
         ddmu.unique();
         ddmu.sort();
         int S, I, Z, A;
         split_id( i, S, I, Z, A );
         int ZAM = Z * 10000 + A * 10 + I;
         str +=
             QString( "%1 %2 ### %3 %4" )
                 .arg( id, 13 )
                 .arg( m[i], 7, 'f', qprec )
                 .arg( i, 5 )
                 .arg( ScaleData::Utils::zzzaaai_to_symbol( ZAM ).c_str(), 6 );
         while( !ddmu.empty() )
         {
             str += QString( " %1" ).arg( ddmu.front(), 3 );
             ddmu.pop_front();
         }
         str += QString( "\n" );
     }
     // std::cout << str.toStdString();
     return str;
 }
QString toQString_transitions (const int sigdigs, const char * trans_sort, double const eps_sigma = 0.0, double const eps_decay = 0.0)
References TransitionMatrixP::a, TransitionMatrixP::first_transition(), TransitionMatrixP::last_transition(), TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::nucl, and TransitionMatrixP::toQString_sizzzaaa().
Referenced by TransitionMatrixP::toQString().
 {
     QString str;  // output string
     const int qprec =
         sigdigs - 1;  // precision in QString is according to number of decimals
     str += QString( "%1 <-- %2 %3 %4   ### %5\n" )
                .arg( "daughter", 13 )
                .arg( "parent", 13 )
                .arg( "mt", 7 )
                .arg( "coeff", 15 )
                .arg( "tind", 7 );
     for( size_t i = 0; i < nucl.size(); i++ )
     {
         QString daughter = this->toQString_sizzzaaa( i );
         for( int tind = this->first_transition( i );
              tind < this->last_transition( i, 1.0 );
              tind++ )
         {
             QString parent = this->toQString_sizzzaaa( loc[tind] );
             if( ( mt[tind] > 0 && ( a[tind] >= eps_sigma ) ) ||
                 ( mt[tind] <= 0 && ( a[tind] >= eps_decay ) ) )
             {
                 str += QString( "%1 <-- %2 %3 %4   ### %5\n" )
                            .arg( daughter, 13 )
                            .arg( parent, 13 )
                            .arg( mt[tind], 7 )
                            .arg( a[tind], 15, 'e', qprec )
                            .arg( tind, 7 );
             }
         }
     }
     // get header at the end after we know how many lines
     str.prepend( QString( "TRANSITIONS %1\n" ).arg( str.count( "\n" ) ) );
     return str;
 }
QString toQString_cross_section_mt (const int mt_in, const int sigdigs, double const eps_sigma = 0.0)
References TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::nucl, and TransitionMatrixP::toQString_sizzzaaa().
Referenced by TransitionMatrixP::toQString_cross_sections().
 {
     QString str;  // output string
     str += QString( "CROSS_SECTIONS_MT%1 %2\n" )
                .arg( mt_in )
                .arg( nucl.size() + 1 );
     std::vector<double> xs = get_xs_stdvec( mt_in );
     str += QString( "%1 %2   ### %3\n" )
                .arg( "S:I:ZZZ:AAA", 13 )
                .arg( "xs", 15 )
                .arg( "nind", 7 );
     for( size_t i = 0; i < nucl.size(); i++ )
     {
         if( xs[i] >= eps_sigma )
         {
             QString sizzzaaa = this->toQString_sizzzaaa( i );
             str += QString( "%1 %2   ### %3\n" )
                        .arg( sizzzaaa, 13 )
                        .arg( xs[i], 15, 'e', sigdigs )
                        .arg( i, 7 );
         }
     }
     // std::cout << str.toStdString();
     return str;
 }
QString toQString_cross_sections (const int sigdigs, double const eps_sigma = 0.0)
References TransitionMatrixP::find_all_mts(), and TransitionMatrixP::toQString_cross_section_mt().
Referenced by TransitionMatrixP::toQString().
 {
     QString str;  // output string
     // OrigenLibrary does not store this mt list so we need to generate it
     // on-the-fly
     IntegerList mts;
     this->find_all_mts( mts );
     for( size_t i = 0; i < mts.size(); i++ )
     {
         str += toQString_cross_section_mt( mts[i], sigdigs, eps_sigma );
     }
     // std::cout << str.toStdString();
     return str;
 }
void set_itot (int _itot) inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::itot.
Referenced by TEST().
 { itot = _itot; }
void set_ilite (int _ilite) inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::ilite.
Referenced by TEST().
 { ilite = _ilite; }
void set_iact (int _iact) inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::iact.
Referenced by TEST().
 { iact = _iact; }
void set_ifp (int _ifp) inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::ifp.
Referenced by TEST().
 { ifp = _ifp; }
void set_non (int _non) inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::non.
Referenced by TEST().
 { non = _non; }
void set_nmonth (int _month) inline
References TransitionMatrixP::nmonth.
 { nmonth = _month; }
void set_nday (int _day) inline
References TransitionMatrixP::nday.
 { nday = _day; }
void set_nyear (int _year) inline
References TransitionMatrixP::nyear.
 { nyear = _year; }
void set_nfluxgrp (int _nfluxgrp) inline
References TransitionMatrixP::nfluxgrp.
 { nfluxgrp = _nfluxgrp; }
void set_nti (int _nti) inline
References TransitionMatrixP::nti.
 { nti = _nti; }
void set_nfiso (int _nfiso) inline
References TransitionMatrixP::nfiso.
 { nfiso = _nfiso; }
void set_pos (int _pos) inline
References TransitionMatrixP::pos.
Referenced by Library::populate_transition_matrix_reaction().
 { pos = _pos; }
void set_burnup (float _bu) inline
References TransitionMatrixP::burnup.
 { burnup = _bu; }
void set_filename (std::string _fn) inline
References TransitionMatrixP::filename.
 { filename = _fn; }
void set_nucl (IntegerList _nucl)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::itot, and TransitionMatrixP::nucl.
Referenced by TEST().
 {
     Require( static_cast<int>( _nucl.size() ) == itot );
     nucl = _nucl;
 }
void set_kd_ (IntegerList _kd_)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::itot, and TransitionMatrixP::kd_.
Referenced by TEST().
 {
     Require( static_cast<int>( _kd_.size() ) == itot );
     kd_ = _kd_;
 }
void set_non0_ (IntegerList _non0_)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::itot, and TransitionMatrixP::non0_.
Referenced by TEST().
 {
     Require( static_cast<int>( _non0_.size() ) == itot );
     non0_ = _non0_;
 }
void set_kd (IntegerList _kd)
References TransitionMatrixP::itot, and TransitionMatrixP::kd.
 {
     Require( static_cast<int>( _kd.size() ) == itot );
     kd = _kd;
 }
void set_non0 (IntegerList _non0)
References TransitionMatrixP::itot, and TransitionMatrixP::non0.
 {
     Require( static_cast<int>( _non0.size() ) == itot );
     non0 = _non0;
 }
void set_loc (IntegerList _loc)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::loc, and TransitionMatrixP::non.
Referenced by TEST().
 {
     Require( static_cast<int>( _loc.size() ) == non );
     loc = _loc;
 }
void set_a (DoubleList _a)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::a, and TransitionMatrixP::non.
Referenced by TEST().
 {
     Require( static_cast<int>( _a.size() ) == non );
     a = _a;
 }
void set_mt (IntegerList _mt)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::mt, and TransitionMatrixP::non.
Referenced by TEST().
 {
     Require( static_cast<int>( _mt.size() ) == non );
     mt = _mt;
 }
void set_dis (FloatList _dis)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::dis, and TransitionMatrixP::itot.
Referenced by TEST().
 {
     Require( static_cast<int>( _dis.size() ) == itot );
     dis = _dis;
 }
void set_q (FloatList _q)
References TransitionMatrixP::itot, and TransitionMatrixP::q.
 {
     Require( static_cast<int>( _q.size() ) == itot );
     q = _q;
 }
void set_fg (FloatList _fg)
References TransitionMatrixP::fg, and TransitionMatrixP::itot.
 {
     Require( static_cast<int>( _fg.size() ) == itot );
     fg = _fg;
 }
void set_ampc (FloatList _ampc)
References TransitionMatrixP::ampc, and TransitionMatrixP::itot.
 {
     Require( static_cast<int>( _ampc.size() ) == itot );
     ampc = _ampc;
 }
void set_wmpc (FloatList _wmpc)
References TransitionMatrixP::itot, and TransitionMatrixP::wmpc.
 {
     Require( static_cast<int>( _wmpc.size() ) == itot );
     wmpc = _wmpc;
 }
void set_abund (FloatList _abund)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::abund, and TransitionMatrixP::ilite.
Referenced by TEST().
 {
     Require( static_cast<int>( _abund.size() ) == ilite );
     abund = _abund;
 }
void set_wabund (FloatList _wabund)
References TransitionMatrixP::ilite, and TransitionMatrixP::wabund.
 {
     Require( static_cast<int>( _wabund.size() ) == ilite );
     wabund = _wabund;
 }
void set_tocap (DoubleList _tocap)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::itot, and TransitionMatrixP::tocap.
Referenced by TEST().
 {
     Require( static_cast<int>( _tocap.size() ) == itot );
     tocap = _tocap;
 }
void set_fiss (DoubleList _fiss)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::fiss, and TransitionMatrixP::iact.
Referenced by TEST().
 {
     Require( static_cast<int>( _fiss.size() ) == iact );
     fiss = _fiss;
 }
void set_genneu (FloatList _genneu)
References TransitionMatrixP::genneu, TransitionMatrixP::iact, and TransitionMatrixP::ilite.
 {
     Require( static_cast<int>( _genneu.size() ) == ( ilite + iact ) );
     genneu = _genneu;
 }
void set_spectrum (FloatList _spectrum)
References TransitionMatrixP::nfluxgrp, and TransitionMatrixP::spectrum.
 {
     Require( static_cast<int>( _spectrum.size() ) == nfluxgrp );
     spectrum = _spectrum;
 }
void set_nucfis (IntegerList _nucfis)
References TransitionMatrixP::nfiso, and TransitionMatrixP::nucfis.
 {
     Require( static_cast<int>( _nucfis.size() ) == nfiso );
     nucfis = _nucfis;
 }
void set_titles (StringList _titles)
References TransitionMatrixP::nti, and TransitionMatrixP::titles.
 {
     Require( static_cast<int>( _titles.size() ) == nti );
     titles = _titles;
 }
void populate_transition_ids_cache ()
References TransitionMatrixP::clear_transition_ids_cache(), TransitionMatrixP::d_possible_transition_ids_cache, TransitionMatrixP::d_transition_ids_cache, TransitionMatrixP::itot, TransitionMatrixP::loc, TransitionMatrixP::mt, and TransitionMatrixP::non0_.
Referenced by TransitionMatrixP::get_possible_transition_ids(), and TransitionMatrixP::get_transition_ids().
 {
     // clear the cache
     clear_transition_ids_cache();
     // reserve initial space
     Check( d_transition_ids_cache.empty() );
     for( int j = 0; j < itot; j++ )
     {
         d_transition_ids_cache[j].reserve( 6 );
     }
     // populate
     int k = -1;
     for( int j = 0; j < itot; j++ )
     {
         for( int i = 0; i < non0_[j]; i++ )
         {
             k++;
             int nind = loc[k];
             d_transition_ids_cache[nind].push_back( mt[k] );
         }
     }
     // shrink-to-fit
     for( int j = 0; j < itot; j++ )
     {
         Vec_Int( d_transition_ids_cache[j].begin(),
                  d_transition_ids_cache[j].end() )
             .swap( d_transition_ids_cache[j] );
     }
     // repopulate set with std::vector data
     Check( d_possible_transition_ids_cache.empty() );
     std::copy( mt.begin(),
                mt.end(),
                std::inserter( d_possible_transition_ids_cache,
                               d_possible_transition_ids_cache.end() ) );
     Ensure( d_transition_ids_cache.size() == (size_t)itot );
     return;
 }
void clear_transition_ids_cache ()
References TransitionMatrixP::d_possible_transition_ids_cache, and TransitionMatrixP::d_transition_ids_cache.
Referenced by TransitionMatrixP::populate_transition_ids_cache().
 {
     d_transition_ids_cache.clear();
     d_possible_transition_ids_cache.clear();
     return;
 }
void get_transition_ids (const int nind, Vec_Int & tids)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::d_transition_ids_cache, and TransitionMatrixP::populate_transition_ids_cache().
Referenced by TEST().
 {
     if( d_transition_ids_cache.empty() )
     {
         populate_transition_ids_cache();
     }
     std::map<int, std::vector<int>>::iterator it =
         d_transition_ids_cache.find( nind );
     Check( it != d_transition_ids_cache.end() );
     tids.clear();
     tids = it->second;
     return;
 }
void get_possible_transition_ids (Vec_Int & tids)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::d_possible_transition_ids_cache, TransitionMatrixP::d_transition_ids_cache, and TransitionMatrixP::populate_transition_ids_cache().
Referenced by TEST().
 {
     if( d_transition_ids_cache.empty() )
     {
         populate_transition_ids_cache();
     }
     tids.clear();
     std::copy( d_possible_transition_ids_cache.begin(),
                d_possible_transition_ids_cache.end(),
                std::inserter( tids, tids.end() ) );
     return;
 }
void filter_reaction_mts (Vec_Int::const_iterator tids_begin, Vec_Int::const_iterator tids_end, Vec_Int & mts) const
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
Referenced by TEST().
 {
     Require( std::distance( tids_begin, tids_end ) >= 0 );
     // Clear the destination std::vector
     mts.clear();
     // Return if the source is empty
     if( tids_begin == tids_end )
     {
         return;
     }
     // Dump the tids into a set, which makes them unique and sorts them
     std::set<int> mt_set( tids_begin, tids_end );
     // Search for the first element greater than -1.  This is where we'll
     // begin copying (after the decay elements)
     std::set<int>::const_iterator search_iter = mt_set.upper_bound( -1 );
     // Copy back into mts
     mts.reserve( mt_set.size() );
     for( std::set<int>::const_iterator iter = search_iter,
                                        iter_end = mt_set.end();
          iter != iter_end;
          ++iter )
     {
         mts.push_back( *iter );
     }
     Ensure( nemesis::is_positive( mts.begin(), mts.end() ) );
     Ensure( std::is_sorted( mts.begin(), mts.end() ) );
     Ensure( nemesis::is_unique( mts.begin(), mts.end() ) );
 }
void set_kappa_fission (const FloatList & kappa_fission)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::b_kappa_fission.
Referenced by TEST().
 {
     b_kappa_fission = kappa_fission;
 }
void set_kappa_capture (const FloatList & kappa_capture)
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::b_kappa_capture.
Referenced by TEST().
 {
     b_kappa_capture = kappa_capture;
 }
const FloatList * get_kappa_capture () const
Examples:
Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::b_kappa_capture.
Referenced by h5_write_trx().
 {
     return &b_kappa_capture;
 }
const FloatList * get_kappa_fission () const
Examples:
Core/io/tests/tstMaterialBuffer.cpp.
References TransitionMatrixP::b_kappa_fission.
Referenced by h5_write_trx().
 {
     return &b_kappa_fission;
 }
double get_decay_power (const DoubleList & numden, double vol)
References TransitionMatrixP::dis, TransitionMatrixP::itot, and TransitionMatrixP::q.
 {
     Require( itot == static_cast<int>( numden.size() ) );
     Require( itot == static_cast<int>( q.size() ) );
     double power = 0.0;
     for( int i = 0; i < itot; ++i )
     {
         power += numden[i] * q[i] * dis[i];
     }
     power *= vol;
     return power;
 }
double get_reaction_power (const DoubleList & numden, double vol, double flux)
References TransitionMatrixP::get_capture_power(), and TransitionMatrixP::get_fission_power().
 {
     double power = get_fission_power( numden, vol, flux ) +
                    get_capture_power( numden, vol, flux );
     return power;
 }
double get_fission_power (const DoubleList & numden, double vol, double flux)
References TransitionMatrixP::b_kappa_fission, TransitionMatrixP::bounds, TransitionMatrixP::fiss, TransitionMatrixP::iact, TransitionMatrixP::ilite, TransitionMatrixP::itot, and Origen::SUBLIB_2AC.
Referenced by TransitionMatrixP::get_reaction_power().
 {
     Require( itot == static_cast<int>( numden.size() ) );
     Require( iact == static_cast<int>( b_kappa_fission.size() ) );
     Require( vol >= 0.0 );
     Require( flux >= 0.0 );
     double power = 0.0;
     for( int i = bounds[SUBLIB_2AC][0]; i < bounds[SUBLIB_2AC][1]; i++ )
     {
         Check( b_kappa_fission[i - ilite] >= 0.0 );
         power += b_kappa_fission[i - ilite] * numden[i] * fiss[i - ilite];
     }
     power *= vol * flux;
     Ensure( power >= 0.0 );
     return power;
 }
double get_capture_power (const DoubleList & numden, double vol, double flux)
References TransitionMatrixP::b_kappa_capture, TransitionMatrixP::bounds, TransitionMatrixP::fiss, TransitionMatrixP::ilite, TransitionMatrixP::itot, Origen::SUBLIB_2AC, and TransitionMatrixP::tocap.
Referenced by TransitionMatrixP::get_reaction_power().
 {
     Require( itot == static_cast<int>( numden.size() ) );
     Require( itot == static_cast<int>( b_kappa_capture.size() ) );
     Require( vol >= 0.0 );
     Require( flux >= 0.0 );
     double power = 0.0;
     for( int i = 0; i < itot; i++ )
     {
         Check( b_kappa_capture[i] >= 0.0 );
         double sigma_capture = tocap[i];
         if( i >= bounds[SUBLIB_2AC][0] && i < bounds[SUBLIB_2AC][1] )
         {
             sigma_capture -= fiss[i - ilite];
         }
         power += b_kappa_capture[i] * numden[i] * sigma_capture;
     }
     power *= vol * flux;
     Ensure( power >= 0.0 );
     return power;
 }
int add_tally_nuclide (const std::vector< double > & tally_dw, const std::vector< int > & tally_di, const std::vector< double > & tally_rw, const std::vector< int > & tally_ri) inline
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::num_tallies.
Referenced by TransitionMatrixP::add_concentration_tallies(), TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_captures_tally(), TransitionMatrixP::add_num_fissions_tally(), and TEST().
     {
         return this->add_tally_nuclide(
             tally_dw, tally_di, tally_rw, tally_ri, 8000000 + num_tallies );
     }
int add_tally_nuclide (const std::vector< double > & tally_dw, const std::vector< int > & tally_di, const std::vector< double > & tally_rw, const std::vector< int > & tally_ri, int zaid)
Add a tally nuclide to the system.
Warning
After calling this function, only add_tally_nuclide, fold_flux, get_non0_/non0/kd-/kd/loc_/loc/nucl are quaranteed to work. All other functions will exhibit unspecified behavior. All classes using this TransitionMatrix will exhibit unspecified behavior.
The modified matrix is only quaranteed to work with CRAM.
Note
The caller is responsible for keeping track of his tallies. The results of the j:th tally added will be output as the concentration of the N + j:th nuclide, where N is the number of real nuclides.
A tally nuclide produces the integral of sum N_i rw_i phi + N_i dw_i over the length of the step. N_i is the concentration of the i:th nuclide and rw_i and dw_i the corresponding weights for decay and transition reactions. Negative weights are permitted, if you figured a use for those.
Parameters
[in] tally_rw The nonzero weights rw_i specifying the tally.
[in] tally_ri Indices i of the nonzero reaction weights.
[in] tally_dw The nonzero weights dw_i specifying the tally.
[in] tally_di Indices i of the nonzero decay weights.
[in] zaid ZAID for the tally nuclide. Used for sorting in CRAM. This can have a large effect on performance.
Returns
Index of the freshly added tally in the composition vectors.
References TransitionMatrixP::_cached_has_valid_mts, TransitionMatrixP::a, TransitionMatrixP::dis, TransitionMatrixP::itot, TransitionMatrixP::kd, TransitionMatrixP::kd_, TransitionMatrixP::loc, TransitionMatrixP::mt, TransitionMatrixP::non, TransitionMatrixP::non0, TransitionMatrixP::non0_, TransitionMatrixP::nucl, TransitionMatrixP::num_tallies, and TransitionMatrixP::tocap.
 {
     // >>> Add the tally nuclide
     ++itot;
     // Decay constant, capture xs, ZAID
     dis.push_back( 0.0 );
     tocap.push_back( 0.0 );
     nucl.push_back( zaid );
     // Number of decay parents and total parents
     kd_.push_back( tally_di.size() );
     non0_.push_back( tally_ri.size() + tally_di.size() );
     // Pointers to last decay parent and last parent
     kd.push_back( non0.back() + tally_di.size() );
     non0.push_back( non0.back() + tally_ri.size() + tally_di.size() );
     // >>> Add the production of the tally nuclide
     a.insert( a.end(), tally_dw.begin(), tally_dw.end() );
     a.insert( a.end(), tally_rw.begin(), tally_rw.end() );
     loc.insert( loc.end(), tally_di.begin(), tally_di.end() );
     loc.insert( loc.end(), tally_ri.begin(), tally_ri.end() );
     mt.insert( mt.end(), tally_di.size(), -1 );
     mt.insert( mt.end(), tally_di.size(), -2 );
     non += tally_di.size() + tally_ri.size();
     // If they weren't broken before, they are now
     _cached_has_valid_mts = false;
     ++num_tallies;
     return itot - 1;
     // Variety of stuff is intentionally left unupdated. Hopefully these cause
     // errors if anyone tries to call wrong funstions afterwards.
 }
int add_energy_tally (double flux)
Add a tally nuclide that tallies total energy released.
The Energy released is in [MeV] times the units of n0 in the depletion solver.
Warning
Read the description of add_tally_nuclide()!
Parameters
[in] flux Neutron flux in the system. Only used to check whether it is zero (decay only).
Returns
Index of the freshly added tally in the composition vectors.
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::b_kappa_capture, TransitionMatrixP::b_kappa_fission, TransitionMatrixP::dis, TransitionMatrixP::fiss, TransitionMatrixP::iact, TransitionMatrixP::ilite, TransitionMatrixP::itot, TransitionMatrixP::num_tallies, TransitionMatrixP::q, TransitionMatrixP::tocap, and TransitionMatrixP::typ_nuc.
Referenced by Solver_cram::solve_impl(), Solver_matrex::solve_impl(), and TEST().
 {
     std::vector<double> tally_dw, tally_rw;
     std::vector<int> tally_di, tally_ri;
     // Loop over real nuclides
     for( int i = 0; i < itot - num_tallies; i++ )
     {
         double reaction_energy = 0.0;
         if( typ_nuc[i] == 2 )
         {                            // Actinide
             int ia = ( i - ilite );  // index in the actinide block
             Check( ia >= 0 );
             Check( ia < iact );
             // Add fission energy
             reaction_energy += fiss[ia] * b_kappa_fission[ia];
             // Add capture-that-is-not-fission energy
             reaction_energy += ( tocap[i] - fiss[ia] ) * b_kappa_capture[i];
         }
         else
         {
             // Add capture energy
             reaction_energy += tocap[i] * b_kappa_capture[i];
         }
         // Add the production
         if( reaction_energy > 0.0 )
         {
             tally_rw.push_back( reaction_energy );
             tally_ri.push_back( i );
         }
     }
     // Decay energies are rolled into kappas, so we only do this with zero flux
     if( flux == 0 )
     {
         // Loop over real nuclides
         for( int i = 0; i < itot - num_tallies; i++ )
         {
             if( q[i] > 0.0 && dis[i] > 0.0 )
             {
                 tally_dw.push_back( q[i] * dis[i] );
                 tally_di.push_back( i );
             }
         }
     }
     // Add the tally nuclide
     return this->add_tally_nuclide( tally_dw, tally_di, tally_rw, tally_ri );
 }
int add_num_fissions_tally ()
Add a tally nuclide that tallies the total number(density) of neutron induced fissions.
The result is in units of n0 in the depletion solver times [s].
Warning
Read the description of add_tally_nuclide()!
Returns
Index of the freshly added tally in the composition vectors.
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::fiss, TransitionMatrixP::iact, and TransitionMatrixP::ilite.
Referenced by Solver_cram::solve_impl(), Solver_matrex::solve_impl(), and TEST().
 {
     std::vector<double> tally_dw, tally_rw;
     std::vector<int> tally_di, tally_ri;
     // Loop over real actinide nuclides
     for( int i = 0; i < iact; i++ )
         if( fiss[i] > 0.0 )
         {
             // Add the tally line
             tally_rw.push_back( fiss[i] );
             tally_ri.push_back( i + ilite );
         }
     // Add the tally nuclide
     return this->add_tally_nuclide( tally_dw, tally_di, tally_rw, tally_ri );
 }
int add_num_captures_tally ()
Add a tally nuclide that tallies the total number(density) of neutron induced removals, including fissions.
The result is in units of n0 in the depletion solver times [s].
Warning
Read the description of add_tally_nuclide()!
Returns
Index of the freshly added tally in the composition vectors.
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::itot, TransitionMatrixP::num_tallies, and TransitionMatrixP::tocap.
Referenced by Solver_cram::solve_impl(), Solver_matrex::solve_impl(), and TEST().
 {
     std::vector<double> tally_dw, tally_rw;
     std::vector<int> tally_di, tally_ri;
     // Loop over real nuclides
     for( int i = 0; i < itot - num_tallies; i++ )
         if( tocap[i] > 0.0 )
         {
             // Add the tally line
             tally_rw.push_back( tocap[i] );
             tally_ri.push_back( i );
         }
     // Add the tally nuclide
     return this->add_tally_nuclide( tally_dw, tally_di, tally_rw, tally_ri );
 }
int add_concentration_tallies (std::vector< int > & zaids)
Add tally nuclides to tally the integrals of the concentrations of ALL nuclides in the library.
The results are in units of n0 in the depletion solver times [s].
Warning
Read the description of add_tally_nuclide()!
Parameters
[out] zaids The nuclide identifiers corresponding to the added tallies. Note that these are the zaids of the nuclides whose averages are being tallied. The zaid of the corresponding tally is zaids[i]+5.
Returns
Index of the FIRST freshly added tally in the composition vectors.
Examples:
Core/dc/tests/tstTransitionMatrixP.cpp.
References TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::itot, TransitionMatrixP::nucl, and TransitionMatrixP::num_tallies.
Referenced by Solver_cram::solve_impl(), Solver_matrex::solve_impl(), and TEST().
 {
     std::vector<double> tally_dw, tally_rw;
     std::vector<int> tally_di, tally_ri;
     zaids.clear();
     // Add the first tally and catch its index
     tally_dw.push_back( 1.0 );
     tally_di.push_back( 0 );
     int rv = this->add_tally_nuclide( tally_dw, tally_di, tally_rw, tally_ri );
     zaids.push_back( nucl[0] );
     // Loop over nuclides
     for( int i = 1; i < itot - num_tallies; i++ )
     {
         // Set the index
         tally_di[0] = i;
         // Add the tally nuclide
         this->add_tally_nuclide(
             tally_dw, tally_di, tally_rw, tally_ri, nucl[i] + 5 );
         // Add the identifier to the list
         zaids.push_back( nucl[i] );
     }
     return rv;
 }
const NuclideSet& nuclide_set () const inline
References TransitionMatrixP::b_nuclide_set.
Referenced by Case::load_new_concentrations().
     {
         Require( b_nuclide_set != nullptr );
         return *b_nuclide_set;
     }
void init_bounds () protected
Initialize library boundaries (for internal function use)
References TransitionMatrixP::bounds, TransitionMatrixP::iact, TransitionMatrixP::ifp, TransitionMatrixP::ilite, and TransitionMatrixP::itot.
Referenced by TransitionMatrixP::finish_init().
 {
     Require( ilite + iact + ifp == itot );
     bounds[0][0] = 0;
     bounds[0][1] = itot;
     bounds[1][0] = 0;
     bounds[1][1] = ilite;
     bounds[2][0] = ilite;
     bounds[2][1] = ilite + iact;
     bounds[3][0] = ilite + iact;
     bounds[3][1] = itot;
 }
void init_typ_nuc () protected
Initialize typ_nuc array on class.
References TransitionMatrixP::iact, TransitionMatrixP::ilite, TransitionMatrixP::itot, Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, Origen::SUBLIB_3FP, and TransitionMatrixP::typ_nuc.
Referenced by TransitionMatrixP::finish_init().
 {
     // Setup nuclide type arrays
     typ_nuc.clear();
     for( int i = 0; i < ilite; i++ )
     {
         typ_nuc.push_back( SUBLIB_1LT );
     }
     for( int i = ilite; i < ( ilite + iact ); i++ )
     {
         typ_nuc.push_back( SUBLIB_2AC );
     }
     for( int i = ( ilite + iact ); i < itot; i++ )
     {
         typ_nuc.push_back( SUBLIB_3FP );
     }
     // Make sure nuclide type array size matches total nuclides
     Ensure( static_cast<int>( typ_nuc.size() ) == itot );
 }
std::string emsgn (const int i, const std::string v1msg, const V1 val1, const std::string v2msg, const V2 val2) inline private
References TransitionMatrixP::toQString_sizzzaaa().
Referenced by TransitionMatrixP::check().
     {
         // Require(i>=0 && i<itot);
         std::string id = toQString_sizzzaaa( i ).toStdString();
         std::string output_msg = "nuclide=" + id + " (nind=" +
                                  ScaleUtils::IO::toString( i ) + ")" + v1msg +
                                  ScaleUtils::IO::toString( val1 ) + v2msg +
                                  ScaleUtils::IO::toString( val2 );
         return output_msg;
     }
std::string emsgs (const std::string v1msg, const V1 val1, const std::string v2msg, const V2 val2) inline private
Referenced by TransitionMatrixP::check().
     {
         // Require(i>=0 && i<itot);
         std::string output_msg = v1msg + ScaleUtils::IO::toString( val1 ) +
                                  v2msg + ScaleUtils::IO::toString( val2 );
         return output_msg;
     }
Friends And Related Function Documentation
friend class Origen::Library friend
Member Data Documentation
int non protected
Number of non-zero off-diagonal elements of the transition matrix A.
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::check(), TransitionMatrixP::check_library(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::collect_xs(), TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::find_all_mts(), TransitionMatrixP::first_transition(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_loc_array(), TransitionMatrixP::get_non(), TransitionMatrixP::get_xs(), TransitionMatrixP::has_valid_mts(), TransitionMatrixP::last_transition(), TransitionMatrixP::loc_size(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::print_info(), TransitionMatrixP::set_a(), TransitionMatrixP::set_loc(), TransitionMatrixP::set_mt(), TransitionMatrixP::set_non(), TransitionMatrixP::set_xs(), TransitionMatrixP::toQString_sizes(), and TransitionMatrixP::transpose_transition_matrix().
int ilite protected
Number of light-element activation product nuclides in the library.
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_fissions_tally(), TransitionMatrixP::convert_abundances(), TransitionMatrixP::fast_set_xs(), TransitionMatrixP::finish_init(), TransitionMatrixP::get_capture_power(), TransitionMatrixP::get_fission_power(), TransitionMatrixP::get_ilite(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::init_bounds(), TransitionMatrixP::init_typ_nuc(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::print_info(), TransitionMatrixP::set_abund(), TransitionMatrixP::set_genneu(), TransitionMatrixP::set_ilite(), TransitionMatrixP::set_wabund(), TransitionMatrixP::set_xs(), TransitionMatrixP::setup_fast_transition_access(), and TransitionMatrixP::toQString_sizes().
int iact protected
Number of actinide nuclides in the library.
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_fissions_tally(), TransitionMatrixP::check(), TransitionMatrixP::finish_init(), TransitionMatrixP::get_fission_power(), TransitionMatrixP::get_iact(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::init_bounds(), TransitionMatrixP::init_typ_nuc(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::print_info(), TransitionMatrixP::set_fiss(), TransitionMatrixP::set_genneu(), TransitionMatrixP::set_iact(), and TransitionMatrixP::toQString_sizes().
int ifp protected
Number of fission product nuclides in the library.
Referenced by TransitionMatrixP::finish_init(), TransitionMatrixP::get_ifp(), TransitionMatrixP::init_bounds(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), TransitionMatrixP::set_ifp(), and TransitionMatrixP::toQString_sizes().
int itot protected
Total number of nuclides in the library.
Referenced by TransitionMatrixP::add_concentration_tallies(), TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_captures_tally(), TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::check_library(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::find_daughters(), TransitionMatrixP::find_parents(), TransitionMatrixP::finish_init(), TransitionMatrixP::first_transition(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_capture_power(), TransitionMatrixP::get_decay_power(), TransitionMatrixP::get_fission_power(), TransitionMatrixP::get_itot(), TransitionMatrixP::get_kd_array(), TransitionMatrixP::get_non0_array(), TransitionMatrixP::get_xs(), TransitionMatrixP::init_bounds(), TransitionMatrixP::init_typ_nuc(), TransitionMatrixP::kd_size(), TransitionMatrixP::last_transition(), TransitionMatrixP::non0_size(), TransitionMatrixP::operator=(), TransitionMatrixP::populate_transition_ids_cache(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::print_info(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::remove_fp_reactions(), TransitionMatrixP::set_ampc(), TransitionMatrixP::set_dis(), TransitionMatrixP::set_fg(), TransitionMatrixP::set_itot(), TransitionMatrixP::set_kd(), TransitionMatrixP::set_kd_(), TransitionMatrixP::set_non0(), TransitionMatrixP::set_non0_(), TransitionMatrixP::set_nucl(), TransitionMatrixP::set_q(), TransitionMatrixP::set_tocap(), TransitionMatrixP::set_wmpc(), TransitionMatrixP::set_xs(), TransitionMatrixP::toQString_sizes(), and TransitionMatrixP::transpose_transition_matrix().
int nfluxgrp protected
Number of energy groups in the collapse spectrum.
Referenced by TransitionMatrixP::get_nfluxgrp(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::set_nfluxgrp(), TransitionMatrixP::set_spectrum(), and TransitionMatrixP::toQString_sizes().
int nti protected
Number of title cards.
Referenced by TransitionMatrixP::get_nti(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), TransitionMatrixP::set_nti(), TransitionMatrixP::set_titles(), TransitionMatrixP::toQString_info(), TransitionMatrixP::toQString_sizes(), and TransitionMatrixP::toQString_title().
int nfiso protected
Number of fissionable isotopes.
Referenced by TransitionMatrixP::get_nfiso(), TransitionMatrixP::operator=(), TransitionMatrixP::set_nfiso(), TransitionMatrixP::set_nucfis(), and TransitionMatrixP::toQString_sizes().
float burnup protected
Burnup [MWd/tU] of the library.
Referenced by Library::add_transition_matrix(), TransitionMatrixP::get_burnup(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::set_burnup(), and TransitionMatrixP::toQString_info().
std::string filename protected
Base filename of the library.
Referenced by TransitionMatrixP::get_filename(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), TransitionMatrixP::set_filename(), and TransitionMatrixP::toQString_info().
int pos protected
Position number of the burnup-dependent XS set in the library.
Referenced by TransitionMatrixP::get_pos(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), TransitionMatrixP::set_pos(), and TransitionMatrixP::toQString_info().
int numLibs protected
Number of available burnup positions in the library.
Referenced by TransitionMatrixP::operator=().
int sizes[3] protected
[ilite, iact, ifp] array
Referenced by TransitionMatrixP::operator=().
int bounds[4][2] protected
ilo/ihi for each library (0=all; 1,2,3 = lite/act/fp)
Referenced by TransitionMatrixP::get_capture_power(), TransitionMatrixP::get_fission_power(), TransitionMatrixP::get_xs(), TransitionMatrixP::init_bounds(), TransitionMatrixP::operator=(), TransitionMatrixP::remove_fp_reactions(), TransitionMatrixP::set_xs(), and TransitionMatrixP::setup_fast_transition_access().
IntegerList typ_nuc protected
Gives the nuclide type for each nuclide [1/2/3] [itot].
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::get_typ_nuc(), TransitionMatrixP::init_typ_nuc(), TransitionMatrixP::operator=(), TransitionMatrixP::remove_fp_reactions(), and TransitionMatrixP::split_id().
IntegerList nucl protected
NUCL array (ZAID for all nuclides in the library) [itot].
Referenced by TransitionMatrixP::add_concentration_tallies(), TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::collect_xs(), TransitionMatrixP::convert_abundances(), TransitionMatrixP::finish_init(), TransitionMatrixP::get_nucl(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::operator=(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::set_nucl(), TransitionMatrixP::set_xs(), TransitionMatrixP::setup_fast_transition_access(), TransitionMatrixP::split_id(), TransitionMatrixP::toQString_cross_section_mt(), TransitionMatrixP::toQString_nuclides(), and TransitionMatrixP::toQString_transitions().
IntegerList kd_ protected
Total number of parents for nuclide I by decay transitions [itot].
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::check(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::get_kd_(), TransitionMatrixP::operator=(), TransitionMatrixP::set_kd_(), and TransitionMatrixP::transpose_transition_matrix().
IntegerList non0_ protected
Total number of parents for nuclide I [itot].
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::check(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::find_daughters(), TransitionMatrixP::first_transition(), TransitionMatrixP::get_non0_(), TransitionMatrixP::operator=(), TransitionMatrixP::populate_transition_ids_cache(), TransitionMatrixP::set_non0_(), and TransitionMatrixP::transpose_transition_matrix().
IntegerList kd protected
Pointer [NON] to last decay parent of nuclide I in A [itot].
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::check_library(), TransitionMatrixP::collect_xs(), TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_kd(), TransitionMatrixP::get_kd_array(), TransitionMatrixP::last_transition(), TransitionMatrixP::operator=(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::remove_fp_reactions(), and TransitionMatrixP::set_kd().
IntegerList non0 protected
Pointer [NON] to last parent of nuclide I in A [itot].
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::check_library(), TransitionMatrixP::collect_xs(), TransitionMatrixP::expand_matrix_pointers(), TransitionMatrixP::first_transition(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_non0(), TransitionMatrixP::get_non0_array(), TransitionMatrixP::last_transition(), TransitionMatrixP::operator=(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::remove_fp_reactions(), and TransitionMatrixP::set_non0().
IntegerList loc protected
LOC array.
LOC[j] is the position in array NUCL of the parent of the transition stored in position j of the compressed transition matrix A) [non]
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::check_library(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::collect_xs(), TransitionMatrixP::find_daughters(), TransitionMatrixP::find_parents(), TransitionMatrixP::get_loc(), TransitionMatrixP::get_loc_array(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::operator=(), TransitionMatrixP::populate_transition_ids_cache(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::remove_fp_reactions(), TransitionMatrixP::set_loc(), TransitionMatrixP::set_xs(), TransitionMatrixP::toQString_transitions(), and TransitionMatrixP::transpose_transition_matrix().
FloatList dis protected
DIS array (Radioactive decay constants) [itot].
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_decay_power(), TransitionMatrixP::get_dis(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_dis().
FloatList q protected
Q array (Recoverable energy values from decay) [itot].
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::get_decay_power(), TransitionMatrixP::get_q(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_q().
FloatList fg protected
FG array (Fractions of Q-values due to photons) [itot].
Referenced by TransitionMatrixP::get_fg(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_fg().
FloatList ampc protected
AMPC array (RCG values for air) [itot].
Referenced by TransitionMatrixP::get_ampc(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_ampc().
FloatList wmpc protected
WMPC array (RCG values for water) [itot].
Referenced by TransitionMatrixP::get_wmpc(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_wmpc().
FloatList abund protected
ABUND array (Natural abundances of activation-product nuclide in atom%) [ilite]
Referenced by TransitionMatrixP::convert_abundances(), TransitionMatrixP::get_abund(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_abund().
FloatList wabund protected
Natural abundances of nuclides in wt% [ilite].
Referenced by TransitionMatrixP::convert_abundances(), TransitionMatrixP::get_wabund(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_wabund().
IntegerList mt protected
MT numbers for every transition (A-matrix elements) [non].
Referenced by TransitionMatrixP::add_tally_nuclide(), TransitionMatrixP::check(), TransitionMatrixP::collect_xs(), TransitionMatrixP::find_all_mts(), TransitionMatrixP::find_daughters(), TransitionMatrixP::find_parents(), TransitionMatrixP::get_mt(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::has_valid_mts(), TransitionMatrixP::operator=(), TransitionMatrixP::populate_transition_ids_cache(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::set_mt(), TransitionMatrixP::set_xs(), and TransitionMatrixP::toQString_transitions().
IntegerList nucfis protected
List of fissionable nuclides [nfiso].
Referenced by TransitionMatrixP::get_nucfis(), TransitionMatrixP::operator=(), and TransitionMatrixP::set_nucfis().
FloatList spectrum protected
Fluxes used for library collapse [nfluxgrp].
Referenced by Library::add_transition_matrix(), TransitionMatrixP::get_spectrum(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), and TransitionMatrixP::set_spectrum().
FloatList m protected
Atomic masses in grams/mol [itot].
Referenced by TransitionMatrixP::convert_abundances(), TransitionMatrixP::finish_init(), TransitionMatrixP::get_m(), TransitionMatrixP::operator=(), TransitionMatrixP::print_transitions_for(), and TransitionMatrixP::toQString_nuclides().
StringList titles protected
Title cards container.
Referenced by TransitionMatrixP::get_titles(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), TransitionMatrixP::set_titles(), and TransitionMatrixP::toQString_title().
FloatList b_kappa_capture protected
Kappa-capture values in MeV [itot] NOTE: capture = loss - fission
Referenced by TransitionMatrixP::add_energy_tally(), Library::add_transition_matrix(), TransitionMatrixP::finish_init(), TransitionMatrixP::get_capture_power(), TransitionMatrixP::get_kappa_capture(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), and TransitionMatrixP::set_kappa_capture().
FloatList b_kappa_fission protected
Kappa-fission values in MeV [iact].
Referenced by TransitionMatrixP::add_energy_tally(), Library::add_transition_matrix(), TransitionMatrixP::finish_init(), TransitionMatrixP::get_fission_power(), TransitionMatrixP::get_kappa_fission(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), and TransitionMatrixP::set_kappa_fission().
DoubleList a protected
A array [non].
A is the compressed transition matrix for effective one-group neutron capture transitions of the first burnup interval and for decay transitions
Referenced by TransitionMatrixP::add_tally_nuclide(), Library::add_transition_matrix(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::check_library(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::fast_set_xs(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_a(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::print_transitions_for(), TransitionMatrixP::remove_fp_reactions(), TransitionMatrixP::set_a(), TransitionMatrixP::set_xs(), TransitionMatrixP::toQString_transitions(), and TransitionMatrixP::transpose_transition_matrix().
DoubleList tocap protected
TOCAP array (Effective one-group capture cross-sections) [itot].
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_captures_tally(), TransitionMatrixP::add_tally_nuclide(), Library::add_transition_matrix(), TransitionMatrixP::build_full_matrix(), TransitionMatrixP::check(), TransitionMatrixP::cleanup_transitions_for_adjoint(), TransitionMatrixP::fast_set_xs(), TransitionMatrixP::fold_flux(), TransitionMatrixP::get_capture_power(), TransitionMatrixP::get_tocap(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::remove_fp_reactions(), TransitionMatrixP::set_tocap(), and TransitionMatrixP::set_xs().
DoubleList fiss protected
FISS array (Effective one-group fission cross-sections) [iact].
Referenced by TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_fissions_tally(), Library::add_transition_matrix(), TransitionMatrixP::check(), TransitionMatrixP::fast_set_xs(), TransitionMatrixP::get_capture_power(), TransitionMatrixP::get_fiss(), TransitionMatrixP::get_fission_power(), TransitionMatrixP::get_xs(), TransitionMatrixP::get_xs_stdvec(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), TransitionMatrixP::set_fiss(), TransitionMatrixP::set_xs(), and TransitionMatrixP::setup_fast_transition_access().
FloatList genneu protected
GENNEU array (Effective one-group neutron yields) [ilite + act].
Referenced by Library::add_transition_matrix(), TransitionMatrixP::get_genneu(), TransitionMatrixP::operator=(), Library::populate_transition_matrix_reaction(), and TransitionMatrixP::set_genneu().
int nmonth protected
Month the library was made.
Referenced by TransitionMatrixP::get_nmonth(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), and TransitionMatrixP::set_nmonth().
int nday protected
Day the library was made.
Referenced by TransitionMatrixP::get_nday(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), and TransitionMatrixP::set_nday().
int nyear protected
Year the library was made.
Referenced by TransitionMatrixP::get_nyear(), TransitionMatrixP::operator=(), TransitionMatrixP::print_info(), and TransitionMatrixP::set_nyear().
bool _cached_has_valid_mts mutable protected
whether the library has valid MTs or not (used internally for checking)
Referenced by TransitionMatrixP::add_tally_nuclide(), and TransitionMatrixP::has_valid_mts().
std::map<int, std::vector<int> > d_transition_ids_cache protected
Referenced by TransitionMatrixP::clear_transition_ids_cache(), TransitionMatrixP::get_possible_transition_ids(), TransitionMatrixP::get_transition_ids(), and TransitionMatrixP::populate_transition_ids_cache().
std::set<int> d_possible_transition_ids_cache protected
Referenced by TransitionMatrixP::clear_transition_ids_cache(), TransitionMatrixP::get_possible_transition_ids(), and TransitionMatrixP::populate_transition_ids_cache().
int num_tallies protected
Number of tally nuclides added to the system.
Referenced by TransitionMatrixP::add_concentration_tallies(), TransitionMatrixP::add_energy_tally(), TransitionMatrixP::add_num_captures_tally(), and TransitionMatrixP::add_tally_nuclide().
SCP_NuclideSet b_nuclide_set protected
nuclide set for the future
Referenced by TransitionMatrixP::find_nuclide(), TransitionMatrixP::find_nuclide_all(), TransitionMatrixP::find_nuclide_guess(), TransitionMatrixP::nuclide_set(), and TransitionMatrixP::operator=().
The documentation for this class was generated from the following files:
Core/dc/TransitionMatrixP.h
Core/dc/TransitionMatrixP.cpp