ORIGEN API: DecayResource Class Reference
DecayResource Class Reference
#include <DecayResource.h>
Public Types
typedef std::shared_ptr< DecayResource > SP
typedef std::shared_ptr< const DecayResource > SCP
Public Member Functions
DecayResource ()
DecayResource (const Library &lib)
const std::map< int, DecayParent > & get_const_parent_map () const
std::map< int, DecayParent > & get_parent_map ()
int num_parents () const
int num_decay_modes (const int id) const
int num_residuals (const int id, const int decay_mode) const
bool is_present (const int id) const
bool has_decay_mode (const int id, const int decay_mode) const
void list_parent_ids (Vec_Int &parent_ids) const
void list_decay_modes (Vec_Int &decay_modes) const
const DecayParent * get_parent_ptr (const int id) const
void calculate_decay_constants ()
bool check (Vec_Str &errors) const
bool check_consistency (Vec_Str &errors) const
bool check_id (const int id, const std::string prefix, Vec_Str &errors) const
bool check_ids (Vec_Str &errors) const
Scale::Json::Value to_json () const
std::string to_string () const
Static Public Attributes
static const int ISOMERIC_YIELDS = 1
static const int IZZZAAA_YIELDS = 2
static const int MISSING_YIELDS = 3
Private Attributes
std::map< int, DecayParent > parent_map
Detailed Description
Examples:
Core/dc/tests/tstConcentrationConverter.cpp, Core/io/tests/tstDecayResourceIO.cpp, Core/re/tests/tstDecayResource.cpp, Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<DecayResource> SP
typedef std::shared_ptr<const DecayResource> SCP
Constructor & Destructor Documentation
DecayResource ()
 {
     // initialize library
 }
DecayResource (const Library & lib)
References DecayData::decay_constants, Library::decay_data(), Library::definition(), DecayResource::get_parent_map(), NuclideSet::ids_at(), LibraryHeader::nuclide_set(), DecayData::q_fractions_from_photons, DecayData::rcg_for_air, DecayData::rcg_for_water, DecayData::recoverable_energy_values, and NuclideSet::total_nuclides().
 {
     const NuclideSet& nucset = library.definition().nuclide_set();
     const DecayData& dd = library.decay_data();
     for( size_t i = 0; i < nucset.total_nuclides(); ++i )
     {
         int sizzzaaa = nucset.ids_at( i );
         int izzzaaa = sizzzaaa % ScaleData::Utils::PIZZZAAA_P_OFFSET;
         auto& e = get_parent_map()[izzzaaa];
         e.set_rcg_for_air( dd.rcg_for_air[i] );
         e.set_rcg_for_water( dd.rcg_for_water[i] );
         e.set_decay_constant( dd.decay_constants[i] );
         e.set_q_fraction_from_photons( dd.q_fractions_from_photons[i] );
         e.set_recoverable_energy_value( dd.recoverable_energy_values[i] );
     }
 }
Member Function Documentation
const std::map< int, DecayParent > & get_const_parent_map () const
References DecayResource::parent_map.
Referenced by TransitionSystemAdapter_DecayResource::extend(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryToxicity_DecayResource(), and Origen::printDecayTable().
 {
     return parent_map;
 }  // DecayResource::get_const_parent_map
std::map< int, DecayParent > & get_parent_map ()
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
References DecayResource::parent_map.
Referenced by DecayResource::DecayResource(), DecayResourceIO_cimg::read(), and TEST().
 {
     return parent_map;
 }  // DecayResource::get_parent_map
int num_parents () const
References DecayResource::parent_map.
Referenced by Origen::loadMulti().
 { return parent_map.size(); }
int num_decay_modes (const int id) const
References DecayResource::parent_map.
Referenced by DecayResource::is_present().
 {
     std::map<int, DecayParent>::const_iterator it = parent_map.find( id );
     if( it == parent_map.end() )
     {
         return -1;
     }
     return it->second.get_const_channel_map().size();
 }
int num_residuals (const int id, const int decay_mode) const
References DecayResource::parent_map.
Referenced by DecayResource::has_decay_mode().
 {
     std::map<int, DecayParent>::const_iterator it = parent_map.find( id );
     if( it == parent_map.end() ) return -1;
     return ( it->second ).num_residuals( decay_mode );
 }
bool is_present (const int id) const
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
References DecayResource::num_decay_modes().
Referenced by TEST().
 {
     return num_decay_modes( id ) != -1;
 }
bool has_decay_mode (const int id, const int decay_mode) const
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
References DecayResource::num_residuals().
Referenced by TEST().
 {
     return num_residuals( id, decay_mode ) != -1;
 }
void list_parent_ids (Vec_Int & parent_ids) const
References DecayResource::parent_map.
 {
     std::list<int> idList;
     std::map<int, DecayParent>::const_iterator it;
     for( it = parent_map.begin(); it != parent_map.end(); it++ )
     {
         idList.push_back( it->first );
     }
     idList.unique();
     list.clear();
     list.assign( idList.begin(), idList.end() );
 }
void list_decay_modes (Vec_Int & decay_modes) const
References DecayParent::get_const_channel_map(), and DecayResource::parent_map.
Referenced by DecayResource::to_json().
 {
     std::list<int> modeList;
     std::map<int, DecayParent>::const_iterator it;
     for( it = parent_map.begin(); it != parent_map.end(); it++ )
     {
         DecayParent parent = it->second;
         std::map<int, DecayChannel>::const_iterator it2;
         for( it2 = parent.get_const_channel_map().begin();
              it2 != parent.get_const_channel_map().end();
              it2++ )
         {
             modeList.push_back( it2->first );
         }
     }
     modeList.unique();
     list.clear();
     list.assign( modeList.begin(), modeList.end() );
 }
const DecayParent* get_parent_ptr (const int id) const inline
     {
         return &parent_map.find( id )->second;
     }
void calculate_decay_constants ()
References DecayResource::parent_map.
Referenced by DecayResourceIO_cimg::read().
 {
     // This computation is emulating the
     // Fortran source from src/couple/halfl.f90
     // data c/ 6.9315E-01, 1.1552E-02, 1.9254E-04, 8.0226E-06, 2.1965E-08, 0.0,
     // &
     //          2.1965E-11, 2.1965E-14, 2.1965E-17/
     //       if (a <= 0.0) then
     //          if (i == 6) go to 110
     //          a = 9.99
     //          return
     //       endif
     //       a = c(i)/a
     //       return
     //   110 continue
     //       a = 0.0
     // sec,min,hr,day,yr,NONE,1e3 yr, 1e6 yr, 1e9 yr
     double conversion_data[] = {6.9315E-01,
                                 1.1552E-02,
                                 1.9254E-04,
                                 8.0226E-06,
                                 2.1965E-08,
                                 0.0,
                                 2.1965E-11,
                                 2.1965E-14,
                                 2.1965E-17};
     std::map<int, DecayParent>::iterator it;
     for( it = parent_map.begin(); it != parent_map.end(); it++ )
     {
         double decay_constant = 0.0;
         double half_life = it->second.get_half_life();
         int iu = it->second.get_time_units();
         if( half_life <= 0.0 )
         {
             if( iu == 6 )
             {
                 decay_constant = 0.0;
             }
             else
             {
                 decay_constant = 9.99;
             }
         }
         else
         {
             Check( iu != 6 );
             decay_constant = conversion_data[iu - 1] / half_life;
         }
         it->second.set_decay_constant( decay_constant );
     }
 }
bool check (Vec_Str & errors) const
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
References DecayResource::check_consistency(), and DecayResource::check_ids().
Referenced by TEST().
 {
     bool pass = true;
     pass = pass && this->check_ids( errors );
     pass = pass && this->check_consistency( errors );
     return pass;
 }
bool check_consistency (Vec_Str & errors) const
References DecayResource::check_id(), DecayChannel::get_branch_ratio(), DecayParent::get_const_channel_map(), DecayChannel::get_const_yield_map(), DecayParent::get_half_life(), DecayParent::get_recoverable_energy_value(), DecayChannel::get_yield_type(), DecayResource::ISOMERIC_YIELDS, DecayResource::IZZZAAA_YIELDS, DecayResource::MISSING_YIELDS, and DecayResource::parent_map.
Referenced by DecayResource::check().
 {
     size_t nErr = errors.size();
     std::map<int, DecayParent>::const_iterator it;
     for( it = parent_map.begin(); it != parent_map.end(); it++ )
     {
         int id = it->first;
         DecayParent parent = it->second;
         double recoverable_energy_value = parent.get_recoverable_energy_value();
         double half_life = parent.get_half_life();
         if( half_life > 0.0 && recoverable_energy_value == 0.0 )
         {
             std::stringstream ss;
             ss << "Parent id=" << id << " cannot have a half_life=" << half_life
                << ">0.0 and recoverable_energy_value==0.0.";
             errors.push_back( ss.str() );
         }
         std::map<int, DecayChannel>::const_iterator it2;
         if( parent.get_const_channel_map().size() == 0 && half_life != 0.0 )
         {
             std::stringstream ss;
             ss << "Parent id=" << id
                << " cannot have a half_life>0.0 and no decay modes.";
             errors.push_back( ss.str() );
         }
         double sum_branch_ratio = 0;
         for( it2 = parent.get_const_channel_map().begin();
              it2 != parent.get_const_channel_map().end();
              it2++ )
         {
             int decay_mode = it2->first;
             if( !ScaleData::Utils::is_valid_decay_mode( decay_mode ) )
             {
                 std::stringstream ss;
                 ss << "Parent id=" << id
                    << " has invalide decay_mode=" << decay_mode << ".";
                 errors.push_back( ss.str() );
             }
             DecayChannel channel = it2->second;
             sum_branch_ratio += channel.get_branch_ratio();
             int yield_type = channel.get_yield_type();
             std::map<int, double>::const_iterator it3;
             double sum_yield = 0;
             for( it3 = channel.get_const_yield_map().begin();
                  it3 != channel.get_const_yield_map().end();
                  it3++ )
             {
                 int did = it3->first;
                 sum_yield += it3->second;
                 if( yield_type == ISOMERIC_YIELDS )
                 {
                     if( did < 0 && did > 9 )
                     {
                         std::stringstream ss;
                         ss << "Parent id=" << id << " decay_mode=" << decay_mode
                            << " has yield yield_type=ISOMERIC_YIELDS, which "
                               "means only the isomeric state is given (0-9) but"
                            << " I=" << did << " was found.";
                         errors.push_back( ss.str() );
                     }
                 }
                 else if( yield_type == IZZZAAA_YIELDS )
                 {
                     std::stringstream ss;
                     ss << "Parent id=" << id << " decay_mode=" << decay_mode
                        << " has yield yield_type=IZZZAAA_YIELDS, with IZZZAAA="
                        << did << ".";
                     this->check_id( id, ss.str(), errors );
                 }
                 else if( yield_type == MISSING_YIELDS )
                 {
                     std::stringstream ss;
                     ss << "Parent id=" << id << " decay_mode=" << decay_mode
                        << " has yield yield_type=MISSING_YIELDS which means no "
                           "yields may be present.";
                     errors.push_back( ss.str() );
                 }
                 else
                 {
                     std::stringstream ss;
                     ss << "Parent id=" << id << " decay_mode=" << decay_mode
                        << " has yield yield_type=UNKNOWN (" << yield_type
                        << ").";
                     errors.push_back( ss.str() );
                 }
             }
         }
         if( parent.get_const_channel_map().size() > 0 &&
             std::abs( sum_branch_ratio - 1.0 ) > 1.0e-5 )
         {
             std::stringstream ss;
             ss << "The sum of branch ratios for id=" << id << " is "
                << sum_branch_ratio << ".  It should be closer to 1.";
             errors.push_back( ss.str() );
         }
     }
     // no errors were introduced
     return errors.size() == nErr;
 }
bool check_id (const int id, const std::string prefix, Vec_Str & errors) const
Referenced by DecayResource::check_consistency(), and DecayResource::check_ids().
 {
     size_t nErr = errors.size();
     int p, i, z, a;
     ScaleData::Utils::split_pizzzaaa( id, p, i, z, a );
     if( p != 0 )
     {
         std::stringstream ss;
         ss << "The id=" << id << " has an invalid PREFIX=" << p
            << " which should be 0.";
         errors.push_back( prefix + ss.str() );
     }
     if( !ScaleData::Utils::is_valid_nuclide( i, z, a ) )
     {
         std::stringstream ss;
         ss << "The IZZZAAA id=" << id << " is invalid.";
         errors.push_back( prefix + ss.str() );
     }
     return nErr == errors.size();
 }
bool check_ids (Vec_Str & errors) const
References DecayResource::check_id(), and DecayResource::parent_map.
Referenced by DecayResource::check().
 {
     std::map<int, DecayParent>::const_iterator it;
     size_t nErr = errors.size();
     for( it = parent_map.begin(); it != parent_map.end(); it++ )
     {
         this->check_id( it->first, "", errors );
     }
     return errors.size() == nErr;
 }
Json::Value to_json () const
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
References Origen::_to_id_string(), DecayChannel::get_branch_ratio(), DecayParent::get_const_channel_map(), DecayChannel::get_const_yield_map(), DecayParent::get_half_life(), DecayParent::get_q_fraction_from_photons(), DecayParent::get_rcg_for_air(), DecayParent::get_rcg_for_water(), DecayParent::get_recoverable_energy_value(), DecayParent::get_time_units(), DecayChannel::get_yield_type(), DecayResource::list_decay_modes(), and DecayResource::parent_map.
Referenced by TEST(), and DecayResource::to_string().
 {
     Json::Value j_root( Json::objectValue );
     Json::Value j_parents( Json::objectValue );
     std::map<int, DecayParent>::const_iterator it;
     for( it = parent_map.begin(); it != parent_map.end(); it++ )
     {
         int id = it->first;
         DecayParent parent = it->second;
         // initialize parents[idString]
         Json::Value j_parent( Json::objectValue );
         j_parent["half_life"] = parent.get_half_life();
         j_parent["time_units"] = parent.get_time_units();
         j_parent["recoverable_energy_value"] =
             parent.get_recoverable_energy_value();
         j_parent["q_fraction_from_photons"] =
             parent.get_q_fraction_from_photons();
         j_parent["rcg_for_air"] = parent.get_rcg_for_air();
         j_parent["rcg_for_water"] = parent.get_rcg_for_water();
         Json::Value j_decay_modes( Json::objectValue );
         std::map<int, DecayChannel>::const_iterator it2;
         for( it2 = parent.get_const_channel_map().begin();
              it2 != parent.get_const_channel_map().end();
              it2++ )
         {
             int decay_mode = it2->first;
             DecayChannel channel = it2->second;
             // initialize parents[idString]["decay_modes"][decay_modeString]
             Json::Value j_mode( Json::objectValue );
             // populate parents[idString]["decay_modes"][decay_modeString]
             j_mode["branch_ratio"] = channel.get_branch_ratio();
             j_mode["yield_type"] = channel.get_yield_type();
             Json::Value j_yield_map( Json::objectValue );
             std::map<int, double>::const_iterator it3;
             for( it3 = channel.get_const_yield_map().begin();
                  it3 != channel.get_const_yield_map().end();
                  it3++ )
             {
                 int did = it3->first;  // residual id
                 double yield = it3->second;
                 j_yield_map[_to_id_string( did )] = yield;
             }
             j_mode["yield_map"] = j_yield_map;
             std::string decay_modeString =
                 ScaleUtils::IO::toString( decay_mode );
             j_decay_modes[decay_modeString] = j_mode;
         }  // end channels
         // populate parents[idString]["decay_modes"]
         j_parent["decay_modes"] = j_decay_modes;
         // populate parents[idString]
         j_parents[_to_id_string( id )] = j_parent;
     }
     j_root["parents"] = j_parents;
     Vec_Int modes;
     this->list_decay_modes( modes );
     for( size_t i = 0; i < modes.size(); i++ )
     {
         j_root["_present_decay_modes"][ScaleUtils::IO::toString( modes[i] )] =
             ScaleData::Utils::decay_mode_to_name( modes[i] );
     }
     j_root["_legend_times"]["1"] = "second";
     j_root["_legend_times"]["2"] = "minute";
     j_root["_legend_times"]["3"] = "hour";
     j_root["_legend_times"]["4"] = "day";
     j_root["_legend_times"]["5"] = "year";
     j_root["_legend_times"]["6"] = "NONE";
     j_root["_legend_times"]["7"] = "k-year";
     j_root["_legend_times"]["8"] = "M-year";
     j_root["_legend_times"]["9"] = "G-year";
     return j_root;
 }
std::string to_string () const
References DecayResource::to_json().
 {
     return this->to_json().toStyledString();
 }
Member Data Documentation
std::map<int, DecayParent> parent_map private
Referenced by DecayResource::calculate_decay_constants(), DecayResource::check_consistency(), DecayResource::check_ids(), DecayResource::get_const_parent_map(), DecayResource::get_parent_map(), DecayResource::list_decay_modes(), DecayResource::list_parent_ids(), DecayResource::num_decay_modes(), DecayResource::num_parents(), DecayResource::num_residuals(), and DecayResource::to_json().
const int ISOMERIC_YIELDS = 1 static
Examples:
Core/io/tests/tstDecayResourceIO.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by DecayResource::check_consistency(), Origen_DecayResource_ISOMERIC_YIELDS(), DecayResourceIO_cimg::read(), TEST(), and TEST_F().
const int IZZZAAA_YIELDS = 2 static
Referenced by DecayResource::check_consistency(), and Origen_DecayResource_IZZZAAA_YIELDS().
const int MISSING_YIELDS = 3 static
Examples:
Core/io/tests/tstDecayResourceIO.cpp.
Referenced by DecayResource::check_consistency(), Origen_DecayResource_MISSING_YIELDS(), DecayResourceIO_cimg::read(), and TEST().
The documentation for this class was generated from the following files:
Core/re/DecayResource.h
Core/re/DecayResource.cpp