ORIGEN API: GammaResourceIO_cimg Class Reference
GammaResourceIO_cimg Class Reference
#include <GammaResourceIO_cimg.h>
Public Member Functions
bool read (GammaResource &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const GammaResource &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Detailed Description
Examples:
tstGammaResourceIO.cpp.
Member Function Documentation
bool read (GammaResource & obj, std::istream & stream, ScaleUtils::IO::DB opts)
Examples:
tstGammaResourceIO.cpp.
References DiscreteSpectrum::add_line(), EmissionSpectrum::b_continuous, EmissionSpectrum::b_discrete, EmissionResource::b_emission, EmissionResource::b_field_id, EmissionSpectrum::b_field_id, EmissionResource::b_map, Origen::guess_last_bin_energy(), Spectrum::set_bounds(), and Spectrum::set_intensity().
bool write (const GammaResource & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
The documentation for this class was generated from the following files:
Core/io/GammaResourceIO_cimg.h
Core/io/GammaResourceIO_cimg.cpp