ORIGEN API: Solver/cram/src/kernel_cram.cpp File Reference
kernel_cram.cpp File Reference
CRAM depletion solver.
#include "Origen/Solver/cram/src/kernel_cram.hpp"
#include <stdio.h>
#include <cmath>
#include <ctime>
#include <iostream>
#include <limits>
#include <vector>
#include "ScaleUtils/SuperLU/SRC/slu_zdefs.h"
#include "Standard/Interface/jdebug.h"
Classes
struct LUstore
Macros
#define SORT_NUCLIDES 1
#define MAKE_EXPM_INPUT 0
#define MAKE_MATLAB_INPUT 0
#define NAME "Origen/Manager/Wrapper/kernel_cram.cpp"
Identifier for error messages.
Functions
void CopyLU (SuperMatrix *L, SuperMatrix *U, LUstore *LU)
void makeExpmInput (int itot, int a_n, int nnz, doublecomplex *a_val_complex, int *a_ci, int *rp, double delta_t, doublecomplex *Bvals, double **source_term, int source_order, int *ZAI)
void makeMatlabInput (int itot, int a_n, doublecomplex *a_val_complex, int *a_ci, int *a_rp, int *ZAI)
void sortCRSnuclides (int a_n, int a_nnz, double **a_val, int **a_ci, int **a_rp, int *newIdx, int *oldIdx, int sort_nuclides, int *ZAI)
int kernel_cram (double *n_out, double *n0, double **source_term, int source_order, double delta_t, int itot, int non, int *non0, int *kd, double *diag, double *offdiag, int *loc, int zero_flux_step, int is_adjoint, int cram_order, int internal_steps, int remove_negatives, double cutoff, int *ZAI)
void OrigenToCRSMatrix (int *p_a_n, double **p_a_val, int **p_a_ci, int **p_a_rp, int **p_a_diag_idx, int *p_a_nnz, int **p_newIdx, int **p_oldIdx, double **p_src_dummy_n0, int itot, int non, int *non0, int *kd, double *diag, double *offdiag, int *loc, double **source_term, int source_order, int zero_flux_step, int is_adjoint, int sort_nuclides, int *ZAI)
Detailed Description
CRAM depletion solver.
Author
Aarno Isotalo
Macro Definition Documentation
#define SORT_NUCLIDES 1
Sort nuclides if ZAI is provided (logical int). Sorting improves performance by factor of 2. Unless problems arise this should always be on.
Referenced by kernel_cram().
#define MAKE_EXPM_INPUT 0
Controls printing of input for an external test program. For internal testing purposes only. 0 = not printed, 1 = print with separate source, 2 = print with source merged to the matrix with dummy elements
Referenced by makeExpmInput().
#define MAKE_MATLAB_INPUT 0
Controls printing of the matrix in matlab form (logical int). For internal testing purposes only.
Referenced by makeMatlabInput().
#define NAME "Origen/Manager/Wrapper/kernel_cram.cpp"
Identifier for error messages.
Referenced by kernel_cram().
Function Documentation
void CopyLU (SuperMatrix * L, SuperMatrix * U, LUstore * LU)
Special fun fun copy the L and U matrices in SuperLU format.
This copies the pointers, not their contents. New Store is allocated. nzval (the non-zero values) pointers are also copied but then the nzval pointers in L U are set to point to new, freshly allocated memory. This way the data from L, U is now in LU without copying any memory. nzval in L, U are effectively reset, but they are not needed anyway (L,U are used to store the next LU decomposition for different pole in CRAM so nzval would be overwritten anyway.
Because the pointers, rather than the memory they point to is copied, all copies (except nzval) end up pointing to the same space, i.e., the "work" array in the solver. This works because Every A and thus every L, U has the same sparsity pattern.
The first pair of nzval (for term k=0) will point to work while the rest will point to the new arrays allocated on the previous k in this function.
Parameters
References LUstore::L, and LUstore::U.
Referenced by kernel_cram().
 {
     int i;
     doublecomplex* nzval;
     // manually copy all values and pointers in L
     // note that the memory pointers point to is not copied
     LU->L.Stype = L->Stype;
     LU->L.Dtype = L->Dtype;
     LU->L.Mtype = L->Mtype;
     LU->L.nrow = L->nrow;
     LU->L.ncol = L->ncol;
     LU->L.Store = (void*)SUPERLU_MALLOC( sizeof( SCformat ) );
     SCformat* LS_to = (SCformat*)LU->L.Store;
     SCformat* LS_from = (SCformat*)L->Store;
     LS_to->nnz = LS_from->nnz;
     LS_to->nsuper = LS_from->nsuper;
     LS_to->nzval = LS_from->nzval;
     LS_to->nzval_colptr = LS_from->nzval_colptr;
     LS_to->rowind = LS_from->rowind;
     LS_to->rowind_colptr = LS_from->rowind_colptr;
     LS_to->col_to_sup = LS_from->col_to_sup;
     LS_to->sup_to_col = LS_from->sup_to_col;
     // make new nzval for the original L
     // for supernodal size(nzval) is not nnz, count the actual size
     int nn = 0;
     for( i = 0; i <= LS_from->nsuper; ++i )
     {
         int c = LS_from->sup_to_col[i];
         int nsup = LS_from->sup_to_col[i + 1] - c;
         nn += nsup *
               ( LS_from->rowind_colptr[c + 1] - LS_from->rowind_colptr[c] );
     }
     // allocate
     nzval = (doublecomplex*)malloc( nn * sizeof( doublecomplex ) );
     LS_from->nzval = (void*)nzval;
     // Copy all values and pointers in U
     // Note that the memory pointers point to is not copied
     LU->U.Stype = U->Stype;
     LU->U.Dtype = U->Dtype;
     LU->U.Mtype = U->Mtype;
     LU->U.nrow = U->nrow;
     LU->U.ncol = U->ncol;
     LU->U.Store = (void*)SUPERLU_MALLOC( sizeof( NCformat ) );
     NCformat* US_to = (NCformat*)LU->U.Store;
     NCformat* US_from = (NCformat*)U->Store;
     US_to->nnz = US_from->nnz;
     US_to->nzval = US_from->nzval;
     US_to->rowind = US_from->rowind;
     US_to->colptr = US_from->colptr;
     // make new nzval for the original U
     nzval = (doublecomplex*)malloc( US_from->nnz * sizeof( doublecomplex ) );
     US_from->nzval = (void*)nzval;
 }
void makeExpmInput (int itot, int a_n, int a_nnz, doublecomplex * a_val_complex, int * a_ci, int * a_rp, double delta_t, doublecomplex * Bvals, double ** source_term, int source_order, int * ZAI)
Write the CRS matrix to a format used by an external test program "expm". This function exists for development purposes only. The input is written to file "expmInput" in current directory.
References MAKE_EXPM_INPUT, and r.
Referenced by kernel_cram().
 {
     FILE* out;
     int* ccs_ri;
     int* ccs_cp;
     doublecomplex* ccs_val;
     int i, j, real_nnz, real_n;
     if( MAKE_EXPM_INPUT == 0 )
     {
         return;
     }
     else if( MAKE_EXPM_INPUT == 1 )
     {
         printf( "Writing EXPM input (separate source) ... " );
         real_n = itot;
     }
     else if( MAKE_EXPM_INPUT == 2 )
     {
         printf( "Writing EXPM input (merged source) ... " );
         real_n = a_n;
     }
     else
     {
         fprintf(
             stderr, "MAKE_EXPM_INPUT invalid value %d\n", MAKE_EXPM_INPUT );
         std::exit( EXIT_FAILURE );
     }
     if( source_order > 0 )
     {
         fprintf( stderr, "EXPM does not support time dependent source\n" );
         std::exit( EXIT_FAILURE );
     }
     // Make CCS version for outputting to expm (test program)
     zCompRow_to_CompCol( a_n,
                          a_n,
                          a_nnz,
                          a_val_complex,
                          a_ci,
                          a_rp,
                          &ccs_val,
                          &ccs_ri,
                          &ccs_cp );
     real_nnz = 0;
     for( j = 0; j < real_n; j++ )
         for( i = ccs_cp[j]; i < ccs_cp[j + 1]; i++ )
             if( ccs_ri[i] < real_n )
                 if( ( ccs_val[i].r > 0.0 ) || ( ccs_ri[i] == j ) ) real_nnz++;
     out = std::fopen( "expmInput", "w" );
     if( MAKE_EXPM_INPUT == 1 )
         fprintf( out, "-1\n" );
     else
         fprintf( out, "1\n" );
     fprintf( out, "%.15e\n", delta_t );
     fprintf( out, "\n" );
     fprintf( out, "%4d %4d\n", real_n, real_n );
     for( i = 0; i < real_n; i++ )
     {
         fprintf( out, "%4d  %.15e ", i + 1, Bvals[i].r );
         if( MAKE_EXPM_INPUT == 1 )
         {
             if( source_order == 0 )
                 fprintf( out, "%.15e ", source_term[i][0] );
             else
                 fprintf( out, "%.15e ", 0.0 );
         }
         if( ZAI && ( i < itot ) )
             fprintf( out, "%d\n", ZAI[i] );
         else if( ZAI )
             fprintf( out, "%d\n", 9999999 - real_n + i + 1 );
         else
             fprintf( out, "%d\n", i );
     }
     fprintf( out, "%4d %d\n", real_n, real_nnz );
     for( j = 0; j < real_n; j++ )
         for( i = ccs_cp[j]; i < ccs_cp[j + 1]; i++ )
             if( ccs_ri[i] < real_n )
                 if( ( ccs_val[i].r > 0.0 ) || ( ccs_ri[i] == j ) )
                     fprintf( out,
                              "%4d %4d % .15e %d\n",
                              ccs_ri[i] + 1,
                              j + 1,
                              ccs_val[i].r,
                              666 );
     std::fclose( out );
     free( ccs_ri );
     free( ccs_cp );
     free( ccs_val );
     printf( "DONE\n" );
 }
void makeMatlabInput (int itot, int a_n, doublecomplex * a_val_complex, int * a_ci, int * a_rp, int * ZAI)
Write the matrix and ZAI to a .m file
References MAKE_MATLAB_INPUT, and r.
Referenced by kernel_cram().
 {
     FILE* out;
     int i, j;
     if( MAKE_MATLAB_INPUT == 0 ) return;
     printf( "PRINTING MATLAB FORM (matrix.m)... " );
     // the matrix
     out = std::fopen( "matrix.m", "w" );
     fprintf( out, "A=zeros(%d,%d);\n", a_n, a_n );
     for( i = 0; i < a_n; i++ )                    // rows
         for( j = a_rp[i]; j < a_rp[i + 1]; j++ )  // elements on a row
             fprintf( out,
                      "A(%4d,%4d)=% .20e;\n",
                      i + 1,
                      a_ci[j] + 1,
                      a_val_complex[j].r );
     fprintf( out, "\n" );
     // ZAI
     fprintf( out, "ZAI=zeros(%d,1);\n", a_n );
     if( ZAI )
         for( i = 0; i < itot; i++ )
             fprintf( out, "ZAI(%d)=%8d;\n", i + 1, ZAI[i] );
     else
         for( i = 0; i < itot; i++ )
             fprintf( out, "ZAI(%d)=%8d;\n", i + 1, -i - 1 );
     for( i = itot; i < a_n; i++ )  // rows
         fprintf( out, "ZAI(%d)=%8d;\n", i + 1, 9999990 + i - itot );
     fprintf( out, "\n" );
     std::fclose( out );
     printf( "DONE\n" );
 }
void sortCRSnuclides (int a_n, int a_nnz, double ** p_a_val, int ** p_a_ci, int ** p_a_rp, int * newIdx, int * oldIdx, int sort_nuclides, int * ZAI)
Sorts nuclides in a CRS matrix decay/transmutation system by ascending ZAI.
Input is a CRS matrix and a ZAI array. ZAI can be nullptr in which case sorting is not performed. The oldIdx and newIdx arrays are generated either way (they are trivial if no sorting was done).
Parameters
[in] a_n Size of the CRS matrix A
[in] a_nnz Number of elements in CRS matrix A
[in,out] p_a_val[a_nnz] Non-zero elements of CRS matrix A
[in,out] p_a_ci[a_nnz] Column indices of CRS matrix A
[in,out] p_a_rp[itot+1] Row pointers of CRS matrix A
[out] oldIdx[itot] oldIdx[i] is the old index of the nuclide that has new index i
[out] newIdx[itot] newIdx[i] is the new index of the nuclide that had old index i
[in] sort_nuclides Logical, whether to actually sort the nuclides
[in] ZAI[itot] ZAI identifiers of the nuclides. Can be nullptr in which case sorting is not actually done. (Still needs to be called to set the index arrays.)
Referenced by OrigenToCRSMatrix().
 {
     double* a_val = *p_a_val;
     int* a_ci = *p_a_ci;
     int* a_rp = *p_a_rp;
     double* na_val;
     int *na_ci, *na_rp;
     int i, j, tmp_ZAI, tmp_idx, idx_na;
     /*** initialize the index arrays ***/
     for( i = 0; i < a_n; i++ )
     {
         newIdx[i] = i;
         oldIdx[i] = i;
     }
     /*** check that indexing can and should be done ***/
     if( sort_nuclides && !ZAI )
     {
         jDebugLine( "   WARNING: sort_nuclides = 1 but ZAI is nullptr!" );
     }
     if( !ZAI )
     {
         jDebugLine( "   Sorting nuclides... NOT DONE: ZAI not provided." );
         return;
     }
     else if( !sort_nuclides )
     {
         jDebugLine( "   Sorting nuclides... NOT DONE: sort_nuclides = 0" );
         return;
     }
     else
     {
         jDebugLine( "   Sorting nuclides..." );
     }
     /*** sort ZAI (insertion sort) ***/
     for( i = 0; i < a_n; i++ )
     {  // nuclides
         // move the idx_a:th element left until the left side is sorted
         tmp_ZAI = ZAI[i];
         tmp_idx = oldIdx[i];
         j = i;
         // move each element that should be after idx_a:th one to the right
         while( ( j > 0 ) && ( j < a_n ) && ( ZAI[j - 1] > tmp_ZAI ) )
         {
             ZAI[j] = ZAI[j - 1];
             oldIdx[j] = oldIdx[j - 1];
             j--;
         }
         // put the moved element
         ZAI[j] = tmp_ZAI;
         oldIdx[j] = tmp_idx;
     }
     /*** fill in newIdx ***/
     for( i = 0; i < a_n; i++ ) newIdx[oldIdx[i]] = i;
     /*** change the column indices ***/
     for( i = 0; i < a_nnz; i++ ) a_ci[i] = newIdx[a_ci[i]];
     /*** rearrange the rows ***/
     na_val = (double*)calloc( a_nnz, sizeof( double ) );
     na_ci = (int*)calloc( a_nnz, sizeof( int ) );
     na_rp = (int*)calloc( a_n + 1, sizeof( int ) );
     idx_na = 0;  // index in na
     for( i = 0; i < a_n; i++ )
     {  // i = NEW rows
         // row j=oldIdx[i] becomes row i
         j = oldIdx[i];
         na_rp[i] = idx_na;
         std::copy( a_val + a_rp[j], a_val + a_rp[j + 1], na_val + idx_na );
         std::copy( a_ci + a_rp[j], a_ci + a_rp[j + 1], na_ci + idx_na );
         idx_na += a_rp[j + 1] - a_rp[j];
     }
     na_rp[a_n] = a_nnz;
     /*** free the old a ***/
     free( a_val );
     free( a_ci );
     free( a_rp );
     /*** set the return pointers to new a ***/
     *p_a_val = na_val;
     *p_a_ci = na_ci;
     *p_a_rp = na_rp;
 }
int kernel_cram (double * n_out, double * n0, double ** source_term, int source_order, double delta_t, int itot, int non, int * non0, int * kd, double * diag, double * offdiag, int * loc, int zero_flux_step, int is_adjoint, int cram_order, int internal_steps, int remove_negatives, double cutoff, int * ZAI)
CRAM depletion solver with source term and adjoint capabilities.
Based on the publication: Pusa, M. and Leppnen, J. "Computing the matrix exponential in burnup calculations." Nucl. Sci. Eng., 164 (2010) 140-150.
The required linear system solutions are done with the SuperLU library: Xiaoye S. Li. "An Overview of {SuperLU}: Algorithms, Implementation, and User Interface." ACM Trans.Math. Softw., 31;3 (2005) 302-325.
Fortran should call kernel_cram_from_fortran() instead.
Source term can have polynomial time dependency. Due to numerical issues source order is limited to cram_order/2-2. Non constant source term will cause some deterioration in accuracy, but below this limit it should be negligible.
Adjoint calculation is also possible by passing is_adjoint=1. In adjoint mode n0, source_term and delta_t>0 must be those for the adjoint problem while everything else must have values defining the forward system.
Internal substeps: Dividin steps to pieces greatly improved accuracy. This is particularly significant for decay problems where accuracy without might not be good enough for all purposes. The solver can do this division internally, which is more efficient than calling the solver multiple times as the LU decompositions only need to be formed once. internal_steps=1 means means that there is no substepping. Setting internal_steps=2 increases running time by roughly 25%. Each substep above 2 increases it by another 10-15% of the running time without substepping. See *** for details.
Parameters
[out] n_out[itot] Final concentrations. Must be Pre-allocated.
[in] n0[itot] Initial concentrations
[in] source_term[itot][source_order+1] Polynomial coefficients s_i,j for the source term
[in] source_order Order of the source term polynomial
[in] delta_t Length of the time step in seconds
[in] itot The number of nuclides in the system
[in] non Number of reactions (inc. decay) in the system
[in] non0[itot] Number of parents for each nuclide
[in] kd[itot] Number of decay parents for each nuclide
[in] diag[itot] Diagonal elements of A, i.e., (-lambda_eff)
[in] offdiag[non] Reaction specific decay constant of each reaction.
[in] loc[non] Index of the parent in each reaction.
[in] zero_flux_step Logical integer, is the flux zero?
[in] is_adjoint Logical integer, is this adjoint calculation?
[in] cram_order Order of the CRAM approximation (just use 16).
[in] internal_steps Number of internal substeps to use
[in] remove_negatives How to treat negative vaues in results: 0: Do nothing. 1: Remove all negative values. 2: Remove all negative values in forward mode. Remove all negative values in adjoint mode if source term is constant and both source and initial concentrations are non-negative.
[in] cutoff Concentrations whose ABSOLUTE value is below cutoff times sum(abs(n_out)) are set to zero. This is applied after remove_negatives.
[in] ZAI[itot] ZAI identifiers of the nuclides.
Note
The indexing in loc must be in c style, i.e., starts from 0. Be avare of this when calling from Fortran.
offdiag (which is called "a" in most of Origen source code) and loc must be sorted in the special Origen way:
decay parents of first nuclide,
activation parents of first nuclide,
decay parents of second nuclide,
activation parents of the second,
and so on.
The culling feature from earlier versions was removed. Use internal substeps instead.
Returns
zero on successfull exit or nonzero on failed exit. On failed exit the results (i.e., n) are unspecified.
Examples:
Solver/cram/src/tests/tstCRAM.cpp.
References LUstore::C, CopyLU(), LUstore::equed, Origen::info(), kernel_cram_coefficients(), makeExpmInput(), makeMatlabInput(), NAME, OrigenToCRSMatrix(), r, LUstore::R, and SORT_NUCLIDES.
Referenced by kernel_cram_from_fortran(), Solver_cram::solve_impl(), TEST(), and TEST_F().
 {
     /*** The input/output varaibles for "expert mode" SuperLU driver
      * ***********/
     superlu_options_t options;
     SuperMatrix A;  // the coefficient matrix
     int* perm_r;    // row permutations from partial pivoting
     int* perm_c;    // column permutation vector
     int* etree;
     char equed[1];
     double* R;
     double* C;
     SuperMatrix L;
     SuperMatrix U;
     void* work;
     int lwork;
     SuperMatrix B;  // righe hand side
     SuperMatrix X;  // solution
     double recip_pivot_growth;
     double rcond;
     double* FERR;
     double* BERR;
     mem_usage_t mem_usage;
     SuperLUStat_t stat;
     int info;
     LUstore LU[8];  // store the LU decompositions for other internal substeps
     /*** Other variables
      * *******************************************************/
     // CRS matrix A (The modified coefficient matrix or further modified)
     int a_n;                       // size
     int a_nnz;                     // number of allocated elements
     double* a_val;                 // allocated elements
     doublecomplex* a_val_complex;  // allocated elements converted to complex
     int* a_rp;                     // row pointers
     int* a_ci;                     // column indices
     int* a_diag_idx;       // indices of the diagonal elements of A
     double* a_diag;        // copy of the diagonal values of A
     int *newIdx, *oldIdx;  // see sortCRSnuclides()
     double*
         src_dummy_n0;  // initial concentrations of dummy nuclides for source
     int nrhs;  // number of different right hand sides (initial compositions)
     // to solve for in superLU
     double* n;  // concentrations of nuclides, inc. dummies.
     // this has the same inexing as n0
     doublecomplex *Bvals, *Xvals;              // internal storage of B and X
     doublecomplex alpha0, alpha[8], theta[8];  // CRAM coefficients
     char tmpstr[512];
     int i, k, s;
     /*** SuperLU solver options
      * ************************************************/
     set_default_options( &options );  // set default options
     options.Equil = NO;          // no scaling
     options.Fact = DOFACT;       // solve from scratch (for first time only)
     options.ColPerm = MY_PERMC;  // hand set column permutations (set to none)
     options.IterRefine = NOREFINE;
     options.DiagPivotThresh = 0.0;  // do not pivot unless it cannot be avoided
     options.SymmetricMode = NO;     // matrix is not symmetric
     options.PivotGrowth = NO;       // do not calculate pivotal growth
     options.ConditionNumber = NO;   // do not calculate condition number
     options.RowPerm = NOROWPERM;    // no row permutations
     // options.PrintStat = YES;      // does not do anything
     if( !is_adjoint ) options.Trans = NOTRANS;  // forward calculation
     if( is_adjoint )
         options.Trans = TRANS;  // adjoint calculation (transpose A)
     /*** Time the whole solver
      * *************************************************/
     jDebugBlock( std::clock_t start = std::clock() );
     /*** Check input
      * ***********************************************************/
     if( ( cram_order < 4 ) || ( cram_order > 16 ) || ( cram_order % 2 != 0 ) )
     {
         sprintf( tmpstr,
                  "%s: invalid CRAM order %d. (must be 4-16 and even)\n",
                  NAME,
                  cram_order );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( source_order > cram_order / 2 - 2 )
     {
         sprintf(
             tmpstr,
             "%s: Source term order %d is above the maximum (cram_order/2-2)\n",
             NAME,
             source_order );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( ( source_order >= 0 ) && !( source_term ) )
     {
         sprintf( tmpstr,
                  "%s: Source term is nullptr but source term order %d\n",
                  NAME,
                  source_order );
         SErrLine( 1, tmpstr );
         sprintf( tmpstr,
                  "%s: source_term can only be nullptr for source_order < 0\n",
                  NAME );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( ( remove_negatives < 0 ) || ( remove_negatives > 2 ) )
     {
         sprintf( tmpstr,
                  "%s: remove_negatives has invalid value %d "
                  "(valid values are 0, 1, 2)\n",
                  NAME,
                  remove_negatives );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( cutoff < 0.0 )
     {
         sprintf( tmpstr, "%s: cutoff must be non-negative\n", NAME );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( !n_out || !n0 || !non0 || !kd || !diag || !offdiag || !loc )
     {
         sprintf( tmpstr,
                  "%s: nullptr argument other than source_term, ZAI\n",
                  NAME );
         SErrLine( 1, tmpstr );
         return 1;
     }
     /*** Build modified coefficient matrix A
      * ***********************************/
     OrigenToCRSMatrix( &a_n,
                        &a_val,
                        &a_ci,
                        &a_rp,
                        &a_diag_idx,
                        &a_nnz,
                        &newIdx,
                        &oldIdx,
                        &src_dummy_n0,
                        itot,
                        non,
                        non0,
                        kd,
                        diag,
                        offdiag,
                        loc,
                        source_term,
                        source_order,
                        zero_flux_step,
                        is_adjoint,
                        SORT_NUCLIDES,
                        ZAI );
     // store a copy of the diagonal elements
     a_diag = (double*)calloc( a_n, sizeof( double ) );
     for( i = 0; i < a_n; i++ ) a_diag[i] = a_val[a_diag_idx[i]];
     // convert a_val to complex
     a_val_complex = (doublecomplex*)calloc( a_nnz, sizeof( doublecomplex ) );
     for( i = 0; i < a_nnz; i++ ) a_val_complex[i].r = a_val[i];
     free( a_val );
     // convert to SuperLU format, note that a_* arrays are not copied
     zCreate_CompRow_Matrix(
         &A, a_n, a_n, a_nnz, a_val_complex, a_ci, a_rp, SLU_NR, SLU_Z, SLU_GE );
     /*** Set up other junk
      * *****************************************************/
     // number of right hand sides (back to always having 1)
     nrhs = 1;
     // nuclide compositions
     n = (double*)calloc( a_n, sizeof( double ) );
     // Create right-hand side matrix B (itot x nrhs)
     Bvals = (doublecomplex*)calloc( a_n * nrhs, sizeof( doublecomplex ) );
     zCreate_Dense_Matrix( &B, a_n, nrhs, Bvals, a_n, SLU_DN, SLU_Z, SLU_GE );
     // Write the initial composition to B
     for( i = 0; i < itot; i++ )
     {  // old idx
         Bvals[newIdx[i]].r = n0[i];
         Bvals[newIdx[i]].i = 0.0;
     }
     for( i = itot; i < a_n; i++ )
     {  // old idx
         Bvals[( nrhs - 1 ) * a_n + newIdx[i]].r = src_dummy_n0[i - itot];
         Bvals[( nrhs - 1 ) * a_n + newIdx[i]].i = 0.0;
     }
     // Create a matrix (itot x nrhs) to hold the solution
     Xvals = (doublecomplex*)calloc( a_n * nrhs, sizeof( doublecomplex ) );
     zCreate_Dense_Matrix( &X, a_n, nrhs, Xvals, a_n, SLU_DN, SLU_Z, SLU_GE );
     /* Column and row pivoting vectors (no pivoting) */
     perm_r = (int*)calloc( a_n, sizeof( int ) );
     perm_c = (int*)calloc( a_n, sizeof( int ) );
     for( i = 0; i < a_n; i++ )
     {
         perm_r[i] = i;
         perm_c[i] = i;
     }
     // work arrays for SuperLU
     // WORK, R, C must go to LUstore. NOTE: the old recycled work
     work = nullptr;
     lwork = 0;
     etree = (int*)calloc( a_n, sizeof( int ) );
     R = (double*)calloc( a_n, sizeof( double ) );
     C = (double*)calloc( a_n, sizeof( double ) );
     FERR = (double*)calloc( nrhs, sizeof( double ) );
     BERR = (double*)calloc( nrhs, sizeof( double ) );
     /* Initialize the statistics variables. */
     StatInit( &stat );
     // produce input for an external test program (Debug/development only)
     makeExpmInput( itot,
                    a_n,
                    a_nnz,
                    a_val_complex,
                    a_ci,
                    a_rp,
                    delta_t,
                    Bvals,
                    source_term,
                    source_order,
                    ZAI );
     // produce matlab input (for more testing)
     makeMatlabInput( itot, a_n, a_val_complex, a_ci, a_rp, ZAI );
     // get CRAM coefficients
     kernel_cram_coefficients( &alpha0, alpha, theta, cram_order );
     // A -> A*t     t = length of internal step!
     for( i = 0; i < a_nnz; i++ )
         a_val_complex[i].r *= ( delta_t / (double)internal_steps );
     /*** calculate n=e^{At}*n0 with CRAM
      * ***************************************/
     jDebugLine( "Evaluating order " << cram_order << " CRAM solution." );
     jDebugLine( "  " << internal_steps << " internal substeps." );
     jDebugBlock( std::clock_t start_calc =
                      std::clock() );  // time the main loop
     for( s = 0; s < internal_steps; s++ )
     {
         // alpha0 term
         for( i = 0; i < a_n; i++ ) n[oldIdx[i]] = alpha0.r * Bvals[i].r;
         /*** sum over the poles ***/
         for( k = 0; k < cram_order / 2; k++ )
         {
             // reuse stuff
             if( k == 1 && s == 0 ) options.Fact = SamePattern_SameRowPerm;
             if( s == 1 ) options.Fact = FACTORED;
             // change variable "A" from (A*t) to (A*t - theta(k)*I)
             // This is needed even when LU is recycled.
             for( i = 0; i < a_n; i++ )
             {  // i = new index
                 a_val_complex[a_diag_idx[i]].r =
                     a_diag[i] * ( delta_t / (double)internal_steps ) -
                     theta[k].r;
                 a_val_complex[a_diag_idx[i]].i = -theta[k].i;
             }
             // Solve (A*t -theta(k)*I)x=n0 for x
             if( s == 0 )
             {
                 // On the first substep we use all the variables (memory slots)
                 // defined in kernel_cram() for each solve.
                 // L,U,R,C are stored from each solve if there are internal
                 // steps
                 zgssvx( &options,
                         &A,
                         perm_c,
                         perm_r,
                         etree,
                         equed,
                         R,
                         C,
                         &L,
                         &U,
                         &work,
                         lwork,
                         &B,
                         &X,
                         &recip_pivot_growth,
                         &rcond,
                         FERR,
                         BERR,
                         &mem_usage,
                         &stat,
                         &info );
             }
             else
             {
                 // After first substep we reuse the LU decompositions from the
                 // first substep (U,K,R,C) stored to LU[k].
                 // other stuff is the same as on the first substep.
                 zgssvx( &options,
                         &A,
                         perm_c,
                         perm_r,
                         etree,
                         LU[k].equed,
                         &( LU[k].R[0] ),
                         &( LU[k].C[0] ),
                         &( LU[k].L ),
                         &( LU[k].U ),
                         &work,
                         lwork,
                         &B,
                         &X,
                         &recip_pivot_growth,
                         &rcond,
                         FERR,
                         BERR,
                         &mem_usage,
                         &stat,
                         &info );
             }
             // Check solver output
             if( info != 0 )
             {
                 sprintf( tmpstr,
                          "%s: SuperLU solver failed with error code %d\n",
                          NAME,
                          info );
                 SErrLine( 1, tmpstr );
                 return 1;
             }
             if( equed[0] != 'N' )
             {
                 sprintf( tmpstr,
                          "%s: SuperLU solver equed is not N but %s\n",
                          NAME,
                          equed );
                 SErrLine( 1, tmpstr );
                 return 1;
             }
             if( ( s == 0 ) && ( internal_steps > 1 ) )
             {
                 // Store the LU decomposition:
                 CopyLU( &L, &U, &( LU[k] ) );
                 // These are also needed by SuperLU to ge with the decomposition
                 LU[k].R.resize( a_n );
                 std::copy( R, R + a_n, &( LU[k].R[0] ) );
                 LU[k].C.resize( a_n );
                 std::copy( C, C + a_n, &( LU[k].C[0] ) );
                 LU[k].equed[0] = equed[0];
             }
             /*** Add this term to the results (real part only) ***/
             for( i = 0; i < a_n; i++ )  // i=new index
                 n[oldIdx[i]] +=
                     2 * ( alpha[k].r * Xvals[i].r - alpha[k].i * Xvals[i].i );
         }
         /*** Make the substep final composition the initial for next substep
          * ***/
         for( i = 0; i < a_n; i++ )
         {  // old idx
             Bvals[newIdx[i]].r = n[i];
             Bvals[newIdx[i]].i = 0.0;
         }
     }
     /*** Copy the final concentrations of real nuclides to output ***/
     for( i = 0; i < itot; i++ ) n_out[i] = n[i];
     /*** Remove negative values from the results if that was requested ***/
     bool cull = false;  // Whether to remove negatives
     if( remove_negatives == 0 )
         cull = false;
     else if( remove_negatives == 1 )
         cull = true;
     else if( remove_negatives == 2 )
     {
         cull = true;
         if( is_adjoint != 0 )
         {
             if( source_order > 0 ) cull = false;
             if( cull == true )
                 for( i = 0; i < itot; i++ )
                     if( n0[i] < 0.0 )
                     {
                         cull = false;
                         break;
                     }
             if( ( cull == true ) && ( source_order == 0 ) )
                 for( i = 0; i < itot; i++ )
                     if( source_term[i][0] < 0.0 )
                     {
                         cull = false;
                         break;
                     }
         }
     }
     if( cull )
         for( i = 0; i < itot; i++ )
             if( n_out[i] < 0.0 ) n_out[i] = 0.0;
     /*** Apply the cutoff for atomic densities ***/
     if( cutoff != 0.0 )
     {
         double n_tot = 0.0;
         for( i = 0; i < itot; i++ ) n_tot += std::fabs( n_out[i] );
         double n_limit = cutoff * n_tot;
         for( i = 0; i < itot; i++ )
             if( std::fabs( n_out[i] ) < n_limit ) n_out[i] = 0.0;
     }
     /*** Print some statistics ***/
     // can't enable this unless it goes to STDERR (currently muddies up output
     // file)
     // jDebugBlock(StatPrint(&stat));
     jDebugLine(
         "CRAM solution completed in "
         << 1000 * (double)( std::clock() - start ) / (double)CLOCKS_PER_SEC
         << " ms, of which "
         << 1000 * (double)( std::clock() - start_calc ) / (double)CLOCKS_PER_SEC
         << " ms in the main solver loop" );
     /*** De-allocate storage ***/
     Destroy_CompRow_Matrix( &A );
     Destroy_SuperMatrix_Store( &B );
     Destroy_SuperMatrix_Store( &X );
     Destroy_SuperNode_Matrix( &L );
     Destroy_CompCol_Matrix( &U );
     StatFree( &stat );
     if( internal_steps > 1 )
         for( k = 0; k < cram_order / 2; k++ )
         {
             free( ( (SCformat*)LU[k].L.Store )->nzval );
             free( ( (SCformat*)LU[k].U.Store )->nzval );
             free( LU[k].L.Store );
             free( LU[k].U.Store );
         }
     free( work );
     free( Bvals );
     free( Xvals );
     free( perm_r );
     free( perm_c );
     free( n );
     free( FERR );
     free( BERR );
     free( etree );
     free( R );
     free( C );
     free( a_diag );
     free( a_diag_idx );
     free( newIdx );
     free( oldIdx );
     if( source_order >= 0 ) free( src_dummy_n0 );
     return 0;
 }
void OrigenToCRSMatrix (int * p_a_n, double ** p_a_val, int ** p_a_ci, int ** p_a_rp, int ** p_a_diag_idx, int * p_a_nnz, int ** p_newIdx, int ** p_oldIdx, double ** p_src_dummy_n0, int itot, int non, int * non0, int * kd, double * diag, double * offdiag, int * loc, double ** source_term, int source_order, int zero_flux_step, int is_adjoint, int sort_nuclides, int * ZAI)
Convert ORIGEN form input to regular compressed row storage (CRS) matrix representing the equivalent homogeneous equations.
This has two main functions:
Build the actual coefficient matrix
Homogenize the equations (i.e., dn/dt = An +s ==> dn'/dt = A'n')
which are done simultaneously. In addition this:
Allocates all diagonal elements (even zeros)
Sorts nuclides by ZAI
Sorts each row
For details about the homogenization see:
Note
The first nine arguments are used for output. They are pointers to the variables p_<name in kernel_cram()> The other arguments are same as for kernel_cram(). The output, except for p_a_n and p_a_nnz which are scalars, will be allocated by this function.
Examples:
Solver/cram/src/tests/tstCRAM.cpp.
References sortCRSnuclides().
Referenced by kernel_cram(), TEST(), and tstOrigenToCRSMatrix::~tstOrigenToCRSMatrix().
 {
     int num_src;        // number of nonzero coefficients in source term
     int num_dummy;      // number of dummy nuclides
     int* ZAI_with_src;  // ZAI but with made up values for dummies appended
     double* src_dummy_n0 =
         nullptr;  // (initial) concentrations of dummy elements
     int i, j, p, pmax, idx_a, rowstart;
     int a_n, a_nnz;
     jDebugLine( "Building CRS matrix A..." );
     /*** Source term background work
      * *******************************************/
     // Count the total number of non zero coefficients in the source term
     num_src = 0;
     for( i = 0; i < itot; i++ )
         for( j = 0; j < source_order + 1; j++ )
             if( source_term[i][j] != 0.0 ) num_src++;
     // Number of source term dummy nuclides
     num_dummy = source_order + 1;
     if( num_dummy > 0 )
     {
         jDebugLine( "   Order " << source_order << " source term with "
                                 << num_src
                                 << " non-zero elements" );
     }
     else
     {
         jDebugLine( "   No source term" );
     }
     // The size of the matrix when source has been included
     // a_nnz may later be reduced if decay and transmutation get merged
     a_n = itot + num_dummy;
     a_nnz = a_n + non + num_src + ( a_n - itot );
     // allocate
     if( num_dummy > 0 )
     {
         src_dummy_n0 = (double*)calloc( num_dummy, sizeof( double ) );
         src_dummy_n0[0] = 1.0;
     }
     // Make a copy of ZAI with possible dummies appended to the end.
     // Dummies get large bogus ZAI so that they won't get moved in sorting
     if( ZAI )
     {
         ZAI_with_src = (int*)calloc( a_n, sizeof( int ) );
         std::copy( ZAI, ZAI + itot, ZAI_with_src );
         for( i = itot; i < a_n; i++ ) ZAI_with_src[i] = 9000000 + ( i - itot );
     }
     else
         ZAI_with_src = nullptr;
     /*** allocate space ***/
     // These are the same as in kernel_cram()
     double* a_val = (double*)calloc( a_nnz, sizeof( double ) );
     int* a_ci = (int*)calloc( a_nnz, sizeof( int ) );
     int* a_rp = (int*)calloc( a_n + 1, sizeof( int ) );
     int* newIdx = (int*)calloc( a_n, sizeof( int ) );
     int* oldIdx = (int*)calloc( a_n, sizeof( int ) );
     int* a_diag_idx = (int*)calloc( a_n, sizeof( int ) );
     // work arrays
     double* rowval = (double*)calloc( 2 * itot, sizeof( double ) );
     int* rowloc = (int*)calloc( 2 * itot, sizeof( int ) );
     /*** fill in CRS form (unsorted) ***/
     idx_a = 0;     // index in a
     rowstart = 0;  // index from which the row starts in offdiag
     for( i = 0; i < itot; i++ )
     {  // rows
         a_rp[i] = idx_a;  // row i starts at...
         // copy the values (to avoid modifying the input)
         std::copy( &loc[rowstart], &loc[rowstart] + non0[i], rowloc );
         std::copy( &offdiag[rowstart], &offdiag[rowstart] + non0[i], rowval );
         // add the diagonal element to beginning of each row
         a_val[idx_a] = diag[i];
         a_ci[idx_a] = i;
         idx_a++;
         /*** add offdiagonal elements ***/
         if( zero_flux_step )
             pmax = kd[i];
         else
             pmax = non0[i];
         for( p = 0; p < pmax; p++ )
         {
             /* nuclide ZAI[i] is produced from nuclide ZAI[rowloc[p]] */
             // find out if matrix element (i,p) already exists
             for( j = a_rp[i]; j < idx_a; j++ )
             {
                 if( a_ci[j] == rowloc[p] )
                 {
                     // the element already exists, add to it
                     a_val[j] += rowval[p];
                     break;
                 }
             }
             if( j == idx_a )
             {
                 // the element does not exist, add the element
                 a_val[idx_a] = rowval[p];
                 a_ci[idx_a] = rowloc[p];
                 idx_a++;
             }
         }
         /*** add source term elements ***/
         for( j = 0; j < source_order + 1; j++ )
             if( ( source_term[i][j] != 0.0 ) && ( !is_adjoint ) )
             {
                 a_val[idx_a] = source_term[i][j];
                 a_ci[idx_a] = itot + j;
                 idx_a++;
             }
         // next row starts at...
         rowstart += non0[i];
     }
     a_rp[itot] = idx_a;
     /*** add source term dummy element rows ***/
     for( i = 0; i < num_dummy; i++ )
     {  // dummy row = itot+i
         // in adjoint calculation source is on the last row so that when the
         // matrix is transposed it ends up in the last column
         if( is_adjoint )
             for( j = 0; j < itot; j++ )  // columns = nuclides
                 if( source_term[j][i] != 0.0 )
                 {
                     a_val[idx_a] = source_term[j][i];
                     a_ci[idx_a] = j;
                     idx_a++;
                 }
         // the offdiagonal "produce dummy from dummy" element
         // note that we are left from diagonal for forward
         if( ( !is_adjoint ) && ( i > 0 ) )
         {
             a_val[idx_a] = i;
             a_ci[idx_a] = itot + i - 1;
             idx_a++;
         }
         // diagonal
         a_val[idx_a] = 0;
         a_ci[idx_a] = itot + i;
         idx_a++;
         // the offdiagonal "produce dummy from dummy" element
         // note that we want it left of diagonal after transpose
         if( ( is_adjoint ) && ( i < num_dummy - 1 ) )
         {
             a_val[idx_a] = i + 1;
             a_ci[idx_a] = itot + i + 1;
             idx_a++;
         }
         a_rp[itot + i + 1] = idx_a;
     }
     // the real size of the system (arrays are not reallocated)
     a_nnz = idx_a;
     /*** sort the nuclides (maybe) ***/
     sortCRSnuclides( a_n,
                      a_nnz,
                      &a_val,
                      &a_ci,
                      &a_rp,
                      newIdx,
                      oldIdx,
                      sort_nuclides,
                      ZAI_with_src );
     /*** Sort each row by column index (insertion sort) ***/
     for( i = 0; i < a_n; i++ )  // rows
         for( idx_a = a_rp[i] + 1; idx_a < a_rp[i + 1]; idx_a++ )
         {  // elements on row
             // move the idx_a:th element left until the left side is sorted
             int tmp_ci = a_ci[idx_a];
             double tmp_val = a_val[idx_a];
             j = idx_a;
             // move each element that should be after idx_a:th one to the right
             while( ( j > 0 ) && ( j > a_rp[i] ) && ( a_ci[j - 1] > tmp_ci ) )
             {
                 a_ci[j] = a_ci[j - 1];
                 a_val[j] = a_val[j - 1];
                 j--;
             }
             // put the moved element
             a_ci[j] = tmp_ci;
             a_val[j] = tmp_val;
         }
     /*** find diagonal element indices ***/
     for( i = 0; i < a_n; i++ )  // rows
         for( idx_a = a_rp[i]; idx_a < a_rp[i + 1]; idx_a++ )
             if( a_ci[idx_a] == i )
             {
                 a_diag_idx[i] = idx_a;
                 break;
             }
     /*** set the return values/pointers ***/
     *p_a_n = a_n;
     *p_a_nnz = a_nnz;
     *p_a_val = a_val;
     *p_a_ci = a_ci;
     *p_a_rp = a_rp;
     *p_a_diag_idx = a_diag_idx;
     *p_newIdx = newIdx;
     *p_oldIdx = oldIdx;
     *p_src_dummy_n0 = src_dummy_n0;
     /*** free memory ***/
     free( rowval );
     free( rowloc );
     if( ZAI_with_src ) free( ZAI_with_src );
 }