ORIGEN API: Solver/cram/src/kernel_cram.hpp File Reference
kernel_cram.hpp File Reference
Header for kernel_cram.cpp, kernel_cram_coefficients.cpp and kernel_cram_from_fortran.cpp.
#include "ScaleUtils/SuperLU/SRC/slu_dcomplex.h"
#include "Standard/Interface/Reporter.h"
Functions
int kernel_cram (double *n, double *n0, double **source_term, int source_order, double delta_t, int itot, int non, int *non0, int *kd, double *diag, double *a, int *loc, int zero_flux_step, int is_adjoint, int cram_order, int internal_steps, int remove_negatives, double cutoff, int *ZAI)
void OrigenToCRSMatrix (int *a_n, double **p_a_val, int **p_a_ci, int **p_a_rp, int **p_a_diag_idx, int *a_nnz, int **p_newIdx, int **p_oldIdx, double **src_dummy_n0, int itot, int non, int *non0, int *kd, double *diag, double *offdiag, int *loc, double **source_term, int source_order, int zero_flux_step, int is_adjoint, int sort_nuclides, int *ZAI)
int kernel_cram_from_fortran (double *n, double *n0, double *source_term, int source_order, double delta_t, int itot, int non, int *non0, int *kd, double *diag, double *a, int *loc, int zero_flux_step, int is_adjoint, int cram_order, int internal_steps, int remove_negatives, double cutoff, int *ZAI)
int kernel_cram_coefficients (doublecomplex *alpha0, doublecomplex *alpha, doublecomplex *theta, int cram_order)
Detailed Description
Header for kernel_cram.cpp, kernel_cram_coefficients.cpp and kernel_cram_from_fortran.cpp.
Author
Aarno Isotalo
Function Documentation
int kernel_cram (double * n_out, double * n0, double ** source_term, int source_order, double delta_t, int itot, int non, int * non0, int * kd, double * diag, double * offdiag, int * loc, int zero_flux_step, int is_adjoint, int cram_order, int internal_steps, int remove_negatives, double cutoff, int * ZAI)
CRAM depletion solver with source term and adjoint capabilities.
Based on the publication: Pusa, M. and Leppänen, J. "Computing the matrix exponential in burnup calculations." Nucl. Sci. Eng., 164 (2010) 140-150.
The required linear system solutions are done with the SuperLU library: Xiaoye S. Li. "An Overview of {SuperLU}: Algorithms, Implementation, and User Interface." ACM Trans.Math. Softw., 31;3 (2005) 302-325.
Fortran should call kernel_cram_from_fortran() instead.
Source term can have polynomial time dependency. Due to numerical issues source order is limited to cram_order/2-2. Non constant source term will cause some deterioration in accuracy, but below this limit it should be negligible.
Adjoint calculation is also possible by passing is_adjoint=1. In adjoint mode n0, source_term and delta_t>0 must be those for the adjoint problem while everything else must have values defining the forward system.
Internal substeps: Dividin steps to pieces greatly improved accuracy. This is particularly significant for decay problems where accuracy without might not be good enough for all purposes. The solver can do this division internally, which is more efficient than calling the solver multiple times as the LU decompositions only need to be formed once. internal_steps=1 means means that there is no substepping. Setting internal_steps=2 increases running time by roughly 25%. Each substep above 2 increases it by another 10-15% of the running time without substepping. See *** for details.
Parameters
[out] n_out[itot] Final concentrations. Must be Pre-allocated.
[in] n0[itot] Initial concentrations
[in] source_term[itot][source_order+1] Polynomial coefficients s_i,j for the source term
[in] source_order Order of the source term polynomial
[in] delta_t Length of the time step in seconds
[in] itot The number of nuclides in the system
[in] non Number of reactions (inc. decay) in the system
[in] non0[itot] Number of parents for each nuclide
[in] kd[itot] Number of decay parents for each nuclide
[in] diag[itot] Diagonal elements of A, i.e., (-lambda_eff)
[in] offdiag[non] Reaction specific decay constant of each reaction.
[in] loc[non] Index of the parent in each reaction.
[in] zero_flux_step Logical integer, is the flux zero?
[in] is_adjoint Logical integer, is this adjoint calculation?
[in] cram_order Order of the CRAM approximation (just use 16).
[in] internal_steps Number of internal substeps to use
[in] remove_negatives How to treat negative vaues in results: 0: Do nothing. 1: Remove all negative values. 2: Remove all negative values in forward mode. Remove all negative values in adjoint mode if source term is constant and both source and initial concentrations are non-negative.
[in] cutoff Concentrations whose ABSOLUTE value is below cutoff times sum(abs(n_out)) are set to zero. This is applied after remove_negatives.
[in] ZAI[itot] ZAI identifiers of the nuclides.
Note
The indexing in loc must be in c style, i.e., starts from 0. Be avare of this when calling from Fortran.
offdiag (which is called "a" in most of Origen source code) and loc must be sorted in the special Origen way:
decay parents of first nuclide,
activation parents of first nuclide,
decay parents of second nuclide,
activation parents of the second,
and so on.
The culling feature from earlier versions was removed. Use internal substeps instead.
Returns
zero on successfull exit or nonzero on failed exit. On failed exit the results (i.e., n) are unspecified.
References LUstore::C, CopyLU(), LUstore::equed, Origen::info(), kernel_cram_coefficients(), makeExpmInput(), makeMatlabInput(), NAME, OrigenToCRSMatrix(), r, LUstore::R, and SORT_NUCLIDES.
Referenced by kernel_cram_from_fortran(), Solver_cram::solve_impl(), TEST(), and TEST_F().
 {
     /*** The input/output varaibles for "expert mode" SuperLU driver
      * ***********/
     superlu_options_t options;
     SuperMatrix A;  // the coefficient matrix
     int* perm_r;    // row permutations from partial pivoting
     int* perm_c;    // column permutation vector
     int* etree;
     char equed[1];
     double* R;
     double* C;
     SuperMatrix L;
     SuperMatrix U;
     void* work;
     int lwork;
     SuperMatrix B;  // righe hand side
     SuperMatrix X;  // solution
     double recip_pivot_growth;
     double rcond;
     double* FERR;
     double* BERR;
     mem_usage_t mem_usage;
     SuperLUStat_t stat;
     int info;
     LUstore LU[8];  // store the LU decompositions for other internal substeps
     /*** Other variables
      * *******************************************************/
     // CRS matrix A (The modified coefficient matrix or further modified)
     int a_n;                       // size
     int a_nnz;                     // number of allocated elements
     double* a_val;                 // allocated elements
     doublecomplex* a_val_complex;  // allocated elements converted to complex
     int* a_rp;                     // row pointers
     int* a_ci;                     // column indices
     int* a_diag_idx;       // indices of the diagonal elements of A
     double* a_diag;        // copy of the diagonal values of A
     int *newIdx, *oldIdx;  // see sortCRSnuclides()
     double*
         src_dummy_n0;  // initial concentrations of dummy nuclides for source
     int nrhs;  // number of different right hand sides (initial compositions)
     // to solve for in superLU
     double* n;  // concentrations of nuclides, inc. dummies.
     // this has the same inexing as n0
     doublecomplex *Bvals, *Xvals;              // internal storage of B and X
     doublecomplex alpha0, alpha[8], theta[8];  // CRAM coefficients
     char tmpstr[512];
     int i, k, s;
     /*** SuperLU solver options
      * ************************************************/
     set_default_options( &options );  // set default options
     options.Equil = NO;          // no scaling
     options.Fact = DOFACT;       // solve from scratch (for first time only)
     options.ColPerm = MY_PERMC;  // hand set column permutations (set to none)
     options.IterRefine = NOREFINE;
     options.DiagPivotThresh = 0.0;  // do not pivot unless it cannot be avoided
     options.SymmetricMode = NO;     // matrix is not symmetric
     options.PivotGrowth = NO;       // do not calculate pivotal growth
     options.ConditionNumber = NO;   // do not calculate condition number
     options.RowPerm = NOROWPERM;    // no row permutations
     // options.PrintStat = YES;      // does not do anything
     if( !is_adjoint ) options.Trans = NOTRANS;  // forward calculation
     if( is_adjoint )
         options.Trans = TRANS;  // adjoint calculation (transpose A)
     /*** Time the whole solver
      * *************************************************/
     jDebugBlock( std::clock_t start = std::clock() );
     /*** Check input
      * ***********************************************************/
     if( ( cram_order < 4 ) || ( cram_order > 16 ) || ( cram_order % 2 != 0 ) )
     {
         sprintf( tmpstr,
                  "%s: invalid CRAM order %d. (must be 4-16 and even)\n",
                  NAME,
                  cram_order );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( source_order > cram_order / 2 - 2 )
     {
         sprintf(
             tmpstr,
             "%s: Source term order %d is above the maximum (cram_order/2-2)\n",
             NAME,
             source_order );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( ( source_order >= 0 ) && !( source_term ) )
     {
         sprintf( tmpstr,
                  "%s: Source term is nullptr but source term order %d\n",
                  NAME,
                  source_order );
         SErrLine( 1, tmpstr );
         sprintf( tmpstr,
                  "%s: source_term can only be nullptr for source_order < 0\n",
                  NAME );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( ( remove_negatives < 0 ) || ( remove_negatives > 2 ) )
     {
         sprintf( tmpstr,
                  "%s: remove_negatives has invalid value %d "
                  "(valid values are 0, 1, 2)\n",
                  NAME,
                  remove_negatives );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( cutoff < 0.0 )
     {
         sprintf( tmpstr, "%s: cutoff must be non-negative\n", NAME );
         SErrLine( 1, tmpstr );
         return 1;
     }
     if( !n_out || !n0 || !non0 || !kd || !diag || !offdiag || !loc )
     {
         sprintf( tmpstr,
                  "%s: nullptr argument other than source_term, ZAI\n",
                  NAME );
         SErrLine( 1, tmpstr );
         return 1;
     }
     /*** Build modified coefficient matrix A
      * ***********************************/
     OrigenToCRSMatrix( &a_n,
                        &a_val,
                        &a_ci,
                        &a_rp,
                        &a_diag_idx,
                        &a_nnz,
                        &newIdx,
                        &oldIdx,
                        &src_dummy_n0,
                        itot,
                        non,
                        non0,
                        kd,
                        diag,
                        offdiag,
                        loc,
                        source_term,
                        source_order,
                        zero_flux_step,
                        is_adjoint,
                        SORT_NUCLIDES,
                        ZAI );
     // store a copy of the diagonal elements
     a_diag = (double*)calloc( a_n, sizeof( double ) );
     for( i = 0; i < a_n; i++ ) a_diag[i] = a_val[a_diag_idx[i]];
     // convert a_val to complex
     a_val_complex = (doublecomplex*)calloc( a_nnz, sizeof( doublecomplex ) );
     for( i = 0; i < a_nnz; i++ ) a_val_complex[i].r = a_val[i];
     free( a_val );
     // convert to SuperLU format, note that a_* arrays are not copied
     zCreate_CompRow_Matrix(
         &A, a_n, a_n, a_nnz, a_val_complex, a_ci, a_rp, SLU_NR, SLU_Z, SLU_GE );
     /*** Set up other junk
      * *****************************************************/
     // number of right hand sides (back to always having 1)
     nrhs = 1;
     // nuclide compositions
     n = (double*)calloc( a_n, sizeof( double ) );
     // Create right-hand side matrix B (itot x nrhs)
     Bvals = (doublecomplex*)calloc( a_n * nrhs, sizeof( doublecomplex ) );
     zCreate_Dense_Matrix( &B, a_n, nrhs, Bvals, a_n, SLU_DN, SLU_Z, SLU_GE );
     // Write the initial composition to B
     for( i = 0; i < itot; i++ )
     {  // old idx
         Bvals[newIdx[i]].r = n0[i];
         Bvals[newIdx[i]].i = 0.0;
     }
     for( i = itot; i < a_n; i++ )
     {  // old idx
         Bvals[( nrhs - 1 ) * a_n + newIdx[i]].r = src_dummy_n0[i - itot];
         Bvals[( nrhs - 1 ) * a_n + newIdx[i]].i = 0.0;
     }
     // Create a matrix (itot x nrhs) to hold the solution
     Xvals = (doublecomplex*)calloc( a_n * nrhs, sizeof( doublecomplex ) );
     zCreate_Dense_Matrix( &X, a_n, nrhs, Xvals, a_n, SLU_DN, SLU_Z, SLU_GE );
     /* Column and row pivoting vectors (no pivoting) */
     perm_r = (int*)calloc( a_n, sizeof( int ) );
     perm_c = (int*)calloc( a_n, sizeof( int ) );
     for( i = 0; i < a_n; i++ )
     {
         perm_r[i] = i;
         perm_c[i] = i;
     }
     // work arrays for SuperLU
     // WORK, R, C must go to LUstore. NOTE: the old recycled work
     work = nullptr;
     lwork = 0;
     etree = (int*)calloc( a_n, sizeof( int ) );
     R = (double*)calloc( a_n, sizeof( double ) );
     C = (double*)calloc( a_n, sizeof( double ) );
     FERR = (double*)calloc( nrhs, sizeof( double ) );
     BERR = (double*)calloc( nrhs, sizeof( double ) );
     /* Initialize the statistics variables. */
     StatInit( &stat );
     // produce input for an external test program (Debug/development only)
     makeExpmInput( itot,
                    a_n,
                    a_nnz,
                    a_val_complex,
                    a_ci,
                    a_rp,
                    delta_t,
                    Bvals,
                    source_term,
                    source_order,
                    ZAI );
     // produce matlab input (for more testing)
     makeMatlabInput( itot, a_n, a_val_complex, a_ci, a_rp, ZAI );
     // get CRAM coefficients
     kernel_cram_coefficients( &alpha0, alpha, theta, cram_order );
     // A -> A*t     t = length of internal step!
     for( i = 0; i < a_nnz; i++ )
         a_val_complex[i].r *= ( delta_t / (double)internal_steps );
     /*** calculate n=e^{At}*n0 with CRAM
      * ***************************************/
     jDebugLine( "Evaluating order " << cram_order << " CRAM solution." );
     jDebugLine( "  " << internal_steps << " internal substeps." );
     jDebugBlock( std::clock_t start_calc =
                      std::clock() );  // time the main loop
     for( s = 0; s < internal_steps; s++ )
     {
         // alpha0 term
         for( i = 0; i < a_n; i++ ) n[oldIdx[i]] = alpha0.r * Bvals[i].r;
         /*** sum over the poles ***/
         for( k = 0; k < cram_order / 2; k++ )
         {
             // reuse stuff
             if( k == 1 && s == 0 ) options.Fact = SamePattern_SameRowPerm;
             if( s == 1 ) options.Fact = FACTORED;
             // change variable "A" from (A*t) to (A*t - theta(k)*I)
             // This is needed even when LU is recycled.
             for( i = 0; i < a_n; i++ )
             {  // i = new index
                 a_val_complex[a_diag_idx[i]].r =
                     a_diag[i] * ( delta_t / (double)internal_steps ) -
                     theta[k].r;
                 a_val_complex[a_diag_idx[i]].i = -theta[k].i;
             }
             // Solve (A*t -theta(k)*I)x=n0 for x
             if( s == 0 )
             {
                 // On the first substep we use all the variables (memory slots)
                 // defined in kernel_cram() for each solve.
                 // L,U,R,C are stored from each solve if there are internal
                 // steps
                 zgssvx( &options,
                         &A,
                         perm_c,
                         perm_r,
                         etree,
                         equed,
                         R,
                         C,
                         &L,
                         &U,
                         &work,
                         lwork,
                         &B,
                         &X,
                         &recip_pivot_growth,
                         &rcond,
                         FERR,
                         BERR,
                         &mem_usage,
                         &stat,
                         &info );
             }
             else
             {
                 // After first substep we reuse the LU decompositions from the
                 // first substep (U,K,R,C) stored to LU[k].
                 // other stuff is the same as on the first substep.
                 zgssvx( &options,
                         &A,
                         perm_c,
                         perm_r,
                         etree,
                         LU[k].equed,
                         &( LU[k].R[0] ),
                         &( LU[k].C[0] ),
                         &( LU[k].L ),
                         &( LU[k].U ),
                         &work,
                         lwork,
                         &B,
                         &X,
                         &recip_pivot_growth,
                         &rcond,
                         FERR,
                         BERR,
                         &mem_usage,
                         &stat,
                         &info );
             }
             // Check solver output
             if( info != 0 )
             {
                 sprintf( tmpstr,
                          "%s: SuperLU solver failed with error code %d\n",
                          NAME,
                          info );
                 SErrLine( 1, tmpstr );
                 return 1;
             }
             if( equed[0] != 'N' )
             {
                 sprintf( tmpstr,
                          "%s: SuperLU solver equed is not N but %s\n",
                          NAME,
                          equed );
                 SErrLine( 1, tmpstr );
                 return 1;
             }
             if( ( s == 0 ) && ( internal_steps > 1 ) )
             {
                 // Store the LU decomposition:
                 CopyLU( &L, &U, &( LU[k] ) );
                 // These are also needed by SuperLU to ge with the decomposition
                 LU[k].R.resize( a_n );
                 std::copy( R, R + a_n, &( LU[k].R[0] ) );
                 LU[k].C.resize( a_n );
                 std::copy( C, C + a_n, &( LU[k].C[0] ) );
                 LU[k].equed[0] = equed[0];
             }
             /*** Add this term to the results (real part only) ***/
             for( i = 0; i < a_n; i++ )  // i=new index
                 n[oldIdx[i]] +=
                     2 * ( alpha[k].r * Xvals[i].r - alpha[k].i * Xvals[i].i );
         }
         /*** Make the substep final composition the initial for next substep
          * ***/
         for( i = 0; i < a_n; i++ )
         {  // old idx
             Bvals[newIdx[i]].r = n[i];
             Bvals[newIdx[i]].i = 0.0;
         }
     }
     /*** Copy the final concentrations of real nuclides to output ***/
     for( i = 0; i < itot; i++ ) n_out[i] = n[i];
     /*** Remove negative values from the results if that was requested ***/
     bool cull = false;  // Whether to remove negatives
     if( remove_negatives == 0 )
         cull = false;
     else if( remove_negatives == 1 )
         cull = true;
     else if( remove_negatives == 2 )
     {
         cull = true;
         if( is_adjoint != 0 )
         {
             if( source_order > 0 ) cull = false;
             if( cull == true )
                 for( i = 0; i < itot; i++ )
                     if( n0[i] < 0.0 )
                     {
                         cull = false;
                         break;
                     }
             if( ( cull == true ) && ( source_order == 0 ) )
                 for( i = 0; i < itot; i++ )
                     if( source_term[i][0] < 0.0 )
                     {
                         cull = false;
                         break;
                     }
         }
     }
     if( cull )
         for( i = 0; i < itot; i++ )
             if( n_out[i] < 0.0 ) n_out[i] = 0.0;
     /*** Apply the cutoff for atomic densities ***/
     if( cutoff != 0.0 )
     {
         double n_tot = 0.0;
         for( i = 0; i < itot; i++ ) n_tot += std::fabs( n_out[i] );
         double n_limit = cutoff * n_tot;
         for( i = 0; i < itot; i++ )
             if( std::fabs( n_out[i] ) < n_limit ) n_out[i] = 0.0;
     }
     /*** Print some statistics ***/
     // can't enable this unless it goes to STDERR (currently muddies up output
     // file)
     // jDebugBlock(StatPrint(&stat));
     jDebugLine(
         "CRAM solution completed in "
         << 1000 * (double)( std::clock() - start ) / (double)CLOCKS_PER_SEC
         << " ms, of which "
         << 1000 * (double)( std::clock() - start_calc ) / (double)CLOCKS_PER_SEC
         << " ms in the main solver loop" );
     /*** De-allocate storage ***/
     Destroy_CompRow_Matrix( &A );
     Destroy_SuperMatrix_Store( &B );
     Destroy_SuperMatrix_Store( &X );
     Destroy_SuperNode_Matrix( &L );
     Destroy_CompCol_Matrix( &U );
     StatFree( &stat );
     if( internal_steps > 1 )
         for( k = 0; k < cram_order / 2; k++ )
         {
             free( ( (SCformat*)LU[k].L.Store )->nzval );
             free( ( (SCformat*)LU[k].U.Store )->nzval );
             free( LU[k].L.Store );
             free( LU[k].U.Store );
         }
     free( work );
     free( Bvals );
     free( Xvals );
     free( perm_r );
     free( perm_c );
     free( n );
     free( FERR );
     free( BERR );
     free( etree );
     free( R );
     free( C );
     free( a_diag );
     free( a_diag_idx );
     free( newIdx );
     free( oldIdx );
     if( source_order >= 0 ) free( src_dummy_n0 );
     return 0;
 }
void OrigenToCRSMatrix (int * p_a_n, double ** p_a_val, int ** p_a_ci, int ** p_a_rp, int ** p_a_diag_idx, int * p_a_nnz, int ** p_newIdx, int ** p_oldIdx, double ** p_src_dummy_n0, int itot, int non, int * non0, int * kd, double * diag, double * offdiag, int * loc, double ** source_term, int source_order, int zero_flux_step, int is_adjoint, int sort_nuclides, int * ZAI)
Convert ORIGEN form input to regular compressed row storage (CRS) matrix representing the equivalent homogeneous equations.
This has two main functions:
Build the actual coefficient matrix
Homogenize the equations (i.e., dn/dt = An +s ==> dn'/dt = A'n')
which are done simultaneously. In addition this:
Allocates all diagonal elements (even zeros)
Sorts nuclides by ZAI
Sorts each row
For details about the homogenization see:
Note
The first nine arguments are used for output. They are pointers to the variables p_<name in kernel_cram()> The other arguments are same as for kernel_cram(). The output, except for p_a_n and p_a_nnz which are scalars, will be allocated by this function.
References sortCRSnuclides().
Referenced by kernel_cram(), TEST(), and tstOrigenToCRSMatrix::~tstOrigenToCRSMatrix().
 {
     int num_src;        // number of nonzero coefficients in source term
     int num_dummy;      // number of dummy nuclides
     int* ZAI_with_src;  // ZAI but with made up values for dummies appended
     double* src_dummy_n0 =
         nullptr;  // (initial) concentrations of dummy elements
     int i, j, p, pmax, idx_a, rowstart;
     int a_n, a_nnz;
     jDebugLine( "Building CRS matrix A..." );
     /*** Source term background work
      * *******************************************/
     // Count the total number of non zero coefficients in the source term
     num_src = 0;
     for( i = 0; i < itot; i++ )
         for( j = 0; j < source_order + 1; j++ )
             if( source_term[i][j] != 0.0 ) num_src++;
     // Number of source term dummy nuclides
     num_dummy = source_order + 1;
     if( num_dummy > 0 )
     {
         jDebugLine( "   Order " << source_order << " source term with "
                                 << num_src
                                 << " non-zero elements" );
     }
     else
     {
         jDebugLine( "   No source term" );
     }
     // The size of the matrix when source has been included
     // a_nnz may later be reduced if decay and transmutation get merged
     a_n = itot + num_dummy;
     a_nnz = a_n + non + num_src + ( a_n - itot );
     // allocate
     if( num_dummy > 0 )
     {
         src_dummy_n0 = (double*)calloc( num_dummy, sizeof( double ) );
         src_dummy_n0[0] = 1.0;
     }
     // Make a copy of ZAI with possible dummies appended to the end.
     // Dummies get large bogus ZAI so that they won't get moved in sorting
     if( ZAI )
     {
         ZAI_with_src = (int*)calloc( a_n, sizeof( int ) );
         std::copy( ZAI, ZAI + itot, ZAI_with_src );
         for( i = itot; i < a_n; i++ ) ZAI_with_src[i] = 9000000 + ( i - itot );
     }
     else
         ZAI_with_src = nullptr;
     /*** allocate space ***/
     // These are the same as in kernel_cram()
     double* a_val = (double*)calloc( a_nnz, sizeof( double ) );
     int* a_ci = (int*)calloc( a_nnz, sizeof( int ) );
     int* a_rp = (int*)calloc( a_n + 1, sizeof( int ) );
     int* newIdx = (int*)calloc( a_n, sizeof( int ) );
     int* oldIdx = (int*)calloc( a_n, sizeof( int ) );
     int* a_diag_idx = (int*)calloc( a_n, sizeof( int ) );
     // work arrays
     double* rowval = (double*)calloc( 2 * itot, sizeof( double ) );
     int* rowloc = (int*)calloc( 2 * itot, sizeof( int ) );
     /*** fill in CRS form (unsorted) ***/
     idx_a = 0;     // index in a
     rowstart = 0;  // index from which the row starts in offdiag
     for( i = 0; i < itot; i++ )
     {  // rows
         a_rp[i] = idx_a;  // row i starts at...
         // copy the values (to avoid modifying the input)
         std::copy( &loc[rowstart], &loc[rowstart] + non0[i], rowloc );
         std::copy( &offdiag[rowstart], &offdiag[rowstart] + non0[i], rowval );
         // add the diagonal element to beginning of each row
         a_val[idx_a] = diag[i];
         a_ci[idx_a] = i;
         idx_a++;
         /*** add offdiagonal elements ***/
         if( zero_flux_step )
             pmax = kd[i];
         else
             pmax = non0[i];
         for( p = 0; p < pmax; p++ )
         {
             /* nuclide ZAI[i] is produced from nuclide ZAI[rowloc[p]] */
             // find out if matrix element (i,p) already exists
             for( j = a_rp[i]; j < idx_a; j++ )
             {
                 if( a_ci[j] == rowloc[p] )
                 {
                     // the element already exists, add to it
                     a_val[j] += rowval[p];
                     break;
                 }
             }
             if( j == idx_a )
             {
                 // the element does not exist, add the element
                 a_val[idx_a] = rowval[p];
                 a_ci[idx_a] = rowloc[p];
                 idx_a++;
             }
         }
         /*** add source term elements ***/
         for( j = 0; j < source_order + 1; j++ )
             if( ( source_term[i][j] != 0.0 ) && ( !is_adjoint ) )
             {
                 a_val[idx_a] = source_term[i][j];
                 a_ci[idx_a] = itot + j;
                 idx_a++;
             }
         // next row starts at...
         rowstart += non0[i];
     }
     a_rp[itot] = idx_a;
     /*** add source term dummy element rows ***/
     for( i = 0; i < num_dummy; i++ )
     {  // dummy row = itot+i
         // in adjoint calculation source is on the last row so that when the
         // matrix is transposed it ends up in the last column
         if( is_adjoint )
             for( j = 0; j < itot; j++ )  // columns = nuclides
                 if( source_term[j][i] != 0.0 )
                 {
                     a_val[idx_a] = source_term[j][i];
                     a_ci[idx_a] = j;
                     idx_a++;
                 }
         // the offdiagonal "produce dummy from dummy" element
         // note that we are left from diagonal for forward
         if( ( !is_adjoint ) && ( i > 0 ) )
         {
             a_val[idx_a] = i;
             a_ci[idx_a] = itot + i - 1;
             idx_a++;
         }
         // diagonal
         a_val[idx_a] = 0;
         a_ci[idx_a] = itot + i;
         idx_a++;
         // the offdiagonal "produce dummy from dummy" element
         // note that we want it left of diagonal after transpose
         if( ( is_adjoint ) && ( i < num_dummy - 1 ) )
         {
             a_val[idx_a] = i + 1;
             a_ci[idx_a] = itot + i + 1;
             idx_a++;
         }
         a_rp[itot + i + 1] = idx_a;
     }
     // the real size of the system (arrays are not reallocated)
     a_nnz = idx_a;
     /*** sort the nuclides (maybe) ***/
     sortCRSnuclides( a_n,
                      a_nnz,
                      &a_val,
                      &a_ci,
                      &a_rp,
                      newIdx,
                      oldIdx,
                      sort_nuclides,
                      ZAI_with_src );
     /*** Sort each row by column index (insertion sort) ***/
     for( i = 0; i < a_n; i++ )  // rows
         for( idx_a = a_rp[i] + 1; idx_a < a_rp[i + 1]; idx_a++ )
         {  // elements on row
             // move the idx_a:th element left until the left side is sorted
             int tmp_ci = a_ci[idx_a];
             double tmp_val = a_val[idx_a];
             j = idx_a;
             // move each element that should be after idx_a:th one to the right
             while( ( j > 0 ) && ( j > a_rp[i] ) && ( a_ci[j - 1] > tmp_ci ) )
             {
                 a_ci[j] = a_ci[j - 1];
                 a_val[j] = a_val[j - 1];
                 j--;
             }
             // put the moved element
             a_ci[j] = tmp_ci;
             a_val[j] = tmp_val;
         }
     /*** find diagonal element indices ***/
     for( i = 0; i < a_n; i++ )  // rows
         for( idx_a = a_rp[i]; idx_a < a_rp[i + 1]; idx_a++ )
             if( a_ci[idx_a] == i )
             {
                 a_diag_idx[i] = idx_a;
                 break;
             }
     /*** set the return values/pointers ***/
     *p_a_n = a_n;
     *p_a_nnz = a_nnz;
     *p_a_val = a_val;
     *p_a_ci = a_ci;
     *p_a_rp = a_rp;
     *p_a_diag_idx = a_diag_idx;
     *p_newIdx = newIdx;
     *p_oldIdx = oldIdx;
     *p_src_dummy_n0 = src_dummy_n0;
     /*** free memory ***/
     free( rowval );
     free( rowloc );
     if( ZAI_with_src ) free( ZAI_with_src );
 }
int kernel_cram_from_fortran (double * n, double * n0, double * source_term, int source_order, double delta_t, int itot, int non, int * non0, int * kd, double * diag, double * offdiag, int * loc, int zero_flux_step, int is_adjoint, int cram_order, int internal_steps, int remove_negatives, double cutoff, int * ZAI)
Interface function for calling kernel_cram() from Fortran. Converts the source_term to the form expected by kernel_cram().
Note
All arguments are the same as for kernel_cram(), except that source_term is a 1D array whose elements must be ordered so that the coefficients for given nuclide are consequtive in memory. This only converts source_term, loc indexing must be converted by the caller.
Returns
EXIT_SUCCESS or EXIT_FAILURE. On failed exit the results (i.e., n) are unspecified.
References kernel_cram().
 {
     int rv, i;
     double** src;
     if( source_order >= 0 )
     {
         // Make the pointer pointer list expected by kernel_cram()
         src = (double**)malloc( itot * sizeof( double* ) );
         for( i = 0; i < itot; i++ )
             src[i] = &source_term[i * ( source_order + 1 )];
         rv = kernel_cram( n,
                           n0,
                           src,
                           source_order,
                           delta_t,
                           itot,
                           non,
                           non0,
                           kd,
                           diag,
                           offdiag,
                           loc,
                           zero_flux_step,
                           is_adjoint,
                           cram_order,
                           internal_steps,
                           remove_negatives,
                           cutoff,
                           ZAI );
         free( src );
     }
     else
     {
         // there is no source term
         rv = kernel_cram( n,
                           n0,
                           nullptr,
                           source_order,
                           delta_t,
                           itot,
                           non,
                           non0,
                           kd,
                           diag,
                           offdiag,
                           loc,
                           zero_flux_step,
                           is_adjoint,
                           cram_order,
                           internal_steps,
                           remove_negatives,
                           cutoff,
                           ZAI );
     }
     return rv;
 }
int kernel_cram_coefficients (doublecomplex * alpha0, doublecomplex * alpha, doublecomplex * theta, int cram_order)
Set CRAM coefficients for partial fraction decomposition form.
Sets the poles and residues of chebyshev rational approximation on the negative real axis. Available orders are 4, 6, 8, 10, 12, 14, and 16.
Order 14 and 16 coefficients are from: Maria Pusa, "Correction to partial fraction decomposition coefficients for Chebyshev rational approximation on the negative real axis." arXiv:1206.2880v1 [math.NA] (2013). Others have been provided by Maria Pusa directly.
Parameters
[out] alpha0,alpha,theta The coefficients. alpha and theta must be preallocated to hold at least order/2 values
[in] cram_order The desired order of the CRAM approximation.
Returns
EXIT_SUCCESS or EXIT_FAILURE. On failed exit the results are unspecified.
References NAME.
Referenced by kernel_cram().
 {
     char tmpstr[512];
     switch( cram_order )
     {
         case 4:
             alpha0[0].r = 0.0000865224069528885234822434582541;
             alpha0[0].i = 0.000000000000000000e+00;
             theta[0].r = 1.54839322329712217439053288467;
             theta[0].i = 1.19182294662742561401495648251;
             alpha[0].r = -0.0616867795678329241678504486404;
             alpha[0].i = -1.90504097930308129535281161601;
             theta[1].r = -0.367845386181539838043792199124;
             theta[1].i = 3.65812129867866730352793955219;
             alpha[1].r = 0.07339595716394220745843949906;
             alpha[1].i = 0.449999922474062719432847725798;
             return EXIT_SUCCESS;
         case 6:
             alpha0[0].r = 0.00000100845437489967070793452877641;
             alpha0[0].i = 0.000000000000000000e+00;
             theta[0].r = 2.4006027476632035398246974381;
             theta[0].i = 1.19312926415015560426698786597;
             alpha[0].r = -0.579013010129504855155852234143;
             alpha[0].i = -4.28688757534708729558196757879;
             theta[1].r = 1.15855236282301717250331028498;
             theta[1].i = 3.61477244803838460675130645578;
             alpha[1].r = 0.663006885647110409573986063133;
             alpha[1].i = 1.45141249620623755570950495036;
             theta[2].r = -1.78198851962569031912455200319;
             theta[2].i = 6.19651209626542478597275999529;
             alpha[2].r = -0.0835816264914570742345518670486;
             alpha[2].i = -0.106429205529952808746350135093;
             return EXIT_SUCCESS;
         case 8:
             alpha0[0].r = 0.0000000117226521163349071779543230394;
             alpha0[0].i = +0.000000000000000000e+00;
             theta[0].r = 3.22094523994511336683659527236;
             theta[0].i = 1.19361960462065194569987188314;
             alpha[0].r = -1.83177170577152029138268182072;
             alpha[0].i = -9.52560807406433584603303877609;
             theta[1].r = 2.29224914230486699264307911539;
             theta[1].i = 3.60077149348338105520887151095;
             alpha[1].r = 2.43624072578176493680519785406;
             alpha[1].i = 3.71675561350832400534482436932;
             theta[2].r = 0.269490980912751490292788764412;
             theta[2].i = 6.0820325874935431647316879023;
             alpha[2].r = -0.632588051311574395996051852802;
             alpha[2].i = -0.443923096947896811466230624898;
             theta[3].r = -3.40853950966365281231428086571;
             theta[3].i = 8.77303455357903932775145799212;
             alpha[3].r = 0.0281297570232989888931609445591;
             alpha[3].i = 0.0115773842089237064112712850731;
             return EXIT_SUCCESS;
         case 10:
             alpha0[0].r = 0.000000000136112052334544774987078816154;
             alpha0[0].i = +0.000000000000000000e+00;
             theta[0].r = 4.02773246751874866428893530954;
             theta[0].i = 1.19385606645533239082655038817;
             alpha[0].r = -4.8183819908450345755836435054;
             alpha[0].i = -21.0545972383997125069657312356;
             theta[1].r = 3.28375288323130073306218909826;
             theta[1].i = 3.59438677235590308653499337877;
             alpha[1].r = 7.1171651040990542520528633368;
             alpha[1].i = 8.81953315787319681991703092772;
             theta[2].r = 1.71540601576895681462522539959;
             theta[2].i = 6.03893492548391903365834900072;
             alpha[2].r = -2.56558495484112777814351837981;
             alpha[2].i = -1.2163857061202029670452282956;
             theta[3].r = -0.894404701609480658145514094125;
             theta[3].i = 8.58275689861338752740345609881;
             alpha[3].r = 0.272586980296403028648081449556;
             alpha[3].i = 0.0142117270316311441640833114401;
             theta[4].r = -5.16119127202007600680367398793;
             theta[4].i = 11.3751562519165412007834939217;
             alpha[4].r = -0.00578490385801288543461916600512;
             alpha[4].i = 0.000685850708944701283550607534625;
             return EXIT_SUCCESS;
         case 12:
             alpha0[0].r = 0.00000000000157945683705123877148675673282;
             alpha0[0].i = +0.000000000000000000e+00;
             theta[0].r = 4.82749345216106448153474237756;
             theta[0].i = 1.19398799122308291759808771853;
             alpha[0].r = -11.7993799560122330693107870203;
             alpha[0].i = -46.4116353335267857488915186843;
             theta[1].r = 4.20612420431830133451003843159;
             theta[1].i = 3.59092075888461612300899129821;
             alpha[1].r = 18.7859774215254172390621171827;
             alpha[1].i = 20.2372851260634540920395512197;
             theta[2].r = 2.91786854507930581237563126374;
             theta[2].i = 6.01734592409237235951998980032;
             alpha[2].r = -8.23825593423480805645459207605;
             alpha[2].i = -2.79619126230380745862951054299;
             theta[3].r = 0.851707096715501743570816381388;
             theta[3].i = 8.50383282563463592395677159867;
             alpha[3].r = 1.31941153407118645768993631993;
             alpha[3].i = -0.183523582873346460062763208093;
             theta[4].r = -2.23596824613067950797452532842;
             theta[4].i = 11.1092962327028404610964379772;
             alpha[4].r = -0.068571494249760100694471517994;
             alpha[4].i = 0.0384190828866480488124159476513;
             theta[5].r = -6.99868790860361702699094416312;
             theta[5].i = 13.9959166249707282704404398378;
             alpha[5].r = 0.000818433499262444251243168263201;
             alpha[5].i = -0.000581353582426121335919208815826;
             return EXIT_SUCCESS;
         case 14:
             alpha0[0].r = +1.832174378254041200e-14;
             alpha0[0].i = +0.000000000000000000e+00;
             alpha[0].r = -7.154288063589066700e-05;
             alpha[1].r = +9.439025310736169600e-03;
             alpha[2].r = -3.763600387822697000e-01;
             alpha[3].r = -2.349823209108270200e+01;
             alpha[4].r = +4.693327448883129400e+01;
             alpha[5].r = -2.787516194014564500e+01;
             alpha[6].r = +4.807112098832508500e+00;
             alpha[0].i = +1.436104334954130000e-04;
             alpha[1].i = -1.718479195848301700e-02;
             alpha[2].i = +3.351834702945010200e-01;
             alpha[3].i = -5.808359129714207600e+00;
             alpha[4].i = +4.564364976882776400e+01;
             alpha[5].i = -1.021473399905645200e+02;
             alpha[6].i = -1.320979383742872500e+00;
             theta[0].r = -8.897773186468889200e+00;
             theta[1].r = -3.703275049423448100e+00;
             theta[2].r = -2.087586382501301400e-01;
             theta[3].r = +3.993369710578568400e+00;
             theta[4].r = +5.089345060580624700e+00;
             theta[5].r = +5.623142572745977400e+00;
             theta[6].r = +2.269783829231112500e+00;
             theta[0].i = +1.663098261990208500e+01;
             theta[1].i = +1.365637187148326800e+01;
             theta[2].i = +1.099126056190126000e+01;
             theta[3].i = +6.004831642235037000e+00;
             theta[4].i = +3.588824029027006400e+00;
             theta[5].i = +1.194069046343966900e+00;
             theta[6].i = +8.461737973040222000e+00;
             return EXIT_SUCCESS;
         case 16:
             alpha0[0].r = +2.124853710495223600e-16;
             alpha0[0].i = +0.000000000000000000e+00;
             alpha[0].r = -5.090152186522492000e-07;
             alpha[1].r = +2.115174218246603100e-04;
             alpha[2].r = +1.133977517848393000e+02;
             alpha[3].r = +1.505958527002346700e+01;
             alpha[4].r = -6.450087802553964900e+01;
             alpha[5].r = -1.479300711355799900e+00;
             alpha[6].r = -6.251839246320791700e+01;
             alpha[7].r = +4.102313683541002100e-02;
             alpha[0].i = -2.422001765285228900e-05;
             alpha[1].i = +4.389296964738067200e-03;
             alpha[2].i = +1.019472170421585700e+02;
             alpha[3].i = -5.751405277642182200e+00;
             alpha[4].i = -2.245944076265209600e+02;
             alpha[5].i = +1.768658832378293700e+00;
             alpha[6].i = -1.119039109428322800e+01;
             alpha[7].i = -1.574346617345546700e-01;
             theta[0].r = -1.084391707869698800e+01;
             theta[1].r = -5.264971343442646800e+00;
             theta[2].r = +5.948152268951177200e+00;
             theta[3].r = +3.509103608414918100e+00;
             theta[4].r = +6.416177699099434600e+00;
             theta[5].r = +1.419375897185666000e+00;
             theta[6].r = +4.993174737717996700e+00;
             theta[7].r = -1.413928462488886200e+00;
             theta[0].i = +1.927744616718165100e+01;
             theta[1].i = +1.622022147316792800e+01;
             theta[2].i = +3.587457362018322100e+00;
             theta[3].i = +8.436198985884374200e+00;
             theta[4].i = +1.194122393370138600e+00;
             theta[5].i = +1.092536348449672300e+01;
             theta[6].i = +5.996881713603942300e+00;
             theta[7].i = +1.349772569889274500e+01;
             return EXIT_SUCCESS;
         default:
             sprintf( tmpstr,
                      "%s: Unsupported or invalid CRAM order: %d",
                      NAME,
                      cram_order );
             SErrLine( 1, tmpstr );
             return EXIT_FAILURE;
     }
 }