ORIGEN API: Core/dc/tests/tstTransitionStructure.cpp File Reference
tstTransitionStructure.cpp File Reference
#include <cstdlib>
#include <iostream>
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/dc/TransitionStructure.h"
#include "Standard/Interface/SerialStream.h"
Functions
TEST (TransitionStructure, Basic)
Function Documentation
TEST (TransitionStructure , Basic)
References FakeFactory::createLibraryHeader_random1(), TransitionStructure::deserialize(), TransitionStructure::serialize(), and FakeFactory::TransitionStructure_random1().