ORIGEN API: LibraryHeader Class Reference
LibraryHeader Class Reference
#include <LibraryHeader.h>
Public Types
typedef std::shared_ptr< LibraryHeader > SP
typedef std::shared_ptr< const LibraryHeader > SCP
Public Member Functions
LibraryHeader ()
std::string to_string () const
Scale::Json::Value to_json () const
bool operator== (const LibraryHeader &a) const
std::string print_compare (const LibraryHeader &a) const
const NuclideSet & nuclide_set () const
return a const reference to nuclide_set
SCP_NuclideSet scp_nuclide_set () const
return a shared (read-only) nuclide_set pointer
bool has_nuclide_set () const
return whether the class has a non-null nuclide_set
void get_nuclide_set (NuclideSet &) const
populate an existing NuclideSet with a copy of nuclide_set
void set_nuclide_set (const NuclideSet &)
set the nuclide_set (copy operation)
void getptr_nuclide_set (const NuclideSet *&) const
retrieve pointer (read-only) to nuclide_set
void manageptr_nuclide_set (NuclideSet *&)
set the nuclide_set (ownership transfer)
virtual int serialize (Standard::AbstractStream *stream) const
virtual int deserialize (Standard::AbstractStream *stream)
virtual unsigned long getSerializedSize () const
virtual LibraryHeader * getCopy () const
virtual long getUID () const
virtual bool childOf (long parentUID) const
virtual std::string toString () const
void set_month_made (int)
set the scalar month_made
int month_made () const
return the scalar month_made
void set_day_made (int)
set the scalar day_made
int day_made () const
return the scalar day_made
void set_year_made (int)
set the scalar year_made
int year_made () const
return the scalar year_made
void set_title (std::string)
set the scalar title
std::string title () const
return the scalar title
size_t total_nuclides () const
Static Public Attributes
static const long uid = 0x99514754f6b0dc5d
Protected Member Functions
void canonicalize_nuclide_set ()
Protected Attributes
SP_NuclideSet b_nuclide_set
int b_month_made
int b_day_made
int b_year_made
std::string b_title
Friends
class ScaleUtils::IO::Accessor< Origen::LibraryHeader >
Detailed Description
Examples:
Core/dc/tests/tstDecayData.cpp, Core/dc/tests/tstLibrary.cpp, Core/dc/tests/tstLibraryHeader.cpp, Core/dc/tests/tstTransitionCoeff.cpp, Core/dc/tests/tstTransitionStructure.cpp, Core/io/tests/tstLibraryIO.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Member Typedef Documentation
typedef std::shared_ptr<LibraryHeader> SP
typedef std::shared_ptr<const LibraryHeader> SCP
Constructor & Destructor Documentation
LibraryHeader ()
Referenced by LibraryHeader::getCopy().
     : b_nuclide_set( new NuclideSet() )
     , b_month_made( 0 )
     , b_day_made( 0 )
     , b_year_made( 0 )
     , b_title( "" )
 {
 }
Member Function Documentation
std::string to_string () const
References LibraryHeader::to_json().
Referenced by LibraryHeader::toString().
 {
     return to_json().toStyledString();
 }
Json::Value to_json () const
References LibraryHeader::b_day_made, LibraryHeader::b_month_made, LibraryHeader::b_nuclide_set, LibraryHeader::b_title, LibraryHeader::b_year_made, LibraryHeader::has_nuclide_set(), and LibraryHeader::uid.
Referenced by LibraryHeader::to_string().
 {
     Json::Value root;
     root["uid"] = Json::Value::Int64( uid );
     root["month_made"] = b_month_made;
     root["day_made"] = b_day_made;
     root["year_made"] = b_year_made;
     root["title"] = b_title;
     if( has_nuclide_set() ) root["nuclide_set"] = b_nuclide_set->to_json();
     return root;
 }
bool operator== (const LibraryHeader & a) const
References LibraryHeader::b_day_made, LibraryHeader::b_month_made, LibraryHeader::b_nuclide_set, LibraryHeader::b_title, LibraryHeader::b_year_made, LibraryHeader::day_made(), LibraryHeader::month_made(), LibraryHeader::nuclide_set(), LibraryHeader::title(), and LibraryHeader::year_made().
 {
     ORIGEN_COMPARE_SCALAR( month_made, b_month_made, a.b_month_made );
     ORIGEN_COMPARE_SCALAR( year_made, b_year_made, a.b_year_made );
     ORIGEN_COMPARE_SCALAR( day_made, b_day_made, a.b_day_made );
     ORIGEN_COMPARE_STRING( title, b_title, a.b_title );
     ORIGEN_COMPARE_SP( nuclide_set, b_nuclide_set, a.b_nuclide_set );
     return true;
 }
std::string print_compare (const LibraryHeader & a) const
References LibraryHeader::b_day_made, LibraryHeader::b_month_made, LibraryHeader::b_nuclide_set, LibraryHeader::b_title, and LibraryHeader::b_year_made.
 {
     std::stringstream ss;
     ss << "Library Title A: " << b_title << std::endl;
     ss << "Library Title B: " << a.b_title << std::endl << std::endl;
     ss << std::setw( 55 ) << "Library Header" << std::endl;
     ss << std::setw( 55 ) << "=-=-=-=-=-=-=-";
     ss << std::endl << std::endl;
     ss << std::setw( 40 ) << " " << std::setw( 10 ) << "A" << std::setw( 15 )
        << " " << std::setw( 10 ) << "B" << std::endl;
     ss << std::setw( 40 ) << " "
        << "--------------------"
        << "     "
        << "--------------------" << std::endl;
     ss << std::setw( 35 ) << "Day Made:" << std::setw( 25 ) << b_day_made
        << std::setw( 25 ) << a.b_day_made << std::endl;
     ss << std::setw( 35 ) << "Month Made:" << std::setw( 25 ) << b_month_made
        << std::setw( 25 ) << a.b_month_made << std::endl;
     ss << std::setw( 35 ) << "Year Made:" << std::setw( 25 ) << b_year_made
        << std::setw( 25 ) << a.b_year_made << std::endl;
     ss << std::setw( 35 ) << "NuclideSet Size:" << std::setw( 25 )
        << b_nuclide_set.get()->total_nuclides() << std::setw( 25 )
        << a.b_nuclide_set.get()->total_nuclides() << std::endl;
     ss << std::endl;
     ss << b_nuclide_set.get()->print_compare( *( a.b_nuclide_set ) );
     ss << std::endl;
     return ss.str();
 }
const NuclideSet & nuclide_set () const
return a const reference to nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Invalid if this instance of LibraryHeader goes out of scope.
Examples:
Core/dc/tests/tstNuclideSet.cpp, Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
Referenced by Origen::construct_coeff_map(), Origen::construct_neutron_prod_map(), Origen::construct_neutron_yields_map(), Origen::createDecayData_random1(), Origen::createTransitionCoeff_random1(), Origen::createTransitionStructure_random1(), DecayResource::DecayResource(), get_decay_data(), get_transition_data(), Origen::graphvizLibrary(), gtestLibraryMasses(), gtestLibrarySizes(), inject_fission_yields(), TransitionMatrixUpdater::load(), LibraryHeader::operator==(), Library::populate_transition_matrix(), Origen::populateLibraryAbundance_NuclideResource(), Origen::populateLibraryDecayEnergy_DecayResource(), Origen::populateLibraryMass(), Origen::populateLibraryMass_NuclideResource(), Origen::populateLibraryToxicity_DecayResource(), LibraryIO_bof::read(), LibraryIO_s61::read(), LibraryIO_s62b::read(), Origen::tabulateFissionXs(), Origen::tabulateLossXs(), Origen::tabulateNuclideInfo(), Origen::tabulateReactionTransitions(), Origen::tabulateTransitionCoeff(), TEST(), TEST_F(), Origen::thinLibrary(), LibraryIO_bof::write(), LibraryIO_s62b::write(), and LibraryIO_s61::write().
SCP_NuclideSet scp_nuclide_set () const
return a shared (read-only) nuclide_set pointer
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
bool has_nuclide_set () const
return whether the class has a non-null nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Referenced by Library::populate_transition_matrix(), LibraryHeader::to_json(), and LibraryHeader::total_nuclides().
void get_nuclide_set (NuclideSet & nuclide_set) const
populate an existing NuclideSet with a copy of nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void set_nuclide_set (const NuclideSet & nuclide_set)
set the nuclide_set (copy operation)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::createLibraryHeader_random1(), Origen::populateLibraryHeader_YieldResource(), LibraryIO_s61::read(), LibraryIO_bof::read(), LibraryIO_s62b::read(), and LibraryTest::SetUp().
void getptr_nuclide_set (const NuclideSet *&) const
retrieve pointer (read-only) to nuclide_set
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
void manageptr_nuclide_set (NuclideSet *& nuclide_set)
set the nuclide_set (ownership transfer)
Auto-generated from macro #ORIGEN_ACCESSORS_SP_OBJECT().
int serialize (Standard::AbstractStream * stream) const virtual
Examples:
Core/dc/tests/tstLibraryHeader.cpp.
References LibraryHeader::b_day_made, LibraryHeader::b_month_made, LibraryHeader::b_nuclide_set, LibraryHeader::b_title, LibraryHeader::b_year_made, LibraryHeader::getSerializedSize(), and Origen::write().
Referenced by TEST().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "writing Origen::LibraryHeader::uid..." );
     Standard::write( stream, LibraryHeader::uid );
     jDebugTaggedLine( "writing Origen::LibraryHeader::SerializedSize..." );
     Standard::write( stream, getSerializedSize() );
     Remember( size_t checkpoint = stream->getWriteHead() );
     jDebugTaggedLine( "reading Origen::LibraryHeader::b_month_made..." );
     Standard::write( stream, b_month_made );
     jDebugTaggedLine( "writing Origen::LibraryHeader::b_day_made..." );
     Standard::write( stream, b_day_made );
     jDebugTaggedLine( "writing Origen::LibraryHeader::b_year_made..." );
     Standard::write( stream, b_year_made );
     jDebugTaggedLine( "writing Origen::LibraryHeader::b_nuclide_set..." );
     Standard::write( stream, b_nuclide_set );
     jDebugTaggedLine( "writing Origen::LibraryHeader::b_title..." );
     Standard::write( stream, b_title );
     Ensure( stream->getWriteHead() == checkpoint + getSerializedSize() );
     return 0;
 }
int deserialize (Standard::AbstractStream * stream) virtual
Examples:
Core/dc/tests/tstLibraryHeader.cpp.
References LibraryHeader::b_day_made, LibraryHeader::b_month_made, LibraryHeader::b_nuclide_set, LibraryHeader::b_title, LibraryHeader::b_year_made, LibraryHeader::canonicalize_nuclide_set(), LibraryHeader::getSerializedSize(), and Origen::read().
Referenced by TEST().
 {
     Require( stream != nullptr );
     jDebugTaggedLine( "reading Origen::LibraryHeader::uid..." );
     int return_code = read( stream, LibraryHeader::uid );
     if( return_code != 0 ) return return_code;
     jDebugTaggedLine( "reading Origen::LibraryHeader::SerializedSize..." );
     unsigned long size;
     read( stream, size );
     size_t bytes = 0;
     jDebugTaggedLine( "reading Origen::LibraryHeader::b_month_made..." );
     bytes += read( stream, b_month_made );
     jDebugTaggedLine( "reading Origen::LibraryHeader::b_day_made..." );
     bytes += read( stream, b_day_made );
     jDebugTaggedLine( "reading Origen::LibraryHeader::b_year_made..." );
     bytes += read( stream, b_year_made );
     jDebugTaggedLine( "reading Origen::LibraryHeader::b_nuclide_set..." );
     b_nuclide_set = std::make_shared<NuclideSet>();
     bytes += read( stream, b_nuclide_set );
     canonicalize_nuclide_set();
     jDebugTaggedLine( "reading Origen::LibraryHeader::b_title..." );
     bytes += read( stream, b_title );
     Ensure( size == getSerializedSize() && size == bytes );
     if( size != getSerializedSize() || size != bytes ) return 1;
     return 0;
 }
unsigned long getSerializedSize () const virtual
References LibraryHeader::b_day_made, LibraryHeader::b_month_made, LibraryHeader::b_nuclide_set, LibraryHeader::b_title, and LibraryHeader::b_year_made.
Referenced by LibraryHeader::deserialize(), and LibraryHeader::serialize().
 {
     Standard::AbstractStream* a = nullptr;
     return Standard::bytes( a, b_month_made ) +
            Standard::bytes( a, b_day_made ) +
            Standard::bytes( a, b_year_made ) + Standard::bytes( a, b_title ) +
            Standard::bytes( a, b_nuclide_set );
 }
LibraryHeader * getCopy () const virtual
References LibraryHeader::LibraryHeader().
 {
     return new LibraryHeader( *this );
 }
long getUID () const virtual
References LibraryHeader::uid.
 { return LibraryHeader::uid; }
bool childOf (long parentUID) const virtual
 {
     return Standard::Serializable::getUID() == parentUID ||
            Standard::Serializable::childOf( parentUID );
 }
std::string toString () const virtual
References LibraryHeader::to_string().
 { return to_string(); }
void set_month_made (int scalar)
set the scalar month_made
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::createLibraryHeader_random1(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and LibraryTest::SetUp().
int month_made () const
return the scalar month_made
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Referenced by LibraryHeader::operator==(), Library::populate_transition_matrix(), LibraryIO_s61::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
void set_day_made (int scalar)
set the scalar day_made
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::createLibraryHeader_random1(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and LibraryTest::SetUp().
int day_made () const
return the scalar day_made
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Referenced by LibraryHeader::operator==(), Library::populate_transition_matrix(), LibraryIO_s61::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
void set_year_made (int scalar)
set the scalar year_made
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by LibraryBuilder::create_library(), FakeFactory::createLibraryHeader_random1(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and LibraryTest::SetUp().
int year_made () const
return the scalar year_made
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Referenced by LibraryHeader::operator==(), Library::populate_transition_matrix(), LibraryIO_s61::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
void set_title (std::string scalar)
set the scalar title
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Examples:
Core/dc/tests/tstLibrary.cpp.
Referenced by FakeFactory::createLibraryHeader_random1(), LibraryIO_s62b::read(), LibraryIO_s61::read(), LibraryIO_bof::read(), and LibraryTest::SetUp().
std::string title () const
return the scalar title
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCALAR().
Referenced by LibraryHeader::operator==(), Library::populate_transition_matrix(), LibraryIO_s61::write(), LibraryIO_bof::write(), and LibraryIO_s62b::write().
size_t total_nuclides () const
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_DecayResource.cpp.
References LibraryHeader::b_nuclide_set, and LibraryHeader::has_nuclide_set().
Referenced by get_decay_data(), get_transition_data(), gtestLibrarySizes(), and inject_fission_yields().
 {
     return has_nuclide_set() ? b_nuclide_set->total_nuclides() : 0;
 }
void canonicalize_nuclide_set () protected
Referenced by LibraryHeader::deserialize().
 {}
Friends And Related Function Documentation
friend class ScaleUtils::IO::Accessor< Origen::LibraryHeader > friend
Member Data Documentation
const long uid = 0x99514754f6b0dc5d static
Referenced by Library::deserialize(), LibraryHeader::getUID(), Origen_LibraryHeader_uid(), and LibraryHeader::to_json().
SP_NuclideSet b_nuclide_set protected
Referenced by LibraryHeader::deserialize(), LibraryHeader::getSerializedSize(), LibraryHeader::operator==(), LibraryHeader::print_compare(), Accessor< Origen::LibraryHeader >::read(), LibraryHeader::serialize(), LibraryHeader::to_json(), and LibraryHeader::total_nuclides().
int b_month_made protected
Month library was made (nmonth)
Referenced by LibraryHeader::deserialize(), LibraryHeader::getSerializedSize(), LibraryHeader::operator==(), LibraryHeader::print_compare(), Accessor< Origen::LibraryHeader >::read(), LibraryHeader::serialize(), and LibraryHeader::to_json().
int b_day_made protected
Day library was made (nday)
Referenced by LibraryHeader::deserialize(), LibraryHeader::getSerializedSize(), LibraryHeader::operator==(), LibraryHeader::print_compare(), Accessor< Origen::LibraryHeader >::read(), LibraryHeader::serialize(), and LibraryHeader::to_json().
int b_year_made protected
year library was made (nyear)
Referenced by LibraryHeader::deserialize(), LibraryHeader::getSerializedSize(), LibraryHeader::operator==(), LibraryHeader::print_compare(), Accessor< Origen::LibraryHeader >::read(), LibraryHeader::serialize(), and LibraryHeader::to_json().
std::string b_title protected
Library title
Referenced by LibraryHeader::deserialize(), LibraryHeader::getSerializedSize(), LibraryHeader::operator==(), LibraryHeader::print_compare(), Accessor< Origen::LibraryHeader >::read(), LibraryHeader::serialize(), and LibraryHeader::to_json().
The documentation for this class was generated from the following files:
Core/dc/LibraryHeader.h
Core/dc/LibraryHeader.cpp