ORIGEN API: EnergyResource Class Reference
EnergyResource Class Reference
#include <EnergyResource.h>
Computes kappa values for fission/capture based on izzzaaa lookup.
Public Member Functions
bool getKappaValues (int izzzaaa, double &kapCap, double &kapFiss) const
getKappaValues
double getKappaAbs (int izzzaaa, double sigCap, double sigFiss, double numden=1.0) const
Detailed Description
Computes kappa values for fission/capture based on izzzaaa lookup.
Examples:
tstEnergyResource.cpp.
Member Typedef Documentation
typedef std::map<int, std::pair<double, double> > Map
typedef Map::value_type Pair
typedef Map::mapped_type Value
Member Function Documentation
bool getKappaValues (int izzzaaa, double & kapCap, double & kapFiss) const
getKappaValues
Parameters
<b>int</b> izzzaaa : nuclide id
<b>double</b> kapCap : kappa-capture in MeV
<b>double</b> kapFiss : kappa-fission in MeV
Returns
bool - true if izzzaaa was found, else false.
Examples:
tstEnergyResource.cpp.
References EnergyResource::DEFAULT_KAPPA_CAPTURE, EnergyResource::DEFAULT_KAPPA_FISSION, and EnergyResource::map.
Referenced by TransitionMatrixP::finish_init(), Origen::get_default_kappas(), and EnergyResource::getKappaAbs().
double getKappaAbs (int izzzaaa, double sigCap, double sigFiss, double numden = 1.0) const
References EnergyResource::getKappaValues().
Member Data Documentation
const EnergyResource::Map map static private
Referenced by EnergyResource::getKappaValues().
const double DEFAULT_KAPPA_CAPTURE = 5.0 static private
Referenced by EnergyResource::getKappaValues().
const double DEFAULT_KAPPA_FISSION = 200.0 static private
Referenced by EnergyResource::getKappaValues().
The documentation for this class was generated from the following files:
Core/re/EnergyResource.h
Core/re/EnergyResource.cpp