ORIGEN API: StateSetIO_s62b Class Reference
StateSetIO_s62b Class Reference
#include <StateSetIO_s62b.h>
Public Member Functions
bool read (StateSet &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const StateSet &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Member Function Documentation
bool read (StateSet & obj, std::istream & stream, ScaleUtils::IO::DB opts)
References StateSet::add_states(), StateInfo::case_number(), Origen::convertConcUnitToPrettyString(), StateInfo::energy(), StateInfo::flux(), Origen::intAsUnit(), StateInfo::library_position(), NuclideSet::looks_like_zzzaaai(), State::num_alpha_groups(), State::num_beta_groups(), State::num_gamma_groups(), State::num_neutron_groups(), StateInfo::power(), State::set_alpha_spectra(), State::set_beta_spectra(), Spectrum::set_bounds(), StateInfo::set_case_number(), State::set_concs(), State::set_definition(), StateInfo::set_energy(), StateInfo::set_flux(), State::set_gamma_spectra(), NuclideSet::set_ids(), NuclideSet::set_ids_legacy(), Spectrum::set_intensity(), NeutronSpectra::set_intensity_alphan(), NeutronSpectra::set_intensity_delayn(), NeutronSpectra::set_intensity_sf(), StateInfo::set_library_position(), State::set_neutron_spectra(), Concentrations::set_nuclide_set(), GammaSpectra::set_nuclide_type(), AlphaSpectra::set_nuclide_type(), BetaSpectra::set_nuclide_type(), StateInfo::set_power(), StateInfo::set_step_number(), StateInfo::set_time(), Concentrations::set_units(), Concentrations::set_vals(), StateInfo::step_number(), StateInfo::time(), State::total_nuclides(), and Concentrations::units().
 {
     // binary stream manipulator
     ScaleUtils::IO::IStreamManipulator_FBin binsman( stream );
     //
     // Insist we can read from this istream
     //
     if( !stream.good() )
     {
         opts.appendError( "Failed to open stream for reading." );
         return false;
     }
     nemesis::Timer t;
     t.start();
     //
     // Read first header to check for endianess
     //
     int test = 0;
     bool revBytes = false;
     stream.read( (char*)( &test ), sizeof( int ) );
     if( test < 0 || test > 1000 )
     {
         revBytes = true;
     }
     binsman.setReverseBytes( revBytes );
     // add file endianness
     opts.set( "readFileEndian",
               ScaleUtils::IO::EndianUtils::file_is_big_endian( !revBytes )
                   ? "big"
                   : "little" );
     //
     // Rewind to beginning of file
     //
     stream.seekg( 0, std::ios::beg );
     //
     // Loop over cases
     // if header states size=0, then no more cases
     //
     for( ;; )
     {
         //
         // Peek ahead to ensure not at eof
         //
         stream.peek();
         if( stream.good() == false ) break;
         //
         // Read Case Header
         //
         //
         // Read fortran header of record
         binsman.readHeader();
         jDebugTaggedLine( "reading header" );
         if( binsman.getHeader() <= 0 ) break;
         // Will add everything to this
         State state;
         //
         // Process header
         //
         StateInfo def;
         int cn, sn, lp;
         float po, bu, fl, ti;
         binsman >> cn;
         def.set_case_number( cn );
         binsman >> sn;
         def.set_step_number( sn );
         binsman >> lp;
         def.set_library_position( lp );
         binsman >> po;
         def.set_power( po );
         binsman >> bu;
         def.set_energy( bu );
         binsman >> fl;
         def.set_flux( fl );
         binsman >> ti;
         def.set_time( ti );
         int tn, nln, nan, nfpn;
         binsman >> tn;    // def.total_nuclides;
         binsman >> nln;   // def.num_lite_nuclides;
         binsman >> nan;   // def.num_actinide_nuclides;
         binsman >> nfpn;  // def.num_fission_product_nuclides;
         int nng, ngg, nag, nbg;
         binsman >> nng;  // def.num_neutron_groups;
         binsman >> ngg;  // def.num_gamma_groups;
         binsman >> nag;  // def.num_alpha_groups;
         binsman >> nbg;  // def.num_beta_groups;
         state.set_definition( def );
         jDebugLine( "Case number: " << def.case_number() << ", Step number: "
                                     << def.step_number()
                                     << ", Library position: "
                                     << def.library_position()
                                     << ", power: "
                                     << def.power()
                                     << ", energy: "
                                     << def.energy()
                                     << ", flux: "
                                     << def.flux()
                                     << ", time: "
                                     << def.time() );
         //
         // Read fortran footer of record
         binsman.readFooter();
         // Check fortran record consistency
         if( binsman.getHeader() != binsman.getFooter() )
         {
             opts.appendError( "Record #1 Fortran header not equal to footer" );
             return false;
         }
         //
         // Read Case concentrations
         // OPTIONAL
         //
         // Read fortran header of record
         binsman.readHeader();
         if( binsman.getHeader() > 0 )
         {
             Check( tn > 0 );
             Concentrations concs;
             Vec_Int nuclide_ids( tn );
             binsman >> nuclide_ids;
             int units = -1;
             binsman >> units;
             concs.set_units( intAsUnit( units ) );
             jDebugLine( "Read "
                         << convertConcUnitToPrettyString( concs.units() )
                         << " <- "
                         << units
                         << " as units on F71" );
             NuclideSet nucset;
             // sizzzaaa case
             if( nln == 0 && nan == 0 && nfpn == 0 )
             {
                 nucset.set_ids( nuclide_ids );
             }
             // zai case
             else
             {
                 Check( NuclideSet::looks_like_zzzaaai( nuclide_ids ) );
                 nucset.set_ids_legacy( nln, nan, nfpn, nuclide_ids );
             }
             concs.set_nuclide_set( nucset );
             Vec_Dbl concentrations( tn );
             binsman >> concentrations;
             concs.set_vals( concentrations );
             state.set_concs( concs );
             jDebugLine( "--Concentrations.units:"
                         << convertConcUnitToPrettyString( concs.units() )
                         << ", number concentrations:"
                         << state.total_nuclides() );
         }  // though was no concentrations record
         else
         {
             jDebugLine( "--No Concentrations record." );
         }
         //
         // Read fortran footer of record
         binsman.readFooter();
         // Check fortran record consistency
         Check( binsman.getHeader() == binsman.getFooter() );
         //
         // Read Case neutron spectra
         // OPTIONAL
         //
         // Read fortran header of record
         binsman.readHeader();
         if( binsman.getHeader() > 0 )
         {
             Check( nng > 0 );
             NeutronSpectra nspec;
             Vec_Dbl dvec;
             dvec.resize( nng + 1 );
             binsman >> dvec;
             nspec.set_bounds( dvec );
             dvec.resize( nng );
             binsman >> dvec;
             nspec.set_intensity( dvec );
             dvec.resize( nng );
             binsman >> dvec;
             nspec.set_intensity_sf( dvec );
             dvec.resize( nng );
             binsman >> dvec;
             nspec.set_intensity_alphan( dvec );
             dvec.resize( nng );
             binsman >> dvec;
             nspec.set_intensity_delayn( dvec );
             state.set_neutron_spectra( nspec );
             jDebugLine( "--Read Neutron spectra" );
         }
         else
         {
             jDebugLine( "--No Neutron spectra record." );
         }
         //
         // Read fortran footer of record
         binsman.readFooter();
         // Check fortran record consistency
         Check( binsman.getHeader() == binsman.getFooter() );
         //
         // Read Case gamma spectra
         // OPTIONAL
         //
         // Read fortran header of record
         binsman.readHeader();
         if( binsman.getHeader() > 0 )
         {
             Check( ngg > 0 );
             GammaSpectra gspec;
             Vec_Dbl dvec;
             dvec.resize( ngg + 1 );
             binsman >> dvec;
             gspec.set_bounds( dvec );
             int nt;
             binsman >> nt;
             gspec.set_nuclide_type( nt );
             dvec.resize( ngg );
             binsman >> dvec;
             gspec.set_intensity( dvec );
             state.set_gamma_spectra( gspec );
             jDebugLine( "--Read Gamma spectra." );
         }
         else
         {
             jDebugLine( "--No Gamma spectra record." );
         }
         //
         // Read fortran footer of record
         binsman.readFooter();
         // Check fortran record consistency
         Check( binsman.getHeader() == binsman.getFooter() );
         //
         // Read Case alpha spectra
         // OPTIONAL
         //
         // Read fortran header of record
         binsman.readHeader();
         if( binsman.getHeader() > 0 )
         {
             Check( nag > 0 );
             AlphaSpectra aspec;
             Vec_Dbl dvec;
             dvec.resize( nag + 1 );
             binsman >> dvec;
             aspec.set_bounds( dvec );
             int nt;
             binsman >> nt;
             aspec.set_nuclide_type( nt );
             dvec.resize( nag );
             binsman >> dvec;
             aspec.set_intensity( dvec );
             state.set_alpha_spectra( aspec );
             jDebugLine( "--Read Alpha spectra." );
         }
         else
         {
             jDebugLine( "--No Alpha spectra record." );
         }
         //
         // Read fortran footer of record
         binsman.readFooter();
         // Check fortran record consistency
         Check( binsman.getHeader() == binsman.getFooter() );
         //
         // Read Case beta spectra
         // OPTIONAL
         //
         // Read fortran header of record
         binsman.readHeader();
         if( binsman.getHeader() > 0 )
         {
             Check( nbg > 0 );
             BetaSpectra bspec;
             Vec_Dbl dvec;
             dvec.resize( nbg + 1 );
             binsman >> dvec;
             bspec.set_bounds( dvec );
             int nt;
             binsman >> nt;
             bspec.set_nuclide_type( nt );
             dvec.resize( nbg );
             binsman >> dvec;
             bspec.set_intensity( dvec );
             state.set_beta_spectra( bspec );
             jDebugLine( "--Read Beta spectra." );
         }
         else
         {
             jDebugLine( "--No Beta spectra record." );
         }
         //
         // Read fortran footer of record
         binsman.readFooter();
         // Check fortran record consistency
         Check( binsman.getHeader() == binsman.getFooter() );
         jDebugLine( ", total nuclides: " << state.total_nuclides()
                                          << ", num neutron groups: "
                                          << state.num_neutron_groups()
                                          << ", num gamma groups: "
                                          << state.num_gamma_groups()
                                          << ", num alpha groups: "
                                          << state.num_alpha_groups()
                                          << ", num beta groups: "
                                          << state.num_beta_groups() );
         //
         // Save the case we just read
         //
         set.add_states( state );
     }  // infinite
     t.stop();
     opts.set( "loadTime", 1000 * t.wall_clock() );
     return true;
 }
bool write (const StateSet & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
References State::alpha_spectra(), State::beta_spectra(), Spectrum::bounds_array(), StateInfo::case_number(), State::concs(), NuclideSet::convert_sizzzaaa_to_zzzaaai(), Origen::convertConcUnitToPrettyString(), NuclideSet::count_sublibs(), State::definition(), StateInfo::energy(), kernel_rksuite::f(), StateInfo::flux(), State::gamma_spectra(), State::has_definition(), NuclideSet::ids(), NuclideSet::ids_array(), NeutronSpectra::intensity_alphan_array(), Spectrum::intensity_array(), NeutronSpectra::intensity_delayn_array(), NeutronSpectra::intensity_sf_array(), StateInfo::library_position(), State::neutron_spectra(), Concentrations::nuclide_set(), BetaSpectra::nuclide_type(), GammaSpectra::nuclide_type(), AlphaSpectra::nuclide_type(), State::num_alpha_groups(), State::num_beta_groups(), State::num_gamma_groups(), NuclideSet::num_in_sublib(), State::num_neutron_groups(), StateInfo::power(), StateSet::states_at(), StateSet::states_size(), StateInfo::step_number(), Origen::SUBLIB_1LT, Origen::SUBLIB_2AC, Origen::SUBLIB_3FP, StateInfo::time(), Concentrations::total_nuclides(), Origen::unitAsInt(), Concentrations::units(), and Concentrations::vals_array().
 {
     nemesis::Timer t;
     t.start();
     // add file endianness
     opts.set( "wroteFileEndian",
               ScaleUtils::IO::EndianUtils::system_is_big_endian() ? "big"
                                                                   : "little" );
     int zero = 0;
     int int_size = sizeof( int );
     int float_size = sizeof( float );
     int double_size = sizeof( double );
     for( size_t index = 0; index < set.states_size(); ++index )
     {
         const State& state = set.states_at( index );
         int nc = 0;
         int nn = 0;
         int ng = 0;
         int na = 0;
         int nb = 0;
         const StateInfo& def = state.definition();
         const Concentrations& concs = state.concs();
         const NuclideSet& nucset = concs.nuclide_set();
         const NeutronSpectra& nspec = state.neutron_spectra();
         const GammaSpectra& gspec = state.gamma_spectra();
         const AlphaSpectra& aspec = state.alpha_spectra();
         const BetaSpectra& bspec = state.beta_spectra();
         // flag to write legacy style outputs so Triton can read it with
         // DeprecatedIO
         bool legacy_style = true;
         //
         // Write header
         //
         if( !state.has_definition() )
         {
             //
             // Just dump fortran header and footer
             //
             stream.write( (char*)&zero, int_size );  // header
             stream.write( (char*)&zero, int_size );  // footer
         }
         else
         {
             int bytes = 3 * int_size + 4 * float_size + 8 * int_size;
             stream.write( (char*)&bytes, int_size );  // header
             jDebugTaggedLine( def.case_number() << "." << def.step_number() );
             int i;
             float f;
             i = def.case_number();
             stream.write( (char*)&i, int_size );
             i = def.step_number();
             stream.write( (char*)&i, int_size );
             i = def.library_position();
             stream.write( (char*)&i, int_size );
             f = def.power();
             stream.write( (char*)&f, float_size );
             f = def.energy();
             stream.write( (char*)&f, float_size );
             f = def.flux();
             stream.write( (char*)&f, float_size );
             f = def.time();
             stream.write( (char*)&f, float_size );
             nc = concs.total_nuclides();
             stream.write( (char*)&nc, int_size );
             // handle writing with or without sublibs
             if( nucset.count_sublibs() == 3 )
             {
                 i = nucset.num_in_sublib( SUBLIB_1LT );
                 stream.write( (char*)&i, int_size );
                 i = nucset.num_in_sublib( SUBLIB_2AC );
                 stream.write( (char*)&i, int_size );
                 i = nucset.num_in_sublib( SUBLIB_3FP );
                 stream.write( (char*)&i, int_size );
             }
             else
             {
                 legacy_style = false;
                 i = 0;
                 stream.write( (char*)&i, int_size );
                 i = 0;
                 stream.write( (char*)&i, int_size );
                 i = 0;
                 stream.write( (char*)&i, int_size );
             }
             nn = state.num_neutron_groups();
             stream.write( (char*)&nn, int_size );
             ng = state.num_gamma_groups();
             stream.write( (char*)&ng, int_size );
             na = state.num_alpha_groups();
             stream.write( (char*)&na, int_size );
             nb = state.num_beta_groups();
             stream.write( (char*)&nb, int_size );
             stream.write( (char*)&bytes, int_size );  // footer
             jDebugLine( "Case number: " << def.case_number()
                                         << ", Step number: "
                                         << def.step_number()
                                         << ", Library position: "
                                         << def.library_position()
                                         << ", power: "
                                         << def.power()
                                         << ", energy: "
                                         << def.energy()
                                         << ", flux: "
                                         << def.flux()
                                         << ", time: "
                                         << def.time()
                                         << ", total nuclides: "
                                         << nc
                                         << ", num neutron groups: "
                                         << nn
                                         << ", num gamma groups: "
                                         << ng
                                         << ", num alpha groups: "
                                         << na
                                         << ", num beta groups: "
                                         << nb );
         }
         //
         // Write concentrations
         //
         if( nc == 0 )
         {
             //
             // Just dump fortran header and footer
             //
             stream.write( (char*)&zero, int_size );  // header
             stream.write( (char*)&zero, int_size );  // footer
         }
         else
         {
             int bytes = int_size * nc + int_size + double_size * nc;
             stream.write( (char*)&bytes, int_size );  // header
             // legacy style requires zzzaai ids
             if( legacy_style )
             {
                 Vec_Int ids = nucset.ids();
                 NuclideSet::convert_sizzzaaa_to_zzzaaai( &ids );
                 stream.write( (char*)&ids[0], int_size * nc );
             }
             else
             {
                 stream.write( (char*)nucset.ids_array(), int_size * nc );
             }
             int units_int = unitAsInt( concs.units() );
             jDebugLine( "Writing "
                         << convertConcUnitToPrettyString( concs.units() )
                         << " . "
                         << units_int
                         << " as units on F71" );
             stream.write( (char*)&units_int, int_size );
             stream.write( (char*)concs.vals_array(), double_size * nc );
             stream.write( (char*)&bytes, int_size );  // footer
         }
         //
         // Write neutron spectra
         //
         if( nn == 0 )
         {
             //
             // Just dump fortran header and footer
             //
             stream.write( (char*)&zero, int_size );  // header
             stream.write( (char*)&zero, int_size );  // footer
         }
         else
         {
             int bytes = double_size * ( nn + 1 ) + double_size * (nn)*4;
             stream.write( (char*)&bytes, int_size );  // header
             stream.write( (char*)nspec.bounds_array(),
                           double_size * ( nn + 1 ) );
             stream.write( (char*)nspec.intensity_array(),
                           double_size * ( nn ) );
             stream.write( (char*)nspec.intensity_sf_array(),
                           double_size * ( nn ) );
             stream.write( (char*)nspec.intensity_alphan_array(),
                           double_size * ( nn ) );
             stream.write( (char*)nspec.intensity_delayn_array(),
                           double_size * ( nn ) );
             stream.write( (char*)&bytes, int_size );  // footer
         }
         //
         // Write gamma spectra
         //
         if( ng == 0 )
         {
             //
             // Just dump fortran header and footer
             //
             stream.write( (char*)&zero, int_size );  // header
             stream.write( (char*)&zero, int_size );  // footer
         }
         else
         {
             int bytes =
                 double_size * ( ng + 1 ) + double_size * ( ng ) + int_size;
             stream.write( (char*)&bytes, int_size );  // header
             stream.write( (char*)gspec.bounds_array(),
                           double_size * ( ng + 1 ) );
             int nt = gspec.nuclide_type();
             stream.write( (char*)&nt, int_size );
             stream.write( (char*)gspec.intensity_array(),
                           double_size * ( ng ) );
             stream.write( (char*)&bytes, int_size );  // footer
         }
         //
         // Write alpha spectra
         //
         if( na == 0 )
         {
             //
             // Just dump fortran header and footer
             //
             stream.write( (char*)&zero, int_size );  // header
             stream.write( (char*)&zero, int_size );  // footer
         }
         else
         {
             int bytes =
                 double_size * ( na + 1 ) + double_size * ( na ) + int_size;
             stream.write( (char*)&bytes, int_size );  // header
             stream.write( (char*)aspec.bounds_array(),
                           double_size * ( na + 1 ) );
             int nt = aspec.nuclide_type();
             stream.write( (char*)&nt, int_size );
             stream.write( (char*)aspec.intensity_array(),
                           double_size * ( na ) );
             stream.write( (char*)&bytes, int_size );  // footer
         }
         //
         // Write beta spectra
         //
         if( nb == 0 )
         {
             //
             // Just dump fortran header and footer
             //
             stream.write( (char*)&zero, int_size );  // header
             stream.write( (char*)&zero, int_size );  // footer
         }
         else
         {
             int bytes =
                 double_size * ( nb + 1 ) + double_size * ( nb ) + int_size;
             stream.write( (char*)&bytes, int_size );  // header
             stream.write( (char*)bspec.bounds_array(),
                           double_size * ( nb + 1 ) );
             int nt = bspec.nuclide_type();
             stream.write( (char*)&nt, int_size );
             stream.write( (char*)bspec.intensity_array(),
                           double_size * ( nb ) );
             stream.write( (char*)&bytes, int_size );  // footer
         }
     }  // loop
     t.stop();
     opts.set( "saveTime", 1000 * t.wall_clock() );
     return true;
 }
The documentation for this class was generated from the following files:
Core/io/StateSetIO_s62b.h
Core/io/StateSetIO_s62b.cpp