ORIGEN API: DecayParent Class Reference
DecayParent Class Reference
#include <DecayResource.h>
Public Member Functions
DecayParent ()
~DecayParent ()
void get_channel_map (Vec_Int &decay_modes, std::vector< DecayChannel * > &decaychannels)
void list_decay_modes (Vec_Int &decay_modes) const
const DecayChannel * get_decaychannel_ptr (const int decay_mode) const
int num_residuals (const int decay_mode) const
int num_decay_modes () const
double get_half_life () const
void set_half_life (double value)
double get_rcg_for_air () const
void set_rcg_for_air (double value)
double get_rcg_for_water () const
void set_rcg_for_water (double value)
double get_decay_constant () const
void set_decay_constant (double value)
double get_q_fraction_from_photons () const
void set_q_fraction_from_photons (double value)
double get_recoverable_energy_value () const
void set_recoverable_energy_value (double value)
int get_time_units () const
void set_time_units (int value)
const std::map< int, DecayChannel > & get_const_channel_map () const
std::map< int, DecayChannel > & get_channel_map ()
Detailed Description
Examples:
tstDecayResourceIO.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
Constructor & Destructor Documentation
DecayParent ()
~DecayParent ()
Member Function Documentation
void get_channel_map (Vec_Int & decay_modes, std::vector< DecayChannel * > & decaychannels)
Examples:
tstDecayResourceIO.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
References DecayParent::channel_map.
Referenced by DecayResourceIO_cimg::read().
void list_decay_modes (Vec_Int & decay_modes) const
References DecayParent::channel_map.
const DecayChannel* get_decaychannel_ptr (const int decay_mode) const inline
int num_residuals (const int decay_mode) const
References DecayParent::channel_map.
int num_decay_modes () const
Examples:
tstTransitionSystemAdapter_DecayResource.cpp.
References DecayParent::channel_map.
double get_half_life () const
References DecayParent::half_life.
Referenced by DecayResource::check_consistency(), and DecayResource::to_json().
void set_half_life (double value)
References DecayParent::half_life.
Referenced by DecayResourceIO_cimg::read().
double get_rcg_for_air () const
References DecayParent::rcg_for_air.
Referenced by ConcentrationConverter::mol2d(), and DecayResource::to_json().
void set_rcg_for_air (double value)
References DecayParent::rcg_for_air.
Referenced by DecayResourceIO_cimg::read().
double get_rcg_for_water () const
References DecayParent::rcg_for_water.
Referenced by ConcentrationConverter::mol2d(), and DecayResource::to_json().
void set_rcg_for_water (double value)
References DecayParent::rcg_for_water.
Referenced by DecayResourceIO_cimg::read().
double get_decay_constant () const
Examples:
tstDecayResourceIO.cpp, and tstTransitionSystemAdapter_DecayResource.cpp.
References DecayParent::decay_constant.
Referenced by TransitionSystemAdapter_DecayResource::extend(), ConcentrationConverter::mol2d(), and Origen::printDecayTable().
void set_decay_constant (double value)
References DecayParent::decay_constant.
double get_q_fraction_from_photons () const
References DecayParent::q_fraction_from_photons.
Referenced by ConcentrationConverter::mol2d(), Origen::printDecayTable(), and DecayResource::to_json().
void set_q_fraction_from_photons (double value)
References DecayParent::q_fraction_from_photons.
Referenced by DecayResourceIO_cimg::read().
double get_recoverable_energy_value () const
References DecayParent::recoverable_energy_value.
Referenced by DecayResource::check_consistency(), ConcentrationConverter::mol2d(), Origen::printDecayTable(), and DecayResource::to_json().
void set_recoverable_energy_value (double value)
References DecayParent::recoverable_energy_value.
Referenced by DecayResourceIO_cimg::read().
int get_time_units () const
References DecayParent::time_units.
Referenced by DecayResource::to_json().
void set_time_units (int value)
References DecayParent::time_units.
Referenced by DecayResourceIO_cimg::read().
const std::map< int, DecayChannel > & get_const_channel_map () const
References DecayParent::channel_map.
Referenced by DecayResource::check_consistency(), TransitionSystemAdapter_DecayResource::extend(), DecayResource::list_decay_modes(), Origen::printDecayTable(), and DecayResource::to_json().
std::map< int, DecayChannel > & get_channel_map ()
References DecayParent::channel_map.
Member Data Documentation
double half_life private
Referenced by DecayParent::get_half_life(), and DecayParent::set_half_life().
int time_units private
Referenced by DecayParent::get_time_units(), and DecayParent::set_time_units().
double recoverable_energy_value private
Referenced by DecayParent::get_recoverable_energy_value(), and DecayParent::set_recoverable_energy_value().
double q_fraction_from_photons private
Referenced by DecayParent::get_q_fraction_from_photons(), and DecayParent::set_q_fraction_from_photons().
double decay_constant private
Referenced by DecayParent::get_decay_constant(), and DecayParent::set_decay_constant().
double rcg_for_air private
Referenced by DecayParent::get_rcg_for_air(), and DecayParent::set_rcg_for_air().
double rcg_for_water private
Referenced by DecayParent::get_rcg_for_water(), and DecayParent::set_rcg_for_water().
std::map<int, DecayChannel> channel_map private
Referenced by DecayParent::get_channel_map(), DecayParent::get_const_channel_map(), DecayParent::list_decay_modes(), DecayParent::num_decay_modes(), and DecayParent::num_residuals().
The documentation for this class was generated from the following files:
Core/re/DecayResource.h
Core/re/DecayResource.cpp