ORIGEN API: origen_output_class Type Reference
origen_output_class Type Reference
Exposure table printing functions; needed for Origami.
Public Member Functions
procedure, public init => orgout__init
procedure, public output => orgout__output
procedure, public removal_rates_sort
procedure output_absfrac => orgout__output_absfrac
Prints the absorption fraction table.
procedure output_kinf => orgout__output_kinf
Prints the k-inf and neutron balance table.
procedure output_fisrate => orgout__output_fisrate
Prints the fission rate tables.
procedure evaluate_rates_and_balances => orgout__evaluate_rates_and_balances
Public Attributes
character(80) case_title
Subcase title.
integer nsteps
Number of steps.
integer case_number
Sequential number of the case.
integer max_case
Max number of the case.
character(80) case_tag
SON tag.
logical library_print_lite
Light elements library printout control.
logical library_print_act
Actinides library printout control.
logical library_print_fp
Fission products library printout control.
logical library_print_info
Library header printout control.
logical high_precision
Should the printouts contain more significant digits?
logical cutoff_relative
Is the cutoff relative or absolute value?
integer cutoff_step
Step at which the cutoff is applied.
real(c_double), dimension(11) cutoff_value
Cutoff treshold.
character(4) time_unit_name
Name of the time unit.
real(c_double) time_unit_constant
Conversion constant for the time unit (number of seconds per unit)
logical, dimension(11, 4, 2) tables
Which tables should be printed? Nonzero entry means yes. dimension 1 : units (OU_GRAMATOMS, OU_GRAMS,) dimension 2 : nuclide type (Origen_SUBLIB_1LT/Origen_SUBLIB_2AC/Origen_SUBLIB_3FP/ALL) dimension 3 : table type (OT_NUCLIDE, OT_ELEMENT)
logical kinf
Print neutron balance (k-infinity)
integer absfrac
Print neutron absorption fractions (4=all, 1/2/3 = lite/fp/act)
integer fisrate
Print actinide fission rates (1 = absolute, 2 = relative)
integer astar
Time step for sorting absorption fractions.
real(c_double), dimension(:), allocatable neutron_production_coeff
without flux [0:nstep] (lite+act)
real(c_double), dimension(:), allocatable absorption_coeff
without flux [0:nstep] (lite+act)
real(c_double), dimension(:), allocatable absorption_rate
tocap*N*F [0:nstep] (all)
real(c_double), dimension(:), allocatable fission_rate
fiss*N*F [0:nstep] (act)
real(c_double), dimension(:), allocatable actinide_absorption_rate
tocap*N*F [0:nstep] (act)
real(c_double), dimension(:), allocatable macro_absorption
macroscopic absorption at step NSTAR (libitot)
integer, dimension(:), allocatable absorption_order
ordering array for absorption fractions (libitot)
real(c_double), dimension(:), allocatable macro_fission
macroscopic fission at step NSTAR (itot)
integer, dimension(:), allocatable fission_order
ordering array for fission fractions (itot)
real(c_double), dimension(:,:), allocatable absorption_fraction
absorption rate fraction (0:nsteps,libitot))
real(c_double), dimension(:,:), allocatable nuclide_fission_rate
absolute fission rate (0:nsteps,libitot))
real(c_double), dimension(:), allocatable removal_rates
Data for processing (removal)
integer, dimension(:,:), allocatable removal_elements
real(c_double), dimension(n_elements) removal_sorted
Detailed Description
Exposure table printing functions; needed for Origami.
Class handling the concentrations and additional output from ORIGEN.
Member Function/Subroutine Documentation
procedure, public init ()
procedure, public output ()
procedure, public removal_rates_sort ()
procedure output_absfrac ()
Prints the absorption fraction table.
procedure output_kinf ()
Prints the k-inf and neutron balance table.
procedure output_fisrate ()
Prints the fission rate tables.
procedure evaluate_rates_and_balances ()
References origen_definitions_m::avogadro, origen_output::convert_concentrations(), origen_definitions_m::err, const::library_titles, auxiliary::nuclide_compact(), origen_definitions_m::origen_sublib_1lt, origen_definitions_m::origen_sublib_2ac, origen_definitions_m::origen_sublib_3fp, origen_output::ot_nuclide, auxiliary::output(), auxiliary::print_banner(), auxiliary::print_break(), origen_output::print_element_table(), origen_output::print_nuclide_table(), auxiliary::print_time_table(), origen_output::rbuffer, origen_output::sortpn(), auxiliary::table_banner(), auxiliary::table_tail(), const::table_titles, and const::unit_titles.
Member Data Documentation
character(80) case_title
Subcase title.
integer nsteps
Number of steps.
integer case_number
Sequential number of the case.
integer max_case
Max number of the case.
character(80) case_tag
SON tag.
logical library_print_lite
Light elements library printout control.
logical library_print_act
Actinides library printout control.
logical library_print_fp
Fission products library printout control.
logical library_print_info
Library header printout control.
logical high_precision
Should the printouts contain more significant digits?
logical cutoff_relative
Is the cutoff relative or absolute value?
integer cutoff_step
Step at which the cutoff is applied.
real(c_double), dimension(11) cutoff_value
Cutoff treshold.
character(4) time_unit_name
Name of the time unit.
real(c_double) time_unit_constant
Conversion constant for the time unit (number of seconds per unit)
logical, dimension(11,4,2) tables
Which tables should be printed? Nonzero entry means yes. dimension 1 : units (OU_GRAMATOMS, OU_GRAMS,) dimension 2 : nuclide type (Origen_SUBLIB_1LT/Origen_SUBLIB_2AC/Origen_SUBLIB_3FP/ALL) dimension 3 : table type (OT_NUCLIDE, OT_ELEMENT)
logical kinf
Print neutron balance (k-infinity)
integer absfrac
Print neutron absorption fractions (4=all, 1/2/3 = lite/fp/act)
integer fisrate
Print actinide fission rates (1 = absolute, 2 = relative)
integer astar
Time step for sorting absorption fractions.
real(c_double), dimension(:), allocatable neutron_production_coeff
without flux [0:nstep] (lite+act)
real(c_double), dimension(:), allocatable absorption_coeff
without flux [0:nstep] (lite+act)
real(c_double), dimension(:), allocatable absorption_rate
tocap*N*F [0:nstep] (all)
real(c_double), dimension(:), allocatable fission_rate
fiss*N*F [0:nstep] (act)
real(c_double), dimension(:), allocatable actinide_absorption_rate
tocap*N*F [0:nstep] (act)
real(c_double), dimension(:), allocatable macro_absorption
macroscopic absorption at step NSTAR (libitot)
integer, dimension(:), allocatable absorption_order
ordering array for absorption fractions (libitot)
real(c_double), dimension(:), allocatable macro_fission
macroscopic fission at step NSTAR (itot)
integer, dimension(:), allocatable fission_order
ordering array for fission fractions (itot)
real(c_double), dimension(:,:), allocatable absorption_fraction
absorption rate fraction (0:nsteps,libitot))
real(c_double), dimension(:,:), allocatable nuclide_fission_rate
absolute fission rate (0:nsteps,libitot))
real(c_double), dimension(:), allocatable removal_rates
Data for processing (removal)
integer, dimension(:,:), allocatable removal_elements
real(c_double), dimension(n_elements) removal_sorted
The documentation for this type was generated from the following file:
Manager/emit/origen_output.f90