ORIGEN API: Time Struct Reference
Time Struct Reference
#include <Time.h>
Public Types
enum UNITS {
UNKNOWN = -1, SECONDS, MINUTES, HOURS,
DAYS, YEARS, END
}
Static Public Member Functions
template<Time::UNITS u>
static std::string name ()
static std::string name (Time::UNITS u)
template<Time::UNITS u>
static double base ()
static double base (Time::UNITS u)
template<Time::UNITS to, Time::UNITS from>
static double factor ()
template<Time::UNITS to>
static double factor (Time::UNITS from)
static double factor (Time::UNITS to, Time::UNITS from)
static Time::UNITS units (const char *s)
static constexpr Time::UNITS units (int i)
Static Public Attributes
static const UNITS DEFAULT = SECONDS
Detailed Description
Examples:
Core/dc/tests/tstTime.cpp.
Member Enumeration Documentation
enum UNITS
Enumerator
UNKNOWN
SECONDS
MINUTES
HOURS
DAYS
YEARS
END
     {
         UNKNOWN = -1,
         SECONDS,
         MINUTES,
         HOURS,
         DAYS,
         YEARS,
         END
     };
Member Function Documentation
static std::string name () static
Examples:
Core/dc/tests/tstTime.cpp.
Referenced by TEST().
std::string name (Time::UNITS u) inline static
static double base () static
Examples:
Core/dc/tests/tstTime.cpp.
Referenced by Time::factor(), TEST(), and Origen::Time::name< Time::DAYS >().
double base (Time::UNITS u) inline static
static double factor () inline static
Examples:
Core/dc/tests/tstTime.cpp.
Referenced by TEST().
     {
         return base<from>() / base<to>();
     }
static double factor (Time::UNITS from) inline static
References Time::base().
     {
         return base( from ) / base<to>();
     }
static double factor (Time::UNITS to, Time::UNITS from) inline static
     {
         return base( from ) / base( to );
     }
Time::UNITS units (const char * s) inline static
Examples:
Core/dc/tests/tstTime.cpp.
Referenced by TEST().
     {
         return static_cast<Time::UNITS>( i );
     }
 };
 #include "Time.i.h"
 }  // namespace
static constexpr Time::UNITS units (int i) inline static
     {
         return static_cast<Time::UNITS>( i );
     }
Member Data Documentation
const UNITS DEFAULT = SECONDS static
The documentation for this struct was generated from the following files:
Core/dc/Time.h
Core/dc/Time.i.h