ORIGEN API: Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp File Reference
tstTransitionSystemAdapter_AmpxN.cpp File Reference
#include <iomanip>
#include "AmpxLoader/AmpxLoader.h"
#include "Nemesis/gtest/nemesis_gtest.hh"
#include "Origen/Core/TestPaths.h"
#include "Origen/Core/dc/FakeFactory.h"
#include "Origen/Core/fn/print.h"
#include "Origen/Core/io/DecayResourceIO.h"
#include "Origen/Core/io/LibraryIO.h"
#include "Origen/Core/io/ReactionResourceIO.h"
#include "Origen/Core/io/YieldResourceIO.h"
#include "Origen/Core/re/ReactionResource.h"
#include "Origen/Core/ts/Channel.h"
#include "Origen/Core/ts/ChannelType.h"
#include "Origen/Core/ts/Nuclide.h"
#include "Origen/Core/ts/Transition.h"
#include "Origen/Core/ts/TransitionSystem_Gen.h"
#include "Origen/Manager/libld/LibraryBuilder.h"
#include "Origen/Manager/libld/TransitionSystemAdapter_AmpxN.h"
#include "Origen/Manager/libld/TransitionSystemAdapter_DecayResource.h"
#include "ScaleData/Core/Utils.h"
#include "ScaleUtils/IO/DB.h"
Classes
class TransitionSystemAdapterTesterJeff252
Macros
#define MIRROR_VECTOR(PARENT1, VAR1, PARENT2, ADD)
Functions
std::shared_ptr< AmpxLibrary > loadAmpx (std::string ampxlib)
float explicit_calc_og_xs (const int search_iza, const int search_mt, const AmpxLibrary &nxs, const std::vector< float > &flux)
float check_og_xs (Origen::TransitionSystem &ts, const int iza, const int mt, const AmpxLibrary &idnxs, const std::vector< float > &mg_flux)
TEST_F (TransitionSystemAdapterTesterJeff252, OneGroupXsCalc)
TEST_F (TransitionSystemAdapterTesterJeff252, ThreeGroupStorage)
TEST_F (TransitionSystemAdapterTesterJeff252, FissionYields)
TEST_F (TransitionSystemAdapterTesterJeff252, LibraryBuilder)
void output_ampx_library_text_files (std::string ampxlib, std::string prefix="ampx")
TEST (Output, AmpxLib)
TEST (Output, DISABLED_DoubleMatrix)
Variables
const bool print = false
Macro Definition Documentation
#define MIRROR_VECTOR (PARENT1, VAR1, PARENT2, ADD)
Value:
auto new##VAR1 = PARENT1.VAR1;\
    auto old##VAR1 = PARENT2.VAR1;\
    for(size_t i=0; i<old##VAR1.size(); ++i )\
    {\
        new##VAR1.push_back( ADD + old##VAR1[i] );\
    }\
    PARENT1.VAR1 = new##VAR1
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST().
Function Documentation
std::shared_ptr<AmpxLibrary> loadAmpx (std::string ampxlib)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by output_ampx_library_text_files(), and TransitionSystemAdapterTesterJeff252::SetUp().
float explicit_calc_og_xs (const int search_iza, const int search_mt, const AmpxLibrary & nxs, const std::vector< float > & flux)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by check_og_xs().
float check_og_xs (Origen::TransitionSystem & ts, const int iza, const int mt, const AmpxLibrary & idnxs, const std::vector< float > & mg_flux)
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References TransitionSystem::channel_type(), explicit_calc_og_xs(), TransitionSystem::field(), Origen::NEUTRON_FIELD, TransitionSystem::nuclide(), and auxiliary::nuclide().
Referenced by TEST_F().
TEST_F (TransitionSystemAdapterTesterJeff252 , OneGroupXsCalc)
References TransitionSystem::add_field(), TransitionSystem::channel_type(), check_og_xs(), TransitionSystem::field(), Origen::NEUTRON_FIELD, TransitionSystem::num_nuclides(), and Checkable::to_string().
TEST_F (TransitionSystemAdapterTesterJeff252 , ThreeGroupStorage)
References check_og_xs(), TransitionSystem::num_nuclides(), Origen::printTransitionSystemXs(), and Checkable::to_string().
TEST_F (TransitionSystemAdapterTesterJeff252 , FissionYields)
References TransitionSystem::channel_type(), TransitionSystem::field(), Origen::NEUTRON_FIELD, TransitionSystem::nuclide(), print, and Origen::printTransitionSystemXs().
TEST_F (TransitionSystemAdapterTesterJeff252 , LibraryBuilder)
References LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_library(), LibraryBuilder::create_reaction_transitions(), FakeFactory::createNuclideIds_scale62(), TransitionSystemAdapter_DecayResource::extend(), TransitionSystemAdapter_AmpxN::extend(), origen_beta::iii, Origen::saveLibrary(), LibraryBuilder::set_minimum_reaction_coeff(), TransitionSystemAdapter_AmpxN::set_reaction_resource(), and TransitionSystemAdapter_AmpxN::update().
void output_ampx_library_text_files (std::string ampxlib, std::string prefix = "ampx")
Examples:
Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
References loadAmpx().
TEST (Output , AmpxLib)
TEST (Output , DISABLED_DoubleMatrix)
References dec(), DecayData::decay_constants, Library::decay_data(), Library::definition(), NuclideSet::ids(), TransitionCoeff::matrix(), MIRROR_VECTOR, LibraryHeader::nuclide_set(), TransitionStructure::parent_positions(), Library::set_decay_data(), Library::set_definition(), Library::set_transition_coeff_at(), Library::set_transition_structure(), Library::transition_coeff_at(), and Library::transition_structure().
Variable Documentation
const bool print = false
Examples:
Core/xf/tests/tstMultiZoneDepleter.cpp, and Manager/libld/tests/tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by expokit::dgexpv(), expokit::dgphiv(), and TEST_F().