ORIGEN API: EmissionSpectrum Class Reference
EmissionSpectrum Class Reference
#include <EmissionSpectrum.h>
defines a continuous + discrete line spectra for a single nuclide
Public Types
typedef std::shared_ptr< EmissionSpectrum > SP
typedef std::shared_ptr< const EmissionSpectrum > SCP
Public Member Functions
EmissionSpectrum (int id)
int id () const
size_t num_discrete () const
size_t num_continuous () const
DiscreteSpectrum discrete () const
EnergyRange_t energy_range () const
double total_intensity () const
double total_energy_intensity () const
double mean_energy () const
void set_discrete (const DiscreteSpectrum &discrete)
void set_continuous (const Spectrum &continuous)
Spectrum continuous () const
void bin (const Vec_Dbl &bounds, Vec_Dbl *intensity, double wt=1.0) const
std::string print_continuous () const
std::string print_discrete () const
Static Public Member Functions
static Vec_Dbl create_bounds_log (double emax, double emin, size_t ndiv)
Public Attributes
Spectrum b_continuous
DiscreteSpectrum b_discrete
int b_izzzaaa
int b_field_id
Detailed Description
defines a continuous + discrete line spectra for a single nuclide
Examples:
tstEmissionResource.cpp, tstEmissionSpectrum.cpp, tstGammaResource.cpp, and tstGammaResourceIO.cpp.
Member Typedef Documentation
typedef std::shared_ptr<EmissionSpectrum> SP
typedef std::shared_ptr<const EmissionSpectrum> SCP
Constructor & Destructor Documentation
EmissionSpectrum (int id)
Member Function Documentation
int id () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_izzzaaa.
Referenced by EmissionResource::add_emission(), GammaResourceData::SetUp(), and TEST_P().
size_t num_discrete () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_discrete, and DiscreteSpectrum::b_line.
Referenced by GammaResourceData::SetUp(), and TEST().
size_t num_continuous () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_continuous, and Spectrum::intensity_size().
Referenced by GammaResourceData::SetUp(), and TEST().
DiscreteSpectrum discrete () const
Examples:
tstEmissionResource.cpp, and tstGammaResourceIO.cpp.
References EmissionSpectrum::b_discrete.
Referenced by EmissionSpectrum::set_discrete(), and TEST().
EnergyRange_t energy_range () const
References EmissionSpectrum::b_continuous, EmissionSpectrum::b_discrete, DiscreteSpectrum::energy_range(), and Spectrum::energy_range().
double total_intensity () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_continuous, EmissionSpectrum::b_discrete, DiscreteSpectrum::total_intensity(), and Spectrum::total_intensity().
Referenced by EmissionSpectrum::mean_energy(), and GammaResourceData::SetUp().
double total_energy_intensity () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_continuous, EmissionSpectrum::b_discrete, DiscreteSpectrum::total_energy_intensity(), and Spectrum::total_energy_intensity().
Referenced by EmissionSpectrum::mean_energy(), and GammaResourceData::SetUp().
double mean_energy () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::total_energy_intensity(), and EmissionSpectrum::total_intensity().
Referenced by GammaResourceData::SetUp().
void set_discrete (const DiscreteSpectrum & discrete)
Examples:
tstEmissionSpectrum.cpp.
References EmissionSpectrum::b_discrete, and EmissionSpectrum::discrete().
Referenced by TEST().
void set_continuous (const Spectrum & continuous)
Examples:
tstEmissionSpectrum.cpp.
References EmissionSpectrum::b_continuous, and EmissionSpectrum::continuous().
Referenced by TEST().
Spectrum continuous () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_continuous.
Referenced by EmissionSpectrum::set_continuous(), and TEST().
void bin (const Vec_Dbl & bounds, Vec_Dbl * intensity, double wt = 1.0) const
Examples:
tstEmissionSpectrum.cpp, and tstGammaResourceIO.cpp.
References EmissionSpectrum::b_continuous, EmissionSpectrum::b_discrete, DiscreteSpectrum::bin(), and Spectrum::map_intensity().
Referenced by TEST(), and TEST_P().
Vec_Dbl create_bounds_log (double emax, double emin, size_t ndiv) static
Examples:
tstGammaResourceIO.cpp.
Referenced by TEST_P().
std::string print_continuous () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_continuous, and Spectrum::print_bins().
Referenced by gnuplot_binning_output().
std::string print_discrete () const
Examples:
tstGammaResourceIO.cpp.
References EmissionSpectrum::b_discrete, and DiscreteSpectrum::print_lines().
Referenced by gnuplot_binning_output().
Member Data Documentation
Spectrum b_continuous
Referenced by EmissionSpectrum::bin(), EmissionSpectrum::continuous(), EmissionSpectrum::energy_range(), EmissionSpectrum::num_continuous(), EmissionSpectrum::print_continuous(), GammaResourceIO_cimg::read(), EmissionSpectrum::set_continuous(), EmissionSpectrum::total_energy_intensity(), and EmissionSpectrum::total_intensity().
DiscreteSpectrum b_discrete
Referenced by EmissionSpectrum::bin(), EmissionSpectrum::discrete(), EmissionSpectrum::energy_range(), EmissionSpectrum::num_discrete(), EmissionSpectrum::print_discrete(), GammaResourceIO_cimg::read(), EmissionSpectrum::set_discrete(), EmissionSpectrum::total_energy_intensity(), and EmissionSpectrum::total_intensity().
int b_izzzaaa
Referenced by EmissionSpectrum::id().
int b_field_id
Referenced by GammaResourceIO_cimg::read().
The documentation for this class was generated from the following files:
Core/dc/EmissionSpectrum.h
Core/dc/EmissionSpectrum.cpp