ORIGEN API: Field_Gen Class Reference
Field_Gen Class Reference
#include <Field_Gen.h>
General-purpose implementation of the Field interface.
Public Types
typedef SP_Field SP
strong pointer
typedef WP_Field WP
weak pointer
INTERFACE<<Origen::Checkable>>
See Origen::Checkable for details.
std::string name () const
void get_name (std::string &name) const
void set_name (std::string name)
int id () const
void get_id (int &id) const
void set_id (int id)
bool has_initialized_id () const
std::string to_string () const
bool good () const
bool good (Vec_Str &errors) const
bool is_initialized () const
Scale::Json::Value to_json () const
INTERFACE<<Origen::Field>>
See Origen::Field for details.
double intensity () const
void get_intensity (double &intensity) const
void set_intensity (double intensity)
bool has_initialized_intensity () const
SP_Species species () const
void get_species (SP_Species &species) const
void set_species (SP_Species species)
bool has_initialized_species () const
Public Member Functions
Field_Gen ()
virtual ~Field_Gen ()
Private Member Functions
virtual double intensity_impl () const
virtual void get_intensity_impl (double &intensity) const
virtual void set_intensity_impl (double intensity)
virtual Species::SP species_impl () const
virtual void get_species_impl (Species::SP &species) const
virtual void set_species_impl (Species::SP species)
Private Attributes
Species::SP b_species
double b_intensity
Detailed Description
General-purpose implementation of the Field interface.
See also
Origen::ChannelType_Gen
Examples:
tstTransitionSystem_Gen.cpp.
Member Typedef Documentation
typedef SP_Field SP inherited
strong pointer
typedef WP_Field WP inherited
weak pointer
Constructor & Destructor Documentation
Field_Gen ()
~Field_Gen () virtual
Member Function Documentation
double intensity_impl () const private virtual
Implements Field.
References Field_Gen::b_intensity.
void get_intensity_impl (double & intensity) const private virtual
Reimplemented from Field.
References Field_Gen::b_intensity.
void set_intensity_impl (double intensity) private virtual
Implements Field.
References Field_Gen::b_intensity, and Field::intensity().
Species::SP species_impl () const private virtual
Implements Field.
References Field_Gen::b_species.
void get_species_impl (Species::SP & species) const private virtual
Reimplemented from Field.
References Field_Gen::b_species.
void set_species_impl (Species::SP species) private virtual
Implements Field.
References Field_Gen::b_species, and Field::species().
double intensity () const inherited
Referenced by Field_Gen::set_intensity_impl().
void get_intensity (double & intensity) const inherited
void set_intensity (double intensity) inherited
Referenced by NullField::NullField().
bool has_initialized_intensity () const inherited
SP_Species species () const inherited
Referenced by Field_Gen::set_species_impl().
void get_species (SP_Species & species) const inherited
void set_species (SP_Species species) inherited
Referenced by AlphaField::AlphaField(), DeuteronField::DeuteronField(), ElectronField::ElectronField(), HelionField::HelionField(), NeutrinoField::NeutrinoField(), NeutronField::NeutronField(), NullField::NullField(), PositronField::PositronField(), ProtonField::ProtonField(), and TritonField::TritonField().
bool has_initialized_species () const inherited
std::string name () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), ChannelType_Fiss::good_impl(), ChannelType_Decay::good_impl(), ChannelType_Reac::good_impl(), and TEST().
void get_name (std::string & name) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_name (std::string name) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
int id () const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TransitionSystem_Gen::add_nuclide_impl(), TransitionSystem_Gen::add_species_impl(), Channel_Gen::add_transition_impl(), LibraryBuilder::create_decay_transitions(), LibraryBuilder::create_reaction_transitions(), Nuclide_Gen::gain_impl(), LibraryBuilder::search_reaction_transitions(), Nuclide_Gen::set_losses_impl(), Channel_Gen::set_transition_impl(), TEST(), and TEST_F().
void get_id (int & id) const inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
void set_id (int id) inherited
Examples:
tstTransitionSystem_Gen.cpp.
Referenced by TEST().
bool has_initialized_id () const inherited
Referenced by Nuclide_Gen::set_losses_impl(), TransitionSystem_Gen::set_nuclides_impl(), and Channel_Gen::set_transitions_impl().
std::string to_string () const inherited
Examples:
tstTransitionSystemAdapter_AmpxN.cpp.
Referenced by TEST_F().
bool good () const inherited
bool good (Vec_Str & errors) const inherited
bool is_initialized () const inherited
Referenced by ChannelType_Decay::good_impl(), and ChannelType_Decay::update_byproducts().
Scale::Json::Value to_json () const inherited
Member Data Documentation
Species::SP b_species private
Referenced by Field_Gen::get_species_impl(), Field_Gen::set_species_impl(), and Field_Gen::species_impl().
double b_intensity private
Referenced by Field_Gen::get_intensity_impl(), Field_Gen::intensity_impl(), and Field_Gen::set_intensity_impl().
The documentation for this class was generated from the following files:
Core/ts/Field_Gen.h
Core/ts/Field_Gen.cpp