ORIGEN API: YieldResourceIO_stab1 Class Reference
YieldResourceIO_stab1 Class Reference
#include <YieldResourceIO_stab1.h>
Public Member Functions
bool read (YieldResource &obj, std::istream &stream, ScaleUtils::IO::DB opts)
bool write (const YieldResource &obj, std::ostream &stream, ScaleUtils::IO::DB opts)
Member Function Documentation
bool read (YieldResource & obj, std::istream & stream, ScaleUtils::IO::DB opts)
basic file definition: PART 1: FISSIONABLE NUCLIDE DEFINITION ZA - NUMBER_OF_DATA_SETS - - - PART 2: DATA SET DEFINITION ENERGY - - INTERPOLATION_FLAG - NUM_FISSION_PRODUCTS PART 3: FISSION PRODUCT YIELDS FP_ZA1 FP_YLD1 FP_ZA2 FP_YLD2 FP_ZA3 FP_YLD3 (3 pairs per line) PART 4: LINE OF ZEROES PART 5: LINE OF ZEROES
References YieldParent::add_data(), YieldResource::add_fissionable(), YieldResource::clear(), STab1::Data::cr, STab1::Block::cr, STab1::Data::id, auxiliary::nuclide(), STab1Reader::read(), STab1::Block::set, STab1Reader::stab1, and STab1::Data::val.
 {
     nemesis::Timer t;
     t.start();
     size_t num_errors0 = opts.numError();
     // clear to make sure we start out empty
     obj.clear();
     STab1Reader str;
     std::string error = str.read( stream );
     if( error != "" )
     {
         opts.appendError( error );
         return false;
     }
     // Simplified Tab1
     SP_STab1 stab1 = str.stab1;
     // root/title
     opts.set( "title", stab1->title );
     jDebugLine( "YieldResource: read title=" << ( stab1->title ) );
     // nuclide loop
     for( size_t b = 0; b < stab1->block.size(); ++b )
     {
         // root/nuclide[b]
         const STab1::Block& nuclide = stab1->block[b];
         // root/nuclide[b]/control_record
         const STab1::CR& cr_nuclide = nuclide.cr;
         // root/nuclide[b]/id
         int act_zai = cr_nuclide.getC1();
         // ERROR: id
         if( act_zai == 0 )
         {
             std::stringstream ss;
             ss << "nuclide block " << ( b + 1 ) << " of " << stab1->block.size()
                << " has an id=0";
             opts.appendError( ss.str() );
             continue;
         }
         int act_iza = ScaleData::Utils::zzzaaai_to_pizzzaaa( act_zai );
         // ERROR: nset
         size_t nset = cr_nuclide.getL1();
         if( nset != 0 && nset != nuclide.set.size() )
         {
             std::stringstream ss;
             ss << "nuclide block " << ( b + 1 ) << " of " << stab1->block.size()
                << " has control record with nset=" << nset << " but "
                << nuclide.set.size() << " sets found in data";
             opts.appendError( ss.str() );
             continue;
         }
         // add the new fissionable nuclide
         YieldParent& yp = obj.add_fissionable( act_iza );
         // yield set loop
         for( size_t s = 0; s < nuclide.set.size(); ++s )
         {
             // root/nuclide[b]/yield[s]
             const STab1::Data& yield = nuclide.set[s];
             // root/nuclide[b]/yield[s]/control_record
             const STab1::CR& cr_yield = yield.cr;
             // root/nuclide[b]/yield[s]/energy
             float energy = cr_yield.getC1();
             // root/nuclide[b]/yield[s]/id
             // root/nuclide[b]/yield[s]/val
             const Vec_Int& id = yield.id;
             const Vec_Flt& val = yield.val;
             // ERROR: id/val size consistency
             if( id.size() != val.size() )
             {
                 std::stringstream ss;
                 ss << "nuclide block " << ( b + 1 ) << " of "
                    << stab1->block.size() << " yield set " << ( s + 1 )
                    << " of " << nuclide.set.size()
                    << " has inconsistent sizes of id and value arrays";
                 opts.appendError( ss.str() );
                 continue;
             }
             // trim off the zeros
             Vec_Int filtered_id;
             Vec_Dbl filtered_val;
             for( size_t j = 0; j < id.size(); ++j )
             {
                 if( id[j] == 0 && val[j] == 0.0 ) break;
                 int fp_zai = id[j];
                 int fp_iza = ScaleData::Utils::zzzaaai_to_pizzzaaa( fp_zai );
                 filtered_id.push_back( fp_iza );
                 filtered_val.push_back( val[j] );
             }
             // ERROR: npoints
             size_t npoints = cr_yield.getN2();
             if( npoints != 0 && npoints != filtered_id.size() )
             {
                 std::stringstream ss;
                 ss << "nuclide block " << ( b + 1 ) << " of "
                    << stab1->block.size() << " yield set " << ( s + 1 )
                    << " of " << nuclide.set.size()
                    << " has control record with npoints=" << npoints << " but "
                    << filtered_id.size() << " points found in data";
                 opts.appendError( ss.str() );
                 continue;
             }
             // add the new yield set
             // YieldData& ys =
             yp.add_data( energy, filtered_id, filtered_val );
         }
     }
     t.stop();
     opts.set( "loadTime", 1000 * t.wall_clock() );
     return opts.numError() == num_errors0;
 }
bool write (const YieldResource & obj, std::ostream & stream, ScaleUtils::IO::DB opts)
References STab1::Data::cr, STab1::Block::cr, YieldParent::energy_at(), kernel_rksuite::f(), YieldResource::fissionable_at(), YieldParent::get_fp_ids(), YieldParent::get_yields(), STab1::Data::id, YieldParent::id(), auxiliary::nuclide(), YieldParent::num_energies(), YieldResource::num_fissionables(), YieldParent::num_fps(), STab1::Block::set, STab1Writer::stab1, STab1::Data::val, and STab1Writer::write().
 {
     nemesis::Timer t;
     t.start();
     size_t num_errors0 = opts.numError();
     // Simplified Tab1
     SP_STab1 stab1 = std::make_shared<STab1>();
     // title
     stab1->title = "my title";
     // nuclide loop
     stab1->block.resize( obj.num_fissionables() );
     for( int f = 0; f < obj.num_fissionables(); ++f )
     {
         // get the block and the control record of the fissionable
         STab1::Block& nuclide = stab1->block[f];
         STab1::CR& cr_nuclide = nuclide.cr;
         // extract data from nuclide
         const YieldParent& yn = obj.fissionable_at( f );
         int act_iza = yn.id();
         int act_zai = ScaleData::Utils::pizzzaaa_to_zzzaaai( act_iza );
         // get number of energies
         int num_energies = yn.num_energies();
         // set stuff on the stab1 block
         cr_nuclide.setC1( act_zai );
         cr_nuclide.setL1( num_energies );
         // fission product containers
         int num_fps = yn.num_fps();
         Vec_Int fp_ids( num_fps );
         Vec_Dbl yields( num_fps );
         // get fission product ids
         yn.get_fp_ids( &fp_ids );
         for( size_t j = 0; j < fp_ids.size(); ++j )
         {
             int fp_iza = fp_ids[j];
             int fp_zai = ScaleData::Utils::pizzzaaa_to_zzzaaai( fp_iza );
             fp_ids[j] = fp_zai;
         }
         // loop over energies
         nuclide.set.resize( num_energies );
         for( int e = 0; e < num_energies; ++e )
         {
             // get a yields vector
             yn.get_yields( &yields, e );
             // get the data and control record of the yield set
             STab1::Data& data = nuclide.set[e];
             STab1::CR& cr_yield = data.cr;
             // allocate space for ids and yields
             Vec_Int& id = data.id;
             Vec_Flt& val = data.val;
             id.resize( num_fps );
             val.resize( num_fps );
             // set energy & npoints
             cr_yield.setC1( yn.energy_at( e ) );
             cr_yield.setN2( num_fps );
             // set yields
             for( int j = 0; j < num_fps; ++j )
             {
                 id[j] = fp_ids[j];
                 val[j] = yields[j];
             }
         }
     }
     // Write out using writer.
     STab1Writer stw;
     stw.stab1 = stab1;
     stw.write( stream );
     t.stop();
     opts.set( "saveTime", 1000 * t.wall_clock() );
     return opts.numError() == num_errors0;
 }
The documentation for this class was generated from the following files:
Core/io/YieldResourceIO_stab1.h
Core/io/YieldResourceIO_stab1.cpp