ORIGEN API: StateSet Class Reference
StateSet Class Reference
#include <StateSet.h>
Public Types
typedef std::shared_ptr< StateSet > SP
StateSet smart pointer typedef.
typedef std::shared_ptr< const StateSet > SCP
StateSet constant smart pointer typedef.
Public Member Functions
StateSet ()
Default constructor.
bool operator== (const StateSet &a) const
Test for equality.
bool has_states () const
Get whether the StateSet has states.
size_t states_size () const
Get number of states.
const State & states_at (size_t) const
Create a shallow copy of a State at a given index.
SCP_State scp_states_at (size_t) const
Get a shared pointer to a State at a given index.
bool has_states_at (size_t) const
Get whether the StateSet has a particular state.
void getptr_states_at (const State *&, size_t) const
Get a raw pointer to a state.
void resize_states (size_t)
Resize the states list.
void get_states_at (State &, size_t) const
Get a state at an index.
void set_states_at (const State &, size_t)
Set a state at an index.
void add_states (const State &)
Add a state to the end.
void delete_states_at (size_t)
Delete a state and shift elements.
void manageptr_states_at (State *&, size_t)
Manage a new raw pointer as a shared pointer.
const State & states_back () const
Return the last/back element.
const State & states_front () const
Return the first/front element.
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
void set_decay_resource (SCP_DecayResource)
set a new shared (read-only) decay_resource resource (non-const version) \
Vec_Pair_NSpectra neutron_spectra () const
Return the neutron spectra.
Vec_Pair_ASpectra alpha_spectra () const
Return the alpha spectra.
Vec_Pair_BSpectra beta_spectra () const
Return the beta spectra.
Vec_Pair_GSpectra gamma_spectra () const
Return the gamma spectra.
Vec_Pair_Concs concs () const
Return all concentrations.
Vec_Pair_Concs concs (const Concentrations &filter) const
Return all concentrations for a set of nuclide.
Vec_Dbl burnups () const
Return each burnup on the StateSet.
Vec_Dbl energies () const
Return each energy-released on the StateSet.
Vec_Dbl times () const
Return each time on the StateSet.
Vec_Dbl powers () const
Return each power on the StateSet.
Vec_Dbl fluxes () const
Return each flux on the StateSet.
SP_StateInfo interpolate_info (float time, int case_number) const
Interpolate headers to a given time (cheap)
SP_State interpolate (float time, int case_number) const
Interpolate States to a given time (expensive)
std::vector< size_t > matching_states (int case_number) const
Find all States matching a case number.
size_t nearest_time (float time, const std::vector< size_t > &matches) const
Find State closest to the given time.
int guessNumSteps () const
std::string to_string () const
Scale::Json::Value to_json () const
template<>
std::vector< GridView_StateInfo > create_interp_viewers (const std::vector< size_t > &matches) const
Create an interpolation viewer (GridView_StateInfo) of the headers from a match set of States.
template<>
std::vector< GridView_State > create_interp_viewers (const std::vector< size_t > &matches) const
Create an interpolation viewer from a match set of States.
Protected Member Functions
void canonicalize_states_at (size_t)
bool check_headers ()
Check for self-consistency of all headers on this StateSet.
SP_State interpolate_internal (float time, int case_number, bool info_only) const
Interpolate a StateSet to a given time & optionally generate a new interpolated State.
std::vector< float > create_interp_times (const std::vector< size_t > &viewer_list) const
Create a set of reference times as grid points for interpolation, based on a selected set of States (matches)
template<typename T >
std::vector< T > create_interp_viewers (const std::vector< size_t > &matches) const
template<typename T >
T::GD_t::Vec_Rptr create_interp_responses (const std::vector< T > &viewer_list) const
Create a set of interpolated responses from a viewer list.
template<typename View >
View::Type::SP interpolate_view (float time, const std::vector< float > &times, const std::vector< View > &viewer_list, const View &prototype) const
Generate an interpolation view of the StateSet by mapping a set of States onto GridData;.
Protected Attributes
SP_Vec_SP_State b_states
SCP_DecayResource r_decay_resource
Detailed Description
Stores a set of calculation states.
Author
William A. Wieselquist
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstState.cpp, Core/dc/tests/tstStateSet.cpp, and Core/io/tests/tstStateSetIO.cpp.
Member Typedef Documentation
typedef std::shared_ptr<StateSet> SP
StateSet smart pointer typedef.
typedef std::shared_ptr<const StateSet> SCP
StateSet constant smart pointer typedef.
Constructor & Destructor Documentation
StateSet ()
Default constructor.
 : b_states( new Vec_SP_State() ) {}
Member Function Documentation
bool operator== (const StateSet & a) const
Test for equality.
Test for equality with this State.
References StateSet::b_states, and StateSet::states_size().
 {
     // check that either both lists are nullptr or both exist
     ORIGEN_CHECK_SP( state, b_states, a.b_states );
     // compare elements in list
     ORIGEN_COMPARE_SCALAR( states_size, b_states->size(), a.b_states->size() );
     for( size_t i = 0; i < b_states->size(); ++i )
     {
         ORIGEN_COMPARE_SP( state[i], ( *b_states )[i], ( *a.b_states )[i] );
     }
     return true;
 }
bool has_states () const
Get whether the StateSet has states.
has a non-null states vector
size_t states_size () const
Get number of states.
size of states vector
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
Core/dc/tests/tstStateSet.cpp.
Referenced by StateSet::alpha_spectra(), StateSet::beta_spectra(), StateSet::check_headers(), StateSet::concs(), Obiwan_diff::diff(), StateSet::energies(), StateSet::fluxes(), StateSet::gamma_spectra(), Origen::loadMulti(), StateSet::neutron_spectra(), StateSet::operator==(), StateSet::powers(), Origen::printConcentrations_csv(), Origen::printStateInfo(), Origen::printTags_json(), TEST(), StateSet::times(), timing_ref(), timing_ref_at(), timing_smart_pointer(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
const State & states_at (size_t i) const
Create a shallow copy of a State at a given index.
return a const element for read-only access
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstState.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by StateSet::alpha_spectra(), StateSet::beta_spectra(), StateSet::check_headers(), StateSet::concs(), Obiwan_diff::diff(), StateSet::energies(), StateSet::fluxes(), StateSet::gamma_spectra(), StateSet::neutron_spectra(), StateSet::powers(), TEST(), StateSet::times(), timing_ref(), timing_ref_at(), StateSetIO_s62b::write(), and StateSetIO_bof::write().
SCP_State scp_states_at (size_t i) const
Get a shared pointer to a State at a given index.
return a const std::shared_ptr for read-only access
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
Core/dc/tests/tstGridView.cpp, and Core/dc/tests/tstStateSet.cpp.
Referenced by StateSet::create_interp_times(), StateSet::create_interp_viewers(), Origen::printConcentrations_csv(), Origen::printStateInfo(), Origen::printTags_json(), TEST(), and timing_smart_pointer().
bool has_states_at (size_t i) const
Get whether the StateSet has a particular state.
has a non-null element of states vector
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void getptr_states_at (const State *& , size_t) const
Get a raw pointer to a state.
get a read-only pointer by index
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void resize_states (size_t n)
Resize the states list.
resize the vector
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void get_states_at (State & element, size_t i) const
Get a state at an index.
get a copy of the element in-place
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void set_states_at (const State & element, size_t i)
Set a state at an index.
set a new element by index
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
Core/dc/tests/tstGridView.cpp.
Referenced by TEST().
void add_states (const State & element)
Add a state to the end.
add a new element to the end
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
Examples:
Core/dc/tests/tstGridView.cpp, Core/dc/tests/tstStateSet.cpp, and Core/io/tests/tstStateSetIO.cpp.
Referenced by StateSetIO_bof::read(), StateSetIO_s61::read(), StateSetIO_s62b::read(), FakeFactory::StateSet_random1(), TEST(), and TEST_F().
void delete_states_at (size_t i)
Delete a state and shift elements.
delete an element
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
void manageptr_states_at (State *& element, size_t i)
Manage a new raw pointer as a shared pointer.
manage an existing pointer in this class
Auto-generated from macro \ * #ORIGEN_ACCESSORS_SP_VECTOR_WITH_MANAGEMENT().
const State & states_back () const
Return the last/back element.
References StateSet::b_states.
 {
     Require( b_states->size() > 0 );
     return *b_states->back();
 }
const State & states_front () const
Return the first/front element.
 {
     Require( b_states->size() > 0 );
     return *b_states->front();
 }
SCP_DecayResource decay_resource () const
return shared (read-only) decay_resource resource \
Auto-generated from macro \ #ORIGEN_ACCESSORS_SCP_RESOURCE().
bool has_decay_resource () const
whether this instantiation of class has the decay_resource resource \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
void set_decay_resource (SCP_DecayResource decay_resource)
set a new shared (read-only) decay_resource resource (non-const version) \
Auto-generated from macro #ORIGEN_ACCESSORS_SCP_RESOURCE().
Vec_Pair_NSpectra neutron_spectra () const
Return the neutron spectra.
Return the neutron spectra for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::energy(), State::scp_neutron_spectra(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
Referenced by TEST().
 {
     Vec_Pair_NSpectra result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         SCP_NeutronSpectra s = c.scp_neutron_spectra();
         if( s && s->bounds_size() > 0 )
         {
             result.push_back(
                 std::make_pair( std::make_pair( c.definition().time(),
                                                 c.definition().energy() ),
                                 s ) );
         }
     }
     return result;
 }
Vec_Pair_ASpectra alpha_spectra () const
Return the alpha spectra.
Return the alpha spectra for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::energy(), State::scp_alpha_spectra(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
Referenced by TEST().
 {
     Vec_Pair_ASpectra result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         SCP_AlphaSpectra s = c.scp_alpha_spectra();
         if( s && s->bounds_size() > 0 )
         {
             result.push_back(
                 std::make_pair( std::make_pair( c.definition().time(),
                                                 c.definition().energy() ),
                                 s ) );
         }
     }
     return result;
 }
Vec_Pair_BSpectra beta_spectra () const
Return the beta spectra.
Return the beta spectra for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::energy(), State::scp_beta_spectra(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
Referenced by TEST().
 {
     Vec_Pair_BSpectra result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         SCP_BetaSpectra s = c.scp_beta_spectra();
         if( s && s->bounds_size() > 0 )
         {
             result.push_back(
                 std::make_pair( std::make_pair( c.definition().time(),
                                                 c.definition().energy() ),
                                 s ) );
         }
     }
     return result;
 }
Vec_Pair_GSpectra gamma_spectra () const
Return the gamma spectra.
Return the gamma spectra for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::energy(), State::scp_gamma_spectra(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
Referenced by TEST().
 {
     Vec_Pair_GSpectra result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         SCP_GammaSpectra s = c.scp_gamma_spectra();
         if( s && s->bounds_size() > 0 )
         {
             result.push_back(
                 std::make_pair( std::make_pair( c.definition().time(),
                                                 c.definition().energy() ),
                                 s ) );
         }
     }
     return result;
 }
Vec_Pair_Concs concs () const
Return all concentrations.
Return concentrations for for every State in StateSet.
Returns
Concentrations at each state
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::energy(), State::scp_concs(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
Referenced by TEST().
 {
     Vec_Pair_Concs result;
     for( size_t i = 0; i < states_size(); ++i )
     {
         SCP_Concentrations c = states_at( i ).scp_concs();
         if( c && c->vals_size() > 0 )
         {
             const StateInfo& h = states_at( i ).definition();
             result.push_back(
                 std::make_pair( std::make_pair( h.time(), h.energy() ), c ) );
         }
     }
     return result;
 }
Vec_Pair_Concs concs (const Concentrations & filter) const
Return all concentrations for a set of nuclide.
Return filtered concentrations.
Parameters
Concentrations object with a NuclideSet and units used to filter what is returned
Returns
Concentrations at each state
References State::definition(), StateInfo::energy(), State::scp_concs(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
 {
     Vec_Pair_Concs result;
     for( size_t i = 0; i < states_size(); ++i )
     {
         SCP_Concentrations c = states_at( i ).scp_concs();
         if( c && c->vals_size() > 0 )
         {
             const StateInfo& h = states_at( i ).definition();
             // copy the filter and set data
             SP_Concentrations copy( new Concentrations( filter ) );
             copy->set_concs( *c );
             // copy now has the units and nuclide set of proto
             result.push_back( std::make_pair(
                 std::make_pair( h.time(), h.energy() ), copy ) );
         }
     }
     return result;
 }
Vec_Dbl burnups () const
Return each burnup on the StateSet.
Return the (deprecated) burnups for each State on the StateSet.
References StateSet::energies().
 {
     return energies();
 }
Vec_Dbl energies () const
Return each energy-released on the StateSet.
Return the energies for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::energy(), StateSet::states_at(), and StateSet::states_size().
Referenced by StateSet::burnups(), Obiwan_diff::diff(), and TEST().
 {
     Vec_Dbl result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         result.push_back( c.definition().energy() );
     }
     return result;
 }
Vec_Dbl times () const
Return each time on the StateSet.
Return the cycle times for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
Referenced by StateSet::create_interp_times(), Obiwan_diff::diff(), StateSet::guessNumSteps(), StateSet::interpolate_internal(), and TEST().
 {
     Vec_Dbl result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         result.push_back( c.definition().time() );
     }
     return result;
 }
Vec_Dbl powers () const
Return each power on the StateSet.
Return the sub-cycle irradiation power for each State on the StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::power(), StateSet::states_at(), and StateSet::states_size().
Referenced by Obiwan_diff::diff(), and TEST().
 {
     Vec_Dbl result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         result.push_back( c.definition().power() );
     }
     return result;
 }
Vec_Dbl fluxes () const
Return each flux on the StateSet.
Return the sub-cycle flux for each State on StateSet.
Examples:
Core/dc/tests/tstStateSet.cpp.
References State::definition(), StateInfo::flux(), StateSet::states_at(), and StateSet::states_size().
Referenced by Obiwan_diff::diff(), and TEST().
 {
     Vec_Dbl result;
     for( int i = 0; i < states_size(); ++i )
     {
         const State& c = states_at( i );
         result.push_back( c.definition().flux() );
     }
     return result;
 }
SP_StateInfo interpolate_info (float time, int case_number) const
Interpolate headers to a given time (cheap)
Examples:
Core/dc/tests/tstGridView.cpp.
References StateSet::interpolate_internal().
Referenced by TEST().
 {
     SP_State state = interpolate_internal( time, case_number, true );
     return std::make_shared<StateInfo>( state->definition() );
 }
SP_State interpolate (float time, int case_number) const
Interpolate States to a given time (expensive)
Interpolate states to a given time (expensive)
Examples:
Core/dc/tests/tstStateSet.cpp.
References StateSet::interpolate_internal().
Referenced by TEST().
 {
     SP_State state = interpolate_internal( time, case_number, false );
     return state;
 }
std::vector< size_t > matching_states (int case_number) const
Find all States matching a case number.
Returns the index(es) of all states matching the requested case number.
Parameters
case_number Case number to search on
Returns
Vector of case indexes with a case number matching the requested case number; empty vector if no matches found
References StateSet::b_states, StateInfo::case_number(), and Origen::info().
Referenced by StateSet::interpolate_internal().
 {
     std::vector<size_t> matches;
     matches.reserve( b_states->size() );
     size_t n = 0;
     for( auto& state : *b_states )
     {
         const StateInfo& info = state->definition();
         if( info.case_number() == case_number )
         {
             matches.push_back( n );
         }
         ++n;
     }
     return matches;
 }
size_t nearest_time (float time, const std::vector< size_t > & matches) const
Find State closest to the given time.
Find the State closest to the time value provided.
Parameters
time Time (in seconds) to search on
matches Index numbers of States on StateSet to check for promixity to the given time
Returns
Index of the nearest State to the given time; -1 if no indices to match on are provided (invalid input)
References StateSet::b_states, Origen::info(), and StateInfo::time().
Referenced by StateSet::interpolate_internal().
 {
     size_t nearest = 0;
     for( const auto& n : matches )
     {
         const StateInfo& info = ( *b_states )[n]->definition();
         if( std::fabs( info.time() - time ) <
             ( ( *b_states )[nearest]->definition().time() - time ) )
         {
             nearest = n;
         }
     }
     if( matches.size() == 0 ) nearest = static_cast<size_t>( -1 );
     return nearest;
 }
int guessNumSteps () const
References StateSet::times().
 {
     int n = 0;
     Vec_Dbl t = times();
     while( ( n + 1 < (int)t.size() ) && ( t[n] <= t[n + 1] ) ) n++;
     return n + 1;
 }
std::string to_string () const
References StateSet::to_json().
 { return to_json().toStyledString(); }
Json::Value to_json () const
References StateSet::b_states.
Referenced by StateSet::to_string().
 {
     Json::Value root;
     char buf[40];
     for( size_t index = 0; index < b_states->size(); ++index )
     {
         root["states"][(int)index] = ( *b_states )[index]->to_json();
         // add comments to show the start and end of the large reaction set
         // blocks
         sprintf( buf, "/* %s %d */", "begin state ", (int)index );
         root["states"][(int)index].setComment( buf, Json::commentBefore );
         sprintf( buf, "/* %s %d */", "end state ", (int)index );
         root["states"][(int)index].setComment( buf, Json::commentAfter );
     }
     return root;
 }
void canonicalize_states_at (size_t i) protected
References StateSet::r_decay_resource.
 {
     // set a Concentration's DecayResource from the StateSet's DecayResource
     if( has_decay_resource() )
     {
         auto concs = b_states->at( i )->b_concs;
         if( concs != nullptr ) concs->r_decay_resource = r_decay_resource;
     }
 }
bool check_headers () protected
Check for self-consistency of all headers on this StateSet.
Checks that all header parameters (i.e., total number of nuclides, number of light elements / actinides / fission products) are equal
Also checks for monotonicity in time / burnup values
References State::definition(), StateInfo::energy(), State::num_alpha_groups(), State::num_beta_groups(), State::num_gamma_groups(), State::num_neutron_groups(), StateSet::states_at(), StateSet::states_size(), and StateInfo::time().
 {
     if( states_size() <= 1 ) return true;
     for( size_t i = 1; i < states_size(); ++i )
     {
         const State& ci = states_at( i );
         const State& cp = states_at( i - 1 );
         if( cp.num_neutron_groups() != ci.num_neutron_groups() ) return false;
         if( cp.num_alpha_groups() != ci.num_alpha_groups() ) return false;
         if( cp.num_gamma_groups() != ci.num_gamma_groups() ) return false;
         if( cp.num_beta_groups() != ci.num_beta_groups() ) return false;
         if( cp.definition().time() >= ci.definition().time() ) return false;
         if( cp.definition().energy() >= ci.definition().energy() ) return false;
     }
     return true;
 }
SP_State interpolate_internal (float time, int case_number, bool info_only) const protected
Interpolate a StateSet to a given time & optionally generate a new interpolated State.
Parameters
info_only True: Only get the interpolated headers (don't generate an interpolated State - cheap) False: Generate a new interpolated State (expensive)
References StateSet::create_interp_times(), Origen::info(), StateSet::matching_states(), StateSet::nearest_time(), and StateSet::times().
Referenced by StateSet::interpolate(), and StateSet::interpolate_info().
 {
     // get matching states based on case number
     auto&& matches = matching_states( case_number );
     if( matches.size() == 0 ) return nullptr;
     // get times of each matching state
     auto&& times = create_interp_times( matches );
     // get nearest time (for prototype copy)
     size_t nearest = nearest_time( time, matches );
     // get interpolated header
     SP_StateInfo info;
     {
         // get list of views for those matches
         auto&& viewer_list =
             create_interp_viewers<GridView_StateInfo>( matches );
         // interpolate
         info = interpolate_view<GridView_StateInfo>(
             time, times, viewer_list, viewer_list[nearest] );
     }
     Check( info != nullptr );
     // quick return if only interested in state
     SP_State state( new State() );
     // get interpolated state
     if( !info_only )
     {
         // get list of views for those matches
         auto&& viewer_list = create_interp_viewers<GridView_State>( matches );
         // interpolate
         state = interpolate_view<GridView_State>(
             time, times, viewer_list, viewer_list[nearest] );
     }
     Check( state != nullptr );
     state->set_definition( *info );
     return state;
 }
std::vector< float > create_interp_times (const std::vector< size_t > & viewer_list) const protected
Create a set of reference times as grid points for interpolation, based on a selected set of States (matches)
References Origen::info(), StateSet::scp_states_at(), and StateSet::times().
Referenced by StateSet::interpolate_internal().
 {
     std::vector<float> times;
     for( auto& m : matches )
     {
         SCP_State state = scp_states_at( m );
         Check( state );
         SCP_StateInfo info = state->scp_definition();
         Check( info );
         times.push_back( info->time() );
     }
     return times;
 }
std::vector<T> create_interp_viewers (const std::vector< size_t > & matches) const protected
T::GD_t::Vec_Rptr create_interp_responses (const std::vector< T > & viewer_list) const protected
Create a set of interpolated responses from a viewer list.
References kernel_rksuite::f(), and r.
Referenced by StateSet::interpolate_view().
 {
     size_t nx = viewer_list.size();
     size_t nr = ( nx == 0 ) ? 0 : viewer_list[0].nr();
     typename T::GD_t::Vec_Rptr response( nr * nx );
     size_t f = 0;
     for( auto& v : viewer_list )
     {
         // get response grid
         const typename T::GD_t::Vec_Rptr& r = v.r();
         Check( v.nr() == nr );
         for( size_t j = 0; j < nr; ++j )
         {
             response[f] = r[j];
             ++f;
         }
     }
     Ensure( f == nr * nx );
     return response;
 }
View::Type::SP interpolate_view (float time, const std::vector< float > & times, const std::vector< View > & viewer_list, const View & prototype) const protected
Generate an interpolation view of the StateSet by mapping a set of States onto GridData;.
Remarks
Grid extents defined by times (interpolated on time)
References StateSet::create_interp_responses().
 {
     // get responses
     auto&& response = create_interp_responses( viewer_list );
     size_t nx = times.size();
     // Grid b_state object
     typename View::GD_t gd;
     // set x-grid (1D with times in this case)
     typename View::GD_t::Vec_I gextents( {nx} );       // one-dimension
     typename View::GD_t::Vec_Xptr grid = {&times[0]};  // one set of pointers
     gd.setx( gextents, grid );
     // set response-grid (multiple in this case)
     gd.setr( prototype.rextents(), response );
     // interpolate (linear for now)
     std::vector<float> time_wts( nx );
     interpwts_lin( times, time, &time_wts );
     typename View::GD_t::Vec_Xptr wts = {&time_wts[0]};
     typename View::GD_t::Vec_Z interp_view = gd.rgridsum( wts );
     // create new interpolated StateInfo by pushing interpolated
     // response back to newly created state info
     typename View::Type::SP interp = prototype.permute( interp_view );
     return interp;
 }
std::vector<GridView_StateInfo> create_interp_viewers (const std::vector< size_t > & matches) const inline
Create an interpolation viewer (GridView_StateInfo) of the headers from a match set of States.
This method translates StateInfo objects (headers for State) into a set of GridView extents, which can then be used for ND interpolation operations
References Origen::info(), and StateSet::scp_states_at().
 {
     std::vector<GridView_StateInfo> viewer_list;
     viewer_list.reserve( matches.size() );
     for( auto& m : matches )
     {
         SCP_State state = scp_states_at( m );
         Check( state );
         SCP_StateInfo info = state->scp_definition();
         viewer_list.emplace_back( info );
     }
     return viewer_list;
 }
std::vector<GridView_State> create_interp_viewers (const std::vector< size_t > & matches) const inline
Create an interpolation viewer from a match set of States.
This method translates State objects into a set of GridView extents, which can then be used for ND interpolation operations
Here, interpolation would be of concentrations & spectra (as responses) on a time dimension (i.e., time mapped onto extents)
References StateSet::scp_states_at().
 {
     std::vector<GridView_State> viewer_list;
     viewer_list.reserve( matches.size() );
     for( auto& m : matches )
     {
         SCP_State state = scp_states_at( m );
         Check( state );
         viewer_list.emplace_back( state );
     }
     return viewer_list;
 }
Member Data Documentation
SP_Vec_SP_State b_states protected
Referenced by StateSet::matching_states(), StateSet::nearest_time(), StateSet::operator==(), StateSet::states_back(), and StateSet::to_json().
SCP_DecayResource r_decay_resource protected
Referenced by StateSet::canonicalize_states_at().
The documentation for this class was generated from the following files:
Core/dc/StateSet.h
Core/dc/StateSet.cpp