ORIGEN API: auxiliary Module Reference
auxiliary Module Reference
Auxiliary subroutines; mostly pretty-printers for the output – it is preferred to use this module for any table printout.
Functions/Subroutines
character(3) function bool (x)
Convert a logical to a string.
subroutine table_tail ()
Print a nice footer for a table.
subroutine print_dhrule ()
Print a double (=) horizontal rule.
subroutine print_hrule ()
Print a single (-) horizontal rule.
subroutine output (s)
Print a string into a file.
subroutine print_break ()
Print a spacer in the output file.
subroutine table_banner (table_title, case_tag, case_title, case_number, max_case)
Print a header for an output table.
subroutine print_banner (title)
Print a large section banner.
subroutine flip (len, a)
Reverse order of a floating-point array.
subroutine rflip (len, a)
Reverse order of a single-precision floating-point array.
subroutine iflip (len, a)
Reverse order of an integer array.
subroutine nuclide (nuclide_id, name)
Convert six-digit nuclide identifier to alphanumeric symbol. The result will be exactly six characters long.
subroutine nuclide_compact (nuclide_id, name)
Convert six-digit nuclide identifier to alphanumeric symbol. No spaces will be in the resulting string.
subroutine print_multigroup_time_table (ngroups, nsteps, bounds, times, time_unit, high_precision, print_total, x)
subroutine print_multigroup_table (ngroups, nvars, bounds, high_precision, print_total, vars, x)
subroutine print_time_table (nsteps, nvars, times, time_unit, high_precision, print_total, vars, x)
Detailed Description
Auxiliary subroutines; mostly pretty-printers for the output – it is preferred to use this module for any table printout.
Function/Subroutine Documentation
character(3) function auxiliary::bool (logical, intent(in) x)
Convert a logical to a string.
Parameters
[in] x the boolean to be converted
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> the boolean to be converted
     logical, intent(in) :: x
     if (x) then
       bool = 'yes'
     else
       bool = ' no'
     end if
subroutine auxiliary::table_tail ()
Print a nice footer for a table.
Referenced by origen_librarywrapper_m::copyorigen_librarywrapper(), origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_gamma_class::get_spectrum(), origen_neutron_class::order_target(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     soutline(1, "(121('='))")
     soutline(1, '(a)') "."
     soutline(1, '(a)') "."
subroutine auxiliary::print_dhrule ()
Print a double (=) horizontal rule.
Referenced by origen_librarywrapper_m::copyorigen_librarywrapper().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     soutline(1, "(121('='))")
subroutine auxiliary::print_hrule ()
Print a single (-) horizontal rule.
Referenced by origen_librarywrapper_m::copyorigen_librarywrapper(), origen_beta::distea(), origen_gamma_class::get_spectrum(), origen_neutron_class::order_target(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     soutline(1, "(121('-'))")
subroutine auxiliary::output (character(len=*) s)
Print a string into a file.
Parameters
s String to be printed
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_neutron_class::order_target(), print_multigroup_table(), print_multigroup_time_table(), print_time_table(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> String to be printed
     character(len=*) :: s
     soutline(1, "(a)") trim(s)
subroutine auxiliary::print_break ()
Print a spacer in the output file.
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_gamma_class::get_spectrum(), origen_neutron_class::order_target(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     soutline(1, '(a)') "."
     soutline(1, '(a)') "."
     soutline(1, '(a)') "."
subroutine auxiliary::table_banner (character(*), intent(in) table_title, character(*), intent(in) case_tag, character(*), intent(in) case_title, integer, intent(in) case_number, integer, intent(in) max_case)
Print a header for an output table.
Parameters
[in] table_title Title of the table
[in] case_tag Title of the table
[in] case_title Title of the table
[in] case_number Number of the current (sub)case
[in] max_case Number of the current (sub)case
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_gamma_class::get_spectrum(), origen_neutron_class::order_target(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Title of the table
     character(*), intent(in) :: table_title,case_tag,case_title
     !> Number of the current (sub)case
     integer, intent(in) :: case_number,max_case
     ! the top rule
     soutline(1, "(121('='))")
     if( max_case==0 )then
         soutline(1, '("=",3x,a," (#",i0,")",t121,"=")') trim(table_title)//" for case '"//trim(case_tag)//"'",case_number
     else
         soutline(1, '("=",3x,a," (#",i0,"/",i0,")",t121,"=")') trim(table_title)//" for case '"//trim(case_tag)//"'",case_number,max_case
     end if
     if( len_trim(case_title)/=0 )then
         soutline(1, '("=",3x,a,t121,"=")')trim(case_title)
     end if
     ! the mid-rule
     soutline(1, "(121('-'))")
subroutine auxiliary::print_banner (character(*), intent(in) title)
Print a large section banner.
Parameters
[in] title Title of the table
Referenced by origen_output_class::evaluate_rates_and_balances().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> Title of the table
     character(*), intent(in) :: title
     ! the banner
     soutline(1, "(121('*'))")
     soutline(1, "(20('*'),t102,20('*'))")
     soutline(1, "(20('*'),t102,20('*'))")
     soutline(1, "(20('*'),20x,a,t102,20('*'))") trim(title)
     soutline(1, "(20('*'),t102,20('*'))")
     soutline(1, "(20('*'),t102,20('*'))")
     soutline(1, "(121('*'))")
     soutline(1, "('.')")
     soutline(1, "('.')")
subroutine auxiliary::flip (integer, intent(in) len, real(c_double), dimension(len), intent(inout) a)
Reverse order of a floating-point array.
Parameters
[in] len length of the array
[in,out] a array to be flipped
cycle variable
temporary array
Referenced by origen_beta::distea(), and origen_neutron_class::order_target().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> length of the array
     integer, intent(in) :: len
     !> array to be flipped
     real(C_DOUBLE), dimension(len), intent(inout) :: a
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> cycle variable
     integer  :: n
     !> temporary array
     real(C_DOUBLE), dimension(len) :: temp
     do n = 1,len
       temp(n) = a(len - n + 1)
     end do
     a = temp
subroutine auxiliary::rflip (integer, intent(in) len, real, dimension(len), intent(inout) a)
Reverse order of a single-precision floating-point array.
Parameters
[in] len length of the array
[in,out] a array to be flipped
cycle variable
temporary array
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> length of the array
     integer, intent(in) :: len
     !> array to be flipped
     real, dimension(len), intent(inout) :: a
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> cycle variable
     integer  :: n
     !> temporary array
     real, dimension(len) :: temp
     do n = 1,len
       temp(n) = a(len - n + 1)
     end do
     a = temp
subroutine auxiliary::iflip (integer, intent(in) len, integer, dimension(len), intent(inout) a)
Reverse order of an integer array.
Parameters
[in] len length of the array
[in,out] a array to be flipped
cycle variable
temporary array
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> length of the array
     integer, intent(in) :: len
     !> array to be flipped
     integer, dimension(len), intent(inout) :: a
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> cycle variable
     integer  :: n
     !> temporary array
     integer, dimension(len) :: temp
     do n = 1,len
       temp(n) = a(len - n + 1)
     end do
     a = temp
subroutine auxiliary::nuclide (integer, intent(in) nuclide_id, character(len=6), intent(out) name)
Convert six-digit nuclide identifier to alphanumeric symbol. The result will be exactly six characters long.
Parameters
[in] nuclide_id 6-digit integer nuclide ID
[out] name 6-character string containing the symbol
I/Z/A numbers
intermediate buffer
Examples:
tstCompManager.cpp, tstTransitionSystem_Gen.cpp, and tstTransitionSystemAdapter_AmpxN.cpp.
References const::elements, and const::sta.
Referenced by TransitionSystem::add_nuclide(), check_og_xs(), origen_librarywrapper_m::copyorigen_librarywrapper(), TransitionSystemAdapter_AmpxN::extend(), TransitionSystemAdapter_AmpxN::extend_by_mix(), FakeStdComp::FakeStdComp(), CompManager::getMolarMass(), TransitionSystem::populate_gains_impl(), Origen::populateNuclideResource_StdComp(), Origen::printTransitionSystemXs(), YieldResourceIO_stab1::read(), TransitionSystem_Gen_Setup::SetUp(), TEST(), TEST_F(), TransitionSystemAdapter_AmpxN::update(), TransitionSystemAdapter_AmpxN::update_by_mix(), and YieldResourceIO_stab1::write().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> 6-digit integer nuclide ID
     integer, intent(in) :: nuclide_id
     !> 6-character string containing the symbol
     character(len=6), intent(out) :: name
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     !> I/Z/A numbers
     integer :: i, z, a
     !> intermediate buffer
     character(8) :: buf
     ! Z-number
     z = nuclide_id / 10000
     ! A-number
     a = nuclide_id / 10 - z * 1000
     ! I-number
     i = mod(nuclide_id,10) + 1
     write (unit=buf, fmt='(A2,I3,A1)') elements(z), a, sta(i)
     name = buf(1:6)
     return
subroutine auxiliary::nuclide_compact (integer, intent(in) nuclide_id, character(7), intent(out) name)
Convert six-digit nuclide identifier to alphanumeric symbol. No spaces will be in the resulting string.
Parameters
[in] nuclide_id nuclide_id [in] 6-digit integer nuclide ID
[out] name name [out] 7-character string containing the symbol
References const::elements, and const::sta.
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_gamma_class::get_spectrum(), origen_neutron_class::order_target(), origen_output::print_table(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> nuclide_id [in] 6-digit integer nuclide ID
     integer, intent(in) :: nuclide_id
     !> name [out] 7-character string containing the symbol
     character(7), intent(out) :: name
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     integer :: i, z, a
     character(8) :: buf
     !-----------------------------------------------
     ! Z-number
     z = nuclide_id / 10000
     ! A-number
     a = nuclide_id / 10 - z * 1000
     ! I-number
     i = mod(nuclide_id,10) + 1
     if (a < 10) then
       write (unit=buf, fmt='(A2,A1,I1,A1)') elements(z), '-', a, sta(i)
     else if (a < 100) then
       write (unit=buf, fmt='(A2,A1,I2,A1)') elements(z), '-', a, sta(i)
     else
       write (unit=buf, fmt='(A2,A1,I3,A1)') elements(z), '-', a, sta(i)
     end if
     name = trim(adjustl(buf(1:7)))
     return
subroutine auxiliary::print_multigroup_time_table (integer, intent(in) ngroups, integer, intent(in) nsteps, real(c_double), dimension(0:ngroups), intent(in) bounds, real(c_double), dimension(0:nsteps), intent(in) times, character(4), intent(in) time_unit, logical, intent(in) high_precision, logical, intent(in) print_total, real(c_double), dimension(1:ngroups,0:nsteps), intent(in) x)
Parameters
[in] ngroups number of energy groups
[in] nsteps number of time steps
[in] bounds group boundaries
[in] times time values
[in] time_unit time units
[in] high_precision 4 / 6 digits
[in] print_total print total at the bottom
[in] x data
References origen_definitions_m::err, and output().
Referenced by origen_beta::distea(), origen_gamma_class::get_spectrum(), and origen_neutron_class::order_target().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> number of energy groups
     integer, intent(in) :: ngroups
     !> number of time steps
     integer, intent(in) :: nsteps
     !> group boundaries
     real(C_DOUBLE), intent(in) :: bounds(0:ngroups)
     !> time values
     real(C_DOUBLE), intent(in) :: times(0:nsteps)
     !> time units
     character(4), intent(in) :: time_unit
     !> 4 / 6 digits
     logical, intent(in) :: high_precision
     !> print total at the bottom
     logical, intent(in) :: print_total
     !> data
     real(C_DOUBLE), intent(in) :: x(1:ngroups,0:nsteps)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     ! cycle over steps
     integer :: n
     ! cycle over groups
     integer :: g
     !
     integer :: gg
     !
     integer :: k
     if (sum(x) < err) then
       call output(".")
       call output("   --- all entries are zero in this table ---")
       call output(".")
       return
     end if
     !--- print step header
     if (high_precision) then
       if ((times(0) > err .and. times(0) < 0.002) .or. (nsteps > 1 .and. times(1) < 0.002) .or. times(nsteps) > 9999999) then
         soutline(1, '(a21,4x,999(es10.3,a4))') "boundaries (MeV)",(times(n), time_unit, n=0,nsteps)
       else
         soutline(1, '(a21,4x,999(f10.3,a4))') "boundaries (MeV)", (times(n), time_unit, n=0,nsteps)
       end if
     else
       if ((times(0) > err .and. times(0) < 0.2) .or. (nsteps > 1 .and. times(1) < 0.2) .or. times(nsteps) > 999999) then
         soutline(1, '(a21,4x,999(es8.1,a4))') "boundaries (MeV)",(times(n), time_unit, n=0,nsteps)
       else
         soutline(1, '(a21,4x,999(f8.1,a4))') "boundaries (MeV)",(times(n), time_unit, n=0,nsteps)
       end if
     end if
     !--- print data
     g = 1
     k = 0
     do while (g <= ngroups)
       gg = g
       if (sum(x(g,:)) < err) then
         do while (gg < ngroups .and. sum(x(gg,:)) < err)
           gg = gg + 1
         end do
         if (sum(x(gg,:)) >= err) gg = gg - 1
       end if
       k = k + 1
       if (gg > g) then
         soutline(1, '(6x,"--- groups ",i5," through ",i5," are zero ---")') g,gg
         g = gg
       else
         sout(1, '(es10.3," -",es10.3,2x)') bounds(g-1), bounds(g)
         if (high_precision) then
           soutline(1, '(999(es14.6))') (x(g,n), n=0,nsteps)
         else
           soutline(1, '(999(es12.4))') (x(g,n), n=0,nsteps)
         end if
       end if
       g = g + 1
     end do
     if (print_total) then
       k = k + 1
       soutline(1, '(a22,2x)') '--------------------'
       k = k + 1
       sout(1, '(a22,2x)') 'total'
       if (high_precision) then
         soutline(1, '(999(es14.6))') (sum(x(:,n)), n=0,nsteps)
       else
         soutline(1, '(999(es12.4))') (sum(x(:,n)), n=0,nsteps)
       end if
     end if
subroutine auxiliary::print_multigroup_table (integer, intent(in) ngroups, integer, intent(in) nvars, real(c_double), dimension(0:ngroups), intent(in) bounds, logical, intent(in) high_precision, logical, intent(in) print_total, character(20), dimension(nvars), intent(in) vars, real(c_double), dimension(ngroups,nvars), intent(in) x)
Parameters
[in] ngroups number of energy groups
[in] nvars number of variables
[in] bounds group boundaries
[in] high_precision 4 / 6 digits
[in] print_total print total at the bottom
[in] vars variable names
[in] x data
References origen_definitions_m::err, and output().
Referenced by origen_neutron_class::order_target(), and origen_neutron::totaln().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> number of energy groups
     integer, intent(in) :: ngroups
     !> number of variables
     integer, intent(in) :: nvars
     !> group boundaries
     real(C_DOUBLE), intent(in) :: bounds(0:ngroups)
     !> 4 / 6 digits
     logical, intent(in) :: high_precision
     !> print total at the bottom
     logical, intent(in) :: print_total
     !> variable names
     character(20), intent(in) :: vars(nvars)
     !> data
     real(C_DOUBLE), intent(in) :: x(ngroups,nvars)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     ! cycle over variables
     integer :: n
     ! cycle over groups
     integer :: g, gg
     ! line counter
     integer :: k
     if (sum(x) < err) then
       call output(".")
       call output("   --- all entries are zero in this table ---")
       call output(".")
       return
     end if
     !--- print header
     soutline(1, '(a20,6x,999(2x,a11))') "boundaries (MeV)",(vars(n), n=1,nvars)
     k = 0
     !--- print data
     g = 1
     k = 0
     do while (g <= ngroups)
       gg = g
       if (sum(x(g,:)) < err) then
         do while (gg < ngroups .and. sum(x(gg,:)) < err)
           gg = gg + 1
         end do
         if (sum(x(gg,:)) >= err) gg = gg - 1
       end if
       k = k + 1
       if (gg > g) then
         soutline(1, '(6x,"--- groups ",i3," through ",i3," are zero ---")') g,gg
         g = gg
       else
         sout(1, '(e10.3," -",e10.3,2x)') bounds(g-1), bounds(g)
         if (high_precision) then
           soutline(1, '(999(es13.6))') (x(g,n), n=1,nvars)
         else
           soutline(1, '(999(2x,es11.4))') (x(g,n), n=1,nvars)
         end if
       end if
       g = g + 1
     end do
     if (print_total) then
       k = k + 1
       soutline(1, '(a22,2x)') '--------------------'
       k = k + 1
       sout(1, '(a22,2x)') 'total'
       if (high_precision) then
         soutline(1, '(999(es13.6))') (sum(x(:,n)), n=1,nvars)
       else
         soutline(1, '(999(2x,es11.4))') (sum(x(:,n)), n=1,nvars)
       end if
     end if
subroutine auxiliary::print_time_table (integer, intent(in) nsteps, integer, intent(in) nvars, real(c_double), dimension(0:nsteps), intent(in) times, character(4), intent(in) time_unit, logical, intent(in) high_precision, logical, intent(in) print_total, character(20), dimension(nvars), intent(in) vars, real(c_double), dimension(0:nsteps, 1:nvars), intent(in) x)
Parameters
[in] nsteps number of time steps
[in] nvars number of variables
[in] times time values
[in] time_unit time units
[in] high_precision 4 / 6 digits
[in] print_total print total at the bottom
[in] vars variable names
[in] x data
References origen_definitions_m::err, and output().
Referenced by origen_beta::distea(), origen_output_class::evaluate_rates_and_balances(), origen_gamma_class::get_spectrum(), and origen_neutron_class::order_target().
     !-----------------------------------------------
     !   D u m m y   A r g u m e n t s
     !-----------------------------------------------
     !> number of time steps
     integer, intent(in) :: nsteps
     !> number of variables
     integer, intent(in) :: nvars
     !> time values
     real(C_DOUBLE), intent(in) :: times(0:nsteps)
     !> time units
     character(4), intent(in) :: time_unit
     !> 4 / 6 digits
     logical, intent(in) :: high_precision
     !> print total at the bottom
     logical, intent(in) :: print_total
     !> variable names
     character(20), intent(in) :: vars(nvars)
     !> data
     real(C_DOUBLE), intent(in) :: x(0:nsteps, 1:nvars)
     !-----------------------------------------------
     !   L o c a l   V a r i a b l e s
     !-----------------------------------------------
     ! cycle over variables
     integer :: n
     ! cycle over steps
     integer :: s
     ! line counter
     integer :: k
     if (sum(x) < err) then
       call output(".")
       call output("   --- all entries are zero in this table ---")
       call output(".")
       return
     end if
     !--- print step header
     if (high_precision) then
       if ((times(0) > err .and. times(0) < 0.002) .or. (nsteps > 1 .and. times(1) < 0.002) .or. times(nsteps) > 9999999) then
         soutline(1, '(a21,1X,999(es10.3,a4))') ' ', (times(s), time_unit, s=0,nsteps)
       else
         soutline(1, '(a21,1X,999(f10.3,a4))') ' ', (times(s), time_unit, s=0,nsteps)
       end if
     else
       if ((times(0) > err .and. times(0) < 0.2) .or. (nsteps > 1 .and. times(1) < 0.2) .or. times(nsteps) > 999999) then
         soutline(1, '(a21,1X,999(es8.1,a4))') ' ', (times(s), time_unit, s=0,nsteps)
       else
         soutline(1, '(a21,1X,999(f8.1,a4))') ' ', (times(s), time_unit, s=0,nsteps)
       end if
     end if
     k = 0
     do n = 1, nvars
       if (sum(x(:,n)) > err) then
         k = k + 1
         sout(1, '(a20,1X)') vars(n)
         if (high_precision) then
           soutline(1, '(999(es14.6))') (x(s,n),s=0,nsteps)
         else
           soutline(1, '(999(es12.4))') (x(s,n),s=0,nsteps)
         end if
       end if
     end do
     if (print_total) then
       k = k + 1
       soutline(1, '(a20,1X)') '--------------------'
       k = k + 1
       sout(1, '(a20,1X)') 'total'
       if (high_precision) then
         soutline(1, '(999(1x,es13.6))') (sum(x(s,:)), s=0,nsteps)
       else
         soutline(1, '(999(1x,es11.4))') (sum(x(s,:)), s=0,nsteps)
       end if
     end if