ORIGEN API: origen_gamma_class Type Reference
origen_gamma_class Type Reference
Gamma calculations.
Public Member Functions
procedure, public init => orggam__init
Constructor.
procedure, public destroy => orggam__destroy
Destructor.
procedure, public output => orggam__output
Print the photon tables.
procedure get_spectrum => orggam__get_spectrum
Calculate photon yields and spectra for given concentrations.
Public Attributes
integer nsteps
Number of steps.
type(origen_librarywrapper), pointer lib =>NULL()
associated ORIGEN library
type(gamma_library_class), pointer glib =>NULL()
associated GAMMA library
type(origen_gamma_options) opts
options for gamma calculations
real(c_double), dimension(:,:,:), allocatable gamma_yields
non-summed n/s spectrum [ngroups * 0:nsteps * itot]
real(c_double), dimension(:,:), allocatable spectrum_n
spectrum [n/s] [ngroups * 0:nsteps]
real(c_double), dimension(:,:), allocatable spectrum_e
spectrum [MeV/s] [ngroups * 0:nsteps]
real(c_double), dimension(:), allocatable total_n
total counts including outside bin structure [n/s] [0:nsteps]
real(c_double), dimension(:), allocatable total_e
total energy including outside bin structure [MeV/s] [0:nsteps]
real(c_double), dimension(:), allocatable missing_e_nobrem
total energy for nuclides without spectra [MeV/s] [0:nsteps] but not including brem
Detailed Description
Gamma calculations.
Member Function/Subroutine Documentation
procedure, public init ()
Constructor.
procedure, public destroy ()
Destructor.
procedure, public output ()
Print the photon tables.
procedure get_spectrum ()
Calculate photon yields and spectra for given concentrations.
References auxiliary::nuclide_compact(), auxiliary::print_break(), auxiliary::print_hrule(), auxiliary::print_multigroup_time_table(), auxiliary::print_time_table(), auxiliary::table_banner(), and auxiliary::table_tail().
Member Data Documentation
integer nsteps
Number of steps.
     integer :: nsteps
type(origen_librarywrapper), pointer lib =>NULL()
associated ORIGEN library
     type(origen_librarywrapper),pointer :: lib=>null()
type(gamma_library_class), pointer glib =>NULL()
associated GAMMA library
     type(gamma_library_class),pointer :: glib=>null()
type(origen_gamma_options) opts
options for gamma calculations
     type(origen_gamma_options) :: opts
real(c_double), dimension(:,:,:), allocatable gamma_yields
non-summed n/s spectrum [ngroups * 0:nsteps * itot]
     real(C_DOUBLE), allocatable :: gamma_yields(:,:,:)
real(c_double), dimension(:,:), allocatable spectrum_n
spectrum [n/s] [ngroups * 0:nsteps]
     real(C_DOUBLE), allocatable :: spectrum_n(:,:)
real(c_double), dimension(:,:), allocatable spectrum_e
spectrum [MeV/s] [ngroups * 0:nsteps]
     real(C_DOUBLE), allocatable :: spectrum_e(:,:)
real(c_double), dimension(:), allocatable total_n
total counts including outside bin structure [n/s] [0:nsteps]
     real(C_DOUBLE), allocatable :: total_n(:)
real(c_double), dimension(:), allocatable total_e
total energy including outside bin structure [MeV/s] [0:nsteps]
     real(C_DOUBLE), allocatable :: total_e(:)
real(c_double), dimension(:), allocatable missing_e_nobrem
total energy for nuclides without spectra [MeV/s] [0:nsteps] but not including brem
     real(C_DOUBLE), allocatable :: missing_e_nobrem(:)
The documentation for this type was generated from the following file:
Manager/emit/origen_gamma.f90